pkg/dockerregistry/server/errorblobstore.go
pkg/dockerregistry/server/repositorymiddleware.go

Signed-off-by: yupeng <yu.peng36@zte.com.cn>

context.Context should be the first parameter of a function

---

images/node/Dockerfile
images/router/haproxy/Dockerfile

HAProxy doesn't build on overlay2 because of overlay2

---

pkg/auth/authenticator/token/filetoken/token.go

Signed-off-by: YuPengZTE yu.peng36@zte.com.cn

The first letter should be small in error of token.go

---

hack/build-rpm-release.sh
hack/lib/test/junit.sh
hack/test-cmd.sh
hack/test-end-to-end-docker.sh
hack/test-end-to-end.sh
test/extended/alternate_certs.sh
test/extended/alternate_launches.sh
test/extended/cmd.sh
test/extended/compatibility.sh
test/extended/conformance.sh
test/extended/core.sh
test/extended/gssapi.sh
test/extended/ldap_groups.sh
test/extended/localquota/local_fsgroup_quota.go
test/extended/networking.sh
test/extended/setup.sh

/cc @smarterclayton we need to version our CI badly....

Backport edits to tests for 1.5 CI

---

hack/build-cross.sh
hack/common.sh

Restrict gssapi flag to only host platform

---

vendor/k8s.io/kubernetes/pkg/storage/etcd/etcd_helper_test.go
vendor/k8s.io/kubernetes/pkg/storage/etcd3/store.go
vendor/k8s.io/kubernetes/pkg/storage/etcd3/store_test.go

UPSTREAM: 42622: Preserve custom etcd prefix compatibility for etcd3

---

hack/lib/util/environment.sh

Make image prefix configurable in setup_image_vars

---

pkg/cmd/admin/router/router.go

This reverts commit 5b708a582d25b103f187207b7ac93db553192c67.

Revert "Fix of BUG 1405440"

---

pkg/sdn/plugin/subnets.go

Remove a pointless cast

---

hack/lib/util/environment.sh
test/extended/router/scoped.go
test/extended/router/weighted.go
test/extended/testdata/scoped-router.yaml
test/extended/testdata/weighted-router.yaml

[test]
@stevekuznetsov this may cause some jobs to break, not sure yet.

The router images used in e2e tests should come from the build setup

---

hack/build-images.sh
hack/common.sh
hack/release.sh

Backport some 1.5 release fixes

---

origin.spec

[1.5] Remove the excluders origin-excluder

---

contrib/systemd/openshift-sdn-ovs.conf

Fixes https://github.com/openshift/origin/issues/13318

Fix race between ovsdb-server.service and node service

---

pkg/build/builder/docker_test.go
test/util/client.go

fix https://github.com/openshift/origin/issues/13367

test Base Directory should be created if not exist

---

test/extended/setup.sh

openshift binary not required for TEST_ONLY extended

---

docs/cluster_up_down.md
pkg/bootstrap/docker/openshift/cnetwork.go
pkg/bootstrap/docker/openshift/helper.go
pkg/bootstrap/docker/openshift/helper_unix.go
pkg/bootstrap/docker/openshift/helper_windows.go
pkg/bootstrap/docker/up.go
test/end-to-end/core.sh

Makes cluster less reliant on current IP address of machine.

cluster up: Use loopback interface for nodename and default server IP

---

.tito/lib/origin/common.py

Small changes for removing unnecessary variables in tito common.py
Closes #13442

Removed unnecessary variables for common.py

---

hack/lib/util/environment.sh

fixes https://github.com/openshift/origin/issues/13435
[merge]

Handle the case where no `$PATH` prefix is necessary

---

test/extended/cni_vendor_test.sh
test/extended/networking.sh
test/extended/networking/networkpolicy.go
test/extended/networking/util.go

This adds the NetworkPolicy test from #12991 but doesn't enable it yet for openshift-sdn, only for CNI plugins. Also some other tweaks and cleanups.

updates to CNI network plugin tests

---

test/extended/setup.sh

Dump container logs on `$TEST_ONLY` extended runs

---

hack/build-rpm-release.sh

enable release repo

---

Godeps/Godeps.json
vendor/github.com/fatih/structs/.gitignore
vendor/github.com/fatih/structs/.travis.yml
vendor/github.com/fatih/structs/LICENSE
vendor/github.com/fatih/structs/README.md
vendor/github.com/fatih/structs/field.go
vendor/github.com/fatih/structs/structs.go
vendor/github.com/fatih/structs/tags.go

Grab the fatih/structs dependency and vendor it to simplify changes in #13379

bump(gihtub.com/fatih/structs):v1.0

---

hack/build-rpm-release.sh

Gather all rpms for the repo creation

---

test/extended/builds/no_outputname.go
test/extended/image_ecosystem/mariadb_ephemeral.go
test/extended/image_ecosystem/mongodb_ephemeral.go
test/extended/image_ecosystem/mongodb_replica_statefulset.go
test/extended/image_ecosystem/mysql_ephemeral.go

fixes https://github.com/openshift/origin/issues/13497

make test names static

---

hack/build-rpm-release.sh

Let the name of the RPM package being built vary

---

examples/db-templates/redis-ephemeral-template.json
examples/db-templates/redis-persistent-template.json
pkg/bootstrap/bindata.go
test/extended/testdata/bindata.go

use secret refs for redis password value so it is not exposed on the console

---

tools/rebasehelpers/util/git.go

hack/verify-upstream-commits.sh: take into account pkg/build/vendor dir

---

test/extended/builds/pipeline.go
test/extended/testdata/bindata.go
test/extended/testdata/samplepipeline-withenvs.yaml

add extended test for jenkins bc with env vars

---

vendor/k8s.io/kubernetes/pkg/volume/rbd/rbd.go
vendor/k8s.io/kubernetes/pkg/volume/rbd/rbd_util.go

UPSTREAM: 37380: Improve error reporting in Ceph RBD provisioner

---

test/extended/util/framework.go

Since the build' start time.
This allows us to debug extended test failures on GCE instances.

extended tests: dump registry logs

---

pkg/build/api/types.go
pkg/build/generator/generator.go
pkg/build/generator/generator_test.go
test/extended/builds/pipeline.go
test/extended/util/jenkins/ref.go

updates, tests, for new jenkins log annotations

---

pkg/build/builder/docker_test.go
test/extended/builds/dockerfile.go

Fixes #12666 
@openshift/devex ptal?

Added tests for preventing pulling image 'scratch'

---

pkg/deploy/controller/deployment/controller.go
pkg/deploy/controller/deploymentconfig/controller.go
pkg/deploy/controller/deploymentconfig/factory.go
pkg/deploy/controller/generictrigger/controller.go
pkg/deploy/controller/generictrigger/factory.go

@mfojtik @csrwng I got the math wrong. This should be fine.
Verified the numbers with https://github.com/kubernetes/kubernetes/issues/43948

Update retries to a saner count

---

pkg/project/controller/controller.go
pkg/project/controller/controller_test.go

Cherry pick of #13563 on release-1.5.
#13563: Update namespace finalizer to delete RoleBindingRestrictions

Automated cherry pick of #13563

---

test/extended/router/metrics.go

This can potentially mask real issues with a cluster, but it's a valid
configuration to not have it enabled.

Extended tests for router metrics should skip when not configured

---

pkg/client/deploymentconfigs.go
pkg/client/testclient/fake_deploymentconfigs.go
pkg/cmd/util/clientcmd/factory_client_access.go

@kargakis I think this is a looooong overdue, but would like to have it in 1.6. PTAL.

deploy: use patch for pausing and resuming deployment config

---

examples/deployment/README.md

Update instructions to explicitly tag an image from docker repository

---

Godeps/Godeps.json
vendor/github.com/openshift/source-to-image/pkg/api/describe/describer.go
vendor/github.com/openshift/source-to-image/pkg/api/helpers.go
vendor/github.com/openshift/source-to-image/pkg/api/types.go
vendor/github.com/openshift/source-to-image/pkg/build/strategies/layered/layered.go
vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/postexecutorstep.go
vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti.go
vendor/github.com/openshift/source-to-image/pkg/build/strategies/strategies.go
vendor/github.com/openshift/source-to-image/pkg/docker/docker.go
vendor/github.com/openshift/source-to-image/pkg/docker/fake_docker.go
vendor/github.com/openshift/source-to-image/pkg/docker/util.go
vendor/github.com/openshift/source-to-image/pkg/util/status/build_status.go

bump(github.com/openshift/source-to-image): 0765440c43e9622d42cf17f452c751a416e84fc4

---

pkg/auth/client/impersonate.go
pkg/build/admission/jenkinsbootstrapper/admission.go
pkg/build/admission/secretinjector/admission.go
pkg/cmd/server/origin/master.go
pkg/cmd/server/origin/run_components.go
pkg/template/controller/templateinstance_controller.go
pkg/template/servicebroker/bind.go
pkg/template/servicebroker/deprovision.go
pkg/template/servicebroker/provision.go
pkg/template/servicebroker/servicebroker.go

I broke this out of #11647 since it was getting a bit large.  @mfojtik @soltysh can one of you take a look?
[test][testextended][extended:core(templates)]
cc @jim-minter since this touches broker stuff (should have no change in functionality).

Cleanup impersonating code

---

hack/lib/util/misc.sh
hack/test-end-to-end-docker.sh
test/end-to-end/core.sh

Reverts openshift/origin#13529
[test][merge]

Revert "Increase journald rate limiter when running test-end-to-end-docker.sh"

---

test/common/build/controllers.go

Improve diagnosis for https://github.com/openshift/origin/issues/13650.
It seems that the build watch missed an update event when the build changed from pending to running.

Build pod controller integration test - add debug

---

api/protobuf-spec/github_com_openshift_origin_pkg_build_api_v1.proto
api/swagger-spec/oapi-v1.json
api/swagger-spec/openshift-openapi-spec.json
hack/update-generated-completions.sh
pkg/build/api/types.go
pkg/build/api/v1/generated.proto
pkg/build/api/v1/swagger_doc.go
pkg/build/api/v1/types.go
pkg/openapi/zz_generated.openapi.go

Stop forcing a re-build when updating generated completions
---
Enumerated the possible build phase states in the comment
---

Enumerated the possible build phase states in the comment

---

test/extended/image_ecosystem/helper.go
test/extended/image_ecosystem/s2i_python.go

added debug for image_ecosystem tests

---

tools/testdebug/cmd/load_etcd.go

Fixes https://github.com/openshift/origin/issues/13584
@jim-minter ptal.

update load-etcd for new client

---

vendor/github.com/google/cadvisor/info/v2/conversion.go

Fixes https://github.com/openshift/origin/issues/13719

UPSTREAM: google/cadvisor: 1639: Reduce cAdvisor log spam

---

hack/update-changelog.sh

Also correct some minor issues.
[merge]

Changelog generation not handling versions correctly

---

pkg/cmd/cli/cmd/process.go
test/cmd/templates.sh

fixes https://github.com/openshift/origin/issues/12277

ignore namespace when processing templates

---

pkg/generate/app/cmd/newapp.go
pkg/generate/app/cmd/newapp_test.go
test/cmd/newapp.sh

https://bugzilla.redhat.com/show_bug.cgi?id=1436552

don't read buildenv from stdin twice

---

api/protobuf-spec/github_com_openshift_origin_pkg_build_api_v1.proto
api/swagger-spec/oapi-v1.json
api/swagger-spec/openshift-openapi-spec.json
pkg/build/api/types.go
pkg/build/api/v1/generated.proto
pkg/build/api/v1/swagger_doc.go
pkg/build/api/v1/types.go
pkg/openapi/zz_generated.openapi.go

fixes https://github.com/openshift/origin/issues/13775

explain dir copy behavior for image sourcepath

---

pkg/sdn/plugin/master.go

backport of #13765 
@openshift/networking PTAL

Fix service IP validation to handle "ClusterIP: None"

---

hack/lib/cleanup.sh

Use the correct warning log function in cleanup scripts

---

pkg/build/builder/dockerutil.go
pkg/build/registry/buildconfiginstantiate/rest.go

https://bugzilla.redhat.com/show_bug.cgi?id=1441929

use k8s helper to retrieve tls client config

---

hack/common.sh

Can remove once upstream fixes
[merge] @stevekuznetsov

Work around an OSX xcode ld error temporarily

---

pkg/build/admission/defaults/admission.go
pkg/build/admission/defaults/admission_test.go
pkg/build/api/types.go
pkg/build/controller/strategy/docker.go
pkg/build/controller/strategy/sti.go
pkg/build/controller/strategy/util.go
pkg/build/controller/strategy/util_test.go
pkg/build/util/util.go
pkg/build/util/util_test.go

https://bugzilla.redhat.com/show_bug.cgi?id=1441701

allow GIT_SSL_NO_VERIFY to be set on build pods via build defaulter

---

pkg/cmd/cli/cmd/set/triggers.go
test/cmd/triggers.sh

fixes https://github.com/openshift/origin/issues/13805

handle setting triggers on BCs with no default ICT

---

pkg/bootstrap/docker/host/host.go

Replace using of cat | grep by a single grep invocation

---

test/extended/setup.sh
test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml

Immediate follow-ups from rebase merge.

Unblock master after rebase merge

---

test/cmd/migrate.sh

Opened https://github.com/openshift/origin/issues/13924 .
It doesn't fail locally.  @sttts @soltysh

disable image-references

---

pkg/build/admission/defaults/admission.go
pkg/build/admission/defaults/admission_test.go

https://bugzilla.redhat.com/show_bug.cgi?id=1443187

apply build resource defaults directly to the build pod

---

examples/gitserver/gitserver-persistent.yaml

fixes https://github.com/openshift/origin/issues/13882

fix git server capacity to 1gi

---

test/cmd/admin.sh
test/cmd/login.sh

Wait for service account token

---

test/extended/builds/no_outputname.go
test/extended/util/framework.go

fixes https://github.com/openshift/origin/issues/13888

debug logging for WaitForABuild failures

---

docs/debugging-openshift.md
examples/sample-app/README.md
examples/wordpress/README.md

- fix/update links
- improve example by using `oc patch`
PTAL @bparees 
CC @mfojtik

Minor improvements

---

test/extended/util/framework.go

fixes https://github.com/openshift/origin/issues/13894

make build event checking tolerant of latency

---

vendor/k8s.io/kubernetes/pkg/controller/deployment/sync_test.go
vendor/k8s.io/kubernetes/pkg/controller/deployment/util/deployment_util.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1441984
**Currently blocked on https://github.com/openshift/origin/pull/13653**

UPSTREAM: 44439: controller: fix saturation check in Deployments

---

test/common/build/controllers.go

Increases the build controller test timeout to give the informer a chance to send pod update events.
fixes https://github.com/openshift/origin/issues/13650 (we hope)

Increase BuildPodControllerTest timeout

---

tools/etcdhelper/etcdhelper.go

cc @soltysh @deads2k @liggitt @sttts

Fix etcdhelper imports

---

vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go

This mirrors the changes made locally in https://github.com/openshift/origin/pull/13467 .
@jupierce ptal

Fix build-cross

---

pkg/proxy/hybrid/proxy.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1444125
@openshift/networking @knobunc @DirectXMan12 @eparis

proxy/hybrid: add locking around userspace map

---

pkg/cmd/util/clientcmd/factory_client_access.go

Compare https://github.com/openshift/origin/pull/13653#discussion_r112429796

Remove clarified todos

---

pkg/dockerregistry/server/blobdescriptorservice_test.go
pkg/dockerregistry/server/manifestservice.go
pkg/dockerregistry/server/manifestservice_test.go
pkg/dockerregistry/server/pullthroughblobstore_test.go
pkg/dockerregistry/server/pullthroughmanifestservice_test.go
pkg/dockerregistry/server/repositorymiddleware.go
pkg/dockerregistry/server/repositorymiddleware_test.go
pkg/dockerregistry/server/signaturedispatcher_test.go
pkg/dockerregistry/server/tagservice_test.go
pkg/dockerregistry/server/util.go
pkg/dockerregistry/testutil/fakeopenshift.go
pkg/dockerregistry/testutil/fakeopenshiftutil.go
pkg/dockerregistry/testutil/manifests.go
pkg/dockerregistry/testutil/util.go

[BZ 1433232](https://bugzilla.redhat.com/show_bug.cgi?id=1433232)

Use docker image reference from ImageStream 

---

pkg/cmd/cli/describe/deployments.go

Part of #13732 
@sttts @liggitt @deads2k @mfojtik @soltysh @kargakis @smarterclayton

Switch back to kapi instead of v1 for RCs in deployment describer

---

pkg/router/f5/f5.go
pkg/router/f5/plugin.go

More of an RFE - https://bugzilla.redhat.com/show_bug.cgi?id=1431655

support for reencrypt routes in the same vserver

---

pkg/cmd/cli/cmd/deploy.go

Nit-fix for https://bugzilla.redhat.com/show_bug.cgi?id=1447573

deploy: suggest to cancel dc instead of rc in oc deploy

---

pkg/cmd/cli/describe/describer.go

They're not supported any more.
Part of #13732
@deads2k @liggitt @smarterclayton @mfojtik @pweil-

Don't show policy rules with attribute restrictions

---

pkg/build/admission/defaults/api/v1/types.go

fixes https://github.com/openshift/origin/issues/14039

fix build default import to v1 api

---

hack/build-rpm-release.sh

- Add SRPM generation for CBS
- mv srpm from container location to host location
I did a scratch build in CBS based on output of src.rpm generated
https://cbs.centos.org/koji/taskinfo?taskID=178616

Add ability to provide additional rpmbuild-options to tito

---

pkg/cmd/server/kubernetes/master/master_config.go

Fixes https://github.com/openshift/origin/pull/13653#pullrequestreview-34092491.

master: zero kubelet readonly port to match node

---

pkg/cmd/server/origin/admissionconfig_test.go
pkg/cmd/server/origin/master_config.go
pkg/cmd/server/start/admission.go

Include DefaultTolerationSeconds admission plugin but off by default.

---

vendor/github.com/google/cadvisor/container/common/helpers.go
vendor/github.com/google/cadvisor/container/docker/handler.go
vendor/github.com/google/cadvisor/container/raw/handler.go
vendor/github.com/google/cadvisor/container/rkt/handler.go
vendor/github.com/google/cadvisor/fs/fs.go
vendor/github.com/google/cadvisor/info/v1/container.go
vendor/github.com/google/cadvisor/info/v1/machine.go
vendor/github.com/google/cadvisor/machine/info.go
vendor/github.com/google/cadvisor/metrics/prometheus.go

Filesystem metrics are missing

UPSTREAM: google/cadvisor: 1642 : cAdvisor fs metrics should appear in /metrics

---

Godeps/Godeps.json
vendor/github.com/gophercloud/gophercloud/FAQ.md
vendor/github.com/gophercloud/gophercloud/README.md
vendor/github.com/gophercloud/gophercloud/STYLEGUIDE.md
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v1/apiversions/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v1/apiversions/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v1/apiversions/results.go
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v1/apiversions/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/volumes/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/volumes/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/volumes/results.go
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/volumes/urls.go
vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/volumes/util.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/results.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tokens/results.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/trusts/results.go
vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go
vendor/github.com/gophercloud/gophercloud/results.go
vendor/github.com/gophercloud/gophercloud/util.go
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/BUILD
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack.go
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_test.go
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_volumes.go

fix BZ #1427701 and #1444828
@childsb @pospispa @gnufied @eparis @sttts

backport upstream Cinder fixes

---

pkg/build/controller/build_controller.go
pkg/build/controller/buildpod/buildpod_controller.go
pkg/build/controller/buildpod/buildpod_controller_test.go
pkg/build/controller/common/util.go

https://bugzilla.redhat.com/show_bug.cgi?id=1443687

ensure build start time is always set

---

vendor/k8s.io/kubernetes/federation/pkg/kubefed/init/init.go

This is a cherrypick to default the federation api server to bind to 8443 to avoid having the pod require anyuid privileges to run:
https://github.com/kubernetes/kubernetes/pull/44639

UPSTREAM: 44639: Set fed apiserver to bind to 8443 instead of 443

---

Godeps/Godeps.json
vendor/github.com/fatih/structs/.gitignore
vendor/github.com/fatih/structs/.travis.yml
vendor/github.com/fatih/structs/LICENSE
vendor/github.com/fatih/structs/README.md
vendor/github.com/fatih/structs/field.go
vendor/github.com/fatih/structs/structs.go
vendor/github.com/fatih/structs/tags.go

Was accidentally dropped by the rebase
[merge]

bump(github.com/fatih/structs):v1.0

---

pkg/cmd/server/start/start_master.go
vendor/k8s.io/kubernetes/pkg/controller/resourcequota/resource_quota_controller.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1449568

Fix quota sync

---

pkg/bootstrap/docker/dockerhelper/helper.go

dockerhelper.Helper.DockerRoot(): don't swallow an error

---

pkg/quota/controller/clusterquotamapping/clusterquotamapping.go

switch to the normal "wait for cache sync" function.
Fixes https://github.com/openshift/origin/issues/14170

switch clusterquotamapping to use the normal cache wait

---

pkg/cmd/server/origin/master.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/wrap.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go

Fixes https://github.com/openshift/origin/issues/13438

only log stacks on server errors

---

vendor/k8s.io/kubernetes/pkg/registry/core/pod/strategy.go
vendor/k8s.io/kubernetes/plugin/pkg/admission/gc/gc_admission.go
vendor/k8s.io/kubernetes/plugin/pkg/admission/gc/gc_admission_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1450461

Fix kubelet status updates

---

vendor/k8s.io/kubernetes/pkg/registry/core/pod/strategy.go
vendor/k8s.io/kubernetes/plugin/pkg/admission/gc/gc_admission.go
vendor/k8s.io/kubernetes/plugin/pkg/admission/gc/gc_admission_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1450461

Fix kubelet status stage

---

test/extended/deployments/deployments.go

Saw this:
```
• Failure [240.232 seconds]
deploymentconfigs
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:959
with revision history limits [Conformance]
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:867
should never persist more old deployments than acceptable after being observed by the controller [It]
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/deployments.go:866
Expected
<int>: 4
to be ==
<int>: 3
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/deployments/depl …
```

Make revisionHistoryLimit test more resistant to failures

---

vendor/k8s.io/kubernetes/pkg/controller/node/timed_workers_test.go

This flakes the queue every so often.
cc @smarterclayton @liggitt 
[merge]

UPSTREAM: 45413: Extend timeouts in timed_workers_test

---

vendor/k8s.io/kubernetes/pkg/util/iptables/iptables.go
vendor/k8s.io/kubernetes/pkg/util/iptables/iptables_linux.go
vendor/k8s.io/kubernetes/pkg/util/iptables/iptables_test.go
vendor/k8s.io/kubernetes/pkg/util/iptables/iptables_unsupported.go

@eparis @openshift/networking @knobunc

UPSTREAM: backport a couple iptables-restore locking PRs

---

test/integration/build_admission_test.go

fixes https://github.com/openshift/origin/issues/14236

wait for builder service accounts before running build tests

---

hack/lib/util/environment.sh
test/extended/router/scoped.go
test/extended/router/weighted.go
test/integration/router_test.go

Use OS_IMAGE_PREFIX over router-specific test env

---

vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/attach_detach_controller.go
vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/attach_detach_controller_test.go
vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/cache/desired_state_of_world.go
vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/cache/desired_state_of_world_test.go
vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/populator/desired_state_of_world_populator.go
vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/populator/desired_state_of_world_populator_test.go
vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/reconciler/reconciler_test.go
vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/util/util.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go
vendor/k8s.io/kubernetes/pkg/volume/util/volumehelper/volumehelper.go
vendor/k8s.io/kubernetes/test/integration/volume/attach_detach_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1446788

UPSTREAM: 45286: When pods are terminated we should detach the volume

---

pkg/client/cache/template.go
pkg/cmd/server/api/types.go
pkg/cmd/server/api/v1/swagger_doc.go
pkg/cmd/server/api/v1/types.go
pkg/cmd/server/api/v1/types_test.go
pkg/cmd/server/origin/master.go
pkg/cmd/server/start/start_master.go
pkg/template/servicebroker/catalog.go
pkg/template/servicebroker/provision.go
pkg/template/servicebroker/servicebroker.go
test/extended/setup.sh
test/extended/templates/templateservicebroker_e2e.go
test/integration/etcd_storage_path_test.go

https://trello.com/c/2FY9BDpS/1204-5-template-broker-configuration-template-broker
@openshift/api-review, please can you ok the master config changes?
@openshift/devex

Make template service broker namespace(s) configurable

---

pkg/cmd/cli/describe/describer.go

Fixes https://github.com/openshift/origin/issues/14058 (template describer)
Avoid the universal decoder (use only `UnstructuredJSONScheme`) when decoding the list of template objects to bypass validation in fields like "quantity". Read `Kind` from the unstructured content.
PTAL @juanvallejo @deads2k @ncdc

Fixes template objects describer

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go

UPSTREAM: 45940: apiserver: no Status in body for http 204

---

test/extended/networking/util.go

Service tests are currently flaking because apparently the endpoints controller believes that there are no pods (even un-ready ones) backing the service sometimes:
May 12 20:32:13 nettest-master openshift[137]: I0512 20:32:13.660931     137 endpoints_controller.go:445] Update endpoints for e2e-tests-net-services1-jnk1d/service-8nc7r, ready: 0 not ready: 0
The code in the test updates the pod without retrying-on-failure; something must have changed elsewhere recently that causes some other part of the code to update new pods immediately after creation (or at least changed the timing of an existing potential conflict that we were reliably avoiding).
Fixes #14197 
(hopefully)
@openshift/networking @smarterclayton @stevekuznetsov

Fix extended networking service tests to retry updates on conflict

---

test/extended/testdata/bindata.go
test/extended/testdata/jenkins-plugin/create-job.xml
test/extended/testdata/jenkins-plugin/delete-job.xml

delete refs to https://github/gabemontero

---

pkg/router/f5/f5.go

@knobunc This needs to go in asap in current. No backports needed.
@lihongan Please review
Thanks.

syntax fix in irule TCL code

---

pkg/cmd/server/start/start_master.go
vendor/k8s.io/kubernetes/pkg/controller/resourcequota/resource_quota_controller.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1449568

Fix quota sync stage

---

vendor/k8s.io/kubernetes/pkg/controller/namespace/deletion/BUILD
vendor/k8s.io/kubernetes/pkg/controller/namespace/deletion/namespaced_resources_deleter.go

UPSTREAM: 46037: NS controller: don't stop deleting GVRs on error

---

hack/lib/cleanup.sh

[test][merge]
this was a copy-pasta error

Correctly remove containers and volumes on cleanup

---

vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go
vendor/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller.go

Improves namespace deletion speed slightly.  Already merged upstream.
[merge]

UPSTREAM: 45304: increase the QPS for namespace controller

---

vendor/k8s.io/kubernetes/pkg/kubelet/container/container_reference_manager.go
vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go
vendor/k8s.io/kubernetes/pkg/kubelet/prober/prober.go
vendor/k8s.io/kubernetes/pkg/kubelet/rkt/rkt.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1452442

UPSTREAM: 46246: Fix kubelet event recording

---

examples/prometheus/prometheus.yaml

simple fix to the IMAGE_PROMETHEUS parameter description

fix IMAGE_PROMETHEUS parameter description

---

pkg/image/registry/imagestreamimport/rest.go

Use the helper to populate all fields of a user into the subject access review

Populate user in subject access review correctly

---

pkg/image/importer/importer.go

[BZ 1442855](https://bugzilla.redhat.com/show_bug.cgi?id=1442855)

Set layer size whether it found in cache or not

---

vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go
vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container_test.go

xref https://bugzilla.redhat.com/show_bug.cgi?id=1454674
https://github.com/kubernetes/kubernetes/pull/45977

UPSTREAM: 45977: kuberuntime: report StartedAt regardless of container states

---

vendor/k8s.io/kubernetes/pkg/kubelet/pleg/generic.go

xref https://github.com/kubernetes/kubernetes/pull/45496

UPSTREAM: 45496: fix pleg relist time

---

vendor/k8s.io/kubernetes/pkg/api/v1/pod/util.go
vendor/k8s.io/kubernetes/pkg/api/v1/pod/util_test.go

xref https://bugzilla.redhat.com/show_bug.cgi?id=1453180
https://github.com/kubernetes/kubernetes/pull/46305
@derekwaynecarr @smarterclayton

UPSTREAM: 46305: clear init container status annotations when cleared in status

---

vendor/k8s.io/kubernetes/pkg/kubelet/prober/worker.go
vendor/k8s.io/kubernetes/pkg/kubelet/prober/worker_test.go

xref https://bugzilla.redhat.com/show_bug.cgi?id=1455056
https://github.com/kubernetes/kubernetes/pull/46371

UPSTREAM: 46371: reset resultRun on pod restart

---

test/integration/imagechange_buildtrigger_test.go

Add debugging for build change test

---

pkg/cmd/server/origin/master_config.go
pkg/quota/admission/resourcequota/admission_test.go
pkg/quota/image/registry.go
pkg/quota/registry.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1454550

Bug 1454550 - Do not double count the image* quota resources

---

pkg/diagnostics/client/run_diagnostics_pod.go

Hopefully fixes https://github.com/openshift/origin/issues/14259

DiagnosticPod: double timeout for pod start

---

pkg/serviceaccounts/controllers/deleted_dockercfg_secrets_test.go

fixes #14386 flake
[merge][severity:blocker]

Wait for controller startup in test

---

pkg/service/controller/ingressip/service_ingressip_controller_test.go

[test][severity:blocker]
Flake in unit tests

Fix service ingress ip controller test flake

---

pkg/cmd/util/pluginconfig/config.go
pkg/cmd/util/pluginconfig/config_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1452092

admission config: fix decoding error for legacy config without Kind

---

vendor/k8s.io/kubernetes/pkg/api/validation/validation.go
vendor/k8s.io/kubernetes/pkg/api/validation/validation_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1456156
xref:
https://github.com/kubernetes/kubernetes/pull/46640
https://github.com/kubernetes/kubernetes/pull/46711

UPSTREAM: 46640: Improve validation of active deadline seconds

---

vendor/k8s.io/kubernetes/pkg/volume/azure_dd/attacher.go
vendor/k8s.io/kubernetes/pkg/volume/azure_dd/vhd_util.go
vendor/k8s.io/kubernetes/pkg/volume/azure_dd/vhd_util_test.go

UPSTREAM: 44295: Azure disk: dealing with missing disk probe

---

pkg/cmd/server/bootstrappolicy/policy.go
test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1449608

Allow basic users to 'get' StorageClasses

---

vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go

This commit also picked pv annotation set for `auto_unmount` mount option
from upstream commit #45995.

UPSTREAM: 46614: Add `auto_unmount` mount option for glusterfs fuse mount

---

images/node/Dockerfile
images/node/Dockerfile.centos7
images/node/scripts/docker
images/openvswitch/Dockerfile
origin.spec

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1455472
Related https://github.com/openshift/origin/pull/14350

Move docker specific scripts back into image directories

---

vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi.go
vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go
vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util_test.go

@mtanino @humblec  @childsb @eparis

UPSTREAM: 46239: Log out from multiple target portals when using iscsi plugin

---

pkg/cmd/server/api/validation/master.go

pkg/cmd/server/api/validation/master.go: fix typo in warning message

---

pkg/auth/oauth/external/openid/openid.go
pkg/auth/oauth/external/openid/openid_test.go

Cherry pick of https://github.com/openshift/origin/pull/14420

Use base64url to decode id_token

---

Godeps/Godeps.json

zero diff bump (just find and replace) to the commit from here: https://github.com/openshift/kubernetes/commits/openshift-1.6-20170501
@liggitt this one will need a green button to ensure it's in the right spot

bump(k8s.io/kubernetes): 010d313ca749b4005269f1cd1b9cd17168635490

---

pkg/cmd/admin/migrate/images/imagerefs.go
pkg/cmd/admin/migrate/migrator.go
pkg/cmd/admin/migrate/storage/storage.go

Remove duplicate migrate code

---

hack/push-release.sh

@stevekuznetsov  @derekwaynecarr @eparis @jpeeler

Push origin-cluster-capacity image to docker hub.

---

hack/build-local-images.sh

fixes https://github.com/openshift/origin/issues/14309

script for building local images

---

pkg/template/api/validation/validation.go
pkg/template/api/validation/validation_test.go

make templateinstance immutability message less unfriendly

---

hack/build-rpm-release.sh

When running 'make release' as root with the source mounted in via NFS and
root_squash set (e.g., when using Vagrant), mv will move normal files correctly
(but complaining about not being able to set the uid/gid), but it will fail to
move symlinks (same complaint, then exit(1)).
Unhappily for us, _output contains a symlink, hence this workaround.

use cp; rm instead of mv to transfer the tito output to _output

---

pkg/cmd/cli/cmd/logs.go

@bparees @stevekuznetsov per IRC yesterday

soften pipeline log missing annotation msg

---

hack/build-local-images.py

There was a missing : that was breaking the script.  This corrects it.

Add a missing : to if line

---

hack/build-local-images.py

Changed the code so that if the source is a directory, the tree will be copied to the target.
Added support for building haproxy-router images.
Changed from copyfile() to copy() so mode bits are preserved.

Copy directory trees, and add support for haproxy images

---

hack/build-local-images.py

An explanatory comment about how the script operates as well as
available arguments and environment variables should clear up the
usage and possibilities for this script. The script now also detects
when the user has requested an image that the script does not know
how to build.
/cc @bparees @jwforres

Improve the UX of the local image build script

---

pkg/sdn/plugin/networkpolicy.go

With NetworkPolicy v1, there is no longer a "DefaultDeny" annotation, and instead, pods are isolated if and only if there is a NetworkPolicy selecting them. This updates for that.
First, when parsing NetworkPolicies, we note which pod IPs they select. Then when updating OVS, we output the "accept" flows for all the policies at `priority=150`, while also checking if any policy selects the entire Namespace. If there *is not* a policy that selects the entire Namespace, then that means there are potentially un-isolated pods that are default-accept rather than default-deny, so we also output a `priority=100, actions=drop` flow for each IP mentioned in any of the "accept" flows, and a `priority=50` flow accepting all other traffic in the namespace. (If there *is* a policy that selects the …

Update NetworkPolicy code for v1 semantics

---

test/integration/gc_default_test.go

Fixes https://github.com/openshift/origin/issues/14353
@sttts @liggitt @mfojtik @ironcladlou  I'm open to better suggestions.  I described the issue in the code.  Longer term, perhaps we have an LRU of orphanings?

deflake orphaning GC

---

hack/build-local-images.py

Tag local images with full name, not nick-names

---

vendor/k8s.io/kubernetes/pkg/api/register.go
vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/metaonly/metaonly.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/register.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/scheme.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/scheme_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/pkg/api/register.go
vendor/k8s.io/kubernetes/test/integration/master/master_test.go

UPSTREAM: 46112: apimachinery: move unversioned registration to metav1

---

pkg/cmd/server/kubernetes/master/master_config.go
pkg/util/restoptions/configgetter.go

Ensures that controllers like GC won't delete resources incorrectly.
[test]

Make the default quorum reads

---

Godeps/Godeps.json

origin bump matching https://github.com/openshift/kubernetes/commits/openshift-1.6-20170501
@liggitt needs to be forced

bump(k8s.io/kubernetes): 2d104177c1bb3d16a21244b899f649016d63d684

---

vendor/k8s.io/kubernetes/pkg/volume/empty_dir/empty_dir.go
vendor/k8s.io/kubernetes/pkg/volume/volume.go

for BZ https://bugzilla.redhat.com/show_bug.cgi?id=1460280
@eparis @childsb

UPSTREAM: 43878: Delete EmptyDir volume directly instead of renaming the directory

---

hack/lib/cleanup.sh

Fix permissions on event harvest

---

vendor/k8s.io/kubernetes/pkg/kubelet/cm/helpers_linux.go

xref https://bugzilla.redhat.com/show_bug.cgi?id=1459826
https://github.com/kubernetes/kubernetes/pull/44898

UPSTREAM: 44898: while calculating pod's cpu limits, need to count in init-container

---

examples/prometheus/README.md
examples/prometheus/prometheus.yaml
pkg/bootstrap/bindata.go

Fix a broken CLI flag on the prometheus example and start recording actual useful queries.
[merge]

Add prometheus query examples

---

Godeps/Godeps.json

update to latest openshift/kubernetes

bump(k8s.io/kubernetes): 3a5b73339d2adbb002a9820e125a5529f3a749fd

---

hack/build-local-images.py

Add in the rules needed to build keepalived-ipfailover.

Add keepalived-ipfailover image support

---

pkg/build/util/util.go

https://bugzilla.redhat.com/show_bug.cgi?id=1458200
bug 1458200

handle nil URLs in safeforlogging

---

vendor/k8s.io/kubernetes/pkg/volume/util/util.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1459461
@rootfs @gnufied for review
@childsb @eparis for merge
(we really miss CI for storage...)

UPSTREAM: 43982: Fix deletion of Gluster, Ceph and Quobyte volumes

---

cmd/cluster-capacity/go/src/github.com/kubernetes-incubator/cluster-capacity/pkg/api/api.go
cmd/cluster-capacity/go/src/github.com/kubernetes-incubator/cluster-capacity/pkg/framework/restclient/external/restclient.go
cmd/cluster-capacity/go/src/github.com/kubernetes-incubator/cluster-capacity/pkg/framework/restclient/external/restclient_test.go
cmd/cluster-capacity/go/src/github.com/kubernetes-incubator/cluster-capacity/pkg/framework/restclient/external/watch_test.go
cmd/cluster-capacity/go/src/github.com/kubernetes-incubator/cluster-capacity/pkg/framework/simulator.go
cmd/cluster-capacity/go/src/github.com/kubernetes-incubator/cluster-capacity/pkg/framework/simulator_test.go
cmd/cluster-capacity/go/src/github.com/kubernetes-incubator/cluster-capacity/pkg/framework/store/fake.go
cmd/cluster-capacity/go/src/github.com/kubernetes-incubator/cluster-capacity/pkg/framework/store/store.go
cmd/cluster-capacity/go/src/github.com/kubernetes-incubator/cluster-capacity/pkg/framework/watch/watch.go

UPSTREAM: kubernetes-incubator/cluster-capacity: 78: Remove resources that are not needed to run cluster  capacity analysis.

---

hack/test-go.sh
vendor/k8s.io/kubernetes/pkg/api/v1/pod/util_test.go

Fixes https://github.com/openshift/origin/issues/14341

Run k8s API unit tests

---

pkg/cmd/server/bootstrappolicy/controller_policy.go
pkg/template/servicebroker/catalog.go
pkg/template/servicebroker/test-scripts/provision.sh
test/extended/templates/templateinstance_security.go
test/integration/authorization_test.go
test/testdata/bootstrappolicy/bootstrap_cluster_role_bindings.yaml

give template instance controller admin permissions

---

vendor/github.com/gophercloud/gophercloud/pagination/http.go

Fix BZ https://bugzilla.redhat.com/show_bug.cgi?id=1461374
@eparis @childsb

UPSTREAM: 383: support HTTP Multiple Choices in pagination

---

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_test.go

Fixes - https://bugzilla.redhat.com/show_bug.cgi?id=1461865
cc @derekwaynecarr @eparis

UPSTREAM: 47516: Fix getInstancesByNodeNames for AWS

---

pkg/cmd/server/kubernetes/master/master_config.go

GC controller tries to start it twice
Part of #8229

Autoscaler should GC via autoscaling v1

---

pkg/bootstrap/docker/openshift/ansible.go
pkg/bootstrap/docker/openshift/helper.go
pkg/bootstrap/docker/openshift/logging.go
pkg/bootstrap/docker/openshift/metrics.go
pkg/bootstrap/docker/run/run.go
pkg/bootstrap/docker/up.go

This PR modifies 'oc cluster up' to use openshift-ansible to install logging and metrics
Blocked on:
* https://github.com/openshift/openshift-ansible/pull/4279
* openshift-ansible images being tagged consistently like others 'origin-openshift-ansible'

Use openshift-ansible for logging and metrics in 'oc cluster up'

---

pkg/cmd/admin/policy/reconcile_sccs.go

Preserve original error during SCC Reconcile

---

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_blob.go

Fix BZ https://bugzilla.redhat.com/show_bug.cgi?id=1462551
@eparis @childsb

UPSTREAM: 47605: Change Container permissions to Private for provisioned Azure Volumes

---

origin.spec

Make clients require bash-completion

---

pkg/generate/app/cmd/newapp.go
pkg/generate/app/sourcelookup.go

fixes https://github.com/openshift/origin/issues/14418

retry ls-remote in new-app

---

examples/prometheus/prometheus.yaml

Fixes: https://github.com/openshift/origin/issues/14666

make prometheus example work on older servers

---

pkg/bootstrap/bindata.go

update bindata for prometheus

---

examples/prometheus/prometheus.yaml
pkg/bootstrap/bindata.go

This reverts commit b14017547388eca65aa9bcbf858db7b9b8315918.
Reverts #14768, this was intentional.

Revert "make prometheus example work on older servers"

---

pkg/cmd/cli/cmd/process.go

fixes https://github.com/openshift/origin/issues/14755

improve error message when processing non-template resources

---

pkg/bootstrap/docker/openshift/helper.go
pkg/bootstrap/docker/up.go

fixes https://github.com/openshift/origin/issues/14762

enforce server version requirement for service catalog

---

Godeps/Godeps.json

godep reference bump from https://github.com/openshift/kubernetes/commits/openshift-1.6-20170501

bump(k8s.io/kubernetes): e14cf3cef86ecaf0ec2a2b685a8113c0b258eacb

---

hack/lib/log/system.sh

[test]
[merge][severity: lowrisk]
/cc @enj

Handle system logging cleanup when no logfile exists

---

examples/jenkins/pipeline/maven-pipeline.yaml
pkg/bootstrap/bindata.go
test/extended/builds/pipeline.go
test/extended/testdata/bindata.go
test/extended/util/framework.go
test/extended/util/jenkins/monitor.go

Fixes https://github.com/openshift/origin/issues/13984
@bparees ptal

fix for tls handshake timeout flakes with jenkins pipelines

---

pkg/bootstrap/docker/openshift/helper.go
pkg/bootstrap/docker/openshift/logging.go
pkg/bootstrap/docker/openshift/servicecatalog.go
pkg/bootstrap/docker/up.go

fixes https://github.com/openshift/origin/issues/14827

move SC and logging templates to a system namespace

---

test/extended/router/metrics.go

Router metrics tests should use the configured port

---

vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go

https://github.com/kubernetes/kubernetes/pull/47823
xref https://bugzilla.redhat.com/show_bug.cgi?id=1449820
@derekwaynecarr @eparis

UPSTREAM: 47823: don't pass CRI error through to waiting state reason

---

images/node/system-container/config.json.template
images/node/system-container/tmpfiles.template
images/openvswitch/system-container/service.template

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1463574

System container, node: add missing mount points

---

test/extended/builds/pipeline.go
test/extended/testdata/bindata.go
test/extended/testdata/config-map-jenkins-slave-pods.yaml
test/extended/testdata/imagestream-jenkins-slave-pods.yaml
test/extended/testdata/imagestreamtag-jenkins-slave-pods.yaml
test/extended/testdata/jenkins-slave-template.yaml

add ext tests for cfgmap/is -> jenkins slave pod template

---

examples/jenkins/pipeline/bluegreen-pipeline.yaml
examples/jenkins/pipeline/mapsapp-pipeline.yaml
examples/jenkins/pipeline/maven-pipeline.yaml
examples/jenkins/pipeline/samplepipeline.yaml
examples/quickstarts/cakephp-mysql-persistent.json
examples/quickstarts/cakephp-mysql.json
examples/quickstarts/dancer-mysql-persistent.json
examples/quickstarts/dancer-mysql.json
examples/quickstarts/django-postgresql-persistent.json
examples/quickstarts/django-postgresql.json
examples/quickstarts/httpd.json
examples/quickstarts/nodejs-mongodb-persistent.json
examples/quickstarts/nodejs-mongodb.json
examples/quickstarts/rails-postgresql-persistent.json
examples/quickstarts/rails-postgresql.json
examples/wordpress/template/wordpress-mysql.json
pkg/bootstrap/bindata.go
test/extended/testdata/bindata.go

https://bugzilla.redhat.com/show_bug.cgi?id=1365656
@bparees ptal

Updating GITHUB_WEBHOOK_SECRET description

---

pkg/image/trigger/deploymentconfigs/deploymentconfigs.go
pkg/image/trigger/deploymentconfigs/deploymentconfigs_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1462131
Also related to https://github.com/openshift/origin/issues/14725#issuecomment-309746020
cc: @mfojtik @smarterclayton

Fix chained DC IST trigger

---

Godeps/Godeps.json

https://github.com/openshift/kubernetes/commits/openshift-1.6-20170501
@liggitt

bump(k8s.io/kubernetes): 314edd5dc58f36ee1238dd2127a61feae14b9a4a

---

hack/godep-save.sh
hack/lib/util/misc.sh
hack/verify-govet.sh

@derekwaynecarr @eparis @stevekuznetsov @jpeeler 
Fix https://github.com/openshift/origin/issues/14751

Fix godep-save by ignoring cmd/cluster-capacity and cmd/service-catalog dirs.

---

pkg/deploy/apis/apps/types.go
pkg/deploy/apis/apps/v1/types.go

Fixes https://github.com/openshift/origin/issues/14855
@mfojtik @jim-minter 

Update documentation for DC conditions

---

cmd/cluster-capacity/go/src/github.com/kubernetes-incubator/cluster-capacity/pkg/framework/simulator.go

Fix https://bugzilla.redhat.com/show_bug.cgi?id=1449891
@derekwaynecarr @sjenning  @eparis @chengzhang1016

UPSTREAM: kubernetes-incubator/cluster-capacity: 81: Fix cluster-capacity to avoid pending pods not created by it.

---

images/ipfailover/keepalived/lib/utils.sh
images/ipfailover/keepalived/tests/verify_failover_image.sh

- Added IPv6 Address support
- Added IPv6 Address Range Support
- Added IPv6 Address Validation
- Added IPv4 Address Validation
- Added relevant test cases

Added IPv6 support for the ipfailover keepalived image. (bz1459960)

---

pkg/cmd/server/origin/master_config.go
test/integration/buildcontroller_test.go

remove unused privileged clients from master config

---

test/extended/builds/new_app.go
test/extended/deployments/util.go

hunting down the cause of https://github.com/openshift/origin/issues/14043
[test]

extended: add deployment config failure trap to new-app

---

test/extended/builds/pipeline.go

@openshift/devex fyi
stems from some recent results with jenkins-client plugin PR testing

more env, server side debug for pipeline ext tests

---

test/extended/util/framework.go

Adding additional debugging information to diagnose a
failure running WaitForOpenShiftNamespaceImageStreams

Additional debugging for WaitForOpenShiftNamespaceImageStreams

---

pkg/deploy/controller/deployer/deployer_controller.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1465801
changes
1. emit an event if you cannot create a deployer pod right away to improve ux
2. cleanup the event text when doing failed retry to remove the deployment.name because events are already about that deployment inherently.

Deployer controller emits event when failed to create deploy pod

---

pkg/router/f5/f5.go

Fix for bz: https://bugzilla.redhat.com/show_bug.cgi?id=1465304
@lihongan Review please. Thanks.
/cc @openshift/networking

fix for bz1465304 - use regular escaping of the resource

---

.gitignore
hack/lib/build/binaries.sh
hack/lib/build/version.sh

Ref. https://trello.com/c/Cn8IaH8g/209-properly-sign-and-package-oc-binary-for-windows
Supersedes https://github.com/openshift/origin/pull/14862 addressing review comments.

Windows compile time info

---

.gitignore
hack/lib/build/binaries.sh
hack/lib/build/version.sh

Reverts openshift/origin#14967

Revert "Windows compile time info"

---

Godeps/Godeps.json
vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/apply_raw.go
vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go
vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_unix.go
vendor/github.com/opencontainers/runc/libcontainer/console_linux.go
vendor/github.com/opencontainers/runc/libcontainer/console_windows.go
vendor/github.com/opencontainers/runc/libcontainer/container.go
vendor/github.com/opencontainers/runc/libcontainer/label/label.go
vendor/github.com/opencontainers/runc/libcontainer/label/label_selinux.go
vendor/github.com/opencontainers/runc/libcontainer/label/label_selinux_test.go
vendor/github.com/opencontainers/runc/libcontainer/process_linux.go
vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
vendor/github.com/opencontainers/runc/libcontainer/selinux/selinux.go
vendor/github.com/opencontainers/runc/libcontainer/standard_init_linux.go
vendor/github.com/opencontainers/runc/libcontainer/utils/utils.go

https://github.com/kubernetes/kubernetes/pull/44940
xref https://bugzilla.redhat.com/show_bug.cgi?id=1466636
fixes bug 1466636
@derekwaynecarr @eparis

UPSTREAM: 44940: Bump runc to d223e2a

---

pkg/cmd/cli/cmd/set/triggers.go

set triggers is fetching resources twice

---

Godeps/Godeps.json
vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/postexecutorstep.go
vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti.go
vendor/github.com/openshift/source-to-image/pkg/ignore/ignore.go
vendor/github.com/openshift/source-to-image/pkg/tar/tar.go

bump(github.com/openshift/source-to-image): b4097ed9cdefeb304d684c5ff34a764a45244c7c

---

pkg/cmd/cli/describe/projectstatus.go

Fixes: https://github.com/openshift/origin/issues/15008
[test]

cli: recognize persistent volume claim in status

---

hack/lib/start.sh

Adds audit logging to help debug https://github.com/openshift/origin/issues/14990

add audit logging to apiserver starts

---

pkg/util/ovs/ovs.go
pkg/util/ovs/ovs_test.go

So we can figure out what the actual error is.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1467387
@openshift/networking @knobunc

sdn: add better logging of ofport request failure

---

Godeps/Godeps.json

based on https://github.com/openshift/kubernetes/commits/openshift-1.6-20170501

bump(k8s.io/kubernetes): fff65cf41bdeeaff9964af98450b254f3f2da553

---

test/extended/util/test.go

Add disabled DNS test back into conformance

---

pkg/cmd/server/kubernetes/node/node.go

[merge][severity:bug]
Will prevent future annoyance

When CRI runtime is not docker, don't init docker socket

---

images/release/golang-1.7/Dockerfile
images/release/golang-1.8/Dockerfile

Will allow us to perform static builds of some components
[merge]

Add static library to release image

---

HACKING.md

We doc the format of the cherry-pick comments, but I found the documentation about the PR case lacking.  I have filled out the docs a little.

Clarify what needs to be said in cherry-pick commit comments

---

test/extended/builds/pipeline.go

dump jenkins logs on env var ext test mismatch

---

docs/openshift_networking_requirements.md

Just a url update.
@pravisankar Can you mark merge?

update upstream kubernetes link for cni

---

vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go

xref: https://github.com/kubernetes/kubernetes/pull/48085
xref: https://github.com/kubernetes/kubernetes/pull/48624

UPSTREAM: 48085: Move iptables logging in kubeproxy

---

pkg/authorization/controller/authorizationsync/origin_to_rbac_clusterrole_controller.go
pkg/authorization/controller/authorizationsync/origin_to_rbac_clusterrolebinding_controller.go
pkg/authorization/controller/authorizationsync/origin_to_rbac_role_controller.go
pkg/authorization/controller/authorizationsync/origin_to_rbac_rolebinding_controller.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1468629

Tolerate NotFound on delete, remove roles on policybinding deletion

---

test/extended/builds/pipeline.go
test/extended/image_ecosystem/jenkins_plugin.go
test/extended/util/jenkins/ref.go

add PR testing hook for openshift-login plugin

---

test/extended/templates/templateinstance_impersonation.go

fix templateinstance update test logic

---

pkg/generate/app/app.go
pkg/generate/app/app_test.go
pkg/generate/app/cmd/newapp.go
pkg/generate/app/pipeline.go
pkg/generate/appjson/appjson.go

fixes https://github.com/openshift/origin/issues/15224

don't add ICT for source images if build is binary

---

pkg/build/apis/build/types.go
pkg/build/apis/build/validation/validation.go
pkg/build/controller/build/build_controller.go
pkg/build/controller/build/build_controller_test.go
pkg/build/controller/build/buildupdate.go
pkg/build/generator/generator.go
pkg/build/generator/generator_test.go
pkg/build/util/util.go
pkg/cmd/server/bootstrappolicy/controller_policy.go
test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml

https://bugzilla.redhat.com/show_bug.cgi?id=1443163
bug 1443163

resolve image push secret in controller, not instantiate

---

vendor/k8s.io/kubernetes/plugin/pkg/admission/podpreset/admission.go
vendor/k8s.io/kubernetes/plugin/pkg/admission/podpreset/admission_test.go

upstream pick for https://bugzilla.redhat.com/show_bug.cgi?id=1471725
bug 1471725

UPSTREAM: 49120: Modify podpreset lister to use correct namespace

---

vendor/k8s.io/kubernetes/pkg/quota/evaluator/core/configmap.go
vendor/k8s.io/kubernetes/pkg/quota/evaluator/core/registry.go
vendor/k8s.io/kubernetes/pkg/quota/evaluator/core/replication_controllers.go
vendor/k8s.io/kubernetes/pkg/quota/evaluator/core/resource_quotas.go
vendor/k8s.io/kubernetes/pkg/quota/evaluator/core/secrets.go
vendor/k8s.io/kubernetes/pkg/quota/evaluator/core/services.go
vendor/k8s.io/kubernetes/pkg/quota/evaluator/core/services_test.go

xref: https://bugzilla.redhat.com/show_bug.cgi?id=1473370
bug 1473370
see: https://github.com/kubernetes/kubernetes/pull/49230

UPSTREAM: 49230: use informers for quota calculation

---

pkg/bootstrap/docker/openshift/helper.go

The aggregator is always on in 3.7.  We should just go ahead and create keys for it.
[test]

always generate a config which contains aggregator keys for cluster up

---

pkg/build/builder/dockerutil.go

Add additional conditions to retry docker image push

---

pkg/router/metrics/haproxy/haproxy.go

fixes https://github.com/openshift/origin/issues/15279
Prometheus tightened rules on how counters can operate.
@deads2k
[test]

Switch haproxy methods to gauge from counter

---

pkg/cmd/server/origin/controller/quota.go
vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go
vendor/k8s.io/kubernetes/pkg/controller/resourcequota/resource_quota_controller.go
vendor/k8s.io/kubernetes/pkg/controller/resourcequota/resource_quota_controller_test.go
vendor/k8s.io/kubernetes/test/integration/quota/quota_test.go

[test]
lgtm'ed upstream, helps with debugging.  Will tag for merge on green.

UPSTREAM: 49227: tighten quota controller interface

---

pkg/security/scc/byrestrictions.go
pkg/security/scc/byrestrictions_test.go

In order to reduce number of magic numbers and simplify maintenance, this PR extracts these numbers into constants. Note that it's pure refactoring and it shouldn't break anything.
This also simplifies the way of adding additional weights later (see https://github.com/openshift/origin/pull/14825).
PTAL @openshift/security

Use constants for representation of the SCCs restrictiveness

---

pkg/cmd/server/kubernetes/master/controller/core.go
pkg/cmd/server/origin/master_config.go
vendor/k8s.io/kubernetes/plugin/cmd/kube-scheduler/app/configurator.go

@deads2k @derekwaynecarr 
Please review if helps without needing NewFromConfig.

Create scheduler from SchedulerServer and Configurator.

---

tools/etcdhelper/etcdhelper.go

Fixes: https://github.com/openshift/origin/issues/15209

[3.5] Backport etcdhelper

---

vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/BUILD
vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/plugins.go
vendor/k8s.io/kubernetes/pkg/volume/fc/BUILD
vendor/k8s.io/kubernetes/pkg/volume/fc/attacher.go
vendor/k8s.io/kubernetes/pkg/volume/fc/disk_manager.go
vendor/k8s.io/kubernetes/pkg/volume/fc/fc_test.go
vendor/k8s.io/kubernetes/pkg/volume/fc/fc_util.go

fix https://bugzilla.redhat.com/show_bug.cgi?id=1474469
@childsb @eparis
@jsafrane @tsmetana : is there anywhere else in ose master to make FC volume to support attach/detach?

UPSTREAM: 48940: support fc volume attach and detach

---

hack/update-generated-bindata.sh

Don't put OWNERS into bindata

---

cmd/cluster-capacity/go/src/github.com/kubernetes-incubator/cluster-capacity/OWNERS

UPSTREAM: kubernetes-incubator/cluster-capacity: <drop>: update OWNERS

---

pkg/cmd/server/origin/master.go
pkg/cmd/server/start/start_master.go

We were using the wrong client when the controller authorizes
@deads2k

Properly authorize controller API requests

---

images/openldap/OWNERS
pkg/api/OWNERS
pkg/auth/OWNERS
pkg/oauth/OWNERS
pkg/project/OWNERS
pkg/security/OWNERS
pkg/serviceaccounts/OWNERS
pkg/user/OWNERS
test/OWNERS

cc @stevekuznetsov @openshift/security PTAL

Add enj to appropriate OWNERS

---

test/testdata/admin-role-minus-create-istag.yaml
vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory_test.go
vendor/k8s.io/kubernetes/pkg/kubectl/resource/categories.go
vendor/k8s.io/kubernetes/pkg/kubectl/resource/categories_test.go
vendor/k8s.io/kubernetes/pkg/registry/batch/cronjob/storage/storage.go

we support cronjobs, so we need to expose them.

UPSTREAM: 49326: add cronjobs to all

---

vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/BUILD
vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
vendor/k8s.io/kubernetes/cmd/kube-controller-manager/controller-manager.go
vendor/k8s.io/kubernetes/federation/cmd/federation-controller-manager/controller-manager.go
vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/BUILD
vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go
vendor/k8s.io/kubernetes/pkg/util/reflector/prometheus/BUILD
vendor/k8s.io/kubernetes/pkg/util/reflector/prometheus/prometheus.go
vendor/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/BUILD
vendor/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/controller.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/cacher.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/BUILD
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/reflector.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/reflector_metrics.go

This will help us determine how healthy our reflectors are when dealing with "why are we listing so much" and "why aren't my watches working" problems.
@eparis @ironcladlou

add reflector metrics

---

vendor/github.com/containers/image/signature/mechanism_openpgp.go

3.6 version of https://github.com/openshift/origin/pull/15490

[3.6] UPSTREAM: containers/image: <carry>: Do not check lifetime for v3 gpg signatures

---

cmd/OWNERS
pkg/cmd/OWNERS
pkg/config/OWNERS
test/cmd/OWNERS
tools/clicheck/OWNERS
tools/genman/OWNERS

More CLI OWNERS

---

hack/test-integration.sh

Most flakes are uncommon.  Our e2e tests retry a failing test once to see if it passes a second time.  This is fine as long as we can track the failures.
This retries a failing integration test in CI if it fails.  There is a spot to wire a hook to track the flake so we can chase it down later.
@stevekuznetsov I'd like to see an issue about tracking this.  I'm fine with having a second source of junit failures to even just track the names and $out.

retry integration failures to suppress the long tail of flakes

---

hack/push-release.sh

Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1475752

Include origin-egress-http-proxy image in the release

---

vendor/github.com/containers/image/signature/mechanism_openpgp.go

Fixes: https://github.com/openshift/origin/issues/15489
@mtrmac 
With this fix:
```
$ oc adm verify-image-signature sha256:582cb940a6e730dbdffee7cc5e1983522fdeeb3c40bea7373b255a209124cc02 --expected-identity=registry.access.redhat.com/rhel7:latest --public-key=/tmp/redhat.pub --save
$ oc describe istag rhel7:latest
Image Signatures:
Name:		sha256:582cb940a6e730dbdffee7cc5e1983522fdeeb3c40bea7373b255a209124cc02@rhel7
Type:		AtomicImageV1
Status:		Verified
Issued By:	199E2F91FD431D51
Signature is Trusted (verified by user "test-admin" on 2017-07-27 10:44:00 +0200 CEST)
Signature is ForImage ( on 2017-07-27 10:44:00 +0200 CEST)
```

UPSTREAM: containers/image: <carry>: Do not check lifetime for v3 gpg signature

---

pkg/deploy/strategy/support/lifecycle.go

Fixes: https://github.com/openshift/origin/issues/15445

deploy: use subPath in hooks for volumes when defined

---

examples/service-catalog/service-catalog.yaml
pkg/bootstrap/bindata.go
pkg/bootstrap/docker/openshift/servicecatalog.go
pkg/bootstrap/docker/up.go

bug 1475219
https://bugzilla.redhat.com/show_bug.cgi?id=1475219

respect --image flag value for service catalog image name

---

examples/wordpress/OWNERS
images/release/OWNERS
pkg/openapi/OWNERS
pkg/service/OWNERS
tools/OWNERS
tools/rebasehelpers/OWNERS

PTAL @stevekuznetsov @kargakis

Remove myself from the reviewers list for a bunch of components

---

Godeps/Godeps.json

Fixing wrong import path for kube-gen

bump(k8s.io/kubernetes): d2e5420de791a3a5234eb1c3d84921d68ae2b6d6

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/maxinflight.go

We need this to debug prod issues, is replaced with a better change in
3.7 that is more invasive

UPSTREAM: <drop>: Carry a patch for reporting 429 metrics

---

CONTRIBUTING.adoc

PTAL @stevekuznetsov 
CC @simo5

CONTRIBUTING.adoc: update minimum Go version

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/cacher.go

Punch through to the underlying storage when we are unable to get the
initial state for the cache, as in very large clusters.
@deads2k @liggitt verified this manually with my local "force watches and lists to be slow"

UPSTREAM: 49688: Don't block watch cache Get/List on unready

---

OWNERS
examples/db-templates/OWNERS
examples/project-quota/OWNERS
pkg/OWNERS
pkg/dns/OWNERS
pkg/gitserver/OWNERS
pkg/ipfailover/OWNERS
pkg/route/OWNERS
pkg/util/OWNERS
test/OWNERS
test/cmd/OWNERS
test/integration/OWNERS
test/templates/OWNERS
test/testdata/OWNERS

Remove myself from a bunch of OWNERS files

---

test/extended/util/framework.go

fixes https://github.com/openshift/origin/issues/14972

debug for extended test pv creation

---

OWNERS
examples/OWNERS
hack/OWNERS
images/OWNERS
images/builder/OWNERS
pkg/auth/OWNERS
pkg/authorization/OWNERS
pkg/dns/OWNERS
pkg/oauth/OWNERS
pkg/quota/OWNERS
pkg/route/OWNERS
pkg/scheduler/OWNERS
pkg/sdn/OWNERS
pkg/security/OWNERS
pkg/unidling/OWNERS

remove mfojtik from bunch of OWNERs

---

contrib/completions/OWNERS

More OWNERS, PTAL @stevekuznetsov @liggitt.

Owners for CLI completions

---

contrib/completions/OWNERS

Reverts openshift/origin#15596

Revert "Owners for CLI completions"

---

pkg/build/builder/common.go

Retry build status update on non-conflict error

---

pkg/oc/bootstrap/docker/openshift/logging.go
pkg/oc/bootstrap/docker/openshift/servicecatalog.go
pkg/oc/bootstrap/docker/openshift/util.go

fixes https://github.com/openshift/origin/issues/15562

Tolerate pre-existence of SC roles during SC setup.

---

contrib/kubernetes/static/controllers-pod.yaml
pkg/cmd/server/api/v1/conversions.go
pkg/cmd/server/api/v1/swagger_doc.go
pkg/cmd/server/api/v1/types.go
pkg/cmd/server/kubernetes/master/master_config.go
pkg/cmd/server/origin/leaderelection.go
pkg/cmd/server/start/start_master.go
vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
vendor/k8s.io/kubernetes/pkg/client/leaderelection/resourcelock/interface.go
vendor/k8s.io/kubernetes/plugin/cmd/kube-scheduler/app/server.go

Use configmap election by default

---

pkg/cmd/server/origin/controller/standalone_apiserver.go
pkg/cmd/server/origin/master.go
pkg/cmd/server/origin/nonapiserver.go
pkg/cmd/server/origin/openshift_apiserver.go
pkg/cmd/server/start/start_master.go
pkg/openservicebroker/server/apiserver.go

@soltysh getting ready for switching.

cleanup apiserver wiring using a `With` pattern

---

pkg/bootstrap/docker/dockerhelper/ipv4range.go
pkg/bootstrap/docker/dockerhelper/registryconfig.go
pkg/bootstrap/docker/dockerhelper/registryconfig_test.go
pkg/oc/bootstrap/docker/dockerhelper/helper.go
pkg/oc/bootstrap/docker/errors/docker.go
pkg/oc/bootstrap/docker/up.go

Fixes #13136
@jorgemoralespou @csrwng

issue-13136 cluster up validates/allows all appropriate docker registry CIDR

---

examples/image-streams/OWNERS

As a courtesy since Ryan does not work at Red Hat anymore.
On the correct branch this time! 😄

Remove oatmealraisin from OWNERS

---

pkg/cmd/server/origin/storage.go
pkg/oc/admin/router/router.go
pkg/security/admission/admission.go
pkg/security/admission/admission_test.go
pkg/security/registry/podsecuritypolicyreview/rest.go
pkg/security/registry/podsecuritypolicyreview/rest_test.go
pkg/security/registry/podsecuritypolicyselfsubjectreview/rest.go
pkg/security/registry/podsecuritypolicyselfsubjectreview/rest_test.go
pkg/security/registry/podsecuritypolicysubjectreview/rest.go
pkg/security/registry/podsecuritypolicysubjectreview/rest_test.go
pkg/security/securitycontextconstraints/bypriority.go
pkg/security/securitycontextconstraints/bypriority_test.go
pkg/security/securitycontextconstraints/byrestrictions.go
pkg/security/securitycontextconstraints/byrestrictions_test.go
pkg/security/securitycontextconstraints/matcher.go
pkg/security/securitycontextconstraints/matcher_test.go

Move all the files from `pkg/security/scc` into `pkg/security/securitycontextconstraints`.
PTAL @pweil- @deads2k 
CC @simo5

Merge pkg/security/scc into pkg/security/securitycontextconstraints package

---

pkg/cmd/server/bootstrappolicy/controller_policy.go
test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml

I found this making the separate TSB work.  The role is missing permissions.

update the TSB role to have required permissions

---

examples/db-templates/mariadb-ephemeral-template.json
examples/db-templates/mariadb-persistent-template.json
examples/db-templates/mongodb-ephemeral-template.json
examples/db-templates/mongodb-persistent-template.json
examples/db-templates/mysql-ephemeral-template.json
examples/db-templates/mysql-persistent-template.json
examples/db-templates/postgresql-ephemeral-template.json
examples/db-templates/postgresql-persistent-template.json
pkg/oc/bootstrap/bindata.go
test/extended/testdata/bindata.go

https://bugzilla.redhat.com/show_bug.cgi?id=1479660

add db name to the provided secret

---

hack/lib/build/images.sh

Previously, we were concealing the error code of the actual image build
and not passing it all the way up. This meant that errors were ignored
and that the retry logic did not kick in.

Correctly propogate error code from image builds up

---

pkg/cmd/server/origin/storage.go
pkg/template/registry/templateinstance/etcd/etcd.go
pkg/template/registry/templateinstance/strategy.go

Tighten the interface in the strategy to what's needed.

tighten interfaces for template instance API

---

pkg/cmd/server/origin/master.go

This removes an unnecessary layer and brings us closer to upstream.

collapse onto the upstream requestcontextmapper

---

pkg/assets/apiserver/asset_apiserver.go
pkg/assets/handlers.go
pkg/cmd/server/origin/asset_apiserver_adapter.go
pkg/cmd/server/origin/handlers.go
pkg/cmd/server/origin/master.go
pkg/cmd/server/start/start_master.go

moves the asset server out of the main apiserver package.

separate the asset server from the rest of the servers

---

examples/prometheus/README.md

toying around with promql, few new useful queries.

add 2 new queries

---

examples/prometheus/prometheus.yaml
pkg/oc/bootstrap/bindata.go
test/extended/testdata/bindata.go

Was not registered on the route.
Found while testing #15078

Fix alerts proxy configuration to include proper SAR and oauth

---

hack/update-generated-bindata.sh
test/extended/cluster/cl.go
test/extended/cluster/context.go
test/extended/cluster/utils.go
test/extended/extended_test.go
test/extended/testdata/bindata.go
test/extended/testdata/cluster/master-vert.yaml
vendor/github.com/fatih/structs/.gitignore
vendor/github.com/fatih/structs/.travis.yml
vendor/github.com/fatih/structs/LICENSE
vendor/github.com/fatih/structs/README.md
vendor/github.com/fatih/structs/field.go
vendor/github.com/fatih/structs/field_test.go
vendor/github.com/fatih/structs/structs.go
vendor/github.com/fatih/structs/structs_example_test.go
vendor/github.com/fatih/structs/structs_test.go
vendor/github.com/fatih/structs/tags.go
vendor/github.com/fatih/structs/tags_test.go

New test to automate loading of clusters for perf  & scale tests.
@smarterclayton @jeremyeder

Clusterloader basic

---

pkg/cmd/server/kubernetes/master/controller/config.go
pkg/cmd/server/kubernetes/master/kube_controller_init.go
pkg/cmd/server/origin/controller/config.go
pkg/cmd/server/origin/controller/quota.go
pkg/cmd/server/origin/master_config.go
pkg/cmd/server/origin/openshift_apiserver.go
pkg/cmd/server/start/start_master.go
test/integration/buildcontroller_test.go

Move controller initialization closer to where they belong and further from the apiserver

scrub controller methods

---

pkg/cmd/server/kubernetes/master/kube_controller_init.go
pkg/cmd/server/kubernetes/master/master_config.go
pkg/cmd/server/origin/master_config.go
pkg/cmd/server/start/start_master.go
pkg/util/restoptions/configgetter.go
test/integration/buildcontroller_test.go
tools/testdebug/cmd/load_etcd.go

Remove unnecessary fields and indirection from api server start

remove unnecessary fields

---

pkg/cmd/server/kubernetes/master/master_config.go
pkg/cmd/server/origin/master_config.go
pkg/cmd/server/start/start_master.go
pkg/util/restoptions/configgetter.go
test/integration/buildcontroller_test.go
tools/testdebug/cmd/load_etcd.go

This reverts commit 2a42c755c5eaf7c10919d22c53ba7cea35e798b0, reversing
changes made to b0df9bc949122bdde3bb1e7a80be0a3ce715d3ad.
/cc @deads2k @bparees

Revert "Merge pull request #15845 from deads2k/server-32-scrub-kuber"

---

examples/quickstarts/cakephp-mysql-persistent.json
examples/quickstarts/cakephp-mysql.json
examples/quickstarts/dancer-mysql-persistent.json
examples/quickstarts/dancer-mysql.json
examples/quickstarts/django-postgresql-persistent.json
examples/quickstarts/django-postgresql.json
examples/quickstarts/nodejs-mongodb-persistent.json
examples/quickstarts/nodejs-mongodb.json
examples/quickstarts/rails-postgresql-persistent.json
examples/quickstarts/rails-postgresql.json
examples/sample-app/application-template-custombuild.json
examples/sample-app/application-template-dockerbuild.json
examples/sample-app/application-template-pullspecbuild.json
examples/sample-app/application-template-stibuild.json
examples/wordpress/template/wordpress-mysql.json
pkg/oc/bootstrap/bindata.go
test/extended/testdata/bindata.go

add missing template.alpha.openshift.io/wait-for-ready annotations to examples

---

examples/templateservicebroker/templateservicebroker-template.yaml
pkg/oc/bootstrap/bindata.go
pkg/oc/bootstrap/docker/openshift/templateservicebroker.go
pkg/oc/bootstrap/docker/up.go
test/extended/testdata/bindata.go

oc cluster up: pass server loglevel to template service broker

---

pkg/cmd/server/bootstrappolicy/policy.go

Stop using NormalizeResources in bootstrap policy

---

test/extended/templates/helpers.go
test/extended/templates/templateservicebroker_e2e.go
test/extended/templates/templateservicebroker_security.go

debugging information for https://github.com/openshift/origin/issues/15912

add logging information to debug failing port-forward

---

test/extended/router/metrics.go

Hit a flake where endpoints weren't available. Instead of exiting and failing on the next test, wait longer, and fail if we never succeed.

Retry longer for metrics to become available

---

pkg/cmd/server/origin/master.go
pkg/cmd/server/origin/openshift_apiserver.go
pkg/openservicebroker/server/apiserver.go
vendor/k8s.io/kubernetes/pkg/master/master.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/hooks.go

Ensure AddPostStartHook always succeeds, or die

---

pkg/sdn/plugin/proxy.go

fixes #15922
@derekwaynecarr @smarterclayton

fix bad scope nil deref in endpoints update

---

test/extended/image_ecosystem/s2i_images.go
test/extended/image_ecosystem/scl.go

the closed variables were getting updated mid-test due to parallelism.

remove use of closure from imageecosystem

---

pkg/cmd/util/clientcmd/factory_client_access.go
pkg/oc/cli/cmd/set/set.go
test/cmd/set-image.sh

fixes https://github.com/openshift/origin/issues/14487

default oc set image to --source=docker

---

test/extended/templates/helpers.go

resolve `groups "impersonategroup" already exists` error

---

images/dind/master/openshift-master.service
images/dind/node/openshift-node.service
test/util/etcd.go

Bump integration test loglevel down to 4

---

pkg/client/client.go
pkg/image/controller/imagestream_controller.go
pkg/image/controller/scheduled_image_controller.go

@deads2k the requested followup to #15985

Remove unnecessary imageStreamLister interface

---

hack/build-images.sh
hack/release.sh

Includes release v3.7.0-alpha.1 tag

Break release into pieces, build images in parallel

---

test/extended/templates/templateservicebroker_e2e.go
test/extended/templates/templateservicebroker_security.go

This reverts commit 3e9c66cc1449f691751bd9cb20b1e7a0e7b0a028.

Revert "skip tsb tests on GCE until new images are published"

---

test/extended/builds/build_pruning.go
test/extended/builds/docker_pullsecret.go
test/extended/builds/new_app.go
test/extended/builds/no_outputname.go
test/extended/builds/optimized.go
test/extended/builds/remove_buildconfig.go
test/extended/builds/s2i_quota.go
test/extended/builds/s2i_root.go
test/extended/builds/valuefrom.go

This reverts commit 676bff335c3d0a9d86a904f81886d5c79d35bbbb.

Revert "skip build tests on GCE because new images are needed there"

---

examples/service-catalog/service-catalog.yaml
install/templateservicebroker/apiserver-template.yaml
install/templateservicebroker/rbac-template.yaml
pkg/oc/bootstrap/bindata.go
pkg/oc/bootstrap/docker/openshift/servicecatalog.go
pkg/oc/bootstrap/docker/openshift/templateservicebroker.go
pkg/oc/bootstrap/docker/up.go
test/extended/testdata/bindata.go

fixes https://github.com/openshift/origin/issues/15875
and 
https://bugzilla.redhat.com/show_bug.cgi?id=1470628

include token in tsb registration

---

Godeps/Godeps.json

zero-diff bump for marking https://github.com/openshift/kubernetes/commits/openshift-3.7

bump(k8s.io/kubernetes): 80709908fd80e48ea9a619e23892747856969487

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store_test.go

From openshift/origin: `hack/cherry-pick.sh 511481`

UPSTREAM: 51148: Enable finalizers independent of GC enablement

---

install/service-catalog-broker-resources/template-service-broker-registration.yaml
pkg/oc/bootstrap/bindata.go
pkg/oc/bootstrap/docker/openshift/logging.go
pkg/oc/bootstrap/docker/openshift/servicecatalog.go
pkg/oc/bootstrap/docker/openshift/templateservicebroker.go
pkg/oc/bootstrap/docker/openshift/util.go
pkg/oc/bootstrap/docker/up.go
test/extended/testdata/bindata.go

fixes https://github.com/openshift/origin/issues/16075

perform tsb registration via a template

---

pkg/auth/server/tokenrequest/endpoints.go
pkg/oauth/apiserver/auth.go
test/util/server/server.go

This change makes it so that the Osin OAuth client for the token request endpoint is lazily initialized when the endpoint is called.  Initializing in this case refers to fetching the private OpenShift browser OAuth client from the API to get its secret (it is required to build the Osin client).  This behavior was lost when we moved away from using the OAuth registries.
Fixes #16078
/assign @deads2k @liggitt
I plan to open a separate PR with something that tests this endpoint to make sure we do not regress again.  Tracked in #16146

Lazily initialize Osin client for token endpoint

---

pkg/oc/bootstrap/docker/openshift/templateservicebroker.go
pkg/oc/bootstrap/docker/up.go

fixes https://bugzilla.redhat.com/show_bug.cgi?id=1488060

allow cluster up/tsb to tolerate any version of 3.7.x, prerelease or otherwise

---

pkg/cmd/server/start/start_kube_scheduler.go

fixes https://github.com/openshift/origin/issues/16135

use configmaps for scheduler lease

---

vendor/k8s.io/kubernetes/pkg/volume/flexvolume/driver-call.go
vendor/k8s.io/kubernetes/pkg/volume/flexvolume/mounter-defaults.go
vendor/k8s.io/kubernetes/pkg/volume/flexvolume/plugin.go

also includes https://github.com/kubernetes/kubernetes/pull/51342

UPSTREAM: 50843: FlexVolume: Add ability to control 'SupportsSELinux' during driver's init phase

---

pkg/build/builder/common.go
pkg/build/builder/docker.go
pkg/build/builder/sti.go

Ensure that StepExecPostCommit is not recorded if no PostCommit exists

---

pkg/generate/app/cmd/newapp.go
test/cmd/newapp.sh
test/testdata/newapp/imagestream-ref.yaml

Fixes https://github.com/openshift/origin/issues/16206

new-app: fix stack overflow when resolving imagestream reference to a different imagestream

---

pkg/authorization/apis/authorization/types.go
pkg/authorization/authorizer/scope/converter.go
pkg/authorization/authorizer/scope/converter_test.go
pkg/cmd/server/bootstrappolicy/policy.go
test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml

Use rbac.PolicyRule directly for DiscoveryRule

---

pkg/cmd/server/bootstrappolicy/policy.go
test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml

Remove policy and policybinding from bootstrap policy

---

examples/prometheus/README.md
examples/prometheus/node-exporter.yaml
pkg/oc/bootstrap/bindata.go
test/extended/testdata/bindata.go

Optional component to be installed alongside prometheus

Add node-exporter example to prometheus

---

Godeps/Godeps.json

Bump from openshift/kubernetes@80709908fd80e48ea9a619e23892747856969487 to openshift/kubernetes@930b5c4b2db777e7ece981d84e9430808feceb4c

bump(github.com/kubernetes/kubernetes):930b5c4b2db

---

examples/quickstarts/cakephp-mysql-persistent.json
examples/quickstarts/cakephp-mysql.json
examples/quickstarts/dancer-mysql-persistent.json
examples/quickstarts/dancer-mysql.json
examples/quickstarts/httpd.json
pkg/oc/bootstrap/bindata.go
test/extended/image_ecosystem/s2i_perl.go
test/extended/image_ecosystem/s2i_php.go
test/extended/image_ecosystem/s2i_python.go
test/extended/image_ecosystem/s2i_ruby.go
test/extended/testdata/bindata.go

also refreshes the quickstart examples from their source repos.

use offsets for test failure reporting

---

vendor/k8s.io/kubernetes/pkg/volume/fc/attacher.go
vendor/k8s.io/kubernetes/pkg/volume/fc/disk_manager.go
vendor/k8s.io/kubernetes/pkg/volume/fc/fc_util.go

fix https://bugzilla.redhat.com/show_bug.cgi?id=1473855
@mtanino 

UPSTREAM: 49416: FC volume plugin: remove block device at DetachDisk

---

pkg/apps/controller/deployer/factory.go
pkg/image/controller/factory.go
pkg/image/controller/imagestream_controller.go
pkg/image/controller/imagestream_controller_test.go

Fixes #15103.
@smarterclayton || @deads2k ptal

Fix getByKey to return all errors

---

pkg/apps/cmd/delete.go
pkg/apps/cmd/delete_test.go

Ignore the first 2 commits, they are part of https://github.com/openshift/origin/pull/16149
Don't try to emulate PATCH behavior with retrying updates on conflicts (of course patch can also conflict, but chances are low). Also we use PATCH for pausing in `oc rollout pause` already, so this just unify this behavior.
Ref: https://github.com/openshift/origin/pull/16149#discussion_r137062257

apps: use patch when pausing dc on delete

---

pkg/oc/bootstrap/docker/openshift/helper.go

fixes https://github.com/openshift/origin/issues/16313

do not enable pod presets, they've been removed from 3.7

---

test/integration/imageimporter_test.go

cherry-pick of 0d8eb249e7d97bbcfd81c3905b8b9cac8e0bb630
/cc @deads2k @bparees @soltysh

cherry-pick of 0d8eb249e7d97bbcfd81c3905b8b9cac8e0bb630

---

vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go

Downstream kubernetes/kubernetes#52344

UPSTREAM: 52344: Do not log spam image pull backoff

---

test/extended/builds/pipeline.go
test/extended/util/framework.go

improve debug for maven jenkins pipeline failures

---

hack/dind-cluster.sh
images/dind/master/openshift-generate-master-config.sh
images/dind/master/ovn-kubernetes-master-setup.sh
images/dind/master/ovn-kubernetes-master.sh
images/dind/node/Dockerfile
images/dind/node/crio-node.service
images/dind/node/crio-node.sh
images/dind/node/openshift-generate-node-config.sh
images/dind/node/ovn-kubernetes-node-setup.sh
images/dind/node/ovn-kubernetes-node.sh
pkg/cmd/server/kubernetes/node/sdn_linux.go

@danwinship @stevekuznetsov @openshift/networking @openshift/sig-networking @marun

dind: add support for CRI-O runtime via "-c crio" start argument

---

pkg/cmd/server/admin/overwrite_bootstrappolicy.go
pkg/cmd/util/clientcmd/gating.go
pkg/cmd/util/clientcmd/gating_test.go
pkg/oc/admin/migrate/authorization/authorization.go
pkg/oc/cli/cmd/create/policy_binding.go
test/cmd/admin.sh
test/cmd/migrate.sh
test/cmd/policy.sh

Use discovery based version gating for policy commands #16219

---

pkg/oc/bootstrap/docker/up.go

fixes https://github.com/openshift/origin/issues/16372

only install component specific templates when requested

---

vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go

Fixes  https://bugzilla.redhat.com/show_bug.cgi?id=1474441

UPSTREAM: 49420: Fix c-m crash while verifying attached volumes

---

hack/import-restrictions.json
pkg/image/apis/image/v1/conversion.go
pkg/image/apis/image/v1/conversion_test.go

Use a specific, private scheme to handle the conversion of internal image apis stuff.
@bparees @soltysh found it!

remove install dependency from images

---

hack/import-restrictions.json
pkg/apps/apis/apps/v1/conversion_test.go
pkg/apps/apis/apps/v1/defaults_test.go
pkg/authorization/apis/authorization/v1/defaults_test.go
pkg/build/apis/build/v1/conversion_test.go
pkg/build/apis/build/v1/defaults_test.go
pkg/quota/apis/quota/deep_copy_test.go

Removes API install dependencies from the rest of the API pacakges.

remove install dependencies from api packages

---

pkg/service/controller/servingcert/secret_creating_controller.go
pkg/service/controller/servingcert/secret_updating_controller.go
pkg/service/controller/servingcert/secret_updating_controller_test.go

Switch the service serving cert controller to use listers over cache.Store.

servingcert: switch to listers

---

pkg/cmd/util/clientcmd/client.go
pkg/cmd/util/clientcmd/factory_client_access.go
pkg/cmd/util/clientcmd/factory_object_mapping.go
pkg/user/reaper/bindings.go
pkg/user/reaper/group.go
pkg/user/reaper/group_test.go
pkg/user/reaper/user.go
pkg/user/reaper/user_test.go

Alternative to https://github.com/openshift/origin/pull/16203

cli: provide generated clients via ClientAccessFactory

---

images/openldap/OWNERS
pkg/auth/OWNERS
pkg/authorization/OWNERS
pkg/cmd/OWNERS
pkg/oauth/OWNERS
pkg/security/OWNERS
pkg/serviceaccounts/OWNERS
pkg/user/OWNERS
test/OWNERS
test/testdata/OWNERS

Add security team to reviewers for security pkgs

---

vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go
vendor/k8s.io/kubernetes/pkg/kubelet/cadvisor/BUILD
vendor/k8s.io/kubernetes/pkg/kubelet/cadvisor/cadvisor_linux.go
vendor/k8s.io/kubernetes/pkg/kubelet/cadvisor/cadvisor_unsupported.go
vendor/k8s.io/kubernetes/pkg/kubelet/cadvisor/cadvisor_windows.go
vendor/k8s.io/kubernetes/pkg/kubelet/cadvisor/helpers_linux.go
vendor/k8s.io/kubernetes/pkg/kubelet/cadvisor/helpers_unsupported.go
vendor/k8s.io/kubernetes/pkg/kubelet/cadvisor/types.go
vendor/k8s.io/kubernetes/pkg/kubelet/cadvisor/util.go
vendor/k8s.io/kubernetes/test/e2e_node/environment/conformance.go

https://github.com/kubernetes/kubernetes/pull/51728
https://github.com/kubernetes/kubernetes/pull/52073
https://github.com/kubernetes/kubernetes/pull/52297
@derekwaynecarr @mrunalp 
https://trello.com/c/9nhJ7wcK

Pick kubelet CRI-O enhancements

---

test/extended/router/metrics.go

https://github.com/openshift/origin/pull/16365

fix http codes for router e2e

---

pkg/apps/client/v1/scale.go
pkg/cmd/server/api/helpers.go
pkg/cmd/server/origin/controller/autoscaling.go
pkg/cmd/server/origin/controller/interfaces.go
pkg/cmd/server/origin/controller/unidling.go
pkg/cmd/server/origin/ensure.go
pkg/cmd/server/origin/master.go
pkg/cmd/server/origin/master_config.go
pkg/cmd/server/origin/openshift_apiserver.go
pkg/cmd/server/start/controllers.go
pkg/cmd/server/start/informers.go
pkg/gitserver/gitserver.go
pkg/router/controller/factory/eventqueue.go
pkg/router/controller/factory/eventqueue_test.go
pkg/router/controller/factory/factory.go
pkg/service/admission/endpoint_admission.go
pkg/user/reaper/group_test.go
pkg/user/reaper/user_test.go
test/extended/util/test.go

Cleans up a bunch of different legacy client usage.

remove legacy client usage

---

test/cmd/images.sh

fixes https://github.com/openshift/origin/issues/16468

remove scheduled import patch test

---

api/docs/apis-build.openshift.io/v1.BuildConfig.adoc
api/docs/oapi/v1.BuildConfig.adoc
api/swagger-spec/oapi-v1.json
api/swagger-spec/openshift-openapi-spec.json
pkg/build/registry/buildconfiginstantiate/rest.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go

fixes #8345
dependent on https://github.com/kubernetes/kubernetes/pull/51972 merging

api docs should show right return value for build instantiate{binary,}

---

examples/prometheus/prometheus.yaml
hack/import-restrictions.json
install/templateservicebroker/apiserver-template.yaml
pkg/oc/bootstrap/bindata.go
pkg/templateservicebroker/cmd/server/start.go
pkg/templateservicebroker/openservicebroker/server/apiserver.go
pkg/templateservicebroker/servicebroker/test-scripts/clusterrole.yaml
test/extended/testdata/bindata.go

https://trello.com/c/wDxqVOqy/1181-5-prometheus-metrics-for-template-broker-techdebt

enable base prometheus metrics for template service broker

---

pkg/assets/apiserver/asset_apiserver.go
pkg/auth/oauth/external/handler_test.go
pkg/auth/oauth/handlers/default_auth_handler.go
pkg/auth/oauth/handlers/default_auth_handler_test.go
pkg/cmd/server/kubernetes/master/master_config.go
pkg/cmd/server/origin/master.go
pkg/cmd/server/start/start_master.go
pkg/oauth/apiserver/auth.go
pkg/oauth/apiserver/oauth_apiserver.go

Wire advanced audit to asset and oauth api servers

---

pkg/diagnostics/cluster/rolebindings.go
pkg/diagnostics/cluster/roles.go
pkg/oc/admin/diagnostics/cluster.go
pkg/oc/admin/policy/reconcile_clusterrolebindings.go
pkg/oc/admin/policy/reconcile_clusterroles.go

This took less work than I thought (yay!).
@openshift/sig-security fyi

switch reconciliation to generated clients

---

pkg/templateservicebroker/servicebroker/lastoperation.go

tsb: return error description on failed async operation

---

pkg/cmd/server/kubernetes/master/master_config.go

@enj @deads2k ptal this is the forgotten fix from #16567

Return error instead of glog.Fatalf

---

pkg/oc/cli/cmd/extract.go
test/cmd/secrets.sh

oc extract configmap/foo --to=-
will output the configmap to stdout.

Allow oc extract to output to stdout

---

pkg/build/builder/source.go

bug 1486457
https://bugzilla.redhat.com/show_bug.cgi?id=1486457

Wipe out any existing content in the workdir before cloning

---

test/extended/deployments/deployments.go

Fixes: https://github.com/openshift/origin/issues/16592

Make DC extended ControllerRef test more resilient

---

pkg/apps/metrics/prometheus/metrics.go

Fixes: http://bugzilla.redhat.com/show_bug.cgi?id=1497394
EDIT: I think using the `generation` in RC is wrong here. We should use the latestVersion instead. I will add that change into this PR.

apps: fix logic error in last failed rollout metric

---

test/extended/builds/pipeline.go
test/extended/image_ecosystem/jenkins_plugin.go
test/extended/util/jenkins/monitor.go

@openshift/devex ptal
(per recent @bparees request to quiet down / rework ext failure debug given natural evolution)

reverse default for jenkins ext test mem monitor

---

examples/prometheus/prometheus.yaml
pkg/oc/bootstrap/bindata.go
test/extended/prometheus/prometheus.go
test/extended/testdata/bindata.go

Update images to latest built tags (beta.5) and correct a few minor nits.

Switch to stateful set in prometheus

---

pkg/templateservicebroker/openservicebroker/api/types.go
pkg/templateservicebroker/servicebroker/provision.go
test/extended/templates/templateinstance_readiness.go
test/extended/templates/templateservicebroker_e2e.go

annotate TemplateInstance objects created by TSB with instance UUID

---

pkg/oc/cli/cmd/process.go
pkg/template/template.go
pkg/template/template_test.go

oc process: show multiple parameter errors where present

---

pkg/build/controller/strategy/sti.go
pkg/build/controller/strategy/sti_test.go
pkg/cmd/server/origin/controller/build.go
pkg/cmd/server/origin/controller/interfaces.go

use PodSecurityPolicySubjectReview in build controller to avoid actually submitting a pod

---

pkg/oc/admin/prune/images.go

Resolves: [bz#1469654](https://bugzilla.redhat.com/show_bug.cgi?id=1469654)

image-pruning: Improve help and error reporting

---

test/extended/templates/templateservicebroker_e2e.go
test/extended/templates/templateservicebroker_security.go

have tsb provision tests timeout after 20 minutes

---

test/extended/templates/templateinstance_readiness.go
test/extended/templates/templateservicebroker_e2e.go
test/extended/templates/templateservicebroker_security.go

wait for builder service account on necessary templateinstance/tsb tests

---

test/extended/prometheus/prometheus_builds.go

see https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_builds/229/display/redirect
@openshift/devex per this morning's email exchange

add retry to openshift build prometheus ext test initial service access

---

pkg/network/node/metrics.go

Fixes: https://github.com/openshift/origin/pull/16518
Fixes for comments on the code that happened after it merged.
@smarterclayton @danwinship @eparis @knobunc

sdn: metrics fixes for review comments

---

vendor/github.com/google/cadvisor/container/common/fsHandler.go

https://github.com/google/cadvisor/pull/1766
xref https://bugzilla.redhat.com/show_bug.cgi?id=1498632
@derekwaynecarr @ravisantoshgudimetla 
hold pending #16615

UPSTREAM: google/cadvisor: 1766: adaptive longOp for du operation

---

vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/cache/desired_state_of_world.go
vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/reconciler/reconciler.go
vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/reconciler/reconciler_test.go

UPSTREAM: 53401: Fix spam of multiattach errors in event logs

---

test/extended/util/cli.go
test/extended/util/sar.go

Fixes https://github.com/openshift/origin/issues/15792

Fix extended test namespace provisioning - wait for SA using selfSAR

---

pkg/cmd/server/origin/leaderelection.go

This change makes it easier to determine which controller process is the leader in a high availability set up by using hostname and IP as the base. The lookup of both values is best effort and will not error.  A random postfix is still used to guarantee uniqueness.
/assign @smarterclayton @jupierce
/kind bug
Marking this as a bug because it wastes CD team's time by forcing them to look at which process is "working" to determine the current leader.

Base random controller leader ID on machine info

---

pkg/build/registry/buildconfiginstantiate/rest.go

@openshift/devex fyi
fix the panic
```
panic(0x512e0c0, 0xf08fa50)
/usr/lib/golang/src/runtime/panic.go:489 +0x2cf
github.com/openshift/origin/pkg/build/registry/buildconfiginstantiate.(*binaryInstantiateHandler).handle(0xc437c069c0, 0x7f767c03d528, 0xc43427c960, 0x0, 0x0, 0x0, 0x0)
/tmp/openshift/build-rpm-release/tito/rpmbuild-originnDR2dQ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/pkg/build/registry/buildconfiginstantiate/rest.go:231 +0x3f5
github.com/openshift/origin/pkg/build/registry/buildconfiginstantiate.(*binaryInstantiateHandler).ServeHTTP(0xc437c069c0, 0xf115400, 0xc42d56e920, 0xc4326d8600)
/tmp/openshift/build-rpm-release/tito/rpmbuild-originnDR2dQ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/pkg/build/registry/buildconfiginstanti …
```

fix select error handling after WaitForRunningBuild

---

pkg/oc/bootstrap/docker/openshift/OWNERS

This PR adds my github ID as an approver in packages required to approve service-catalog updates.

Add pmorie to OWNERS in required packages for service-catalog updates

---

tools/etcdhelper/etcdhelper.go

Register APIService for apiregistration.k8s.io/v1beta1

---

Godeps/Godeps.json

@deads2k you missed pushing that after syncing our fork.

bump(k8s.io/kubernetes): c84beffa03930fdedb9d523dde9f34506913f2b0

---

pkg/oc/cli/cmd/importimage.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1494231

Fix reimporting from insecure registries

---

examples/service-catalog/service-catalog.yaml
pkg/oc/bootstrap/bindata.go

Let servicecatalog-serviceclass-viewer also view plans

---

vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/cache/desired_state_of_world.go

Fixes https://github.com/openshift/origin/issues/16787

UPSTREAM: 53682: Use proper locks when updating desired state

---

origin.spec

Change golang version from 1.8.3 to 1.8.1 in origin.spec

---

docs/rebase.md

@mfojtik like promised, although I'm still working on details...
@ironcladlou since you were doing the last one with me and you might have valuable input
@smarterclayton @liggitt @deads2k @sttts as the old cavalry with with multiple rebase done

Rebase docs

---

test/extended/builds/s2i_env.go
test/extended/builds/s2i_incremental.go

fixes https://github.com/openshift/origin/issues/16826

wait for pod before waiting for endpoint

---

pkg/cmd/util/cmd.go
pkg/oc/admin/registry/registry.go
pkg/oc/admin/router/router.go
pkg/oc/cli/cmd/example.go
pkg/oc/cli/cmd/export.go
pkg/oc/cli/cmd/extract.go
pkg/oc/cli/cmd/idle.go
pkg/oc/cli/cmd/importer/appjson.go
pkg/oc/cli/cmd/newapp.go
pkg/oc/cli/cmd/newbuild.go
pkg/oc/cli/cmd/set/buildhook.go
pkg/oc/cli/cmd/set/buildsecret.go
pkg/oc/cli/cmd/set/deploymenthook.go
pkg/oc/cli/cmd/set/env.go
pkg/oc/cli/cmd/set/probe.go
pkg/oc/cli/cmd/set/routebackends.go
pkg/oc/cli/cmd/set/triggers.go
pkg/oc/cli/cmd/set/volume.go
pkg/oc/experimental/ipfailover/ipfailover.go

fixes https://github.com/openshift/origin/issues/10404

replace cmdutil.ErrExit with kcmdutil.ErrExit

---

pkg/project/registry/projectrequest/delegated/delegated.go
pkg/quota/admission/clusterresourceoverride/admission.go

picking https://github.com/openshift/origin/pull/16845 to stage
@derekwaynecarr @smarterclayton @eparis @portante @jupierce

clusterresourceoverride: exempt known infra projects from enforcement

---

vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/reconciler/reconciler_test.go

Fixes https://github.com/openshift/origin/issues/16836

Backport reconciler flake fix

---

test/extended/templates/templateservicebroker_security.go

disable tsb extended testing on gce

---

pkg/oc/admin/project/new_project.go
test/integration/login_test.go
test/integration/project_test.go
test/util/server/server.go

Cherry pick of #16849 on stage.
#16849: Make admin project creation wait for SAR

Automated cherry pick of #16849

---

vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go
vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller_test.go

UPSTREAM: 50583: Make endpoints controller update based on semantic equality

---

vendor/github.com/google/cadvisor/container/docker/handler.go

stage pick for https://github.com/openshift/origin/pull/16931

UPSTREAM: google/cadvisor: 1770: Monitor diff directory for overlay2

---

test/extended/templates/templateinstance_security.go

fixes #16775 (hopefully).
@smarterclayton @bparees @enj

wait for group cache to avoid flake in templateinstance test

---

pkg/oc/bootstrap/docker/openshift/rbac.go
pkg/oc/bootstrap/docker/openshift/servicecatalog.go

Adds rules for the view role to have add,list,watch permissions on
serviceinstances and servicebindings.
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1496753

catalog: edit view role to have required rbac rules

---

pkg/api/serialization_test.go

enhance template fuzz testing

---

vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go
vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller_base.go
vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1501152
This is the same as #16927, just for master instead of stage.

[master] UPSTREAM: 49016: PV controller: resync informers manually

---

test/integration/oauth_token_endpoint_test.go

Add integration test for the request token endpoints

---

vendor/k8s.io/kubernetes/test/e2e/garbage_collector.go

Fixes #16878 #16838
Backport kubernetes/kubernetes#54308
We created too many pods

UPSTREAM: 54308: The garbage collector creates too many pods

---

test/integration/router/router_http_server.go

fix flake: Router test "address already in use"

---

pkg/network/node/iptables.go

The reorganization of getNodeIPTablesChains() for multi-CIDR support resulted in the OPENSHIFT-ADMIN-OUTPUT-RULES and OPENSHIFT-FIREWALL-FORWARD tables getting swapped such that OPENSHIFT-FIREWALL-FORWARD now accepts all packets before OPENSHIFT-ADMIN-OUTPUT-RULES gets a chance to reject them.
Rather than reverting the ordering of the chains in getNodeIPTablesChains(), I just made syncIPTablesRules() process them in reverse order, which (since it's using Prepend) means that now the chains end up in the same order as they appear in getNodeIPTablesChains(), which makes a little more sense anyway. (The relative ordering of the other two chains doesn't matter since neither of them shares a srcChain with any of the others.)
I also fixed the "don't create a rule pointing to …

Fix base iptables rule ordering to fix the OPENSHIFT-ADMIN-OUTPUT-RULES table

---

test/extended/builds/pipeline.go
test/extended/util/framework.go

better debug for https://github.com/openshift/origin/issues/16853
@openshift/devex

more pipeline bld ext tst dbg improvements

---

examples/image-streams/image-streams-centos7.json
examples/image-streams/image-streams-rhel7.json
pkg/oc/bootstrap/bindata.go
test/extended/testdata/bindata.go

This depends on the outcome of https://github.com/openshift/origin/issues/16755

Add provider annotations to image-streams

---

test/extended/networking/util.go

Attempting to debug #14385; the logs don't show anything suspicious so let's try to get more logs
@knobunc One thing I noticed is that the test is using the hybrid proxier, so if you have any ideas on possible failure modes with that (or additional debug commands that might be useful with it), let me know.

Try to collect some debug info if e2e service test fails

---

images/openldap/OWNERS
pkg/auth/OWNERS
pkg/authorization/OWNERS
pkg/cmd/OWNERS
pkg/oauth/OWNERS
pkg/security/OWNERS
pkg/serviceaccounts/OWNERS
pkg/user/OWNERS
test/OWNERS
test/testdata/OWNERS

As a courtesy so Bruno does not get tagged to review pull requests.
/assign @simo5
/kind bug

Remove abstractj from OWNERS

---

pkg/network/node/pod.go

Fix the check for "pod has HostPorts"

---

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go

xref https://github.com/kubernetes/kubernetes/pull/54593
fixes #17011

UPSTREAM: 54593: Removed containers are not always waiting

---

pkg/oc/cli/describe/describer.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1278683
Adds the "Limit" and "Limit/Request" columns seen when describing a
LimitRange to the "describe" output of projects.
**Before**
```
$ oc describe project myproject
...
Resource limits:
Name:           limits
Type            Resource        Min     Max     Default
----            --------        ---     ---     ---
Pod             cpu             200m    2       -
Pod             memory          6Mi     1Gi     -
Container       cpu             100m    2       300m
Container       memory          4Mi     1Gi     200Mi
```
**After**
```
$ oc describe project myproject
...
Resource limits:
Name:           limits
Type            Resource        Min     Max     Default Limit   Limit/Request
----            --------        ---     --- …
```

add Limit & Limit/Request columns

---

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go

xref https://github.com/openshift/origin/pull/17042
cc @jupierce

[stage] UPSTREAM: 54593: Removed containers are not always waiting

---

vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go

https://github.com/openshift/origin/pull/17051
@frobware @joelsmith @derekwaynecarr

[stage] UPSTREAM: 54597: kubelet: check for illegal container state transition

---

vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go

xref kubernetes/kubernetes#54597

UPSTREAM: 54597: kubelet: check for illegal container state transition

---

test/extended/builds/s2i_root.go
test/extended/util/cli.go

retry scc update in extended test on conflict

---

Godeps/Godeps.json
vendor/github.com/openshift/source-to-image/pkg/util/fs/fs.go

Include https://github.com/openshift/source-to-image/pull/820, assuming it passes tests.  Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1506173.

bump source-to-image

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/maxinflight.go

fixes https://bugzilla.redhat.com/show_bug.cgi?id=1506375

UPSTREAM: 48813: maxinflight handler should let panicrecovery handler call NewLogged

---

vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go

bug: 1506332
https://bugzilla.redhat.com/show_bug.cgi?id=1506332

UPSTREAM: 54700: Reduce node iptables logging in V(2)

---

vendor/github.com/google/cadvisor/container/common/fsHandler.go

https://github.com/google/cadvisor/pull/1785
xref https://bugzilla.redhat.com/show_bug.cgi?id=1498632#c8
pick to fixup log message

UPSTREAM: google/cadvisor: 1785: fix long du duration message

---

origin.spec

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1469034

Move master config ghosts to /etc/origin/master/

---

pkg/oc/bootstrap/docker/openshift/rbac.go

This simply adds patch for admin and edit roles.

catalog: add RBAC rules for serviceinstances

---

vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go
vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller_test.go

[stage] UPSTREAM: 54828: trigger endpoint update on pod deletion

---

vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go
vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller_test.go

UPSTREAM: 54828: trigger endpoint update on pod deletion

---

vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_sandbox.go

master PR:
https://github.com/openshift/origin/pull/17175

UPSTREAM: 55028: kubelet: dockershim: remove orphaned checkpoint files

---

pkg/oc/bootstrap/docker/openshift/rbac.go

Note that this is just a role without a binding. (#17158)

catalog: add cluster service broker admin role

---

pkg/templateservicebroker/servicebroker/provision.go
pkg/templateservicebroker/servicebroker/servicebroker.go

fixes https://github.com/openshift/origin/issues/17085
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1509022

introduce a configurable delay between creating resources to prevent spurious GC

---

pkg/cmd/server/origin/controller/config.go
pkg/image/controller/signature/container_image_downloader.go
pkg/image/controller/signature/signature_import_controller.go

fixes https://github.com/openshift/origin/issues/17172

limit retries of imagesignature import and don't log failures

---

pkg/cmd/util/clientcmd/factory.go
test/cmd/env.sh

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1509793
Adds support for updating environment variables on buildConfigs
that use the JenkinsPipeline strategy.
/kind bug
cc @openshift/cli-review @bparees

add support for JenkinsPipeline strategy env update

---

pkg/image/trigger/deploymentconfigs/deploymentconfigs.go

Add tombstone handling to deployment trigger controller. Previously the
controller would panic when handling a tombstone object during trigger
indexing.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1510172

Fix deployment trigger controller crash

---

examples/service-catalog/service-catalog.yaml
pkg/oc/bootstrap/bindata.go

* Adds the ability for the catalog controller service account to modify
clusterserviceclass and clusterserviceplan status
Bug 1499413

Add missing catalog service account roles

---

pkg/oc/admin/prune/images_test.go

Resolves #17223
Signed-off-by: Michal Minář <miminar@redhat.com>

unit: increase timeout for getting master version

---

pkg/network/node/metrics.go
pkg/network/node/vnids.go

sdn: add metric for "failed to find netid for namespace: XXXX in vnid map" errors

---

pkg/diagnostics/pod/dns.go

- IPv4 dns servers are preferred over IPv6 servers for addr resolution
- Fixes 'too many colons in addr' error
Fixes https://github.com/openshift/origin/issues/10656

Fix dns lookup in PodCheckDns diagnostic

---

pkg/build/registry/rest.go

fixes https://github.com/openshift/origin/issues/17266

retry build watch on error/expiration

---

pkg/cmd/server/bootstrappolicy/controller_policy.go
test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
test/testdata/bootstrappolicy/bootstrap_policy_file.yaml

fixes https://github.com/openshift/origin/issues/17260

fix up template instance controller permissions

---

vendor/k8s.io/kubernetes/pkg/kubelet/sysctl/runtime.go

Fix https://bugzilla.redhat.com/show_bug.cgi?id=1508781
@smarterclayton @mrunalp PTAL
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

UPSTREAM: 50390: Admit sysctls for other runtime.

---

pkg/oc/admin/node/evacuate.go
pkg/oc/admin/node/listpods.go
pkg/oc/admin/node/node_options.go
test/cmd/admin.sh

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1509661
cc @openshift/cli-review

include namespace in --list-pods for node output

---

pkg/oc/cli/describe/printer_test.go

This is a discussion from https://github.com/openshift/cucushift/pull/5558/files#r148792246
@akostadinov @juanvallejo ptal

TestPrintRoleBindingRestriction output check test enhance

---

test/extended/image_ecosystem/scl.go

should fix flakes like this one:
https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/277/testReport/junit/(root)/Extended/_image_ecosystem__Slow__openshift_images_should_be_SCL_enabled__returning_s2i_usage_when_running_the_image__openshift_ruby_20_centos7__should_print_the_usage__Suite_openshift_/

add toleration for slow logs in scl tests

---

pkg/oc/experimental/dockergc/dockergc.go

xref https://bugzilla.redhat.com/show_bug.cgi?id=1511852

check RepoTags len before accessing

---

examples/zookeeper/README.md

https://github.com/openshift/origin/issues/12620 probably covers updating this to use StatefulSets, but in the meantime a warning is needed.
@mfojtik @bparees

add warning to Zookeeper example

---

test/extended/router/metrics.go

Because we are using delegated auth, the server can allow anonymous
access, and so we can receive either a 401 or 403. Test for both.
@rajatchopra even for anonymous users we ask the master if the user has permission, so forbidden is correct now when this mode is on (admin could choose to grant that permission if they wanted).

Delegated auth for router metrics allows anonymous

---

pkg/generate/app/cmd/newapp.go
pkg/generate/app/cmd/newapp_test.go
pkg/generate/app/imageref.go
pkg/util/portutils/common.go
pkg/util/portutils/common_test.go

Cleaning up and de-duplicating port/protocol splitting and validation code

Cleaning up port/protocol split/validation code

---

pkg/network/node/node.go
pkg/network/node/sdn_controller.go

It's been few releases that we moved to CNI interfaces.
Previous release migrations should have done the pre CNI cleanup if needed.
So we no longer need this dead code.

Remove pre CNI docker cleanup code from openshift SDN

---

hack/import-restrictions.json
pkg/template/generated/listers/template/v1/template_expansion.go
pkg/templateservicebroker/openservicebroker/server/apiserver.go
pkg/templateservicebroker/servicebroker/bind.go
pkg/templateservicebroker/servicebroker/catalog.go
pkg/templateservicebroker/servicebroker/catalog_test.go
pkg/templateservicebroker/servicebroker/deprovision.go
pkg/templateservicebroker/servicebroker/lastoperation.go
pkg/templateservicebroker/servicebroker/provision.go
pkg/templateservicebroker/servicebroker/servicebroker.go
pkg/templateservicebroker/servicebroker/unbind.go
pkg/templateservicebroker/util/util.go

https://trello.com/c/LclZtOcc/1382-5-switch-template-service-broker-to-use-external-clients

tsb: use external clients

---

pkg/network/node/vnids.go

- Existing 1 sec timeout for WaitAndGetVNID() may not be sufficient
for loaded nodes (I might have chosen this value due to lack of enough info).
Now the timeout is bumped to 5 secs.
- WaitAndGetVNID() also queries the api server if needed (do not expect this
to happen often with the new timeout) to differentiate between these 2 cases:
(1) Genuine error: Namespace doesn't exist so netid won't be present
(2) Propagation issue: Namespace exists but watch NetNamespace event not
propagated to the node. May be insufficient timeout or event missed.
Newly added VnidNotFoundErrors metric will give more insights.

Bug 1509799 - Fix WaitAndGetVNID() in sdn node

---

hack/OWNERS
pkg/cmd/infra/router/OWNERS

'knbonuc' -> 'knobunc'
'rchopra' -> 'rajatchopra'

Fixed a typo in OWNERS (rajatchopra and knobunc were wrong)

---

hack/lib/constants.sh

Removing gitserver from build images

---

test/extended/image_ecosystem/scl.go

there's some lag time between the pod being reported and the log containing the expected output, this adds tolerance for that.

poll for log output in extended tests

---

examples/jenkins/pipeline/bluegreen-pipeline.yaml
examples/jenkins/pipeline/maven-pipeline.yaml
pkg/oc/bootstrap/bindata.go
test/extended/testdata/bindata.go

@liggitt @mfojtik the cherry-pick from https://github.com/openshift/origin/pull/17115/

interesting: fixup template data types

---

pkg/oc/bootstrap/docker/dockerhelper/helper.go

Fixes #17394
/test extended_clusterup

Normalize image ref before pulling in cluster up

---

vendor/k8s.io/kubernetes/pkg/kubelet/cadvisor/cadvisor_linux.go

master PR https://github.com/openshift/origin/pull/17106

UPSTREAM: 49885: Ignore UDP metrics in kubelet [3.7]

---

examples/storage-examples/OWNERS
pkg/diagnostics/OWNERS
pkg/dns/OWNERS
pkg/network/OWNERS
pkg/proxy/OWNERS
pkg/route/OWNERS
test/old-start-configs/OWNERS
tools/genman/OWNERS

Remove soltysh from OWNERS

---

pkg/cmd/server/start/bootstrap_node.go

Enable cert rotation for node bootstrap

---

vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory_object_mapping.go

UPSTREAM: 56045: Fix getting logs from daemonset

---

vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go

UPSTREAM: 55796: Correct ConstructVolumeSpec()

---

hack/lib/constants.sh

@smarterclayton noticed this was double building.  I wonder if the fix is this easy.

stop double building hyperkube

---

vendor/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/BUILD
vendor/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go
vendor/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1496256
There are two upstream commits here, 53135 was already merged to 3.3 - 3.7, 53989 fixes performance regression that was discovered after merge to 3.7 and earlier.

Fix predicate counting

---

vendor/k8s.io/kubernetes/pkg/apis/extensions/validation/validation.go
vendor/k8s.io/kubernetes/pkg/apis/networking/validation/validation.go
vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go

fixes https://bugzilla.redhat.com/show_bug.cgi?id=1516228
This updates GC to give us error messages and updates the network policy validation to allow GC-ing
@jwforres fyi

ensure that network policy can be GC'd

---

examples/prometheus/prometheus.yaml
pkg/oc/bootstrap/bindata.go
test/extended/prometheus/prometheus.go
test/extended/testdata/bindata.go

Fixes a number of crash / data loss issues.
/hold

Update prometheus to 2.0.0 GA

---

pkg/image/controller/trigger/image_trigger_controller_test.go

Image trigger test was mutating the wrong object

---

pkg/apps/OWNERS
pkg/cmd/infra/deployer/OWNERS
pkg/controller/OWNERS
test/OWNERS

@mfojtik getting ready for upcoming PTOs :)

Add tnozicka to deployments related OWNERS

---

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_blobDiskController.go
vendor/k8s.io/kubernetes/pkg/volume/azure_dd/azure_common.go
vendor/k8s.io/kubernetes/pkg/volume/azure_dd/azure_mounter.go

fix https://bugzilla.redhat.com/show_bug.cgi?id=1506708 and https://bugzilla.redhat.com/show_bug.cgi?id=1513859

upstream azure fixes

---

vendor/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go

fixes https://github.com/openshift/origin/issues/17558

UPSTREAM: docker/distribution: 2140: Add 'ca-central-1' region for registry S3 storage driver

---

pkg/build/registry/buildconfiginstantiate/rest.go

fixes https://github.com/openshift/origin/issues/15215

don't block on stdout during binary build attach

---

test/extended/security/supplemental_groups.go

Resolve:
Error from server (Conflict): Operation cannot be fulfilled on securitycontextconstraints.security.openshift.io \"anyuid\": the object has been modified; please apply your changes to the latest version and try again
Fixes https://github.com/openshift/origin/issues/17359.

Address oc adm conflict.

---

pkg/auth/oauth/external/github/github.go

When configured to use the GitHubIdentityProvider, the user endpoint was previously used as the sole source for a user's email.  This fails if the user has no public email set.  Now we additionally query the user email endpoint if needed.  Since we already request the user:email scope, this requires no additional permissions from the user.
---
Fixes #17658
/assign @simo5

Get email via GitHub API if user has no public email

---

vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go
vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/security_context.go

Cherry pick of #17512 into `release-3.6` branch.
PTAL @liggitt @simo5

UPSTREAM: 56503: MustRunAsNonRoot should reject a pod if it has non-numeric USER

---

test/extended/util/test.go

/assign mfojtik
/assign liggitt
/assign smarterclayton

disable metric exposure and single flaky deployment tests

---

hack/test-end-to-end-docker.sh

Revert "Drop changing journald limits, now that ansible owns that piece"

---

test/extended/prometheus/prometheus_builds.go
test/extended/util/framework.go

debug for https://github.com/openshift/origin/issues/17694
@openshift/sig-developer-experience fyi / ptal

add debug for build prometheus extended test failures

---

pkg/oc/admin/groups/changemembership.go
pkg/oc/admin/policy/modify_roles.go

Fixes https://github.com/openshift/origin/issues/17615
Will add tests
cc @openshift/cli-review

add affirmative output `oc adm groups`

---

pkg/cmd/server/kubernetes/node/node.go
pkg/cmd/server/kubernetes/node/node_config_test.go

These came out of non-blocking comments on the rebase

rebase comments on node wiring

---

hack/dind-cluster.sh

- 'hack/dind-cluster.sh start' now takes optional param '-a' which creates
'eth1' interface on all nodes in the cluster.
Useful for https://trello.com/c/sCNKKYCz

dind: Added support for additional network interface on all the nodes

---

glide.yaml
pkg/api/compatibility_test.go
vendor/k8s.io/kubernetes/pkg/api/serialization_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/fuzzer/fuzzer.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/group_version_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1525162

Restore ugorji json decoding with type coercion

---

test/extended/imageapis/quota_admission.go

Workaround for broken quota admission test

---

test/extended/cni_vendor_test.sh

@openshift/networking 
Please review and mark this for merge if it looks good. Thanks.

Fix the regexp for networking test match

---

cmd/OWNERS
contrib/completions/OWNERS
hack/clibyexample/OWNERS
hack/lib/OWNERS
pkg/assets/OWNERS
pkg/cmd/OWNERS
pkg/config/OWNERS
pkg/oc/OWNERS
pkg/oc/admin/diagnostics/OWNERS
pkg/oc/admin/router/OWNERS
test/cmd/OWNERS
tools/clicheck/OWNERS
tools/genman/OWNERS

Removes me from lists of reviewers and approvers.

fabiano no longer a thing

---

contrib/completions/OWNERS
pkg/config/OWNERS
pkg/oc/OWNERS
test/cmd/OWNERS

Followup to https://github.com/openshift/origin/pull/17886

Add soltysh to cli-related stuff as reviewer and approver

---

images/builder/docker/custom-docker-builder/build.sh

add documentation to custom builder shell script

---

test/extended/prometheus/prometheus_builds.go
test/extended/util/framework.go

dump logs from all containers in pod in DumpPodLogs

---

pkg/build/builder/util_linux.go
pkg/build/controller/strategy/docker_test.go
pkg/build/controller/strategy/sti_test.go
pkg/build/controller/strategy/util.go

fixes https://github.com/openshift/ose/issues/973

remove dependency on crio constant for socket path

---

test/extended/clusterup.sh

disable cluster up 3.7 test for now

---

vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go
vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/operations.go
vendor/k8s.io/kubernetes/test/integration/garbagecollector/cluster_scoped_owner_test.go
vendor/k8s.io/kubernetes/test/integration/garbagecollector/garbage_collector_test.go

fixes https://bugzilla.redhat.com/show_bug.cgi?id=1525699

UPSTREAM: 57211: Process cluster-scoped owners correctly

---

cmd/oadm/main.go
hack/lib/constants.sh
origin.spec

@deads2k this will provide 'oadm' command for some time with fat deprecation warning. Not sure if I have to plumb the hack/ scripts more or this should be enough.

re-add oadm binary as alias for oc adm

---

pkg/cmd/server/origin/controller/interfaces.go
pkg/cmd/server/start/controllers.go
pkg/cmd/server/start/start_kube_controller_manager.go
pkg/cmd/server/start/start_master.go
vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go

3.8 pick of https://github.com/openshift/origin/pull/17859

 wait for kube controllers to be ready before starting informers

---

pkg/oc/generate/app/cmd/newapp.go

This just looked like it could be a little bit clearer.

newapp: boring code improvements

---

pkg/oc/cli/cmd/set/triggers.go
test/cmd/triggers.sh

bug 1532142
https://bugzilla.redhat.com/show_bug.cgi?id=1532142

make set triggers tolerate new secretReference format

---

pkg/oc/cli/describe/helpers.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1518502

Corrects oc tag alias shows importing latest image forever

---

pkg/oc/bootstrap/docker/up.go

Fix logic to determine whether nsenter mounter should be used

---

vendor/k8s.io/kubernetes/pkg/controller/statefulset/stateful_set.go
vendor/k8s.io/kubernetes/pkg/controller/statefulset/stateful_set_control.go
vendor/k8s.io/kubernetes/pkg/controller/statefulset/stateful_set_control_test.go
vendor/k8s.io/kubernetes/pkg/controller/statefulset/stateful_set_test.go

UPSTREAM: 55316: Make StatefulSet report an event when recreating failed pod

---

test/extended/builds/forcepull.go

fixes https://github.com/openshift/origin/issues/17596
(I don't really consider this a proper fix, but apparently oc adm isn't going to get the proper fix so this is as close as we're getting).

avoid conflict updating custom build role

---

pkg/oc/bootstrap/docker/dockerhelper/helper.go

Fixes oc cluster fails to abort when it first fails to pull an image

---

images/node/system-container/service.template

this is what the openshift-ansible template file has for the
containerized version.

node, syscontainer: drop EnvironmentFile=$NAME-dep

---

Godeps/Godeps.json

fixes https://bugzilla.redhat.com/show_bug.cgi?id=1533433

update Godep file for 1.8.5 rebase

---

pkg/apps/graph/edges.go

Fixes: https://github.com/openshift/origin/issues/17977
This change is weird as you should not be able to create a DC without template, but I haven't looked deeply on how the graph is constructed and whether this case can happen. We protect from nil template in other function.

cli: fix nil pointer panic in dc status

---

vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go

Thanks to @vikaschoudhary16 for doing all the legwork upstream on this!
Fixes https://github.com/openshift/origin/issues/16246
https://github.com/opencontainers/runc/pull/1683
https://github.com/google/cadvisor/pull/1861
https://github.com/kubernetes/kubernetes/pull/58117

UPSTREAM: opencontainers/runc: 1683: Fix race against systemd

---

pkg/image/admission/imagepolicy/imagepolicy.go
pkg/image/admission/imagepolicy/imagepolicy_test.go

the ImagePolicy admission plugin must ensure the image spec on the incoming object still passes policy rules during the validation phase, in case a later admission plugin messed with a resolved/approved pull spec later in the mutation phase.
changes or policy failures result in rejection

Implement Admit and Validate stages for image policy admission

---

vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go

UPSTREAM: 57993: Add volumemetrics for glusterfs plugin

---

pkg/assets/apiserver/asset_apiserver.go
pkg/cmd/server/origin/asset_apiserver_adapter.go
pkg/cmd/server/origin/master.go
pkg/cmd/server/start/start_master.go

fixes https://bugzilla.redhat.com/show_bug.cgi?id=1533564
3.8 version of https://github.com/openshift/origin/pull/18076
@spadgett @jwforres 
/assign mfojtik

plumb through the clusterresourceoverride settings

---

pkg/project/OWNERS

/assign @eparis @simo5 
cc @deads2k @liggitt @mfojtik

Add enj to approvers in pkg/project/OWNERS

---

pkg/network/node/ovscontroller.go

Noticed while trying to fix rhbz 1527642: oc.tunMAC currently only gets set from SetupOVS(), so if you restart OpenShift and SDN setup gets skipped, then tunMAC will be unset, and so new auto-egress-ip rules will fail.
The switch from using netlink to use ovs-vsctl to fetch the MAC is because an earlier version of the patch broke the hack in ovscontroller_test.go that manually sets tunMAC, and made it so that SetupOVS would always have to read tunMAC from tun0. But calling netlink wouldn't work from ovscontroller_test, so I rewrote it to use ovs-vsctl to get the MAC instead, since that was mockable. But then I ended up rewriting things so that it was possible for ovscontroller_test to still just manually override it anyway. But I liked the ovs-vsctl-rather-than-netlink approach because it …

Make sure oc.tunMAC gets set even if AlreadySetUp()

---

test/extended/builds/pipeline.go

@openshift/sig-developer-experience 
step 5 (last step) from https://github.com/openshift/jenkins-client-plugin/pull/107

additional test for jenkins client plugin

---

.gitattributes

This is taken from https://github.com/kubernetes/kubernetes/pull/54766 with some additional changes for origin.
@liggitt ptal

Make github hide generated files in diffs

---

vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
vendor/k8s.io/kubernetes/pkg/volume/util.go

partly fixes https://bugzilla.redhat.com/show_bug.cgi?id=1532531
cc @humblec @rootfs

UPSTREAM: 56581: Fix volume units used by glusterfs

---

images/dind/Dockerfile

dind is used for development and I expect basic debugging tools to be present by default.

dind: Bundle basic network debugging tools

---

vendor/k8s.io/kubernetes/pkg/volume/configmap/configmap_test.go
vendor/k8s.io/kubernetes/pkg/volume/projected/projected_test.go
vendor/k8s.io/kubernetes/pkg/volume/secret/secret_test.go
vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer.go
vendor/k8s.io/kubernetes/pkg/volume/util/atomic_writer_test.go

See #18165 for background info.

[3.7] UPSTREAM: 57422: Rework method of updating atomic-updated data volumes

---

pkg/authorization/authorizer/scope/authorizer.go
pkg/authorization/authorizer/scope/authorizer_test.go
pkg/cmd/server/origin/authorizer.go

Now that we have an authoritative deny, it makes sense to use it for scopes, since scopes are inherently limiting and should result in rejection.
/assign simo5
/assign enj

wire scopes with authoritative deny

---

images/base/Dockerfile
images/base/Dockerfile.centos7
images/base/Dockerfile.rhel7

These are identical, and should be easily kept in sync.
@kargakis can you give this a once over?  I couldn't review these differences when I was making an unrelated change. I manually confirmed they are the same.

Make yum packages comparable across base images

---

pkg/oc/OWNERS

This is for all the security related CLI commands such as login, policy, project, etc.
/assign @eparis @simo5 @soltysh

Add enj to reviewers/approvers in pkg/oc/OWNERS

---

test/extended/prometheus/prometheus.go

The service account secret may take a small amount of time to create

Prevent races across prometheus installs

---

hack/lib/constants.sh
hack/lib/util/golang.sh
hack/update-deps.sh

Same thing as in https://github.com/openshift/client-go/pull/19
/assign @deads2k @stevekuznetsov

Check glide version

---

vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory_client_access.go

Fixes #12672
@juanvallejo ptal

UPSTREAM: 57742: Allow kubectl set image/env on a cronjob

---

install/origin-web-console/console-config.yaml
pkg/oc/bootstrap/bindata.go
test/extended/testdata/bindata.go

See https://github.com/openshift/api/pull/32
/assign @jwforres 
/cc @deads2k

Add clusterResourceOverridesEnabled flag to console config template

---

pkg/util/ovs/OWNERS

We might as well own this.
@knobunc @eparis @openshift/networking

ovs: add OWNERS file

---

tools/depcheck/pkg/cmd/trace/pkg.go
tools/depcheck/pkg/cmd/trace/pkg_test.go
tools/depcheck/pkg/graph/graph.go

add graph-building pieces to tools/depcheck

---

pkg/oc/bootstrap/docker/up.go
test/extended/clusterup.sh

fixes https://github.com/openshift/origin/issues/18230

don't install jenkins ephemeral template in cluster up

---

pkg/oc/admin/migrate/authorization/authorization.go
pkg/oc/admin/migrate/migrator.go
pkg/oc/cli/cmd/create/policy_binding.go
pkg/oc/cli/util/clientcmd/gating.go

Cherry pick of #18005 on release-3.8.
#18005: Fix issues with oc adm migrate authorization

Automated cherry pick of #18005 on release-3.8

---

test/extended/router/metrics.go

The metrics test flaked out because the router was still deploying when the e2e test ran (it was the first test). We don't block provision exit on router deploying yet.

Retry until router deploys in e2e test for metrics

---

test/integration/oauth_serviceaccount_client_events_test.go

Add integration tests for SA OAuth events

---

pkg/build/apis/build/types.go
pkg/build/controller/build/build_controller.go
pkg/build/controller/build/build_controller_test.go

fixes https://bugzilla.redhat.com/show_bug.cgi?id=1333030

wait for default service account secrets before running build

---

install/origin-web-console/console-template.yaml
pkg/oc/bootstrap/bindata.go
test/extended/testdata/bindata.go

/assign @jwforres 
/cc @derekwaynecarr

Add resource requests to console template

---

pkg/image/controller/imagestream_controller.go
pkg/image/controller/imagestream_controller_test.go

https://bugzilla.redhat.com/show_bug.cgi?id=1515060

only run scheduled image import on tags marked scheduled

---

install/origin-web-console/console-template.yaml
pkg/oc/bootstrap/bindata.go
test/extended/testdata/bindata.go

Add prometheus annotations to webconsole service

---

pkg/oc/cli/secrets/dockercfg.go
test/cmd/secrets.sh

It looks like I missed one more create secret thing. Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1531511

Fix oc secrets new-dockercfg to create secret identical like oc create secret

---

origin.spec

fix #18236 and BZ 1536362
cifs-utils and dependency add 19MB 
@stevekuznetsov

add cifs-utils to origin rpm

---

tools/depcheck/pkg/cmd/trace/filter.go
tools/depcheck/pkg/cmd/trace/filter_test.go
tools/depcheck/pkg/cmd/trace/pkg.go
tools/depcheck/pkg/graph/graph.go

add vendor packages filter

---

pkg/oc/cli/cmd/set/triggers.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1539575

cli: use the image namespace for image change trigger

---

pkg/oc/cli/describe/printer.go

fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1539415

cli: truncate users in get clusterrolebindings

---

pkg/image/admission/imagepolicy/accept.go
pkg/image/admission/imagepolicy/imagepolicy.go
pkg/image/admission/imagepolicy/rules/accept.go
pkg/image/admission/imagepolicy/rules/rules.go

Add tracing to help chase down bug reports like https://bugzilla.redhat.com/show_bug.cgi?id=1516496

delete unnecessary skiponresolution logic and add tracing to image policy

---

test/extended/image_ecosystem/postgresql_replica.go

the psql tests are among our worst flakes, let's just test the most recent version.

drop old postgres replica tests

---

examples/statefulsets/zookeeper/README.md

Fix the wrong check script for zookeeper

---

examples/helm/tiller-template.yaml

Fixes #18350 
Signed-off-by: Pavol Loffay <ploffay@redhat.com>

Add helm version to tiller template

---

vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go

UPSTREAM: 56315:  Record volumeID in GlusterFS PV spec
UPSTREAM: 56823:  Add volID based delete() and resize() if volID is available in pv spec
UPSTREAM: 57516:  Add custom volume name based on SC parameter
UPSTREAM: 58513:  Add Namespace to glusterfs custom volume names
UPSTREAM: 58626:  Use correct pv annotation to fetch volume ID

Add custom volume name support for GlusterFS PVs

---

test/extended/deployments/deployments.go

fixes https://github.com/openshift/origin/issues/18366

Fix flake in DC extended test

---

pkg/oc/bootstrap/docker/up.go

I have been troubleshooting couple openshift installations done using `oc cluster up` recently and found one common pattern. MacOS users who used `oc cluster up` for the first time almost always experienced problems with reaching running cluster.  Example:
```
curl 127.0.0.1:8443
curl: (7) Failed connect to 127.0.0.1:8442; Connection refused
```
Problem related with missing or improperly installed `socat` command.
Following [documentation](https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#macos-with-docker-for-mac) is often not enough. Users who install this command using brew may miss some additional libraries and this is really hard to debug and track cause of the issue when looking into logs. Example output:
```
> socat
dyld: Library not loaded: …
```

Display warning when socat cmd is missing

---

hack/push-release.sh

Push :vX.Y and :vX.Y.Z instead of just :latest

By default, push images as multiple tags beyond :latest

---

examples/jenkins/pipeline/nodejs-sample-pipeline.yaml
pkg/oc/bootstrap/bindata.go
test/extended/testdata/bindata.go

@openshift/sig-developer-experience fyi / ptal
one of our upstream jenkins users discovered that this example did not line up with https://github.com/openshift/jenkins-client-plugin#overview

fix nesting of pipeline and openshift.withCluster directives

---

pkg/build/generator/generator_test.go
pkg/build/registry/buildconfig/webhook.go
pkg/build/registry/buildconfig/webhook_test.go
pkg/build/webhook/webhook.go

fix part of https://github.com/openshift/origin/issues/17496

mask webhook secret value in builds

---

test/extended/image_ecosystem/s2i_perl.go
test/extended/image_ecosystem/s2i_python.go
test/extended/image_ecosystem/s2i_ruby.go
test/extended/testdata/bindata.go
test/extended/testdata/image_ecosystem/perl-hotdeploy/index.pl
test/extended/testdata/image_ecosystem/perl-hotdeploy/lib/My/Test.pm
test/extended/testdata/image_ecosystem/perl-hotdeploy/perl.json

fixes https://github.com/openshift/origin/issues/16229

only run one httpd instance in perl hot deploy test

---

docs/proposals/instrumentation-of-services.md

Observability of the infrastructure and reporting to operations is becoming critical.  This lays out the current best practices.

Service monitoring best practices for infrastructure

---

pkg/apps/controller/deployer/deployer_controller.go
pkg/apps/controller/deployer/deployer_controller_test.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1535375
@deads2k @smarterclayton this will allow injecting reasonable sized vars into deployer, we can start deprecation process for `OPENSHIFT_CA_DATA` in 3.10?

apps: do not inject oversized env vars into deployer pod

---

examples/prometheus/README.md

this patch will let the node exporter pods to run on any node
by any label.
In continuing to #17645 #17639

node selector annotation for any label.

---

pkg/oc/graph/kubegraph/analysis/podspec.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1542325
I think it is safe to assume that any Pod with ownerReference.Controller=true is not controlled by a human an therefore we should not suggests users to augment them with probes.

cli: do not suggest liveness probes for controller owned pods

---

pkg/build/generator/generator.go
test/cmd/builds.sh

bug 1541914
https://bugzilla.redhat.com/show_bug.cgi?id=1541914

check all buildrequest options for validity against build type

---

hack/build-local-images.py

locally built images don't update hyperkube.
/assign @stevekuznetsov

add hyperkube to locally built images

---

hack/lib/build/binaries.sh

Perform golang check in a unified way

---

pkg/oc/cli/describe/printer.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1539415

cli: truncate groups in get clusterrolebindings

---

pkg/cmd/server/admin/create_bootstrappolicy_file.go
pkg/cmd/server/admin/create_nodeconfig_test.go
pkg/oc/admin/diagnostics/diagnostics/systemd/systemd.go
pkg/oc/admin/node/evacuate.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1542332

cli: remove traces of openshift admin command

---

pkg/oc/bootstrap/docker/printer.go
pkg/oc/bootstrap/docker/up.go

Annoying little oversight.  I need to see my failures.

show error when cluster up fails

---

pkg/oc/cli/cmd/set/volume.go
pkg/oc/cli/cmd/set/volume_test.go

Fixes `oc set volume` such that, if user is adding a new mounted volume from same PVC, rather than creating new `pod.Spec.Volumes` - we reuse existing one.
Partly fixes - https://bugzilla.redhat.com/show_bug.cgi?id=1527685

Fix volume code to consider existing pvc

---

pkg/oc/cli/cmd/importimage.go
pkg/oc/cli/cmd/importimage_test.go

Fixes https://github.com/openshift/origin/issues/14631

Allow import image into empty imagestream

---

pkg/oc/cli/cmd/login/login.go
pkg/oc/cli/cmd/login/loginoptions.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1540049
Improves error message seen on login when incorrect credentials are provided
cc @soltysh

update unauthorized err message - oc login

---

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go

Fixes #18173
xref https://github.com/kubernetes/kubernetes/pull/59297

UPSTREAM: 59297: Improve error returned when fetching container logs during pod termination

---

test/extended/builds/pipeline.go

add declarative pipeline example to build extended test suite

---

hack/build-local-images.py

build-local-images was missing oc update too.

update oc in build local images

---

pkg/oc/cli/describe/projectstatus.go
pkg/oc/graph/kubegraph/nodes/nodes.go

Fixing: https://bugzilla.redhat.com/show_bug.cgi?id=1540560

cli: fix status for standalone deployment

---

vendor/k8s.io/kubernetes/pkg/kubelet/config/config.go
vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/cache/actual_state_of_world.go
vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/cache/actual_state_of_world_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/cache/desired_state_of_world.go
vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/cache/desired_state_of_world_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go
vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler_test.go
vendor/k8s.io/kubernetes/pkg/util/mount/mount.go
vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_executor.go
vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go

fix https://bugzilla.redhat.com/show_bug.cgi?id=1508578
Note, e2e test is not ported, because the dependency on kubernetes #56593
@childsb @gnufied @jsafrane

UPSTREAM: 58177: Redesign and implement volume reconstruction work

---

test/extended/cluster/cl.go
test/extended/cluster/utils.go

Small change to allow us to create duplicate templates per project.

Multiple template creation for Cluster Loader

---

pkg/oc/admin/prune/imageprune/prune.go

Fixes [BZ#1543511](https://bugzilla.redhat.com/show_bug.cgi?id=1543511)

Make image pruner tolerate since to empty docker image reference

---

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go

https://github.com/kubernetes/kubernetes/pull/59767
xref https://bugzilla.redhat.com/show_bug.cgi?id=1534492
@derekwaynecarr @smarterclayton @tnozicka

UPSTREAM: 59767: kubelet: check for illegal phase transition

---

publishing-rules.yaml

add publishing rules

---

pkg/oc/bootstrap/docker/up.go

There are many "tasks" added the Complete method which actually mutate struct state and effectively complete the object.  This updates the method to simply call the checks and struct completion directly instead of adding them to a list to later be run.
This allows the values to be safely used after calling complete like other CLI commands.
part of cluster up pull.

complete the cluster up struct in the Complete method

---

HACKING.md

fix typo in HACKING.md

---

examples/image-streams/image-streams-centos7.json
pkg/oc/bootstrap/bindata.go
test/extended/testdata/bindata.go

Fixes https://github.com/openshift/origin/issues/18330
These images are built from: https://github.com/redhat-developer/s2i-dotnetcore/.
@bparees PTAL

Add .NET Core CentOS ImageStreams

---

examples/grafana/README.md
examples/grafana/setup-grafana.sh

updates:
- automate the oauth configuration phase.
- deploy node exporter dashboard.
- use bash switches.
- update readme fonts and how to.

Grafna deployment update.

---

publishing-kube-rules.yaml

@sttts @deads2k FYI.
I'm going to fetch the rules in openshift/kubernetes bot directly from master branch.

add publishing rules for openshift/kubernetes repo

---

pkg/cmd/OWNERS

- Mainly to review/approve network related changes in pkg/cmd

Added dcbw to pkg/cmd/OWNERS

---

pkg/apps/controller/deploymentconfig/deploymentconfig_controller.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1546854

Fix panic in error printing in DC controller

---

pkg/build/util/util.go
test/cmd/newapp.sh
test/testdata/invalid-build-strategy.yaml

Fixes new-app segmentation fault on invalid build strategy

---

pkg/oauthserver/oauth/external/handler.go

Limit logging to provider name

---

tools/depcheck/pkg/cmd/cmd.go
tools/depcheck/pkg/graph/filter.go
tools/depcheck/pkg/graph/filter_test.go
tools/depcheck/pkg/graph/graph.go
tools/depcheck/pkg/graph/graph_test.go
tools/depcheck/pkg/graph/pkg.go
tools/depcheck/pkg/graph/pkg_test.go

Prerequisite to https://github.com/openshift/origin/pull/18466
cc @deads2k

add more graph methods

---

docs/man/OWNERS

I can already approve CLI changes so I should be able to approve the generated docs as well.

Add enj to generated man page OWNERS

---

pkg/image/controller/signature/signature_import_controller.go

https://bugzilla.redhat.com/show_bug.cgi?id=1543122

Skip managed images when importing signatures

---

pkg/oc/cli/cmd/set/volume.go
test/cmd/volumes.sh

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1541177
cc @soltysh

add configmap volume description

---

pkg/project/apis/project/validation/validation_test.go

This is the Unit test for the test case and it's [an internal link.](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-12128)
@deads2k @juanvallejo
Could you help to review, please? Thanks!

Add an error text check for project validation

---

vendor/k8s.io/kubernetes/pkg/kubelet/BUILD
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
vendor/k8s.io/kubernetes/pkg/kubelet/metrics/BUILD
vendor/k8s.io/kubernetes/pkg/kubelet/metrics/collectors/BUILD
vendor/k8s.io/kubernetes/pkg/kubelet/metrics/collectors/helper_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/metrics/collectors/volume_stats.go
vendor/k8s.io/kubernetes/pkg/kubelet/metrics/collectors/volume_stats_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/metrics/metrics.go
vendor/k8s.io/kubernetes/pkg/kubelet/server/stats/BUILD
vendor/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1542135

UPSTREAM: 59170: Fix kubelet PVC stale metrics

---

pkg/image/trigger/deploymentconfigs/deploymentconfigs.go

Fix initContainer name lookup for ImageChange trigger

---

test/extended/images/hardprune.go
test/extended/images/prune.go

* Migrate from the DeploymentConfigs to `oc rollout ...`.
* Fix #18384.

Wipe off registry cache

---

pkg/cmd/server/bootstrappolicy/controller_policy.go
test/extended/builds/build_pruning.go
test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
test/testdata/bootstrappolicy/bootstrap_policy_file.yaml

https://bugzilla.redhat.com/show_bug.cgi?id=1549832

Fixes: cannot prune builds on buildConfig change

---

test/extended/builds/pipeline.go

new test to validate recent bug fix in sync plugin

add ext test for pipeline bc deletion behavior

---

vendor/k8s.io/kubernetes/pkg/kubelet/images/image_gc_manager.go

https://github.com/kubernetes/kubernetes/pull/60289

UPSTREAM: 60289: fix freespace for image GC

---

pkg/network/master/subnets.go

This was introduced in https://github.com/openshift/origin/pull/16766

Fix handleDeleteSubnet() to release network from subnet allocator

---

vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go

master PR https://github.com/openshift/origin/pull/18791
kubernetes/kubernetes#54530
fixes #17595
xref https://bugzilla.redhat.com/show_bug.cgi?id=1534492
@tnozicka @smarterclayton @derekwaynecarr

[3.9] UPSTREAM: 54530: api: validate container phase transitions

---

contrib/completions/OWNERS

This should be the last piece I need to actually approve CLI changes.

Add enj to completions OWNERS

---

cmd/hypershift/main.go
hack/build-local-images.py
hack/lib/constants.sh
origin.spec
pkg/cmd/openshift-apiserver/cmd.go
pkg/cmd/openshift-apiserver/server.go
pkg/cmd/openshift-kube-apiserver/cmd.go
pkg/cmd/openshift-kube-apiserver/server.go
pkg/cmd/server/origin/aggregator.go
pkg/cmd/server/origin/handlers.go
pkg/cmd/server/origin/informers.go
pkg/cmd/server/origin/master.go
pkg/cmd/server/origin/master_config.go
pkg/cmd/server/origin/openshift_apiserver.go
pkg/cmd/server/origin/profiler.go
pkg/cmd/server/start/controllers.go
pkg/cmd/server/start/start_allinone.go
pkg/cmd/server/start/start_api.go
pkg/cmd/server/start/start_controllers.go
pkg/cmd/server/start/start_etcd.go
pkg/cmd/server/start/start_master.go
pkg/cmd/server/start/start_node.go
pkg/oauthserver/oauthserver/oauth_apiserver.go
test/integration/buildcontroller_test.go
test/integration/master_routes_test.go

Adds commands for kube-apiserver and openshift-apiserver to hypershift.
@openshift/sig-master @smarterclayton fyi

add hypershift kube-apiserver and openshift-apiserver

---

hack/lib/util/golang.sh

Fix golang check so that it performs arithemtic comparison

---

examples/grafana/setup-grafana.sh

the following script uses prometheus namespace on the fly (if not specified by the user).
we should use that namespace accordingly when generate the payload.

Grab the sa token per namespace.

---

hack/import-restrictions.json
pkg/cmd/server/origin/oauth_apiserver_adapter.go
pkg/cmd/util/net.go
pkg/oauth/apiserver/apiserver.go
pkg/oauthserver/oauthserver/auth.go
pkg/oauthserver/oauthserver/oauth_apiserver.go
pkg/oauthserver/oauthserver/oauth_apiserver_test.go
pkg/oc/bootstrap/docker/openshift/helper.go
pkg/serviceaccounts/oauthclient/oauthclientregistry.go
pkg/serviceaccounts/oauthclient/oauthclientregistry_test.go

clips internal route client and cmd/util from oauthserver

clip more dependencies from oauthserver

---

pkg/oc/cli/cmd/newapp_test.go

Add negative checking for new-app unit-test, please have a review, thanks！
@mfojtik  @coreydaley  could you have a  look?

add negative checking for new-app

---

test/cmd/etcdhelper.sh
tools/etcdhelper/README.md
tools/etcdhelper/etcdhelper.go

Etcdhelper improvements

---

pkg/oc/cli/describe/projectstatus.go
pkg/oc/graph/genericgraph/graphview/service_group.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1540560#c10

nest daemonsets under their services

---

test/extended/cluster/OWNERS

Add myself to the OWNERS file.

Add OWNERS for cluster loader

---

pkg/build/controller/build/defaults/defaults.go
pkg/build/controller/build/defaults/defaults_test.go

apply build defaults to init containers

---

images/dind/master/ovn-kubernetes-master.sh
images/dind/node/ovn-kubernetes-node.sh

Update CLI options and config file format for
https://github.com/openvswitch/ovn-kubernetes/pull/228
@pecameron @rajatchopra @openshift/networking

dind: update for latest ovn-kubernetes config changes

---

pkg/oc/bootstrap/clusterup/kubelet/run_kubelet.go
pkg/oc/bootstrap/docker/dockerhelper/helper.go
pkg/oc/bootstrap/docker/host/host.go
pkg/oc/bootstrap/docker/openshift/helper.go
pkg/oc/bootstrap/docker/up.go

@deads2k fixes one of the side effects, will continue to remove them all. also fixes printing the container id.

bootstrap: minor cluster up fixes (part 2)

---

install/openshift-controller-manager/install.yaml
pkg/oc/bootstrap/bindata.go
pkg/oc/bootstrap/clusterup/kubeapiserver/config.go
pkg/oc/bootstrap/clusterup/kubeapiserver/openshift_controller.go
pkg/oc/bootstrap/docker/run_self_hosted.go
test/extended/testdata/bindata.go

Updates `oc cluster up` to use the `hypershift openshift-controller-manager` instead of `openshift start`.

use pure openshift controllers

---

pkg/templateservicebroker/servicebroker/unbind.go

bug 1554141
https://bugzilla.redhat.com/show_bug.cgi?id=1554141

require templateinstance delete, not update, on unbind

---

pkg/apps/registry/deployconfig/etcd/etcd.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1544496
Hotfix before https://github.com/openshift/origin/pull/18640
/cc @mfojtik @liggitt @DirectXMan12

Fix DC selectors for autoscaling

---

hack/lib/log/output.sh

Should help with, among other things, knowing which part of the Docker registry log you need to look at for failed pushes.

Add timestamps to bash log output

---

test/extended/networking/multicast.go
test/extended/networking/util.go

Reverts openshift/origin#18978

Revert "Fix multicast test to run under ovs-networkpolicy plugin"

---

test/extended/router/metrics.go

Now that the PR has merged and router images contain the updated code

Enable router metrics preservation test

---

test/extended/builds/pipeline.go
test/extended/idling/idling.go
test/extended/image_ecosystem/helper.go
test/extended/image_ecosystem/mongodb_replica_statefulset.go
test/extended/image_ecosystem/mysql_replica.go
test/extended/image_ecosystem/postgresql_replica.go
test/extended/util/endpoints.go
test/extended/util/framework.go
test/extended/util/nfs.go
test/extended/util/pods.go
test/extended/util/volumes.go

Depends on https://github.com/openshift/jenkins-sync-plugin/pull/199
Depends on https://github.com/openshift/openshift-ansible/pull/7517

Tests for delete job runs when associated builds are deleted

---

test/extended/router/stress.go

They were still pulling when the 1 minute timeout hit.
Fixes https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19016/test_pull_request_origin_extended_conformance_gce/17838/#conformanceareanetworkingfeaturerouter-the-haproxy-router-converges-when-multiple-routers-are-writing-conflicting-status-suiteopenshiftconformanceparallel

Wait longer for router stress test replicas to start

---

vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go

https://bugzilla.redhat.com/show_bug.cgi?id=1558183#c5
@derekwaynecarr @smarterclayton @liggitt @vikaschoudhary16 @jupierce

Revert runc picks

---

hack/lib/build/binaries.sh
hack/lib/util/golang.sh

slightly modified backport of https://github.com/openshift/origin/pull/18807
partial backport of https://github.com/openshift/origin/pull/18445
/cc @stevekuznetsov @soltysh

[3.7] Fix golang version check

---

examples/prometheus/prometheus-standalone.yaml
examples/prometheus/prometheus.yaml
pkg/oc/bootstrap/bindata.go
test/extended/testdata/bindata.go

Fixes various issues with the tsdb

upgrade prometheus v2.0.0 -> v2.1.0

---

examples/image-streams/image-streams-centos7.json
examples/image-streams/image-streams-rhel7.json
examples/jenkins/jenkins-ephemeral-template.json
examples/jenkins/jenkins-persistent-template.json
pkg/oc/bootstrap/bindata.go
test/extended/testdata/bindata.go

this is using the new `make update-examples` stuff after merging some changes in openshift/library which merged changes from openshift/jenkins

pull in recent jenkins template, imagestream updates

---

pkg/util/writerlease/writerlease.go
pkg/util/writerlease/writerlease_test.go

Prevent a race in writer lease tests

---

vendor/k8s.io/kubernetes/pkg/kubelet/container/runtime.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/volume_manager.go
vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
vendor/k8s.io/kubernetes/test/e2e/storage/subpath.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1559424

UPSTREAM: 61373: Fix subpath reconstruction

---

test/extended/image_ecosystem/jenkins_plugin.go
test/extended/util/jenkins/monitor.go
test/extended/util/jenkins/ref.go

cleaning up ginkgolog and replacing with e2e.Logf

replaceing ginkgolog with e2e.Logf

---

test/extended/clusterup.sh

Change remaining --version flags to --tag for oc cluster up calls

---

hack/dind-cluster.sh
images/dind/node/ovn-kubernetes-node.sh

@dcbw PTAL
/cc @openshift/networking

setup gateway by default for dind-ovn

---

vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go
vendor/k8s.io/kubernetes/pkg/kubelet/cm/container_manager.go
vendor/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux.go
vendor/k8s.io/kubernetes/pkg/kubelet/cm/helpers_linux.go
vendor/k8s.io/kubernetes/pkg/kubelet/cm/helpers_linux_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/cm/helpers_unsupported.go
vendor/k8s.io/kubernetes/pkg/kubelet/cm/pod_container_manager_linux.go

https://bugzilla.redhat.com/show_bug.cgi?id=1554471
Upstream: https://github.com/kubernetes/kubernetes/pull/61294

UPSTREAM: 61294: Fix cpu cfs quota flag with pod cgroups

---

pkg/apps/apis/apps/helpers.go
pkg/apps/apis/apps/types.go
pkg/apps/controller/deployer/deployer_controller.go
pkg/apps/controller/deployer/factory.go
pkg/apps/controller/deploymentconfig/controller_ref_manager.go
pkg/apps/controller/deploymentconfig/factory.go
pkg/apps/registry/deploylog/rest.go
pkg/apps/registry/instantiate/rest.go
pkg/apps/strategy/rolling/rolling.go
pkg/apps/strategy/support/lifecycle.go
pkg/apps/util/util.go
pkg/cmd/infra/deployer/deployer.go

@tnozicka PTAL, no functional changes, just minor cleanup.

apps: cleanup unused code

---

pkg/build/controller/strategy/custom.go
pkg/build/controller/strategy/custom_test.go
pkg/build/controller/strategy/util.go
pkg/build/registry/buildconfiginstantiate/rest.go

bug 1560661
https://bugzilla.redhat.com/show_bug.cgi?id=1560661

setup binary input for custom builds properly

---

vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux_test.go

Fixes : https://bugzilla.redhat.com/show_bug.cgi?id=1558564
cc @childsb @eparis @rootfs @tsmetana

UPSTREAM: 61480: Fix subpath mounting for unix sockets

---

images/dind/master/ovn-kubernetes-master.sh
images/dind/node/ovn-kubernetes-node.sh

The OVN CI/CD tests are broken without this.
@pravisankar @dcbw PTAL

cluster cidr format has changed: fix it for ovn-dind

---

examples/jenkins/jenkins-ephemeral-template.json
examples/jenkins/jenkins-persistent-template.json
pkg/oc/bootstrap/bindata.go
test/extended/testdata/bindata.go

https://bugzilla.redhat.com/show_bug.cgi?id=1551500
@bparees @jwforres @smunilla @adammhaile ptal / fyi

bump jenkins route request timeout based on online testing

---

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/nodemanager.go
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vclib/virtualmachine.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1554379

UPSTREAM: 57978: [vSphere] Renews cached NodeInfo with new vSphere

---

test/extended/networking/networkpolicy.go

test/extended/networking/networkpolicy.go is a modified version of an upstream test. This syncs us up with some upstream changes, specifically from https://github.com/kubernetes/kubernetes/pull/49593.
In particular, it logs more info on failure, and retries the client a few times, to prevent spurious failures if the client runs before the node applies its NetworkPolicies, which might fix https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19080/test_pull_request_origin_extended_conformance_gce/18196/

Sync NetworkPolicy test with upstream to fix flake

---

tools/depcheck/README.md
tools/depcheck/pkg/graph/flags.go
tools/depcheck/pkg/graph/pkg.go

~~Work in progress...~~
~~Opening now to collect feedback as this is being written.~~

add tools/depcheck README

---

pkg/image/registry/imagestream/strategy.go
pkg/image/registry/imagestream/strategy_test.go

Fixes [bug 1555149](https://bugzilla.redhat.com/show_bug.cgi?id=1555149).

Setting reference to true may create a status tag

---

images/router/haproxy/reload-haproxy

Reverts openshift/origin#19076

Revert "Fix for wildcard routes taking precedence over other routes"

---

vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux_test.go
vendor/k8s.io/kubernetes/test/e2e/common/empty_dir.go

UPSTREAM : 61284: Fix creation of subpath with SUID/SGID directories.

---

test/extended/builds/build_pruning.go

changing timeout to 10 minutes

---

pkg/build/builder/dockerutil.go

Imagebuilder is failing on crio systems

Have to unmarshal to pointer for json

---

pkg/oc/cli/cmd/observe/observe.go

A production service lost networking configuration and was unable to
continue. The reflector just broke and stayed broken, which means the
observe starved. observe should respect `--maximum-errors` as well.
Rather than complicating the code by trying to mix error counts the list
error count is tracked separately, meaning after some amount of seconds
we exit.

Observe should exit when enough reflector errors occur

---

docs/openshift_networking_requirements.md

- plugins should use daemonset as a preferred way of installation
- plugins should be aware of possible conflicts with NetworkManager

networking requirements changes

---

test/extended/image_ecosystem/s2i_images.go
test/extended/image_ecosystem/scl.go

fixes https://github.com/openshift/origin/issues/19241

fix swapped format args and fix ruby version checking

---

publishing-kube-rules.yaml

Config to propagate from https://github.com/openshift/kubernetes/commits/origin-3.10-kubernetes-1.10.0

Add 1.10.0 publishing rules

---

test/extended/router/stress.go

Before we count our own writes. It would be better to have a route
exclusion mechanism (like taint avoidance).

Wait until other routers have written their status

---

pkg/cmd/server/origin/master.go
pkg/cmd/server/origin/webconsole_proxy.go
test/integration/master_routes_test.go

Supplants #19150 
Checks for what is the Webconsole Public URL from the proper config map and uses it for proxying there.

Dynamic discovery of Web Console Public URL

---

examples/prometheus/prometheus-standalone.yaml
examples/prometheus/prometheus.yaml
pkg/oc/bootstrap/bindata.go
test/extended/testdata/bindata.go

update prometheus 2.0.0 -> 2.2.1

---

pkg/network/node/ovscontroller.go

If pods get set up so that they have the node's IP address as their DNS resolver address, and they also have auto-egress-IP set up, then DNS requests will end up being forwarded to the egress node, and then back to the app node from there. In the best case this is inefficient, and in the worst case it doesn't work, either because the app node doesn't answer non-local DNS queries, or because the nodes are firewalled such that the egress node can't connect back to the app node.
We already had a special case to make DNS-to-local-node traffic not be subject to EgressNetworkPolicy; this patch moves the special case so that now the traffic is not subject to auto-egress-IP either.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1557924
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1560651 …

Make DNS to the local node IP bypass auto-egress-IP routing

---

test/extended/builds/build_pruning.go
test/extended/testdata/bindata.go
test/extended/testdata/builds/build-pruning/errored-build-config.yaml
test/extended/testdata/builds/build-pruning/failed-build-config.yaml
test/extended/testdata/builds/build-pruning/imagestream.yaml
test/extended/testdata/builds/build-pruning/successful-build-config.yaml

reverting build pruning tests to previous version

---

vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/logs/logs.go

https://github.com/kubernetes/kubernetes/pull/62416
xref https://bugzilla.redhat.com/show_bug.cgi?id=1566559
@derekwaynecarr @vikaslaad

UPSTREAM: 62416: kuberuntime: logs: reduce logging level on waitLogs msg

---

pkg/cmd/server/apis/config/serialization_test.go

fixes flake
https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/test_branch_origin_unit/161/

fix fuzzer test

---

pkg/oc/bootstrap/docker/down.go
pkg/oc/bootstrap/docker/status.go
pkg/oc/cli/cmd/cluster/cluster.go

Signed-off-by: Haoran Wang <haowang@redhat.com>

Update help doc of oc cluster up

---

images/node/system-container/config.json.template
images/node/system-container/manifest.json
images/node/system-container/service.template

Remove openvswitch from node system container

---

examples/pruner/README.md
examples/pruner/cronjob.yaml

@mfojtik since you were the original author
@sspeiche since you asked about it

Update image pruning example

---

images/node/system-container/config.json.template

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1552511
/cc @sjenning
Signed-off-by: vikaschoudhary16 <vichoudh@redhat.com>

Mount device manager socket dir path

---

glide.lock
glide.yaml

resolves ssh cloning issues - https://github.com/Masterminds/glide/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+SSH

switch glide to https
