- pkg/oc/admin/policy/modify_roles.go
- pkg/oc/admin/policy/remove_from_project.go
- test/integration/policy_commands_test.go
> Fix oc policy remove-user to remove rolebindings too

- pkg/oc/cli/describe/projectstatus.go
- pkg/oc/graph/kubegraph/nodes/nodes.go
- pkg/oc/graph/kubegraph/nodes/types.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1544183
- Implements the `ExistenceChecker` interface for Deployments and ReplicaSets
which allows the HPA error marker to be set if it is trying to scale a deleted Deployment (or rs).
- Skips standalone resources that are not found
cc @soltysh @mfojtik @deads2k
> Deployment updates in status graph

- pkg/quota/admission/clusterresourceoverride/admission.go
- pkg/quota/admission/clusterresourceoverride/admission_test.go
- test/integration/clusterresourceoverride_admission_test.go
Update the ClusterResourceOverride admission plugin to never mutate
container resource requirements below the floor specified by any
LimitRange from the same namespace.
Reason:
- Web console stripped out cluster resource override config awareness,
but the user experience is broken right now when users select a
memory limit that is the floor of the LimitRange value.
- You can see this on free-int by setting a memory limit of 100Mi,
your deployment will not work because we allowed
ClusterResourceOverride to go below the LimitRange floor.
The implication of this change is the over-commit ratio is skewed at
the lower end of the resource consumption scale (but honestly, that
makes sense).
> CRO admission plugin: never mutate below namespace minimums

- pkg/apps/controller/deployer/deployer_controller.go
- pkg/apps/controller/deployer/deployer_controller_test.go
- pkg/apps/controller/deploymentconfig/deploymentconfig_controller.go
- pkg/apps/controller/deploymentconfig/deploymentconfig_controller_test.go
- pkg/image/trigger/deploymentconfigs/deploymentconfigs.go
- test/extended/deployments/deployments.go
- test/extended/deployments/util.go
- test/extended/testdata/bindata.go
- test/extended/testdata/deployments/deployment-trigger.yaml
- fixup import and variable names to avoid conflicts with backports
- backport https://github.com/openshift/origin/pull/17539/commits
- backport https://github.com/openshift/origin/pull/18118/commits
/cc @mfojtik @ironcladlou
> [3.7] Backport dc trigger reconciliation on image change release

- pkg/cmd/server/origin/controller/config.go
- pkg/cmd/server/origin/controller/serviceaccount.go
- pkg/cmd/server/start/start_kube_controller_manager.go
- pkg/cmd/server/start/start_master.go
- test/util/server/server.go
- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch.go
- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_satoken.go
This patches in our service serving cert CA initialization in the upstream SA token controller when requested.  This makes it easier to run the upstream controllers in 3.10 and doing it in 3.9 makes for a smooth transition on the leases.
> use the upstream SA token controller

- test/cmd/policy.sh
> Add tests for remove-user with a rolebinding name

- pkg/image/controller/factory.go
- pkg/image/controller/scheduled_image_controller.go
- pkg/image/controller/scheduled_image_controller_test.go
- pkg/image/controller/scheduler.go
- pkg/image/controller/scheduler_test.go
I believe this fixes https://bugzilla.redhat.com/show_bug.cgi?id=1515058 and substantially helps https://bugzilla.redhat.com/show_bug.cgi?id=1543446
> stop scheduler from advancing through empty buckets without accept from ratelimiter

- pkg/cmd/util/serviceability/panic.go
- pkg/cmd/util/serviceability/panic_test.go
This allows a server to crash after it experiences a panic on a delay.  The delay allows us to break bootstrapping loops if we're panicing, but still making progress.  It also allows us to configure multiple handlers, so we can have this plus sentry by doing `OPENSHIFT_ON_PANIC=["crash-after-delay:10m", "sentry:https://foo"]`
@openshift/sig-master @smarterclayton @eparis @derekwaynecarr as discussed separately
> allow a panic to crash the server after a delay

- pkg/oc/cli/cmd/importimage.go
- pkg/oc/cli/cmd/wrappers.go
This patch has tiny changes as:
- Replace `oc image` with `oc start` for the suggestion for `oc run`
- Remove `oc image` from the suggetion for `oc import-image`
`oc import` is already existing command, so current `SuggestFor:
[]string{"image"}` is not working.
> Fix invalid SuggestFor for oc image

- pkg/cmd/server/kubernetes/master/master_config.go
- pkg/cmd/server/origin/master_config.go
- tools/testdebug/cmd/load_etcd.go
Found while investigating other problems.   We should use the standard loopback client connection information
> use the normal loopback connection for loopback to the apiserver

- pkg/build/builder/docker.go
- pkg/build/builder/sti.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_logs.go
back ports https://github.com/openshift/origin/pull/17094 to `release-3.7`
> [release-3.7] setup selinux labels for build containers

- pkg/image/registry/imagestream/strategy.go
- pkg/image/registry/imagestream/strategy_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1542238
cc @deads2k
> Preserve namespace on imagestreams server-side export

- pkg/network/apis/network/plugin.go
- pkg/network/master/subnets.go
openshift deletes a nodes hostsubnet automatically but during startup there is a window before the watches start that a node can be deleted and we miss the event for the deletion of the hostsubnet. At the end of startup look through the list of hostsubnets and make sure there is an accompanying node, if no node is found delete it.
Bug [1470612](https://bugzilla.redhat.com/show_bug.cgi?id=1470612)
> automatically remove hostsubnets with no nodes on startup

- pkg/router/controller/host_admitter.go
Instead of printing an error message when a route is invalid,
print a log error with verbose loglevel.
Fixes: rhbz#1491717
> Change rejected routes error message to verbose logging

- vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
- vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator_test.go
- vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go
- vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/volume_manager.go
- vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_executor.go
- vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
Thanks to @jsafrane for these fixes
https://github.com/kubernetes/kubernetes/pull/59873
https://github.com/kubernetes/kubernetes/pull/59923
59923 modified from upstream because some logging levels where already higher in 1.9
xref https://bugzilla.redhat.com/show_bug.cgi?id=1538216
Fixes https://github.com/openshift/origin/issues/17605
Fixes https://github.com/openshift/origin/issues/17556
> Picks for volume manager

- pkg/cmd/server/origin/health_grpc.go
- pkg/cmd/server/origin/healthy_gprc_test.go
- pkg/cmd/server/origin/master.go
This detects too many grpc connections being stuck, makes the server unhealthy, and causes a panic (no kubelet detects health on us at the moment).  This in combination with the delay-panic-death pull which already merged would allow us to report to sentry, report to a kubelet in the future, make some progress if needed, and die so that we don't have to manually keep our apiserver running.
/assign @eparis 
/assign @ironcladlou 
@openshift/sig-master @derekwaynecarr  
Thanks (ish?) to @eparis for finding a way to count this inside the process.  Nasty.
> auto-panic and become unhealthy on too many grpc connections

- pkg/build/apis/build/types.go
- pkg/build/metrics/prometheus/metrics.go
- pkg/build/metrics/prometheus/metrics_test.go
- test/extended/prometheus/prometheus_builds.go
- test/integration/metrics_test.go
this PR is in reference to our work for candidate metrics / alerts for builds this sprint (https://trello.com/c/kl4dzl8F/1483-2-define-candidate-metricsalerts-for-builds)
Aside from functionality changes, there are some questions to generate discussion.
As you review, please do so with this context:
- this stemmed from recent starter us east debug attempts based on current metrics
- this is very much an initial iteration ... while I think the core of these changes is valid and needed, there is certainly potential, additional changes down the line wrt metric types, label/dimensions as well, that could be warranted; I foresee multiple PRs perhaps to progress vs. a prolonged iterative cycle with this change, but let's see if folks get on board with …
> Bld reason count all phases

- pkg/apps/controller/deployer/factory.go
- pkg/apps/controller/deploymentconfig/factory.go
By ignoring periodic relist we fail to periodically reconcile DCs that have been dropped of the queue for some reason. Same for RCs in deployer_controller.
> Fix periodic reconciliation for DCs

- .tito/lib/origin/tagger/__init__.py
Tito upstream changed the method signature of the version to tag
resolution routine. We need to update our implementation to stay in
sync.
/assign @smarterclayton @dgoodwin
> Update custom tito tagger for new version

- pkg/oc/generate/cmd/resolve.go
- test/cmd/newapp.sh
- the --source-image flag should count as a source input
- the --strategy flag should override the build strategy in all source repositories
Fixes #17675
> --source-image should count as a source input

- pkg/cmd/server/start/start_kube_controller_manager.go
- pkg/cmd/server/start/start_kube_scheduler.go
- pkg/cmd/server/start/start_master.go
These flags were lost when we split the call.  The impact wasn't felt until we started relying on the kube-controler-manager for SA tokens and it was behind.  This is a good guess for generally slowness of controller-y things.
@smarterclayton @openshift/sig-master
> restore qps and burst for scheduler and kbue-controller-manager

- pkg/cmd/server/apis/config/v1/swagger_doc.go
- pkg/cmd/server/apis/config/v1/types.go
fda7222b1e6893ff97200e67156bc3f304fc9fa5 changed the doc for the internal struct.  This change simply updates the external type to match.
xref: https://github.com/openshift/origin/pull/10845/files#diff-3788994f990386b63387ece5c3b5dc33R638
xref: https://github.com/openshift/oauth-proxy/issues/55
/assign @liggitt
> masterPublicURL must be both internally and externally accessible

- pkg/network/node/ovscontroller.go
- pkg/util/ovs/fake_ovs.go
- pkg/util/ovs/ovs.go
- pkg/util/ovs/parse.go
- pkg/util/ovs/parse_test.go
If the pod is torn down after its veth has already been destroyed, then OVS will report "-1" for its ofport, so we can't rely on using that to find the pod IP from the flows.
One way to reproduce this is to "systemctl restart docker" when there's a pod running. The pod teardown attempt will fail because ovscontroller will try to run "ovs-ofctl dump-flows br0 in_port=-1", and then it will leave behind stray flows related to the old IP address (while reporting success to the caller).
This is a new bug in 3.9, and it's probably not related to #12544
> Store pod IP in OVS external-ids and use that on teardown

- pkg/build/controller/buildconfig/buildconfig_controller.go
- pkg/build/generator/generator.go
- test/cmd/newapp.sh
Build config instatiate should not emit a warning when
bc.Status.LastVersion != lastVersion and lastVersion == 0
Fixes #16557
> Fix BuildConfigInstantiateFailed warning when lastVersion == 0

- pkg/cmd/server/kubernetes/network/sdn_linux.go
- pkg/cmd/server/kubernetes/node/options/options.go
- pkg/network/node/metrics.go
- pkg/network/node/node.go
- pkg/network/node/pod.go
Remove un-needed kubelet flags and rationalize paths that kubelet and the SDN use.
@knobunc @openshift/networking @danwinship
> SDN options and CNI directory cleanup

- pkg/cmd/server/crypto/crypto.go
- test/cmd/certs.sh
Correctly handle newlines in SerialFileGenerator
This change makes it so that `SerialFileGenerator` correctly reads and writes serial files that end in a newline.  This allows it to interoperate with other tools that may interact with the serial file such as openssl.  Tests were added to assert that the incrementing logic works and that the serial file always ends with a newline.
[Bug 1512825](https://bugzilla.redhat.com/show_bug.cgi?id=1512825)
---
/kind bug
/assign @simo5 @deads2k
> Correctly handle newlines in serial files

- test/extended/prometheus/prometheus.go
The absence of a selector meant other pods in the kube-system namespace
caused failures of the test case.
> The prometheus e2e isn't checking for its pods correctly

- pkg/oc/admin/diagnostics/diagnostics/cluster/master_node.go
- pkg/oc/admin/diagnostics/diagnostics/systemd/analyze_logs.go
- pkg/oc/admin/diagnostics/diagnostics/systemd/locate_units.go
When we run `oc adm diagnostics AnalyzeLogs`, diagnostics command
often misses error messsages in journal logs. So, as an admin we are
trying to find out the reason, but debug message gives us unclear
message:
```
$ oc adm diagnostics AnalyzeLogs -l=0
...
debug: Stopped reading docker log: timestamp 1518835107917828 too old
...
```
So, this patch changes regarding AnayzeLogs as:
- Output field of struct of discovered systemd unit
- Produce correct error message if journal log has invalid timestamp
- Output why diagnostics stopped reading logs with readable timestamp.
Here is the message after applied this patch:
```
debug: Stopped reading docker log: timestamp 2018-02-17 11:33:58 +0900 JST more than 1 hour ago
```
> [Diagnostics] Fix AnalyzeLogs to provide more clear debug message

- images/node/scripts/openshift-node
Will be used by the installer in bootstrapping mode.
> Add a containerized node script for bootstrap equivalent

- pkg/oc/cli/cmd/newapp.go
- test/cmd/newapp.sh
I think someone just got a little overzealous with the `heredoc.Docf()` where it was not specifically needed.
Fixes #18562
Previous Output:
```
panic: runtime error: index out of range
github.com/openshift/origin/vendor/github.com/MakeNowJust/heredoc.Doc(0x0, 0x0, 0xc4216f8f38, 0x1)
/home/cdaley/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/MakeNowJust/heredoc/heredoc.go:36 +0x15c
github.com/openshift/origin/pkg/oc/cli/cmd.transformRunError(0x7a6d100, 0xc4201f6500, 0x4c8029e, 0x2, 0x4c87799, 0x7, 0xc4205f5446, 0xa, 0xc420b69a70, 0xc42117bc00)
/home/cdaley/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/cmd/newapp.go:832 +0x1a01 …
```
> Fixes index out of range error on oc new-app --template foo

- pkg/image/apis/image/validation/whitelist/whitelister.go
[21:42] $ hack/verify-govet.sh
pkg/image/apis/image/validation/whitelist/whitelister.go:198: possible formatting directive in Info call
pkg/image/apis/image/validation/whitelist/whitelister.go:202: possible formatting directive in Info call
[FATAL] FAILURE: go vet failed!
[ERROR] hack/verify-govet.sh exited with code 1 after 00h 00m 08s
> Fix govet error - formatting in glog.V(0).Info() call

- pkg/oc/cli/cmd/login/loginoptions.go
As a compromise to #18684 we are going to surpress the project list functionality if the number of projects available to a user is greater than 50
Original RFE was at BZ #1542326 - https://bugzilla.redhat.com/show_bug.cgi?id=1542326
RFE is within that BZ, but there was a compromise.
> Surpress project list on login if you have access to greater than 50 projects

- pkg/cmd/server/kubernetes/network/OWNERS
Added appropriate networking team members to:
pkg/cmd/server/kubernetes/network/OWNERS
> Add networking team members to OWNERS file

- pkg/network/node/egressip.go
- pkg/network/node/egressip_test.go
When dropping an egress IP from eth0, we weren't updating our internal state to reflect that we had done that, so if you added it back again it wouldn't do everything it needed to do. (Introduced in #18121 but not discoverable until after #18547 was fixed.)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1547899
>  Fix reassignment of egress IP after removal

- pkg/cmd/server/crypto/crypto.go
- test/cmd/certs.sh
This changes makes it so that SerialFileGenerator never returns a value less than 2 for a call to Next.  This guarantees that certificates generated using it do not have a serial number that conflicts with the CA's serial number of 1.  This behavior was lost in 266aa46bd0a5728d3a8831a6321cd1c3fd8b2360.
/kind bug
/assign @liggitt
Supersedes #18710
> Guarantee that SerialFileGenerator starts at 2

- pkg/network/node/ovscontroller.go
- pkg/util/ovs/fake_ovs.go
- pkg/util/ovs/ovs.go
currently in openshift when creating a new ovs bridge it does so using
ovs-vsctl --if-exists del-br br0 -- add-br br0 -- set Bridge br0 fail-mode=secure protocols=OpenFlow13
which while it does delete the bridge does not clear the flows attached to it. Spliting bridge creation into two steps, deleting the old bridge and creating the new one correctly deletes any stale ovs flows.
Bug [1539187](https://bugzilla.redhat.com/show_bug.cgi?id=1539187)
> Correctly flush stale ovs rules on Node startup

- examples/jenkins/pipeline/nodejs-sample-pipeline.yaml
- pkg/oc/bootstrap/bindata.go
- test/extended/testdata/bindata.go
@openshift/sig-developer-experience fyi / ptal
started seeing intermittent flake/timeouts in our declarative pipeline test run
see https://github.com/openshift/jenkins-sync-plugin/pull/208#issuecomment-368146115 for additional details
> relax aggressive timeouts in declarative pipeline example

- examples/prometheus/README.md
- pkg/build/metrics/prometheus/metrics.go
- pkg/build/metrics/prometheus/metrics_test.go
@openshift/sig-developer-experience fyi / ptal 
Part of the efforts for https://trello.com/c/kl4dzl8F/1483-2-define-candidate-metricsalerts-for-builds
A few things prompted this proposed change:
1) after the SRE videos, learned the existing zabbix query for builds stuck in new state that Ops is using filters out jenkins pipeline, so added strategy label
It is possible we want to get the strategy label into 3.9 ... let's include in the discussion
2) also, based on us-starter-east research, learned there are some user errors that will result in builds getting stuck in New state .... filtering those out ... reasons for all stages were recently merged
3) Through various exchanges with @jim-minter and @bparees , this PR originally attempted to follow some of the new approaches @jim-minter …
> Bld metrics path to alerts part 2

- vendor/k8s.io/kubernetes/plugin/cmd/kube-scheduler/app/server.go
Scheduler is not able to read from config file if configmap is not found. 
Upstream PR: https://github.com/kubernetes/kubernetes/pull/59386
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1540785
/cc @aveshagarwal  @sjenning
> UPSTREAM: 59386: Scheduler - not able to read from config file if configmap not found

- pkg/oc/cli/describe/projectstatus.go
- pkg/oc/cli/describe/projectstatus_test.go
- pkg/oc/graph/genericgraph/graphview/daemonset.go
- pkg/oc/graph/genericgraph/test/hpa-with-scale-ref.yaml
- pkg/oc/graph/genericgraph/test/rollingupdate-daemonset.yaml
- pkg/oc/graph/kubegraph/edges.go
- pkg/oc/graph/kubegraph/nodes/nodes.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1544183#c3
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1540560#c7
Followup to: https://github.com/openshift/origin/pull/18579
cc @soltysh
> tags existing deployment nodes as "found"

- vendor/k8s.io/kubernetes/pkg/controller/deployment/recreate.go
- vendor/k8s.io/kubernetes/pkg/controller/deployment/recreate_test.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1547169
/cc @tnozicka picked for you
/cc @derekwaynecarr FYI
/cc @smarterclayton we need this before we cut 3.9
> UPSTREAM: 60301: Fix Deployment with Recreate strategy not to wait on pods in terminal phase

- vendor/k8s.io/kubernetes/test/e2e/common/pods.go
https://github.com/kubernetes/kubernetes/pull/60457
fixes https://github.com/openshift/origin/issues/18726
@smarterclayton @liggitt @derekwaynecarr
> UPSTREAM: 60457: tests: e2e: empty msg from channel other than stdout should be non-fatal

- vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go
- vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier_test.go
Pull in multiple upstream iptables fixes to improve performance in "very large clusters" (ie, Online).
Includes https://github.com/kubernetes/kubernetes/pull/57336, https://github.com/kubernetes/kubernetes/pull/56164, https://github.com/kubernetes/kubernetes/pull/57461, and https://github.com/kubernetes/kubernetes/pull/60306.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1514174
> kube-proxy iptables performance fixes

- test/extended/deployments/deployments.go
This stops the flake as the conflict message has changed (?). It does not fix the root cause, which should be investigated and fixed (/cc @tnozicka)
Fixes: https://github.com/openshift/origin/issues/18743
> apps: stop dc cancellation flake

- pkg/network/node/metrics.go
- pkg/network/node/node.go
Data directory passed to the CNI host-local delegate plugin
should be /var/lib/cni/networks, but the original patch missed
one place to append "/networks" (the one that mattered).
Fix-up for https://github.com/openshift/origin/pull/18404
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1549491
@openshift/networking
> sdn: fix CNI IPAM data dir

- pkg/cmd/infra/router/f5.go
- pkg/cmd/infra/router/router.go
- pkg/cmd/infra/router/template.go
- pkg/router/controller/status.go
- pkg/router/controller/unique_host.go
- test/extended/router/headers.go
- test/extended/router/metrics.go
- test/extended/router/scoped.go
- test/extended/router/unprivileged.go
- test/extended/router/weighted.go
- test/extended/testdata/bindata.go
- test/extended/testdata/scoped-router.yaml
User can specify --update-status=false on the router to have a router that doesn't write back to routes. The default is true for backwards compatibilty. Allows testing routers when you don't have route status/update.
Also unify a number of host setup paths. Makes F5 and template more consistent.
Question for reviewer - on the F5 plugin we weren't performing a number of "standard" operations like setting the canonical hostname. Was there a concrete reason for that?
@openshift/sig-networking
> Make updating status on the router optional

- vendor/k8s.io/kubernetes/pkg/volume/configmap/configmap.go
- vendor/k8s.io/kubernetes/pkg/volume/downwardapi/downwardapi.go
- vendor/k8s.io/kubernetes/pkg/volume/projected/projected.go
- vendor/k8s.io/kubernetes/pkg/volume/secret/secret.go
- vendor/k8s.io/kubernetes/pkg/volume/util/BUILD
- vendor/k8s.io/kubernetes/pkg/volume/util/nested_volumes.go
- vendor/k8s.io/kubernetes/pkg/volume/util/nested_volumes_test.go
Since the runtime may try to create mount points within the sandbox, it will fail if the mount point is within a read-only API data volume, like a secret or configMap volume.
Create any needed mount points during volume setup.
xref https://github.com/kubernetes/kubernetes/pull/60342
**Which issue(s) this PR fixes**:
None
**Special notes for your reviewer**:
**Release note**:
No release notes because we haven't released anything (yet) that has this bug.
```release-note
NONE
```
> UPSTREAM: 60342: Fix nested volume mounts for read-only API data volumes

- hack/lib/constants.sh
- images/egress/dns-proxy/.cccp.yml
- images/egress/dns-proxy/Dockerfile
- images/egress/dns-proxy/egress-dns-proxy.sh
- images/egress/dns-proxy/egress_dns_proxy_test.go
- images/egress/router/egress-router.sh
Introduced dns-proxy egress router mode that allows specifying DNS name for EGRESS_DESTINATION.
Currently, dns-proxy egress mode implementation is based on HAProxy.
HAProxy 1.6+ version is used to leverage DNS resolution at runtime.
Trello Card: https://trello.com/c/407uoUFz
> Support for DNS names in egress routes

- pkg/cmd/server/kubernetes/master/master_config.go
The audit config loading doesn't respect embedded config.
> audit doesn't respect embedded config

- test/extended/cni_vendor_test.sh
- test/extended/networking.sh
- test/extended/networking/isolation.go
- test/extended/networking/multicast.go
- test/extended/networking/services.go
- test/extended/networking/util.go
- test/extended/util/test.go
Currently the extended networking test requires you to set `NETWORKING_E2E_ISOLATION=true` when using the multitenant plugin, and `NETWORKING_E2E_NETWORKPOLICY=true` when using the networkpolicy plugin (or a third-party plugin). This changes it to just check the active network plugin at runtime, and select the right tests automatically based on that. Which means
1. When running the tests against an installed cluster with `OPENSHIFT_TEST_KUBECONFIG=... ./test/extended/networking.sh`, you don't have to also set the correct additional environment variables.
2. We can change conformance_gce to install multitenant rather than subnet, and the tests will adapt themselves correctly automatically.
I know at some point someone said we were supposed to decide what tests to do based on labels or …
> change how extended network tests are selected/skipped

- pkg/cmd/infra/router/template.go
- pkg/router/metrics/haproxy/haproxy.go
- test/extended/router/metrics.go
Router metrics aren't preserved across HAProxy reloads. To counter that, capture the state of certain counter style metrics (NOT rate style metrics) immediately before a router reload, then add them to subsequent reports. Some metrics will be lost (any recorded between the capture and the actual restart time) but this will make metrics accurate to within a few percent, even when routers are restarting frequently.
This increases the cost of the reload slightly, but metrics are arguably worth it.
> Preserve router metrics across restarts

- vendor/k8s.io/kubernetes/pkg/controller/history/controller_history.go
- vendor/k8s.io/kubernetes/pkg/controller/history/controller_history_test.go
- vendor/k8s.io/kubernetes/pkg/controller/statefulset/stateful_set_utils.go
Backport of https://github.com/kubernetes/kubernetes/pull/59365
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1550415
> UPSTREAM: 59365: Fix StatefulSet set-based selector bug

- test/extended/util/test.go
This is extracted from https://github.com/openshift/origin/pull/18816/ in order
to make hostpath tests pass.
> Allow all nodes to run upstream kube tests

- pkg/admission/namespaceconditions/decorator.go
- pkg/admission/namespaceconditions/namecondition.go
We don't control the creation of all namespaces.  Some namespaces are created by post-starthooks of one kind or another, upstream and downstream. This special cases them.  We can later create a controller or some such to reconcile these.
/assign @sttts
> exclude some namespaces in run levels based on name

- vendor/k8s.io/kubernetes/pkg/printers/internalversion/describe.go
https://bugzilla.redhat.com/show_bug.cgi?id=1524379
This is so trivial that it could catch 3.9
> UPSTREAM: 57202: Fix format string in describers

- pkg/oc/bootstrap/docker/dockerhelper/ipv4range.go
Currently `fromCIDR()` uses fixed value `0XFFFFFFFF` to get upper
bound. Due to this, compiling for 32 bit env (e.g windows/386) fails
by overflows. Below is the error:
```
$ make all OS_BUILD_PLATFORMS=windows/386 WHAT=cmd/oc
hack/build-go.sh cmd/oc
++ Building go targets for windows/386: cmd/oc
pkg/oc/bootstrap/docker/dockerhelper/ipv4range.go:106:22: constant 4294967295 overflows int
```
This patch replace `0XFFFFFFFF` with `^uint32(0)`, so users can
compile the binary for 32 bit platform.
> Use ^uint32(0) instead of 0XFFFFFFFF

- docs/cluster_up_down.md
**Description**:
As of `docker-1.12.6-34`, registries should be added to the `/etc/containers/registries.conf` instead of the `/etc/sysconfig/docker` file. This PR updates the docs for RHEL/Fedora users to reflect this change.
> Update path to registries file

- pkg/oc/admin/diagnostics/diagnostics/cluster/aggregated_logging/diagnostic.go
Fix for https://github.com/openshift/origin/issues/18705
This still reports missing logging project as an error, but not a fatal error
> diagnostics: missing logging project shouldn't be fatal error

- CONTRIBUTING.adoc
- Updating the contributing doc with changes I need to do in order to run 'oc cluster up' successfully.
- Also, found few others have run into similar issue.
Eg: https://botbot.me/freenode/openshift-dev/2017-05-25/?msg=86129314&page=5
same Solution: https://botbot.me/freenode/openshift-dev/2017-05-25/?msg=86129367&page=5
> Updating CONTRIBUTING.adoc

- pkg/router/template/certmanager.go
- pkg/router/template/certmanager_test.go
- pkg/router/template/router.go
- pkg/router/template/types.go
When a router is reloaded after a batch of route/ingress changes are committed, haproxy sometimes fail to reload. This can happen if a new request to delete a route (and so delete the associated certificates) is processed when the haproxy router is reloading. The router does recover on subsequent reloads when the config changes are actually processed. 
See associated error log: 
https://gist.github.com/ramr/122d70591d1fb8f97820869f7ca5550f
The change here defers the deletes till commit time and ensures we only delete the certificates for the routes that are being processed as part of the current batchset.
To recreate:  
Just create and delete a number of routes in a loop ala:
```
function create_routes() {
local n=${1:-$NROUTES}
for i in `seq $n`; do
echo "  - Creating route …
```
> Fix router reload errors for deleted certificates

- pkg/apps/apiserver/apiserver.go
- pkg/authorization/apiserver/apiserver.go
- pkg/build/apiserver/apiserver.go
- pkg/cmd/server/origin/master.go
- pkg/cmd/server/origin/openshift_apiserver.go
- pkg/image/apiserver/apiserver.go
- pkg/oauth/apiserver/apiserver.go
- pkg/project/apiserver/apiserver.go
- pkg/route/apiserver/apiserver.go
- pkg/security/apiserver/apiserver.go
- pkg/template/apiserver/apiserver.go
Sometimes you need a loopback (your particular apiserver), sometimes you need a connection to the kube-apiserver (resource outside your group).  This provides the distinction.
> use the correct loopback connection

- pkg/image/registry/imagestreamtag/rest.go
fixes https://github.com/openshift/origin/issues/18519
> explicitly prohibit updates to imagestream tags that are not spec tags

- vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
https://github.com/kubernetes/kubernetes/pull/54530
fixes https://github.com/openshift/origin/issues/17595
xref https://bugzilla.redhat.com/show_bug.cgi?id=1534492
@tnozicka @smarterclayton @derekwaynecarr
> UPSTREAM: 54530: api: validate container phase transitions

- vendor/k8s.io/kubernetes/pkg/kubelet/container/helpers.go
- vendor/k8s.io/kubernetes/pkg/kubelet/container/helpers_test.go
Aim to fix the selinux issue we're seeing between cri-o and docker on builds
/cc @bparees @smarterclayton @mrunalp @rhatdan @derekwaynecarr 
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
> UPSTREAM: 58977: Fix pod sandbox privilege.

- vendor/github.com/docker/docker/client/hijack.go
https://github.com/moby/moby/issues/36516
https://github.com/moby/moby/pull/36517
fixes https://github.com/openshift/origin/issues/18862
> UPSTREAM: <carry>: ensure hijackedConn implements CloseWrite function

- test/extended/util/test.go
fixes https://github.com/openshift/origin/issues/18823
need to take a pass at all tests that are self-scheduling to see if we need to open this list more.
> Allow all node scheduling for more tests

- pkg/cmd/server/apis/config/serialization_test.go
- pkg/cmd/server/apis/config/types.go
- pkg/cmd/server/apis/config/v1/conversions.go
- pkg/cmd/server/apis/config/validation/master.go
Fixes #18753. I'll open an issue for 3.11 to turn change this entirely into a requirement. 
David, you ain't gonna like it, so be warned :wink: but I couldn't figure out a better approach than the one in this PR, b/c we modify all the paths to be absolute before we reach validation. Lemme know what you think. 
> Warn when AuditFilePath is relative

- pkg/oc/admin/diagnostics/diagnostics/cluster/aggregated_logging/clusterrolebindings.go
- pkg/oc/admin/diagnostics/diagnostics/cluster/aggregated_logging/clusterrolebindings_test.go
- pkg/oc/admin/diagnostics/diagnostics/cluster/aggregated_logging/diagnostic.go
- pkg/oc/admin/diagnostics/diagnostics/cluster/aggregated_logging/interfaces.go
The clusterRoleBindings check can output false alarm even if `cluster-reader` role is assigned to fluentd service account and logging works as expected.
The check used to query for `cluster-readers` CRB, but the common command
```
oc adm policy add-cluster-role-to-user cluster-reader system:serviceaccount:logging:aggregated-logging-fluentd
```
no longer appers to add the SA into `cluster-readers` group but instead creates `cluster-reader-1` CRB.
```
$ oc get clusterrolebindings cluster-readers -o yaml
...
roleRef:
name: cluster-reader
...
userNames: null
$ oc get clusterrolebindings
NAME              ROLE            USERS  GROUPS                  SERVICE ACCOUNTS                   SUBJECTS
...
cluster-reader    /cluster-reader …
```
> diagnostics: AggregatedLogging ClusterRoleBindings false negative fix

- pkg/oc/admin/prune/deployments.go
This patch makes a tiny change to remove invalid SuggestFor
Since cobra has a suggestion based on Levenshtein distance by default,
removing SuggestFor by this patch is not valid.
> Remove invalid SuggestFor from prune deployments

- pkg/cmd/server/crypto/crypto.go
This is to workaround Bug #18715, which is caused by Golang Crypto's x509
certificate generation ordering Subjects RDN incorrectly *and* GNUTLS'
bug that "fixes" client certs on read with the correct encoding.
To avoid issues until both are fixed we set the correct ordering ourself
Fixes #18715
xref https://github.com/golang/go/issues/24254 https://gitlab.com/gnutls/gnutls/issues/403#note_61687722
> Reorder groups in cert Subjects

- examples/prometheus/prometheus.yaml
- pkg/oc/bootstrap/bindata.go
- test/extended/testdata/bindata.go
- remove containerPort config from alertmanager and alertbuffer so that the prometheus
kube discovery doesn't try to scrape them
- allow unauthenticated access to /metrics path so and alert buffer can be scraped
- minor whitespace fix
> examples/prometheus: fix some prometheus service discovery scraping

- examples/prometheus/prometheus.yaml
- pkg/oc/bootstrap/bindata.go
- test/extended/testdata/bindata.go
Use case: config updated via configmap. When the change lands in the container (~60 seconds delay) the config directory hash changes and the process is killed. This does not kill the pod but results in a silent reload of config with a corresponding metric timestamp, `prometheus_config_last_reload_success_timestamp_seconds`.
Signed-off-by: Aaron Weitekamp <aweiteka@redhat.com>
> Prometheus config reload livenessprobe

- pkg/network/node/egressip.go
- pkg/network/node/egressip_test.go
- pkg/network/node/ovscontroller.go
OK, 3 "setup" commits followed by 2 commits with fixes:
- the first and second commits only change `egressip_test.go`, so clearly don't break the actual functioning of auto-egress-IP
- the third commit ("Have multiple egress IP ovscontroller methods rather than one confusing one") is small and fairly self-explanatory.
- the fourth commit ("Fix egressip handling when a NetNamespace is updated") involves a small fix to `egressip.go` and then a larger update to `egressip_test.go` to show that the fix works. Specifically: if the `EgressIPs` field on a NetNamespace was changed while that egress IP was active, then we did not clean up all of the state associated with the old egress IP, because we were accidentally cleaning up the state associated with the *new* egress IP instead.
- the last …
> Multiple auto-egress-IP fixes

- test/extended/image_ecosystem/jenkins_plugin.go
> add some debug to old jenkins plugin tests

- tools/depcheck/examples/origin_excludes.json
- tools/depcheck/examples/origin_filters.json
- tools/depcheck/pkg/cmd/cmd.go
- tools/depcheck/pkg/cmd/trace.go
- tools/depcheck/pkg/graph/filter.go
- tools/depcheck/pkg/graph/filter_test.go
- tools/depcheck/pkg/graph/flags.go
- tools/depcheck/pkg/graph/graph.go
- tools/depcheck/pkg/graph/openshift.go
- tools/depcheck/pkg/graph/pkg.go
- tools/depcheck/pkg/graph/pkg_test.go
Depends on https://github.com/openshift/origin/pull/18625
Wire through the `./depcheck trace` command. Optionally receives a file containing a list of import paths to squash.
Some output generated by it:
```bash
./depcheck trace --root=github.com/openshift/origin --entry=cmd --entry=pkg --exclude=./tools/depcheck/examples/origin_excludes.json --filter=./tools/depcheck/examples/origin_filters.json > graph.dot
```
[Contents of graph.dot](https://gist.github.com/juanvallejo/f962f5493031b601c8e461862fb23dd4)
[Contents of graph.png](https://gist.github.com/juanvallejo/c0dac021691d9d14d21eeb3eebff2aa4)
*Note* the above graph is using the smaller set of filters from `examples/origin_filters.json`, displaying ~50 nodes and only using `pkg` and `cmd` as entrypoints.
[Render of the graph, using the …
> Adds trace cmd

- pkg/network/node/node.go
When moving to shared informers in 3.6, the check to ignore events for headless/external services accidentally got limited to only add events, not delete, so now Online logs lots of errors like:
I0307 15:51:47.196166   21826 ovs.go:143] Error executing ovs-ofctl: ovs-ofctl: 0/0: invalid IP address
E0307 15:51:47.196211   21826 sdn_controller.go:284] Error deleting OVS flows for service &{...}: exit status 1
(That's for deleting an ExternalName service; trying to delete a headless service gives `ovs-ofctl: None: invalid IP address`.) In either case, the bug is harmless other than the spurious error message; we're just failing to delete a flow that wasn't there anyway.
> Don't try to delete (nonexistent) OVS flows for headless/external services

- pkg/cmd/server/apis/config/install/install.go
- pkg/cmd/server/apis/config/validation/master.go
- test/integration/audit_test.go
Fixes #18752.
/cherry-pick 3.9
> Register audit/v1beta1 for master config

- pkg/network/node/runtime.go
It seems that NewRemoteRuntimeService() doesn't actually block until the
remote runtime is actually running.  And since the remote runtime could
be started in parallel to SDN startup (in the case of dockershim at least)
it may not be available by the time we try to use it in to kill stale
pods on startup.
So when getting the runtime service for stale pod cleanup on SDN startup,
don't return until we can actually talk to it, or the timeout is reached.
@openshift/networking @pravisankar 
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1542910
(note that this doesn't actually fix the whole kill-pods-on-restart problem, because we haven't written /etc/cni/net.d/openshift-sdn.conf yet, and only when that's written and the container runtime has found that file, which is on a 30s timer, can …
> sdn: wait until container runtime is actually ready before using it

- vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go
master PR https://github.com/openshift/origin/pull/18876
opencontainers/runc#1754
xref https://bugzilla.redhat.com/show_bug.cgi?id=1548358
Hold until upstream merge.
@derekwaynecarr @vikaschoudhary16
> [3.9] UPSTREAM: opencontainers/runc: 1754: Add timeout while waiting for StartTransinetUnit completion signal

- vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go
https://github.com/opencontainers/runc/pull/1754
xref https://bugzilla.redhat.com/show_bug.cgi?id=1548358
Hold until upstream merge.
@derekwaynecarr @vikaschoudhary16
> UPSTREAM: opencontainers/runc: 1754: Add timeout while waiting for StartTransinetUnit completion signal

- install/kube-apiserver/apiserver.yaml
- install/openshift-apiserver/install.yaml
- install/openshift-controller-manager/install.yaml
- pkg/oc/bootstrap/bindata.go
- pkg/oc/bootstrap/clusterup/componentinstall/readiness_apigroup.go
- pkg/oc/bootstrap/clusterup/kubeapiserver/config.go
- pkg/oc/bootstrap/clusterup/kubeapiserver/openshift_apiserver.go
- pkg/oc/bootstrap/clusterup/kubelet/config.go
- pkg/oc/bootstrap/clusterup/kubelet/dns.go
- pkg/oc/bootstrap/clusterup/kubelet/flags.go
- pkg/oc/bootstrap/clusterup/kubelet/run_kubelet.go
- pkg/oc/bootstrap/clusterup/tmpformac/tmp_for_mac_snowflakes.go
- pkg/oc/bootstrap/docker/host/host.go
- pkg/oc/bootstrap/docker/openshift/pvsetup.go
- pkg/oc/bootstrap/docker/openshift/servicecatalog.go
- pkg/oc/bootstrap/docker/openshift/util.go
- pkg/oc/bootstrap/docker/run_self_hosted.go
- pkg/oc/bootstrap/docker/up.go
- test/end-to-end/core.sh
- test/extended/testdata/bindata.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
This is ready for review.  I've split some bits out into separate pulls to make it easier to review.  It separates openshift-apiserver and kube-apiserver and successfully produces a working cluster by aggregating openshift-apiserver using cluster up (on my machine).
> Run openshift aggregated behind kube

- vendor/k8s.io/kubernetes/pkg/util/iptables/iptables.go
- vendor/k8s.io/kubernetes/pkg/util/iptables/iptables_test.go
iptables-restore's option-parsing code is weird and broken, and it requires you to say "-w 5" rather than "-w5". Up until now we've never been running OpenShift against a version of iptables new enough to have that flag, so we didn't notice, but 1.6.2 is now in updates-testing in Fedora 27, and when it hits updates, it will totally break kube-proxy in docker-in-docker. (For master/3.9; older releases still use F25 so won't ever see iptables 1.6.2.)
> UPSTREAM: 60978: Fix use of "-w" flag to iptables-restore

- pkg/util/labels.go
Fixes #18899
New sample error (instead of segfault):
```
$ oc new-app -f fail.yaml
--> Deploying template "cdaley/random" for "fail.yaml" to project cdaley
--> Creating resources ...
error: DeploymentConfig "" is invalid: [metadata.name: Required value: name or generateName is required, spec.template: Required value, spec.selector: Invalid value: map[string]string(nil): selector cannot be empty]
--> Failed
```
> segfault with invalid template

- pkg/oc/bootstrap/clusterup/componentinstall/apply_list.go
- pkg/oc/bootstrap/clusterup/componentinstall/apply_template.go
- pkg/oc/bootstrap/clusterup/componentinstall/interface.go
- pkg/oc/bootstrap/clusterup/componentinstall/log.go
- pkg/oc/bootstrap/clusterup/kubeapiserver/config.go
- pkg/oc/bootstrap/clusterup/kubeapiserver/openshift_apiserver.go
- pkg/oc/bootstrap/clusterup/kubelet/config.go
- pkg/oc/bootstrap/clusterup/kubelet/dns.go
- pkg/oc/bootstrap/clusterup/kubelet/flags.go
- pkg/oc/bootstrap/clusterup/kubelet/run_kubelet.go
- pkg/oc/bootstrap/docker/openshift/admin.go
- pkg/oc/bootstrap/docker/openshift/templateservicebroker.go
- pkg/oc/bootstrap/docker/run/errors.go
- pkg/oc/bootstrap/docker/run_self_hosted.go
- pkg/oc/bootstrap/docker/up.go
last commit is unique.
This creates a "logs" directory alongside our config directories and tracks the install containers stdout and stderr output.
@stevekuznetsov Where do I need to copy directories to in order to have my logs picked up on failures?
>  add better logging for oc cluster up component install

- pkg/build/controller/build/build_controller.go
- pkg/build/controller/build/build_controller_test.go
- pkg/build/controller/strategy/util.go
Follow up from https://bugzilla.redhat.com/show_bug.cgi?id=1547551
> use owner references instead of timestamps to determine build/build pod ownership

- pkg/oc/cli/cmd/debug.go
Now that there are extra info together with yaml output, suggest to separate them.
Currently they are output together, not so easy for user to pick up yaml text or even for automation test checking yaml.
`$ Shell Commands: oc debug  --config=/home/jenkins/workspace/Runner-v3/workdir/cucushift-oc39-standard-slave-pdxxt-0/ose_hasha1.kubeconfig dc/hello --keep-annotations -o yaml`
```
Defaulting container name to hello.
Use 'oc describe pod/hello-debug -n urrqq' to see all of the containers in this pod.
apiVersion: v1
kind: Pod
metadata:
annotations:
debug.openshift.io/source-container: hello
debug.openshift.io/source-resource: deploymentconfigs/hello
openshift.io/deployment-config.latest-version: "1"
openshift.io/deployment-config.name: hello
openshift.io/deployment.name: hello-1 …
```
> One tiny suggest to separate oc debug info and yaml output

- pkg/cmd/server/origin/master.go
- pkg/cmd/server/origin/service_proxy_handler.go
Adds a (very) basic error page for when the console is not installed.
Suggestions to make this better? It's hard to get specific in the error description since it's a generic service proxy.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1538006
@jwforres @smarterclayton FYI
> Bug 1538006 - Improve error page when console not installed

- test/extended/cluster/cl.go
- test/extended/cluster/context.go
- test/extended/cluster/metrics.go
- test/extended/cluster/utils.go
An example of the log entry:
{"marker":"cluster_loader_marker","name":"cluster-loader-test","type":"TestDuration","startTime":"2018-02-26T22:44:56.46700834Z","testDuration":"639.046555ms"}
The 3rd party, eg, logstash/fluentd can parse the json output by
filtering out the entry by marker. For now, it is hard coded
as "cluster_loader_marker".
> Log test duration with json format for cluster-loader

- hack/lib/constants.sh
- hack/push-release.sh
Will allow us to rename images from openshift/* locally to a different
name when we push, for example to a per PR image repository.
@stevekuznetsov
> Allow a new OS_PUSH_BASE_REPO flag to push-release

- images/router/haproxy/conf/haproxy-config.template
It limits the max concurrent connections a pod can receive.
New annotation: **haproxy.router.openshift.io/pod-concurrent-connections**.
It uses HAProxy maxconn parameter to limit the connections a server(pod) can receive:
https://cbonte.github.io/haproxy-dconv/1.5/configuration.html#5.2-maxconn
It addresses the issue: https://github.com/openshift/origin/issues/14822
> Adds pod-concurrent-connections annotation.

- pkg/cmd/util/variable/variable.go
- pkg/oc/bootstrap/docker/up.go
Uses a tag like `v3.10` instead of something qualifying all the way down to last tagged level.
@smarterclayton as discussed
> use the major.minor version as default for cluster up

- pkg/network/node/sdn_controller.go
Noticed while debugging: we currently log `err` when it's nil, and don't log it when it's set
> Fix SDN startup log messages

- pkg/oc/bootstrap/clusterup/kubelet/config.go
- pkg/oc/bootstrap/clusterup/kubelet/dns.go
- pkg/oc/bootstrap/docker/run_self_hosted.go
Create the kubedns config based on the node config, not separately.  
I need this to be able to start having cluster-up use `openshift.local.clusterup` in the CWD instead of using a tempdir.  I need that to be able to default to "re-use existing environment" like `openshift start` does today.
> switch kubedns to be copy of node config, not fresh creation

- test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
- test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
- vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
- vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml
Due to how daemonsets interact with the project node selector, we need to limit write access to them to the cluster admin.
Bug 1536304
Bug 1501514
/kind bug
/assign @liggitt @deads2k @simo5 @smarterclayton
/cherrypick release-3.9
> UPSTREAM: <carry>: Remove write permissions on daemonsets from Kubernetes bootstrap policy

- pkg/oc/bootstrap/docker/run_self_hosted.go
- pkg/oc/bootstrap/docker/up.go
This removes the extra layer in the cluster up config struct and moves the installation logic from `complete` to `start`.
I'll use this as a building block for building all of our parallel tasks.  The first commit is straight moves without logic changes.
>  remove the concept of tasks from cluster up and move installation log to start

- test/extended/networking/multicast.go
- test/extended/networking/util.go
We're currently testing multicast only on the multitenant plugin, but we should be testing it on ovs-networkpolicy too. (In particular, with conformance-gce now running ovs-networkpolicy, we should test that multicast works, rather than only testing that it *doesn't* work when you don't enable it.)
> Fix multicast test to run under ovs-networkpolicy plugin

- pkg/authorization/controller/defaultrolebindings/defaultrolebindings.go
- pkg/cmd/server/bootstrappolicy/project_policy.go
- pkg/project/registry/projectrequest/delegated/delegated.go
This change correctly allows AlreadyExists errors for the default role bindings during project creation (which is race between the API master and the default role binding controller).  However, it does
not generically ignore these errors.
Fixes #18982
Alternative to #18994
/kind bug
/assign @simo5 @deads2k
> Handle role binding AlreadyExists errors on project creation

- pkg/network/master/subnets.go
#This change fixes these 2 issues:
- Currently, clearing NodeNetworkUnavailable node condition only works
if we are successful in updating the node status during the first iteration.
Subsequent retries will not work because:
1. knode != node
2. node.Status is updated in memory
3. UpdateNodeStatus(knode)
(3) will have no effect as in step (2) node.Status is updated but not knode.Status
- Node object passed to this method is pointer to an item in the informer
cache and it should not be modified directly.
Avoid NodeNetworkUnavailable condition check for every node status update
- We know that kubelet sets NodeNetworkUnavailable condition when the node is
created/registered with api server.
- So we only need to call clearInitialNodeNetworkUnavailableCondition()
for the first time and not …
> Bug 1550266 - Fix clearInitialNodeNetworkUnavailableCondition() in sdn master 

- pkg/cmd/OWNERS
We occasionally need to change files in this tree so it would be handy to have two team members in the file.  dcbw was added recently.
> Add networking team members to pkg/cmd/OWNERS

- pkg/cmd/infra/router/f5.go
- pkg/cmd/infra/router/router.go
- pkg/cmd/infra/router/template.go
- pkg/router/controller/router_controller.go
- pkg/router/controller/status.go
- pkg/router/controller/status_test.go
- pkg/util/writerlease/writerlease.go
- pkg/util/writerlease/writerlease_test.go
- test/extended/router/stress.go
- test/extended/util/cli.go
- test/extended/util/framework.go
- test/extended/util/url/url.go
- test/extended/util/url/url_test.go
- test/integration/router_without_haproxy_test.go
The current route backoff mechanism works by tracking the last touch
time from other routes, but this is prone to failure and will not scale
to very large sets of routers competing for updating status.
Instead, treat the ability to write status as a lease renewal, and have
failure to write status as a cue to backoff. Each new write further
increases the lease confidence up to an interval. Treat observed writes
from other processes as a signal that the lease holder is maintaining
their lease.
This should allow route status updates to be scale free
Needs an e2e test still
@openshift/sig-networking @ramr
> Perform real backoff when contending for writes from the router

- examples/prometheus/prometheus.yaml
- pkg/oc/bootstrap/bindata.go
- test/extended/testdata/bindata.go
This change tweaks the Prometheus example configuration to avoid
watching all the namespaces when only one is effectively of interest.
> Limit Prometheus discovery to relevant namespaces

- test/extended/router/metrics.go
Don't hide the previous values
> Print correct router metrics output to test on failure

- contrib/completions/bash/oc
- contrib/completions/zsh/oc
- pkg/oc/admin/registry/registry.go
- pkg/oc/bootstrap/clusterup/kubelet/flags.go
- pkg/oc/bootstrap/docker/dockerhelper/helper.go
- pkg/oc/bootstrap/docker/down.go
- pkg/oc/bootstrap/docker/errors/docker.go
- pkg/oc/bootstrap/docker/errors/errors.go
- pkg/oc/bootstrap/docker/openshift/admin.go
- pkg/oc/bootstrap/docker/openshift/errors.go
- pkg/oc/bootstrap/docker/openshift/helper.go
- pkg/oc/bootstrap/docker/openshift/logging.go
- pkg/oc/bootstrap/docker/openshift/metrics.go
- pkg/oc/bootstrap/docker/openshift/servicecatalog.go
- pkg/oc/bootstrap/docker/openshift/webconsole.go
- pkg/oc/bootstrap/docker/printer.go
- pkg/oc/bootstrap/docker/run/run.go
- pkg/oc/bootstrap/docker/status.go
- pkg/oc/bootstrap/docker/up.go
- pkg/oc/cli/cmd/cluster/cluster.go
First two commits are part of https://github.com/openshift/origin/pull/18896
Other 3 are fixing registry installation, removing unused constants, dealing with proxy setting and making some containers running in non-privileged mode as they don't have to be privileged.
/cc @deads2k 
/cc @openshift/sig-master
> bootstrap: minor cluster up fixes

- pkg/oc/admin/prune/imageprune/prune.go
This patch makes a tiny change to replace loop index with actual generation
number in the log message.
> Replace loop index with generation number in addImageStreamsToGraph()

- pkg/oc/cli/describe/projectstatus.go
Fixes https://github.com/openshift/origin/issues/7503
**Before**
```bash
$ oc status
In project My Project (myproject) on server https://127.0.0.1:8443
svc/foo - foo.com
dc/myapp deploys istag/myapp:latest <-
bc/myapp source builds https://github.com/juanvallejo/myapp on openshift/nodejs:8
deployment #1 deployed 7 minutes ago - 1 pod
svc/bar - 172.30.75.107:8080
dc/myapp deploys istag/myapp:latest <-
bc/myapp source builds https://github.com/juanvallejo/myapp on openshift/nodejs:8
deployment #1 deployed 7 minutes ago - 1 pod
...
```
**After**
```bash
$ oc status
In project My Project (myproject) on server https://127.0.0.1:8443
svc/bar - 172.30.75.107:8080
svc/foo - foo.com
dc/myapp deploys istag/myapp:latest <-
bc/myapp source builds https://github.com/juanvallejo/myapp on …
```
> group services w same selectors in `oc status`

- pkg/oc/cli/cmd/observe/observe.go
Fixes https://github.com/openshift/origin/issues/17743
These errors should not count against the --maximum-errors count
as the process has cleanly run and exited before wait4 syscall is made.
cc @smarterclayton @soltysh
> ignore wait4 errs in observe max-err-count

- pkg/network/master/master.go
- pkg/network/master/subnet_allocator.go
- pkg/network/master/subnet_allocator_test.go
- pkg/network/master/subnets.go
- pkg/util/netutils/common.go
- pkg/util/netutils/common_test.go
- Moved subnet allocator from pkg/util/netutils to pkg/network/master
Subnet allocator is specific to SDN master and not used anywhere.
- Currently, we need to pass all allocated subnets during
subnet allocator creation time (inUse arg to NewSubnetAllocator()).
This means we need to know all existing subnets beforehand.
- This change exposes additional method so that we can mark a
specific subnet as already allocated dynamically (after the subnet
allocator is created).
Precursor for https://github.com/openshift/origin/pull/18911
> Allow subnet allocator to mark assigned subnet dynamically

- tools/depcheck/pkg/analyze/analyze.go
- tools/depcheck/pkg/cmd/analyze.go
- tools/depcheck/pkg/cmd/analyze_test.go
- tools/depcheck/pkg/cmd/cmd.go
Depends on https://github.com/openshift/origin/pull/18466
Depends on https://github.com/openshift/origin/pull/18606
Adds dependency graph analysis.
Outputs "yours", "mine", "ours" dependencies.
Usage:
```bash
$ ./depcheck analyze --root=github.com/openshift/origin --entry=cmd/... --entry=pkg/... --entry=tools/... --entry=test/... --openshift --dep=github.com/openshift/origin/vendor/k8s.io/kubernetes
```
[Output of the command above](https://gist.github.com/juanvallejo/d83d2f56e4f7345c3f37769237cb12a1)
cc @deads2k
> adds dependency analysis

- pkg/util/writerlease/writerlease.go
- pkg/util/writerlease/writerlease_test.go
- test/extended/router/stress.go
The new writer lease code when encountering a conflict would drop the queued work, causing status not to be written
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18930/test_pull_request_origin_extended_conformance_gce/17834/#conformanceareanetworkingfeaturerouter-the-haproxy-router-converges-when-multiple-routers-are-writing-status-suiteopenshiftconformanceparallel
This could cause tests that depend on route status to fail
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19018/test_pull_request_origin_extended_conformance_gce/17839/#conformanceareanetworkingfeaturerouter-the-haproxy-router-should-support-reencrypt-to-services-backed-by-a-serving-certificate-automatically-suiteopenshiftconformanceparallel
> Some route status updates were being lost

- vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_sandbox.go
- vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_sandbox_test.go
We're about to tear the container down, there's no point.  It also suppresses
an annoying error message due to kubelet stupidity that causes multiple
parallel calls to StopPodSandbox for the same sandbox.
docker_sandbox.go:355] failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod "docker-registry-1-deploy_default": Unexpected command output nsenter: cannot open /proc/22646/ns/net: No such file or directory
1) A first StopPodSandbox() request triggered by SyncLoop(PLEG) for
a ContainerDied event calls into TearDownPod() and thus the network
plugin.  Until this completes, networkReady=true for the
sandbox.
2) A second StopPodSandbox() request triggered by SyncLoop(REMOVE)
calls PodSandboxStatus() and calls into the network plugin to read
the IP …
> UPSTREAM: 59301: dockershim: don't check pod IP in StopPodSandbox

- test/extended/builds/contextdir.go
- test/extended/builds/gitauth.go
- test/extended/builds/new_app.go
- test/extended/builds/pipeline.go
- test/extended/cluster/cl.go
- test/extended/image_ecosystem/jenkins_plugin.go
- test/extended/image_ecosystem/mariadb_ephemeral.go
- test/extended/image_ecosystem/mongodb_ephemeral.go
- test/extended/image_ecosystem/mysql_ephemeral.go
- test/extended/image_ecosystem/mysql_replica.go
- test/extended/image_ecosystem/postgresql_replica.go
- test/extended/image_ecosystem/s2i_perl.go
- test/extended/image_ecosystem/s2i_php.go
- test/extended/image_ecosystem/s2i_python.go
- test/extended/image_ecosystem/s2i_ruby.go
- test/extended/image_ecosystem/sample_repos.go
- test/extended/util/framework.go
see discussion in https://github.com/openshift/jenkins/pull/544 and failure in https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/417/consoleFull#-153881154656cbb9a5e4b02b88ae8c2f77
> allow for bypass of not proceeding deployment check jenkins extended tests given update center sync delay is now on startup

- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack.go
- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_instances.go
- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_routes.go
- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_volumes.go
https://github.com/kubernetes/kubernetes/pull/59931
xref https://bugzilla.redhat.com/show_bug.cgi?id=1558422
Basically, the fix is to never filter instances by whether they are active or not.  Just always return all instances.
> UPSTREAM: 59931: do not delete node in openstack, if those still exist in cloudprovider

- pkg/cmd/server/kubernetes/node/options/options.go
TL;DR: OpenShift is overriding IPTablesMasqueradeBit in the proxy configuration, but upstream requires that if you override it there, you have to override it in the kubelet config too, which we were not doing.
Upstream kubernetes has two separate codepaths for dealing with iptables masquerade and drop rules; one in kubelet for hostports, and one in kube-proxy for services. They attempt to coordinate with each other (by both using the same iptables chain names), but since kubelet and kube-proxy are configured separately, they have to both be given the same alternative configuration if you want to change something.
We have been overriding the IPTablesMasqueradeBit value in kube-proxy from bit 14 to bit 0 for a long time now. (I don't know why.) But we weren't overriding the corresponding …
> Default the kubelet IPTablesMasqueradeBit to the same value as the kube-proxy IPTablesMasqueradeBit

- pkg/oc/generate/cmd/newapp_test.go
- pkg/util/docker/dockerfile/dockerfile.go
- pkg/util/docker/dockerfile/dockerfile_test.go
- pkg/util/docker/dockerfile/shell_parser.go
Dockerfile `EXPOSE` label allows ranges and `ENV`/`ARG` variables as described in the following example:
```
ARG PORT=8079
ENV PORT1 8080
ENV PORT_RANGE=8081-8085 PORT2=8086
EXPOSE $PORT $PORT1 $PORT_RANGE "$PORT2" 8087 8088-8090
```
This change allows setting ports for `EXPOSE` using ranges, `ENV`/`ARG` variables for `oc new-app` as described and discussed in:
https://trello.com/c/MxgLLqju/1228-3-support-additional-expose-values-in-new-app-appcreation
> Bug 1452162 - oc new-app eval ENV/ARG and ranges in dockerfile EXPOSE

- pkg/oc/bootstrap/clusterup/kubeapiserver/openshift_apiserver.go
- pkg/oc/bootstrap/docker/openshift/logging.go
- pkg/oc/bootstrap/docker/openshift/metrics.go
- pkg/oc/bootstrap/docker/openshift/servicecatalog.go
- pkg/oc/bootstrap/docker/run_self_hosted.go
- pkg/oc/bootstrap/docker/up.go
fixes https://github.com/openshift/origin/issues/18902
This sets the routing suffix to `<serverIP>.nip.io` and rewires the `--routing-suffix` option.  Without this flag, you'd have to modify config on every ec2 instance you ran on.
This highlights linkages and ordering requirements that need to be snipped and indicates the need to have `oc cluster up` create pods that can recognize when their config changes so they can restart.  For cluster up, one interesting option we have is a pod that is special for our configuration that starts deleting pods.
@liggitt @mfojtik @soltysh
> rewire the routing suffix for oc cluster up

- examples/prometheus/prometheus.yaml
- pkg/oc/bootstrap/bindata.go
- test/extended/testdata/bindata.go
Needed for https://github.com/openshift/image-registry/pull/73
> Add virtual resource for SAR checks

- pkg/image/controller/signature/container_image_downloader.go
- pkg/image/controller/signature/signature_import_controller.go
- pkg/image/registry/image/strategy.go
- pkg/image/registry/image/strategy_test.go
Because they were never meant to be allowed.
Includes and superseds #19030 (kudos to @deads2k)
Closes #19011
Resolves: [rhbz#1557607](https://bugzilla.redhat.com/show_bug.cgi?id=1557607)
/assign @bparees @deads2k 
/cc @mfojtik
> Drop image signature annotations

- test/extended/builds/pipeline.go
- test/extended/image_ecosystem/mongodb_replica_statefulset.go
- test/extended/image_ecosystem/mysql_replica.go
- test/extended/image_ecosystem/postgresql_replica.go
- test/extended/util/deploymentconfigs.go
- test/extended/util/framework.go
- test/extended/util/nfs.go
- test/extended/util/pods.go
- test/extended/util/statefulsets.go
- test/extended/util/volumes.go
This pull request is intended to build upon the NFS backed persistent volumes introduced in #18708 for the Jenkins extended tests.
The main goal is to remove the dependency on host path volumes for persistent volumes in our tests so that they can be run in parallel across a cluster.
Fixes #7102
> Updates db replica extended tests to use nfs backed persistent volumes

- images/router/nginx/conf/nginx-config.template
Minor fix. Or when both ssl/plain routes are present, the health checks begin to fail.
> http port should not be configured for ssl

- pkg/build/controller/strategy/custom.go
- pkg/build/controller/strategy/custom_test.go
- pkg/build/controller/strategy/docker.go
- pkg/build/controller/strategy/docker_test.go
- pkg/build/controller/strategy/sti.go
- pkg/build/controller/strategy/sti_test.go
- pkg/build/controller/strategy/util.go
- pkg/build/registry/buildlog/rest.go
When using istio auto-inject, the build pod is enhanced with a container sidecar - proxy https://github.com/openshift/origin/issues/18997
Given the build pod container name can change and istio appends its containers to the end of the container list, it should be possible to treat the first container in the pod's container list as the desired build container.
@openshift/sig-developer-experience any better suggestions? Do we want to stream the logs from all containers in builder pod instead?
> Pick build container for logs with istio auto-inject - fixes #18997

- examples/OWNERS
- examples/service-catalog/service-catalog.yaml
- pkg/oc/bootstrap/bindata.go
Enables the async binding feature of service catalog when created with `oc cluster up`
> Enable async binding in service-catalog

- pkg/oc/bootstrap/clusterup/components/registry/registry_install.go
- pkg/oc/bootstrap/docker/openshift/admin.go
- pkg/oc/bootstrap/docker/up.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go
Demonstrate a simple way of making a component and installing it.  This builds on previous pulls and shows how we can start define an interface.
I think after we switch pieces over, we'll find points of commonality as their entry points.  I suspect they will include:
1. cluster-admin.kubeconfig 
2. docker helper? We should try to switch this to actually installing with pods.
3. uninstall API.  Something to remove it anyway.
4. idempotent.  We will call it *on every cluster up*
>  make registry installation a component

- pkg/oc/cli/util/clientcmd/factory.go
fixes: https://github.com/openshift/origin/issues/19089
This will make sure we are using the latest RC when selecting the pod we are going to rsh into. In case the latest rollout does not have any pods created yet, this will fail, which I think is correct, because it won't connect you to the "old" pods which will likely be terminated soon. 
/cc @tnozicka 
/cc @soltysh (as you always appreciate code removal)
> cli: get latest rc from a dc when selecting pod to rsh

- pkg/cmd/server/apis/config/serialization_test.go
- pkg/cmd/server/apis/config/v1/conversions.go
- pkg/cmd/server/apis/config/v1/testdata/master-config.yaml
- pkg/cmd/server/apis/config/validation/master.go
Currently in order for openshift to start the first entry in clusterNetworks and the old clusterNetworkCIDR/hostSubnetLength have to match. Change it
so the older clusterNetworkCIDR/hostSubnetLength fields are no longer required.
Bug [1534779](https://bugzilla.redhat.com/show_bug.cgi?id=1534779)
> Remove requirement of having deprecated clusterNetworkCIDR/hostSubnetLength in master.networkConfig

- contrib/completions/bash/oc
- contrib/completions/zsh/oc
- pkg/oc/cli/cmd/rollout/cancel.go
This patch makes a tiny change to add ValidArgs so that  users can get
completion when it runs `oc rollout cancel <TAB><TAB>`.
> Add ValidArgs to rollout cancel

- hack/dind-cluster.sh
- images/dind/node/Dockerfile
- images/dind/node/crio-node.sh
- Fix runtime endpoint for crio
- Use vfs storage driver for crio as overlay on overlayfs is not supported
> dind: crio runtime fixes

- test/extended/builds/pipeline.go
- test/extended/image_ecosystem/mongodb_replica_statefulset.go
- test/extended/image_ecosystem/mysql_replica.go
- test/extended/image_ecosystem/postgresql_replica.go
- test/extended/util/deploymentconfigs.go
- test/extended/util/statefulsets.go
- test/extended/util/volumes.go
- Adds additional debugging information for tests that use persistent volumes
- Ensures that the tests use the persistent volumes that are backed by the NFS server in their namespace
Created in reference to https://github.com/openshift/jenkins-sync-plugin/pull/215#issuecomment-375974185
> Adding additional logging for tests that use nfs backed persistent volumes

- pkg/oc/bootstrap/clusterup/componentinstall/readiness_apigroup.go
- pkg/oc/bootstrap/docker/openshift/servicecatalog.go
- pkg/oc/bootstrap/docker/run_self_hosted.go
When we use an operator, the apiservice won't be available immediately.  This makes us wait for at least one.
> wait for at least one apiservice

- pkg/oc/bootstrap/docker/openshift/admin.go
Fixes https://github.com/openshift/origin/issues/19109
The move to use the local dir caused some selinux issues.  Making the container privileged matches the registry component we already have and resolves the problem for now.
> make cluster up router work with selinux

- hack/test-end-to-end-docker.sh
- pkg/oc/bootstrap/clusterup/kubeapiserver/config.go
- pkg/oc/bootstrap/clusterup/kubelet/config.go
- pkg/oc/bootstrap/docker/openshift/admin.go
- pkg/oc/bootstrap/docker/openshift/helper.go
- pkg/oc/bootstrap/docker/openshift/login.go
- pkg/oc/bootstrap/docker/openshift/servicecatalog.go
- pkg/oc/bootstrap/docker/openshift/templateservicebroker.go
- pkg/oc/bootstrap/docker/run_self_hosted.go
- pkg/oc/bootstrap/docker/up.go
- test/extended/clusterup.sh
Now that everything is under a `base-dir`, we don't need to repeat `oc-cluster-up-` and directory prefixes and now that we've refactored enough to find them, we can eliminate the `kube-apiserver/master` assumption in the code.  This does both.
> flatten oc cluster up directory path

- images/router/haproxy/Dockerfile
- images/router/haproxy/conf/haproxy-config.template
combined the two maps for insecure routes os_edge_http_be.map and os_route_http_expose.map and the two maps for secure routes os_edge_reencrypt.map and os_edge_http_be.map  reducing the number of map files and fixing path based routing
Bug [1534816](https://bugzilla.redhat.com/show_bug.cgi?id=1534816)
> Combine backend map files to fix path based routing

- test/extended/networking/multicast.go
- test/extended/networking/util.go
Re-attempt of #18978 which mistakenly merged in a broken state (due to disabled CI tests) and then had to be reverted.
1. Makes the multicast test get run under ovs-networkpolicy
2. Makes the "ensure multicast doesn't work" tests fail rather than passing if the test can't even be set up
3. Makes the multicast test clear namespace node-selectors and also try to obey scheduling restrictions. (This is redundant but it's what the other networking tests do, probably because there's no way to figure out the cluster-wide default node selector.)
> Fix multicast test problems

- pkg/build/builder/source.go
glog.Is(0) is the lowest loglevel, so the if statement is not
necessary. This patch removes it.
> Remove unncessary if glog.Is(0) condition

- pkg/cmd/server/kubernetes/node/options/options.go
Backport of #19005 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1560584
> [3.9][backport] Default the kubelet IPTablesMasqueradeBit to the same value as the kube-proxy IPTablesMasqueradeBit

- pkg/oc/bootstrap/docker/up.go
Fixes https://github.com/openshift/origin/issues/19039
> Fix oc cluster up to do image pull

- pkg/build/builder/source.go
When build stopped with the message `"Receiving source from STDIN as
archive ..."`, it is hard to debug and so would be nice to get some
progress status.
This patch changes to output the bsdtar command stdout and stderr with
BUILD_LOGLEVEL 4 in real time.
Fixes https://github.com/openshift/origin/issues/13612
(Also https://bugzilla.redhat.com/show_bug.cgi?id=1462069)
> Provide feedback on progression for extracting of binary build

- pkg/network/node/egressip.go
- pkg/network/node/egressip_test.go
- pkg/network/node/ovscontroller.go
Backport of #18808 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1553294
> [3.9] Multiple auto-egress-IP fixes

- pkg/template/controller/metrics.go
- pkg/template/controller/metrics_test.go
- pkg/template/controller/readiness_test.go
- pkg/template/controller/templateinstance_controller.go
- pkg/template/controller/templateinstance_controller_test.go
- test/integration/metrics_test.go
tweak of https://github.com/openshift/origin/pull/18650
> TemplateInstance metrics update

- pkg/network/node/node.go
- pkg/network/node/ovscontroller.go
- pkg/network/node/ovscontroller_test.go
- pkg/network/node/sdn_controller.go
- pkg/network/node/subnets.go
- pkg/network/node/subnets_test.go
In certain circumstances we can end up with two HostSubnets having the same HostIP, which will then eventually cause nodes to delete the wrong flows:
1. node1 and node2 register with the master, the SDN master creates HostSubnets for them, and node0 observes this and creates OVS flows for them
2. The underlying VMs (or whatever) backing node1 and node2 are deleted. However, their Node objects are *not* deleted (and therefore neither are their HostSubnets).
3. node1 and node2 are recreated. Node2 comes up first, requests an IP address from its cloud/hypervisor, **and is given node1's old IP address**. It registers with the master, updating node2's Node with the new IP address. (There are now two Node objects claiming the same IP. This is apparently allowed.)
4. The SDN master sees that …
> Prevent incorrect deletion of HostSubnet OVS flows

- pkg/service/controller/servingcert/secret_creating_controller.go
- pkg/service/controller/servingcert/secret_creating_controller_test.go
If the secret is missing, the service serving cert signing controller should always create a new one even if other annotations are in place.
> if the secret is missing, always generate a cert

- contrib/completions/bash/oc
- contrib/completions/zsh/oc
- pkg/oc/cli/cmd/rollout/latest.go
Just dropping `ValidArgs` as `oc rollout latest will support ` unlikely supports `deployments` in the near future.
Fixes https://github.com/openshift/origin/issues/19088
> Remove wrong ValidArgs from rollout latest

- glide.lock
- glide.yaml
- vendor/github.com/miekg/dns/client.go
- vendor/github.com/miekg/dns/clientconfig.go
- vendor/github.com/miekg/dns/clientconfig_test.go
- vendor/github.com/miekg/dns/msg.go
- vendor/github.com/miekg/dns/server_test.go
dns dev has been more active, we want to track latest releases (for security fixes), but not master
> bump(dns): pin to ~v1

- pkg/network/sdn-cni-plugin/sdn_cni_plugin_test.go
#18355 accidentally made it so the pkg/network/sdn-cni-plugin/ unit test only passes when run as root (which apparently we must have previously been doing in our CI but recently stopped?)
This fixes it by passing in a mock ns.NetNS object, so that when doCNI() tries to ensure that the cniserver connection happens in the right namespace, it won't actually do any privileged syscalls.
Fixes #19165
> Use a dummy ns.NetNS in sdn_cni_plugin_test.go

- glide.lock
- glide.yaml
ensures update-deps.sh doesn't revert scope changes in #19017
> update docker/distribution sha

- pkg/oc/cli/describe/projectstatus.go
The graph builder doesn't know how to deal with arbitrary scale targets,
so we're disabling the "missing scale target" checks until we can rework
that.
Related to #18927
> Disable HPA scale ref check in `oc status`

- test/extended/networking.sh
This makes it so the test artifacts will contain uncompressed logs, so you can view them in the browser if you want, rather than having gzipped logs. Requested by Steve in https://github.com/openshift/ose/issues/1116#issuecomment-377398939. (We'll need to backport this to each branch we care about.) 
I also made some minor edits to clarify when/why the "dump to stdout" code runs
> Store logs uncompressed in the networking test artifacts

- pkg/network/master/master.go
- pkg/network/master/subnet_allocator.go
- pkg/network/master/subnet_allocator_test.go
- pkg/network/master/subnets.go
- pkg/network/master/vnids.go
https://trello.com/c/Uifetuz3/597-5-minimize-direct-api-calls-in-sdn-using-shared-informers
> Minimize direct API calls in SDN master by using informer cache

- pkg/authorization/authorizer/scope/converter.go
- pkg/cmd/server/apis/config/helpers.go
- pkg/cmd/server/apis/config/types.go
- pkg/cmd/server/apis/config/v1/testdata/master-config.yaml
- pkg/cmd/server/apis/config/v1/types.go
- pkg/cmd/server/apis/config/validation/master.go
- pkg/cmd/server/apis/config/validation/master_test.go
- pkg/cmd/server/kubernetes/master/master_config.go
- pkg/cmd/server/origin/master.go
- pkg/cmd/server/origin/nonapiserver.go
- pkg/oauth/util/discovery.go
- pkg/oauth/util/discovery_test.go
- test/integration/oauth_external_test.go
This helps replacing our internal Oauth Server with an external one.
REquires a metadata file to be generated by the external OAuth server and be provided for config.
> Add option to configure an external OAuth server

- pkg/cmd/server/kubernetes/node/options/options.go
- pkg/cmd/server/start/start_kube_controller_manager.go
@deads2k as discussed although I bumped the default for pods-per-core rather than removing.
> Adjust defaults to better handle self-hosting and bootstrapping

- pkg/cmd/server/apis/config/helpers.go
- pkg/cmd/server/apis/config/serialization_test.go
- pkg/cmd/server/apis/config/types.go
- pkg/cmd/server/apis/config/v1/conversions.go
- pkg/cmd/server/apis/config/v1/testdata/master-config.yaml
- pkg/cmd/server/apis/config/v1/types.go
- pkg/cmd/server/apis/config/v1/types_test.go
- pkg/cmd/server/apis/config/v1/zz_generated.deepcopy.go
- pkg/cmd/server/apis/config/validation/master.go
- pkg/cmd/server/apis/config/validation/master_test.go
- pkg/cmd/server/apis/config/zz_generated.deepcopy.go
- pkg/cmd/server/kubernetes/master/master_config.go
Removes the admission config, mastercount, and static node names from the kubemasterconfig.
The admissionconfig was a validation error before, so the server wouldn't start and the staticnodenames appears to have been completely dead.
@openshift/api-review
> remove illegal and dead kubemasterconfig fields

- test/extended/cni_vendor_test.sh
- test/extended/networking/util.go
The networking tests currently assume that all network plugins other than ovs-subnet and ovs-multitenant implement NetworkPolicy. But that means that running the extended test suite under kubenet (as in the OSE CI) will fail. Seen in https://github.com/openshift/ose/issues/1149 though this isn't a fix for the other failures discussed there.
This fixes `cni_vendor_test.sh` to explicitly set `NETWORKING_E2E_NETWORKPOLICY=true` (by default) so that the tests can then assume that if that isn't set, and we're not using ovs-networkpolicy, then it should disable the NetworkPolicy tests. (The tests can't autodetect the plugin if it's not an SDN plugin.)
> Fix NetworkPolicy tests to be skipped under kubenet

- pkg/cmd/server/apis/config/helpers.go
- pkg/cmd/server/apis/config/serialization_test.go
- pkg/cmd/server/apis/config/types.go
- pkg/cmd/server/apis/config/v1/conversions.go
- pkg/cmd/server/apis/config/v1/testdata/master-config.yaml
- pkg/cmd/server/apis/config/v1/types.go
- pkg/cmd/server/apis/config/v1/zz_generated.deepcopy.go
- pkg/cmd/server/apis/config/v1/zz_generated.defaults.go
- pkg/cmd/server/apis/config/validation/master.go
- pkg/cmd/server/apis/config/zz_generated.deepcopy.go
- pkg/cmd/server/start/master_args.go
We have a completely dead option the master-config for a client we don't support.  Found it on my quest to unwind client connections.
> remove dead client from config

- pkg/cmd/openshift-controller-manager/controller/config.go
- pkg/cmd/server/apis/config/helpers.go
- pkg/cmd/server/apis/config/serialization_test.go
- pkg/cmd/server/apis/config/types.go
- pkg/cmd/server/apis/config/v1/conversions.go
- pkg/cmd/server/apis/config/v1/testdata/master-config.yaml
- pkg/cmd/server/apis/config/v1/types.go
- pkg/cmd/server/apis/config/validation/master.go
- pkg/cmd/server/apis/config/validation/validation.go
- pkg/cmd/server/start/master_args.go
These values weren't respected anywhere (barring a single accidental reference for heapster).
@openshift/api-review 
@openshift/sig-security fyi
> remove dead auth related master-config fields

- CONTRIBUTING.adoc
- docs/cluster_up_down.md
* Specify max versions of golang and Docker on macOS
* Update `cluster_up_down.md` to use Docker CE for Mac.
* Identify issue with plain Docker for Mac and oc client v3.7
* Link to work-around for github API limitations downloading boot2docker.
@bmcelvee Please review.
> Updates to CONTRIBUTING documentation.

- contrib/completions/bash/oc
- contrib/completions/zsh/oc
- hack/lib/constants.sh
- pkg/cmd/server/apis/config/helpers.go
- pkg/cmd/server/apis/config/helpers_test.go
- pkg/cmd/server/apis/config/validation/master.go
- pkg/cmd/server/kubernetes/master/master_config.go
- pkg/cmd/server/kubernetes/master/master_test.go
- pkg/cmd/server/kubernetes/node/options/options.go
- pkg/cmd/server/start/start_kube_controller_manager.go
- pkg/cmd/server/start/start_kube_scheduler.go
- pkg/cmd/server/start/start_node.go
- pkg/oc/admin/migrate/migrator.go
- pkg/oc/cli/cmd/create/route.go
Picks from https://github.com/openshift/origin/pull/19137 that can merge before the rebase
> Pre-rebase fixes

- test/extended/builds/start.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/test-bc-with-pr-ref.yaml
An effort to speed up one of the slower extended tests, `start.go` - https://github.com/openshift/origin/issues/19077
The ruby `sample-build` is faster than mvn build of jenkins plugin, but https://github.com/wozniakjan/bc-with-pr-ref is even faster and allows to validate the output of the build - that it was executed from the specified PR
|repository used in `BuildConfig` | average build time |
|-|-|
|https://github.com/openshift/jenkins-openshift-login-plugin.git | ~5min|
|https://github.com/openshift/ruby-hello-world.git | ~1min|
|https://github.com/wozniakjan/bc-with-pr-ref | ~15s|
@openshift/sig-developer-experience ptal. If this passes our review, the `bc-with-pr-ref` repo should probably reside under openshift wings.
> extended tests: use faster built repo for bc with PR

- pkg/cmd/openshift-kube-apiserver/server.go
- pkg/cmd/server/apis/config/helpers.go
- pkg/cmd/server/apis/config/serialization_test.go
- pkg/cmd/server/apis/config/types.go
- pkg/cmd/server/apis/config/v1/conversions.go
- pkg/cmd/server/apis/config/v1/types.go
- pkg/cmd/server/apis/config/v1/types_test.go
- pkg/cmd/server/apis/config/v1/zz_generated.deepcopy.go
- pkg/cmd/server/apis/config/v1/zz_generated.defaults.go
- pkg/cmd/server/apis/config/validation/master.go
- pkg/cmd/server/apis/config/validation/master_test.go
- pkg/cmd/server/apis/config/zz_generated.deepcopy.go
- pkg/cmd/server/kubernetes/master/master_config.go
- pkg/cmd/server/kubernetes/master/master_config_test.go
- pkg/cmd/server/origin/admission/config_test.go
- pkg/cmd/server/start/master_args.go
- pkg/cmd/server/start/start_api.go
- pkg/cmd/server/start/start_master.go
- test/integration/api_paths_test.go
- test/integration/clusterresourceoverride_admission_test.go
The `KubeMasterConfig` in a master-config.yaml hasn't been optional in a long while.  The server refused to start it wasn't present.  This makes it a non-pointer so that all the conditional checks in the code can drop out.  No serialization changes.
@openshift/api-review fyi
> make kubemasterconfig non-pointer since it is required

- pkg/util/ovs/ovs.go
Log OVS comments at V(4) rather than V(5), so that they end up in test output by default. V(5) is considered a more "spammy" level, and OVS changes are not frequent enough that we need to worry about them spamming the logs.
(This was inspired by trying to debug https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19080/test_pull_request_origin_extended_conformance_gce/18196/, which is hard without being able to see what OVS flows were in effect...)
> log OVS commands at level 4

- hack/build-local-images.py
this allows using this script with docker daemons that prefix docker.io to everything
> allow docker.io prefix in hack/build-local-images.py

- pkg/cmd/server/kubernetes/master/master_config.go
- pkg/cmd/server/origin/rest/storage_options.go
- pkg/security/apis/security/install/install.go
- test/integration/etcd_storage_path_test.go
Since v3.9 has the groupified types, we should start storing our etcd data in the groupfied format.
@liggitt @mfojtik @soltysh @sttts
> start storing data in groupified format

- images/dind/master/openshift-generate-master-config.sh
#19188 didn't fix the dind startup certificate-generation race condition, it just pushed it around. It turns out that `openshift start master --write-config` also does stuff with the CA, so we need that be inside the lock too.
> Further dind start certificate generation serialization

- install/origin-web-console/console-template.yaml
- pkg/oc/bootstrap/bindata.go
- test/extended/testdata/bindata.go
Avoid error:
cannot set terminal process group (-1):
Inappropriate ioctl for device bash: no job control in this shell exit
Add message:
webconsole-config.yaml has changed.
/assign @jwforres 
> Update console liveness probe

- pkg/oc/bootstrap/docker/up.go
- test/extended/clusterup.sh
Makes the `oc cluster up --enable` flag behave like the `kube-controller-manager --controllers` flag.  Remember that `*` means "all default-enabled components", **not** "all components". It takes explicit actions to enable things that are off by default.
```go
"A list of components to enable.  '*' enables all on-by-default components, 'foo' enables the component "+
"named 'foo', '-foo' disables the component named 'foo'.\nAll components: %s\nDisabled-by-default components: %s",
strings.Join(knownComponents.List(), ", "), strings.Join(componentsDisabledByDefault.List(), ", ")
```
> add * and - as oc clusterup enable concepts

- pkg/oc/bootstrap/docker/up.go
fixes https://github.com/openshift/origin/issues/19230
Setting a KUBECONFIG to something in a subdir under the basedir usually means that you're point at an admin.kubeconfig.  If you're doing that, then you're likely to accidentally mutate the cluster-admin creds that every component uses to install after the fact.  In addition, creating that directly destroys signal information for the creation of configdirs.  Just don't allow anything in a subdir under the basedir.
> prevent oc cluster up from allowing bad KUBECONFIGs

- pkg/security/apis/security/validation/validation_test.go
`TestValidateSecurityContextConstraints` panics when expected error isn't present. This is a regression from https://github.com/openshift/origin/commit/6c585668f03ae5958f25aae65290a507f87a6a9f#diff-f8c7bee9ffab811e5d3d9938626f89dfL208 (#17576, 1.9.0 rebase).
This PR reverts that change to make it work again.
> TestValidateSecurityContextConstraints: fix "index out of range" panic when there no errors encountered

- images/dind/node/ovn-kubernetes-node.service
Just like we do for openshift-node/SDN itself.
@danwinship @knobunc @rajatchopra @pravisankar @openshift/networking
> dind: restart ovn-kubernetes-node via systemd if it fails

- pkg/oc/cli/cmd/startbuild.go
Currently `--build-loglevel` with binary build outputs warning as
"Specifyinig environment variables is not supported". It is difficult
to find out why `--build-loglevel` option causes this warning.
This patch changes the warning message to `--build-loglevel` so that
it makes clear.
Before:
```
$ oc start-build --build-loglevel=3 myapp --from-dir="." --follow
WARNING: Specifying environment variables with binary builds is not supported.
```
After:
```
$ oc start-build --build-loglevel=3 myapp --from-dir="." --follow
WARNING: Specifying --build-loglevel with binary builds is not supported.
```
> Better warning for --build-loglevel with binary builds

- images/node/system-container/config.json.template
- images/node/system-container/manifest.json
> node, syscontainer: bind mount /var/lib/kubelet from the host

- pkg/network/master/master.go
Workaround for #19217
```
Running test/cmd/sdn.sh:27: executing 'oc get netnamespace default -o jsonpath="{.netid}"' expecting success and text '^0$'...
FAILURE after 0.283s: test/cmd/sdn.sh:27: executing 'oc get netnamespace default -o jsonpath="{.netid}"' expecting success and text '^0$': the command returned the wrong error code; the output content test failed
There was no output from the command.
Standard error from the command:
Error from server (NotFound): netnamespaces.network.openshift.io "default" not found
[ERROR] [17:05:28+0000] PID 7491: hack/lib/cmd.sh:241: `return "${return_code}"` exited with status 1.
```
> Hoist sdn informer into Start()

- test/cmd/quota.sh
Fixes https://github.com/openshift/origin/issues/19282
This resolves a long-standing race condition in the first test that was masked by an overly broad output regex that happened to match `-o name` output prior to the 1.10 rebase
> Fix flake in cluster resource quota test

- pkg/apps/strategy/recreate/recreate.go
- pkg/apps/strategy/recreate/recreate_test.go
- pkg/cmd/infra/deployer/deployer.go
This will switch the kubectl scaler in deployer pod to use the scale client to scale replication controllers.
It builds on @deads2k https://github.com/openshift/origin/pull/19275 (only last commit is new) and replaces https://github.com/openshift/origin/pull/19299 and https://github.com/openshift/origin/pull/19296.
There was a discussion under #19299 about mutating the spec.replicas field on RC directly with a benefit of not needed a new client and being able to do atomic updates if we need to change other fields during scaling operation. The scale client has benefit of not needing to encode entire RC when updating one field and is preferred way to execute the "scale" operation upstream (HPA use the same mechanism).
I will squash this after @deads2k PR merges.
/cc @deads2k @tnozicka
> apps: use scale client to scale replication controllers

- pkg/oc/cli/cmd/startbuild.go
Reverts openshift/origin#19120
fixes https://github.com/openshift/origin/issues/19319
@nak3 @soltysh @juanvallejo fyi
> Revert "Better warning for --build-loglevel with binary builds"

- pkg/util/docker/dockerfile/dockerfile.go
- pkg/util/docker/dockerfile/dockerfile_test.go
There were two issues with my earlier implementation:
1) The env vars in `EXPOSE` should be processed while processing the Dockerfile AST along with processing `ARG` and `ENV` labels in order to be correctly evaluated. Previously AST was processed for `ARG` and `ENV` first and then the `EXPOSE` ports were processed.
2) `ShellLex` iterates the array of env variables from start to end, in order for latter ENV label to take effect, new env variables should be prepended to the env variables array. Previously were appended
This PR allows following dockerfile to expose ports 8080, 8081
```dockerfile
FROM centos
ENV port=8080
EXPOSE $port
ENV port=8081
EXPOSE $port
```
@wzheng1 , feel free to re-test, I have covered the combinations I didn't previously think of in unit tests as well as in …
> oc new-app: correctly evaluate env vars in multiple EXPOSE

- pkg/oc/bootstrap/docker/run_self_hosted.go
@deads2k found it: https://github.com/kubernetes/kubernetes/pull/61126
This ultimately breaks Docker for Mac, as there is no way you can run the `mount --make-rshared /` in Docker VM and the shared folders use `fuse.osxfs` and are dynamically mounted into containers...
This patch will disable `MountPropagation` for OSX (wonder if we should do the same for Linux).
> up: set MountPropagation=false on osx to bypass shared mount

- pkg/cmd/server/kubernetes/master/master_config.go
- test/integration/etcd_storage_path_test.go
Follow up to https://github.com/openshift/origin/pull/19137
Fixes #13857
Mirrors kube switch in 1.10
> Switch preferred storage to apps/v1

- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/apps.go
- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/config/config.go
- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/config/patch.go
- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/options/options.go
- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch.go
- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_flags.go
- vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
- vendor/k8s.io/kubernetes/pkg/controller/daemon/patch_nodeselector.go
- vendor/k8s.io/kubernetes/pkg/controller/daemon/patch_nodeselector_test.go
Something to talk about.  This places a shim in the upstream controller to check nodes against node selectors to avoid creating extra pods. We can talk about the expense of making the check compared to alternatives, but something concrete to show relative complexity may be useful.
Changing the default policy for all openshift installations seems like a comparatively big deal.  The cost of this patch is only borne by those who enable the node limiting features.
@simo5 @mfojtik @tnozicka @liggitt
> UPSTREAM: <carry>: filter daemonset nodes by namespace node selectors

- pkg/oc/cli/cmd/set/volume.go
- pkg/oc/cli/cmd/set/volume_test.go
When `oc set volum` was run, cli proceeds
`Validate()`->`Complete()`. This order is different from any other
cli implementations. Currently there are no isseus, but this may
effect future implementation so fix it now.
> Change the order of Validate() and Complete() for oc set volume

- images/router/haproxy/Dockerfile
- images/router/haproxy/conf/haproxy-config.template
- images/router/haproxy/reload-haproxy
- pkg/router/template/router.go
- pkg/router/template/template_helper.go
- pkg/router/template/template_helper_test.go
- pkg/router/template/util/map_paths.go
- pkg/router/template/util/map_paths_test.go
Add template helper code to sort haproxy map files so that wildcard routes don't 
take precedence over routes that start with a number.
Based on discussions in PR #19076   to fix issue #16724
@smarterclayton @jmprusi
> Template helper code to sort map files

- examples/service-catalog/service-catalog-rbac.yaml
- pkg/oc/bootstrap/bindata.go
This change fixes the following issues in the SC RBAC template:
1. Use a variable for the kube-service-catalog namespace to prevent oc process from setting the value to the empty string
2. Update the service-catalog-controller cluster role to use rbac.authorization.k8s.io/v1 as its apiVersion so that it will not be ignored by "oc auth reconcile"
3. Update role bindings to not specify a namespace in their roleRef as the RBAC roleRef struct has no such field
4. Update all roles and bindings to explicitly specify a namespace
Fixes #19163
/kind bug
/assign @deads2k @jpeeler
> Fix service catalog RBAC template

- images/router/haproxy/reload-haproxy
We initialized and never used $old_pid ($old_pids is initialized and
used later).
> Removed an unused variable from reload-haproxy

- examples/dockergc/dockergc-ds.yaml
The `ex` subcommand moved to `oc` from `openshift` in 3.9.  Need to update this example.
@vikaslaad @derekwaynecarr
> dockergc: fix example DS to use oc instead of openshift

- cmd/openshift/openshift.go
- pkg/cmd/openshift/openshift.go
- pkg/cmd/openshift/openshift_test.go
- pkg/cmd/server/start/command_test.go
- pkg/cmd/server/start/start_allinone.go
- pkg/cmd/server/start/start_node.go
- tools/clicheck/check_cli_conventions.go
- tools/genman/gen_man.go
This commit threads a stop channel into NewCommandOpenShift() so that
SIGTERM and SIGINT can be handled gracefully.
This commit only updates NewCommandStartNode() to handle the stop
channel, which is only signalled on receipt of either SIGTERM or
SIGINT. Existing usages of NewCommandStart*() (e.g., StartMaster(),
StartNetwork(), StartEtcdServer(), StartTemplateServiceBroker(), et
al) remain as is.
Now when you run:
it has the opportunity to unwind and return EXIT_SUCCESS (i.e., 0).
For example:
Process: 6801 ExecStart=/usr/bin/openshift start node \
--config=${CONFIG_FILE} $OPTIONS (code=exited, status=0/SUCCESS)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1557851
> Make NewCommandStartNode() handle SIGTERM and SIGINT

- examples/service-catalog/service-catalog.yaml
- pkg/oc/bootstrap/bindata.go
* Change secure port to 6443 to match how we install with ansible
* Create controller manager service so we can utilize the service's SSL cert
* Prometheus scrape config over for Catalog Controller over SSL
mirrors the configuration for ansible:  https://github.com/openshift/openshift-ansible/pull/7681
> catalog: create SSL cert for controller, add prometheus scrape

- vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
- vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux_test.go
Discard this PR, in case we are going to rebase again with release-1.10 branch upstream.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1563336
> UPSTREAM: 61480: Allow sockets to be mounted in subpath

- pkg/network/node/ovscontroller.go
- pkg/util/ovs/parse.go
Fix-up to #19080: when passing a cookie to del-flows (or dump-flows), you have to use the `cookie=value/mask` syntax: saying `cookie=value` without the mask always means "set the cookie to `value`", not "match a cookie with `value`". This fixes that and also fixes fake_ovs so that this would have been caught in the unit tests.
(The bug is only in master; we hadn't backported #19080 yet.)
> Fix use of cookies in HostSubnet deletion

- pkg/oc/admin/diagnostics/config.go
- pkg/oc/admin/image/verify-signature.go
- pkg/oc/cli/cmd/login/login.go
- pkg/oc/cli/cmd/login/logout.go
- pkg/oc/cli/cmd/project.go
- pkg/oc/cli/cmd/projects.go
- pkg/oc/cli/cmd/request_project.go
- pkg/oc/cli/cmd/startbuild.go
- pkg/oc/cli/cmd/startbuild_test.go
- pkg/oc/cli/cmd/status.go
- pkg/oc/cli/cmd/version.go
- pkg/oc/cli/cmd/whoami.go
- pkg/oc/cli/sa/create_kubeconfig.go
- pkg/oc/cli/util/clientcmd/factory_builder.go
- pkg/oc/cli/util/clientcmd/factory_client_access.go
- pkg/oc/cli/util/clientcmd/factory_object_mapping.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/patch_factory.go
This method prevents collapsing onto the upstream factory because it relies on direct kubeconfig access which is hidden/abstracted via a factory.
We've now got a patch to indicate that delta that we carry.
> stop using factory.OpenshiftClientConfig

- pkg/oc/cli/cmd/set/set.go
- pkg/oc/cli/util/clientcmd/factory_client_access.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/set/patch_setimage.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/set/set_image.go
demonstrates what a mess we have.
We should never add flags again.  This is needed to stop having a fake factory.
> own up to the attrocities commited in set

- pkg/oc/bootstrap/docker/run_self_hosted.go
> up: write static pod definitions on --write-config

- examples/image-streams/image-streams-centos7.json
- examples/quickstarts/README.md
- examples/quickstarts/dotnet-pgsql-persistent.json
- examples/quickstarts/dotnet.json
- pkg/oc/bootstrap/bindata.go
- test/extended/testdata/bindata.go
This add .NET Core templates which are also in openshift-ansible
openshift-ansible additionally includes a dotnet-runtime-example template. That template wasn't added to openshift/library because it is using the the docker strategy.
I am leaving it out here since it is not in openshift/library.
CC @bparees
> Add .NET Core templates

- vendor/k8s.io/kubernetes/pkg/volume/util/recyclerclient/recycler_client.go
In WatchPod(), if one of the two channels being watched (pod updates and events) is closed, the for/select loop turns into a tight infinite loop because the select immediately falls through due to the channel being closed. Watch them independently instead.
xref https://github.com/kubernetes/kubernetes/pull/62572
**Which issue(s) this PR fixes**:
N/A, but see upstream issue https://github.com/kubernetes/kubernetes/issues/62571
**Special notes for your reviewer**:
```release-note
Fix potential infinite loop that can occur when NFS PVs are recycled.
```
> UPSTREAM: 62572: Prevent virtual infinite loop in volume controller

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/resource/get.go
Fixes issue with openapi schema being retrieved on every `oc get` request
> UPSTREAM: 62584: Make x-kubernetes-print-column print handling opt-in

- test/extended/conformance-k8s.sh
Should have been part of rebase, need to figure out how to make this obvious.
> Switch conformance tests to release-1.10

- pkg/network/node/ovscontroller.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1558484
Fixes https://github.com/openshift/origin/issues/19276
> OpenShift SDN: Improvements to UpdateEgressNetworkPolicyRules()

- pkg/cmd/openshift-controller-manager/controller/interfaces.go
- pkg/cmd/openshift-controller-manager/controller/network_sdn.go
- pkg/cmd/openshift-controller-manager/controller_manager.go
- pkg/cmd/server/origin/admission/plugin_initializer.go
- pkg/cmd/server/origin/informers.go
- pkg/cmd/server/origin/master_config.go
- pkg/network/common/common.go
- pkg/network/common/common_test.go
- pkg/network/master/master.go
- pkg/network/master/subnets.go
- pkg/network/master/vnids.go
- test/integration/buildcontroller_test.go
This eliminate the only use of the internal kube client and types we have in the openshift-controllers. We need to remove the dependency for ease of maintenance.
@openshift/sig-networking
> switch the sdn to use external types

- pkg/cmd/server/start/start_kube_controller_manager.go
- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_imagetemplate.go
Minimal change pull for fixing up 3.9.  You'll still need a bugzilla and to use the actual flags in 3.10.
@gnufied I was thinking something more like this.  Doing it like this keeps the duplicated template resolution code as close to the original as possible.
> recycler images

- test/cmd/newapp.sh
PR was against a commit, but this was reading from master, so only
failed after we merged.
xref https://github.com/openshift/origin/commit/1dfbdf996ba1692fc3d5baf967cc1ef9d7e164e1
> Remove test reference to deleted content

- pkg/cmd/openshift-controller-manager/controller/build.go
- pkg/cmd/server/admission/init.go
- pkg/cmd/server/admission/types.go
- pkg/ingress/admission/ingress_admission.go
- pkg/scheduler/admission/podnodeconstraints/admission.go
- pkg/scheduler/admission/podnodeconstraints/admission_test.go
- pkg/security/registry/podsecuritypolicyselfsubjectreview/rest_test.go
- pkg/service/admission/endpoint_admission.go
Upstream has the same interface, so there is no need for us to have a copy of it.
---
Remove decode code related to PSP Subject Reviews
This change removes the dead admission code from the build controller.  That controller uses PodSecurityPolicySubjectReviews to avoid having to be tied directly to admission.
Also removed an unused function in the PSP Self Subject Review unit test.
---
/kind cleanup
> Remove duplicate WantsAuthorizer interface

- cmd/hypershift/main.go
- install/openshift-web-console-operator/install-rbac.yaml
- install/openshift-web-console-operator/install.yaml
- pkg/cmd/openshift-experimental/cmd.go
- pkg/cmd/openshift-operators/apis/operators/v1alpha1/types.go
- pkg/cmd/openshift-operators/apis/operators/v1alpha1helpers/helpers.go
- pkg/cmd/openshift-operators/apis/webconsole/v1alpha1/register.go
- pkg/cmd/openshift-operators/webconsole-operator/cmd.go
- pkg/cmd/openshift-operators/webconsole-operator/starter.go
- pkg/cmd/openshift-operators/webconsole-operator/sync_v310_00.go
- pkg/cmd/openshift-operators/webconsole-operator/webconsole_operator_trigger.go
- pkg/oc/bootstrap/bindata.go
- pkg/oc/bootstrap/clusteradd/cmd.go
- pkg/oc/bootstrap/clusteradd/components/web-console-operator/OWNERS
- pkg/oc/bootstrap/clusteradd/components/web-console-operator/web_console_operator.go
- test/extended/testdata/bindata.go
This adds a simple skeleton of a CRD driven controller that uses leader election and then wires it through `oc cluster add` for proof that it runs.  This is all boilerplate code.
> add a simple web console operator

- test/extended/cluster/cl.go
- test/extended/cluster/metrics/metrics.go
Prequisite work to have the scraper read JSON metrics from the Cluster Loader stdout log.
Go doesn't handle serializing/deserializing `time.Duration` into anything meaningful, so we need some trickery... Didn't want to make alias types altogether.
Now we can just import the metrics library into the scraper and it will handle it magically.
> Add custom JSON marshaling implementations, metrics broken into lib

- test/extended/ldap_groups.sh
After 1.10 rebase this test started failing because we now use grouped
APIs by default.
> Fix LDAP test to catch the correct output.

- pkg/network/node/ovscontroller.go
- pkg/network/node/ovscontroller_test.go
- pkg/network/node/sdn_controller.go
Before this, we did not set the MTU on the tun0 interface explicitly.
Since that interface is of type internal it is created and managed by
OVS.  Because it is managed by OVS, the MTU changes when pods are
added and removed from the bridge.  With a pod we see the desired MTU
on tun0, but when there are no pods, the MTU goes back to 1500.  This
is normally fine, but if there are packets above the MTU going between
nodes using their SDN addresses, then those packets will get dropped
when there are no pods using the SDN on one of those nodes.
The change is to request the correct MTU when we add the port to OVS.
Fixes bug 1564346 (https://bugzilla.redhat.com/show_bug.cgi?id=1564346)
> Explicitly set the MTU on the tun0 interface

- pkg/cmd/openshift-apiserver/server.go
- pkg/cmd/openshift-controller-manager/controller/config.go
- pkg/cmd/openshift-controller-manager/controller_manager.go
- pkg/cmd/openshift-kube-apiserver/server.go
- pkg/cmd/server/apis/config/helpers.go
- pkg/cmd/server/kubernetes/node/options/options.go
- pkg/cmd/server/origin/informers.go
- pkg/cmd/server/origin/master_config.go
- pkg/cmd/server/start/start_master.go
- test/extended/templates/helpers.go
- test/extended/templates/templateservicebroker_e2e.go
- test/extended/util/cli.go
- test/integration/buildcontroller_test.go
- test/integration/ingressip_test.go
- test/util/client.go
This pull cleans up a lot of initial client creation so that we can unwind the controller config.  Don't worry, it'll make sense.  This is the non-contentious bit that slims down various helpers and move dependencies closer to the point of use.
> cleanup launch of openshift controller client

- pkg/oc/bootstrap/docker/errors/docker.go
- pkg/oc/bootstrap/docker/up.go
- test/extended/clusterup.sh
When the cluster is already initialized in baseDir, we should not allow to specify `--enable` flag but users should use oc cluster add instead.
/cc @deads2k
> up: validate usage of enable on initialized cluster

- glide.lock
- glide.yaml
@liggitt @deads2k lets do this separately from the etcd pull.
> glide: fix go4.org repo url and bump the k8s.io shas to match forks

- images/node/system-container/config.json.template
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1565482
> node, syscontainer: bind mount /opt/cni/bin from the host

- pkg/router/controller/host_admitter.go
- pkg/router/controller/host_admitter_test.go
Fixes the host admitter plugin to respect the namespaces it is supposed to service. 
And not update the status of a route that it is not supposed to process (e.g. for router shards).
@knobunc  fyi
> Fix for bugz 1564984 -  rejected by router when using router sharding and NAMESPACE_LABELS

- images/node/system-container/config.json.template
Fix for #19427
Due to extra comma a generated config.json is invalid, which breaks 
Fedora Atomic and system-containers tests (see 
https://s3.amazonaws.com/aos-ci/ghprb/openshift/openshift-ansible/76079433422c82e4ad66b46b26e5561003172ba0.0.1524215134798135132/output.log and 
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/8039/test_pull_request_openshift_ansible_extended_conformance_install_system_containers/7337/)
> system containers: remove extra comma, which breaks json syntax

- pkg/oc/bootstrap/clusteradd/components/service-catalog/service_catalog.go
Fixes #19422. 
I tested this manually:
- When running `oc cluster up --enable=service-catalog`, no clusterservicebroker resource is created.
- When running `oc cluster up --enable=service-catalog,template-service-broker`, the resource _is_ created.
> Don't install template-service-broker broker resource unless tsb enabled

- pkg/cmd/server/apis/config/serialization_test.go
- pkg/cmd/server/apis/config/v1/conversions.go
- pkg/cmd/server/apis/config/v1/testdata/node-config.yaml
- pkg/cmd/server/apis/config/v1/types.go
- pkg/cmd/server/kubernetes/node/node_config_test.go
- test/util/server/server.go
- File path without protocol for CRI endpoint is deprecated
```
Apr 04 20:16:05 openshift-node-1 openshift[313]: W0404 20:16:05.768925     313 util_unix.go:75] Using "/var/run/dockershim.sock" as endpoint is deprecated, please consider using full url format "unix:///var/run/dockershim.sock".
Apr 04 20:16:05 openshift-node-1 openshift[313]: I0404 20:16:05.768885     313 remote_runtime.go:43] Connecting to runtime service /var/run/dockershim.sock
```
> Prefix with unix protocol for docker shim socket

- test/extended/builds/pipeline.go
See https://github.com/openshift/jenkins-client-plugin/pull/148
will clear up builds ext test until I  can sort out new results from `oc get -o json` on openshift api objs
> temporarily disable client plugin while we adjust to new kind/apiVersion

- pkg/oc/admin/diagnostics/config.go
`--config` option for oc adm diagnostics is not clear what config was read.
When we specify `--config`, the log message displays below:
```
[Note] Determining if client configuration exists for client/cluster diagnostics
Info:  Successfully read a client config file at 'myconfig'
Info:  Successfully read a client config file at '/root/.kube/config'
```
This looks like `'/root/.kube/config'` was read over after `myconfig` was
read. (Actually it was NOT, though.)
This patch breaks the loop when config file found.
> diagnostics: Break a loop when config file found

- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status_test.go
https://github.com/kubernetes/kubernetes/pull/62914
fixes https://github.com/openshift/origin/issues/19443
> UPSTREAM: 62914: kubelet: fix flake in TestUpdateExistingNodeStatusTimeout

- test/extended/testdata/bindata.go
- test/extended/testdata/builds/valuefrom/failed-docker-build-value-from-config.yaml
- test/extended/testdata/builds/valuefrom/successful-docker-build-value-from-config.yaml
Another candidate for potential speedup https://github.com/openshift/origin/issues/19077, I added build logs to the test output (https://github.com/wozniakjan/origin/pull/1) so I have a better idea what was taking so long in waiting forv the build such as in `valuefrom.go`:
```
Apr 10 08:49:49.583: INFO: Waiting for mydockertest-1 to complete 
Apr 10 08:56:35.591: INFO: Done waiting for mydockertest-1: util.BuildResult{BuildPath:"build/mydockertest-1", BuildName:"mydockertest-1", StartBuildStdErr:"", StartBuildStdOut:"build/mydockertest-1", StartBuil>
```
and the culprits are confirmed:
```
docker build: 280s 
2018-04-10T08:50:10.666080715Z Step 1/16 : FROM centos/s2i-base-centos7
2018-04-10T08:54:50.094010994Z Successfully built f3d34cd6d7d3
docker push: 102s …
```
> extended tests: use leaner image in valuefrom.go

- pkg/oc/generate/app/app.go
- test/extended/builds/pipeline.go
- test/extended/util/framework.go
- test/integration/newapp_test.go
The `oc new-app --build-env` cmdline env variables are propagated to the `BuildConfig` only when using a template. With git repository as a source, env variables can be silently dropped if it contains no template.
This fixes  #19142 ~~by joining the env for `objects` from component references similarly like it is done for `templateObjects` from template component refs in `(c *AppConfig) buildTemplates`.~~
~~Looking at the `BuildConfig` with this fix, env variables are propagated, however, I am not sure how it obtains the Jenkinsfile because neither embedded Jenkinsfile nor path to it contain anything.~~
```json
"Strategy": {
"DockerStrategy": null,
"SourceStrategy": null,
"CustomStrategy": null,
"JenkinsPipelineStrategy": {
"JenkinsfilePath": "", 
"Jenkinsfile": "", 
"Env": [
{
"Name": …
```
> oc new-app: propagate cmdline env to pipeline/git builds

- pkg/authorization/controller/defaultrolebindings/defaultrolebindings.go
Only append errors on creating a role binding if the error isn't an already exists error.
/assign @simo5
> skip already exists errors for default role bindings

- pkg/oc/cli/cmd/startbuild.go
Currently `--build-loglevel` with binary build outputs warning as
"Specifyinig environment variables is not supported". It is difficult
to find out why `--build-loglevel` option causes this warning.
This patch changes the warning message to `--build-loglevel` so that
it makes clear.
Before:
```
$ oc start-build --build-loglevel=3 myapp --from-dir="." --follow
WARNING: Specifying environment variables with binary builds is not supported.
```
After:
```
$ oc start-build --build-loglevel=3 myapp --from-dir="." --follow
WARNING: Specifying --build-loglevel with binary builds is not supported.
Uploading directory "." as binary input for the build ...
$ _output/local/bin/linux/amd64/oc start-build  myapp --from-dir="." --follow -e foo=bar
WARNING: Specifying environment variables with binary …
```
> Distinguish warning message between --build-loglevel and --env with binary builds

- test/cmd/newapp.sh
Should fix https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/19339/test_pull_request_origin_cmd/12853/
Seems like the mysql 5.7 removed the volumes?
```
~/.../openshift/origin → docker inspect centos/mysql-57-centos7 | grep Volume
"Volumes": null,
"Volumes": null,
```
/cc @bparees
> new-app: remove check for volumes in new-app test

- pkg/router/template/plugin.go
- Currently, service with empty ClusterIP is ignored but headless services
can have ClusterIP="None" and those need to be ignored as well.
Found this problem on ca-central starter cluster where router reload failed due to incorrect haproxy config:
```
limiter.go:137] error reloading router: exit status 1
: parsing [/var/lib/haproxy/conf/haproxy.config:63325] : 'server ept:mysql:None:3306' : could not resolve address 'None'.
: Failed to initialize server(s) addr.
```
`None` in `endpoint.ID` came from `service.Spec.ClusterIP`
> Bug 1567532 - Unidle handling in router should ignore headless services

- vendor/k8s.io/kubernetes/pkg/features/kube_features.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status_test.go
https://trello.com/c/0Omf07Vr/891-3-node-prevent-abuse-of-local-ephemeral-storage
We need more time to evaluate the implications of this feature, especially for Online.
> UPSTREAM: <carry>: disable local storage isolation feature gate

- pkg/apps/apiserver/apiserver.go
- pkg/apps/registry/deploylog/rest.go
- pkg/apps/registry/deploylog/rest_test.go
- pkg/cmd/server/origin/openshift_apiserver.go
Make the deploymentconfig logs loopback to the kubeapiserver to get pod logs instead of going direct to the kubelet.  This will eventually allow us to avoid direct access on network access to the kubelet.
> remove directly kubelet dependency from deploymentconfigs

- pkg/image/registry/imagestreamtag/rest.go
- test/integration/imagestream_test.go
Because image stream tags are virtual, it's very likely that creating
two IST's on the same stream at the same time will conflict. We can't
use patch because they're virtual on the lower registry, but we can do a
conflict retry loop.
Found this while getting ready for the ci-operator - it creates multiple image stream tags on the same stream and was flaking >50% of the time.
@bparees
> Creating an image stream tag is too likely to conflict

- test/extended/builds/pipeline.go
@openshift/sig-developer-experience fyi 
(there may be some timing issues to sort out with the test pipeline in the client-plugin repo, or an as yet tbd issue accessing oapi objects, with recent 3.10 changes ... let's see what happens)
> re-enable jenkins client plugin ext tests

- vendor/k8s.io/kubernetes/pkg/volume/git_repo/BUILD
- vendor/k8s.io/kubernetes/pkg/volume/git_repo/git_repo.go
- vendor/k8s.io/kubernetes/pkg/volume/git_repo/git_repo_test.go
RHEL 7 has old git so we should pick this PR to restore git volume functionality.
Upstream PR: https://github.com/kubernetes/kubernetes/pull/62394
/assign @gnufied @rootfs @tsmetana 
https://bugzilla.redhat.com/show_bug.cgi?id=1565553
> UPSTREAM: 62394: Revert "git: Use VolumeHost.GetExec() to execute stuff in volume plugins"

- pkg/network/node/pod.go
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1562783
> SDN: In maybeAddMacvlan(), print the error returned from ns.GetNS

- contrib/completions/bash/oc
- contrib/completions/zsh/oc
- pkg/oc/cli/cmd/rsync/copyrsync.go
- pkg/oc/cli/cmd/rsync/rsync.go
- pkg/oc/cli/cmd/rsync/util.go
This adds option --compress to oc rsync. Fixes #16227
I did some test to verify this is working, some results:
$ Without compression
sent 262 bytes  received 50,558 bytes  7,818.46 bytes/sec
total size is 49,661  speedup is 0.98
$ with compression
sent 262 bytes  received 14,695 bytes  2,301.08 bytes/sec
total size is 49,661  speedup is 3.32
> Add --compress option to oc rsync

- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go
- vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go
- vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector_test.go
- vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go
- vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/operations.go
- vendor/k8s.io/kubernetes/pkg/controller/namespace/deletion/BUILD
- vendor/k8s.io/kubernetes/pkg/controller/namespace/deletion/namespaced_resources_deleter.go
- vendor/k8s.io/kubernetes/pkg/controller/namespace/deletion/namespaced_resources_deleter_test.go
- vendor/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory_object_mapping.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/BUILD
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructuredscheme/BUILD
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructuredscheme/scheme.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/dynamic/BUILD
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/dynamic/bad_debt.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/dynamic/client.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/dynamic/client_pool.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/dynamic/client_test.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/dynamic/scheme.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/dynamic/simple.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/rest/request.go
- vendor/k8s.io/kubernetes/test/e2e_node/services/BUILD
- vendor/k8s.io/kubernetes/test/e2e_node/services/namespace_controller.go
- vendor/k8s.io/kubernetes/test/integration/client/dynamic_client_test.go
- vendor/k8s.io/kubernetes/test/integration/master/crd_test.go
no conflicts?  Unpossible.
@bparees
> UPSTREAM: 62913: make a simple dynamic client that is easy to use

- images/router/nginx/Dockerfile
- images/router/nginx/conf/error-page-503.html
- images/router/nginx/conf/nginx-config.template
- images/router/nginx/nginx.repo
- images/router/nginx/reload-nginx
- pkg/router/template/template_helper.go
- pkg/router/template/template_helper_test.go
This PR brings the following changes to the NGINX-based router:
Misc imrovements:
Implemented features:
Docs:
Note, to run the NGINX Plus Router, assuming you have built `openshift/nginx-router` image, you can use the following commands:
```
$ oc delete dc router # remove the default HAProxy router
$ oc adm router nginx-router --images=openshift/nginx-router
$ oc set env dc/nginx-router ROUTER_METRICS_TYPE=""
```
> Improve NGINX-based router

- pkg/cmd/server/origin/openshift_apiserver.go
- pkg/oc/admin/router/router.go
- pkg/security/admission/admission.go
- pkg/security/admission/admission_test.go
- pkg/security/admission/scc_exec.go
- pkg/security/apiserver/apiserver.go
- pkg/security/registry/podsecuritypolicyreview/rest.go
- pkg/security/registry/podsecuritypolicyreview/rest_test.go
- pkg/security/registry/podsecuritypolicyselfsubjectreview/rest.go
- pkg/security/registry/podsecuritypolicyselfsubjectreview/rest_test.go
- pkg/security/registry/podsecuritypolicysubjectreview/rest.go
- pkg/security/registry/podsecuritypolicysubjectreview/rest_test.go
- pkg/security/securitycontextconstraints/matcher.go
- test/cmd/policy.sh
- test/integration/scc_test.go
Allow authorization of SCC use via RBAC
This change adds the minimal logic required to support the following
SAR check as a means to allow access to a specific SCC in a specific
namespace:
```
Verb:      use
Namespace: <namespace>
Name:      <scc name>
APIGroup:  security.openshift.io
Resource:  securitycontextconstraints
```
This SAR check mimics the upstream PSP check but with the SCC group
and resource.  This has the added benefit of allowing namespace
scoped SCC access.
It does not update any bootstrap data to use this method.  It does
not update the router command's SCC check to use this method.  Thus
nothing currently relies on this method as a means of SCC access.
---
https://trello.com/c/LkCMxnjt
/assign @simo5 @deads2k @php-coder
/hold …
> Allow authorization of SCC use via RBAC

- pkg/oc/admin/migrate/legacyhpa/hpa.go
The doc text on `oc adm migrate legacy-hpa` referenced some non-existent
flags.  This fixes it to no longer reference those flags.
> Fix doc text on `migrate legacy-hpa`

- pkg/build/apiserver/apiserver.go
- pkg/build/registry/buildconfiginstantiate/rest.go
- pkg/cmd/server/apis/config/helpers.go
- pkg/cmd/server/origin/master.go
- pkg/cmd/server/origin/master_config.go
- pkg/cmd/server/origin/openshift_apiserver.go
- pkg/cmd/server/origin/reststorage_validation_test.go
This cleans out the last need for a direct kubelet connection from the openshift apiserver.  I'm assuming that extended build tests will check binary builds for us.
>  remove direct kubelet connection for binary builds

- pkg/oc/bootstrap/clusteradd/components/sample-templates/sample_templates.go
- test/extended/clusterup.sh
Another minor bit of fallout from the cluster up refactor to discuss
I've submitted this change as much to start the discussion vs. my thinking this is the correct solution.
The particulars / competing concerns:
- we used to expose both jenkins ephemeral and jenkins persistent templates in the openshift namespace via cluster up
- complaints about "why 2" ,etc.
- going with persistent is consistent with the other samples
- but the jenkins autoprovisioner defaults to jenkins-ephemeral if it is not explicitly set (see https://github.com/openshift/origin/blob/master/pkg/cmd/server/apis/config/v1/conversions.go#L50-L52) ... traditionally, meaning when that feature first dropped many moons ago, there were openshift start paths which would not ensure there were PVs set up to leverage, so for …
> switch sample jenkins template to ephemeral to match auto provisioner

- test/extended/networking/multicast.go
In order to help debugging problems print the pod log if the multicast test fails while launching the pod.
NOTE: ¿Should we look for a generic solution for printing pod logs in tests?
Fixes partially: rhbz#1557487
> Print pod logs for tests

- test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
- test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
- vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go
- vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml
>  UPSTREAM: 62146: Fix daemon-set-controller bootstrap RBAC policy

- pkg/util/ovs/ovs.go
- pkg/util/ovs/ovs_test.go
If the vswitchd exits (or is OOM killed) while an ovs-vsctl is
being run, that command may hang waiting for the database state
to be updated, which never happens because vswitchd is dead and
hasn't been restarted.  Add a timeout so we don't block forever.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1571379
@openshift/networking @danwinship
> ovs: add default 30s timeout to ovs-vsctl operations

- pkg/util/writerlease/writerlease.go
Prevent conflicting routers from conflicting as much up front. Prevents out of order actions and requeues causing us to "steal" leadership more often. Should reduce contention.
> Pause the work queue when following, instead of retrying

- vendor/k8s.io/kubernetes/pkg/apis/core/types.go
- vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
- vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation_test.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods_test.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/api/core/v1/types.go
- vendor/k8s.io/kubernetes/test/e2e/node/mount_propagation.go
Introduce private mount propagation and make it default.
https://github.com/kubernetes/kubernetes/pull/62462
> UPSTREAM: 62462: Private mount propagation

- hack/lib/start.sh
- images/router/haproxy/reload-haproxy
- test/extended/setup.sh
Since we moved to haproxy 1.8 in OpenShift 3.9 we make use of the
seamless reload feature, and there is no need to mess with iptables to
drop SYNs to try to make reloads seamless.
This change strips out all of that code now that it no longer needed.
> Remove the DROP_SYN_DURING_RESTART iptables rules

- test/extended/image_ecosystem/sample_repos.go
Making the mongodb tests less strict about how the example app counts the pagecount.
`SampleRepoConfig` is never used outside of this package and it probably makes sense only for its package so making it non-exported.
Slightly improved readability of instantiating the `sampleRepoConfig`, given all its fields are `string`, it was easy to get confused with the order.
relevant to: https://github.com/openshift/origin/issues/19379
ptal @openshift/sig-developer-experience
> ext_tests: make mongodb check tolerate any non zero pagecount

- images/router/haproxy/conf/haproxy-config.template
when using env variable ROUTER_SYSLOG_ADDRESS the haproxy router
issues this warning
[WARNING] 010/021149 (26) : parsing [/var/lib/haproxy/conf/haproxy.config:31] : 'option httplog' not usable with frontend 'public_ssl' (needs 'mode http'). Falling back to 'option tcplog'.
Since the router falls back on 'option tcplog' we add a switch to add 'option tcplog' to frontend public_ssl when ROUTER_SYSLOG_ADDRESS is set
bug 1533346
https://bugzilla.redhat.com/show_bug.cgi?id=1533346
> router - add "option tcplog" to frontend public_ssl

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go
The wrong object was being decorated, which prevented image streams from
having the correct image registry URL status set.
> UPSTREAM: 63349: Decorate function not called on Create

- pkg/admission/namespaceconditions/decorator.go
- pkg/oc/bootstrap/clusteradd/componentinstall/apply_template.go
- pkg/quota/admission/clusterresourcequota/admission.go
I don't think we actually create anything in default that we need until after the openshift apiserver is around.  I've stopped special casing that namespace.
/assign @liggitt 
@liggitt seem safe to you?
@openshift/sig-master I thought I saw an issue about this, but I can't find it now
> run SCC in default

- pkg/oc/bootstrap/clusteradd/components/registry/registry_install.go
- pkg/oc/bootstrap/docker/down.go
- pkg/oc/cli/cli.go
- pkg/oc/cli/cmd/cluster/cluster.go
In remote docker daemon case, the registry host mount path should be prefixed
into /var/lib/origin
Fixes: https://github.com/openshift/origin/pull/19561
/cc @deads2k
/cc @praveenkumar
> up: fix mount-path for docker registry

- pkg/build/util/util.go
- pkg/build/util/util_test.go
1. Ensure build config environment vars are not modified when they are safely logged.
2. Only redact a URL if it contains a password
Fixes bug [BZ-1571349](https://bugzilla.redhat.com/show_bug.cgi?id=1571349)
> Fix BuildConfig Environment Variable Modification

- pkg/cmd/openshift-controller-manager/controller/interfaces.go
- pkg/cmd/openshift-controller-manager/controller/template.go
- pkg/cmd/openshift-controller-manager/controller_manager.go
- pkg/template/controller/templateinstance_controller.go
- pkg/template/controller/templateinstance_controller_test.go
- test/extended/testdata/bindata.go
- test/extended/testdata/templates/templateservicebroker_bind.yaml
Still need to resolve https://bugzilla.redhat.com/show_bug.cgi?id=1568607
merging this allows the creation of CRDs, but GC is still going to do weird things.
fixes https://github.com/openshift/origin/issues/19368
> allow template instance controller to create CRDs

- test/integration/ownerrefs_test.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/gc/gc_admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/gc/gc_admission_test.go
Create and delete aren't the same thing, but the alternatives seem worse.  This stops checking for deletion powers on create.
WIP so we don't accidentally merge this without an upstream pull.
@bparees @openshift/sig-master
> don't block creation on lack of delete powers

- pkg/oc/admin/diagnostics/diagnostics/README.md
- pkg/oc/admin/diagnostics/diagnostics/systemd/unit_status.go
- For openshift version >= 3.10, openvswitch on the node will be run as a daemonset
so it won't appear on node systemd units.
> Bug 1572179 - Remove openvswitch check from UnitStatus diagnostic 

- pkg/network/node/multitenant.go
- pkg/network/node/networkpolicy.go
- pkg/network/node/ovscontroller.go
- pkg/network/node/ovscontroller_test.go
- pkg/network/node/singletenant.go
- pkg/util/ovs/fake_ovs.go
- pkg/util/ovs/fake_ovs_test.go
- pkg/util/ovs/ovs.go
- pkg/util/ovs/ovs_test.go
- Leverages ovs.bundle() to perform atomic transactions
- Now ovs.Transaction interface has AddFlow(), DeleteFlows() and Commit() methods
General usage:
otx := ovs.NewTransaction()
otx.AddFlow(flow1) // No execution, only caches flow context
...
otx.DeleteFlows(flowN) // No execution, only caches flow context
...
err := otx.Commit() // Executes all cached flows as single atomic transaction
- With this change, most of the operations in ovs controller like setup,
addHostSubnet, addService, etc. has only one ovs bundle call. So there
won't be partial commited changes and it reduces the downtime during
watch resync events.
> OpenShift SDN: Changed ovs.Transaction from pseudo to real atomic transaction

- test/extended/testdata/bindata.go
- test/extended/testdata/builds/test-imageresolution-custom-build.yaml
- test/extended/testdata/builds/test-imageresolution-docker-build.yaml
- test/extended/testdata/builds/test-imageresolution-s2i-build.yaml
- test/extended/testdata/builds/test-imagesource-buildconfig.yaml
Ruby examples in image stream test rely on ruby 2.2, tests images were built on ruby 2.3. Leads to test flake where scl cannot find ruby 2.2.
> Fix ruby version skew in imagestream extended tests

- test/extended/cluster/cl.go
- test/extended/cluster/context.go
- test/extended/cluster/utils.go
This function is defined in the python version [1]. We implement
it with the following modifications:
ifexists: parameter accepts values : reuse/delete. This specifies
the action to take if a namespace/project already exists. This
field is *mandatory*.
* reuse: Reuse the existing project and create all the specified
objects under it. If the projects do not exist, an error will
be raised.
* delete: If exists, delete the project and proceed.
[1]. https://github.com/openshift/svt/blob/master/openshift_scalability/README.md
> Handle project existence in cluster-loader

- vendor/k8s.io/kubernetes/pkg/features/kube_features.go
- vendor/k8s.io/kubernetes/pkg/kubelet/types/pod_update.go
- vendor/k8s.io/kubernetes/pkg/kubelet/types/pod_update_test.go
If we pursue the static pod based deployment topology, we should extend the critical pod support to openshift-* namespaces pending priority/preemption graduation in kubernetes.
input from @smarterclayton @liggitt @sjenning @aveshagarwal appreciated.
> UPSTREAM: <carry>: pods in openshift-* namespace can be marked critical

- vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_sandbox.go
- vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_sandbox_test.go
If the CNI network plugin completes successfully, but something fails
between that success and dockerhsim's sandbox setup code, plugin resources
may not be cleaned up. A non-trivial amount of code runs after the
plugin itself exits and the CNI driver's SetUpPod() returns, and any error
condition recognized by that code would cause this leakage.
The Kubernetes CRI RunPodSandbox() request does not attempt to clean
up on errors, since it cannot know how much (if any) networking
was actually set up. It depends on the CRI implementation to do
that cleanup for it.
In the dockershim case, a SetUpPod() failure means networkReady is
FALSE for the sandbox, and TearDownPod() will not be called later by
garbage collection even though networking was configured, because
dockershim can't know how far …
> UPSTREAM: 62874: dockershim/sandbox: clean up pod network even if SetUpPod() failed

- pkg/network/node/egressip.go
- pkg/network/node/egressip_test.go
After talking with @knobunc , here's the first half of #19578 as a separate PR... that way we can merge this sooner and if there are any bugs in the reorg part we'll catch them early.
Mostly this is just code reorganization; the only user-visible change is:
In preparation for later fully supporting multiple NetNamespace
EgressIPs, begin sanity-checking all of them (so that if namespace A
has EgressIPs ["1.2.3.4", "1.2.3.6"] and namespace B has EgressIPs
["1.2.3.5", "1.2.3.6"], that's considered an error even though
"1.2.3.6" would never get used by the current code).
@openshift/sig-networking PTAL
> Auto egress IP code reorg in prep for future features

- images/router/haproxy/conf/haproxy-config.template
- pkg/router/template/plugin.go
- pkg/router/template/template_helper.go
- pkg/router/template/template_helper_test.go
- pkg/router/template/util/haproxy/map_entry.go
- pkg/router/template/util/haproxy/map_entry_test.go
- pkg/router/template/util/haproxy/types.go
- pkg/router/template/util/util.go
- pkg/router/template/util/util_test.go
@smarterclayton  PTAL - this is based on your comments on #19219 
It seems lot more work/code as opposed to a `grep -v | sort -r  + grep | sort -r  + cat` but on the flip side, there is more testing around the map generation code. 
/cc @knobunc
> Second version of helper code for sorting map files.

- test/extended/builds/jenkins_plugin.go
- test/extended/image_ecosystem/jenkins_plugin.go
- test/extended/testdata/bindata.go
- test/extended/testdata/jenkins-plugin/shared-resources-template.json
the wait used to work when jenkins was in a separate project which we deleted before this point .. the project delete would terminate jenkins
now that we are deferring project delete, we cannot depend on that for the `oc logs dc/jenkins -f` ... but we can just kill that when we are done and dump the data we got
> Fix jenkins plugin hang

- pkg/oc/cli/util/clientcmd/factory_client_access.go
We have a vanity setting for OC_EDITOR.  There's no real reason, we should use the "standard" from upstream.
```release-note
oc edit now respects KUBE_EDITOR.  OC_EDITOR support will be removed in a future release, switch to KUBE_EDITOR.
```
> start collapsing onto upstream env vars

- pkg/cmd/server/crypto/crypto.go
- pkg/cmd/util/crypto.go
- pkg/route/apis/route/validation/validation.go
- pkg/service/controller/servingcert/cryptoextensions/doc.go
- pkg/service/controller/servingcert/cryptoextensions/extensions.go
- pkg/service/controller/servingcert/cryptoextensions/serversigning.go
- pkg/service/controller/servingcert/secret_creating_controller.go
- pkg/service/controller/servingcert/secret_creating_controller_test.go
- pkg/service/controller/servingcert/secret_updating_controller.go
`pkg/cmd/server/crypto` is used by everything that serves endpoints and by client and controller code for using certificates.  This snips the links to code that doesn't need to move to library-go.
/assign @liggitt
> snip links to libraries that cannot be included in library-go

- hack/import-restrictions.json
- pkg/cmd/server/crypto/crypto.go
- pkg/cmd/util/crypto.go
- pkg/controller/ownerref.go
- pkg/controller/ownerref_test.go
- pkg/route/apis/route/validation/validation.go
- pkg/service/controller/servingcert/cryptoextensions/doc.go
- pkg/service/controller/servingcert/cryptoextensions/extensions.go
- pkg/service/controller/servingcert/cryptoextensions/serversigning.go
- pkg/service/controller/servingcert/secret_creating_controller.go
- pkg/service/controller/servingcert/secret_creating_controller_test.go
- pkg/service/controller/servingcert/secret_updating_controller.go
Builds on a previous pull.  We'll move the content of pkg/controller into library-go (and perhaps ultimately into kube).  this removes the last non-portable links to kube/kube and openshift/orign.  After updating library-go and vendoring back here, it should be possible to move the SSCS to openshift/service-serving-cert-signer.
/assign @liggitt 
@openshift/sig-security fyi.  I don't think there's anything contentious in the pull
>  remove final troublesome deps from SSCS

- publishing-kube-rules.yaml
- publishing-rules.yaml
openshift/kubernetes has the 1.10.2 branch merged and the fork repos have the branch created. need the publish bot to start fanning those out, then will bump deps in https://github.com/openshift/origin/pull/19684
> update publishing rules for 1.10.2

- images/node/system-container/manifest.json
- images/node/system-container/service.template
Both of these services have been removed in 3.10.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1572868
/cc @giuseppe @smarterclayton 
/assign @giuseppe @smarterclayton
> Remove old service dependencies from node system container

- pkg/oc/bootstrap/clusterup/kubeapiserver/openshift_apiserver.go
- pkg/oc/bootstrap/clusterup/kubeapiserver/openshift_controller.go
- pkg/oc/bootstrap/clusterup/kubelet/dns.go
Write YAML to disk instead of JSON as projects using cluster up might depend on patching
the YAML and having JSON makes their live harder.
Fixes: https://github.com/openshift/origin/issues/19671
/cc @deads2k
> up: use YAML instead of JSON for configs

- pkg/oc/bootstrap/docker/run_self_hosted.go
- pkg/oc/bootstrap/docker/up.go
This sets the right `imagePullPolicy` for components added by cluster add (which is also called from cluster up). 
/cc @deads2k @soltysh
> up: add pull policy to context and pass it properly to cluster add

- test/extended/deployments/deployments.go
- test/extended/deployments/util.go
- test/extended/testdata/bindata.go
- test/extended/testdata/deployments/custom-deployment.yaml
- test/extended/testdata/deployments/deployment-example.yaml
- test/extended/testdata/deployments/deployment-history-limit.yaml
- test/extended/testdata/deployments/deployment-ignores-deployer.yaml
- test/extended/testdata/deployments/deployment-image-resolution-is.yaml
- test/extended/testdata/deployments/deployment-image-resolution.yaml
- test/extended/testdata/deployments/deployment-min-ready-seconds.yaml
- test/extended/testdata/deployments/deployment-simple.yaml
- test/extended/testdata/deployments/deployment-trigger.yaml
- test/extended/testdata/deployments/deployment-with-ref-env.yaml
- test/extended/testdata/deployments/failing-pre-hook.yaml
- test/extended/testdata/deployments/generation-test.yaml
- test/extended/testdata/deployments/multi-ict-deployment.yaml
- test/extended/testdata/deployments/paused-deployment.yaml
- test/extended/testdata/deployments/readiness-test.yaml
- test/extended/testdata/deployments/tag-images-deployment.yaml
- test/extended/testdata/deployments/test-deployment-broken.yaml
- test/extended/testdata/deployments/test-deployment-test.yaml
This will make all deployments extended tests use API calls when creating the fixtures instead of using the CLI (`create -f`). Also makes sure the failure traps we have use the correct deployment config names.
/cc @tnozicka 
(this might also reveal how many broken failure traps we have ;-)
> apps: use api calls when creating dc in extended tests

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/run.go
fixes panic in kubectl
xref https://bugzilla.redhat.com/show_bug.cgi?id=1577334
> UPSTREAM: 61713: kubectl: fix a panic when createGeneratedObject failed

- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/discovery_client_test.go
Currently the server may delay sending out the response (buffering), thus we need to flush the headers always. Additionally, I've changed the error output check looking for timeout:true string, because the error is of errors.errorString type.
> UPSTREAM: 63848: Deflake discovery timeout test

- pkg/oc/cli/cmd/wrappers.go
oc specific 'RunOptions' supplies incorrect default
generator for non-RestartAlways jobs.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1577770
> Fix incorrect oc run default option

- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/discovery_client_test.go
Hopefully fixes the unit test flake we're seeing.
> UPSTREAM: 63875: make TestGetServerGroupsWithTimeout more reliable

- hack/import-restrictions.json
- pkg/oauthserver/userregistry/identitymapper/lookup_test.go
- pkg/oauthserver/userregistry/identitymapper/provision_test.go
- pkg/oauthserver/userregistry/identitymapper/strategy_add_test.go
- pkg/oauthserver/userregistry/identitymapper/strategy_claim_test.go
- pkg/oauthserver/userregistry/identitymapper/strategy_generate_test.go
- pkg/oauthserver/userregistry/identitymapper/strategy_test.go
Updates oauthserver tests to use clients for mocks instead of internal registry shims from the storage.
> remove internal openshift refs from oauthserver

- pkg/oc/generate/app/env.go
- pkg/oc/util/env/env.go
- test/cmd/env.sh
- test/cmd/images.sh
fixes: https://github.com/openshift/origin/issues/8771
reuses validators from https://github.com/kubernetes/kubernetes/pull/48986
ptal @openshift/sig-developer-experience
> oc new-app: allow 'dot' in ENV variable names

- pkg/oc/bootstrap/docker/run_self_hosted.go
- pkg/oc/bootstrap/docker/up.go
Adds a hidden, alpha, `oc cluster up --kube-only` that start just the kube pieces of the cluster.  We need something like this to test https://github.com/openshift/service-serving-cert-signer
> allow cluster up to produce a non-openshift cluster

- pkg/oc/cli/describe/printer.go
Makes the list for istag a bit more useful. Image stream image will
eventually get a list view, so also slim it down. Docker ref continues
to be the bulk of output, but no great solution today to resolve.
> Move image stream tag and image columns to -o wide

- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status_test.go
Backporting https://github.com/kubernetes/kubernetes/pull/62543
> UPSTREAM: 62543: Timeout on instances.NodeAddresses cloud provider request

- cmd/openshift-node-config/openshift-node-config.go
- pkg/cmd/server/origin/node/node.go
- pkg/cmd/server/start/start_node.go
let "openshift-node-config" and "openshift start node --write-flags"
generate the same --cluster-dns flag when 0.0.0.0 is specified in the
configuration file.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1577886
> openshift-node-config: resolve cluster-ip when 0.0.0.0 is specified

- pkg/build/apis/build/types.go
- pkg/build/builder/cmd/builder.go
- pkg/build/builder/util/consts.go
- pkg/build/controller/strategy/custom.go
- pkg/build/controller/strategy/custom_test.go
- pkg/build/controller/strategy/docker.go
- pkg/build/controller/strategy/docker_test.go
- pkg/build/controller/strategy/sti.go
- pkg/build/controller/strategy/sti_test.go
- pkg/build/controller/strategy/util.go
We were setting an `ORIGIN_VERSION` env var to an unstructured, human readable output value on the build pods that we create.  Being unstructured, it wasn't stable.  Being the version of the controllers, it wasn't guaranteed to match other versions in the system.  As it stands now, versions skew during every update.  As components are split apart, versions will skew forever.  This removes that particular env var.
> stop adding controller version to build pod

- cmd/OWNERS
Now that service catalog has been moved to a separate repository, I have
no business here.
> Remove jpeeler from cmd/OWNERS

- vendor/k8s.io/kubernetes/pkg/kubectl/resource/builder.go
Fixes: https://github.com/openshift/origin/issues/19746
Seems like this has been broken since 3.7
/cc @soltysh
/sig master
> UPSTREAM: 63966: kubectl: fix Flatten() when used without Latest()

- pkg/serviceaccounts/oauthclient/oauthclientregistry.go
- pkg/serviceaccounts/oauthclient/oauthclientregistry_test.go
`pkg/serviceaccounts/oauthclient` is used by the oauthserver and the oauth apiserver.  We need to snip the kube and origin links in order to move it to library-go in a shared location.
@openshift/sig-security 
/assign @simo5 @enj
> snip dependencies in a future library-go package

- pkg/cmd/infra/router/f5.go
- pkg/cmd/infra/router/template.go
- pkg/router/controller/contention.go
- pkg/router/controller/router_controller.go
- pkg/router/controller/status.go
- pkg/router/controller/status_test.go
- test/extended/router/stress.go
- test/integration/router_without_haproxy_test.go
The conflict detection mechanism in the router did not correctly handle sync (which on large clusters could be a huge number of writes).  The informer delivers events in order - all SYNC, then updates.  Two routers starting at the beginning of the sync could conflict without detecting it until they see the first update (so O(2*routes)).  Instead of detecting conflicts in the router plugin, move detection to a side scanner that looks at the informer directly and only processes updates (so we ignore the initial sync and then rapidly start detecting updates).  This causes conflicting routers to converge quickly.
In addition, the stress test is not tuned particularly well for passing.  We create 3 routers with conflicting status and update 10 routes.  The hard stop for conflict detection is …
> Make router conflict detection work even during initial informer sync

- images/node/Dockerfile
As a result of https://github.com/openshift/origin/pull/19509, packages `iptables`, `ethtool`, and `socat` ended up being defined twice in `yum install`. This removes duplicate packages in the same command.
It is no issue, only cosmetic change
> images: remove duplicate packages

- vendor/k8s.io/kubernetes/cmd/kubelet/app/patch_volumequota.go
Follow on to https://github.com/openshift/origin/pull/19533
- Transforms `perFSGroupInGB` back to `perFSGroup` with a `Quantity` value.
- Changes the config file location to `/etc/origin/node/volume-config.yaml` so that it can be a second key to the existing `node-config-compute` configmap and everything will Just Work (tm).
xref https://bugzilla.redhat.com/show_bug.cgi?id=1579305
@derekwaynecarr @smarterclayton @jupierce
> UPSTREAM: <carry>: change config file location and restore perFSGroup to Quantity

- examples/service-catalog/service-catalog.yaml
- pkg/oc/clusterup/manifests/bindata.go
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1578936
I0516 14:16:29.464865       1 controller.go:294] error getting the cluster info configmap: "configmaps \"cluster-info\" is forbidden: User \"system:serviceaccount:kube-service-catalog:service-catalog-controller\" cannot get configmaps in the namespace \"default\": User \"system:serviceaccount:kube-service-catalog:service-catalog-controller\" cannot get configmaps in project \"default\""
> catalog: start controller with --cluster-id-configmap-namespace

- pkg/cmd/infra/router/clientcmd.go
- pkg/cmd/infra/router/f5.go
- pkg/cmd/infra/router/template.go
- pkg/cmd/openshift-controller-manager/controller/apps.go
- pkg/cmd/openshift/openshift_test.go
Drops long-deprecated (deprecated in 3.4) support for specifying credential info via envvars or a mix of kubeconfig and `--master` flags in favor of in-cluster config or explicit `--config` file
> Remove deprecated envvar-based credential support from images

- pkg/cmd/server/admin/create_bootstrappolicy_file.go
- pkg/cmd/server/bootstrappolicy/policy_test.go
- test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
Also remove the shared resource namespace flag
Fixes #15825
> Update bootstrap policy file encoding

- pkg/cmd/infra/router/template.go
- pkg/oc/admin/router/router.go
- pkg/router/metrics/health.go
- pkg/router/metrics/metrics.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/healthz/healthz.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/healthz/healthz_test.go
Create upstream commit that allows for multiple groups of checks to be associated with health checking. Using the multiple groupings differentiate the liveness and readiness probes for the Haproxy router
Bug [1550007](https://bugzilla.redhat.com/show_bug.cgi?id=1550007)
> Differentiate liveness and readiness probes for router pods

- pkg/oc/admin/diagnostics/diagnostics/cluster/network/objects.go
- Containerized openshift mode is no longer supported
Fixes one of the issue in https://bugzilla.redhat.com/show_bug.cgi?id=1572182
> Remove containerized openshift handling in network diagnostics

- pkg/build/registry/buildlog/rest.go
- pkg/oc/cli/cmd/startbuild.go
- pkg/oc/cli/cmd/startbuild_test.go
- test/extended/gssapi.sh
- test/extended/ldap_groups.sh
Fixes [bug 1575990](https://bugzilla.redhat.com/show_bug.cgi?id=1575990)
> Retrying when attempting to stream build logs

- pkg/serviceaccounts/controllers/docker_registry_service.go
- pkg/serviceaccounts/controllers/docker_registry_service_test.go
This change will make the docker registry service controller check all secrets regardless
whether the docker registry service location changed or not. This should effectively fix
all secrets in the cluster that are missing the registry DNS in the dockercfg content.
The drawback here is that the controller will now need to decode all dockercfg secrets
to perform the check, which might increase the load when the controller starts.
However, the controller resync is zero which means it won't run very often, so I think the CPU time here is worth to spend to make sure the dockercfg content in the secret is correct ;-)
Should fix https://bugzilla.redhat.com/show_bug.cgi?id=1578195
/cc @soltysh
/cc @deads2k
> sa: make docker registry service controller check all secrets

- test/extended/testdata/bindata.go
- test/extended/testdata/deployments/test-deployment-test.yaml
Attempt to fix https://github.com/openshift/origin/issues/19681
My theory is that the rollout transition fast from running to success and the logs
don't have time to capture the output. This should give the log endpoint time to
catch up with the rollout and stream the logs successfully.
(just a theory, will run this several times to see if this flake keep occuring)
/cc @tnozicka
> apps: add sleep to test hook fixture so logs can catch up

- hack/verify-imports.sh
we've caught a few of these accidentally creeping in
sample output with bad import:
```sh
$ hack/verify-imports.sh 
FAILURE after 2.000s: hack/verify-imports.sh:21: executing 'egrep -r '"github.com/openshift/origin/[^"]+"$' vendor/k8s.io/kubernetes' expecting failure: the command returned the wrong error code
Standard output from the command:
vendor/k8s.io/kubernetes/hack/e2e.go:	_ "github.com/openshift/origin/foo/bar"
There was no error output from the command.
[ERROR] [10:52:43-0400] PID 12945: hack/lib/cmd.sh:15: `return "${return_code}"` exited with status 1.
[INFO] [10:52:43-0400] 		Stack Trace: 
[INFO] [10:52:43-0400] 		  1: hack/lib/cmd.sh:15: `return "${return_code}"`
[INFO] [10:52:43-0400] 		  2: hack/verify-imports.sh:21: os::cmd::expect_failure
[INFO] [10:52:43-0400]   Exiting …
```
> ensure nothing in kubernetes depends on origin

- images/node/Dockerfile
- origin.spec
- pkg/network/common/dns.go
- pkg/network/common/dns_test.go
- pkg/network/common/egress_dns.go
- pkg/network/node/ovscontroller.go
- pkg/network/proxy/proxy.go
Also fixes bug: https://bugzilla.redhat.com/show_bug.cgi?id=1575583
>  Use dns go bindings instead of dig command for dns resolution in egress network policy

- vendor/k8s.io/kubernetes/pkg/controller/service/service_controller.go
If the service controller is processing a service that does not have type LoadBalancer and does not have any external load balancer recorded in its status, do not call the cloud provider to check for an associated load balancer.
This commit fixes bug 1571940.
https://bugzilla.redhat.com/show_bug.cgi?id=1571940
---
Note for backporting: `createLoadBalancersIfNeeded` in 3.9 returns two arguments, so the `return nil` will need to be amended as `return nil, notRetryable` in any backport to 3.9.
> UPSTREAM: 63926: Avoid unnecessary calls to the cloud provider

- test/extended/images/helper.go
- test/extended/util/cli.go
However, we don't support Docker 1.9 anymore, so this check can be
simplified.
@bparees
> Prune tests panicked when log writer was nil

- vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go
https://github.com/opencontainers/runc/pull/1805
xref https://bugzilla.redhat.com/show_bug.cgi?id=1581409
Thanks to @derekwaynecarr for the fix
Until upstream merges
/hold
> UPSTREAM: opencontainers/runc: 1805: fix systemd cpu quota for -1

- pkg/cmd/server/apis/config/types.go
- pkg/cmd/server/start/master_args.go
- test/integration/imageimporter_test.go
- test/util/server/server.go
Add an integration test that validates the whitelist. We don't set this
by default in installer, and in the future we want it to by dynamic on a
cluster.  In general, this is an optional setting.
@bparees
Enables openshift/image-registry#88
> Default config no longer sets a whitelist

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
Fixes unbounded memory growth and apiserver instability when redialing a dead etcd server
xref https://github.com/kubernetes/kubernetes/issues/62538
> UPSTREAM: 61459: etcd client add dial timeout

- pkg/oc/admin/policy/modify_roles.go
- pkg/oc/admin/policy/modify_roles_test.go
When removing a subject from a role we decided to remove the rolebinding
if no subjects are left.
This is normally a good housekeeping operation, however breaks the case
where someone wants to remove subjects from a rolebinding that is
subject to automatic reconciliation because it is part of the bootstrap
set.
Prevent role deletion if the user marks the rolebinding as protected
from reconciliation.
https://bugzilla.redhat.com/show_bug.cgi?id=1580538
> Prevent rolebinding deletion if it is protected

- test/extended/idling/idling.go
The idling extended test looks up resoures from `oc create` by resource
name.  The resource name of deploymentconfigs change to the fully
qualified group name, so we need to look them up by that now.
> Fix Idling extended test resource name for DC

- examples/storage-examples/local-examples/local-storage-provisioner-template.yaml
So it can create PVs for newly mounted devices.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1582400
> Allow local provisioner see new mounts.

- pkg/cmd/openshift-controller-manager/controller/serviceaccount.go
- pkg/serviceaccounts/controllers/docker_registry_service.go
- pkg/serviceaccounts/controllers/docker_registry_service_test.go
Adds the dns suffixed version of the docker service dns names to the dockercfg secret.  It's hardcoded because for now we have no way to configure it in openshift clusters.
@mfojtik @sdodson
> set the dns suffix for docker config secrets

- test/integration/oauth_serviceaccount_client_events_test.go
> Add an event poll for TestOAuthServiceAccountClientEvent

- pkg/oc/clusteradd/components/registry/registry_install.go
- pkg/oc/clusteradd/components/router/router_install.go
- pkg/oc/clusterup/coreinstall/components/persistent-volumes/setup_persistent_volumes.go
- pkg/oc/clusterup/docker/host/host.go
- pkg/oc/clusterup/run_self_hosted.go
- pkg/oc/clusterup/up.go
This removes support for cluster up running against remote Docker daemon (DOCKER_HOST).
/cc @deads2k 
/cc @soltysh
> up: remove support for remote docker host

- test/integration/imageimporter_test.go
- test/util/client.go
This change should make it harder to write a flaky test that uses the `test/util` package (or at least make it easier to detect that a test is going to be flaky).
/assign @simo5 @deads2k @stevekuznetsov
Since you guys thought this was a good idea :)
Fixes #16940 #16941
> Turn off client rate limiting in integration tests

- vendor/k8s.io/kubernetes/pkg/kubelet/certificate/bootstrap/BUILD
- vendor/k8s.io/kubernetes/pkg/kubelet/certificate/bootstrap/bootstrap.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/util/cert/io.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/util/certificate/certificate_store.go
The node.kubeconfig created by bootstrap will not work after the first
rotation - write bootstrap credentials into the cert store in order to
guarantee that rotation preserves that config.
Without this, SDN, the sync pod, and a few other node level actions will stop working when the pod gets rotated.
@liggitt
> UPSTREAM: 62152: Keep node.kubeconfig correct during rotation

- pkg/cmd/server/admin/create_bootstrappolicy_file.go
- pkg/cmd/server/bootstrappolicy/policy_test.go
fixes #19819 
This will also need doc updates wherever `oc process` is invoked to pass a bootstrap file to `oc auth reconcile`
> Drop template wrapping from bootstrap policy file

- images/egress/router/egress-router.sh
- images/egress/router/egress_router_test.go
- pkg/network/sdn-cni-plugin/openshift-sdn.go
Egress routers can't currently connect to their own node, because they try to do it via the macvlan, and macvlans are never able to reach their parent interface, regardless of configuration options. This fixes it so that egress-router-to-node-IP traffic gets routed via the SDN instead. This also requires a fix to the egress-router iptables NAT rules, which were being overzealous before.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1552738
> Allow egress-router to connect to its own node IP, for DNS, etc

- images/ipfailover/keepalived/lib/config-generators.sh
Internal check script does not work with current
security checks for keepalived, this patch is a
workaround for this problem.
Fixes: rhbz#1576398
> Fix VRRP check script

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1584555
Copying via `kubectl cp` from a pod to local will no longer panic if any received tar headers contain an extra "../". This can happen when specifying a remote location beyond "/" - for example:
```
$ kubectl cp mypod:/one/two/../../../etc/hosts ./
```
The above command results in a tar header containing an extra "../" in its name (../etc/hosts), causing a panic [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/cp.go#L388).
cc @soltysh
> UPSTREAM: 64573: remove extra "../" when copying from pod to local

- pkg/build/webhook/bitbucket/bitbucket.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1585663
/cc @bparees
> build: handle empty commits in bitbucket webhook payload

- hack/build-local-images.py
This change is motivated by the need to use this script in older branches. For master there's no change in behavior. The plan is to backport this to 3.10/3.9 (with the tag config changed appropriately).
> add support to build different tags in hack script

- pkg/oc/admin/migrate/storage/storage.go
This change moves the rate limiting logic in migrate storage to after both the GET and PUT have completed (instead of being in between the two operations).  This should make the command less sensitive to conflicts caused by resources that change often.
Bug 1585511
> Make API storage migration less sensitive to conflicts

- pkg/oc/cli/cmd/buildlogs.go
- pkg/oc/cli/cmd/deploy.go
- pkg/oc/cli/cmd/export.go
- pkg/oc/cli/secrets/basicauth.go
- pkg/oc/cli/secrets/dockercfg.go
- pkg/oc/cli/secrets/new.go
- pkg/oc/cli/secrets/sshauth.go
This will hide all the deprecated commands from help and everywhere else. 
> Hide deprecated commands

- pkg/oc/cli/cmd/create/route.go
currently using the --output flag with 'oc create route does not show the resulting object. I changed
that so the the file is printed reflecting the information provided in the help text
bug 1418021
https://bugzilla.redhat.com/show_bug.cgi?id=1418021
> support the --output flag in 'oc create route'

- images/dind/OWNERS
- images/egress/OWNERS
- images/ipfailover/OWNERS
- images/router/OWNERS
- pkg/cmd/infra/router/OWNERS
- pkg/oc/admin/router/OWNERS
- pkg/route/OWNERS
- pkg/router/OWNERS
- test/cmd/OWNERS
- test/end-to-end/OWNERS
- test/extended/OWNERS
- test/integration/OWNERS
- test/testdata/OWNERS
As Network Edge team lead Dan Mace should be able to review and approve changes to relevant sections of the code.
> Add Dan Mace (ironcladlou) to relevant OWNERS

- pkg/oc/admin/diagnostics/diagnostics/client/config_contexts.go
Since `projectClient, err := projectclientinternal.NewForConfig(clientConfig)` uses `err` as new value, `err` turns back to `nil` after the block and `errMsg := err.Error()` causes panic.
Fixes https://github.com/openshift/origin/issues/19573
> [diagnostics] Catch error from NewForConfig() as a new assigned error value

- pkg/util/restoptions/configgetter.go
Ensures openshift resources show up in `etcd_object_counts` (they were not before because this defaulted to zero).
@liggitt
> Poll metrics for openshift resources

- vendor/k8s.io/kubernetes/pkg/volume/configmap/configmap.go
- vendor/k8s.io/kubernetes/pkg/volume/downwardapi/downwardapi.go
- vendor/k8s.io/kubernetes/pkg/volume/projected/projected.go
- vendor/k8s.io/kubernetes/pkg/volume/secret/secret.go
- vendor/k8s.io/kubernetes/test/e2e/storage/BUILD
- vendor/k8s.io/kubernetes/test/e2e/storage/ephemeral_volume.go
Make sure ephemeral setup gets done only after
fetching the keys is successful.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1580485
/sig storage
cc @childsb
> UPSTREAM: 64855: Fix setup of ephemeral storage

- pkg/network/common/dns.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1575583#c23
> Do not throw spurious error when minTTL=0 for the domain in egress network policy

- pkg/cmd/server/start/start_master.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
DialTimeout addresses apiserver memory issues when trying to reach a dead etcd server
Etcd ordering issues fix deadlock in all-in-one, since setting DialTimeout makes etcd client construction blocking
> Set etcd DialTimeout, fix etcd start order in all-in-one

- vendor/k8s.io/kubernetes/pkg/controller/daemon/BUILD
- vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
picks https://github.com/kubernetes/kubernetes/pull/64916
This should reduce the memory overheat the `metav1.IsControlledBy` is causing on large clusters with multiple daemonsets where each daemonset basically deep copy the ownerreferences for each pod on every resync on every node (as seen in ca-central-1 memory profile).
/cc @sttts 
I think this is safe to pick for 3.10 and keep for 3.11, then drop in 3.12 when @sttts fix obsoletes this.
> UPSTREAM: 64916: improve memory footprint of daemonset simulate

- vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/reconciler/reconciler.go
Picks https://github.com/kubernetes/kubernetes/pull/64969
This pick will decrease memory allocations done by Sprintf() statement in the glog.V(5).Infof() function. 
/cc @jsafrane 
> UPSTREAM: 64969: volume: decrease memory allocations for debugging messages

- pkg/cmd/infra/router/template.go
- pkg/router/metrics/health.go
The function that was checking whether the router had synced needed to check the nilness of the target of a pointer, not the pointer itself.
I also corrected the logic so that when the routerPtr target was not defined, it says the router has not synced.
Fixes bug 1589740 (https://bugzilla.redhat.com/show_bug.cgi?id=1589740)
> Prevent a router panic when ROUTER_BIND_PORTS_AFTER_SYNC is set

- glide.lock
- glide.yaml
- vendor/github.com/golang/glog/README
- vendor/github.com/golang/glog/glog.go
- vendor/github.com/gorilla/securecookie/AUTHORS
- vendor/github.com/gorilla/securecookie/LICENSE
- vendor/github.com/openshift/client-go/glide.lock
- vendor/github.com/openshift/client-go/glide.yaml
- vendor/github.com/openshift/imagebuilder/dockerclient/client.go
- vendor/github.com/openshift/library-go/glide.lock
- vendor/github.com/openshift/library-go/glide.yaml
- vendor/github.com/openshift/service-serving-cert-signer/glide.lock
- vendor/github.com/openshift/service-serving-cert-signer/glide.yaml
Update glide.yaml to point to release branches for dependencies so we can start moving the prereq repos forward.
I also pinned glog.
/assign @liggitt
>  use release-3.10 for deps

- pkg/network/common/dns.go
- pkg/network/common/dns_test.go
- Currently, we consider minTTL as lowest TTL among all available dns
'A' records and TTL for CNAME recs are ignored. This change will get
lowest TTL for the entire chain irrespective of the dns record type.
Related bug: https://bugzilla.redhat.com/show_bug.cgi?id=1575583
> Egress DNS: Get lowest TTL from the dns resolution chain

- test/extended/testdata/bindata.go
- test/extended/testdata/router-http-echo-server.yaml
The router tests use an echo test server based on socat and Perl.  This test server runs in a container launched using the openshift/origin-base image.  However, commit 4333db3960e1f134bbf606bd5a8ea7f4fd062c93 removed Perl from openshift/origin-base, which breaks this test server.
This commit replaces Perl with Bash, printf, and sed.
This commit fixes openshift/origin#19887.
> Replace Perl with Bash in router echo test server

- pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/util/log.go
brctl (and its bridge-utils package) has been unmaintained
for years and it's functionality replaced by the 'ip' tool
from the iproute project. brctl may not be available on
systems so just use 'ip link' instead.
@knobunc @openshift/networking @pravisankar
> diagnostics: replace usage of brctl with /sbin/ip

- test/extended/testdata/bindata.go
- test/extended/testdata/router-http-echo-server.yaml
The router tests use an echo test server based on socat and Perl.  This test server runs in a container launched using the openshift/origin-base image.  However, commit 4333db3960e1f134bbf606bd5a8ea7f4fd062c93 removed Perl from openshift/origin-base, which breaks this test server.
This commit replaces Perl with Bash, printf, and sed.
This commit fixes openshift/origin#19887.
> [release-3.9] Replace Perl with Bash in router echo test server

- pkg/cmd/server/kubernetes/network/network.go
- pkg/cmd/server/kubernetes/network/options/options.go
- pkg/cmd/server/origin/dns_server.go
- pkg/cmd/server/start/start_allinone.go
- pkg/cmd/server/start/start_node.go
- pkg/dns/dnsmasq.go
- pkg/dns/dnsmasq_test.go
- pkg/dns/server.go
- pkg/dns/serviceaccessor.go
- test/util/server/server.go
Prevents dnsmasq from pending a dead server when the network pod dies or is interrupted. Also prevents us serving DNS before our caches fill.
https://bugzilla.redhat.com/show_bug.cgi?id=1584995
> Remove the node from dnsmasq config when shutting down

- vendor/k8s.io/kubernetes/pkg/kubelet/certificate/bootstrap/bootstrap.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/util/cert/io.go
If we create a new key on each CSR, if CSR fails the next attempt will
create a new one instead of reusing previous CSR.
If approver/signer don't handle CSRs as quickly as new nodes come up,
they can pile up and approver would keep handling old abandoned CSRs and
Nodes would keep timing out on startup.
> UPSTREAM: 65063: Re-use private key after failed CSR

- pkg/oc/bootstrap/docker/openshift/helper.go
pick https://github.com/openshift/origin/pull/19908 for origin 3.9 (to run tests), will pick this for ose.
/cc @soltysh 
/cc @thoraxe 
> [3.9] up: default openshift imagepolicy admission

- test/extended/networking/networkpolicy.go
The cni vendor tests were not including the Network Policy tests by default. Fix the ginkgo keyword so that they are included.
> Include the keyword Area:Networking for NetworkPolicy tests

- pkg/serviceaccounts/controllers/docker_registry_service.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1591632
@deads2k doing the initial sweep and correction of dockercfg secrets revealed a bug where we accidentally override user-specified secrets as well.
/cherrypick release-3.9
> serviceaccounts: do not manage pull secrets created by third parties

- images/node/scripts/openshift-node
Fix rhbz https://bugzilla.redhat.com/show_bug.cgi?id=1587824. With experimental-allowed-unsafe-sysctls,
"*" is a valid character now as part of kubelet arguments. For example:
```
kubeletArguments:
experimental-allowed-unsafe-sysctls:
- 'kernel.shm*,kernel.msg*,kernel.sem,fs.mqueue.*,net.*'
```
@sjenning @smarterclayton 
Related PR to openshift-ansible: https://github.com/openshift/openshift-ansible/pull/8772
> Fix to pass quoted unsafe strings (with characters like *,<,%) correctly to kubelet

- cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/validation/binding.go
- cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/pkg/apis/servicecatalog/validation/binding_test.go
- cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_broker.go
- cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_broker_test.go
- cmd/service-catalog/go/src/github.com/kubernetes-incubator/service-catalog/pkg/controller/controller_test.go
Update service catalog to v0.1.9.1 for https://bugzilla.redhat.com/show_bug.cgi?id=1586135. This should not be merged until both https://github.com/openshift/origin/pull/19918 and https://github.com/openshift/aos-cd-jobs/pull/1434 are merged and the catalog test re-run.
> Service Catalog patch update to v0.1.9.1

- pkg/oc/admin/diagnostics/diagnostics/cluster/network/in_pod/util/util.go
- In case of OCP, generated defaults for 3.10 release:
--pod-image=registry.access.redhat.com/openshift3/ose-control-plane:v3.10
--test-pod-image=registry.access.redhat.com/openshift3/ose-deployer:v3.10
- In case of origin, generated defaults for 3.10 release:
--pod-image=openshift/origin-control-plane:v3.10
--test-pod-image=openshift/origin-deployer:v3.10
- For testing on AWS, user need to manually pass the image params
--pod-image=registry.reg-aws.openshift.com:443/openshift3/ose-control-plane:v3.10
--test-pod-image=docker.io/openshift/hello-openshift
> Fix default image paths used in network diagnostics

- pkg/oc/admin/migrate/storage/storage.go
This change correctly casts the dividend to a float before division to prevent integer floor division.  The dividend is too large and the divisor is too small for this to matter in practice.
/assign @simo5
> Fix math division truncation in migrate storage

- pkg/network/node/networkpolicy.go
Similar to #19869 but different, and not caused by "new features" in this case. In theory, NetworkPolicy allows you to say:
kind: NetworkPolicy
spec:
podSelector:
ingress:
- ports
- protocol: TCP
meaning "allow all TCP ports but no UDP ports". This is a dumb feature, and we don't bother to implement it, but we were accidentally crashing if we saw a NetworkPolicy like that. (Which only happened because someone created a NetworkPolicy with broken indentation that caused parts of it to be parsed as the wrong subfield.)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1591584
> Fix a crash on a certain type of unsupported NetworkPolicy

- pkg/cmd/server/apis/config/types.go
- pkg/cmd/server/apis/config/v1/swagger_doc.go
- pkg/cmd/server/apis/config/v1/testdata/master-config.yaml
- pkg/cmd/server/apis/config/v1/types.go
- pkg/oauthserver/authenticator/password/keystonepassword/keystonepassword.go
- pkg/oauthserver/authenticator/password/keystonepassword/keystonepassword_test.go
- pkg/oauthserver/oauthserver/auth.go
This code prevents situations when, after removing a user
account in Keystone, a new user with the same name can
see all the resources available to the previous user.
This is achieved by storing the user ID instead of his name
in the identity, i.e. "<provider_name>:<keystone_user_id>".
If the identifier of the new user does not match what is
stored in the identity, then the user's request to login
to the system is rejected, even if he entered the correct
password.
For backward compatibility reasons new boolean config option
"useKeystoneIdentity" was added for the provider. If it is
set to false, the old behavior will be used, i.e. authentication
by username.
Default value is false.
> Allow to reject login if the user id does not match the id in Keystone

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp_test.go
Addresses an issue where copying from a remote location containing path
shortcuts (podName:../../../tmp/foo) causes an index out of range panic.
UPSTREAM: https://github.com/kubernetes/kubernetes/pull/65189
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1592324
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1584555
cc @soltysh
> UPSTREAM: 65189: fix paths w shortcuts when copying from pods

- pkg/oc/cli/cmd/rsync/copyrsync.go
- pkg/oc/cli/cmd/rsync/copyrsyncd.go
- pkg/oc/cli/cmd/rsync/rsync.go
- test/extended/cli/rsync.go
Fixes #19365
Add --no-owner and --no-group as defaults to rsync command, --omit-dir-times was already there
Also refactored the default flags that are passed to rsync to de-duplicate code.
> adds --no-owner and --no-group flags to oc rsync

- pkg/oc/admin/image/verify-signature.go
https://bugzilla.redhat.com/show_bug.cgi?id=1461324
> Bug 1461324 - Log image changes on verify-image-signature without --save

- cmd/openshift/openshift.go
- pkg/cmd/openshift/openshift.go
- pkg/cmd/openshift/openshift_test.go
- pkg/cmd/server/start/command_test.go
- pkg/cmd/server/start/start_allinone.go
- pkg/cmd/server/start/start_node.go
- tools/clicheck/check_cli_conventions.go
- tools/genman/gen_man.go
This reverts commit 8377bcdebcd69e96dec9b6545fa4829a1661487c.
This change needs to be layered on top of
https://github.com/kubernetes/kubernetes/pull/63859 to avoid duplicate
signal handler registrations.
Conflicts:
pkg/cmd/openshift/openshift_test.go
> Revert "Make NewCommandStartNode() handle SIGTERM and SIGINT"

- pkg/image/controller/factory.go
- pkg/image/controller/imagestream_controller.go
- pkg/image/controller/imagestream_controller_test.go
- pkg/image/controller/metrics.go
- pkg/image/controller/scheduled_image_controller.go
- pkg/image/metrics/prometheus/metrics.go
Implemented two counters:
openshift_imagestreamcontroller_success_count{
// processed in scheduled or new queue
scheduled: bool,
// just the registry's hostname
registry: "...",        // e.g. docker.io
}
openshift_imagestreamcontroller_error_count{
// processed in scheduled or new queue
scheduled: bool,
registry: "...",
// e.g. “Unauthorized”
reason: tagEventList.Conditions[0].Reason,
}
> Prometheus metrics for image import controllers

- hack/import-restrictions.json
Some IDEs, when not set properly, automatically add imports and include references to staging, which should never be imported directly, only through the vendor symlinks.
/cc @mfojtik
> Verify that someone isn't accidentally importing staging

- pkg/oc/generate/app/pipeline.go
- pkg/oc/generate/cmd/describe.go
- test/cmd/newapp.sh
https://trello.com/c/BOR33gza/1559-3-reuse-existing-imagestreams-with-new-app-appcreationtechdebt
> Resuse existing imagestreams with new-app

- images/origin/Dockerfile
fix https://bugzilla.redhat.com/show_bug.cgi?id=1582059
> install ceph-common in control plane so rbd provisioner can find rbd cli to create rbd images

- vendor/k8s.io/kubernetes/pkg/volume/aws_ebs/BUILD
- vendor/k8s.io/kubernetes/pkg/volume/aws_ebs/aws_ebs.go
- vendor/k8s.io/kubernetes/pkg/volume/azure_dd/BUILD
- vendor/k8s.io/kubernetes/pkg/volume/azure_dd/azure_provision.go
- vendor/k8s.io/kubernetes/pkg/volume/azure_file/azure_provision.go
- vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder.go
- vendor/k8s.io/kubernetes/pkg/volume/flocker/flocker_volume.go
- vendor/k8s.io/kubernetes/pkg/volume/gce_pd/gce_pd.go
- vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
- vendor/k8s.io/kubernetes/pkg/volume/host_path/host_path.go
- vendor/k8s.io/kubernetes/pkg/volume/photon_pd/photon_pd.go
- vendor/k8s.io/kubernetes/pkg/volume/portworx/portworx.go
- vendor/k8s.io/kubernetes/pkg/volume/quobyte/quobyte.go
- vendor/k8s.io/kubernetes/pkg/volume/rbd/BUILD
- vendor/k8s.io/kubernetes/pkg/volume/rbd/rbd.go
- vendor/k8s.io/kubernetes/pkg/volume/scaleio/sio_volume.go
- vendor/k8s.io/kubernetes/pkg/volume/storageos/storageos.go
- vendor/k8s.io/kubernetes/pkg/volume/util/util.go
- vendor/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume.go
- vendor/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go
Upstream: kubernetes/kubernetes#64447
Fixes: http://bugzilla.redhat.com/show_bug.cgi?id=1583058
/sig storage
/assign @gnufied @tsmetana @childsb
> UPSTREAM: 64447: Add block volume support to internal provisioners

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp_test.go
This reverts commit 6359a955909ce54b1d00a54757f68bffc6a81e71.
The upstream master PR did not merge because of some issues found, and the 1.11 PR was reverted. We don't want this to go into 3.10 as is
> UPSTREAM: 65189: revert: fix paths w shortcuts when copying from pods"

- glide.lock
- vendor/k8s.io/kubernetes/pkg/volume/aws_ebs/BUILD
- vendor/k8s.io/kubernetes/pkg/volume/aws_ebs/aws_ebs.go
- vendor/k8s.io/kubernetes/pkg/volume/azure_dd/BUILD
- vendor/k8s.io/kubernetes/pkg/volume/azure_dd/azure_provision.go
- vendor/k8s.io/kubernetes/pkg/volume/azure_file/azure_provision.go
- vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder.go
- vendor/k8s.io/kubernetes/pkg/volume/flocker/flocker_volume.go
- vendor/k8s.io/kubernetes/pkg/volume/gce_pd/gce_pd.go
- vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
- vendor/k8s.io/kubernetes/pkg/volume/host_path/host_path.go
- vendor/k8s.io/kubernetes/pkg/volume/photon_pd/photon_pd.go
- vendor/k8s.io/kubernetes/pkg/volume/portworx/portworx.go
- vendor/k8s.io/kubernetes/pkg/volume/quobyte/quobyte.go
- vendor/k8s.io/kubernetes/pkg/volume/rbd/BUILD
- vendor/k8s.io/kubernetes/pkg/volume/rbd/rbd.go
- vendor/k8s.io/kubernetes/pkg/volume/scaleio/sio_volume.go
- vendor/k8s.io/kubernetes/pkg/volume/storageos/storageos.go
- vendor/k8s.io/kubernetes/pkg/volume/util/util.go
- vendor/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume.go
- vendor/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go
prior to switching the bot to publish from release-3.10, update to latest state of the kube branch
> [3.10] bump(*): update to kube 3.10 branch

- glide.lock
- vendor/github.com/openshift/imagebuilder/dockerclient/archive.go
- vendor/github.com/openshift/imagebuilder/dockerclient/archive_test.go
- vendor/github.com/openshift/imagebuilder/dockerclient/client.go
- vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_1
- vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_10
- vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_2
- vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_3
- vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_4
- vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_5
- vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_6
- vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_7
- vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_8
- vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_9
- vendor/github.com/openshift/imagebuilder/dockerclient/testdata/copyfrom/Dockerfile
A dockerfile with
```
FROM a AS a
RUN mkdir -p /a/b && touch /a/b/1
FROM b
COPY --from=a /a/b/* /a
```
would fail with an lstat error because we were not properly handling
wildcards on archives. Added more tests and verified the included
scenarios were correct.
@liggitt one more, found this while testing copying an entire directory over.
openshift/imagebuilder#81
> 3.10: imagebuilder: Some `COPY --from` statements would fail

- pkg/network/node/cniserver/cniserver.go
- pkg/network/node/cniserver/cniserver_test.go
- pkg/network/node/node.go
- pkg/network/node/pod.go
- pkg/network/node/pod_test.go
- pkg/network/sdn-cni-plugin/openshift-sdn.go
- pkg/network/sdn-cni-plugin/sdn_cni_plugin_test.go
https://github.com/openshift/origin/pull/19885 allows egress routers to
connect to the node IP but when openshift node is configured to use
service network IP as DNS IP then egress router pod will not be able
to resolve DNS requests. This change will address this issue.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1594958
> Allow egress-router to connect to cluster service network for DNS, etc.

- pkg/oc/clusterup/coreinstall/components/components.go
- pkg/oc/clusterup/up.go
Fixes: https://github.com/openshift/origin/issues/20062
With this change, the cluster up will write list of enabled components into empty base-dir. On subsequent run, it will read the list and use it instead of using the "default" list.
This fix a case when user disable particular component, but subsequent run will re-enable it (if it is default component).
/cc @deads2k
> up: store components user ran cluster up

- pkg/oc/cli/cmd/startbuild.go
I was able to create a zip archive that was as little as 183 bytes with valid but very short Dockerfile as the only file, so the peek was too large even for an archive created differently than from git repo and should probably not warn a false alarm
ptal @openshift/sig-developer-experience 
including the conversation for reference https://github.com/openshift/origin/pull/20090
also, I think the magic number for .gz was not completely correct, it had an extra byte (which is used to signal "deflate" compression algorithm but the byte can have different values as well and still denote .gz archive)
RFC for reference: https://tools.ietf.org/html/rfc1952
> start-build: remove false alarm warning for repo binary input

- images/node/system-container/config.json.template
This goes hand-in-hand with https://github.com/openshift/openshift-ansible/pull/8964 for fixing flex volume plugin when kubelet runs as system container.
We will have to cherry-pick this to 3.10 too.
cc @jsafrane 
/sig storage
> Bind mount /etc/origin/kubelet-plugins for flex volumes

- hack/import-restrictions.json
- pkg/oc/cli/cmd/importimage.go
~`WATCH` doesn't work with RBAC `resourceNames` as well as `GET`. Changing the `waitForImport` to poll a `GET` instead.~
fixes https://github.com/openshift/origin/issues/13214
~NOTE: I selected both pollPeriod: `1*time.Second` and pollTimeout: `60*time.Second` based on what I saw when going over a couple of polls in our codebase but not sure if it is appropriate and fits here.~
ptal @openshift/sig-developer-experience
> oc import-image: deprecate legacy path using annotations

- pkg/network/node/egressip.go
- pkg/network/node/egressip_test.go
- pkg/network/node/vxlan_monitor.go
- pkg/network/node/vxlan_monitor_test.go
- pkg/util/ovs/ovs.go
OK, this changes the semantics of automatic egress IPs so that:
- You are now allowed to specify multiple IPs in the `EgressIPs` field of a `NetNamespace`, and if so, the first one in the list that is currently hosted on a node will be used.
- However, if *any* of the IPs in the list are duplicates of IPs used by another namespace, then the namespace will be considered broken (and egress traffic will be dropped). Previously this rule only applied if the *first* IP was a duplicate, since further IPs were simply ignored.
- If a namespace specifies multiple egress IPs, and the node hosting its current egress IP stops responding, then nodes will automatically switch to using the namespace's next available egress IP. (Each node does this independently, when it notices that packets are being …
> Basic high availability for auto egress IPs

- pkg/cmd/server/apis/config/v1/types.go
- pkg/cmd/server/start/start_node.go
- pkg/oauthserver/osinserver/osinserver_test.go
- pkg/oc/cli/describe/describer.go
- pkg/security/securitycontextconstraints/provider_test.go
- test/integration/dockerregistryclient_test.go
- test/integration/imageimporter_test.go
- test/integration/oauth_cert_fallback_test.go
- test/integration/oauthstorage_test.go
- tools/rebasehelpers/godepchecker/godepchecker.go
@smarterclayton the unit weren't flakes.  They were failing one these directives https://unsid.com/openshift/pull-ci-origin-unit/690/ which set non-zero return values.
> fix the go 1.10 unit test failures

- test/extended/router/stress.go
This was a fencepost condition in the test.
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20173/pull-ci-origin-e2e-gcp/304/
> Sometimes stress test takes exactly 30 times

- pkg/build/admission/buildpodutil.go
- pkg/build/admission/strategyrestrictions/admission.go
- pkg/build/admission/strategyrestrictions/admission_test.go
- pkg/build/admission/testutil/pod.go
- pkg/build/apis/build/validation/validation.go
- pkg/build/buildscheme/scheme.go
- pkg/build/buildscheme/scheme_test.go
- pkg/build/controller/build/build_controller.go
- pkg/build/controller/buildconfig/buildconfig_controller.go
- pkg/build/controller/strategy/custom.go
- pkg/build/controller/strategy/custom_test.go
- pkg/build/registry/buildconfig/webhook.go
The legacy scheme is unreliable, side-effect prone.  Switching to specific encoder and decoders will ensure consistent behavior pre and post rebase.  I started this in case it had a problem like the deployer.  Doesn't look like it.
> stop using legacyscheme in builds

- hack/lib/build/environment.sh
- hack/lib/cmd.sh
- hack/lib/init.sh
- hack/lib/log/output.sh
- hack/lib/test/junit.sh
- hack/push-release.sh
- hack/test-go.sh
- tools/gotest2junit/gotest2junit.go
- tools/gotest2junit/pkg/api/junit.xsd
- tools/gotest2junit/pkg/api/string.go
- tools/gotest2junit/pkg/api/test_case.go
- tools/gotest2junit/pkg/api/test_suite.go
- tools/gotest2junit/pkg/api/types.go
- tools/gotest2junit/test/test_test.go
- tools/import-verifier/import-verifier.go
- tools/junitreport/pkg/parser/gotest/parser_nested_test.go
Update a few other small changes that were made to the common scripts,
and remove special cased output from 3.10 for pushing releases
alongside.
> Switch origin to use gotest2junit

- pkg/cmd/server/bootstrappolicy/securitycontextconstraints.go
- pkg/cmd/server/bootstrappolicy/securitycontextconstraints_test.go
https://github.com/openshift/origin/pull/20152 added a new field to SCC objects, which defaults to `true` if unspecified. The in-memory bootstrap SCC objects weren't updated to populate this field, which meant that when they were compared to objects from the server, it appeared there were differences that required them to be updated.
This round-trips the bootstrap SCC objects to make sure all the same defaults are applied to them.
Fixes spurious `reconcile-scc` output for defaulted fields
/assign @simo5
/cc @sdodson @michaelgugino
> Apply defaults to bootstrap SCCs before reconciliation

- pkg/cmd/openshift-kube-apiserver/server.go
- pkg/cmd/server/kubernetes/master/master_config.go
- pkg/cmd/server/origin/master_config.go
The loopback config from the master config might reference the master service. It is meant to be used by components which run out-of-process. The openshift-kube-apiserver though talks to itself and should use Kube's "magic" loopback client config instead, which also uses its own self-generated CA and cert (without the need to add 127.0.0.1 to the main server cert and without the need to know the master IP in advance).
Fixes https://github.com/openshift/origin/issues/20060
> openshift-kube-apiserver: use in-process loopback client config from Kube

- pkg/cmd/server/apis/config/latest/helpers.go
This change logs an error in the following format:
`Encountered config error json: unknown field "foobar" in object *config.MasterConfig`
when config data contains unknown fields.  It is written with the assumption that it will be changed to a fatal error at some future point (we will likely need to add some oc commands to help validate the various config objects).
Fixes #19914
> Log an error when config data contains unknown fields

- glide.yaml
This is an origin specific dependency used by oc to provide Kerberos support on Linux and Mac.  It is owned by the auth team.
> Pin github.com/apcera/gssapi to release-2.6.3

- hack/test-go.sh
We want to capture this for debugging in some cases
> Store the test error log and the report output to the artifacts dir

- test/extended/util/framework.go
We are getting a NotFound error the first time we try to find the
service account, not timing out.
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20217/pull-ci-origin-e2e-gcp/517/
> WaitForBuilder was too fast, not too slow

- vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher_test.go
This is a stopgap(temporary) fix for the flake, https://github.com/openshift/origin/issues/20136
This part has got changed recently, and this issue is not there at upstream kube. This PR,https://github.com/kubernetes/kubernetes/pull/65662, is cherry-picking the changed part to kube 1.11.
Meanwhile this fix will help avoiding this flake.
Implementation of `NotifyRegistrationStatus` RPC at example plugin is writing registration status to a channel that unit test is listening on. Unit test after receving data on this channel, stops the example plugin server. Here is a race. Sometimes plugin server gets closed before `NotifyRegistrationStatus` could return and thus showing error on client (plugin watcher), which if being verified in the unit test.
Fix: With this 1 ms delay, plugin server is …
> Fix pluginwatcher flake

- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_loadbalancer_internal_test.go
See https://github.com/kubernetes/kubernetes/issues/65883
> UPSTREAM: <drop>: GCE load balancer unit test is flaky

- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vsphere_test.go
Using `SetFinalizer(logout)` in vsphere code is not safe (since the
connection object has no mutex and finalizers run in other threads).
Disabling the test until resolution of https://github.com/kubernetes/kubernetes/pull/63824#issuecomment-402929418
> UPSTREAM: <drop>: vSphere test has race conditions, disable

- pkg/cmd/server/apis/config/types.go
- pkg/cmd/server/apis/config/v1/types.go
- pkg/cmd/server/apis/config/v1/zz_generated.deepcopy.go
- pkg/cmd/server/apis/config/zz_generated.deepcopy.go
- pkg/oauthserver/oauth/external/gitlab/gitlab_mux.go
- pkg/oauthserver/oauth/external/gitlab/gitlab_oauth.go
- pkg/oauthserver/oauth/external/gitlab/gitlab_oauth_test.go
- pkg/oauthserver/oauth/external/gitlab/gitlab_oidc.go
- pkg/oauthserver/oauthserver/auth.go
Update GitLab IDP to support OIDC
This change updates the GitLab IDP integration to support OpenID
Connect (while retaining support for OAuth2).  This has the benefit
of using a standard that was meant for authentication.  In a future
release this will allow us to remove the GitLab specific code from
our integration.  The GitLab OIDC provider reuses the standard OIDC
code with a GitLab specific configuration.  This change is fully
backwards compatible as the identity/user objects are unchanged.
It is not possible to detect if OIDC or OAuth2 should be used when
GitLab is configured.  Thus the configuration of the IDP has a new
field called legacy which determines if OAuth2 or OIDC should be
used.  If true, OAuth2 is used and if false, OIDC is used.  If the
value is unspecified and the …
> Update GitLab IDP to support OIDC

- test/extended/builds/contextdir.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/test-context-build.json
- test/extended/util/framework.go
speed up from 166s to 17s
```
old using s2i ruby based docker image
STEP: starting a build
Jun 12 11:54:45.365: INFO: Running 'oc start-build --config=/tmp/configfile443130924 --namespace=e2e-test-contextdir-ntbrt dockercontext'
build "dockercontext-1" started
STEP: waiting for build to finish
[AfterEach]
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/contextdir.go:38
[AfterEach] [Feature:Builds][Slow] builds with a context directory
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/test/extended/util/cli.go:72
STEP: Deleting namespaces
Jun 12 11:57:21.689: INFO: namespace : e2e-test-contextdir-ntbrt api call to delete is complet
```
```
new using busybox
STEP: …
```
> extended tests: use leaner repo for contextdir test

- pkg/build/builder/docker_test.go
I forgot to update the import path in one of the tests in https://github.com/openshift/origin/pull/20205 and found out when comparing changes with https://github.com/openshift/ose/pull/1345
> builder test: fix broken import after PR #20205

- vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/example_plugin.go
Missed to notice that timeout duration for plugin stop is also 1 sec and therefore it started flaking, which is obvious.
Related: https://github.com/openshift/origin/pull/20212#issuecomment-402805692
/cc @sjenning @smarterclayton @liggitt
> UPSTREAM: <drop>: Fix pluginwatcher flake

- images/router/haproxy/reload-haproxy
Before we were using a bunch of piped commands to pull the PID for the running haproxy processes.  It is simpler to just call pidof.
Thanks https://github.com/openshift/origin/issues/18892 for the suggestion
> Changed to pidof to find the haproxy pids

- pkg/oc/admin/router/router.go
- pkg/oc/experimental/ipfailover/ipfailover.go
Added a colon to the error message to separate the command to run from the error message.
Before:
error: router could not be created; service account "router" is not allowed to access the host network on nodes, grant access with oc adm policy add-scc-to-user hostnetwork -z router
After:
error: router could not be created; service account "router" is not allowed to access the host network on nodes, grant access with: oc adm policy add-scc-to-user hostnetwork -z router
(note the : after with)
> Fix the oc adm message when the permissions are missing

- images/node/system-container/config.json.template
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1598271
iscsiadm tries to write /var/lib/iscsi/send_targets/ (and later /var/lib/iscsi/nodes) when trying to attach an iscsi volume to the host but it fails because the filesystem in the kubelet system container (at /var/lib/iscsi) is read only. I think we should be writing this information to the host. Fix is similar to the fix for flex plugins.
I've confirmed iscsi attachment succeeds with this change.
> Bindmount /var/lib/iscsi rw for iscsi attach

- test/extended/networking/multicast.go
Otherwise it can fail while racing against the controllers.
Flaked in https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/batch/pull-ci-origin-e2e-gcp/677/
@dcbw @danwinship
> Multicast test needs to wait for NetNamespace to be created

- pkg/network/common/egressip.go
- pkg/network/common/egressip_test.go
- pkg/network/node/egressip.go
- pkg/network/node/egressip_test.go
- pkg/network/node/vxlan_monitor.go
- pkg/network/node/vxlan_monitor_test.go
Prelude to master-side egress IP tracking; the master will need to be doing the same egressIP-tracking that  the node does, so move the code to pkg/network/common so they can share it.
pkg/network/common/egressip_test.go is mostly just a copy of pkg/network/node/egressip_test.go, with the "netlink" and "OVS" changes squished together into a single change stream, and the comments changed in a few places to reflect the fact that "local node" vs "remote node" doesn't matter to the common code.
The changes at the end of pkg/network/node/egressip_test.go are because if egressIPWatcher deletes OVS flows and then recreates them, the testing code requires that we call `assertOVSChanges` rather than `assertNoOVSChanges` even if the new flows are identical to the old ones. The new code doesn't …
> Migrate egress IP tracking code to pkg/network/common

- images/router/haproxy/conf/haproxy-config.template
Adds http2 support for haproxy.
Ref: https://trello.com/c/qzvlzuyx/27-3-implement-router-http-2-support-terminating-at-the-router-router
To run: 
```
$ oc adm router --latest-images=true
$ oc set env dc/router ROUTER_ENABLE_HTTP2=true
$ #  add edge secured and/or reencrypt routes:
$ #  Example: use routes from https://github.com/ramr/nodejs-header-echo
```
Test: 
```
$ curl -k --http2 -vvv --resolve edge.header.test:443:127.0.0.1 https://edge.header.test/
$ curl -k --http2  -vvv --resolve reencrypt.header.test:443:127.0.0.1 https://reencrypt.header.test/
```
You should see that the protocol negotiation (between haproxy and the client) uses HTTP2 and there's a new header sent to the backend ` x-forwarded-proto-version: h2`.
@ironcladlou @knobunc PTAL thx
> Add http/2 support for haproxy router.

- test/extended/deployments/deployments.go
Temporary hack for DC tests to avoid a race (https://github.com/openshift/origin/issues/20225) while it gets fixed.
/cc @bparees
> Avoid race between inserting secret for internal registry into SA and creation of a Pod in DC tests

- tools/rebasehelpers/commitchecker/validate.go
- tools/rebasehelpers/commitchecker/validate_test.go
- tools/rebasehelpers/util/git.go
- vendor/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/auth/reconcile.go
- vendor/k8s.io/kubernetes/test/fixtures/pkg/kubectl/cmd/auth/rbac-v1beta1.yaml
Reverts the change that depends on internal types (kubectl is quickly moving away from those).  This will fail until https://bugzilla.redhat.com/show_bug.cgi?id=1597334 is done.
@sdodson @openshift/sig-master
> Collapse back to upstream reconcile command

- pkg/cmd/server/kubernetes/master/master_config_test.go
- pkg/quota/admission/clusterresourcequota/admission.go
- test/integration/oauth_serviceaccount_client_events_test.go
- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/options/options_test.go
- vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go
- vendor/k8s.io/kubernetes/pkg/quota/install/registry.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/BUILD
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/Godeps/Godeps.json
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/crdserverscheme/BUILD
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/crdserverscheme/unstructured.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd_test.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/error.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/scheme.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/json/json_test.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning_test.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/naming/BUILD
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/naming/from_stack.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/naming/from_stack_test.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/Godeps/Godeps.json
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/patch.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/Godeps/Godeps.json
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/BUILD
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/reflector.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/Godeps/Godeps.json
- vendor/k8s.io/kubernetes/staging/src/k8s.io/metrics/Godeps/Godeps.json
- vendor/k8s.io/kubernetes/staging/src/k8s.io/sample-apiserver/Godeps/Godeps.json
- vendor/k8s.io/kubernetes/staging/src/k8s.io/sample-controller/Godeps/Godeps.json
- vendor/k8s.io/kubernetes/test/integration/framework/serializer.go
1. track schemes by name so we know which scheme is failing
2. only ignore events for GC and quota
both are lgtm'd upstream
> upstream machinery picks

- test/extended/images/mirror.go
Sometimes progress bar could overlap with output of headers:
```
> GET /v2/e2e-test-image-mirror-6kfk4/mirror-8411f276df6b9760ff42e9f92503a1bf6236d47d/manifests/sha256:6a7d45238874e24bf677f3724ece6f8a3fccc9deae5b80be3cfe18a2f4bfc0b2 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 172.30.215.36:5000
> Accept: */*
> Authorization:bearer P7ZQZkM4TNCSbAKPnhHHSAAAAAAAAAAA
> 
0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0< HTTP/1.1 200 OK
< Content-Length: 1148
< Content-Type: application/vnd.docker.distribution.manifest.v2+json
```
This causes an error because the string `< HTTP/1.1 200 OK` is not at the beginning of the line. In this case, it will be correct to remove the unnecessary progress bar.
> Disable progress bar in curl

- Makefile
- hack/lib/constants.sh
- origin.spec
The OS_OUTPUT_GOPATH value is only set by the makefile, and an RPM build
environment won't have it set otherwise. This resulted in the RPM build
failing because the GOPATH didn't match the repo. 
Blocks 3.11 OCP builds @sosiouxme @adammhaile
> Must use `make build` in spec file to build ginkgo

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/wait/wait.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/wait/wait_test.go
- vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/helper.go
- vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/helper_test.go
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_cmd/15509/consoleText indicates that UIDs don't match so the wait never finishes.
@liggitt @soltysh @juanvallejo
> UPSTREAM: 00000: make delete waits match on UID

- pkg/cmd/server/bootstrappolicy/policy.go
- test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
- test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
To sustain registry catalog API implemented in openshift/image-registry#87
Not really necessary since registry will attempt to use user's token. But a fall-back to registry client depends on this policy.
> registry can now list image streams

- images/router/haproxy/conf/haproxy-config.template
Using an OpenShift route with several services setup for A/B testing,
and the "oc set route-backends", setting a zero weigth to a service
removes the endpoints from the haproxy backend.
This results in a loss of all existing connections, and a loss of
associated end-users sessions.
Changing:
{{ if ne $weight 0 }}
to
{{ if ge $weight 0 }}
fixes the issue.
Removing older services is then done whith the  "set route-backend" command.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1584701
> HAProxy config template: Fix weight logic for A/B testing

- hack/build-local-images.py
- hack/dind-cluster.sh
- images/dind/master/openshift-generate-master-config.sh
- images/dind/node/openshift-generate-node-config.sh
- This will be useful for dev testing router, egress router features.
- This will also help if we plan to switch dind to use newer openshift
deployment(kubelet with openshift flags, sdn/ovs/config daemonsets)
> dind: Added support for local registry to push and pull images

- test/integration/node_authorizer_test.go
The node authorizer is watch-fed, so there can be a delay between a change that adds/removes access and the access being effective.
This transitions the condition checks to retry until the expected result is returned.
View [ignoring whitespace](https://github.com/openshift/origin/pull/20304/files?utf8=%E2%9C%93&diff=split&w=1) to see the real change
> Make node authorizer integration test retry conditions

- pkg/api/legacy/authorization.go
- pkg/api/legacy/doc.go
- pkg/api/legacy/install.go
- pkg/authorization/apis/authorization/install/install.go
- pkg/authorization/apis/authorization/register.go
- pkg/authorization/apis/authorization/v1/conversion.go
- pkg/authorization/apis/authorization/v1/defaults_test.go
- pkg/authorization/apis/authorization/v1/register.go
- pkg/authorization/authorizer/personal_subjectaccessreview.go
- pkg/authorization/authorizer/scope/converter.go
- pkg/authorization/registry/localresourceaccessreview/rest.go
- pkg/authorization/registry/localsubjectaccessreview/rest.go
- pkg/authorization/registry/resourceaccessreview/rest.go
- pkg/authorization/registry/rolebindingrestriction/etcd/etcd.go
- pkg/authorization/registry/subjectaccessreview/rest.go
- pkg/cmd/server/bootstrappolicy/policy.go
- pkg/oc/admin/policy/reconcile_clusterrolebindings.go
- pkg/oc/admin/policy/reconcile_clusterroles.go
- pkg/oc/cli/describe/describer.go
- pkg/project/registry/projectrequest/delegated/delegated.go
- test/extended/templates/templateservicebroker_e2e.go
builds on https://github.com/openshift/origin/pull/20200
@gabemontero I think this solves your problem.  I'll test it on Monday.  The problem was that the kube-apiserver didn't have the ungroupified objects registered in the scheme for interpreting requests and our SAR is special.
>  use new authorization install pattern to have reliable self-SAR resolution

- pkg/oc/admin/admin.go
- pkg/oc/cli/cli.go
- pkg/oc/cli/cmd/registry/info/info.go
- pkg/oc/cli/cmd/registry/login/login.go
- pkg/oc/cli/cmd/registry/registry.go
- pkg/oc/cli/cmd/startbuild.go
- pkg/oc/cli/cmd/startbuild_test.go
- pkg/oc/cli/cmd/tag.go
- pkg/oc/cli/cmd/tag_test.go
- pkg/oc/cli/cmd/version.go
Updates `tag`, `registry/info`, `registry/login`, `version`, `startbuild` commands with upstream patterns.
cc @deads2k
> Update tag, registry-info, registry-login, version, startbuild cmds

- examples/image-streams/image-streams-rhel7.json
- pkg/oc/clusterup/manifests/bindata.go
- test/extended/testdata/bindata.go
ansible is being updated here: https://github.com/openshift/openshift-ansible/pull/9200
note that the upstream repos are not updated, so running hack/update-external-examples will revert this change.  please don't commit these files if you run that script.
> switch imagestream refs to pull from new registry

- test/extended/image_ecosystem/mongodb_replica_statefulset.go
- test/extended/image_ecosystem/mysql_replica.go
- test/extended/image_ecosystem/postgresql_replica.go
these tests are unacceptably flaky and we've burned too many engineering resources on them already.  supporting db replica functionality on the SCL images is not part of our mission at this point, so i am dumping these tests.
> disable all the problematic db replica tests

- pkg/templateservicebroker/servicebroker/provision.go
- pkg/templateservicebroker/servicebroker/servicebroker.go
Bug 1579194
Bug 1584970
This correctly handles the case when multiple provision requests come in for the same Broker Template Instance.
API changes would be a better solution, however went with this approach, since the migration costs to do the API changes would not be practical at this point.
> Bug 1579194 - Fixes handling of multiple provision request

- pkg/oc/cli/newapp/newapp.go
- pkg/oc/lib/newapp/cmd/newapp.go
fixes https://github.com/openshift/origin/issues/20002 by checking the `kind` of each resource
now it fails very early, produces following output if builds are disabled
```
oc new-app https://github.com/wozniakjan/oc_newapp_expose#env_dot_syntax                  
error: Missing required resources: Build, BuildConfig
```
ptal @openshift/sig-developer-experience, @mfojtik
> new-app: verify if API has required resources enabled

- install/openshift-apiserver/install.yaml
- install/openshift-service-cert-signer-operator/install-rbac.yaml
- install/openshift-service-cert-signer-operator/install.yaml
- pkg/oc/clusterup/coreinstall/kubeapiserver/openshift_apiserver.go
- pkg/oc/clusterup/coreinstall/kubeapiserver/openshift_controller.go
- pkg/oc/clusterup/manifests/bindata.go
- pkg/oc/clusterup/run_self_hosted.go
- test/extended/testdata/bindata.go
This makes `oc cluster up` reliant on the service cert signer project for generating the certs for the apiserver and for injecting the valid CA into the apiservices.
@smarterclayton @stevekuznetsov I saw there's a way in CI to stand up a real cluster.  Is there a similar thing for oc cluster up I could add to the CI for https://github.com/openshift/service-serving-cert-signer
> use the service cert signing project

- pkg/cmd/server/origin/aggregator.go
- pkg/cmd/server/origin/master.go
- pkg/cmd/server/origin/master_config.go
request in rebase.  This makes the InformerAccess struct stand out.
> make restmapper poststarthook a function

- pkg/cmd/server/apis/config/serialization_test.go
- pkg/image/admission/apis/imagepolicy/v1/defaults.go
fixes https://github.com/openshift/origin/issues/19775
> default resolution rule policy to the imagepolicy default

- pkg/oc/clusteradd/components/web-console-operator/web_console_operator.go
@deads2k from the godoc the defaultBackoff should be used when client fights with controllers... I wonder if this fixers the flake @smarterclayton reported.
> up: change retry to defaultBackoff

- test/extended/deployments/deployments.go
We're seeing a bunch of flakies on this test (e.g. here https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20265/pull-ci-origin-e2e-gcp-crio/1/)
Using run timeout here should help here so running a bunch of crio jobs now.
@mrunalp @smarterclayton PTAL
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
> test/extended/deployments: check for deployment completion with deploymentRunTimeout

- pkg/build/admission/jenkinsbootstrapper/admission.go
- pkg/build/admission/jenkinsbootstrapper/admission_test.go
- pkg/build/admission/jenkinsbootstrapper/jenkins/jenkins.go
- pkg/build/admission/jenkinsbootstrapper/jenkins/jenkins_test.go
- pkg/client/templateprocessing/dynamic_process.go
- pkg/cmd/server/admission/init.go
- pkg/cmd/server/admission/types.go
- pkg/cmd/server/origin/admission/plugin_initializer.go
- pkg/oc/cli/admin/createbootstrapprojecttemplate/create_bootstrap_project_template.go
- pkg/oc/cli/process/process.go
- pkg/oc/lib/newapp/cmd/template.go
- pkg/project/apiserver/apiserver.go
- pkg/project/registry/projectrequest/delegated/delegated.go
- pkg/project/registry/projectrequest/delegated/sample_template.go
- pkg/template/controller/templateinstance_controller.go
- pkg/template/templateprocessing/template.go
- pkg/template/templateprocessing/template_test.go
- test/integration/project_request_test.go
Simplify processing a template via the API and getting a result you can use with dynamic client.
post-rebase request from @mfojtik 
> make the template processing more compatible with the dynamic client

- pkg/service/controller/ingressip/service_ingressip_controller_test.go
Eliminate flakes in the TestBasicControllerFlow test by polling fake action
state rather than relying on custom fake watch consumption; the event counts on
the watch are not deterministic, and so the previous assumption of two events
doesn't always hold and causes a deadlock in the test's custom controller
handler.
Refactor the test to remove unnecessary fake watch and controller setup; just
use the fake client and its built-in watch capabilities directly.
Add stronger update validity assertions.
/xref https://github.com/openshift/origin/issues/20168
/xref [this flake](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/batch/pull-ci-origin-unit/984/#githubcomopenshiftoriginpkgservicecontrolleringressip-testbasiccontrollerflow)
/cc @openshift/sig-network-edge 
/cc …
> Stabilize ingressip controller unit test

- pkg/oc/clusteradd/components/web-console-operator/web_console_operator.go
@mfojtik @smarterclayton when I made the "retry on conflict" pull, I forgot to re-get the thing I was updating.  That means it just fails six times.
Here's the fix with the re-get.
> really fix the cluster up race

- hack/import-restrictions.json
- pkg/authorization/apis/authorization/rbacconversion/conversion.go
- pkg/oc/cli/admin/diagnostics/diagnostics/README.md
- tools/testdebug/cmd/load_etcd.go
#20322 left some stray references to `pkg/oc/admin`. In particular, the import in `tools/testdebug/cmd/load_etcd.go` causes `hack/update-deps.sh` to fail.
I don't know if the changes to `import-restrictions.json` are correct. I deleted the comment in `rbacconversion/conversion.go` because nothing in `pkg/oc` refers to that annotation anyway.
> Fix stale references to pkg/oc/admin

- test/integration/authorization_test.go
This makes sure we never accidentally re-add old endpoints we had as both cluster scoped and not in /oapi.
Request from the rebase.
> add test to ensure namespaced SAR and RAR return 404

- pkg/build/apis/build/types.go
- pkg/build/controller/build/build_controller.go
- pkg/build/registry/build/strategy.go
- test/extended/builds/failure_status.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/statusfail-oomkilled.yaml
Init container can be OOMKilled as well, that way the OOMKilled doesn't bubble up to the `pod.status.reason` but remains among `pod.status.initcontainerstatuses`.
Comparing as a string because it looks like kubelet is setting this as a raw string as well, I couldn't find any constants representing OOMKilled reason
https://github.com/openshift/origin/blob/ea877acae817559712c8d42ef2c5caee880d319d/vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_container.go#L355-L359
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1596440
ptal @openshift/sig-developer-experience
> Bug 1596440 - surface OOMKilled pod to build

- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/fake/fake.go
- vendor/k8s.io/kubernetes/pkg/kubelet/BUILD
- vendor/k8s.io/kubernetes/pkg/kubelet/cloud_request_manager.go
- vendor/k8s.io/kubernetes/pkg/kubelet/cloud_request_manager_test.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status_test.go
@ingvagabund @derekwaynecarr @sjenning
> Pick cloud resource sync manager related fixes.

- pkg/network/node/egressip.go
When ifup brings up an interface, it calls /sbin/arping to send some unsolicited ARP messages to get other hosts on the subnet to update their ARP caches to reflect the new IP assignment. (This is particularly important when the IP in question was previously on a different host.)
We were copying this behavior in the egress-router, but not when adding egress IPs. This fixes that. (The fact that we weren't doing this in earlier releases isn't a huge deal since egress IPs weren't normally moved between hosts, but with #20258 this is more important.)
It seems like there should be a cleaner/more automatic way to do this, but AFAICT there isn't.
> Use arping when claiming egress IPs

- pkg/oc/cli/startbuild/startbuild.go
The bottleneck appears to be a POST HTTP request and I am not sure there is a way to provide proper progress bar in k8 go-client REST calls
https://github.com/openshift/origin/blob/bb11f51660b665259cebcb626b2d7097bdd7af86/pkg/build/client/internalversion/buildinstantiatebinary.go#L25-L37
Making very simple "progress" measurement that tells the user every 5s that the POST is still executing
sample output:
```
Uploading directory "nodejs-ex" as binary input for the build ...
....
Uploading finished
build.build.openshift.io "bc1-12" started
```
this is a followup to https://github.com/openshift/origin/pull/19121
\cc @apupier. @openshift/sig-developer-experience
> oc start-build: provide progress on file upload

- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go
- vendor/k8s.io/kubernetes/pkg/kubelet/network/dns/dns.go
This fixes the frequent checking for resolv.conf entries on kubelet side.
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1569137
Upstream PR: https://github.com/kubernetes/kubernetes/pull/64860
/cc @derekwaynecarr
> UPSTREAM: 64860:checkLimitsForResolvConf for the pod create and update events instead of checking period

- test/integration/etcd_storage_path_test.go
Update the storage test to use discovery instead of schemes.  Uncovered some interesting gaps in the existing test.
This blocks some pulls cleaning up scheme and old API methods, so fixing things like, "why aren't you using a dynamic client" are outside the scope of this pull.
/assign @enj @liggitt
> switch etcdstorage test to be driven via discovery

- contrib/migration/migrate-network-policy.sh
- contrib/migration/unmigrate-network-policy.sh
Just noticed that the migration script still refers to NetworkPolicy by its old apiVersion.
The current version of the script still works, but we need to update it at some point.
Also added some comments while I was there. (I referred to the docs by titles rather than linking directly to a URL so that it's not linking to any specific product [Origin/OCP/Dedicated] or version.)
> Update apiVersion in migrate-network-policy.sh, add comments

- hack/import-restrictions.json
- pkg/build/client/v1/logs.go
- pkg/oc/cli/idle/idle.go
- pkg/oc/cli/idle/idle_test.go
- pkg/oc/cli/logs/logs.go
- pkg/oc/cli/logs/logs_test.go
- pkg/oc/originpolymorphichelpers/logsforobject.go
- pkg/unidling/util/scale.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/logs.go
cc @deads2k 
Depends on https://github.com/openshift/origin/pull/20362
Switches more commands to deal with external versions of objects
Picks https://github.com/kubernetes/kubernetes/pull/66352
> switch logs, idle commands to externals

- OWNERS
Automated Release Tooling needs review and approval rights
Sometimes the build team has to update build files (spec, tito,
etc). This adds tbielawa (ART team lead) to the OWNERS file for review
and approval purposes.
> Add tbielawa to OWNERS file

- pkg/oc/cli/cancelbuild/cancelbuild.go
- pkg/oc/cli/cancelbuild/cancelbuild_test.go
https://bugzilla.redhat.com/show_bug.cgi?id=1608745
sample output:
```
build.build.openshift.io/sample-pipeline-1 marked for cancellation, waiting to be cancelled
build.build.openshift.io/sample-pipeline-1 cancelled
```
> increase timeout to cancel pipeline builds, augment cancel-build status

- pkg/oc/clusterup/run_self_hosted.go
The default is something like 20 seconds.  Change it to one second to pick up the static pod manifests very quickly.
@mfojtik @sjenning
> tighten static pod manifest check frequency

- .tito/lib/origin/tagger/__init__.py
This change allows the CD process to proceed correctly when building with tito-0.6.11., It is backward compatible with the tito-0.6.10, currently in use, but out of date.
tito-0.6.11 corrects a bug. In 0.6.10 the version string is passed to ttio.tagger.VersionTagger._get_tag_for_version() with the release suffix included in the version string parameter. 0.6.11 passes the version and release in separate arguments. This change allows the build process to handle either input.
Without this change, building with tito-0.6.11 generates an error:
```
Getting latest package info from: /home/bos/mlamouri/sample/ose/.tito/packages/
atomic-openshift
Command: awk '{ print $1 ; exit }' /home/bos/mlamouri/sample/ose/.tito/packages
/atomic-openshift
Status code: 0
Command output: 3.9.37-1
Traceback (most …
```
> use the release string if tito provides it for the tag string

- pkg/build/controller/build/build_controller.go
handleCompletedBuild may be called with a nil pod, but isOOMKilled()
doesn't check whether the pod is nil first.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1608112
@bparees
Blocks upgrading api.ci to 3.11
> Prevent panic in build controller when pod has already been deleted

- pkg/network/common/egressip.go
- pkg/network/common/egressip_test.go
- pkg/network/node/egressip_test.go
Pointed out by @pravisankar while reviewing the fully-automatic egress IP stuff. This will probably need to be backported (which will probably involve backporting the `common/egressip.go` PR too).
(There is a similar bug with `NetNamespace.NetID` changing, which will be addressed by a later PR.)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1607395 (bug filed just to make sure we get QE tests)
> Update egress IPs when node changes IP

- pkg/oc/cli/cli.go
Adding the one blank between cli name and ex option.
- before
```
Examples:
ocex dockergc
```
-  after
```
Examples:
oc ex dockergc
```
> Correct the typo in the command examples comments.

- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce_disks.go
- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_test.go
- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_volumes.go
- vendor/k8s.io/kubernetes/pkg/volume/aws_ebs/aws_util.go
- vendor/k8s.io/kubernetes/pkg/volume/azure_dd/azure_provision.go
- vendor/k8s.io/kubernetes/pkg/volume/cinder/attacher_test.go
- vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder.go
- vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder_util.go
- vendor/k8s.io/kubernetes/pkg/volume/flocker/flocker_util.go
- vendor/k8s.io/kubernetes/pkg/volume/gce_pd/gce_pd.go
- vendor/k8s.io/kubernetes/pkg/volume/gce_pd/gce_pd_test.go
- vendor/k8s.io/kubernetes/pkg/volume/gce_pd/gce_util.go
- vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
- vendor/k8s.io/kubernetes/pkg/volume/photon_pd/photon_util.go
- vendor/k8s.io/kubernetes/pkg/volume/quobyte/quobyte_util.go
- vendor/k8s.io/kubernetes/pkg/volume/rbd/rbd_util.go
- vendor/k8s.io/kubernetes/pkg/volume/storageos/storageos.go
- vendor/k8s.io/kubernetes/pkg/volume/util/util.go
- vendor/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume_util.go
- vendor/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go
This fixes/mitigates https://bugzilla.redhat.com/show_bug.cgi?id=1592653
commits 1 & 2 are needed for patching GCE files cleanly. They fix a bug with GCE GiB vs GB and they were cherrypicked into kubernetes 1.11 (and 1.10) as well so there is no harm in doing the same here.
commit 3 is for patching cinder files cleanly. it is arguable whether it's needed or I should have just manually fixed the conflict but It seems harmless to me.
commit 4 is the patch I actually want to cherry-pick
> UPSTREAM: 66464: Avoid overflowing int64 in RoundUpSize and return error if overflow int

- vendor/k8s.io/kubernetes/cmd/kubelet/app/patch_volumequota.go
Follow-on carry to https://github.com/openshift/origin/pull/19533
Gracefully handle an empty `volume-config.yaml` file.
xref https://bugzilla.redhat.com/show_bug.cgi?id=1596439
@derekwaynecarr @jupierce
> UPSTREAM: <carry>: gracefully handle empty volume-config file

- pkg/image/registry/imagestream/etcd/etcd.go
- pkg/image/registry/imagestream/etcd/image.go
- test/extended/images/layers.go
Our external API and internal structure is wrong. All images are manifests, and all manifests are blobs.
In addition, a v2 schema 2 manifest references a blob that is a "config", not a "manifest".
Corrected the internal code so that the image/manifest digest now shows up in blobs, renamed the internal
field "config", and set the correct mime types and fixed tests.
Replaces https://github.com/openshift/image-registry/pull/115
> An image represents a manifest (and is a blob) and also references a config

- .tito/lib/origin/tagger/__init__.py
The prior PR that added logic to use the release value in titio tagger got the test inverted.
This PR corrects the logic.
> invert tag string selection logic

- hack/import-restrictions.json
- pkg/oauth/util/discovery.go
Trying to snip out more links coupling separate components together.  I found this easy one while tidying up the list.  It's better to have separate chains indicate their acceptance separately than pulling in the dep.
> tighten usage of oauthserver package in openshift

- hack/lib/constants.sh
This is why the size was variable - blocks can vary depending on file system.
@mfojtik
> Use `--apparent-size` in size check

- images/router/haproxy/Dockerfile
- images/router/haproxy/conf/haproxy-config.template
- pkg/router/template/template_helper.go
- pkg/router/template/util/haproxy/whitelist.go
- pkg/router/template/util/haproxy/whitelist_test.go
Changes to use a file based acl if the annotation for the ip whitelist exceeds the max haproxy config line arguments.
fixes bugz #1598738
> HAProxy router fix for ip whitelist exceeding max config arguments that haproxy allows.

- test/cmd/basicresources.sh
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/patch.go
The specific logic in the patch command that exited with code 1, was only doing so when there was no diff between an existing object and its patched counterpart. (In case of errors, we just return those, which eventually ends up exiting with code 1 anyway). This patch removes this block, as we should not be treating patch no-ops as errors.
Fixes https://github.com/kubernetes/kubernetes/issues/58212
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1609179
UPSTREAM: https://github.com/kubernetes/kubernetes/pull/66725
cc @soltysh
> UPSTREAM: 66725: update exit code to 0 if patch not needed

- images/dind/node/Dockerfile
- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/cmd.go
- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/collect.go
- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/node.go
- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/pod.go
- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/service.go
- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/util/log.go
- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/util/runtime.go
- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/results.go
- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/run_pod.go
Trello card: https://trello.com/c/YlLoBpg5/16-5-make-network-diagnostics-work-with-cri-o-runtime
> Use CRI interface instead of docker calls in network diagnostics

- .tito/lib/origin/common.py
We may need to just copy the contents of .tito/lib/ from OSE to Origin if there are more changes here.
> Injecting new required vars into origin.spec file

- pkg/oc/cli/admin/policy/authz_helpers.go
- pkg/oc/cli/admin/policy/modify_scc.go
- pkg/oc/cli/admin/policy/modify_scc_test.go
- pkg/oc/clusteradd/componentinstall/privileged.go
- pkg/oc/clusteradd/components/router/router_install.go
- pkg/oc/clusteradd/components/template-service-broker/template_service_broker.go
- pkg/oc/clusterup/coreinstall/components/persistent-volumes/setup_persistent_volumes.go
- pkg/oc/clusterup/docker/openshift/helper.go
- pkg/oc/clusterup/run_self_hosted.go
- pkg/oc/clusterup/up.go
* first commit move modify SCC to external (@enj do we use this anywhere else? the only usage I found was setup persistent volume component in cluster up...)
* second commit moves router to use external client/types
* last commit removes post-startup mutations which were there to support `oc cluster join` (which we don't support) and moves webconsole oauth client to external
This is moving us closer to cluster up extraction. 
/cc @deads2k
> sanitize some cluster up imports

- pkg/image/apiserver/registry/imagestream/etcd/etcd.go
Because images are larger than most other objects, it may take longer for
them to propagate to watchers than the changes to objects that reference
those images do (image streams, for example). When accessing an image
stream that points to images that are not in the cache, assume that the
common case is that propagation has not yet happened and retry after a
slight interval.
This prevents a race condition where we upload an image, tag it into the image stream,
then immediately try to pull it. The registry calls the /layers api which may only see
the image stream change, not the image change. A future change will return the additional
info about the missing image and let the registry make the right decision about whether
to allow the access or not.
@liggitt
Only the top commit is new, the …
> When images are not found in the cache, delay slightly and retry

- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go
- vendor/k8s.io/kubernetes/pkg/kubelet/network/dns/dns.go
This fixes the frequent checking for resolv.conf entries on kubelet side.
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1594952
Upstream PR: kubernetes/kubernetes#64860
/cc @derekwaynecarr @sjenning
> UPSTREAM: 64860:checkLimitsForResolvConf for the pod create and update events instead of checking periodically

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/top_node.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/top_pod.go
Previously, kubectl top ignored the passed in streams unless no other options were set.  This behavior is a bit confusing, and can lead to strange foot-guns (like when Origin overrides the Heapster options) from people trying to use the kubectl top code.
Now, we make use of the streams as long as something else didn'texplicitly set them in the options struct.
> UPSTREAM: 66931: Use the passed-in streams in kubectl top

- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/scc.go
- pkg/oc/cli/admin/policy/reconcile_sccs.go
Refactored `ReconcileSCCOptions.ChangedSCCs` to return two separate
`SecurityContextConstraints` arrays, one representing the SCCs
that need to be created, one that need to be updated to match
the recommended bootstrap SCCs.
The refactoring makes the code avoid unnecessary prodding of the server
for the existence of an SCC.
-----
Rebased on top of https://github.com/openshift/origin/pull/19610, requested in https://github.com/openshift/origin/pull/19610#discussion_r195723544
> Make ReconcileSCCOptions.ChangedSCCs return separate constraints slices

- hack/build-local-images.py
Replace print statements with functions to make
./hack/build-local-images runnable with python3.
---
This makes life easier for those who use python3 as the default.
> make hack/build-local-images.py runnable with py3

- README.md
/cc @smarterclayton @coverprice @sudhaponnaganti @dmueller2001
> Update README.md to reflect OKD rebranding

- pkg/oc/cli/set/buildhook.go
- test/cmd/setbuildhook.sh
Returns an error when dealing with an empty file, or no infos are returned from the resource builder.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1612023
> fix set build-hook panic on empty file

- pkg/oc/cli/admin/policy/modify_scc.go
I found that descriptions for these commands where written the other way around, am I right?
/assign @enj
> Update SCC-related commands' descriptions

- pkg/build/controller/build/build_controller_test.go
Remove extra negation by using proper "opposite" comparison operations.
Found using https://go-critic.github.io/overview#boolExprSimplify-ref
> build/controller/build: simplify bool exprs

- pkg/cmd/server/apis/config/v1/conversions.go
- pkg/cmd/server/start/master_args.go
Skipped test files to make tests fail if const value is changed.
In the normal code though, it may be better to use named constants
explicitly.
Found using https://go-critic.github.io/overview#namedConst-ref
> cmd/server: replace raw literals with named constants

- pkg/oc/originpolymorphichelpers/logsforobject.go
- test/cmd/builds.sh
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1612021
Allows --version to be specified when viewing logs for a buildconfig
cc @soltysh @deads2k
> allow versions to be specified for bc logs

- test/extended/builds/gitauth.go
- test/extended/builds/jenkins_plugin.go
- test/extended/builds/new_app.go
- test/extended/builds/pipeline.go
- test/extended/cluster/cm.go
- test/extended/deployments/deployments.go
- test/extended/image_ecosystem/mariadb_ephemeral.go
- test/extended/image_ecosystem/mongodb_ephemeral.go
- test/extended/image_ecosystem/mysql_ephemeral.go
- test/extended/image_ecosystem/mysql_replica.go
- test/extended/image_ecosystem/postgresql_replica.go
- test/extended/image_ecosystem/s2i_perl.go
- test/extended/image_ecosystem/s2i_php.go
- test/extended/image_ecosystem/s2i_python.go
- test/extended/image_ecosystem/s2i_ruby.go
- test/extended/image_ecosystem/sample_repos.go
- test/extended/images/append.go
- test/extended/router/config_manager.go
- test/extended/router/metrics.go
- test/extended/router/router.go
- test/extended/router/scoped.go
- test/extended/router/stress.go
- test/extended/util/deploymentconfigs.go
Fixes bad timing in the test. We should wait for the first deployment to finish before we start counting time for the next deployment (in case the first deployment take longer, it cuts the time from second deployment)
/cc @tnozicka 
Fixes: https://github.com/openshift/origin/issues/20522
> apps: fix extended flake

- pkg/oc/lib/describe/describer.go
Display the SuccessfulBuildsHistoryLimit and FailedBuildsHistoryLimit when running `oc describe bc/foo`
Examples:
```
// Both fields set
Builds History Limit:
Successful:	5
Failed:		3
```
```
// Only one field set
Builds History Limit:
Successful:	5
```
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1608715
> Show builds history limit settings with oc describe bc/foo

- pkg/cmd/server/admission/init.go
- pkg/cmd/server/origin/admission/plugin_initializer.go
- pkg/cmd/server/origin/master.go
- pkg/cmd/server/origin/master_config.go
- pkg/cmd/server/origin/openshift_apiserver.go
- pkg/image/apis/image/helper.go
- pkg/image/apis/image/validation/validation_test.go
- pkg/image/apis/image/validation/whitelist/whitelister.go
- pkg/image/apiserver/apiserver.go
- pkg/image/apiserver/registry/imagestream/etcd/etcd.go
- pkg/image/apiserver/registry/imagestream/etcd/etcd_test.go
- pkg/image/apiserver/registry/imagestream/strategy.go
- pkg/image/apiserver/registry/imagestream/strategy_test.go
- pkg/image/apiserver/registry/imagestreamimage/rest_test.go
- pkg/image/apiserver/registry/imagestreammapping/rest.go
- pkg/image/apiserver/registry/imagestreammapping/rest_test.go
- pkg/image/apiserver/registry/imagestreammapping/strategy.go
- pkg/image/apiserver/registry/imagestreamtag/rest_test.go
- pkg/image/apiserver/registryhostname/environmentresolvercache.go
- pkg/image/apiserver/registryhostname/environmentresolvercache_test.go
- pkg/image/apiserver/registryhostname/retriever.go
This tightens usage of the image registry hostname which is needed to make admission config managable which is needed to make a split kube/openshift server start tractable.
/assign @bparees @mfojtik
> clean up image registry hostname retrieval

- pkg/router/template/configmanager/haproxy/manager.go
we need to simulate an actual change otherwise router commit doesn't call reload (as it detects no diffs), so use a generated name and cleanup after.
fixes bugz #1612019
> Fix for router with dynamic config changes not reloading 

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/drain.go
An upstream pick for Kubectl drain podEvictions. Bugzilla [1586120](https://bugzilla.redhat.com/show_bug.cgi?id=1586120).
> UPSTREAM 64896: kubectl: wait for all errors and successes on podEviction

- hack/lib/constants.sh
@smarterclayton or @liggitt can one of you please merge this so we can unblock the builds?
New size is 31, so just bumped one above that. But I can set to whatever you want.
> Increasing allowed openshift-node-config size

- pkg/client/genericinformers/interface.go
- pkg/cmd/openshift-controller-manager/controller/apps.go
- pkg/cmd/openshift-controller-manager/controller/authorization.go
- pkg/cmd/openshift-controller-manager/controller/build.go
- pkg/cmd/openshift-controller-manager/controller/image.go
- pkg/cmd/openshift-controller-manager/controller/ingress.go
- pkg/cmd/openshift-controller-manager/controller/interfaces.go
- pkg/cmd/openshift-controller-manager/controller/network.go
- pkg/cmd/openshift-controller-manager/controller/network_sdn.go
- pkg/cmd/openshift-controller-manager/controller/project.go
- pkg/cmd/openshift-controller-manager/controller/quota.go
- pkg/cmd/openshift-controller-manager/controller/security.go
- pkg/cmd/openshift-controller-manager/controller/service.go
- pkg/cmd/openshift-controller-manager/controller/serviceaccount.go
- pkg/cmd/openshift-controller-manager/controller/template.go
- pkg/cmd/openshift-controller-manager/controller/unidling.go
- pkg/cmd/openshift-controller-manager/controller_manager.go
- pkg/cmd/server/origin/informers.go
- pkg/cmd/server/origin/master_config.go
- test/integration/buildcontroller_test.go
The controller manager and apiserver now have very different sets of informers and some of my other separate work is hitting construction problems so I'm separating these here.
> separate controller manager and apiserver informers

- pkg/network/common/egressip.go
- pkg/network/common/egressip_test.go
The EgressIPTracker has to keep track of every egress IP value that is referenced by *either* a node or a namespace, but we should not be auto-assigning egress IPs that are not currently assigned to a namespace.
First commit fixes the bug. Second commit GCs unused entries from the egressIPs map (which is related, but would not fix the bug on its own).
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1609112
> Don't auto-assign egress IPs that are no longer in use

- vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/resource_allocation.go
@sjenning 
Fix https://bugzilla.redhat.com/show_bug.cgi?id=1611988
> UPSTREAM: 67094: Fix incorrect reporting of cpu,memory and also output volumes when BalanceAttachedNodeVolumes is enabled.

- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/app_create/app.go
- pkg/oc/cli/debug/debug.go
- pkg/oc/cli/newapp/newapp.go
- pkg/oc/lib/conditions/conditions.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/logs.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/run.go
Debug was creating and using kcmd.LogOptions without passing a "consumeRequest" func and a RESTClientGetter
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1612661
> Fix debug panic

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/healthz/healthz.go
@liggitt i don't see this in current upstream nor in 1.11 branch. Do we carry this in rebase ?
Fixes: http://bugzilla.redhat.com/show_bug.cgi?id=1608109
> UPSTREAM: <drop>: increase loglevel for health check

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest_test.go
Minimal backport of 3.11 changes
Fixes patch in cases of stuck watch caches - https://bugzilla.redhat.com/show_bug.cgi?id=1582094
```sh
$ git describe
v3.10.17-1-3-g752e84746d5
$ make
hack/build-go.sh  
++ Building go targets for darwin/amd64: cmd/hypershift cmd/openshift cmd/oc cmd/oadm cmd/template-service-broker cmd/openshift-node-config vendor/k8s.io/kubernetes/cmd/hyperkube
[INFO] [16:27:07-0400] hack/build-go.sh exited with code 0 after 00h 04m 29s
$ go test ./vendor/k8s.io/apiserver/pkg/endpoints/handlers
ok  	github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/endpoints/handlers	0.068s
$ hack/test-integration.sh TestPatch
=== RUN   TestIntegration
=== RUN   TestIntegration/TestPatchConflicts
--- PASS: TestIntegration (0.07s)
--- PASS: TestIntegration/TestPatchConflicts …
```
> UPSTREAM: 63146: Remove patch retry conflict detection

- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/clientcmd/client_config_test.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/clientcmd/config.go
In cases where there are few destination filenames for a given
amount of contexts, but a large amount of contexts, this patch
prevents reading and writing to the same file (or small number
of files) over and over again needlessly.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1613075
cc @deads2k @soltysh @liggitt
> UPSTREAM: 67093: improve config file modification time

- vendor/k8s.io/kubernetes/cmd/kubelet/app/patch_volumequota.go
xref https://bugzilla.redhat.com/show_bug.cgi?id=1594144
> UPSTREAM: <carry>: ensure perFSGroup quantity is positive

- pkg/router/template/configmanager/haproxy/manager.go
use the correct namespace add/remove/provision - aka use the cloned route, not the actual representative blueprint namespace - otherwise the route namespaces are off and
creates cleanup issues.
fixes bugz #1614727
> router dynamic config manager fix to use the cloned blueprint

- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/cmd.go
- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/util/runtime.go
- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/results.go
Don't default to crio runtime when crio and docker binaries are installed.
Node object has the container runtime version, so now we fetch the runtime
info from there.
Fix provided options object is not a PodLogOptions error in network diags
This seems fallout from 1.11 rebase (#20033)
>  Bug 1614660 - Network diagnostic will auto detect runtime 

- pkg/cmd/infra/router/template.go
- pkg/router/template/configmanager/haproxy/manager.go
- pkg/router/template/types.go
Fix haproxy router config manager issue where sanitize pems don't match when
extended validation is enabled (causes a reload where none is needed).
fixes bugz #1615802
(Sorta depends on #20630 to merge to test dynamic blueprint changes).
> Fix haproxy router config manager issue where sanitize pems cause a blueprint route to not be selected 

- pkg/security/apiserver/admission/sccadmission/admission.go
We have not split our admission chain into validating and mutating.  Because of this we disable the webhook admission plugins by default and don't claim support.  When they are turned on, they bypass our admission chain checks.  There are more to do, but SCC stands out as one that is super important and we don't want people to get used to bypassing.
@liggitt as discussed
> split scc admission into mutating and validating

- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/collect.go
- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/util/runtime.go
- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/in_pod/util/util.go
Follow up of https://github.com/openshift/origin/pull/20647
We could have some nodes running crio and others with docker runtime.
Starter clusters are doing this but this could change with 4.0+ release.
Fetch the runtime info from the local node object so that it works
on all cases.
> Network diags: Determine runtime based on local node object

- vendor/k8s.io/kubernetes/pkg/controller/resourcequota/resource_quota_controller.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_apis.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_apis_test.go
- vendor/k8s.io/kubernetes/test/integration/examples/apiserver_test.go
This fixes GC behavior by providing 503s instead of 404s.
> UPSTREAM: 66932: Include unavailable apiservices in discovery response

- pkg/oc/cli/set/env.go
The behavior of an object being altered when `-o yaml` or `-o json` is specified without `--dry-run` should be expected. Removing incorrect text asserting otherwise from this command's help output.
cc @soltysh 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1615214
> remove "does not alter the object" text

- vendor/k8s.io/kubernetes/cluster/get-kube-local.sh
- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/BUILD
- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/plugins.go
- vendor/k8s.io/kubernetes/cmd/kubelet/app/plugins.go
- vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go
- vendor/k8s.io/kubernetes/hack/local-up-cluster.sh
- vendor/k8s.io/kubernetes/pkg/util/nsenter/BUILD
- vendor/k8s.io/kubernetes/pkg/util/nsenter/exec.go
- vendor/k8s.io/kubernetes/pkg/util/nsenter/exec_unsupported.go
- vendor/k8s.io/kubernetes/pkg/volume/flexvolume/flexvolume_test.go
- vendor/k8s.io/kubernetes/pkg/volume/flexvolume/plugin.go
- vendor/k8s.io/kubernetes/pkg/volume/flexvolume/probe.go
- vendor/k8s.io/kubernetes/pkg/volume/flexvolume/probe_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1602963
/sig storage
> UPSTREAM: 65549: Fix flexvolume in containerized kubelets

- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/fake/fake.go
- vendor/k8s.io/kubernetes/pkg/kubelet/BUILD
- vendor/k8s.io/kubernetes/pkg/kubelet/cloud_request_manager.go
- vendor/k8s.io/kubernetes/pkg/kubelet/cloud_request_manager_test.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status_test.go
The logic of retrieving node address from a cloud provider was re-implemented. Instead of querying for node addresses each time a node status is updated, the node addresses are cached and provided. This allows the kubelet to limit the number of queries to a cloud provider and avoid timeouts/hangouts which would otherwise block the node status update loop.
> Backport retrieve node address logic from upstream

- images/node/system-container/service.template
Port of an installer fix[1] for a RHEL environment bug[2] which has been
reproduced on Atomic Host environments. The dnsmasq service should start with
the node, but both services should then operate independently (e.g. stopping
dnsmasq should not stop the node service).
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1617976.
[1] https://github.com/openshift/openshift-ansible/pull/6843
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1532960
> Fix dnsmasq/node dependency

- pkg/cmd/server/apis/config/v1/register.go
- vendor/k8s.io/kubernetes/cluster/clientbin.sh
Fixes upstream patch and scheme registration to allow `oc patch --local -f openshift.local.config/master/master-config.yaml --patch="{\"etcdConfig\": {\"address\": \"${API_HOST}:${ETCD_PORT}\"}}" --loglevel=8 -o yaml`
@soltysh @juanvallejo 
I think the upstream is out of date
/hold
> allow patching configapi using oc patch

- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/run_pod.go
We expect network diagnostics to work out of the box without any additional
inputs, '--test-pod-image' and '--pod-image' options were exposed for testing
and to handle the situation where diag pod image pull fails for some reason.
We are not using the exact deployer/ose image directly, instead we are customizing
these images by injecting commands. Showing these image names as defaults will
mislead the user, just like what we saw in the bug.
This change will remove the defaults and instead improves the help message for
these flags.
> Bug 1600741 - Provide better help for network diagnostic flags

- pkg/oc/lib/newapp/app/imageref.go
- pkg/oc/lib/newapp/cmd/newapp.go
- test/cmd/newapp.sh
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1612723
https://bugzilla.redhat.com/show_bug.cgi?id=1611462
> Fix imagestream bugs

- images/router/haproxy/conf/haproxy-config.template
and use the default router load balance algorithm if tcp balance scheme is not specified.
fixes bugz #1618563
> Fix router issue to use tcp balance scheme if configured

- pkg/gitserver/autobuild/autobuild.go
- pkg/gitserver/getbuildconfigs.go
- pkg/gitserver/getbuildconfigs_test.go
Moves `pkg/gitserver` to use external client for buildconfigs.
> move git server to external build client

- images/router/haproxy/conf/haproxy-config.template
Partially fixes #13771. (I'm mostly interested in getting the protocol of the initial client request.)
According to the [forwarded header RFC](https://tools.ietf.org/html/rfc7239)
> A proxy server that wants to add a new "Forwarded" header field value can either append it to the last existing "Forwarded" header field after a comma separator or add a new field at the end of the header block.
I hope that add_header really adds it to the end. I choose to add it instead of replacing it because it is simpler.
I'm not 100% sure after reading the RFC if it's semantically correct to add completely new `Forwarded` headers or if only the value of `for` should be extended. Do you know?
I did not touch the behavior of the `X-Forwarded-*` headers because I'm not sure what the desired behavior is.
> Add forwarded header instead of replacing it

- pkg/cmd/server/apis/config/validation/master.go
- pkg/cmd/server/origin/admission/chain_builder.go
- test/integration/node_authorizer_test.go
- test/integration/service_account_test.go
- test/util/server/server.go
We don't know of anything supporting this.  It was never turned on downstream.  One release after producing it, we realized it was impractical to use.  This removes the ability to configure it and clearly fails in case anyone actually managed to run with it on.  Our plan is to apologize to those people and explain that the ACL boundary for openshift and kubernetes is on namespaces
@liggitt we talked about doing this
> remove the ability to limit secret refs based on service account

- test/extended/images/append.go
- test/extended/router/config_manager.go
- test/extended/router/headers.go
- test/extended/router/metrics.go
- test/extended/router/reencrypt.go
- test/extended/router/router.go
- test/extended/router/scoped.go
- test/extended/router/stress.go
- test/extended/router/unprivileged.go
- test/extended/router/weighted.go
- test/extended/util/framework.go
In preparation for the move to operators, look at both DC and deployments
and at multiple namespaces. Abstract format string lookup into its own
method for future changes.
@ironcladlou
> Make the router tests tolerate multiple namespaces

- pkg/quota/controller/clusterquotareconciliation/reconciliation_controller.go
- vendor/k8s.io/kubernetes/pkg/controller/resourcequota/resource_quota_controller.go
@smarterclayton you were asking about this in the master channel
@juanvallejo since you expressed an interest
> make cluster quota controller tolerate inaccessible api resources

- hack/lib/start.sh
- test/extended/gssapi.sh
- test/extended/setup.sh
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/patch.go
~~Work in progress...~~
Depends on https://github.com/openshift/origin/pull/20642
Picks https://github.com/kubernetes/kubernetes/pull/67399
Diff between old and new master config patch (hack/lib/start.sh) using changes from this PR: http://www.mergely.com/0HlByqZs/
cc @soltysh @deads2k
> switch to using upstream patch cmd

- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_blobDiskController.go
fix https://bugzilla.redhat.com/show_bug.cgi?id=1613676
> UPSTREAM: 67236: fix azure disk create failure due to sdk upgrade

- pkg/api/legacy/install.go
- pkg/cmd/openshift-controller-manager/controller/template.go
- pkg/template/controller/metrics.go
- pkg/template/controller/readiness.go
- pkg/template/controller/readiness_test.go
- pkg/template/controller/templateinstance_controller.go
- pkg/template/controller/templateinstance_controller_test.go
- pkg/template/controller/templateinstance_finalizer.go
- test/extended/templates/helpers.go
Switches the template controller to external types and external build client. This is on a path for eliminating the internal build client entirely.
/cc @bparees 
/cc @deads2k
> switch template controller to external

- contrib/systemd/origin-node.sysconfig
- origin.spec
This file is wholely managed by openshift-ansible. However if we remove
the file from the RPM entirely then that will delete the file during
upgrades to the newer version. So leave the file in the package with
empty contents. The %config(noreplace) directive will ensure that RPM
doesn't replace local modifications when upgrading.
/cc @sjenning @vrutkovs @smarterclayton 
Supersedes #20683
>  RPMS - Add stub /etc/sysconfig/origin-node 

- pkg/git/repository.go
Prepare pkg/git to be moved to library-go, lose the s2i dependency and just copy the s2i struct fields.
/cc @deads2k 
> git: copy struct fields and lose the s2i dependency

- hack/import-restrictions.json
- install/kube-dns/install.yaml
- install/kube-proxy/install.yaml
- pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
- pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/flags.go
- pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
- pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_handlerchain.go
- pkg/cmd/openshift-kube-apiserver/server.go
- pkg/cmd/server/origin/admission/chain_builder.go
- pkg/cmd/server/origin/admission/config_test.go
- pkg/cmd/server/origin/admission/register.go
- pkg/cmd/server/origin/admission/sync_test.go
- pkg/cmd/server/origin/master.go
- pkg/oc/clusterup/manifests/bindata.go
- test/extended/testdata/bindata.go
- test/integration/master_routes_test.go
- vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/aggregator.go
- vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/patch_openshift.go
- vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
- vendor/k8s.io/kubernetes/pkg/kubeapiserver/options/patch.go
- vendor/k8s.io/kubernetes/pkg/kubeapiserver/options/plugins.go
- vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/patch_policy.go
- vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/admission.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/patch_admission.go
@sttts I've come around.  This is where my head's at.  Not pretty, but I think we can fit most everything into those two spots.
> add kube-apiserver wiring

- pkg/oc/cli/debug/debug.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/attach.go
o.AttachFunc is nil since we use our own custom `oc debug` command.
Attaching the defaultAttachFunc if nil fixes the crash and gives a
prompt.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1618522
> oc debug: fix crash on attach

- pkg/oc/cli/create/create.go
- test/cmd/create.sh
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/create/create.go
Fix following invocation:
`oc create deploymentconfig name --image=myimage -- myargs`
/assign @juanvallejo @mfojtik 
Fixes #20728.
> Fix NameFromCommandArgs when passing command after -- 

- test/extended/images/hardprune.go
- test/extended/images/signatures.go
- test/extended/util/framework.go
Closes https://github.com/openshift/image-registry/issues/39.
> Restore test for image signature workflow

- vendor/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux_test.go
- vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount.go
- vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount_test.go
- vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount_unsupported.go
- vendor/k8s.io/kubernetes/pkg/util/mount/fake.go
- vendor/k8s.io/kubernetes/pkg/util/mount/mount.go
- vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
- vendor/k8s.io/kubernetes/pkg/util/mount/mount_unsupported.go
- vendor/k8s.io/kubernetes/pkg/util/mount/mount_windows.go
- vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount.go
- vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount_unsupported.go
- vendor/k8s.io/kubernetes/pkg/util/removeall/removeall_test.go
- vendor/k8s.io/kubernetes/pkg/volume/host_path/host_path_test.go
- vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
this is to fix https://bugzilla.redhat.com/show_bug.cgi?id=1594201 for 3.11
I do not know how to test it with containerized kubelet, I assume our e2e will.
@openshift/sig-storage kindly review please ty.
> UPSTREAM: 65447: Resolve potential devicePath symlink when MapVolume

- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_test.go
https://github.com/kubernetes/kubernetes/pull/66835
xref https://bugzilla.redhat.com/show_bug.cgi?id=1559271
fixes #19899
@derekwaynecarr @jsafrane @liggitt
> UPSTREAM: 66835: cloudprovider: aws: return true on existence check for stopped instances

- pkg/templateservicebroker/servicebroker/bind.go
- pkg/templateservicebroker/servicebroker/bind_test.go
This PR fixes a regression that caused template service broker bindings to fail to evaluate.
> Bug 1609676 - Fix missing bind values regression

- pkg/network/common/egressip.go
- pkg/network/common/egressip_test.go
- pkg/network/master/egressip.go
Tracks node online/offline state and handles reassigning egress IPs as needed.
The tracking code is very similar to the semi-automatic tracking code, but couldn't easily be shared since we don't do the OVS flow tracking in this case. Like the semi-automatic code, it needs to be made more configurable at some point...
@openshift/sig-networking PTAL
> HA for fully-automatic egress IPs

- pkg/network/node/vxlan_monitor.go
- pkg/network/node/vxlan_monitor_test.go
For nodes that host multiple egress IPs, we were accidentally only monitoring the traffic on the last IP, so we wouldn't notice that the node had gone down until someone tried and failed to access *that* egress IP, rather than trying and failing to access *any* egress IP on the node.
The actual fix is one character long; most of this is just updating the unit test...
> Minor fixup to egress IP monitoring

- pkg/oc/lib/describe/describer.go
- pkg/printers/internalversion/printer.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1609149
> Show EgressCIDRs in "oc get hostsubnets"

- pkg/build/apiserver/admission/jenkinsbootstrapper/admission.go
- pkg/build/apiserver/admission/jenkinsbootstrapper/initializer.go
- pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
- pkg/cmd/server/admission/init.go
- pkg/cmd/server/admission/types.go
- pkg/cmd/server/origin/admission/plugin_initializer.go
jenkins config is openshift apiserver only and only for one plugin. This move it to point of use, but keeps it wired for the combined server
@sig-master
/assign @bparees @mfojtik
> tighten admission to avoid unnecessary pieces of config

- hack/dind-cluster.sh
- images/dind/master/Dockerfile
- images/dind/master/openshift-sdn-master-setup.service
- images/dind/master/openshift-sdn-master-setup.sh
- images/dind/master/ovn-kubernetes-master-setup.sh
- images/dind/master/ovn-kubernetes-master.sh
- images/dind/node/Dockerfile
- images/dind/node/openshift-dind-lib.sh
- images/dind/node/openshift-node.sh
- images/dind/node/openshift-sdn-node.service
- images/dind/node/openshift-sdn-node.sh
- images/dind/node/ovn-kubernetes-node-setup.sh
- images/dind/node/ovn-kubernetes-node.sh
Let's win half the battle and do the whole daemonset/image thing as the second part.
@openshift/sig-networking @squeed @danwinship @JacobTanenbaum
> dind: move to hyperkube and 'openshift start network'

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/serve.go
xref https://bugzilla.redhat.com/show_bug.cgi?id=1620272
> UPSTREAM: 67957: Size http2 buffers to allow concurrent streams

- test/extended/deployments/deployments.go
- test/extended/deployments/util.go
Raises the timeout for triggering new deployment after tagging an image. On slow servers it might take more than 10s.
Also print the image stream tags in failure trap to confirm the tag exists.
/cc @tnozicka
> apps: raise trigger timeout for slow servers

- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_managedDiskController.go
- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_test.go
- vendor/k8s.io/kubernetes/pkg/volume/azure_dd/azure_dd.go
- vendor/k8s.io/kubernetes/pkg/volume/azure_dd/azure_provision.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1596319
Contains these PRs:
* https://github.com/kubernetes/kubernetes/pull/65217
* https://github.com/kubernetes/kubernetes/pull/65516
* https://github.com/kubernetes/kubernetes/pull/65443
@openshift/sig-storage, PTAL
> [3.10] Allow configuration of ResourceGroup in Azure StorageClass

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1623352
> UPSTREAM: 68007: Orphan DaemonSet when deleting with --cascade option set

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/serve.go
xref https://bugzilla.redhat.com/show_bug.cgi?id=1620272
> [3.10] UPSTREAM: 67960: Size http2 buffers to allow concurrent streams

- test/extended/testdata/bindata.go
- test/extended/testdata/reencrypt-serving-cert.yaml
- test/extended/testdata/router-config-manager.yaml
Use a specific tag for the nginx image used in extended tests.
Using a specific version ensures a more consistent test environment, and using a tag that is not "latest" changes the implicit image pull policy from "Always" to "IfNotPresent", which should reduce the impact of intermittent problems pulling the image during tests.
* `test/extended/testdata/reencrypt-serving-cert.yaml`:
* `test/extended/testdata/router-config-manager.yaml`: Change from using the `nginx:latest` image to using the `nginx:1.15.3` image.
* `test/extended/testdata/bindata.go`: Regenerate.
> Avoid using nginx:latest tag in extended tests

- pkg/gitserver/autobuild/autobuild.go
- pkg/gitserver/gitserver.go
- pkg/gitserver/initializer.go
- pkg/gitserver/url.go
Moves pkg/gitserver to external client for auth and lose the s2i dependency by coping the URL parsing and validation to pkg/git (which will move to library-go, where I think s2i can consume it from as well... make common deps common...)
/cc @deads2k 
@smarterclayton after this I guess we can move the gitserver to its own repo (with its deps).
> git: move to external and lose s2i dep

- hack/cherry-pick.sh
Not sure why we use the complicated merge-base before, which could break and does in 50% of the time. This PR changes the cherry-pick script to just you `pr_merge^1..pr_merge` as the selector, without any magic.
> hack/cherry-pick.sh: use dead simple selector for PR merge

- pkg/build/apiserver/apiserver.go
- pkg/build/apiserver/registry/buildclone/rest.go
- pkg/build/apiserver/registry/buildclone/rest_test.go
- pkg/build/apiserver/registry/buildconfiginstantiate/rest.go
- pkg/build/apiserver/registry/buildconfiginstantiate/rest_test.go
- pkg/build/generator/generator.go
- pkg/build/generator/generator_test.go
- pkg/build/generator/test/mocks.go
- pkg/build/generator/testing_client.go
- pkg/image/controller/trigger/image_trigger_controller_test.go
- test/extended/builds/start.go
This change will replace the internal build and image clients inside build generator with external (client-go) clients and allow us to delete the internal build client in next iteration entirely.
Since the generator mainly used by API server, the `InstantiateInternal()` and `CloneInternal()` functions are provided for convenience. 
@deads2k I don't believe that 2 conversions in those wrapper methods are worse than using internal client there which does much more conversions. So it is not ideal, but better than before I believe.
/cc @bparees 
/cc @soltysh 
NOTE: I have to wait for @soltysh PR with `pkg/image` refactoring to finish up the image trigger test.
> Make build generator use external clients

- test/extended/images/layers.go
Flaked when master is overloaded.
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18830/pull-ci-origin-e2e-gcp/3148/#featureimagelayers-image-layer-subresource-should-return-layers-from-tagged-images-suiteopenshiftconformanceparallel
Probably should consider increasing the timeout on the server (probable cause of ci-operator failures with "no such image")
> If layer is missing, retry the test

- test/extended/router/stress.go
Each router instance is capped at 10 conflicts, but we are running 4
routers (primary cluster router instance, and the three in this test).
In the future if we add router exclusion we could potentially reduce
this back down to 30.
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20772/pull-ci-origin-e2e-gcp/3154/#conformanceareanetworkingfeaturerouter-the-haproxy-router-converges-when-multiple-routers-are-writing-conflicting-status-suiteopenshiftconformanceparallelminimal
> Master replica can also contend and cause us to exceed our hard limit

- test/extended/images/layers.go
In the event we do fill the cache in time
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20488/pull-ci-origin-e2e-gcp/3168/#featureimagelayers-image-layer-subresource-should-identify-a-deleted-image-as-missing-suiteopenshiftconformanceparallel
> ImageLayers test should loop until image is missing

- pkg/oc/cli/admin/release/new.go
When reading from a stream, only images that declare release participation
should get extracted.
> Filter out non-participating images from the payload list

- pkg/network/common/egressip_test.go
TestEgressCIDRAllocationOffline is flaking. The problem is that the allocation logic uses a greedy algorithm that will give an answer that's mostly right, give or take 1 or 2 IP addresses, but the test case is using a small enough number of IPs that "within 1 or 2 IPs of right" can end up being basically wrong. I should rewrite the test to use a larger number of IPs, but let's get it to stop flaking first.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1624998
> Fix up logic in TestEgressCIDRAllocationOffline

- pkg/oc/cli/admin/release/extract.go
- pkg/oc/cli/image/extract/extract.go
Tar extraction tries to preserve all permissions by default, which is
not useful for release content. Also attempt to create the directory
so users have a convenient shortcut
> Strip permissions when extracting a release, and create the directory

- pkg/build/generator/generator.go
- test/extended/builds/start.go
When we switched to versioned client the defaulting mechanism kicks in which results in `.spec.source.binary` to be set to non-nil value. This in turn fails validation we were previously relying on.
This PR changes the generator so that not only it clears `.spec.source.binary` but also clears `.spec.source.type` which is available only in external and ensures the `.spec.source.binary` is not defaulted. 
This fixes https://bugzilla.redhat.com/show_bug.cgi?id=1624950
/assign @mfojtik @bparees
> Set empty source type after we switched to versioned build client

- pkg/oc/clusterup/run_self_hosted.go
- pkg/oc/clusterup/signing_secret.go
Create the service-ca (SSCS) signing key secret with the legacy signing CA (service-signer.{crt,key}) ahead of launching the operator. This bootstraps the operator with the legacy signing CA so it does not create a new signing CA, allowing components that still trust the legacy signing CA to properly verify
service-signing certificates.
(We may prefer this for a 3.11 fix of https://bugzilla.redhat.com/show_bug.cgi?id=1607913
rather than https://github.com/openshift/origin/pull/20760)
@openshift/sig-master @deads2k
> cluster up: create the service-ca operator signing secret

- hack/cherry-pick.sh
- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_loadbalancer.go
- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_wrap.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/BUILD
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/timeout_test.go
- Revert of https://github.com/openshift/origin/pull/20832 because the cherry-pick contents was wrong.
- fixed cherry pick of kubernetes/kubernetes#68001 onto release-3.10.
> UPSTREAM: 68009: apiserver: forward panic in WithTimeout filter

- pkg/router/metrics/metrics.go
Router metrics change to use http1 cockroach db matcher  instead of Http1Fast 
for backward compatibility.
fixes bugz 1623632 ( https://bugzilla.redhat.com/show_bug.cgi?id=1623632 )
> Router metrics change to use http1 cockroach db matcher 

- pkg/oc/cli/admin/release/extract.go
- pkg/oc/cli/admin/release/new.go
- pkg/oc/cli/admin/release/release.go
- pkg/oc/cli/image/append/append.go
- test/extended/images/append.go
Make it clear that omitting --to-file and --to-image are allowed, also accept
'-' as --to-file to pipe.
Also fix an error where mounting a blob from one repo to another caused the command to exit because we didn't handle the special "mount error" returned by the server, like we do in other commands.  Added an e2e test.
> Print better debug info about release creation

- hack/lib/constants.sh
- origin.spec
This should be enough to include the kubectl binary along side with the oc binary.
> hack: add kubectl to release tars and zip

- cmd/oc/oc.go
This removes the custom resource from the scheme of `oc`, which should keep apply from trying to build a strategic merge patch.
@soltysh you have a test you can run to confirm this?
@mfojtik @derekwaynecarr this is the `oc cluster up` blocker, right?
Fixes https://github.com/openshift/origin/issues/20462
> switch oc scheme installation to avoid installing custom resources for apply

- pkg/cmd/server/origin/admission/chain_builder.go
- pkg/cmd/server/origin/admission/register.go
Follow-up of https://github.com/openshift/origin/pull/20743.
> admission: enable webhooks by default

- docs/cluster_up_down.md
- pkg/oc/cli/cluster/cluster.go
- pkg/oc/clusterup/up.go
Followup to #20821 to clear all the places from `--routing-suffix`.
> Remove --routing-suffix since it's not supported anymore

- pkg/oc/cli/set/volume.go
- pkg/oc/cli/set/volume_test.go
When cluster has default storageclass and PVC is created, all PVCs
that have no storageClassName can be bound only to PVs of that
default. In other words, it is not possible to bound to static PV by
oc set volume.
If storageClassName: "" can be defined, it is possible, though. The
detail is described in
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
Hence, this patch changes to assign "" to storageClassName, when oc
set volume --claim-class="" was used.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1626373
> Support setting storageClassName: "" when "" is specified by claim-class

- install/etcd/install.yaml
- pkg/cmd/openshift-kube-apiserver/cmd.go
- pkg/cmd/openshift-kube-apiserver/configdefault/config_default.go
- pkg/cmd/openshift-kube-apiserver/configdefault/kubecontrolplane_default.go
- pkg/oc/clusterup/manifests/bindata.go
- pkg/oc/clusterup/run_self_hosted.go
- test/extended/testdata/bindata.go
Just the last commit is unique.  This adds value defaulting for the kubeapiserverconfig.
I plan to add some logic cluster up to prime the configmaps and secrets with content that currently exists in the local folder.
> add default values for kubeapiserverconfig to make it easier to use

- hack/build-cross.sh
- hack/lib/build/binaries.sh
> hack: copy oc to kubectl

- pkg/oc/clusteradd/components/default-imagestreams/create_secret.go
https://bugzilla.redhat.com/show_bug.cgi?id=1627669
> treat missing .docker/config.json as a warning, not an error

- install/cluster-kube-apiserver-operator/install.yaml
- pkg/cmd/openshift-kube-apiserver/configdefault/kubecontrolplane_default.go
- pkg/cmd/server/start/master_args.go
- pkg/oc/clusterup/coreinstall/components/pivot/initialconfig.go
- pkg/oc/clusterup/manifests/bindata.go
- pkg/oc/clusterup/run_self_hosted.go
- test/extended/testdata/bindata.go
This provides an install component that primes the `openshift-kube-apiserver` namespace with the required configmaps and secrets, then installs the cluster-kube-apiserver-operator which will create a deployment with an empty config that will leverage them.
>  add kube-apiserver-operator to cluster up

- pkg/oc/clusterup/up.go
currently `kcmdutils.CheckErr` obfuscates the `WithCause` (et all) error details and you get an error without any details.
before:
```
[pi-victor@dev-machine ~]$ oc cluster up
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Creating shared mount directory on the remote host ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if required ports are available ...
error: a port needed by OpenShift is not available
```
after:
```
[pi-victor@dev-machine ~]$ oc cluster up
Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.11 is available ...
Creating shared mount directory on the remote host ...
Determining server IP ...
Checking if …
```
> [oc cluster up] fix bootstrap surfacing errors

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/BUILD
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/timeout_test.go
Cherry pick of kubernetes/kubernetes#68001 onto master.
> UPSTREAM: 68008: apiserver: forward panic in WithTimeout filter

- hack/lib/log/stacktrace.sh
Stacktraces aren't that useful at info level
> Print less gorp when builds fail

- pkg/authorization/apis/authorization/rbacconversion/conversion.go
- pkg/authorization/apiserver/registry/subjectrulesreview/storage.go
- pkg/authorization/authorizer/scope/authorizer.go
- pkg/authorization/authorizer/scope/authorizer_test.go
- pkg/authorization/authorizer/scope/converter.go
- pkg/authorization/authorizer/scope/converter_test.go
- pkg/project/apiserver/registry/project/proxy/proxy.go
- pkg/project/auth/cache.go
- test/integration/scopes_test.go
This allows us to interop with an OIDC/OAuth server that sends us tokens with additional scopes used for other applications than Openshift
> Ignore errors caused by unkonwn scopes where it makes sense to do so.

- vendor/k8s.io/kubernetes/pkg/kubelet/cm/pod_container_manager_linux.go
This will fix launching pods on dind cluster.
When --cgroups-per-qos=false (default is true), kubelet sets pod
container management to podContainerManagerNoop implementation and
GetPodContainerName() returns '/' as cgroup parent (default cgroup root).
(1) In case of 'systemd' cgroup driver, '/' is invalid parent as
docker daemon expects '.slice' suffix and throws this error:
'cgroup-parent for systemd cgroup should be a valid slice named as \"xxx.slice\"'
(https://github.com/moby/moby/blob/5fc12449d830ae9005138fb3d3782728fa8d137a/daemon/daemon_unix.go#L618)
'/' corresponds to '-.slice' (root slice) in systemd but I don't think
we want to assign root slice instead of runtime specific default value.
In case of docker runtime, this will be 'system.slice' …
> UPSTREAM: 66617: Do not set cgroup parent when --cgroups-per-qos is disabled

- contrib/completions/bash/oc
- contrib/completions/zsh/oc
- pkg/oc/cli/types/types.go
> Deprecate oc types

- vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
Helps apiservice status recover from networking glitches sooner
/assign @sttts
> UPSTREAM: 68678: tighten maximum retry loop for aggregate api availability

- pkg/cmd/server/start/network/start_network.go
Restore signal handling and graceful shutdown of DNS that had been added in https://github.com/openshift/origin/pull/19987/commits/c802e2226b524a83e3c7ddb0500cbb289fecea8c but was subsequently lost during rebase in https://github.com/openshift/origin/commit/564ee038cff669480ccecd7e999d3f41464b30ff.
Graceful shutdown is necessary to ensure that when OpenShift's DNS server shuts down, we remove it from the dnsmasq configuration.
This commit fixes bug 1624448.
https://bugzilla.redhat.com/show_bug.cgi?id=1624448
@knobunc @ironcladlou @sdodson @smarterclayton
> Restore graceful shutdown of DNS server

- pkg/cmd/server/start/start_network.go
Restore signal handling and graceful shutdown of DNS that had been added in commit https://github.com/openshift/origin/pull/19987/commits/c802e2226b524a83e3c7ddb0500cbb289fecea8c but was subsequently lost during rebase in commit https://github.com/openshift/origin/pull/20344/commits/564ee038cff669480ccecd7e999d3f41464b30ff.
Graceful shutdown is necessary to ensure that when OpenShift's DNS server shuts down, we remove it from the dnsmasq configuration.
This commit fixes bug 1624448.
https://bugzilla.redhat.com/show_bug.cgi?id=1624448
This is a manual cherry-pick of #21009
> [release-3.11] Restore graceful shutdown of DNS server

- test/extended/conformance-k8s.sh
'role' was deprecated after 3.9
> Use standard node roles for conformance isolation

- pkg/network/common/egressip.go
The egress IP node offline tracking code was assuming that when nodes go offline, this would manifest as connections timing out. That works for detecting the initial online->offline transition, but eventually the kernel will start just returning `EHOSTUNREACH` to new connection attempts right away if it knows the node is still not reachable. So we should consider that "offline" too.
> Improve egress IP node-offline-tracking error checking

- test/extended/cluster/README.md
Update cluster loader README to link to latest OKD documentation instead of a hardcoded link to 3.9 OCP documentation.
@sjug PTAL
> Cluster loader: Link to latest OKD docs instead of 3.9 OCP docs

- test/extended/setup.sh
@smarterclayton per recent email thread
> make ext test need for existing cluster painfully obvious

- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
If scheduler starts fast in start_master.go then the controller manager go routine will fail immediately because the configz already have componentconfig registered.
/cc @deads2k 
I suspect we want this in 3.11?
> UPSTREAM: <drop>: comment out componentconfig registration for kube controller manager

- install/cluster-kube-apiserver-operator/install.yaml
- install/cluster-openshift-apiserver-operator/install.yaml
- install/cluster-openshift-controller-manager-operator/install.yaml
- pkg/oc/clusterup/manifests/bindata.go
- test/extended/testdata/bindata.go
The latest image tag is having some trouble, this should pin us to unblock CI until we get it sorted out.
@derekwaynecarr fyi, oc cluster up now openshift apiserver and openshift controller manager via operator.
> pin to v4.0 so that the latest image problem can be bypassed for now

- pkg/oc/clusterup/up.go
oc cluster up no longer brings up a registry, a router, or installs default templates
so this PR removes that text from the oc cluster up --help
> Adjusting oc cluster up help text

- pkg/network/common/egressip.go
- pkg/network/common/egressip_test.go
Backport #20950 and #20971 to release-3.11
> egress IP fixes for 3.11

- pkg/image/apis/image/sort.go
- pkg/oc/lib/describe/describer.go
- pkg/printers/internalversion/printer.go
- pkg/printers/internalversion/printer_test.go
1. Tags were not stable when their creation timestamp was in the same second
2. Use "IMAGE REPOSITORY" as the column name instead of "DOCKER REPO" to remove use of docker
3. Try to pack more tags and make the column less ragged
After:
```
NAME                  DOCKER REPO                                                        TAGS                                                                     UPDATED
release               registry.svc.ci.openshift.org/clayton-test-1/release               4.0-20180921084620,4.0,4.0-20180921072659                                About an hour ago
test                  registry.svc.ci.openshift.org/clayton-test-1/test                  aws-machine-controllers,control-plane,logging-eventrouter + 67 more...   About an hour ago
test-20180921072659 …
```
> Fix a few small bugs in image stream describe and printers

- pkg/oc/cli/admin/release/new.go
> OS constant in `oc adm release new` was invalid

- pkg/image/apis/image/sort.go
- pkg/image/apis/image/sort_test.go
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/21089/pull-ci-openshift-origin-master-unit/30
Only when date is equal should we fall through to name.
> Image sort is flaky because of order

- contrib/completions/bash/oc
- contrib/completions/zsh/oc
- pkg/oc/cli/cluster/cluster.go
- pkg/oc/clusterup/clusteradd/add_cmd.go
- pkg/oc/clusterup/clusteradd/apply_image.go
This creates a new `oc cluster add` command based off our CVO image requirements that applies the content from the image's `/manifest` directory.  There are no other dependencies or checks. This simply applies those manifests until they succeed.
> oc cluster add

- pkg/oc/cli/admin/migrate/migrator.go
- test/cmd/migrate.sh
This change updates the reporting during migration to use the group resource instead of just the resource.
Thus the confusing messages with "the server does not allow this method on the requested resource" for pod metrics will go from:
-n hasha-pro1 pods/nodejs-ex-2-kmzrv
to:
-n hasha-pro1 pods.metrics.k8s.io/nodejs-ex-2-kmzrv
This makes it clear what resource is being referenced.
Bug 1631517
> Use group resource in migrate reporting

- contrib/completions/bash/oc
- contrib/completions/zsh/oc
- pkg/oc/cli/image/extract/extract.go
- test/extended/images/extract.go
Images can contain whiteout directives that will result in existing
contents being deleted. Since it's easy to accidentally do this in
your working dir, make `--confirm` required if any destination path
is non-empty.
@deads2k sorry :)
> Require confirmation before extracting into directories

- pkg/oc/lib/graph/kubegraph/nodes/nodes_test.go
This is fixing the flake that keeps happening very frequently recently, eg. https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/21097/pull-ci-openshift-origin-master-unit/70
> Fix JobSpecNode flake

- test/extended/testdata/bindata.go
- test/extended/testdata/deployments/custom-deployment.yaml
We are seeing Back-off failures in the test logs as myapp exits after 10 seconds right now.
I have also picked @derekwaynecarr kubelet fix for running tests which we can remove before merging.
> test: Set custom deployment template app to sleep infinity

- contrib/completions/bash/oc
- contrib/completions/zsh/oc
- pkg/oc/cli/admin/release/extract.go
- pkg/oc/cli/image/extract/extract.go
Add a column to the --dry-run output that includes the layer the image
came from. The --all-layers flag will show the highest layer.
Mostly for debugging.
> oc image extract should be able to print which layer files come from

- images/openldap/OWNERS
- pkg/apiserver/authentication/OWNERS
- pkg/authorization/OWNERS
- pkg/cmd/OWNERS
- pkg/oauth/OWNERS
- pkg/oauthserver/OWNERS
- pkg/security/OWNERS
- pkg/serviceaccounts/OWNERS
- pkg/user/OWNERS
- test/OWNERS
- test/testdata/OWNERS
As a courtesy since Simo is no longer working on OpenShift.
> Remove Simo Sorce from OWNERS

- vendor/k8s.io/kubernetes/test/e2e/framework/util.go
- vendor/k8s.io/kubernetes/test/e2e/storage/subpath.go
We are seeing flakes where pod event isn't yet visible when
we check for it leading to test failure.
cc: @derekwaynecarr 
Signed-off-by: Mrunal Patel <mpatel@redhat.com>
> UPSTREAM: 69300: test: Wait for pod event to show up

- pkg/oc/clusterup/coreinstall/controlplane-operator/run_render.go
- pkg/oc/clusterup/docker/util/client.go
- pkg/oc/clusterup/docker/util/helper.go
- pkg/oc/clusterup/required_images.go
- pkg/oc/clusterup/run_self_hosted.go
- pkg/oc/clusterup/up.go
Follow up on https://github.com/openshift/cluster-kube-controller-manager-operator/pull/19
The controller manager needs locks to orchestrate hand-off of host port from bootstrap to real controller manager. 
/cc @deads2k 
/cc @soltysh
> cluster-up: add locks for controller manager

- pkg/oc/clusterup/coreinstall/assets/apiserver.go
- pkg/oc/clusterup/coreinstall/assets/render.go
This is a bit dirty and broader than necessary, but it makes `oc logs` function again for as long as cluster up is here.
> make oc logs function

- examples/db-templates/mariadb-ephemeral-template.json
- examples/db-templates/mariadb-persistent-template.json
- examples/db-templates/mongodb-ephemeral-template.json
- examples/db-templates/mongodb-persistent-template.json
- examples/db-templates/mysql-ephemeral-template.json
- examples/db-templates/mysql-persistent-template.json
- examples/db-templates/postgresql-ephemeral-template.json
- examples/db-templates/postgresql-persistent-template.json
- examples/image-streams/image-streams-centos7.json
- examples/image-streams/image-streams-rhel7.json
- examples/jenkins/jenkins-ephemeral-template.json
- examples/jenkins/jenkins-persistent-template.json
- examples/quickstarts/cakephp-mysql-persistent.json
- examples/quickstarts/cakephp-mysql.json
- examples/quickstarts/dancer-mysql-persistent.json
- examples/quickstarts/dancer-mysql.json
- examples/quickstarts/django-postgresql-persistent.json
- examples/quickstarts/django-postgresql.json
- examples/quickstarts/httpd.json
- examples/quickstarts/nodejs-mongodb-persistent.json
- examples/quickstarts/nodejs-mongodb.json
- examples/quickstarts/rails-postgresql-persistent.json
- examples/quickstarts/rails-postgresql.json
- pkg/oc/clusterup/manifests/bindata.go
- test/cmd/debug.sh
- test/cmd/images.sh
- test/cmd/newapp.sh
- test/extended/testdata/bindata.go
update-external-examples to include .NET Core 2.1.
@bparees ptal
I can limit this to .NET Core only if that is preferable.
> update-external-examples to include .NET Core 2.1

- pkg/cmd/openshift-apiserver/cmd.go
- pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
- pkg/cmd/openshift-apiserver/server.go
- pkg/cmd/server/origin/master.go
This removes the `network.openshift.io` group from the openshift-apiserver so that the new networking CRDs can run instead.
/assign @sttts @squeed 
@openshift/sig-networking
> remove networking apiserver from hypershift openshift-apiserver

- vendor/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go
- vendor/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler_test.go
I think this should be backported to 3.11 as well.
ref: https://github.com/kubernetes/kubernetes/pull/68563
cc @derekwaynecarr @sjenning @aveshagarwal
> UPSTREAM: 68563 : fix scheduler crash when Prioritize Map function failed

- pkg/oc/cli/rsync/copytar.go
- pkg/oc/cli/rsync/util.go
- test/cmd/rsync.sh
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1559693
Adds support for `--include` and `--exclude` flags with the tar strategy.
cc @soltysh @smarterclayton
> add rsync include,exclude support

- test/extended/cluster/README.md
small typo in README.md 
./extended.test --ginkg.focus ->  ./extended.test --ginkgo.focus
Signed-off-by: Elvir Kuric <elvirkuric@gmail.com>
> fixed typo in README.md

- pkg/configconversion/legacyconfig_conversion.go
Another finding in the path to split integation #21096.
> Use kubernetes prefix for its API server

- vendor/k8s.io/kubernetes/pkg/volume/iscsi/BUILD
- vendor/k8s.io/kubernetes/pkg/volume/iscsi/attacher.go
- vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi.go
- vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go
- vendor/k8s.io/kubernetes/pkg/volume/util/device_util.go
- vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
- vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux_test.go
- vendor/k8s.io/kubernetes/pkg/volume/util/device_util_unsupported.go
- vendor/k8s.io/kubernetes/pkg/volume/util/io_util.go
- Retry attaching iSCSI devices until we either have at least two paths or we tried long enough
- Wait longer for multipath devices to appear.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1632418 and https://bugzilla.redhat.com/show_bug.cgi?id=1609703 and perhaps https://bugzilla.redhat.com/show_bug.cgi?id=1627962
cc @openshift/storage @humblec
> 3.10: Fix iSCSI multipath issues 

- pkg/apiserver/admission/chain_builder.go
- pkg/apiserver/admission/config_test.go
- pkg/apiserver/admission/register.go
- pkg/cmd/openshift-kube-apiserver/server.go
- pkg/cmd/server/origin/legacyadmission/register.go
- pkg/cmd/server/start/start_master.go
These are the changes necessary to admission wiring to make https://github.com/openshift/origin/pull/21096 working.
> Explicitly disable admission plugins that we have off in the legacy path

- pkg/network/common/egressip.go
- pkg/network/common/egressip_test.go
The new unit test from #20971 was supposed to reject the egress IPs because there were multiple IPs, but in fact it was rejecting them because I made a typo and one of them wasn't actually a valid IP, and the "don't mix auto-assigned-HA with multiple-egress-IP HA" check wasn't actually working at all. So this fixes the test case and the check, and then for good measure also ensures we don't auto-assign egress IPs in two other "broken" cases. (The new "NetID: 49" test case is because I initially thought the problem might have been that we were handling the case of "good namespace goes bad" but not the case of "new namespace is bad from the start". That was a red herring but I left the extra test in anyway.)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1633574 (which has been bumped …
> Fix up "should not auto-assign egress IPs" cases

- pkg/cmd/openshift-apiserver/openshiftapiserver/configprocessing/audit.go
We should've defaulted the logformat to `legacy`, but since we didn't back when we first introduced it we need to default to `json` but still allow administrators to set it correctly to whatever they want.
/assign @deads2k @mfojtik
> Bug 1632155 - Accept logFormat when passed to audit config

- pkg/apiserver/admission/chain_builder.go
We forgot the namespace lifecycle admission plugin.
@soltysh  please add test for this to test-integration for an openshift resource
@juanvallejo pick up this commit to get test-cmd to pass for now.
> make sure that the openshift apiserver includes namespace lifecycle admission

- pkg/oc/cli/admin/release/image_mapper.go
- pkg/oc/cli/admin/release/new.go
We have to rewrite the payload if we aren't mirroring.
> `oc adm release new --from-release` should honor mappings

- pkg/oc/cli/image/append/append.go
- pkg/oc/cli/image/extract/extract.go
Fix bug #21247 which show properly the baseline of the command for the examples.
> Fix help examples for image append/extract

- pkg/cmd/openshift-kube-apiserver/configdefault/kubecontrolplane_default.go
This default constrained choice used by the openshift/installer at the moment.
> remove aggressive default for kubelet

- cmd/hypershift/main.go
- hack/dind-cluster.sh
- images/dind/master/Dockerfile
- images/dind/master/openshift-generate-master-config.sh
- images/dind/master/openshift-sdn-master-setup.sh
- images/dind/master/openshift-sdn-master.service
- images/dind/node/Dockerfile
- pkg/cmd/openshift-controller-manager/controller_manager.go
- pkg/cmd/openshift-network-controller/cmd.go
- pkg/cmd/openshift-network-controller/network_controller.go
This moves the SDN controller out of the controller manager as step 1 of the plan to be able to bring up the network without needing the openshift apiserver or controllers.
After some false starts last week I realized this can actually be done pretty simply by basically just making a duplicate of openshift-controller-manager that only includes the network controller.
I ripped out `origincontrollers.RunControllerServer()` because I wasn't sure what it was doing, but it didn't seem necessary (and probably would end up conflicting with the actual controller manager if I'd left it in?)
This updates dind to start a separate network controller, but we'll need to have an ansible patch too.
> Move SDN controller out of openshift-controller-manager

- pkg/network/node/networkpolicy.go
- test/extended/networking/networkpolicy.go
currently Openshift networkpolicy only allows for using either peer.PodSelector or peer.NamespaceSelector. This brings the operation of Openshift's networkpolicy support closer to that of upstream by allowing the use of both.
> Added support of Namespace and Pod selector for networkpolicy 

- hack/update-generated-informers.sh
- hack/update-generated-listers.sh
Currently if you run `make update` you'll end up with
Untracked files:
(use "git add <file>..." to include in what will be committed)
pkg/apps/generated/
pkg/build/generated/
Fallout from #20499, #20817.
> Don't regenerate apps and build files

- test/extended/util/test.go
Reverts openshift/origin#21183
The openshift-apiserver can now be successfully installed by openshift/installer.  Let's see how this goes.
> Revert "use namespace labels to prevent SCC usage"

- vendor/k8s.io/kubernetes/pkg/util/mount/mount.go
- vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1640078
https://github.com/kubernetes/kubernetes/pull/68741
https://github.com/kubernetes/kubernetes/pull/69565
> 3.11 Fixed subpath cleanup when /var/lib/kubelet is a symlink

- hack/local-up-master/util.sh
cc @enj 
Fixes the following error sometimes seen during `localup/master.sh` cleanup
```
hack/local-up-master/../local-up-master/util.sh: line 73: KUBE_TEMP: unbound variable
```
> fix unbound var check in localup temp dir cleanup

- pkg/oc/cli/set/imagelookup.go
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1640843
By default, all imagestream resources were selected if no arguments
were passed to the "set image-lookup" command. This patch updates
the command so that either the --all flag, or a specific set of
imagestream names must be provided in order for those resources
to be updated.
cc @soltysh @smarterclayton
> remove default behavior of selecting all resources

- pkg/oc/lib/describe/helpers.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1628789
cc @smarterclayton @soltysh
> fix formatString describe helper

- pkg/oc/cli/image/extract/extract.go
Some images have non-writable directories, due to the way that root
can write to read only directories. When extracting contents from an
image as a non-root user where the directory was r-x we would get a
permission denied error. Make the extract logic union our mode bits
so that the current user can write the directory.
> cli: Extracting image as non-root fails on directory permissions

- test/extended/testdata/bindata.go
- test/extended/testdata/cluster/master-vert.yaml
A new mandatory field has been added to the Cluster Loader test, so the embedded configuration needs to be updated.
> Add new ifexists field to CL config

- pkg/network/node/ovscontroller.go
I think we didn't add this before because we didn't want to rule out the possibility of a pod participating in a VXLAN with some external host. However, it seems like that's not really a possibility: a host that isn't on the SDN wouldn't be able to send packets directly to the pod's IP, and a host that is on the SDN wouldn't be able to accept packets on the vxlan port because OVS would already have claimed it. So there is no way for an external host to send VXLAN packets to a pod (other than by using some alternate port, which wouldn't be affected by this patch).
The more-complicated alternative to this patch would be to add per-node flows to specifically recognize pod-to-node traffic, and only filter out pod-to-node-vxlan-port traffic.
@openshift/sig-networking please discuss.
> Don't allow pods to send VXLAN packets out of the SDN

- vendor/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux_test.go
- vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount.go
- vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount_test.go
- vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount_unsupported.go
- vendor/k8s.io/kubernetes/pkg/util/mount/fake.go
- vendor/k8s.io/kubernetes/pkg/util/mount/mount.go
- vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
- vendor/k8s.io/kubernetes/pkg/util/mount/mount_unsupported.go
- vendor/k8s.io/kubernetes/pkg/util/mount/mount_windows.go
- vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount.go
- vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount_unsupported.go
- vendor/k8s.io/kubernetes/pkg/util/nsenter/nsenter.go
- vendor/k8s.io/kubernetes/pkg/util/removeall/removeall_test.go
- vendor/k8s.io/kubernetes/pkg/volume/host_path/host_path_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1640077
https://github.com/kubernetes/kubernetes/pull/68741
https://github.com/kubernetes/kubernetes/pull/69565
> 3.10 Fixed subpath cleanup when /var/lib/kubelet is a symlink

- pkg/network/node/ovscontroller.go
Backport of #21363. (But now without configurable VXLAN port.)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1643965
> [3.10] Don't allow pods to send VXLAN packets out of the SDN

- vendor/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/builder.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1641991
Based on the godoc and desired behavior of the ContinueOnError visitor, encountering an error while visiting results should not short-circuit a visitor chain.
This patch removes existing behavior, which wraps a decorated visitor in a ContinueOnError visitor, and introduces the originally-intended behavior which uses a ContinueOnError visitor as the visitor in a DecoratedVisitor list.
cc @soltysh
> UPSTREAM: 70311: fix ContinueOnError visitor

- vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
> UPSTREAM: 70286:  Use pvc uid instead of pvc name in glusterfs endpoint name

- examples/sample-app/application-template-custombuild.json
- examples/sample-app/application-template-dockerbuild.json
- examples/sample-app/application-template-pullspecbuild.json
- examples/sample-app/application-template-stibuild.json
- test/extended/testdata/bindata.go
Corrects issue referenced at https://jira.coreos.com/browse/DEVEXP-170?focusedCommentId=52856&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-52856
Rails should use the "script" option for postCommit hooks, as referenced in the below templates:
https://github.com/sclorg/rails-ex/blob/master/openshift/templates/rails-postgresql-persistent.json
https://github.com/sclorg/rails-ex/blob/master/openshift/templates/rails-postgresql.json
And also by looking at the documentation the "script" options seems correct instead of the "args" option, as "args" is supposed to be for supplying arguments to the default entrypoint for the image.
> Updating postcommit hooks to use correct options

- pkg/network/common/egressip.go
- pkg/network/common/egressip_test.go
Backport of #21122 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1633574
> [3.11] Fix up "should not auto-assign egress IPs" cases

- images/dind/master/openshift-generate-master-config.sh
- images/dind/master/openshift-sdn-master.service
- pkg/cmd/openshift-network-controller/cmd.go
https://github.com/openshift/cluster-network-operator/pull/19 will create an OpenShiftControllerManagerConfig rather than a master-config.yaml, so drop the master-config.yaml support that had been copied from openshift-controller-manager.
Also updates the dind setup (with a hack to make it keep working if https://github.com/openshift/api/pull/112 gets merged).
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1639896
> Drop master-config.yaml support from openshift-network-controller

- images/dind/master/ovn-kubernetes-master.sh
- images/dind/node/ovn-kubernetes-node.sh
The default service cidr range, found in the master-config.yaml file (usually, 172.30.0.0/16) is now passed into ovnkube through the --service-cluster-ip-range command line option.
> dind - add default --service-cluster-ip-range

- pkg/cmd/openshift-controller-manager/controller/interfaces.go
This is necessary for the CRD-based network API and mostly harmless for the non-CRD-based API. (As compared to #21243, this doesn't actually try to get rid of the protobuf code for the network API, because that's apparently still needed anyway. It just makes it so that controller-to-apiserver communication will not use protobufs for the network types, regardless of whether it's supported.)
> Make controller use JSON rather than protobuf for network types

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/drain.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/drain_test.go
https://bugzilla.redhat.com/show_bug.cgi?id=1628693
Upstream PR link: https://github.com/kubernetes/kubernetes/pull/68767
/cc @sjenning @derekwaynecarr @soltysh @smarterclayton
> UPSTREAM: 68767: Fix drain for evicting terminal DS pods

- cmd/hypershift/main.go
- hack/import-restrictions.json
- pkg/cmd/openshift-osinserver/cmd.go
- pkg/cmd/openshift-osinserver/server.go
We can transition to a new binary and a new image, but this gives something for @openshift/sig-security to use to start wiring a fresh config format (master-config.yaml is going away).
`hypershift openshift-osinserver --kubeconfig=path/to/kubeconfig --config=master-config.yaml` will let you run it locally and see it's output.  Regrettably my cluster doesn't want to come up yet, but I'm reasonably confident and will continue to test as the day goes on.
/assign @enj @ericavonb 
> create a temporary hypershift openshift-osinserver

- vendor/k8s.io/kubernetes/pkg/kubelet/cadvisor/util.go
https://github.com/kubernetes/kubernetes/pull/69313
xref https://bugzilla.redhat.com/show_bug.cgi?id=1631300
@mrunalp @runcom
> UPSTREAM: 69313: kubelet: fix cri-o when using unix prefix

- pkg/oc/cli/admin/release/image_mapper.go
- pkg/oc/cli/admin/release/new.go
Prune the set of input images down to only images referenced by the operator.
To get in the release image, an operator has to reference you.
> release: Only referenced images are included in the payload

- .gitignore
- vendor/github.com/prometheus/procfs/fixtures/26231/exe
An issue (https://github.com/src-d/go-git/issues/1017) was found in go-git library that the publishing bot is using that leads to a dirty checkout which will block progress of publishing bot for the origin repo. It seems like the go-git can't handle the symlinks properly (along with other problem that we fixed in publishing bot).
> fix go-git problem with some vendored fixtures

- test/integration/etcd_storage_path_test.go
- vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/aggregator.go
- vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
- vendor/k8s.io/kubernetes/test/integration/etcd/BUILD
- vendor/k8s.io/kubernetes/test/integration/etcd/OWNERS
- vendor/k8s.io/kubernetes/test/integration/etcd/data.go
- vendor/k8s.io/kubernetes/test/integration/etcd/etcd_storage_path_test.go
- vendor/k8s.io/kubernetes/test/integration/etcd/server.go
- vendor/k8s.io/kubernetes/test/integration/master/transformation_testcase.go
- vendor/k8s.io/kubernetes/test/integration/utils.go
UPSTREAM: 70019: Refactor dry run test to reuse ETCD storage data
This change updates the ETCD storage test so that its data is
exported. Thus it can be used by other tests. The dry run test was
updated to consume this data instead of having a duplicate copy.
The code to start a master that can be used for "one of every
resource" style tests was also factored out. It is reused in the
dry run test as well.
This prevents these tests from drifting in the future and reduces
the long term maintenance burden.
---
UPSTREAM: <drop>: 70019: Remove too new ETCD storage data
We do not have the REST storage for these resources yet.
---
Remove dead code from ETCD storage test
Signed-off-by: Monis Khan …
> Collapse on top of upstream ETCD storage test

- pkg/build/controller/build/build_controller.go
- pkg/build/controller/build/build_controller_test.go
- pkg/build/controller/build/podcreationstrategy.go
- pkg/build/controller/build/podcreationstrategy_test.go
- pkg/build/controller/strategy/custom.go
- pkg/build/controller/strategy/custom_test.go
- pkg/build/controller/strategy/docker.go
- pkg/build/controller/strategy/docker_test.go
- pkg/build/controller/strategy/sti.go
- pkg/build/controller/strategy/sti_test.go
- pkg/build/controller/strategy/util.go
- pkg/build/controller/strategy/util_test.go
- pkg/build/util/consts.go
- pkg/cmd/openshift-controller-manager/controller/build.go
Read CA bundle from disk so it can be mounted into build pods.
> Add Trusted CA Bundle to Build Controller

- contrib/completions/bash/oc
- contrib/completions/zsh/oc
- pkg/oc/cli/admin/release/image_mapper.go
- pkg/oc/cli/admin/release/info.go
- pkg/oc/cli/admin/release/new.go
- pkg/oc/cli/admin/release/release.go
- pkg/oc/cli/image/extract/extract.go
By default will print high level info about a release image. With the
`--changes-from=IMAGE` option shows you the delta between that image and
the one you specified. Support `--commits` to display source info for
both diffs and normal output.
> cli: Add an `oc adm release info` command that views and diffs releases

- pkg/oc/cli/admin/release/new.go
This leaves open the door for resources that should be applied last.
Discussed as part of having service monitor definitions be created in `/manifests`
by individual operators. They need to be declared after CMO is installed. Therefore,
to define a service monitor CR, a team creates it in:
```
0000_99_cluster-kube-scheduler-operator_monitoring.yaml
```
which ensures that it runs after other operators are created. If the CRD isn't created,
then the person defining what is in the release payload needs to sort that out.
> Autoassign the 0000_70_ run level in release payloads

- contrib/completions/bash/oc
- contrib/completions/zsh/oc
- pkg/oc/cli/cli_bashcomp_func.go
This patch changes:
- to uses `oc api-resources` in bash completion
- to fix a bug in `__oc_override_flags()` based on https://github.com/kubernetes/kubernetes/pull/63421#discussion_r186091439
~~~
alertmanagers.monitoring.coreos.com                           horizontalpodautoscalers.autoscaling                          projects.project.openshift.io
apiservices.apiregistration.k8s.io                            hostsubnets.network.openshift.io                              prometheuses.monitoring.coreos.com
appliedclusterresourcequotas.quota.openshift.io               identities.user.openshift.io                                  prometheusrules.monitoring.coreos.com
brokertemplateinstances.template.openshift.io                 images.image.openshift.io …
> Update completion to use api-resources

- pkg/oc/cli/admin/migrate/storage/storage.go
Storage migration is special in that all it needs to do is a no-op
update to cause the API server to migrate the object to the
preferred version.  Thus if we encounter a conflict, we know that
something updated the object and we no longer need to do anything.
If the object needed migration, the API server has already migrated
it.
> Do not retry conflicts during storage migration

- pkg/network/node/iptables.go
We aren't recreating the iptables rules associated with egress IPs in our iptables-resyncing code, so if they get deleted by an iptables.service restart or firewalld reload, we won't recreate them.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1643304
> Ensure Egress IP rules are recreated after firewalld reload

- test/extended/setup.sh
- test/extended/util/test.go
- Currently not supported by openshift dns operator
This functionality is needed to ensure backward compatibility.
- Extended tests should honor SKIP env when FOCUS env is set
> Disable wildcard dns extended test

- contrib/completions/bash/oc
- contrib/completions/zsh/oc
- pkg/oc/cli/image/image.go
- pkg/oc/cli/image/info/info.go
- test/extended/images/info.go
As a user I often want to see data about an image before I import, mirror,
or use it in a build. Add an image info command that prints info about
images on registries.
> cli: Add an `image info` command to make debugging images easier

- glide.yaml
- publishing-rules.yaml
This change will make the bot publish to `origin-4.0-kubernetes-1.11.1` instead of `origin-3.11-kubernetes-1.11.1`. It also moves glide to track the `origin-4.0-` branch instead of `origin-3.11`.
Next step will be cleaning up the `origin-3.11-` branches inside the forks to get rid of extra commits that we published after we cut the `release-3.11` branch in origin.
/cc @deads2k 
/cc @sttts 
/cc @soltysh
> use origin-4.0-kubernetes-1.11.1 branch for publishing master

- hack/local-up-master/util.sh
whoami will fail if /etc/passwd is not correct, but id -u won't.
> test-cmd is broken inside an Openshift container

- test/extended/imageapis/limitrange_admission.go
- test/extended/imageapis/quota_admission.go
- test/extended/images/helper.go
- test/extended/images/prune.go
Fixes 2 of 4 tests described at #20079.
> Make admission extended tests dockerless
