- pkg/apps/controller/deployer/factory.go
- pkg/apps/controller/deploymentconfig/factory.go
- pkg/build/controller/build/build_controller.go
- pkg/build/controller/buildconfig/buildconfig_controller.go
- pkg/cmd/infra/deployer/deployer.go
- pkg/cmd/openshift-controller-manager/controller/image.go
- pkg/cmd/openshift-controller-manager/controller_manager.go
- pkg/service/controller/ingressip/service_ingressip_controller.go
Stop using an unnecessary layer in the event broadcaster init flow.
> remove layer for creating event broadcaster

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory_object_mapping.go
- vendor/k8s.io/kubernetes/pkg/printers/internalversion/BUILD
- vendor/k8s.io/kubernetes/pkg/printers/internalversion/describe.go
- vendor/k8s.io/kubernetes/pkg/printers/internalversion/describe_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1567722
> UPSTREAM: 62744: Fix kubectl describe cronjob

- examples/grafana/setup-grafana.sh
- don't replace existing htpasswd file if it exists
- make setup-grafana.sh executable
- don't require SSL cert verification, e.g. in the case of self-signed certificates
> examples/grafana: minor improvements to setup script

- test/extended/cluster/README.md
- test/extended/cluster/cm.go
- test/extended/cluster/context.go
Initial CM functionality + README
Original CM PR https://github.com/openshift/origin/pull/19303 was closed.
>  Cluster Mirror Base

- hack/build-local-images.py
@soltysh untested, but should work
> hack: use control-plane in build local images

- hack/build-local-images.py
the control plane images weren't getting updated by building local images.
/assign @stevekuznetsov
> update build-local-images for controlplane

- examples/quickstarts/dotnet.json
- pkg/oc/bootstrap/bindata.go
- test/extended/testdata/bindata.go
Sync with upstream to include template fix
CC @bparees
> .NET Core: Fix quickstart example template

- images/ipfailover/keepalived/Dockerfile
bug 1517740
https://bugzilla.redhat.com/show_bug.cgi?id=1517740
> ipfailover - add missing ipset/libipset to image

- test/extended/image_ecosystem/jenkins_plugin.go
- test/extended/image_ecosystem/s2i_php.go
Fixes https://github.com/openshift/origin/issues/19513
Pulls in https://github.com/openshift/origin/pull/19110 commit so that ext image_ecosystem passes
@cuppett fyi
> Fix ext test namespace stuff

- vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/logs/logs.go
https://github.com/kubernetes/kubernetes/pull/63160
@derekwaynecarr @smarterclayton
> UPSTREAM: 63160: kubelet: logs: do not wait when following terminated container

- pkg/image/registry/imagestreamtag/rest.go
Also return a structured error instead of an opaque error so that
clients can react when unknown problems occur.
@bparees dual to the other one
> Allow imagestreamtag delete to retry conflicts

- vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder.go
https://github.com/kubernetes/kubernetes/pull/62668
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1569865
> UPSTREAM: 62668: add metrics to cinder volume

- examples/jenkins/pipeline/README.md
Fixes https://github.com/openshift/origin/issues/19305
> add declarative pipeline example to readme

- vendor/github.com/google/cadvisor/manager/manager.go
https://github.com/google/cadvisor/pull/1903
xref https://bugzilla.redhat.com/show_bug.cgi?id=1570577
@derekwaynecarr @RobertKrawitz
> UPSTREAM: google/cadvisor: 1903: fix #1902 bug with retryDockerStatus

- pkg/authorization/registry/clusterrole/proxy.go
- pkg/authorization/registry/clusterrolebinding/proxy.go
- pkg/authorization/registry/role/proxy.go
- pkg/authorization/registry/rolebinding/proxy.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1574404
> Ensure Continue token is proxied for openshift RBAC list calls

- vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
https://github.com/kubernetes/kubernetes/pull/63339
fixes https://github.com/openshift/origin/issues/19497
@smarterclayton @jsafrane @derekwaynecarr
> UPSTREAM: 63339: kubelet: volume: do not create event on mount success

- hack/lib/build/binaries.sh
- hack/lib/constants.sh
Simple build level check.
@liggitt
> Prevent accidental binary size regressions

- examples/deployment/OWNERS
- hack/lib/OWNERS
- images/base/OWNERS
- images/builder/OWNERS
- images/deployer/OWNERS
- images/egress/OWNERS
- images/ipfailover/OWNERS
- images/node/OWNERS
- images/origin/OWNERS
- images/pod/OWNERS
- images/recycler/OWNERS
- images/source/OWNERS
- pkg/api/OWNERS
- pkg/apps/OWNERS
- pkg/cmd/OWNERS
- pkg/controller/OWNERS
- pkg/oc/cli/deploymentconfigs/OWNERS
- test/end-to-end/OWNERS
- test/extended/OWNERS
- test/integration/OWNERS
- tools/genman/OWNERS
Trying to make some sense of github notifications
/cc mfojtik 
/assign mfojtik
> Drop myself from owners files

- test/extended/builds/contextdir.go
- test/extended/builds/image_source.go
- test/extended/builds/pipeline.go
- test/extended/builds/start.go
- test/extended/cluster/utils.go
- test/extended/image_ecosystem/helper.go
- test/extended/image_ecosystem/mongodb_ephemeral.go
- test/extended/image_ecosystem/mongodb_replica_statefulset.go
- test/extended/image_ecosystem/mysql_replica.go
- test/extended/image_ecosystem/postgresql_replica.go
- test/extended/image_ecosystem/s2i_perl.go
- test/extended/image_ecosystem/s2i_php.go
- test/extended/image_ecosystem/s2i_python.go
- test/extended/image_ecosystem/s2i_ruby.go
- test/extended/jobs/jobs.go
- test/extended/util/framework.go
- test/extended/util/jenkins/ref.go
Only check if pod exists when examining build environment
Fixes #19608 (for real)
> Relaxing docker image source extended test

- pkg/apps/strategy/recreate/recreate.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1549931
/cc @mfojtik
> Apps: Fix DC recreate strategy to wait only for running pods

- pkg/oc/bootstrap/OWNERS
So that I can fully approve changes to cluster add service-catalog
> Add pmorie to approvers for pkg/oc/bootstrap

- images/dind/node/Dockerfile
- images/dind/node/journald.conf
@openshift/networking @knobunc
> dind: bump up journald ratelimiting to ensure messages get logged

- pkg/cmd/openshift-controller-manager/controller/config.go
- pkg/cmd/openshift-controller-manager/controller/template.go
- pkg/cmd/server/bootstrappolicy/controller_policy.go
- pkg/template/apis/template/constants.go
- pkg/template/controller/templateinstance_controller.go
- pkg/template/controller/templateinstance_finalizer.go
- test/extended/templates/templateinstance_objectkinds.go
- test/extended/templates/templateservicebroker_e2e.go
- test/extended/testdata/bindata.go
- test/extended/testdata/templates/templateinstance_objectkinds.yaml
- test/extended/testdata/templates/templateservicebroker_bind.yaml
- test/integration/authorization_test.go
- test/testdata/bootstrappolicy/bootstrap_cluster_role_bindings.yaml
- test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
- test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
bug https://bugzilla.redhat.com/show_bug.cgi?id=1568607
> use a finalizer instead of GC to clean up templateinstances

- pkg/image/controller/scheduled_image_controller.go
@soltysh just bring the scheduled importer controller in sync with other controllers
> image: use deletion handling metanamespace key in import scheduler

- publishing-kube-rules.yaml
removes BUILD file conflicts pushing to forks
/assign @sttts
> skip publishing BUILD files to forks

- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/metadata.go
- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/metadata_test.go
- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack.go
- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_instances.go
https://bugzilla.redhat.com/show_bug.cgi?id=1566455
> Restore pre-1.10 openstack cloud provider node name behavior

- pkg/oc/bootstrap/clusteradd/components/template-service-broker/template_service_broker.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1577843
/cc @deads2k
> up: fix tsb image template parameter

- test/integration/authorization_test.go
> Add legacy rbac endpoint integration tests

- hack/dind-cluster.sh
This change sets the default KUBECONFIG when empty so that we don't
use the dind one as the default when the original default KUBECONFIG
was in use.
i.e. if KUBECONFIG is unset, before this change when you sourced the
rc file it would set KUBECONFIG to the dind kubeconfig.  If you had
been working with other clusters defined in the default ~/.kube/config
you would lose visibility of them.  This change just sets the default
path if KUBECONFIG is not set.
This also cleans up the way that the function was embedded into the rc
file we generate by defining the function in bash and then using
`declare` to get bash to output the definition.  This means that bash
will check the syntax of the function when run and we don't have to
deal with all of the horrible escaping of characters from bash.
> Set the default kubeconfig when empty

- pkg/scheduler/admission/podnodeconstraints/admission.go
- pkg/scheduler/admission/podnodeconstraints/admission_test.go
This change updates the PodNodeConstraints admission plugin to ignore mirror pods that are created by a node with PodSpec.NodeName that matches the given node's name.
Thus nodes are allowed to create mirror pods that target themselves.
The NodeRestriction plugin continues to guarantee that nodes can only create and delete mirror pods that target themselves.  These mirror pods are also prevented from referencing any API objects.
Bug 1579605
/kind bug
/assign @simo5 @liggitt
@openshift/sig-security @openshift/sig-master
> Ignore node created self targeting mirror pods in PodNodeConstraints

- vendor/k8s.io/kubernetes/pkg/kubelet/remote/remote_image.go
- vendor/k8s.io/kubernetes/pkg/kubelet/remote/remote_runtime.go
- vendor/k8s.io/kubernetes/pkg/kubelet/remote/utils.go
https://github.com/kubernetes/kubernetes/pull/63977
@derekwaynecarr @runcom
> UPSTREAM: 63977: pkg: kubelet: remote: increase grpc client default size

- hack/lib/constants.sh
/cc @mfojtik 
Fixes: https://github.com/openshift/origin/issues/19785
> Initialize defaultImageStreams

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/certificates.go
> UPSTREAM: 63416: Retry certificate approval on conflict errors

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/scalejob/scalejob.go
> UPSTREAM: 64028: Tolarate negative values when calculating job scale progress

- test/extended/cluster/cl.go
Add functionality as per https://github.com/openshift/origin/issues/19628
> CL skip config write by default

- test/extended/builds/no_outputname.go
- test/extended/idling/idling.go
- test/extended/util/cli.go
Not everything needs to go into artifacts, these are mostly not
valuable.
> Remove unnecessary output files

- pkg/proxy/hybrid/proxy.go
The hybrid proxy just put the names for services and other objects in the log messages.  This made it impossible to trace errors when objects across different namespaces have the same names.  In openshift.io there is a standard template used to create things so they stamp out the same names in the same namespaces.  So when we are trying to debug the service proxy it becomes impossible.  This adds the namespace to all of the messages.
> Added namespaces to log messages in the hybid proxy

- images/dind/node/openshift-generate-node-config.sh
Important for kube e2e network policy tests
@dcbw @danwinship @pravisankar PTAL. Thanks.
> support dns resolution

- pkg/oc/admin/groups/sync/cli/prune.go
This cleans up the command help and aligns it with others
> Cleanup prune groups command to align with other commands

- test/extended/image_ecosystem/helper.go
- test/extended/image_ecosystem/s2i_php.go
See https://ci.openshift.redhat.com/jenkins/job/test_branch_origin_extended_image_ecosystem/490/display/redirect
> move cakephp ext test count check to greater than zero

- pkg/oc/clusteradd/components/template-service-broker/template_service_broker.go
Fixes: https://github.com/openshift/origin/issues/19794
> Fix TSB Registration

- test/common/build/controllers.go
There appears to be probably multiple issues with https://github.com/openshift/origin/issues/16940
One could be that the `WaitLoop` with timeout 60s watching `Build` and `BuildConfig` events appears to never finish because the timeout is restarted every time an event on either of the watches appears. 
- This is a run just with @enj commit to client rate limiting and `TestConcurrentBuildImageChangeTriggerControllers` fails with `panic: test timed out after 5m0s`
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/17930/consoleText
and one of the goroutines being stuck at 
https://github.com/openshift/origin/blob/5843432e015a1abe1087b0404a9cb1f5c0267923/test/common/build/controllers.go#L460
- Added here a bunch of debugging statements (note that despite some …
> tests: allow `watch` to timeout

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
This reverts commit f15c48dbfe26f5abf37dec421c73e0527294bcd6.
Fixes: #19852
> Revert "UPSTREAM: 61459: etcd client add dial timeout"

- vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi.go
> UPSTREAM: 60632: Add volumemetrics for ISCSI Plugin

- vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller_test.go
Bug https://bugzilla.redhat.com/show_bug.cgi?id=1583079
already lgtm'd upstream.
> UPSTREAM: 64443: services must listen on port 443 for aggregation

- hack/dind-cluster.sh
- images/dind/master/ovn-kubernetes-master-setup.sh
- images/dind/node/ovn-kubernetes-node-setup.sh
> ovn-k8s-overlay executable  is deprecated

- glide.lock
- glide.yaml
- vendor/github.com/openshift/api/servicecertsigner/v1alpha1/register.go
- vendor/github.com/openshift/library-go/glide.lock
- vendor/github.com/openshift/library-go/glide.yaml
- vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourcecread/core.go
- vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helper_test.go
- vendor/github.com/openshift/library-go/pkg/operator/v1alpha1helpers/helpers.go
- vendor/github.com/openshift/library-go/pkg/operator/versioning/compare.go
- vendor/github.com/openshift/library-go/pkg/operator/versioning/compare_test.go
- vendor/github.com/openshift/source-to-image/hack/build-test-images.sh
- vendor/github.com/openshift/source-to-image/hack/test-integration.sh
- vendor/github.com/openshift/source-to-image/pkg/api/describe/describer.go
- vendor/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti.go
- vendor/github.com/openshift/source-to-image/pkg/build/strategies/strategies.go
- vendor/github.com/openshift/source-to-image/pkg/cmd/cli/cmd/rebuild.go
- vendor/github.com/openshift/source-to-image/pkg/docker/util.go
- vendor/github.com/openshift/source-to-image/pkg/docker/util_test.go
- vendor/github.com/openshift/source-to-image/pkg/errors/errors.go
- vendor/github.com/openshift/source-to-image/test/integration/images/sti-fake-assemble-root/Dockerfile
- vendor/github.com/openshift/source-to-image/test/integration/images/sti-fake-assemble-user/Dockerfile
- vendor/github.com/openshift/source-to-image/test/integration/integration_test.go
This pull updates the definition of the runc fork and also the source-to-image level which changed concurrently.
/assign @adambkaplan @vikaschoudhary16 @sjenning
>  update fork bump

- pkg/oc/clusterup/coreinstall/kubeapiserver/openshift_apiserver.go
Somehow missed during refactoring.
/cc @deads2k
> up: default openshift imagepolicy admission

- vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
> UPSTREAM: 64797: Handle deleted DaemonSet properly

- hack/build-local-images.py
This adds the tag to the calculated FROM line, which for this branch is v3.9.0. (Backport of #19917.)
> add support to build different tags in hack script

- images/dind/OWNERS
- pkg/cmd/OWNERS
- pkg/cmd/server/kubernetes/network/OWNERS
- pkg/network/OWNERS
- pkg/proxy/OWNERS
- pkg/util/ovs/OWNERS
- test/cmd/OWNERS
- test/end-to-end/OWNERS
- test/extended/OWNERS
- test/integration/OWNERS
- test/testdata/OWNERS
As SDN team lead Casey should be able to sign-off and approve PRs.
> Add Casey Callendrello (squeed) to the relevant OWNERS files

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/get.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go
xref https://bugzilla.redhat.com/show_bug.cgi?id=1555057
/cc @eparis @mfojtik
> UPSTREAM: 65001: Quiet verbose apiserver logs

- vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
- vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller_test.go
picks https://github.com/kubernetes/kubernetes/pull/65009
/cc @liggitt
> UPSTREAM: 65009: daemon: add custom node indexer

- tools/rebasehelpers/commitchecker/validate.go
Our new upstream patching strategy stops upstream patches other than k8s.io/kubernetes.  This enforces that restriction.
I've added a commit which should run afoul of this detection to prove it works.  I'll remove it before merge.
> restrict upstream patches to k8s.io/kubernetes only

- publishing-kube-rules.yaml
I want publish rules for kube staging to get the codegenerator current with our patches.
@liggitt green button if it looks good.
@mfojtik how do I deploy to the bot and rekick?
> add kube staging publish rules

- pkg/oc/cli/cmd/image/mirror/mirror.go
User can't find out what is wrong
> Image mirror doesn't print out tag in error

- pkg/apps/controller/deployer/deployer_controller.go
Fixes: https://github.com/openshift/origin/issues/17445
Don't want to block this on missing unit tests, I'm going to add issue for that.
> Fix deployer pod tolerations

- pkg/apiserver/authentication/internaloauth/tokenauthenticator.go
- pkg/apiserver/authentication/internaloauth/tokenauthenticator_test.go
This change masks the error returned from a Get OAuthAccessToken failure in tokenAuthenticator.  This prevents errors like the following from appearing in the logs:
Unable to authenticate the request due to an error: oauthaccesstokens.oauth.openshift.io "...token_data..." not found
/kind bug
/assign @eparis @simo5
> Do not log Get failures for OAuthAccessToken lookups

- test/extended/image_ecosystem/mysql_replica.go
- test/extended/util/db/mysql.go
https://github.com/sclorg/mysql-container/issues/226 is fixed so re-enabling this.
> re-enable slave restart test

- pkg/build/controller/build/build_controller.go
- pkg/build/controller/build/build_controller_test.go
- pkg/build/controller/buildconfig/buildconfig_controller.go
- pkg/build/controller/common/util.go
- test/extended/builds/pipeline.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/build-pruning/failed-pipeline.yaml
- test/extended/testdata/builds/build-pruning/successful-pipeline.yaml
Trello: https://trello.com/c/AZICjYb7/1554-pruning-for-pipeline-builds-pipelineintegration
> Prune builds for Jenkins Pipelines

- examples/db-templates/mysql-ephemeral-template.json
- examples/db-templates/mysql-persistent-template.json
- examples/image-streams/image-streams-centos7.json
- examples/image-streams/image-streams-rhel7.json
- examples/jenkins/jenkins-persistent-template.json
- examples/quickstarts/dotnet-pgsql-persistent.json
- examples/quickstarts/dotnet.json
- pkg/oc/clusterup/manifests/bindata.go
- test/cmd/debug.sh
- test/cmd/images.sh
- test/cmd/newapp.sh
- test/extended/testdata/bindata.go
> update external example content

- pkg/oc/cli/cmd/image/image.go
- pkg/oc/cli/cmd/image/mirror/mirror.go
- pkg/oc/cli/cmd/importer/appjson.go
- pkg/oc/cli/cmd/importer/import.go
- pkg/oc/cli/cmd/login/login.go
- pkg/oc/cli/cmd/login/loginoptions.go
- pkg/oc/cli/cmd/login/logout.go
- pkg/oc/cli/cmd/logs.go
- pkg/oc/cli/cmd/set/env.go
- pkg/oc/cli/cmd/set/volume.go
- pkg/oc/cli/cmd/tag.go
- pkg/oc/clusterup/docker/openshift/login.go
- pkg/oc/clusterup/up.go
- test/integration/login_test.go
- test/integration/oauth_oidc_test.go
- test/integration/oauth_request_header_test.go
Work in progress...
Update additional commands with upstream changes.
cc @soltysh
> update additional cmds

- pkg/oc/cli/cmd/observe/observe.go
- pkg/oc/cli/cmd/registry/info/info.go
- pkg/oc/cli/cmd/registry/login/login.go
- pkg/oc/cli/cmd/registry/registry.go
- pkg/oc/cli/cmd/rollback.go
- pkg/oc/cli/cmd/startbuild.go
- pkg/oc/cli/cmd/version.go
update a few more commands with upstream changes
cc @soltysh
> update even more cmds

- origin.spec
* Adds -hyperkube
* Removes -sdn-ovs
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1593209
> Bug 1593209 - Update OpenShift Excluder

- vendor/k8s.io/kubernetes/pkg/controller/nodelifecycle/scheduler/taint_manager.go
pick of https://github.com/openshift/origin/pull/20068
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1588244
> [3.10] UPSTREAM: 65339: Remove item from taint manager workqueue on completion

- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
- vendor/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1467244
Upstream: https://github.com/kubernetes/kubernetes/pull/65223
/assign @gnufied @tsmetana
> UPSTREAM: 65223: Fixed detection of inaccessible AWS encryption key

- pkg/security/OWNERS
> Greetings me as a new SCC maintainer!

- pkg/oc/cli/cmd/deploy.go
- pkg/oc/cli/cmd/extract.go
- pkg/oc/cli/cmd/project.go
- pkg/oc/cli/cmd/status.go
- pkg/oc/cli/cmd/whoami.go
> update deploy, extract, project, status, whoami cmds

- pkg/oc/admin/admin.go
- pkg/oc/cli/cli.go
- pkg/oc/cli/cmd/export.go
- pkg/oc/cli/cmd/request_project.go
- pkg/oc/cli/cmd/rsync/rsync.go
- pkg/oc/cli/cmd/version.go
- pkg/oc/clusterup/docker/openshift/project.go
> update export, req_project, rsync cmds

- pkg/oc/cli/cmd/idle.go
- pkg/oc/cli/cmd/importimage.go
- pkg/oc/cli/cmd/newapp.go
- pkg/oc/cli/cmd/newbuild.go
- pkg/oc/cli/cmd/project.go
- pkg/oc/cli/cmd/projects.go
- pkg/oc/cli/cmd/request_project.go
- pkg/oc/cli/cmd/rsh.go
Finish updating remaining commands
> update remaining cmds

- publishing-kube-rules.yaml
- publishing-rules.yaml
start publishing 3.11 kube fork
> update publishing rules

- test/extended/builds/forcepull.go
fixes https://github.com/openshift/origin/issues/20078
> ensure user has custom access before testing

- test/extended/cluster/cl.go
Currently when users set `ifexists: reuse` to the Cluster Loader config, the project creation will stop unless the projects already exist (for reuse). We want the functionality to be reuse of existing projects, and creation if they don't exist.
> Small CL logic change to create projects when using ifexists config setting

- Godeps/Godeps.json
> update version file

- test/extended/builds/build_timing.go
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/20228/test_pull_request_origin_extended_conformance_install/12961/
@bparees
> Some build pushes can take less than a second

- pkg/oc/generate/app/pipeline.go
- test/cmd/newapp.sh
> Reverting PR 20052 reuse existing imagestreams

- examples/image-streams/image-streams-centos7.json
- examples/image-streams/image-streams-rhel7.json
- examples/quickstarts/dotnet-pgsql-persistent.json
- examples/quickstarts/dotnet.json
- pkg/oc/clusterup/manifests/bindata.go
- test/extended/testdata/bindata.go
> Sync .NET Core template changes

- pkg/cmd/server/apis/config/helpers.go
- pkg/cmd/server/apis/config/types.go
- pkg/cmd/server/apis/config/v1/types.go
- pkg/cmd/server/apis/config/validation/master.go
- pkg/cmd/server/origin/master.go
- pkg/cmd/server/origin/openshift_apiserver.go
- pkg/image/apiserver/apiserver.go
- pkg/oc/clusteradd/components/default-imagestreams/create_secret.go
- pkg/oc/clusteradd/components/default-imagestreams/default_imagestreams.go
- pkg/oc/clusteradd/components/registry/registry_install.go
fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1592936
fixes https://github.com/openshift/origin/issues/20022
> registry auth support for cluster up

- pkg/oc/clusteradd/components/web-console-operator/web_console_operator.go
fixes https://github.com/openshift/origin/issues/20203
handle an update conflict
> handle update conflicts in webconsole component install

- pkg/oc/cli/cmd/export.go
- pkg/oc/cli/cmd/rsync/rsync.go
Updates export and rsync commands to follow updated upstream patterns
cc @deads2k
> update export, rsync cmds

- pkg/oc/cli/cmd/importimage.go
- pkg/oc/cli/cmd/importimage_test.go
- pkg/oc/cli/cmd/project.go
- pkg/oc/cli/cmd/projects.go
- pkg/oc/cli/cmd/request_project.go
- pkg/oc/cli/cmd/request_project_test.go
- pkg/oc/cli/cmd/rsh.go
- pkg/oc/clusterup/docker/openshift/project.go
- test/integration/unprivileged_newproject_test.go
Updates `importimage.go`, `projects.go`, `rsh.go`, `project.go`, and `request_project.go`
cc @deads2k
> update importimage, projects, rsh, req_project

- pkg/build/controller/build/build_controller.go
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1596449
> update logsnippet on initial transition to failing state

- contrib/completions/bash/oc
- contrib/completions/zsh/oc
- pkg/oc/cli/cmd/image/image.go
- pkg/oc/cli/cmd/importer/appjson.go
- pkg/oc/cli/cmd/importer/import.go
- pkg/oc/cli/cmd/login/login.go
- pkg/oc/cli/cmd/login/loginoptions.go
- pkg/oc/cli/cmd/login/loginoptions_test.go
- pkg/oc/cli/cmd/login/logout.go
- pkg/oc/cli/cmd/logs.go
- pkg/oc/cli/cmd/logs_test.go
- pkg/oc/clusteradd/cmd.go
- pkg/oc/clusterup/docker/openshift/login.go
- pkg/oc/clusterup/up.go
- test/integration/login_test.go
- test/integration/oauth_oidc_test.go
- test/integration/oauth_request_header_test.go
Picks and rebases changes from https://github.com/openshift/origin/pull/20232
cc @deads2k
> Update logs, importer, login & logout

- images/router/haproxy/conf/haproxy-config.template
Solves https://github.com/openshift/origin/issues/20211 (full description on the issue)
> Correct quoting issue with Forwarded field in HAproxy 1.8

- vendor/k8s.io/kubernetes/pkg/controller/statefulset/stateful_set_control.go
- vendor/k8s.io/kubernetes/pkg/controller/statefulset/stateful_set_control_test.go
Cherrypick of https://github.com/kubernetes/kubernetes/pull/62943
/assign mfojtik tnozicka
/cc  mfojtik tnozicka
> UPSTREAM: 62943: set updated replicas in statefulsets

- publishing-kube-rules.yaml
- publishing-rules.yaml
prereq of https://github.com/openshift/origin/pull/20354
> set up 1.11.1 branch publishing

- pkg/oc/lib/newapp/app/imageref.go
- pkg/oc/lib/newapp/app/pipeline.go
- test/cmd/newapp.sh
Trello: https://trello.com/c/BOR33gza/1559-3-reuse-existing-imagestreams-with-new-app-appcreationtechdebt
Fixes #20107
> Reuse imagestreams with new-app

- examples/service-catalog/service-catalog-rbac.yaml
- pkg/oc/clusterup/manifests/bindata.go
> catalog: add RBAC rules for namespaced brokers

- examples/service-catalog/service-catalog.yaml
- pkg/oc/clusterup/manifests/bindata.go
> ServiceCatalog:  add NamespacedServiceBroker & CatalogRestrictions feature gates

- pkg/oc/cli/image/append/append.go
- pkg/oc/cli/image/image.go
- pkg/oc/cli/image/mirror/mirror.go
Updates image/mirror command with upstream patterns
cc @deads2k
> update image/mirror image/append cmds

- pkg/oc/cli/cli.go
- pkg/oc/cli/set/deploymenthook.go
- pkg/oc/cli/status/status.go
- pkg/oc/lib/describe/projectstatus.go
- pkg/router/template/configmanager/haproxy/client_test.go
- pkg/router/template/configmanager/haproxy/converter_test.go
- pkg/router/template/configmanager/haproxy/map_test.go
- pkg/router/template/configmanager/haproxy/testing/haproxy.go
- test/cmd/deployments.sh
- test/cmd/status.sh
Fixes #20097
/assign @deads2k @juanvallejo
> Restore -v in set deploymenthook and status 

- tools/depcheck/README.md
cc @deads2k @soltysh 
Thought it might help someone in the future to have a specific set of steps
that can be specifically followed in order for our repo.
> update readme to include origin-specific guide

- test/extended/router/config_manager.go
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/batch/test_pull_request_origin_extended_conformance_install/13740/
> Skip the HAProxy config manager until it is deflaked

- test/integration/namespace_lifecycle_admission_test.go
finalize subresource does a conditional update which can conflict with a controller adding UIDs.
> deflake integration test

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/get/humanreadable_flags_test.go
- vendor/k8s.io/kubernetes/pkg/printers/humanreadable.go
- vendor/k8s.io/kubernetes/pkg/printers/internalversion/printers.go
- vendor/k8s.io/kubernetes/pkg/printers/internalversion/printers_test.go
- vendor/k8s.io/kubernetes/pkg/registry/core/pod/storage/storage_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1608277
> Fix panic with incorrect number of server side pod printing columns

- examples/quickstarts/cakephp-mysql-persistent.json
- examples/quickstarts/cakephp-mysql.json
- examples/quickstarts/django-postgresql-persistent.json
- examples/quickstarts/django-postgresql.json
- examples/quickstarts/nodejs-mongodb-persistent.json
- examples/quickstarts/nodejs-mongodb.json
- pkg/oc/clusterup/manifests/bindata.go
- test/extended/testdata/bindata.go
> pick up recent quickstart changes

- test/extended/deployments/deployments.go
- test/extended/images/layers.go
- test/extended/testdata/bindata.go
- test/extended/testdata/deployments/test-deployment-test.yaml
Replaces #20359 
@smarterclayton @runcom PTAL
> Fixes for CRI-O

- pkg/oc/cli/set/deploymenthook.go
- pkg/oc/cli/status/status.go
- pkg/oc/lib/describe/projectstatus.go
Followup to https://github.com/openshift/origin/pull/20412 fixing typos in the original PR.
> Bug 1608254 - update help messages

- hack/lib/constants.sh
In OSX, `make build` fails with:
```
~/.../openshift/origin → make build WHAT=cmd/oc
hack/build-go.sh cmd/oc
++ Building go targets for darwin/amd64: cmd/oc
du: illegal option -- -
usage: du [-H | -L | -P] [-a | -s | -d depth] [-c] [-h | -k | -m | -g] [-x] [-I mask] [file ...]
[ERROR] PID 49040: hack/lib/constants.sh:336: `ocsize=$(du --apparent-size -m "${OS_OUTPUT_BINPATH}/${platform}/oc" | cut -f 1)` exited with status 64.
[INFO] 		Stack Trace:
[INFO] 		  1: hack/lib/constants.sh:336: `ocsize=$(du --apparent-size -m "${OS_OUTPUT_BINPATH}/${platform}/oc" | cut -f 1)`
[INFO] 		  2: hack/lib/build/binaries.sh:268: os::build::check_binaries
[INFO] 		  3: hack/lib/build/binaries.sh:156: os::build::internal::build_binaries
[INFO] 		  4: hack/build-go.sh:25: os::build::build_binaries
[INFO] …
```
> hack: fix usage of du in osx

- pkg/apps/apiserver/apiserver.go
- pkg/apps/apiserver/registry/deploylog/rest.go
- pkg/apps/apiserver/registry/deploylog/rest_test.go
- pkg/apps/apiserver/registry/rollback/rest.go
- pkg/apps/apiserver/registry/rollback/rest_test.go
- test/extended/builds/contextdir.go
- test/extended/builds/gitauth.go
- test/extended/builds/jenkins_plugin.go
- test/extended/builds/new_app.go
- test/extended/builds/pipeline.go
- test/extended/cluster/cl.go
- test/extended/image_ecosystem/mariadb_ephemeral.go
- test/extended/image_ecosystem/mongodb_ephemeral.go
- test/extended/image_ecosystem/mysql_ephemeral.go
- test/extended/image_ecosystem/mysql_replica.go
- test/extended/image_ecosystem/postgresql_replica.go
- test/extended/image_ecosystem/s2i_perl.go
- test/extended/image_ecosystem/s2i_php.go
- test/extended/image_ecosystem/s2i_python.go
- test/extended/image_ecosystem/s2i_ruby.go
- test/extended/image_ecosystem/sample_repos.go
- test/extended/templates/templateinstance_readiness.go
- test/extended/util/framework.go
> apps: moves extended test helper and some registries to external types

- hack/import-restrictions.json
- pkg/oc/cli/cancelbuild/cancelbuild.go
- pkg/oc/cli/cancelbuild/cancelbuild_test.go
cc @deads2k @soltysh 
Updated pkg/build/client/v1:
- made client lister external
- made some build/client utils external
> Update cancelbuild cmd to use external versions

- pkg/template/controller/templateinstance_controller.go
- test/extended/templates/templateinstance_security.go
https://bugzilla.redhat.com/show_bug.cgi?id=1610995
> set full user info for SAR check on template readiness checks

- pkg/build/controller/build/defaults/defaults.go
- pkg/build/controller/build/overrides/overrides.go
- pkg/build/controller/build/pluginconfig/config.go
@mfojtik as promised.  Simplified and de-generified so that it turns into "decode these bytes using this scheme".
> divorce the build overrides and defaults from the main configapi scheme

- test/cmd/newapp.sh
fixes https://github.com/openshift/origin/issues/20519
> check for tag before proceeding with new-app test

- pkg/oc/lib/describe/describer.go
https://bugzilla.redhat.com/show_bug.cgi?id=1611248
> only print each webhook once.

- examples/grafana/grafana.yaml
- examples/grafana/setup-grafana.sh
Bump grafana version and use update the setup script.
> Bump grafana version.

- pkg/apiserver/authentication/oauth/expirationvalidator.go
- pkg/apiserver/authentication/oauth/expirationvalidator_test.go
- pkg/apiserver/authentication/oauth/interfaces.go
- pkg/apiserver/authentication/oauth/timeoutvalidator.go
- pkg/apiserver/authentication/oauth/tokenauthenticator.go
- pkg/apiserver/authentication/oauth/tokenauthenticator_test.go
- pkg/apiserver/authentication/oauth/uidvalidator.go
- pkg/cmd/server/origin/authenticator.go
- pkg/cmd/server/origin/informers.go
- pkg/cmd/server/origin/master_config.go
Switch the oauth authenticators to using external clients.
@openshift/sig-security 
/assign @enj @simo5
> switch authenticators to external clients

- pkg/oc/cli/newapp/newapp.go
cc @bparees @deads2k 
Since the only point behind doing this decoding is to handle specific resource types, there's no point in actually error-ing out here for custom resources, etc.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1610255
> log scheme error for custom resources

- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/round_tripper.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/round_trippers.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1599428
Picks https://github.com/kubernetes/kubernetes/pull/66929
Picks https://github.com/kubernetes/kubernetes/pull/67024
> UPSTREAM: 67024: add CancelRequest to discovery round-tripper

- test/extended/builds/pipeline.go
- test/extended/util/cli.go
- test/extended/util/jenkins/ref.go
> info/diag for direct ext test invocation on gcp/prow

- .tito/lib/origin/common.py
Cherry pick of https://github.com/openshift/origin/pull/20503 from 3.10 branch
> Injecting new required vars into origin.spec file

- pkg/build/builder/source.go
This reverts commit 922bb91edc7fbdfca5f1e703a759d95c2e6b2d62.
This change introduced a hang during binary builds that is only seen with large binary inputs (either large number of files or large total size, not sure which).
If we revisit this change, someone needs to recreate the hangs and perform thread dumps
to see why the StdoutPipe/StderrPipe behavior is causing a hang (bsdtar cmd execution
never completes).
bug https://bugzilla.redhat.com/show_bug.cgi?id=1614347
> Revert "Provide feedback on progression for extracting of binary build"

- pkg/oc/cli/admin/diagnostics/diagnostics.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1612031
> Wire factory to DiagnosticsOptions

- cmd/sdn-cni-plugin/openshift-sdn_linux.go
> sdn: don't fail when adding a duplicate route

- pkg/image/controller/imagestream_controller.go
- pkg/image/controller/imagestream_controller_test.go
https://bugzilla.redhat.com/show_bug.cgi?id=1613979
> skip import call when there is nothing to import

- pkg/oc/cli/buildlogs/buildlogs.go
- pkg/oc/cli/export/export.go
- pkg/oc/cli/logout/logout.go
- pkg/oc/cli/process/process.go
- pkg/oc/cli/process/process_test.go
- pkg/template/client/v1/templateconfig.go
~~Work in progress~~
cc @soltysh
> Update more commands to use external versions

- pkg/network/node/ovscontroller.go
Apparently just because `ovs-vsctl add-port` returns an error doesn't mean that it didn't do anything, and this isn't considered a bug:
> See this example:
> 
>     [root@plex ~]# ovs-vsctl add-port ovsbr0 foo 
>     ovs-vsctl: Error detected while setting up 'foo': could not open network device foo (No such device).  See ovs-vswitchd log for details.
>     ovs-vsctl: The default log directory is "/var/log/openvswitch".
>     
>     [root@plex ~]# ovs-vsctl show 
>     36a1b8c2-9512-4f38-a9b1-2328ea8832e2
>         Bridge "ovsbr0"
>             Port foo
>                 Interface foo
>                     error: "could not open network device foo (No such device)"
>             Port "ovsbr0"
>                 Interface "ovsbr0"
>                     type: internal
>     
>     [root@plex …
> Clean up bad OVS ports

- pkg/oc/lib/newapp/source/detector.go
Detect Rust projects using the presence of a Cargo.toml file
> Add Rust detector

- examples/service-catalog/service-catalog.yaml
- pkg/oc/clusterup/manifests/bindata.go
reflects change in upstream Service Catalog
> service-catalog: use K8s NamespaceLifecycle admission controller

- pkg/oc/clusterup/docker/dockerhelper/helper.go
bug https://bugzilla.redhat.com/show_bug.cgi?id=1615762
> use local dockerconfig for auth when pulling images

- test/end-to-end/core.sh
See https://github.com/openshift/origin/pull/20593#issuecomment-413933333
> in e2e wait for istag creation after the import, before the pull

- docs/cli_hacking_guide.adoc
Updates the CLI Hacking Guide with current conventions.
cc @soltysh
> update CLI Hacking Guide

- pkg/template/templateprocessing/template.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1619186
Just need to move the GVK replacement after the substitution.
> allow substitution of legacy api kinds in templates

- cmd/oc/oc.go
- glide.lock
- vendor/github.com/openshift/api/install.go
- vendor/github.com/openshift/api/template/v1/consts.go
prove that https://github.com/openshift/api/pull/77 works
/hold
holding for real bump
> use upstream install function

- vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/max_attachable_volume_predicate_test.go
- vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/predicates.go
- vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/predicates_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1608626
> UPSTREAM: 66397: Fix upper limit on m5/c5 instance typesn

- images/egress/dns-proxy/egress-dns-proxy.sh
- images/egress/dns-proxy/egress_dns_proxy_test.go
This change allows workaround suggested in https://discourse.haproxy.org/t/trouble-with-dns-resolvers-sticking-to-single-ip-address/146/24
> Egress DNS proxy router: Allow load distribution when domain resolves to multiple IP addrs

- vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
Signed-off-by: hchiramm <hchiramm@redhat.com>
> UPSTREAM: 67822: Remove provisioner config from log message.

- pkg/oc/lib/newapp/app/errors.go
- test/cmd/newapp.sh
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1622920
> Remove count from new-build/new-app error message

- test/extended/clusterup.sh
fixes https://github.com/openshift/origin/issues/20766
> use v3.10 version of Service Catalog

- images/dind/master/ovn-kubernetes-master.sh
use go-template format instead
> Fix ovn script so that apiserver can be fetched correctly

- publishing-kube-rules.yaml
> add skip-tags to publishing kube rules

- docs/cluster_up_down.md
fixes https://github.com/openshift/origin/issues/17461
> remove alternate platforms from cluster up documentation

- vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
> UPSTREAM: 67822: Remove provisioner config from log message

- vendor/k8s.io/kubernetes/pkg/controller/job/job_controller.go
> UPSTREAM: 66085: fix updateJob scheduling of resync

- hack/import-restrictions.json
- pkg/network/master/vnids.go
- pkg/oc/cli/admin/network/isolate_projects.go
- pkg/oc/cli/admin/network/join_projects.go
- pkg/oc/cli/admin/network/make_projects_global.go
- pkg/oc/cli/admin/network/pod_network.go
- pkg/oc/cli/admin/network/project_options.go
/assign @juanvallejo 
@openshift/sig-networking fyi
> Update admin network commands to use external clients

- pkg/cmd/server/start/start_kube_controller_manager.go
- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_imagetemplate.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1598334
cc @deads2k @liggitt @childsb
> Fix recylcer image

- pkg/oc/lib/describe/describer.go
- pkg/oc/lib/describe/describer_test.go
- test/cmd/images.sh
Add a new "Layers" field to describers that lists layers and size.
> Images should print their layers (too important to hide)

- test/extended/prometheus/prometheus.go
- test/extended/prometheus/prometheus_builds.go
> Switch prometheus tests to use cluster monitoring operator

- pkg/oc/clusterup/coreinstall/kubelet/dns.go
- pkg/oc/clusterup/run_self_hosted.go
It's way too late for Friday evening but there is something wrong in the `oc cluster up` with DNS, at least if you run dnsmasq on your machine, but I don't think this is enough to fix it.
> Fix DNS in oc cluster up for user having DNS on localhost

- pkg/oc/clusterup/run_self_hosted.go
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1622106
/cc @deads2k @sjenning @derekwaynecarr
>  Mount docker auth config into kubelet

- vendor/k8s.io/kubernetes/pkg/volume/flexvolume/detacher.go
- vendor/k8s.io/kubernetes/pkg/volume/flexvolume/unmounter.go
- vendor/k8s.io/kubernetes/pkg/volume/util/util.go
https://github.com/kubernetes/kubernetes/pull/67097
xref https://bugzilla.redhat.com/show_bug.cgi?id=1625640
@gnufied @jsafrane @derekwaynecarr
> UPSTREAM: 67097: Ignore EIO error in unmount path

- vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/predicates.go
- vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/predicates_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1608625
/sig storage
/sig scheduling
cc @jsafrane @liggitt
> UPSTREAM: 66397: Update scheduler to use different limits for m5/c5

- pkg/image/util/helpers.go
- pkg/oc/cli/tag/tag.go
- pkg/oc/cli/tag/tag_test.go
> Externalize oc tag

- test/extended/deployments/deployments.go
- test/extended/deployments/util.go
- test/extended/testdata/bindata.go
- test/extended/testdata/deployments/custom-deployment.yaml
- test/extended/testdata/deployments/test-deployment-test.yaml
> Add more logging to deployment tests and waiting for tests to set up

- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch.go
- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_recycler.go
Cherry pick of https://github.com/openshift/origin/pull/20925 to release-3.11
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1602793
> UPSTREAM: <carry>: simplify kube-controller-manager patches

- pkg/quota/image/imagestreamimport_evaluator.go
- pkg/quota/image/imagestreamtag_evaluator.go
- test/cmd/quota.sh
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1629519
/assign @mfojtik @deads2k 
@nhr fyi
> Fix image quota evaluators to support both internal and external resources

- pkg/oc/cli/admin/release/new.go
It was too easy / confusing for people who wanted to use a numeric
prefix to sort their manifests. Now, a user has to explicitly prefix
with 0000_ (which is stripped during the release build creation) to
get a global ordering.
> Use 0000_ as the "ordering" prefix for now

- test/util/server/server.go
> Extract the etcd start from intetration - step 1

- pkg/oc/clusterup/run_self_hosted.go
Signed-off-by: Praveen Kumar <kumarpraveen.nitdgp@gmail.com>
> Issue #20985 Don't mount the docker/config.json if file doesn't exist

- glide.lock
- glide.yaml
- vendor/github.com/openshift/library-go/pkg/assets/assets.go
- vendor/github.com/openshift/library-go/pkg/assets/template.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
RangelReale has given ownership of the osin repositories to Red Hat.
See RangelReale/osin#186
---
Currently waiting on the transfer process to be completed.
Proposed steps: https://github.com/RangelReale/osin/issues/186#issuecomment-419510401
cc @dobbymoodge
> Update glide to tolerate osin moving into openshift org

- vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/reconciler/reconciler.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1622245
/sig storage
> UPSTREAM: 67825: disable multiattach in vSphere

- hack/import-restrictions.json
- pkg/oc/cli/admin/prune/imageprune/helper.go
- pkg/oc/cli/admin/prune/imageprune/prune.go
- pkg/oc/cli/admin/top/graph.go
- pkg/oc/cli/admin/verifyimagesignature/verify-signature.go
- pkg/oc/cli/create/imagestreamtag.go
- pkg/oc/cli/debug/debug.go
- pkg/oc/cli/importimage/importimage.go
- pkg/oc/cli/logs/logs.go
- pkg/oc/cli/registry/info/info.go
- pkg/oc/cli/registry/login/login.go
- pkg/oc/cli/set/triggers.go
- pkg/oc/cli/startbuild/startbuild_test.go
- pkg/oc/cli/whoami/whoami.go
- pkg/oc/clusterup/up.go
- pkg/oc/lib/buildapihelpers/helpers.go
- pkg/oc/lib/describe/helpers.go
- pkg/oc/lib/graph/buildgraph/analysis/bc.go
- pkg/oc/lib/graph/buildgraph/edges.go
- pkg/oc/lib/graph/imagegraph/edges.go
- pkg/oc/lib/kubeconfig/smart_merge.go
- pkg/oc/lib/newapp/cmd/newapp.go
- pkg/oc/originpolymorphichelpers/logsforobject.go
- pkg/oc/util/clientcmd/resolve.go
- pkg/oc/util/clientcmd/resolve_test.go
- pkg/oc/util/project/util.go
- test/integration/login_test.go
- test/integration/oauth_oidc_test.go
- test/integration/webhook_token_auth_test.go
Further snips dependencies from `oc` on the core repo.
See: https://docs.google.com/spreadsheets/d/19beyAMX3Jp-rlh9i68DgXVSoE9OF3C9EiLs2rPJvpic/edit#gid=0
cc @soltysh @deads2k
> Remove internalclientset usage from oc helpers

- pkg/oc/cli/admin/migrate/migrator.go
This change updates `FindAllCanonicalResources` to check the verbs asserted by discovery for listing and updating capability.  This prevents us from trying to update aggregated resources such as pod metrics.
Bug 1631517
/kind bug
/cc @jupierce
> migrate: ignore resources that cannot be listed and updated

- vendor/k8s.io/kubernetes/pkg/util/mount/BUILD
- vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount.go
- vendor/k8s.io/kubernetes/pkg/util/mount/mount.go
- vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
- vendor/k8s.io/kubernetes/pkg/util/mount/mount_test.go
- vendor/k8s.io/kubernetes/pkg/util/mount/mount_windows.go
- vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount.go
https://bugzilla.redhat.com/show_bug.cgi?id=1631449
Verified that fix works.
/sig storage
> UPSTREAM: 68626: Fix mount options for netdev

- vendor/k8s.io/kubernetes/pkg/volume/flexvolume/driver-call.go
- vendor/k8s.io/kubernetes/pkg/volume/flexvolume/mounter.go
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1631834
@childsb
> UPSTREAM: 68680: Fix chown on distributed flex volumes (like gluster)

- hack/start-local.sh
Replaces previous local dev use of `openshift start`.
> Add a new simple start-local server option for quick iteration

- vendor/k8s.io/kubernetes/test/e2e/apps/cronjob.go
> UPSTREAM: 68820: Wait for events instead of just checking them in cronjob e2e

- test/cmd/status.sh
@juanvallejo you asked for it in #21073 
> Add job test for oc status

- pkg/cmd/openshift-apiserver/openshiftapiserver/configprocessing/audit.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1632155
> Bug 1632155 - Accept logFormat when passed to audit config

- vendor/k8s.io/kubernetes/test/e2e/storage/empty_dir_wrapper.go
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1622195
I will create a separate PR to re-enable the test
> UPSTREAM: 68023: Replace git volume with configmap in emptydir wrapper conflict test

- vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go
See https://github.com/kubernetes/kubernetes/pull/68980
> UPSTREAM: 68980: kubelet should not create pod sandbox

- pkg/cmd/openshift-kube-apiserver/configdefault/kubecontrolplane_default.go
- pkg/oc/clusterup/coreinstall/assets/render.go
- pkg/oc/clusterup/docker/openshift/helper.go
- pkg/oc/clusterup/docker/openshift/helper_unix.go
- pkg/oc/clusterup/run_self_hosted.go
- pkg/oc/clusterup/up.go
This matches the openshift/installer and the operator
> switch kube-apiserver port to 6443

- pkg/project/apiserver/registry/project/proxy/proxy.go
- pkg/project/auth/watch.go
- pkg/project/auth/watch_test.go
- pkg/project/util/util.go
- test/integration/project_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1633101
Fixes fieldSelector matching when watching Projects.
> fix projects when watching with selector

- test/extended/util/test.go
Use namespace labels to prevent SCC usage.  This will prevent using openshift APIs when they may not be available.
/assign @derekwaynecarr 
/cc @abhinavdahiya
> use namespace labels to prevent SCC usage

- examples/jenkins/pipeline/README.md
- examples/jenkins/pipeline/bluegreen-pipeline.yaml
- examples/jenkins/pipeline/mapsapp-pipeline.yaml
- examples/jenkins/pipeline/maven-pipeline.yaml
- examples/jenkins/pipeline/samplepipeline.yaml
- pkg/oc/clusterup/manifests/bindata.go
- test/extended/testdata/bindata.go
@openshift/sig-developer-experience
> Upd jenkins samples old plugin

- pkg/oc/clusterup/coreinstall/controlplane-operator/run_render.go
- pkg/oc/clusterup/run_self_hosted.go
Counterpart of https://github.com/openshift/cluster-kube-controller-manager-operator/pull/31
> cluster-up: no --manifest-lock-host-path for controller manager

- vendor/k8s.io/kubernetes/pkg/volume/iscsi/BUILD
- vendor/k8s.io/kubernetes/pkg/volume/iscsi/attacher.go
- vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi.go
- vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go
- vendor/k8s.io/kubernetes/pkg/volume/util/device_util.go
- vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
- vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux_test.go
- vendor/k8s.io/kubernetes/pkg/volume/util/device_util_unsupported.go
- vendor/k8s.io/kubernetes/pkg/volume/util/io_util.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1637422 and https://bugzilla.redhat.com/show_bug.cgi?id=1627962
@openshift/storage @humblec
> 4.0: iSCSI multipath issues

- pkg/authorization/authorizer/project_request_info_resolver.go
Fixes https://github.com/openshift/origin/issues/20251.
> RequestInfoResolver: restrict special project logic to project API groups

- pkg/cmd/openshift-controller-manager/configdefault/openshiftcontrolplane_default.go
fixes https://github.com/openshift/cluster-openshift-controller-manager-operator/issues/19
Sets some missing controller manager tuning defaults.
> fix defaults for openshift-controller-manager

- pkg/oc/clusteradd/components/web-console-operator/web_console_operator.go
Since cherry pick for https://github.com/openshift/origin/pull/20353#issuecomment-427762139 was having a conflict so this should do it.
cc @mfojtik @deads2k @juanvallejo
> Fix #20203 for release-3.10 branch

- examples/jenkins/README.md
@openshift/sig-developer-experience fyi ptal
> remove refs to old plugin in base jenkins readme

- pkg/configconversion/simple.go
Another one for admission to make #21096 working.
> Filter kubernetes admission plugins

- vendor/k8s.io/kubernetes/pkg/volume/iscsi/BUILD
- vendor/k8s.io/kubernetes/pkg/volume/iscsi/attacher.go
- vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi.go
- vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go
- vendor/k8s.io/kubernetes/pkg/volume/util/device_util.go
- vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
- vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux_test.go
- vendor/k8s.io/kubernetes/pkg/volume/util/device_util_unsupported.go
- vendor/k8s.io/kubernetes/pkg/volume/util/io_util.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1637413
@openshift/sig-storage @humblec
> 3.11: Fix iSCSI multipath issues

- pkg/apiserver/admission/chain_builder.go
> Move openshift.io/RestrictSubjectBindings to kube admissions

- pkg/oc/clusterup/up.go
This is what an easy fix we see to make sure the user doesn't affect with #21153 issue from minishift point of view.
cc @mfojtik @deads2k
> Issue #21153 update the console URI not to redirect 127.0.0.1

- hack/build-local-images.py
Will use specified tag for built images
> Adding OS_IMAGE_TAG env var

- pkg/oc/cli/admin/release/new.go
Make this important functionality more discoverable, since it's very useful for testing operators ;).
CC @smarterclayton, @sallyom, @sjenning
> pkg/oc/cli/admin/release/new: Document SRC=DST positional args

- pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/flags.go
> Wire tls-sni-cert-key flag

- pkg/cmd/server/kubernetes/master/master_config.go
> Bug 1632154 - Accept logFormat when passed to audit config

- pkg/apiserver/admission/chain_builder.go
- pkg/apiserver/admission/config_test.go
- pkg/configconversion/legacyconfig_conversion.go
- pkg/configconversion/simple.go
> Filter kubernetes plugins but only when building kubernetes config

- pkg/apiserver/admission/chain_builder.go
- pkg/apiserver/admission/config_test.go
- pkg/apiserver/admission/register.go
- pkg/cmd/openshift-apiserver/openshiftapiserver/config.go
> Disable admission's DefaultOffPlugins unless they are explicitly enabled

- test/extended/testdata/cluster/OWNERS
Nobody else works on these tests, so we need some owners to review and approve changes.
> Create new testdata/cluster OWNERS file

- vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/reconciler/reconciler.go
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1640791
> UPSTREAM: 67825: fix vsphere multiattach issue

- pkg/oc/cli/cli.go
This patch allows the `oc` binary to be used as a kubectl plugin
based on the "plugin name" that it is given. For example, renaming
or symlinking `oc` to `kubectl-login` (anywhere on your PATH) will
cause `oc` to be invoked as a plugin from `kubectl`. The `oc`
binary will, based on this filename, behave solely as the "login"
command when invoked.
```bash
$ sudo ln -s /path/to/oc /usr/local/bin/kubectl-whoami
$ kubectl plugin list
The following kubectl-compatible plugins are available:
/usr/local/bin/kubectl-whoami
```
```bash
$ kubectl whoami
system:admin
$ kubectl whoami --show-server
https://local-api.tt.testing:6443
```
```bash
$ sudo ln -s /path/to/oc /usr/local/bin/kubectl-new_app
$ kubectl plugin list
The following kubectl-compatible plugins are available: …
```
> allow oc to behave as a kubectl plugin based on filename

- vendor/k8s.io/kubernetes/test/e2e/apps/cronjob.go
needed by https://github.com/openshift/origin/pull/21193 to continue chasing down test flakes
@smarterclayton @soltysh @mrunalp PTAL
> [release-1.11] Backport cronjobs fixes

- pkg/apiserver/admission/chain_builder.go
- pkg/apiserver/admission/config_test.go
- pkg/apiserver/admission/register.go
- pkg/apiserver/admission/sync_test.go
- pkg/cmd/openshift-kube-apiserver/server.go
> Remove CombinedAdmissionControlPlugins from kube-api startup and enable only kube-specific ones

- vendor/k8s.io/kubernetes/test/e2e/apps/cronjob.go
Backport https://github.com/kubernetes/kubernetes/pull/70206 for CRI testing in https://github.com/openshift/origin/pull/21193
@smarterclayton @soltysh PTAL
> UPSTREAM: 70206: test/e2e/apps: fix race in cronjob test

- pkg/oc/originpolymorphichelpers/attachablepodforobject.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1642745
cc @soltysh
> handle appsv1.DeploymenConfigs in AttachablePodForObject helper

- pkg/network/node/ovscontroller.go
Backport of #21363
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1643964
> [3.11] Don't allow pods to send VXLAN packets out of the SDN

- pkg/configconversion/simple.go
- test/integration/clusterquota_test.go
- test/util/server/server.go
> Switch integration test to manually starting kube & openshift controller managers

- install/openshift-web-console-operator/install.yaml
- pkg/oc/clusterup/manifests/bindata.go
- test/extended/testdata/bindata.go
Have a look to https://github.com/openshift/origin-web-console-server/issues/37 and https://github.com/openshift/openshift-ansible/pull/8558/files , This will also solve minishift issue https://github.com/minishift/minishift/issues/2809
> Change file permissions on console serving cert

- publishing-rules.yaml
We need to publish to the correct level of our kube fork
> publish to the correct branch

- pkg/cmd/openshift-apiserver/openshiftapiserver/informers.go
- pkg/cmd/server/origin/informers.go
- pkg/cmd/server/origin/master_config.go
> switch to use external authz informers

- vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
>     UPSTREAM: 66612: Remove `auto_unmount` mount option from pv spec annotation.

- pkg/apiserver/admission/plugin_initializer.go
- pkg/cmd/openshift-apiserver/openshiftapiserver/informers.go
- pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
- pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
- pkg/cmd/server/admission/init.go
- pkg/cmd/server/admission/types.go
- pkg/cmd/server/bootstrappolicy/securitycontextconstraints_test.go
- pkg/cmd/server/origin/informers.go
- pkg/cmd/server/origin/legacyadmission/plugin_initializer.go
- pkg/cmd/server/origin/master_config.go
- pkg/security/apiserver/admission/sccadmission/admission.go
- pkg/security/apiserver/admission/sccadmission/admission_test.go
- pkg/security/apiserver/admission/sccadmission/scc_exec.go
- pkg/security/apiserver/admission/sccadmission/scc_exec_test.go
- pkg/security/apiserver/admission/testing/util.go
- pkg/security/apiserver/apiserver.go
- pkg/security/apiserver/registry/podsecuritypolicyreview/rest_test.go
- pkg/security/apiserver/registry/podsecuritypolicyselfsubjectreview/rest_test.go
- pkg/security/apiserver/registry/podsecuritypolicysubjectreview/rest_test.go
- pkg/security/apiserver/securitycontextconstraints/matcher.go
- pkg/security/apiserver/securitycontextconstraints/provider.go
- pkg/security/securitycontextconstraints/util/sort/bypriority.go
- pkg/security/securitycontextconstraints/util/sort/bypriority_test.go
- pkg/security/securitycontextconstraints/util/sort/byrestrictions.go
- pkg/security/securitycontextconstraints/util/sort/byrestrictions_test.go
- pkg/security/securitycontextconstraints/util/util.go
- pkg/security/securitycontextconstraints/util/util_test.go
cc @deads2k 
Related upstream PR https://github.com/kubernetes/kubernetes/pull/69685
> switch to external security informers

- pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
> remove unused image informer

- publishing-kube-rules.yaml
/assign @deads2k @sttts @mfojtik
> Set up 1.12.2 branch publishing

- examples/image-streams/README.md
- examples/image-streams/image-streams-centos7.json
- examples/image-streams/image-streams-rhel7.json
- examples/quickstarts/cakephp-mysql-persistent.json
- examples/quickstarts/cakephp-mysql.json
- test/extended/testdata/bindata.go
@bparees ptal
Will this make .NET Core available on Red Hat CDK?
> update-external-examples to include .NET Core on RHEL7

- hack/local-up-master/kube-apiserver.yaml
- test/cmd/observe.sh
- test/testdata/external-service.yaml
- test/testdata/multiport-service.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1639461
Revers CIDR changes to observe.sh tests introduced in https://github.com/openshift/origin/pull/21206
> update localup-master Service CIDR

- hack/local-up-master/lib.sh
- hack/test-cmd.sh
> Log proper logging directory

- README.md
https://bugzilla.redhat.com/show_bug.cgi?id=1649227
> Fix bug 1649227: 404 url

- pkg/build/controller/build/build_controller.go
- pkg/build/controller/build/build_controller_test.go
- test/extended/builds/pullsecret.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/test-docker-app/Dockerfile
bug https://bugzilla.redhat.com/show_bug.cgi?id=1649062
> [3.11] fallback to the default builder SA secret for build pushes/pulls

- pkg/build/controller/build/build_controller.go
- pkg/build/controller/build/build_controller_test.go
- test/extended/builds/pullsecret.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/test-docker-app/Dockerfile
fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1648775
> [3.10] fallback to the default builder SA secret for build pushes/pulls

- pkg/build/controller/build/build_controller.go
- pkg/build/controller/build/build_controller_test.go
- test/extended/builds/pullsecret.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/test-docker-app/Dockerfile
bug https://bugzilla.redhat.com/show_bug.cgi?id=1649063
> fallback to the default builder SA secret for build pushes/pulls

- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vclib/virtualmachine.go
- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vsphere.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1645260
> UPSTREAM: 70291: don't delete vsphere node on shutdown

- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vclib/virtualmachine.go
- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vsphere.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1645258
> UPSTREAM: 70291: do not delete vsphere nodes when instance is shutdown

- pkg/proxy/hybrid/proxy.go
There are cases where switchService is called twice as a service is being unidled. This can cause the service to never actually appear back in the main proxy.
Rather than tracking down the logic bugs, just add some more state and short-circuit when called incorrectly.
> proxy: Don't allow multiple calls to switchService

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
Fix Bug 1649727 - Some pods in running state but not accessible via rsh or exec
> UPSTREAM: 67288: immediately close the other side of the connection when proxying

- vendor/k8s.io/kubernetes/pkg/util/mount/BUILD
- vendor/k8s.io/kubernetes/pkg/util/mount/exec_mount.go
- vendor/k8s.io/kubernetes/pkg/util/mount/mount.go
- vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
- vendor/k8s.io/kubernetes/pkg/util/mount/mount_test.go
- vendor/k8s.io/kubernetes/pkg/util/mount/mount_windows.go
- vendor/k8s.io/kubernetes/pkg/util/mount/nsenter_mount.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1640746
> UPSTREAM: 68626: fix netdev mount option

- hack/test-cmd.sh
> Clean FAKE_HOME_DIR before executing test-cmd.sh

- hack/local-up-master/lib.sh
More fixes to test-cmd so that it's easier to run and debug. We should eventually switch all to use our logging which is sooooo much better (kudos to @stevekuznetsov).
> Check for free ports when starting master in test-cmd

- pkg/cmd/openshift-apiserver/openshiftapiserver/config.go
- pkg/cmd/openshift-apiserver/openshiftapiserver/project.go
- pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
- pkg/cmd/server/origin/master_config.go
- pkg/image/apiserver/admission/imagepolicy/imagepolicy_test.go
- pkg/project/apiserver/admission/nodeenv/admission_test.go
- pkg/project/apiserver/admission/requestlimit/admission.go
- pkg/project/apiserver/admission/requestlimit/admission_test.go
- pkg/project/auth/watch.go
- pkg/project/auth/watch_test.go
- pkg/project/cache/cache.go
- pkg/project/util/util.go
- pkg/quota/apiserver/admission/clusterresourceoverride/admission_test.go
- pkg/quota/apiserver/admission/runonceduration/admission_test.go
- pkg/quota/controller/clusterquotamapping/clusterquotamapping.go
- pkg/quota/controller/clusterquotamapping/clusterquotamapping_test.go
> switch to use kcorev1 informers in project cache

- pkg/proxy/hybrid/proxy.go
This backports #21387 to 3.10.
There are cases where switchService is called twice as a service is
being unidled. This can cause the service to never actually appear back
in the main proxy.
Rather than tracking down the logic bugs, just add some more state and
short-circuit when called incorrectly.
> backport proxy: Don't allow multiple calls to switchService

- hack/cherry-pick.sh
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3/BUILD
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3/logger.go
Gives us etcd logs like for connection or TLS issues.
> UPSTREAM: 71318: apiserver: set glog as etcdclient logger

- pkg/network/node/iptables.go
Backport of https://github.com/openshift/origin/pull/21441
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1653381
> [3.10] Ensure Egress IP rules are recreated after firewalld reload

- pkg/apps/strategy/support/acceptor.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1638140
Not particularly smart or handling other cases but could be reasonable until we get UntilWithSync from the rebase.
Let's see if this passes the CI.
/cc @mfojtik @damemi
> DC: handle closed watch in deployer acceptor

- test/extended/util/test.go
It is flaking extremely often - 3/4 runs.
> Temporarily flag the pruning test as flaky

- test/extended/util/test.go
This reverts commit c6b7b7e1ec0761dc84f21f825cf2937793f1ff34.
> Revert "Temporarily flag the pruning test as flaky"

- pkg/oc/cli/image/info/info.go
- pkg/oc/cli/image/manifest/manifest.go
Print an error that lists the available images and let the user select
one with --filter-by-os.
```
oc image info registry.access.redhat.com/rhel7:latest
error: the image is a manifest list and contains multiple images - use --filter-by-os to select from:
OS            DIGEST
linux/amd64   sha256:2fb67122fa3a8e14565016865ca67402e00f055ba7dba6febd8999b650beef72
linux/ppc64le sha256:806a6140f248c8eca39b2f3a98469415c08c575e17e5d7a733e3d31df3df83ca
linux/s390x   sha256:58e18319993c8f61dbb09c24167b638ae14d66d62dda92c585a40ce37b4964fc
```
> Ensure `oc image info` works with manifest lists

- contrib/migration/migrate-network-policy.sh
Fixes two issues with the networkpolicy migration script:
1. If you run the migration script, then run the unmigration script, then run the migration script again, it errors out the second time, becuase the policies already exist. This changes it to just assume that if policies with the expected names already exist, then they presumably are the right policies.
2. In at least one case, a customer had a few crufty NetNamespace objects that did not correspond to any existing Namespace. So we clean those up before migrating now if they exist.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1626207
Fixes #20618
> Fix some bugs in the networkpolicy migration script

- test/extended/builds/s2i_quota.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/test-s2i-build-quota.json
needs https://github.com/openshift/builder/pull/26 before it can merge.
> re-enable cgroup quota checking build tests

- pkg/router/controller/host_admitter_test.go
@smarterclayton  as requested added an extra specific test for unmodified wildcard and non-wildcard routes for host_admitter - btw, this is also covered albeit a wee bit differently with tests in `TestDisableOwnershipChecksFuzzing`. PTAL Thx
*Edited* also added a check for no rejections on plain routes that the original PR addressed.
> Router: add disable namespace check test for host_admitter using unchanged routes

- pkg/oc/cli/image/extract/extract.go
- pkg/oc/cli/image/workqueue/workqueue.go
We were dependent on responses coming quickly, and we must guarantee
we return from the provided function before continuing.
This is currently blocking OCP release builds, because we have to pull through from quay which is slightly slower than our internal registry and triggers the bug.
> The workqueue for image extract can hang when downloads are very slow

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware_test.go
pick of the OSE fix
/assign @eparis
> UPSTREAM: 00000: Verify backend upgrade

- vendor/k8s.io/kubernetes/pkg/probe/http/http.go
- vendor/k8s.io/kubernetes/pkg/probe/http/http_test.go
Picks: https://github.com/kubernetes/kubernetes/pull/68663
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1639137
cc @praveenkumar @smarterclayton @soltysh
> Ignore kubelet proxy settings in http probe

- cmd/openshift-tests/e2e.go
> add jenkins e2e suite to play nice with openshift-tests

- hack/build-local-images.py
Option to not use docker via `OS_USE_BUILDAH` env var.
> build local images with buildah

- images/router/f5/Dockerfile
bug: 1645755
https://bugzilla.redhat.com/show_bug.cgi?id=1645755
> Add openssh-clients package to f5-router

- pkg/image/apiserver/apiserver.go
configmap is mounted by https://github.com/openshift/cluster-openshift-apiserver-operator/pull/89
> read image import CAs from mounted configmap

- vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/cache/actual_state_of_world.go
- vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/BUILD
- vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler_test.go
- vendor/k8s.io/kubernetes/pkg/volume/testing/testing.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1659653
> UPSTREAM: 71074: fix device path being empty

- images/cli/OWNERS
- images/hyperkube/OWNERS
- images/hypershift/OWNERS
- images/tests/OWNERS
Removing myself from any remaining OWNERS in origin
since I no longer actively approve PRs here.
/cc @mfojtik
> Remove kargakis from OWNERS

- vendor/k8s.io/kubernetes/pkg/scheduler/cache/node_info.go
- vendor/k8s.io/kubernetes/pkg/scheduler/cache/node_info_test.go
Upstream PRs:
https://github.com/kubernetes/kubernetes/pull/67481
https://github.com/kubernetes/kubernetes/pull/67456
Fix rhbz: https://bugzilla.redhat.com/show_bug.cgi?id=1647474 
@sjenning
> UPSTREAM: 67456:fix an issue in NodeInfo.Clone()

- pkg/template/controller/templateinstance_controller.go
- test/extended/templates/templateinstance_fail.go
- test/extended/testdata/bindata.go
- test/extended/testdata/templates/templateinstance_badobject.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1662339
> properly handle object creation error in template instantiate

- test/extended/networking/multicast.go
The multicast extended test currently sends just a single UDP packet between each pair of pods, so if the network is dropping packets, it could fail spuriously. This changes it to send 5 packets and only fail if *all* of them are lost.
Fixes #19218 
(hopefully)
> Make the multicast extended test resilient to packet loss

- test/extended/operators/operators.go
I don't know why this isn't blocking origin but it's definitely blocking other repos that run e2e-aws:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-openshift-controller-manager-operator/49/pull-ci-openshift-cluster-openshift-controller-manager-operator-master-e2e-aws/161
given that operators shouldn't be creating those objects any more and service signing is the only one doing it and it's not populating the conditions properly, this seems like the most expedient fix.
> stop looking at legacy clusteroperator objects and fix the clusteroperator status test

- publishing-kube-rules.yaml
> Set up 1.12.4 branch publishing

- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/metrics.go
fix bug 1571176
https://bugzilla.redhat.com/show_bug.cgi?id=1571176
> [3.11] MetricsApiProxy diagnostic: fix endpoint

- cmd/openshift-tests/openshift-tests.go
> Support openshift-test profiling like all the other binaries

- pkg/oc/admin/diagnostics/diagnostics/cluster/metrics.go
fix bug 1571176
https://bugzilla.redhat.com/show_bug.cgi?id=1571176
> [3.10] MetricsApiProxy diagnostic: fix endpoint

- pkg/monitor/cmd.go
- pkg/monitor/event.go
> make sure event messages end up one one line and include counts

- test/extended/util/metrics.go
In between the pass and now, the operators have gotten chattier.
> set the QPS ratchet correctly

- pkg/oc/cli/admin/admin.go
cc @soltysh 
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1664842
> improve deprecation message for non-ca adm cmds

- pkg/build/controller/build/build_controller.go
- pkg/build/controller/build/defaults/defaults.go
- pkg/build/controller/build/defaults/defaults_test.go
Depends on #21614 
Apply default proxy configuration to build pod through env vars
> Apply default proxy configuration to build pod through env vars

- publishing-rules.yaml
> Update publisher bot for the master branch

- vendor/k8s.io/kubernetes/pkg/kubelet/pleg/generic.go
- vendor/k8s.io/kubernetes/pkg/kubelet/pleg/generic_test.go
https://github.com/kubernetes/kubernetes/pull/69008
xref https://bugzilla.redhat.com/show_bug.cgi?id=1632430
> UPSTREAM: 69008: improve pleg error msg when it has never been successful

- vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/client-gen/generators/client_generator.go
This will allow me to generate https://github.com/openshift/api/pull/188
> UPSTREAM: <carry>: don't double pluralize features

- test/extended/deployments/util.go
> Add better logging to deployerPodInvariantChecker

- test/extended/deployments/deployments.go
Fixes: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/21911/pull-ci-openshift-origin-master-e2e-aws/3123
/cc @mfojtik
> test/extended: Wait for DC to be seen by DC controller

- vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/client-gen/generators/client_generator.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/informer-gen/generators/generic.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/informer-gen/generators/packages.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/lister-gen/generators/lister.go
I missed the lister and informer gen. I added a comment to remind me next time.
/assign @sttts
> UPSTREAM: <carry>: update informer and lister gen for Features

- pkg/build/apis/build/validation/validation.go
- pkg/build/apis/build/validation/validation_test.go
- pkg/oc/cli/set/buildhook.go
- test/cmd/setbuildhook.sh
- Remove documentation to set args on default entrypoint
- Update/add/remove tests
- Fix --script option not working with --all
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1670000
> Update set post-commit

- pkg/oc/cli/cli.go
- pkg/oc/cli/kubectl_compat_test.go
- pkg/oc/cli/kubectlwrappers/wrappers.go
- tools/clicheck/check_cli_conventions.go
- tools/gendocs/gen_openshift_docs.go
- tools/genman/gen_man.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cmd.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cmd_test.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/plugin.go
Will open upstream PR once we reach some general consensus on this approach
~~Work in progress, will need to also patch the `plugin list` command.~~
cc @soltysh
> add plugin support oc prefix

- vendor/k8s.io/kubernetes/pkg/kubelet/eviction/api/types.go
- vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go
- vendor/k8s.io/kubernetes/pkg/kubelet/eviction/helpers.go
- vendor/k8s.io/kubernetes/pkg/kubelet/eviction/helpers_test.go
- vendor/k8s.io/kubernetes/test/e2e_node/BUILD
- vendor/k8s.io/kubernetes/test/e2e_node/eviction_test.go
@RobertKrawitz @derekwaynecarr 
https://github.com/kubernetes/kubernetes/pull/72844
> UPSTREAM: 72844: Fix PidPressure, and add fork-bomb e2e-node test

- glide.lock
> bump(k8s.io/kubernetes): fix kubernetes revisions

- vendor/k8s.io/kubernetes/pkg/printers/internalversion/printers.go
- vendor/k8s.io/kubernetes/pkg/printers/internalversion/printers_test.go
Picks https://github.com/kubernetes/kubernetes/pull/70466
cc @soltysh
> UPSTREAM: 70466: add Ready column for kubectl get sts command

- contrib/completions/OWNERS
- docs/man/OWNERS
- hack/clibyexample/OWNERS
- pkg/bulk/OWNERS
- pkg/cmd/OWNERS
- pkg/oc/OWNERS
- pkg/oc/cli/admin/router/OWNERS
- pkg/unidling/OWNERS
- pkg/version/OWNERS
- test/cmd/OWNERS
- tools/OWNERS
- tools/clicheck/OWNERS
- tools/depcheck/OWNERS
- tools/genman/OWNERS
> remove juanvallejo from OWNERS files

- pkg/build/controller/build/build_controller.go
- pkg/build/controller/build/build_controller_test.go
- pkg/build/controller/strategy/util.go
- pkg/build/controller/strategy/util_test.go
- pkg/build/util/consts.go
- pkg/cmd/openshift-controller-manager/controller/interfaces.go
- test/extended/builds/cluster_config.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/cluster-config.yaml
- test/extended/testdata/builds/cluster-config/registry-blacklist.yaml
- test/extended/testdata/builds/cluster-config/registry-search.yaml
- test/extended/testdata/builds/cluster-config/registry-whitelist.yaml
This will allow https://github.com/openshift/api/pull/192 to bump cleanly in origin.
> Ignore Search Registries for Build Controller Config

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/set/set_env.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/set/set_image.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/set/set_resources.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/set/set_serviceaccount.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/set/set_subject.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/resource/visitor.go
> UPSTREAM: 65636: fix --local panic in set commands

- vendor/k8s.io/kubernetes/cmd/kubelet/app/options/options.go
- vendor/k8s.io/kubernetes/pkg/features/kube_features.go
- vendor/k8s.io/kubernetes/pkg/kubelet/apis/kubeletconfig/types.go
- vendor/k8s.io/kubernetes/pkg/kubelet/apis/kubeletconfig/v1beta1/defaults.go
- vendor/k8s.io/kubernetes/pkg/kubelet/cm/cgroup_manager_linux.go
- vendor/k8s.io/kubernetes/test/e2e_node/BUILD
UPSTREAM: 72076: SupportPodPidsLimit feature beta with tests
UPSTREAM: 73034: [Text Fix] Fix panic in NodeAllocatable node e2e test
>  UPSTREAM: 72076: SupportPodPidsLimit feature beta with tests 

- pkg/cmd/openshift-osinserver/server.go
> Wire CORS to openshift-osinserver command

- test/extended/deployments/util.go
> Fix deployerPodInvariantChecker error string

- pkg/image/apis/image/v1/conversion.go
- pkg/image/apis/image/validation/whitelist/whitelister.go
- pkg/image/apiserver/registry/image/strategy.go
- pkg/oc/cli/debug/debug.go
replace some loops with idiomatic go
> nits: replace unnecessary loops

- pkg/monitor/event.go
Reduces a lot of pointless noise in monitor logs
> Only add event count if greater than one

- test/extended/testdata/bindata.go
- test/extended/testdata/builds/statusfail-oomkilled.yaml
Ensures pod schedules and fails during image pull.
> builds - Increase RAM for OOMKilled test.

- test/extended/router/metrics.go
- Also fixed router test cases related to metrics
> Added router test to check if openshift-monitoring is able to pull haproxy metrics

- test/extended/prometheus/prometheus_builds.go
- test/extended/util/framework.go
Dump Prometheus pod state and logs on prometheus builds failure.
> e2e - Dump State for Prometheus

- pkg/cmd/openshift-apiserver/openshiftadmission/chain_builder.go
- pkg/cmd/openshift-apiserver/openshiftapiserver/config.go
Remove our custom admission plugin loading code and collapse onto the upstream functions
> remove all custom admission loading code

- vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go
Fixes https://github.com/openshift/origin/issues/21979
/sig storage
/sig node
> UPSTREAM: 70821: Fix flake in plugin watcher

- test/extended/util/test.go
We should have latest kubelet version now
> Re-enable volume limit tests

- pkg/cmd/server/bootstrappolicy/policy.go
- test/extended/deployments/deployments.go
- test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
- test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
/cc @soltysh @openshift/sig-master @openshift/sig-auth
> Fix deployer permissions

- images/base/Dockerfile.rhel
- images/cli/Dockerfile.rhel
- images/deployer/Dockerfile.rhel
- images/hyperkube/Dockerfile.rhel
- images/hypershift/Dockerfile.rhel
- images/pod/Dockerfile.rhel
- images/recycler/Dockerfile.rhel
- images/sdn/Dockerfile.rhel
- images/template-service-broker/Dockerfile.rhel
- images/tests/Dockerfile.rhel
Reduce the size of origin images by moving to UBI based images.  Switch to multistage builds in place.  Shrink SDN.
> UBI images

- test/extended/router/metrics.go
Another fix is coming shortly.
> Temporarily mark the router prometheus metrics test as flaky

- cmd/openshift-tests/openshift-tests.go
- cmd/openshift-tests/upgrade.go
- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/test.go
- test/e2e/upgrade/upgrade.go
- test/extended/util/test.go
- vendor/k8s.io/kubernetes/test/e2e/upgrades/apparmor.go
- vendor/k8s.io/kubernetes/test/e2e/upgrades/apps/daemonsets.go
- vendor/k8s.io/kubernetes/test/e2e/upgrades/ingress.go
- vendor/k8s.io/kubernetes/test/e2e/upgrades/nvidia-gpu.go
- vendor/k8s.io/kubernetes/test/e2e/upgrades/services.go
- vendor/k8s.io/kubernetes/test/e2e/upgrades/sysctl.go
```
openshifts-tests run-upgrade --to-image=X --include-success all
```
Upgrades to image X.  You can pass `[pause]` instead of X to run the tests but not do an upgrade.
> Add openshift-tests run-upgrade * to qualify upgrades

- pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_handlerchain.go
The oauthconfig is about to become truly optional.  https://github.com/openshift/cluster-authentication-operator/pull/59  is needed.
/assign @mfojtik @soltysh
> disable the oauth server in kubeapiserver

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go
Needs:
https://github.com/openshift/machine-api-operator/pull/202
https://github.com/openshift/installer/pull/1215
https://github.com/openshift/cluster-autoscaler-operator/pull/43
> Update protected OpenShift namespaces: openshift-machine-api

- pkg/oc/cli/admin/release/new.go
Prevent "dumping ground" of versions by putting a check in unrestricted
addition. Eventually will be removed.
> release: Create a list of allowed versions that are strongly controlled

- pkg/network/node/networkpolicy.go
Straight backport of #22106.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1679268
> [3.11] Use BoundedFrequencyRunner to limit the rate of NetworkPolicy updates

- pkg/network/node/networkpolicy.go
Straight backport of #22106
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1679269
> [3.10] Use BoundedFrequencyRunner to limit the rate of NetworkPolicy updates

- pkg/oc/cli/admin/upgrade/upgrade.go
> Fix typo in oc adm upgrade message

- docs/cli_hacking_guide.adoc
- builder has move to https://github.com/openshift/builder
- fix wrong package and method name of cmdutil
> Fix the wrong doc

- vendor/k8s.io/kubernetes/pkg/kubelet/images/image_manager.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go
- vendor/k8s.io/kubernetes/pkg/volume/util/recyclerclient/recycler_client_test.go
Improve the legibility and consistency of these events.
> UPSTREAM: 73892: Report more consistent container start/stop/kill events

- vendor/k8s.io/kubernetes/cluster/gce/config-test.sh
- vendor/k8s.io/kubernetes/test/e2e/storage/mounted_volume_resize.go
- vendor/k8s.io/kubernetes/test/e2e/storage/volume_expand.go
- vendor/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go
Also make sure we have a test to capture the behaviour that admission controller is enabled.
https://bugzilla.redhat.com/show_bug.cgi?id=1671837
> Enable volume resize tests to run by default

- pkg/oc/cli/admin/release/extract.go
- pkg/oc/cli/admin/release/info.go
Reuse the same logic as `oc adm release extract`.
Blocks release controller being able to show change logs when you access
the page.
> `oc adm release info --changelog` should clone if necessary

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
Fix the previous PR by pull the sleep out to the Run method of the server. Before the handler chain wait group got the undelayed channel, but the server was delayed, leading to the "shutting down" messages.
> UPSTREAM: 74416: apiserver: add --minimal-shutdown-duration to delay until endpoint convergence

- test/extended/bootstrap_user/bootstrap_user_login.go
The OAuth server may not be ready when this test runs.  Thus we need to poll for a while to make sure any failures are not flakes.
> Poll in bootstrap user e2e test

- pkg/admission/customresourcevalidation/features/OWNERS
> Fix deads2k typo in features OWNERS

- .travis.yml
https://travis-ci.org/openshift/origin/builds/499298642
> [3.11] Fix OS_GIT_MAJOR: unbound variable

- pkg/oc/cli/admin/release/git.go
Missed a few spots when cleaning up earlier.
> Ensure clone works without `-C` for release extraction

- vendor/k8s.io/kubernetes/pkg/volume/iscsi/BUILD
- vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go
Upstream issue: https://github.com/kubernetes/kubernetes/issues/74523
Upstream PR: https://github.com/kubernetes/kubernetes/pull/74524
/sig storage
/assign @jsafrane @wongma7 @gnufied
> UPSTREAM: 74524: Don't fail if iface is being used by iSCSI session

- pkg/oc/cli/image/info/info.go
This is re-pick of https://github.com/openshift/origin/pull/21963.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1666583
I'm self-tagging since this was a clean pick w/o any modifications.
> Bug 1666583 - improve image layer size output when size info not available

- docs/rebase.md
Signed-off-by: Zhou Peng <p@ctriple.cn>
> docs/rebase.md: fix word typo

- pkg/oc/cli/admin/prune/deployments/prune.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1684368
Previously we've been manually removing but only failed deployments.
Now that we have proper ower references set we can leave the GC proper
cleaning of all dependents.
> Bug 1684368 - Use proper deletion propagation policy when removing deployments

- HACKING.md
> explain UPSTREAM: 00000:

- test/extended/builds/cluster_config.go
Temporary change until [BZ 1685185](https://bugzilla.redhat.com/show_bug.cgi?id=1685185) is fixed.
> TEMP: Disabling build cluster config tests

- pkg/oc/cli/admin/release/info.go
Makes markdown more effective.
> release: Add newlines to descriptions in changelog

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/authorization.go
> UPSTREAM: 74956: make delegating authorization use protobuf client

- vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/aggregator.go
- vendor/k8s.io/kubernetes/pkg/kubeapiserver/authenticator/config.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/serving.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/single_certkey_pair.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiservice_controller.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy_test.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/cmd/server/start.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller_test.go
Adds one commit to dynamically reload aggregator certs
> dynamically reload aggregator cert

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/clientca.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/serving.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/authentication.go
Adds logging for certs and fixes client-ca issue.  Also prevents resetting to empty certs
> cert logging

- examples/db-templates/OWNERS
- examples/hello-openshift/OWNERS
- examples/image-streams/OWNERS
- examples/quickstarts/OWNERS
- examples/sample-app/OWNERS
- pkg/admission/customresourcevalidation/image/OWNERS
- pkg/api/OWNERS
- pkg/build/OWNERS
- pkg/image/OWNERS
- pkg/oc/cli/admin/prune/imageprune/OWNERS
- pkg/oc/lib/newapp/OWNERS
- pkg/openapi/OWNERS
- pkg/template/OWNERS
- test/extended/OWNERS
- tools/buildanalyzer/OWNERS
> Add adambkaplan as DevEx approver

- pkg/oc/cli/registry/info/info.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1665357
> Bug  1665357 - update oc registry info help message

- test/OWNERS
> Add soltysh to test approvers

- pkg/oc/lib/newapp/cmd/describe.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1564849
> Bug 1564849 - Fix oc command suggestions in new-app

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp_test.go
> UPSTREAM: 75037: Fix panic in kubectl cp command

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/plugin.go
Someone was asking about plugins for oc on windows, so I've picked the necessary bits. 
> Added windows executable extensions to Kubectl plugins

- pkg/oc/cli/admin/release/info.go
https://bugzilla.redhat.com/show_bug.cgi?id=1686322
> Fix URL ( bug 1686322 )

- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
- vendor/k8s.io/kubernetes/test/e2e_node/BUILD
- vendor/k8s.io/kubernetes/test/e2e_node/system_node_critical_test.go
UPSTREAM: 74222: kubelet: return mirror pod in GetActivePods()
> UPSTREAM: 74222: kubelet: return mirror pod in GetActivePods()

- test/extended/util/test.go
> Do not set empty volume directory

- pkg/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
- pkg/admission/customresourcevalidation/scheduler/OWNERS
- pkg/admission/customresourcevalidation/scheduler/validate_scheduler.go
Add scheduler CRD validation.
/cc @sjenning @mfojtik @enj
> Add scheduling CRD validation

- test/extended/prometheus/prometheus.go
The installer already pushes the pull secret to Secret `kube-system/coreos-pull-secret`. This allows installer to redact the pull-secret from the `cluster-config-v1` ConfigMap as ConfigMaps should not have secrets.
installer PR: https://github.com/openshift/installer/pull/1379
cluster-monitoring-operator PR: https://github.com/openshift/cluster-monitoring-operator/pull/286
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1686119
> test/extended/prom: use coreos-pull-secret for pullsecret

- test/e2e/upgrade/upgrade.go
During e2e runs one minute does not seem to be long enough to wait, and
upgrades will almost certainly take longer than 15m. Add some debugging
info for this error case.
> Display more debug info and wait longer for upgrade test

- images/node/system-container/config.json.template
This is cherry pick of #20221 to 3.10
https://bugzilla.redhat.com/show_bug.cgi?id=1686336
cc @wongma7 @sdodson
> Bindmount /var/lib/iscsi rw for iscsi attach

- vendor/k8s.io/kubernetes/pkg/apis/core/helper/qos/qos.go
- vendor/k8s.io/kubernetes/pkg/apis/core/v1/helper/qos/qos.go
- vendor/k8s.io/kubernetes/pkg/apis/core/v1/helper/qos/qos_test.go
upstream issue
https://github.com/kubernetes/kubernetes/issues/75212
upstream PR
https://github.com/kubernetes/kubernetes/pull/75223
bz xref
https://bugzilla.redhat.com/show_bug.cgi?id=1687004
> UPSTREAM: 75223: kubelet: include init containers when determining pod QoS

- vendor/k8s.io/kubernetes/pkg/registry/rbac/validation/rule.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/authentication/serviceaccount/util.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/authentication/serviceaccount/util_test.go
Reduces total allocations about 5% in profiles, see https://github.com/kubernetes/kubernetes/pull/75264
> UPSTREAM: 75264: Optimize authorization service account check

- test/extended/deployments/deployments.go
- test/extended/deployments/util.go
- test/extended/scheme/install.go
- test/extended/scheme/scheme.go
- test/extended/util/manifest.go
- test/extended/util/manifest_test.go
> Cleanup fixture reading in extended tests

- pkg/oc/cli/startbuild/startbuild.go
- test/cmd/builds.sh
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1590743
> Bug  1590743 - Include all webhook types when listing all

- pkg/oc/cli/admin/release/info.go
Show in `--size` because we have lots of horizontal room and rebuilds
align base layers.
> Make it easier to see how old images are for freshness

- pkg/oc/lib/describe/describer.go
Backport openshift/origin#22165 for 3.11
> Fix bug 1278683 for 3.11

- pkg/image/apiserver/admission/apis/imagepolicy/v1/default-policy.yaml
- pkg/image/apiserver/admission/apis/imagepolicy/v1/defaults.go
- pkg/image/apiserver/admission/imagepolicy/imagepolicy.go
- pkg/image/apiserver/admission/imagepolicy/imagepolicy_test.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1679602
/cc @bparees 
/cc @adambkaplan 
/cc @deads2k
> imagepolicy: remove legacy oapi

- pkg/util/labelselector/labelselector.go
- pkg/util/labelselector/labelselector_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1683819.
Fixes https://github.com/openshift/origin/issues/21972
> Bug 1683819 - allow empty selector

- publishing-kube-rules.yaml
> add 1.13.4 sync rules

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/controller.go
We used to merge and marshal OpenAPI spec triggered by informer events, one event at a time. This leads to a burst of OpenAPI updates when starting up.
This PR only addresses the CRD side. We have the same problem for APIServices. But there the code is much more involved. Upstream I have a half-finished PR fixing the complicated logic.
Upstream PR: https://github.com/kubernetes/kubernetes/pull/75399
> UPSTREAM: 75399: apiextensions: merge OpenAPI specs once after cache sync

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/healthz.go
It reports readiness if the process is healthy and it is not terminating.
> apiserver: add /readyz endpoint

- test/e2e/upgrade/upgrade.go
- vendor/k8s.io/kubernetes/test/e2e/framework/networking_utils.go
Small things that make debugging easier.
> Improve error output in upgrades

- pkg/network/node/networkpolicy.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1689678
/cc @deads2k
> network: fix conversion when handling network policy delete

- pkg/cmd/openshift-controller-manager/controller/interfaces.go
> remove internal clients from controller-manager

- test/extended/builds/pipeline_origin_bld.go
/assign @adambkaplan  
(our newly minted owner :-) )
> add some more dump of jenkins pod logs on e2e test failures

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/clientca.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/serving.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/single_certkey_pair.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/util.go
This PR will print out details about certificate that was dynamically reloaded. It should help debug wedged openshift api server.
> UPSTREAM: 00000: debug wedged openshift api cert reload

- cmd/sdn-cni-plugin/OWNERS
With SDN team members as review/approve.
@knobunc @smarterclayton @pweil-
> cmd/sdn-cni-plugin: add OWNERS file

- vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go
- vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager_test.go
- vendor/k8s.io/kubernetes/pkg/kubelet/eviction/types.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go
- vendor/k8s.io/kubernetes/pkg/kubelet/runonce_test.go
Supplemental fix to upstream https://github.com/kubernetes/kubernetes/pull/74222
> UPSTREAM: 75144: kubelet: updated logic of verifying a static critical pod

- pkg/oc/cli/admin/release/new.go
When generating the tar layer, ensure the timestamps of content is 
predictable based on the input in order to guarantee two users generating a
payload from the same inputs will get an identical tar
(within the bounds of golang's tar/gzip implementations).
Remove some old code around reading payloads from disk that can't be used
now that we have to replace versions from the originals.
> Make the release image vary only by inputs

- pkg/apps/strategy/support/lifecycle.go
`NewResyncableFIFO` is a carry on kubernetes in a difficult to read area.  We developed new watch tools and we should use this. This updates us to use the watchtools and eliminates a carry.
> stop using a carry on FIFO queue to observe pods

- hack/cherry-pick.sh
Glide.yaml is the authorative source for the intended revisions. If it references a branch, it is usually our fork branch which includes carry patches applied by the publishing bot. This is a better base for cherry-picking than the last rebase revision from `glide.lock` or `Godeps.json`.
> hack/cherry-pick.sh: switch to glide.yaml

- test/extended/operators/operators.go
All operators must report an operator version that matches the cluster
release version for the cluster to pass.
> e2e: Add conformance test to verify cluster operators have versions

- pkg/oc/cli/cancelbuild/cancelbuild.go
- pkg/oc/cli/rollback/rollback.go
- pkg/oc/cli/rollout/cancel.go
- pkg/oc/cli/rollout/latest.go
- pkg/oc/cli/rollout/retry.go
- pkg/oc/cli/set/env.go
- pkg/oc/cli/set/volume.go
- pkg/oc/cli/set/volume_test.go
These are external objects that do not need the conversion check.
> oc: remove unnecessary conversion

- pkg/build/controller/strategy/custom.go
- pkg/build/controller/strategy/custom_test.go
- pkg/build/controller/strategy/docker.go
- pkg/build/controller/strategy/docker_test.go
- pkg/build/controller/strategy/sti.go
- pkg/build/controller/strategy/sti_test.go
- pkg/build/util/consts.go
- pkg/build/util/util_test.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/test-build-app/utf8_tést_app.rb
* Set default LANG env var in builds for bsdtar.
* Add support for the builder's LANG env var to be overridden.
> Bug 1673806: build - support UTF-8 filenames in binary builds

- vendor/k8s.io/kubernetes/test/e2e/scheduling/preemption.go
https://github.com/kubernetes/kubernetes/pull/75335
> UPSTREAM: 75335: test/e2e: fix PreemptionExecutionPath nodeSelector

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/authentication.go
This might fix the openshift-apiserver cert rotation issues.
> UPSTREAM: 00000: fix closure error when calling cert rotation Run func

- glide.lock
- glide.yaml
- vendor/github.com/containers/image/openshift/openshift.go
- vendor/github.com/docker/docker/pkg/archive/archive_unix.go
- vendor/github.com/docker/docker/pkg/archive/changes_linux.go
- vendor/github.com/docker/docker/pkg/signal/signal_linux.go
- vendor/github.com/docker/docker/pkg/system/mknod.go
- vendor/github.com/docker/docker/vendor.conf
- vendor/github.com/google/cadvisor/metrics/prometheus.go
- vendor/github.com/openshift/imagebuilder/dockerclient/client.go
- vendor/github.com/vmware/photon-controller-go-sdk/photon/client.go
- vendor/github.com/vmware/photon-controller-go-sdk/photon/deployments_test.go
- vendor/github.com/vmware/photon-controller-go-sdk/photon/lightwave/oidcclient_test.go
https://github.com/openshift/google-cadvisor/pull/4
`make update-deps` came in with some other changes too :disappointed:
google#2004
xref https://bugzilla.redhat.com/show_bug.cgi?id=1691023
@soltysh @deads2k @sttts @derekwaynecarr
> bump(*): pick cadvisor fix

- vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/types.go
Upstream is kubernetes/kubernetes#75602
> Bug 1691857: Use protobuf from kubelet to retrieve resources, not just send them

- vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
- vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-role-bindings.yaml
- vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml
Move /readyz into system:openshift:public-info-viewer.
> UPSTREAM: <carry>: bootstrap-policy: add /readyz system:openshift:public-info-viewer policy

- test/extended/router/metrics.go
Partial fix for flake: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22058/pull-ci-openshift-origin-master-e2e-aws/4200#openshift-tests-conformanceareanetworkingfeaturerouter-the-haproxy-router-should-enable-openshift-monitoring-to-pull-metrics-suiteopenshiftconformanceparallelminimal
cluster-ingress-operator pr: https://github.com/openshift/cluster-ingress-operator/pull/123
> Retry when checking prometheus working target for router-internal-default job

- pkg/build/controller/build/build_controller.go
- pkg/build/controller/build/build_controller_test.go
Add new reason to indicate a build fails because its pod was evicted.
/cc @bparees
> Bug 1689061: Report build failures due to eviction

- test/extended/operators/images.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1692384
> operators: pull release image with pull secret from cluster

- pkg/oc/util/project/whoami.go
> Check NewForConfig err in WhoAmI

- test/extended/testdata/bindata.go
- test/extended/testdata/deployments/deployment-trigger.yaml
busybox has weird sleep not supporting infinity
/cc @mfojtik
> [3.11] Fix dc tests

- test/extended/testdata/bindata.go
- test/extended/testdata/builds/test-build-app/utf8_tést_app.rb
Non-ascii characters break tito.
/assign @sosiouxme
> Removing utf-8 file in extended build test

- pkg/cmd/openshift-kube-apiserver/kubeadmission/register.go
@openshift/sig-auth @openshift/sig-master 
/assign @derekwaynecarr
> Temporarily disable RBR until we move it to a CRD

- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1689000
> UPSTREAM: <drop>: comment out componentconfig registration for kube controller manager

- glide.lock
- pkg/build/controller/build/build_controller.go
- pkg/build/controller/build/build_controller_test.go
- vendor/github.com/google/btree/go.mod
- vendor/github.com/openshift/api/build/v1/consts.go
- vendor/github.com/vmware/photon-controller-go-sdk/photon/client.go
- vendor/github.com/vmware/photon-controller-go-sdk/photon/deployments_test.go
- vendor/github.com/vmware/photon-controller-go-sdk/photon/lightwave/oidcclient_test.go
Add new reason to indicate a build fails because its pod was evicted.
/cc @bparees 
/cc @sjenning
> [3.11] Bug 1690066: Report build failures due to eviction

- pkg/oc/cli/admin/diagnostics/cluster.go
- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/aggregated_logging/cronjobs.go
- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/aggregated_logging/cronjobs_test.go
- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/aggregated_logging/deploymentconfigs.go
- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/aggregated_logging/diagnostic.go
- pkg/oc/cli/admin/diagnostics/diagnostics/cluster/aggregated_logging/interfaces.go
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1676720 which fixes by:
checking for a curator cronjob instead of DC
> bug 1676720. Fix diagnostics check for logging curator

- test/extended/util/test.go
https://bugzilla.redhat.com/show_bug.cgi?id=1695278
> e2e: disable broken hostAlias test

- test/extended/deployments/util.go
/cc @mfojtik 
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1694172
> Check for closed watches in deployerPodInvariantChecker

- publishing-kube-rules.yaml
> add rules for publishing 1.14.0

- test/e2e/upgrade/upgrade.go
Don't show status that isn't important (i.e. avaliable=true, progressing=false, failing=false).
> Improve output of upgrade command for versions and important changes

- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_test.go
This should fix one of the flakes in the CI.
/assign @ingvagabund @jsafrane
> UPSTREAM: 76142:  Fix TestCreateDisk by sorting tags

- vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/logs/logs.go
- vendor/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go
Backport of: https://github.com/giuseppe/kubernetes/tree/fix-logs
> UPSTREAM: 73041: fix some race conditions in logs -f

- pkg/oc/cli/admin/release/extract_tools.go
Reduce CPU use with buffering, lower gzip level, and smaller search buffer
```
before:       18.08 real        15.78 user         2.25 sys
after:         6.85 real         4.87 user         0.26 sys
```
> Improve performance of extract --tools

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/plugin/BUILD
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/plugin/plugin.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/plugin/plugin_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1695225.
> Add missing kubectl plugin patches

- pkg/apps/apiserver/registry/deploylog/rest.go
- pkg/apps/apiserver/registry/deploylog/wait.go
- pkg/apps/apiserver/registry/deploylog/wait_test.go
- pkg/apps/strategy/support/acceptor.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1618685
/assign
/cc
> Handle watch restarts in deployers

- pkg/oc/originpolymorphichelpers/attachablepodforobject.go
- pkg/oc/originpolymorphichelpers/canbeautoscaled.go
- pkg/oc/originpolymorphichelpers/canbeexposed.go
- pkg/oc/originpolymorphichelpers/historyviewer.go
- pkg/oc/originpolymorphichelpers/logsforobject.go
- pkg/oc/originpolymorphichelpers/mapbasedselectorforobject.go
- pkg/oc/originpolymorphichelpers/portsforobject.go
- pkg/oc/originpolymorphichelpers/protocolsforobject.go
- pkg/oc/originpolymorphichelpers/rollbacker.go
- pkg/oc/originpolymorphichelpers/statusviewer.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1695216
> Cleanup origin polymorphichelpers from internal types

- hack/local-up-master/kube-apiserver-manifests/01_cluster_resource_quota_crd.yaml
Taken from https://github.com/openshift/cluster-config-operator/pull/33
> hack: update cluster resource quota fixture used in tests

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/serving.go
Serve using IPs listed in SNI configuration even though clients don't send it.
> UPSTREAM: <carry>: support SNI with IPs

- test/extended/util/test.go
- vendor/k8s.io/kubernetes/test/e2e/scheduling/priorities.go
Re-enabling scheduler serial tests with some picks from upstream. Will fix them, if they don't pass.
/cc @deads2k @sjenning
> Re-enable scheduler serial tests

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/create/create_secret.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1693054
> UPSTREAM: 76021: Fix create secret generic paths examples

- vendor/k8s.io/kubernetes/plugin/pkg/admission/podtolerationrestriction/admission.go
- vendor/k8s.io/kubernetes/plugin/pkg/admission/podtolerationrestriction/admission_test.go
Upstream fixes for podtolerationsrestrictions plugin
/cc @sjenning
> UPSTREAM: 75985:  Fix besteffort pods for conflicting tolerations

- pkg/oc/cli/rsync/rsync.go
https://bugzilla.redhat.com/show_bug.cgi?id=1699048
> oc rsync: fix tar strategy

- pkg/cmd/openshift-integrated-oauth-server/server.go
- test/extended/include.go
- test/extended/oauth/http1.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/secure_serving.go
@openshift/sig-auth @deads2k @smarterclayton @ironcladlou @Miciah @jupierce
> Bug 1686476: Force http1.1 in OAuth server

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/waitgroup.go
Make existing carry to match https://github.com/kubernetes/kubernetes/pull/75368
We need this as the `http.Error()` overrides the Content-Type header so we return structured error but  use plain text instead of JSON.
> UPSTREAM: 75368: replace http.Error that override content type headers

- vendor/k8s.io/kubernetes/pkg/volume/azure_dd/attacher.go
- vendor/k8s.io/kubernetes/pkg/volume/azure_dd/azure_common.go
- vendor/k8s.io/kubernetes/pkg/volume/azure_dd/azure_common_test.go
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1696901
Upstream PR: https://github.com/kubernetes/kubernetes/pull/70002
/sig storage
> UPSTREAM: 70002: Fix Azure disk attachment error on Linux

- images/cli/Dockerfile.rhel
- images/hyperkube/Dockerfile.rhel
- images/hypershift/Dockerfile.rhel
- images/sdn/Dockerfile.rhel
- images/template-service-broker/Dockerfile.rhel
- images/tests/Dockerfile.rhel
Same as https://github.com/openshift/origin/pull/22410
@sdodson
> Support Mulit-Arch Builds

- test/extended/prometheus/prometheus.go
/cc @brancz @sttts @paulfantom
> test/extended/prometheus: temporarily disable scheduler metrics checks

- vendor/k8s.io/kubernetes/pkg/kubectl/util/templates/templates.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1556963
> UPSTREAM: 74682: Fix flag template when both visible and explicit flags are specified

- test/extended/machines/workers.go
`e2e-aws-operator` suite for machine API is aggressively being hit by a networking issue when scaling machines, some new nodes do not go ready - https://bugzilla.redhat.com/show_bug.cgi?id=1698624 
This ensure we fail earlier if a regression might be introduced
> Add check for node readiness when recovering workers

- pkg/image/registryclient/dockercredentials/credentials.go
The docker daemon behavior (inherited from kubelet code) is not
consistent with docker client behavior. Instead, clients should only
search the home dir.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1696366
@sttts this fixes your issue
> Local registry config should only search home dir, not working dir

- test/extended/prometheus/prometheus.go
To ensure we don't regress on https://bugzilla.redhat.com/show_bug.cgi?id=1694766 again.
@s-urbaniak @squat @paulfantom @mxinden @metalmatze 
> test/extended/prometheus: Add test for host cAdvisor metrics

- vendor/k8s.io/kubernetes/test/e2e/scheduling/preemption.go
~~The theory I have currently is based on race conditions that could happen when the node gets created and the usage of node objects within the test. I am trying to compute the exact usage depending on the pods before creating pods with other priority classes, so that we won't see resource crunch on the node while creating new pods.~~
EDIT: https://github.com/openshift/origin/pull/22584#issuecomment-483818273
>  UPSTREAM: 76663: Fix preemption race conditions on heavy utilized nodes in e2e tests

- test/extended/builds/image_source.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/test-imagesource-buildconfig.yaml
Verify that we're copying symlinks correctly
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1694859
See openshift/builder#59
> Bug 1694859: verify image source symlinks

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/plugin/BUILD
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/plugin/plugin.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1695225
> UPSTREAM: 76707: Warn to stderr when we encounter PathError listing plugins

- vendor/k8s.io/kubernetes/pkg/kubectl/describe/versioned/describe.go
- vendor/k8s.io/kubernetes/pkg/kubectl/describe/versioned/describe_test.go
- vendor/k8s.io/kubernetes/pkg/kubectl/util/templates/markdown.go
- vendor/k8s.io/kubernetes/pkg/kubectl/util/templates/normalizers.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1656328
> Bug 1656328 - Fix smartLabelFor to properly handle annotations and labels containing .io

- pkg/monitor/event.go
Establishing the watch doesn't always report the error right away.
Upgrade tests spewed:
```
Apr 10 16:20:26.538 I kube-apiserver received an error while watching events: The resourceVersion for the provided watch is too old.
Apr 10 16:20:26.638 I kube-apiserver received an error while watching events: The resourceVersion for the provided watch is too old.
Apr 10 16:20:26.738 I kube-apiserver received an error while watching events: The resourceVersion for the provided watch is too old.
```
endlessly.
> When watch event returns a "too old" error, we must exit

- pkg/oc/cli/cancelbuild/OWNERS
- pkg/oc/cli/newapp/OWNERS
- pkg/oc/cli/newbuild/OWNERS
- pkg/oc/cli/startbuild/OWNERS
> Add OWNERS for DevEx build CLI

- vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_image.go
https://github.com/kubernetes/kubernetes/pull/75367
> UPSTREAM: 75367: Fix panic when removing docker images

- vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_image.go
https://github.com/kubernetes/kubernetes/pull/75367
master PR: https://github.com/openshift/origin/pull/22630
> [3.11] UPSTREAM: 75367: Fix panic when removing docker images

- pkg/admission/customresourcevalidation/authentication/validate_authentication.go
- pkg/admission/customresourcevalidation/authentication/validate_authentication_test.go
- pkg/admission/customresourcevalidation/helpers.go
> Add Authentication CR validation

- test/extended/cli/mustgather.go
Implement changes request at https://github.com/openshift/origin/pull/22594#pullrequestreview-228397430
> implement code review suggestions

- examples/OWNERS
- examples/db-templates/OWNERS
- examples/hello-openshift/OWNERS
- examples/image-streams/OWNERS
- examples/jenkins/OWNERS
- examples/quickstarts/OWNERS
- examples/sample-app/OWNERS
- images/builder/OWNERS
- pkg/build/OWNERS
- pkg/image/OWNERS
- pkg/oc/cli/admin/prune/imageprune/OWNERS
- pkg/oc/clusteradd/components/default-imagestreams/OWNERS
- pkg/oc/clusteradd/components/registry/OWNERS
- pkg/oc/clusteradd/components/sample-templates/OWNERS
- pkg/oc/lib/newapp/OWNERS
- pkg/template/OWNERS
- test/templates/OWNERS
- tools/buildanalyzer/OWNERS
> [3.11] Update DevEx OWNERS

- vendor/k8s.io/kubernetes/test/e2e/apps/statefulset.go
- vendor/k8s.io/kubernetes/test/e2e/framework/BUILD
- vendor/k8s.io/kubernetes/test/e2e/framework/pv_util.go
- vendor/k8s.io/kubernetes/test/e2e/storage/pvc_protection.go
- vendor/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go
- vendor/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1700076
> UPSTREAM: 76625: Skip tests that depend on default SC

- pkg/oc/cli/newapp/newapp.go
> BUG 1671528: QE induced tweaks to recent new-app CRD error message

- pkg/oc/cli/admin/mustgather/mustgather.go
Use the `/usr/bin/gather` to run `must-gather`.
> oc adm must-gather: use gather script

- test/extended/prometheus/prometheus.go
> test/extended/prometheus: reenable control plane tests

- pkg/printers/OWNERS
> Add soltysh to pkg/printer owners

- vendor/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume_util.go
- vendor/k8s.io/kubernetes/test/e2e/storage/vsphere/vsphere_volume_disksize.go
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1699820
> UPSTREAM: 76719: vsphere: correctly handle PV size

- hack/lib/constants.sh
- pkg/version/version.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1702449
> Set gitTreeState, golang version, compiler and platform variables in version command

- vendor/k8s.io/kubernetes/pkg/controller/cronjob/utils.go
- vendor/k8s.io/kubernetes/pkg/controller/cronjob/utils_test.go
> UPSTREAM: 75772: Avoid panic in cronjob sorting

- pkg/oc/cli/admin/release/mirror.go
- pkg/oc/cli/image/mirror/mappings.go
- pkg/oc/cli/image/mirror/mirror.go
- pkg/oc/cli/image/mirror/s3.go
Allows us to publish to a pure content hosting location.
> Fix two issues with s3 mirroring and extend to release images

- test/extended/builds/new_app.go
https://bugzilla.redhat.com/show_bug.cgi?id=1702743
> Disable tests while flake is investigated

- images/cli-artifacts/Dockerfile.rhel
- images/cli/Dockerfile.rhel
- images/hyperkube/Dockerfile.rhel
- images/hypershift/Dockerfile.rhel
- images/sdn/Dockerfile.rhel
- images/template-service-broker/Dockerfile.rhel
- images/tests/Dockerfile.rhel
Fixes regression in CI performance (replacement is by URL and the
ci-operator file changed).
> Correct Dockerfile FROM statements

- pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_authenticator.go
Regardless of external configuration, OAuth tokens should always work.
This prevents issues where multiple masters exist but only some will honor OAuth tokens due to differences in configuration.
Bug 1694878
> Bug 1694878: Always honor OAuth tokens

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp/cp.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1572149
> UPSTREAM: 77010: Check error when copying from pod

- pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
> keep re-creating SCC

- pkg/cmd/openshift-kube-apiserver/server.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/patch_always_local_delegate.go
APIServices in https://github.com/openshift/cluster-config-operator/pull/51 are fighting.
>  don't fight with CRDs for SCC and RBR

- test/integration/dockerregistryclient_test.go
/assign @deads2k @derekwaynecarr
> Use openshift controller image from dockerhub in integration

- pkg/oc/cli/idle/idle.go
If network policies are in place, idling services may cause connections
before the service is up to bypass the network policy entirely
Signed-off-by: Ricardo Carrillo Cruz <ricardo.carrillo.cruz@gmail.com>
> Warn user when idling services if network policies are in place

- vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/BUILD
- vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go
- vendor/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher_test.go
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1695329
> UPSTREAM: 75110: Send events before adding watchers in traversePluginDir

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp/BUILD
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp/cp.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp/cp_test.go
> UPSTREAM: 76788: Clean links handling in cp's tar code

- test/integration/buildpod_admission_test.go
Let build pods have additional tolerations in integration test.
These may come from enabled admission plugins.
> Allow extra tolerations in buildpod admission test

- vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
> UPSTREAM: 76184: Use pvc uid in endpoint/service label

- pkg/network/node/cniserver/cniserver.go
- pkg/network/node/cniserver/cniserver_test.go
SDN pods always log the errors:
E0418 15:36:07.273730    2304 cniserver.go:149] failed to remove old pod info socket: remove /var/run/openshift-sdn: device or resource busy
E0418 15:36:07.273814    2304 cniserver.go:152] failed to remove contents of socket directory: remove /var/run/openshift-sdn: device or resource busy
at startup. This is because they're trying to delete the existing cniserver directory, but it's actually a mountpoint.
The reason it wants to delete and recreate the directory is because the CNIServer socket needs to be in a mode 0700 directory or else it's not secure. But `/var/run/openshift-sdn` currently ends up being mode 0755, meaning non-root users would have access to the socket and could spoof openshift-sdn into doing certain things on their behalf.
We can't …
> Fix up SDN CNIServer startup security logic

- hack/import-restrictions.json
- pkg/admission/customresourcevalidation/oauth/helpers.go
- pkg/admission/customresourcevalidation/oauth/validate_github.go
- pkg/admission/customresourcevalidation/oauth/validate_github_test.go
- pkg/admission/customresourcevalidation/oauth/validate_gitlab.go
- pkg/admission/customresourcevalidation/oauth/validate_gitlab_test.go
- pkg/admission/customresourcevalidation/oauth/validate_google.go
- pkg/admission/customresourcevalidation/oauth/validate_google_test.go
- pkg/admission/customresourcevalidation/oauth/validate_idp.go
- pkg/admission/customresourcevalidation/oauth/validate_idp_test.go
- pkg/admission/customresourcevalidation/oauth/validate_keystone.go
- pkg/admission/customresourcevalidation/oauth/validate_keystone_test.go
- pkg/admission/customresourcevalidation/oauth/validate_ldap.go
- pkg/admission/customresourcevalidation/oauth/validate_ldap_test.go
- pkg/admission/customresourcevalidation/oauth/validate_oauth.go
- pkg/admission/customresourcevalidation/oauth/validate_openid.go
- pkg/admission/customresourcevalidation/oauth/validate_openid_test.go
- pkg/admission/customresourcevalidation/oauth/validate_requestheader.go
- pkg/admission/customresourcevalidation/oauth/validate_requestheader_test.go
This PR adds some basic static validation for the Authentication and OAuth CRs.
/cc @openshift/sig-auth
> Add validation for Authentication and OAuth CRs

- pkg/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
- pkg/admission/customresourcevalidation/securitycontextconstraints/validate_scc.go
- pkg/admission/customresourcevalidation/securitycontextconstraints/validation/validation.go
- pkg/admission/customresourcevalidation/securitycontextconstraints/validation/validation_test.go
@deads2k there's [this](https://github.com/openshift/origin/pull/22745), also. 
@enj rebase yours
merge whichever
> add SCC validation plugin

- vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
Bug# https://bugzilla.redhat.com/show_bug.cgi?id=1618465
Signed-off-by: hchiramm <hchiramm@redhat.com>
> UPSTREAM: 76983: Shuffle addresslist for random mount server and cleanup error messages

- pkg/oc/cli/debug/debug.go
The point of debug is to give you enough of a lift that you can
debug a running / stopped workload controller.
> Add CronJobs and StatefulSet to debug for workload controllers

- cmd/openshift-tests/openshift-tests.go
why would you ever turn this off....
that easy?
> always dump logs

- vendor/k8s.io/kubernetes/test/e2e/apimachinery/namespace.go
Partial fix of https://bugzilla.redhat.com/show_bug.cgi?id=1703875
The initializer portion of this e2e test `Namespaces [Serial] should ensure that all pods are removed when a namespace is deleted [Conformance] [Suite:openshift/conformance/serial/minimal] [Suite:k8s]` is flaking heavily. It assumes an uninitialized pod is created then deleted quickly within 1m30s. But initializers are not enabled, so the pod starts and may take longer than 1m30s to delete.
This is a partial cherry-pick of https://github.com/kubernetes/kubernetes/pull/72972/files#diff-35baea3ee2d40a29c405b9114bde6c84
> UPSTREAM: <drop>: Remove use of alpha initializers

- hack/local-up-master/lib.sh
cc @sallyom @openshift/sig-auth
> test-cmd: don't hang in bash if SCCs fail to appear

- test/extended/prometheus/prometheus.go
Adding e2e tests to make sure that the sdn metrics are exposed to prometheus correctly
> adding e2e tests to ensure sdn metrics 

- pkg/cmd/openshift-kube-apiserver/kubeadmission/register.go
Now that it is crd based, there is no reason for special cases
> Run RBR on all namespaces

- origin.spec
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1702769
> origin.spec: replace 3.x client RPMs

- test/extended/operators/tolerations.go
@ravisantoshgudimetla @derekwaynecarr @RobertKrawitz 
xref https://bugzilla.redhat.com/show_bug.cgi?id=1705649
> Bug: 1705649: test: extended: add check for pod tolerations

- pkg/oc/cli/admin/mustgather/mustgather.go
`oc adm must-gather` spends minutes waiting for the remote command to complete. This PR logs the output of the remote command in the meantime.
> oc adm must-gather: provide better feedback

- pkg/oc/cli/cli.go
- pkg/oc/cli/kubectlwrappers/wrappers.go
- test/cmd/deployments.sh
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1707205 and removes outdated wrappers where we can.
> Bug 1707205: Get rid of oc wrappers where we can

- test/extended/builds/s2i_incremental.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/incremental-auth-build.json
Update the s2i_incremental.go test to more accurately represent
how a real s2i incremental build is done.
Coinsides with / depends on https://github.com/openshift/builder/pull/70
> Bug 1704767: Update tests for S2I incremental builds

- publishing-kube-rules.yaml
> Update publishing rules for origin 4.2 and k8s 1.14

- test/integration/dockerregistryclient_test.go
This reverts commit 8bfec95f521cf71e009ddd83f8c8c52a0ff91c14.
> Revert "disable broken test"

- test/e2e/upgrade/upgrade.go
As discussed, this takes care of waiting for all the MCPs to be updated before confirming the upgrade went through.
Signed-off-by: Antonio Murdaca <runcom@linux.com>
> test/e2e/upgrade: wait until all pools have upgraded

- pkg/cmd/openshift-apiserver/server.go
@deads2k I've added reflector and workqueue metrics, not sure if this is what you wanted?
> Add reflector and workqueue metrics

- pkg/oc/cli/admin/prune/imageprune/helper_test.go
https://github.com/golang/go/issues/23689 changed how http servers
in golang respond.
> PrunerPing unit fails because of golang 1.12 HTTPS server change

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/grpc_service_unix_test.go
The tests need to be rewritten to be safe for concurrent use and for
work in contended environments. Disabling the worst offenders and fixing
reuse issues around the tests here.
Tracking bug is https://bugzilla.redhat.com/show_bug.cgi?id=1711701
> UPSTREAM: 00000: gRPC tests for encryption envelope are flaky

- vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1711688
> UPSTREAM: 76193: Fix nfs multi-node PV test

- vendor/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go
Fixes the unit test
/sig storage
> UPSTREAM: 78132: Fix CSI attacher test

- vendor/k8s.io/kubernetes/pkg/volume/testing/testing.go
Fixes flake detailed in https://github.com/kubernetes/kubernetes/pull/78257
> UPSTREAM: 78257: Fix volume reconciler flake

- publishing-staging-rules.yaml
Steps to make this work:
1) Lets create `release-4.2` branch in template-service-broker
2) `git commit --allow-empty -m "Origin-commit: fc1f8f45e2ad57b1fcc0c02f04ff933a6997f7ac"`
3) `git push`
4) Merge this PR.
/cc @deads2k 
/cc @sttts
> add publishing rule file for staging

- hack/import-restrictions.json
- pkg/authorization/apis/authorization/helpers.go
- pkg/authorization/apis/authorization/internal/serviceaccount/doc.go
- pkg/authorization/apis/authorization/util.go
Trim helpers and move to point of use.
/assign @enj
> move authorization validation functions

- hack/verify-imports.sh
Prevent unintentional refs to k/k and to other staging repos
/assign @sttts
> get more strict on staging

- pkg/oc/cli/rsh/rsh.go
to reduce further false issue reports like #9602 and #18696
> Add example 'oc rsh' command

- pkg/admission/customresourcevalidation/oauth/validate_idp.go
- pkg/admission/customresourcevalidation/oauth/validate_idp_test.go
> Bug 1715020: oauth validation: don't allow multiple IdPs in single IdP object

- staging/src/github.com/openshift/oauth-server/OWNERS
- staging/src/github.com/openshift/oauth-server/README.md
- staging/src/github.com/openshift/openshift-controller-manager/OWNERS
- staging/src/github.com/openshift/openshift-controller-manager/README.md
- vendor/github.com/openshift/oauth-server
- vendor/github.com/openshift/openshift-controller-manager
This preps the directory with empty README.md and OWNERS files and create symlinks.
We need this to setup publishing to external repositories.
> staging: prepare openshift-controller-manager and oauth-server

- pkg/build/apiserver/registry/buildconfig/webhook.go
- pkg/build/apiserver/registry/buildconfig/webhook_test.go
- pkg/build/client/clients.go
- pkg/build/controller/build/build_controller.go
- pkg/build/controller/buildconfig/buildconfig_controller.go
- pkg/build/controller/buildconfig/buildconfig_controller_test.go
- pkg/build/controller/common/util.go
- pkg/build/controller/common/util_test.go
- pkg/build/controller/policy/parallel.go
- pkg/build/controller/policy/parallel_test.go
- pkg/build/controller/policy/policy.go
- pkg/build/controller/policy/policy_test.go
- pkg/build/controller/policy/serial.go
- pkg/build/controller/policy/serial_latest_only.go
- pkg/build/controller/policy/serial_latest_only_test.go
- pkg/build/controller/policy/serial_test.go
- pkg/cmd/openshift-controller-manager/controller/image.go
- pkg/image/controller/trigger/image_trigger_controller_test.go
- pkg/image/trigger/buildconfigs/buildconfigs.go
- pkg/image/trigger/buildconfigs/buildconfigs_test.go
- pkg/oc/cli/cancelbuild/cancelbuild.go
Use the real client instead. This is removing and replacing obvious cruft. I will work on listers in the next episode.
/cc @deads2k
> pkg/build/client: remove this cruft

- test/extended/testdata/bindata.go
- test/extended/testdata/deployments/custom-deployment.yaml
@tnozicka  I've compiled and tested on my localhost. Could you please help review ? thanks.
> deploy hook inherit the inexistent volume

- test/e2e/upgrade/monitor.go
- test/e2e/upgrade/upgrade.go
Because [this][1]:
```
Cluster did not complete upgrade: timed out waiting for the condition
```
is not as helpful [as][2]:
```
Cluster did not complete upgrade: timed out waiting for the condition: Working towards registry.svc.ci.openshift.org/ci-op-xqgf4kzn/release@sha256:21fadc31273b07ecbcf749ffc37bc87ed0e2f5ea1b442205d0370509ef44ec5e: downloading update
```
or similar.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1712581#c0
[2]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_console-operator/229/pull-ci-openshift-console-operator-master-e2e-aws-upgrade/100/artifacts/e2e-aws-upgrade/clusterversion.json
> Bug 1712581: test/e2e/upgrade: Summarize ClusterVersion on upgrade failures

- pkg/oc/cli/admin/release/info.go
Useful for scripting and automation.
* `-o digest`: outputs the digest, if set, of any images
* `-o pullspec`: outputs the pullspec of referenced images
* `-o name`: outputs the name of the tag of a referenced image
Used this to find all images to verify RPM db from
> Allow `oc adm release info` to output digest, name, or pull spec

- vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go
- vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-role-bindings.yaml
This reverts commit 50872400c21124bf825b4663ac720106f5aba351.
> Bug 1711533: UPSTREAM: revert: 00000: restore unprivileged access

- glide.lock
- vendor/github.com/openshift/library-go/pkg/apps/OWNERS
- vendor/github.com/openshift/library-go/pkg/apps/appsserialization/scheme.go
- vendor/github.com/openshift/library-go/pkg/apps/appsserialization/scheme_test.go
- vendor/github.com/openshift/library-go/pkg/apps/appsserialization/serialize.go
- vendor/github.com/openshift/library-go/pkg/apps/appsutil/const.go
- vendor/github.com/openshift/library-go/pkg/apps/appsutil/rc_scale_client.go
- vendor/github.com/openshift/library-go/pkg/apps/appsutil/util.go
- vendor/github.com/openshift/library-go/pkg/apps/appsutil/util_test.go
- vendor/github.com/openshift/library-go/pkg/authorization/scopemetadata/clusterrole_describers.go
- vendor/github.com/openshift/library-go/pkg/authorization/scopemetadata/describers.go
- vendor/github.com/openshift/library-go/pkg/authorization/scopemetadata/user_describers.go
- vendor/github.com/openshift/library-go/pkg/authorization/scopemetadata/validation.go
- vendor/github.com/openshift/library-go/pkg/authorization/scopemetadata/validation_test.go
- vendor/github.com/openshift/library-go/pkg/legacyapi/legacygroupification/groupification.go
> bring in library-go updates to break bad deps

- pkg/api/imagereferencemutators/meta.go
- pkg/api/imagereferencemutators/pods.go
- pkg/image/controller/trigger/image_trigger_controller_test.go
> Remove internal from imagereferencemutators

- test/extended/cluster/cl.go
Decouple Cluster Loader waiting for deployment configs from builds.
> Fix CL dc wait

- cmd/sdn-cni-plugin/OWNERS
> [3.11] cmd/sdn-cni-plugin: add OWNERS file

- test/extended/builds/multistage.go
@openshift/devexp-qe Could you help review this change?
> Add multi stage build with external image test, caseid OCP-22469

- vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1710168
/sig storage
> UPSTREAM: 78595: Add dangling volumes as uncertain

- staging/src/github.com/openshift/oc/pkg/helpers/legacy/apps.go
- staging/src/github.com/openshift/oc/pkg/helpers/legacy/authorization.go
- staging/src/github.com/openshift/oc/pkg/helpers/legacy/build.go
- staging/src/github.com/openshift/oc/pkg/helpers/legacy/doc.go
- staging/src/github.com/openshift/oc/pkg/helpers/legacy/image.go
- staging/src/github.com/openshift/oc/pkg/helpers/legacy/install.go
- staging/src/github.com/openshift/oc/pkg/helpers/legacy/network.go
- staging/src/github.com/openshift/oc/pkg/helpers/legacy/oauth.go
- staging/src/github.com/openshift/oc/pkg/helpers/legacy/project.go
- staging/src/github.com/openshift/oc/pkg/helpers/legacy/quota.go
- staging/src/github.com/openshift/oc/pkg/helpers/legacy/route.go
- staging/src/github.com/openshift/oc/pkg/helpers/legacy/security.go
- staging/src/github.com/openshift/oc/pkg/helpers/legacy/template.go
- staging/src/github.com/openshift/oc/pkg/helpers/legacy/user.go
Extracted from #22970 since it's needed for #23014.
/cc @deads2k @damemi
> Copy external legacy helpers to staging

- test/extended/builds/build_pruning.go
Here starting three builds are incorrect, modify to four.
> Modify cancel builds numbers

- test/extended/operators/qos.go
> tests/extended: remove openshift-monitoring from QoS check exclusion list

- test/extended/builds/dockerfile.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/docker-add/Dockerfile
Case: OCP-23721
@openshift/devexp-qe pls help to review it
/assign @coreydaley @adambkaplan 
Thanks all
> Bug 1694867:  text/extended/builds: Fix buildah in image build

- pkg/oc/cli/startbuild/startbuild.go
- pkg/oc/lib/describe/helpers.go
- staging/src/github.com/openshift/oc/pkg/helpers/build/webhooks.go
> Move build webhook to oc staging

- glide.lock
- vendor/github.com/openshift/api/build/v1/consts.go
- vendor/github.com/openshift/api/project/v1/types.go
- vendor/github.com/openshift/library-go/pkg/image/dockerv1client/conversion.go
- vendor/github.com/openshift/library-go/pkg/image/dockerv1client/types.go
- vendor/github.com/openshift/library-go/pkg/image/imageutil/helpers.go
- vendor/github.com/openshift/library-go/pkg/image/imageutil/helpers_test.go
- vendor/sigs.k8s.io/yaml/.travis.yml
- vendor/sigs.k8s.io/yaml/OWNERS
- vendor/sigs.k8s.io/yaml/go.mod
- vendor/sigs.k8s.io/yaml/go.sum
> Bump library-go and api deps

- hack/import-restrictions.json
- pkg/cmd/server/apis/config/stringsource.go
- pkg/oc/cli/admin/admin.go
- pkg/oc/cli/admin/cert/cert.go
- pkg/oc/cli/admin/cert/create_keypair.go
- pkg/oc/cli/admin/cert/create_mastercerts.go
- pkg/oc/cli/admin/cert/create_servercert.go
- pkg/oc/cli/admin/cert/create_signercert.go
- pkg/oc/cli/admin/cert/decrypt.go
- pkg/oc/cli/admin/cert/encrypt.go
- pkg/oc/cli/admin/cert/pem.go
- pkg/oc/cli/admin/createclient/create_client.go
- pkg/oc/cli/admin/createclient/create_clientcert.go
- pkg/oc/cli/admin/createkubeconfig/create_kubeconfig.go
- pkg/oc/lib/signercertoptions/default_certs.go
- pkg/oc/lib/signercertoptions/signer_cert_args.go
- test/integration/front_proxy_test.go
- test/integration/oauth_cert_fallback_test.go
- test/integration/oauth_ldap_test.go
- test/util/server/deprecated_openshift/start/master_args.go
- test/util/server/server.go
rebase of https://github.com/openshift/origin/pull/22995 in case it merges before he wakes up.
@damemi the commits are still yours
> Move cmd/server/admin to oc/cli/admin/server

- test/extended/authorization/rbac/OWNERS
- test/extended/authorization/rbac/groups_default_rules.go
> rbac: update e2e to handle namespace scoped policy

- hack/lib/constants.sh
- origin.spec
> Force golang 1.12

- hack/import-restrictions.json
- pkg/image/apis/image/helper.go
- pkg/oc/cli/importimage/importimage.go
- pkg/oc/cli/newapp/newapp.go
- pkg/oc/cli/process/process.go
- pkg/oc/cli/tag/tag.go
- pkg/oc/lib/describe/describer.go
- pkg/oc/lib/describe/describer_test.go
- pkg/oc/lib/describe/helpers.go
- pkg/oc/lib/describe/helpers_test.go
- pkg/oc/lib/describe/imports.go
- pkg/oc/lib/describe/projectstatus_test.go
- pkg/oc/lib/newapp/app/dockerimagelookup.go
- pkg/oc/lib/newapp/app/imagestreamlookup.go
- staging/src/github.com/openshift/oc/pkg/helpers/build/helpers.go
- staging/src/github.com/openshift/oc/pkg/helpers/graph/genericgraph/test/job.yaml
- staging/src/github.com/openshift/oc/pkg/helpers/graph/genericgraph/test/new-project-deployed-app.yaml
- staging/src/github.com/openshift/oc/pkg/helpers/image/constants.go
- staging/src/github.com/openshift/oc/pkg/helpers/image/helpers.go
- staging/src/github.com/openshift/oc/pkg/helpers/image/helpers_test.go
Replaces #22993, builds on top of #23018 so ignore first commit.
/cc @damemi
> Remove internal api usages from describer

- pkg/network/node/vxlan_monitor.go
In a case when a pod sends traffic using egressIP, and receives
no reply, we should no treat that as the node being offline. Thus
start sending ping probes upon our first suspicion that the
node might be offline, but actually dont report for the first time
as that would be confusing.
Also, anytime we encounter received packets reset the retries counter.
> Bug 1718542: Fix egress monitoring for some rare corner cases.

- pkg/network/node/vxlan_monitor.go
"Forward port" of @rkojedzinszky 's #23069 to master. (No changes were needed.)
> Bug 1717639: Fix egress monitoring for some rare corner cases.

- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/mutation_detector.go
> UPSTREAM: 78869: cache mutation detector: use correct diff function

- test/extended/operators/clusteroperators.go
https://github.com/openshift/cluster-dns-operator/pull/118
https://github.com/openshift/cluster-ingress-operator/pull/249
> Bug 1717734, 1717737: tests: enable dns/ingress clusteroperator cases

- pkg/apps/apis/apps/internaltest/ok.go
- pkg/apps/apiserver/apiserver.go
- pkg/apps/apiserver/registry/instantiate/rest.go
- pkg/apps/apiserver/registry/instantiate/rest_test.go
- pkg/image/apiserver/admission/imagepolicy/imagepolicy.go
- pkg/image/apiserver/admission/imagepolicy/imagepolicy_test.go
- pkg/image/apiserver/admission/imagepolicy/rules/accept_test.go
- pkg/image/apiserver/admission/imagepolicy/rules/rules.go
- pkg/image/apiserver/apiserver.go
- pkg/image/apiserver/registry/imagesignature/rest.go
- pkg/image/apiserver/registry/imagesignature/strategy_test.go
Switch the apiserver over to external clients.
> remove internal image clients from apiserver

- hack/import-restrictions.json
- pkg/oc/cli/admin/prune/auth/bindings.go
- pkg/oc/cli/admin/prune/auth/cluster_role_test.go
Removed dependencies on:
- `github.com/openshift/origin/pkg/authorization/apis/authorization`
- `github.com/openshift/origin/pkg/authorization/apis/authorization/install`
> remove oc dependency on pkg/authorization/apis/authorization

- OWNERS
> Add sttts and soltysh as top level approvers

- test/extended/util/test.go
> UPSTREAM: 0000: Re-enable preemption tests

- publishing-staging-rules.yaml
I think this is what you need.
> publishing rule for sdn

- hack/local-up-master/lib.sh
- pkg/authorization/apiserver/admission/restrictusers/restrictusers.go
- pkg/authorization/apiserver/admission/restrictusers/restrictusers_test.go
- pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
- pkg/cmd/server/admission/init.go
- pkg/cmd/server/admission/types.go
- test/extended/authorization/rolebinding_restrictions.go
- test/extended/include.go
- test/integration/restrictusers_test.go
- test/util/server/server.go
Bug 1706637
1) use RBRInformer rather than getter for admission, to cache rbrs/improve performance
2) add extended tests for RBRs
@enj please review
> switch to RoleBindingRestrictionInformer for restrictusers admission

- test/extended/authorization/rbac/groups_default_rules.go
- test/extended/builds/dockerfile.go
- test/extended/builds/s2i_quota.go
- test/extended/builds/start.go
- test/extended/cluster/cl.go
- test/extended/deployments/deployments.go
- test/extended/deployments/util.go
- test/extended/idling/idling.go
- test/extended/imageapis/limitrange_admission.go
- test/extended/images/append.go
- test/extended/images/hardprune.go
- test/extended/images/prune.go
- test/extended/oauth/well_known.go
- test/extended/router/scoped.go
- test/extended/templates/helpers.go
- test/extended/templates/templateinstance_cross_namespace.go
- test/extended/templates/templateinstance_impersonation.go
- test/extended/templates/templateinstance_security.go
- test/extended/templates/templateservicebroker_bind.go
- test/extended/templates/templateservicebroker_e2e.go
- test/extended/templates/templateservicebroker_security.go
- test/extended/util/auth_rule_resolver.go
- test/extended/util/cli.go
- test/extended/util/framework.go
Following @damemi changes and trying to plumb the template instance...
x-ref: https://github.com/openshift/origin/pull/23127
> tests: sweep extended tests for referenced to origin

- hack/OWNERS
So I can properly own my mistakes -.-
> Add enj to hack OWNERS

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/drain.go
- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/drain_test.go
https://bugzilla.redhat.com/show_bug.cgi?id=1628693
Upstream PR link: kubernetes/kubernetes#68767
@ravisantoshgudimetla @derekwaynecarr
> UPSTREAM: 68767: Fix drain for evicting terminal DS pods and pods with local storage

- test/extended/builds/cluster_config.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/build-cluster-config.yaml
- test/extended/testdata/builds/cluster-config/invalid-build-cluster-config.yaml
- test/extended/testdata/builds/test-build.yaml
@openshift/devexp-qe  Added cases:OCP-22137, OCP-22136 to e2e test, please help to review it
@coreydaley @adambkaplan please help to check it too, thanks all.
> test/extended/builds: Apply default proxy configuration to build pod

- HACKING.md
- README.md
- Vagrantfile
- docs/builds.md
- docs/debugging-openshift.md
- docs/images.md
- examples/sample-app/README.md
- examples/sample-app/cleanup.sh
- examples/sample-app/container-setup.md
- examples/storage-examples/gluster-examples/nginx_gluster_host/README.md
- examples/storage-examples/gluster-examples/nginx_gluster_plugin/README.md
- examples/storage-examples/gluster-examples/nginx_gluster_pvc/README.md
- examples/storage-examples/gluster-examples/nginx_template/README.md
- examples/storage-examples/host-path-examples/README.md
- hack/dind-cluster.sh
- hack/env
- hack/lib/cleanup.sh
- pkg/build/apis/build/types.go
- staging/src/github.com/openshift/oc/pkg/cli/deployer/strategy/doc.go
- staging/src/github.com/openshift/oc/pkg/cli/rollout/rollout.go
- test/extended/testdata/bindata.go
- test/util/server/deprecated_openshift/apis/config/types.go
Docker container -> container
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>
> Change references from Docker to Container.

- OWNERS
3.11 version of https://github.com/openshift/origin/commit/de39268c0ba3a3e1169497290bcf43d9039ab2f2
@derekwaynecarr @deads2k @smarterclayton
> [3.11] add sjenning to top level approvers

- CONTRIBUTING.adoc
> Fix CONTRIBUTING.adoc

- pkg/cmd/openshift-kube-apiserver/admission/authorization/restrictusers/restrictusers.go
- test/extended/authorization/rolebinding_restrictions.go
- test/extended/include.go
- test/integration/restrictusers_test.go
- test/util/server/server.go
@enj  adding back test plus a few minor bits from [revert](https://github.com/openshift/origin/pull/23176)
> add RoleBindingRestriction e2e test

- vendor/k8s.io/kubernetes/pkg/util/iptables/iptables.go
- vendor/k8s.io/kubernetes/pkg/util/iptables/iptables_test.go
- vendor/k8s.io/kubernetes/pkg/util/iptables/save_restore.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1720677
> Bug 1720677: Fix panic in kube-proxy when iptables-save prints to stderr

- pkg/cmd/openshift-controller-manager/controller/image.go
- pkg/image/controller/signature/signature_import_controller.go
https://bugzilla.redhat.com/show_bug.cgi?id=1705984
> [3.11] Increase limit for signatures

- test/extended/prometheus/prometheus.go
This is needed to get https://github.com/openshift/cluster-kube-controller-manager-operator/pull/262 green
/cc @brancz @paulfantom
> extended/prometheus: temporarily disable scrape duplicate alert

- Makefile
- cmd/hypershift/main.go
- cmd/openshift-integrated-oauth-server/OWNERS
- hack/import-restrictions.json
- hack/lib/constants.sh
- hack/verify-imports.sh
- pkg/cmd/openshift-integrated-oauth-server/OWNERS
- staging/src/github.com/openshift/oauth-server/OWNERS
- staging/src/github.com/openshift/oauth-server/cmd/oauth-server/main.go
- staging/src/github.com/openshift/oauth-server/pkg/cmd/oauth-server/cmd.go
- staging/src/github.com/openshift/oauth-server/pkg/cmd/oauth-server/server.go
- staging/src/github.com/openshift/oauth-server/pkg/version/version.go
The oauth-server is ready for its own image.  After this, we need to get a separate image for it.
> move oauth-server fully to staging

- staging/src/github.com/openshift/sdn/pkg/network/node/healthcheck.go
OVS exiting usually indicates a restart of the OVS pod for upgrade
or other reasons, not a crash of OVS itself. It's misleading and
pointless to print out error messages that SDN can't talk to OVS
every 100ms while OVS is restarting. Suppress those messages and
leave the final "timed out waiting for condition" message to
indicate that the full ovsRecoveryTimeout (10s) has elapsed.
@squeed @danwinship @pecameron @JacobTanenbaum @rcarrillocruz
> sdn: suppress misleading OVS healthcheck log messages

- staging/src/github.com/openshift/oauth-server/cmd/oauth-server/main.go
> update oauth-server usage

- README.md
This pull request adds MariaDB under the list of available database images.
> Add MariaDB Image to Main README.md

- pkg/network/node/vxlan_monitor.go
> Bug 1718541: Fix egress monitoring for some rare corner cases [4.1]

- publishing-staging-rules.yaml
openshift-apiserver master is now prepped.
> start publishing to master

- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
Fix panic logspam when running kubelet in standalone mode.
ref: https://github.com/kubernetes/kubernetes/pull/77947
> UPSTREAM: 77947: Fix panic logspam when running kubelet in standalone mode

- vendor/k8s.io/kubernetes/pkg/kubectl/describe/versioned/describe.go
> UPSTREAM: 77347: Fix describe error of Successful Job History Limit

- test/extended/util/azure/config_file.go
- test/extended/util/test.go
Allows certain tests to be skipped based on the platform being tested.
> test/extended/util: allow tests to be skipped based on platform

- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/reflector.go
> UPSTREAM: 78991: log stale cache Info not Warning Bug 1573460

- staging/src/github.com/openshift/openshift-apiserver/Dockerfile
- staging/src/github.com/openshift/openshift-apiserver/Dockerfile.rhel
Add `Dockerfile.rhel` for CI and release builds.
Add `Dockerfile` for local builds.
> add Dockerfile for openshift-apiserver image

- glide.yaml
/assign @mfojtik @sttts @deads2k @smarterclayton
> Bug 1722919: Pin openshift to release-4.1 branches 

- hack/local-up-master/lib.sh
- staging/src/github.com/openshift/oauth-server/pkg/cmd/oauth-server/server.go
- staging/src/github.com/openshift/oauth-server/pkg/oauthserver/auth.go
- staging/src/github.com/openshift/oauth-server/pkg/oauthserver/oauth_apiserver.go
- test/util/server/server.go
- vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
- vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch_handlerchain.go
- vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch_oauthserver.go
blocked by: https://github.com/openshift/cluster-authentication-operator/pull/138
> oauth-server: don't bootstrap OAuthClients upon start

- staging/src/github.com/openshift/openshift-controller-manager/Dockerfile
- staging/src/github.com/openshift/openshift-controller-manager/Dockerfile.rhel
Add `Dockerfile.rhel` for CI and release builds.
Add `Dockerfile` for local builds.
> add Dockerfiles for openshift-apiserver images

- test/extended/builds/pipeline_jenkins_e2e.go
- test/extended/builds/pipeline_origin_bld.go
Temporary until underlying issue with Jenkins is addressed.
> Bug 1726326 - Temporarily skip Jenkins template tests

- glide.lock
- glide.yaml
- pkg/cmd/server/kubernetes/master/master_config_test.go
- vendor/github.com/evanphx/json-patch/README.md
- vendor/github.com/evanphx/json-patch/errors.go
- vendor/github.com/evanphx/json-patch/patch.go
- vendor/github.com/evanphx/json-patch/patch_test.go
- vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/options/options_test.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/groupversion.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/delete.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/update.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/BUILD
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/server_run_options.go
- vendor/k8s.io/kubernetes/test/integration/apiserver/BUILD
- vendor/k8s.io/kubernetes/test/integration/apiserver/max_json_patch_operations_test.go
- vendor/k8s.io/kubernetes/test/integration/apiserver/max_request_body_bytes_test.go
- vendor/k8s.io/kubernetes/test/integration/examples/BUILD
- vendor/k8s.io/kubernetes/test/integration/examples/webhook_test.go
- vendor/k8s.io/kubernetes/test/integration/framework/BUILD
- vendor/k8s.io/kubernetes/test/integration/framework/test_server.go
backports https://github.com/openshift/origin/pull/22267
> Bug 1723753: OpenShift incorrectly applies RFC 6902 JSON PATCH

- test/extended/util/azure/config_file.go
- test/extended/util/test.go
Reverts #23299
Also move the regex calculation out of the hot-loop.
>  Revert "Revert "test/extended/util: allow tests to be skipped based on platform""

- test/extended/builds/pipeline_jenkins_e2e.go
- test/extended/builds/pipeline_origin_bld.go
> add jenkins e2e back in with MCO fixes merged

- test/extended/authorization/authorization.go
This will prevent flakes on `TestAuthorizationResourceAccessReview` and it will allow new operators to claim cluster-admin powers without tripping on this test.  My cluster hasn't finished starting, so we'll see how this goes.
@smarterclayton per request.
> relax e2e RAR to allow openshift- namespace SAs to be cluster-admin

- test/extended/project/project.go
This test appears to be flaking.  This makes the test more conventional to get better inline messages and tightens a wait window.
> make test more conventional to get better messages

- staging/src/github.com/openshift/openshift-apiserver/pkg/openapi/zz_generated.openapi.go
- vendor/k8s.io/kubernetes/pkg/generated/openapi/zz_generated.openapi.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status_test.go
- vendor/k8s.io/kubernetes/pkg/util/node/BUILD
- vendor/k8s.io/kubernetes/pkg/util/node/node.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/api/core/v1/generated.proto
- vendor/k8s.io/kubernetes/staging/src/k8s.io/api/core/v1/types.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/api/core/v1/types_swagger_doc_generated.go
> Bug 1696628: Don't use strategic merge patch on Node.Status.Addresses

- staging/src/github.com/openshift/oc/pkg/cli/registry/login/login.go
When a user attempts to registry login, if they aren't logged in
to the cluster we were eating the error. Specifically return just
that error case, since login has certain expectations for users.
> Report unauthenticated error when performing `oc registry login`

- publishing-staging-rules.yaml
publishing change only.  I plan to merge once https://github.com/openshift/oauth-server/pull/1 merges
> stop publishing oauth-server

- test/extended/cluster/cl.go
- test/extended/cluster/utils.go
Add another possible object to wait for and the end of the test.
> Add RC ready wait to CL

- publishing-staging-rules.yaml
> remove sdn staging publish

- test/extended/oauth/htpasswd.go
https://bugzilla.redhat.com/show_bug.cgi?id=1731191  to track
> Temporarily mark htpasswd test as Flaky

- test/extended/templates/template.go
- test/extended/templates/templateinstance_cross_namespace.go
- test/extended/templates/templateinstance_fail.go
- test/extended/templates/templateinstance_impersonation.go
- test/extended/templates/templateinstance_objectkinds.go
- test/extended/templates/templateinstance_readiness.go
- test/extended/templates/templateinstance_security.go
- test/extended/templates/templateservicebroker_bind.go
- test/extended/templates/templateservicebroker_e2e.go
- test/extended/templates/templateservicebroker_security.go
Skip these until we determine the root cause of bug 1731222.
> TEMP: Skip template conformance tests

- test/extended/prometheus/prometheus.go
..as most service have now been moved to cluster monitoring.
/cc @paulfantom
> test/extended/prometheus: enabled scrape duplicate alert

- pkg/router/template/router.go
Backport of https://github.com/openshift/router/pull/7 for https://github.com/openshift/router/issues/6.
> Bug 1730778: Respect route targetPort in dynamic config

- test/extended/cluster/cl.go
- test/extended/cluster/metrics/metrics.go
- test/extended/cluster/utils.go
Eg, 
```
{"marker":"cluster_loader_marker","name":"cluster-loader-test","type":"metrics.TestDuration","startTime":"2018-06-30T00:01:48.770961141Z","Steps":[{"type":"metrics.PodStepDuration","startTime":"2018-06-30T00:02:19.496877336Z","totalTime":366231042742,"waitPodsDurations":[3052256947,3052078113],"rateDelay":0,"rateDelayCount":0,"stepPause":180,"stepPauseCount":2,"syncTime":493}],"testDuration":"6m37.014031085s"}
```
> Generate more fine-grained test duration in cluster-loader

- test/extended/images/imagestream_admission.go
May fix https://bugzilla.redhat.com/show_bug.cgi?id=1732622
> tolerate already exists for imagestream update test prep

- vendor/k8s.io/kubernetes/test/e2e/scheduling/preemption.go
related to https://bugzilla.redhat.com/show_bug.cgi?id=1733005  this just skips them
> skip flaky scheduler tests

- test/extended/builds/s2i_root.go
This removes the last direct use of the s2i repo
> snip use of s2i

- test/extended/etcd/etcd_storage_path.go
> Use linearizable etcd Get

- vendor/k8s.io/kubernetes/pkg/volume/rbd/attacher.go
- vendor/k8s.io/kubernetes/pkg/volume/rbd/rbd_test.go
- vendor/k8s.io/kubernetes/pkg/volume/rbd/rbd_util.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1699146
https://github.com/kubernetes/kubernetes/pull/79940
> Bug: 1699146: UPSTREAM: 79940: Avoid RbdDiskManager's DetachDisk function never be executed again

- vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
Bug# https://bugzilla.redhat.com/show_bug.cgi?id=1724953
> UPSTREAM: 79656: If volume in delete request does not exist, return success

- vendor/k8s.io/kubernetes/pkg/volume/nfs/nfs.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1719106
> UPSTREAM: 75805: Expose nfs volume stat metrics

- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_volumes.go
https://bugzilla.redhat.com/show_bug.cgi?id=1732193
upstream: https://github.com/kubernetes/kubernetes/pull/80518
> Bug 1732193: UPSTREAM: 80518: Fix detachment of deleted volumes

- test/extended/cmd/cmd.go
- test/extended/testdata/bindata.go
- test/extended/testdata/cmd/test/cmd/basicresources.sh
match-version won't match since we build in separate repos
> make test/cmd/basicresources work

- vendor/k8s.io/kubernetes/pkg/api/pod/util.go
- vendor/k8s.io/kubernetes/pkg/api/pod/util_test.go
- vendor/k8s.io/kubernetes/pkg/apis/apps/v1/zz_generated.defaults.go
- vendor/k8s.io/kubernetes/pkg/apis/apps/v1beta1/zz_generated.defaults.go
- vendor/k8s.io/kubernetes/pkg/apis/apps/v1beta2/zz_generated.defaults.go
- vendor/k8s.io/kubernetes/pkg/apis/batch/v1/zz_generated.defaults.go
- vendor/k8s.io/kubernetes/pkg/apis/batch/v1beta1/zz_generated.defaults.go
- vendor/k8s.io/kubernetes/pkg/apis/batch/v2alpha1/zz_generated.defaults.go
- vendor/k8s.io/kubernetes/pkg/apis/core/fuzzer/fuzzer.go
- vendor/k8s.io/kubernetes/pkg/apis/core/v1/defaults.go
- vendor/k8s.io/kubernetes/pkg/apis/core/v1/zz_generated.defaults.go
- vendor/k8s.io/kubernetes/pkg/apis/extensions/v1beta1/zz_generated.defaults.go
- vendor/k8s.io/kubernetes/test/e2e/framework/deployment_util.go
- vendor/k8s.io/kubernetes/test/e2e/framework/jobs_util.go
- vendor/k8s.io/kubernetes/test/e2e/framework/rs_util.go
- vendor/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go
- vendor/k8s.io/kubernetes/test/e2e/upgrades/apps/daemonsets.go
https://github.com/kubernetes/kubernetes/pull/78883
We want this backported to 4.1z too.
> UPSTREAM: 78883: Fix incorrect procMount defaulting

- vendor/k8s.io/kubernetes/pkg/volume/csi/csi_metrics.go
- vendor/k8s.io/kubernetes/pkg/volume/csi/csi_metrics_test.go
- vendor/k8s.io/kubernetes/pkg/volume/metrics_errors.go
> UPSTREAM: 79851: Fix nil pointer dereference error in volume_stat_calculator

- test/extended/prometheus/OWNERS
/cc @squat @LiliC @smarterclayton
> test/extended/prometheus/OWNERS: remove mxinden, add LiliC

- test/extended/builds/cluster_config.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/build-cluster-config.yaml
- test/extended/testdata/builds/test-build-cluster-config.yaml
- test/extended/testdata/builds/test-build.yaml
For https://jira.coreos.com/browse/DEVEXP-381
Note the integration test was deleted between when I started this work the beginning of this week (when the file was still around) and when I created this PR, so its deletion is not part of this PR.
@openshift/openshift-team-developer-experience fyi
> moving build integration tests to cluster config ext/ginkgo tests

- test/extended/user/basic.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1734148
> Bug 1734148: extended/user: backed users eventually return all their groups

- test/extended/project/project.go
We are waiting in the test until the API servers have noticed RBAC changes. But we only check once, giving a high chance to pass that test although one of the other two instances has not converged yet.
> Bug 1727086: test/extended/project: deflake in HA environments waiting for all instances

- vendor/k8s.io/kubernetes/pkg/kubelet/metrics/collectors/log_metrics.go
- vendor/k8s.io/kubernetes/pkg/kubelet/metrics/collectors/log_metrics_test.go
ref: https://github.com/openshift/origin/pull/23513
> Bug 1731827: UPSTREAM: 80657: add UID to kubelet_container_log_filesystem_used_bytes [4.1]

- test/extended/oauth/expiration.go
- test/extended/oauth/helpers.go
- test/extended/oauth/htpasswd.go
- test/extended/oauth/server_headers.go
Part of Issue https://github.com/openshift/origin/issues/23258
> Move TestOAuthExpiration to e2e

- test/extended/builds/custom_build.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/custom-build/Dockerfile
- test/extended/testdata/builds/custom-build/Dockerfile.sample
- test/extended/testdata/builds/custom-build/build.sh
- test/extended/testdata/builds/test-custom-build.yaml
> Add custom build strategy e2e test using buildah

- test/extended/builds/pipeline_origin_bld.go
- test/extended/testdata/bindata.go
- test/extended/testdata/verifyservice-pipeline-template.yaml
This PR contains tests for https://github.com/openshift/jenkins-client-plugin/pull/261
Will remove WIP tag after making final canges to the above given PR
> e2etests/jenkins client plugin/verifyservice

- vendor/k8s.io/kubernetes/test/e2e/scheduling/priorities.go
xref: https://github.com/kubernetes/kubernetes/pull/80922
> Bug 1724332: Toleration priority function score computation

- test/extended/builds/OWNERS
@openshift/openshift-team-developer-experience fyi
> add OWNERS file for builds ext tests

- vendor/k8s.io/kubernetes/test/e2e/framework/service_util.go
- vendor/k8s.io/kubernetes/test/e2e/framework/ssh.go
- vendor/k8s.io/kubernetes/test/e2e/framework/util.go
https://github.com/kubernetes/kubernetes/pull/76637
xref https://bugzilla.redhat.com/show_bug.cgi?id=1738690
@csrwng
> Bug 1738690: UPSTREAM: 76637: Add missing node.address != "" condition in tests

- vendor/k8s.io/kubernetes/pkg/api/pod/util.go
- vendor/k8s.io/kubernetes/test/e2e/framework/deployment_util.go
- vendor/k8s.io/kubernetes/test/e2e/framework/jobs_util.go
- vendor/k8s.io/kubernetes/test/e2e/framework/rs_util.go
- vendor/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go
- vendor/k8s.io/kubernetes/test/e2e/upgrades/apps/daemonsets.go
> Bug 1734663: UPSTREAM: 78882: Fix incorrect procMount defaulting

- test/e2e/dr/quorum_restore.go
Requires https://github.com/openshift/release/pull/4355 to be merged to have tests for DR
> test/e2e/dr/quorum_restore: set MCO image for setup-etcd-environment image

- pkg/apps/strategy/support/acceptor.go
> Bug 1741103: Fix deployer error output

- test/extended/util/framework.go
Employs verifications noted in https://bugzilla.redhat.com/show_bug.cgi?id=1721380#c11 
but with my rationale for verifying the latest OCM rollout does include the internal image registry hostname, instead of doing a canary build.
- verifies the internal registry hostname value in the OCM config matches the image config
- verifies the OCM rollout occurs  after the image config was created/populated with the hostname
- verifies the OCM rollout is complete, and the pods are updated 
- verifies the samples operator conditions indicate successful completion of imagestream import (this replaces my porting of the verification logic to the tests this PR originally had.
> Bug 1721380: more exhaustive verification of imagestream import completeness

- test/extended/cluster/cl.go
- test/extended/cluster/clt.go
The new concurrent created templates should also wait for object to be in good status.
> CL: Support waiting for arbitrary objects after creation

- test/extended/util/test.go
Skips currently failing e2e tests for gce provider.
> [gcp]: Skip failing e2e tests

- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_server_journal.go
- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_server_journal_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1669657
/assign @deads2k @smarterclayton
> Bug 1669657 - Add --boot option to oc adm node-logs

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/generic/BUILD
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/generic/conversion.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/generic/conversion_test.go
- vendor/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go
- vendor/k8s.io/kubernetes/test/e2e/framework/crd_util.go
See https://bugzilla.redhat.com/show_bug.cgi?id=1739085 and https://github.com/kubernetes/kubernetes/pull/79495 for reference.
> Bug 1739085: Fix multi-version CRD and admission webhook

- images/sdn/Dockerfile.rhel
bug 1740264
https://bugzilla.redhat.com/show_bug.cgi?id=1740264
SDN-503 Dockerfiles: verify that packages are installed
https://jira.coreos.com/browse/SDN-503
> Bug 1740264: Dockerfiles: verify package installation

- vendor/k8s.io/kubernetes/test/e2e/scheduling/priorities.go
This carries the changes from https://github.com/kubernetes/kubernetes/pull/81472/commits to fix https://bugzilla.redhat.com/show_bug.cgi?id=1724332
> Bug 1724332: Fix upstream scheduler taints/tolerations e2e

- pkg/oc/cli/admin/prune/images/images.go
Backport of https://github.com/openshift/origin/pull/22655.
> [release-3.11] Bug 1702346: use pager to get images for pruning

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/test/integration/BUILD
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/test/integration/scope_test.go
Upstream https://github.com/kubernetes/kubernetes/pull/80851.
> Bug 1740748: apiextensions: 404 if request scope does not match crd scope

- pkg/network/node/iptables.go
- pkg/network/node/node.go
Fixes: [1737386](https://bugzilla.redhat.com/show_bug.cgi?id=1737386)
Parent bz: [1726045](https://bugzilla.redhat.com/show_bug.cgi?id=1726045)
This backports the following openshift/sdn commits:
- c171df175a6be9ae9c97f84b0f8601f0443fb1f5 (openshift/sdn#13)
- b6e0ec16c9c35829a2b6b55fc6ebb3a3438420cb (openshift/sdn#17)
> Bug 1737386: pkg/network: skip OPENSHIFT-MASQ for traffic already marked for masquerade

- vendor/k8s.io/kubernetes/pkg/kubelet/server/portforward/websocket.go
- vendor/k8s.io/kubernetes/pkg/kubelet/server/remotecommand/websocket.go
- vendor/k8s.io/kubernetes/pkg/kubelet/server/server.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/watch.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/wrap.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/healthz/BUILD
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/healthz/healthz.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/httplog/httplog_test.go
Upstream: https://github.com/kubernetes/kubernetes/pull/79017
> UPSTREAM: 79017: apiserver: don't log stack trace on /healthz error

- vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
Upstream test/integration/master is green.
> UPSTREAM: <carry>: fix kube-apiserver testserver

- vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_volumes.go
expansion
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1744893
> Bug 1744893: Fix error event when cinder volume is expanded online

- test/extended/deployments/deployments.go
- test/extended/testdata/bindata.go
- test/extended/testdata/deployments/custom-deployment.yaml
- test/extended/testdata/deployments/deployment-history-limit.yaml
- test/extended/testdata/deployments/deployment-ignores-deployer.yaml
- test/extended/testdata/deployments/deployment-image-resolution-is.yaml
- test/extended/testdata/deployments/deployment-min-ready-seconds.yaml
- test/extended/testdata/deployments/deployment-simple.yaml
- test/extended/testdata/deployments/deployment-trigger.yaml
- test/extended/testdata/deployments/deployment-with-ref-env.yaml
- test/extended/testdata/deployments/failing-pre-hook.yaml
- test/extended/testdata/deployments/generation-test.yaml
- test/extended/testdata/deployments/paused-deployment.yaml
- test/extended/testdata/deployments/readiness-test.yaml
- test/extended/testdata/deployments/test-deployment-broken.yaml
- test/extended/testdata/deployments/test-deployment-test.yaml
forward port of https://github.com/openshift/origin/pull/22324
replaces https://github.com/openshift/origin/pull/22409
/cc @soltysh @mfojtik
> Bug 1741133: Fix dc adoption

- test/extended/oauth/oauth_ldap.go
- test/extended/util/ldap.go
https://github.com/openshift/origin/pull/23395 automatically closed when I messed up the branch during rebase (I'm not able to re-open).
> convert LDAP IDP integration test to e2e

- vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/max_attachable_volume_predicate_test.go
- vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/predicates.go
- vendor/k8s.io/kubernetes/pkg/scheduler/algorithmprovider/defaults/register_predicates.go
Fix counting of volumes by matching provisioner names.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1746172
> Bug 1746172: Fix bug with counting of volumes by matching provisioner names

- test/extended/util/framework.go
…e SCL/Jenkins streams we care about, ignore others
/hold
for https://github.com/openshift/cluster-samples-operator/pull/180
> Bug 1745418: Only wait for relevant imagestreams in build tests

- vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/csi_volume_predicate.go
- vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/csi_volume_predicate_test.go
- vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/max_attachable_volume_predicate_test.go
- vendor/k8s.io/kubernetes/pkg/scheduler/algorithmprovider/defaults/register_predicates.go
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1747377
Upstream PR: https://github.com/kubernetes/kubernetes/pull/73863
/assign @gnufied
> Bug 1747377: UPSTREAM: 73863: Fix code to handle delayed binding volumes

- pkg/cmd/openshift-integrated-oauth-server/server.go
We are using kube authnentication to wrap the oauth-server
endpoints and, typically, let the oauth-server itself fetch
the clientCA from the cluster for cluster admin
authenticatication.
When using Request Header identity provider, we also need to use
client cert authentication. However, oauth-server's own authentication
is logically preceded by the kube one. Since this one is configured
to fail on errors, and the client CA for Request Header IdPs is
usually different from the one that issued cluster admin cert,
the kube cert authnetication fails sooner than the request is passed
to the oauth-server.
The behavior is fixed here by using a union authenticator of the
kube authenticator and an authenticator that will ignore kube
authentication errors on paths that any user is authorized to …
> Bug 1744995: Request headers fix x509 [4.1]

- test/extended/images/hardprune.go
There is no reason to have commented out code. We'll restore this code if we decided to implement this feature.
> Bug 1718878: remove commented code

- test/extended/cli/mustgather.go
https://github.com/openshift/oc/pull/84 changed how must-gather lays out its output on disk. Updated the e2e tests to wotk with either old or new disk layout.
> support old and new must-gather output

- test/extended/cli/mustgather.go
Missed a test case in PR https://github.com/openshift/origin/pull/23724 required for PR https://github.com/openshift/oc/pull/84.
> support old and new must-gather output (2)

- test/extended/testdata/bindata.go
- test/extended/testdata/cmd/test/cmd/set-data.sh
Part of https://github.com/openshift/oc/pull/90
> test: Add cmd test for oc set data

- test/extended/operators/olm.go
Correct the test to not use the loop variable, which should ensure each group is tested.
> Bug 1752988: OLM e2e test closes over a loop variable, thus doesn't test correctly

- vendor/k8s.io/kubernetes/test/e2e/upgrades/storage/persistent_volumes.go
Enable volume upgrade tests on most/all cloudproviders
/sig storage
> UPSTREAM: 82760: Enable volume upgrade tests on all cloudproviders

- vendor/k8s.io/kubernetes/test/e2e/scheduling/taints.go
This test is occasionally flaking with the following error
```
fail [k8s.io/kubernetes/test/e2e/scheduling/taints.go:442]: Sep 16 20:50:26.054: Failed to evict all Pods. 1 pod(s) is not evicted.
```
It seems that possibly the changes in https://github.com/openshift/machine-config-operator/pull/1120 affecting the kubelet timeout have also affected the time this test should wait to look for a proper pod deletion. The kubelet's default wait time is now 2 minutes, this updates the test's timeout to 130 seconds (to account for fudge).
> Bug 1733581: Change timeout in eviction e2e test to account for new kubelet delay in pod deletion

- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/helpers_test.go
> UPSTREAM: 82790: Fix Errorf arguments in tests

- test/extended/prometheus/prometheus.go
When the cluster is skewed due to an upgrade being paused both
Prometheus and kubelets cause alerts to fire. For now disable this
test when operating in this mode.
> Ignore firing alerts when cluster version is skewed

- pkg/oauthserver/oauthserver/oauth_apiserver.go
If RequestHeaders are configured for challenges, don't set up
the bootstrap IdP for challenges either. This would otherwise
add the WWW-Authenticate header on top of the redirecting request
which then in turn causes oauth-server internal errors.
> Bug 1750809: [4.1] Fix bootstrap IdP challenges ruining RequestHeaders IdP

- hack/build-rpms.sh
- origin.spec
- Prepared the specfile for builds of OKD packages
- Removed mentions of Tito
> origin.spec OKD RPM build readiness

- test/extended/builds/s2i_env.go
- test/extended/builds/s2i_incremental.go
- test/extended/image_ecosystem/scl.go
> Bug 1757424: remove use of deprecated -p with kubectl/oc exec

- test/extended/prometheus/prometheus.go
Sometimes Prometheus seems to report not having scraped the target
for the ingresscontroller created during this test, even after 4 minutes.
Since this test for the user-defined ingresscontroller seems inessential
compared to the latest ingress-operator e2e tests, rather than increasing
the timeout or spending additional effort to root-cause the scrape delay,
just delete the test to stabilize the test suite.
> Bug 1755936: e2e: stabilize ingress metrics tests

- test/extended/cli/rsh.go
- test/extended/testdata/bindata.go
- test/extended/testdata/cli/pod-with-two-containers.yaml
Auto for smoke case: OCP-10658. 
Checkpoint:  `oc rsh` command with specific flags should work well.
> auto for smoke case OCP-10658

- glide.lock
- glide.yaml
- vendor/github.com/google/btree/btree_test.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_cmd.go
- vendor/github.com/openshift/library-go/pkg/operator/staticpod/certsyncpod/certsync_controller.go
- vendor/gopkg.in/yaml.v2/benchmark_test.go
- vendor/gopkg.in/yaml.v2/decode.go
- vendor/gopkg.in/yaml.v2/decode_test.go
- vendor/gopkg.in/yaml.v2/encode.go
- vendor/gopkg.in/yaml.v2/encode_test.go
- vendor/gopkg.in/yaml.v2/resolve.go
- vendor/gopkg.in/yaml.v2/scannerc.go
- vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/options/options_test.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/test/integration/BUILD
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/test/integration/limit_test.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/json/BUILD
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/json/json_limit_test.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/yaml/BUILD
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/yaml/yaml_test.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/json/json.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
- vendor/k8s.io/kubernetes/test/integration/apiserver/max_request_body_bytes_test.go
- vendor/k8s.io/kubernetes/test/integration/master/synthetic_master_test.go
Process followed:
1. modified and committed glide.yaml
2. 'make update-deps' and committed
3. cherry-picked e6aadb2078f3ef4880323fc00b214fef02bc1536
4. did make to build locally
> Bug 1757712: CVE-2019-11253 billion laughs

- vendor/k8s.io/kubernetes/test/e2e/upgrades/apps/daemonsets.go
- vendor/k8s.io/kubernetes/test/e2e/upgrades/apps/deployments.go
- vendor/k8s.io/kubernetes/test/e2e/upgrades/apps/replicasets.go
for better debugging of failed upgrade tests
> UPSTREAM: 00000: add debugging for upgrade tests

- vendor/k8s.io/kubernetes/pkg/volume/csi/csi_mounter.go
xref: https://github.com/kubernetes/kubernetes/pull/83747
> Bug 1745773: UPSTREAM: 83747: Improve efficiency of csiMountMgr.GetAttributes

- test/extended/operators/tolerations.go
ovnkube-master should tolerate NotReady forever.
/cc @danwinship
> tests: exclude ovnkube-master from toleration test

- test/extended/dr/quorum_restore.go
Supercedes #23961 (fixes name restoration)
@enxebre minor typo in your PR (you removed SetName accidentally).  Fixed here.
> Clear providerID during quorum restore test

- pkg/monitor/pod.go
We were not reporting this individually (although events may exist).
> monitor: Report when pods are evicted or preempted

- vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
https://github.com/kubernetes/kubernetes/pull/83567
https://bugzilla.redhat.com/show_bug.cgi?id=1698829
@openshift/storage, PTAL
> Bug 1698829: UPSTREAM: 83567: Fix attachment of just detached AWS volumes

- vendor/k8s.io/kubernetes/pkg/kubelet/cm/pod_container_manager_linux.go
ref: https://github.com/kubernetes/kubernetes/pull/83296
> UPSTREAM: 83296: Only kill process where killing failed during previous iterations

- vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go
- vendor/k8s.io/kubernetes/pkg/volume/flexvolume/detacher.go
- vendor/k8s.io/kubernetes/pkg/volume/flexvolume/unmounter.go
- vendor/k8s.io/kubernetes/pkg/volume/util/util.go
> Bug 1757904: Add missing patches against between ose and origin 3.10

- images/os/Dockerfile
Use a few more specialized workarounds to install missing packages
if they exist. This is specific to the CI environment, but that is
the current target. A future commit will likely move this to an
alternate build tooling.
> images: Extend the os image to install machine-config-daemon

- vendor/k8s.io/kubernetes/pkg/kubelet/metrics/metrics.go
- vendor/k8s.io/kubernetes/pkg/kubelet/preemption/preemption.go
Surprised we don't have these.
> UPSTREAM: 84120: Preemption metrics

- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/delta_fifo_test.go
> Bug 1761814: Informers can miss notifications

- test/extended/oauth/requestheaders.go
This will add more debugging information to `RequestHeaders IdP` test around oauth server.
> Bug 1764414: oauth: add more debugging to oauth test

- test/extended/testdata/bindata.go
- test/extended/testdata/cmd/test/cmd/completions.sh
This is needed to land https://github.com/openshift/oc/pull/132
/assign @damemi
> Fix completion tests to be more resilient to changes

- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/delta_fifo_test.go
> Bug 1761809: Informers can miss notifications

- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/cached_discovery.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/cached_discovery_test.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/round_tripper.go
- vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/round_tripper_test.go
> Bug 1718487: fix CVE-2019-11244: kubectl --http-cache=<world-accessible dir>

- vendor/k8s.io/kubernetes/test/integration/etcd/data.go
- vendor/k8s.io/kubernetes/test/integration/namespace/ns_conditions_test.go
this pull deprecates https://github.com/openshift/origin/pull/23830
> Bug 1766365: TestNamespaceCondition integration test fails

- test/extended/cluster/cl.go
- test/extended/testdata/bindata.go
- test/extended/testdata/cluster/master-vert.yaml
- test/extended/testdata/cluster/quickstarts/cakephp-mysql.json
- test/extended/testdata/cluster/quickstarts/dancer-mysql.json
- test/extended/testdata/cluster/quickstarts/django-postgresql.json
- test/extended/testdata/cluster/quickstarts/nodejs-mongodb.json
- test/extended/testdata/cluster/quickstarts/rails-postgresql.json
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1761925
> Bug 1761925: CL fix fixture path & update config path, quickstarts & bindata

- vendor/k8s.io/kubernetes/test/e2e/framework/volume/fixtures.go
Optionally run e2e pod as privileged for SELinux
> Bug 1751124: UPSTREAM: 83727: Optionally run e2e pod as privileged for SELinux

- test/extended/images/extract.go
Fixes: https://github.com/openshift/origin/issues/24068
> Remove command execution from the extended image

- test/extended/builds/pipeline_origin_bld.go
- test/extended/builds/start.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/test-build-proxy.yaml
- test/extended/testdata/cmd/test/cmd/admin.sh
- test/extended/testdata/cmd/test/cmd/builds.sh
- test/extended/testdata/cmd/test/cmd/newapp.sh
- test/extended/testdata/cmd/test/cmd/templates.sh
- test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/new-project-deployed-app.yaml
- test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/new-project-no-build.yaml
- test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/new-project-one-build.yaml
- test/extended/testdata/cmd/test/cmd/testdata/app-scenarios/new-project-two-deployment-configs.yaml
- test/extended/testdata/cmd/test/cmd/testdata/application-template-dockerbuild.json
- test/extended/testdata/cmd/test/cmd/testdata/application-template-stibuild.json
- test/extended/testdata/cmd/test/cmd/testdata/new-app/build-arg-dockerfile/Dockerfile
- test/extended/testdata/cmd/test/cmd/testdata/new-app/template-with-app-label.json
- test/extended/testdata/cmd/test/cmd/testdata/new-app/template-without-app-label.json
- test/extended/testdata/cmd/test/cmd/testdata/statefulset.yaml
- test/extended/testdata/cmd/test/cmd/testdata/test-bc.yaml
- test/extended/testdata/cmd/test/cmd/testdata/test-buildcli.json
- test/extended/testdata/cmd/test/cmd/triggers.sh
Update tests to use ruby-25 image.
fyi @openshift/openshift-team-developer-experience
> React to openshift/ruby-hello-world update

- test/extended/testdata/cmd/test/cmd/help.sh
Needed for https://github.com/openshift/oc/pull/132
/assign @damemi
> Fix cmd tests to be more resilient to changes

- examples/hello-openshift/hello-pod.json
- examples/jenkins/jenkins-ephemeral-template.json
- test/extended/builds/valuefrom.go
- test/extended/testdata/bindata.go
- test/extended/testdata/cmd/test/cmd/testdata/hello-openshift/hello-pod.json
- test/extended/testdata/cmd/test/cmd/testdata/jenkins/jenkins-ephemeral-template.json
- test/extended/testdata/cmd/test/cmd/testdata/templates/guestbook.json
- test/extended/testdata/cmd/test/cmd/testdata/test-image.json
- test/extended/testdata/image/test-image.json
- test/extended/testdata/oauthserver/oauth-network.yaml
- test/extended/testdata/templates/guestbook.json
- test/integration/testdata/test-image.json
One of the steps to land https://github.com/openshift/oc/pull/149
> Remove non-existing fields

- test/extended/testdata/cmd/test/cmd/testdata/statefulset.yaml
Fixes https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/24102/pull-ci-openshift-origin-master-e2e-cmd/1808
/cc @soltysh
> Fix deprecated versions in cmd test

- vendor/k8s.io/kubernetes/pkg/controller/replicaset/init_test.go
- vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go
- vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set_test.go
Backport of https://github.com/kubernetes/kubernetes/pull/82572
/cc @soltysh @mfojtik 
/cherrypick release-4.2
> Bug 1761689: Fix RS expectations for recreate case

- vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_server_journal.go
> Bug 1763807: UPSTREAM: <carry>: Expose a simple journald shim on the kubelet logs endpoint

- vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
- vendor/k8s.io/kubernetes/pkg/controller/controller_utils_test.go
- vendor/k8s.io/kubernetes/pkg/controller/replicaset/BUILD
- vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go
- vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set_test.go
- vendor/k8s.io/kubernetes/test/e2e/apps/deployment.go
- vendor/k8s.io/kubernetes/test/e2e/apps/types.go
- vendor/k8s.io/kubernetes/test/e2e/framework/service/jig.go
Part of https://github.com/openshift/origin/pull/24195
> Bug 1776351: Restore Miciah's dropped UPSTREAM commits from #24159

- vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go
- vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_ebs.go
- vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_ebs_block.go
- vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_ebs_block_test.go
- vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_ebs_test.go
- vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_util.go
- vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder_block.go
- vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder_block_test.go
- vendor/k8s.io/kubernetes/pkg/volume/gcepd/gce_pd_block.go
- vendor/k8s.io/kubernetes/pkg/volume/gcepd/gce_pd_block_test.go
- vendor/k8s.io/kubernetes/pkg/volume/local/local.go
- vendor/k8s.io/kubernetes/pkg/volume/local/local_test.go
- vendor/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume_block.go
- vendor/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume_block_test.go
- vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/disruptive.go
- vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go
- vendor/k8s.io/kubernetes/test/e2e/storage/utils/BUILD
- vendor/k8s.io/kubernetes/test/e2e/storage/utils/utils.go
Part of https://github.com/openshift/origin/pull/24195
> Bug 1776351: Restore UPSTREAMs dropped in #24159

- pkg/network/common/egressip.go
- pkg/network/common/egressip_test.go
- pkg/network/master/egressip.go
- pkg/network/node/egressip.go
Backport of https://github.com/openshift/sdn/pull/51
> Bug 1772904: [4.1] Clean up egress IPs on startup

- vendor/k8s.io/kubernetes/pkg/volume/csi/csi_mounter.go
This backport was requested by @JohnStrunk:
https://bugzilla.redhat.com/show_bug.cgi?id=1745773
> [release-4.2] Bug 1762658: UPSTREAM: 83747: Improve efficiency of csiMountMgr.GetAttributes

- pkg/network/common/egressip.go
- pkg/network/common/egressip_test.go
- pkg/network/master/egressip.go
- pkg/network/node/egressip.go
Backport of https://github.com/openshift/sdn/pull/51
> Bug 1762235: [3.11] Clean up egress IPs on startup

- test/extended/controller_manager/pull_secret.go
- Reverts commit dadd659.
- Raise error fetching dockercfg secret
> Bug 1765294: Debug flaking token delete test

- vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
https://bugzilla.redhat.com/show_bug.cgi?id=1772189
https://github.com/kubernetes/kubernetes/pull/85675
> Bug 1772189: UPSTREAM: 85675: Fix AWS eventual consistency of AttachDisk

- test/extended/images/imagechange_buildtrigger.go
Typo from 03479b8bd9 (#23372).
> test/extended/images/imagechange_buildtrigger: Fix "triggger" -> "trigger" typo
