images/router/haproxy/conf/haproxy-config.template
Partially fixes #13771.
Backport #20667  to 3.10
Can't automatically cherrypick because of conflicts.
=> [backport-3.10] Add forwarded header instead of replacing it

hack/local-up-master/lib.sh, hack/local-up-master/master.sh, hack/test-cmd.sh
/assign @juanvallejo 
We can't move server logs from `test-cmd.sh` to a temporary directory b/c they won't be available in our CI. Those need to stay in `_output/scripts/test-cmd/`.
=> test-cmd logs

cmd/openshift-tests/openshift-tests.go, pkg/test/ginkgo/cmd_runsuite.go, pkg/test/ginkgo/cmd_runtest.go, test/extended/util/test.go
The namespaces serial tests are too slow right now, until we figure out
why openshift-apiserver is dogging it. Disable them for smoke-4.
Fix the output so that we can't overlap stderr or stdout by always writing
summary info to stdout.
=> e2e: Omit a slow test from smoke-4, clean up error output

pkg/cmd/openshift-apiserver/server.go, pkg/cmd/openshift-controller-manager/cmd.go, pkg/cmd/openshift-controller-manager/controller_manager.go, pkg/cmd/openshift-kube-apiserver/server.go, pkg/cmd/openshift-network-controller/network_controller.go, pkg/cmd/openshift-osinserver/server.go
There are client-side metrics, but we have to register for them.  This imports the package so we get those metrics published.
=> add client metrics

hack/lib/util/environment.sh
Currently our CI sets `ARTIFACT_DIR` (https://github.com/openshift/release/blob/0d11e633e49a937036d4bbd7886854b50365dbee/ci-operator/config/openshift/origin/openshift-origin-master.yaml#L170) which is then being copied over to artifacts and available in CI, we need to ensure we save logs to that dir when this value is set.
=> Save logs to ARTIFACT_DIR if one was provided

vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/patch_policy.go
This change will enable the system prefixed certs to work for communication to the kubelet from https://github.com/openshift/installer/pull/703
@soltysh it's an upstream we need to unstick metrics from kubelet
=> UPSTREAM: <carry>: bootstrap rbac permissions patch

pkg/project/auth/cache.go
When this happens, there's not really anything to do. We ought to keep track of how many bad clusterrolebindings we have (or point them out in some kind of status), but this message is super annoying.
@liggitt you were right
mute that annoying, unhelpful message that is cluttering my log.
=> mute project cache evaluation error

pkg/network/node/ovscontroller.go, pkg/util/ovs/fake_ovs_test.go, pkg/util/ovs/ovs.go, pkg/util/ovs/ovs_test.go
When the SDN has to restart pods on restart, it ends up logging:
will restart pod 'openshift-apiserver/apiserver-4shs9' due to update failure on restart: could not parse ofport "": strconv.Atoi: parsing "": invalid syntax
This fixes it to be:
will restart pod 'openshift-apiserver/apiserver-4shs9' due to update failure on restart: failed to find pod details in OVS database
The actual fix is the bit in pkg/util/ovs/ovs.go, although that also fixes a second bug found while adding the test case, which is that if Find returned multiple rows, the last value would have a trailing `"\n"`. (But we aren't using Find anywhere where we wanted to get back multiple rows so it didn't matter.)
(Mentioned in #18924 which I let get auto-closed because we're probably not going to fix it at this point, but …
=> Fix an incorrect error message on SDN restart

hack/local-up-master/lib.sh
We need to explicitly set the `--cert-dir` for kube-controller-manager, otherwise it'll get defaulted to `/var/run/kubernetes` which CI does not have access to write to. 
=> Set --cert-dir for kube-controller-manager in test-cmd

pkg/cmd/openshift-apiserver/openshiftapiserver/config.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/authorization/path/doc.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/authorization/path/path.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/authorization/path/path_test.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/authorization.go
/heathz is not confidential and system:masters can do anything, so exclude those in the delegated authorizer to improve reliability
@openshift/sig-auth @openshift/sig-master 
/assign @sttts @mfojtik 
@smarterclayton to avoid 403s during health checks.
=> allow openshift-apiserver to avoid SAR for certain paths and groups

images/dind/node/ovn-kubernetes-node.sh
ok, actually you need to specify --nodeport on both master and nodes...
=> additional OVN dind fix

examples/storage-examples/host-path-examples/README.md
Path `/usr/share/nginx/html/testlocal` and path `/usr/share/nginx/html/testl` are used as mountPath in host-path-example, sync them to `/usr/share/nginx/html/test`
/sig storage
=> Sync path of mountPath in host-path-example

pkg/network/node/iptables.go
Backport of https://github.com/openshift/origin/pull/21441
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1653380
=> [3.11] Ensure Egress IP rules are recreated after firewalld reload

test/extended/operators/cluster.go
During the e2e runs, no pods in kube-* or openshift-* should be unhealthy
or be failing.
=> e2e: Add a test to verify no crashlooping pods

pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/default_audit_policy.go, pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/flags.go, test/integration/oauth_server_headers_test.go, test/util/server/server.go
Turns on the audit log by default so that we don't have to deal with "who did that!?" questions from customers.  We probably need to expose knobs to turn it off and set the retention policy (I chose one day).  How far we between now and when dynamic auditing arrives (1.14 probably) is an open question.
@cuppett @derekwaynecarr as discussed
/assign @mfojtik @soltysh
=> turn hyperkube audit logging on by default

test/extended/templates/templateinstance_readiness.go
It's also above our e2e cap, so we don't get output
=> Waiting 20 minutes for template readiness is excessive

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/healthz/healthz.go
For easier debugging of readiness errors.
=> UPSTREAM: <carry>: log a warning with verbose output if healthz fails

test/extended/builds/pipeline_jenkins_e2e.go, test/extended/builds/pipeline_origin_bld.go
This is a quick fix to prevent Jenkins tests from polluting the global
namespace. exutil.NewCLI() can only be used within a scope, not global.
Caught while debugging 
https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.0/2073/?log#openshift-tests-featureplatformsuiteopenshiftsmoke-4-managed-cluster-should-have-no-crashlooping-pods-in-core-namespaces-over-two-minutes-suiteopenshiftconformanceparallel
=> Jenkins is registering global ginkgo hooks, must be scoped

pkg/test/ginkgo/cmd_runsuite.go
The warnings will be displayed on Gubernator like flakes, but not
break the build until we get this under control.
=> Don't error out for now when events are detected

test/extended/builds/build_pruning.go, test/extended/testdata/bindata.go, test/extended/testdata/builds/build-pruning/errored-build-config.yaml, test/extended/testdata/builds/build-pruning/failed-build-config.yaml, test/extended/testdata/builds/build-pruning/successful-build-config.yaml
this introduced flakes because when all 4 builds run in parallel, the one we're waiting for can get pruned before waitforabuild actually sees that it is complete.
since Clayton sped up the build this test uses, i'm going back to running them in serial.
=> revert running prune test builds in parallel

pkg/oc/cli/admin/release/new.go
[DATE]-[TIME] instead of [DATE]T[TIME]Z
=> Slightly new format string for default release command

pkg/router/metrics/haproxy/haproxy.go
Running into this issue on our clusters:
We have around 1040 servers/backend reported in haproxy metrics and the `ServerThreshold` is the default on `500`.
As expected `haproxy_server_*` are not existing in prometheus as we exceed the threshold. But unfortunately the `backend` and `frontend` are not fully exported, they stop at around ~400.
Reason is that as soon as the rowparser reaches the 500th server it runs `continue` but it does that also for `backends` and `frontends`, leading into the situation that not all `backend` and `frontend` are reported.
Fixes https://github.com/openshift/origin/issues/21545
=> only check for exceeding of ServerThreshold if the current row is a server

test/extended/builds/s2i_quota.go, test/extended/util/framework.go
Seeing weird build log output when `--timestamps` is passed which breaks the output checking this test does.  The log output looks like:
```
2018-12-02T13:27:11.370755435Z MEMORY=2018-12-02T13:27:11.466193503Z 209715200
```
when we are looking for
`MEMORY=209715200`
somehow a timestamp got dumped in the middle of the output.
Note that the pod logs printed later show the correct/expected output:
```
time="2018-12-02T13:27:11Z" level=debug msg="Running &exec.Cmd{Path:\"/bin/sh\", Args:[]string{\"/bin/sh\", \"-c\", \"/tmp/scripts/assemble\"}, Env:[]string{\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\", \"BUILD_LOGLEVEL=6\", \"OPENSHIFT_BUILD_NAMESPACE=e2e-test-s2i-build-quota-7d49h\", \"OPENSHIFT_BUILD_NAME=s2i-build-quota-1\"}, Dir:\"/\", …
```
=> skip timestamps in build log output check

pkg/oc/cli/admin/release/new.go
We were not overwriting the previous values, so the new payload pointed
to the old locations incorrectly.
=> When mirroring, ensure the payload image location is updated

test/extended/builds/multistage.go, test/extended/images/append.go, test/extended/images/extract.go, test/extended/templates/templateservicebroker_bind.go, test/extended/templates/templateservicebroker_e2e.go, test/extended/templates/templateservicebroker_security.go
Make TSB tests skip based on install status. Update other tests to lookup
the correct hostname for the registry rather than hardcode it.
=> Update e2e tests for 4.0 conventions

test/extended/router/metrics.go
It will be replaced with a more generic client-go variation.
=> We're going to remove openshift_build_info from the router when split

test/extended/testdata/bindata.go, test/extended/testdata/router-override-domains.yaml, test/extended/testdata/router-override.yaml, test/extended/testdata/router-scoped.yaml
Eliminate an unready backend as a potential source of e2e flakes.
=> Set readiness checks on test routers

pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_handlerchain.go, pkg/oauthserver/authenticator/password/bootstrap/bootstrap.go, pkg/oauthserver/oauthserver/auth.go, pkg/oauthserver/oauthserver/oauth_apiserver.go, pkg/oauthserver/server/login/login.go, pkg/oauthserver/server/logout/logout.go, pkg/oauthserver/server/selectprovider/bootstrapselectprovider.go, pkg/oauthserver/server/session/authenticator.go, pkg/oauthserver/server/session/bootstrapauthenticator.go, pkg/oauthserver/server/session/put.go, pkg/oauthserver/server/session/types.go, pkg/oauthserver/server/tokenrequest/endpoints.go
Enforce strong password for kube:admin
---
Refactor out bootstrap session logic
---
Add logout endpoint to force session invalidation
---
@openshift/sig-auth @smarterclayton @derekwaynecarr
=> kube:admin strong password, logout endpoint

pkg/oc/cli/admin/release/info.go, pkg/oc/cli/admin/release/new.go
Try to create the metadata if possible. Also update the name on
disk from 'cincinnati' to 'release-metadata'.
@crawford
=> release: Generate a manifest if the name is semantic

vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
A success on any endpoint for api aggregation is enough to keep the service alive.
/assign @sttts
=> UPSTREAM: <carry>: try multiple endpoints in parallel

pkg/oc/cli/admin/release/new.go
It should instead be referenced by another component, but include it here
until we can identify what that is. This gives us installer reproducibility
for hive.
=> Temporarily force the installer to be part of the payload

vendor/k8s.io/kubernetes/test/e2e/framework/util.go
The new metrics adapter is periodically failing, causing e2e tests to
fail because they get a 500 trying to list podmetrics/nodemetrics.
Ignore those resources for now.
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-monitoring-operator/174/pull-ci-openshift-cluster-monitoring-operator-master-e2e-aws/21/
=> UPSTREAM: <drop>: Temporarily ignore metrics during namespace cleanup

pkg/build/buildapihelpers/util.go, pkg/build/controller/build/build_controller.go, pkg/build/controller/build/build_controller_test.go, pkg/build/controller/strategy/custom.go, pkg/build/controller/strategy/custom_test.go, pkg/build/controller/strategy/docker.go, pkg/build/controller/strategy/docker_test.go, pkg/build/controller/strategy/sti.go, pkg/build/controller/strategy/sti_test.go, pkg/build/controller/strategy/util.go, pkg/build/controller/strategy/util_test.go, pkg/build/util/consts.go
* Create ConfigMap per build mounting registry configurations
* Add owner reference ensuring proper GC on cluster
JIRA-ID: [DEVEXP-154](https://jira.coreos.com/browse/DEVEXP-154)
=> Mount Registry Config to Build Pods

pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/nonapiserver.go, pkg/oauth/util/discovery.go
This change makes kubeAPIServerConfig.authConfig.oauthMetadataFile
the preferred source for the OAuth authorization server metadata
instead of the data from the OAuth config.  This serves as a
starting point for breaking out osin from the kube apiserver.
Soon this code path will have no reliance on OAuth config.
Also makes failure to initialize OAuth metadata not fatal for the
kube apiserver.
@openshift/sig-auth @openshift/sig-master
=> Prefer oauthMetadataFile as OAuth metadata source

vendor/k8s.io/kubernetes/pkg/util/mount/mount.go
Fixes NFS volume setup and EmptyDir subpath.
https://bugzilla.redhat.com/show_bug.cgi?id=1657735
https://bugzilla.redhat.com/show_bug.cgi?id=1656927
@openshift/sig-storage, PTAL
=> Fix mount point checks

vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go, vendor/k8s.io/kubernetes/pkg/proxy/service.go, vendor/k8s.io/kubernetes/pkg/proxy/types.go, vendor/k8s.io/kubernetes/pkg/util/conntrack/conntrack.go, vendor/k8s.io/kubernetes/pkg/util/conntrack/conntrack_test.go
https://github.com/kubernetes/kubernetes/pull/71573
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1659204
=> UPSTREAM: 71573: Correctly Clear conntrack entry on endpoint changes when using nodeport

pkg/apiserver/authentication/oauth/bootstrapauthenticator.go, pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_authenticator.go, pkg/oauthserver/authenticator/password/bootstrap/bootstrap.go, pkg/oauthserver/oauthserver/auth.go, pkg/oauthserver/oauthserver/oauth_apiserver.go, pkg/oauthserver/server/selectprovider/bootstrapselectprovider.go, pkg/oauthserver/server/session/bootstrapauthenticator.go
This change makes the secret backing the kube:admin user bounded by
the creation timestamp of kube-system.  Thus once the secret is
deleted, recreating it will not allow kube:admin to be reused.  This
makes write access to the secret far less powerful.
@sallyom how is that test coming :smile: ?
=> Tighten kube:admin provisioning period

origin.spec
* Adds -sdn-ovs
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1593209
Reverts part of https://github.com/openshift/origin/pull/20059
=> Bug 1593209 - Add sdn-ovs back to OpenShift excluder

pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go
The first `restMapper.Reset()` call might block if some other code has accessed the rest mapper before and is still holding the lock. In that case the whole apiserver boostrapping will block, and in the case of discovery issues in the cluster this might lead to a dead lock.
Note, that `wait.Until` immediately calls the func, i.e. `f(); wait.Until(f, 10*time.Seconds)` is even worse than `wait.Until(f, 10*time.Seconds)` for our purposes because the former calls `f` twice immediately without waiting the 10 seconds.
=> Unblock openshift.io-restmapperupdater post start hook

test/extended/operators/operators.go
- This will be enabled again after https://github.com/openshift/cluster-dns-operator/pull/58 is merged
=> Disable required operator check in e2e test

pkg/template/controller/templateinstance_controller.go, test/extended/templates/templateinstance_fail.go, test/extended/testdata/bindata.go, test/extended/testdata/templates/templateinstance_badobject.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1661845
=> properly handle object creation error in template instantiate

images/cli/Dockerfile, images/cli/manifests/01_imagestream.yaml, images/cli/manifests/image-references, test/extended/images/append.go, test/extended/router/config_manager.go, test/extended/router/scoped.go, test/extended/router/stress.go, test/extended/router/unprivileged.go, test/extended/router/weighted.go, test/extended/util/framework.go, vendor/k8s.io/kubernetes/test/e2e/framework/util.go
Workers are now private, which means we can't directly connect to
them. For now, make the e2e tests tolerate a bastion hop by
proxying the SSH connection from a given instance.
TODO:
https://github.com/openshift/release/pull/2469
Blocks moving away from e2e-gcp because some tests still depend on SSH https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-all-4.0/18/
=> Support tunneling to masters over SSH for e2e tests

test/extended/conformance-k8s.sh
We changed from node-role.kubernetes.io/master=true to an empty string
like tectonic. Update to a mode both can use.
=> conformance-k8s.sh should work against AWS kube

pkg/apiserver/authentication/oauth/bootstrapauthenticator.go, pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_authenticator.go, pkg/oauthserver/authenticator/password/bootstrap/bootstrap.go, pkg/oauthserver/oauthserver/auth.go, pkg/oauthserver/oauthserver/oauth_apiserver.go, pkg/oauthserver/server/selectprovider/bootstrapselectprovider.go, pkg/oauthserver/server/session/bootstrapauthenticator.go
Move bootstrap user data to BootstrapUserData struct
This change moves the bootstrap OAuth user behind an interface to
isolate the logic.  The data needed to validate flows for this user
are now stored in a BootstrapUserData struct to make it easier to
extend the associated flows.
---
Allow kube:admin to be scoped
When I originally wrote the authenticator for the bootstrap user, I
was thinking of a user that could always perform any action, similar
to an x509 cert based user.  However, unlike a cert based user, the
bootstrap user can go through OAuth flows, meaning that untrusted
clients can get scoped tokens for it.  We need those tokens to not
be all powerful, otherwise we break the safety guarantees of those
flows.
This change removes the …
=> Allow kube:admin to be scoped

pkg/oc/cli/admin/release/image_mapper.go
The other messages in this function show path and tag.Name, this message
should too. Makes debugging which tag hasn't been cloned much easier.
=> Explain which image short name is missing from the input

vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go, vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/recycle_test.go
In the situation when a PVC is deleted and a new one with the same name bound to a different PV the "old" PV may fail to recycle since it's associaded with a PVC that is detected as being in use. This may cause the recycler processes to hang.
Upstream PR: kubernetes/kubernetes#70580
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1623426
=> [release-3.11] UPSTREAM: 70580: PV Controller -- fix recycling

vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go, vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/recycle_test.go
In the situation when a PVC is deleted and a new one with the same name bound to a different PV the "old" PV may fail to recycle since it's associaded with a PVC that is detected as being in use. This may cause the recycler processes to hang.
Upstream PR: https://github.com/kubernetes/kubernetes/pull/70580
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1623426
=> [release-3.10] UPSTREAM: 70580: PV Controller -- fix recycling

test/extended/util/test.go
In https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-all-4.0/23/ these were the last two failing tests blocking switching e2e-aws to conformance.
=> Temporarily remove these tests from conformance until they are fixed

contrib/completions/bash/oc, contrib/completions/zsh/oc, pkg/oc/cli/cli_bashcomp_func.go
`__debug` is already replaced with `__oc_debug`. This patch makes
completion use `__oc_debug` instead of `__debug`.
Fixes https://github.com/openshift/origin/issues/21705
=> Fix completion for __oc_get_containers

cmd/openshift-tests/e2e.go, cmd/openshift-tests/openshift-tests.go, pkg/test/ginkgo/cmd_runsuite.go, pkg/test/ginkgo/test.go, test/extended/operators/cluster.go, test/extended/util/test.go
* smoke-4 is not needed anymore
* make conformance/parallel tolerate some flakes for now
* rename `openshift/all` to `all` for easier typing
* add `openshift/conformance-excluded` to better review excluded
* add `openshift/scalability` to test repeatable performance numbers
* make flake detection per suite, not per run
Will add openshift/scalability to a release blocking job.
=> Remove the smoke-4 suite and add new suites for scalability

HACKING.md, pkg/version/version.go, test/util/server/server.go
Without this being set to a non-empty string, the openapi spec will lack a version string in `$root.info` which makes the apiservers' launch to fail.
=> pkg/version: set versionFromGit to 'unknown' value for debugging in IDE

test/extended/util/test.go
now that https://github.com/openshift/origin/pull/20959 has merged, the test should pass. Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1622195
=> Re-enable emptydir test, no longer uses git volume

vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
The aggregator shouldn't report the status on an endpoint to be good unless it gets back a 200-ish return code.  This builds the correct transport so that a unauthorized *should* pop out if the backing apiserver would return one.
/assign @sttts
I'm actually not sure how to wire this upstream since the proxy transport is created in an odd way and we couldn't/shouldn't modify it here. We already customized this to hit many in parallel, what's one more :(
@mfojtik checking at the other end.
=> UPSTREAM: <carry>: require good status on discovery check

origin.spec
This patch adds kubectl compltion script to client RPM package.
=> Add kubectl bash compeltion to client RPM package

pkg/build/controller/strategy/docker.go, pkg/build/controller/strategy/docker_test.go, pkg/build/controller/strategy/sti.go, pkg/build/controller/strategy/sti_test.go, pkg/build/util/util.go
@mrunalp @mtrmac @bparees @smarterclayton 
This is just a wip to test things out as we need the resulting hypershift image from this PR to substitute the original one in a cluster and test this workflow, so, do not merge
Signed-off-by: Antonio Murdaca <runcom@linux.com>
=> build/strategy: wire in blob mount-from functionality

pkg/apps/controller/deployer/deployer_controller.go, pkg/apps/controller/deployer/deployer_controller_test.go
Now that pruning and pod garbage collection are implemented, we can be less aggressive about removing completed deployer pods. This keeps logs available for longer for custom deployments or hook pods and fixes a number of irritating race conditions that tests continue to struggle with.
An admin is unlikely to see an impact by this, and it makes viewing logs and hook logs much easier for a user.
=> Preserve completed deployer pods

pkg/network/node/cniserver/cniserver.go, pkg/network/node/node.go, pkg/network/node/ovscontroller.go, pkg/network/node/pod.go, pkg/network/node/pod_test.go, pkg/network/node/runtime.go, pkg/network/node/sdn_controller.go, pkg/util/ovs/fake_ovs.go, pkg/util/ovs/fake_ovs_test.go, pkg/util/ovs/ovs.go, pkg/util/ovs/ovs_test.go, pkg/util/ovs/parse.go
This fixes the SDN to be able to preserve existing pod networking after a restart, and specifically in the case of an upgrade to a new version of the SDN/OVS pods.
The problem with the current code is that while the OVS vsdb is persisted to disk and preserved across a restart/upgrade of the OVS pod, the OVS *flow* database is apparently kept only in memory. This means that when openshift-sdn is restarted, it will find that `br0` exists and has pods attached to it, but it has no flows. There was code that was intended to deal with this case, but it had bit-rotted (#18924).
This PR fixes it to save the information about the previously-attached pods before destroying and recreating the bridge, and then use that information later to reattach them. (Leaving the existing bridge in place rather …
=> Don't restart pods on SDN restart/upgrade

vendor/k8s.io/kubernetes/pkg/controller/namespace/deletion/namespaced_resources_deleter.go
this is needed to allow us to safely remove finalizers on openshift-apiserver
sorry @soltysh
=> UPSTREAM: 72744: delete as much content from a namespace as possible

pkg/build/controller/build/build_controller.go, pkg/build/controller/strategy/util.go, pkg/build/util/consts.go
Add policy.json to the mounted system config for buildah.
Currently empty - eventually will be populated via cluster config.
JIRA-ID: DEVEXP-154
=> build - Stage policy.json for Buildah

pkg/admission/customresourcevalidation/attributes.go, pkg/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go, pkg/admission/customresourcevalidation/customresourcevalidator.go, pkg/admission/customresourcevalidation/customresourcevalidator_test.go, pkg/admission/customresourcevalidation/helpers.go, pkg/admission/customresourcevalidation/image/validate_image.go, pkg/cmd/openshift-kube-apiserver/server.go
This makes an easy pattern to follow and provide CR validation functions.  I'm thinking about our config APIs in particular.  This isn't totally pure, but it does solve our ordering issue, makes it easy for teams to add validation, provides for immutable fields, and could maybe be added as a webhook later if we decided against this.
@derekwaynecarr @smarterclayton we've discussed the need for validation
@openshift/sig-master think of something better or we'll have to hold our noses :)
=> add easy pattern for customresource validation

test/extended/README.md
test/extended/README.md fix, how to run a subset of tests using regexp
change `openshift-tests run openshift/all` to `openshift-tests run all`
=> test/extended/README openshift/all->all suite

pkg/oc/originpolymorphichelpers/attachablepodforobject.go
Backport of https://github.com/openshift/origin/pull/21367
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1642745
cc @soltysh
=> handle appsv1.DeploymenConfigs in AttachablePodForObject helper

test/extended/bootstrap_user/bootstrap_user_login.go, test/extended/include.go
@enj @smarterclayton test for kubeadmin login.
this test generates and applies a new kubeadmin secret to test login, then restores to original if it existed, or deletes it if it did not.
=> add kubeadmin login test

test/extended/router/router.go
host name if it is available.
On aws when the proxy protocol is enabled, the cluster ip would talk the
"proxy" protocol, so we have to use the external load balancer host name to
talk http[s].
This is blocking https://github.com/openshift/cluster-ingress-operator/pull/84 tests.
@ironcladlou  PTAL thx
=> Fix the router tests host name to use the external load balancer service

pkg/test/ginkgo/cmd_runsuite.go, test/extended/util/metrics.go
~~Work in progress... Trying to find the best place to wire this.~~
Adds an extended test that checks `requests-per-second` made by operator pods which expose a `/metrics` endpoint.
Fails on any operator pods whose request-rate exceeds 1.5 requests / second
cc @deads2k @tnozicka @soltysh
=> add operator metrics test for requests per second

test/extended/util/test.go
The test causes other dynamic provisioning to get delayed because it's
so aggressive. Marking it serial so it runs in isolation in the
serial suite.
@jsafrane identified this test as the culprit for https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.0/3122#openshift-tests-sig-storage-dynamic-provisioning-invalid-aws-kms-key-should-report-an-error-and-create-no-pv-suiteopenshiftconformanceparallel-suitek8s
=> Make DynamicProvisioner serial because it consumes a lot of AWS quota

pkg/test/ginkgo/cmd_runsuite.go
The limits are lower than what the components are doing, and this
is causing most e2e runs to fail.
Reintroduce as an e2e test, not as a top level test.  Also, let's make sure this isn't flaking before we merge it.
https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.0/3265
https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.0/3267
https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.0/3267
=> Revert #21694, most components are not behaving properly

contrib/completions/bash/oc, contrib/completions/zsh/oc, pkg/oc/cli/cli_bashcomp_func.go
This patch adds/removes/moves completion in custom func:
- Add oc_autoscale, oc_port-forward, oc_attach to custom func.
- Remove oc_env, oc_secrets_new, oc_volume, oc_deploy from custom func as obsoleted.
- Move oc_attach to call __oc_require_pod_and_container based on https://github.com/kubernetes/kubernetes/pull/72448.
=> Update custom func in completion

test/extended/testdata/bindata.go, test/extended/testdata/deployments/custom-deployment.yaml, test/extended/testdata/deployments/test-deployment-test.yaml
Ensure that log output has a chance to make it to disk.
=> Wait at end of deployer tests to catch log output

pkg/oc/cli/admin/release/image_mapper.go, pkg/oc/cli/admin/release/image_mapper_test.go
cluster monitoring operator was using an equals sign as the preceeding
character for an image which the regex didn't grab. Use `\W` to identify
the leading char instead.
=> oc adm release new doesn't replace correctly for leading characters

pkg/oc/cli/admin/release/new.go
For now we consistently set these throughout our automation. In the
future we can consider adding support for other labels.
OCP releases were showing no version info.
=> oc adm release new should prefer openshift scoped git labels

pkg/cmd/openshift-apiserver/cmd.go, pkg/cmd/openshift-controller-manager/cmd.go, pkg/cmd/openshift-kube-apiserver/cmd.go
Only fall through in case of missing kind, missing version or unknown gvk.
=> Return decoding errors of non-legacy config types

test/extended/operators/olm.go
Add a ginkgo test to list all necessary OLM resources to verify if they are
available and ensure OLM is working properly.
Note: This is an initial verification test for OLM. The test suite will be
expanded further at a later time.
Signed-off-by: Vu Dinh <vdinh@redhat.com>
=> e2e: Add a test verifying OLM is working properly by listing its resources

pkg/admission/customresourcevalidation/authentication/OWNERS, pkg/admission/customresourcevalidation/authentication/validate_authentication.go, pkg/admission/customresourcevalidation/customresourcevalidationregistration/OWNERS, pkg/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go, pkg/admission/customresourcevalidation/image/OWNERS, pkg/admission/customresourcevalidation/image/validate_image.go, pkg/admission/customresourcevalidation/oauth/OWNERS, pkg/admission/customresourcevalidation/oauth/validate_oauth.go, pkg/admission/customresourcevalidation/project/OWNERS, pkg/admission/customresourcevalidation/project/validate_project.go
Use consts for custom resource validators plugin names
---
Add boilerplate for Authentication validation
---
Add boilerplate for OAuth validation
---
@openshift/sig-auth @openshift/sig-master 
This is a no-op change to get the validation scaffolding in place.
=> Add stubs for Authentication and OAuth validation

test/extended/deployments/deployments.go, test/extended/testdata/bindata.go, test/extended/testdata/deployments/custom-deployment.yaml, test/extended/testdata/deployments/test-deployment-test.yaml
this might address some flakes we are seeing when using logs -f and
excessive iops.
=> test, deployments: do not use logs -f

pkg/oc/cli/admin/release/info.go
To use `o.ShowPullSpec`, matching the example set by the other options.  It had been using `o.ShowCommit` as the default since 19df633b (#21432), which may have been a copy/paste error.
CC @smarterclayton
=> pkg/oc/cli/admin/release/info: Fix pullspecs default

test/extended/deployments/deployments.go
We waited 5s, but lots of things can prevent this from happening
in under 10s. Set a longer timeout consistently through the test.
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_telemeter/118/pull-ci-openshift-telemeter-master-e2e-aws/41#openshift-tests-featuredeploymentconfig-deploymentconfigs-when-run-iteratively-conformance-should-immediately-start-a-new-deployment-suiteopenshiftconformanceparallelminimal
=> Deployment test is too aggressive on start timing

pkg/oc/cli/admin/release/mirror.go, pkg/oc/cli/admin/release/new.go
We parallelize actions against the registry and these methods need
to guard against concurrent writes to the maps.
=> Synchronize access to shared data in commands with concurrency

test/extended/util/test.go
`[sig-storage] Volume limits should verify that all nodes have volume limits [Suite:openshift/conformance/parallel] [Suite:k8s]`
Introduced in rebase, https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/21860/pull-ci-openshift-origin-master-e2e-aws/2856/
@wongma7 @gnufied fyi
=> Temporarily disable flaky volume test

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/metrics/metrics.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/metrics/metrics_test.go
Admission metrics were 90% of all reported metrics for the apiserver,
for little benefit.
=> UPSTREAM: 69895: Reduce cardinality of admission metrics

vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/cache/actual_state_of_world.go, vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/BUILD, vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler_test.go, vendor/k8s.io/kubernetes/pkg/volume/testing/testing.go
bugfix.
will also help reduce flakes https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/21776/pull-ci-openshift-origin-master-e2e-aws/2846#openshift-tests-sig-storage-dynamic-provisioning-dynamicprovisioner-should-provision-storage-with-different-parameters-suiteopenshiftconformanceparallel-suitek8s
=> UPSTREAM: 72118: Fixed clearing of devicePath after UnmountDevice

vendor/k8s.io/kubernetes/pkg/probe/http/http.go, vendor/k8s.io/kubernetes/pkg/probe/http/http_test.go
Picks: https://github.com/kubernetes/kubernetes/pull/68663
Prevents kubelet proxy settings from being used by liveness / readiness probes.
cc @soltysh
=> UPSTREAM: 68663: Ignore kubelet proxy settings in http probe

pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go, pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_handlerchain.go
When a valid authConfig.OAuthMetadataFile is set, we should not run the internal OAuth server.  This roughly equates to the master config validation from 3.x which required these to be mutually
exclusive.
=> Prevent internal OAuth server from running when using external

publishing-rules.yaml
This add publishing from the `release-3.11` to kube fork.
=> publishing: add rules for 3.11 branch to track 1.11.1 kube

pkg/oc/cli/admin/prune/imageprune/prune.go, pkg/oc/cli/login/helpers.go, pkg/oc/cli/login/loginoptions_test.go, pkg/oc/lib/tokencmd/request_token.go, pkg/oc/lib/tokencmd/request_token_test.go
oc: http.NewRequest use http.Method* enums
---
oc login: use system roots when necessary
When performing an OAuth flow with an external OAuth server, the use
of system roots may be required (ex: if the OAuth server is using a
route with a valid Let's Encrypt cert).  Combing system roots with
custom CA data only works reliably on Linux style operating systems.
Since oc must work across operating systems, we opt to probe the
OAuth server to determine what CA store to use.
---
/assign @mrogers950
=> oc login: use system roots when necessary

vendor/k8s.io/kubernetes/test/e2e/framework/util.go
Greatly assists in debugging who is calling skip
=> UPSTREAM: 70939: Use more precise Skipf() locations in tests

pkg/router/controller/hostindex/hostindex.go, pkg/router/controller/hostindex/hostindex_test.go
When an existing route's path is updated to a new value not previously observed,
the new route state is correctly activated, but the previous route is not
replaced in the `hostRules` internal active list. Instead, the updated route
state (with a different path but duplicate UID) is appended to the active list.
A `hostRules` active list with more than one route instance sharing a UID and
host is an invalid internal state. The net effect is some unintended confusing
behavior which manifests when updating the route's path, including:
* Updating from path A->B->A preventing future transitions to B
* Updating from path A->B->A->B leaves an orphaned claim on the host in the
namespace, preventing the recreation of the route with either of the previously
observed paths until the router is …
=> Fix broken update handling of path-based routes

pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/flags.go, pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/flags_test.go
When building the command line for kube-apiserver, named certificates without explicit names defined (names are optional) result in a malformed `--tls-sni-cert-key` command line option.
=> handle named certificates with no explicit names

pkg/router/controller/hostindex/hostindex.go, pkg/router/controller/hostindex/hostindex_test.go
=> [release-3.10] Fix broken update handling of path-based routes

test/extended/router/wildcard.go, test/extended/util/test.go
Add a test which exercises:
* Wildcard DNS management
* Route host defaulting
* Default wildcard certificates
By:
* Creating a reencrypt route using only defaults
* Asserting the route is accessible over its public hostname
This test should only execute when wildcard DNS management is enabled as
indicated by the presence of an ingress domain on the cluster config resource.
=> Add default wildcard routing e2e test

vendor/k8s.io/kubernetes/test/e2e/apps/statefulset.go, vendor/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go
sync sometimes hangs with misbehaving NFS during the tests
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>
cc: @gnufied @smarterclayton
=> UPSTREAM: 69755: Use fsync instead of sync for test

test/extended/builds/pipeline_origin_bld.go
/hold pending recipe in https://github.com/openshift/jenkins/pull/767#issuecomment-458955033
=> revert 5ee0dfc; use operator installed jenkins imagestream as is

test/extended/util/framework.go
diagnostics / "just in case" delay discussed in https://github.com/openshift/cluster-samples-operator/pull/81#issuecomment-459002846 through https://github.com/openshift/cluster-samples-operator/pull/81#issuecomment-459007569
ptal
=> Give streams time for rhel content

pkg/oauthserver/oauthserver/oauth_apiserver.go
This PR adds the denyAllIdentityProvider logic from cluster-authentication-operator to oauthserver.
See this: https://github.com/openshift/cluster-authentication-operator/pull/55
When no identity providers are configured, deny all is implied. This ends up looking weird in the UI due to how `kube:admin` is wired. We need to move the logic out of the operator and directly into the OAuth server.
=> Move denyAllIdp logic from operator to oauthserver

pkg/oc/cli/admin/top/top.go
Heapster is not used in OSE 4.0. Remove the heapster config. Fixes a crash within oc using 4.0:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]      
panic: tabwriter: panic during Flush                                             
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x100cc8d]                 
goroutine 1 [running]: 
text/tabwriter.handlePanic(0xc0017aae30, 0x28944cc, 0x5)
/usr/lib/go/src/text/tabwriter/tabwriter.go:482 +0x112                           
panic(0x2514700, 0x49b9920)                                                              
/usr/lib/go/src/runtime/panic.go:513 +0x1b9                          
text/tabwriter.(*Writer).write0(0xc001151130, 0xc00005d000, 0x4, 0x80) …
```
=> oc: update oc admin top to conform to K8S 1.12

vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_sandbox_test.go
https://github.com/kubernetes/kubernetes/pull/73603
=> UPSTREAM: 73603: TestCreatePodSandbox_RuntimeClass should not expect RunPodSandbox when runtime class is not found

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go, vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status_test.go
In 3.11 and later, nodeIP determination breaks under vSphere if you have many IP addresses on a node (eg due to router HA or egress IPs)
Backport of #21807, however that is blocked waiting for the 1.12 rebase, so this could potentially be committed now...
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1666820
=> [3.11] UPSTREAM: 70805: Fix a CloudProvider-vs-nodeIP edge case

vendor/k8s.io/kubernetes/pkg/kubelet/nodestatus/setters.go, vendor/k8s.io/kubernetes/pkg/kubelet/nodestatus/setters_test.go
In 3.11 and later, nodeIP determination breaks under vSphere if you have many IP addresses on a node (eg due to router HA or egress IPs)
Backport of https://github.com/kubernetes/kubernetes/pull/70805
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1643348
=> UPSTREAM: 70805: Fix a CloudProvider-vs-nodeIP edge case

cmd/openshift-tests/openshift-tests.go
openshift-tests removed the ability to pass command line flags to e2e test, on the perf & scale team Cluster Loader is a key tool/test that exists in extended test. In order for it to be functional we need to be able to pass variable configurations into it.
@smarterclayton can you suggest someone to review/approve this, as well as any other tasks to get this in?
=> Add VIPERCONFIG env var to openshift-tests

hack/import-restrictions.json, pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_oauthserver.go, pkg/cmd/openshift-osinserver/server.go, pkg/oauthserver/oauthserver/auth.go, pkg/oauthserver/oauthserver/oauth_apiserver.go, pkg/oauthserver/server/logout/logout.go, test/integration/web_console_access_test.go
Remove dead code in OAuth server
This code path is no longer required after the 1.12 rebase.
---
Remove openshift-web-console OAuth client
This OAuth client is no longer used.  Currently the console operator
manages its own OAuth client.  AUTH-234 is tracking moving that
responsibility to the authentication operator.
Bug 1666623
---
Allow redirects to assetPublicURL from logout
This change allows the console to redirect back to itself after
logging out the kube:admin user.
AUTH-170
---
/assign @stlaz
=> Allow redirects to assetPublicURL from logout

pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
This inject openshift specific endpoints into list of allowed long running requests. Hope is that the aggregator picks this up. Only @deads2k know :-)
Fixes #21884.
=> kube-apiserver: wire long running processes

pkg/build/controller/build/build_controller.go, pkg/build/controller/build/build_controller_test.go, pkg/build/controller/strategy/util.go, pkg/build/controller/strategy/util_test.go, pkg/build/util/consts.go, pkg/cmd/openshift-controller-manager/controller/interfaces.go, test/extended/builds/cluster_config.go, test/extended/testdata/bindata.go, test/extended/testdata/builds/cluster-config.yaml, test/extended/testdata/builds/cluster-config/registry-blacklist.yaml, test/extended/testdata/builds/cluster-config/registry-search.yaml, test/extended/testdata/builds/cluster-config/registry-whitelist.yaml
Generate `registries.conf` and `policy.json` for builds from the cluster-wide config.
=> builds - Generate Registry Configurations

images/os/Dockerfile
This would take the machine-os-content base image and override it
with our changes in the PR
=> Add PR based override for machine-os-content

pkg/build/controller/strategy/util.go, pkg/build/controller/strategy/util_test.go
* Registry CAs will be stored in a ConfigMap with key format "hostname[..port]"
* hostname[..port] gets mounted in at path "certs.d/hostname[:port]"
Fixes openshift/builder#41
JIRA-ID: DEVEXP-154
=> builds - Handle port numbers in registry CA hosts

pkg/build/controller/strategy/docker.go, pkg/build/controller/strategy/docker_test.go, pkg/build/controller/strategy/sti.go, pkg/build/controller/strategy/sti_test.go, pkg/build/controller/strategy/util.go, pkg/build/util/util.go
Use `EmptyDir` to host the container blob _content_ cache, rather than relying on container storage.
=> Emptydir blob cache for builds

pkg/authorization/apiserver/admission/restrictusers/restrictusers.go, pkg/build/apiserver/admission/secretinjector/admission.go, pkg/build/apiserver/admission/strategyrestrictions/admission.go, pkg/cmd/openshift-apiserver/openshiftadmission/chain_builder.go, pkg/cmd/openshift-apiserver/openshiftadmission/config_test.go, pkg/cmd/openshift-apiserver/openshiftadmission/register.go, pkg/cmd/openshift-kube-apiserver/kubeadmission/register.go, pkg/configconversion/legacyconfig_conversion.go, pkg/image/apiserver/admission/apis/imagepolicy/name.go, pkg/image/apiserver/admission/limitrange/admission.go, pkg/project/apiserver/admission/nodeenv/admission.go, pkg/project/apiserver/admission/requestlimit/admission.go, pkg/quota/apiserver/admission/apis/clusterresourceoverride/name.go, pkg/quota/apiserver/admission/clusterresourceoverride/admission.go, pkg/quota/apiserver/admission/clusterresourceoverride/doc.go, pkg/quota/apiserver/admission/clusterresourcequota/admission.go, pkg/quota/apiserver/admission/runonceduration/admission.go, pkg/route/apiserver/admission/ingress_admission.go, pkg/scheduler/admission/podnodeconstraints/admission.go, pkg/security/apiserver/admission/sccadmission/admission.go, pkg/security/apiserver/admission/sccadmission/scc_exec.go, pkg/service/admission/externalipranger/deprecated_register.go, pkg/service/admission/externalipranger/externalip_admission.go, pkg/service/admission/restrictedendpoints/deprecated_register.go, pkg/service/admission/restrictedendpoints/endpoint_admission.go, test/integration/pod_node_constraints_test.go, test/integration/project_reqlimit_test.go, test/integration/restrictusers_test.go, test/integration/runonce_duration_test.go
All openshift admission plugins should be namespaced. Since we aren't config-compatible from 3.11 to 4.0, this is a legal change.
=> properly prefix all admission plugins

test/integration/namespace_lifecycle_admission_test.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go
Given an operator based installation, the only two namespaces that need to be protected are `openshift-config` (user defined information that we cannot recreate) and `openshift-cluster-version` (the CVO which is responsible for recreating all the rest).
/assign @derekwaynecarr @smarterclayton
=> UPSTREAM: <carry>: protect key openshift namespaces

pkg/service/admission/apis/externalipranger/install/install.go, pkg/service/admission/apis/externalipranger/register.go, pkg/service/admission/apis/externalipranger/v1/register.go, pkg/service/admission/apis/restrictedendpoints/install/install.go, pkg/service/admission/apis/restrictedendpoints/register.go, pkg/service/admission/apis/restrictedendpoints/v1/register.go
Once this merges, we'll be able to fix the operator and then remove the non-groupified version.
=> make the network admission plugins tolerate groupified config

pkg/cmd/server/origin/admission/register.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1671837
The e2e for verifying if expansion is disabled or enabled is here - https://github.com/kubernetes/kubernetes/pull/73818 . I will backport it once it merges in upstream.
=> Enable resize admission plugin by default

pkg/oc/cli/process/process.go
This is purely aesthetic, yet annoying when piped through e.g. `| oc create -f -`
Before:
```
warning: Template parameter "FOO" already defined, ignoring value from file "test.env"{
"kind": "List",
"apiVersion": "v1",
"metadata": {},
```
```
2 input templates found, but only the first will be processed{ 
"kind": "List",                                     
"apiVersion": "v1",                           
"metadata": {},
```
After:
```
warning: Template parameter "FOO" already defined, ignoring value from file "test.env"
{
"kind": "List",
"apiVersion": "v1",
"metadata": {},
```
```
2 input templates found, but only the first will be processed
{                                                              
"kind": "List",                                     
"apiVersion": "v1", …
```
=> add newline to oc process output

vendor/k8s.io/kubernetes/pkg/kubectl/cmd/drain.go, vendor/k8s.io/kubernetes/pkg/kubectl/cmd/drain_test.go
The command already supports multiple args - allow it by removing the
singleton check.
=> UPSTREAM: 68655: Allow cordon and drain of multiple nodes

vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go
This should fix dynamic nfs subpath flakes that look like https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-openshift-controller-manager-operator/68/pull-ci-openshift-cluster-openshift-controller-manager-operator-master-e2e-aws/294#openshift-tests-sig-storage-in-tree-volumes-driver-nfs-testpattern-dynamic-pv-default-fs-subpath-should-support-non-existent-path-suiteopenshiftconformanceparallel-suitek8s
it will also fix flakes in subpath tests where the pod doesn't timeout, but fails (writer container starts 10s after reader container)
=> UPSTREAM: 73318: Do writes in init container before trying reads

vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/api/meta/table/table.go
Most other printers use the new 2-3 digit precision duration, and
the generic one should also.
=> UPSTREAM: 73888: Use higher precision duration in server side print

pkg/cmd/openshift-kube-apiserver/cmd.go, pkg/cmd/openshift-kube-apiserver/configdefault/kubecontrolplane_default.go
SA token verification iterates through a list of files.  This pull allows us to specify a directory as one of the files.  This means we don't have to track individual certs which will make unioning for rotation easier.
/assign @sttts
=> allow the kube-apiserver sa token public keys to be a directory

vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector_test.go, vendor/k8s.io/kubernetes/pkg/kubectl/cmd/top_pod_test.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/cached/memcache.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/cached_discovery.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/cached_discovery_test.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/discovery_client.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/fake/discovery.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/restmapper/BUILD, vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/restmapper/discovery.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/restmapper/discovery_test.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/restmapper/shortcut_test.go
=> UPSTREAM: 73345: discovery: speedup kubectl restmapper cache misses

pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/flags.go
Since we're installing the platform on the platform, the ability to keep events for the duration of a CI run to figure out why we're in the state we're in is important.  This updates the event ttl.
/assign @sttts
=> keep events for three hours

test/integration/master_routes_test.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
A stab at https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-kube-controller-manager-operator/148/pull-ci-openshift-cluster-kube-controller-manager-operator-master-e2e-aws/636
Let's imagine this sad story.  You have an automanaged system that is trying to come up.
1. kube-apiserver completes installation, the first time, and goes available
2. openshift-apiserver installs and is not available because openapi needs aggregating
3. @sttts vastly improves openapi aggregation performance
4. openshift's openapi is aggregated really fast now so it finishes before....
5. networking completes and an cidr somewhere is updated, which feeds into a kube-apiserver admission plugin
6. CVO updates and realizes it is "done"
7. kube-apiserver goes into progressing …
=> UPSTREAM: 00000: wait for apiservices on startup

vendor/k8s.io/kubernetes/pkg/master/controller/crdregistration/crdregistration_controller.go, vendor/k8s.io/kubernetes/pkg/master/controller/crdregistration/patch.go
This coerces our "special" groups above the unwashed masses of CRs.  This makes sure that `oc edit authentication` will edit the `authentication.config.openshift.io`, not `authentication.operator.openshift.io`
@enj @benjaminapetersen fyi
=> UPSTREAM: <carry>: prioritize some CRD groups over others

vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler_test.go
this will fix flakes like https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/batch/pull-ci-openshift-origin-master-unit/2571#githubcomopenshiftoriginvendork8siokubernetespkgkubeletvolumemanagerreconciler-test_run_positive_volumemountcontrollerattachenabledrace
@tsmetana
=> UPSTREAM: 73404: Kubelet: Fix volumemanager test race

test/extended/include.go, test/extended/machines/machines.go
Adds a basic smoke test that verifies every node is referenced by a machine.
Further iterations should scope this for IPI mode on AWS only.
=> Add smoke test for machine-api

vendor/k8s.io/kubernetes/test/e2e/storage/pvc_protection.go
we want to switch the default storageclass to WaitForFirstConsumer to avoid unschedulable pods in multizone clusters https://github.com/openshift/cluster-storage-operator/pull/12 https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode . this fix is needed to make the test tolerate such a storageclass
=> UPSTREAM: 73928: Fix PVC protection e2es when default storage class is WaitForFirstConsumer

pkg/cmd/openshift-apiserver/cmd.go, pkg/cmd/openshift-controller-manager/cmd.go, pkg/cmd/openshift-kube-apiserver/cmd.go, pkg/cmd/openshift-network-controller/cmd.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/rest/config.go
By default, Kubernetes will use the `os.Args[0]` as the source for the command name in `User-Agent` string. This change will allow to override this with custom command name and set this per component name in `hypershift` binary.
That means each component will be uniquely identifiable in prometheus.
=> Set command name for user-agent in rest client per component.

test/extended/operators/operators.go
This should catch flakes or failure retries
=> e2e: Test that all operators are stable

pkg/oc/cli/admin/release/new.go
Before we were recording the increment on the new filename, not the
old one.
=> When adding the same manifest 3 or more times, prevent duplicates

Makefile, contrib/completions/bash/oc, contrib/completions/zsh/oc, hack/update-generated-versions.sh, hack/verify-generated-versions.sh, images/hyperkube/Dockerfile, pkg/oc/cli/admin/release/image_mapper.go, pkg/oc/cli/admin/release/image_mapper_test.go, pkg/oc/cli/admin/release/new.go
Many components need to track important versions in the release payload,
such as the kubernetes version they offer. This change to release
creation from image streams allows images to declare standard versions
that can then be substituted into the release payload at creation time.
Images define the versions they export via a LABEL in their dockerfile
LABEL io.openshift.build.versions=kubernetes=1.12.4,prometheus=1.3.5
Each key must be alphanumeric with interior dashes, and the value must
be a semantic version. A manifest inside an operator that references
the above image in their image-references can have the following strings
in their manifest substituted:
0.0.1-snapshot-kubernetes -> 1.12.4
0.0.1-snapshot-prometheus -> 1.3.5
An additional global reference is supported for the payload …
=> release: Allow version strings to be replaced during release creation

pkg/oc/cli/image/append/append.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1662088
cc @soltysh @smarterclayton
=> add "pull" action to docker registry client context

vendor/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go
Currently, the glusterfs e2e test is using the default storageclass (aws) instead of the glusterfs one it's supposed to be testing. This patch fixes that & unblocks https://github.com/openshift/cluster-storage-operator/pull/12 because the test in its current state can't tolerate a storageclass with WaitForFirstConsumer
see also https://github.com/openshift/origin/pull/22048
=> UPSTREAM: 73962: Fix glusterfs e2e not using correct storageclass 

test/extended/bootstrap_user/bootstrap_user_login.go
Other PRs are investigating fixes but we don't have a fix right now.
=> Mark the bootstrap user test flaky because it does not pass

pkg/router/controller/host_admitter.go, pkg/router/controller/host_admitter_test.go
As part of the resync processing, wildcard routes get a "HostAlreadyClaimed"
error and then later as part of the same event processing flow, the route gets re-added.
This results in a temporary outage (route returns 503s).
fixes #1660647 (https://bugzilla.redhat.com/show_bug.cgi?id=1660647)
@openshift/sig-network-edge  PTAL Thx
*Edited* clarified route gets added in the same event processing flow.
=> Fix issue where wildcard routes get 503s intermittently.

pkg/router/controller/host_admitter.go, pkg/router/controller/host_admitter_test.go
Couldn't cherrypick from #22087  due to conflicts in the unit test file (import package name changes), so this is a new PR. Code fixes are the same.
As part of the resync processing, wildcard routes get a "HostAlreadyClaimed"
error and then later as part of the same event processing flow, the route
gets re-added. This results in a temporary outage (route returns 503s).
fixes #1660647 (https://bugzilla.redhat.com/show_bug.cgi?id=1660647)
@openshift/sig-network-edge  PTAL Thx
=> [Backport-3.10] Fix issue where wildcard routes get 503s intermittently.

pkg/oauthserver/oauth/external/google/google.go, pkg/oauthserver/oauth/external/google/google_test.go, pkg/oauthserver/oauthserver/auth.go
This change adds glog level based request and response logging to all HTTP communication performed by IDPs.  This will greatly aid in debugging failures related to IDPs.
Note that this does not cover the LDAP and RequestHeader IDPs.  LDAP will require inspection at the net.Conn level.  RequestHeader will require upstream changes (primarily to add logging around x509
errors).
AUTH-167
=> Wrap IDP transports with DebugWrappers

contrib/vagrant/provision-minimal.sh
Restores CI for source-to-image until we switch to ci-operator.
=> Restore contrib/vagrant/provision-minimal.sh

pkg/admission/customresourcevalidation/console/OWNERS, pkg/admission/customresourcevalidation/console/validate_console.go, pkg/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
@spadgett @enj fyi
This is just a stub, but should get us parsing & a single config named `cluster`.  That's a win, we can follow with additional validation.
=> Add stub for console config validation

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/server_run_options.go
This is meant to delay the apiserver shutdown for a defined time duration in order to give the SDN a chance to update changed endpoints.
The reconciler is part of the "master controller", also called "bootstrap controller". It has a pre shutdown hook triggered by the `stopCh`. We delay the `internalStopCh` being closed which triggers to stop serving. So this looks good.
=> UPSTREAM: 74416: apiserver: add --minimal-shutdown-duration to delay until endpoint convergence

vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/client-gen/generators/client_generator.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/informer-gen/generators/generic.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/informer-gen/generators/packages.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/lister-gen/generators/lister.go
our generated dns client is wrong:
`E0221 21:15:01.517722       1 reflector.go:134] github.com/openshift/client-go/config/informers/externalversions/factory.go:101: Failed to list *v1.DNS: the server could not find the requested resource (get dnss.config.openshift.io)
`
/assign @sttts
=> UPSTREAM: <carry>: handle pluralization of dnses

pkg/oc/lib/tokencmd/request_token.go, pkg/oc/lib/tokencmd/request_token_test.go
This is a better check to perform than HEAD /oauth/token/implicit as it does not assume anything about the OAuth server (which could be Keycloak and not Osin).
xref: https://github.com/openshift/console/pull/1216
=> oc login: HEAD issuer for x509 cert check

images/tests/Dockerfile, images/tests/Dockerfile.rhel
This image is primarily intended for running the test suite against an external cluster, but it's also a convenient place to collect the tools needed to retrieve and store logs extracted from those tested clusters.  If the inspection dependencies become too onerous, we might want to split them out into their own image, but for now it seems easier to overload tests.
It's not clear to me why only the RHEL Dockerfile lists `util-linux`, which it has since 228e3f56 (#22065), but I've left that part alone.
This is a pre-req for openshift/release#2911.
=> images/tests/Dockerfile*: Install gzip for compressing logs

vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux_test.go
Allow unit tests to run against a TMPDIR that is a Kube EmptyDir and memory backed (kube sets sticky gid on volumes).
=> UPSTREAM: 74478: Ignore sticky gid filemode bit on unit test

vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/metrics.go
We picked the commit introducing these metrics before. And we might have alerts defined (remembering some aos-devel communication with @derekwaynecarr).
=> UPSTREAM: 74244: kube-aggregator: fix typo aggregator_unavailable_api{server -> service}_gauge

pkg/network/node/networkpolicy.go
In clusters with lots of podSelector-based NetworkPolicies, some changes (like redeploying a Deployment) can result in spamming OVS with flow updates (as we rewrite the entire namespace's worth of flows once for each pod that changes). In some cases this can result in blah blah PLEG blah blah and the Node becoming NotReady.
This changes it to use the same code kube-proxy uses to limit the rate of updates. Further improvements to this are possible, but this is enough to fix the Node NotReady status.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1656805
=> Use BoundedFrequencyRunner to limit the rate of NetworkPolicy updates

pkg/build/controller/build/defaults/defaults_test.go, pkg/build/util/consts.go
Add the following default proxy env vars to the whitelist:
- HTTP_PROXY
- HTTPS_PROXY
- NO_PROXY
Also updates tests for the application of the default proxy env vars
to the source, docker, and custom build strategies.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1677585
=> Add default proxy env vars to whitelist and update tests

vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go, vendor/k8s.io/kubernetes/pkg/proxy/service.go, vendor/k8s.io/kubernetes/pkg/proxy/types.go, vendor/k8s.io/kubernetes/pkg/util/conntrack/conntrack.go, vendor/k8s.io/kubernetes/pkg/util/conntrack/conntrack_test.go
https://github.com/kubernetes/kubernetes/pull/71573
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1537780
=> UPSTREAM: 71573  Correctly Clear conntrack entry on endpoint changes when using nodeport

test/integration/master_routes_test.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go
A kube-apiserver can report healthy before it is able to serve CRD requests for all the CRDs already registered. We cannot eliminate the race for new types being added after a server is up, but we can be sure we have a view of the world that is consistent with a particular resourceVersion. This pull adds a health check to do that
=> UPSTREAM: 74532: CRD server wait for CRDs to sync before reporting healthy

images/os/Dockerfile
Instead of using the SELinux policy of whatever is in the buildroot
(right now, Fedora 29), we should always be using the policy of the base
tree on top of which we're overlaying.
=> Build OSTree using baked SELinux policy

pkg/oc/cli/debug/debug.go
Now that input can vary by output host, move setting this value into approximatePodForObject.
=> NodeName was being cleared for `oc debug node/X` instead of set

vendor/k8s.io/kubernetes/pkg/printers/internalversion/printers.go
Makes it much easier to read events.
```
119m   Normal    SuccessfulDelete         cronjob/image-mirror-origin-v3.11-quay                Deleted job image-mirror-origin-v3.11-quay-1550088000
60m    Normal    SuccessfulCreate         cronjob/image-mirror-origin-v3.11-quay                Created job image-mirror-origin-v3.11-quay-1550095200
59m    Normal    SawCompletedJob          cronjob/image-mirror-origin-v3.11-quay                Saw completed job: image-mirror-origin-v3.11-quay-1550095200
59m    Normal    SuccessfulDelete         cronjob/image-mirror-origin-v3.11-quay                Deleted job image-mirror-origin-v3.11-
```
=> UPSTREAM: 73894: Print the involved object in the event table

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_discovery_controller.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go
Working version of https://github.com/openshift/origin/pull/22146
=> UPSTREAM: 00000: wait for CRD discovery to be successful once before

vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator.go
We don't have to encode two times for /openapi/v2 and /swagger.json. In upstream master the latter is gone already due to deprecation in 1.10.
=> UPSTREAM: <carry>: openapi: half encoding costs

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/audit/request.go
this fixes metadata gathering for audit for custom resources
=> UPSTREAM: 74617: make audit metadata work for custom resources

pkg/oc/cli/admin/release/git.go
Found this when I actually started adding tests and trying to use it.
`--git-dir=PATH/.git` is the replacement.
=> Git 1.8.1 (default in el7) does not support `-C`

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go
Retrying should prevent these errors and API server start failures:
`
F0227 10:32:31.605070       1 hooks.go:188] PostStartHook "crd-discovery-available" failed: unable to retrieve the complete list of server APIs: autoscaling.openshift.io/v1alpha1: the server could not find the requested resource, cloudcredential.openshift.io/v1beta1: the server could not find the requested resource,....
`
Fixes: https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.0/4888/
/cc @deads2k
=> UPSTREAM: 0000: retry on discovery errors in crd-discovery-available post-start hook

pkg/oc/cli/debug/debug.go
I had trouble with this command and this help text would have aided me.  See https://github.com/openshift/origin/pull/21997#issuecomment-463208050
@sjenning is the phrasing correct?
=> add some advice to 'oc debug' for debugging nodes

pkg/oc/cli/admin/top/top.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1470006
=> Bug 1470006 - Replace all kubectl in oc adm top pod/node examples

vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
https://bugzilla.redhat.com/show_bug.cgi?id=1669560
https://github.com/kubernetes/kubernetes/pull/74306
=> [3.11] UPSTREAM: 74306: Fix scanning of failed targets

vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
https://bugzilla.redhat.com/show_bug.cgi?id=1680012
https://github.com/kubernetes/kubernetes/pull/74306
=> [4.0] UPSTREAM: 74306: Fix scanning of failed targets

cmd/hypershift/main.go, cmd/openshift-integrated-oauth-server/OWNERS, cmd/openshift-integrated-oauth-server/main.go, hack/import-restrictions.json, hack/lib/constants.sh, pkg/cmd/openshift-integrated-oauth-server/OWNERS, pkg/cmd/openshift-integrated-oauth-server/cmd.go, pkg/cmd/openshift-integrated-oauth-server/server.go, pkg/oauthserver/oauthserver/auth.go
This serves as the official standalone binary run by the cluster-authentication-operator when it is managing the integrated OAuth server.
=> Add openshift-integrated-oauth-server command

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder_test.go, vendor/k8s.io/kubernetes/test/e2e/apimachinery/crd_publish_openapi.go
https://github.com/soltysh/origin/pull/30 was incomplete as it added TypeMeta/ObjectMeta to openapi schemas of CRDs even if they have no validation schema set. This fixes this and adds tests.
=> apiextensions: openapi ObjectMeta/TypeMeta schema only if validation spec is given

vendor/k8s.io/kubernetes/pkg/volume/iscsi/BUILD, vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go
Upstream issue: https://github.com/kubernetes/kubernetes/issues/74523
Upstream PR: https://github.com/kubernetes/kubernetes/pull/74524
/sig storage
/assign @jsafrane @wongma7 @gnufied
=> [4.0] UPSTREAM: 74524: Don't fail if iface is being used by iSCSI session

vendor/k8s.io/kubernetes/pkg/util/reflector/prometheus/prometheus.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/reflector.go
Picks the kubelet memory leak fix from upstream.
/cc @derekwaynecarr @sjenning 
ref: https://github.com/kubernetes/kubernetes/issues/73587
ref: https://github.com/kubernetes/kubernetes/pull/74636
=> UPSTREAM: 74636: Remove reflector metrics as they currently cause a memory leak

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_discovery_controller.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go
Also get rid of wrong upstream carry.
Compare https://github.com/kubernetes/kubernetes/pull/74587#issuecomment-468183531.
=> apiextensions-apiserver: fix empty APIResource group+version handling in wait logic

pkg/cmd/openshift-integrated-oauth-server/cmd.go
Both the hypershift and openshift-integrated-oauth-server binaries are expected to use this struct now.
/hold
/assign @stlaz 
This requires https://github.com/openshift/cluster-authentication-operator/pull/79
=> Require OsinServerConfig in OAuth server binary

pkg/oc/cli/admin/release/extract.go, pkg/oc/cli/admin/release/git.go, pkg/oc/cli/admin/release/image_mapper.go, pkg/oc/cli/admin/release/new.go
Otherwise we lose image-references data when you try to rebuild from disk
=> Write image-references to disk after all metadata is fetched

vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go, vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/recycle_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1663149
This is already fixed in 3.9 and newer, so in order not to regress we should have it in 4.0.
=> UPSTREAM: 70580: PV Controller: fix recycling

contrib/systemd/origin-accounting.conf
https://github.com/openshift/origin/pull/14644 added IO accounting for systemd.
Unfortunately, the systemd version in RHEL doesn't understand `DefaultIOAccounting` (yet) and fails to apply any part of the config file, leading to this issue https://bugzilla.redhat.com/show_bug.cgi?id=1623261
`DefaultBlockIOAccounting` is what RHEL understands.
@derekwaynecarr @smarterclayton @sdodson @RobertKrawitz
=> contrib: systemd: fix systemd accounting

pkg/oc/lib/describe/describer.go
Fix https://bugzilla.redhat.com/show_bug.cgi?id=1278683
Apply a limit to a project, then describe the limit and describe the project, output different values for the limit.
The content of the limit,
```
$ oc describe limits resource-limit
......
Type        Resource  Min   Max  Default Request  Default Limit  Max Limit/Request Ratio
----        --------  ---   ---  ---------------  -------------  -----------------------
Container   cpu       100m  2    200m             300m           10
Container   memory    4Mi   1Gi  100Mi            200Mi          -
```
**Before**
```
......
Type		Resource	Min	Max	Default	Limit	Limit/Request
----		--------	---	---	---	-----	-------------
Container	cpu		100m	2	300m	300m	10
Container	memory		4Mi	1Gi	200Mi	200Mi	-
```
**After**
```
......
Type		Resource …
```
=> Fix bug 1278683

pkg/openapi/zz_generated.openapi.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/fuzzer/fuzzer.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation_test.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/validation/validation.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/validation/validation_test.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/conversion.go
Backport of https://github.com/kubernetes/kubernetes/pull/74804
Empty `RawExtensions` render to null, same for zero-valued timestamps (like in ObjectMeta).
=> UPSTREAM: 74804: apiextensions: add nullable support to OpenAPI v3 validations

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/BUILD, vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go, vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_test.go
Solves "Allow to override default AWS endpoint" by merging in upstream fix kubernetes/kubernetes#72245.
Add several new properties to AWS CloudConfig to support custom endpoints.
Initialize/Parse on aws.go init() method which gets called when aws is loaded.
Allows overridden endpoints per servce and region. This allows functionality on air gapped networks.
This change is benign if services are not overridden in CloudConfig
=> UPSTREAM: 72245: Add AWS Custom Endpoint capability

pkg/cmd/openshift-apiserver/cmd.go
I tracked the rouge openshift apiserver storage that makes 50k+ SAR requests using JSON client instead of protobuf.
The only case I found that does not apply the override with protobuf seems to be legacy config.
=> openshift-apiserver: set openshift apiserver config defaults for legacy config

pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_authenticator.go, vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go, vendor/k8s.io/kubernetes/cmd/kubelet/app/auth.go, vendor/k8s.io/kubernetes/pkg/kubeapiserver/authenticator/config.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/authentication/authenticatorfactory/delegating.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/clientca.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/dynamic.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/serving.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config_selfclient.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamic_certificate_test.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/hooks.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/authentication.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/serving.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/serving_test.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/serving_with_loopback.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/testing/certs.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/secure_serving.go
I understand how the configForClient function works now.  I've updated the code to use it and provided a way to have the authenticators reload.
I still need to wire the aggregator for reloading, but I think I can force that based on a value change with another patch.
=> Support reloading CA files

pkg/network/node/networkpolicy.go
So there were three bugs here:
1. In most cases, deleting a namespace that had previously been in use on the node would leave behind a single flow (`table=80, priority=50, reg1=XXXX, actions=output:NXM_NX_REG2[]`), because that's what would have been left after all of the NetworkPolicies were auto-deleted before the Namespace was fully deleted, and we weren't doing any further cleanup when the Namespace/NetNamespace itself was deleted.
2. Post-#22106 there might also be additional flows left behind because the processing of the NetworkPolicy deletions would end up being delayed, but the `np.namespaces` entry would have been deleted before `np.syncFlows()` got a chance to run the last time, so it would no longer know to finish cleaning up that namespace. (Because of this we should probably …
=> properly delete NetworkPolicies when deleting their namespace

hack/lib/constants.sh
Saves ~15% on binary size for commonly accessed images. If we have
a future use case for debugging we could consider adding an optional
flag.
=> Strip binaries by default, debug use is not common

vendor/k8s.io/kubernetes/test/e2e/framework/util.go
Ignore these resources in the test to reduce confusing output
=> UPSTREAM: 72376: Filter resources logged by e2e ns debugging

test/extended/util/test.go
OpenShift uses /var/lib/kubelet now. This should fix SELinux test failures like [this](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22143/pull-ci-openshift-origin-master-e2e-aws/4962#openshift-tests-k8sio-sig-node-security-context-featuresecuritycontext-should-support-volume-selinux-relabeling-suiteopenshiftconformanceparallel-suitek8s):
```
openshift-tests [k8s.io] [sig-node] Security Context [Feature:SecurityContext] should support volume SELinux relabeling [Suite:openshift/conformance/parallel] [Suite:k8s]
...
STEP: Creating a pod to test Pod with same MCS label reading test file
Feb 26 06:15:12.138: INFO: Waiting up to 5m0s for pod "security-context-dfe4d89b-398d-11e9-ab76-0a58ac10f523" in namespace "e2e-tests-security-context-nfscc" to be "success or …
```
=> Don't override kubelet volume path

pkg/security/apiserver/admission/sccadmission/admission.go
The SCC admission plugin logs & returns an error that says "unable to
validate against any pod security policy". The correct error message
should be "unable to validate against any security context constraint",
since it's checking SCCs, not PSPs.
=> Fix incorrect validation message in sccadmission (replace psp with scc)

pkg/network/node/networkpolicy.go
Backport of #22158; since #22106 makes this problem worse, we should backport the fix to all of the releases we backported #22106 to.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1686025
=> [3.11] properly delete NetworkPolicies when deleting their namespace

vendor/k8s.io/kubernetes/pkg/generated/openapi/zz_generated.openapi.go
We create the openapi spec in vendor/k8s.io/kubernetes/pkg/generated/openapi/zz_generated.openapi.go manually during rebase. Upstream does not check it in. I.e. any carry patch will never update it.
The one in pkg/openapi/zz_generated.openapi.go plays no role for kube-apiserver.
In https://github.com/openshift/origin/pull/22202, the later was updated, the former was not.
=> Fixing openapi spec

pkg/admission/namespaceconditions/decorator.go, pkg/quota/apiserver/admission/clusterresourcequota/admission.go
We respected admission in `default` because we had legacy components relying on it, but no pods should be created in there now that require SCC values set.
See https://github.com/openshift/origin/pull/19457
/assign @enj
=> skip openshift admission on default namespace

pkg/cmd/util/cmd.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1558935
=> Bug 1558935 - Replace kubectl name in long description of oc commands

pkg/autoscaling/admission/clusterresourceoverride/admission.go, pkg/autoscaling/admission/clusterresourceoverride/admission_test.go, pkg/autoscaling/admission/runonceduration/admission.go, pkg/autoscaling/admission/runonceduration/admission_test.go, pkg/cmd/openshift-kube-apiserver/kubeadmission/register.go, pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go, pkg/cmd/server/admission/init.go, pkg/cmd/server/admission/types.go, pkg/image/apiserver/admission/imagepolicy/imagepolicy.go, pkg/image/apiserver/admission/imagepolicy/imagepolicy_test.go, pkg/project/apiserver/admission/requestlimit/admission.go, pkg/project/apiserver/admission/requestlimit/admission_test.go, pkg/project/cache/cache.go, pkg/scheduler/admission/nodeenv/admission.go, pkg/scheduler/admission/nodeenv/admission_test.go
The kube-apiserver should avoid deps on openshift resources as much as possible.  This removes usage of the project cache from kube admission plugins.
=> remove admission dependencies on project cache

pkg/cmd/openshift-kube-apiserver/kubeadmission/register.go
Looks like an oversight during admission rewiring. There is no project request limit to secure.
/assign @enj @mfojtik
=> project admission isn't required on the kube-apiserver

pkg/cmd/openshift-kube-apiserver/kubeadmission/register.go
Bug 1684344: rolebindingrestriction for 4.x
Cause: 4.x did not support configuring the rolebindingrestriction admission plugin
Consequence: No way to turn on RestrictSubjectBindings admission plugin
Fix: Turn on the RestrictSubjectBindings admission plugin by default
Result: No change in behavior for those not utilizing the plugin. Ability to create SubjectBindingRestrictions for those who do in 4.x.
=> fix(kubeadmission): turn RestrictSubjectBindings admission plugin on by default

vendor/k8s.io/kubernetes/pkg/kubelet/qos/BUILD, vendor/k8s.io/kubernetes/pkg/kubelet/qos/policy.go, vendor/k8s.io/kubernetes/pkg/kubelet/qos/policy_test.go
@derekwaynecarr 
To help with https://github.com/openshift/cluster-network-operator/pull/80 by allowing containers in a pod that has system-critical priority to get the same `oom_score_adj` that Guaranteed pods do without having to specify memory limits.
=> UPSTREAM: 73758: kubelet: set low oom_score_adj for containers in critical pods

vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/config/testdata/conversion/master/internal.yaml, vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/config/testdata/conversion/master/v1alpha2.yaml, vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/config/testdata/conversion/master/v1alpha3.yaml, vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/config/testdata/defaulting/master/defaulted.yaml, vendor/k8s.io/kubernetes/pkg/kubelet/apis/config/v1beta1/defaults.go
Reference https://github.com/kubernetes/kubernetes/pull/74842 (Kubernetes 1.12 backport)
=> UPSTREAM: 74755: Revert kubelet to default to ttl cache secret/configmap

vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/client-gen/generators/client_generator.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/informer-gen/generators/generic.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/informer-gen/generators/packages.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/lister-gen/generators/lister.go
FeaturesList and DNSList are not being pluralized correctly within the code generator. This patch adds the two objects to the pluralExceptions.
/cc @deads2k @sjenning
=> code-generator: add FeaturesList and DNSList to pluralExceptions

pkg/test/ginkgo/status.go
Upgrade tests only have one ginkgo top level test and duplicating
the monitor output inside the test is redundant with the overall
test and the conditions.
=> Suppress monitor output per test when only running a few tests

pkg/oc/cli/admin/release/git.go, pkg/oc/cli/admin/release/info.go
It's possible the repo isn't in the list of remotes, so do a direct
fetch instead.
=> release: Fetch the target repo instead of '--all'

cmd/openshift-tests/upgrade.go, test/e2e/upgrade/upgrade.go
https://openshift-gce-devel.appspot.com/builds/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade-4.0/
The suite defaults to 15m
=> Increase the upgrade suite timeout longer

pkg/apps/controller/deploymentconfig/deploymentconfig_controller.go
Seeing couple thousand of: `I0311 07:48:49.801055       1 deploymentconfig_controller.go:500] Error syncing deployment config e2e-test-cli-deployment-tlfw9/deployment-simple: Operation cannot be fulfilled on deploymentconfigs.apps.openshift.io "deployment-simple": the object has been modified; please apply your changes to the latest version and try again` in log.
Since these are always retried, we can mute the glog and move these to loglevel 5.
=> deploymentconfig: log update conflicts using higher log level in controller

contrib/systemd/origin-accounting.conf
master PR (doesn't matter against 4.x really) https://github.com/openshift/origin/pull/21138
https://github.com/openshift/origin/pull/14644 added IO accounting for systemd.
Unfortunately, the systemd version in RHEL doesn't understand `DefaultIOAccounting` (yet) and fails to apply any part of the config file, leading to this issue https://bugzilla.redhat.com/show_bug.cgi?id=1623261
`DefaultBlockIOAccounting` is what RHEL understands.
@derekwaynecarr @smarterclayton @sdodson
=> [3.11] contrib: systemd: fix systemd accounting

vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/examples/fake-client/main_test.go
backport of https://github.com/kubernetes/kubernetes/pull/74969
Fixes: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/batch/pull-ci-openshift-origin-master-unit/3803#githubcomopenshiftoriginvendork8sioclient-goexamplesfake-client-testfakeclient
/cc @sttts @mfojtik
=> Fix example flake

test/extended/builds/start.go
Ensure the openshift-builder version is reported when verbose build logs are enabled.
=> Bug 1682978: Verify builder version is reported

pkg/network/node/node.go
Log a message both before and after the CNI config file is written, so
we can be sure of when the plugin notifies kubelet that it is ready.
@pecameron @weliang1 @squeed @JacobTanenbaum @danwinship
=> sdn: clarify SDN startup log message

vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_image.go, vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_image_test.go, vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/libdocker/fake_client.go
https://github.com/kubernetes/kubernetes/pull/70647
xref https://bugzilla.redhat.com/show_bug.cgi?id=1647348
=> UPSTREAM: 70647: Always run untag when removing docker image

pkg/oc/cli/debug/debug.go
Bash shouldn't be necessary, and PATH was confusing to a user who
didn't understand the concept of chroot.
=> Simplify the host root message

Makefile
This is a followup from https://github.com/openshift/origin/pull/22218. @smarterclayton we need to build `hypershift` command, I wonder how your PR merged since it's required for test-cmd. This brings back only the `hypershift` portion back, ptal.
=> Add build-all target to Makefile

pkg/cmd/openshift-kube-apiserver/kubeadmission/register.go
Without this, the CRD validation admission plugins are disabled and not used.
/cc @deads2k
=> kube-apiserver: delete CRD validation from default off plugin list

pkg/network/node/multitenant.go, pkg/network/node/networkpolicy.go, pkg/network/node/ovscontroller.go, pkg/network/node/ovscontroller_test.go
In the case where we have to recreate the OVS bridge and then reattach pods to it, the NetworkPolicy initialization code was initializing its namespace `inUse` fields based on what the state of the *old* OVS bridge would have been rather than the state of the *new* OVS bridge (which would have no policy-related rules yet). As a result, when the pods were reattached, it would think that it had already created the policy rules for their namespaces, even though it hadn't, and so there would never end up being rules for those namespaces, and so traffic to the reattached pods would get dropped.
This fixes it by initializing the `inUse` fields based on what's actually in OVS (which means it will work correctly in both the recreating-the-bridge case and the not-recreating-the-bridge case).
(It …
=> OVS flows go missing during upgrade

vendor/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations/BUILD, vendor/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go, vendor/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go, vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go, vendor/k8s.io/kubernetes/pkg/volume/util/types/types.go
Fixes flake associated with unmount operation. This would in general result in quicker mount and unmount operations across all calls.
=> UPSTREAM: 75213: Make mount and unmount op. have different name

pkg/network/node/networkpolicy.go
This reverts #22251:
- The code has needed at least one fixup in master (#22302)
- The corresponding 3.10 PR (#22252) never passed CI. While I wasn't able to figure out why due to lack of logs in the 3.10 CI artifacts, it seemed to pretty reliably fail with this patch and pass without it.
- Although it's nice to clean things up properly right away, the hourly `SyncVNIDRules` run will clean things up eventually anyway, so the problem is merely that "at any given time there are some unused OVS flows", not "unused OVS flows keep piling up forever" like I'd originally though.
(Note that this is reverting a change that never made it into an errata release.)
=> Revert NetworkPolicy cleanup

pkg/oc/cli/admin/release/image_mapper.go, pkg/oc/cli/admin/release/new.go, pkg/oc/cli/image/mirror/mirror.go
When we clarified reference modes to support OCP preserving quay inputs and
fixed versions, we lost the remapping that ensured the mirror destination
is what is in the payload. Refactor the rewriting so that even without a
payload, we remap the pull locations after mirror.
Fix mirroring schema1 to schema2 images
=> Mirroring a new payload should rewrite payload image references

pkg/cmd/openshift-controller-manager/controller/unidling.go, pkg/oc/cli/idle/idle.go, pkg/unidling/controller/unidling_controller.go, pkg/unidling/controller/unidling_controller_test.go, pkg/unidling/util/scale.go
/assign @derekwaynecarr 
@derekwaynecarr we need an owner.
=> switch unidling to external API

pkg/cmd/openshift-apiserver/openshiftapiserver/config.go, pkg/cmd/openshift-apiserver/openshiftapiserver/project.go, pkg/project/apiserver/apiserver.go, pkg/project/apiserver/registry/project/proxy/proxy.go, pkg/project/apiserver/registry/project/proxy/proxy_test.go, pkg/project/auth/cache.go, pkg/project/auth/cache_test.go, pkg/project/auth/watch.go, pkg/project/auth/watch_test.go, pkg/project/util/util.go, pkg/project/util/util_test.go
=> switch project auth cache to external types

pkg/scheduler/admission/nodeenv/admission.go, pkg/scheduler/admission/nodeenv/admission_test.go
/assign @ravisantoshgudimetla 
@openshift/sig-pod
=> switch scheduling.openshift.io/OriginPodNodeEnvironment to external client

pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go, pkg/quota/apiserver/admission/clusterresourcequota/accessor.go, pkg/quota/apiserver/admission/clusterresourcequota/accessor_test.go, pkg/quota/apiserver/admission/clusterresourcequota/admission.go, pkg/quota/apiserver/apiserver.go, pkg/quota/apiserver/registry/appliedclusterresourcequota/filter.go
=> switch quota to external clients

pkg/oc/cli/rollout/latest.go, pkg/oc/cli/rsh/rsh.go, pkg/oc/cli/rsync/forwarder.go, pkg/oc/cli/set/volume.go, pkg/oc/cli/set/volume_test.go
=> switch oc to external clients where possible

pkg/authorization/apiserver/admission/restrictusers/restrictusers.go, pkg/authorization/apiserver/admission/restrictusers/restrictusers_test.go, pkg/authorization/apiserver/admission/restrictusers/subjectchecker.go, pkg/authorization/apiserver/admission/restrictusers/subjectchecker_test.go
=> use external clients for authorization admission

pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go, pkg/project/apiserver/apiserver.go, pkg/project/apiserver/registry/projectrequest/delegated/delegated.go, pkg/project/apiserver/registry/projectrequest/delegated/delegated_test.go
=> remove internal types from projectrequest

pkg/image/apiserver/apiserver.go, pkg/image/apiserver/registry/imagesecret/rest.go, pkg/image/apiserver/registry/imagesecret/rest_test.go
@openshift/sig-developer-experience
=> switch image rest API to external client

pkg/authorization/apiserver/registry/clusterrole/proxy.go, pkg/authorization/apiserver/registry/clusterrolebinding/proxy.go, pkg/authorization/apiserver/registry/role/proxy.go, pkg/authorization/apiserver/registry/rolebinding/proxy.go, pkg/authorization/apiserver/registry/util/convert.go, pkg/build/apiserver/admission/secretinjector/admission.go, pkg/client/impersonatingclient/impersonate.go, pkg/client/impersonatingclient/impersonate_rbac.go, test/integration/authorization_rbac_proxy_test.go
The conversion code now has extra hops from:
rbac v1 -> rbac internal -> authorization internal
authorization internal -> rbac internal -> rbac v1
The "rbac v1" hops were introduced in this change.
---
Update impersonating client to use external clients
---
Restore authorization to RBAC proxy test
This test was removed in b93335cf0e36985a864db01e860858bad0645dfa as part of the removal of all oapi related code.  The functionality this test checks is not related to oapi (even though the original version of the test explicitly used the oapi endpoints).  The updated test does not rely on any internal clients.
---
=> Update authorization to RBAC proxy registry to use external clients

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/BUILD, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/waitgroup.go
First commit will cause the client-go to retry after it get "apiserver is shutting down error".
Second commit will make the error structured (metav1.Status) and it change the error code from 500 to 503.
NOTE: This is not fixing the reason why we see that much apiserver shutting down errors. These errors should be rare and there is probably bug in shutdown order that is causing them.
picks: https://github.com/kubernetes/kubernetes/pull/75368
/cc @deads2k 
/cc @sttts
=> UPSTREAM: 75368: handle apiserver is shutting down errors

vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go, vendor/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go, vendor/k8s.io/kubernetes/pkg/proxy/service.go, vendor/k8s.io/kubernetes/pkg/proxy/types.go
This brings in two Upstream commits to clear conntrack entries for externalIP addresses
fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1632192
https://bugzilla.redhat.com/show_bug.cgi?id=1679260
=> [release-3.11] Clear conntrack entries for externalIPs 

images/sdn/Dockerfile.rhel
QE needs to test openvswitch 2.11.0 for possible inclusion in OpenShift 4.0
=> SDN test image for QE testing with ovs-2.11.0

vendor/k8s.io/kubernetes/pkg/kubelet/cm/pod_container_manager_linux.go
backport of https://github.com/openshift/origin/pull/20596
fix pods launching in a dind cluster
=> [release 3.11] UPSTREAM: 66617: Do not set cgroup parent when --cgroups-per-qos is disabled

vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go, vendor/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go, vendor/k8s.io/kubernetes/pkg/proxy/service.go, vendor/k8s.io/kubernetes/pkg/proxy/types.go
This brings in two Upstream commits to clear conntrack entries for externalIP addresses
fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1632192
https://bugzilla.redhat.com/show_bug.cgi?id=1679260
=> [release-3.10] Clear conntrack entries for externalIPs 

cmd/sdn-cni-plugin/openshift-sdn_linux.go, cmd/sdn-cni-plugin/sdn_cni_plugin_test.go, pkg/network/node/node.go, pkg/network/node/pod.go
This PR makes openshift-sdn support CNI version 0.3.0 and 0.3.1, which allows openshift-sdn to be used with additional CNI plugins (plugin chaining). 
Fixes https://github.com/openshift/origin/issues/21891
=>  Support CNI 0.3.x in openshift-sdn

test/integration/authorization_rbac_proxy_test.go
This change adds a test that exercises the authorization to RBAC proxy to make sure that escalation is not possible.  This confirms that the internal impersonation code is working.  It also checks to make sure that the group resource returned matches the authorization resource (and not the proxied RBAC resource).
=> Confirm escalation is not possible via authorization to RBAC proxy

pkg/oc/cli/admin/release/new.go
elasticsearch-operator broke the payload by force merging but
the images job should have failed with a clear verification error
that the payload was not correct.
=> Check the payload for real Kube objects before accepting

pkg/oauthserver/authenticator/identitymapper/identitymapper.go, pkg/oauthserver/authenticator/password/allowanypassword/anyauthpassword.go, pkg/oauthserver/authenticator/password/basicauthpassword/basicauthpassword.go, pkg/oauthserver/authenticator/password/htpasswd/htpasswd.go, pkg/oauthserver/authenticator/password/keystonepassword/keystonepassword.go, pkg/oauthserver/authenticator/password/ldappassword/ldap.go, pkg/oauthserver/authenticator/request/headerrequest/requestheader.go, pkg/oauthserver/oauth/external/handler.go
This change reduces some code duplication related to the bridge code between the UserIdentityMapper and kube authenticator interfaces.
xref: https://github.com/openshift/origin/pull/22363#discussion_r267016511
/assign @stlaz
=> Refactor UserFor helper to ResponseFor

pkg/oc/cli/admin/release/extract.go, pkg/oc/cli/admin/release/git.go, pkg/oc/cli/admin/release/info.go
When comparing between a public and private repo the repo URL might
change but the commits may be compatible. Add the alternate as an
upstream and fetch on demand.
=> Fetch alternate repos for commits on release extraction

hack/verify-upstream-commits.sh
fixes failures due to bad commit in the branch history https://github.com/openshift/origin/pull/22177/commits/709eb6f499a4d5b59f094c5ad458e7724a6c9a65
@sdodson @derekwaynecarr @smarterclayton @stevekuznetsov
=> [3.11] hack: make verify commits work against correct branch

test/extended/operators/images.go
Validate that any pod run in kube-* or openshift-* namespace only uses images from our release image.
Validate that all pod containers in the above namespaces have image pull policy of IfNotPresent.
=> extended: validate release image used and image pull policy

vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go, vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml
This way the ELB can access /readyz without authentication.
=> bootstrap-policy: add /readyz to system:discovery

test/extended/operators/images.go
Update test to exit if unable to read release payload while we sort out authentication issue.
=> extended: exit early if unable to read release payload

images/sdn/Dockerfile.rhel, images/sdn/scripts/ip6tables, images/sdn/scripts/ip6tables-restore, images/sdn/scripts/ip6tables-save, images/sdn/scripts/iptables, images/sdn/scripts/iptables-restore, images/sdn/scripts/iptables-save
In order to use the hosts versions of the iptables command scripts are added to replace the containerized versions to point to the versions in the host.
https://github.com/openshift/cluster-network-operator/pull/127 needs to merge first so the hosts iptables will be mounted in
=> change the sdn pod to run the iptables command on the host

vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go, vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch.go, vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_flags.go
I've named the commit to be able to squash it with other during next rebase. 
This is changing how we shim flags when invoking kube-controller-manager.
/assign @deads2k @sttts
=> UPSTREAM: <carry>: allow running bare kube-controller-manager

pkg/oc/cli/kubectlwrappers/wrappers.go
because:
$ oc get --help
Display one or many resources 
Possible resources include builds, buildConfigs, services, pods, etc. To see a list of common resources, use 'oc get'.
but:
$ oc get
You must specify the type of resource to get. Use "oc api-resources" for a complete list of supported resources.
error: Required resource not specified.
Use "oc explain <resource>" for a detailed description of that resource (e.g. oc explain pods).
See 'oc get -h' for help and examples.
This brings it in line with `kubectl`:
$ kubectl get --help
Display one or many resources 
(...)
Use "kubectl api-resources" for a complete list of supported resources.
=> minor fix in "oc get --help" text re. "list of common resources"

vendor/k8s.io/kubernetes/pkg/util/mount/BUILD, vendor/k8s.io/kubernetes/pkg/util/mount/fake.go, vendor/k8s.io/kubernetes/pkg/util/mount/mount_helper.go, vendor/k8s.io/kubernetes/pkg/util/mount/mount_helper_test.go, vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux.go, vendor/k8s.io/kubernetes/pkg/util/mount/mount_linux_test.go, vendor/k8s.io/kubernetes/pkg/volume/util/BUILD, vendor/k8s.io/kubernetes/pkg/volume/util/util.go, vendor/k8s.io/kubernetes/pkg/volume/util/util_test.go, vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go
This fixes flakes found by upstream gluster e2e suite - sometimes it terminates gluster server before clients finish their cleanup.
https://github.com/kubernetes/kubernetes/pull/71804
Upstream issue: https://github.com/kubernetes/kubernetes/issues/71584
=> UPSTREAM: 71804: Use UnmountMountPoint util to clean up subpaths

images/kube-proxy/Dockerfile, images/kube-proxy/Dockerfile.rhel, images/kube-proxy/OWNERS
This image is hyperkube with conntrack-tools and iptables
SDN-310 Create origin kube-proxy image
https://jira.coreos.com/browse/SDN-310
=> Build kube-proxy image

pkg/apps/apis/apps/validation/validation.go, pkg/apps/apis/apps/validation/validation_test.go, pkg/apps/controller/deploymentconfig/deploymentconfig_controller.go, test/extended/deployments/deployments.go, test/extended/deployments/util.go, test/extended/testdata/bindata.go, test/extended/testdata/deployments/deployment-trigger.yaml
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1620608
/cc @mfojtik
=> Bug 1620608: Fix dc adoption

vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/options/options.go
allow serving the scheduler securely so we can force it insecure, so we can land the rebase.
=> UPSTREAM: <drop>: enable secure serving for scheduler

test/extended/machines/workers.go
Add disruptive testing to ensure if we delete worker machines, we recover with new machines and ready nodes in 5 minutes.
/cc @enxebre
=> e2e: delete worker machines and ensure recovery

vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go, vendor/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go, vendor/k8s.io/kubernetes/pkg/proxy/service.go, vendor/k8s.io/kubernetes/pkg/proxy/types.go
This brings in two Upstream commits to clear conntrack entries for externalIP addresses
fixes: 
https://bugzilla.redhat.com/show_bug.cgi?id=1632192
https://bugzilla.redhat.com/show_bug.cgi?id=1679260
=> Clear conntrack entries for externalIPs 

test/extended/util/test.go
https://bugzilla.redhat.com/show_bug.cgi?id=1695220
=> Disable BlockVolume tests that need kubelet 1.13

test/extended/cli/compat.go
The OpenShift `oc` binary must be able to run on Linux amd64 platforms
that are different but reasonably similar, like musl, busybox, and other
glibc's.  Test it here.
=> Add an e2e test that verifies the CLI works under arbitrary Linux envs

test/extended/prometheus/prometheus.go
To be able to land https://github.com/openshift/cluster-kube-controller-manager-operator/pull/207 we need to disable temporarily kcm verification. After the aforementioned PR lands we need to switch to `https`. 
/assign @sttts
=> Disable kcm metrics endpoint temporarily

vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_util.go
In Kubernetes 1.13, `fstype` was parsed as case-sensitive. We need to fix it to case-insensitive, so `fsType` works.
https://bugzilla.redhat.com/show_bug.cgi?id=1694656
https://github.com/kubernetes/kubernetes/pull/75943
=> UPSTREAM: 75943: Fix AWS driver to provision specified fsType

pkg/network/node/multitenant.go, pkg/network/node/networkpolicy.go, pkg/network/node/ovscontroller.go, pkg/network/node/ovscontroller_test.go
Second attempt at a backport of #22158, now including #22302 as well to hopefully fix up the problems from the last backport attempt (#22251)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1686025 ("Network Policy Plugin does not clean up flows from deleted namespaces") AND https://bugzilla.redhat.com/show_bug.cgi?id=1694704 ("NetworkPolicy rules don't update reliably after a service restart")
=> [3.11] Fix up VNID tracking on restart / delete unused NetworkPolicy flows

pkg/oc/cli/admin/prune/deployments/deployments.go, pkg/oc/cli/admin/prune/deployments/prune.go
This is a followup to https://github.com/openshift/origin/pull/22211 removing dead code from deployments pruning.
=> Remove unused code in prune deployments

publishing-kube-rules.yaml, publishing-rules.yaml
The upstream bot master branch switched to go.mod.
=> publishing: skip gomod

pkg/network/node/node.go
Cleaning up pods on startup may involve doing CNI DELETEs. When Multus is in use, this will require making apiserver calls, and it will try to use the kubernetes service IP, which openshift-sdn may not have set
up yet, resulting in network errors and timeouts. Fix this by doing the deletes in a goroutine, so SDN can continue initializing and set up the proxy.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1695554
=> Bug 1695554 - SDN may be very slow to start up after a reboot

pkg/security/apis/security/validation/validation.go, pkg/security/apis/security/validation/validation_test.go, pkg/security/apiserver/registry/podsecuritypolicysubjectreview/rest.go
The spec.user and spec.groups field of PSP subject review are
optional.  Per the API docs:
If User and Groups are empty, then the check is performed using
*only* the ServiceAccountName in the PodTemplateSpec.
Thus we check if either field is specified before attempting to
perform a check via FindApplicableSCCs.
This does not cause any issues as the the error is simply logged and
the SA is consulted as usual.  The error just looks scary.
@openshift/sig-auth @deads2k
=> PSP subject review: do not pass empty user to FindApplicableSCCs

pkg/oc/cli/admin/network/join_projects.go
When joing two projects if the first one specified does not exist
instead of issueing the error "no projects found" the command fails
with a timeout.
Correct this so that regardless of which project does not exist the
correct error is thrown
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1592217
=> BZ 1592217 Correct error message when joining two projects

pkg/printers/internalversion/printer.go, pkg/printers/internalversion/printer_test.go
Add server side table printer for RangeAllocation
```
$ oc get rangeallocations
NAME      RANGE                         DATA
scc-uid   1000000000-1999999999/10000   0x3f
$ oc get rangeallocations scc-uid 
NAME      RANGE                         DATA
scc-uid   1000000000-1999999999/10000   0x3f
```
Bug 1690243
---
Remove dead printer code
---
Fix TestPrinterCoverage
It will now correctly fail when a type is missing a printer:
printer_test.go:105: missing printer for security.RangeAllocation.
Check pkg/cmd/cli/describe/printer.go
---
@openshift/sig-auth @soltysh
=> Bug 1690243: Add server side table printer for RangeAllocation

test/extended/prometheus/prometheus.go
Test the same prometheus targets as in cluster monitoring operator e2e test:
https://github.com/openshift/cluster-monitoring-operator/blob/2975434dccad2ed726a22f367cc33c4deec86ffa/test/e2e/main_test.go#L115-L127
=> e2e: test more prometheus scrape targets

pkg/user/apiserver/registry/user/etcd/etcd.go
The use of the kube:admin user against the API causes lookups against the API that will result in "validation" errors:
apiserver received an error that is not an metav1.Status:
&field.Error{Type:"FieldValueInvalid", Field:"metadata.name",
BadValue:"kube:admin", Detail:"may not contain \":\""}
By returning a proper status error, we make sure that the API server does not attempt to log these expected "failures."
Bug 1697206
Fixes #21632
=> Bug 1697206: Return a status error on GET user with invalid name

vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator_test.go
Backport of kubernetes/kubernetes#73484, leading to stable OpenAPI specs and their etags.
=> UPSTREAM: 73484: Sort apiservices properly during openapi aggregation

hack/local-up-master/kube-apiserver-manifests/01_cluster_resource_quota_crd.yaml, hack/local-up-master/lib.sh, hack/test-cmd.sh, pkg/admission/customresourcevalidation/attributes.go, pkg/admission/customresourcevalidation/clusterresourcequota/validate_crq.go, pkg/admission/customresourcevalidation/clusterresourcequota/validation/validation.go, pkg/admission/customresourcevalidation/clusterresourcequota/validation/validation_test.go, pkg/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go, pkg/cmd/openshift-apiserver/openshiftapiserver/informers.go, pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go, pkg/cmd/openshift-controller-manager/controller/interfaces.go, pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go, pkg/cmd/openshift-kube-apiserver/server.go, pkg/quota/apiserver/admission/clusterresourcequota/admission.go, pkg/quota/apiserver/apiserver.go, pkg/quota/apiserver/registry/clusterresourcequota/etcd/etcd.go, test/integration/clusterquota_test.go, test/integration/clusterresourceoverride_admission_test.go, test/integration/etcd_storage_path_test.go, test/util/client.go, test/util/server/server.go, vendor/k8s.io/kubernetes/pkg/master/controller/crdregistration/crdregistration_controller.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/patch_always_local_delegate.go
Goal of this change is to move ClusterResourceQuota from OpenShift API server to CRD so the admission plugins that run in kubernetes apiserver do not have dependency on OpenShift API resource. In case the OpenShift API server have downtime that means every request to Kubernetes API server is delayed.
This PR require https://github.com/openshift/cluster-config-operator/pull/25 to land first, otherwise CRQ is broken.
This will also disable etcd storage for openshift clusterresourcequota so we don't accidentally write to a wrong bucket (and we can actually prove this works).
TODO:
/cc @sttts 
/cc @deads2k 
/cc @enj 
/cc @derekwaynecarr
=> Move ClusterResourceQuota to CRD

Makefile, hack/lib/build/binaries.sh
The cross-platform builds are failing because brew uses /go:/opt/rhtoolset/...
and the release copy step fails to find the generated binary because
`/go:/opt/rhtoolset/...` is not a valid path. We must set OS_TARGET_BIN
to the internal GOPATH.  We will remove support for external GOPATH in preparation for Go 1.12.
Failed with:
```
2019-04-05 17:00:42,409 - atomic_reactor.plugins.imagebuilder - INFO - + go install -pkgdir /go/src/github.com/openshift/origin/_output/local/pkgdir/darwin/amd64 -tags 'include_gcs include_oss containers_image_openpgp ' '-ldflags=-s -w -X github.com/openshift/origin/pkg/oc/clusterup.defaultImageStreams=centos7 -X github.com/openshift/origin/pkg/cmd/util/variable.DefaultImagePrefix=openshift/origin -X github.com/openshift/origin/pkg/version.majorFromGit=4 -X …
```
=> hack: Handle multiple entries in OS_EXTRA_GOPATH for brew builds

test/extended/prometheus/prometheus.go
Checking if Watchdog alert is in firing state by querying prometheus metrics.
Based on `"should report telemetry if a cloud.openshift.com token is present"` test and on https://github.com/openshift/cluster-monitoring-operator/pull/266 PR.
/cc @brancz @mxinden @s-urbaniak @squat @metalmatze
=> test/extended: check if prometheus is firing a watchdog alert

vendor/k8s.io/kubernetes/pkg/features/kube_features.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/features/kube_features.go
Now that nullable support is in again, we should enable validation ASAP to avoid broken code being merged.
This independent of CRD openapi publishing.
Prereq: https://github.com/openshift/cluster-kube-apiserver-operator/pull/376
=> UPSTREAM: <drop>: Revert: disable CRD validation until openapi fixes land

vendor/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager_test.go
To unblock the queue, disable just this one test. Future releases should
investigate why it is flaking.
=> UPSTREAM: <drop>: TestNewManagerImplStartProbeMode is flaky 

test/extended/operators/images.go, test/extended/prometheus/prometheus.go
requires: https://github.com/openshift/installer/pull/1554
=> Bug 1697644: test/extended: update test to use openshift-config pull-secret

test/util/server/server.go, vendor/k8s.io/kubernetes/cmd/cloud-controller-manager/app/controllermanager.go, vendor/k8s.io/kubernetes/cmd/hyperkube/main.go, vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go, vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/deprecated_insecure_serving.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver_test.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/secure_serving.go
Right know the upstream does not call the `server.Shutdown()` when the controller manager receives SIGTERM. The SIGTERM `stopCh` is not even wired into controller manager and scheduler.
In that case, when the controller manager or scheduler are terminated, their ports will keep open until kernel timeout is hit (~60s++) and the port is freed. Since for these two components we use host network, this is causing the operator observing container restart in pod and ultimately setting failure condition to true.
=> Make sure SIGTERM shutdown the controller manager and scheduler API server

vendor/k8s.io/kubernetes/pkg/controller/podautoscaler/horizontal_test.go
See https://bugzilla.redhat.com/show_bug.cgi?id=1695807
and the upstream PR https://github.com/kubernetes/kubernetes/pull/76455
=> UPSTREAM: 76455: Fix flakes in HPA tests

test/cmd/OWNERS, test/end-to-end/OWNERS, test/extended/networking/OWNERS, test/integration/OWNERS, test/testdata/OWNERS
A long time ago we added some sig-network people to test-related OWNERS files so we could update the network-related tests easily, but these days, this mostly just results in us being asked to review test changes that we don't know anything about. And the networking tests were split out into their own subdirectory and there aren't any networking cmd or integration tests any more.
(`approvers` in the new networking/OWNERS file is just copied from the parent directory's `approvers`)
=> Add test/extended/networking/OWNERS, clean up others

pkg/oauthserver/oauthserver/oauth_apiserver.go, pkg/oauthserver/server/grant/grant.go, pkg/oauthserver/server/headers/headers.go, pkg/oauthserver/server/login/login.go, pkg/oauthserver/server/logout/logout.go, test/integration/oauth_server_headers_test.go
We should always set these headers on all pages of the OAuth server.
=> Always set standard security headers for OAuth server

pkg/oc/lib/tokencmd/basicauth.go, pkg/oc/lib/tokencmd/request_token.go
We used to be able to tell this information via "oc version"
@openshift/sig-auth @soltysh
=> oc: make it clear what challenge handlers are enabled

test/extended/util/test.go
@smarterclayton @deads2k 
xref https://bugzilla.redhat.com/show_bug.cgi?id=1694182
/hold
until os-container is verified to be at 1.13
=> test/e2e: re-enable kubelet hostAliases test

pkg/oc/cli/admin/admin.go, pkg/oc/cli/admin/mustgather/mustgather.go, test/cmd/admin.sh
```
namespace/openshift-must-gather-rfvmp created
clusterrolebinding.rbac.authorization.k8s.io/must-gather-6s6rb created
receiving incremental file list
created directory must-gather.local.312900838098712312
.
.
.
sent 24,843 bytes  received 117,399,750 bytes  2,472,096.69 bytes/sec
total size is 117,259,199  speedup is 1.00
clusterrolebinding.rbac.authorization.k8s.io/must-gather-6s6rb deleted
namespace/openshift-must-gather-rfvmp deleted
```
=> always print name of resources created by must-gather

pkg/oc/cli/admin/admin.go, pkg/oc/cli/admin/mustgather/mustgather.go, test/cmd/admin.sh
```
Launch a pod to gather debugging information 
This command will launch a pod in a temporary namespace on your cluster that gathers debugging
information, using a copy of the active client config context, and then downloads the gathered
information.
Usage:
oc adm must-gather [flags]
Examples:
oc adm must-gather
oc adm must-gather --dest-dir=/local/directory
oc adm must-gather --image=my/image:tag --source-dir=/pod/directory -- myspecial-command.sh
Options:
--dest-dir='': Set a specific directory on the local machine to write gathered data to.
--image='': Set a specific to use - by default the image will be looked up for OpenShift's must-gather
--node-name='': Set a specific node to use - by default a random master will be used
```
Picking up from …
=> add must-gather command

vendor/k8s.io/kubernetes/pkg/master/controller/crdregistration/crdregistration_controller.go
This should mitigate the issue when the CRD registration controller was stomping the `quota.openshift.io/v1` APIService and fighting with OpenShift API server operator.
The change will remove the APIService from the sync and it won't be reconciled. The APIService will still be created (we want this when the cluster is installed), but consequent updated from OpenShift API server operator won't be overridden.
=> Fix case when operator fight with CRD registration on quota.openshift.io

images/sdn/Dockerfile.rhel, images/sdn/scripts/ip6tables, images/sdn/scripts/ip6tables-restore, images/sdn/scripts/ip6tables-save, images/sdn/scripts/iptables, images/sdn/scripts/iptables-restore, images/sdn/scripts/iptables-save
somewhere in the build path for the sdn image iptables gets installed as a dependancey. If the scripts are copied into the image after we are assured that the iptables wrappers get used.
=> Move the COPY scriptes to below the RUN INSTALL_PKGS for sdn image

tools/etcdhelper/etcdhelper.go
Small change, the default client port for etcd v3 is 2379.
=> tools/etcdhelper: update default client port

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
Trying to debug https://bugzilla.redhat.com/show_bug.cgi?id=1698829
@wongma7, PTAL
It does extra DescribeInstances after detach, otherwise it just logs stuff and does not prevent the bug in any way.
=> UPSTREAM: drop: Add extra logs for flake analysis

vendor/k8s.io/kubernetes/pkg/controller/podautoscaler/legacy_horizontal_test.go
See https://github.com/kubernetes/kubernetes/pull/76455
This is the second half of the fixes from the upstream PR. Hopefully it will take care of https://bugzilla.redhat.com/show_bug.cgi?id=1695326
(Here's the first half: #22531)
=> UPSTREAM: 76455: More flake fixes in HPA legacy tests

images/tests/Dockerfile.rhel
This lets us SSH from the teardown container into the cluster without hitting:
```console
$ ssh -A core@$bootstrap_ip
No user exists for uid 1051910000
```
OpenSSH has [a very early `getpwuid` call][1] with no provision for bypassing via `HOME` or `USER` environment variables [like we did for Bazel][2].  OpenShift runs with the random UIDs by [default][3]:
> By default, all containers that we try and launch within OpenShift, are set blocked from “RunAsAny” which basically means that they are not allowed to use a root user within the container.  This prevents root actions such as chown or chmod from being run and is a sensible security precaution as, should a user be able to perform a local exploit to break out of the container, then they would not be running as root on the underlying …
=> images/tests: Globally-writeable /etc/passwd

pkg/build/controller/build/build_controller.go
this came up during a CI infra investigation...  the ci operator would attempt to delete a build, the foreground propagation policy would delete the pod first (due to GC ownership relationship), then the build controller would see the build get updated and create a new build pod for the build, before the deletion propagation finished deleting the build object.
At least that was what we speculated.  Regardless this seems like an appropriate check to have.
=> build controller should ignore builds that are being deleted

hack/lib/constants.sh
Allows binaries to start in environments without libcrypto at the
correct version and path.
In the future this can be removed when RHEL golang correctly uses
dlopen() instead of dynamic linking and when RHCoS has the correct openssl compat lib
=> Disable openssl linking in Origin binaries

test/extended/machines/workers.go
This PR removes dependency on openshift specific labels on the machine object for listing worker nodes.
/cc @enxebre @mfojtik
=> Dont rely on machine labels for listing worker nodes

hack/lib/build/binaries.sh, hack/lib/constants.sh
Yes, you read right, Bash 3. Unfortunately, there is a difference between how Bash 3 and more recent versions handle looping via arrays.
When https://github.com/openshift/origin/pull/22218 was put in, these arrays were changed to a single entry with an empty string, as opposed to an empty array.
When https://github.com/openshift/origin/blob/71af8a34fc829e902a957da00abb263d33b0df9e/hack/lib/build/binaries.sh#L411-L413 ends up running in Bash 5, it doesn't run the loop because it sees a single empty entry. When it runs on Bash 3 however, it runs a single time, with `${linkname}` being empty. This results in a symlink of `oc -> oc`, overwriting the binary that was just generated.
The one place where this matters is on Darwin, as it still ships with Bash 3 out of the box, and oc is the one …
=> Fix symlink arrays for Bash 3

test/extended/util/test.go
When undefined, distro is set to "debian" and that disables GlusterFS tests.
=> Run e2e tests with "custom" distro

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/clientca.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/certs/single_certkey_pair.go
One possibility for unauthorized is that we haven't read the client cert.  I haven't seen any evidence of this (every log I've seen looks good), but this makes it an error.
=> UPSTREAM: <carry>: squash to dynamic certs, don't load zero length certs

vendor/k8s.io/kubernetes/test/e2e/framework/util.go, vendor/k8s.io/kubernetes/test/e2e/scheduling/resource_quota.go
This is to skip resource quota tests when featuregates are disabled
/cc @deads2k @sjenning @vikaschoudhary16
=> UPSTREAM: 75985: Add feature gates for resource quota

test/extended/cluster/cl.go, test/extended/cluster/context.go
We want to use the `--node-selector` on a namespace/project to easily route all deployed objects to worker pods (`node-role.kubernetes.io/worker=`).
=> Switch ClusterLoader to use `oc adm` to create projects

cmd/openshift-tests/e2e.go, cmd/openshift-tests/openshift-tests.go, vendor/k8s.io/kubernetes/test/e2e/instrumentation/logging/generic_soak.go
This is just a placeholder to allow us to prep the jobs. It will be
clarified later.
Also cleans up output logging that doesn't add anything.
=> Add a disruptive suite to openshift-tests

pkg/image/registryclient/client.go, pkg/image/registryclient/client_test.go, pkg/oc/cli/admin/release/info.go, pkg/oc/cli/image/info/info.go, pkg/oc/cli/image/manifest/manifest.go
Introduce a global rate limiter for a given registry client context at 5qps
/ 5 burst, then have the retry repository wrapper enforce limiting. Make
429 from the client trigger a 2s cooldown. In combination this allows us to
avoid the limits. Do not expose rate limit as a tunable for now in CLI, but
future iterations may do so.
This should allow nightly builds to succeed.
=> Quay tightened rate limits, causing release creation to fail

pkg/oc/cli/admin/release/info.go, pkg/oc/cli/image/info/info.go, pkg/oc/cli/image/manifest/manifest.go
The info command had duplicate code, causing it to fail to properly
log errors. Unify the code paths.
Correct two failing edge cases in the release info printers related
to images that don't exist. This panicked:
oc adm release info quay.io/openshift-release-dev/ocp-release:4.0.0-2
since the images have been deleted out of it now.
=> Use the image retriever and reuse cached command contexts

pkg/oc/cli/admin/admin.go, pkg/oc/cli/admin/mustgather/mustgather.go, test/cmd/admin.sh
User the `must-gather` ImageStream in the `openshift` namespace to get the image for the `must-gather` tool.
=> get must-gather image from imagestream

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/routes/openapi.go
We'll need this patch for:
Bug 1698625
Bug 1684344
(and PRs associated w/ those)
/cc @deads2k 
/cc @mfojtik
=>  UPSTREAM: <carry>: filter out RBR and SCC paths from OpenAPI

test/extended/builds/start.go
Now there's a case [OCP-23057](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-23057) about  [bz1694871](https://bugzilla.redhat.com/show_bug.cgi?id=1694871), so add extended test, here is a pass log[1] [2]for my local host. 
@wzheng1 @xiuwang Could you help to review it,  and @adambkaplan ,  hope devels can review it and give advice too, thanks. 
[1]http://pastebin.test.redhat.com/754739
[2]http://pastebin.test.redhat.com/754740
=> Add test/extended to cover  bz1694871

test/extended/router/headers.go, test/extended/router/metrics.go, test/extended/router/reencrypt.go, test/extended/router/router.go, test/extended/util/cli.go
If the ingress controller/router does not have a LoadBalancer service, use the internal service for tests.
Delete broken skip logic.  The logic in question was checking an error value from `wait.PollImmediate` using the `IsNotFound` function from the Kubernetes API machinery.  In the polling in question, if a resource is not found, the polling eventually times out, and `wait.PollImmediate` returns `wait.ErrWaitTimeout`, which is not an `APIStatus` type, which means that `IsNotFound` would never return true for it.
* `test/extended/router/router.go` (`waitForRouterMetricsIP`): Rename from this...
(`waitForRouterInternalIP`): ...to this.
(`waitForRouterServiceIP`): Rename from this...
(`waitForRouterExternalIP`): to this.
(`routerShouldHaveExternalService`): New function that checks the …
=> Bug 1700068: test/extended: Use internal service if no router LB

pkg/cmd/openshift-kube-apiserver/cmd.go, pkg/cmd/openshift-kube-apiserver/server.go
This fixes the case when kube apiserver is shut down using the TERM signal and should exit with 0 code (after gracefully stopping all connections/etc.). Otherwise if the apiserver run in a static pod with restart on failure, with kubelet managing it, the container will be restarted.
/cc @deads2k
/cc @sttts
=> kube-apiserver: exit with zero code on term signal

pkg/oc/cli/admin/release/extract_tools.go
The installer `Dockerfile` has put the binary in `/bin` since openshift/install@29e4d10eb7 (openshift/installer#343).  Fixes:
```console
$ oc adm release extract --command=openshift-install registry.svc.ci.openshift.org/openshift/origin-release:v4.0
error: image did not contain usr/bin/openshift-install
```
CC @smarterclayton
=> pkg/oc/cli/admin/release/extract_tools: Fix false "did not contain" when not hashing

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_server_journal.go, vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_server_journal_test.go
During upgrades or other significant disruptive events, being able
to look at node logs from the previous boot may be very very important.
Have the journal log endpoint check whether there are multiple boot
entries present, and if so, use `-1` to denote the current and previous.
=> UPSTREAM: <carry>: Return journal logs from previous boot if possible

pkg/network/node/node.go
In trying to improve the logging on SDN restart in #22471 I accidentally broke the pod-reattachment code. I had assumed that the PR wouldn't merge if e2e-aws-upgrade had failed, but it looks like the bot didn't even wait for it to finish. :-/
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1702194
=> Re-fix pod reattachment on SDN restart

test/extended/util/test.go
=> Disable resource quota

pkg/oc/cli/admin/upgrade/upgrade.go, test/e2e/upgrade/upgrade.go
As part of adding certificate verification to the payload we must now
tell the CVO to bypass certain failing conditions. Wire --force to
force and mark that upgrade is not experimental for 4.1.
First two commits from #22644
=> Upgrading with --force should set the force boolean

pkg/test/ginkgo/cmd_runsuite.go
In the future, we might want to allow users to definitively turn this
off.
=> If only one test is being run in a suite, always include success output

pkg/oc/cli/admin/mustgather/mustgather.go, test/extended/cli/mustgather.go
Running a command such as `oc adm must-gather --source-dir /output -- bash -c "ls -l > /output/out.log"` ran into 2 issues: 1) the custom command was not executed properly, and 2) the `--source-dir` option was not properly applied.
=> fix problem running custom must-gather command

test/e2e/upgrade/upgrade.go
This should not be necessary, filed https://bugzilla.redhat.com/show_bug.cgi?id=1703158
=> Wait slightly longer to observe version

pkg/oc/lib/describe/describer.go
Describer printing bool pointer directly, it should print out bool variable.
Signed-off-by: Zhou Peng <p@ctriple.cn>
=> Bugfix: oc describe scc <name> printing error

pkg/serviceaccounts/controllers/docker_registry_service.go, pkg/serviceaccounts/controllers/docker_registry_service_test.go
If the registry service uses HTTP/S default ports, allow auth to drop
the port number.
This is a hack until DEVEXP-190 is implemented.
=> Bug 1701422: registry auth without port number

test/extended/builds/start.go
Buildah 1.7.3 changed how it warns about unused build args, changing a `"[Warning] One or more build-args %v were not consumed\n"` format string into `"[Warning] one or more build args were not consumed: %v\n"`.  Accept either version.
=> Accept buildah 1.7.3+ unused build arg error

.travis.yml, hack/lib/constants.sh, images/cli-artifacts/Dockerfile.rhel, images/cli/Dockerfile.rhel, images/hyperkube/Dockerfile.rhel, images/hypershift/Dockerfile.rhel, images/sdn/Dockerfile.rhel, images/template-service-broker/Dockerfile.rhel, images/tests/Dockerfile.rhel, origin.spec
Out of curiosity I'm opening a rebased version of https://github.com/openshift/origin/pull/22510
=> Switch to go1.11

test/extended/util/test.go
This depends on https://github.com/openshift/cluster-kube-apiserver-operator/pull/344 and https://github.com/openshift/cluster-kube-controller-manager-operator/pull/195
We are going to re-enable local storage in preparation for 4.1
=> Enable local storage e2e

pkg/oc/cli/admin/release/new.go
Now that CVO only applies ordering on update, we are reorganizing
the order components are applied to better align with correct
upgrades. The order is:
0000_10_*: config-operator
0000_20_*: kube-apiserver
0000_25_*: kube scheduler and controller manager
0000_30_*: other apiservers: openshift and machine
0000_40_*: reserved
0000_50_*: all non-order specific components
0000_60_*: reserved
0000_70_*: disruptive node-level components: dns, sdn, multus
0000_80_*: machine operators
0000_90_*: reserved for any post-machine updates
Operators in 0000_50_* should have no prefix (like 0000_70_
before). No other rules of ordering have changed.
=> Move default components to an appropriate upgrade order (generic)

test/extended/cli/mustgather.go
Checks the following files are created and are > 100 bytes in size:
```
audit_logs/openshift-apiserver_audit.log
audit_logs/kube-apiserver_audit.log
host_service_logs/masters/kubelet_service.log
host_service_logs/masters/crio_service.log
```
=> test that must-gather generated audit logs

pkg/network/node/node.go, pkg/network/node/runtime.go
While we improved SDN's own logging about handling pods after a reboot, we were still logging Events about being forced to kill pods, which then led some people to suspect an upgrade problem was network-related.
This fixes us to recognize and ignore already-dead pods.
=> Continue improving SDN startup logging

pkg/monitor/operator.go, pkg/monitor/operator_test.go
Versions are showing up multiple times.
```
Apr 27 04:19:51.684 I clusteroperator/monitoring versions: operator 0.0.1-2019-04-27-030828 -> 0.0.1-2019-04-27-030928
Apr 27 04:19:51.684 I clusteroperator/monitoring versions: operator 0.0.1-2019-04-27-030828 -> 0.0.1-2019-04-27-030928
Apr 27 04:19:51.684 I clusteroperator/monitoring versions: operator 0.0.1-2019-04-27-030828 -> 0.0.1-2019-04-27-030928
```
should be one line
=> Collapse version changes in monitor output

test/extended/prometheus/OWNERS
This unblocks the monitoring team from adding new tests into origin.
=> test/extenden/prometheus: add monitoring team as owners

pkg/oc/cli/admin/release/image_mapper.go, pkg/oc/cli/admin/release/new.go, pkg/oc/cli/image/append/append.go
Print an output consistent with oc adm release info --verify if no
arguments are specified or if an image is pushed. Other modes bypass the
image creation and so do not have this output.
Make --dry-run on oc image append calculate the SHA instead of just doing
nothing.
Clean up some incremental output from append and in general make the entire
experience more pleasant.
Finally, perform a final step verification that a no-argument recreation
of the payload works correctly.
=> When no argument passed to oc adm release new, dry run the output

test/extended/cli/mustgather.go
Lets make debugging https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-4.1/78#openshift-tests-cli-oc-adm-must-gather-runs-successfully-suiteopenshiftconformanceparallel easier.
/cc @sanchezl 
/cc @deads2k
=> extended: print empty files when must-gather test fail

pkg/authorization/apiserver/admission/restrictusers/restrictusers.go, pkg/cmd/openshift-apiserver/openshiftapiserver/informers.go, test/integration/restrictusers_test.go
Goal of this change plus [this](https://github.com/openshift/origin/pull/22699) is to move RoleBindingRestrictions from OpenShift API server to CRD so the admission plugins that run in kubernetes apiserver do not have dependency on OpenShift API resource. 
This PR moves to external client,types for RBRs
openshift/cluster-config-operator#32 adds the CRD
=> move RoleBindingRestriction to CRD Part 1

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
We don't log v(4) in e2e jobs. And add volume ID to logs so we can track volume lifetime easily.
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1698829
=> UPSTREAM: <drop>: Bump debug logs for e2e

test/integration/dockerregistryclient_test.go
Something happened over night (~4am CET) and `kubernetes/guestbook` is not available anymore. I'm switching to using our `openshift/hello-openshift` image from dockerhub. 
/assign @mfojtik @dmage
=> Use openshift controller image from dockerhub in integration

pkg/image/apiserver/registry/imagestream/strategy.go, pkg/image/apiserver/registry/imagestream/strategy_test.go
When an ImageStream is created with a large number of tags that
reference other ImageStreamTags in the same namespace, it is wasteful to
check for permissions to acces every single one, serially.
/assign @smarterclayton @adambkaplan
=> Don't send identical SAR checks on ImageStream creation

vendor/k8s.io/kubernetes/test/e2e/common/pods.go
Upstream code comment admits the test can become flaky with heavily loaded kubelets (i.e. high test parallelization)
https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/test/e2e/common/pods.go#L50-L52
Increasing from 10s to 1m.
xref https://bugzilla.redhat.com/show_bug.cgi?id=1703881
=> UPSTREAM: <carry>: test/e2e: increase timeout for pod readiness test

test/extended/cli/mustgather.go
Disable checking the file sizes of the files expected to be generated by `oc adm must-gather` during e2e. Will follow up with a more comprehensive fix after analyzing the various causes of the 0 byte files.
https://bugzilla.redhat.com/show_bug.cgi?id=1704325
=> e2e must-gather disable check for file sizes

vendor/k8s.io/kubernetes/test/e2e/upgrades/services.go
The upstream can't enable this, but we need to do so in order to
properly validate that cluster upgrades retain availability.
=> UPSTREAM: <carry>: Always test PDB's during service upgrade test

test/extended/operators/cluster.go
The pod created by `oc adm must-gather` spends a  lot of time in pending state. This trips up the hot looping detection tests when they happen to run concurrently.
=> Ignore pending pods with running init containers when trying to detect crash loops

pkg/oc/cli/admin/release/extract_tools.go, pkg/oc/cli/cli.go, pkg/oc/cli/requestproject/request_project.go
kubectl is now a hard link in mac and windows exports of the cli
tools. Add a readme to all three platforms that describes how to
get started, and also in Windows describe how to copy to get
kubectl.
In the intro help, use django-psql-example and simplify some of
the doc. Clarify that kubectl runs equally well against OpenShift,
and give a few examples.
=> Bug 1704570: Include kubectl in extracted tools with a readme and streamline oc help

pkg/apiserver/authentication/oauth/tokenauthenticator.go, pkg/authorization/authorizer/scope/converter.go, pkg/authorization/authorizer/scope/validate_test.go, pkg/oauth/apis/oauth/validation/validation.go, pkg/oauth/apis/oauth/validation/validation_test.go, pkg/oauth/apiserver/registry/oauthclientauthorization/strategy_test.go, pkg/oauthserver/ldaputil/identityfactory.go, pkg/user/apis/user/validation/validation.go, pkg/user/apis/user/validation/validation_test.go, pkg/user/apiserver/registry/user/strategy.go, test/integration/etcd_storage_path_test.go, test/integration/groups_test.go, test/integration/oauth_ldap_test.go, test/integration/oauth_serviceaccount_client_test.go, test/integration/oauthstorage_test.go, test/integration/scopes_test.go, test/testdata/oauthaccesstoken.yaml, test/util/client.go
This PR makes changes to the validation of the authn-owned objects and tightens the edges around them.
cc @openshift/sig-auth @enj
=> Bug 1703595: oauth/user/authz: tighten API validation checks

pkg/cmd/openshift-integrated-oauth-server/server.go, pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_oauthserver.go, pkg/oauthserver/oauthserver/oauth_apiserver.go, pkg/oauthserver/server/headers/oauthbasic.go
This change allows us to have delegated authentication and
authorization back to the kube API server for all non-OAuth
endpoints.  For example, this will make our metrics endpoint
protected with auth.
Bug 1703506
Bug 1704822
/assign @stlaz
=> Bug 1703506: Move OAuth server to standard handler chain

pkg/image/apiserver/registry/imagestream/strategy.go, pkg/image/apiserver/registry/imagestream/strategy_test.go
When an ImageStream is created with a large number of tags that
reference other ImageStreamTags in the same namespace, it is wasteful to
check for permissions to acces every single one, serially.
=> [release-3.11] Don't send identical SAR checks on ImageStream creation

hack/local-up-master/lib.sh, pkg/cmd/openshift-apiserver/openshiftapiserver/openshift_apiserver.go, test/util/server/server.go
Without this, we end up having inconsistent bootstrapping behavior.  By doing it in a loop, the healthz reports what we expect and we have a clear signal of failure before getting inconsistent results about which SCC have and have not been created.
=> SCC bootstrapping must not return until it has created all defaults

test/extended/prometheus/prometheus.go
This will fail currently until 
* https://github.com/openshift/installer/pull/1666
* https://github.com/openshift/cluster-monitoring-operator/pull/336
are merged. Putting this in place to prevent breaking this in the future or at least explicitly track it.
@s-urbaniak @squat @metalmatze @mxinden @paulfantom @deads2k @hexfusion
=> test/extended/prometheus: Add etcd target check

pkg/cmd/openshift-apiserver/openshiftadmission/register.go, pkg/image/apiserver/admission/imagepolicy/accept.go, pkg/image/apiserver/admission/imagepolicy/imagepolicy.go, pkg/image/apiserver/admission/imagepolicy/internalimagereferencemutators/builds.go, pkg/image/apiserver/admission/imagepolicy/internalimagereferencemutators/builds_test.go, pkg/image/apiserver/admission/imagepolicy/internalimagereferencemutators/meta.go, pkg/image/apiserver/admission/imagepolicy/internalimagereferencemutators/pods.go, pkg/image/apiserver/admission/imagepolicy/internalimagereferencemutators/pods_test.go, pkg/scheduler/admission/podnodeconstraints/admission.go, pkg/scheduler/admission/podnodeconstraints/admission_test.go, test/integration/pod_node_constraints_test.go
This updates PodNodeConstraints to only run against pods as we discussed a while back and then cleans up the related cruft.
/assign @ravisantoshgudimetla
=> Simplify pod node constraints

pkg/cmd/server/bootstrappolicy/policy.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml, test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
The contents of detailed healthz are considered sensitive.
@openshift/sig-auth @openshift/sig-master 
=> Remove /healthz/* from bootstrap RBAC

pkg/security/apiserver/admission/sccadmission/admission.go
@deads2k 
So the next person who messes with SCC admission has a better experience.
=> Improve error when SCC admission fails to create SecurityContextConstraintsProvider

cmd/openshift-tests/openshift-tests.go, cmd/openshift-tests/upgrade.go, pkg/test/ginkgo/cmd_runsuite.go, pkg/test/ginkgo/status.go, pkg/test/ginkgo/test.go, test/e2e/upgrade/monitor.go, test/e2e/upgrade/upgrade.go
Allow a test to specify that you want an upgrade to abort
part way through via
openshift-tests run-upgrade all ... --option abort-at=10
instructs the upgrade test to abort after it reaches 10% of
the test. This allows us to test disruption.
=> Support --option on upgrade tests to abort in progress

contrib/completions/bash/oc, contrib/completions/zsh/oc, pkg/oc/cli/whoami/whoami.go, test/cmd/whoami.sh
This flag will fetch configmap that contain location of web console URL and print it to user.
For 3.x API servers, this will use the API server hostname which should redirect user to console.
Example output:
```
$ oc whoami --show-console
https://api.ci.openshift.org:443
```
xref: https://github.com/openshift/console-operator/pull/218
=> Bug 1705627: Add --show-console flag to whoami command

pkg/oc/cli/admin/mustgather/mustgather.go
when openshift must-gather:latest imagestream tag cannot be resolved.
=> fallback to quay.io/openshift/origin-must-gather:latest

test/extended/imageapis/limitrange_admission.go, test/extended/util/framework.go
For tests that use imagestreams, wait for the internal registry
hostname to be available.
=> Bug 1702743: Wait for internal registry hostname to be published before running e2e tests

test/extended/cli/explain.go
This is a followup from https://github.com/openshift/origin/pull/22696 now that https://github.com/openshift/cluster-version-operator/pull/168 merged 
=> Add clusteroperators and clusterversions to explain tests

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/routes/openapi.go
RBR is namespace scoped, so the check cannot be a simple prefix.  Just nuke them all from orbit for now.
=> UPSTREAM: <carry>: filter out RBR and SCC paths from OpenAPI

pkg/build/controller/build/build_controller.go, pkg/build/controller/build/build_controller_test.go, pkg/build/util/util.go, pkg/cmd/openshift-controller-manager/controller/build.go, pkg/cmd/openshift-controller-manager/controller/interfaces.go
With openshift/cluster-openshift-controller-manager-operator#96,
the openshift controller manager will be able to read the internal registry's
certificate authority from a central ConfigMap.
Updating build controller to copy the registry CA into each build's CA ConfigMap.
=> Bug 1704874: Copy Registry CA to Build Pods

pkg/build/controller/build/build_controller.go, pkg/build/controller/build/build_controller_test.go, pkg/build/util/util.go, pkg/cmd/openshift-controller-manager/controller/build.go
switching to using the informer cache for service account + secret retrieval which will hopefully reduce our client api consumption a bit.
also raised the rate limits to 2x.
=> Bug 1704722: increase build controller client rate limit and reduce api calls

test/extended/imageapis/limitrange_admission.go, test/extended/templates/templateinstance_readiness.go, test/extended/util/framework.go
Identical to #22705, but adds a wait to the templateinstance readiness test.
=> Bug 1702743: Wait for internal registry hostname to be published before running e2e test (2)

test/extended/prometheus/prometheus.go
In https://github.com/openshift/origin/pull/22512 we are checking if prometheus is firing Watchdog alert which should be the only one fired. This test ensures there are no more firing alerts present.
/CC: @brancz @mxinden @s-urbaniak @squat @metalmatze
=> test/extended: check if there is less than two alerts fired

pkg/cmd/openshift-sdn/cmd.go
There's no need for this to return an error, and it annoys the upgrade tests.
=> openshift-sdn: exit with 0 when gracefully shut down

vendor/k8s.io/kubernetes/pkg/util/iptables/iptables.go
The bump to using iptables-nft in RHCOS seems to have gone smoothly, other than that we are now erroneously logging some errors on startup because the `iptables.IsNotFoundError` function does string matching, and the new iptables logs slightly different errors.
=> UPSTREAM: 77303: Update iptables.IsNotFoundError for iptables-nft error messages

pkg/oc/cli/admin/release/new.go
We have overrides if any field is set, not all fields are set.
Prevents building a release from an existing nightly correctly.
=> The new release command incorrectly detected user metadata

pkg/cmd/openshift-sdn/cmd.go, pkg/cmd/openshift-sdn/proxy.go, pkg/cmd/openshift-sdn/sdn.go, pkg/network/node/node.go
Wait for proxy services and endpoints to sync before writing the
CNI config file and thus declaring node network readiness.
@squeed @rcarrillocruz @pecameron @danwinship @JacobTanenbaum
=> sdn: wait for proxy initialization before declaring node network ready

test/integration/groups_test.go, test/integration/oauth_serviceaccount_client_test.go
Readd tests that check the "~" user endpoint and that check that approval for full-scopes is once again needed when scope of the original oauthclientauthorization gets restricted
cc @enj @openshift/sig-auth
=> tests follow-up to tightening authn APIs validation

pkg/oc/cli/admin/release/extract_tools.go
Pass security options so that e.g. adm release extract --tools from an image in a private repository can work.
=> extract_tools: pass security options

pkg/oc/cli/admin/upgrade/upgrade.go
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1706245
If you try to upgrade to an image which fails (ex: `the image may not be safe to use`), and re-attempt with `--force` it should allow you to proceed. Other workarounds include cancelling the first attempt with `oc adm upgrade --clear` and trying again with `--force`
=> Allow oc adm upgrade with --force even if versions match

images/sdn/Dockerfile.rhel
Makes it easier to debug any issues that iptables/iptables-nft might
have. Yes we can run iptables-save but we can get the raw info by
rsh-ing into the SDN pod and running nftables too.
@squeed @danwinship @JacobTanenbaum @knobunc @pecameron @rcarrillocruz
=> sdn: install nftables in SDN image

test/extended/cli/mustgather.go
This reverts commit 6abc26cf63bab324a9719e4cca0637563d9b1138.
=> Revert "e2e must-gather disable check for file sizes"

test/extended/builds/start.go
Buildah 1.7.3 changed how it warns about unused build args, changing a "[Warning] One or more build-args %v were not consumed\n" format string into "[Warning] one or more build args were not consumed: %v\n".  Accept only the new version of the message.
This is a follow-up to https://github.com/openshift/origin/pull/22641#issuecomment-485941286.
=> Only accept buildah 1.7.3+ unused build arg error

cmd/openshift-tests/openshift-tests.go, vendor/k8s.io/kubernetes/test/e2e/upgrades/apps/job.go, vendor/k8s.io/kubernetes/test/e2e/upgrades/apps/replicasets.go
Try to gather logs for https://bugzilla.redhat.com/show_bug.cgi?id=1706082 again.
This does two things:
1. hard code dumping logs where we're failing in upgrades
2. attempt to set the *other* global test context to dump them
=> log more failures during e2e

cmd/sdn-cni-plugin/openshift-sdn_linux.go, pkg/network/admission/restrictedendpoints/endpoint_admission.go, pkg/network/node/iptables.go
In conjunction with the MCS/approver changes happening elsewhere, this attempts to block all (non-privileged / non-`CAP_NET_ADMIN`) pods from being able to reach the MCS.
There are two commits, and both are hacks which are assumed to be temporary; if we want to keep something like this, we can reimplement the functionality more cleanly later.
The `OUTPUT` rule in the pod netns blocks direct connections from a pod to the MCS (including via egress IP, or via multus-created interfaces). The `FORWARD` rule in the pod netns blocks connections from a pod to the MCS via an egress-router. The `OUTPUT` rule in the root netns blocks direct connections from hostNetwork pods to the MCS. (I'm not sure that the `FORWARD` rule in the root netns actually does anything at this point... but it's not …
=> Bug 1707162: Block access to MCS

pkg/oc/cli/admin/mustgather/mustgather.go
Occasionally, we start trying to capture the `oc adm must-gather` StdOut logs before they are available.
The `retry.RetryOnConnectionErrors()` mechanics were not appropriate in this context. Switched to `wait.PollImmediate()`, but still made use of  `retry.IsHTTPClientError()` to enable retry on connections errors.
=> wait for must-gather logs to be available

hack/local-up-master/lib.sh
Running master.sh script dies as soon as something needs to be logged,
since the name of the function doesn't exist.
The warning function should be called instead.
=> Fix invocation of log function on local-up

pkg/oc/cli/admin/release/git.go
It's a more natural ordering and is less confusing when comparing
repos.
=> Sort the release changelog by newest pull request first

pkg/oc/lib/groupsync/rfc2307/ldapinterface.go, pkg/oc/lib/groupsync/rfc2307/ldapinterface_test.go
Go 1.12's govet throws an error for the %s formatting directive used in these two places to format the ldap.Entry structure, this fixes it by instead using the distinguished name property of the group rather than the group struct itself.
Output of govet step of `make check` on go 1.12.1:
```
pkg/oc/lib/groupsync/rfc2307/ldapinterface.go:145:16: Errorf format %s has arg group of wrong type *github.com/openshift/origin/vendor/gopkg.in/ldap.v2.Entry
pkg/oc/lib/groupsync/rfc2307/ldapinterface_test.go:266:23: Errorf format %s has arg newTestGroup("", "cn=testUser,ou=users,dc=example,dc=com") of wrong type *github.com/openshift/origin/vendor/gopkg.in/ldap.v2.Entry
test/extended/cluster/metrics/metrics.go:41:3: struct field TestDuration repeats json tag "testDuration" also at metrics.go:28 …
```
=> Don't use the %s formatting directive for ldap.Entry type

test/extended/prometheus/prometheus.go
Pending alerts are not necessarily worth a test failure, firing alerts definitely are, but pending alerts can happen due to various reasons and are too flaky to fail on, in some cases it's even expected to see pending alerts from time to time. The fact that they may not be firing would validate that the `for` value has been chosen appropriately.
@mxinden @paulfantom @squat @s-urbaniak @metalmatze
=> test/extented/prometheus: Relax alert firing smoke test

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go, vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go, vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager_test.go
Pods were incorrectly allowed to transition from Failed to Succeeded
when terminated due to TerminatePod clearing the status on the containers
(unnecessarily).
Upstream fix is kubernetes/kubernetes#77870.
=> Bug 1694087: Do not reset container state when pod is deleted

test/integration/dockerregistryclient_test.go
```
=== RUN   TestIntegration/TestRegistryClientAPIv1
=== PAUSE TestIntegration/TestRegistryClientAPIv1
=== CONT  TestIntegration/TestRegistryClientAPIv1
--- FAIL: TestIntegration/TestRegistryClientAPIv1 (1.98s)
runner_test.go:129: FAILED TestRegistryClientAPIv1, retrying:
dockerregistryclient_test.go:246: openshift/schema-v1-test-repo was pushed by Docker 1.8.2
dockerregistryclient_test.go:207: error retrieving tag: server returned 503
=== OUTPUT
I0515 17:28:23.233141   26920 client.go:493] Getting repository openshift/origin-not-found from https://registry.hub.docker.com
I0515 17:28:23.440353   26920 client.go:493] Getting repository openshift/schema-v1-test-repo from https://registry.hub.docker.com
runner_test.go:125: 
dockerregistryclient_test.go:246: openshift/schema-v1-test-repo was …
```
=> disable registry v1 client test

cmd/sdn-cni-plugin/openshift-sdn_linux.go, pkg/network/admission/restrictedendpoints/endpoint_admission.go, pkg/network/node/ovscontroller.go
Block access to the EC2 metadata service from (non-hostNetwork) pods.
The EC2 metadata IP is actually in the IPv4 link-local address range, so technically it's incorrect for us to be forwarding packets addressed to that IP range out of the SDN anyway. So in addition to the iptables rules, this also adjusts the OVS flows to drop all packets destined for that range. (The iptables rules are still needed to block output via egress-router and multus interfaces.)
So, there are three parts:
- iptables rules to block access just to 169.254.169.254, for security
- OVS flows to block access to all of 169.254.0.0/16, for correctness
- RestrictedEndpointsAdmission changes to block creating services pointing to all of 169.254.0.0/16, for security and correctness
=> Restrict access to EC2 metadata

cmd/sdn-cni-plugin/openshift-sdn_linux.go
As seen in https://bugzilla.redhat.com/show_bug.cgi?id=1705686, there's a bug in the kernel where if you create a macvlan directly into a different namespace from its parent, and it ends up getting the same ifindex in that namespace as its parent has in its namespace, then if you ask about the macvlan's attributes via netlink later, the kernel won't report the parent link ifindex, so our golang netlink code leaves the field 0-initialized, and since we don't actually check that the field got set (because it's a macvlan, it *has to* have a parent) we end up using the "0" later and asking for information about a non-existent interface and getting back `EINVAL`.
There should eventually be a kernel fix, but this works around the problem on our side by assuming that if netlink reports that the …
=> Bug 1705686: Work around a kernel bug in the assign-macvlan code

test/extended/util/test.go
They are broken until a 1.14 kubelet lands
=> Disable NodeLease and RuntimeClass tests temporarily

test/extended/util/test.go
https://bugzilla.redhat.com/show_bug.cgi?id=1711687
Needs to be fixed before 4.2 upgrades can work.
=> Disable probe restart test because it is flaky under kubelet skew

test/extended/util/test.go
A significant chunk of tests disabled during the 1.13 rebase are still disabled, including storage tests.
Reenable all of them, triage what is broken, identify whether we have severe bugs against 4.1 due to teams not correctly restoring their tests.
=> Re-enable a large chunk of disabled tests

vendor/k8s.io/kubernetes/test/e2e/framework/networking_utils.go
The e2e tests that use this method don't need to report success, only failure.
This removes thousands of pointless lines of output from specific e2e tests that
use this framework.
This carry was lost during rebase to 1.14 because the method was refactored.
Example from upgrade tests:
```
May 19 18:13:23.055: INFO: cluster upgrade is failing: Cluster operator network is still updating
May 19 18:13:24.427: INFO: Poke("http://a1c8cff807a5811e99543121d93a203b-926229886.us-east-1.elb.amazonaws.com:80/echo?msg=hello"): success
May 19 18:13:26.460: INFO: Poke("http://a1c8cff807a5811e99543121d93a203b-926229886.us-east-1.elb.amazonaws.com:80/echo?msg=hello"): success
May 19 18:13:28.498: INFO: Poke("http://a1c8cff807a5811e99543121d93a203b-926229886.us-east-1.elb.amazonaws.com:80/echo?msg=hello"): …
```
=> UPSTREAM: <carry>: Disable excessive success logging in HTTP checking

test/e2e/upgrade/upgrade.go
Was printing -1 instead of what the actual value is.
=> Display the randomly chosen upgrade abort percentage

test/extended/router/headers.go, test/extended/router/metrics.go, test/extended/router/reencrypt.go, test/extended/router/router.go, test/extended/util/router.go
* `test/extended/router/headers.go`:
* `test/extended/router/metrics.go`:
* `test/extended/router/reencrypt.go`: Use `WaitForRouterServiceIP` and `WaitForRouterInternalIP` from the `exutil` package.
* `test/extended/router/router.go`: Move `waitForRouterInternalIP`, `waitForRouterExternalIP`, `routerShouldHaveExternalService`, `waitForRouterServiceIP`, and `waitForNamedRouterServiceIP` from here...
* `test/extended/util/router.go`: ...to here.  Rename `waitForRouterServiceIP` to `WaitForRouterServiceIP` and `waitForRouterInternalIP` to `WaitForRouterInternalIP`.
Some platforms may set an IP address and not set a host name on LoadBalancer services, so check both fields.
* `test/extended/router/router.go` (`waitForNamedRouterServiceIP`): Check both `IP` and `Hostname`.  Delete check for the …
=> text/extended: Check both IP and Hostname on LB

test/extended/cluster/cl.go, test/extended/cluster/utils.go
=> Cluster Loader: Add switch to handle yaml as podspec in config

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack.go, vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder_test.go
Now, to build a kubernetes client, provider uses only in-cluster config, but if kubelet is not running as a pod, then it doesn't work.
This commit adds an ability to specify a path to the kubeconfig file if necessary. If no value was provided, then the provider falls back to in-cluster config.
=> UPSTREAM: 77415: Allow to define kubeconfig file for OpenStack cloud provider

pkg/network/node/networkpolicy.go, pkg/network/node/ovscontroller.go
Kubernetes 1.12 adds beta support for SCTP and Openshift needs to support this. Adding SCTP to the list of acceptable network protocols
https://jira.coreos.com/browse/SDN-137
=> add support for SCTP in the Openshift SDN

images/cli-artifacts/Dockerfile.rhel, images/cli/Dockerfile.rhel, images/deployer/Dockerfile.rhel, images/hyperkube/Dockerfile.rhel, images/hypershift/Dockerfile.rhel, images/recycler/Dockerfile.rhel, images/sdn/Dockerfile.rhel, images/template-service-broker/Dockerfile.rhel, images/tests/Dockerfile.rhel
This ensure a newer cli image is used in all images.
Note, that this is in fact ignored on CI and downstream builds (these replace build image during build), but its nice to replace these for consistency. Also it may prevent confusion when doing local builds
=> images: use cli:4.2 as a base for all images

vendor/k8s.io/kubernetes/test/e2e/framework/util.go
Fixes the dump function to actually dump pod information.  We still want more, but this is probably all upstream will produce.
=> UPSTREAM: 77742: improve e2e namespace dumping on failure

pkg/oc/cli/admin/upgrade/upgrade.go, pkg/oc/cli/admin/upgrade/upgrade_test.go
The previous implementation would always return false if both `errA` and `errB` were nil, without actually comparing the valid-SemVer versions [rhbz#1713262][1].
/cherrypick release-4.1
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1713262
=> Bug 1713262: pkg/oc/cli/admin/upgrade: Fix and test sortSemanticVersions

pkg/build/controller/build/defaults/defaults.go, pkg/build/controller/build/defaults/defaults_test.go, pkg/build/controller/build/overrides/overrides.go, pkg/build/controller/build/overrides/overrides_test.go, pkg/build/controller/build/podcreationstrategy.go, pkg/build/controller/build/podcreationstrategy_test.go, test/extended/builds/start.go, test/integration/buildpod_admission_test.go
https://jira.coreos.com/browse/DEVEXP-341
=> avoid builds on non-linux nodes

pkg/oc/cli/admin/policy/who_can.go, pkg/oc/cli/policy/cani/cani.go
I took the same approach as upstream here: https://github.com/kubernetes/kubernetes/blob/bf79c7c7eedf2e79a721259cf0cbf519cdea623c/pkg/kubectl/cmd/auth/cani.go#L294-L301
although I wonder if we shouldn't either error out.
/assign @enj @sallyom
=> Bug 1699285: Add warning when unrecognized resource is found

vendor/k8s.io/kubernetes/pkg/kubelet/stats/BUILD, vendor/k8s.io/kubernetes/pkg/kubelet/stats/cri_stats_provider.go, vendor/k8s.io/kubernetes/pkg/kubelet/stats/cri_stats_provider_test.go, vendor/k8s.io/kubernetes/pkg/kubelet/stats/log_metrics_provider_test.go
Fixes `server returned HTTP status 500 Internal Server Error` for some kubelet endpoints.
Pick from master: https://github.com/openshift/origin/pull/22889
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1712645
=> UPSTREAM: 77426: Remove terminated pod from summary api

publishing-staging-rules.yaml
Merge after https://github.com/openshift/origin/pull/22915
This will make `update-deps` work after above land.
The openshift-apiserver branch should be ready.
/cc @deads2k
=> publishing: introduce openshift-apiserver to staging

pkg/cmd/openshift-apiserver/cmd.go, pkg/cmd/openshift-controller-manager/cmd.go, pkg/cmd/openshift-kube-apiserver/cmd.go
This prevents consumption of the old master-config.yaml so we can start pruning the usage down further.  I think we're down to networking and `oc` now.
=>  stop accepting old master config

publishing-rules.yaml
Without this fix, the publishing bot is publishing `master branch from openshift/origin repository to 1.13.4 branch in kube fork. That broke the publishing. This PR is:
1) Adding rule to publish "master" branch to kube fork "1.14.0"
2) Adding rule to publish "release-4.1" branch to kube fork "1.13.4"
=> update publishing rules for kube 1.13.4 and kube 1.14.0

HACKING.md
1. Removed outdated e2e instructions.
2. Referred contributors to the `test/extended/README`.
=> Fix guidance for e2e tests in HACKING.md

cmd/sdn-cni-plugin/openshift-sdn_linux.go
Backport of #22784 to 4.1. While the bug is also being fixed in the RHEL kernel, this ensures that the feature works before that is release, and for people on older RHEL 7 releases.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1715055
=> Bug 1715055: Work around a kernel bug in the assign-macvlan code [4.1]

test/extended/csrapprover/csrapprover.go, test/extended/include.go
It was previously possible to get the node-approver SA's token,
which lead to the attacker being able to use cluster-machine-approver
and kube cert API to issue a certificate for them that would normally
be used for nodes. Since that cert has "client auth", this leads to
an easy privilege escalation.
https://github.com/openshift/machine-config-operator/issues/731
@enxebre @enj @mrogers950 @openshift/sig-auth
=> test-extended: test MCS is blocked for pods and CMA does not approve random CSRs

publishing-staging-rules.yaml
This updates the publishing bot rules for origins staging by adding openshift-controller-manager and oauth-server.
/hold
=> staging: update publishing rules for oauth-server and controller manager

pkg/oc/cli/newapp/newapp.go, pkg/template/templateprocessing/template.go, pkg/template/templateprocessing/template_test.go
Remove `templateprocessing` dependency from new-app, making `templateprocessing` only depend on legacygroupification.
@soltysh i think this helps you.
=> template: remove templateprocessing dep from new-app

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest_test.go
While debugging an unusual timeout, the 30 second value is so common that it's harder to figure out exactly which timeout is involved. Changing this to something slightly different makes it possible to differentiate the values.
=> UPSTREAM: 78541: choose a more unique request timeout default

test/extended/cluster/cl.go, test/extended/cluster/context.go, test/extended/cluster/utils.go
The specific goals of this PR include:
- Enable user to specify `VIPERCONFIG` that is an absolute path
- Enable user to specify `VIPERCONFIG` file extension
- Improve robustness of the pod/template file location specified in the config
=> Improve Cluster Loader VIPERCONFIG handling and template file locating

pkg/autoscaling/admission/clusterresourceoverride/admission.go, pkg/autoscaling/admission/runonceduration/admission.go, pkg/cmd/server/apis/config/latest/helpers.go, pkg/image/apiserver/admission/imagepolicy/imagepolicy_test.go, pkg/network/admission/externalipranger/externalip_admission.go, pkg/network/admission/restrictedendpoints/endpoint_admission.go, pkg/project/apiserver/admission/requestlimit/admission.go, pkg/route/apiserver/admission/ingress_admission.go, pkg/scheduler/admission/podnodeconstraints/admission.go, test/integration/clusterresourceoverride_admission_test.go, test/integration/oauth_ldap_test.go
This is needed to unwind bad/legacy/unintended deps on the legacy configuration types.
=> use custom scheme for consuming admission configuration

hack/import-restrictions.json, pkg/authorization/apis/authorization/types.go, pkg/authorization/authorizer/scope/converter.go, pkg/authorization/authorizer/scope/converter_test.go, pkg/authorization/authorizer/scope/validate_test.go, pkg/authorization/authorizer/scopeauthorizer/authorizer.go, pkg/authorization/authorizer/scopeauthorizer/authorizer_test.go, pkg/authorization/authorizer/scopelibrary/clusterrole_describers.go, pkg/authorization/authorizer/scopelibrary/describers.go, pkg/authorization/authorizer/scopelibrary/user_describers.go, pkg/authorization/authorizer/scopelibrary/validation.go, pkg/authorization/authorizer/scopelibrary/validation_test.go, pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch_authorizer.go, pkg/oauth/apis/oauth/validation/validation.go, pkg/oauth/apiserver/registry/oauthaccesstoken/strategy.go, pkg/oauth/apiserver/registry/oauthauthorizetoken/strategy.go, pkg/oauth/apiserver/registry/oauthclientauthorization/strategy.go, pkg/oauthserver/oauth/handlers/grant.go, pkg/oauthserver/oauth/registry/grantchecker.go, pkg/oauthserver/osinserver/registrystorage/storage.go, pkg/oauthserver/scopecovers/scope.go, pkg/oauthserver/scopecovers/scope_test.go, pkg/oauthserver/server/grant/grant.go, pkg/serviceaccounts/oauthclient/oauthclientregistry.go, pkg/serviceaccounts/oauthclient/oauthclientregistry_test.go, test/integration/oauth_serviceaccount_client_events_test.go, test/integration/oauth_serviceaccount_client_test.go
This is needed to allow the descriptions to go into library-go for re-use between oauth-server, the openshift-apiserver, and kube-apiserver.
=>  split scopes into descriptions/validation and action

pkg/oc/cli/admin/mustgather/mustgather.go
The fallback image was only being used if the `must-gather` imagestream was available, but did not resolve.
=> Bug 1712637: use fallback when must-gather imagestream not available

cmd/sdn-cni-plugin/openshift-sdn_linux.go
Backport of #22784 to 3.11. While the bug is also being fixed in the RHEL kernel, this ensures that the feature works before that is release, and for people on older RHEL 7 releases.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1715056
=> Bug 1715056: Work around a kernel bug in the assign-macvlan code [3.11]

test/extended/operators/qos.go
@smarterclayton @derekwaynecarr @blomquisg 
Currently there are 23 components in violation
```
kube-*-operator/revision-pruner (library-go)
openshift-cluster-node-tuning-operator/tuned
openshift-cluster-storage-operator/cluster-storage-operator
openshift-console/downloads
openshift-image-registry/node-ca
openshift-marketplace/certified-operators
openshift-marketplace/community-operators
openshift-marketplace/marketplace-operator
openshift-marketplace/redhat-operators
openshift-monitoring/kube-state-metrics
openshift-monitoring/prometheus-adapter
openshift-monitoring/prometheus-k8s
openshift-monitoring/prometheus-operator
openshift-multus/multus
openshift-operator-lifecycle-manager/catalog-operator
openshift-operator-lifecycle-manager/olm-operator …
```
=> tests: extended: validation cluster components do not run as BestEffort pods

test/extended/util/test.go
After Prometheus starting making reasonable memory requests, the assumptions that the `SchedulerPreemption` tests make about the scheduled load on test nodes do not hold (i.e. less than 40% of capacity is scheduled).
Example e2e failure
https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-serial-4.2/598
```
Jun  4 15:35:22.846: INFO: At 2019-06-04 15:35:10 +0000 UTC - event for pod0-sched-preemption-low-priority: {default-scheduler } Scheduled: Successfully assigned sched-preemption-2604/pod0-sched-preemption-low-priority to ip-10-0-138-81.ec2.internal
Jun  4 15:35:22.846: INFO: At 2019-06-04 15:35:10 +0000 UTC - event for pod0-sched-preemption-low-priority: {default-scheduler } Preempted: by …
```
=> test/e2e: scheduling: disable preemption tests

glide.lock, glide.yaml, vendor/github.com/prometheus/client_golang/OWNERS, vendor/github.com/prometheus/client_golang/prometheus/registry.go, vendor/github.com/prometheus/client_golang/prometheus/registry_test.go
> checkMetricConsistency relies on labels being sorted. If they are not, it is sorting them, which is modifying a slice that is assumed to be immutable elsewhere. Even if they are sorted, sort.Sort might temporarily change order (even if no equal elements are in the slice) if there are more than 12 labels (where the implementation switches from ShellSort to HeapSort or QuickSort).
> Just using sort.Stable is not a solution as the immutable slice will still be mutated if it is not sorted (which can only happen with home-grown metric families, but it can still happen).
This is fixed in 4.2.
ref: https://github.com/prometheus/client_golang/pull/513
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1713098
=> Bug 171309: backport prometheus client_go race fix to 4.1

test/extended/builds/remove_buildconfig.go
When builds are deleted, ensure that the referenced ConfigMaps
containing CAs and runtime configs are also deleted.
=> Ensure Build ConfigMaps Are Removed

pkg/cmd/openshift-sdn/cmd.go, pkg/cmd/openshift-sdn/config.go, pkg/cmd/openshift-sdn/informers.go, pkg/cmd/openshift-sdn/proxy.go, pkg/network/networkconfig/network.go
This frees up the old internal config types to be used only for integration tests, which will be removed and allows us to fix our scheme to not include these.
=> move the SDN config to external types

test/extended/authorization/rbac/groups_default_rules.go, test/extended/include.go
The system:authenticated, system:authenticated:oauth and system:unauthenticated groups are automatically applied under certain circumstances.  This change adds a test to track the RBAC policy rules granted to those groups at the cluster scope.
=> Bug 1711533: rbac: add e2e to track rules applied to automatic groups

hack/import-restrictions.json, pkg/oc/cli/importer/appjson/appjson.go, pkg/oc/cli/process/process.go, pkg/oc/lib/newapp/cmd/newapp.go, pkg/oc/lib/newapp/cmd/template.go, staging/src/github.com/openshift/oc/pkg/helpers/template/templateprocessorclient/templateconfig.go
Only used by `oc`, straight move to staging.
/cc @soltysh
=> template: move processor client to oc

test/extended/operators/clusteroperators.go
ClusterOperators should have at least 2 relatedObjects defined to assist in problem determination:
- a namespace
- an operator config (this test just looks for "not a namespace")
Defining these related objects will assure that tools such as "must-gather" will collect the relevant resources.
=> e2e: ClusterOperators should specify related objects

test/extended/cluster/cl.go, test/extended/cluster/utils.go
Allows users to specify only pod image location or full podspec.
=> CL handle empty podspec with only image name defined

pkg/oc/lib/newapp/app/pipeline.go
The config API group with CRDs in that scheme broke kubectl edit.
=> newapp: don't install complete OpenShift API into kubectl scheme

vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
We are blind on graceful shutdown because cri-o does not log after that period has been initiated. This carry patch adds event creation against the namespace for all relevant steps during shutdown.
=> UPSTREAM: <carry>: create termination events

hack/import-restrictions.json, pkg/oc/lib/describe/describer.go, pkg/quota/apis/quota/convert.go
Replaced dependency on `github.com/openshift/origin/pkg/quota/apis/quota` with `github.com/openshift/oc/pkg/helpers/quota`.
=> remove oc dependency on origin/pkg/quota/apis/quota

pkg/oc/cli/admin/release/git.go
This gets us closer to [the new Prow plugin's][1]:
```
(?i)^.*Bug ([0-9]+):
```
adding case-insensitive matching with the [`(?i)`][2] and allowing prefixes with the [`.*?`][2] (non-greedy version in flight upstream, kubernetes/test-infra#12910).  Prefixes are useful because the cherry-pick bot generates pull-request subjects [like][4]:
```
[release-4.1] Bug 1715020: oauth validation: ...
```
and we want to allow that without requiring folks to manually adjust their pull-request subjects after using the cherry-pick bot.
Prefixes and case-insensitive matching make it slightly more likely that we get false-positives.  For example:
```console
$ git log --format=%s | grep -i 'bug [0-9][0-9]* *[:-]' | grep -iv '^bug '
Fix bug 1649227: 404 url
We should not be able to create a route when the …
```
=> pkg/oc/cli/admin/release/git: Case-insensitive bug regexp allowing prefixes

tools/rebasehelpers/commitchecker/validate.go, tools/rebasehelpers/util/git.go
Prevents commits like https://github.com/openshift/origin/pull/22572/commits/ce473d8e13f02834177da0f6cb9a42fd6b234cb2 from landing and force committers to configure `git` properly.
Sample output:
```
FAILURE after 0.000s: hack/verify-upstream-commits.sh:19: executing 'commitchecker' expecting success: the command returned the wrong error code
Standard output from the command:
Invalid email in commit 6f0e6c3b10: "root@dhcp-140-138.nay.redhat.com"
Standard error from the command:
Found commits with invalid commit author
[ERROR] hack/lib/cmd.sh:10: `return "${return_code}"` exited with status 1.
[ERROR] hack/verify-upstream-commits.sh exited with code 1 after 00h 00m 04s
```
=> tools: verify the commit author

vendor/k8s.io/kubernetes/pkg/kubeapiserver/admission/config.go, vendor/k8s.io/kubernetes/pkg/kubeapiserver/admission/patch_restmapper.go
if the SDN is down, then the discovery check for GC admission permission checks on blockownerdeletion will fail.  This includes a small list of hardcoded mappings from that admission plugin that allow us to rebootstrap the SDN without a working SDN.
For a real fix, I plan to open a KEP to change the ownerref to include a resource which would be used in preference to kind to avoid a lookup.
/assign @sttts
=> Bug 1714699: hardcode a small list of mappings to allow SDN to rebootstrap

test/extended/oauth/well_known.go
This test checks that authorization_endpoint is
* accessible
* returns 200
* properly configured 
`oc get --raw /.well-known/oauth-authorization-server` authorization_endpoint matches 
openshift-authentication route/oauth-openshift spec.host + `oauth/authorize`
broke this out from https://github.com/openshift/origin/pull/23024 there are comments there regarding this test
=> add well-known endpoint e2e

pkg/admission/admissiontimeout/decorator.go, pkg/admission/admissiontimeout/timeoutadmission.go, pkg/admission/admissiontimeout/timeoutadmission_test.go, pkg/cmd/openshift-apiserver/openshiftapiserver/config.go, pkg/cmd/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
Adding a limit for individual admission plugins of 13 seconds so we don't wait forever and to see if I can catch https://bugzilla.redhat.com/show_bug.cgi?id=1714699
/hold
holding until I actually try it
/assign @sttts @p0lyn0mial
=> add timeout decorator for admission and limit to 13 seconds

pkg/cmd/openshift-sdn/cmd.go, pkg/cmd/openshift-sdn/sdn.go, pkg/network/node/node.go, pkg/network/node/pod.go, pkg/network/node/pod_test.go, pkg/network/node/runtime.go
We only support CRI-O now, so drop the HostPort stuff that was needed with dockershim
=> Drop CRI/CNI configurability from openshift-sdn

pkg/network/common/dns.go, pkg/network/common/dns_test.go
Before this change, zero-TTL records would cause the `EgressDNS` controller to
query for updates to those records in a tight loop with no rate limiting.
Prevent the flooding behavior by defaulting TTL to 30 minutes when the provided
TTL is zero
An alternative considered was to store the true TTL internally but enforce a
minimum sync interval through `EgressDNS.GetMinQueryTime`, which may also be
useful in its own right as a hedge against future bugs. Using a rate limited
work queue would be another possibility.
=> Bug 1709178: Prevent egress DNS request flooding

staging/src/github.com/openshift/oc/pkg/cli/admin/release/git.go
Reverts openshift/origin#23051
=> Revert "pkg/oc/cli/admin/release/git: Case-insensitive bug regexp allowing prefixes"

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/conversion.go
We mutated the input OpenAPI schema in-place while building the go-openapi output schema. We assumed that we own that input object, but it comes from a lister. Hence, the mutation made the cache inconcistent for a short time and produced races.
=> apiextensions: don't mutate input schema on OpenAPI publishing

test/extended/cli/mustgather.go
=> Bug 1718052: must-gather: make sure audit logs do not contain OAuth tokens

vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller_test.go
We should not stomp on the discovery transport with the proxy
transport as the proxy transport is always unauthenticated.  We need
to make sure these calls are always authenticated as system:masters
to prevent any forbidden errors.  Thus we only use the proxy
transport to set the dial context.
This matches the logic upstream (while maintaining our dynamic cert
reloading logic):
https://github.com/kubernetes/kubernetes/blob/d873167e8f816f5f83846bc4587c3047452293bd/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go#L114-L116
=> UPSTREAM: 75126: available controller: do not stomp transport

vendor/k8s.io/kubernetes/test/e2e/upgrades/services.go
In heavily contended AWS accounts, it can take more than 2m for an
LB to get created and pick up entries.
Should address bug 1690087
/cherrypick release-4.1
=> Increase the wait for the service upgrade e2e test for LB

vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go
Bug # https://bugzilla.redhat.com/show_bug.cgi?id=1671364
=> UPSTREAM: 78475: Increase device discovery timeout to 30seconds/equal to checker_timeout

test/extended/util/cli.go
This check is inconsistent with the behavior of the e2e framework
when running in a container (it uses in cluster config). Remove
the check so that `openshift-tests -h` does not panic when KUBECONFIG
is unset.
=> Do not panic when running openshift-tests without KUBECONFIG set

publishing-staging-rules.yaml
history in https://github.com/openshift/openshift-controller-manager is fixed, so we're ready for this.
=> publish to master

vendor/k8s.io/kubernetes/test/e2e/upgrades/services.go
In heavily contended AWS accounts, it can take more than 2m for an
LB to get created and pick up entries.
Cherrypicked from #23160
=> Bug 1690087: Increase the wait for the service upgrade e2e test for LB

test/extended/util/test.go
Reenable node lease tests since we have a 1.14 kubelet now.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1711569
/cc @sjenning
=> Bug 1711569: reenable node lease tests

staging/src/github.com/openshift/sdn/pkg/openshift-sdn/config.go, staging/src/github.com/openshift/sdn/pkg/openshift-sdn/proxy.go
We were trying to read an `apiVersion: kubeproxy.config.k8s.io/v1alpha1` file into an internal-type `KubeProxyConfiguration`. We need to read in the external type and then convert. Fortunately there was already code in kube-proxy for doing this, we just weren't using it because I'd copied the `node-config.yaml`-reading code instead.
(Tested this time; since reading the command-line is the first thing it does, you can just run the binary locally to test that part...)
/assign @squeed
=> Fix openshift-sdn --proxy-config parsing

test/extended/operators/clusteroperators.go
See: https://github.com/openshift/cluster-node-tuning-operator/pull/64
=> Bug 1717739: ClusterOperators should specify related objects

test/extended/util/test.go
Reverts openshift/origin#23198
NodeLease and Runtimeclass tests are failing:
https://prow.svc.ci.openshift.org/?job=release-openshift-ocp-installer-e2e-aws-4.2
/cc @sjenning
=> Revert "Bug 1711569: reenable node lease tests"

cmd/openshift-tests/openshift-tests.go, test/extended/util/azure/config_file.go
Single test can be run with 
`TEST_PROVIDER='azure' _output/local/bin/linux/amd64/openshift-tests run-test "[sig-storage] Zone Support Verify dynamically created pv with multiple zones specified in the storage class, shows both the zones on its labels [Suite:openshift/conformance/parallel] [Suite:k8s]" --dry-run`
test suite can be run with
`_output/local/bin/linux/amd64/openshift-tests run openshift/conformance/parallel --provider='azure'`
The cloud config file is fetched from the cluster, and creds are also setup to run this test from outside the cluster.
=>  cmd/openshift-tests: load the configuration for test from cluster when provider is azure

test/extended/operators/clusteroperators.go
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1717640
Related: https://github.com/openshift/cluster-storage-operator/pull/37
=> Bug 1717640: include cluster-storage-operator when testing status.relatedObjects

test/extended/authorization/rbac/groups_default_rules.go
- Add system:authenticated exception for CRDs used by console for extensions
These 3 CRDs:
- `consoleclidownloads`
- `consolelinks`
- `consolenotifications`
Are intended to be used by other operators to enhance the console experience.  As such, they can be requested by any logged in user.  For example, A cluster admin could install an operator that wants to add additional links to the console menu.  Users of the console should be able to access these links to use the new functionality.
The console team is exploring ways to instead proxy these requests through the console backend, using the console Service Account token, instead of needing special bindings to `system:authenticated`.  
Discussion regarding the reasonableness of this exception: 
- …
=> Exception for console extension CRDs in extended tests

hack/import-restrictions.json, test/extended/bootstrap_user/bootstrap_user_login.go, test/extended/templates/helpers.go, test/extended/templates/openservicebroker/api/helpers.go, test/extended/templates/openservicebroker/api/types.go, test/extended/templates/openservicebroker/api/validation.go, test/extended/templates/openservicebroker/api/validation_test.go, test/extended/templates/openservicebroker/client/client.go, test/extended/templates/templateservicebroker_bind.go, test/extended/templates/templateservicebroker_e2e.go, test/extended/templates/templateservicebroker_security.go
this copies an API and client to the e2e tests so that we no longer carry a direct TSB dependency.  It tightens and simplifies the verify-imports further to continue restricting what we can rely upon.
=> remove TSB dependency from origin

examples/examples_test.go, test/extended/authorization/rolebinding_restrictions.go, test/integration/authorization_test.go, test/integration/deploy_defaults_test.go, test/integration/front_proxy_test.go, test/integration/image_layers_mocks.go, test/integration/imagestream_admission_test.go, test/integration/imagestream_test.go, test/integration/newapp_test.go, test/integration/oauth_external_test.go, test/integration/project_test.go, test/integration/restrictusers_test.go, test/integration/scopes_test.go, test/integration/webhook_token_auth_test.go, tools/buildanalyzer/cmd/buildanalyzer.go, tools/etcdhelper/etcdhelper.go
To avoid unpleasant rebase dependencies, we need to move openshift-apiserver usage from e2e tests.
=> snip easy openshift-apiserver test deps

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go, vendor/k8s.io/kubernetes/pkg/kubelet/pod/mirror_client.go, vendor/k8s.io/kubernetes/pkg/kubelet/pod/pod_manager.go, vendor/k8s.io/kubernetes/pkg/kubelet/pod/testing/fake_mirror_client.go, vendor/k8s.io/kubernetes/pkg/kubelet/pod/testing/mock_manager.go
aka UPSTREAM: 79147: Do not delete an incorrect pod when replacing a mirror pod
=> Bug 1712528 - oc delete of a static pod results in multiple attempts to re-create the mirror pod before succeeding

staging/src/github.com/openshift/oauth-server/pkg/oauthserver/oauth_apiserver.go
This disables the post start hook in the 4.x code paths.  All of this code should be deleted but this unblocks the various efforts to move integration to e2e.
=> Let the authentication operator manage OAuth clients in 4.x

images/kube-proxy/Dockerfile.rhel, images/kube-proxy/scripts/ip6tables, images/kube-proxy/scripts/ip6tables-restore, images/kube-proxy/scripts/ip6tables-save, images/kube-proxy/scripts/iptables, images/kube-proxy/scripts/iptables-restore, images/kube-proxy/scripts/iptables-save
Turns out using the scripts from sdn works in OSBS but not ART, huh.
=> images/kube-proxy: copy iptables wrapper scripts from sdn

vendor/k8s.io/kubernetes/pkg/proxy/BUILD, vendor/k8s.io/kubernetes/pkg/proxy/endpoints.go, vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go, vendor/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go, vendor/k8s.io/kubernetes/pkg/proxy/metrics/metrics.go, vendor/k8s.io/kubernetes/pkg/proxy/service.go, vendor/k8s.io/kubernetes/pkg/proxy/winkernel/metrics.go, vendor/k8s.io/kubernetes/pkg/proxy/winkernel/proxier.go
This adds some useful metrics around pending changes and last successful
sync time.
The goal is for administrators to be able to alert on proxies that, for
whatever reason, are quite stale.
backport these new metrics in order to continue work on [SDN-405](https://jira.coreos.com/browse/SDN-405)
=> UPSTREAM: 74027: proxy: add some useful metrics

cmd/openshift-tests/openshift-tests.go, cmd/openshift-tests/upgrade.go, test/e2e/upgrade/upgrade.go, test/extended/cluster/cl.go, test/extended/cluster/cm.go, test/extended/util/test.go, vendor/k8s.io/kubernetes/test/e2e/e2e_test.go, vendor/k8s.io/kubernetes/test/e2e/framework/config/config.go, vendor/k8s.io/kubernetes/test/e2e/framework/config/config_test.go, vendor/k8s.io/kubernetes/test/e2e/framework/test_context.go, vendor/k8s.io/kubernetes/test/e2e/framework/viperconfig/viperconfig.go, vendor/k8s.io/kubernetes/test/e2e/instrumentation/logging/BUILD, vendor/k8s.io/kubernetes/test/e2e/instrumentation/logging/generic_soak.go, vendor/k8s.io/kubernetes/test/e2e/instrumentation/monitoring/BUILD, vendor/k8s.io/kubernetes/test/e2e/instrumentation/monitoring/cadvisor.go, vendor/k8s.io/kubernetes/test/e2e/lifecycle/cluster_upgrade.go, vendor/k8s.io/kubernetes/test/e2e/lifecycle/patch_flagaccess.go, vendor/k8s.io/kubernetes/test/e2e/patch_from_e2e_testfile.go, vendor/k8s.io/kubernetes/test/e2e/storage/drivers/csi_objects.go
This revert will be long term debt if we cannot address it.  I'm reverting the revert here so that I can see what I've got in a prettier diff.
=> remove a revert on the upstream test infrastructure

staging/src/github.com/openshift/sdn/pkg/openshift-sdn/cmd.go
@anuragthehatter 
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1710652
=> sdn: fix spelling error in log message

hack/lib/constants.sh, images/oauth-server/Dockerfile.rhel
This is in preparation of migrating oauth-server out of staging
/cc @tnozicka
=> build oauth-server binary into a separate image, split from hypershift

Makefile, cmd/hypershift/main.go, staging/src/github.com/openshift/openshift-apiserver/cmd/openshift-apiserver/main.go, staging/src/github.com/openshift/openshift-apiserver/pkg/cmd/openshift-apiserver/cmd.go
* Added new `openshift-apiserver` binary.
* `hypershift openshift-apiserver` equivalent is `openshift-apiserver start`
* `hypershift openshift-apiserver` deprecated & hidden
=> build stand-alone openshift-apiserver binary

Makefile, cmd/hypershift/main.go, staging/src/github.com/openshift/openshift-controller-manager/cmd/openshift-controller-manager/main.go, staging/src/github.com/openshift/openshift-controller-manager/pkg/cmd/openshift-controller-manager/cmd.go
* Added new `openshift-controller-manager` binary.
* `hypershift openshift-controller-manager` equivalent is `openshift-controller-manager start`
* `hypershift openshift-controller-manager` deprecated & hidden
=> build stand-alone openshift-controller-manager binary

test/extended/util/azure/config_file.go, test/extended/util/test.go
Reverts openshift/origin#23245
Appears to have caused a significant CPU spike, which is likely due to the new skip rules being treated as wildcards (there's an O(N^2) factor in skip rules if you're not careful.)
=> Revert "test/extended/util: allow tests to be skipped based on platform"

test/extended/operators/images.go, test/extended/util/client.go
For now, we have to check if these images are downstream for each sub-team. I have intended to check the `image` labels, but I didn't find the related options. So, I added related checks steps in here. I'm not sure if it's appropriate for upstream. @sosiouxme @vikaslaad Could you help take a review? Thanks! cc: @scolange @bandrade @cuipinghuo @chengzhang1016 @dongboyan77 @zihantang-rh @emmajiafan
=> check if the containers' image is downstream

vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/apiserver/OWNERS, vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver.go, vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver_test.go, vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validation_wrapper.go, vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/customresourcevalidationregistration/cr_validation_registration.go
UPSTREAM: <carry>: add apiserver.config.openshift.io validation to prevent overriding internal LB SNI settings
The internal LB is used by kubelets which cannot update their trust. This means that if the internal LB certificate is changed, the cluster loses connectivity.  We auto-rotate the serving cert, but not the corresponding trust for it.
/assign @sttts
=> UPSTREAM: <carry>: add apiserver.config.openshift.io validation to prevent overriding internal LB SNI settings

staging/src/github.com/openshift/openshift-apiserver/pkg/project/apiserver/registry/projectrequest/delegated/delegated.go
This change will help debugging problems like https://bugzilla.redhat.com/show_bug.cgi?id=1664638 where the resource failed to create because of mapping error but we don't know which resource it was.
/cc @deads2k 
/cc @sttts
=> project: improve error reported when template objects failed to create

staging/src/github.com/openshift/oc/pkg/helpers/describe/describer.go
In some cases the docker image metadata does not fill the ContainerConfig (possible bug in importer?). According to Docker API, the Config should be always set as received from the client.
This fix will return the later for describe but fallback when the Config is not set to ContainerConfig.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1726374
@soltysh @adambkaplan @dmage this need more investigation.
=> oc: fix describer for docker images

staging/src/github.com/openshift/oc/pkg/cli/image/info/info.go, staging/src/github.com/openshift/oc/pkg/helpers/describe/describer.go
Users may want to compare a single layer digest against another image,
but if we don't print the layer they can't do that. Fix the image
describer to show info about the single layer like we would with
multiple layers:
```
Image Size: 59.51MB in 1 layer
Layers:     59.5MB sha256:abcdef1434
```
=> Single layer images should still print layer digest

vendor/k8s.io/kubernetes/test/e2e/framework/kubelet_stats.go
Fixes a flake in kubelet_stats.go
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1679612
=> UPSTREAM: 1679612: kubelet_stats: fix potential e2e crash dereferencing CPU

test/extended/cli/mustgather.go
The "oc adm must-gather" test in the e2e-vsphere suite is failing because the `audit_logs/openshift-apiserver.audit_logs_listing` file is only 78 bytes while the test is expecting the size to be at least 100 bytes. This commit changes the minimum required size to 50 bytes.
https://bugzilla.redhat.com/show_bug.cgi?id=1710973
/cc @sanchezl
=> Bug 1710973: reduce minimum size of expected files in must-gather tests

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go, vendor/k8s.io/kubernetes/pkg/kubelet/pod/mirror_client.go, vendor/k8s.io/kubernetes/pkg/kubelet/pod/pod_manager.go, vendor/k8s.io/kubernetes/pkg/kubelet/pod/testing/fake_mirror_client.go, vendor/k8s.io/kubernetes/pkg/kubelet/pod/testing/mock_manager.go
UPSTREAM: 79147: Do not delete an incorrect pod when replacing a mirror pod
=> Bug 1723553: oc delete of a static pod results in multiple attempts to re-create the mirror pod before succeeding

test/extended/project/unprivileged_newproject.go, test/integration/unprivileged_newproject_test.go
part of #23320, splitting to find flake.
=> move project request tests to e2e

test/extended/cluster/cl.go
Undefined `VIPERCONFIG` is now `""`. Small logging change for clarity.
First step to fix: https://github.com/openshift/origin/issues/23195
=> Handle new VIPERCONFIG value for built-in config

test/extended/cluster/cl.go, test/extended/testdata/bindata.go, test/extended/testdata/cluster/master-vert.yaml, test/extended/testdata/cluster/quickstarts/cakephp-mysql.json, test/extended/testdata/cluster/quickstarts/dancer-mysql.json, test/extended/testdata/cluster/quickstarts/django-postgresql.json, test/extended/testdata/cluster/quickstarts/nodejs-mongodb.json, test/extended/testdata/cluster/quickstarts/rails-postgresql.json
Cluster Loader uses an additional `IDENTIFIER` parameter in the template that is not in the default quickstarts, which causes breakage as described in https://github.com/openshift/origin/issues/23195.
Rather than modifying the existing quickstarts, I've just added our own for this. This PR also needs the changes in https://github.com/openshift/origin/pull/23306 to fix the issue.
=> Add new CL quickstarts, new CL config and updated bindata

test/extended/cluster/cl.go, test/extended/cluster/utils.go
Wait for pods outside of tuningset functionality. Fixes https://github.com/openshift/origin/issues/23308.
=> Add pod wait upon object creation

test/extended/operators/olm.go
Removes the assumption that at least one instance of each OLM kind exists on a cluster for OLM tests.
This borrows code from @jianzhangbjz's PR (#23224).
=> Don't assume instances of OLM kinds exist

staging/src/github.com/openshift/oc/pkg/cli/admin/release/info.go
This allows someone to click directly to the version of code available,
instead of having to go to the changelog.
=> Link the component image in a changelog to the GitHub source view

test/extended/oauth/htpasswd.go, test/extended/testdata/bindata.go, test/extended/testdata/oauthserver/cabundle-cm.yaml, test/extended/testdata/oauthserver/oauth-network.yaml, test/extended/testdata/oauthserver/oauth-pod.yaml, test/extended/testdata/oauthserver/oauth-sa.yaml, test/extended/util/client.go, test/extended/util/oauthserver/helpers.go, test/extended/util/oauthserver/oauthserver.go
This PR makes it possible to allow deploying a separate OAuth server for e2e tests
/assign @sallyom 
It ss a part of https://github.com/openshift/origin/issues/23258
=> test/e2e: add deploying separate OAuth server to util

test/extended/util/test.go, vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1716311
=> UPSTREAM: 78697: Skip multi-node PV test when pods scheduled on the same node

test/extended/builds/run_policy.go
I met several times that build has been running when expects pending.
Add running state here to make the scenario more stable
=> Append build running state for serial runpolicy

vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validation_wrapper.go, vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/customresourcevalidator.go
The admission stack was never calling the `Validate` method of the embedded plugin.
=> Fix APIServer CRD admission

test/extended/builds/new_app.go
Test flakes due to image pull auth errors.
Temporarily increasing build log level to capture pull specs and pull auth.
=> Bug 1721380: Increase logs on flaking build test

test/extended/testdata/bindata.go, test/extended/testdata/ldap/ldapserver-scripts-cm.yaml
The groupsync test data was failing to load completely since the testPerson schema was missing.
=> Load testPerson schema for ldap tests

staging/src/github.com/openshift/sdn/cmd/network-controller/network-controller.go
Extracted from hypershift, necessary for staging split.
=> Add sdn network-controller

test/extended/crdvalidation/apiserver.go, test/extended/include.go, vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver.go
Add validation for the new `additionalCORSAllowedOrigins` field in APIServer CRD
Running `glide update` always ended-up with a SIGSEGV for me so I just picked the API for the bump.
=> APIServer CRD: add additionalCORSAllowedOrigins validation

cmd/hypershift/main.go
Now that cluster-authentication-operator is using openshift/origin-oauth-server:v4.2 image,
we no longer need openshift-osinserver within hypershift command.
=> Remove osinserver from hypershift command

test/extended/authorization/rbac/groups_default_rules.go
RE https://github.com/openshift/console-operator/pull/246
Extending initial exceptions in #23231
=> Add ConsoleLogLinks to exceptions list for Console CRDs

test/extended/cluster/cl.go
Currently we are trying to compare all pods in a namespace to the count of running pods with a label. This fixed the expectation so that when we have other pods that are managed by higher level objects like builds or deployments they don't cause pod wait timeout.
=> Wait for pods that have the correct label

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/metadata.go, vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack.go, vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_instances.go
This commit improves the reading of OpenStack's cloud provider configuration from a secret. In some cases, if kubeConfigPath parameter specifies a configuration file, which is created by kubelet itself as a result of bootstrap (i.e. /var/lib/kubelet/kubeconfig), then the initialization of the cloud provider fails, because this file has not yet been created on the local file system.
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#bootstrap-initialization
To solve this problem we transfer the real initialization of the provider from the init() function, which is called at the stage of modules import, to the functions from the Provider's top-level interface. https://github.com/kubernetes/cloud-provider/blob/master/cloud.go#L42-L62
This allows to …
=> UPSTREAM: 79221: Ensure that OpenStack cloud provider is initialized before making a call

test/extended/bootstrap_user/bootstrap_user_login.go
Even if the bootstrap user test fails, we must restore the cluster back to its original state.
=> Bug 1731278: Always restore kube:admin secret

vendor/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go
We can fail to observe ready because pod completes so fast.
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.1/978
=> UPSTREAM: 80393: Prevent a flake in a pod e2e test

test/extended/etcd/etcd_storage_path.go, test/extended/etcd/etcd_test_runner.go, test/extended/etcd/generated_copy.go, test/extended/include.go
```diff
1c1
< package integration
---
> package etcd
3a4
> 	"bytes"
12a14
> 	g "github.com/onsi/ginkgo"
20a23
> 	"k8s.io/apimachinery/pkg/util/errors"
33,34d35
< 	testserver "github.com/openshift/origin/test/util/server"
< 	"github.com/openshift/origin/test/util/server/deprecated_openshift/etcd"
36a38
>
204c206,222
< // TestEtcd3StoragePath tests to make sure that all objects are stored in an expected location in etcd.
---
> type helperT struct {
> 	g.GinkgoTInterface
> 	errs []string
> }
>
> func (t *helperT) Errorf(format string, args ...interface{}) {
> 	t.errs = append(t.errs, fmt.Sprintf(format, args...))
> }
>
> func (t *helperT) done() {
> 	if len(t.errs) == 0 {
> 		return
> 	}
> 	t.GinkgoTInterface.Errorf("test failed:\n%s", …
```
=> Port etcd storage path test to e2e

test/extended/images/append.go, test/extended/images/imagestream.go, test/extended/images/oc_copy.go, test/extended/images/prune.go, test/extended/operators/images.go, test/extended/operators/oc_copy.go, test/extended/router/oc_copy.go, test/extended/router/scoped.go, test/extended/util/client.go, test/extended/util/oauthserver/helpers.go, test/extended/util/oauthserver/oauthserver.go, test/extended/util/oauthserver/tokencmd/basicauth.go, test/extended/util/oauthserver/tokencmd/basicauth_test.go, test/extended/util/oauthserver/tokencmd/multi.go, test/extended/util/oauthserver/tokencmd/negotiate.go, test/extended/util/oauthserver/tokencmd/negotiate_helpers.go, test/extended/util/oauthserver/tokencmd/negotiator_gssapi_unsupported.go, test/extended/util/oauthserver/tokencmd/negotiator_sspi_unsupported.go, test/extended/util/oauthserver/tokencmd/request_token.go, test/extended/util/oauthserver/tokencmd/request_token_test.go, test/extended/util/oc_copy.go, test/extended/util/test.go
This removes our final `oc` links from e2e.  Some files were copied.  The deepest copy was for getting tokens. We may want to put that in library-go someday, but for now this copy holds us and we know that the API it uses can't change.
=> remove e2e-test deps on oc

test/extended/cluster/clt.go, test/extended/cluster/context.go, test/extended/cluster/utils.go
This tests exists to speed up tests like master vertical which have a large number of projects and large number of templates within them.
=> Add CL simple concurrency test for template creation

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go
This namespace will soon be used to store etcd encryption keys.  Deleting it would cause the cluster to be unrecoverable.
=> UPSTREAM: <carry>: Prevent deletion of openshift-config-managed

test/extended/util/test.go
revert https://github.com/openshift/origin/pull/22865 now that 4.2 kubelet is in place
xref https://bugzilla.redhat.com/show_bug.cgi?id=1711687#c3
=> revert: Disable probe restart test because it is flaky under kubelet skew

test/extended/util/test.go
Allows better filtering during debug, this is a regression from previous code (not sure when this regressed, it's at least 1 week old).
=> test: Ensure e2e tests create a namespace prefixed with e2e-

vendor/k8s.io/kubernetes/openshift-kube-apiserver/kubeadmission/register.go
changes the order of admission plugins so that RQ is applied before CRQ.
This prevents a scenario where a resource cannot be created due to RQ limits but CRQ would allow for it because it doesn't know about RQ constraints.
=> UPSTREAM: <carry>: run ClusterResourceQuota before ResourceQuota

images/sdn/Dockerfile.rhel
This is a backport of https://github.com/openshift/sdn/pull/7 into 4.1
SDN-488
https://jira.coreos.com/browse/SDN-488
bug 1731913
https://bugzilla.redhat.com/show_bug.cgi?id=1731913
=> [release-4.1]Bug 1731913: Add arping to openshift-sdn image

test/extended/etcd/etcd_storage_path.go
nothing should be using internal types anymore
=> remove internal api usage from test

test/extended/cmd/cmd.go
at 2 minutes e2e-cmd is flaking.  Let's see if setting it up to 5 minutes gives us consistent passing.
=> run the e2e-cmd pods longer

test/extended/cmd/cmd.go
The only failing e2e-cmd test we have is basicresources.  I fixed the current failure, but let's disable the whole thing so we can enable the rest of the e2e-cmd tests.
=> skip test/cmd/basicresources so we can get the rest enabled

.travis.yml, hack/verify-upstream-commits.sh, test/integration/dockerregistryclient_test.go
Otherwise builds fail with:
`/home/travis/gopath/src/github.com/openshift/origin/hack/lib/constants.sh: line 129: OS_GIT_MAJOR: unbound variable`
because travis apparently doesn't fetch tags by default.
=> Fix CI failures due to travis, broken tests, and missing commit verify branch name

pkg/network/node/vxlan_monitor.go
=> Bug 1732486: Fix egress monitoring for some rare corner cases.

.travis.yml, pkg/quota/admission/clusterresourcequota/admission.go
changes ClusterResourceQuota to be a validating admission plugin so that the correct order of admission is preserved, that is RQ is before CRQ.
this prevents a scenario where a resource cannot be created due to RQ limits but CRQ would allow for it because it doesn't know about RQ constraints.
=> UPSTREAM: <carry>: run ResourceQuota before ClusterResourceQuota

cmd/openshift-tests/e2e.go, cmd/openshift-tests/openshift-tests.go, test/extended/util/test.go, vendor/k8s.io/kubernetes/test/e2e/storage/external/external.go, vendor/k8s.io/kubernetes/test/e2e/storage/external/external_test.go
Goal: create test definitions for installed CSI driver.
Usage: `TEST_CSI_DRIVER_FILES=my-csi-driver.yaml openshift-tests run openshift/csi` in a custom prow job.
See  k8s.io/kubernetes/test/e2e/storage/external for yaml file definition and upstream usage
=> Add suite for CSI tests

test/e2e/dr/common.go, test/e2e/dr/quorum_restore.go, test/e2e/dr/restore_from_snapshot.go, test/e2e/upgrade/upgrade.go, test/extended/testdata/bindata.go, test/extended/testdata/disaster-recovery/restore-etcd.sh, test/extended/testdata/disaster-recovery/rollback-A.yaml, test/extended/testdata/disaster-recovery/rollback-B.yaml, test/extended/testdata/disaster-recovery/ssh-bastion/clusterrole.yaml, test/extended/testdata/disaster-recovery/ssh-bastion/clusterrolebinding.yaml, test/extended/testdata/disaster-recovery/ssh-bastion/deployment.yaml, test/extended/testdata/disaster-recovery/ssh-bastion/namespace.yaml, test/extended/testdata/disaster-recovery/ssh-bastion/role.yaml, test/extended/testdata/disaster-recovery/ssh-bastion/rolebinding.yaml, test/extended/testdata/disaster-recovery/ssh-bastion/service.yaml, test/extended/testdata/disaster-recovery/ssh-bastion/serviceaccount.yaml, test/extended/testdata/disaster-recovery/ssh-bastion/sshd_config, test/extended/testdata/disaster-recovery/update_route_53.py
This adds new disruptive tests for DR scenarios: etcd snapshot restore (part of # #23080) and etcd quorum restore
TODO:
```
No user exists for uid 1475100000
```
=> tests: add e2e tests to verify DR scenarios

hack/lib/constants.sh
Per https://jira.coreos.com/browse/ART-666 4.2 should no longer be disabling openssl linking.
@stevekuznetsov @smarterclayton I am guessing you will probably not want to do this until the latest golang-builder is being used in CI so that dynamic linking of openssl fails over as intended to static linked crypto. That builder is ready when you are.
=> hack/lib/constants.sh: remove no_openssl flag

examples/jenkins/OWNERS, examples/jenkins/pipeline/bluegreen-pipeline.yaml, examples/jenkins/pipeline/samplepipeline.yaml, test/extended/testdata/bindata.go
Hi team,
Jenkins e2e test are failing [1] because of nodejs:4 imagestreamtag was removed in openshift/cluster-samples-operator#158 
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_jenkins/895/pull-ci-openshift-jenkins-master-e2e-aws-jenkins/349
@mfojtik or @jupierce can you PTAL ?
=> Fix e2e test: bump nodejs version after eol trimmed images

test/extended/cluster/utils.go
Cluster Loader needs to read YAML, so we convert YAML to JSON before decoding.
=> CL: Support YAML templates

vendor/k8s.io/kubernetes/pkg/kubelet/metrics/collectors/log_metrics.go, vendor/k8s.io/kubernetes/pkg/kubelet/metrics/collectors/log_metrics_test.go
Upstream pick
[buildPodRef](https://github.com/kubernetes/kubernetes/blob/946087b422e38dba37a8418860b0f2ede8597394/pkg/kubelet/stats/cadvisor_stats_provider.go#L267) creates a unique key with the {podName, namespace, UID}
tuple. By omitting the UID in the metric, duplicate metrics can be sent
to prometheus causing 500's on the /metrics endpoint.
This change adds the UID to the `kubelet_container_log_filesystem_used_bytes` metric so it is unique and doesn't cause errors like:
```
"An error has occurred during metrics collection:\n\ncollected metric kubelet_container_log_filesystem_used_bytes label:<name:\"container\" value:\"prometheus\" > label:<name:\"namespace\" value:\"openshift-monitoring\" > label:<name:\"pod\" value:\"prometheus-k8s-0\" > gauge:<value:40960 >  was collected before …
```
=> UPSTREAM: 80657: add UID to kubelet_container_log_filesystem_used_bytes metric

test/extended/prometheus/prometheus.go
We are improving metric names in the MAO in the [PR](https://github.com/openshift/machine-api-operator/pull/356/commits/93ba99c41a290b6b792b2fc536ad8c44369f2426#diff-7cbe8e056d62a2de30c7066e359bd9c9R20), to get the CI passing on this PR, we need to use a metric in the e2e, name of which is not being changed.
=> Change the metric name in the MAO metrics e2e

test/extended/machines/scale.go, test/extended/machines/workers.go
Continuation of Alberto's PR https://github.com/openshift/origin/pull/22544
Scaling machines/nodes is a feature we support. From modifying a replica number to having a new running node there are multiple components involved: machine api, networking, container runtime, mco, etc. This is a gate to prevent any component to break this feature, e.g https://bugzilla.redhat.com/show_bug.cgi?id=1698253, https://bugzilla.redhat.com/show_bug.cgi?id=1698624
list machineSets
Scale current replicas of each machineSet to 3
Verify new nodes are created and go ready for each machineSet
Scale down to the original replica number
Verify the final number of worker nodes in the cluster match the original
=> Add test for scaling machineSets

vendor/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go
=> UPSTREAM: 78222: Fix nil pointer dereference in metrics value calculator

test/extended/oauth/htpasswd.go, test/extended/oauth/server_headers.go, test/extended/util/oauthserver/helpers.go, test/extended/util/oauthserver/oauthserver.go
- When creating a test oauth-server, block until the oauth server rbac updates, pod, and route are ready.
- return a closure for creating TokenRequestOptions to discourage of a single instance.
=> Harden test oauth server against flakiness

vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
When SCCs are not synched, admission rejects pods with "no SecurityContextConstraints found in cluster".
=> Bug 1733600: kube-apiserver: wait for kube informers in openshift patch

cmd/openshift-tests/e2e.go
The tests need SSH to the host && restart kubelet there, which is not possible now.
Therefore mark the tests into the suite only if they pass through `excludedTestsFilter` during `ginkgo.WalkTests()`.
=> Don't run [Disruptive] tests in Suite:openshift/csi

vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/config/testdata/conversion/controlplane/internal.yaml, vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/config/testdata/conversion/controlplane/v1beta1.yaml, vendor/k8s.io/kubernetes/cmd/kubelet/app/options/options.go, vendor/k8s.io/kubernetes/pkg/generated/openapi/zz_generated.openapi.go, vendor/k8s.io/kubernetes/pkg/kubelet/apis/config/fuzzer/fuzzer.go, vendor/k8s.io/kubernetes/pkg/kubelet/apis/config/helpers_test.go, vendor/k8s.io/kubernetes/pkg/kubelet/apis/config/types.go, vendor/k8s.io/kubernetes/pkg/kubelet/apis/config/v1beta1/zz_generated.conversion.go, vendor/k8s.io/kubernetes/pkg/kubelet/apis/config/zz_generated.deepcopy.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/kubelet/config/v1beta1/types.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/kubelet/config/v1beta1/zz_generated.deepcopy.go
Pick the upstream PR to enable sysctls in kubeletconfiguration.
ref: https://github.com/kubernetes/kubernetes/pull/72974
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1690754
/cc @sjenning
=> UPSTREAM: 72974: add allowed sysctl to KubeletConfiguration

test/extended/util/client.go
The resourceToDelete refactoring resulted in namespaces not getting
deleted.
=> e2e: Fix namespace cleanup

test/extended/prometheus/prometheus.go
We are improving metric names in [this PR at MAO](https://github.com/openshift/machine-api-operator/pull/356/commits/93ba99c41a290b6b792b2fc536ad8c44369f2426#diff-7cbe8e056d62a2de30c7066e359bd9c9R20).
To get the CI passing on ^ PR, we need to use a metric in the e2e, name of which is not being changed.
We tried(**INCORRECTLY**) to do the same in[ previous PR](https://github.com/openshift/origin/pull/23518) and used a wrong metric by mistake. We actually wanted to use the metric which is being changed in this PR.
Apologies for the noise.
=> Re-fix to use mao metric which has backward compatible name

test/extended/include.go
This is required for DR tests to appear in `openshift-tests run --dry-run`
=> tests: import 'dr' package so that DR tests were registered in disruptive suite

glide.yaml, vendor/github.com/evanphx/json-patch/README.md, vendor/github.com/evanphx/json-patch/patch.go, vendor/github.com/evanphx/json-patch/patch_test.go
this pull pins the library to the specific commit - the one that is required by k8s.
=> Bug 1723753: OpenShift incorrectly applies RFC 6902 JSON PATCH

vendor/k8s.io/kubernetes/pkg/kubelet/cadvisor/util.go
This https://github.com/openshift/origin/pull/21398 was merged into master but doesn't look like was cherry-picked for 3.11.
bug 1631300 - https://bugzilla.redhat.com/show_bug.cgi?id=1631300
cc: @sjenning
=> [release-3.11] UPSTREAM: 69313: kubelet: fix cri-o when using unix prefix

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack_volumes.go
Instead of making a request to Cinder we can read availability zone name from metadata
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1735729
=> Bug 1735729: Read availability zone name from metadata

vendor/k8s.io/kubernetes/pkg/kubelet/eviction/BUILD, vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go, vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go, vendor/k8s.io/kubernetes/pkg/kubelet/pod/pod_manager.go, vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go, vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager_test.go, vendor/k8s.io/kubernetes/pkg/kubelet/types/pod_update.go, vendor/k8s.io/kubernetes/pkg/kubelet/types/pod_update_test.go
https://github.com/kubernetes/kubernetes/pull/80491
Proactive pick for upstream fix.
Some fuzz around https://github.com/kubernetes/kubernetes/commit/ca6003bc75a3b9c81f38738c7363c9453247682e#diff-9fe046de3c6aaa377bb7fa24a34509c9 but otherwise it applies cleanly.
Extra +/-1 line changed is `goimports` adding `v1` alias
https://github.com/openshift/origin/pull/23576/files#diff-5cdd56e52dd392c4f849386f73dc723aR23
@derekwaynecarr @mrunalp
=> Bug 1739601: UPSTREAM: 80491: Changed IsCriticalPod to return true in case of static pods

test/extended/operators/tolerations.go
More info in https://github.com/openshift/machine-config-operator/pull/1031 as to why the gcp-routes-controller pod is required to keep running.
/cc @csrwng
=> test/operators: whitelist gcp-routes-controller static pod as it is part of infra

test/extended/builds/pipeline_origin_bld.go, test/extended/testdata/bindata.go, test/extended/testdata/verifyservice-pipeline-template.yaml
Fixed as containers were going to crashloopbackoff.
The image loaded before was an s2i image without the source. 
In this iteration we are using the redis-epemeral template with reduced memory which also provides us with the basic service to test and in the template jenkins-verifyservice-pipeline we are creating the headless service and the buildconfig with the jenkins file to test the feature.
cc @akram @gabemontero
=> Fixed jenkins verifyservice e2e tests 

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/test/integration/BUILD, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/test/integration/scope_test.go
Upstream PR: https://github.com/kubernetes/kubernetes/pull/80851
Already fixed in 4.1.
=> Bug 1732205: UPSTREAM: 80851: apiextensions: check request scope against CRD scope correctly

pkg/cmd/openshift-kube-apiserver/kubeadmission/register.go
changes the order of admission plugins so that RQ is applied before CRQ.
this prevents a scenario where a resource cannot be created due to RQ limits but CRQ would allow for it because it doesn't know about RQ constraints.
=> Bug 1733921:  ClusterResourceQuota usage is above project usage quota impacting all projects in ClusterResourceQuota

test/extended/util/test.go
* All tests that need specific cloud have proper Skip()
* Remove rules that don't match anything
* Enable tests that depend on 1.13 kubelet
This is continuation of https://github.com/openshift/origin/pull/22460
> @smarterclayton: This looks like it substantially increased test runtime.
I don't see any increase (`openshift/conformance/parallel` was actually slower before the PR than it is now, I blame low nr. of samples).
There are two new real tests:
```
"[sig-storage] GCP Volumes GlusterFS should be mountable [Suite:openshift/conformance/parallel] [Suite:k8s]"
"[sig-storage] PersistentVolumes NFS when invoking the Recycle reclaim policy should test that a PV becomes Available and is clean after the PVC is deleted. 
[Suite:openshift/conformance/parallel] [Suite:k8s]"
```
Additional 37 …
=> Clean up disabled tests #2

vendor/k8s.io/kubernetes/pkg/printers/internalversion/printers.go
ConfigMaps may have both data and binaryData keys and the printer
was ignoring binaryData when counting the keys.
=> Bug 1735404: ConfigMap printer ignores binaryData keys

vendor/k8s.io/kubernetes/test/e2e/scheduling/priorities.go
Reverts openshift/origin#23544
This test is failing is continuously, I still need to debug why this is failing. In meanwhile, I'm reverting the PR.
=> Bug 1740315: Revert toleration priority function score computation

test/extended/operators/routable.go, test/extended/router/router.go
based on https://github.com/openshift/origin/blob/1f707e35708112ac19446570268f0b916578119a/test/extended/util/url/url.go#L80
the test fails on first invalid response that cannot be decoded rather than retying for expected time in Within.
Esp. when the DNS resolution hasn't propagated, which we are seeing on GCP and Azure.. empty response causes the test to immediatly fail with error like
```
response 0 could not be decoded: invalid character '0' after object key:value pair
```
With passthrough set to true, the test should keep retrying.
=> test/extended: set ErrorPassthrough true for URL checker

test/extended/oauth/htpasswd.go
Removing 'Flaky' from htpasswd e2e, running through CI - should not require retry 
testing flakiness with this merge: https://github.com/openshift/origin/commit/111a801fddf9ca7ec9c11a454e9436ad3ea0531e
=> Bug 1731191: Flaky htpasswd e2e

test/extended/prometheus/prometheus.go
This is needed to merge following PRs:
- https://github.com/openshift/cluster-version-operator/pull/235
- https://github.com/openshift/cluster-monitoring-operator/pull/390
After those are merged it should be reverted.
=>  test/extended/prometheus: temporarily increase number of possible failing alerts

vendor/k8s.io/kubernetes/pkg/apis/core/types.go, vendor/k8s.io/kubernetes/pkg/generated/openapi/zz_generated.openapi.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/api/core/v1/generated.proto, vendor/k8s.io/kubernetes/staging/src/k8s.io/api/core/v1/types.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/api/core/v1/types_swagger_doc_generated.go
This backports the following upstream PRs:
* https://github.com/kubernetes/kubernetes/pull/80487
This addresses the issue in [BZ-1731316](https://bugzilla.redhat.com/show_bug.cgi?id=1731316).
=> Bug 1731316: UPSTREAM: 80487: Corrected Cinder typos

vendor/k8s.io/kubernetes/pkg/volume/csi/csi_attacher.go, vendor/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go, vendor/k8s.io/kubernetes/pkg/volume/csi/csi_block.go, vendor/k8s.io/kubernetes/pkg/volume/csi/csi_client.go, vendor/k8s.io/kubernetes/pkg/volume/csi/csi_client_test.go, vendor/k8s.io/kubernetes/pkg/volume/csi/fake/fake_client.go, vendor/k8s.io/kubernetes/test/e2e/storage/drivers/csi.go
NodeStageVolume needs the MountOptions passed through for drivers to mount the global directory with the correct options.
https://bugzilla.redhat.com/show_bug.cgi?id=1737389
https://github.com/kubernetes/kubernetes/pull/80191
=> Bug 1737389: UPSTREAM: 80191: Add passthrough for MountOptions for NodeStageVolume for CSI

test/extended/authentication/ldap/ad/sync-config-dn-everywhere.yaml, test/extended/authentication/ldap/ad/sync-config-paging.yaml, test/extended/authentication/ldap/ad/sync-config-partially-user-defined.yaml, test/extended/authentication/ldap/ad/sync-config-user-defined.yaml, test/extended/authentication/ldap/ad/sync-config.yaml, test/extended/authentication/ldap/augmented-ad/sync-config-dn-everywhere.yaml, test/extended/authentication/ldap/augmented-ad/sync-config-paging.yaml, test/extended/authentication/ldap/augmented-ad/sync-config-partially-user-defined.yaml, test/extended/authentication/ldap/augmented-ad/sync-config-user-defined.yaml, test/extended/authentication/ldap/augmented-ad/sync-config.yaml, test/extended/authentication/ldap/rfc2307/sync-config-dn-everywhere.yaml, test/extended/authentication/ldap/rfc2307/sync-config-paging.yaml, test/extended/authentication/ldap/rfc2307/sync-config-partially-user-defined.yaml, test/extended/authentication/ldap/rfc2307/sync-config-tolerating.yaml, test/extended/authentication/ldap/rfc2307/sync-config-user-defined.yaml, test/extended/authentication/ldap/rfc2307/sync-config.yaml, test/extended/oauth/groupsync.go, test/extended/testdata/bindata.go, test/extended/testdata/ldap/groupsync.sh
This restores the old ldap_groups.sh extended test to run in a container.  
Depends on https://github.com/openshift/origin/pull/23347 (will drop commit and rebase when it merges)
=> convert ldap group sync tests to e2e

vendor/k8s.io/kubernetes/test/e2e/scheduling/taints.go
Upstream: https://github.com/kubernetes/kubernetes/pull/80879
=> Bug 1733581: Failing tests NoExecuteTaintManager Multiple Pods evicts pods

hack/build-local-images.py
@openshift/openshift-team-developer-experience fyi
I found in my attempts to inject development versions of things like the openshift/origin-hypershift image, it was better to inject my locally built binaries into the image with the v3.11 tag that `oc cluster up` wants to pull down by default.
the latest and v3.11 tags at docker.io are not the same image ... just pulled them down a second ago:
```
gmontero ~/go/src/github.com/openshift/origin  (upd-build-local-images-311)$ docker images 
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
openshift/origin-hypershift   v3.11               9b50ed8c6a93        2 days ago          550MB
openshift/origin-hypershift   latest              020d15eb71bb        4 months ago        458MB …
```
=> update build-local-images, use 3.11 tag (more stable)

test/extended/machines/scale.go
Based on the logs in https://prow.k8s.io/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-serial-4.2/3322.
1) Both machineset were scaled up:
STEP: scaling "ci-op-4mlicwcq-ce7d8-mqsjq-worker-us-east-1a" from 3 to 2 replicas
Aug 15 03:42:08.361: INFO: >>> kubeConfig: /tmp/admin.kubeconfig
STEP: scaling "ci-op-4mlicwcq-ce7d8-mqsjq-worker-us-east-1b" from 2 to 1 replicas
Aug 15 03:42:08.485: INFO: >>> kubeConfig: /tmp/admin.kubeconfig
2) Machine controller deleted both machines and nodes successfully:
I0815 03:42:08.487601       1 controller.go:205] Reconciling machine "ci-op-4mlicwcq-ce7d8-mqsjq-worker-us-east-1a-5djht" triggers delete
W0815 03:42:28.610350       1 controller.go:298] drain failed for machine "ci-op-4mlicwcq-ce7d8-mqsjq-worker-us-east-1a-5djht": Drain …
=> bug 1737134: [Feature:Machines][Serial] Managed cluster should: increase timeout waiting for nodes to disappear

test/extended/prometheus/prometheus.go
https://github.com/openshift/cluster-monitoring-operator/pull/390 is merged and we can revert #23605 as it is no longer needed.
/cc @s-urbaniak
=> test/extended/prometheus: revert #23605

test/extended/router/config_manager.go, test/extended/router/scoped.go, test/extended/router/unprivileged.go, test/extended/testdata/bindata.go, test/extended/testdata/router/router-override-domains.yaml, test/extended/testdata/router/router-override.yaml, test/extended/testdata/router/router-scoped.yaml
Fix `waitForRouteToRespond`, `waitForRouterOKResponseExec`, and `expectRouteStatusCodeRepeatedExec` to honor their timeout parameter values and to specify a timeout for each curl invocation.
Before this change, each function used its timeout parameter value as the number of times to retry the curl command and did not specify a timeout value to that command.  As a result, each command invocation could keep trying indefinitely, and the function could keep retrying the command for far longer than the timeout period that the caller indicated.
Follow-up to https://github.com/openshift/origin/pull/12346 and https://github.com/openshift/origin/pull/19073.
* `test/extended/router/config_manager.go` (`waitForRouteToRespond`):
* `test/extended/router/scoped.go` (`waitForRouterOKResponseExec`) …
=> Bug 1703885: test/extended/router: Fix curl timeout, log dumping, template parameters, and router readiness probes

test/extended/testdata/bindata.go, test/extended/testdata/cmd/test/cmd/policy-storage-admin.sh
Fix `cmd/policy-storage-admin` tests to verify that a user with the storage-admin role *can* get pods in all namespaces.
See https://github.com/openshift/openshift-apiserver/pull/10.
* `test/extended/testdata/cmd/test/cmd/policy-storage-admin.sh`: Replace an old test that verified that a user with the storage-admin role could *not* get pods in all namespaces with a test that verifies that the *can* get pods in all namespaces.
* `test/extended/testdata/bindata.go`: Regenerate.
=> test/extended/.../policy-storage-admin.sh: Fix pods test

vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go, vendor/k8s.io/kubernetes/test/integration/garbagecollector/garbage_collector_test.go
backports https://github.com/kubernetes/kubernetes/pull/81081 and https://github.com/kubernetes/kubernetes/pull/78650 (for `hasFinalizer` method)
=> Bug 1642530 - Custom Resource is stuck if deleted repeatedly with PropagationPolicy Foreground

pkg/network/node/networkpolicy.go
Backport to 3.10 https://github.com/openshift/origin/pull/20031
Fixes on 3.10: https://bugzilla.redhat.com/show_bug.cgi?id=1591584
=> Bug 1743747: Fix a crash on a certain type of unsupported NetworkPolicy

test/extended/machines/scale.go
Machineset matching labels do not guarantee they will contain any specific label.
Though, given we label templated machines with machine.openshift.io/cluster-api-machine-role,
it's sufficient replacement for now.
=> Bug 1737134: [Feature:Machines][Serial] Managed cluster should: get machineset role from template labels

pkg/cmd/server/bootstrappolicy/policy.go, test/cmd/policy-storage-admin.sh, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml, test/testdata/bootstrappolicy/bootstrap_policy_file.yaml
Add ability to read pods to storage-admin users. This addresses [BZ-1741039](https://bugzilla.redhat.com/show_bug.cgi?id=1741039) for 4.1.
Note that this was addressed for 4.2 in the openshift-apiserver with https://github.com/openshift/openshift-apiserver/pull/10 .
=> Bug 1741039: Add ability to read pods to storage-admin users.

test/extended/authorization/authorization_rbac_proxy.go
=> LegacyEndpointConfirmNoEscalation: Always clean up RBAC data

test/extended/util/framework.go
Specify the namespace in the `oc describe` command in `DumpPodLogs`.
Before this commit, `DumpPodLogs` used the current namespace in the `oc describe` command.  As a result, if the pod was in a different namespace, the `oc describe` command could fail:
INFO: Running 'oc describe --config=[...] --namespace=e2e-test-router-stress-47g75 pod/router-default-bf57996-scvhc'
INFO: Error running &{/home/mmasters/bin/oc [oc describe --config=[...] --namespace=e2e-test-router-stress-47g75 pod/router-default-bf57996-scvhc] []   Error from server (NotFound): pods "router-default-bf57996-scvhc" not found
Error from server (NotFound): pods "router-default-bf57996-scvhc" not found
[] <nil> 0xc42310d200 exit status 1 <nil> <nil> true [0xc4223f06a0 0xc4223f06c8 0xc4223f06c8] [0xc4223f06a0 0xc4223f06c8] …
=> test/extended/util: DumpPodLogs: Always specify ns

vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/BUILD, vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go
This is a backport of kubernetes PR that Ravi pointed out in https://bugzilla.redhat.com/show_bug.cgi?id=1734673#c17
/assign @damemi
=> Bug 1734673: UPSTREAM: 81306: Scheduler should terminate on loosing leader lock

test/extended/authorization/rbac/groups_default_rules.go, vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go, vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml
Preparation for https://bugzilla.redhat.com/show_bug.cgi?id=1711533.
This PR:
- moves the `.well-known` non-resource RBAC path to kube-apiserver. This is a preparation for pruning of the openshift-apiserver provided non-resource rules, in order to inherit upstream's discovery and status authentication behaviour (now openshift-apiserver adds additional RBAC rules to allow discovery and status for unauthenticated access).
- prepares the `groups_default_rules.go` test for remove anon discovery and status in openshift-apiserver.
=> Bug 1711533: bootstrap-rbac-policy: prepare for non-anon discovery

test/extended/prometheus/prometheus.go
Add an e2e test which ensures that ingress controllers are successfully scraped
by Prometheus. Cover the default ingresscontroller and a non-default instance.
cc @smarterclayton @openshift/sig-network-edge
=> e2e: test ingress controller prometheus integration

test/extended/cli/explain.go
The tests
[cli] oc explain should contain proper fields description for special types [Suite:openshift/conformance/parallel]
[cli] oc explain should contain proper spec+status for CRDs [Suite:openshift/conformance/parallel]
are broken in e2e-aws-ovn-kubernetes because they assume the existence of the old `network.openshift.io` types that (in 4.x) only exist when using openshift-sdn.
The tests should be unnecessary anyway; the network types are CRDs now, so the other CRD-based tests would catch problems affecting CRDs in general. But if anyone thinks it's important to keep them, we could split these out into a separate ginkgo test case and use the `InPluginContext` function from `test/extended/networking/util.go` (or something like it) to automatically skip that test under …
=> Don't test openshift-sdn-specific things in the CLI e2e tests

vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
The Golang ReverseProxy prints out `suppressing panic for copyResponse error in test; copy error: context canceled` on termination of the process. This is highly misleading in logs and people think this is fatal, leading to lots of noise when debugging systems.
Backport of https://github.com/kubernetes/kubernetes/pull/81776
=> UPSTREAM: 81776: apimachinery: hide 'suppressing panic for copyResponse' error' in ReverseProxy

test/extended/apiserver/root_403.go
With https://github.com/openshift/openshift-apiserver/pull/18 unauthenticated access to / will lead to 403. This PR add tests for both authenticated and non-authenticated access, weaking the later temporarily until https://github.com/openshift/openshift-apiserver/pull/18 has merged.
=> Bug 1711533: extended: fix anon / access test and add one when authenticated

pkg/network/node/ovscontroller.go
If a packet is being sent over the VXLAN to a remote egress IP, we have to tell conntrack to remember the packet first, so that when we get the response it will be recognized as such (and thus accepted regardless of NetworkPolicy).
Backport of https://github.com/openshift/sdn/pull/19 (on the way to backporting it to 3.11).
/assign @squeed
=> Bug 1741499: [4.1] Pass egress IP packets to conntrack

vendor/k8s.io/kubernetes/pkg/kubelet/eviction/BUILD, vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go, vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go, vendor/k8s.io/kubernetes/pkg/kubelet/pod/pod_manager.go, vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go, vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager_test.go, vendor/k8s.io/kubernetes/pkg/kubelet/types/pod_update.go, vendor/k8s.io/kubernetes/pkg/kubelet/types/pod_update_test.go
upstream PR https://github.com/kubernetes/kubernetes/pull/80491
master PR https://github.com/openshift/origin/pull/23576
@derekwaynecarr @mrunalp
=> Bug 1739603: UPSTREAM: 80491: Changed IsCriticalPod to return true in case of static pods [4.1]

pkg/network/node/ovscontroller.go
If a packet is being sent over the VXLAN to a remote egress IP, we have to tell conntrack to remember the packet first, so that when we get the response it will be recognized as such (and thus accepted regardless of NetworkPolicy).
Backport of openshift/sdn#19 via #23609 
/assign @squeed
=> Bug 1741477: [3.11] Pass egress IP packets to conntrack

pkg/network/node/iptables.go, pkg/network/node/node.go
Fixes: [1733429](https://bugzilla.redhat.com/show_bug.cgi?id=1733429)
This backports the following openshift/sdn commits:
- c171df175a6be9ae9c97f84b0f8601f0443fb1f5 (sdn #13)
- b6e0ec16c9c35829a2b6b55fc6ebb3a3438420cb (sdn #17)
=> Bug 1733429: pkg/network: skip OPENSHIFT-MASQ for traffic already marked for masquerade

vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/remote/docker_server.go
Upstream pick to bump the max message size for dockershim
Fixes a CI issue found today
ref: https://github.com/kubernetes/kubernetes/pull/77165
/cc @stevekuznetsov
=> UPSTREAM: 77165: Increase maxMsgSize for dockershim

test/extended/prometheus/prometheus.go
This should allow easier triaging e2e test failures by being more specific about what is happening.
/cc @s-urbaniak
=> add annotations to frequently failing prometheus test cases

test/extended/machines/scale.go
From test suite logs
```
Aug 28 05:55:02.613: INFO: Running AfterSuite actions on all nodes
```
From machine controller logs:
```
I0828 05:51:37.299415       1 controller.go:205] Reconciling machine "ci-op-1zzgtx6m-3a8ca-trcpx-worker-centralus3-fvmdx" triggers delete
I0828 05:52:39.091238       1 controller.go:302] drain successful for machine "ci-op-1zzgtx6m-3a8ca-trcpx-worker-centralus3-fvmdx"
I0828 05:55:41.244092       1 virtualmachines.go:242] successfully deleted vm ci-op-1zzgtx6m-3a8ca-trcpx-worker-centralus3-fvmdx
I0828 05:56:41.832275       1 disks.go:65] successfully deleted disk ci-op-1zzgtx6m-3a8ca-trcpx-worker-centralus3-fvmdx_OSDisk
I0828 05:56:52.253019       1 networkinterfaces.go:197] successfully deleted nic ci-op-1zzgtx6m-3a8ca-trcpx-worker-centralus3-fvmdx-nic
I0828 …
```
=> bug 1744908: [Feature:Machines][Serial] Managed cluster should: increase timeout waiting for nodes to disappear

images/os/Dockerfile, origin.spec
Those RPMs have moved into oc repo. We are now trying to switch ART team to use them but we shouldn't build from 2 places at once. 
hyperkube needs to stay for providing kubelet to the base image. (https://github.com/openshift/origin/blob/7aedc3cb19c39e22b382eff96380bef245f92352/images/os/Dockerfile#L7)
/cc @smarterclayton @eparis @deads2k @soltysh
=> Bug 1739445: Remove oc rpms

test/extended/project/project.go
This test breaks in HA clusters because there is no guarantee the watches will be synchronized.
The bug in title links to a flake found in Azure e2e tests already.
https://bugzilla.redhat.com/show_bug.cgi?id=1744105 is tracking conversion of this (and other) tests to openshift-apiserver unit tests (4.3).
/cc @deads2k 
/cc @sttts
=> Bug 1743927: Add sleep before starting a watch in project e2e test

vendor/k8s.io/kubernetes/test/e2e/scheduling/preemption.go
Rebased changes from https://github.com/openshift/origin/pull/23050
=>  Bug 1731263: Re-enable preemption test with fixes

test/extended/util/framework.go, test/extended/util/url/url.go
The current level of Kubernetes does not support routing packets from
the host network interface to LoadBalancer Service external IPs. Although such
routing tends to work on AWS with our current topology, it only works by
coincidence. On other platforms like Azure and GCP, packets will not route to
the load balancer except when the node is part of the load balancer target pool.
At best, the level of support is undefined and all behavior in this context is
considered unintentional by upstream.
The practical implication is that connectivity to Routes on cloud platorms is
only supported from public and container network clients.
Refactor the e2e tests to exercise Route connectivity only through the container
network. This eliminates a class of test flake whereby tests pass when the test
pod …
=> e2e: use container network to access routes

test/extended/prometheus/prometheus.go
This test was failing because machine-api-operator component is not
installed everywhere, so we often see this test failing. We will remove
it for now, and rethink the test in a future PR.
cc @s-urbaniak @paulfantom @smarterclayton
=> test/extended/prometheus: Remove machine api operator metrics test

test/extended/operators/qos.go
Marketplace added resources requests
https://github.com/operator-framework/operator-lifecycle-manager/pull/955
Close the gate to prevent regression
@rphillips @derekwaynecarr @smarterclayton
=> tests/extended: prevent QoS class regression on marketplace operators

test/extended/builds/failure_status.go, test/extended/testdata/bindata.go, test/extended/testdata/builds/statusfail-pushtoregistry.yaml
If an image push doesn't have a tag, ensure that `:latest` is appended and doesn't fail due to an "identifier is not an image" error.
=> Bug 1746499: Ensure images push without full tag spec

examples/jenkins/pipeline/maven-pipeline.yaml, test/extended/testdata/bindata.go
When using current build mechanism, if any previous build has been identified has failure we fall in an infinite loop and have to wait until the 20 minutes timeout are reached.
This solution is based on a logic I implemented on personal project.
When a build is started the build number is printed out. The Openshift jenkins pipeline allows to select a build from its number with `openshift.selector('builds', "${buildNumber}")`
We can as well directly fail if the build has been identified as failure.
=> Allow previous build failure

vendor/k8s.io/kubernetes/pkg/volume/csi/csi_plugin.go
In case of short timeout (15s), some CSI plugins like RBD can bahave
weird. That said, if timeout occurs RBD plugin try an unmap and do other cleanup/rollback operations. In most
of the cases, it is just that, its taking more than 15s when there are
parellel requests  to serve and map. If the timeout is high, most of the
mapping operations will succeed and it will not cause any rollback
operation/cleanup in the system which avoid other issues.
Fix#  https://bugzilla.redhat.com/show_bug.cgi?id=1745776
=> Bug: 1745776: UPSTREAM: 79529: change default timeout value in csi plugin

vendor/k8s.io/kubernetes/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/resource/visitor.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/resource/visitor_test.go
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1727917
4.2 fix (links to upstream PR as well): ~~https://github.com/openshift/kubernetes-cli-runtime/pull/2~~ https://github.com/openshift/kubernetes-cli-runtime/pull/3
=> [release-4.1] Bug 1727917: FlattenListVisitor now continues traversal on errors and returns an aggregate

vendor/k8s.io/kubernetes/pkg/controller/certificates/certificate_controller.go, vendor/k8s.io/kubernetes/pkg/controller/certificates/csrsuicider/patch_die_on_cert_change.go, vendor/k8s.io/kubernetes/pkg/controller/certificates/signer/cfssl_signer.go
Once we have this, we can wire a cert-syncer to it in the operator and we'll be able to avoid relying on rollouts to get a new CSR signer.  This appears to have caused an unstable cluster where a rollout failed and all kubelets are lost.  Can't get logs from a dead kubelet though.
@soltysh
=> UPSTREAM: <carry>: kill kube-controller-manager on CSR file content change

vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go, vendor/k8s.io/kubernetes/openshift-kube-apiserver/configdefault/admission_config.go, vendor/k8s.io/kubernetes/openshift-kube-apiserver/enablement/admission.go
Without this, no openshift admission plugin is registered and trying to enable them via unsupported config overrides error out with "unknown" plugin.
This is because of wrong order :-)
Credits to @sttts with debugging help.
/cc @sttts 
/cc @deads2k
=> Bug 1748501: UPSTREAM: <carry>: fix openshift admission plugin registration

pkg/network/node/multitenant.go, pkg/network/node/node.go, pkg/network/node/ovscontroller.go, pkg/network/node/pod.go, pkg/network/node/sdn_controller.go
This is a fix for [BUG 1723924](https://bugzilla.redhat.com/show_bug.cgi?id=1723924)
FIX for 4.X on origin, see linked PR's in 
SDN:
https://github.com/openshift/sdn/pull/20
3.11:
https://github.com/openshift/origin/pull/23522
The problem:
As mentioned in the link above, when the openshift networking process dies, the "podManager" object and its attribute "runningPods" is wiped for memory, which can lead to stateful inconsistencies 
with openflow ports concerning pods from a multicast-enabled namespaces 
The fix:
We now initialize the "podManager" with the initial state of all running pods when the process is booted, as such we will have a synchronized state.
=> Bug 1740731: Initializing runningPods on SDN bootup for 4.x

test/extended/networking/util.go, test/extended/prometheus/prometheus.go
The tests
[Feature:Prometheus][Conformance] Prometheus when installed on the cluster should be able to get the sdn ovs flows [Suite:openshift/conformance/parallel/minimal]
[Feature:Prometheus][Conformance] Prometheus when installed on the cluster should start and expose a secured proxy and unsecured metrics [Suite:openshift/conformance/parallel/minimal]
are broken in e2e-aws-ovn-kubernetes because they assume the existence of openshift-sdn-specific metrics which won't exist when running other network plugins.
I've wrapped the "should be able to get the sdn ovs flows" test in a helper that will automatically skip it under other network plugins. (This is similar to what we have done in the past to skip multitenant-specific or NetworkPolicy-specific tests when using the other mode.)
For the …
=> Don't always assume openshift-sdn in prometheus e2e tests

vendor/k8s.io/kubernetes/test/e2e/scheduling/preemption.go
This fixes a bug introduced in https://github.com/openshift/origin/pull/23645 by initializing the pod array with a length of 0 and a capacity of 4, due to the fact that some nodes may be unschedulable and thus we can't assume that `len(pods)` will always have 4 pods
=> Bug 1748150: Modify scheduler preemption tests (fixup #23645)

test/extended/oauth/groupsync.go, test/extended/util/ldap.go
The tests should use the vendored repos directly, not from kube staging.
-----
This makes `openshift-tests` binary buildable with go-1.13
=> Fix extended tests imports

test/extended/util/test.go
OpenShift 4.x does not support Ceph, Ceph CSI driver should be used instead.
https://docs.openshift.com/container-platform/4.1/storage/understanding-persistent-storage.html#types-of-persistent-volumes_understanding-persistent-storage
=> Bug 1747343: Disable unsupported Ceph tests

test/extended/util/test.go
Disabled the GCE CSI tests temporarily, as they are currently failing due to a CRI-O bug that prevents accessing IPs [1], currently being targeted for 4.3.
This resolves [BZ 1745720](https://bugzilla.redhat.com/show_bug.cgi?id=1745720).
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1718389
=> Bug 1745720: Disable GCE CSI tests due to CRI-O bug

pkg/apps/apis/apps/validation/validation.go, pkg/apps/apis/apps/validation/validation_test.go, pkg/apps/controller/deploymentconfig/deploymentconfig_controller.go, test/extended/deployments/deployments.go, test/extended/testdata/bindata.go, test/extended/testdata/deployments/custom-deployment.yaml, test/extended/testdata/deployments/deployment-history-limit.yaml, test/extended/testdata/deployments/deployment-ignores-deployer.yaml, test/extended/testdata/deployments/deployment-image-resolution-is.yaml, test/extended/testdata/deployments/deployment-min-ready-seconds.yaml, test/extended/testdata/deployments/deployment-simple.yaml, test/extended/testdata/deployments/deployment-trigger.yaml, test/extended/testdata/deployments/deployment-with-ref-env.yaml, test/extended/testdata/deployments/failing-pre-hook.yaml, test/extended/testdata/deployments/generation-test.yaml, test/extended/testdata/deployments/paused-deployment.yaml, test/extended/testdata/deployments/readiness-test.yaml, test/extended/testdata/deployments/test-deployment-broken.yaml, test/extended/testdata/deployments/test-deployment-test.yaml
forwardport of https://github.com/openshift/origin/pull/22324 - can't really do backport from 4.2 because the repo split, but this fix started in 3.11 anyways (and missed 4.1)
/cc @soltysh
=> Bug 1741135: Fix dc adoption

vendor/k8s.io/kubernetes/test/e2e/common/kubelet.go
Trivial fix for a crash in e2e tests.
ref: https://github.com/kubernetes/kubernetes/pull/82335
=> Bug 1744422: UPSTREAM: 82335: defer the close to after the error check

vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go, vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp_test.go
This is a pick-ish of  [UPSTREAM: 80871](https://github.com/kubernetes/kubernetes/pull/80871) (that is an automatic cherry-pick of 80436 on kube release-1.13)  kube only carried as far as 1.13 AFAICT
=> Bug 1737655: UPSTREAM: 80436: refactors to kubernetes CP command

vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp/BUILD, vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp/cp.go, vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp/cp_test.go
This is cherry pick of [UPSTREAM: 80871](https://github.com/kubernetes/kubernetes/pull/80871) (that is an automatic cherry-pick of 80436 on kube release-1.13)
=> Bug 1737656: UPSTREAM: 80436: refactors to kubernetes CP command

test/extended/cli/explain.go
In 1.16 (maybe in 1.15) kube the RawExtension does not have any public fields to explain to show. This is failing the e2e test in 1.16 PR and should be changed here to only look for the description.
/cc @soltysh 
/cc @sttts
=> extended: RawExtension does not have fields

vendor/k8s.io/kubernetes/test/e2e/apps/daemon_set.go
DS e2e detects schedulable nodes at startup which results in flakes if cluster has some nodes not schedulable yet when e2e start. This limits the occurence but doesn't fix the issue of us starting e2e on a cluster that is not ready for it.
backport of https://github.com/kubernetes/kubernetes/pull/75349 via https://github.com/kubernetes/kubernetes/pull/82415
/hold
(for https://github.com/kubernetes/kubernetes/pull/82415 to merge upstream first)
/cc @soltysh @smarterclayton @sjenning
=> Bug 1743104: DS - detect schedulable nodes on demand

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
looks like https://github.com/kubernetes/kubernetes/issues/82130 which is fixed by https://github.com/kubernetes/kubernetes/pull/82303
/assign @JacobTanenbaum
=> Bug 1749645 - watch cache causes update failure on stale data

test/extended/builds/build_timing.go
Ensure that the push spec printed by builds does not include the tag (only sha).
=> Bug 1716697: Verify valid push specs in logs

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig/config_test.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/value/transformer.go, vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/value/transformer_test.go
This change updates NewPrefixTransformers to not short-circuit on
the first transformer that has a matching prefix.  If the same type
of encryption ProviderConfiguration is used more than once, they
will share the same prefix.  A failure in the first one should not
prevent a later match from being attempted.
Added TestCBCKeyRotationWithOverlappingProviders unit test to
prevent regressions.  Note that this test explicitly exercises this
flow using an EncryptionConfiguration object as the structure of the
resulting transformer is an important part of the check.
=> UPSTREAM: 82434: Encryption config: correctly handle overlapping providers

vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/csi_volume_predicate.go, vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/csi_volume_predicate_test.go, vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/max_attachable_volume_predicate_test.go, vendor/k8s.io/kubernetes/pkg/scheduler/algorithmprovider/defaults/register_predicates.go
Re-submitting the patch since the previous one (https://github.com/openshift/origin/pull/23718)  was not picked by the rebase (https://github.com/openshift/origin/pull/23674).
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1747377
Upstream PR: kubernetes/kubernetes#73863
=> Bug 1747377: UPSTREAM: 73863: Fix code to handle delayed binding volumes

test/extended/util/test.go
This is a followup to https://github.com/openshift/origin/pull/23720, that disables the remaining failing tests. These tests appear to be failing due to a CRI-O bug that prevents accessing IPs [1], currently being targeted for 4.3.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1718389
=> Bug 1750926: Disable failing storage GCE Serial tests due to openshift blocking pod access to cloud provider.

test/extended/util/test.go
These tests don't work on our GCP infra
https://bugzilla.redhat.com/show_bug.cgi?id=1750851
=> Disable HPA Stackdriver custom metrics e2e tests

test/extended/authorization/authorization.go
gcp appears to add an unexpected user, but only sometimes (this flakes, see https://testgrid.k8s.io/redhat-openshift-release-informing#redhat-canary-openshift-ocp-installer-e2e-gcp-serial-4.2).    I'm sure why, but I don't really care if we actually need it.
/assign @brenton 
https://prow.k8s.io/view/gcs/origin-ci-test/logs/canary-openshift-ocp-installer-e2e-gcp-serial-4.2/144#0:build-log.txt%3A1362 shows the log line
=> relax RAR check to pass GCP

cmd/openshift-tests/openshift-tests.go, test/extended/crdvalidation/apiserver.go, test/extended/oauth/oauth_ldap.go, test/extended/util/test.go, test/extended/util/test_test.go
The logic for adding labels to tests is twisty.  I refactored enough to add tests, so I can be convinced they work.  This let's me know that https://prow.k8s.io/view/gcs/origin-ci-test/logs/canary-openshift-ocp-installer-e2e-gcp-serial-4.2/142 still didn't have the latest skip logic from https://github.com/openshift/origin/pull/23768 applied.
=> Log which tests are skipped, add tests

test/extended/security/scc.go
Fixing:
```
fail [github.com/openshift/origin/test/extended/authorization/authorization.go:361]: who can view deploymentconfigs in hammer by harold
: evaluation errors does not match (clusterrole.rbac.authorization.k8s.io "all-scc-e2e-test-scc-pmktf" not found!=)
```
=> Bug 1726392: extended: clean up cluster role binding after scc test

pkg/cmd/openshift-sdn/proxy.go, pkg/network/proxy/proxy.go, pkg/proxy/hybrid/proxy.go, vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server.go, vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server_others.go, vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server_windows.go, vendor/k8s.io/kubernetes/pkg/kubemark/BUILD, vendor/k8s.io/kubernetes/pkg/kubemark/hollow_proxy.go, vendor/k8s.io/kubernetes/pkg/proxy/BUILD, vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier_openshift.go, vendor/k8s.io/kubernetes/pkg/proxy/types.go, vendor/k8s.io/kubernetes/pkg/proxy/userspace/BUILD, vendor/k8s.io/kubernetes/pkg/proxy/userspace/loadbalancer.go, vendor/k8s.io/kubernetes/pkg/proxy/userspace/proxier.go, vendor/k8s.io/kubernetes/pkg/proxy/userspace/proxier_openshift.go, vendor/k8s.io/kubernetes/pkg/proxy/userspace/proxier_test.go, vendor/k8s.io/kubernetes/pkg/proxy/winuserspace/BUILD, vendor/k8s.io/kubernetes/pkg/proxy/winuserspace/loadbalancer.go, vendor/k8s.io/kubernetes/pkg/proxy/winuserspace/proxier.go
This is the 4.1 backport of https://github.com/openshift/sdn/pull/8. It includes:
- backport of upstream PR 71735, which moves the userspace proxy over to an asynchronous model
- Changes needed to use that backport
- A small carry patch that lets us tweak the proxy internals slightly
- A patch that combines both proxy's sync loops, preventing lock contention
=> Bug 1734003:  Unidling: minimize iptables lock contention

vendor/k8s.io/kubernetes/test/e2e/storage/drivers/in_tree.go
Cinder tests are failing in a downstream test suite. With disabled block support, we test that a block volume cannot be dynamically provisioned and it fails, because Cinder provisions block volumes just fine.
=> UPSTREAM: 82367: Enable block tests for Cinder

cmd/openshift-tests/upgrade.go
On GCP the upstream upgrade test was being run (no skip rule) which fails because it doesn't actually know how to upgrade us. Disable that in the upgrade suite so only the openshift variant runs.
Caught in upgrade test https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade-4.2/2
```
failed: (24m56s) 2019-09-16T21:39:43 "[sig-cluster-lifecycle] Upgrade [Feature:Upgrade] cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade] [Suite:k8s] [Disabled:SpecialConfig]"
started: (1/2/2) "[Disruptive] Cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade] [Suite:openshift] [Serial]"
```
We only want to run the latter.
=> tests: Only the OpenShift upgrade e2e suite should run

test/extended/router/headers.go, test/extended/util/test.go
It seems that most platforms are either having trouble with, or have already disabled this test. This test occasionally passes but usually doesn't in our canaries, and we believe the best course of action is to disable it.
Test Grid:
https://testgrid.k8s.io/redhat-openshift-release-informing#redhat-canary-openshift-ocp-installer-e2e-openstack-4.2
Example Failure:
https://prow.k8s.io/view/gcs/origin-ci-test/logs/canary-openshift-ocp-installer-e2e-openstack-4.2/194
=> Bug #1752646: Disable the router header test for all platforms

test/extended/builds/webhook.go
Reduce the number of builds invoked in the webhook tests.
These seem to cause delays tearing down the namespace and are not needed to verify webhook functionality.
=> Bug 1752581: Reduce Builds in Webhook Tests

test/extended/util/client.go
Group based permissions can take a long time to be effective due to the extra layer of indirection via the group reverse index.
@deads2k
=> Bug 1752582: e2e: wait longer for authz checks

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_getters.go
This enables the kubelet pod list to have correctly updated statuses for
static pods.
ref: https://github.com/kubernetes/kubernetes/pull/77661
=> Bug 1751959: UPSTREAM: 77661: Kubelet status manager sync the status of local pods

test/extended/operators/images.go, test/extended/operators/operators.go
When reproducing specific upgrade states (4.2 control plane and
4.1 nodes) we need to provide a partial payload. That causes certain
sanity tests to fail. Allow those tests to be bypassed in extremely
rare conditions.
A future change may make this more explicit but this is the easiest
short term option. Environment variables should not in general be used
to impact the contents of a suite, and the future "test options"
addition to openshift-tests will remove the env var.
=> Bug 1753070: Allow an env var to disable certain tests for skew testing

vendor/k8s.io/kubernetes/test/e2e/framework/BUILD, vendor/k8s.io/kubernetes/test/e2e/framework/util.go
Adds debugging information when namespaces don't get cleaned up.
/assign @p0lyn0mial
=> UPSTREAM: 82803: dump namespace object in e2e when it doesn't get deleted

test/extended/builds/s2i_quota.go, test/extended/testdata/bindata.go, test/extended/testdata/builds/test-s2i-build-quota.json
trying to get confirmation that OOMKills can appear when the container process hits the container memory limit: https://coreos.slack.com/archives/CK1AE4ZCK/p1568807371055900
=> bug 1752557: bump s2i quota test memory limit to avoid oomkills

vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
Backport of https://github.com/kubernetes/kubernetes/pull/82759
=> Bug 1743675: validations: for negative PVC storage size don't report "must be >= 0"

test/extended/operators/olm.go
The closure was capturing the last i value instead of testing each individual item. Change the test to loop correctly.
```
fail [github.com/openshift/origin/test/extended/operators/olm.go:36]: subscriptions list should have at least one item
Expected
<bool>: true
to be false
```
All of the tests in the suite return that when a 4.1 cluster is run against 4.2.  Blocks us starting the skew test (there's almost certainly an actual bug here, this is just a blocker for knowing what the other bugs are).
No 4.2 change necessary because the test was already refactored as part of an epic.
=> Bug 1752983: Ensure the OLM e2e test loops correctly

test/extended/builds/new_app.go
Disable flaking tests due to [bug 1753731](https://bugzilla.redhat.com/show_bug.cgi?id=1753731).
=> Disable oc new-app tests

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_getters.go
This is an upstream pick to pull a change to get updated pod statuses. 
/cc @sjenning @derekwaynecarr @RobertKrawitz @joelsmith 
ref: https://github.com/kubernetes/kubernetes/pull/77661
=> [release-3.11] Bug 1720174: upstream: Kubelet status manager sync the status of local pods

pkg/network/node/cniserver/cniserver.go, pkg/network/node/multitenant.go, pkg/network/node/node.go, pkg/network/node/ovscontroller.go, pkg/network/node/ovscontroller_test.go, pkg/network/node/pod.go, pkg/network/node/pod_test.go, pkg/network/node/runtime.go, pkg/network/node/sdn_controller.go, pkg/util/ovs/fake_ovs.go, pkg/util/ovs/fake_ovs_test.go, pkg/util/ovs/ovs.go, pkg/util/ovs/ovs_test.go, pkg/util/ovs/parse.go
This is a fix for [BUG 1723924](https://bugzilla.redhat.com/show_bug.cgi?id=1723924)
The problem:
As mentioned in the link above, when the openshift networking process dies, the "podManager" object and its attribute "runningPods" is wiped for memory, which can lead to stateful inconsistencies with iptable rules defined for the pods running on that node. 
The fix:
We now initialize the "podManager" with the initial state of all running pods when the process is booted, as such we will have a synchronized state.
=> Bug 1723924: Initializing runningPods on SDN bootup for 3.11

test/extended/operators/images.go, test/extended/operators/operators.go
Skew tests create payloads that don't completely upgrade a cluster in order to get reproducible partial upgrade states. Some tests need to be disabled in order to allow the suite to succeed. Uses an env var for now, although future changes will switch to an argument flag.
Backport of #23820 to enable skewed node testing.
=> Bug 1753071: Allow certain tests to be skipped when performing skew testing

cmd/openshift-tests/e2e.go, test/extended/util/test.go, test/extended/util/test_test.go
This fixes two problems:
- We need to be able to skip some tests on ovn-kubernetes (eg, the Service SessionAffinity tests, since that feature isn't implemented yet in 4.2).
- We need to be able to *not* skip some tests on ovn-kubernetes that we are skipping on openshift-sdn (eg, NetworkPolicy egress tests)
This also lets us simplify the way the multitenant suite is done.
(WIP until the 1.16 rebase lands since this will need to be updated for that)
=> Bug 1753324: Allow skipping tests based on detected network plugin

glide.lock, glide.yaml, vendor/github.com/evanphx/json-patch/patch_test.go, vendor/github.com/google/btree/go.mod, vendor/github.com/google/cadvisor/container/crio/client.go, vendor/github.com/google/cadvisor/container/crio/handler.go, vendor/github.com/openshift/imagebuilder/OWNERS, vendor/github.com/openshift/imagebuilder/dockerclient/archive.go, vendor/github.com/openshift/imagebuilder/dockerclient/archive_test.go, vendor/github.com/openshift/imagebuilder/dockerclient/conformance_test.go, vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_11, vendor/github.com/openshift/imagebuilder/dockerclient/testdata/Dockerfile.copyfrom_12, vendor/github.com/vmware/photon-controller-go-sdk/photon/client.go, vendor/github.com/vmware/photon-controller-go-sdk/photon/deployments_test.go, vendor/github.com/vmware/photon-controller-go-sdk/photon/lightwave/oidcclient_test.go
master PR https://github.com/openshift/origin/pull/23585
4.1.z PR https://github.com/openshift/origin/pull/23619
pull in https://github.com/openshift/google-cadvisor/pull/7
The delta is larger because a `make update-deps` on a clean `origin/master` makes a lot of changes and the `github.com/apcera/gssapi` dep needed to be redirected to the openshift fork because that repo doesn't exist anymore.  I've split up the bump(*) on the clean master into a separate commit.
Fixes #23492
@derekwaynecarr @deads2k @mfojtik
=> Bug 1741679: Bump cadvisor [3.11.z]

vendor/k8s.io/kubernetes/plugin/pkg/admission/storage/persistentvolume/label/BUILD, vendor/k8s.io/kubernetes/plugin/pkg/admission/storage/persistentvolume/label/admission.go, vendor/k8s.io/kubernetes/plugin/pkg/admission/storage/persistentvolume/label/admission_test.go
https://bugzilla.redhat.com/show_bug.cgi?id=1753012
https://github.com/kubernetes/kubernetes/pull/82830
Some backport changes were necessary, `pkg/controller/volume/persistentvolume/util` is not available in 1.14 and `annDynamicallyProvisioned` is private in pv_controller.go
~WIP: remove the first debug commit~
=> BUG 1753012: UPSTREAM: 82830: Do not query the cloud if PV has all the labels

test/extended/images/imagechange_buildtrigger.go, test/extended/images/imagestream.go, test/extended/images/imagestream_admission.go
Replace `t.Fatal` and `t.Fatalf` with gomega equivalents
=> Refactor image tests to gomega

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status_test.go, vendor/k8s.io/kubernetes/pkg/util/node/BUILD, vendor/k8s.io/kubernetes/pkg/util/node/node.go
Backport of #23345 / #23367 to release-3.11 for a customer. (Their symptom is slightly different, involving IPv4 vs IPv6 addresses, but it appears to be the same underlying bug.)
/cc @RobertKrawitz @sjenning
=> Bug 1734385: [3.11] Don't use strategic merge patch on Node.Status.Addresses

publishing-rules.yaml
We are branching and need to update this
/cherrypick release-4.2
=> publish kube 1.14 from release-4.2

vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go, vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp_test.go
This was a manual process of bringing in changes from mentioned UPSTREAM commits.   
This is a pick-ish of:
* [UPSTREAM: 80871](https://github.com/kubernetes/kubernetes/pull/80871) (that is an automatic cherry-pick of 80436 on kube release-1.13)  kube only carried as far as 1.13
* [UPSTREAM: 82834](https://github.com/kubernetes/kubernetes/pull/82384)
=> Bug 1737653: UPSTREAM: 75037: UPSTREAM: 76788: UPSTREAM: 80436

test/extended/util/test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1755000 until kubelet version is updated.
/sig storage
=> Bug 1755000: Disable tests that need latest kubelet

test/extended/util/test.go
In 1.16 we added new storage tests that were not matched by the old expressions. Make the expression more generic to catch any in-line or pre-provisioned tests on Azure.
=> Update azure storage regexp to 1.16 rebase

test/extended/util/test.go
The additional whitespace was causing the test to still getting included.
=> Bug 1755000: Remove whitespace from online expansion test

test/extended/operators/tolerations.go
We don't need to test static pods in openshift-openstack-namespace here.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1753953
=> Bug 1753953: exclude openstack infra namespace from the tolerations tests

vendor/k8s.io/kubernetes/test/e2e/storage/empty_dir_wrapper.go
https://bugzilla.redhat.com/show_bug.cgi?id=1744909
https://github.com/kubernetes/kubernetes/pull/82245
=> Bug 1744909: UPSTREAM: 82245: Don't require any resources in race test

glide.lock, glide.yaml, vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go
1st commit bumps dependencies with `make update-deps`. GRPC needed a bump.
2nd commit bumps runc with the fix.
ref [4.2]: https://github.com/openshift/origin/pull/23860
[4.3 BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1755991)
=> Bug 1755991: bump runc for delegation fix

test/extended/util/test.go
We missed a Nvidia GPU test when we rebased to 1.16. Disable from E2E for now.
=> Disable GPUDevicePluginAcrossRecreate test

cmd/openshift-tests/openshift-tests.go, test/extended/util/cloud/cloud.go, test/extended/util/test.go
Ensure the cloud provider is autodetected where possible, although
not all cloud providers will behave this way.
=> cmd/openshift-tests: Autodetect cloud

vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/network/externalipranger/externalip_admission.go, vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/network/externalipranger/externalip_admission_test.go
This PR adds a RBAC checker for adding an External IP range for a service.
=> Bug 1752045: UPSTREAM: <carry>:Add a RBAC checker for external IP ranger

test/extended/util/cloud/cloud.go
Autodetection was failing on vsphere because it has no zone labels.
Instead only set zone if we have one.
=> test: Don't block on cloud providers without zones in autodetect

cmd/openshift-tests/openshift-tests.go, test/extended/util/test.go
this pull changes `openshift-test` to print 
```
openshift-tests excluded test regex is "\\[Disabled:|\\[Disruptive\\]|\\[Skipped\\]|\\[Slow\\]|\\[Flaky\\]|\\[local\\]|\\[Suite:openshift/test-cmd\\]|\\[Skipped:skeleton\\]"
error: invalid configuration: no configuration has been provided
```
instead of
```
runtime/debug.Stack(0xc0039959a0, 0x1cbef8d, 0xc000bc4690)
/usr/local/Cellar/go/1.12.9/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/openshift/origin/test/extended/util.FatalErr(0x5536180, 0xc00289c520)
/Users/lszaszki/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/util/client.go:643 +0x26
github.com/openshift/origin/test/extended/util.InitTest(0x0, 0x0, 0x0) …
```
=> changes openshift-tests to report and error when creating kube client fails

vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go
Backports a sync.WorkGroup fix causing `Observed a panic: "sync: negative WaitGroup counter" `
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1758267
ref: https://github.com/kubernetes/kubernetes/pull/61330
=> [3.11] BUG 1758267: UPSTREAM: 61330: fix workgroup panic bug

vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_image.go, vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_image_test.go, vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/libdocker/fake_client.go
https://github.com/kubernetes/kubernetes/pull/70647
https://github.com/kubernetes/kubernetes/pull/75367
3.11 PRs:
https://github.com/openshift/origin/pull/22154
https://github.com/openshift/origin/pull/22629
@sferich888 @soukron @derekwaynecarr 
supercedes https://github.com/openshift/origin/pull/22500 that doesn't include https://github.com/kubernetes/kubernetes/pull/75367
=> [3.10] ImageGC fixes

vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
flags that are passed in APIServerArguments are overridden by the patch and should be printed
so that the end users can read the actual values.
=> UPSTREAM: <carry> print merged flags at startup

test/extended/util/test.go
\+ remove one unused pattern
\+ reshuffle remaining disabled storage tests a bit and add BZ link to one
(see the individual commits)
=> Bug 1755039: Enable storage tests that require 1.16 kubelet

pkg/network/node/networkpolicy.go, pkg/network/node/networkpolicy_test.go
Backport of https://github.com/openshift/sdn/pull/36 and https://github.com/openshift/sdn/pull/42 to 3.11.
This ended up being slightly different from the 4.3/4.2/4.1 version because 3.11 doesn't have namespaceSelector+podSelector support so the `selectNamespacesInternal` changes didn't apply completely cleanly and had to be rewritten a bit.
=> Bug 1758235: NetworkPolicy performance fixes [3.11]

test/extended/util/test.go
- Let the ovn-master pod tolerate NotReady nodes
- Add some more variations of the session affinity test
/cc @danwinship
=> OVN-Kubernetes: some more test tweaks

test/extended/util/test.go, vendor/k8s.io/kubernetes/test/e2e/node/BUILD, vendor/k8s.io/kubernetes/test/e2e/node/mount_propagation.go
\+ enable the test downstream
https://github.com/kubernetes/kubernetes/pull/82424
https://bugzilla.redhat.com/show_bug.cgi?id=1711600
@openshift/storage, PTAL
=> Bug 1711600: UPSTREAM: 82424:Use pod + nsenter instead of SSH in mount propagation tests
