vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go

Call `DescribeVolumes` less frequently so OpenShift is not throttled by AWS. `DescribeVolumes` is basically the only Kubernetes call that suffers API throttling by AWS.
This is a temporary patch that adds extra logs here and there to get accurate numbers. We should revert it in a week or two, analyze if it helped with API throttling and either post it upstream or find a better solution.

UPSTREAM: <drop>: Lower DescribeVolumes polling frequency

---

vendor/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/topology_manager.go
vendor/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/topology_manager_test.go

Picks an upstream patch to fix a bug in TopologyManager with SingleNUMANode Policy.
ref: https://github.com/kubernetes/kubernetes/pull/83697

UPSTREAM: 83751: Fixed bug in TopologyManager with SingleNUMANode Policy

---

pkg/test/ginkgo/cmd_runsuite.go
pkg/test/ginkgo/junit.go

By splitting monitor into a separate file we can exclude it from
testgrid, cleaning up the summary of jobs. We still however want
it to be visible to spyglass.

Bug 1761276: Write test monitor errors to monitor_*.xml

---

test/extended/builds/new_app.go

Undo https://github.com/openshift/origin/pull/23832 as part of https://github.com/openshift/openshift-controller-manager/pull/34 on path for merging
Getting a few runs in pre-merge to see if we can repro the original flake with any frequency, followed by absence of flakes after https://github.com/openshift/openshift-controller-manager/pull/34 merges

Bug 1753731: add extended build new-app tests back

---

vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp/cp.go
vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp/cp_test.go

This is a manual pick of kubernetes/kubernetes#82503
Reorder symlinks to prevent path escapes

Bug 1753500: UPSTREAM: 82503

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/delta_fifo_test.go

UPSTREAM: 83911: Fix DeltaFIFO Replace method to prevent SharedIndexInformers from missing notifications

---

vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go
vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp_test.go

This is a manual pick of https://github.com/kubernetes/kubernetes/pull/82503
Reorder symlinks to prevent path escapes

Bug 1753501: UPSTREAM: 82503

---

images/router/haproxy/conf/haproxy-config.template

Fix for BZ1748814 (OCP 3.11)  backport-of-BZ1579729
The option tcplog is not supported in backends, hence removing it.

Bug 1748814: Remove 'option tcplog' from passthrough backend in template router

---

pkg/route/controller/routeapihelpers/validation.go
pkg/route/controller/routeapihelpers/validation_test.go

This is manual cherry-pick of openshift/router#39.

[release-3.11] Bug 1758375: fix haproxy reload crash when processing ECDSA keys

---

test/extended/authorization/rbac/groups_default_rules.go

Related to:
- https://github.com/openshift/origin/pull/23231
- https://github.com/openshift/origin/pull/23382
To unblock this PR in the console-operator:
- https://github.com/openshift/console-operator/pull/306
/cc @bparees @spadgett 
fyi @jhadvig

Add consoleyamlsamples to list of console resource exceptions

---

vendor/OWNERS

Since openshift-ci-robot does not honor OWNERS in vendor any longer (https://github.com/openshift/release/pull/4249), storage folks need to have someone who would approve our stuff.
Proposing @knobunc as our group lead and @childsb as our team lead.
I am really tempted to put everyone from our team who is in any upstream OWNERS here, but I start small. This is SO annoying...
/assign @eparis @smarterclayton

Add OWNERS of storage components

---

test/extended/util/oauthserver/oauthserver.go

Makes waiting for the pod to become ready prior to waiting for
the route readiness, increases timeout for the pod ready check.
-----
It seems that every now and then the oauth server container takes too long to become ready which causes flakes.
/assign @sanchezl

Bug 1761682: test oauth server: increase timeout, wait for pod ready first

---

pkg/router/metrics/haproxy/haproxy.go

Description of problem:
When ServerThreshold is exceeded, it doesn't ignore the rest of the servers, it ignores the rest of the records including backend, frontend and server records.
Version-Release number of selected component (if applicable):
OCP 3.11
Actual results:
Currently, OCP 3.11 does not have the backport fix of https://github.com/openshift/router/pull/12 made in 4.2
Expected results:
OCP 3.11 to have this fix as well to not ignore the non-server records if the serverThreshold is reached.
Additional info:
Upstream 4.2 PR = https://github.com/openshift/router/pull/12
OCP 3.11 code reference = https://github.com/openshift/origin/blob/release-3.11/pkg/router/metrics/haproxy/haproxy.go#L428-L435

Bug 1749649: Fix ignoring non-server records when server threshold is exceeded

---

pkg/test/ginkgo/cmd_runsuite.go
pkg/test/ginkgo/junit.go
test/e2e/upgrade/upgrade.go
test/extended/util/disruption/disruption.go

Testgrid would omit disruption tests.

test: Update junit naming to ensure disruption tests are recorded

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws_fakes.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws_test.go

Cherry-picked from https://github.com/kubernetes/kubernetes/pull/80747.
On AWS nodes with multiple network interfaces, the interfaces are iterated in an unpredictable order, so adding a new interface may cause the primary IP to change. This has apparently always been a problem but until recently people could work around it by using `--node-ip` to force the correct IP to be chosen. This is no longer really possible in 4.x so we need to fix the code to select the right IP itself.

Bug 1734319: aws: sort addresses of multiple interfaces correctly

---

vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go
vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp_test.go

This was a manual process of bringing in changes from mentioned UPSTREAM commits.   
This is a pick-ish of  [UPSTREAM: 80871](https://github.com/kubernetes/kubernetes/pull/80871) (that is an automatic cherry-pick of 80436 on kube release-1.13)  kube only carried as far as 1.13

Bug 1737654: UPSTREAM: 75037: UPSTREAM: 76788: UPSTREAM: 80436

---

test/extended/operators/operators.go

The check was dropped in 040f521 [1] during the rebase. reinstating the check correctly.
[1]: https://github.com/openshift/origin/commit/040f521d78039a06be7c5393bc6968285ae4ba4e

Bug 1751820: test/extended/operators: ensure clusterversion current version is set

---

test/extended/util/url/url.go

Truncate the `/tmp/body` and `/tmp/headers` files in the shell script for each `url.Expect` clause to prevent a failing test from printing "No such file or directory" errors or stale output from a previous test.
* `test/extended/util/url/url.go` (`ToShell`): Add a command to truncate `/tmp/body` and `/tmp/headers` before running `curl` in the generated script.

test/extended/util/url: Truncate test output files

---

pkg/oauthserver/oauth/handlers/default_auth_handler.go
pkg/oauthserver/oauth/handlers/default_auth_handler_test.go

Certain browsers might interpret the 500 error page as an HTML
page even though it's text/plain in some corner cases.
cc @enj

Bug 1757046: Sanitize user input when erroring on an unknown redirect handler [4.1]

---

pkg/network/node/networkpolicy.go
pkg/network/node/networkpolicy_test.go

Backport of https://github.com/openshift/sdn/pull/36 and https://github.com/openshift/sdn/pull/42 to 4.1. Other than moving from sdn to origin, no changes were needed.

Bug 1758233: NetworkPolicy performance fixes [4.1]

---

test/extended/prometheus/prometheus.go

We unnecessarily wrap the metric in `sum` function, because we are counting the results either way. Not wrapping that into the sum allows us to see the actual fired alrerts when they exceed the 2, example:
```
fail [github.com/openshift/origin/test/extended/prometheus/prometheus_builds.go:166]: Expected
<map[string]error | len:1>: {
"ALERTS{alertstate=\"firing\"}": {
s: "query ALERTS{alertstate=\"firing\"} for tests []prometheus.metricTest{prometheus.metricTest{labels:map[string]string(nil), greaterThanEqual:false, value:-1, success:false}} had results {\"status\":\"success\",\"data\":{\"resultType\":\"vector\",\"result\":[{\"metric\":{\"__name__\":\"ALERTS\",\"alertname\":\"Watchdog\",\"alertstate\":\"firing\",\"severity\":\"none\"},\"value\":[1571674299.451,\"1\"]}]}}",
},
}
```
I …

Make the metric more readable when fails

---

vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
vendor/k8s.io/kubernetes/pkg/controller/controller_utils_test.go
vendor/k8s.io/kubernetes/pkg/controller/replicaset/BUILD
vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go
vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set_test.go
vendor/k8s.io/kubernetes/test/e2e/apps/deployment.go
vendor/k8s.io/kubernetes/test/e2e/apps/types.go
vendor/k8s.io/kubernetes/test/e2e/framework/service/jig.go

When scaling down a ReplicaSet, delete doubled up replicas first, where a "doubled up replica" is defined as one that is on the same node as an active replica belonging to a related ReplicaSet.  ReplicaSets are considered "related" if they have a common controller (typically a Deployment).
My intention with this change is to make a rolling update of a Deployment scale down the old ReplicaSet as it scales up the new ReplicaSet by deleting pods from the old ReplicaSet that are colocated with ready pods of the new ReplicaSet.  This change in the behavior of rolling updates can be combined with pod affinity rules to preserve the locality of a Deployment's pods over rollout.
A specific scenario that benefits from this change is when a Deployment's pods are exposed by a Service that has type …

UPSTREAM: 80004: Prefer to delete doubled-up pods of a ReplicaSet

---

test/extended/builds/s2i_quota.go

It is currently failing with cri-o 1.16 so disabling
the test for now to unblock cri-o.
Have opened a high severity bug for this https://bugzilla.redhat.com/show_bug.cgi?id=1764323
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

Disable the s2i build with quota memory test

---

test/extended/router/scoped.go

Many router tests use `waitForRouterOKResponseExec()` to wait for test route
connectivity. However, due to a bug in the check script, if the underlying
`curl` command times out once during checks, the `waitForRouterOKResponseExec()`
function will always time out even if the target route becomes responsive.
If the `curl` command itself never times out, the function works properly.
Fix the check script so that `curl` timeouts are correctly handled.
This probably fixes many e2e flakes associated with router tests which use
`waitForRouterOKResponseExec()`.

Bug 1765177: e2e: fix flaky route wait function

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go

This replaces our temporary patch introduced in #23936 with proper upstream patch. This removes our extra logging of Attach/Detach.
https://github.com/kubernetes/kubernetes/pull/84181
https://bugzilla.redhat.com/show_bug.cgi?id=1759998

Bug 1759998: Bug 1690588: UPSTREAM: 84181: Lower AWS DescribeVolume frequency

---

test/extended/prometheus/prometheus.go

Alerts are fired in skewed environments which prevent tests from
passing. This is required for the 4.2 and 4.1 skew tests to pass.

Bug 1753071: Skip alert test when test environment is known to be skewed

---

test/extended/operators/olm.go

@bparees @ecordell @njhale As title, please have a review. Thanks! cc: @cuipinghuo @scolange @chengzhang1016 @zihantang-rh @emmajiafan @jianzhangbjz 
Log shows as below.
```
./openshift-tests run all --dry-run | grep "OLM should have imagePullPolicy:IfNotPresent" | ./openshift-tests run -f -
started: (0/1/1) "[Feature:Platform] OLM should have imagePullPolicy:IfNotPresent on thier deployments [Suite:openshift/conformance/parallel]"
Sep  2 20:19:33.796: INFO: >>> kubeConfig: /home/vagrant/kubeconfig
Sep  2 20:19:33.801: INFO: Waiting up to 30m0s for all (but 100) nodes to be schedulable
Sep  2 20:19:34.918: INFO: Waiting up to 10m0s for all pods (need at least 0) in namespace 'kube-system' to be running and ready
Sep  2 20:19:35.454: INFO: 0 / 0 pods in namespace 'kube-system' are running …
```

Automate [OLM] [OCP-24061] - [bz 1685230] OLM operator should use imagePullPolicy: IfNotPresent

---

test/extended/operators/operators.go

The ClusterVersions config/v1 type has no status.desired.payload: https://github.com/openshift/api/blob/master/config/v1/types_cluster_version.go#L197
Pruning will remove this value. It blocks 1.16.2 rebase.
This reverts commit 2f21b747a119d1427111987255a508e4e26b086f.

Revert "test/extended/operators: ensure clusterversion current version is set"

---

test/extended/prometheus/prometheus.go
test/extended/prometheus/prometheus_builds.go

Revert #23995 and improve reporting of which alerts are firing.

test/extended/prometheus: better check for firing alerts

---

test/extended/router/config_manager.go
test/extended/router/headers.go
test/extended/router/scoped.go

Follow-up to 34297f29e11c14918bbc098cf06598755419f89b with newly discovered
instances where a return code variable is uninitialized leading to flaky
wait behavior.

e2e: fix more flaky route wait functions

---

vendor/k8s.io/kubernetes/test/e2e/framework/pod/resource.go

To help in FIPS debugging, add pod logs to the e2e dump.

UPSTREAM: carry: add pod logs dump to e2e

---

test/extended/machines/machines.go
test/extended/operators/images.go
test/extended/operators/qos.go
test/extended/operators/tolerations.go

These tests are not necessary for preventing a bad CI run, just for
ensuring tests are valid.

test: Fewer smoke tests

---

vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/config/testdata/defaulting/controlplane/defaulted.yaml
vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/config/testdata/defaulting/controlplane/defaulted_non_linux.yaml
vendor/k8s.io/kubernetes/pkg/kubelet/apis/config/v1beta1/defaults.go

Pick of UPSTREAM: 74781: kubelet watch-manager test, restore watch-based manager default
We should be using the watch-based manager in 4.2 to reduce apiserver load.

Bug 1757234: Cherry-pick: Kubelet should use watch-based configMapAndSecretChangeDetectionStrategy

---

test/extended/router/metrics.go
test/extended/router/reencrypt.go

Specify the correct namespace to `DumpPodLogsStartingWithInNamespace`.
In OpenShift v3, the installer creates the default router in the `default` namespace, but in OpenShift v4, the ingress operator creates routers in the `openshift-ingress` namespace.
* `test/extended/router/metrics.go`:
* `test/extended/router/reencrypt.go`: Change the namespace argument for `DumpPodLogsStartingWithInNamespace` from `default` to `openshift-ingress`.

test/extended/router: Fix namespace for DumpPodLogs

---

test/extended/util/client.go

Fix the deferred call to the `cancel` function in `SetupProject`.
`SetupProject` has a deferred call to the function in the variable named `cancel`, which is initialized to a no-op function with the expectation that subsequent statements may assign another function to the variable.  However, because `defer` statements evaluate their expressions immediately, what is actually deferred is a call to the initial value of the `cancel` variable (i.e., the no-op function).  To defer a call to whatever is in the `cancel` variable when the deferred statement is executed, an anonymous function that calls the `cancel` function must be used, so that the variable is closed over at the point of the `defer` statement and only evaluated when the deferred statement is executed.
* …

test/extended/util: SetupProject: Fix cancel logic

---

test/extended/oauth/requestheaders.go

This fixes a not-surprisingly often observed flake.
Partially replaces current changes in https://github.com/openshift/origin/pull/24042

e2e: RequestHeader IDP: fix common flake

---

cmd/openshift-tests/e2e.go

@akram @waveywaves @openshift/openshift-team-developer-experience FYI
some of the individual ginkgo contexts are taking 12 to 15 minutes, and the test time is currently 20 minutes as you can see in the commit diff

try to run all 4 jenkins e2e ginkgos in parallel before bumping timeout

---

test/extended/cli/explain.go

Supersedes https://github.com/openshift/origin/pull/23935

Bug 1756421: bring back explain tests

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce_fake.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce_instancegroup.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce_loadbalancer_internal.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce_loadbalancer_internal_test.go

upstream PR: https://github.com/kubernetes/kubernetes/pull/84466
This is required for internal cluster support in GCP, otherwise we can't use internal LB for API and also have other internal LB service type load balancer because control-plane is also part of the LB backend for all such k8s services.

Upstream 84466: gce: ensureInternalInstanceGroups: reuse instance-groups for internal load balancers

---

test/extended/util/framework.go

Build controller logs updated to directly report the internal registry hostname.
Blocked by https://github.com/openshift/openshift-controller-manager/pull/45

Update build e2e check for internal registry host

---

test/extended/util/disruption/disruption.go

We need a relatively high level catch, caught during upgrade tests
where we observed this panic escape a goroutine.

test: Catch panics in the disruption suite

---

test/extended/prometheus/prometheus.go

We shouldn't have any failing rule evaluation in a fresh cluster. If it is firing, it usually means there is a problem with promQL.
/cc @LiliC @simonpasquier @s-urbaniak

[MON-832] test/extended/prometheus: check if any rule evaluation is failing

---

test/extended/router/metrics.go

The router metrics tests assume they're talking to a single router pod. During
the v4 refactor, this assumption broke, and the test connection to the router
was load-balanced to router pods behind the router service. This made the test
flaky.
Refactor the test to discover and operate against a single ingress endpoint.

Bug 1683057: Fix router metrics test flakes

---

vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/network/externalipranger/externalip_admission.go
vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/network/externalipranger/externalip_admission_test.go

In case the supplied external IPs in the service spec are valid,
allow the RBAC check to override the specified ranges in the
external IP range checker.

Bug 1759181: UPSTREAM: <carry>:Add a RBAC checker for external IP ranger

---

test/extended/operators/qos.go
test/extended/operators/tolerations.go

Because the test runs when other tests run, it can sometimes fail
if must gather happens to be running. It's ok for must-gather pods
to tolerate all taints.

test: must-gather pods may tolerate all taints

---

test/extended/util/test.go

The test was enabled in https://github.com/openshift/origin/pull/23921, but then accidentally disabled by https://github.com/openshift/origin/pull/23894 (github did not catch it as conflict).

Bug 1751640: Enable block bad-case tests

---

test/extended/controller_manager/pull_secret.go

Known broken bug, team has it on their priority list.

test: Disable TestDockercfgTokenDeletedController until fixed

---

test/extended/router/metrics.go
test/extended/router/scoped.go
test/extended/router/weighted.go

On AWS, the default router speaks PROXY protocol. The fix in
https://github.com/openshift/origin/pull/24075 switched some router tests to
(correctly) speak to the router directly. However, the fix did not update client
code to speak PROXY to the router on AWS. The tests still sometimes pass on AWS
by coincidence (as other non-test clients send traffic to the router through the
LB, causing router stats to sometimes match test expectations.)
Fix the tests so that test clients talking to routers use PROXY protocol on AWS.

e2e: fix router metrics test flake on AWS

---

OWNERS

He was in vendor/OWNERS that got accidentally removed in #24014. Since it's common to remove files in vendor/ during rebases, adding him to top-level OWNERS is more stable.

Add Ben as top-level OWNER

---

vendor/k8s.io/kubernetes/test/e2e/framework/util.go

Backport of https://github.com/kubernetes/kubernetes/pull/84513
In case node object update fails due to revision conflict, it does not make sense to return success.
It needs to be retried so the v1.PreferAvoidPodsAnnotationKey annotation can be properly set in the next round.

bug 1713134: UPSTREAM: 84513: test/e2e: AddOrUpdateAvoidPodOnNode/RemoveAvoidPodsOffNode: retry when conflict hit during annotation update

---

test/extended/operators/cluster.go

No reason to fail on these tests.

test: Skip pending must-gather pods in the crashloop test

---

test/extended/testdata/bindata.go
test/extended/testdata/jobs/v1.yaml

All the tests in k8s repos are now started using docker.io/busybox and it will be good to keep sync with that and will be helpful in terms of running tests on non-amd64 platforms as well.

Switch to docker.io/busybox

---

vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
vendor/k8s.io/kubernetes/pkg/controller/controller_utils_test.go
vendor/k8s.io/kubernetes/pkg/controller/replicaset/BUILD
vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go
vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set_test.go
vendor/k8s.io/kubernetes/test/e2e/apps/deployment.go
vendor/k8s.io/kubernetes/test/e2e/apps/types.go
vendor/k8s.io/kubernetes/test/e2e/framework/service/jig.go

This commit brings back https://github.com/openshift/origin/pull/23806, which was dropped during a rebase scuffle (see https://github.com/openshift/origin/pull/24014#commitcomment-35709732), and adds a fix for [BZ#1765756](https://bugzilla.redhat.com/show_bug.cgi?id=1765756).
---
When scaling down a ReplicaSet, delete doubled up replicas first, where a "doubled up replica" is defined as one that is on the same node as an active replica belonging to a related ReplicaSet.  ReplicaSets are considered "related" if they have a common controller (typically a Deployment).
The intention of this change is to make a rolling update of a Deployment scale down the old ReplicaSet as it scales up the new ReplicaSet by deleting pods from the old ReplicaSet that are colocated with ready pods of the new …

Bug 1765756: UPSTREAM: 80004: Prefer to delete doubled-up pods of a ReplicaSet

---

test/extended/prometheus/prometheus.go

Sometimes Prometheus seems to report not having scraped the target
for the ingresscontroller created during this test, even after 4 minutes.
Since this test for the user-defined ingresscontroller seems inessential
compared to the latest ingress-operator e2e tests, rather than increasing
the timeout or spending additional effort to root-cause the scrape delay,
just delete the test to stabilize the test suite.

Bug 1757807: e2e: stabilize ingress metrics tests

---

vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
vendor/k8s.io/kubernetes/pkg/controller/cronjob/BUILD
vendor/k8s.io/kubernetes/pkg/controller/cronjob/cronjob_controller.go
vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
vendor/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go
vendor/k8s.io/kubernetes/pkg/controller/deployment/sync.go
vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go
vendor/k8s.io/kubernetes/pkg/controller/endpointslice/reconciler.go
vendor/k8s.io/kubernetes/pkg/controller/job/job_controller.go
vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go
vendor/k8s.io/kubernetes/pkg/controller/serviceaccount/serviceaccounts_controller.go
vendor/k8s.io/kubernetes/pkg/controller/serviceaccount/tokens_controller.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/api/core/v1/types.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/BUILD
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission_test.go

Several controllers spam the apiserver during namespace deletion. Make
it easier for clients to detect namespace deletion and stop trying
when a namespace is deleting.

UPSTREAM: 84123: Handle namespace shutdown gracefully

---

vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver.go
vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver_test.go

I made some wrong assumptions about turning TLS1.3 on for 1.12 golang binaries...

apiserver crd validation: remove tls1.3 and modern profile

---

test/extended/oauth/groupsync.go
test/extended/util/framework.go
test/extended/util/ldap.go
test/extended/util/oauthserver/oauthserver.go

Fixes a couple of issues with the LDAP e2e tests
Also tries to fix https://bugzilla.redhat.com/show_bug.cgi?id=1759248

Bug 1763988: LDAP e2e: add dnf install retries, extend run timeout

---

test/extended/oauth/requestheaders.go

Don't force our client certificates on the server, instead respect
the selection of CAs the server sends us to pick the correct trusted
client cert.
This should be breaking tests until https://github.com/openshift/oauth-server/pull/19 get merged

e2e requestheader: make client follow TLS correctly

---

test/extended/builds/cluster_config.go

* Make sure the OCM rollout completes between disruptive test runs.
/assign @gabemontero 
fyi @openshift/openshift-team-developer-experience

Check ocm rollout between build tests

---

test/extended/router/config_manager.go
test/extended/router/headers.go
test/extended/router/scoped.go

Many router tests use `waitForRouterOKResponseExec()` to wait for test route
connectivity. However, due to a bug in the check script, if the underlying
`curl` command times out once during checks, the `waitForRouterOKResponseExec()`
function will always time out even if the target route becomes responsive.
If the `curl` command itself never times out, the function works properly.
Fix the check script so that `curl` timeouts are correctly handled.
This probably fixes many e2e flakes associated with router tests which use
`waitForRouterOKResponseExec()`.

[release-4.2] Bug 1765179: e2e: fix flaky route wait functions

---

test/extended/authorization/rbac/groups_default_rules.go

The PR https://github.com/openshift/openshift-apiserver/pull/42 adds
this rule to the defaults; so, we need to expect it as part of the
tests.

Add "get configmaps from openshift namespace" rule to expected rules

---

test/extended/router/headers.go
test/extended/util/test.go

This change loosens the test expectations for AWS only.
On AWS the packet (GET request) leaves the cluster and will be NAT'd;
source addresses will now reflect the elastic IP address of the node.
Matching on the PODs IP address is therefore not possible on AWS; we
now assert that we have an 'X-Forwarded-For' header only.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1752646

Bug 1752646: e2e: Re-enable HAProxy router header test

---

vendor/k8s.io/kubernetes/test/e2e/framework/framework.go

I reviewed [BZ1768262](https://bugzilla.redhat.com/show_bug.cgi?id=1768262#c4) and various CI builds leading to the `Cluster upgrade should maintain a functioning cluster` error. The timeout for nodes to be ready is 3 minutes. 3 minutes is a relatively short period of time for a node to boot, get networking provisioned, and restart pods. A number of pods are transitioning to running after the timeout has triggered within CI, which has failed the test.
This PR bumps the timeout to 7 minutes.
/cc @sjenning

Bug 1768262: Bump nodes ready timeout

---

test/extended/builds/new_app.go

Ensure that `oc new-app` works with the `--image-stream` argument set.

Bug 1767163: Verify new-app works with imagestream

---

cmd/openshift-tests/csi.go
cmd/openshift-tests/openshift-tests.go
test/extended/csi/install.go
test/extended/testdata/bindata.go
test/extended/testdata/csi/README.md
test/extended/testdata/csi/aws-ebs/install-template.yaml
test/extended/testdata/csi/aws-ebs/manifest.yaml

Goal: create a prow job that tests CSI sidecars shipped as part of OCP / OKD. In the future, use the same approach to test CSI drivers too.
There are 6 CSI sidecars in total (and the number is growing), so to simplify job definition in each repostory, I embedded AWS EBS driver yaml files into openshift-tests.
Prow configs for each sidecar repo would then contain something like this:
```
- as: e2e-aws-csi
commands: TEST_INSTALL_CSI_DRIVERS=aws-ebs TEST_SUITE=openshift/csi run-tests
openshift_installer:
cluster_profile: aws
upgrade: false
```
Env. variables are the easiest to pass between parent openshift-test and child openshift-test processes. It's a bit hacky though. I tried command line arguments, you can find the unsuccessful attempt in the commits in this PR. 
The architecture is open …

Install CSI driver on openshift-test start.

---

vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go
vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_ebs.go
vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_ebs_block.go
vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_ebs_block_test.go
vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_ebs_test.go
vendor/k8s.io/kubernetes/pkg/volume/awsebs/aws_util.go
vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder_block.go
vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder_block_test.go
vendor/k8s.io/kubernetes/pkg/volume/gcepd/gce_pd_block.go
vendor/k8s.io/kubernetes/pkg/volume/gcepd/gce_pd_block_test.go
vendor/k8s.io/kubernetes/pkg/volume/local/local.go
vendor/k8s.io/kubernetes/pkg/volume/local/local_test.go
vendor/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume_block.go
vendor/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume_block_test.go
vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/disruptive.go
vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go
vendor/k8s.io/kubernetes/test/e2e/storage/utils/BUILD
vendor/k8s.io/kubernetes/test/e2e/storage/utils/utils.go

This is cumulative backport for all issues that have been fixed in block and local volume reconstruction in 1.17 cycle as part of Block volum GA feature.
Backported PRs:
* https://github.com/kubernetes/kubernetes/pull/83451
* https://github.com/kubernetes/kubernetes/pull/83466
* https://github.com/kubernetes/kubernetes/pull/84173
* https://github.com/kubernetes/kubernetes/pull/84218

Bug 1758543: Fix volume reconstruction

---

test/extended/controller_manager/pull_secret.go

The passive way of waiting for events to come in through a Watch may be
causing some problems with this specific test. This PR converts it into
an active polling approach.

Bug 1765294:  Changing from passive to active approach on secret deletion.

---

test/extended/images/imagestream.go

Have seen this test failing if rerun on the same setup again as we are not deleting the image post-run, hence cleanup is required to have a clean environment!

Cleanup created image

---

test/extended/router/stress.go

The stress.go test makes some brittle assumptions about the number of writes to
Route resources in a namespace. The assumptions used to hold true on v3
clusters, but in v4 there are other routers which break the assumptions.
For now, relax the assumptions. In the future, this test should probably be
refactored to not rely on specific write counts.

Bug 1768002: Stabilize router stress test

---

test/extended/router/config_manager.go
test/extended/router/scoped.go
test/extended/router/stress.go
test/extended/router/unprivileged.go
test/extended/router/weighted.go
test/extended/testdata/bindata.go
test/extended/testdata/router/router-config-manager.yaml
test/extended/testdata/router/router-override-domains.yaml
test/extended/testdata/router/router-override.yaml
test/extended/testdata/router/router-scoped.yaml
test/extended/testdata/router/weighted-router.yaml
test/extended/util/framework.go

The router e2e tests are using a hard-coded router test image from dockerhub
that isn't part of the release payload. Fix the tests to discover the router
image from the clusteroperator/ingress resource, which references the image used
by the ingress operator.
Depends on https://github.com/openshift/router/pull/60

Bug 1762162: e2e: fix incorrect router image references

---

test/extended/cli/explain.go

Requires openshift/cluster-openshift-controller-manager-operator#131 to
merge first.

Bug 1769016: Verify ocm's CRD schema

---

test/extended/util/test.go

Not expected to work yet. Only recently was re-enabled for SDN too, so clearly
it's not a huge issue that the test fails (at least for now).
@danwinship

test/extended: skip "Services should be rejected when no endpoints exist" for OVNKubernetes

---

test/extended/router/headers.go

This is a follow-up to https://github.com/openshift/origin/pull/24093 which breaks (or flakes on) OpenStack.
Rather than trying to run down all the flakes on all the platforms in
4.3 I've changed the router header test to run against the following
platforms only:
- AWS
- Azure
- GCP
A new BZ[1] has been opened to ensure that the other platforms are not
forgotten.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1772125

e2e: run router header test on AWS/GCP/Azure only

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce_loadbalancer_internal.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce_loadbalancer_internal_test.go

Make sure we don't ensure cluster-managed instance group for a zone that has no more nodes left. Creating am IG for a zone that has no instances causes errors when attaching to backend service.
```
failed to ensure load balancer: googleapi: Error 400: Invalid value for field 'resource.backends[5].group': 'https://www.googleapis.com/compute/v1/projects/openshift-qe/zones/us-central1-c/instanceGroups/k8s-ig--8d8682bc12c7a717'. Instance group must have a network to be attached to a backend service. Add an instance to give the instance group a network., invalid
```

Bug 1767295: UPSTREAM: 84466: gce: skip ensureInstanceGroup for a zone that has no remaining nodes for k8s managed IG

---

test/e2e/upgrade/monitor.go

The use of `percent <=` meant that we never aborted at 100%. We should
use `percent <` so that we rollback after all operators are upgraded.

test: Upgrade rollback abort at 100 should work

---

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_fakes.go
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_test.go

Bug 1758158: aws: sort addresses of multiple interfaces correctly [4.2]

---

test/extended/prometheus/prometheus.go
test/extended/prometheus/prometheus_builds.go

This extends test framework by adding a way to expect no metrics being
returned. Additionally it should improve testing if no alerts are
firing, apart from Watchdog.
Backporting MON-813 from #24019

Bug 1767182: test/extended/prometheus: run full promQL queries and improve reporting firing alerts

---

cmd/oc/oc.go

This is a cherry-pick of https://github.com/openshift/oc/pull/41 onto 4.1 release.
/assign @sttts

Bug 1764147: don't install CRD SCC types into global scheme

---

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_fakes.go
vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws_test.go

Bug 1758159: aws: sort addresses of multiple interfaces correctly [4.1]

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce_loadbalancer_internal.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce_loadbalancer_internal_test.go

Make sure we don't ensure cluster-managed instance group for a zone that has no more nodes left. Creating am IG for a zone that has no instances causes errors when attaching to backend service.
```
failed to ensure load balancer: googleapi: Error 400: Invalid value for field 'resource.backends[5].group': 'https://www.googleapis.com/compute/v1/projects/openshift-qe/zones/us-central1-c/instanceGroups/k8s-ig--8d8682bc12c7a717'. Instance group must have a network to be attached to a backend service. Add an instance to give the instance group a network., invalid
```
This was  merged with https://github.com/openshift/origin/pull/24135 but was reverted in https://github.com/openshift/origin/pull/24159
/cc @sttts @sdodson

UPSTREAM: 84466: gce: skip ensureInstanceGroup for a zone that has noremaining nodes for k8s managed IG

---

test/extended/prometheus/prometheus.go
test/extended/prometheus/prometheus_builds.go

Ensure there are no regressions.

test: Verify platform metrics are available

---

vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
vendor/k8s.io/kubernetes/pkg/controller/cronjob/BUILD
vendor/k8s.io/kubernetes/pkg/controller/cronjob/cronjob_controller.go
vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
vendor/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go
vendor/k8s.io/kubernetes/pkg/controller/deployment/sync.go
vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go
vendor/k8s.io/kubernetes/pkg/controller/endpointslice/reconciler.go
vendor/k8s.io/kubernetes/pkg/controller/job/job_controller.go
vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go
vendor/k8s.io/kubernetes/pkg/controller/serviceaccount/serviceaccounts_controller.go
vendor/k8s.io/kubernetes/pkg/controller/serviceaccount/tokens_controller.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/api/core/v1/types.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/BUILD
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission_test.go

Part of https://github.com/openshift/origin/pull/24195
Several controllers spam the apiserver during namespace deletion. Make
it easier for clients to detect namespace deletion and stop trying
when a namespace is deleting.

Bug 1776351: Restore UPSTREAM: 84123: Handle namespace shutdown gracefully

---

vendor/k8s.io/kubernetes/test/e2e/framework/framework.go

Part of https://github.com/openshift/origin/pull/24195

Bug 1776351: Restore UPSTREAM: <carry>: bump nodes ready timeout

---

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_server_journal.go

Part of https://github.com/openshift/origin/pull/24195.

Bug 1776351: Restore UPSTREAM from #24159: Expose a simple journald shim on the kubelet logs endpoint

---

vendor/k8s.io/kubernetes/pkg/volume/rbd/rbd_test.go
vendor/k8s.io/kubernetes/pkg/volume/rbd/rbd_util.go

Fixes  https://bugzilla.redhat.com/show_bug.cgi?id=1719686
This PR basically fixes 3 issues with ceph expansion:
1. upstream PR#72431 fixes problem with parsing of output by converting output to json. But this is not enough because `rbd` command seems to spew random warnings to stderr when ceph keyring file is missing 
2. upstream PR#75588 fixes silencing some of those warnings logged to stderr so as JSON output could be parsed correctly. But this is not enough because in Openshift we seem to have bundled rather old `ceph-common` package and not all warnings are silenced by `-k=/dev/null` option
3. The carry patch uses bit of heavy handed approach and skips using `mount.Exec` interface which combines stdout and stderr, in favour of `os/exec` so as we could just read `stdout`. This fixes …

Bug 1719686: Fix ceph expansion

---

vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/aggregator.go
vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/apiextensions.go
vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/patch_openshift.go
vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch.go

This avoids a second coordinated callback that is prone to error on rebases.
If this works, I'll open the upstream.

inject poststarthooks via config

---

vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver.go
vendor/k8s.io/kubernetes/openshift-kube-apiserver/admission/customresourcevalidation/apiserver/validate_apiserver_test.go

Part of https://github.com/openshift/origin/pull/24195.

Bug 1776351: Restore UPSTREAM:<carry>: apiserver crd validation: remove tls1.3 and modern profile

---

test/extended/controller_manager/pull_secret.go

Currently a high source of flakes preventing merge.
Disabling until root cause is fixed.

Bug 1765294: Disable flaking token delete test

---

publishing-staging-rules.yaml

We don't have any staging repo so this is redundant.

remove publishing staging rules

---

pkg/oauthserver/oauthserver/auth.go

OAuth server uses the APIServer wrapping for its endpoints. This
wrapping has its own RequestHeader IdP for the cluster admin login
with client cert. As a part of that, before the RequestHeader is
set, DelegatingAuthenticationOptions() adds its own ClientCA to
the serving info config.
The result of the above behavior is that during TLS handshake, when
the names for acceptable client certificate CAs are announced, the
CAs of the above mentioned apiserver RequestHeader IdP are announced.
When users configure their own RequestHeader IdP to be used in
OpenShift for the oauth-server to try to retrieve the users from,
oauth-server was not adding this RequestHeader's client CA name
among the acceptable client certificate CA names mentioned above.
This commit adds the client CA data from the user …

Bug 1739262: RequestHeaders IdP: fix TLS handshake [4.1]

---

test/extended/util/oauthserver/oauthserver.go

It seems that the images are being pulled for up to 55 seconds in
the CI test runs, which would leave the oauth-server to start for
only about 5 seconds.
Increase the timeout for pod readiness in order to stop jobs from
failing too often.

extended util oauthserver - increase pod ready wait time

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/v2/conversion.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/v2/conversion_test.go

kubectl would fall over null values for required, nullable fields. This removes these fields from the required field set.

UPSTREAM: 85722: apiextensions: filter required nullable to workaround kubectl validation

---

tools/rebasehelpers/commitchecker/commitchecker.go
tools/rebasehelpers/commitchecker/validate.go
tools/rebasehelpers/commitchecker/validate_test.go
tools/rebasehelpers/util/git.go
tools/rebasehelpers/util/git_test.go

Rewrite commitchecker so it validates bumps as well

---

test/extended/prometheus/prometheus.go
test/extended/prometheus/prometheus_builds.go

Since 10c6be0169 (#24117), we've been failing after only a few seconds of failures, which causes problems like:
```
fail [github.com/openshift/origin/test/extended/prometheus/prometheus_builds.go:156]: Expected
<map[string]error | len:1>: {
"openshift_build_total{phase=\"Complete\"} >= 0": {
s: "promQL query: openshift_build_total{phase=\"Complete\"} >= 0 had reported incorrect results: model.Vector{}",
},
}
to be empty
...
failed: (1m4s) 2019-11-26T23:05:24 "[Feature:Prometheus][Feature:Builds] Prometheus when installed on the cluster should start and expose a secured proxy and verify build metrics [Suite:openshift/conformance/parallel]"
```
when we haven't waited long enough for the Prometheus scrape to notice the new builds.  Looking at the timing in that job:
```console
$ curl -s …
```

Bug 1777189: test/extended/prometheus/prometheus_builds: Wait up to 40s

---

cmd/openshift-tests/openshift-tests.go
test/extended/util/test.go

Ensure that if a user does `--dry-run` and `--provider=aws` we do
the right thing. Also add `vsphere` to ensure we can test this way.

test: Don't load client on dryRun or perform cloud autodetect

---

cmd/openshift-tests/e2e.go
cmd/openshift-tests/openshift-tests.go
pkg/test/ginkgo/cmd_runsuite.go
pkg/test/ginkgo/test.go
test/extended/util/cloud/cloud.go
vendor/k8s.io/kubernetes/test/e2e/framework/util.go

Network stress runs the standard network tests 15 times at parallelism 30. 
This isn't perfectly representative of real stress testing - it does not 
verify that existing pods work, and doesn't take disruption or other 
transient behavior into account. But it at least can be used to surface 
problems that occur rarely.

test: Add a network stress test and --count to repeat tests

---

test/extended/cli/explain.go

This PR:
1. prints CRD yaml when it fails match
2. uncoments CRDs which pass explain tests
/assign @sttts

Explain tests

---

test/extended/marketplace/marketplace_lables.go

Fix a flake in an operator-marketplace extended test by polling for packagemanifests instead of assuming they are immediately available.

 Bug 1779340: test(marketplace): poll for packagemanifests

---

test/extended/prometheus/prometheus.go

This will be temporarily required in order to switch sending telemetry to Prometheus native remote-write capabilities (https://github.com/openshift/cluster-monitoring-operator/pull/434). We will want to merge this PR and https://github.com/openshift/cluster-monitoring-operator/pull/434 quickly after each other and then enable the here commented out check that verifies, that remote-write successfully sent data instead of the bespoke telemeter client.
Telemetry via remote-write can only be accepted by the v2 receiving infrastructure, so we need to hold off on merging this and https://github.com/openshift/cluster-monitoring-operator/pull/434 until the infrastructure is completely migrated.
@s-urbaniak @paulfantom @LiliC @squat @smarterclayton 
/hold

tests/extented/prometheus: Disable telemetry e2e for remote-write move

---

vendor/k8s.io/kubernetes/pkg/kubelet/stats/cadvisor_stats_provider.go
vendor/k8s.io/kubernetes/pkg/kubelet/stats/cadvisor_stats_provider_test.go

Backports my fix from upstream with the kubelet injecting duplicate metrics causing 500 on the Kubelet's metric endpoint.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1748073
cc @mrunalp @sjenning

Bug 1748073: UPSTREAM: 86009: kubelet: guarantee at most only one cinfo per containerID

---

test/extended/util/framework.go

Update 4.2 tests so they can detect the internal registry hostname was
published and loaded by the build controller.

Bug 1781302: Handle build controller skew in tests

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/skeleton.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder/builder.go
vendor/k8s.io/kubernetes/test/integration/apiserver/apply/apply_crd_test.go

This picks an upstream commit which fixes complaints from SSA about nullable being invalid, by stripping nullable which is unsupported by SSA

Bug 1781768: UPSTREAM: 85162: Strip nullable for server-side apply

---

pkg/network/admission/externalipranger/externalip_admission.go
pkg/network/admission/externalipranger/externalip_admission_test.go

In case the supplied external IPs in the service spec are valid,
allow the RBAC check to override the specified ranges in the
external IP range checker.

Bug 1759182: Add a RBAC checker for external IP ranger

---

OWNERS

If this works, disabling vendor changes because of rebase should be a simple switch in prow merge search query.
/cc @deads2k @stevekuznetsov 

Label vendor updates

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/cached_discovery.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/cached_discovery_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/round_tripper.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/discovery/round_tripper_test.go

Bug 1718486: UPSTREAM: 77874: fix CVE-2019-11244: kubectl --http-cache=<world-accessible dir>

---

test/extended/operators/olm.go

@ecordell @njhale As title, please have a review. Thanks! cc: @cuipinghuo @scolange @chengzhang1016 @zihantang-rh @emmajiafan @jianzhangbjz 
Success execution (when every package has namespace name defined)
```
./openshift-tests run all --dry-run | grep "Implement packages API server and list packagemanifest info with namespace not NULL" | ./openshift-tests run -f -
started: (0/1/1) "[Feature:Platform] OLM should Implement packages API server and list packagemanifest info with namespace not NULL [Suite:openshift/conformance/parallel]"
E0912 16:33:36.334871   15161 request.go:853] Unexpected error when reading response body: &http.httpError{err:"context deadline exceeded (Client.Timeout exceeded while reading body)", timeout:true}
Sep 12 16:33:32.681: INFO: >>> kubeConfig: …
```

Automate [OLM] [OCP-21082] - [bz 1670311] Implement packages API server and list packagemanifest info with namespace not NULL

---

test/extended/prometheus/prometheus.go

This is necessary to merge https://github.com/openshift/cluster-monitoring-operator/pull/585

test/extended/prometheus: exclude AlertmanagerReceiversNotConfigured from checking

---

test/extended/operators/service_catalog.go
test/extended/testdata/bindata.go
test/extended/testdata/service_catalog/ups-binding.yaml
test/extended/testdata/service_catalog/ups-broker.yaml
test/extended/testdata/service_catalog/ups-deployment.yaml
test/extended/testdata/service_catalog/ups-instance.yaml
test/extended/testdata/service_catalog/ups-service.yaml

This PR will cover ServiceCatalog test cases: OCP-24062, OCP-24049, OCP-15600. @jmrodri @shawn-hurley @bparees Could you help have a review? Thanks! cc: @bandrade @scolange @cuipinghuo @chengzhang1016 @zihantang-rh @emmajiafan

check ServiceCatalog basic usages in OCP 4.x

---

pkg/oc/cli/image/mirror/mirror.go

Simple fix
(cherry picked from commit 72270c620de703fd9d4d07d9818ca2276c4e9086)

[3.11] Bug 1768612: mirror: Support v2_1 docker registries as mirror source

---

test/extended/testdata/bindata.go
test/extended/testdata/image_ecosystem/perl-hotdeploy/perl.json

Bug 1782467: update image eco perl imagestream refs from EOL 5.24 to 5.26

---

vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go
vendor/k8s.io/kubernetes/pkg/kubectl/cmd/cp_test.go

Bug 1753502: UPSTREAM: 82503: Reorder symlinks to prevent path escapes

---

test/extended/util/test.go

Reverts openshift/origin#24185, insufficient justification provided for disablement.

Revert "Bug 1763936: Disable node-Service and pod-Service granular checks"

---

test/extended/util/test.go

In order to increase chances to get a voting CI for OpenStack soon, I
propose to skip Network Granular Check tests that are intermittently
failing on our infrastructure.
This commit must be reverted and the issue properly investigated once
the minimum result of a voting CI is achieved.
ref.: https://bugzilla.redhat.com/show_bug.cgi?id=1763936
ref.: https://github.com/openshift/origin/pull/24313
The bug reference is not in the PR title nor leading the commit message, because this proposed change does not fix it.
/cc @knobunc 
@danwinship Do you think this work for OpenStack? Sorry I am not familiar with the skip logic, and I could not find specific documentation on the matter.

Disable flaky tests on OpenStack

---

test/extended/prometheus/prometheus.go

Follow-up to #24019.
/cc @LiliC @simonpasquier @s-urbaniak

check if ClusterMachineApproverDown UsingDeprecatedAPIExtensionsV1Beta1 alerts are not firing

---

vendor/k8s.io/kubernetes/test/e2e/framework/framework.go

baseline to use to add more test error handling.  I'd like oc inspect output on all involved namespaces and all clusteroperators

UPSTREAM: 86177: make test framework easier to re-use

---

test/extended/util/azure/config_file.go

I hope that this PR will fix the following panic observed in [e2e-azure-upgrade](https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/3/build-log.txt)
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x127b1c6]
github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).CurrentSpecSummary(...)
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:211
github.com/openshift/origin/vendor/github.com/onsi/ginkgo/internal/suite.(*Suite).CurrentRunningSpecSummary(0xc000283400, 0x121a, 0x121b) …
```

openshift-test: azure don't set the UserAgent to include the current test name when loading cloud provider config

---

test/extended/cli/adm.go

This builds on top of https://github.com/openshift/origin/pull/24258 but should not be merged until the former is merged and a new image with new kubelet is delivered otherwise this will block the queue. 
I'll drop the hold once I'm certain the prereq is deployed. 
/hold

Add adm node-logs with --since=date parameter test

---

test/extended/prometheus/prometheus_builds.go

Otherwise some failures are hard to understand (like alerts).

test: When a metrics query fails, print the samples

---

hack/test-go.sh
test/extended/operators/olm.go
test/extended/testdata/bindata.go
test/extended/testdata/olm/etcd-cluster.yaml
test/extended/testdata/olm/etcd-subscription.yaml
test/extended/testdata/olm/operatorgroup.yaml

@bparees @ecordell @njhale As title, please have a review. One question, what's the best solution to switch between `cluster-admin user` and `common user`? Do we have any code implement it? Thanks! cc: @cuipinghuo @bandrade @scolange @chengzhang1016 @zihantang-rh @emmajiafan

auto olm test case OCP-23440: the end user can use operator resources

---

test/extended/builds/s2i_quota.go

The assemble script was reading from the top of the controller's group hierarchy, even though the script itself is run inside of a different control group, which is where the settings are applied.  This is related to investigation in #24157.

Bug 1787457: Read cgroup settings from the right cgroup for build-quota tests

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/rest/request.go

UPSTREAM: 80649: Report api request throttling at v=3

Bug 1788621: Improve logging of kubelet-apiserver logging

---

test/extended/conformance-k8s.sh

OpenShift 4.3 uses Go 1.12, but Kube 1.16 used Go 1.13. Specifically
override the build of the conformance test to use Go 1.12 for this one
release (not part of future releases).

test: Override the Go version required for building the conformance test

---

test/extended/builds/run_policy.go

implementation of https://jira.coreos.com/browse/DEVEXP-95
api updates: https://github.com/openshift/api/pull/532
client-go updates(using temporary bump from bparees fork): https://github.com/openshift/client-go/pull/128
openshift-apiserver updates(using temporary bump from bparees fork): https://github.com/openshift/openshift-apiserver/pull/52
origin(e2e test, using temporary bump from bparees fork) updates: https://github.com/openshift/origin/pull/24254
This won't pass until the openshift-apiserver PR is merged.

add conditions to build api

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/cloud-provider/volume/errors/errors.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go

https://bugzilla.redhat.com/show_bug.cgi?id=1690031

Bug 1690031: UPSTREAM: 86250: AWS: Don't report deletion of attached volume as warning

---

test/extended/bootstrap_user/bootstrap_user_login.go

The test removes the kubeadmin password, efectivelly disabling it
and causing oauth-server pods redeploy.

mark bootstrap user test as disruptive

---

test/extended/operators/tolerations.go

Exclude openshift-ovirt-infra namespaces when testing
"[Feature:Platform] Managed cluster should ensure control plane operators do not make themselves unevictable"

Exclude openshift-ovirt-infra from tolerations tests

---

cmd/openshift-tests/csi.go
test/extended/csi/install.go
test/extended/testdata/bindata.go
test/extended/testdata/csi/README.md
test/extended/testdata/csi/aws-ebs/install-template.yaml
test/extended/testdata/csi/aws-ebs/manifest.yaml
test/extended/testdata/csi/aws-ebs/storageclass.yaml

This patch is the result of running the CSI certification process outlined [here](https://github.com/openshift/enhancements/pull/162/files) against the EBS CSI driver. In other words, we need this change so partners can test and certify their CSI drivers with OpenShift.
We also want to use the EBS CSI driver in our CI, so getting it to work is the first step.

Allow for customization of storageClass in the CSI test suite

---

test/extended/util/test.go

The AZ spreading tests depend on scheduler priorities, not predicates,
and thus a mostly full cluster can result in spreading being ignored
(scheduler prefers to schedule pods that violate spreading priority
if one or more nodes is full). By moving to serial, we ensure that
nodes have the necessary capacity. These tests were flaking fairly
frequently.

test: Move AZ spread e2e test to serial

---

test/extended/images/oc_tag.go

These tests ensure that we won't regress like in the [bug 1757889](https://bugzilla.redhat.com/show_bug.cgi?id=1757889).

Add tests for image references after oc tag

---

test/extended/operators/olm.go

PR Created to automate test case: @ecordell @njhale @kevinrizza. please have a review. Thanks! cc: @cuipinghuo @scolange @chengzhang1016 @emmajiafan @jianzhangbjz @tbuskey
Success execution evidence:
```
./openshift-tests run all --dry-run | grep "Report Upgradeable" | ./openshift-tests run -f -
I1226 04:35:16.456207   24579 test_context.go:419] Tolerating taints "node-role.kubernetes.io/master" when considering if nodes are ready
I1226 04:35:17.864259   24582 test_context.go:419] Tolerating taints "node-role.kubernetes.io/master" when considering if nodes are ready
started: (0/1/1) "[Feature:Platform] OLM should Report Upgradeable in OLM ClusterOperators status [Suite:openshift/conformance/parallel]"
I1226 04:35:35.374320   25071 test_context.go:419] Tolerating taints …
```

[AUTO][OLM][OCP-24829] Report `Upgradeable` in OLM ClusterOperators status

---

vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/namespace_policy.go
vendor/k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/namespace-roles.yaml

kube-scheduler was missing permissions for accessing CM kube-system/extension-apiserver-authentication
/cc @soltysh  @deads2k

[release-4.3] Bug 1790481: Fix delegated auth CM perms

---

vendor/k8s.io/kubernetes/cmd/kubelet/app/options/options.go
vendor/k8s.io/kubernetes/pkg/kubelet/nodestatus/setters.go
vendor/k8s.io/kubernetes/pkg/kubelet/nodestatus/setters_test.go

Needed for single-stack IPv6 support. Will need to be backported to 4.3 (along with another patch that is already in origin from kube 1.17).
/assign @derekwaynecarr

UPSTREAM: 85850: Allow "kubelet --node-ip ::" to mean prefer IPv6

---

test/extended/testdata/bindata.go
test/extended/testdata/csi/OWNERS
test/extended/testdata/csi/aws-ebs/install-template.yaml

These manifests may need to be edited by storage team frequently, so adding OWNERS.

Fix livenessprobe arguments and add CSI manifest OWNERS

---

test/extended/cmd/cmd.go

Since I'm deprecating `--config` flag from oc in https://github.com/openshift/oc/pull/256 the `Output` method being used in this call contains both the config file and the deprecation message which breaks the tests further. This PR make it explicit that we read only stdout when reading that config.

Fix config passing to test-cmd

---

test/extended/util/client.go

Since I'm deprecating `--config` flag from oc in openshift/oc#256 and majority of commands rely on `Output` method combining `stdout` and `stderr` they are getting the deprecation which in turns fails the rest of the test. 

Switch oc used in e2e tests to use --kubeconfig flag

---

test/extended/prometheus/prometheus.go

This alert is currently firing more sensitively than we would like.
Things are working as expected so we're just ignoring it for now and
unblocking the rest of CI.
@LiliC @s-urbaniak @smarterclayton

test/extented/prometheus: Ignore PrometheusRemoteWriteDesiredShards

---

vendor/k8s.io/kubernetes/test/e2e/framework/network/utils.go

This line makes the upgrade log output unreadable and provides
no value during the set of tests it's used in:
```
Jan 12 20:49:25.628: INFO: cluster upgrade is Progressing: Working towards registry.svc.ci.openshift.org/ci-op-jbtg7jjb/release@sha256:144e73d125cce620bdf099be9a85225ade489a95622a70075d264ea3ff79219c: downloading update
Jan 12 20:49:26.692: INFO: Poke("http://a74e3476115ce4d2d817a1e5ea608dad-802917831.us-east-1.elb.amazonaws.com:80/echo?msg=hello"): success
Jan 12 20:49:28.727: INFO: Poke("http://a74e3476115ce4d2d817a1e5ea608dad-802917831.us-east-1.elb.amazonaws.com:80/echo?msg=hello"): success
```

UPSTREAM: <carry>: Remove excessive logging during e2e upgrade test

---

test/extended/authorization/rbac/groups_default_rules.go

This resource is new in 4.4 and is created by openshift-apiserver.

test: Allow imagetags resource to be added to group RBAC

---

test/extended/etcd/leader_changes.go
test/extended/prometheus/client/via_route.go

Adds an extended test which watches the `etcd_server_leader_changes_seen_total` metric and fails if the total across all nodes is ever greater than 9.

test for excessive etcd leadership changes

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/builds.sh

Change to use centos:7 which is more consistent.

test/cmd: build.sh can't reach old openshift/origin:v1.1 image

---

test/extended/etcd/etcd_storage_path.go

This should address following failure:
```
fail [github.com/openshift/origin/test/extended/etcd/etcd_test_runner.go:72]: test failed:
no test data for image.openshift.io/v1, Kind=ImageTag.  Please add a test for your new type to etcdStorageData.
etcd data does not match the types we saw:
in etcd data but not seen:
[]
seen but not in etcd data:
[
image.openshift.io/v1, Resource=imagetags
```
Found by @smarterclayton in https://testgrid.k8s.io/redhat-openshift-ocp-release-4.4-informing#release-openshift-ocp-installer-e2e-metal-serial-4.4
Question: Why was this test not failing before and we only found this on metal?
/cc @bparees 
/cc @adambkaplan

image: add ImageTag to etcd test

---

cmd/openshift-tests/openshift-tests.go
cmd/openshift-tests/provider.go
test/extended/util/cloud/cloud.go

The --provider argument for openshift-tests accepts a string (the type)
which triggers discovery, or JSON, which previously meant "use exactly
these values". However, we have more tests which depend on logic from
implicit fields (multimaster, region, zone, and number of nodes) that
we don't want to have accidentally off. This was recently triggered
when refactoring the methods in that numNodes was lost in CI, causing
certain networking tests not to run.
This commit changes openshift-tests run/run-upgrade to attempt to fill
all fields of the config even when JSON is passed to --provider by
invoking the cloud config load method, then updating provider for
the subsequent exec'd test command so that it is accurate. The run-test
command does not perform discovery, which forces the suite runner …

test: Set appropriate cloud defaults even when not specified on tests

---

vendor/k8s.io/kubernetes/openshift-kube-apiserver/authentication/oauth/expirationvalidator_test.go
vendor/k8s.io/kubernetes/openshift-kube-apiserver/authentication/oauth/tokenauthenticator.go
vendor/k8s.io/kubernetes/openshift-kube-apiserver/authentication/oauth/tokenauthenticator_test.go
vendor/k8s.io/kubernetes/pkg/kubeapiserver/authenticator/config.go
vendor/k8s.io/kubernetes/pkg/kubeapiserver/authenticator/patch_authenticator.go

The TokenReview REST implementation expects that the authn chain returns audiences in the authn response. Authenticators that don't support audiences must return the default slice of audiences, e.g. the legacy service account authenticator does that. This PR adds that to our custom oauth authenticator.
Folliowing https://github.com/kubernetes/kubernetes/blob/master/pkg/serviceaccount/jwt.go#L283.
Compare https://github.com/kubernetes/kubernetes/pull/69582/files#r225535241.

UPSTREAM: <carry>: oauth-authn: add implicit audience support

---

test/extended/prometheus/prometheus.go

As we're going to do another iteration on the backend to receive remote write traffic instead of the legacy telemetry protocol, we're reenabling these tests until we're ready to give it another shot.
/cc @LiliC @s-urbaniak

test/extended/prometheus: Re-enable telemetry test

---

vendor/k8s.io/kubernetes/test/e2e/framework/pod/node_selection.go
vendor/k8s.io/kubernetes/test/e2e/storage/drivers/in_tree.go
vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/multivolume.go

The multi-node PV test creates a PV, starts a pod that writes data to a file on
the PV, then kills the pod and starts another with node anti-affinity to read
the data from the PV attached to a different node. This is problematic on
multi-AZ clusters: there may only be one node in a zone and for volumes that
can't be transferred among zones (AWS EBS, GCE PD, ...) the test would fail.

UPSTREAM: 85898: Fix multinode storage e2e tests for multizone clusters

---

test/extended/util/jenkins/ref.go

- Changes similar to https://github.com/openshift/origin/commit/4a31327f4aff3842812aae731adba9257e28ee54 as `--config` is deprecated and the replacement for the same is `--kubeconfig`
- https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_jenkins/1015/pull-ci-openshift-jenkins-master-e2e-aws-jenkins/756 is a failed build where we are getting the error. 
```
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_jenkins/1015/pull-ci-openshift-jenkins-master-e2e-aws-jenkins/756
```
- Updating this would allow for the Jenkins tests to be done by using the --kubeconfig flag with oc instead of --config

Bug 1796483: Use --kubeconfig flag for Jenkins Tests

---

vendor/k8s.io/kubernetes/test/e2e/scheduling/predicates.go

Backporting https://github.com/kubernetes/kubernetes/pull/87242

bug 1779303: UPSTREAM: 87242: SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run - set resource requests as well

---

pkg/monitor/api.go
pkg/monitor/monitor.go
pkg/monitor/sampler_test.go
pkg/monitor/types.go
test/e2e/upgrade/service/service.go
test/e2e/upgrade/upgrade.go
test/extended/util/disruption/controlplane/controlplane.go
test/extended/util/disruption/disruption.go

The upstream upgrade test doesn't correctly test for disruption of the backend during upgrade - it only tests that the service is not available for more than 2 minutes at a time.
This is obviously not a good test of whether a service maintains availability during upgrade. Take the core structure and use the monitor and polling behavior of the apiserver which is much more effective.

Bug 1796715: Add a service upgrade test that verifies availability

---

cmd/openshift-tests/e2e.go
test/extended/util/annotate/rules.go

**Summary**: 
In df6f5bd we added annotated tests to bindata. However, CSI tests are not part of the generated bindata because CSI drivers can be installed on-demand  (e.g., by an operator). 
This is particularly problematic when a partner wants to [certify their CSI driver](https://github.com/openshift/enhancements/pull/162). 
This PR changes the `openshift/csi` test suite filter by matching the test name directly, instead of adding an annotation and them matching the annotation.
**More info**:
I came up with a few possible solutions to solve this:
a) Change the upstream testing framework to allow for adding annotations to test names. I expect some pushback on this, since it seems too specific.
b) Dynamically add annotations to CSI tests **only**. This wouldn't revert df6f5bd, it would …

Bug 1796895: Don't use annotation in openshift/csi test suite

---

vendor/k8s.io/kubernetes/openshift-kube-apiserver/authentication/oauth/bootstrapauthenticator.go
vendor/k8s.io/kubernetes/pkg/kubeapiserver/authenticator/patch_authenticator.go

Bug 1794885: UPSTREAM: <carry>: bootstrap user - make tokens have implicit audiences

---

vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/config/common.go
vendor/k8s.io/kubernetes/cmd/kubelet/app/options/options.go
vendor/k8s.io/kubernetes/pkg/kubeapiserver/options/serving.go
vendor/k8s.io/kubernetes/pkg/kubelet/nodestatus/setters.go
vendor/k8s.io/kubernetes/pkg/kubelet/nodestatus/setters_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/interface.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/interface_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/serving.go

Backport of #24401 plus https://github.com/kubernetes/kubernetes/pull/84727 (which was already in master)
/assign @derekwaynecarr 
(who reviewed the two upstream commits)
This is a trivial backport other than that the original version of 84727 also modified a function in apimachinery which doesn't exist in origin release-4.3 (and which is only used by kubeadm) so that part of the patch just got dropped.

Bug 1791730: 4.3 ipv6 backports

---

vendor/k8s.io/kubernetes/test/e2e/framework/test_context.go
vendor/k8s.io/kubernetes/test/e2e/storage/vsphere/config.go

This backports https://github.com/kubernetes/kubernetes/pull/82027 to origin.
**What type of PR is this?**
/kind bug
Enables the ability to pass vsphere configuration files for e2e tests outside of an environment variable.
**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

Bug 1722672: UPSTREAM: 82027: Enabled reading config files for vsphere e2e tests

---

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_getters.go
vendor/k8s.io/kubernetes/pkg/kubelet/types/pod_update.go

Backport of https://github.com/openshift/origin/pull/23812
Fixes pod statuses
ref: https://github.com/kubernetes/kubernetes/pull/77661

[release-3.11] Bug 1801445: UPSTREAM: 24453: Sync the status of static Pods

---

pkg/project/apiserver/registry/project/proxy/proxy.go
pkg/project/auth/watch.go
pkg/project/auth/watch_test.go
pkg/project/util/util.go
test/integration/project_test.go

Backport of https://github.com/openshift/origin/pull/21167.
Filters events for projects on membership-change for a user based on a
field or label selector provided by a consumer of project events.

Bug 1800343: fix projects when watching with selector

---

pkg/oauthserver/oauth/handlers/default_auth_handler.go
pkg/oauthserver/oauth/handlers/default_auth_handler_test.go

Certain browsers might interpret the 500 error page as an HTML
page even though it's text/plain in some corner cases.
cc @enj

Bug 1694935: Sanitize user input when erroring on an unknown redirect handler [3.11]

---

test/extended/prometheus/prometheus.go

This test is failing with the new etcd operator static pod.  It is important and will be fixed, but we need to land the bulk of the work and refine this and its certs.
This will be reverted when https://bugzilla.redhat.com/show_bug.cgi?id=1802714 is fixed

bug 1802713: disable etcd metrics check to land operator

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/test/integration/subresources_test.go

This PR is a cherrypick from the upstream PR: https://github.com/kubernetes/kubernetes/pull/65357
We're specifically requesting this change be cherrypicked back to release-3.11 as it currently prevents a single set of CRD resources being compatible with OpenShift 3.11 whilst also being considered 'structural' in OpenShift 4.x (and newer Kubernetes versions).
Without this patch, users will see errors like:
```
Error from server (Invalid): error when creating "cert-manager-openshift-v0.13.0.yaml": CustomResourceDefinition.apiextensions.k8s.io "certificaterequests.cert-manager.io" is invalid: spec.validation.openAPIV3Schema: Invalid value: apiextensions.JSONSchemaProps{ID:""
...
ensions.JSONSchemaDefinitions(nil), ExternalDocs:(*apiextensions.ExternalDocumentation)(nil), …
```

Bug 1803163: UPSTREAM: 65357: Allow more fields at root of CRD schema if status is enabled

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/BUILD
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go

This PR backports a backwards compatible fix for the unbounded client label on apiserver_request_count and apiserver_request_total metrics.
Pick of https://github.com/kubernetes/kubernetes/pull/87673.

Bug 1803071: UPSTREAM: 87673: blank out value for unbounded client label

---

test/extended/prometheus/prometheus.go

In order to merge the `cluster-etcd-operator`, we need to disable `etcdInsufficientMembers` as we pivot from the old etcd-member static pod. This will be followed by the removal of the etcd-member spec from MCO and reenabling this alert.

Bug 1803190: test/extended/prometheus: temporarily disable etcdInsufficientMembers

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/timeout_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/wrap.go

Make request handler stack traces actually useful.
https://github.com/kubernetes/kubernetes/pull/71067/commits

Bug 1801755: UPSTREAM: 71067: apiserver: preserve stack trace in handler panic beyond timeout handler

---

images/tests/Dockerfile.rhel

This reverts commit ca35cd633a46d2156ef598e827ce230391684926, #22592.
As described in that commit message, the access was broadened to allow `ssh` from containers launched from the tests image.  But since openshift/release@7baa9f2e44 (openshift/release#6854) landed, we no longer need to SSH from those containers.  Restore the usual access restrictions to address [CVE-2019-19347][1].
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1793287

Bug 1793340: Revert "images/tests: Globally-writeable /etc/passwd"

---

test/extended/prometheus/prometheus.go

As promised we are returning the alert.
Reverts openshift/origin#24547

Bug 1804429: Revert: test/extended/prometheus: temporarily disable etcdInsufficientMembers"

---

test/extended/oauth/oauthcertfallback.go

Behavior has changed between 4.3 and 4.4 ([commit]( https://github.com/openshift/origin/pull/24178/commits/7e2a82946fb8f0f96c77af908e4a4d5e9a580e22)) which precludes skew testing.

Allow oauth token + cert fallback test to be skipped when running skew tests

---

cmd/openshift-tests/upgrade.go
test/e2e/upgrade/service/service.go
test/e2e/upgrade/upgrade.go
test/extended/operators/cluster.go
test/extended/util/disruption/controlplane/controlplane.go
test/extended/util/disruption/disruption.go

Upgrade test now accepts comma-delimited images or versions in
`openshift-tests run-upgrade --image A,B`. This simplifies bulk testing of
upgrades and will allow us to test existing upgrade paths.
This will allow us to test upgrades over multiple releases more easily
and allows us to avoid testing at ecah upgrade interval.
Will be used in 4.4 to test multiple input upgrades.

test: Allow sequential upgrades to be passed to upgrade test

---

test/e2e/upgrade/upgrade.go
test/extended/util/disruption/frontends/frontends.go

The console and the oauth server should remain reachable throughout
an upgrade. This also tests graceful rollout of the router.

test: Track frontend disruption during upgrades

---

test/extended/util/disruption/controlplane/controlplane.go

When running sequential updates, the control plane appears to take
more disruption than can be currently tolerated. Bump the limit for
now until we identify the root cause of the disruption.

test: Allow more control plane disruption for multi upgrade releases

---

test/extended/prometheus/prometheus.go

In 4.5 we will ship inhibition of `info` alerts so there is no point of checking if such alerts are firing.
Hold until `master` points to `release-4.5` and not `release-4.4`
/hold
/cc @LiliC @s-urbaniak @brancz

test/extended/prometheus: do not fail when info alert is firing

---

vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go

Limit-based eviction has the same outcome as a capacity-based eviction
but was not being reported to the kubelet_evictions metric, which makes
it harder to alert on. Report those evictions to the metric with
appropriate signals.

Bug 1806698: Limit-based eviction should report metrics

---

test/e2e/upgrade/service/service.go
test/extended/util/disruption/controlplane/controlplane.go
test/extended/util/disruption/disruption.go
test/extended/util/disruption/frontends/frontends.go

The error message should include the total duration and the % impacted.
Use a shared method to report that to simplify future changes.
Update the allowed disruption percent for frontends to 20%.

test: Standardize disruption reporting

---

test/extended/prometheus/prometheus.go

Alerts with `info` level severity shouldn't cause tests failure.
/cc @lilic

test/extended/prometheus: do not check for alerts with info level severity

---

pkg/network/node/node.go
pkg/network/node/ovscontroller.go
pkg/network/node/runtime.go
pkg/network/node/sdn_controller.go

We should kill every (non-hostNetwork) sandbox that we can't reattach
to OVS, but previously we were only killing "every (non-hostNetwork)
sandbox that we knew was previously attached to OVS that we couldn't
reattach to OVS".
This is a backport of https://github.com/openshift/sdn/pull/58 and https://github.com/openshift/sdn/pull/52 for 3.11.

Bug 1765220: Fix pod startup reattach/kill loop

---

test/e2e/upgrade/service/service.go

In some tests we are seeing the LB become ready, then start failing again. Try for five successes to reduce the chance that ELB is stable when we start the upgrade.
Example: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/19275 and the failures at the beginning of the upgrade (before anything starts)

test: Ensure the upgrade test LB remains available

---

vendor/k8s.io/kubernetes/cmd/cloud-controller-manager/app/options/options_test.go
vendor/k8s.io/kubernetes/cmd/controller-manager/app/options/debugging.go
vendor/k8s.io/kubernetes/cmd/controller-manager/app/options/generic.go
vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/options/options.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/component-base/config/v1alpha1/defaults.go

Clean pick with the exception that the variable in `vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/options/options.go` changed from `versionedCfg` to `cfgv1alpha1`. 

Bug 1807990: UPSTREAM: 88663: update kube-controller-manager and kube-scheduler to match kube-apiserver defaults

---

vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/aggregator.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/BUILD
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/dynamic_serving_content.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/BUILD
vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiservice_controller.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/cmd/server/start.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller_test.go

not clean, needs review.
based on https://github.com/openshift/kubernetes/commit/adfea731ab01ae9552b8aa309d6bf9f1c97656fc#diff-40fbc204fb430ee43a18f381a4e2182e

UPSTREAM: 88120: add dynamic certificate reloading for kube aggregator

---

vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go
vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager_test.go
vendor/k8s.io/kubernetes/pkg/util/pod/pod.go
vendor/k8s.io/kubernetes/pkg/util/pod/pod_test.go

The kubelet was sending no-op patches unncessarily about half the
time. This dramatically reduces the amount of API requests large
clusters send with some CPU reduction.

Bug 1809709: Don't send no-op pod status patches

---

test/extended/prometheus/prometheus.go

This is a backport of https://github.com/openshift/origin/pull/24276 and #24465 to allow merging https://github.com/openshift/cluster-monitoring-operator/pull/614
/cc @openshift/openshift-team-monitoring

Bug 1791211: test/extended/prometheus: exclude AlertmanagerReceiversNotConfigured from checking

---

test/extended/cli/explain.go

Signed-off-by: Antonio Murdaca <runcom@linux.com>

test/extended/cli: enable explain tests for MCO crds

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/rest/request.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/cache.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/cert_rotation.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/config.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/transport.go
vendor/k8s.io/kubernetes/test/integration/client/cert_rotation_test.go

We need KCM and KS to be able to reload certificates so it can recover when cert regeneration controller fixes the cert in the API and certsyncer downloads them.
Backport of https://github.com/kubernetes/kubernetes/pull/79083 (needed picking https://github.com/kubernetes/kubernetes/pull/88267 first)
/cc @deads2k @soltysh @mfojtik

Bug 1811061: UPSTREAM: 79083: Add ability to reload client certificates from disk

---

images/router/haproxy/conf/haproxy-config.template

Add same variables as in OCP 4.x routers to support Min and Max TLS versions:
Related 4.x activity:
https://github.com/openshift/router/pull/30
https://bugzilla.redhat.com/show_bug.cgi?id=1746467
RFE on 3.11:
https://issues.redhat.com/browse/RFE-167
I've set the default for 3.11 to TLSv1.0 since that was the previous setting without these variables.

Bug 1778856: Add MIN/MAX variables to SSL/TLS versions

---

pkg/test/ginkgo/junit.go

Don't count success as a failure. Looks like copy-paste "typo".

Bug 1811020: Fix count of failures in JUnit output

---

pkg/test/ginkgo/junit.go

Don't count success as a failure. Looks like copy-paste "typo".

[4.4]: Bug 1811088: Fix count of failures in JUnit output

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/rest/request.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/cache.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/cert_rotation.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/config.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/transport.go
vendor/k8s.io/kubernetes/test/integration/client/cert_rotation_test.go

We need KCM and KS to be able to reload certificates so it can recover when cert regeneration controller fixes the cert in the API and certsyncer downloads them.
Backport of https://github.com/openshift/origin/pull/24646
/cc @deads2k @soltysh @mfojtik

[release-4.4] Bug 1811062: UPSTREAM: 79083: Add ability to reload client certificates from disk

---

vendor/k8s.io/kubernetes/test/e2e/storage/utils/utils.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1810459
/sig storage

Bug 1810459: UPSTREAM: 86886: Fix err variable shadowing issue in storage/utils

---

vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/framework_test.go
vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go
vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1796660
/sig storage

[4.4] Bug 1796660: UPSTREAM: 88146: remove duplicate pv delete calls

---

test/extended/operators/tolerations.go

The test `[Feature:Platform][Smoke] Managed cluster should ensure control plane operators do not make themselves unevictable` requires all `Exists` tolerations in non-whitelisted control plane pods to have a `tolerationSeconds` field. But it's mistakenly checking `NoSchedule` tolerations too, even though `NoSchedule` doesn't make you unevictable, and `tolerationSeconds` doesn't have any effect on `NoSchedule` tolerations anyway.
(This is currently breaking that test in e2e-aws-ovn-kubernetes:
1 pods found with invalid tolerations:
openshift-ovn-kubernetes/ovnkube-master-7b846b56b-76vs8 tolerates node.kubernetes.io/not-ready with no tolerationSeconds
but ovnkube-master has:
tolerations:
- key: "node-role.kubernetes.io/master"
operator: "Exists"
effect: "NoSchedule"
- key: …

Only check for tolerationSeconds on NoExecute tolerations

---

vendor/k8s.io/kubernetes/pkg/kubelet/stats/cadvisor_stats_provider_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/stats/helper.go
vendor/k8s.io/kubernetes/pkg/kubelet/stats/stats_provider_test.go

HPA needs metrics for exited init containers before it will
take action. By setting memory and CPU usage to zero for any
containers that cAdvisor didn't provide statistics for, we
are assured that HPA will be able to correctly calculate
pod resource usage.

UPSTREAM: 88734: Work-around for missing metrics on CRI-O exited containers

---

pkg/network/node/runtime.go

This PR addresses the use of an incorrect key as the sandbox ID. Previous fix #24585 introduced a bug where we were using the `getPodKey` API to index the sandbox. This change fixes that to use the `Id` field of the sandbox instead.

Bug 1765220: Use sandbox id instead of getting it using pod key

---

test/e2e/upgrade/service/service.go

This change adds a `framework.Poll` delay between successive retries for reachability check for the test service. This will make sure the SLB is stable before we start disruption.

test: Add a delay between successive retries for service reachability check and wait for n consecutive successes.

---

images/tests/Dockerfile.rhel

This reverts commit 33a6115867f59fc479dba6ca009de3492632c114.
This is required for our CI infrastructure to use SSH correctly
until we have completely moved CI to 4.x infrastructure (where
/etc/passwd becomes dynamic). This broke the disruptive test
suite and etcd recovery, and blocks a number of other tests being
added.
The issue is not a CVE.

Bug 1813428: Restore globally-writeable /etc/passwd in tests image

---

test/extended/operators/olm.go

@jianzhangbjz could you please help review the PR? thanks
```console
I0312 14:29:11.289935   20276 test_context.go:419] Tolerating taints "node-role.kubernetes.io/master" when considering if nodes are ready
I0312 14:29:13.964047   20278 test_context.go:419] Tolerating taints "node-role.kubernetes.io/master" when considering if nodes are ready
started: (0/1/11) "[Feature:Platform] OLM should [Top Level] [Feature:Platform] OLM should be installed with catalogsources at version v1alpha1 [Suite:openshift/conformance/parallel]"
started: (0/2/11) "[Feature:Platform] OLM should [Top Level] [Feature:Platform] OLM should have imagePullPolicy:IfNotPresent on thier deployments [Suite:openshift/conformance/parallel]"
started: (0/3/11) "[Feature:Platform] OLM should [Top Level] [Feature:Platform] OLM …
```

fix unstable case to check resource status

---

vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go

As @liggitt outlined in #88779 (comment) , there are two options in preventing multiple parallel Run goroutines.
This PR adopts option #1.

UPSTREAM: 89055: Remove wait.Until for running Kubelet Bootstrap

---

test/extended/router/headers.go
test/extended/router/metrics.go

Fix nil reference crashes when accessing an infrastructure status field that
hasn't been migrated.

Bug 1814357: Fix nil reference when accessing un-migrated platform status

---

cmd/openshift-tests/openshift-tests.go

`openshift-tests` runs several tests in parallel (in a parallel suite). It is currently not possible to set the parallelism.
During CSI certification (included in openshift-tests binary) some users complain that the parallelism is too high for their small test clusters / storage backends / CI.

Bug 1811726: Make parallelism configurable

---

test/extended/router/headers.go

Another nil reference fix for a crash when accessing an infrastructure status field that
hasn't been migrated.

Bug 1814357: Fix another nil reference when accessing un-migrated platform status

---

test/extended/operators/olm.go

If the operatrgroup is not ready by the time the CSV is created, the CSV
may temporarily make the CSV go unhealthy. This emits an alert, which
can make the prometheus test ensuring no alerts fail.

Bug 1790825: fix test flake in olm tests

---

test/extended/operators/olm.go

When the namespace is deleted, the operatorgroup can be removed
before the csv, which can cause the csv to flip to failed.
there is an alert that fires when the csv flips to failed, which
can cause the monitoring test ensuring no alerts fired to fail

Bug 1790825: fix test flake in operators test

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher_whitebox_test.go

Currently, /readyz starts reporting failure after ShutdownDelayDuration
elapses. We expect /readyz to start returning failure as soon as
shutdown is initiated. This gives the load balancer a window defined by
ShutdownDelayDuration to detect that /readyz is red and stop sending
traffic to this server.

[release-4.3] Bug 1811200: /readyz should start returning failure on shutdown initiation

---

cmd/openshift-tests/openshift-tests.go

Common scenario is running openshift-tests multiple times in a row
for different suites.

test: Allow the e2e log to be sequentially written to

---

vendor/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/policy_single_numa_node.go
vendor/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/policy_single_numa_node_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/topology_manager_test.go

Picks an upstream patch (another one) to fix an issue in Topology Manager
with single-numa-node policy.
ref:https://github.com/kubernetes/kubernetes/pull/83777
Signed-off-by: vpickard <vpickard@redhat.com>

Bug 1813411: UPSTREAM: 85912: Fixed bug in TopologyManager with SingleNUMANode Policy

---

test/extended/builds/failure_status.go

this new test should only pass once https://github.com/openshift/openshift-controller-manager/pull/77 merges

Bug 1809862: log snippet test; failed git clone within init container

---

vendor/github.com/onsi/ginkgo/internal/codelocation/code_location.go

Cuts e2e time from 10k core seconds to 5k core seconds and
openshift-tests startup from 1.2s to 0.3s.
This bypasses normal glide bumps since openshift/api has not yet
been merged.

vendor: Bump ginkgo to pick up performance fix

---

test/extended/util/disruption/disruption.go

Do our best to record at least a single failure.

test: Catch panics in the main disruption body

---

test/extended/machines/scale.go

Deletion of the underlying infrastructure in Azure is taking over 7 min.
https://bugzilla.redhat.com/show_bug.cgi?id=1812240

BUG 1812240: Bump timeout for cluster to get back to original size

---

test/extended/etcd/etcd_test_runner.go

Otherwise it's hard to debug.
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/24739/pull-ci-openshift-origin-master-e2e-aws-serial/13256

test: When the scanner fails print the error

---

cmd/openshift-tests/upgrade.go
test/e2e/upgrade/service/service.go
test/e2e/upgrade/upgrade.go
test/extended/operators/cluster.go
test/extended/util/disruption/controlplane/controlplane.go
test/extended/util/disruption/disruption.go
test/extended/util/disruption/frontends/frontends.go

Backport a number of changes from 4.4 that ensured we reported the correct
behavior while upgrading.

Bug 1806408: Ensure upgrade tests verify application disruption

---

vendor/k8s.io/kubernetes/pkg/apis/core/v1/conversion.go
vendor/k8s.io/kubernetes/pkg/apis/core/v1/conversion_test.go

`pod.status.podIPs` was introduced in kube 1.16 with the requirement that if `podIP` and `podIPs` are both set, they must match. This means that when a kube 1.14 / OCP 4.2 kubelet tries to change the `podIP` of a pod on a kube 1.16 / OCP 4.3 apiserver, it will fail because it didn't also try to change `podIPs`:
```
Mar 23 18:04:42 ip-10-0-163-3 hyperkube[1938]: W0323 18:04:42.769863    1938
status_manager.go:519] Failed to update status for pod "kube-apiserver-operator-
5d7c58bbb4-27mww_openshift-kube-apiserver-operator(93729130-6d20-11ea-
a89d-0a193a986132)": failed to patch status "..." for pod
"openshift-kube-apiserver-operator"/"kube-apiserver-operator-5d7c58bbb4-27mww":
conversion Error: v1.PodIP(10.129.0.65) != v1.PodIPs[0](10.129.0.41)
```
eg, specifically, if during a 4.2 to 4.3 …

Bug 1816302: UPSTREAM: 88505: Honor status.podIP over status.podIPs, node.spec.podCIDR over node.spec.podCIDRs

---

test/extended/router/headers.go

Ignore the address in the `X-Forwarded-For:` header when the cluster is using the `OVNKubernetes` network plugin.
* `test/extended/router/headers.go`: Get the `networks.config/cluster` object. If it indicates that the `OVNKubernetes` plugin is used, ignore the client IP address in the echo server's response.
----
This is temporary measure to get the test passing until we figure out a fix.
@ironcladlou, @abhat

Bug 1802311: e2e: Disable router header test on OVN

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/basicresources.sh
test/extended/testdata/cmd/test/cmd/image-lookup.sh
test/extended/testdata/cmd/test/cmd/run.sh
test/extended/testdata/cmd/test/cmd/status.sh

1.18 rebase of oc no longer supports generators for various objects like dc, jobs, rc.
Equivalent oc create commands must be used instead.

Replace oc run for dc/jobs and others with oc create equivalents

---

vendor/k8s.io/kubernetes/pkg/apis/core/v1/conversion.go
vendor/k8s.io/kubernetes/pkg/apis/core/v1/conversion_test.go

Backport of #24750, but via cherry-picking the upstream backport rather than the origin master PR

Bug 1817039: [4.4] UPSTREAM: 88506: Honor status.podIP over status.podIPs, node.spec.podCIDR over node.spec.podCIDRs

---

vendor/k8s.io/kubernetes/pkg/apis/core/v1/conversion.go
vendor/k8s.io/kubernetes/pkg/apis/core/v1/conversion_test.go

Backport of #24750, but via cherry-picking the upstream backport rather than the origin master PR

Bug 1817040: [4.3] UPSTREAM: 88507: Honor status.podIP over status.podIPs, node.spec.podCIDR over node.spec.podCIDRs

---

pkg/test/ginkgo/junit.go

So we know what version of openshift-tests was running.
This is useful for us when receiving CSI driver test reports to check CSI driver vendors used the right version.

Add test version into JUnit report

---

cmd/openshift-tests/openshift-tests.go

Each test output should start with version of the test binary. This is useful when using openshift-tests as CSI driver certification suite - the test results should show what version of tests was run.
On related note, why standard klog arguments are not exposed?

Show test binary version

---

test/extended/util/annotate/rules.go

Skipping those to merge oc rebase before origin gets rebased to 1.18

Exclude sig-cli kubectl tests removed in 1.18

---

test/extended/builds/new_app.go
test/extended/builds/service.go
test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/env.sh
test/extended/testdata/cmd/test/cmd/printer.sh
test/extended/testdata/cmd/test/cmd/timeout.sh
test/extended/testdata/cmd/test/cmd/triggers.sh
test/extended/util/deploymentconfigs.go
test/extended/util/framework.go

https://github.com/openshift/oc/pull/355 is switching `oc new-app` to produce deployments instead of deployment configs by default. There will be a new flag `--as-deployment-config` to provide backwards compatiblity. 
This change requires our tests to be more resilient expecting the outcome. This PR either changes tests to explicitly create DC where possible or expects either deployment or DC. 

Make new-app related tests more resilient to changes to deployment by default

---

test/extended/prometheus/prometheus.go

This is temporary solution to get https://github.com/openshift/cluster-monitoring-operator/pull/722 merged. After that it should be removed.

test/extended/prometheus: do not check if prom-op is up

---

hack/verify-upstream-commits.sh

The upstream commit message pattern is the following:
```
^UPSTREAM: (revert: )?(([\w\.-]+\/[\w-\.-]+)?: )?(\d+:|<carry>:|<drop>:)
```
Yet, we merged PRs with commit without the first column. Reason was that the commit range was wrong with `master..HEAD` as `master` pointed to the merge commit of the PR into origin/master.

tools/commitchecker: fix base commit in CI

---

test/extended/util/client.go

The node-log tests were generating lines in excess of 10 million columns when an error occurred (usually due to the streaming connection being terminated). Snip the log output before we
print it out or send it to the error (which is printed out by ginkgo when the test fails). This might make some failures harder to debug, but a caller can still use the returned output.
Found in https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-ocp-installer-e2e-openstack-4.4/1347

test: Prevent extremely long e2e log output lines on some tests

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/run.sh

```
$ oc run test1 --image=busybox --attach --dry-run
W0330 11:00:22.611725   19620 helpers.go:535] --dry-run is deprecated and can be replaced with --dry-run=client.
error: --dry-run=[server|client] can't be used with attached containers options (--attach, --stdin, or --tty)
See 'oc run -h' for help and examples
```
```
$ oc run test1 --image=busybox --stdin --dry-run
W0330 11:00:40.067325   19646 helpers.go:535] --dry-run is deprecated and can be replaced with --dry-run=client.
error: --dry-run=[server|client] can't be used with attached containers options (--attach, --stdin, or --tty)
See 'oc run -h' for help and examples
```

[test/extended] Remove oc run --attach/--stdin which can't be dry-run flagged

---

test/extended/router/headers.go
test/extended/router/metrics.go

Fix nil reference crashes when accessing an infrastructure status field that
hasn't been migrated.
Combined backport of https://github.com/openshift/origin/pull/24708 and https://github.com/openshift/origin/pull/24718.

Bug 1815050: Fix nil reference when accessing un-migrated platform status

---

vendor/k8s.io/kubernetes/pkg/volume/csi/csi_plugin.go
vendor/k8s.io/kubernetes/pkg/volume/csi/nodeinfomanager/nodeinfomanager.go
vendor/k8s.io/kubernetes/pkg/volume/testing/testing.go

This replaces https://github.com/marun/origin/pull/4 with a real upstream fix.
`UPSTREAM: <carry>: Don't panic on CSI migration timeout`
This is for OCP 4.5 pre-rebase (kube 1.17). OCP 1.18 version https://github.com/kubernetes/kubernetes/pull/89589 applies cleanly on 4.5.

Bug 1817382: UPSTREAM: 89589: Wait for APIServer 'ok' forever during CSINode initialization during Kubelet init

---

vendor/k8s.io/kubernetes/test/e2e/network/network_policy.go

Sometimes the pod has already been cleaned up by the time the test
tried to grab the logs.
```
Mar 27 16:19:38.066: INFO: Waiting for client-a-jt4tf to complete.
Mar 27 16:19:38.066: INFO: Waiting up to 5m0s for pod "client-a-jt4tf" in namespace "e2e-network-policy-c-9007" to be "success or failure"
Mar 27 16:19:38.072: INFO: Pod "client-a-jt4tf": Phase="Pending", Reason="", readiness=false. Elapsed: 6.270302ms
Mar 27 16:19:40.078: INFO: Pod "client-a-jt4tf": Phase="Pending", Reason="", readiness=false. Elapsed: 2.01233019s
Mar 27 16:19:42.086: INFO: Pod "client-a-jt4tf": Phase="Succeeded", Reason="", readiness=false. Elapsed: 4.020186873s
STEP: Saw pod success
Mar 27 16:19:42.086: INFO: Pod "client-a-jt4tf" satisfied condition "success or failure"
Mar 27 16:19:42.093: FAIL: Error getting …
```

UPSTREAM: 89592: e2e/network: get previous pod errors on NetworkPolicy test failure

---

test/extended/prometheus/prometheus.go

Revert https://github.com/openshift/origin/pull/24780 as https://github.com/openshift/cluster-monitoring-operator/pull/722 is already merged.
Possibly improve checking for firing alerts by inverting query logic. If it works, then e2e tests should fail as there is `TargetDown` alert firing due to https://bugzilla.redhat.com/show_bug.cgi?id=1818772
/cc @lilic

Check if prometheus-operator is reporting metrics

---

cmd/openshift-tests/csi.go
cmd/openshift-tests/e2e.go
cmd/openshift-tests/provider.go
test/extended/csi/install.go
test/extended/util/test.go

As a special exemption, allow CSI tests to access oc and fixtures
before a test starts. In the future this should be refactored so
that a different clearly auditable set of methods is invoked.

test: Allow CSI tests to access fixtures pre run

---

test/extended/builds/s2i_root.go

Update to our old s2i root build via privileged SCC test 
Stemming from ask from @bparees in https://coreos.slack.com/archives/CB48XQ4KZ/p1585580675154600
Using recommendation from @smarterclayton and docs at https://docs.openshift.com/container-platform/4.1/authentication/managing-security-context-constraints.html#role-based-access-to-ssc_configuring-internal-oauth as a reference
@bparees - the slack thread mentions 4.3
- so we will want to backport this, correct?
- if so, is there a tracking BZ for this already?

Bug 1819276: use rbac vs direct scc edit for s2i root bld test

---

test/extended/prometheus/prometheus.go

Metrics should be exposed over secure channel

---

pkg/monitor/api.go
pkg/monitor/event.go
pkg/monitor/pod.go

Also tone down the error state when a pod on a nade moves back to
pending (such as when it is restarted on reboot).

monitor: Report node when events include it

---

test/extended/operators/olm.go

Cherry pick of #24436 and #24723

Bug 1805588: Fix flaky olm test 

---

vendor/k8s.io/kubernetes/pkg/kubelet/pluginmanager/cache/actual_state_of_world.go
vendor/k8s.io/kubernetes/pkg/kubelet/pluginmanager/operationexecutor/operation_executor.go
vendor/k8s.io/kubernetes/pkg/kubelet/pluginmanager/operationexecutor/operation_executor_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go
vendor/k8s.io/kubernetes/pkg/kubelet/pluginmanager/reconciler/reconciler.go
vendor/k8s.io/kubernetes/pkg/kubelet/pluginmanager/reconciler/reconciler_test.go

This PR enhances bookkeeping for csiplugin registration so that the csiplugin can be un-registered without socket path being present.

UPSTREAM: 88006: Unregister csiplugin even if socket path is gone

---

pkg/monitor/event.go
pkg/monitor/pod.go

This data is just too valuable.

Capture e2e events in monitor

---

test/extended/etcd/etcd_storage_path.go

This is required to make the serial tests pass to land the priority and fairness enablement in https://github.com/openshift/cluster-kube-apiserver-operator/pull/818

make the flowcontrol storage tests variable depending upon discovery

---

pkg/monitor/api.go
test/e2e/upgrade/upgrade.go
test/extended/util/disruption/controlplane/controlplane.go

The OpenShift APIs are technically very different from the Kube ones. To make triaging easier, this PR splits them into two monitors.

Bug 1822514: tests: split API availability monitor into kube and OpenShift

---

test/extended/prometheus/prometheus.go

Fix will be tracked in https://issues.redhat.com/browse/SDN-912
@knobunc @fepan

test/extended: exclude ovnkube master/node metrics endpoints from secure test

---

test/extended/marketplace/marketplace_diffname.go
test/extended/marketplace/marketplace_labels.go

The CatalogSourceConfig is being deprecated from Openshift 4.5.
This PR removes the CSC related tests.
Ref: operator-framework/operator-marketplace#302

Bug 1826071: [marketplace] Remove CSC related tests

---

test/integration/sdn_test.go

In the new CI cluster, test-integration gets run in a pod in a cluster
using the default OCP IP ranges, which broke TestOadmPodNetwork
because that test brings up enough of openshift-sdn that it complains
when it sees that eth0 has an IP inside the range it was planning to
use.
The test doesn't actually allocate any IPs, so it doesn't matter what
ranges the master is configured to use, so just set it to something
invalid so it's guaranteed to not overlap no matter what.

integration: fix TestOadmPodNetwork for CI changes

---

vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go

**What type of PR is this?**
/kind bug
When making modifications to an immutable field we don't print the field that's attempted to be edited, only the included message. This PR makes the messages more user-friendly. 
**Which issue(s) this PR fixes**:
Bug 1740604

Bug 1740604: UPSTREAM 89300: Expand the PVC validation messages

---

vendor/k8s.io/kubernetes/test/e2e/framework/util.go
vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go

Bug 1810470: UPSTREAM: <drop> Increase timeout in volume expansion test

---

vendor/k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go

The resource quota priority class preemption tests run in parallel,
and were observed to cause a preemption of another test. The tests
have no need to schedule to a node in order to verify resource quota.
```
Apr 19 16:59:06.749: INFO: At 2020-04-19 16:58:52 +0000 UTC - event for pod-init-b6fbd440-dbc2-454a-b31a-ce44266298d1: {default-scheduler } Scheduled: Successfully assigned e2e-init-container-7691/pod-init-b6fbd440-dbc2-454a-b31a-ce44266298d1 to ip-10-0-148-234.us-west-2.compute.internal
Apr 19 16:59:06.750: INFO: At 2020-04-19 16:58:54 +0000 UTC - event for pod-init-b6fbd440-dbc2-454a-b31a-ce44266298d1: {default-scheduler } Preempted: Preempted by e2e-resourcequota-priorityclass-8850/testpod-pclass9 on node ip-10-0-148-234.us-west-2.compute.internal
```

Bug 1826502: PriorityClass tests can cause preemptions

---

vendor/k8s.io/kubernetes/test/e2e/storage/drivers/in_tree.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1823494

Bug 1823494: Storage tests should more carefully select zones for testing

---

test/extended/prometheus/prometheus.go

In 4.4 the automatic image pruner is initially disabled. Cluster admins are responsible for enabling it day 2. An alert is fired if the image pruner is disabled.
Note that in 4.5 the automatic image pruner is enabled on new clusters.

[release-4.4] Bug 1826033: Ignore ImagePruningDisabled alert

---

test/extended/router/grpc-interop.go
test/extended/router/h2spec.go

Disable router tests that test or rely on HTTP/2 on the frontend.
We are disabling HTTP/2 on the frontend to prevent issues with connection coalescing that break the OAuth flow.
* `test/extended/router/grpc-interop.go`:
* `test/extended/router/h2spec.go`: Skip the tests.
----
@ironcladlou, @danehans

Bug 1825354: test/extended/router: Disable HTTP/2 tests

---

test/extended/prometheus/prometheus.go

Enables secure metrics tests for dns that were disabled due to bz 1809197.
/hold until https://github.com/openshift/cluster-dns-operator/pull/163 merges.

Bug 1827751: Enables secure metrics tests for dns

---

vendor/k8s.io/kubernetes/test/e2e/apimachinery/crd_publish_openapi.go

a temporal fix that will be replaced by https://github.com/kubernetes/kubernetes/pull/90452 in the future.

Bug 1761043: provides a temporal fix to improve CRD publishing e2e tests in an HA setup

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/timeout.sh

Expected "Timeout exceeded while reading body" error message is printed with -v=5.
Without the error message, both --watch oc get commands unexpectedly fail.

Bug 1826230: oc get --request-timeout: Timeout exceeded while reading body printed with -v=5

---

test/extended/util/client.go

The last refactor to the CLI helper resulted in namespaces being
double created for origin tests, which is unnecessary.

test: Do not create namespaces twice

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/deployments.sh
test/extended/testdata/cmd/test/cmd/policy-storage-admin.sh
test/extended/testdata/cmd/test/cmd/policy.sh
test/extended/testdata/cmd/test/cmd/projects.sh
test/extended/testdata/cmd/test/cmd/secrets.sh
test/extended/testdata/cmd/test/cmd/status.sh
test/extended/testdata/cmd/test/cmd/templates.sh
test/extended/testdata/cmd/test/cmd/volumes.sh

To land https://github.com/openshift/oc/pull/310 we need to update the tests to drop the deprecated flags or change to use the currently available. 

Bug 1828280: Remove deprecated flags and commands from test-cmd

---

pkg/network/node/networkpolicy.go
pkg/network/node/networkpolicy_test.go

currently if there are two network policies in a namespace that match an
incoming pod refreshNetworkPolicies() will only call updateNetworkPolicy()
on one of them. UpdateNetworkPolicy calls parseNetworkPolicy which updates
the network policy object.
removing the break in refreshNetworkPolicies() will cause
updateNetworkPolicy() to be run against all changed networkpolicies which
will ensure that all changed policies get successfully updated.
also updated the unit tests to expose this issue, so that this issue won't
be exposed again.
4.5BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816394
4.4BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816392
4.3BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816390
4.2BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816389
4.1BZ: …

[release-4.1] Bug 1816388: handle pod updates correctly in networkpolicy

---

pkg/network/common/dns.go
pkg/network/common/dns_test.go
pkg/network/common/egress_dns.go
pkg/network/node/egress_network_policy.go
pkg/network/node/node.go
pkg/network/node/ovscontroller.go
pkg/network/proxy/proxy.go

Refactor the datastructures to query DNS names more efficiently as
the same DNS name may appear across multiple policies.

[release-3.11] Bug 1772594: Make DNS querying more efficient by querying once per dns name

---

pkg/network/node/networkpolicy.go
pkg/network/node/networkpolicy_test.go

currently if there are two network policies in a namespace that match an
incoming pod refreshNetworkPolicies() will only call updateNetworkPolicy()
on one of them. UpdateNetworkPolicy calls parseNetworkPolicy which updates
the network policy object.
removing the break in refreshNetworkPolicies() will cause
updateNetworkPolicy() to be run against all changed networkpolicies which
will ensure that all changed policies get successfully updated.
also updated the unit tests to expose this issue, so that this issue won't
be exposed again.
4.5BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816394
4.4BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816392
4.3BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816390
4.2BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816389
4.1BZ: …

[release-3.11] Bug 1745898: handle pod updates correctly in networkpolicy

---

vendor/k8s.io/kubernetes/pkg/kubelet/cm/node_container_manager.go

Backports kubepods.slice fix into 3.11 for OOM related issues revolving around kubelet reservations.
Origin PR : https://github.com/openshift/origin/pull/24568
Originating 4.x BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1802687

[release-3.11] Bug 1814804: UPSTREAM: 88251: Partially fix incorrect configuration of kubepods.slice unit by kubelet

---

test/extended/project/project.go

The waitForOnlyDelete() waits only 30s for the project being deleted.
The e2e logs shows that in ~18% of e2e tests, the deletion takes longer
than 30s, presumably because of GC cleaning up the namespace.
In those cases, the cleanup takes 35-40s.

Bug 1829225: Increase waiting time for namespace deletion in project test

---

vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
vendor/k8s.io/kubernetes/cmd/kubelet/app/auth.go
vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go
vendor/k8s.io/kubernetes/pkg/kubeapiserver/options/authentication.go
vendor/k8s.io/kubernetes/test/integration/apiserver/certreload/certreload_test.go

kube-apiserver fails to live reload changed client CA and front proxy CA and refuses clients signed by the new CA with 401 `Unable to authenticate the request due to an error: x509: certificate signed by unknown authority`
backport of https://github.com/kubernetes/kubernetes/pull/90360
/cc @deads2k @sttts @soltysh

Bug 1831042: Fix client-ca dynamic reload in apiserver

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go
vendor/k8s.io/kubernetes/test/e2e/framework/providers/azure/azure.go

Backport of https://github.com/kubernetes/kubernetes/pull/90535
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1828174

Bug 1828174: Fix azure tests in unzoned environment

---

test/extended/oauth/requestheaders.go

This makes debugging the failed test easier on Azure (see the pod status and timestamp drift)

Bug 1831906: Add more debug messages to RequestHeaders IdP test

---

test/extended/operators/operators.go

Drop namespace from output strings, because [`ClusterOperator` is cluster-scoped][1].
Shift the `available` variable down to the block of code that actually consumes it, and convert it from a map to a counter, because we don't care about displaying available operators.
Rename `unavailable` to the more generic `working` (to match the existing "still doing work" messages).  Working operator may be available but progressing, etc., so `unavailable` was too specific.
Remove the `break` from the wait-loop's `ClusterOperator` iteration.  The previous logic would only list the first unavailable operator.  With this commit we now list each unavailable operator while we wait.
Reformat the tab-writer block to print each operator and its worst condition.  The previous format had columns for …

Bug 1829405: test/extended/operators/operators: Rework "start all core operators"

---

vendor/k8s.io/kubernetes/test/e2e/common/volumes.go

https://bugzilla.redhat.com/show_bug.cgi?id=1829331
https://github.com/kubernetes/kubernetes/pull/90715

Bug 1829331: UPSTREAM: 90715: Ignore NotFound error when cleaning up Gluster tests

---

test/extended/util/framework.go
test/extended/util/ldap.go

This PR aims to cut down the CI flakes for the LDAP test.
There are a good number of failures because of connection failures due to race conditions between the LDAP client and the LDAP server. Using `RestartPolicyOnFailure` instead of `RestartPolicyNever` will make sure the pod command completes by restarting the pod in case of transient failures.
The same ldap container image is being used for both server and client. The client implementation is not under our control for the pod to be resilient to transient failures. To cover these failures restarting pod on failure seems to be a good option.

Bug 1805821: change restart policy of command pod to RestartPolicyOnFailure

---

vendor/k8s.io/kubernetes/test/e2e/framework/skipper/skipper.go

This test has recently (and somewhat suspiciously) disappeared from the testgrid top flakes. Upon further investigation, it appears that it is always skipping due to failing [this node count check](https://github.com/kubernetes/kubernetes/blob/9b44fa4a07b14b3dbc644f80e087d516677632f0/test/e2e/scheduling/priorities.go#L161) (even when run locally, which is very odd).
~~This PR removes the node check, but it would be better if we could investigate why this check is constantly skipping (did we change how we set the node count?) and if other tests that use this check are also skipping.~~
**Update:** It turns out that the cause of this is because the e2e skipper package was broken and referred to `TestContext `as an uninitialized variable local to its own package rather than …

Bug 1749246: UPSTREAM: Fix TestContext references in e2e skippers

---

vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/noderesources/resource_allocation.go
vendor/k8s.io/kubernetes/pkg/scheduler/nodeinfo/node_info.go
vendor/k8s.io/kubernetes/pkg/scheduler/nodeinfo/node_info_test.go
vendor/k8s.io/kubernetes/pkg/scheduler/util/BUILD
vendor/k8s.io/kubernetes/pkg/scheduler/util/non_zero.go

Take initcontainers into account when calculating resource requests
ref: https://github.com/kubernetes/kubernetes/pull/89222
ref: https://github.com/kubernetes/kubernetes/pull/90378

Bug 1835785: UPSTREAM: 90378: bugfix: initcontainer wasn't considered when calculate resource request

---

vendor/k8s.io/kubernetes/pkg/kubelet/prober/prober.go

Fixes the log message for kubelet exec-probe log messages
ref: https://github.com/kubernetes/kubernetes/pull/91066
/assign @sjenning

Bug 1835042: UPSTREAM: 91066: tweak exec-probe log statement to be more concise

---

test/extended/apiserver/root_403.go
test/extended/authentication/front_proxy.go
test/extended/bootstrap_user/bootstrap_user_login.go
test/extended/cli/mustgather.go
test/extended/csrapprover/csrapprover.go
test/extended/etcd/etcd_test_runner.go
test/extended/images/imagestream.go
test/extended/machines/machines.go
test/extended/machines/scale.go
test/extended/oauth/oauthcertfallback.go
test/extended/oauth/requestheaders.go
test/extended/oauth/well_known.go
test/extended/prometheus/prometheus.go
test/extended/prometheus/prometheus_builds.go
test/extended/util/client.go
test/extended/util/framework.go
test/extended/util/ibmcloud/provider.go
test/extended/util/oauthserver/oauthserver.go
test/extended/util/test.go

Bug 1829959: [release-4.3] Introduce IBMCloud provider, skip/fix tests

---

test/extended/dr/common.go

Fix out of bounds access which causes intermittent test panics.

Bug 1835931: Fix panic in test code

---

vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
vendor/k8s.io/kubernetes/cmd/kubelet/app/auth.go
vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go
vendor/k8s.io/kubernetes/pkg/kubeapiserver/options/authentication.go
vendor/k8s.io/kubernetes/test/integration/apiserver/certreload/certreload_test.go

kube-apiserver fails to live reload changed client CA and front proxy CA and refuses clients signed by the new CA with 401 `Unable to authenticate the request due to an error: x509: certificate signed by unknown authority`
backport of https://github.com/kubernetes/kubernetes/pull/90360
master PR https://github.com/openshift/origin/pull/24942
/cc @deads2k @sttts @soltysh

Bug 1831045: Fix client-ca dynamic reload in apiserver

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/vsphere/credentialmanager.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/vsphere/credentialmanager_test.go

PR: https://github.com/kubernetes/kubernetes/pull/90796
Scrapped issue with details: https://github.com/kubernetes/kubernetes/issues/90795

Bug 1821945: Ensure the server FQIN is stored and searched in lowercase (vsphere)

---

test/extended/operators/operators.go

We've been failing this test on `Progressing=True` since 6300a87622 (#22058).  But the installer [only cares about `ClusterVersion` `Available=True`][1], which means some operators who have leveled (as far as the cluster-version operator is concerned) may still have `Progressing=True` when the installer declares success.  We aren't too concerned about that as long as operators are available and not degraded, so stop worrying about it in this test.  This avoids failures [like][2]:
```
[sig-arch][Early] Managed cluster should start all core operators [Suite:openshift/conformance/parallel]
fail [github.com/openshift/origin/test/extended/operators/operators.go:159]: May  8 13:27:58.992: Some cluster operators never became ready: kube-apiserver (Progressing=True NodeInstaller: …
```

Bug 1833387: test/extended/operators/operators: Don't worry about Progressing ClusterOperator

---

vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_gc.go
vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/legacy.go
vendor/k8s.io/kubernetes/pkg/kubelet/remote/remote_runtime.go

As the discussion over #52172 showed, there is race condition between the container log rotation and the kubelet GC which may result in the loss of symlink.
Here is how container log rotation works (see containerLogManager#rotateLatestLog):
* rename current log to rotated log file whose filename contains current timestamp (fmt.Sprintf("%s.%s", log, timestamp))
* reopen the container log
* if #2 fails, rename rotated log file back to container log
There is small but indeterministic amount of time during which log file doesn't exist (between steps #1 and #2, between #1 and #3). Hence the symlink may be deemed unhealthy during that period.
This PR resorts to runtimeService.ContainerStatus() to check whether the container corresponding to the potentially unhealthy symlink is alive or not. The …

Bug 1823406: Upstream: 89160: Remove potentially unhealthy symlink only for dead containers

---

test/extended/router/metrics.go

The new metrics backend exposed metrics were explicitly checked to
not return - we will weaken that test in anticipation of the other
PR being merged.
Prerequisite for https://github.com/openshift/router/pull/132

Bug 1835845: Metrics test for router should allow backend metrics

---

test/extended/router/grpc-interop.go
test/extended/router/grpc-interop/Makefile
test/extended/router/grpc-interop/cluster/Makefile
test/extended/router/grpc-interop/cluster/server/server.go
test/extended/router/grpc-interop/test-fixture-gen/gen.go
test/extended/router/h2spec.go
test/extended/testdata/bindata.go
test/extended/testdata/router/router-grpc-interop.yaml
test/extended/testdata/router/router-h2spec.yaml

This re-enables the h2spec and grpc-interop tests for the router. They were disabled by PR #24913. The way http/2 support is enabled was changed in https://github.com/openshift/router/pull/125 and this PR reacts to those changes.

Bug 1834343: router: Re-enable h2spec and grpc-interop e2e tests

---

images/hyperkube/Dockerfile.rhel

This is so we can access the "ss" utility, which we'd like to use during apiserver startup.
Right now we use `lsof`, which doesn't detect all sockets.

Bug 1837992: images/hyperkube: install iproute

---

pkg/apps/apiserver/registry/deployconfig/etcd/etcd.go
vendor/k8s.io/kubernetes/pkg/util/tolerations/tolerations.go
vendor/k8s.io/kubernetes/pkg/util/tolerations/tolerations_test.go
vendor/k8s.io/kubernetes/plugin/pkg/admission/podtolerationrestriction/admission.go
vendor/k8s.io/kubernetes/plugin/pkg/admission/podtolerationrestriction/admission_test.go

This carries upstream changes from k/k/81732, fixing the RFE in bugzilla 1806454.
It allows multiple values to be passed for tolerations, and joins those values together.

Bug 1806454: Allow multiple toleration values with the same key

---

vendor/k8s.io/kubernetes/pkg/controller/service/controller.go
vendor/k8s.io/kubernetes/pkg/controller/service/controller_test.go

In 16443 a set of changes were made to enable service load balancers
for Kube 1.1 and GCP to exclude unschedulable nodes from load balancer
pools. However, Unschedulable has nothing to do with whether nodes
should host service load balancer pods - the act of preventing new
pods from landing on a node has no impact on existing workloads.
In general nodes are not special, and a user who wants to exclude
otherwise healthy nodes can use the beta service load balancer
label to exclude the node from the LB pool.
This commit removes the check for unschedulable nodes from the
LB pool.

Bug 1832641: UPSTREAM: 90823: Service load balancers should include unschedulable nodes

---

vendor/k8s.io/kubernetes/pkg/controller/service/controller.go

Drop UPSTREAM: 63926, which causes deletion of "LoadBalancer"-type services to get stuck.
#19742 added the carry in order to reduce unnecessary cloud-provider API calls, but it is no longer needed and causes problems with recent changes to the clean-up logic for services with type "LoadBalancer".
At the time the PR was written, the service controller added every newly created service to its work queue, which was also used for update and delete events.  When a worker for this queue subsequently processed the service, it would check if the service needed an external load-balancer, and if not, it would then check if a load balancer existed for the service (in case the service had been added to the queue by an update that changed its type from "LoadBalancer", in which case any previously …

Bug 1798282: DROP: Avoid unnecessary calls to the cloud provider

---

vendor/k8s.io/kubernetes/pkg/volume/cinder/cinder.go

Backport of kubernetes/kubernetes#90608
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1827062

Bug 1827062: UPSTREAM: 90608: Updates the fstype of Cinder volumes to be ext4 if nil

---

test/extended/image_ecosystem/s2i_python.go

NOTE: there is no django template in the official OCP catalog that *DOES NOT* employ persistence.
The `oc new-app https://github.com/slcorg/django-ex` ultimately employ a non-persistent template that is in the upstream repo but is not marked for inclusion in OCP.
There was a push by PM a while back to focus on sample templates using persistence, so the lack of a non-persistent template make sense, especially with these SCL ones, who PM at the time would have focused on.
As such, as needed, test case checks will be adjusted to account for the fact that state is persisted in the PV.

Bug 1839187: more upstream to installed template switch in image-eco (django)

---

test/extended/operators/operators.go

We've had these since 5ff7aed012 (#21459), but conditions like `ClusterVersion` `Progressing=True` and `ClusterOperator` `Degraded=True` are serious enough that we don't want to see them post-install.  Make it fatal to see those surprises at all, instead of giving operators a pass during an arbitrary post-install recovery window.

Bug 1833387: test/extended/operators/operators: Drop cvoWait and operatorWait

---

vendor/k8s.io/kubernetes/test/e2e/framework/util.go
vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go

This reverts commit 648d8f84875920df4a6509ec4c1677859117968a.
Currently the flake happens around twice a day. That's probably not caused by the patch itself, but we should drop it anyways because it hasn't improved the situation.

Bug 1824423: Revert "UPSTREAM: <drop>: Increate timeout in volume expansion test"

---

vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_satoken.go
vendor/k8s.io/kubernetes/pkg/controller/serviceaccount/tokens_controller.go

Previously the serving service CA was added to token secrets by default. This commit changes the addition to be disabled by default and optionally enabled by setting `ADD_SERVICE_SERVING_CA_TO_TOKEN_SECRETS=true` in the environment.
PRs that need to merge before this one:

Bug 1813894: Disable the addition of service ca to token secrets

---

test/extended/image_ecosystem/s2i_python.go

cherrypick bot failed to backport from the 4.5 PR ... see https://github.com/openshift/origin/pull/25018#issuecomment-635410003

Bug 1841185: more upstream to installed template switch in image-eco (django this time)

---

test/extended/builds/pipeline_origin_bld.go

@akram @waveywaves FYI
with the verification on https://bugzilla.redhat.com/show_bug.cgi?id=1783530 earlier this month, the path to re-enablement of these tests in OCP's build and conformance suites in openshift/origin and openshift/* repos with those suites seems prudent
quick reminder, the pipeline_jenkins_e2e.go tests still run when you all create PRs in the openshift/jenkins* repos.
let's see how they look
@adambkaplan @coreydaley FYI

Bug 1841315: reenable jenkins e2e in e2e-gcp-builds

---

test/extended/util/disruption/disruption.go

Currently certain disruption measurement tests will report a failure in
junit but not fail the actual job, if the disruption amount is within a
certain limit.  However the message reported does not make it clear:
1) the job is being passed in spite of this "failure"
2) how to distinguish between "good enough" and "correct" results

improve disruption "failure" messaging

---

vendor/k8s.io/kubernetes/pkg/kubelet/pluginmanager/cache/actual_state_of_world.go
vendor/k8s.io/kubernetes/pkg/kubelet/pluginmanager/cache/actual_state_of_world_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/pluginmanager/operationexecutor/operation_executor.go
vendor/k8s.io/kubernetes/pkg/kubelet/pluginmanager/operationexecutor/operation_executor_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go
vendor/k8s.io/kubernetes/pkg/kubelet/pluginmanager/reconciler/reconciler.go

This PR simplifies the unregistration of csiplugin by dropping SocketPluginHandlers struct.
See https://github.com/kubernetes/kubernetes/pull/89934

UPSTREAM: 89934: Simplify the unregistration of csiplugin

---

test/e2e/upgrade/service/service.go

Instead of assuming that the AWS default applies to all providers, as we've done since we carried the upstream code in 9732d0124d (#24471).  This catches our copied-and-tweaked code up with upstream logic like that has switched on provider since kubernetes/kubernetes@46b89464fd (kubernetes/kubernetes#20959).

test/e2e/upgrade/service: Use 10m timeout for TestReachableHTTPWithMinSuccessCount

---

test/extended/networking/internal_ports.go

Fix testRemoteConnectivity error message

---

cmd/openshift-tests/provider.go
test/extended/util/ovirt/provider.go

oVirt didn't get a chance to be added as a provider to Kubernetes e2e tests [1][2][3], So we need to be added to origin like IBM on [4].
This is needed for skipping tests for ovirt [5]
[1] https://github.com/kubernetes-cn/kubernetes/blob/c3bec0bae43b4c46800a13f44534ce6cd14b5f40/test/e2e/framework/providers/openstack/openstack.go
[2] https://github.com/kubernetes-cn/kubernetes/blob/c3bec0bae43b4c46800a13f44534ce6cd14b5f40/test/e2e/framework/providers/vsphere/vsphere.go
[3] https://github.com/kubernetes-cn/kubernetes/blob/c3bec0bae43b4c46800a13f44534ce6cd14b5f40/test/e2e/framework/providers/azure/azure.go
[4] https://github.com/openshift/origin/pull/24817
[5] https://github.com/openshift/origin/blob/master/cmd/openshift-tests/provider.go#L57-L63
Signed-off-by: Gal-Zaidman …

Bug 1843407: oVirt, add oVirt as a provide to openshift tests

---

glide.lock
glide.yaml
vendor/github.com/seccomp/libseccomp-golang/.gitignore
vendor/github.com/seccomp/libseccomp-golang/CHANGELOG
vendor/github.com/seccomp/libseccomp-golang/Makefile
vendor/github.com/seccomp/libseccomp-golang/README
vendor/github.com/seccomp/libseccomp-golang/SUBMITTING_PATCHES
vendor/github.com/seccomp/libseccomp-golang/seccomp.go
vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go
vendor/github.com/seccomp/libseccomp-golang/seccomp_test.go

fixes https://bugzilla.redhat.com/show_bug.cgi?id=1728130
@rphillips

Bug 1728130: Bump libseccomp-golang to v0.9.1

---

test/extended/machines/scale.go

Original PR: Bump timeout for cluster to get back to original size
Deletion of the underlying infrastructure in Azure is taking over 7 min.
https://bugzilla.redhat.com/show_bug.cgi?id=1812240

[release-4.4] BUG 1824092: Managed cluster should grow and decrease when scaling different machineSets simultaneously (backport)

---

pkg/route/controller/ingress/ingress.go
pkg/route/controller/ingress/ingress_test.go

When translating the port specified by an Ingress to the target port for a Route, use the port name rather than the number, or omit the target port if it has no name.
An Ingress resource specifies a Service and a port on that Service whereas a Route resource specifies a Service and a target port on the corresponding Endpoints resource.  The ports on the Endpoints resource and the ports on the Service resources have matching names but may have different numbers. Therefore, when mapping an Ingress and Service to a Route and a target port for the Endpoints resource, we cannot use port numbers; we must use names or omit the target port entirely.
It is safe to omit the target port if it does not have a name because a Service port must have a name if the Service has more than one port; …

Bug 1763340: ingress: targetPortForService: Use port name only

---

cmd/openshift-tests/provider.go
test/extended/util/cloud/cloud.go

The old code allowed annotating tests as both "`[Skipped:Network/OpenShiftSDN]`" ("Skip on OpenShiftSDN") and "`[Skipped:Network/OpenShiftSDN/Multitenant]`" ("Skip on OpenShiftSDN in
Multitenant mode"). But the current code lost that distinction and ended up skipping the "only skip in Multitenant mode" tests even in NetworkPolicy mode (meaning we were always skipping the NetworkPolicy tests on openshift-sdn).

Bug 1842650: All NetworkPolicy tests currently being skipped on openshift-sdn

---

pkg/test/ginkgo/cmd_runsuite.go

The upstream JUnit lens learned how to dedup repeated tests and distinguish flakes in kubernetes/test-infra#16992.  Include our retries in the output to take advantage of that new UX.

pkg/test/ginkgo: Include flake retries in JUnit

---

vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/patch_satoken.go
vendor/k8s.io/kubernetes/pkg/controller/serviceaccount/tokens_controller.go

This reverts commit f24fbff3f692fe13ed7f229ddfa47dca6828e79d.
/cc @mfojtik

Bug 1845188: Revert "UPSTREAM: <carry>: Disable by default the addition of service ca to token secrets

---

cmd/watch-termination/main.go
images/hyperkube/Dockerfile.rhel
vendor/k8s.io/kubernetes/cmd/controller-manager/app/serve.go
vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go
vendor/k8s.io/kubernetes/pkg/kubeapiserver/server/insecure_handler.go
vendor/k8s.io/kubernetes/pkg/kubelet/server/server.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/timeout_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/wrap.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/httplog/httplog_test.go
vendor/k8s.io/kubernetes/test/integration/framework/test_server.go

This should give us insights into requests late in the termination phase. We still won't see those coming after termination. But as we wait 70s anyway to terminate, a request coming into after 20+ seconds (without our current LB configuration) is suspicious.
Note: this needs a fix to actually see logs after SIGTERM. Working on this.

apiserver: verbosity 3 on termination and watch-termination binary

---

vendor/k8s.io/kubernetes/test/e2e/storage/drivers/in_tree.go

Backport of https://github.com/kubernetes/kubernetes/pull/91642 .
Adjusts the Azure e2e binding mode from the default (Immediate) to WaitForFirstConsumer. This change also updates the Azure StorageClass to mirror the AWS and GCE ones.

Bug 1838730: UPSTREAM: 91642: Adjust Azure e2e binding mode

---

test/extended/builds/pipeline_origin_bld.go

- jenkins-second-deployment is no longer created by the jenkins-client-plugin e2e tests
- We are trying to DumpDeploymentLogs for a non-existent/non-expected deploymentConfig
Removing the DumpDeploymentLogs for `jenkins-second-deployment`

Remove dumpLogs for nonexistent DC - Jenkins e2e

---

test/extended/router/metrics.go

This assertion currently flakes a lot. (I believe) the flake occurs
when the router reloads and the GET for the latest metrics reads
zero's because there has been no updates.
It may be better to mark this test as serial. This commit retries the
assertion as opposed to dealing with it as a one-shot.
The expectation is that haxproxy_server_max_sessions needs to be
greater than zero over two successive scrapes once the first scrape
shows an increase. However, this assertion can still fail depending on
when the metrics are refreshed and when the router reloads, which is
every 5s. In my testing I have seen this to be more resilient but
there are periods when running the full openshift/conformance tests
that this continues to fail.

Bug 1835371: router/metrics: Fix haproxy_server_max_sessions test

---

test/extended/prometheus/prometheus.go

this is only being added temporarily until
https://bugzilla.redhat.com/show_bug.cgi?id=1842002 is resolved,
after which this PR must be reverted.

add kubepodcrashlooping to list of ignored alerts

---

test/extended/router/grpc-interop.go

The builder pod is taking a long time to complete in CI. In local
testing (i.e., on a quiescent cluster) it takes between 45s-60s to
complete. In CI this is taking much longer so switching to
WaitForPodRunningSlow which has a longer timeout (currently 15m).
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1845434
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1845646

Bug 1845434: router/grpc-interop: switch to WaitForPodRunningSlow

---

vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go
vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go
vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector_test.go
vendor/k8s.io/kubernetes/test/integration/garbagecollector/garbage_collector_test.go

It prevents the GC from entering a slow loop (up to 1 hour) and blocking the other controllers.
Before this PR the GC used the restmapper (with the cache) in the constructor (a blocking operation) to construct its dependency graph.
In order to fill up the cache, the mapper needs to perform the full discovery which visits all API servers even if what it needs is already in the cache. The cache itself is invalidated by the KCM every 30 seconds. The GC needs to use the mapper many times (~len(deletableResources)) before it creates the graph.
When the discovery is slow (a node is down, a network is slow/broken) and takes more than 30s, creating the graph is also slow (cache invalidation) and might block the other controllers when the GC is run early in the process.
This PR moves the logic …

UPSTREAM: 91816: GC doesn't have to create monitors in the constructor

---

cmd/watch-termination/main.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/goaway.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/server_run_options.go

Picking upstream https://github.com/kubernetes/kubernetes/pull/92136.

kube-apiserver: drain HTTP/2 early during termination

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go

the genericapiserver library must wait until server.Shutdown completes so that connections are gracefully shutdown.
previously there was a race between shutting down a process (server) and closing connections. That might have resulted in some connections not being properly closed on a TCP level.

UPSTREAM: 91984: genericapiserver library must wait for server.Shutdown

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/basicresources.sh

https://github.com/openshift/oc/pull/459 changes the error message into `you must specify at least one of --readiness, --liveness, --startup`.

[test extended] don't be strict about set probe missing probe flag

---

test/extended/oauth/client_secret.go

This is a follow-up to https://github.com/openshift/origin/pull/24984

e2e: Add other client-authn methods to token request test

---

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go

recreated from: https://github.com/openshift/origin/pull/25079

Bug 1845369: UPSTREAM: 91500: reduce race risk in kubelet for missing KUBERNETES_SERVICE_HOST

---

test/extended/dr/common.go
test/extended/dr/quorum_restore.go

The addition of cluster etcd operator introduced a new disaster recovery workflow that broke the disruptive tests. The previous workflow involved doing a snapshot restore of the etcd data file. The advantage to this approach is that once etcd starts the process is complete. The downside is a restore action must take place on each master node.
In 4.4+ we automate this process and require only a single invocation of the cluster-backup.sh script and cluster-restore.sh script. Given new machines the operator then scales etcd on the new machines resulting in a 3 node etcd cluster.
The downside of this process is that it is more disruptive as etcd and the rest of the control plane scales. For this reason, we needed to adjust not only some of the timings of the old test allowing for certain …

Bug 1797244: test/extended/dr: update test to reflect new DR process

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/goaway.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/server_run_options.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/secure_serving.go

This is an alternative to https://github.com/openshift/origin/pull/25106 and https://github.com/openshift/origin/pull/25118. Instead of full http logs, we only get a remote address though. Good enough to leave it on in production code and without risk of logging oauth tokens.

UPSTREAM: <carry>: apiserver: log new connections during termination

---

test/extended/prometheus/prometheus.go

Currently the master CVO serves only HTTP.  There is a pull request in flight (openshift/cluster-version-operator#385) to declare an HTTPS target in the ServiceMonitor.  Allowing both, as I'm doing in this commit, will allow us to land this test-suite change now.  Then we can land the CVO pull request.  And then we can drop the '?' to require HTTPS going forward.

Bug 1809195: test/extended/prometheus: During transition, allow HTTP(S) for CVO

---

test/extended/conformance-k8s.sh

Since recent changes to SCC which in the long term will be managed by
kas-o oc currently modifies rolebindings when assigning SCC to or
removing from user/group. This PR modifies our conformance test such
that the OpenShift specific restrictions are removed from SCC.
/assign @mfojtik @stlaz

Bug 1845549: manually patch scc/restricted and scc/anyuid for conformamce tests

---

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_network.go

This is a release-3.11 cherry-pick of https://github.com/openshift/origin/pull/25141

Bug 1845778: [release-3.11] kubelet: block non-forwarded packets from crossing the localhost boundary

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go

This prevents `GetAzureDiskLabels` from panicking when `c.DisksClient` is nil.
This panicking makes the API server to crash loop for some ARO clusters as elaborated in https://bugzilla.redhat.com/show_bug.cgi?id=1847185
https://github.com/kubernetes/kubernetes/pull/92166
https://github.com/kubernetes/kubernetes/issues/92167

Bug 1847185: fix: GetLabelsForVolume panic issue for azure disk PV

---

cmd/watch-termination/main.go

We log requests of oauth tokens when log level is increased. But in the default case we don't log any requests. This PR restore the old (sub-optimal) situation, i.e. we are not worse than before.

watch-termination: don't log oauth tokens

---

test/extended/prometheus/prometheus.go

Now that the CVO pull request has landed, require HTTPS going forward (firming up the flexible behavior from #25134).
/hold
Until openshift/cluster-version-operator#385 actually lands.

Bug 1809195: test/extended/prometheus: Require HTTPS for the CVO

---

test/extended/authorization/rbac/groups_default_rules.go

Authenticated user will get capability to read VolumeSnapshotClasses [soon](https://github.com/openshift/cluster-csi-snapshot-controller-operator/pull/39). The test must be updated before the actual RBAC change is merged, so CI works both before the update and after.
The test tolerates 15 extra RBAC rules, so it's going to pass, only write this to stdout:
```
Jun 17 10:07:55.555: INFO: test data for system:authenticated has too many unnecessary permissions:
{APIGroups:["snapshot.storage.k8s.io"], Resources:["volumesnapshotclasses"], Verbs:["get" "list" "watch"]}
```
This resolves when cluster-csi-snapshot-controller-operator [actually includes the new RBAC rules](https://github.com/openshift/cluster-csi-snapshot-controller-operator/pull/39).

Bug 1841035: Add volumesnapshotclass to default RBAC test

---

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_network_linux.go

See https://github.com/kubernetes/kubernetes/pull/91569

Bug 1849175: UPSTREAM: 91569: kubelet: block non-forwarded packets from crossing the localhost boundary

---

test/extended/builds/pipeline_origin_bld.go

this test consistently fails because the pipeline references a second deployment which does not exist.

disable broken jenkins test

---

test/extended/builds/pipeline_origin_bld.go

this test consistently fails because the pipeline references a second deployment which does not exist.

[4.5] disable broken jenkins test

---

test/extended/builds/OWNERS
test/extended/imageapis/OWNERS
test/extended/images/OWNERS

Remove the Image Registry team members from builds OWNERS and add OWNERS for images and imageapis tests.

Update test owners

---

vendor/k8s.io/kubernetes/test/e2e/framework/cleanup.go
vendor/k8s.io/kubernetes/test/e2e/framework/pod/delete.go
vendor/k8s.io/kubernetes/test/e2e/framework/util.go
vendor/k8s.io/kubernetes/test/e2e/storage/csi_mock_volume.go
vendor/k8s.io/kubernetes/test/e2e/storage/drivers/csi.go
vendor/k8s.io/kubernetes/test/e2e/storage/external/external.go
vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go
vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/testdriver.go
vendor/k8s.io/kubernetes/test/e2e/storage/utils/create.go
vendor/k8s.io/kubernetes/test/e2e/storage/utils/utils.go

Backport of:
1. https://github.com/kubernetes/kubernetes/pull/90773
2. https://github.com/kubernetes/kubernetes/pull/91221
3. https://github.com/kubernetes/kubernetes/pull/91689
This fixes issues that were caused by CSI driver being deleted before pod that was using could be deleted and hence such pods were left in "terminating" state.  This PR fixes that bug by causing CSI driver to be installed in different namespace. 
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1814282
There are still some issues around snapshot e2es leaving namespaces in terminating state. But those are not e2e bugs but are actual bugs in snapshot controller etc - this is being tracked https://bugzilla.redhat.com/show_bug.cgi?id=1848633

Bug 1814282: Storage e2es leaving namespaces/pods around

---

vendor/k8s.io/kubernetes/pkg/kubelet/stats/cadvisor_stats_provider.go
vendor/k8s.io/kubernetes/pkg/kubelet/stats/cadvisor_stats_provider_test.go

Metrics from the kubelet could contain duplicate metrics. This causes 500's on the metric endpoint causing zero metrics to be sent. This patch is an upstream pick that fixes this issue.
Ref: https://github.com/kubernetes/kubernetes/pull/86009
/assign @sjenning

Bug 1807822: UPSTREAM: 86009: kubelet: guarantee at most only one cinfo per containerID

---

test/extended/topology_manager/resourcealign.go
test/extended/topology_manager/utils.go

TL;DR: the topology manager code is correct, a specific test fails to capture this leading to false negatives
The existing regression test which wants to cover against regressions
on RHBZ#1813567 is actually doing the reverse check than it should.
We noticed after having the test run for few days on environment kindly
provided by nfvpe team.
The likely cause of why this mistake sneaked in is that I wrongly
configured the original environment on which I tried the test.
This patch fixes the issue and puts extra care in documenting and
checking the intent of the original bugzilla.
Signed-off-by: Francesco Romani <fromani@redhat.com>

Bug 1850140: tests: extended: fix TM regression test

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/vsphere/BUILD
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/vsphere/nodemanager.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere_test.go

Cherry-pick of https://github.com/kubernetes/kubernetes/pull/90836
Add ability for vSphere to reconnect to cached nodes on secret update or create
- Refactor getNodeInfo to be more descriptive
- Add log output testing for secret update
- Ensure all nodes refreshed on secret change
- Add config option to disable secret management

Bug 1821280: Unable to provision vSphere volume

---

test/extended/etcd/etcd_storage_path.go

Fixes following flaky test:
```
[sig-api-machinery] API data in etcd should be stored at the correct location and version for all resources [Serial] [Suite:openshift/conformance/serial] expand_less	1m6s
fail [github.com/openshift/origin/test/extended/etcd/etcd_test_runner.go:80]: test failed:
failed to create stub for /v1, Kind=Pod: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"Status", APIVersion:"v1"}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"pods \"pod1\" is forbidden: error looking up service account etcdstoragepathtestnamespace/default: serviceaccount \"default\" not found", Reason:"Forbidden", Details:(*v1.StatusDetails)(0xc003328960), Code:403}}
```

test/etcd: wait for default service account to be avaiable

---

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_network_linux.go

This is a cherry-pick of https://github.com/openshift/origin/pull/25141

Bug 1845774: [release-4.5] kubelet: block non-forwarded packets from crossing the localhost boundary

---

test/extended/builds/pipeline_origin_bld.go

@adambkaplan @akram @waveywaves fyi

Bug 1850109: remove problematic upstream client plugin test

---

cmd/watch-termination/main.go

When a termination lock file is found while starting up, an NonGracefulTermination event is created
using the passed kubeconfig, waiting in the background until the kubeconfig starts working (e.g. until
the kube-apiserver launches).

watch-termination: create NonGracefulTermination event on next launch

---

test/extended/router/metrics.go

The changes to reporting router backend metrics requires a change to our tests to allow backend metrics to be reported, as well as a fix for a flake in the tests after the fix is delivered.  The max_sessions test is disabled because it requires the code to be delivered first and we don't want to do this in two rounds of delivery.  We are confident the code works in the latest release.

Bug 1848687: Fix router metrics to be accurate in 4.4

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher_whitebox_test.go

clean pick.
`TestDispatchingBookmarkEventsWithConcurrentStop` must use `processEvent` instead of `dispatchEvent` to avoid data race conditions with `Cacher.watchersBuffer`.

UPSTREAM: 89164: Fix data race issue in unit test

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/patch_genericapiserver.go

Both kcm and ks connect via localhost. Those do not follow `/readyz` by design and we better don't create LateConnection events for them as this would hide the clients we are really interested in: those going though load balancers and the kubernetes service.
In addition, probes accessing /readyz or /healthz are fine at all times. So also exclude those.

UPSTREAM: <carry>: apiserver: skip local IPs for LateConnections

---

vendor/k8s.io/kubernetes/pkg/volume/azure_dd/azure_common_linux.go

Include /dev/disk/azure/scsi0 when evaluating Azure root disks. This should enable finding of non-root disks for attached volumes.
https://bugzilla.redhat.com/show_bug.cgi?id=1845853
1.16 cherry-pick (= OCP 4.3): https://github.com/kubernetes/kubernetes/pull/86691

Bug 1847089: UPSTREAM: 86691: fix: azure disk could not mounted on Standard_DC4s/DC2s

---

pkg/network/node/egressip.go
pkg/network/node/vxlan_monitor.go
pkg/network/node/vxlan_monitor_test.go

The egressIPTracker has methods that lock eit.mutex and that call
evm functions that lock evm.mutex.
The problem with this is that evm.mutex has to write to the evm.updates
channel which isn't buffered and becomes blocked until
eit.setNodeOffline, which also locks eit.mutex, is running.
This causes a deadlock. Initially I tried doing a horrible hack by
making the updates channel huge, however it wasn't enough.
Instead this fix adds a shared nodes list between eit and evm and the
evm uses the updates channel just to notify the eit that there are
updates in the shared list.

[release 3.11]Bug 1824243: Fix egressVXLANMonitor and egressIPTracker deadlock

---

cmd/watch-termination/main.go

Overrides arg cannot be nil. Upstream PR in the works.

watch-termination: fix NewNonInteractiveDeferredLoadingClientConfig NFE

---

pkg/monitor/monitor.go
pkg/monitor/sampler_test.go
pkg/monitor/types.go

API monitor does not keep track of when an Event started.

monitor: add time to track from for a Condition

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/healthz/healthz.go

instead of newlines for every check, this reduces the output to just the failed checks and provides the detailed health check information in the log (not the endpoint) about the failure. This will make it easier to debug crashloop logs.

UPSTREAM: 92197: make log output of failed healthchecks more focused

---

test/e2e/upgrade/alert/alert.go
test/e2e/upgrade/upgrade.go
test/extended/prometheus/prometheus.go
test/extended/prometheus/prometheus_builds.go
test/extended/util/client.go
test/extended/util/prometheus/helpers.go

cherry-pick https://github.com/openshift/origin/pull/24786/commits/3b8cb3ca9b57e17980aa321bb8402ac9c144a17e
After an upgrade is successful, there should not be any critical
alerts on the cluster. Post upgrade success, this change delays for
alertCheckSleepMinutes and then checks if any critical alerts occurred
within the last alertPeriodCheckMinutes and if so the test fails.
After a successful check that confirms no critical alerts have occurred
post cluster upgrade, this change will perform another Prometheus
query checking for the occurrance of Watchdog alerts thereby verifying
Prometheus is indeed up and running correctly.
Prometheus helper package created to contain common code used to query
Prometheus. The code being moved to the helper package is currently
used by the upgrade Alert …

Bug 1828477: Add CI test to check for critical alerts post upgrade

---

test/extended/cli/mustgather.go

Temporarily disable checking for missing files to unstick the merge queue.
Urgent test blocker: https://bugzilla.redhat.com/show_bug.cgi?id=1853612

must-gather: temporarily disable broken test

---

test/extended/operators/images.go

The UBI8 image has the following string in /etc/redhat-release
Red Hat Enterprise Linux ...
and thus fails this test. We accept both UBI/RHEL 7/8 images and
so we loosen the test here.

test: Broaden check for base images that are RHEL8

---

vendor/k8s.io/kubernetes/pkg/apis/core/validation/conditional_validation.go
vendor/k8s.io/kubernetes/pkg/apis/core/validation/conditional_validation_test.go
vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation_test.go
vendor/k8s.io/kubernetes/pkg/registry/core/rest/storage_core.go
vendor/k8s.io/kubernetes/pkg/registry/core/service/BUILD
vendor/k8s.io/kubernetes/pkg/registry/core/service/storage/BUILD
vendor/k8s.io/kubernetes/pkg/registry/core/service/storage/rest.go
vendor/k8s.io/kubernetes/pkg/registry/core/service/storage/rest_test.go
vendor/k8s.io/kubernetes/pkg/registry/core/service/storage/storage.go
vendor/k8s.io/kubernetes/pkg/registry/core/service/storage/storage_test.go
vendor/k8s.io/kubernetes/pkg/registry/core/service/strategy.go
vendor/k8s.io/kubernetes/pkg/registry/core/service/strategy_test.go

The `IPv6DualStack` feature gate is currently unusable in OCP because of bugs in `Service.Spec.IPFamily` validation. This is now fixed upstream and it would be useful for dual-stack testing to get these fixes into origin master now rather than waiting for the 1.19 rebase

IPFamily fixes from upstream

---

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_network_linux.go

This is a release-4.4 cherry-pick of https://github.com/openshift/origin/pull/25141

Bug 1845780: [release-4.4] kubelet: block non-forwarded packets from crossing the localhost boundary

---

pkg/router/metrics/haproxy/haproxy.go
pkg/router/metrics/haproxy/haproxy_test.go

Backports https://github.com/openshift/router/commit/4aa8e05c8306bdbd87555447bb0cb50be819e278 from https://github.com/openshift/router/pull/127 to origin `release-3.11` as per BZ#1847478.
Note, go.mod & go.sum changes were dropped from `4aa8e05` (necessary packages are already in `release-3.11`), and `klog` was switched out with `glog`/`flag` in `haproxy_test.go`.

[release-3.11] Bug 1847478: Backport haproxy router metrics fix (openshift/router#127)

---

vendor/k8s.io/kubernetes/pkg/registry/rbac/BUILD
vendor/k8s.io/kubernetes/pkg/registry/rbac/helpers.go
vendor/k8s.io/kubernetes/pkg/registry/rbac/helpers_test.go

Manually cherry-picking #25261 back to 4.5, to get a head-start on 4.5 CI jobs (without waiting for the master PR to land).

Bug 1855444: UPSTREAM: 91648: Changes to ManagedFields is not mutation for GC

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go

brings back the egress proxy configuration to the kube-aggregator lost during previous backporting.
it requires backporting at least to 4.5 and 4.4

wires the egress proxy to the kube-aggregator 

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware_test.go

UPSTREAM: 92941: Don't return proxied redirects to the client

---

test/extended/cli/mustgather.go

We also have termination logs in the /var/log/*-apiserver directories. These don't have events inside, obviously.
Fixes e2e tests in https://github.com/openshift/cluster-kube-apiserver-operator/pull/876.

e2e/mustgather: ignore non audit files in /var/log/*-apiserver dir

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/patch_genericapiserver.go

In unit tests we create multiple apiservers in parallel, leading to a race writing the global variable.

UPSTREAM: <carry>: apiserver: skip local IPs and probes for LateConnections – fix race

---

vendor/k8s.io/kubernetes/pkg/kubelet/prober/prober.go

When the kubelet restarts it does not populate the RefManager map. Probes that were running before the kubelet restart do not generate events, but instead log `no ref for container`.
ref: https://github.com/kubernetes/kubernetes/pull/84792

Bug 1856250: UPSTREAM: 84792: Fixes for the `No ref for container` in probes after kubelet restart

---

vendor/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go

Backporting https://github.com/kubernetes/kubernetes/pull/71063

bug 1858287: UPSTREAM: 71063: fix a scheduler panic due to internal cache inconsistency

---

pkg/test/ginkgo/cmd_runsuite.go
test/e2e/upgrade/alert/alert.go
test/e2e/upgrade/service/service.go
test/extended/util/disruption/controlplane/controlplane.go
test/extended/util/disruption/frontends/frontends.go

Future changes will test invariants reported by events, such as whether
images were pulled from outside of the current code base. Also updates
the junit reporting for the "error level events" to be reported as a
flake, and corrects the duration to include "late" tests.

test: Allow test suites to define additional checks for suite failure

---

test/extended/etcd/etcd_storage_path.go

With hyperkube built from openshift/kubernetes this test must work with current version and rebase version. For that we check the server version and apply the 1.19 diff:
```
git diff origin/release-1.18 origin/release-1.19 test/integration/etcd/data.go
```

etcd-storage-test: apply 1.19 diff

---

test/extended/operators/qos.go

fix flake found in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/411/pull-ci-openshift-cluster-version-operator-master-e2e/1286271671807774720
/hold
I need to write a bug to backport this thing.

bug 1860157: allow recycler pods to run with best effort qos

---

test/e2e/upgrade/upgrade.go
test/extended/dr/machine_recover.go
test/extended/util/disruption/controlplane/controlplane.go

This will help us narrow down messages like https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade-4.6/1286281612429889536 more easily.

make the error message specific to which API server connection blipped

---

test/extended/util/framework.go

The logic for testing for pod failure lost the reason why, so no
debug output was possible. Instead, update the one shot pod to
capture fallback logs and then have the executor report that as
the error message.
E.g.
Jul 22 20:13:43.152: INFO: pod "test-cmd" errored trying to run the command: <nil>
because err was nil in the context it was invoked.
Noticed in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/25304/pull-ci-openshift-origin-master-e2e-cmd/1286015364055961600

test: Report an error message when a pod fails in a cmd test

---

test/extended/cli/mustgather.go
test/extended/util/annotate/generated/zz_generated.annotations.go

This is slightly improved and rebased version of #24680 
The main issue with the original was that it might happen that audit files can be empty, in which case `gzip.NewReader(file)` will return `EOF`. The second commit in this PR accounts for that and ignores empty audit files. 
/assign @deads2k @wking

test/extended/cli/mustgather: Separate gather_audit_logs test

---

test/extended/prometheus/prometheus.go

Disabling as it's blocking e2e tests. This is traced in https://bugzilla.redhat.com/show_bug.cgi?id=1860837

Disable named network metrics test.

---

test/extended/prometheus/prometheus.go

The network name is now produced as the composition of namespace and the network name.
This is introduced by a change in multus https://github.com/openshift/multus-cni/commit/e7c8977423a6c221074f173a497a5de0aaa98649
so the change in the test reflects the change in the way the interface name is added to
the pod.

Fix "should provide named network metrics" test.

---

test/extended/operators/olm.go

This test fails (ex https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_oc/491/pull-ci-openshift-oc-master-e2e-aws/1286712821660258304) with:
```
fail [github.com/openshift/origin@/test/extended/operators/olm.go:77]: Expected
<truncated long json output.... "served":true,"storage":true,"subresources":{"status":{}}}
to contain substring
<string>: served:true
```

Update OLM e2e to include quotes on substring check

---

test/extended/cli/mustgather.go

Apparently it takes a while for logs to appear, so we retry on a loop to avoid that.
The openshift-apiserver will have many fewer requests than the kube-apiserver, so have two different counts.
Update the error message to more clearly indicate which audit log is broken for better debugging in the future.

bug 1861201: make must-gather test resilient to failures and disk timing

---

vendor/k8s.io/kubernetes/test/e2e/apps/disruption.go

pdbs were fixed to be more tolerant of certain classes of delete. This means old tests and new cluster break because the delete isn't constrained.  We need https://github.com/kubernetes/kubernetes/pull/92991 . I pulled the entire file in to be sure.
This will go away once we revendor, but the level in o/k is right.  If pdb tests pass, we should green button this.

bug 1861189: UPSTREAM: <drop>: make pdb tests pass reliably

---

test/extended/cli/mustgather.go

opened https://bugzilla.redhat.com/show_bug.cgi?id=1861746 to get the test/functionality fixed for 4.6.0.

skip flaky must-gather audit test to get a payload accepted

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

After it even fails in https://github.com/openshift/origin/pull/25351, let's disable this test.

Bug 1862322: e2e/extended: disable OLM 'can subscribe to the operator' test

---

test/extended/oauth/requestheaders.go

The colon of `sha256:<token>` is escaped to `%3A`. Because we don't parse the URl, but pick it via regex, the result is unescaped.

e2e/oauth: unescape token taken from redirect url fragment

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

ovnkube: skip Conntrack test that's flaky upstream

---

test/extended/prometheus/prometheus.go

Now that https://github.com/openshift/origin/pull/25328 is merged, the test should be fixed.
We can remove the skip and re-enable the test.

Bug 1860837: Re-enable prometheus named network metrics test.

---

test/extended/oauth/token.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Add e2e for https://github.com/openshift/kubernetes/pull/208.

e2e-oauth-authn: support sha256 prefixed tokens

---

test/extended/authorization/authorization.go
test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

This is for ibmcloud and their e2e openshift conformance test framework. To fix the `[Top Level] [sig-auth][Feature:OpenShiftAuthorization][Serial] authorization  TestAuthorizationResourceAccessReview should succeed":                                                                                                      "should succeed [Suite:openshift/conformance/serial]` test for 4.3.

Added skips to checks for IBM serviceaccount and IAM components

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/timeout.sh

Required for the oc 1.19 bump, see https://github.com/openshift/oc/pull/491#issuecomment-667254495
Note: this is only broken in the 1.19 oc bump, because the output of this command changed between 1.18 and 1.19
1.19:
```
$ ./oc get deployment.apps/openshift-kube-scheduler-operator -w -v=5 --request-timeout=1s
NAME                                READY   UP-TO-DATE   AVAILABLE   AGE
openshift-kube-scheduler-operator   1/1     1            1           4h45m
I0731 14:09:15.563497   81453 streamwatcher.go:117] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout or context cancellation while reading body)
```
vs pre-1.19:
```
$ oc get deployment.apps/openshift-kube-scheduler-operator -w -v=5 --request-timeout=1s
NAME                                READY …
```

Update expected text for test-cmd timeout

---

test/extended/operators/images.go

openshift-marketplace intentionally pulls images from outside of the
release

skip openshift-marketplace namespace when checking that images come from the release

---

test/extended/prometheus/prometheus.go

As in title.
Bugzillas for those targets are already in VERIFIED state.
/cc @s-urbaniak  @lilic

test/extended/prometheus: remove exclusion for targets already exposing data over HTTPS

---

test/extended/oauth/expiration.go

Like https://github.com/openshift/origin/pull/25346, but for access tokens.

e2e/oauth/expiration: support sha256 tokens – auth tokens

---

test/extended/util/annotate/rules.go

Fixed by
https://github.com/openshift/cluster-network-operator/pull/608
https://github.com/openshift/cluster-network-operator/pull/658
https://github.com/openshift/cluster-network-operator/pull/659
IBM no longer needs this test to be skipped.

Removed the "Managed cluster should ensure control plane pods do not run in best-effort QoS" test from IBM's skipped list

---

hack/verify-upstream-commits.sh
tools/rebasehelpers/commitchecker/commitchecker.go

backport of https://github.com/openshift/origin/pull/25366 and https://github.com/openshift/origin/pull/24722

[release-4.4] Fix commit checker

---

hack/verify-upstream-commits.sh
tools/rebasehelpers/commitchecker/commitchecker.go

If we are not able to verify a commit we must fail, not silently show an error message and claim it's ok.
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/25326/pull-ci-openshift-origin-release-4.4-verify/1287675728137031680/artifacts/verify/logs/raw_test_output.log
```
=== BEGIN TEST SUITE github.com/openshift/origin/test/verify/upstream-commits ===
=== BEGIN TEST CASE ===
hack/verify-upstream-commits.sh:19: executing 'commitchecker' expecting success
SUCCESS after 0.016s: hack/verify-upstream-commits.sh:19: executing 'commitchecker' expecting success
There was no output from the command.
Standard error from the command:
WARNING: one of the provided commits does not exist, not a true branch
=== END TEST CASE ===
=== END TEST SUITE ===
```
The root cause is fixed on release-4.5, …

[release-4.5] Fix commit checker

---

test/extended/topology_manager/resourcealign.go
test/extended/util/annotate/generated/zz_generated.annotations.go

We seen a resurgence of https://bugzilla.redhat.com/show_bug.cgi?id=1851623
blocking PRs with false negatives.
Despite the test trying hard to be nice, and checking there is at least
a worker node which reports enough allocatable CPU:
Aug  4 15:49:21.372: INFO: node "$NODE1" available cpu {{1500 -3} {<nil>} 1500m DecimalSI} requested cpu {{1000 -3} {<nil>}  DecimalSI}
Aug  4 15:49:21.372: INFO: at least node "$NODE1" has enough resources, cluster OK
the pod stays in pending state and eventually the tests times out:
Aug  4 15:49:21.534: INFO: pod "test-h4k4b" phase Pending
[...]
Aug  4 15:54:21.664: INFO: pod "test-h4k4b" phase Pending
[...]
STEP: Collecting events from namespace "e2e-test-topology-manager-qsqx6".
STEP: Found 1 events.
Aug  4 15:54:21.731: INFO: At 2020-08-04 15:49:21 …

e2e: topomgr: disable again failing test

---

test/extended/oauth/token.go

Those two e2e tests for oauth tokens use the same token name. If they run in parallel by accident, they may conflict with each other.

e2e/oauth: deflake by using random tokens

---

test/extended/oauth/token.go

We have no way to atomatically switch over to sha256~. Hence, we disable e2e first for sha256: and then
re-enable them for sha256~.

extended/oauth: skip sha256 test until https://github.com/openshift/kubernetes/pull/305 merged

---

pkg/monitor/api.go
test/e2e/upgrade/upgrade.go
test/extended/dr/machine_recover.go
test/extended/util/disruption/controlplane/controlplane.go

We created a new server (OAuth API server) that is responsible for managing `oauth.openshift.io` and `user.openshift.io`. Before these groups were managed by the OpenShift API server.
This PR adds a new monitoring test for checking the availability of the new server.

adds a new monitoring test for checking OAuth API server

---

test/extended/oauth/token.go

This reverts commit c26d2f515d264bef0dd8575e608a6571dc3802e6.
Depends on https://github.com/openshift/kubernetes/pull/305.

Revert "extended/oauth: skip sha256 test until https://github.com/openshift/kubernetes/pull/305 merged"

---

test/e2e/upgrade/monitor.go
test/e2e/upgrade/upgrade.go
test/extended/dr/machine_recover.go
test/extended/dr/quorum_restore.go
test/extended/util/disruption/disruption.go

If CVO failed to acknowledge upgrade within the time limit, display
a specific error. If we failed to upgrade, give each failing operator
their own failed junit result including the condition and message.

test: Upgrade test should log more granular failures

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

Re-enabling selected tests now that associated bugs have been fixed and are in the Red Hat OpenShift on IBM Cloud v4.3 builds.
```
[Feature:Prometheus][Conformance] Prometheus when installed on the cluster should provide ingress metrics
[Conformance][Area:Networking][Feature:Router] The HAProxy router should enable openshift-monitoring to pull metrics
[k8s.io] [sig-node] Pods Extended [k8s.io] Pod Container Status should never report success for a pending container
```

Re-enable skipped conformance tests for IBM Cloud

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

Should no longer be necessary now that the 1.19 rebase has landed in origin and oc.

Remove exit code skip

---

test/e2e/upgrade/upgrade.go

We think we're a few minutes slow on aws.  This will let us work it out, while still having a clear indication of how slow we are.

allow longer upgrade times to run tests, but continue to fail junit at 75 minutes

---

test/extended/operators/cluster.go
test/extended/util/annotate/generated/zz_generated.annotations.go

it looks like we have a significant number of recycler pod problems compared against "other" pods.  Both are problematic, but recycler pods are less bad and specifically storage related. This refactors the test and allows filtering.
Review with whitespace off

split the crashlooping pod test to more precisely tag recycler pods

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_standard.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_zones.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_zones_test.go

cherry-pick https://github.com/kubernetes/kubernetes/pull/89877

Bug 1860832: Ensure Azure availability zone is always in lower cases

---

test/extended/util/prometheus/helpers.go

Adds `--retry 15 --max-time 2 --retry-delay 1` to the Prometheus query curl call in `test/extended/util/prometheus/helpers.go`. This is to prevent the test from failing during the `e2e-aws-scaleup-rhel7` job, where DNS pods scheduled on newly spun-up rhel7 worker nodes may not immediately be responsive. As seen in the linked BZ, the first test in `test/extended/prometheus/prometheus.go` is hitting DNS errors during the `e2e-aws-scaleup-rhel7` job while the remainder of the prometheus tests are not, despite using the same curl code. Hence why adding the retry options will be beneficial in reducing test failures. 
/assign @Miciah 
/cc @danehans @frobware

Bug 1826094: Add retry options to Prometheus helper curl command

---

test/e2e/upgrade/upgrade.go

This gives distinct junit for each main failure block.  Once this merges (or once this is tagged), we can update sippy to ignore the "something failed" to reduce noise.
I recommend reviewing without whitespace diff: https://github.com/openshift/origin/pull/25417/files?w=1

finish splitting each part of the upgrade into distinct junit

---

test/extended/machines/cluster.go
test/extended/util/annotate/generated/zz_generated.annotations.go

@deads2k @smarterclayton 
xref https://bugzilla.redhat.com/show_bug.cgi?id=1869654

test: extended: add test checking for mismatch between Machines and Nodes

---

pkg/route/controller/routeapihelpers/validation.go
pkg/route/controller/routeapihelpers/validation_test.go

Modify the extended validation logic to copy any private key found in the certificate field of a route's TLS configuration to its key field.
Extended validation validates a route's TLS configuration using any key that is specified in either the TLS configuration's certificate field or its key field.  As a result, a route that specifies the certificate and key together in the certificate field may pass extended validation and be admitted.  However, the certificate manager only wrote the certificate out if the TLS configuration had a nonempty key field.  As a result, a route with a valid certificate and key could be admitted but the certificate and key not written out, which would cause HAProxy to fail to load.
* `pkg/route/controller/routeapihelpers/validation.go` (`splitCertKey`): New …

Bug 1857025: Sanitize TLS config that has key bundled with cert

---

vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/predicates.go
vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/predicates/predicates_test.go
vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity.go
vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity_test.go

This is a non-breaking version of https://github.com/openshift/origin/pull/24616
The goal of this is to validate Pod affinitys *before* the pod is scheduled and reject the pod if there is an invalid value. Without this check, the invalid pod will be scheduled and *all subsequent pods* will fail to schedule when attempting to parse the invalid value.

[release-3.11] Bug 1760807: UPSTREAM: <carry>: Enforce label selector validation in scheduler podAffinity

---

test/extended/etcd/etcd_storage_path.go
test/extended/etcd/etcd_test_runner.go

The port-forward connection is being broken.  This can happen on kube-apiserver rollouts in general, which we want to tolerate, so this updates the code to handle the case of a broken connection during a test.
This happens to be the #1 serial failure on openstack.

bug 1870247: re-establish etcd connection if required for etcd test

---

test/extended/dr/quorum_restore.go

quorum-guard switched namespaces in 4.6 this PR updates that.

Bug 1868436: test/extended/dr: fix quorum-guard namespace

---

vendor/k8s.io/kubernetes/pkg/controller/history/controller_history.go
vendor/k8s.io/kubernetes/pkg/controller/history/controller_history_test.go

If there are 2 revisions, we need to sort them always the same or statefulset may hotloop updating between the 2 revisions that have the same content but different names.
/cc soltysh

Bug 1863763: Fix statefulset update loop

---

pkg/router/metrics/haproxy/haproxy.go
test/extended/router/metrics.go

This is the 3.11.z backport of https://github.com/openshift/router/pull/132
---
When no servers are exposed, backend metrics are needed to see
how many requests are making it to a service. If we don't report
them users can't see when no pods are up (a crashlooping service
for instance would have no metrics at all because no pods are
ready). Always report all backend metrics. Increases cardinality
by O(routes), but prometheus is a lot faster now.

[release-3.11] Bug 1855852: Backport HAProxy report all backend metrics

---

cmd/openshift-tests/upgrade.go

This link broke in https://github.com/openshift/origin/commit/8ec84ded0375928c4d1ceecec21e6fddb718c501.
Kudos to @cgwalters for noticing.

Bug 1872038: openshift-tests: fix upgrade test suites reference to controlplane availability tests

---

test/extended/util/annotate/rules.go

Remove `ExpandCSIVolumes` rule, it does not match anything.

Bug 1861218: Tune storage tests for 4.6

---

go.mod
test/extended/images/imagestreamimport.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Adding tests for apiserver image stream import feature. These new tests validate if apiserver behavior is correct when importing from "insecure" and "blocked" registries.
Please don't merge this before merging https://github.com/openshift/openshift-apiserver/pull/111.

Bug 1871080: IR-21: Adding tests for image stream imports on blocked/insecure registries

---

test/extended/cli/mustgather.go

Adjust tests as must-gather will no longer collect audit logs by default (https://github.com/openshift/must-gather/pull/144).

Bug 1862426: gather the audit logs for oauth apiserver

---

test/extended/util/annotate/rules.go

The skip rule contains `[Driver: azure]`, however, the test results show `[Driver: azure-disk]`.

Bug 1723603: test: don't skip storage tests in Azure

---

vendor/k8s.io/kubernetes/pkg/scheduler/internal/cache/cache.go
vendor/k8s.io/kubernetes/pkg/scheduler/internal/cache/cache_test.go

Backporting https://github.com/kubernetes/kubernetes/pull/93355
To fix the missing Reason messages in the scheduler logs to tackle https://bugzilla.redhat.com/show_bug.cgi?id=1763662

Bug 1868314: UPSTREAM: 93355: Fix scheduler issue with nodetree additions

---

vendor/k8s.io/kubernetes/openshift-kube-apiserver/authentication/oauth/bootstrapauthenticator.go
vendor/k8s.io/kubernetes/openshift-kube-apiserver/authentication/oauth/tokenauthenticator.go
vendor/k8s.io/kubernetes/openshift-kube-apiserver/authentication/oauth/tokenauthenticator_test.go

Backport of https://github.com/openshift/kubernetes/pull/302 and https://github.com/openshift/kubernetes/pull/305.
This is a blocker to verify https://issues.redhat.com/browse/MSTR-1019 for 4.6.
Depends on openshift/console#6445 and openshift/oc#525.

Bug 1869220: UPSTREAM: <carry>: oauth: support sha256~ prefixed tokens

---

go.mod
go.sum
vendor/k8s.io/legacy-cloud-providers/vsphere/nodemanager.go
vendor/modules.txt

Refactor locks on registeredNodesLocks
All internal calls in these methods were already using atomic operations such as `addNode` or `GetNode`.
This lock instead was volume creation and destroying the ability to provision volume with `thin` SC.
Now the node map will be copied, and all group operations will be executed on a copy, leaving lock for others to use.
Cherry-pick https://github.com/kubernetes/kubernetes/pull/93971

BUG 1863009: vSphere provision failure on ocp46

---

test/extended/apiserver/graceful_termination.go
test/extended/util/annotate/generated/zz_generated.annotations.go

These are produced by kube-apiserver when
- non-localhost clients connect in the last 20% of the termination period. This is a strong hint that the LBs are misconfigured or misbehaving => LateConnections
- the kube-apiserver is not cleanly terminating, but e.g. is receiving a SIGKILL instead of an early SIGTERM => NonGracefulTermination

Bug 1873961: e2e/apiserver: check for LateConnections+NonGracefulTermination events

---

test/e2e/upgrade/service/service.go
test/e2e/upgrade/upgrade.go

Use  ExternalTrafficPolicy set to Local for the service used in the test
`[sig-network-edge] Application behind service load balancer with PDB is not disrupted ` 
This avoid that we do a double hop inside the cluster to reach the pod, since the traffic goes directly from the load balancer to the node that has the pod running.

Bug 1828858: use LoadBalancers with ExternalTrafficPolicy set to Local

---

test/extended/etcd/etcd_storage_path.go
test/extended/etcd/etcd_test_runner.go

Trying to diagnose bits like https://prow.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-ocp-installer-e2e-openstack-serial-4.6/1301127862794850304

bug 1875006: add logging for etcd test when we create new port forwards

---

test/extended/images/imagestreamimport.go
test/extended/util/annotate/generated/zz_generated.annotations.go

This test is currently disruptive because it doesn't wait for the cluster state to return to a set of stable operators (everything available, not progressing, not degraded) and the machine config operator to have finished rolling the change to every node. This causes instability in the tests that follow it that expect a stable clusters.  Examples include scheduling tests that require all workers schedulable with functional networking and storage tests which require long running connections on both apiservers and kubelets to exec into them. After meeting the standard for stability, this test is likely to be [Slow]
Found in https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-serial-4.6/1300627052105306112 specifically, but consistent with …

bug 1875592: move ISI test to disruptive since it leaves an unstable cluster

---

test/extended/csrapprover/csrapprover.go

This change replaces the architecture specific image spec with a spec
that support multi-arch downloads.

Bug 1868760: Drop quay.io/fedora/fedora:32-x86_64 in favor of docker.io/fedora:32

---

test/extended/builds/proxy.go

Update to RHEL 8 bumped git to v2.x. As a result, the "Failed to
connect" error message was altered.

Bug 1876913: Fix test to verify git proxies

---

test/extended/apiserver/root_403.go

The issue would be made part of release note. Skipping the test as it is expected to fail on clusters upgraded from 4.1.

Bug 1821771: For clusters upgraded from 4.1, skip the anonymous browser access test

---

test/extended/deployments/deployments.go
test/extended/deployments/util.go

This makes DC e2e more resilient to apiserver hickups or badly configured loadbalancer.
/cc @soltysh

Bug 1791739: Restart watches in DC e2e tests

---

test/extended/authorization/rbac/groups_default_rules.go

HelmChartRepository instances keep Helm chart repository configuration.
By default users are able to browse charts from all configured repositories through console
To unblock https://github.com/openshift/console-operator/pull/458/
cc @jhadvig @spadgett

Bug 1872375: Add system:authenticated exception for HelmChartRepository CRs used by console

---

test/extended/etcd/etcd_test_runner.go

Based on logs from https://prow.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-ocp-installer-e2e-openstack-serial-4.6/1303933478840045568 on the failing test, it looks like the grpc client itself is retrying on failures forever.  This stops that I think

bug 1877932: don't retry the GRPC connection in our tests

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/filters/impersonation_test.go
vendor/k8s.io/kubernetes/test/cmd/authorization.sh

Currently we add the `system:authenticated` group for any authenticated user (except when the user is `system:anonymous` or the user is in `system:unauthenticated` group). 
On the other hand, if a group is specified (via `--as-group`) for an impersonated user, we don't add `system:authenticated`. The impersonated user's information is stored in the request context and is used to serve the request.
This causes priority and fairness matching to fail if there are no `FlowSchema` rules explicitly permitting the specified group. The `catch-all` flow schema needs the user to be in either the 'system:authenticated' or the 'system:unauthenticated' group. An impersonated user with a specified group is in neither.
If there is no match, the request fails with a panic. Here is an example:
Potential …

Bug 1874251: UPSTREAM: 94204: Add impersonated user to system:authenticated group

---

images/hello-openshift/Dockerfile.rhel

hello-openshift is (in)famously used throughout openshift as both an example and test image, but it's never been built or shipped by ART and it isn't multi-arch. This is the first step to bring it into the release.

Bug 1766287: Add CI Dockerfile for hello-openshift

---

pkg/network/node/node.go
pkg/network/node/pod.go
pkg/network/node/pod_test.go

PR: https://github.com/openshift/origin/pull/23522 fixed syncing initial SDN state for hostport pods. There was however a mistake in that patch, namely: it overlooked that `existingSandboxPods` was a map of sandboxID -> PodSandbox and was retrieving the sandbox using the `podKey` (namespace/name). This lead to other initialization errors when the SDN restarts. This patch reverses the logic, and thus loops over the sandboxes and then retrieves the running pods.
I have not been able to build the images yet, as to test this on a live cluster where I've reproduced the problem. But logically this makes sense. 
/cc @aojea 
/assign @danwinship @squeed

Bug 1857824: Fix incorrect retrieval of sandbox pods and incorrect host port initialization

---

test/extended/apiserver/kubeconfigs.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Adding conformance test verifying kubeconfigs on masters are present and working.
Requires:
/cc @deads2k @sttts

Bug 1710766: Add e2e form kubeconfigs on masters

---

test/extended/operators/olm.go
test/extended/operators/qos.go
test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

This reverts https://github.com/openshift/origin/pull/25352
Apparently the operator used for testing (amq) removed their stable channel, which has since been restored.

Bug 1857928: Re-enable olm tests

---

test/extended/networking/internal_ports.go

Fixes #1874671 - helps fix the tests for the PR dropping the capabilities https://github.com/openshift/machine-config-operator/pull/2051
The "TCP and UDP on ports" test does a tcpdump which
requires the NET_RAW capability to be enabled.
We are dropping NET_RAW from the default list of
capabilities in cri-o, so need to explicitly add it
to the test here.
This is blocking https://github.com/openshift/machine-config-operator/pull/2051
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

Bug 1874671: Add NET_RAW capability to internal_ports test

---

test/extended/project/project.go

From what I have seen the test usually fails on observing a project deletion. It times out after the 30s.
I have never seen a project not being deleted. It just sometimes needs more time.
Given that we don't have an upper bound time after which the project should be deleted I decided to increase the timeout.

Bug 1848754: TestProjectWatch should succeed

---

cmd/openshift-tests/openshift-tests.go
cmd/openshift-tests/storagecaps.go

Following the discussion in [PR #25439](https://github.com/openshift/origin/pull/25439), we add storage capabilities report following the CSI certification tests:
```
$ podman run -v `pwd`:/data:z --rm -it $CONTAINER sh -c "KUBECONFIG=/data/kubeconfig.yaml TEST_CSI_DRIVER_FILES=/data/manifest.yaml /usr/bin/openshift-tests run openshift/csi --junit-dir /data/results"
openshift-tests version: v4.1.0-3107-g627d022
…
Writing JUnit report to /data/results/junit_e2e_20200907-091404.xml
32 pass, 146 skip (4m35s)
Storage Capabilities (guaranteed only on full CSI test suite with 0 fails)
==========================================================================
Driver short name:                  ceph-test
Driver name:                        test.rbd.csi.ceph.com
Storage class: …
```

Bug 1879907: Add storage capabilities report for CSI certification tests

---

test/e2e/upgrade/alert/alert.go

This reverts https://github.com/openshift/origin/pull/24786
https://github.com/kubernetes/kubernetes/pull/94614 was the root cause.

Bug 1878862: Revert "Ignore KubeAPIErrorBudgetBurn alert"

---

test/extended/testdata/bindata.go
test/extended/testdata/builds/custom-build/Dockerfile

At least until https://github.com/containers/buildah/issues/2002 is resolved.
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

Bug 1879554: Use multi-arch registry for buildah images

---

test/extended/operators/olm.go

OKD is defaulting to community-operators only, so the test should 
install operator from community sources. This change would make it pass on OCP and skip this test on OKD. Verified that this test gets skipped with current OKD configuration and runs on OCP.
Later, when community-operators source would contain amq-streams, I'll rework the test to use community source on OKD.
This should resolve [failing OKD promotions](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-okd-installer-e2e-aws-4.6/1306845773220024320)
TODO:

Bug 1879873: OLM 'can subscribe to the operator' test: skip if redhat-operators is not enabled

---

test/extended/cli/mustgather.go

/hold
for debugging azure, where it flaked most heavily

Bug 1861746: bring back must-gather audit e2e

---

cmd/openshift-tests/storagecaps.go

As commented by @jsafrane in [Bugzilla bug 1879907](https://bugzilla.redhat.com/show_bug.cgi?id=1879907), capabilities report mixes CSI and CNV features. This PR distinguishes between the two, e.g.:
```
Driver short name:                       ceph-test
Driver name:                             test.rbd.csi.ceph.com
Storage class:                           ceph-rbd-sc.yaml
Supported CSI features:
Data is persisted across pod restarts: true
Raw block mode:                        true
Volume ownership via fsGroup:          true
Exec a file in the volume:             true
Populate data from snapshot:           true
Populate data from PVC:                true
Use volume from multiple pods on node: true
ReadWriteMany access mode:             true
Volume expansion for controller:       true …
```

Bug 1879907: Distinguish CSI/CNV features in storage capabilities report

---

test/extended/apiserver/graceful_termination.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Counterpart to https://github.com/openshift/kubernetes/pull/356.

Bug 1880941: extended/apiserver: check for NonReadyRequests events for early traffic from LBs

---

test/e2e/upgrade/alert/alert.go
test/e2e/upgrade/monitor.go
test/extended/prometheus/prometheus.go
test/extended/prometheus/prometheus_builds.go
test/extended/router/metrics.go
test/extended/util/pods.go

There is no centos for s390x architecture, so instead use an image that's guaranteed to be multiarch.
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

Bug 1847363: test: use ubi instead of centos

---

test/extended/operators/olm.go

until we have a good multi-arch operator available for test, skip the check that waits for an operator to succeed.

Bug 1881060: don't wait for an OLM operator to succeed on non-amd64

---

test/extended/apiserver/root_403.go

This is a cherry-pick for #25510

[release-4.4] Bug 1880123: For clusters upgraded from 4.1, skip the anonymous browser access test

---

test/extended/machines/scale.go

This test suite is currently checking for labels
and taints on nodes created by the machine-api.
Other components are adding taints to existing workers
which are sometimes selected to scale down during
testing.  This test does not allow for any modification
of labels and taints.
The machine-api is not the sole or final manager of
labels and taints.  We have coverage in our own
test suite that the machine-api adds labels
and taints appropriately, this test is unnecessary
here and does not add cross-component signaling.

Bug 1880741: Remove broken machine-api taint test

---

vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/cpu_manager_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/policy_static.go
vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/policy_static_test.go

ref: kubernetes/kubernetes#90419
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

[release-4.5] Bug 1846451: UPSTREAM: 90419: update strategy used to reuse CPUs from init containers in CPUManager

---

test/extended/authorization/scc.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Found an instance of this that failed an azure install.  This check will run early and see if we're getting large numbers of denials that aren't failing us.

add a test to check for SCC denials during install

---

pkg/test/ginkgo/cmd_runsuite.go
pkg/test/ginkgo/synthentic_tests.go

moves synthetic test creation to a separate spot so that we can add some special handling without muddying the main flow.

bug 1884034: refactor synthetic test creation from monitor

---

pkg/test/ginkgo/cmd_runsuite.go
pkg/test/ginkgo/synthentic_tests.go

pods should never transition back to pending. "invariant violation (bug): pod should not transition Running->Pending even when terminated"
This appears to be frequent https://search.ci.openshift.org/?search=pod+should+not+transition+Running-%3EPending+even+when+terminated&maxAge=48h&context=1&type=build-log&name=4.6&maxMatches=5&maxBytes=20971520&groupBy=job so we'll add a specific failure signal that we can chase.

bug 1884034: add junit for illegal pod state transitions

---

pkg/test/ginkgo/synthentic_tests.go

CI search is showing lots of failures on pod sandbox creation. This attempts to categorize the types and gather frequency information.
See https://search.ci.openshift.org/?search=FailedCreatePodSandBox&maxAge=48h&context=1&type=build-log&name=4.6&maxMatches=5&maxBytes=20971520&groupBy=job

bug 1884245: add test for failing network sandbox creation

---

test/extended/marketplace/marketplace_labels.go

Increase from 60s to 2 mins due to recent increase in initial delay
in the catalog pod.
Signed-off-by: Vu Dinh <vdinh@redhat.com>

Bug 1883235: Adjust wait duration for marketplace test

---

pkg/network/apis/network/types.go

Backport of https://github.com/openshift/cluster-network-operator/pull/796, for https://issues.redhat.com/browse/SDN-1199

Bug 1881529: openshift-sdn: bump EgressNetworkPolicyMaxRules to 1000

---

test/e2e/upgrade/service/service.go

Upgrade tests are programmatically added.  This introduces a very simple programmatic skip at the time when the test runs.
If we find that we have many of these, we can write a filter, but such a filter will require a client.

skip service type load balancer upgrade test on ovirt

---

examples/hello-openshift/OWNERS
images/hello-openshift/OWNERS

`images/hello-openshift/OWNERS`: Add initial owners for the `hello-openshift` art dockerfile. This owners file is a copy-paste of the current `examples/hello-openshift/OWNERS` file (with the addition of myself). 
`examples/hello-openshift/OWNERS`: Add myself to the `hello-openshift` code maintainers OWNERS file.
/cc @wking @yselkowitz

Update hello-openshift OWNERS files

---

test/e2e/upgrade/service/service.go

cherry-pick from https://github.com/openshift/origin/pull/25406
Use ExternalTrafficPolicy set to Local for the service used in the test
[sig-network-edge] Application behind service load balancer with PDB is not disrupted
This avoid that we do a double hop inside the cluster to reach the pod, since the traffic goes directly from the load balancer to the node that has the pod running.
Signed-off-by: Antonio Ojea <aojea@redhat.com>

Bug 1868490: upgrade test use LoadBalancers with ExternalTrafficPolicy set to Local

---

test/extended/prometheus/prometheus.go
test/extended/util/annotate/generated/zz_generated.annotations.go

This is necessary to ensure there are data to send in prometheus and avoid possible test race when telemeter is started before prometheus pods are available.
/cc @openshift/openshift-team-monitoring

Bug 1855325: Move checking telemetry data sending to later stages

---

test/extended/authorization/rbac/groups_default_rules.go
test/extended/cli/mustgather.go
test/extended/oauth/expiration.go
test/extended/prometheus/prometheus.go
vendor/k8s.io/kubernetes/test/e2e/apps/disruption.go

bug 1886174: skip test during skew testing that won't run on 4.6

---

test/extended/prometheus/prometheus.go

We recently increased the series published to telemetry by about
100 (to include resource counts for all CRDs). Bump the allowed
test limits similarly to 600.
Consequence of openshift/cluster-monitoring-operator#951

test: Increase allowed telemetry series by 100

---

test/extended/security/fips.go
test/extended/topology_manager/utils.go
test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/pods.go

See discussion in
https://github.com/openshift/release/pull/10488
and https://bugzilla.redhat.com/show_bug.cgi?id=1861095
This test replaces the bash code in the release repo
with a more proper test here.
While here I noticed that the topology tests had some code
that reused the MCD as a handy privileged pod; extract
that to the toplevel utils and use both here and there.

Add a new FIPS test

---

examples/hello-openshift/hello_openshift.go

Set the "request-port" header on hello-openshift HTTP responses so that clients reaching the hello-openshift application know which port the HTTP listener was accessed on. This will be useful for the Ingress Operator fault detection work. See https://github.com/openshift/enhancements/pull/438 and https://issues.redhat.com/browse/NE-199 for additional context.

hello-openshift: Echo listening port in HTTP responses via headers

---

test/extended/security/scc.go
test/extended/util/annotate/generated/zz_generated.annotations.go

This will test the restricted scc is really restricted,
including only
0x000000000000051b=cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_setpcap,cap_net_bind_service
Signed-off-by: Yuval Kashtan <yuvalkashtan@gmail.com>

add a security test to verify capabilities

---

test/extended/OWNERS

As pillar lead for MCO/CoreOS - we will likely do more
tests here and so should have an approver.

tests/extended/OWNERS: add ashcrow to approvers

---

pkg/test/ginkgo/synthentic_tests.go

Now that we fixed terminating pods transitioning and we suspect that the UIDs will be different on static pods now, we can tighten this test to actually fail.  We occasionally see failures, but if we see failures on running, non-static pods those are relatively severe problems to chase.

fail on pods moving back to pending in 4.7 and later

---

pkg/test/ginkgo/synthentic_tests.go

1. if pod sandbox creation fails before deletion, fail.
2. if pod sandbox creation fails within one second of deletion, allow grace.
3. if pod sandbox creation fails within five seconds of deletion, flake
4. if pod sandbox creation fails more than five seconds after deletion, fail.

handle cases where pod sandboxes fail after pod deletion

---

test/extended/authorization/scc.go
test/extended/security/fips.go
test/extended/util/client.go

This will help prevent regressions.

tighten scc test to start failing on more than six pods failing

---

vendor/k8s.io/kubernetes/pkg/printers/internalversion/printers.go

Backport of https://github.com/kubernetes/kubernetes/pull/94252

bug 1857268: UPSTREAM: 94252: If firstTimestamp is not set use eventTime when printing event

---

test/extended/networking/util.go

Our attempt to determine the plugin mode was generating
pluginName="Flag --config has been deprecated, use --kubeconfig instead\nredhat/openshift-ovs-networkpolicy"
resulting in us never running the openshift-sdn-specific tests

Fix skipping of SDN tests

---

pkg/build/builder/docker_test.go
pkg/build/builder/sti_test.go
test/extended/builds/pipeline.go
test/extended/builds/secrets.go
test/extended/builds/start.go
test/extended/testdata/bindata.go
test/extended/testdata/builds/statusfail-postcommithook.yaml
test/extended/testdata/builds/statusfail-pushtoregistry.yaml
test/extended/testdata/builds/test-build-app/Dockerfile

- unit: Skip or alter pkg/build/builder unit tests which require
access to a Docker socket. This is not available in OCP 4 pods.
- extended: Update tests to use ruby 2.5 instead of 2.3
- extended: Manually pick 847153a73442ee91f6879d7d7f7644bf340700f4
to fix the message we verify the successful build against.
- extended: skipping s2i secrets test. CI is running an outdated
version of docker, which contains a bug impacting symlinks that
exist within a container [1].
- extended: skip Binary build test that fails with corrupted gem
[2].
- extended: skip Jenkins pipeline test that fails to clean itself
up [3].
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1890328
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1890507
[3] https://bugzilla.redhat.com/show_bug.cgi?id=1890523

[release-3.11] Bug 1889868: Clean up 3.11.z build tests

---

test/extended/authorization/scc.go

This will provide a clear signal on regression and prevent unnecessary noise.
Because the CVO starts as a static pod, concurrent with the cluster-policy-controller, there is a time period when namespaces can be created and content placed in them by the CVO before the controller assigning SCC UIDs has had a chance to actually create the range allocations.  Below a certain threshold (I chose five), this is acceptable.  We were dealing with dozens in the past.

Bug 1887850: update SCC test to either pass or fail, but never flake

---

test/e2e/upgrade/service/service.go

The test "Application behind service load balancer with PDB is not disrupted" basically does the following:
- Creates an app using PDB with 2 pods exposing an app that echoes the request
- Exposes the app using a Service Type LoadBalancer (using externalTrafficPolicy=Local)
- Monitors the application during the upgrade performing GET request to the exposed endpoint and checking that the answer is correct.
To monitor the application there are 2 "threads":
- one that reuses the TCP connection to perform the checks
- other that creates a new TCP connection every time
Previously the test was using the Service with `externalTrafficPolicy=Cluster`, that means that the Cloud Provider LB can forward the traffic to any node, and it is possible that it has to do double hops and NAT inside the …

Bug 1886620: deflake e2e test "Application behind service load balancer with PDB is not disrupted "

---

cmd/openshift-tests/upgrade.go
pkg/monitor/api.go
test/e2e/upgrade/upgrade.go
test/extended/dr/machine_recover.go
test/extended/util/disruption/controlplane/controlplane.go

Uptime for apiservers can look different between new connections and existing connections.  This adds checks for new connections and runs both sets of tests so we can start to see which fail when.

check apiserver uptime with both new and re-used connections

---

test/extended/image_ecosystem/s2i_php.go
test/extended/image_ecosystem/sample_repos.go
test/extended/util/annotate/generated/zz_generated.annotations.go

/hold
for now ... tracking upstream efforts into resolving this ... if too far out, will pull the trigger here

disable cakephp while cuppett/scl sort out new upstream regression

---

vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go

/hold
(for QA pretesting it, wasn't clean)
/cc-qa
/cc @soltysh @deads2k

[release-4.5] Bug 1881351: KCM and KS graceful termination

---

examples/sample-app/github-webhook-example.json
test/extended/builds/clone_git_protocol.go
test/extended/builds/controllers.go
test/extended/images/imagechange_buildtrigger.go
test/extended/testdata/bindata.go
test/extended/testdata/builds/test-build-revision.json
test/extended/testdata/builds/test-build.yaml
test/extended/testdata/builds/webhook/generic/testdata/push-generic-envs.json
test/extended/testdata/builds/webhook/generic/testdata/push-generic-envs.yaml
test/extended/testdata/builds/webhook/generic/testdata/push-generic.json
test/extended/testdata/builds/webhook/github/testdata/pushevent-not-master-branch.json
test/extended/testdata/builds/webhook/github/testdata/pushevent.json
test/extended/testdata/cmd/test/cmd/env.sh
test/extended/testdata/cmd/test/cmd/testdata/test-bc.yaml
test/extended/testdata/cmd/test/cmd/testdata/test-buildcli.json
test/extended/testdata/long_names/fixture.json
test/extended/testdata/run_policy/parallel-bc.yaml
test/extended/testdata/run_policy/serial-bc.yaml
test/extended/testdata/run_policy/serial-latest-only-bc.yaml
test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/proxy.go
test/integration/testdata/test-buildcli-beta2.json
test/integration/testdata/test-buildcli.json

Replace git:// urls with https:// urls for all tests

Bug 1882556: Access git over https for tests

---

test/extended/quota/resourcequota.go
test/extended/util/annotate/generated/zz_generated.annotations.go

For backward compatibility we need to maintain `openshift.io/imagestreams` alias for `count/imagestreams.image.openshift.io`. This pr adds an e2e test for counting `imagestreams` resources.

an e2e for testing "openshift.io/imagestreams" count quota 

---

test/e2e/upgrade/alert/alert.go
test/extended/prometheus/prometheus.go
test/extended/prometheus/prometheus_builds.go
test/extended/prometheus/storage.go
test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/prometheus/helpers.go

At the end of e2e test, grab storage operation metrics and check that attach and mount times are under expected limits.
To get there, refactor `RunQueries` to return error instead of failing the test, so storage metric checks can declare themselves as test flakes instead of failures.

Evaluate storage metrics of an e2e test.

---

pkg/monitor/api.go
pkg/monitor/sampler.go
pkg/test/ginkgo/synthentic_tests.go
test/extended/util/disruption/disruption.go

Currently, API server availabilities are tracked under `[sig-arch] Monitor cluster while tests execute`. Create a separate test for them when the API servers are unreachable more than 1% of the test time.
In addition:
* Print status of synthetic tests to stdout for better debug-ability of these test.
* Change monitor interval to 1s to be able to detect outages shorter than 15s.
~WIP: the third commit actually injects some fake errors to see how it works in prow.~

Report API server unavailability in e2e tests

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

We skipped the network tests and thracked the fix on BZ#1838751
The fix is in, so now we can enable them again
ran ./hack/update-generated.sh to generate new tests
Signed-off-by: Gal-Zaidman <gzaidman@redhat.com>

Bug 1838751: oVirt, enable Skipped network tests

---

images/router/haproxy/Dockerfile.art

PR #25542 introduced a change that allows us to pickup a specific
version of HAProxy during a CI build. Unfortunately this broke ART
builds as there is no external network access that would allow access
to the RPM files.
This commit reflects the state of the Dockerfile as it was before
25542 merged.
There is a complementary commit for ocp-build-data:
https://github.com/openshift/ocp-build-data/pull/736
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1894011

Bug 1894011: images/router: Add ART specific Dockerfile

---

vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_gc.go
vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/legacy.go

Cherry-pick of https://github.com/openshift/origin/pull/24926
addressing: https://bugzilla.redhat.com/show_bug.cgi?id=1823406#c15
As the discussion over #52172 showed, there is race condition between the container log rotation and the kubelet GC which may result in the loss of symlink.
Here is how container log rotation works (see containerLogManager#rotateLatestLog):
rename current log to rotated log file whose filename contains current timestamp (fmt.Sprintf("%s.%s", log, timestamp))
reopen the container log
if #2 fails, rename rotated log file back to container log
There is small but indeterministic amount of time during which log file doesn't exist (between steps #1 and #2, between #1 and #3). Hence the symlink may be deemed unhealthy during that period.
This PR resorts to …

Bug 1872726: [3.11] Upstream: 89160: Remove potentially unhealthy symlink only for dead containers

---

vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_gc.go
vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/legacy.go
vendor/k8s.io/kubernetes/pkg/kubelet/remote/remote_runtime.go

Remove potentially unhealthy symlink only for dead containers
Signed-off-by: Ted Yu <zyu@redhat.com>
Signed-off-by: Skyler Clark <wgahnagl@protonmail.com>
backport of Bug 1823406 
PR https://github.com/openshift/origin/pull/24926

Bug 1878795: UPSTREAM: 89160 Only Remove unhealthy symlink for dead containers

---

test/extended/builds/start.go
test/extended/testdata/bindata.go
test/extended/testdata/builds/test-build.yaml

should address build-args error in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/24887/pull-ci-openshift-origin-master-e2e-gcp-builds/1324783058666131456
see the discussion starting with https://coreos.slack.com/archives/C014MHHKUSF/p1604958101444400?thread_ts=1604938369.426700&cid=C014MHHKUSF
@adambkaplan fyi

rename 'foo' build arg to avoid conflicts with 'foo' env's in the tools image

---

test/extended/images/imagestreamimport.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Changes on image config triggers other operators rollout, in order to
play nice with subsequent tests we have to wait until their rollout
process is finished.
For reference, this is an attempt to fix issues reported on https://github.com/openshift/origin/pull/25475/

IR-137: Awaiting for operators rollout to complete

---

pkg/router/metrics/haproxy/haproxy.go
pkg/router/metrics/haproxy/haproxy_test.go

This PR is the 3.11 backport of https://github.com/openshift/router/pull/179
---
The HAProxy router [reload process calls](https://github.com/openshift/router/blob/master/pkg/cmd/infra/router/template.go#L539) `CollectNow()` in `pkg/router/metrics/haproxy/haproxy.go`. Currently, `CollectNow()` _does not_ update `e.lastScrape`, which means it is possible for the normal scrape function `Collect(...)` to be called _just after_ `CollectNow()`, but before HAProxy has actually reloaded, since `CollectNow()` essentially "resets" the metrics scrape interval.
The idea in this PR is to have `CollectNow()` set the `e.lastScrape` time, since `CollectNow()` is calling `scrape()` anyways. This will prevent counter metrics from decreasing across reloads since metrics are only saved for reload …

[release-3.11] Bug 1890545: Backport Fix decreasing metric counters when reloading HAProxy

---

test/extended/images/extract.go

Successful creation of ImageStreamImport doesn't mean that images are imported successfully. Status of the returned object should be checked as it may contain errors from the registry.

Bug 1895537: Image extract tests should check results of ImageStreamImport

---

images/hello-openshift/OWNERS

The Network Edge team maintains the hello-openshift image. Add the routing component to `images/hello-openshift/OWNERS` to satisfy the ART BZ component requirement.

hello-openshift: Set BZ component in OWNERS

---

test/extended/apiserver/apply.go
test/extended/etcd/etcd_storage_path.go
test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/client.go

TODO
- These groups are served by oauth-apiserver
/cc @sttts @stlaz @p0lyn0mial

Add e2e testing of server-side apply for openshift types 

---

test/extended/images/mirror.go

Fixes the problem that was found at https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/24887/pull-ci-openshift-origin-master-e2e-aws-image-registry/1324783058502553600

Make oc mirror tests aware of HTTP/2

---

test/e2e/upgrade/service/service.go

instead of using client-go to do the GET probes against the PDB service,
we use directly the net/http package to avoid dependencies and unneeded
overhead.
Signed-off-by: Antonio Ojea <aojea@redhat.com>
cherry-pick of #25606
/assign aojea

[release-4.5] Bug 1828858: use net/http instead of client-go for e2e PDB test

---

test/e2e/upgrade/upgrade.go
test/extended/util/disruption/imageregistry/imageregistry.go

We expect the registry to be always available during upgrades. This test should help us to ensure this.

IR-152: Monitor availability of image registry during upgrades

---

examples/hello-openshift/hello_openshift.go

Change hello-openshift's `request-port` response header to `x-request-port` to be strictly standards compliant.

hello-openshift: Make request-port header spec compliant

---

test/extended/images/imagestreamimport.go

This patch increases the number of logged information during the
following tests:
ImageStream API TestImportRepositoryFromBlockedRegistry
ImageStream API TestImportImageFromBlockedRegistry
ImageStream API TestImportImageFromInsecureRegistry
ImageStream API TestImportRepositoryFromInsecureRegistry
Tests now log the deployment status. Time between polls was also
increased, no need to rush when checking for the deployment status.
Timeout for endpoints to become available were also increased, from one
to five minutes, logging was also increased during endpoints check.

Bug 1898118: Logging more during ephemeral registry deployment

---

test/extended/topology_manager/resourcealign.go
test/extended/topology_manager/utils.go
test/extended/util/pods.go

The topology manager e2e tests expect MCD running
in order to be able to extract the node Kubelet and
check the test precoditions.
So we add another pre-filter to rule out worker nodes
without MCD running. If no suitable worker nodes are
found, the tests must just skip.
Bug-Url: https://bugzilla.redhat.com/1887509
Signed-off-by: Francesco Romani <fromani@redhat.com>

Bug 1887509: e2e: node: filter out worker nodes without MCD

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_instances.go

When we want to read an instance ID from the metadata service, cloud provider doesn't include "/" prefix, which is required for successful parsing of provider the ID later.
This commit adds the missing "/" prefix to the output.
Cherry-picked from https://github.com/openshift/kubernetes/pull/343

UPSTREAM: <carry>: Bug 1893156: include / prefix in instance ID output

---

test/extended/etcd/etcd_storage_path.go

Required by https://github.com/openshift/kubernetes/pull/471
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/471/pull-ci-openshift-kubernetes-master-e2e-aws-serial/1332340775815483392
/cc @sttts

Update etcd data locations for kube 1.20.0-beta.2

---

test/extended/topology_manager/README.md
test/extended/topology_manager/resourcealign.go
test/extended/topology_manager/utils.go

Pin the busybox image setting a known-good tag.
It was not done previously because of an oversight, no other reason.
Generalize the code which creates the testing pod to make the
code more flexible and a bit easier to read.
Last, use privileged pods for ping tests. This is needed because of the busybox images used
by the pinger pods.
Another approach could be to change base image (e.g. using centos images) but considering
the nature of the test and the fact that the busybox image is tiny, and much smaller than the closest
good alternative (centos), this approach seems good enough.
Bug-Url: https://bugzilla.redhat.com/1887488
Signed-off-by: Francesco Romani <fromani@redhat.com>

Bug 1887488: e2e: node: fix ping tester pod

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

Namely:
- `[sig-apps] ReplicationController should serve a basic image on each replica with a private image`
- `[sig-apps] ReplicaSet should serve a basic image on each replica with a private image`
See https://github.com/kubernetes/kubernetes/issues/97002
BZ reminding us to re-enable the tests again: https://bugzilla.redhat.com/show_bug.cgi?id=1903674

Temporary disable tests broken upstream

---

examples/pruner/README.md
examples/sample-app/README.md
hack/lib/cleanup.sh
hack/lib/start.sh
test/extended/cmd.sh
test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/login.sh

oc --config option is getting removed in 4.7

Replace oc --config with oc --kubeconfig

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

> When trying to upload an unexisting file to a pod, kubectl currently doesn't print any error message and terminates with a zero exit code.
https://github.com/kubernetes/kubernetes/pull/90333
With https://github.com/openshift/oc/pull/648 where the new check is coming in, the test starts to fail since `test/extended/authentication/ldap` does not exist.
Skipping the test for now. Opening https://bugzilla.redhat.com/show_bug.cgi?id=1902702 to address the broken parts.

[sig-auth][Feature:LDAP][Serial] ldap group sync can sync groups from ldap: do not oc cp nonexisting folders

---

test/extended/operators/tolerations.go

To resolve a bug that makes it possible to delete 2 masters simultaneously if kubelet unreachable we removed timeouts for NoExecute and NoSchedule tolerations[1]. But because `etcd-quorum-guard` is not whitelisted the net result is a test failure[2].
```
fail [github.com/openshift/origin/test/extended/operators/tolerations.go:72]: Nov 19 13:12:12.123: 
6 pods found with invalid tolerations:
openshift-machine-config-operator/etcd-quorum-guard-9779b9595-4tz7t tolerates node.kubernetes.io/not-ready with no tolerationSeconds
openshift-machine-config-operator/etcd-quorum-guard-9779b9595-4tz7t tolerates node.kubernetes.io/unreachable with no tolerationSeconds
openshift-machine-config-operator/etcd-quorum-guard-9779b9595-jpj49 tolerates node.kubernetes.io/not-ready with no tolerationSeconds …
```

Bug 1884195: test/extended/operators: add etcd-quorum-guard to unevictable whitelist

---

test/extended/quota/clusterquota.go
test/extended/util/wait.go

kube 1.20 brings in default configmap `kube-root-ca.crt` that is created in every namespace so we need to conditionaly adjust the CM counts.
/cc @sttts

Fix cluster quota test to tolerate a new default config map in every namespace

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/quota.sh

Tolerate 1.20 error message in test-cmd

---

test/e2e/upgrade/monitor.go

```
github.com/onsi/ginkgo@v4.5.0-origin.1+incompatible/internal/codelocation/code_location.go:19 +0x78
github.com/onsi/ginkgo.GinkgoRecover()
github.com/onsi/ginkgo@v4.5.0-origin.1+incompatible/ginkgo_dsl.go:278 +0x66
panic(0x4fa8540, 0x8c5a1a0)
runtime/panic.go:969 +0x175
github.com/openshift/origin/test/e2e/upgrade.(*versionMonitor).Describe(0xc001914480, 0xc00145af20)
github.com/openshift/origin/test/e2e/upgrade/monitor.go:164 +0x702
github.com/openshift/origin/test/e2e/upgrade.clusterUpgrade(0xc00145af20, 0x647cb20, 0xc001fdcf60, 0x644f820, 0xc0020e4000, 0xc00099c480, 0x0, 0x0, 0x0, 0x0, ...)
github.com/openshift/origin/test/e2e/upgrade/upgrade.go:330 +0x76c
github.com/openshift/origin/test/e2e/upgrade.glob..func1.1.1()
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/ …

Fix panic dereferencing nil

---

vendor/k8s.io/kubernetes/pkg/volume/fc/attacher.go
vendor/k8s.io/kubernetes/pkg/volume/fc/fc.go
vendor/k8s.io/kubernetes/pkg/volume/fc/fc_test.go
vendor/k8s.io/kubernetes/pkg/volume/fc/fc_util.go

FibreChannel volume plugin misses one important step when removing a device: "multipath -f". It flushes all multipath buffers to its individual paths. Without it, a filesystem on the device may get corrupted.
~~/hold~~
* The PR is not upstream yet, see https://github.com/kubernetes/kubernetes/pull/97013
* We may need to merge it even before though, upstream is frozen...
* ~I need to test it.~ Testsed with iSCSI instead of FC.

Bug 1903524: [3.11] UPSTREAM: 97013: Fix FibreChannel volume plugin corrupting filesystem on detach

---

vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go

We have a race condition because the `proxier.changesPending` which
was introduced in 0c9e44a08d12c115c72900af6c7513a7d178ea2b is not
locked properly. So most of the times in half of the SDN pods, the
REJECT rule gets created for not finding an endpoint and it does
not get replaced by the correct rules because the `SyncProxyRules`
does not get run because the value of `proxier.changesPending` is racy.
As a consequence of this, until there is a next update that sets
the value of `proxier.changesPending` correctly, the service rejects
requests from users. This patch uses the `proxier.mu.Lock()` on
`proxier.changesPending` when its changed from `Sync()`.
`OnEndpointsUpdate` and `OnServiceUpdate` then in turn call `Sync()`.

Bug 1881319: IPtable rules are racy when pod is created before svc

---

images/node/system-container/config.json.template

Because the atomic-openshift-node container running on RHEL Atomic Host bind mounts `/var/lib/docker/containers` instead of `/var/lib/docker`, the Kubelet gets the wrong disk usage stats when it looks at how much of the `/var/lib/docker` is in use. This results in dangling and unused images never being cleaned up when the ImageFS (i.e. the host's `/var/lib/docker`) fills up, since the Kubelet never triggers its garbage collection.

Bug 1870050: Mount ImageFS in node container

---

cmd/openshift-tests/provider.go
test/e2e/upgrade/service/service.go
test/extended/util/kubevirt/provider.go

Our main goal is creating a tenant cluster on top of existing OpenShift/Kubernetes cluster by creating virtualMachines (using kubevirt) for every node in the tenant cluster (masters and also workers nodes)
You can find more information here: openshift/enhancements#417

add kubevirt as a provide to openshift tests

---

test/e2e/upgrade/upgrade.go

The upgrade test currently just waits for the MCPs to complete their rollout before immediately checking if all ClusterOperators are available and not degraded.  This is causing quite a few false failures in CI, `authentication` and `openshift-apiserver` in particular.
Example job
https://prow.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade-4.7/1336793136516567040
The PR checks the ClusterOperators every 10s for up to 5m to see if they have settled after the MCP rollout.  If they don't settle within 5m, the test fails.
@deads2k @fabianvf

allow operators to settle after MCPs are done upgrading

---

test/extended/builds/pipeline_jenkins_e2e.go
test/extended/builds/pipeline_origin_bld.go
test/extended/builds/pipeline_origin_bld_rhelimagesonly.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Bug 1906588:  normalize ginkgo structuring so we avoid timing windows with k8s e2e setup when changing user

---

vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity.go
vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity_test.go

This follows up to https://github.com/openshift/origin/pull/25350, which added these checks but only if there were no other pods on the node (making the assumption that these would be checked already if there are other pods on the node). This removes that check

[release-3.11] Bug 1760807: Update pod affinity check in priority for valid labels

---

test/extended/etcd/etcd_storage_path.go

We will have to keep v1alpha1 storage version for flowcontrol resources in order to not break downgrade (1.19 kube-apiserver won't be able to read v1beta1 objects).

extended-tests: kube-apiserver: switch flowcontrol storage to alpha

---

test/extended/builds/remove_buildconfig.go

Kube 1.20.0 introduces a default configmap in every namespace so >0 won't ever be true there.
This blocks rebase PR https://github.com/openshift/kubernetes/pull/471
/cc @sttts @adambkaplan

Bug 1907373: Fix build test CM count

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

The following tests fail consistently after the merge of the 1.20 rebase, and this is blocking testing and merge of most repos. Rather than wait for the [1.20 origin bump](https://github.com/openshift/origin/pull/25765) to fix these tests, skip and unblock everyone.
/cc @mfojtik @sttts @tnozicka @soltysh

Skip table tests broken by 1.20 rebase

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

Reverts openshift/origin#25732
/hold

bug 1903674: Revert "Temporary disable tests broken upstream"

---

test/extended/util/image/OWNERS
test/extended/util/image/README.md

Document the review criteria as part of accepting rebase.

test: Update images README and add OWNERS

---

test/extended/builds/s2i_root.go
test/extended/util/image/image.go
test/extended/util/image/zz_generated.txt

hey - one of the docker.io refs used in build e2e's was not handled with your change from last week
please see https://github.com/openshift/origin/blob/master/test/extended/builds/s2i_root.go#L114
as a rule, official s2i builders do not run with root uid, so we don't have any officially s2i builder images to use instead in order to validate that such builders are not allowed
Also, in talking to @bparees this guy is so old, we are not sure which repo/Dockerfile manages this one  ... it might have been manually created and pushed to docker.io ... so perhaps we need to do work along those lines to recreate all that ... either that, or pull docker.io/... and push to quay.io/....
Lastly, and related, I had trouble finding example in openshift/release in order to …

Bug 1904683: add build s2i as root uid image for associated tests

---

test/extended/oauth/expiration.go

The skip function must run inside of the correct ginkgo blocks,
otherwise it panics during code init and the test process exits
without running any tests.
I.e. skew tests are not running at all due to this panic:
```
Dec 13 19:44:59.825: INFO: Test is disabled to allow cluster components to have different versions, and skewed versions have different oauth token rules
panic: Your test failed.
...
github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/skipper.skip.func1(0xc0003bdd00, 0x7d, 0x997c048, 0x76, 0x29, 0xc000c8e240, 0x239)
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/skipper/skipper.go:81 +0xa1
panic(0x4b6e9a0, 0x6501de0) …
```

Bug 1908764: Skew 4.5 to 4.6 tests are failing due to a misplaced skip (prevents all tests from running)

---

test/extended/etcd/etcd_storage_path.go

End to end tests should have correctly formatted hostname, see https://github.com/openshift/router/pull/238/

Bug 1896977: Match e2e test to new enhanced host name validation

---

glide.lock
glide.yaml
vendor/github.com/openshift/library-go/go.mod
vendor/github.com/openshift/library-go/pkg/config/client/client_config.go
vendor/github.com/openshift/library-go/pkg/network/dialer.go
vendor/github.com/openshift/library-go/pkg/network/dialer_linux.go
vendor/github.com/openshift/library-go/pkg/network/dialer_others.go
vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go
vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller_test.go
vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go
vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go
vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller_test.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/manifests/installer-pod.yaml
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/bindata/bindata.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/manifests/pruner-pod.yaml
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go
vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller_test.go
vendor/github.com/openshift/library-go/test/library/encryption/e_log.go
vendor/github.com/openshift/library-go/test/library/encryption/perf_helpers.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/cache.go

we will carry a patch that allows the clients (Kubelet, KCM, etc.) to detect broken connections to the api server more quickly than the default TCP timeout of 15 minutes.
Note: this patch will be dropped in future releases once http2/ping is introduced.

Bug 1907938: Nodes goes into NotReady state (VMware)

---

test/extended/prometheus/prometheus.go

With the recent increase in cluster metrics, some disruptive tests
can trigger errors that result in a burst of
cluster_operator_conditions or alerts series that then clear after
the disruption. We want to run the full suite after we run a
disruption, and in general we are concerned with average over max,
so shorten the interval we check to 1h and calculate the average.
When looking at telemetry from 4.7 CI clusters, the disruptive tests
BRIEFLY peak at 600 series and then fall to 300 almost immediately
after.  Using the average, the total count is closer to 400 over the
hour the tests run and that better represents the desired goal of
the test (to limit average load, not spikes). Check the maximum as
double the average.
Resolves failures encountered when attempting to run the disruptive …

test: Assess average series rather than max over the test window

---

test/e2e/upgrade/alert/alert.go
test/extended/apiserver/graceful_termination.go
test/extended/prometheus/prometheus.go
test/extended/prometheus/storage.go
test/extended/util/conditions.go
test/extended/util/prometheus/helpers.go

A number of cluster invariants check without time boundaries - for 
instance, kube-apiserver hasn't failed to gracefully restart from all
events stored in the api, or prometheus not reporting any alerts since the
start of the test. However, when these tests run after induced disruption
(like recovering a master or a restored cluster) the test would then fail
because it sees the disruption. The current behavior is useful for
assessing install, but can't scale to disruption events.
Instead of tests hardcoding arbitrary intervals, standardize the lookback
window into a pair of utility functions, one for the complete valid range,
and one for a more limited "look back a reasonable period of time". Allow
the test invoker to pass an environment variable …

test: Allow tests that check invariants over time to be constrained

---

test/extended/apiserver/apply.go

When the oauthclientauthorization is created, it checks the SA from
its clientName for tokens and fails if there are none.
The server-side apply test creates an SA but does not wait for it to
be populated with tokens which may cause the test to fail when
it gets to creating the oauthauthorization object too early.
/assign @marun

Bug 1908217: server-side apply e2e: fix oauthclientauthorization race with KCM

---

test/extended/images/trigger/annotation.go

Centos is not compatible with s390x, resulting in observed flakeyness when this is run on s390x.

Bug 1914343: Replacing centos with ubi in image-annotation test.

---

test/extended/image_ecosystem/scl.go

in Adam's absence
@pedjak @jasperchui FYI per our discussion today I got a couple of cycles so I went ahead and threw this up
So the SCL folks recently tweaked the s2i usage message for 2 of their images such that it no longer passes in the test referenced by the associated bugzilla.
That said, at least in my opinion, their usage messages seem good enough to me.  I've pasted them in the associated bugzilla.
So, what to do:
- for now, this PR broadens the acceptance criteria for the images; we could review and iterate and go with some form of this for the test
- during my discussion with @pedjak he brought up a point I'm sure has come up with us before @bparees .... string verifications like this are fragile;  agreed - but conversely, I think making sure they have some …

Bug 1916419: broaden acceptance of scl sample s2i image usage messages

---

pkg/test/ginkgo/cmd_runsuite.go
test/extended/prometheus/prometheus.go
test/extended/util/conditions.go

Some pre-test conditions like upgrade or disruption could result
in rule evaluation failures, so we should check only over the
relevant interval.
Found while testing 4.6->4.7 full e2e upgrades in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/14666/rehearse-14666-release-openshift-origin-installer-e2e-aws-upgrade-4.6-stable-to-4.7-ci/1348694129546104832

test: Only consider rule evaluation failures in current window

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/builds.sh
test/extended/testdata/cmd/test/cmd/testdata/application-template-dockerbuild.json
test/extended/testdata/cmd/test/cmd/testdata/test-buildcli.json
test/extended/testdata/cmd/test/cmd/testdata/test-s2i-build.json

note at least some of these files were touched by clayton's huge refactor, but a few refs slipped the cracks
(in Adam's absence)
thanks @dmage for the heads up

Bug 1915907: replace test/cmd/builds.sh direct/indirect docker.io refs with imagestream image refs

---

test/extended/machines/cluster.go
test/extended/util/annotate/generated/zz_generated.annotations.go

The standard conformance test requires that nodes remain available.
Some suites may deliberately introduce node disruption, so this is
not a general synthetic.

test: Fail if nodes go unready during a normal parallel run

---

test/e2e/upgrade/service/service.go

The upgrade test suite includes an external load balancer service test
which is not supported in libvirt (used for s390x/ppc64le CI). Maybe
there is a possibility/use-case for metal/libvirt deploys to have
external load balancers, but it'd require a publically routable IP and
managing the access to the IP/port. Not sure if that will be supported
in non-cloud platforms.
So for now let's just add a new suite that skips the LB service,
allowing us to run upgrade tests in CI.
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

Bug 1852289: Add libvirt to the list of unsupported platforms for LB service

---

cmd/openshift-tests/e2e.go
cmd/openshift-tests/images.go
cmd/openshift-tests/openshift-tests.go
pkg/test/ginkgo/cmd_runsuite.go
pkg/test/ginkgo/synthentic_tests.go
pkg/test/ginkgo/test.go

The disruption suite needs to skip many of the synthetics because
the invariants aren't expected to be maintained. Hoist those use
cases up and out of the code.

tests: Synthetic tests moved up and out of test infra

---

pkg/test/ginkgo/cmd_runsuite.go
pkg/test/ginkgo/status.go

--count results in each test being run over and over and the last test
result is printed. Instead, each test should be unique.

test/ginkgo: When --count is used tests all fail together

---

pkg/test/ginkgo/cmd_runsuite.go
test/e2e/upgrade/upgrade.go
test/extended/util/operator/settle.go
test/extended/util/operator/settle_test.go

We recently had a BZ about operators not achieving a stable level.  This adds extra debugging to the error message so we know which operator and how long it has been unstable.
TRT identified the problem and https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_openshift-apiserver/167/pull-ci-openshift-openshift-apiserver-master-e2e-aws-upgrade/1351976530204430336 is an example.

 add additional settling debug information

---

cmd/openshift-tests/cni.go
cmd/openshift-tests/e2e.go

This adds a new suite `openshift/network/third-party`, which will be used for testing OCP compliance of third-party network plugins. Currently, [the conformance testing instructions](https://redhat-connect.gitbook.io/openshift-badges/badges/container-network-interface-cni/workflow/running-the-cni-tests) tell partners to run upstream `e2e.test` directly, with a specific set of `--ginkgo.focus` and `--ginkgo.skip` arguments, which is problematic for various reasons (particularly including the fact that by running `e2e.test` rather than `openshift-tests` they don't get the workarounds for e2e-vs-ocp issues (eg, creating an SCC to allow creating privileged pods)). Also, if we want to change the set of tests to be run, we have to change the focus/skip options, and potentially provide …

Bug 1913751: Add openshift/network/third-party suite, for CNI plugin conformance

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers_test.go

clean pick of `94589`
previously all sorts of errors including a data race were possible because deferredResponseWriter resets the writer and returns it to the pool.
an attempt to write to a nil writer will lead to "invalid memory address or nil pointer dereference"
sharing the same instance of deferredResponseWriter might lead to "index out of range [43] with length 30" and "recovered from err index > windowEnd" errors.

Bug 1879208: fixes a data race in SerializeObject function

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/volumes.sh

We were unnecessarily waiting for PV removal in `volumes.sh` test which caused this particular test to stuck for removal of a PV which it didn't create in the first place.

Bug 1921088: don't wait for PV removal in volumes.sh

---

test/extended/etcd/leader_changes.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Our guarantee is that no leader changes should occur during test runs,
not during installation or scenarios prior to the test. Use the new
test duration to constrain the metric by time. Verified against a cluster
that the resulting query is correct.

test: etcd leader changes should be measured over the test, not the run

---

test/extended/cli/admin.go
test/extended/util/client.go

Bug 1914894: get stdout only when invoking oc process

---

test/extended/builds/run_fs_verification.go
test/extended/util/annotate/generated/zz_generated.annotations.go

manual pick of https://github.com/openshift/origin/pull/25810
see https://github.com/openshift/origin/pull/25829#issuecomment-768359413 and https://github.com/openshift/origin/pull/25829#issuecomment-769777078 for the "why"

[release-4.6] Bug 1920626: add test to verify build /run fs contents

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/images.sh

The test is validating the wrong thing - --from only works with
imagestream references, --from-image works with image specs.

test/cmd/images.sh: create imagestreamtag --from is a tag

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/idle.sh

**test/extended/testdata/cmd/test/cmd/idle.sh:**
Remove the need for deleting the test service by removing the custom
runtime-created endpoints. Instead, block test setup on the number of
endpoint addresses actually available in the test endpoint resource.
By being able to keep the service, this test is now compatible with
recent changes to `oc idle`, in which `oc idle` annotates a service
directly (in addition to available endpoints).
**test/extended/testdata/bindata.go:**
Regenerate
---
This PR should unblock CI for https://github.com/openshift/oc/pull/720

Bug 1900989: idle.sh: Drop endpoints mocks from idle tests

---

test/extended/builds/run_fs_verification.go

addresses 
https://storage.googleapis.com/origin-ci-test/logs/release-openshift-okd-installer-e2e-aws-4.7/1355560957442527232/build-log.txt
@vrutkovs 
can you open a BZ to facilitate this FIX?
and is there any pre-merge OKD validation we can/should do?
@adambkaplan - I believe I also addressed some nit but merge anyway comments in this new file that you had ... `dockerfile: |-` for better readability

Bug 1922991: allow OKD /run contents for build fs test

---

cmd/openshift-tests/upgrade.go

Ensure we don't start before install completes or any operators are metastable

test: Upgrade should prereq early tests

---

test/extended/router/idle.go
test/extended/testdata/bindata.go
test/extended/testdata/router/router-idle.yaml
test/extended/util/annotate/generated/zz_generated.annotations.go

An explicit test to assert that a service that is idled will be
unidled when a GET request occurs on the route.

Bug 1900989: test/extended/router: add idle/unidle e2e test

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/BUILD
vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/metrics.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/metrics_test.go

When an apiservice is deleted, its relative
aggregator_unavailable_apiservice metric remains with the value of the
last availability observed. Hence, if an apiservice is deleted while
being unavailable, the metric remains marked as unavailable.
This presents some problems when alerting on unavailable apiservices
as deleted apiservices might trigger the alert indefinitely.
To solve this issue, the aggregator_unavailable_apiservice metric should
only reflect the availability of existing apiservices.
This is achievable by using a custom Collector instead of a GaugeVec and
create throw-away metrics based on an apiservice lister output. With
this approach, on deletion, the apiservice will not be listed anymore,
resulting in its availability metric not being exposed.

Bug 1916660: UPSTREAM: 97916: kube-aggregator: fix apiservice availability gauge

---

vendor/k8s.io/kubernetes/cmd/cloud-controller-manager/app/options/options_test.go
vendor/k8s.io/kubernetes/cmd/controller-manager/app/serve.go
vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/options/options_test.go
vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go
vendor/k8s.io/kubernetes/pkg/kubeapiserver/server/insecure_handler.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/config.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/BUILD
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/timeout_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/filters/wrap.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/authentication.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/authorization.go

Backports 96217, 95725, 95002 and 96424
Default timeout (10 s) for the TokenReview client (96217)
Default timeout (10 s0) for the SubjectAccessReview client (95725)
No stack trace of aborted requests in the logs (95002 and 96424)
Note: moving 95002, 96424 wasn't clean and needs review.
Note: `UPSTREAM: 95002: klog v1 prints to stderr` is a new commit

Bug 1894918: Panic output due to timeouts in kube-apiserver

---

cmd/openshift-tests/upgrade.go

Upgrade output shows linear progress of the test and it is important
for understanding when even successful runs may fail to preserve
invariants.

tests: Upgrade tests should always include success output

---

vendor/k8s.io/kubernetes/pkg/credentialprovider/config.go
vendor/k8s.io/kubernetes/pkg/credentialprovider/config_test.go

[release-4.5] Bug 1887311: UPSTREAM: 94712: [credentialprovider] avoid potential secret leaking while reading .dockercfg

---

test/extended/builds/run_fs_verification.go

On RHEL7 workers /run contents for build fs test are different from all the other variants we are checking, which makes test fail on RHEL7 workers as seen in this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1924128
Adding correct string from RHEL7 worker to the list of checked contents should help.

Bug 1924128: Allow RHE7 /run contents for build fs test

---

test/extended/util/image/image.go
test/extended/util/image/zz_generated.txt

This fixes some niche e2e tests, see the BZ.
In addition, this is pre-requisite for enabling snapshot e2e tests, which we disabled during rebase and forgot to enable in https://bugzilla.redhat.com/show_bug.cgi?id=1906518.
I filed https://bugzilla.redhat.com/show_bug.cgi?id=1925493 for enabling those tests.

Bug 1915912: Fix CSI snapshotter image version

---

cmd/openshift-tests/e2e.go
test/extended/oauth/server_headers.go

Double parallelism, cut repetitions 20% to 12.

tests: Double up the network stress test pressure

---

test/extended/dr/backup_restore.go
test/extended/dr/common.go
test/extended/dr/force_redeploy.go
test/extended/dr/quorum_restore.go
test/extended/util/annotate/generated/zz_generated.annotations.go

- [backup doc](https://docs.openshift.com/container-platform/4.6/backup_and_restore/backing-up-etcd.html)
- [restore doc](https://docs.openshift.com/container-platform/4.6/backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.html)

Bug 1886160:  Add test of documented backup/restore procedure

---

test/extended/etcd/leader_changes.go

If the prometheus process on a conformant cluster has no PVs, the
data in prometheus is lost and the current query will flag that as
a leader election (new prometheus scrapes the old etcd and sees the
increase). The tightened tolerance turned out to be too tight for
serial tests, where we allow the machine set test to replace one
of the workers. If we were using PVs for prometheus in all machine
set clusters this would be ok, but it's valid today to have a
machine set cluster with no PV provisioning.
The test now ignores restarts that happen before the beginning of
prometheus history, and only looks at leader changes over the time
prometheus is up and running with the latest data.

Bug 1924953: Allow prometheus state clear to pass etcd leader change test

---

Makefile
test/extended/builds/s2i_root.go
test/extended/util/image/image.go
test/extended/util/image/zz_generated.txt

While mirroring image for https://github.com/openshift/origin/pull/25862 I've noticed we're still pointing to deprecated images in registry.svc.ci.openshift.org. I've updated them during mirroring but here is the actual PR fixing those.
since you own those bits.

Change registry.svc.ci.openshift.org to registry.ci.openshift.org

---

test/extended/include.go
test/extended/single_node/topology.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Tests that deployments have a single replica when https://github.com/openshift/enhancements/pull/555 control plane topology is set to SingleReplica.
This enhancement is yet to be merged as well as the relevant behavior from the various operators, so this PR is in draft mode until then.

Test that new single replica topology API is taken into account

---

test/extended/util/disruption/controlplane/controlplane.go

OAuth API connection reuse/creation tests were actually checking
OpenShift API connections instead.
/cc @sttts @deads2k

e2e: test OAuth API connections in the tests by that name

---

test/extended/router/idle.go
test/extended/testdata/bindata.go
test/extended/testdata/router/router-idle.yaml
test/extended/util/annotate/generated/zz_generated.annotations.go

This is a manual backport of PR #25850.
An explicit test to assert that a service that is idled will be
unidled when a GET request occurs on the route.

[release-4.6] Bug 1900991: test/extended/router: add idle/unidle e2e test

---

test/extended/authorization/rbac/groups_default_rules.go

Required to land https://github.com/openshift/cluster-kube-apiserver-operator/pull/1038

tolerate permissions for allowing in-cluster CA bundles to all authenticated

---

test/extended/etcd/leader_changes.go

The change to calculation worked when the metric was new (because the serial test cleared the PV data) but not when it was restarted after we added the PV retention.
Simplify the metric with the new data from when we have preserved the change.

test: Calculate leader elections over individual metrics

---

test/extended/router/idle.go

Fixes for failures/flakes seen in CI runs:
- increase timeout for polling operations to 15 mins
- wait for PODs to be running after the fixture has been created
This also switches from using URLTester to making a direct connection
to the route's hostname. This reduces the need for an execpod and will
make the test run faster.
The changes here will also make the test pass for the proxy CI job.

Bug 1926146: test/extended/router/idle: address flakes/failures seen in CI 

---

test/extended/networking/multicast.go

In order to get around docker rate limiting, the e2e tests
need to pull images off either quay or the local image
registry. This change updates the multicast image to be
pulled from the local image registry.
Signed-off-by: Aniket Bhat <anbhat@redhat.com>

Bug 1902054: Update multicast test image for use in release-4.6

---

test/extended/pods/liveness_override.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1899941
Tests https://github.com/openshift/kubernetes/pull/527
Add an e2e test that verifies the liveness override annotation works.
Ran the test 103 times in a while loop on a nightly cluster to tune parameters and verify the fix.
Analyzed data on time elapsed, in seconds:
min | 25% | 50% | 75% | max
-- | -- | -- | -- | --
2.022462378 | 2.0259687905 | 2.030493038 | 16.127785352 | 24.317637698
I had the timeout threshold set at 25s before but upped to 30s just to be super safe given the max...
/cc @rphillips

Bug 1899941: Add e2e test for liveness override annotation

---

pkg/test/ginkgo/synthentic_tests.go

A local variable was shadowed and prevented synthetic failures from
propagating.

test: Synthetic failures were not failing the job

---

cmd/openshift-tests/e2e.go
cmd/openshift-tests/upgrade.go
pkg/monitor/node.go
test/e2e/upgrade/upgrade.go

A node should go down, get upgraded, and come back up ready exactly
once per upgrade. Test that condition.

test: Ensure nodes stay ready during upgrades after reboot

---

test/extended/cli/admin.go
test/extended/cli/observe.go
test/extended/cli/rsh.go
test/extended/util/annotate/generated/zz_generated.annotations.go

This fixes two most frequently failing problems in our CI:
1. oc observe can spit 'Nothing to sync' if it doesn't find anything and that is equally valid as 'Sync ended'
2. oc adm new-project frequently fails on timeout when waiting for project deletion, so I'm bumping this to 2m.

Bug 1921720: fix sig-cli flakes

---

vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity.go
vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity_test.go

#25463 tried addressing additional bugs that were uncovered when fixing this parent issue, and apparently regressed earlier fixes. This reverts that pr
/priority important-soon
/kind regression

[release-3.11] Bug 1760807: Revert #25463 regression in pod affinity check

---

test/extended/single_node/topology.go

It also creates 2 replicas for now so it's allowed to fail

Added openshift-image-registry to single node topology test allowedToFail list

---

test/e2e/upgrade/service/service.go

Required to pass tests in vsphere upgrade workflow.
Ref: https://issues.redhat.com/browse/OTA-308

Bug 1929110: test: add vsphere to unsupported platforms for LB service

---

test/extended/authorization/scc.go

Looks like someone nerfed the SCC test while we had the early render in flight.  This puts it back so we can catch when things get worse again.

put the SCC test back

---

test/extended/prometheus/prometheus.go

The alert test has not been working and a PR was able to merge that was firing alerts during the test run. https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-baremetal-operator/110/pull-ci-openshift-cluster-baremetal-operator-master-e2e-agnostic/1364398641615212544 shows the two firing alerts being bypassed by the query in the `shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured` late test
Fix the test logic based on:
1. Remove the filter on KubeAPILatencyHigh - no longer needed in 4.6+
2. Remove the filter on KubePodCrashLooping - no longer needed in 4.6+
3. Sort the metric by number of seconds the alert was firing
The bug that allowed the merge was the filter for KubePodCrashLooping,
to omit a series we …

Bug 1932618: Don't allow alerts to fire during a test run

---

test/e2e/upgrade/upgrade.go
test/extended/dr/common.go

The MCO is required to roll out the master config pool prior to reporting level, and thus CVO should never reach Available at a
new version without the master pool being updated. Add an extra check to the pool rollout - if we see the master pool with an
Updating condition flag it and fail the upgrade job. Also handle paused pools in the wait loop (a paused pool is effectively "we
will not deal with this pool" and so we will exit early and log).
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/988/pull-ci-openshift-cluster-network-operator-master-e2e-gcp-ovn-upgrade/1364259570968432640 had a possible case where this happened, tighten the test.
```
Feb 23 18:43:19.284: INFO: cluster upgrade is Progressing: Working towards …
```

test: Detect when the master pool is still updating after upgrade

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack.go

This is a cherry-pick of https://github.com/openshift/kubernetes/pull/510

[release-4.5] Bug 1928978: UPSTREAM: 89885: SQUASH: Fix cinder crash

---

test/extended/authorization/scc.go

Tests are required to take into account SCC propagation in order to
not have their own flakes, so during test runs SCC delay is forbidden.

test: Prevent all SCC failures from being allowed during normal e2e

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/apis/flowcontrol/bootstrap/default.go

**What type of PR is this?**
/kind bug
All workloads running using service account (except for the ones distinguished by p&f with a logically higher matching precedence) will match the `service-accounts` flow schema and be assigned to the `workload-low` priority and thus will have only `20` concurrency shares. (~10% of the total)
On the other hand, `global-default` flow schema is assigned to `global-default` priority configuration and thus will have `100` concurrency shares (~50% of the total). If I am not mistaken, `global-default` goes pretty much unused since workloads running with user (not service account) will fall into this category and is not very common. 
Workload with service accounts do not have enough concurrency share and may starve. …

BUG 1891106: UPSTREAM: 95259: allocate service-account flowschema to global-default

---

test/extended/builds/s2i_quota.go

Validate the memory swap cgroup value is logged in builds.
This was blocked by cri-o and buildah related fixes that have been
vendored into openshift/builder.
See also https://github.com/containers/buildah/issues/1213

Restore s2i memoryswap quota test

---

test/extended/router/idle.go

Skip test on platforms where the default router is not exposed by a
load balancer service.

Bug 1933114: test/extended/router/idle: skip test on virt platforms

---

test/extended/machines/cluster.go

The serial test creates a new instance and deletes an old one
(gracefully). This should only cause the "nodes not ready" test
to fail if the node object doesn't get deleted. The query is shifted
1m to the left, so that if at the current time the node doesn't exist
then the ready condition is ignored 1m earlier. This is because
promethues queries can't offset in the future.
This leaves a slight gap at the end of a test (scrape_interval+
1m) where a node could go unready and the test wouldn't catch it.
But in practice it was already (scrape_interval) and the test doesn't
run at the exact end of the test anyway.
Fixes 10% of serial flakes. If 1m isn't long enough we can wait
longer.

test: Nodes that are deleted should not fire the unready alert

---

cmd/openshift-tests/e2e.go
pkg/monitor/operator.go

We supported chain upgrade, but not upgrade then rollback, which
CVO PR jobs do by default (because they're awesome).

test: Consider UpgradeRollback as an invariant reset for node ready

---

cmd/openshift-tests/e2e.go

Events from the upgrade job include the namespace (probably because
I'm holding event sending wrong on cluster scoped events).
For now, simply look at the end of the locator rather than the
beginning.

test: Node unready should ignore the ns/ in event locator

---

cmd/openshift-tests/e2e.go
pkg/monitor/operator.go
pkg/monitor/operator_test.go
pkg/synthetictests/operator_mapping.go

If any operator changes available, degraded, or progressing on non-disruptive, non-upgrade jobs, then fail.  It's easy to apply elsewhere and easy to make fail, but let's see where we are.

flake on operator state changes during e2e

---

test/extended/router/OWNERS
test/extended/testdata/router/OWNERS

Add the Network Team members as approvers and reviewers for router tests.
* `test/extended/router/OWNERS`: New file.
* `test/extended/testdata/router/OWNERS`: New file.
----
@knobunc

test/extended/router: Add OWNERS

---

test/extended/router/oc_copy.go
test/extended/router/scoped.go

Avoid a race condition in the tests by checking the status of the pod to ensure it is ready before checking the health.

Bug 1928297: Wait until router pod is ready before checking health

---

test/e2e/upgrade/service/service.go

This PR adds BareMetalPlatformType into unsupported list in service to exclude load balancer base tests in e2e upgrade.

Add BareMetalPlatformType into e2e upgrade service unsupported list

---

test/extended/operators/cluster.go

Fixes:
```
[It] have no crashlooping pods in core namespaces over four minutes [Suite:openshift/conformance/parallel]
github.com/openshift/origin/test/extended/operators/cluster.go:46
github.com/onsi/ginkgo@v4.7.0-origin.0+incompatible/internal/leafnodes/runner.go:107 +0x76
panic(0x52dfc20, 0x917e2d0)
runtime/panic.go:969 +0x1b9
github.com/openshift/origin/test/extended/operators.crashloopingContainerCheck(0xc001678b70, 0x2, 0x2)
github.com/openshift/origin/test/extended/operators/cluster.go:140 +0xac4
github.com/openshift/origin/test/extended/operators.glob..func2.1()
github.com/openshift/origin/test/extended/operators/cluster.go:47 +0x6b
```
The pod status should be logged and investigated properly.

operators: prevent panic in no crashlooping pods in core namespaces

---

pkg/monitor/e2etest.go
pkg/monitor/noop.go
pkg/synthetictests/operators.go
pkg/test/ginkgo/cmd_runsuite.go
pkg/test/ginkgo/queue.go
pkg/test/ginkgo/status.go
pkg/test/ginkgo/test.go

To be expanded next to reflect tests failing during an apiserver availability outage, but that's a little more surgery.
This also adds monitor events for running tests, so we should see those in the monitor now.

indicate which tests correspond to an operator outage

---

pkg/synthetictests/kubelet.go

Each "leg" of an upgrade is independent and the same invariants
apply.

test: When node upgrade sythetic resets, clear intermediate state

---

test/extended/single_node/topology.go

Based on https://github.com/openshift/console-operator/pull/508 change.
/assign @romfreiman

Remove console deployments from list of 2 replicas in single-replica topology

---

test/extended/operators/daemon_set.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Now that we have fixed all issues related to network upgrades by moving OVS to the node, we can bulk upgrade daemonsets on the nodes.
Daemonsets shipped with the platform must be able to upgrade without disruption to workloads. Daemonsets that are in the data path must gracefully shutdown and redirect workload traffic, or mitigate outage by holding requests briefly (very briefly!). daemonsets that are part of control plane (anything that changes state) must already be able to be upgraded without disruption by having any components that call them retry when unavailable up to a specific duration. Therefore all workloads must individually be graceful, and so a core daemonset can upgrade up to 10% of pods at a time. In the future, we may allow this percentage to be tuned via a global config, …

test: Fail if a daemonset has a different upgrade strategy than default

---

test/extended/router/router.go

Delete a reference to `routes.json`, which https://github.com/openshift/router/pull/126 deleted, when dumping router pod info.
* `test/extended/router/router.go`: Delete `routes.json` from `cat` command.

extended/router: Omit routes.json from cat command

---

pkg/synthetictests/event_junits.go

The disruptive suites do not necessarily hold all of these conditions
true, and disruptive testing is expected to violate some properties.
These should be investigated later.
E.g. https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/25928/pull-ci-openshift-origin-master-e2e-aws-disruptive/1370783035590447104

test: Temporarily move some synthetics out of disruptive

---

pkg/synthetictests/event_junits.go
pkg/synthetictests/kubelet.go

It is continuously failing and blocking merges is unnecessary because
it is a symptom and we have an urgent bug.

test: Mark pod transition back to pending as a flake for now

---

cmd/openshift-tests/images.go
test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/testdata/hello-openshift/hello-pod.json
test/extended/testdata/cmd/test/cmd/testdata/mixed-api-versions.yaml
test/extended/testdata/cmd/test/cmd/testdata/templateinstance_objectkinds.yaml
test/extended/testdata/router/ingress.yaml
test/extended/testdata/router/router-common.yaml
test/extended/testdata/router/router-config-manager.yaml
test/extended/testdata/router/router-metrics.yaml
test/extended/testdata/router/weighted-router.yaml
test/extended/testdata/templates/templateinstance_badobject.yaml
test/extended/testdata/templates/templateinstance_objectkinds.yaml

As a result we were not catching images that had not been mirrored.

test: External image test was silently failing

---

test/e2e/upgrade/alert/alert.go
test/extended/machines/cluster.go
test/extended/prometheus/prometheus.go
test/extended/prometheus/prometheus_builds.go
test/extended/prometheus/storage.go
test/extended/util/prometheus/helpers.go

It is unacceptable to fire alerts during normal upgrades. Tighten
the constraints on the upgrade tests to ensure that any alerts
fail the upgrade test. If the test is skipped, continue to report
which alerts fired. Test over the entire duration of the test like
we do in the post-run variation.

test: Require no alerts during upgrades

---

pkg/synthetictests/kubelet.go

Now that we have a root cause, mark this a flake until the crio
fix is in place.

test: Mark kubelet terminates non-gracefully as a flake

---

test/e2e/upgrade/upgrade.go

`durationToSoftFailure` was added in 4447a19e86 (#25411), but didn't get the 2x on rollbacks we'e been adding to `maximumDuration` since a53efd5e27 (#22726).  That's recently been causing [the cluster-version operator's A->B->A rollback CI jobs to time out][1].  This commit catches `durationToSoftFailure` up with the "2x on rollbacks" approach, and also mentions "aborted" in messages for those types of tests, to help remind folks what's going on.
An alternative approach would be to teach `clusterUpgrade` to treat rollbacks as two separate hops (one for A->B, and another for B->A).  But that would be a more involved restructuring, and since we already had the 2x `maximumDuration` precedent in place, I haven't gone in that direction.
/assign @deads2k @smarterclayton
[1]: …

test/e2e/upgrade: Relax 'too long' soft timeout for rollback jobs

---

cmd/openshift-tests/images.go
pkg/synthetictests/event_junits.go
pkg/synthetictests/kubelet.go
pkg/test/ginkgo/cmd_runsuite.go
pkg/test/ginkgo/synthentic_tests.go

The bool was complex and easy to get wrong, we now simply expect flakes to
be reported with a duplicate junit.

test: Synthetics should only return junit tests instead of a bool

---

test/extended/networking/util.go
test/extended/router/metrics.go
test/extended/util/jenkins/ref.go

You cannot build host:port in a URL with a simple Sprintf due to IPv6,
otherwise you'll produce invalid URL's. This moves to using
net.JoinHostPort to build URL's instead.

test: stop building URL's with host/port and Sprintf

---

test/e2e/upgrade/upgrade.go

To include values of observed generation and updated generation to help
diagnose issue [1].
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1909875

Bug 1909875: upgrade/upgrade.go: Enhance upgrade ack time out error

---

pkg/monitor/operator.go
pkg/monitor/operator_test.go
pkg/synthetictests/operators.go

Extending the the logic from 6ec446bad7 (#25918) to include the reason, since that slug both makes it easier to find the relevant operator code and makes it easier to match CI flakes with seen-in-the-wild Telemetry (where we get the status and reason, but not the message).
I'm also moving some string types into structured config/v1 types. Narrowly, this makes it easier for `GetOperatorConditionStatus` to return all its metadata without a big-list-of-strings API.  More broadly, this drops things like "assume status is a boolean, and neglect `Unknown` and unrecognized values".  This also means that we can't use `!status` to guess at what the previous status was, so I've dropped that and now only talk about the data we actually have.

pkg/synthetictests/operators: Include the reason string in testOperatorState

---

test/extended/image_ecosystem/s2i_images.go
test/extended/util/annotate/generated/zz_generated.annotations.go

See https://github.com/openshift/builder/pull/228#issuecomment-802309995
image-eco currently broken

replace registry.redhat.io refs with internal image registry refs in image-eco

---

test/extended/images/signatures.go

- Use `docker://` instead of `atomic:`, as recommended back in https://github.com/openshift/origin/pull/21782#issuecomment-459077188 https://github.com/openshift/origin/pull/21782#discussion_r253249564
- Then re-enable the test

Fix and re-enable test/extended/images/signatures.go

---

test/extended/baremetal/OWNERS
test/extended/baremetal/hosts.go
test/extended/include.go
test/extended/util/annotate/generated/zz_generated.annotations.go

This PR adds some new basic tests for the baremetal IPI platform, so that it could be possible to integrate them in the current CI/release builds for the baremetal IPI platform.
Tests are referring the following enhancements:
* https://github.com/openshift/enhancements/pull/102
* https://github.com/openshift/enhancements/pull/212
CI baremetal workflow:
* https://github.com/openshift/release/blob/master/ci-operator/step-registry/baremetalds/e2e/baremetalds-e2e-workflow.yaml
This is just an initial PR to begin landing tests for the baremetal IPI platform and clear out the required technical details.

Add new tests for baremetal IPI platform

---

cmd/openshift-tests/provider.go
test/extended/util/baremetal/provider.go

Baremetal IPI tests currently run without any provider set. While we're not so
interested in the cloud specific parts, we at least need a null provider
because loading the config also loads which SDN framework we're using,
and allows us to skip specific tests when using OVN.  Currently the
tests that should be skipped on OVN, aren't -- they're filtered manually
by passing a list of tests to skip.

test: add baremetal provider

---

test/e2e/upgrade/upgrade.go
test/extended/dr/common.go

The MCO is required to roll out the master config pool prior to
reporting level, and thus CVO should never reach Available at a
new version without the master pool being updated. Add an extra
check to the pool rollout - if we see the master pool with an
Updating condition flag it and fail the upgrade job. Also handle
paused pools in the wait loop (a paused pool is effectively "we
will not deal with this pool" and so we will exit early and log).
Cherr-pick of #25922 on release-4.7

Bug 1935707: [release-4.7] test: Detect when the master pool is still updating after upgrade 

---

cmd/openshift-tests/provider.go

When we created the baremetal provider, it wasn't imported in
provider.go to cause it to be registerd.

cmd: initialize baremetal provider

---

examples/image-streams/image-streams-centos7.json
examples/quickstarts/dancer-mysql-persistent.json
examples/quickstarts/dancer-mysql.json
test/extended/testdata/bindata.go
test/extended/testdata/cluster/quickstarts/dancer-mysql.json
test/extended/testdata/cmd/test/cmd/images.sh
test/extended/testdata/cmd/test/cmd/newapp.sh
test/extended/testdata/cmd/test/cmd/testdata/image-streams/image-streams-centos7.json
test/extended/testdata/image_ecosystem/perl-hotdeploy/perl.json

Perl 5.26 is deprecated in centos streams and would be removed from imagestreams in 4.8. `5.26-el7` version is still in the imagestreams.
This commit switches tests to prefer Perl 5.26-ubi8 and 5.30-ubi8 where possible

Sync perl/dancer imagestreams and use Perl 5.26-ubi8 and 5.30-ubi8

---

test/e2e/upgrade/service/service.go

This PR adds BareMetalPlatformType into unsupported list in service to exclude load balancer base tests in e2e upgrade.

[release-4.7] Bug 1940866: Add BareMetalPlatformType into e2e upgrade service unsupported list

---

test/extended/single_node/topology.go

The cluster monitoring operator should honor the topology configuration
since [1] has been merged.
[1] https://github.com/openshift/cluster-monitoring-operator/pull/1077
cc @romfreiman

test/extended/single_node: update for monitoring components

---

test/e2e/upgrade/service/service.go

Cherry-pick of https://github.com/openshift/origin/pull/25900 on `release-4.6`

Bug 1931864: test: add vsphere and libvirt to unsupported platforms for LB service

---

cmd/openshift-tests/images.go
pkg/monitor/api.go
pkg/monitor/cmd.go
pkg/monitor/e2etest.go
pkg/monitor/event.go
pkg/monitor/monitor.go
pkg/monitor/monitor_test.go
pkg/monitor/monitorapi/identification.go
pkg/monitor/monitorapi/types.go
pkg/monitor/node.go
pkg/monitor/noop.go
pkg/monitor/operator.go
pkg/monitor/pod.go
pkg/monitor/sampler.go
pkg/monitor/sampler_test.go
pkg/monitor/types.go
pkg/synthetictests/apiserver.go
pkg/synthetictests/event_junits.go
pkg/synthetictests/kubelet.go
pkg/synthetictests/networking.go
pkg/synthetictests/operators.go
pkg/test/ginkgo/cmd_runsuite.go
pkg/test/ginkgo/status.go
pkg/test/ginkgo/synthentic_tests.go
test/e2e/upgrade/service/service.go
test/extended/util/disruption/controlplane/controlplane.go
test/extended/util/disruption/disruption.go
test/extended/util/disruption/frontends/frontends.go
test/extended/util/disruption/imageregistry/imageregistry.go

This avoids package dep cycles we try to build analysis layers. The monitor event generation should not be relied upon directly by analysis built on top.

allow separating monitor event identification from monitor event generation

---

test/e2e/upgrade/service/service.go

Apps behind service load balancers must also set a minReadySeconds
threshold longer than the time it takes for the load balancer to
see the new pod, otherwise they can fail to be reachable which can
cause the SLB to route to all pods including the unready ones
(implementation dependent behavior).

test: App availability test during upgrade must set minReady

---

test/extended/util/disruption/controlplane/controlplane.go

We fixed GCP and AWS has regressed via https://bugzilla.redhat.com/show_bug.cgi?id=1943804.

test: Mark GCP as fixed and AWS as flaky in upgrade availability

---

test/e2e/upgrade/alert/alert.go
test/extended/operators/resources.go
test/extended/prometheus/prometheus.go
test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/prometheus/helpers.go

Unify some code between the [Late] alerts test and the upgrade
test and move the exceptions so the code looks the same.

test: Remove exceptions in fixed bugs in alert/resource tests

---

pkg/monitor/monitorapi/types.go
test/e2e/upgrade/alert/alert.go

The switch to a string broke > < comparisons on level, causing the
api disruption synthetic tests to stop firing (I > E).

test: EventLevel is compared by value for filtering

---

test/extended/networking/internal_ports.go

The connectivity test for ports 9000-9999 tries to install tcpdump via
apk, and this appears to only be used for debugging purposes. In order
to run these tests disconnected, we can't have dependencies running
in the container that try to reach out to the internet. Currently this
test fails on IPv6 disconnected installs.

test: remove apk add tcpdump to internal ports test

---

test/extended/operators/resources.go

If installer retry pods for etcd are created, the existing exception
doesn't match on these names, resulting on a failure:
```
v1/Pod/openshift-etcd/installer-<revision>-retry-1-<node>/container/installer
defines a limit on cpu of 150m which is not allowed (rule:
"v1/Pod/openshift-etcd/installer-<revision>-retry-1-<node>/container/installer/limit[cpu]")
```
This removes the -retry-N- to normalize the name.

test: grant exception to installer etcd retry pods

---

test/extended/coreos/coreos.go
test/extended/include.go
test/extended/util/annotate/generated/zz_generated.annotations.go

This validates https://github.com/openshift/installer/pull/4760
until we have an in-cluster consumer.

tests/extended: Add a basic sanity test for CoreOS bootimages

---

test/extended/util/oauthserver/oauthserver.go

This PR changes oauthserver's ServingInfo resource's BindNetwork to tcp to support IPv6.

Change BindNetwork of outhserver to tcp to support IPv6

---

pkg/synthetictests/event_junits.go
pkg/synthetictests/operators.go

re-uses the operator monitor to avoid degraded and unavailable operators during an upgrade.

require operator availability and non-degraded for upgrades

---

test/extended/image_ecosystem/s2i_images.go
test/extended/util/annotate/generated/zz_generated.annotations.go

SCL org has deprecated Perl 5.26 and NodeJS 10, so we should be checking Perl 5.30 and NodeJS 12 instead.
See https://github.com/openshift/cluster-samples-operator/pull/360

test: skip checking nodejs 10 and perl 5.26

---

test/extended/dns/dns.go
test/extended/util/annotate/generated/zz_generated.annotations.go

test/extended/util/dns/dns.go:
OCP 4.8 now uses CoreDNS v1.8.1, which adds support for dual-stack clusterIP services (https://github.com/coredns/coredns/pull/4339). Add a new test to verify that CoreDNS pods respond to A and AAAA queries for a service URL (ie `<service>.<namespace>.svc`) as well for a service endpointslice URL (ie `<endpointslice_hostname>.<service>.<namespace>.svc`). Note that the other existing test in `dns.go` is disabled since the DNS operator does not support wildcard DNS.
test/extended/util/annotate/generated/zz_generated.annotations.go:
Regenerate
---
This is in support of https://issues.redhat.com/browse/NE-544.

NE-544: DNS: Add new dual-stack service DNS test

---

test/extended/authorization/scopes.go
test/extended/cli/mustgather.go
test/extended/oauth/client_secret.go
test/extended/oauth/token.go
test/extended/project/project.go
test/extended/util/annotate/generated/zz_generated.annotations.go

fix the rest of parallel tests working with old token format

---

test/extended/oauth/requestheaders.go

Instead of waiting for separate pods, rely on the operator reporting
properly what the status of the rollout is.
Previously, we were waiting for pods for 2 minutes and then the operator
go progressing. But:
- 2 minutes for a pod to rollout does not seem to be enough in 33% of
the cases with the new rollout strategy
- if the operator is still progressing, some pods might still use the
old config, hence the original code issue with the old config still
being used

Bug 1945398: e2e requestheader: properly wait for a new oauth-server rollout
