openshift/origin

pkg/build/controller/strategy/util.go
pkg/build/controller/strategy/util_test.go

manual pick of https://github.com/openshift/openshift-controller-manager/pull/46 into 4.1 since in 4.1 the code lived in openshift/origin but in 4.2 it was moved to openshift/openshift-controller-manager

Bug 1754681: add build ca bundle to init containers

---

vendor/k8s.io/kubernetes/pkg/controller/replicaset/init_test.go
vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go
vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set_test.go

[release-4.2] Bug 1772087: Fix RS expectations

---

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go

This is manual cherry pick of #23977 into 4.2. Cutting down AWS eventual consistency flakes.
https://bugzilla.redhat.com/show_bug.cgi?id=1764044
https://github.com/openshift/origin/pull/23977
@openshift/storage 
@knobunc, please approve backport

Bug 1764044: 4.2: UPSTREAM: 83567: Fix attachment of just detached AWS volumes

---

test/extended/OWNERS

Adding myself to approve OLM tests that are added

---

pkg/cmd/server/kubernetes/network/network.go
pkg/cmd/server/start/start_network.go

This pull request is a backport of the change where we wait for
the sdn proxy to initialize  before marking node as ready.

Bug 1764150: Wait for sdn proxy to initialize

---

test/extended/util/test.go

https://bugzilla.redhat.com/show_bug.cgi?id=1763936

Bug 1763936: Disable node-Service and pod-Service granular checks

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/builds.sh

Attempt to mitigate https://bugzilla.redhat.com/show_bug.cgi?id=1784848

build: disable timeouting test

---

test/extended/controller_manager/pull_secret.go

Increase to 10 minutes to cover full relist window.

Bug 1765294: Increase timeout for Dockercfg tests

---

test/extended/testdata/bindata.go
test/extended/testdata/builds/build-pruning/default-group-build-config.yaml
test/extended/testdata/builds/build-pruning/default-legacy-build-config.yaml
test/extended/testdata/builds/build-pruning/errored-build-config.yaml
test/extended/testdata/builds/build-pruning/failed-build-config.yaml

Bug 1782467: move off of deprecated php:7

---

vendor/k8s.io/kubernetes/test/e2e/apps/cronjob.go

UPSTREAM: 86348: Split cronjob tests, so they don't interfere

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/client-gen/args/args.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/client-gen/generators/client_generator.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/client-gen/main.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/informer-gen/args/args.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/informer-gen/generators/BUILD
vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/informer-gen/generators/generic.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/informer-gen/generators/packages.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/informer-gen/main.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/lister-gen/args/args.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/lister-gen/generators/lister.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/cmd/lister-gen/main.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/pkg/util/BUILD
vendor/k8s.io/kubernetes/staging/src/k8s.io/code-generator/pkg/util/plural_exceptions.go

review carefully wasn't a clean pick.

picks 86212 code-generator: expose pluralExceptions via flag 

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/set-image.sh
test/extended/testdata/cmd/test/cmd/set-liveness-probe.sh

Drop backwards compatibility tests that are not needed anymore

---

hack/OWNERS

I have not been working on hack in the past 3 years.

Remove marun from hack/OWNERS

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/rest/request.go

UPSTREAM: 80649: Report api request throttling at v=3

UPSTREAM: 80649: Report api request throttling at v=3

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/util/shufflesharding/shufflesharding_test.go

hopefully fixed by https://github.com/openshift/release/pull/6530

brings back disabled TestUniformDistribution test

---

test/extended/deployments/deployments.go

Attempt to address https://bugzilla.redhat.com/show_bug.cgi?id=1788253

Bug 1788253: fix deployment config flake by using informer

---

examples/dockergc/dockergc-ds.yaml
examples/grafana/grafana.yaml
examples/helm/tiller-template.yaml
examples/prometheus/node-exporter.yaml
examples/prometheus/prometheus-standalone.yaml
examples/service-catalog/service-catalog.yaml
examples/storage-examples/local-examples/local-storage-provisioner-template.yaml

some leftovers I found in my stash
/cc @soltysh

Migrate apps/v1beta* to apps/v1

---

test/extended/csi/install.go
test/extended/testdata/bindata.go
test/extended/testdata/csi/README.md
test/extended/testdata/csi/aws-ebs/install-template.yaml
test/extended/testdata/csi/aws-ebs/manifest.yaml

This is part of the effort to add e2e tests to CSI sidecars we ship.

Add CSI resizer to e2e tests

---

test/extended/cli/explain.go

Depends on: https://github.com/openshift/cluster-network-operator/pull/398

Bug 1769015: Uncomment the lines to verify oc explain for networking related CRDs

---

vendor/k8s.io/kubernetes/test/e2e/upgrades/apps/deployments.go

Bug 1794813: UPSTREAM: 79160: e2e Flake: Pass updated deployment for comparison of replica count

---

vendor/k8s.io/kubernetes/pkg/kubelet/certificate/kubelet.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/util/certificate/certificate_manager.go

Adds a certificate rotation error metric to the kubelet.
Upstream ref: https://github.com/kubernetes/kubernetes/pull/84614

Bug 1767523: UPSTREAM: 84614: kubelet: add certificate rotation error metric

---

pkg/monitor/api.go
pkg/monitor/monitor.go
pkg/monitor/sampler_test.go
pkg/monitor/types.go
test/e2e/upgrade/service/service.go
test/e2e/upgrade/upgrade.go
test/extended/util/disruption/controlplane/controlplane.go
test/extended/util/disruption/disruption.go

Bug 1796716: Verify services and API are available during upgrade

---

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_getters.go

Fixes sync's status for static pods.

[release-4.3] Bug 1794852: UPSTREAM: 86191: Sync the status of static Pods

---

pkg/oc/cli/admin/diagnostics/cluster.go
pkg/oc/cli/admin/diagnostics/diagnostics/cluster/aggregated_logging/cronjobs.go
pkg/oc/cli/admin/diagnostics/diagnostics/cluster/aggregated_logging/cronjobs_test.go
pkg/oc/cli/admin/diagnostics/diagnostics/cluster/aggregated_logging/deploymentconfigs.go
pkg/oc/cli/admin/diagnostics/diagnostics/cluster/aggregated_logging/diagnostic.go
pkg/oc/cli/admin/diagnostics/diagnostics/cluster/aggregated_logging/interfaces.go

Fix cluster logging diagnostic cronjob curator check 
https://bugzilla.redhat.com/show_bug.cgi?id=1761930

Bug 1761930: Fix ClusterLogging curator diagnostic check

---

images/router/haproxy/conf/haproxy-config.template

Backport of https://github.com/openshift/router/pull/20/commits/e9961a1eb712f79fbfe9c9b3d2902d833d784ea5

Bug 1762040: Fix cosmetic template error

---

test/extended/operators/images.go

This whitelist installer and pruner pods that cause the test to fail with:
```
Jan 21 11:36:14.826: INFO: Error running &{/usr/bin/oc [oc --namespace=openshift-kube-controller-manager --config=/tmp/admin.kubeconfig exec revision-pruner-4-master-1.ci-op-0y5bbkz0-4c0cd.origin-ci-int-aws.dev.rhcloud.com -c pruner -- cat /etc/redhat-release] []   error: cannot exec into a container in a completed pod; current phase is Succeeded
error: cannot exec into a container in a completed pod; current phase is Succeeded
```
Not sure who is the owner of this test.
/cc @derekwaynecarr

test: fix the operator images test to skip succeeded containers

---

vendor/k8s.io/kubernetes/pkg/kubelet/cm/node_container_manager_linux.go

Fixes node allocations on the kubepods.slice on Kubelet startup.
ref: https://github.com/kubernetes/kubernetes/pull/88251
ref: https://github.com/kubernetes/kubernetes/issues/88197
/cc @sjenning @smarterclayton

Bug 1802687: UPSTREAM: 88251: Partially fix incorrect configuration of kubepods.slice unit by kubelet

---

test/extended/builds/cluster_config.go

When running the disruptive build tests, check that the ocm operator
reports`Progressing=False` and nothing else. Work-arounds in the test
were fixed by https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/140.

Bug 1804434: builds: Only check ocm progress state

---

test/e2e/upgrade/service/service.go

Each platform has different settings. Make the different platform
configurations equal where possible and tolerate the longest
possible duration.

test: Set upgrade service LB timeouts for graceful shutdown

---

cmd/openshift-tests/upgrade.go
test/e2e/upgrade/service/service.go
test/e2e/upgrade/upgrade.go
test/extended/operators/cluster.go
test/extended/util/disruption/controlplane/controlplane.go
test/extended/util/disruption/disruption.go
test/extended/util/disruption/frontends/frontends.go

See commits for details, backporting to allow testing of our backports for upgrade
availability.

Bug 1806407: Improve upgrade availability tests and add sequential upgrade input

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go

Currently, /readyz starts reporting failure after ShutdownDelayDuration
elapses. We expect /readyz to start returning failure as soon as
shutdown is initiated. This gives the load balancer a window defined by
ShutdownDelayDuration to detect that /readyz is red and stop sending
traffic to this server.

Bug 1811169: /readyz should start returning failure on shutdown initiation

---

vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/framework_test.go
vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go
vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1809781
/sig storage

Bug 1809781: UPSTREAM: 88146: Do not issue duplicate pv delete calls

---

test/extended/networking/internal_ports.go

This is an attempt at understanding what is going on with: https://bugzilla.redhat.com/show_bug.cgi?id=1811435
I will need tcpdump in the pods that are used in the test to check if TCP & UDP packets are actually arriving on the node or not, this will help determine if the kernel is dropping them or if the back-end is unable to process them. 

Attempt at understanding where packets are being dropped

---

test/extended/cli/explain.go

Fix failed explain job from openshift-svcat-*-operator tests.

remove servicecatalog test from master

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/dynamic_cafile_content.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/static_content.go

Bug 1812877: fixes configmap "extension-apiserver-authentication" not found

---

pkg/network/node/egressip.go
pkg/network/node/iptables.go

Backport of https://github.com/openshift/sdn/pull/88

Bug 1797045: [3.11] Clean up stale egress IP iptables rules on startup

---

test/extended/controller_manager/deploy_defaults.go

needed to unblock OAS rebase PR - https://github.com/openshift/openshift-apiserver/pull/82

e2e: DC defaults - ignore meta ManagedFields

---

vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/framework_test.go
vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go
vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1808551
/sig storage

Bug 1808551: UPSTREAM: 88146: Prevent duplicate errors

---

test/extended/conformance-k8s.sh
test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/help.sh

4.3 backport of https://github.com/openshift/origin/pull/24420

Bug 1802262: Loosen help tests for oc rsh

---

vendor/k8s.io/kubernetes/test/e2e/storage/utils/utils.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1811916
Backport of PR #24644
/sig storage

Bug 1811916: UPSTREAM: 86886: Fix err variable shadowing issue in storage/utils

---

vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/framework_test.go
vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go
vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller_test.go

https://bugzilla.redhat.com/show_bug.cgi?id=1808548
/sig storage

[4.3] Bug 1808548: UPSTREAM: 88146: remove duplicate pv delete commands

---

images/ipfailover/keepalived/lib/config-generators.sh

https://bugzilla.redhat.com/show_bug.cgi?id=1813191

bug 1813191: Fix ipfailover nopreempt & notification problems

---

vendor/k8s.io/kubernetes/pkg/kubelet/server/server.go
vendor/k8s.io/kubernetes/pkg/kubelet/server/server_test.go

ref: https://github.com/kubernetes/kubernetes/pull/87913

Bug 1816409: UPSTREAM: 87913: Add code to fix kubelet/metrics memory issue.

---

vendor/k8s.io/kubernetes/pkg/controller/util/node/controller_utils.go

Fixes the API version on the event objects.

Bug 1808847: UPSTREAM: 87537: Add apiVersion to involvedObject

---

test/extended/util/disruption/frontends/frontends.go

Upgrade tests for routes expect the console page to contain "Red Hat OpenShift Container Platform" title. These tests [fail](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-okd-installer-e2e-aws-upgrade/7) for OKD releases due to different branding.
This PR adds `ExpectRegexp` option for Frontend struct and checks both for OCP and OKD signature so that OKD upgrades could be tested using the same code.

test/extended/util/disruption/frontends/frontends: match route contents by regexp, support OKD

---

test/extended/router/h2spec.go

We were getting CI flakes because the default Dial() timeout in h2spec
is 2s. I've bumped this to 15s for our invocations.
The EOF (see below) was because the results file was zero length.
Flake report from:
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-4.5/1003
```console
[sig-network-edge][Conformance][Area:Networking][Feature:Router] The HAProxy router should pass the h2spec conformance tests [Suite:openshift/conformance/parallel/minimal] expand_less 56s
fail [github.com/openshift/origin/test/extended/router/h2spec.go:186]: Unexpected error:
<*errors.errorString | 0xc0000a6060>: {s: "EOF"}
EOF
occurred
```
I've also changed the overall test invocation to now retry for a
maximum of 5 minutes should we get any h2spec failure. …

test/extended/router: fix h2spec flake

---

test/extended/builds/start.go

please help to review it, thanks.

test/extended/builds: Fix -e option when do build

---

vendor/k8s.io/kubernetes/pkg/kubelet/container/helpers.go
vendor/k8s.io/kubernetes/pkg/kubelet/container/helpers_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go
vendor/k8s.io/kubernetes/test/e2e/node/BUILD
vendor/k8s.io/kubernetes/test/e2e/node/pods.go

Origin Reference: https://github.com/openshift/origin/pull/24627

[release-4.3] Bug 1821341: UPSTREAM: 88440: Report deleted pod status correctly

---

hack/listtests/main.go

use sort.Strings(...) instead of sort.Sort(sort.StringSlice(...))

sort expression

---

vendor/k8s.io/kubernetes/test/e2e/network/ingressclass.go

The test races with the admission cache and is failing 5-7% of the
time in e2e runs.

Bug 1826499: IngressClass error test is flaky

---

vendor/k8s.io/kubernetes/pkg/volume/fc/fc_test.go
vendor/k8s.io/kubernetes/pkg/volume/fc/fc_util.go
vendor/k8s.io/kubernetes/pkg/volume/iscsi/BUILD
vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go

https://bugzilla.redhat.com/show_bug.cgi?id=1813927
https://github.com/kubernetes/kubernetes/pull/89172

Bug 1813927: UPSTREAM: 89172: Fix mountOptions in iSCSI and FC volume plugins

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/dynamic_cafile_content.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/dynamic_serving_content.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/dynamiccertificates/static_content.go

Bug 1813847: fixes configmap "extension-apiserver-authentication" not found 

---

test/extended/dr/quorum_restore.go

We should use a dynamic mechanism rather than a static one.

test: Allow disruptive tests on any platform with machine APIs

---

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_getters.go

Fixes sync's status for static pods.

[release-4.2] Bug 1794854: UPSTREAM: 86195: Sync the status of static Pods

---

test/extended/prometheus/prometheus.go

Bug 1829223: test/extended/prometheus: allow a pending state for AlertmanagerReceiversNotConfigured

---

vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go

Bug 1831533: stop printing usage help when the server commands exit

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_volumes.go

Cherry-pick of https://github.com/kubernetes/kubernetes/pull/88424

Bug 1822667: UPSTREAM: 88424: Respect ignore-volume-az option in admission plugin

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_volumes.go

Cherry-pick of https://github.com/kubernetes/kubernetes/pull/88424

Bug 1822680: UPSTREAM: 88424: Respect ignore-volume-az option in admission plugin

---

vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/framework_test.go
vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go
vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1808549
/sig storage

[4.2] Bug 1808549: UPSTREAM: 88146: remove duplicate pv delete commands

---

vendor/k8s.io/kubernetes/test/e2e/apimachinery/crd_publish_openapi.go

Bug 1828790: provides a temporal fix to improve CRD publishing e2e tests in an HA setup

---

cmd/openshift-tests/e2e.go
test/extended/templates/template.go
test/extended/templates/templateinstance_cross_namespace.go
test/extended/templates/templateinstance_fail.go
test/extended/templates/templateinstance_impersonation.go
test/extended/templates/templateinstance_objectkinds.go
test/extended/templates/templateinstance_readiness.go
test/extended/templates/templateinstance_security.go
test/extended/templates/templateservicebroker_bind.go
test/extended/templates/templateservicebroker_e2e.go
test/extended/templates/templateservicebroker_security.go

manual pick because bot failed
see https://github.com/openshift/origin/pull/24912#issuecomment-626173702

Bug 1833824: unskip template extended tests

---

vendor/k8s.io/kubernetes/pkg/volume/azure_file/azure_file.go
vendor/k8s.io/kubernetes/pkg/volume/azure_file/azure_provision.go
vendor/k8s.io/kubernetes/pkg/volume/gcepd/gce_util.go
vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
vendor/k8s.io/kubernetes/pkg/volume/portworx/portworx_util.go
vendor/k8s.io/kubernetes/pkg/volume/rbd/rbd_util.go
vendor/k8s.io/kubernetes/pkg/volume/scaleio/BUILD
vendor/k8s.io/kubernetes/pkg/volume/scaleio/sio_volume.go
vendor/k8s.io/kubernetes/pkg/volume/scaleio/sio_volume_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/cloud-provider/volume/helpers/rounding.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/cloud-provider/volume/helpers/rounding_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/gce/gce_disks.go

Backport of https://github.com/kubernetes/kubernetes/pull/90907
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1592653
cc @openshift/sig-storage

Bug 1592653: detect int64 overflow when converting volume sizes

---

test/extended/project/project.go

fixing observed panic here https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/347/pull-ci-openshift-cluster-etcd-operator-master-e2e-metal-ipi/190 .
Something else is wrong and this can help us figure out what.

bug 1837464: prevent panic-ing in test to try to figure out what's failing

---

vendor/k8s.io/kubernetes/test/e2e/apimachinery/crd_publish_openapi.go

clean pick - the fix seems to be working (in 4.5) - https://testgrid.k8s.io/redhat-openshift-ocp-release-4.5-blocking#release-openshift-origin-installer-e2e-gcp-4.5&sort-by-flakiness

Bug 1830093: provides a temporal fix to improve CRD publishing e2e tests in an HA setup

---

publishing-kube-rules.yaml

Add publishing rules for origin-4.5-kubernetes-1.18.3

---

test/extended/marketplace/marketplace_diffname.go

The CSC crd is removed from OCP4.5, so the fix need merged to release-4.4. Fix the issue with the test asking too quickly.
test result:
./openshift-tests run all --dry-run | grep "Marketplace diff name test"  | ./openshift-tests run --junit-dir=./  -f -
started: (0/1/1) "[Feature:Marketplace] Marketplace diff name test [Top Level] [Feature:Marketplace] Marketplace diff name test [ocp-25672] create the samename opsrc&csc [Serial] [Suite:openshift/conformance/serial]"
...
R=samename'
May 15 16:42:50.236: INFO: Start to create Resource: /tmp/e2e-test-marketplace-h2fs7-config.json
May 15 16:42:50.236: INFO: Running 'oc --kubeconfig=/home/jfan/work/env/kubeconfig create -f /tmp/e2e-test-marketplace-h2fs7-config.json'
catalogsourceconfig.operators.coreos.com/samename created
May 15 …

Bug 1820731: samename test flake fix

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_volumes.go

https://bugzilla.redhat.com/show_bug.cgi?id=1827071
https://github.com/kubernetes/kubernetes/pull/90792

Bug 1827071: UPSTREAM: 90792: Send a nicer event when resizing attached Cinder volume

---

vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go

This PR sets node.session.scan to manual to avoid unused LUNs being discovered and mapped on a node when it does its initial login. If that happens, the devices are never removed.
https://github.com/kubernetes/kubernetes/pull/90985
https://bugzilla.redhat.com/show_bug.cgi?id=1825915

Bug 1825915: UPSTREAM: 90985: Set session scanning to manual to avoid discovering all iSCSI devices during login

---

test/extended/networking/internal_ports.go

Bug 1837108: Use HostIP on internal connectivity test for vsphere

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/admin.sh

Another alternate to https://github.com/openshift/origin/pull/24974

Bug 1833558: update test to be more resilient for oc adm policy add-sss-to-user changes

---

vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
vendor/k8s.io/kubernetes/pkg/volume/quobyte/quobyte.go
vendor/k8s.io/kubernetes/pkg/volume/scaleio/sio_client.go
vendor/k8s.io/kubernetes/pkg/volume/storageos/storageos_util.go

[4.3] Bug 1822487: UPSTREAM: 89794: Clean up event messages for errors

---

vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
vendor/k8s.io/kubernetes/pkg/volume/quobyte/quobyte.go
vendor/k8s.io/kubernetes/pkg/volume/scaleio/sio_client.go
vendor/k8s.io/kubernetes/pkg/volume/storageos/storageos_util.go

[4.4] Bug 1822488: UPSTREAM: 89794: Clean up event messages for errors

---

vendor/k8s.io/kubernetes/pkg/kubelet/container/helpers.go
vendor/k8s.io/kubernetes/pkg/kubelet/container/helpers_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go
vendor/k8s.io/kubernetes/test/e2e/node/BUILD
vendor/k8s.io/kubernetes/test/e2e/node/pods.go

This is a cherry-pick of #24841
Note: This includes an additional carry patch for 4.2 to fix the testfile ginkgo calls.

Bug 1840872: UPSTREAM: 88440: Report deleted pod status correctly

---

vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
vendor/k8s.io/kubernetes/pkg/volume/quobyte/quobyte.go
vendor/k8s.io/kubernetes/pkg/volume/scaleio/sio_client.go
vendor/k8s.io/kubernetes/pkg/volume/storageos/storageos_util.go

[4.2] Bug 1822486: UPSTREAM: 89794: Clean up event messages for errors

---

vendor/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
vendor/k8s.io/kubernetes/pkg/volume/quobyte/quobyte.go
vendor/k8s.io/kubernetes/pkg/volume/scaleio/sio_client.go
vendor/k8s.io/kubernetes/pkg/volume/storageos/storageos_util.go

[3.11] Bug 1822491: UPSTREAM: 89794: Clean up event messages for errors

---

vendor/k8s.io/kubernetes/pkg/controller/BUILD
vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
vendor/k8s.io/kubernetes/pkg/controller/controller_utils_test.go
vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
vendor/k8s.io/kubernetes/pkg/controller/job/job_controller.go
vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go

Bug 1843187: UPSTREAM: 91008: Do not swallow NotFound error for DeletePod in dsc.manage

---

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go

ref: https://github.com/kubernetes/kubernetes/pull/91500

Bug 1839098: UPSTREAM: 91500: reduce race risk in kubelet for missing KUBERNETES_SERVICE_HOST

---

cmd/watch-termination/main.go

100MB per file, 3 backups, max 28 days.

watch-termination: add log rotation

---

vendor/k8s.io/kubernetes/pkg/controller/BUILD
vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
vendor/k8s.io/kubernetes/pkg/controller/controller_utils_test.go
vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
vendor/k8s.io/kubernetes/pkg/controller/job/job_controller.go
vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go

4.5 cherry-pick of https://github.com/openshift/origin/pull/25060

[release-4.5] Bug 1843462: UPSTREAM: 91008: Do not swallow NotFound error for DeletePod in dsc.manage

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go

manual cherry-pick for https://github.com/openshift/origin/pull/25121.

Bug 1847368: [release-4.5]: UPSTREAM: 92166: fix: GetLabelsForVolume panic issue for azure disk PV

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go

manual cherry-pick for #25121.

Bug 1847419: [release-4.4] UPSTREAM: 92166: fix: GetLabelsForVolume panic issue for azure disk PV

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go

manual cherry-pick for https://github.com/openshift/origin/pull/25121 to get a 4.3 payload to test against ARO.
/hold

Bug 1848622: [release-4.3]: UPSTREAM: 92166: fix: GetLabelsForVolume panic issue for azure disk PV

---

glide.lock
glide.yaml
vendor/github.com/google/cadvisor/fs/fs.go
vendor/github.com/google/cadvisor/fs/fs_test.go
vendor/github.com/google/cadvisor/fs/types.go

Pulls in a cadvisor patch to fix the diskstats metrics on mapped devices
Upstream ref: https://github.com/google/cadvisor/pull/2575

Bug 1831908: bump cadvisor for incorrect diskstats fix

---

vendor/k8s.io/kubernetes/pkg/registry/core/service/allocator/storage/storage.go
vendor/k8s.io/kubernetes/pkg/registry/core/service/allocator/storage/storage_test.go
vendor/k8s.io/kubernetes/pkg/registry/core/service/portallocator/BUILD
vendor/k8s.io/kubernetes/test/integration/master/BUILD
vendor/k8s.io/kubernetes/test/integration/master/kube_apiserver_test.go

Upstream: https://github.com/kubernetes/kubernetes/pull/89937

Bug 1848379: UPSTREAM: 89937: portAllocator sync local data before allocate

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/create.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/fieldmanager.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/fieldmanager_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal/managedfields.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/internal/managedfields_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/structuredmerge.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/update.go
vendor/k8s.io/kubernetes/test/integration/apiserver/apply/apply_test.go

Pick of https://github.com/kubernetes/kubernetes/pull/92007.

Bug 1842660: 4.6: UPSTREAM: 91748: FieldManager: Reset if we receive nil or a list with one

---

cmd/watch-termination/main.go

We didn't notice when we got killed hard without ever seeing a SIGTERM.

watch-termination: create lock file on launch to catch every hard termination

---

vendor/k8s.io/kubernetes/pkg/kubeapiserver/authenticator/config.go

As designed in: https://github.com/openshift/enhancements/pull/142

only patch authenticators when there's no webhook authenticators

---

vendor/k8s.io/kubernetes/pkg/controller/BUILD
vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
vendor/k8s.io/kubernetes/pkg/controller/controller_utils_test.go
vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
vendor/k8s.io/kubernetes/pkg/controller/job/job_controller.go
vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go

4.4 cherry-pick of https://github.com/openshift/origin/pull/25060

[release-4.4] Bug 1843876: UPSTREAM: 91008: Do not swallow NotFound error for DeletePod in dsc.manage

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/vsphere/vclib/diskmanagers/vdm.go

Upstream PR: https://github.com/kubernetes/kubernetes/pull/90638
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1806034

Bug 1806034: UPSTREAM: 90638: Fix race in VSphere volume provisioning

---

test/extended/util/client.go
test/extended/util/framework.go

Manual cherry-pick of https://github.com/openshift/origin/pull/24828

[release-4.4] Bug 1829327: annotations exist, else forbidden: unable to validate

---

test/extended/templates/templateinstance_cross_namespace.go

/hold
feel free to lgtm if you are happy @adambkaplan 
I plan on running the e2e several times to at least get a warm fuzzy on addressing the timing window I'm speculating about

Bug 1844483: poll on deleted obj check; give controller finalizer deletes time to complete

---

vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller_test.go
vendor/k8s.io/kubernetes/pkg/controller/daemon/init_test.go
vendor/k8s.io/kubernetes/pkg/controller/daemon/update_test.go

Backporting https://github.com/kubernetes/kubernetes/pull/91915
/cc @soltysh

Bug 1843319: Fix DS expectations on recreate

---

test/extended/util/framework.go

Surface detailed error analysis in final error reported by ginkgo in the e2e's for waiting on the sample imagestreams in openshift
include direction on how to report possible outages with registry.redhat.io

BUILD-92: update WaitForOpenShiftNamespaceImageStreams with more detailed diagnostics

---

test/extended/router/grpc-interop.go
test/extended/router/h2spec.go
test/extended/router/http2.go

Manual cherry-pick of https://github.com/openshift/origin/pull/25243.

Bug 1854195: Disable HTTP/2 tests

---

publishing-kube-rules.yaml

defines Kube publishing rules for origin-4.6-kubernetes-1.18.3

---

pkg/network/node/egressip.go

Bug 1731905: [backport 3.11] SDN cannot add egress IP to team interface

---

test/extended/util/disruption/disruption.go

The Flakef function currently results in upgrade subtests being
flagged as full failures, when they should be logged as "passed,
but flaky in some form". If we pass but capture a flake, output
two TestCase entries into the JUnit XML (one passing, one failing)
which correctly triggers downstream tools to show the result as
a flake, not a failure.
Should dramatically simplify viewing of Upgrade jobs.

test: Report disruption flakes correctly in junit

---

vendor/k8s.io/kubernetes/pkg/controller/BUILD
vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
vendor/k8s.io/kubernetes/pkg/controller/controller_utils_test.go
vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
vendor/k8s.io/kubernetes/pkg/controller/job/job_controller.go
vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go

4.3 cherry-pick of https://github.com/openshift/origin/pull/25060

[release-4.3] Bug 1843877: UPSTREAM: 91008: Do not swallow NotFound error for DeletePod in dsc.manage

---

pkg/oc/cli/admin/diagnostics/diagnostics/cluster/network/setup.go

Bug 1763610: use proper version of PodLogOptions struct in diagnostics

---

vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller_test.go
vendor/k8s.io/kubernetes/pkg/controller/daemon/init_test.go
vendor/k8s.io/kubernetes/pkg/controller/daemon/update_test.go

backport of https://github.com/openshift/origin/pull/25208
/cc @soltysh

[release-4.5] Bug 1845242: Fix DS expectations on recreate

---

test/extended/router/metrics.go
vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler_test.go

FIx CI for 3.11

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/observe.sh

/assign @sallyom 
This is needed to land https://github.com/openshift/oc/pull/475

Fix oc observe tests

---

vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go
vendor/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller_test.go
vendor/k8s.io/kubernetes/pkg/controller/daemon/init_test.go
vendor/k8s.io/kubernetes/pkg/controller/daemon/update_test.go

backport of https://github.com/openshift/origin/pull/25208
/cc @soltysh

[release-4.4] Bug 1851407: Fix DS expectations on recreate

---

vendor/k8s.io/kubernetes/pkg/kubelet/eviction/BUILD
vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go
vendor/k8s.io/kubernetes/pkg/kubelet/eviction/helpers.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/runonce_test.go

Bug 1857083: Include pod /etc/hosts in ephemeral storage calculation for eviction

---

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_network_linux.go

This is a release-4.3 cherry-pick of https://github.com/openshift/origin/pull/25141

Bug 1845773: [release-4.3] kubelet: block non-forwarded packets from crossing the localhost boundary

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/basicresources.sh
test/extended/testdata/cmd/test/cmd/builds.sh
test/extended/testdata/cmd/test/cmd/edit.sh
test/extended/testdata/cmd/test/cmd/env.sh
test/extended/testdata/cmd/test/cmd/help.sh

e2e-cmd: fix the bits necessary for e2e-cmd to pass

---

test/extended/controller_manager/deploy_scale.go
test/extended/deployments/deployments.go

deploymentconfig: drop unnecessary conversions in tests

---

test/extended/operators/olm.go
test/extended/testdata/bindata.go
test/extended/testdata/olm/operatorgroup.yaml
test/extended/testdata/olm/subscription.yaml
test/extended/util/annotate/generated/zz_generated.annotations.go

we've been seeing timeouts with cockroach

Bug 1857928: switch to amq operator from cockroach for olm sanity test

---

test/extended/oauth/expiration.go

The test assumed the old token format, breaking when https://github.com/openshift/oauth-server/pull/50 merges.

e2e/oauth/expiration: support sha256 tokens

---

test/extended/util/annotate/annotate.go
test/extended/util/disruption/disruption.go
test/extended/util/test.go

Introduction of go.mod changed the file paths reported for reflection
and when we have differening build environments we might fail to
correctly apply categorization heuristics (for instance, -mod vendor
may not report the same path in both places).
Instead of doing simple string comparison, make module checks more
precise by allowing the following forms:
* base_path/full_module/package
* base_path/full_module@/package
* base_path/full_module@version/package

test: Fix inconsistencies in path reporting between Go versions

---

vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/cpu_manager.go
vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/cpu_manager_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/cm/internal_container_lifecycle.go

ref: kubernetes/kubernetes#90377
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

[release-4.5] Bug 1846453: UPSTREAM: 90377: fix exclusive CPU allocations being deleted at container restart

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_standard.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_zones.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_zones_test.go

Cherry-pick https://github.com/kubernetes/kubernetes/pull/89878

Bug 1860830: Ensure Azure availability zone is always in lower cases

---

test/extended/oauth/expiration.go
test/extended/oauth/token.go

Implementing https://github.com/openshift/enhancements/pull/420.
Depending on https://github.com/openshift/kubernetes/pull/305.

oauth: switch to sha256~ prefix

---

hack/verify-upstream-commits.sh
tools/rebasehelpers/commitchecker/commitchecker.go

backport of https://github.com/openshift/origin/pull/25367
/cc @sttts

[release-4.3] Fix commit checker

---

vendor/k8s.io/kubernetes/pkg/kubelet/eviction/BUILD
vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go
vendor/k8s.io/kubernetes/pkg/kubelet/eviction/helpers.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/runonce_test.go

Bug 1857081: Include pod /etc/hosts in ephemeral storage calculation for eviction

---

vendor/k8s.io/kubernetes/pkg/kubelet/eviction/BUILD
vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go
vendor/k8s.io/kubernetes/pkg/kubelet/eviction/helpers.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/runonce_test.go

Bug 1857080: Include pod /etc/hosts in ephemeral storage calculation for eviction

---

vendor/k8s.io/kubernetes/pkg/kubelet/pleg/generic.go
vendor/k8s.io/kubernetes/pkg/kubelet/pleg/generic_test.go

xref https://bugzilla.redhat.com/show_bug.cgi?id=1862194
xref https://github.com/kubernetes/kubernetes/pull/85983
/assign @mrunalp

[release-4.5] Bug 1862194: UPSTREAM: 85983: fix metrics kubelet_running_pod_count

---

test/extended/machines/cluster.go

@deads2k @sdodson 
https://bugzilla.redhat.com/show_bug.cgi?id=1870345

Bug 1870345: test: extended: only run new machines test against platforms that have machines

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

@marun 
xref https://bugzilla.redhat.com/show_bug.cgi?id=1861526

Bug 1861526: test: extended: reenable service account test disabled during rebase

---

test/extended/machines/cluster.go

We need to support running the e2e tests against AWS UPI for
example.

tests/cluster: Check for machinesets, not platforms

---

test/extended/images/layers.go

Use WaitForABuild and DumpBuildLogs to get more information about the build when it has some problems.
/cc @gabemontero

Bug 1871948: Use WaitForABuild helper instead of wait.Poll

---

vendor/k8s.io/kubernetes/pkg/kubelet/eviction/BUILD
vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go
vendor/k8s.io/kubernetes/pkg/kubelet/eviction/helpers.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/runonce_test.go

Bug 1857079: Include pod /etc/hosts in ephemeral storage calculation for eviction

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

Bug 1874281: enable again DR restore cluster after quorum loss

---

pkg/proxy/hybrid/proxy.go

When the ep is deleted before the svc in unidling proxy mode, the port
does not get deleted and remains stuck. This patch adds a new variable
pendingDeletion to hybrid proxier which ensures that the svc is removed
from usingUserspace and switchedToUserspace only after the deletion is
triggered from both OnServiceDelete and OnEndpointsDelete. This way the
order of whether the ep was deleted before svc or vice versa doesn't
matter anymore and the port gets safely removed.
Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>

[release-3.11] Bug 1870064: Port stuck open when ep deleted before svc in unidling mode

---

images/tests/Dockerfile.rhel

Bug 1874056: bump golang to 1.14

---

test/extended/machines/scale.go

more constrained version of https://github.com/openshift/origin/pull/25474
We found that we got valuable signal on this test, like https://bugzilla.redhat.com/show_bug.cgi?id=1870343

bug 1875586: make scaling test wait until the node can take workloads

---

test/extended/include.go
test/extended/tbr_health/OWNERS
test/extended/tbr_health/check.go
test/extended/util/annotate/generated/zz_generated.annotations.go

add a samples only verification to conformance/parallel

---

vendor/k8s.io/kubernetes/pkg/api/endpoints/util.go
vendor/k8s.io/kubernetes/pkg/api/endpoints/util_test.go
vendor/k8s.io/kubernetes/pkg/api/v1/endpoints/util.go
vendor/k8s.io/kubernetes/pkg/api/v1/endpoints/util_test.go
vendor/k8s.io/kubernetes/pkg/controller/endpoint/BUILD
vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go
vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller_test.go
vendor/k8s.io/kubernetes/pkg/printers/internalversion/printers.go
vendor/k8s.io/kubernetes/pkg/registry/core/endpoint/strategy.go

Updated version of https://github.com/openshift/origin/pull/25424 with additional fixes that improve networking performance in endpoints controller

[release-3.11] Bug 1870540: UPSTREAM: 94112: Improve diff check in endpoints controller syncService

---

pkg/network/node/ovscontroller.go
pkg/network/node/ovscontroller_test.go

backport of https://github.com/openshift/sdn/pull/105/commits/01789d2e93641ca5b23c0448aacd196acc9d71a8 and https://github.com/openshift/sdn/pull/105/commits/2da9083753e41e255f4e3e03f72274997b750d5c
/cc @juanluisvaladas

Bug 1790407: [3.11] Fix reinitialization of deny-all NetworkPolicy state on restart

---

test/extended/deployments/deployments.go
test/extended/deployments/util.go

Bug 1868061: switch watchtools.UntilWithoutRetry to watchtools.UntilWithSync in deployment tests

---

test/extended/operators/images.go

When running the test
[sig-arch] Managed cluster should ensure pods use downstream images from our release image with proper ImagePullPolicy
in parallel with another test running a must gather causes this test to faile
fail [github.com/openshift/origin@/test/extended/operators/images.go:161]: Sep  3 13:35:56.971: Pods found with invalid container image pull policy not equal to IfNotPresent: openshift-must-gather-t6z56/must-gather-rp75x/copy imagePullPolicy=Always
openshift-must-gather-t6z56/must-gather-rp75x/gather imagePullPolicy=Always
openshift-must-gather-zv77v/must-gather-nwn8c/copy imagePullPolicy=Always
openshift-must-gather-zv77v/must-gather-nwn8c/gather imagePullPolicy=Always
add must-gather namespace to the ignored namespaces so that this does not record an additional failure …

Bug 1878173: running test of ImagePullPolicy in parallel with must-gather fails

---

pkg/network/node/vxlan_monitor_test.go

backport of https://github.com/openshift/sdn/pull/186
/assign @juanluisvaladas

Bug 1878796: vxlan_monitor_test: fix flake

---

test/extended/deployments/util.go

Bug 1871944: use map to de-duplicate unterminatedPods

---

test/extended/etcd/leader_changes.go

Bug 1880683: test/extended/etcd: make excessive leader_change test actionable

---

test/extended/testdata/bindata.go
test/extended/testdata/builds/build-pruning/default-group-build-config.yaml
test/extended/testdata/builds/build-pruning/default-legacy-build-config.yaml
test/extended/testdata/builds/build-pruning/errored-build-config.yaml
test/extended/testdata/builds/build-pruning/failed-build-config.yaml

See https://github.com/openshift/cluster-samples-operator/pull/326#issuecomment-697045304

Bug 1881573: remove use of imminent SCL EOL images

---

cmd/openshift-tests/provider.go
test/extended/util/cloud/cloud.go

Backport of #25052 to release-4.4
/assign @knobunc

Bug 1842653: [4.4] All NetworkPolicy tests currently being skipped on openshift-sdn

---

vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go
vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go
vendor/k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector_test.go
vendor/k8s.io/kubernetes/test/integration/garbagecollector/garbage_collector_test.go

[release-4.3] Bug 1880293: OpenShift APIs become unavailable for more than 15 minutes

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go

Bug 1877346: Fix bug for inconsistent lists served from etcd

---

vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go
vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller_test.go
vendor/k8s.io/kubernetes/pkg/registry/core/endpoint/strategy.go
vendor/k8s.io/kubernetes/test/integration/endpoints/endpoints_test.go
vendor/k8s.io/kubernetes/test/integration/endpoints/main_test.go

4.6 PR: https://github.com/openshift/kubernetes/pull/318

Bug 1882030: UPSTREAM: 94112: Remove canonicalization of endpoints by endpoints controller for better comparison

---

test/extended/cli/mustgather.go

Bug 1861746: perform oauthaccesstokens only on upgraded clusters

---

test/extended/apiserver/kubeconfigs.go

Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

Bug 1882454: test/apiserver: replace centos by ubi

---

pkg/test/ginkgo/synthentic_tests.go

like https://github.com/openshift/origin/pull/25564, but for all test namespaces

bug 1884252: add test for systemd timeouts

---

test/extended/util/framework.go

Trying to debug cases like https://prow.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-4.6/1311551365771694080

Bug 1884229: test: add more debug info when we fail to wait for service account

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/errors.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/reflector.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/reflector_test.go

Bug 1877346: KubeAPIErrorsHigh firing due to too large resource version

---

test/extended/apiserver/graceful_termination.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Counterpart of https://github.com/openshift/kubernetes/pull/379.

Bug 1882750: extended/apiserver: add test looking out for GracefulTerminationTimeout events

---

test/extended/include.go
test/extended/pods/systemd.go
test/extended/util/annotate/generated/zz_generated.annotations.go

@deads2k @nstielau 
For identifying bz https://bugzilla.redhat.com/show_bug.cgi?id=1879152 in test runs

test: extended: add Late systemd timeout test

---

vendor/k8s.io/kubernetes/pkg/kubelet/server/server_test.go
vendor/k8s.io/kubernetes/pkg/registry/core/pod/rest/log.go
vendor/k8s.io/kubernetes/pkg/registry/core/pod/rest/subresources.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/features/kube_features.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/registry/generic/rest/streamer.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/registry/generic/rest/streamer_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/client-go/transport/spdy/spdy.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go

run into some minor conflicts while moving this to Origin.

Bug 1791520: CVE-2018-1002102: Unvalidated redirect

---

test/extended/util/framework.go

test: add error output for build logs

---

test/extended/util/framework.go

This picks #25331 
/assign @damemi

Bug 1860789: test: Report an error message when a pod fails in a cmd test

---

images/hello-openshift/Dockerfile.rhel

hello-openshift: fix base images

---

pkg/test/ginkgo/synthentic_tests.go

Adding the test here will allow us to have output on upgrade tests, e2e, and e2e-serial.

add event monitor test for kube-apiserver not being shutdown gracefully

---

test/extended/operators/cluster.go

The crashlooping test is also detecting pods that were pending for the entire run of the test and fails if such a pod is detected. I think the logic behind it is wrong: it creates the list of pending pods every 5 seconds so at the end of the test it is incorrect to claim the pod was pending entire time. I'm adding a time stamp comparison that should make this conclusion valid.
Also -- I don't think it's completely corect to refer to the pods by "namespace/pod_name" in this case: some pods might live for really short time and even get re-created between the polls. Hence the change to use UID instead.

test: improve handling of pending pods crashloop detection test

---

vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go
vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller_test.go
vendor/k8s.io/kubernetes/pkg/registry/core/endpoint/strategy.go
vendor/k8s.io/kubernetes/test/integration/endpoints/endpoints_test.go
vendor/k8s.io/kubernetes/test/integration/endpoints/main_test.go

4.5 PR: https://github.com/openshift/origin/pull/25541
4.6 PR: https://github.com/openshift/kubernetes/pull/318

Bug 1882033: UPSTREAM: 94112: Remove canonicalization of endpoints by endpoints controller for better comparison

---

README.md

fix typo in word: strategy

---

vendor/k8s.io/kubernetes/pkg/controller/volume/expand/BUILD
vendor/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller.go
vendor/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller_test.go
vendor/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1879192
This is cherry pick of https://github.com/openshift/kubernetes/pull/347
cc @openshift/sig-storage

Bug 1879192: Make offline volume expansion tests more robust

---

.ci-operator.yaml

Enable build root from repo

---

test/extended/image_ecosystem/s2i_php.go
test/extended/util/annotate/generated/zz_generated.annotations.go

@adambkaplan @sallyom let's see if this still skips cakephp in the e2e's while we wait on the upstream fix
@sallyom let me know what you see when you run locally with this

move cakephp e2e skip down a level to make openshift-tests happy

---

test/extended/builds/build_pruning.go
test/extended/templates/templateinstance_readiness.go

Bug 1892775: disabling cakephp until upstream problem addressed: bugzilla 1891989

---

test/extended/router/router.go

Fixes the wrong file path(/var/lib//var/lib/haproxy/conf/haproxy.conf) for the CI test to pass

Bug 1890901: Fixes the wrong file path(/var/lib//var/lib/haproxy/conf/haproxy.conf) for the CI test to pass

---

test/extended/cli/debug.go

/assign @sallyom 
since you looked at the PR which was changing this
/assign @wking 
since you complained in a good way :wink:

Bug 1896188: bump wait timeout for build completion in oc debug test

---

cmd/openshift-tests/storagecaps.go

Reword CNV as OpenShift Virtualization

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware_test.go

Bug 1852695: CVE-2020-8559 compromised node could escalate to cluster level privileges

---

vendor/k8s.io/kubernetes/pkg/controller/podautoscaler/replica_calculator.go
vendor/k8s.io/kubernetes/pkg/controller/podautoscaler/replica_calculator_test.go

Bug 1899721: HPA: Ignore deleted pods.

---

test/extended/util/disruption/imageregistry/imageregistry.go

When the tests are run outside of the cluster (usually they are), the tests cannot access the registry service. They also cannot rely on the registry route, because the registry route is disabled by default.
To check availability of the registry, tests can create additional route for the registry service and monitor it during upgrades.

Bug 1900030: Fix monitoring availability of image registry

---

test/extended/authorization/rbac/groups_default_rules.go

re https://github.com/openshift/cluster-authentication-operator/pull/381
cc @sttts @deads2k

e2e: add useraccessoauthtokens RBAC

---

test/extended/cli/explain.go
test/extended/util/annotate/generated/zz_generated.annotations.go

/assign @sttts @smarterclayton

Update oc explain tests

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware_test.go

not clean, minor changes applied.

Bug 1852692: CVE-2020-8559  compromised node could escalate to cluster level privileges

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/net/http_test.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware_test.go

Bug 1852694: CVE-2020-8559 compromised node could escalate to cluster level privileges

---

test/extended/images/append.go

The tools image may have different layers over different releases
or build types (CI generates more than OCP right now). Make the
calculation relative to the tools image and double check that shell
image matches it.

Bug 1905232: Append image test should be relative to the tools image

---

test/extended/authorization/rbac/groups_default_rules.go

Related to https://github.com/openshift/origin/pull/23975
/assign @spadgett @bparees

Bug 1906713: Add consolequickstarts to list of console resource exceptions

---

test/extended/apiserver/apply.go
test/extended/etcd/etcd_storage_path.go
test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/client.go

Backport of #25652 to ensure against regression in 4.6
/cc @sttts @p0lyn0mial

[release-4.6] Add e2e testing of server-side apply for openshift types 

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

xref https://bugzilla.redhat.com/show_bug.cgi?id=1908675

Bug 1908675: Re-Enable fsgroup policy test

---

test/extended/images/info.go

Bug 1904679: drop docker.io from image tests

---

test/extended/authorization/rbac/groups_default_rules.go

Add consoleplugins to list of console resource exceptions

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/basicresources.sh

/assign @ingvagabund 
To unblock https://github.com/openshift/oc/pull/693

Bug 1914894: make cmd tests more resilient

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/basicresources.sh

This is needed for https://github.com/openshift/oc/pull/693

Bug 1914894: make tests more resilient

---

test/extended/cli/debug.go

Bug 1896188: wait for RC presence before starting debug session

---

vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/apf_filter.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
vendor/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset_test.go

**What type of PR is this?**
/kind bug
clean up executing request on panic
**Special notes for your reviewer**:
**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
```docs
```

Bug 1912566: UPSTREAM: 97206: clean up executing request on panic

---

test/extended/cli/debug.go

Bug 1896188: bump build timeout to 10m and deploy to 2m in oc debug

---

go.mod
go.sum
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
vendor/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go
vendor/k8s.io/kubernetes/test/e2e/scheduling/predicates.go
vendor/k8s.io/kubernetes/test/e2e/scheduling/priorities.go
vendor/modules.txt

bug 1870342: UPSTREAM: 94684: e2e: Pod should avoid nodes that have avoidPod annotation: clean remaining pods

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/builds.sh
test/extended/testdata/cmd/test/cmd/images.sh
test/extended/testdata/cmd/test/cmd/printer.sh

This is a followup to https://github.com/openshift/origin/pull/25746 I missed some instances which were causing this test to fail consistently.

Bug 1904684: fix missing bits in images.sh tests

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/images.sh

The test was looking for an inaccessible image.

test: Use wildfly 20 since 19 can no longer be accessed at quay

---

test/extended/router/scoped.go

Most routers run in HA configuration, so accepting just a single
200 response is not sufficient if the other router is trailing.
Change the test to verify we get 5 successive in a row before
returning.
Identified by a single flake in https://prow.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-sdn-network-stress-4.7/1353930135601942528

Bug 1921857: Router should require multiple 200 responses (hit multiple instances of the router) before continuing the test

---

go.mod
go.sum
test/extended/util/annotate/generated/zz_generated.annotations.go
vendor/k8s.io/kubernetes/test/e2e/apimachinery/BUILD
vendor/k8s.io/kubernetes/test/e2e/apimachinery/request_timeout.go
vendor/k8s.io/kubernetes/test/e2e/scheduling/ubernetes_lite.go
vendor/modules.txt

Pulling the change from https://github.com/openshift/kubernetes/pull/545, we need to debug why this test is failing

Bug 1896558: bump(openshift/kubernetes): fix flaking multi-AZ test

---

test/extended/image_ecosystem/OWNERS
test/extended/image_ecosystem/sample_repos.go

https://github.com/openshift/openshift-apiserver/pull/167#issuecomment-775524042
https://github.com/openshift/cluster-samples-operator/pull/355

Bug 1926977: adjust route host for redis/nodejs to accomodate new apiserver restrictions

---

test/extended/authorization/scc.go

Errors during test should hard fail (no tolerance). This change is
due to 44% of jobs failing in master on this, once we fix we can
revert.

test: SCC early failures (before suite) flake until fixed

---

test/extended/util/disruption/controlplane/controlplane.go

4.7 brought us to a no disruption on upgrade state for the control
plane. In 4.8 lock that requirement in so that future changes do
not regress us further.

test: AWS and Azure should tolerate no API disruption

---

pkg/monitor/operator.go

Make it consistent with node after improvements there.

monitor: Improve cluster operator transition message

---

test/extended/prometheus/prometheus.go

The alert is firing because cleanup doesn't appear to be happening
in the correct order (so the apiservice object exists while the
deployment is torn down). Disable for now with a tracked and open
bug.

test: Exclude AggregatedAPIDown alert caused by test cleanup

---

cmd/openshift-tests/e2e.go

Termination of the kube-apiserver outside of the suite that is currently running should be a flake, and when the test infra is told to ignore events before a specific time it should do so. Add the test into the upgrade invariants since this would exclude the test from checking upgrades otherwise.
Mitigates impact of pre-install bug in https://bugzilla.redhat.com/show_bug.cgi?id=1928946 but does not fix the issue.

test: Graceful termination invariant should separate pre-suite events

---

cmd/openshift-tests/e2e.go
cmd/openshift-tests/upgrade.go
pkg/synthetictests/apiserver.go
pkg/synthetictests/event_junits.go
pkg/synthetictests/kubelet.go
pkg/synthetictests/networking.go
pkg/synthetictests/operators.go

just for package organization and ability to find stuff.

straight moves of the various synthentic tests

---

test/extended/cli/explain.go

Looks like bindata didn't need to be updated
https://bugzilla.redhat.com/show_bug.cgi?id=1891124

Bug 1891124: Skip MCO CRD checks for ibmcloud provider in cli testing

---

test/extended/operators/daemon_set.go

Make sure that DS pod template node selector matches master. This ensures DS with master and os="linux" are being skipped too.
OVN's `ovnkube-master` has 
```
nodeSelector:
node-role.kubernetes.io/master: ""
beta.kubernetes.io/os: "linux"
```
so it doesn't get skipped (as this nodeSelector doesn't match just master label). Instead, this nodeSelector should be a label set and `node-role` needs to be the requirement.

Skip maxUnavailable check on DS on masters with complex label selectors

---

pkg/synthetictests/event_junits.go
pkg/synthetictests/kubelet.go
test/extended/apiserver/graceful_termination.go

The invariant test should fail the e2e run if a disruption occurs during the test. The e2e tests that the invariant was based on are
still useful for picking up install time failures, but they need to not fail (limit start time doesn't exclude install).
For now, failures for these invariants is in the invariant (scoped to the suite), while detection of flakes is the e2e test. We probably
need an openshift-tests run that checks install time invariants but that needs a bit of design work, and right now this failure at
install is not impacting cluster health.
https://github.com/openshift/origin/pull/25932 was the predecessor but confused the cause and solution (invariants are already scoped to the suite execution)

Bug 1928946: Move apiserver graceful failure responsibility to invariant

---

test/extended/operators/resources.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Enforce the rules we define in CONVENTIONS.md

test: Prevent limits from being set on pods and enforce requests

---

test/extended/operators/resources.go

Copycat of https://github.com/openshift/origin/pull/25982 for https://bugzilla.redhat.com/show_bug.cgi?id=1940876

test: grant ovirt-csi-driver an exception for not having requests

---

test/extended/etcd/etcd_storage_path.go
test/extended/util/client.go

fix CLI and etcd tests to work with the new format of oauth{access,authorize} tokens

---

test/extended/builds/digest.go

Verify that the pushed image has the gzip-ed layer MIME type for
docker v2schema2.

Bug 1905095: Verify layer MIME types in images

---

test/extended/router/idle.go

This is a manual backport of PR #25924.

[release-4.7] Bug 1941574: test/extended/router/idle: skip test on virt platforms

---

test/extended/cli/rsh.go
test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/basicresources.sh
test/extended/testdata/cmd/test/cmd/image-lookup.sh

Fix tests to allow landing k8s bump in oc

---

test/extended/operators/daemon_set.go

[Fixed][1] in openshift/cluster-network-operator#992.  This is the last bug, so I've torn out the `knownBroken` and `bugsAgainstBrokenDaemonSets` stuff, because we are unlikely to want to regress.  And if we end up wanting to regress, that code is still there in the Git history.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1933159#c4

test/extended/operators/daemon_set: Multus bug has been fixed

---

test/extended/baremetal/hosts.go

This PR adds some more detailed expectations to the existing baremetal platform tests. It also provides some additional utility methods to make easier writing expectations on unstructured fields.

Baremetal platform tests refinement

---

test/extended/operators/operators.go

E.g. [bug#1928141][1] has users who are confused by `Upgradeable=Unknown`, of which we currently have [a few][2]:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-4.8/1375324509623554048/artifacts/e2e-aws/clusteroperators.json | jq -r '.items[] | .metadata.name as $n | .status.conditions[] | select(.status == "Unknown") | $n + " " + .type + " " + .reason'
kube-storage-version-migrator Upgradeable NoData
openshift-controller-manager Upgradeable NoData
service-ca Upgradeable NoData
```
This commit adds a post-install guard to reject as surprising any `Upgradeable!=True` conditions.  We should be upgradeable immediately post-install.  Not setting an `Upgradeable` condition is still fine, and is equivalent …

Bug 1948021: test/extended/operators: Require Upgradeable=True or unset for "start all core operators"

---

Makefile
e2echart/e2e-chart-template.html
test/extended/testdata/bindata.go

Set a minimum width to e2e-intervals chart by default

---

test/extended/single_node/topology.go

SNO topology: the oauth-server should only have a single replica now

---

test/extended/router/h2spec.go

Increase the dial timeout and retry the tests if they fail.

Bug 1949978: test/extended/router: h2spec increase timeout and retry tests

---

pkg/monitor/monitor.go

We don't know exactly how long a single sample condition lasted, but given our sampling interval, we can assume it lasted at least one sample interval and that is better than zero duration.

ensure that sampled conditions always have a range of time in their event interval

---

pkg/monitor/event.go

Make it slightly easier to detect long pulls.

monitor: Add pull time to pulled events for analysis

---

test/extended/builds/run_fs_verification.go
test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/basicresources.sh
test/extended/testdata/cmd/test/cmd/testdata/application-template-dockerbuild.json
test/extended/testdata/cmd/test/cmd/testdata/statefulset.yaml
test/extended/testdata/cmd/test/cmd/testdata/templates/template_required_params.yaml
test/extended/testdata/cmd/test/cmd/testdata/test-replication-controller.yaml
test/extended/testdata/cmd/test/cmd/testdata/test-stream.yaml
test/extended/testdata/roles/policy-roles.yaml
test/extended/testdata/stable-busybox.yaml
test/extended/testdata/test-replication-controller.yaml

Bug 1848408: fix validation issues in test files

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/images.sh

This is a followup to https://github.com/openshift/origin/pull/26082 which broke `images.sh` test.

Bug 1949050: fix images.sh script

---

pkg/monitor/operator.go

We recently had a PR that made the operator perma-degraded and CI didn't show it.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-kube-apiserver-operator/1073/pull-ci-openshift-cluster-kube-apiserver-operator-master-e2e-aws-serial/1384229570948894720

monitor: mark the starting point for clusteroperators

---

test/extended/router/idle.go

- This is a manual backport of PR #25924 to 4.6.
- The check for kubevirt has been omitted as that platform type was only available in 4.7.

[release-4.6] Bug 1941577: test/extended/router/idle: skip test on virt platforms

---

pkg/test/ginkgo/cmd_runsuite.go
pkg/test/ginkgo/podanalysis.go

bug 1952473: Dump pod displacement during upgrade

---

test/extended/operators/cluster.go

The marketplace operator deploys default CatalogSources in the openshift-marketplace namespace.
These CatalogSource have polling feature, [eg](https://github.com/operator-framework/operator-marketplace/blob/master/defaults/01_redhat_operators.cr.yaml#L15-L16)
that poll for updates at regular intervals. In the begining of every interval, a new "update" pod
is [created](https://github.com/operator-framework/operator-lifecycle-manager/blob/d980191ecdb848c6538b721906dfc993e86edd6f/pkg/controller/registry/reconciler/grpc.go#L203) which is [removed immediately](https://github.com/operator-framework/operator-lifecycle-manager/blob/d980191ecdb848c6538b721906dfc993e86edd6f/pkg/controller/registry/reconciler/grpc.go#L297-L299)
if there is no difference between the image digest of the fist pod. …

Bug 1949991: Ignore Catalog update pods in openshift/conformance/parallel

---

vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_executor.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1951663

Bug 1951663: Fix volume loop bugs

---

test/extended/authorization/scc.go

The presence of the LimitSuiteToStartTime flag should both constrain
when the test starts AND flag pre-test failures as flakes. This is
used by disruptive jobs that do their own invariant testing and don't
want our generic tests to look too far back.
Mitigates https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/18229/rehearse-18229-periodic-ci-openshift-release-master-nightly-4.8-e2e-aws-upgrade-rollback-oldest-supported/1389336340990005248

test: Suppress the SCC failure when a limit is present

---

test/extended/pods/priorityclasses.go
test/extended/util/annotate/generated/zz_generated.annotations.go

In order to avoid conditions like https://github.com/openshift/cluster-network-operator/pull/994
cc @smarterclayton @soltysh @damemi @ingvagabund

Bug 1957295: All platform pods should have system-* or openshift-user-critical priority class

---

examples/sample-app/github-webhook-example.json
test/extended/builds/clone_git_protocol.go
test/extended/builds/controllers.go
test/extended/images/imagechange_buildtrigger.go
test/extended/testdata/bindata.go
test/extended/testdata/builds/test-build-revision.json
test/extended/testdata/builds/test-build.yaml
test/extended/testdata/builds/webhook/generic/testdata/push-generic-envs.json
test/extended/testdata/builds/webhook/generic/testdata/push-generic-envs.yaml
test/extended/testdata/builds/webhook/generic/testdata/push-generic.json
test/extended/testdata/builds/webhook/github/testdata/pushevent-not-master-branch.json
test/extended/testdata/builds/webhook/github/testdata/pushevent.json
test/extended/testdata/cmd/test/cmd/env.sh
test/extended/testdata/cmd/test/cmd/testdata/test-bc.yaml
test/extended/testdata/cmd/test/cmd/testdata/test-buildcli.json
test/extended/testdata/long_names/fixture.json
test/extended/testdata/run_policy/serial-latest-only-bc.yaml
test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/proxy.go
test/integration/testdata/test-buildcli-beta2.json
test/integration/testdata/test-buildcli.json

Replace git:// urls with https:// urls for all tests

Bug 1936974: Access git over https for tests

---

test/extended/cli/mustgather.go

Removing the oc image calculations which we grew in 17b5a92349
(support old and new must-gather output, 2019-09-04, #23724).  This
pivot avoids failing on:
```go
imageId, ok := imageutil.ResolveLatestTaggedImage(stream, "latest")
o.Expect(ok).To(o.BeTrue())
```
like [this job][1] did.  Checking the contents of that job's must-gathers:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_oc/833/pull-ci-openshift-oc-master-e2e-metal-ipi-ovn-ipv6/1396775908324413440/artifacts/e2e-metal-ipi-ovn-ipv6/gather-must-gather/artifacts/must-gather.tar | tar -tvz | head -n5
drwx------ 1001210000/root   0 2021-05-24 05:38 .
-rw------- 1001210000/root 3406540 2021-05-24 05:38 event-filter.html
-rw------- 1001210000/root  758413 2021-05-24 …
```

Bug 1960758: test/extended/cli/mustgather: Local-only getPluginOutputDir

---

test/extended/cli/admin.go

Bug 1968558: properly remove project after test ends

---

test/extended/single_node/topology.go

This test only tested deployments until now, now it will also test StatefulSets
Also removed openshift-monitoring from allowedToFail list because all its components now use a single replica

Add statefulsets to single-replica topology test

---

go.mod
go.sum
vendor/github.com/google/cadvisor/container/common/helpers.go
vendor/github.com/google/cadvisor/manager/manager.go
vendor/modules.txt

Signed-off-by: Harshal Patil <harpatil@redhat.com>

Bug 1950993: Replace cadvisor with openshift cadvisor fork

---

test/extended/dr/OWNERS
test/extended/etcd/OWNERS

test/extended: add etcd OWNERS

---

test/integration/newapp_test.go

React to changes from openshift/ruby-hello-world#125

Update ruby-hello-world images

---

vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/network/hostport/hostport_syncer.go

Implement the same mechanism used by kubelet in the hostPortManager to delete stale UDP conntrack entries for HostPorts.
Signed-off-by: Antonio Ojea <aojeagar@redhat.com>

Bug 1946593: Delete conntrack HostPort UDP entries

---

test/extended/etcd/etcd_storage_path.go

remove apiextensions.k8s.io/v1beta1 and admissionregistration.k8s.io/v1beta1 from etcd tests

---

test/extended/authorization/rbac/groups_default_rules.go

[release-4.6] Bug 1977093: Add consolequickstarts and consoleplugins extensions to the authenticated rules

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

/assign @ravisantoshgudimetla 
/hold 
to ensure metal is green, since that's where it was flaking the most before

Bug 1957886: re-enable TTLAfterFinished test job

---

test/extended/builds/pipeline_origin_bld.go

bot failed picking from 4.7:  https://github.com/openshift/origin/pull/26296#issuecomment-872494067

Bug 1978442: comment out multi-namespace jenkins pipeline templates test; moving it to jenkins client plugin in-repo e2e's

---

pkg/synthetictests/operators.go

To make it more clear that this test is covering behavior from the whole run, using the oldest event `.from` and the youngest event `.to` to bracket the measured region.

pkg/synthetictests/operators: Set duration for operator-state transitions

---

test/extended/single_node/topology.go

Update the test/extended/single_node/topology.go single-node validation
logic that allows the PackageServer Deployment resource to be more than
one replica when running tests.
OLM will be moving that component from the CVO payload to a second-level
Operator that reads the Infrastructure cluster singleton resource and
propagates the HA/non-HA expectations to the PackageServer CSV resource.

test/extended: Remove the failure allowed logic in the cluster topology SNO test

---

test/extended/util/disruption/frontends/frontends.go

This change allows disruption to occur on OVN during upgrades,
see https://bugzilla.redhat.com/show_bug.cgi?id=1983829.

disruption: allow on OVN during upgrade 

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

xref: https://bugzilla.redhat.com/show_bug.cgi?id=1908677

bug 1908677: reenable SCTP Host Port test

---

pkg/synthetictests/event_junits.go
pkg/synthetictests/events.go
pkg/synthetictests/events_test.go

Based on @deads2k work #26173.

Do not allow an excessive count of an individual event: they indicate a failure

---

pkg/network/node/iptables.go

sdn PR https://github.com/openshift/sdn/pull/316

[release 3.11] Bug 1979216: when assigning and releasing egressIP try more than once before failing

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

Bug 1986003: Disable oc adm storage-admin and idle tests

---

test/extended/cli/observe.go

To land https://github.com/openshift/oc/pull/890
/assign @atiratree

Bug 1986003: Temporarily disable oc observe single test

---

test/extended/operators/olm.go

Signed-off-by: Daniel Sover <dsover@redhat.com>
supersedes #26326

Bug 1981582: [release-4.6] use vpa package and add debug logs to olm test

---

pkg/synthetictests/duplicated_events.go

addressing comments from https://github.com/openshift/origin/pull/26380

tidy up the duplicate event handling

---

vendor/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go

(oops, filed against ose before, refiling against origin now)
Using the mutex in `proxier.Sync()` to protect `proxier.changesPending` means that a call to `proxier.Sync()` can end up blocking waiting for a call to `proxier.syncProxyRules()` to finish, which can take a long time.
In particular, in a large cluster `Sync()` will get called thousands of times during startup, and some of those calls will block waiting on `syncProxyRules()` calls, which may take a few seconds, and "thousands of times" times "a few seconds" can add up to 10 or 20 minutes of delays in synchronizing.
Fix this by using atomics to set/get `changesPending` rather than fighting with `syncProxyRules()` for the mutex.
----
fixup to https://github.com/openshift/origin/pull/25641; this is fallout from our backporting the …

Bug 1981736: Fix a lock contention problem in the proxy

---

pkg/synthetictests/duplicated_events.go
pkg/synthetictests/duplicated_events_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1994113

Bug 1994113: exclude local volume conflicts

---

pkg/synthetictests/duplicated_events.go

Several have been fixed, and we've identified a few new ones.

Bug 1993985, Bug 1993980, Bug 1990041: duplicated events: update list of known issues

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

Bug 1989423: Enable back HAProxy idle service connect test

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

/cc @alexanderConstantinescu @abhat

Bug 1994927: rearrange some test annotations for proper bookkeeping

---

pkg/synthetictests/duplicated_events.go

Bug and Jira were created to track future optimizations.
cc @lilic @bparees 

ETCD-234: pkg/synthetictests: add etcd quorum-gaurd duplicate events to known problems

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

Bug 1989417: bring back oc adm storage-admin test

---

test/extended/operators/olm.go

e2e.NodeOSArchIs and friends do not detect the node arch automatically.
This is a follow-up to https://github.com/openshift/origin/pull/26422 which did not work as intended.
/cc @anik120
/cc @Prashanth684
/assign @timflannagan

Bug 1995198: operators: properly skip OLM test on arm64

---

test/extended/authentication/OWNERS
test/extended/authorization/OWNERS
test/extended/oauth/OWNERS

test/extended[auth*,oauth]: configure OWNERS

---

pkg/test/ginkgo/cmd_runsuite.go

During our TRT stand-up, David pointed out the extremely high pass rates
of upstream kube tests, but those same tests in OpenShift fail quite a
bit. There's a theory that perhaps some of the OpenShift tests like
builds use up so much I/O and other resources that they introduce
instability.

Run k8s test separately from OpenShift tests

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

This PR adds tests, required internet access and fails in disconnected environment, into the [Skipped:Disconnected] list.
This PR is backport of https://github.com/openshift/origin/pull/26051

[release-4.8] Bug 1989402: Add tests required internet into Skipped:Disconnected list

---

test/extended/operators/resources.go

https://bugzilla.redhat.com/show_bug.cgi?id=1940876 has been fixed, this
can be removed.

Remove exception for ovirt resource requests

---

test/extended/util/test.go

leverages https://github.com/openshift/kubernetes/pull/984 .  I think these can merge in any order.

add disable-scc label to kube e2e tests

---

test/extended/etcd/etcd_storage_path.go

Upstream runs this as integration test, but we do as e2e. Hence, nodes can be deleted.

Bug 2008926: etcd-storage-test: mark node ready to save it for 5min from cloud provider

---

test/extended/cli/explain.go

https://bugzilla.redhat.com/show_bug.cgi?id=1991980

Bug 1991980: Skipped non-standard openshift installed crd testing for ibmcloud

---

pkg/synthetictests/duplicated_events.go
pkg/synthetictests/duplicated_events_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2009823

This would make CI for 4.10 in vSphere environment wee bit happier

---

test/extended/networking/endpoint_admission.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Updates the RestrictedEndpointAdmissions e2e test to test EndpointSlices as well.
Requires https://github.com/openshift/kubernetes/pull/899

improve RestrictedEndpointsAdmission test

---

test/extended/image_ecosystem/s2i_perl.go

Skipping the Hot Deploy perl image test for ARM64
https://github.com/openshift/ocp-on-arm/issues/3
/cc @gabemontero 
/cc  @yselkowitz

Skipping test "[sig-devex][Feature:ImageEcosystem][perl][Slow] hot deploy for openshift perl image hot deploy should work" for ARM64

---

test/extended/util/disruption/controlplane/controlplane.go

Currently the tests tolerate 8% API disruption on <4.8 clusters and 0% API disruption on
\>=4.8 azure,aws,gce clusters
This test makes it so no matter what version / cloud provider is used, if the cluster control
plane topology is single node, then 15% API disruption is allowed during an upgrade. This is
because there is no way to avoid disruption on single-node topologies, but we would still
like to make sure that we don't regress to too much downtime.

Tolerate API downtime in upgrade disruption tests on single-node topologies

---

test/extended/oauth/client_secret.go

The tests currently fetch a route and use its status.Ingress[0].Host to
find the oauth issuer. This route doesn't exist in the Hypershift
architecture, as the oauth server doesn't run in-cluster. Use the oauth
discovery information from the kube-apiserver instead, just like `oc`
does.
/assign @stlaz 
/cc @csrwng

Oauth server tests: Get Oauth issuer url from discovery instead of route

---

test/extended/apiserver/resiliency.go
test/extended/operators/cluster.go

Extend the test to validate that pods aren't getting restarted during the API outage.

Bug 1999561: Extend API rollout resiliency test to validate pods restart during the rollout

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

We don't support this setup in our CI.

Disable topology tests for vSphere in-tree storage plugin

---

pkg/monitor/write_job_run_data.go
pkg/test/ginkgo/cmd_runsuite.go

This will make it a little bit easier to add pre-rendered metrics display.

refactor writing data artifacts without behavior change

---

test/extended/cli/env.go
test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/basicresources.sh
test/extended/testdata/test-buildcli.json
test/extended/util/annotate/generated/zz_generated.annotations.go

Moving another section of basicresources.sh to Go tests

Bug 1992596: e2e/cli: Add env tests

---

test/extended/cli/observe.go

Currently, the tests always fail if a different service ip range is used
which is always the case in Hypershfit clusters.

CLI tests: Softcode the kubernetes.default cluster IP

---

test/extended/prometheus/OWNERS

Signed-off-by: Jan Fajerski <jfajersk@redhat.com>

Refresh prometheus OWNERS

---

test/extended/util/disruption/frontends/frontends.go

The frontends tests were missed on 6eb75dc58c2c6a090808ac9d9053272853d847c2,
this makes the same change to them as well

Fix single-node frontends disruption test tolerated disruption %

---

test/extended/baremetal/OWNERS

Refresh baremetal owners list with the latest contributors

Update baremetal tests owners

---

test/extended/operators/clusteroperators.go

Allow operator-lifecycle-manager-packageserver to not define related objects when external controlplane

---

test/extended/util/disruption/imageregistry/imageregistry.go

This disruption can not be avoided on single-node clusters during upgrade

Allow disruption in image-registry availability during single node upgrades

---

test/extended/cli/explain.go

OC explain should contain proper spec+status for CRDs: Skip some resources when controlplane is external

---

test/extended/operators/daemon_set.go

The test allows DaemonSets to ignore this rule if they have a
labelSelector for master nodes. In hypershift there are never master
nodes, hence these DSes don't have a selector for that. Fix the test by
also allowing to ignore the rule if there is just a toleration for
master nodes.
/cc @csrwng

Fix 'should only include cluster daemonsets that have maxUnavailable' for Hypershift

---

test/extended/image_ecosystem/s2i_images.go
test/extended/image_ecosystem/scl.go
test/extended/testdata/bindata.go
test/extended/testdata/builds/build-pruning/default-group-build-config.yaml
test/extended/testdata/builds/build-pruning/default-legacy-build-config.yaml
test/extended/testdata/builds/build-pruning/errored-build-config.yaml
test/extended/testdata/builds/build-pruning/failed-build-config.yaml
test/extended/util/annotate/generated/zz_generated.annotations.go

- builds: upgrade php to 7.4
- image_ecosystem: specify available architectures for each S2I image
- image_ecosystem: update imagestreams
- image_ecosystem: add ubi7 imagestreams and x86-only dotnet

Update imagestreams in build and image-ecosystem

---

test/extended/util/openshift/clusterversionoperator/adminack.go

Two fairly unrelated cleanup commits, while I was getting my bearings in this code, and then the real fix which drops `waitForUpgradeable`.
Since we began polling in 4d1a25aee9 (#26649), there's an increased chance that this test is poking at acks while something else is going on in `Upgradeable` in parallel.  For [example][1]:
Dec  1 21:01:44.722: FAIL: Error while waiting for Upgradeable to go true, err=timed out waiting for the condition Upgradeable: Status=False, Reason=KubeletMinorVersion_KubeletMinorVersionUnsupportedNextUpgrade, Message="Cluster operator kube-apiserver should not be upgraded between minor versions: KubeletMinorVersionUpgradeable: Kubelet minor versions on 6 nodes will not be supported in the next OpenShift minor version upgrade.".
With the incoming logic, this …

Bug 2026806: Admin ack ignore unrelated upgradeable false

---

e2echart/e2e-chart-template.html
pkg/monitor/api.go
pkg/monitor/disruption_backend_sampler.go
pkg/monitor/disruption_known_backends.go
pkg/monitor/disruption_locator.go
pkg/monitor/monitor.go
pkg/monitor/sampler.go
pkg/monitor/types.go
pkg/test/ginkgo/status.go
test/e2e/upgrade/upgrade.go
test/extended/testdata/bindata.go
test/extended/util/disruption/backend_sampler_tester.go
test/extended/util/disruption/controlplane/controlplane.go
test/extended/util/disruption/disruption.go
test/extended/util/disruption/frontends/frontends.go
test/extended/util/disruption/imageregistry/imageregistry.go

Creating one disruption sampler to rule them all

refactor disruption suite to collapse to a single implementation

---

test/extended/olm/olm.go

In the external controlplane case, these pods have to be fetched from a different cluster.

OLM: Fix tests that check on pods when external ControlplaneToplogy

---

test/extended/etcd/leader_changes.go

This fixes the 'etcd leader changes are not excessive' for Hypershift.
As the etcd runs in the management cluster there, we need to talk to
that cluster and limit our query to not get the management clusters own
etcd metric.
/assign @csrwng

Fix etcd leader changes are not excessive for Hypershift

---

cmd/openshift-tests/images.go

This test currently fails for hypershift, because the
`[sig-auth][Feature:OAuthServer] [Headers] expected headers returned from the token URL`
test uses the release image to determine the oauth server image as it
can not derive that from a running pod, as the oauth server is deployed
in the management cluster.

Only known images used by tests: Fix for Hypershift

---

test/extended/etcd/OWNERS

test/extended/etcd: cleanup OWNERS

---

test/e2e/upgrade/alert/alert.go

bug 2033379: [release-4.8] remove perma-failing prometheus upgrade invariant

---

pkg/monitor/backenddisruption/disruption_backend_sampler.go

azure is weirdly slow.  We may even have to bump again, but let's see what this does
ref https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-azure-upgrade/1471779397802397696

extend tcp dial timeout and http response header timeout

---

test/extended/prometheus/prometheus.go

related to https://bugzilla.redhat.com/show_bug.cgi?id=1933144
/assign @tkashem

allow wardle aggregated apiservers to be down pending bug

---

pkg/monitor/alerts.go
pkg/monitor/monitorapi/types.go
pkg/synthetictests/alerts.go
pkg/synthetictests/allowedalerts/all.go
pkg/synthetictests/allowedalerts/basic_alert.go
pkg/synthetictests/allowedbackenddisruption/matches.go
pkg/synthetictests/event_junits.go
pkg/synthetictests/platformidentification/types.go
pkg/test/ginkgo/cmd_runsuite.go
test/extended/prometheus/alerts.go
test/extended/prometheus/prometheus.go
test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/conditions.go

this lets us track burn-budget directly.

watch specific alerts for pending and firing

---

pkg/monitor/monitorapi/types.go
pkg/synthetictests/allowedalerts/all.go
pkg/synthetictests/allowedalerts/basic_alert.go
test/extended/util/annotate/generated/zz_generated.annotations.go

also fixes test name and simplifies a bool evaluation.

separate out more alerts into specific tests

---

test/e2e/upgrade/alert/alert.go

found in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26739/pull-ci-openshift-origin-master-e2e-gcp-upgrade/1481993338713280512
/cc @dgrisonnet 

for upgrades, skip alerts with individual invariant tests

---

pkg/monitor/intervalcreation/rendering.go
pkg/monitor/write_job_run_data.go
pkg/test/ginkgo/cmd_runsuite.go
pkg/test/ginkgo/write_job_run_data.go

refactors interval html creation to optimize different views for different purposes

make it easy to create multiple flavors of interval charts

---

test/extended/cli/timeout.go

Bug 1931594: add one more timeout condition for --request-timeout test

---

pkg/synthetictests/allowedbackenddisruption/matches.go
pkg/synthetictests/allowedbackenddisruption/matches_test.go
pkg/synthetictests/allowedbackenddisruption/query_results.json
pkg/synthetictests/allowedbackenddisruption/types.go

/assign @dgoodwin 
/hold
holding for proof of general working-ness

update disruption times and shift to p99

---

test/extended/baremetal/helper.go

Do not wait for workers to be cleaned up on teardown. Setup in any case will take care of waiting previously deleted ones (impacts only serial jobs)

Bug 2044210: [baremetal] remove wait condition when deleting extraworkers

---

pkg/synthetictests/allowedalerts/basic_alert.go
pkg/synthetictests/allowedalerts/matches.go
pkg/synthetictests/allowedalerts/matches_test.go
pkg/synthetictests/allowedalerts/query_results.json
pkg/synthetictests/allowedalerts/types.go

This will prevent us from getting worse without noticing it, but it will not force an improvement.

use real alert data to determine flake and failure timeframes for alerts

---

test/extended/operators/routable.go
test/extended/prometheus/prometheus.go

This change is needed for openshift/cluster-monitoring-operator#1532

Bug 2047362: Prometheus check targets endpoint

---

test/extended/util/ibmcloud/provider.go

Add a mutex to the IBM Cloud provider FrameworkBeforeEach function
to address concurrency issues in creating a ClusterRoleBinding
not found on IBM managed clusters.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1825034

Bug 2047911: IBMCloud: Concurrent CRB create

---

cmd/openshift-tests/provider.go

In an attempt to fix the e2e-alibaba tests, I have modified the import statement to call the init.

Bug 2045590: Alibaba: enable init for alibabacloud provider

---

test/extended/oauth/requestheaders.go

This causes the authentication not stable failures
I'm seeing serial failures that appear to be due to a serial test not waiting for the authentication operator to settle after the test run: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.10-e2e-aws-serial/1491756102210031616  This is failing the latest 4.10 nightly

bug 2053312: requestheader test must wait for authentication operator to settle after config update

---

test/extended/oauth/requestheaders.go

https://github.com/openshift/origin/pull/26846

Bz2054254 rearrange test cases

---

test/extended/images/resolve.go

Switch to batch/v1 CronJob

---

test/extended/scheduling/pods.go

Pod scheduling tests improve pod deployment identification

---

test/extended/oauth/client_secret.go

The token request with client header authorization does not encode the header client identifier payload with URLEscape like the other request methods. The current oauth-server implements it so but this behavior has changed in newer versions of the dependency. So now the test which makes the token requests can multiple requests to fetch the token and as long as one of them succeeds the test is considered as succeeded.

Attempt multiple different token requests

---

cmd/openshift-tests/minimal.go

per https://github.com/openshift/sippy/pull/372

Update where the canary test lists is retrieved from

---

test/extended/security/sysctl.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Add tests checking that pods with whitelisted sysctl's can be created.

Add pod securityContext sysctl whitelist tests

---

pkg/synthetictests/networking.go

Error appears as:
ns/openshift-monitoring pod/prometheus-k8s-0 node/ci-op-7rbmc903-99831-gg8cc-worker-eastus21-8r5sj - 351.25 seconds after deletion - reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_prometheus-k8s-0_openshift-monitoring_3ac88b2a-ba98-4120-994e-74440426bc89_0(29c646fdadb15d64ec74b12953bbb1c04df8ebf8aced6c198271a32d1f98991f): error adding pod openshift-monitoring_prometheus-k8s-0 to CNI network "multus-cni-network": plugin type="multus" name="multus-cni-network" failed (add): Multus: [openshift-monitoring/prometheus-k8s-0/3ac88b2a-ba98-4120-994e-74440426bc89]: have you checked that your default network is ready? still waiting for readinessindicatorfile @ …

Flake on FailedCreatePodSandbox if missing ovn readiness file.

---

pkg/test/ginkgo/cmd_runsuite.go

Storage tests often hit cloud provider API limits.  Let's see if limiting them to two at a time is enough to alleviate the problems.
/hold
holding until we verify that we have the proper number of tests running.

coarse serialization of storage tests

---

test/extended/oauth/client_secret.go

Currently, the loop which tries the token requests only checks for errors in making the requests. It does not check the response status before marking the response as successful. This change moves the check for the status code to the for loop.

Check token response error code

---

test/extended/networking/util.go

Signed-off-by: Andreas Karis <ak.karis@gmail.com>

Fix typo in OVN Kubernetes skipper

---

pkg/monitor/monitorapi/identification_pod.go
pkg/synthetictests/networking.go

alternative to https://github.com/openshift/origin/pull/26972/files that correctly determines deletion timestamps.

fix evaluation of deleted pods for pod sandbox test

---

test/e2e/upgrade/upgrade.go
test/extended/util/disruption/disruption.go

Team thinks this is related to verification of the payload, and is
affecting only a few metal jobs for the most part, but doing so
very reliably.
Proper investigation and fix being pursued in
https://bugzilla.redhat.com/show_bug.cgi?id=2071998

Bump timeout for CVO to ack the upgrade generation.

---

pkg/monitor/pod.go

found in https://github.com/openshift/cluster-etcd-operator/pull/763

prevent npe for old container status readiness

---

pkg/synthetictests/duplicated_events.go

Bug 2074445: exclude loki-promtail from duplicated events

---

pkg/synthetictests/duplicated_events.go
pkg/synthetictests/event_junits.go
pkg/synthetictests/image_pulls.go
pkg/synthetictests/image_pulls_test.go

Part of [TRT-159](https://issues.redhat.com/browse/TRT-159) and related to [OCPBUGSM-38392](https://issues.redhat.com/browse/OCPBUGSM-38392) and [BZ 2031564](https://bugzilla.redhat.com/show_bug.cgi?id=2031564).

Bug 2031564: Separate out test for 'RequiredInstallerResourcesMissing secrets'

---

pkg/synthetictests/alerts.go
pkg/synthetictests/allowedalerts/all.go
pkg/synthetictests/allowedalerts/allow_on_revision_change.go
pkg/synthetictests/allowedalerts/basic_alert.go
pkg/synthetictests/allowedalerts/job_run_data.go
pkg/synthetictests/allowedalerts/matches.go
pkg/synthetictests/historicaldata/types.go
test/e2e/upgrade/alert/alert.go
test/extended/etcd/leader_changes.go
test/extended/prometheus/alerts.go
test/extended/prometheus/prometheus.go
test/extended/util/annotate/generated/zz_generated.annotations.go

based on https://github.com/openshift/origin/pull/26965/files and https://github.com/openshift/origin/pull/26917

skip tests for etcd leaders when etcd revisions change a lot

---

test/extended/apiserver/resiliency.go

This is a follow on from https://github.com/openshift/origin/pull/26868
where we introduced a working to prevent single-node serial tests from
failing.
This patch rectfies that by removing the artificial delay and patching
the root cause, which is due to the way errors are processed when making
a call to isApiReady. The existing implementation will "bubble up"
errors from the httpClient.Get call to the caller of isApiReady.
However, at this stage, errors are undesirable, we simply want to ask
the question "is the API ready or not? -- for any reason"
So I have simplified the method to return a boolean response even if
errors are encountered.

MGMT-9440: Fix single node serial tests API crash

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/testdata/templates/basic-users-binding.json
test/extended/testdata/idling-echo-server-rc.yaml
test/extended/testdata/router/reencrypt-serving-cert.yaml

Followup to #27008, again needed to land https://github.com/openshift/oc/pull/1092

Switch to groupified APIs

---

test/e2e/upgrade/upgrade.go

ClusterVersion's spec can evolve over time, growing additional properties like [`capabilities`][1].  With the old `POST`/`Update(...)` approach, that could lead to older test-suite (that didn't know about the new properties) naively clearing them when they washed the in-cluster resource through [their local ClusterVersion Go type][2].  With this commit, we transition to `PATCH`, so we can touch just `spec.desiredUpdate`, regardless of what else is going on in spec.
[1]: https://github.com/openshift/api/commit/5b82635ef101e7c10b5fcbbcfb81315bb7a0da20
[2]: https://github.com/openshift/origin/blob/700c47b96aec846672156f657cf76660f11fb1e1/vendor/github.com/openshift/api/config/v1/types_cluster_version.go#L31-L76

test/e2e/upgrade: Use PATCH instead of POST for ClusterVersion spec updates

---

test/extended/security/scc.go

needed for https://github.com/openshift/cluster-kube-apiserver-operator/pull/1338
/assign @s-urbaniak

loosen SCC capabilities check to allow stricter caps

---

test/extended/scheduling/pods.go

When starting from previous levels we will hit a problem.

the 'should be scheduled on different nodes' were only fixed in 4.11 and later

---

test/extended/authorization/rbac/OWNERS
test/extended/authorization/rbac/groups_default_rules.go

Add restricted-v2 to the default RBAC rules for authenticated users

---

test/extended/router/h2spec.go
test/extended/testdata/bindata.go
test/extended/testdata/router/router-h2spec.yaml

This requires access to the legacy "restricted" SCC.
/assign @Miciah 
/cc @chadcrum

haproxy needs to request privilege escalation in order to work

---

pkg/synthetictests/platformidentification/types.go
test/e2e/upgrade/upgrade.go

give multi-arch more time to complete upgrades to clean up signal

---

test/extended/deployments/deployments.go
test/extended/router/h2spec.go
test/extended/util/framework.go
test/extended/util/oauthserver/oauthserver.go

router: wait for "use scc restricted" SAR before pod creation

---

test/extended/csrapprover/csrapprover.go

Make a new token request instead of using node-bootstrappers tokens.

Bug 2080681: Request new token instead of using node-bootstrapper token

---

test/extended/images/oc_tag.go
test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/quota.sh
test/extended/testdata/cmd/test/cmd/secrets.sh

This should solve:
- https://bugzilla.redhat.com/show_bug.cgi?id=2080679
- https://bugzilla.redhat.com/show_bug.cgi?id=2081018

Bug 2080679: fix oc related test to land k8s 1.24

---

test/extended/cli/admin.go

Followup to https://github.com/openshift/origin/pull/27099 
/assign @tkashem

Fix request token ic cli/admin tests

---

test/extended/router/metrics.go

Make a call to token request API to get a token.
Don't rely on auto-generated secrets anymore:
- https://bugzilla.redhat.com/show_bug.cgi?id=2080687
- https://github.com/kubernetes/kubernetes/pull/108309/files
Signed-off-by: Krzysztof Ostrowski <kostrows@redhat.com>

Bug 2080687: request prometheus service account token

---

cmd/openshift-tests/openshift-tests.go
pkg/monitor/api.go
pkg/monitor/intervalcreation/pod.go
pkg/monitor/intervalcreation/rendering.go
pkg/monitor/intervalcreation/rendering_per_namespace.go
pkg/monitor/monitor_cmd/command.go
pkg/monitor/monitorapi/types.go
pkg/monitor/pod.go
pkg/monitor/serialization/serialize.go

Fix some bugs with pod timing for the timeline.

Correct pod timing

---

e2echart/e2e-chart-template.html
pkg/monitor/intervalcreation/pod.go
pkg/monitor/intervalcreation/podTest/end-before-begin/podData.json
pkg/monitor/intervalcreation/podTest/installer-pod/podData.json
pkg/monitor/intervalcreation/podTest/run-once-done/podData.json
pkg/monitor/intervalcreation/pod_test.go
pkg/monitor/monitor.go
pkg/monitor/monitor_cmd/command.go
pkg/monitor/monitorapi/types.go
pkg/monitor/monitoring_reflector_store.go
pkg/monitor/pod.go
pkg/monitor/serialization/resource.go
test/extended/testdata/bindata.go

timeline command, container exit fix, key resources by uid, and use reflector

---

test/extended/util/disruption/backend_sampler_tester.go

We have some p99s that are 0s, but a single unlucky call failing an entire job run  isn't the goal of the test.  Allowing 1s gives some grace, but will still fail if there's more than a single failure.

always allow at least one second for disruption

---

pkg/synthetictests/allowedalerts/matches_test.go
pkg/synthetictests/allowedalerts/query_results.json
pkg/synthetictests/allowedbackenddisruption/matches_test.go
pkg/synthetictests/allowedbackenddisruption/query_results.json

ran the queries to update our historical data.

update alert and disruption limits

---

test/extended/networking/tuning.go

Signed-off-by: Vijay Vinnakota <vijay.vinnakota@ibm.com>

commenting ipv6 for sysctls

---

test/extended/util/pods.go

This lets pass i.e. the following e2e test: `[sig-instrumentation] Prometheus when installed on the cluster should provide ingress metrics [Skipped:Disconnected] [Suite:openshift/conformance/parallel]` but potentially others as well as part of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1339.
/cc @stlaz

Bug 2086519: Auth-133: test/extended/util: comply exec pod to restricted pod security profile

---

pkg/synthetictests/apiserver.go

to avoid firing inaccurately in cases like https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27151/pull-ci-openshift-origin-master-e2e-aws-single-node-upgrade/1526997253254811648 where many single-second failures are contiguous with different messages.
We want to keep the separate disruption events to show these different failures because the message matters and in this case, is weird. But this particular test should not fail.

don't trigger single second disruption on contiguous disruption

---

go.mod
go.sum
vendor/k8s.io/kubernetes/pkg/features/kube_features.go
vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go
vendor/k8s.io/kubernetes/pkg/kubelet/pod/pod_manager.go
vendor/k8s.io/kubernetes/pkg/kubelet/util/manager/cache_based_manager.go
vendor/k8s.io/kubernetes/test/e2e/framework/framework.go
vendor/modules.txt

Bug 2086519: bump o/kube so that test namespaces aren't PSa label synced

---

test/extended/networking/egressip.go
test/extended/networking/egressip_helpers.go

Detect and use the packet capture interface for EgressIP tests. In the
case of SDN, this is the default route of the nodes. In the case of
OVNK, replicate logic found in the OVNK repo to find the main system
interface that belongs to bridge br-ex. Using the physical egress
interface for packet captures fixes a bug where the same interface would
be accounted for 2x.
Fixes failures on OpenShift SDN with the current implementation:
* https://search.ci.openshift.org/?search=Feature%3AEgressIP&maxAge=48h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
* https://prow.ci.openshift.org/job-history/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.11-e2e-azure-techpreview-serial
Tested on GCP OVNKubernetes (/):
~~~
./openshift-tests run-test …

Bug 2089276: Detect and use the packet capture interface for EgessIP tests.

---

pkg/synthetictests/static_pod.go

Test case incorrectly identify failures using wrong namespace.

Bug 2081732: Static pod test error

---

test/e2e/upgrade/dns/dns.go

This will hopefully alleviate problems like https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-kubernetes-1252-nightly-4.11-upgrade-from-stable-4.10-e2e-metal-ipi-upgrade-ovn-ipv6/1523985605116039168
We can still get useful signal from the test.

allow up to two DNS check pods to be waiting

---

test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/help.sh

Required to land https://github.com/openshift/oc/pull/1121
/assign @ardaguclu

Bug 2090692: slightly loosen oc exec help test

---

test/extended/networking/util.go
test/extended/util/operator.go

wait for kube-apiserver to settle after modifying network configuration

---

pkg/monitor/intervalcreation/rendering.go

updating names.  Requires https://github.com/openshift/release/pull/28940

rename intervals to timelines to be self-explanatory

---

e2echart/e2e-chart-template.html
test/extended/testdata/bindata.go

* Adds a filter (JS RegExp) to filter the chart
* Adds a duration to each event (both occurrences and summary on the right side of the chart)

Bug 2093234: Add regex filter and intervals duration to e2e-charts

---

test/extended/apiserver/graceful_termination.go

The late requests validation is based on interpreting the KAS audit
logs. The audit logs are fetched through `oc must-gather`. This works
fine for self-hosted OCP, but with an external controlplane the KAS runs
as pod in a distinct management cluster and thus it is not possible to
get its audit logs from the cluster under test.
This change fixes the test for Hypershift by introduction dedicated
audit log fetching codepaths for selfhosted/hypershift.
/assign @p0lyn0mial 
The diff gets much smaller when omitting whitespace changes.

Bug 2085997: Report late requests verification: Fix for Hypershift

---

examples/db-templates/mariadb-ephemeral-template.json
examples/db-templates/mariadb-persistent-template.json
examples/image-streams/image-streams-centos7.json
examples/jenkins/jenkins-ephemeral-template.json
examples/jenkins/jenkins-persistent-template.json
examples/quickstarts/cakephp-mysql-persistent.json
hack/update-external-examples.sh
test/extended/image_ecosystem/s2i_images.go
test/extended/testdata/bindata.go
test/extended/util/annotate/generated/zz_generated.annotations.go

The image_ecosystem additions depend on https://github.com/openshift/cluster-samples-operator/pull/428
/cc @fbm3307

Bug 2086086: update samples for 4.11

---

pkg/test/ginkgo/cmd_runsuite.go

related to [TRT-261](https://issues.redhat.com/browse/TRT-261).
must-gather takes resources and tests are running at the same time; we found a case where several tests failed during the time the must-gather tests were running.

Bug 2097009: Run must-gather tests in later to reduce resource contention

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

Extend time for kube rebase to land

Bug 2086092: Extend time for kube rebase

---

cmd/openshift-tests/provider.go
test/extended/util/nutanix/provider.go

Added Nutanix provide type for e2e testing

Bug 2097684: Nutanix provider for e2e testing

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

Missed these while rebasing from Abu's commits.
cc @deads2k @mfojtik

Bug 2086092: Re-enable tests

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

Based on this comment https://bugzilla.redhat.com/show_bug.cgi?id=2093339#c6 I'm moving this to perma disablement and will let storage team enable it back when they find it necessary.
@jsafrane @mfojtik @stlaz @stbenjam

Bug 2093339: move provisioning test to permanent disablement, since this is not yet officially supported

---

pkg/synthetictests/kubelet.go

Signed-off-by: ehila <ehila@redhat.com>

Bug 2099698: revert: no longer needed logic for rt kernel

---

test/extended/util/image/OWNERS

Add Ravi and Abu as image approvers

---

pkg/synthetictests/allowedalerts/all.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Regarding https://issues.redhat.com/browse/TRT-390

Separate out test for SamplesImagestreamImportFailing alarm

---

test/extended/networking/acl_audit_log.go
test/extended/networking/egressip.go
test/extended/prometheus/prometheus.go
test/extended/util/client.go
test/extended/util/prometheus/helpers.go

/assign @openshift/sig-networking 
/assign @openshift/openshift-team-network-edge-maintainers

remove CLI.SetupNamespace() in favour of CLI.SetupProject()

---

test/extended/util/image/OWNERS

Add Jan as image approver, remove Ravi and Clayton

---

test/extended/networking/egressip.go

Run sendEgressIPProbesAndCheckPacketSnifferLogs until it eventually
succeeds of for a maximum of 2 minutes.
Before, we checked first until a single packet was EgressIP mapped, and
then ran the main test once. Instead, simply make sure that the test
eventually passed to cut down on flakes.
Signed-off-by: Andreas Karis <ak.karis@gmail.com>
How to test with SDN:
~~~
./openshift-tests run all --print-commands  | grep EgressIP | grep external | grep -v "Skipped:Network/OpenShiftSDN" | while IFS= read -r line; do bash -c "$line" ; done
~~~
How to test with OVN:
~~~
./openshift-tests run all --print-commands  | grep EgressIP | grep external | grep -v "Skipped:Network/OVNKubernetes" | while IFS= read -r line; do bash -c "$line" ; done
~~~
Tested manually with:
* SDN + AWS (latest)
* OVN Azure …

Bug 2110503: EgressIP: Probes and check tcpdump logs should succeed eventually 

---

test/extended/ci/job_names.go

[TRT-470](https://issues.redhat.com//browse/TRT-470)
- Hard fail if a job name indicates a network type, but job is not using
it. For example, a job with sdn in the name that's really ovn.
- Hard fail if any periodic is missing the network type
- Flake if we see a network provider that's not SDN or OVN.  Most code
in origin assumes it's either/or but there's a request from the
network folks that we might have a few jobs using other providers.
This should help find them.

Update job name tests for hard failure cases

---

test/e2e/upgrade/service/service.go

This adds a readyz=false state into the service being served by the load balancer to allow time for the load balancer to realize that an endpoint is no longer ready.  During this time period, requests are still handled by the server, so we should see a reduction in the disruption as a result.

update service load balancer test to gracefully roll out

---

test/extended/etcd/etcd_storage_path.go

Update etcd tests with k8s data

---

cmd/openshift-tests/upgrade.go

Fixes #27383
[TRT-445](https://issues.redhat.com//browse/TRT-445)

Fix upgrade dry-run.

---

test/extended/util/ldap.go

With that addition of retry attempts when the ldapsearch validation step fails we need to use a unique pod name as the previous pod does not exit immediately on failure.  It does get removed but not before the next retry attempt.  Fix is to append the try/retry attempt value to the pod name.
`{ fail [github.com/openshift/origin/test/extended/oauth/groupsync.go:42]: Unexpected error: <*errors.errorString \| 0xc00070be80>: \{ s: "errors encountered trying to run ldapsearch pod: [pods \"runonce-ldapsearch-pod\" already exists]", }
errors encountered trying to run ldapsearch pod: [pods "runonce-ldapsearch-pod" already exists] occurred Ginkgo exit error 1: exit with code 1}`

make runonce-ldapsearch pod name unique

---

pkg/test/ginkgo/cmd_runsuite.go

`getDiscoveryClient()` does not checks whether a cluster is reachable. One needs to e.g. check cluster version to verify the connection with the cluster. A.k.a allow dry-run to skip api group filter builder when a cluster is not reachable.

Check version when discovery client

---

go.mod
go.sum
test/extended/prometheus/prometheus.go
test/extended/util/annotate/generated/zz_generated.annotations.go
vendor/k8s.io/kubernetes/openshift-hack/e2e/annotate/rules.go
vendor/k8s.io/kubernetes/pkg/quota/v1/install/registry.go
vendor/k8s.io/kubernetes/test/e2e/apimachinery/aggregator.go
vendor/k8s.io/kubernetes/test/e2e/network/netpol/kubemanager.go
vendor/k8s.io/kubernetes/test/e2e/network/netpol/model.go
vendor/k8s.io/kubernetes/test/e2e/network/netpol/network_policy.go
vendor/k8s.io/kubernetes/test/e2e/network/netpol/probe.go
vendor/k8s.io/kubernetes/test/e2e/network/netpol/reachability.go
vendor/k8s.io/kubernetes/test/e2e/network/netpol/test_helper.go
vendor/modules.txt

Includes https://github.com/openshift/kubernetes/pull/1307

Bug 1933144: Bump k8s to include c83b5d076f5

---

test/extended/olm/olm.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Skip sig-operator tests if operators.coreos.com API is not registered.

USHIFT-301: microshift: skip sig-operator tests

---

test/extended/imageapis/imagesigning.go
test/extended/images/imagechange_buildtrigger.go
test/extended/images/info.go
test/extended/images/layers.go
test/extended/images/resolve.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Skip sig-imageregistry tests if image.openshift.io API is not registered.

USHIFT-300: microshift: skip sig-imageregistry tests

---

OWNERS

It would be helpful to have another approver from TRT, and Devan has 64+ PR's to origin, along with many, many reviews

Add dgoodwin as approver to origin

---

pkg/synthetictests/resource_growth.go

The new checks don't work with upgrade rollback because there is no completion time for the upgrade. It's aborted at 99% and the clusterversion has the completion time as null.
This will still return a junit, but with [Skipped] for those cases when the completion time is null.
https://issues.redhat.com/browse/SDN-3505

Skip resource growth checks in upgrade-rollback jobs

---

pkg/test/ginkgo/cmd_runsuite.go

the content will now be in openshift-tests-monitor_timestamp.txt.
It is still included in junit.xml, but I'm open to removing that too if you all like.

only print the timeline into artifact dir to reduce noise

---

OWNERS_ALIASES

Set Jakub as a Test Platform team lead

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

Backporting https://github.com/openshift/origin/pull/27529

OCPBUGS-3428: Skip broken [sig-devex][Feature:ImageEcosystem] tests

---

OWNERS_ALIASES

CC @stlaz @soltysh @s-urbaniak

OWNERS_ALIASES: update list of team leads

---

pkg/synthetictests/disruption.go

happened to find this while looking for something else
/assign @DennisPeriquet

cosmetic fix for bad disruption substitution

---

pkg/riskanalysis/cmd.go

[TRT-697](https://issues.redhat.com//browse/TRT-697)
Some jobs taking about 35ms.
[One job](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/27564/pull-ci-openshift-origin-master-e2e-gcp-ovn-rt-upgrade/1594831835135741952/artifacts/e2e-gcp-ovn-rt-upgrade/openshift-e2e-test/build-log.txt) took 176ms.
[Another job](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/27564/pull-ci-openshift-origin-master-e2e-gcp-ovn-upgrade/1594831835966214144/artifacts/e2e-gcp-ovn-upgrade/openshift-e2e-test/build-log.txt) took 245ms.

Introduce timeout for sippy risk analysis; add retries with backoff; add dated logging

---

test/extended/networking/tuning.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Add test for sysctl whitelist update.
NOTE: This PR requires the following PR to be merged first:  https://github.com/openshift/cluster-network-operator/pull/1573

Test tuning cni whitelist update

---

test/extended/apiserver/api_requests.go

OCPBUGS-4550: Bump api-requests for console-operator on vsphere

---

test/extended/pods/priorityclasses.go

All the referenced bugs claim to have been fixed.

remove special cases for priority classes in the payload

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

(cherry picked from commit 14d2ae41781c9332d73ebfdb2b194ec1bc63ebfe)

OCPBUGS-4503: Unskip service session affinity tests

---

test/extended/prometheus/prometheus.go
test/extended/prometheus/storage.go
test/extended/util/prometheus/helpers.go

Attempt to fix [TRT-699](https://issues.redhat.com/browse/TRT-699)

Filter out dropped targets to minimize the size of target api result

---

test/extended/etcd/etcd_storage_path.go

/assign @sanchezl
1.26 PR: https://github.com/openshift/kubernetes/pull/1432

Update ETCD storage data for k8s 1.26

---

OWNERS_ALIASES

Update CVO test ownership: -Jack and Vadim, +Petr

---

pkg/synthetictests/duplicated_events.go
pkg/synthetictests/duplicated_events_test.go

[TRT-687](https://issues.redhat.com/browse/TRT-687)
Add result=allow for flake events and result=reject for fail events

Add result key value to each topological event test output line

---

pkg/synthetictests/allowedalerts/all.go

[TRT-735](https://issues.redhat.com/browse/TRT-735)

Separate mcd error alert

---

cmd/openshift-tests/minimal.go

https://issues.redhat.com/browse/TRT-803
https://github.com/openshift/release/pull/35743

TRT-803: FIxing test name

---

pkg/synthetictests/allowedbackenddisruption/matches_test.go
pkg/synthetictests/historicaldata/next_best_guess.go

https://issues.redhat.com/browse/TRT-813
/cc @xueqzhan

TRT-813: Disabling disruption fallback for upgrades

---

test/extended/authorization/podsecurity_admission.go
test/extended/util/annotate/generated/zz_generated.annotations.go

This adds tests for https://github.com/openshift/kubernetes/pull/1393
/cc @ibihim

AUTH-337: PSa: add test for SCC-mutated PodSpec extraction

---

test/extended/testdata/bindata.go
test/extended/testdata/builds/docker-add/docker-add-env/Dockerfile

/assign @coreydaley 
see https://github.com/openshift/openshift-controller-manager/pull/250#issuecomment-1425832112

replace centos with ubi8 in build test dockerfile

---

pkg/monitor/intervalcreation/node.go
pkg/monitor/intervalcreation/node_test.go
pkg/monitor/monitorapi/identification_pod.go
pkg/synthetictests/allowedalerts/basic_alert.go
pkg/synthetictests/event_junits.go
pkg/synthetictests/kubelet.go

[TRT-819](https://issues.redhat.com//browse/TRT-819): Add check for StartContainer / ErrImagePull issues due to signature parsing errors (Akamai caching issue)

TRT-819: Add check for parse signature error

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

(cherry picked from commit 14d2ae41781c9332d73ebfdb2b194ec1bc63ebfe) (cherry picked from commit efb4c81470ac9e82d7e5997d7e4b50b0d3be0b43)

OCPBUGS-7319: Unskip service session affinity tests

---

test/e2e/upgrade/dns/dns.go

Found in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27694/pull-ci-openshift-origin-master-e2e-aws-ovn-upgrade/1623489514854944768 see the 
```
disruption_tests: [sig-network-edge] Verify DNS availability during and after upgrade success
```
failure specifically. I've noticed that we don't wait for that test DS, which might result in the following scenario:
```
STEP: Creating a DaemonSet to verify DNS availability 02/09/23 02:20:13.567
...
Feb  9 02:20:13.998: FAIL: too many pods were waiting: ns/e2e-check-for-dns-availability-3377 pod/dns-test-b0e2bd0a-19b2-4c42-bbed-842415bd67ad-92dw9,ns/e2e-check-for-dns-availability-3377 pod/dns-test-b0e2bd0a-19b2-4c42-bbed-842415bd67ad-lgj2g,ns/e2e-check-for-dns-availability-3377 …
```

OCPBUGS-6902: Wait for DNS DS pods to be ready

---

test/extended/storage/storageclass.go

https://issues.redhat.com/browse/OCPBUGS-7488

OCPBUGS-7488: test flake: should not reconcile SC when state is Unmanaged

---

test/extended/storage/inline.go

https://issues.redhat.com/browse/STOR-1077
/hold for https://github.com/openshift/cluster-kube-apiserver-operator/pull/1434 to merge first (required to remove the SCC toggle in the test)

STOR-1077: promote CSIInlineVolumeAdmission feature gate to GA

---

pkg/monitor/write_job_run_data.go
pkg/riskanalysis/types.go
pkg/riskanalysis/write_test_failure_summary.go
pkg/synthetictests/platformidentification/types.go
pkg/test/ginkgo/options_monitor_events.go

- Collect Invariant data from platformIdentification.GetJobType
- Add JobType in ProwJobRun
- Pass along invariant data via ProwJobRun to sippy call

TRT-800: Collect variant data for risk analysis

---

pkg/synthetictests/disruption.go

First pass at flaking all azure disruption

TRT-889: Temp flake all azure disruption

---

pkg/synthetictests/duplicated_events.go
pkg/synthetictests/duplicated_events_test.go

[TRT-870](https://issues.redhat.com/browse/TRT-870)

Separate pathological event tests for all known namespaces

---

test/extended/networking/vlan.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Revert "Revert "Add vlan/macvlan/ipvlan incontainer master tests""

---

test/extended/cpu_partitioning/managed.go

Noticed this test fail falsely in the CI due to querying the deployment before the status was updated by the controller.
It was rare locally, but I was able to replicate, adding the poll removed the false positive.

OCPBUGS-10824: fix: add poll to get deployment status and avoid false positive

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

This reverts commit 43284bbffa7f410b210214d2d3ce6692a1b75e76.

OpenStack: Restore in-tree cinder provisioner tests

---

e2echart/e2e-chart-template.html
e2echart/non-spyglass-e2e-chart-template.html
pkg/monitor/intervalcreation/rendering.go
pkg/monitor/monitor_cmd/command.go
test/extended/testdata/bindata.go

follow-on that adds negative matching.

negative filtering

---

e2echart/e2e-chart-template.html
e2echart/non-spyglass-e2e-chart-template.html
pkg/monitor/intervalcreation/rendering.go
pkg/monitor/monitor_cmd/command.go
test/extended/testdata/bindata.go

https://github.com/openshift/origin/pull/27808 with generated code so we see it rendering

Added additional filtering options for e2e chart

---

pkg/synthetictests/operators.go

OCPBUGS-11315: Increasing limits for Nodes OSUpdateStaged time test

---

pkg/monitor/intervalcreation/node.go
pkg/synthetictests/event_junits.go
pkg/synthetictests/kubelet.go

4.13 version of https://github.com/openshift/origin/pull/27852
this was a clean pick

[4.13] add specific test for failing cgroups path

---

pkg/monitor/intervalcreation/node.go
pkg/synthetictests/event_junits.go
pkg/synthetictests/kubelet.go

4.12 version of https://github.com/openshift/origin/pull/27852
this was not clean

[4.12] add specific test for failing cgroups path

---

test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/annotate/rules.go

/assign @ardaguclu @bertinatto

OCPBUGS-11652: disable oc adm node-logs

---

test/extended/authorization/rbac/groups_default_rules.go

CC @soltysh @stlaz 
Edit: tested this with https://github.com/openshift/kubernetes/pull/1524 and it worked OK.

Move selfsubjectreviews RBAC rule to the right place

---

pkg/synthetictests/networking.go

Kuryr can take long to create Pods as it needs to create ports for these pods in Neutron. If a pod gets deleted while this is being processed, a warning Event will be generated. This causes the `[sig-network] pods should successfully create sandboxes by adding pod to network` to fail.
This commit adds this case as a flake.

[release-4.10] OCPBUGS-11874: Add Kuryr exception to "pods should successfully create sandboxes" test

---

test/extended/pods/graceful-shutdown.go

OCPNODE-1257: feat: remove custom node wait logic for upstream framework call

---

cmd/openshift-tests/openshift-tests.go
pkg/cmd/monitor_command/monitor_command.go
pkg/cmd/monitor_command/run_monitor_command.go
pkg/cmd/monitor_command/timeline_command.go

this will give us timelines for *prior* to installation.

Render html from monitor

---

pkg/monitor/backenddisruption/disruption_locator.go
pkg/synthetictests/disruption.go
pkg/synthetictests/disruption_test.go
pkg/synthetictests/event_junits.go

https://issues.redhat.com/browse/TRT-856

TRT-856: DNS and disruption overlap test

---

pkg/riskanalysis/cmd.go

* When we don't find any test failure summary files add a log entry and return instead of continuing to process and returning an error back up the chain.
* When we encounter an error we want to log it but don't pass back up and cause the job to fail

trt-900: log risk-analysis errors but don't pass back up

---

cmd/openshift-tests/e2e.go
test/extended/dr/backup_restore.go
test/extended/dr/common.go
test/extended/dr/force_redeploy.go
test/extended/dr/recovery.go
test/extended/util/annotate/generated/zz_generated.annotations.go

scenario:
* backup of node 0
* copy backup from 0 to 1
* shutdown node 0 and 2 (remove their static pods)
* restore on node 1

ETCD-423: Restore Test - Lost Quorum

---

pkg/duplicateevents/duplicated_event_patterns.go

[TRT-1015](https://issues.redhat.com//browse/TRT-1015)
This pathological failure is known and should no longer fail prowjobs.

Mark ErrorReconcilingNode macAddress not found as known and with existing BZ

---

OWNERS_ALIASES

Update etcd team lead

---

test/extended/cli/explain.go

to prevent the test failures in oc kube bump: 
- https://github.com/openshift/oc/pull/1420
- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_oc/1420/pull-ci-openshift-oc-master-e2e-aws-ovn/1660630230638792704
see aditional explanation in alternative PR by @ardaguclu : https://github.com/openshift/origin/pull/27936#issue-1723706437

fix oc explain status and spec verification

---

test/extended/dr/common.go
test/extended/dr/recovery.go
test/extended/dr/resource_assertions.go

asserting that some resources should or should not exists, depending on the type of restore

ETCD-425: restore test should validate state

---

pkg/monitor/apiserveravailability/summarizer.go
pkg/monitor/backenddisruption/disruption_backend_sampler.go
pkg/monitor/backenddisruption/disruption_locator.go
pkg/monitor/intervalcreation/node.go
pkg/monitor/intervalcreation/node_test.go
pkg/monitor/intervalcreation/pod.go
pkg/monitor/intervalcreation/podTest/container-life/expected.json
pkg/monitor/intervalcreation/podTest/end-before-begin/expected.json
pkg/monitor/intervalcreation/podTest/installer-pod/expected.json
pkg/monitor/intervalcreation/podTest/long-not-ready/expected.json
pkg/monitor/intervalcreation/podTest/run-once-done/expected.json
pkg/monitor/intervalcreation/podTest/simple/expected.json
pkg/monitor/intervalcreation/podTest/trailing-ready-2/expected.json
pkg/monitor/intervalcreation/podTest/trailing-ready/expected.json
pkg/monitor/intervalcreation/rendering_per_namespace.go
pkg/monitor/monitorapi/identification_pod.go
pkg/monitor/pod.go
pkg/monitor/podipcontroller/pod_ip_controller.go
pkg/synthetictests/disruption.go
pkg/synthetictests/kubelet.go
pkg/synthetictests/networking.go

This is a precursor to adjusting the monitor event schema by letting us know the actual annotation in play.  I suspect we'll need to find a way to separate or invert the building of messages from annotations.

hard monitor.Event message creation

---

pkg/test/ginkgo/test_runner.go

/cc @soltysh 
/cc @ingvagabund

USHIFT-1300: Avoid getting cluster state for TEST_PROVIDER env var

---

test/extended/prometheus/prometheus.go

The following critical alerts do not have have runbook_url annotation
| namespace                                                 | alert group name                               | alert                                               |
|-----------------------------------------------------------|------------------------------------------------|-----------------------------------------------------|
| openshift-ovn-kubernetes-master-rules                     | cluster-network-operator-master.rules          | OVNKubernetesNorthboundDatabaseClusterIDError       |
| openshift-ovn-kubernetes-master-rules                     | cluster-network-operator-master.rules          | OVNKubernetesSouthboundDatabaseClusterIDError       |
| openshift-ovn-kubernetes-master-rules                     | …

MON-3213: Changing the severity of "missing runbook_url annotation for critical alerts" test case from flaky to failure

---

test/extended/kubevirt/util.go

AWS ELBs work by hostname and not IP. It can take an unpredictable amount of time for these hostnames to become externally reachable as well.
This PR updates the KubeVirt LB tests to by using the k8s service hostname when it is available over the IP, and it also increases the connectivity timeouts. Both of these changes are required in order for these test cases to pass when hypershift/kubevirt is tested on AWS infrastructure

Update kubevirt LB connectivity tests to work with AWS ELB

---

pkg/synthetictests/allowedalerts/all.go

Items in this list are skipped in other tests.

TRT-1097: add KubeMemoryOvercommit to specific test so that the general test doesn't fail

---

.gitignore
pkg/disruption/backend/disruption/handler.go
pkg/monitor/backenddisruption/disruption_backend_sampler.go
pkg/monitor/backenddisruption/disruption_locator.go
pkg/monitor/monitorapi/identification_pod.go

disruption refinement for availability, not latency.

---

test/extended/operators/operators.go

required for https://github.com/openshift/cluster-config-operator/pull/325

allow cluster-config-operator to manage featuregate upgrade block

---

test/extended/machines/cluster.go
test/extended/machines/display_reboots_pod.yaml

Instead of assuming that every MC is causing a reboot, we should look for "rebooting" message from systemd-login

Update "verify that nodes have no unexpected reboots" test

---

test/extended/scheduling/pods.go

There have been reoccurring failures of this test: https://search.ci.openshift.org/?search=fail+%5C%5Bgithub%5C.com%2Fopenshift%2Forigin%2Ftest%2Fextended%2Fscheduling%2Fpods%5C.go%3A102%5C%5D%3A&maxAge=336h&context=1&type=junit&name=single-node&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
This change helps to debug these failures by assessing the state of the deployment at the time of the failure.

print out deployment for incorrectly scheduled pods

---

test/extended/util/prometheus/helpers.go

to improve https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade/1673703516675248128
/assign @simonpasquier

OCPBUGS-15558: retry promql a few times to mask i/o timeouts

---

test/e2e/upgrade/upgrade.go
test/extended/util/annotate/generated/zz_generated.annotations.go

[TRT-1100](https://issues.redhat.com/browse/TRT-1100)

Add test checking nodes are in proper read state before upgrade

---

test/extended/quota/clusterquota.go

This PR adds more logs in case when quota namespace labeling fails. This is basically added to investigate https://issues.redhat.com/browse/OCPBUGS-15568 bug. However, these logs should also make
easier possible regression in the future and do not generate noise(especially when we decrease timeout value
from 30 to 10 seconds back again, after investigation is finished.)

Add logs in clusterquota test for more verbosity

---

test/extended/cli/idle.go
test/extended/cli/run.go

OCPBUGS-15291: Update broken dc tests due to deprecation warning

---

pkg/monitor/backenddisruption/disruption_backend_sampler.go

[TRT-1124](https://issues.redhat.com/browse/TRT-1124)

Remove audit id from sample err

---

test/extended/util/framework.go

It should be possible to perform this check on a partial discovery response, as long as the desired group is not one of the groups for which discovery failed.

Handle partial discovery results in DoesApiResourceExist.

---

cmd/openshift-tests/disruption.go
pkg/cmd/monitor_command/run_monitor_command.go
pkg/monitor/api.go
pkg/monitor/event_test.go
pkg/monitor/monitor.go
pkg/monitor/monitor_test.go
pkg/monitor/types.go
test/extended/util/disruption/backend_sampler_tester.go

finish scrubbing out sampler

---

test/extended/cpu_partitioning/crio.go

added retry logic to lesson chance of flakes during runs 
removed custom exec logic and leveraged framework pod package to execute commands on pods

feat: make data gathering more robust

---

test/extended/cpu_partitioning/crio.go

I'm noticing some continued flakes and errors crop up around this test.
Some of the flakes below seem to be empty array errors, which should not be the case, so we might be eating an error there. Added some logic to print our any `stderr` and also retry if it's empty in a cluster where cpu partitioning is expected.
https://testgrid.k8s.io/redhat-openshift-ocp-release-4.14-informing#periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-cpu-partitioning&include-filter-by-regex=CPU%20Partitioning
I also noticed some [sippy](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.14/runs?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22failed_test_names%22%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22%5Bsig-node%5D%5Bapigroup%3Aconfig.openshift.io%5D%20CPU%20Partitioning% …

fix: workload partitioning - added more error handling for retry attempts

---

test/extended/util/image/OWNERS

Add Fabio and remove Stefan from image approvers

---

pkg/cmd/openshift-tests/disruption/disruption_command.go
pkg/cmd/openshift-tests/disruption/watch-endpointslice/endpointslice_controller.go

add comments requested in review

---

test/extended/authorization/scc.go
test/extended/util/annotate/generated/zz_generated.annotations.go

cc: @xingxingxia @stlaz @s-urbaniak

add e2e non-functional test for required-scc SCCs 

---

pkg/cmd/openshift-tests/run/flags.go

Fixes https://github.com/openshift/origin/issues/28159

Fixes openshift-tests dry-run failure asking for KUBERNETES_MASTER

---

pkg/monitortests/network/disruptionpodnetwork/host-network-target-deployment.yaml
pkg/monitortests/network/disruptionpodnetwork/host-network-target-service.yaml
pkg/monitortests/network/disruptionpodnetwork/host-network-to-host-network-poller-deployment.yaml
pkg/monitortests/network/disruptionpodnetwork/host-network-to-pod-network-poller-deployment.yaml
pkg/monitortests/network/disruptionpodnetwork/monitortest.go
pkg/monitortests/network/disruptionpodnetwork/pod-network-to-host-network-poller-deployment.yaml
pkg/monitortests/network/disruptionpodnetwork/pod-network-to-pod-network-poller-deployment.yaml

builds on https://github.com/openshift/origin/pull/28189

fail if no sampler output is found for the poller

---

pkg/monitortests/network/disruptionpodnetwork/host-network-target-deployment.yaml
pkg/monitortests/network/disruptionpodnetwork/host-network-target-service.yaml
pkg/monitortests/network/disruptionpodnetwork/host-network-to-host-network-poller-deployment.yaml
pkg/monitortests/network/disruptionpodnetwork/host-network-to-pod-network-poller-deployment.yaml
pkg/monitortests/network/disruptionpodnetwork/monitortest.go
pkg/monitortests/network/disruptionpodnetwork/pod-network-to-host-network-poller-deployment.yaml
pkg/monitortests/network/disruptionpodnetwork/pod-network-to-pod-network-poller-deployment.yaml

Cannot merge until the image is fully available for micro upgrades.

add host-to-pod disruption checking

---

test/extended/cli/basics.go
test/extended/cli/policy.go
test/extended/images/resolve.go
test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/testdata/application-template-mix.json
test/extended/testdata/deployments/deployment-simple-sleep.yaml
test/extended/util/annotate/generated/zz_generated.annotations.go

To get [periodic-ci-openshift-release-master-ci-4.14-e2e-aws-ovn-no-capabilities](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.14-e2e-aws-ovn-no-capabilities/1691809211568099328) passing

Reduce usage of dcs

---

test/extended/networking/egressip_helpers.go

ovnkube-node pod may have either ovnkube-node or ovnkube-controller container with the latest ovn-ic changes. Choose the existing container to run commands.
Tested with cluster -bot cluster based on https://github.com/openshift/cluster-network-operator/pull/1971

[test/extended/networking] Rename ovnkube containers

---

pkg/cmd/openshift-tests/images/images_command.go
test/extended/util/image/zz_generated.txt

Reverts #28200 #28248 
/assign @bertinatto

Revert fake image injections for k8s 1.28

---

test/extended/quota/resourcequota.go
test/extended/util/annotate/generated/zz_generated.annotations.go

@soltysh Raised PR for fix of https://github.com/openshift/origin/pull/28224 in which case failing due to race conditions between https://github.com/openshift/origin/pull/28224/files#diff-32e49140009708cb088e99988f5471cbf622f7ef2fe9d7bd6fa4fb1a98a67a42R121 and https://github.com/openshift/origin/pull/28224/files#diff-32e49140009708cb088e99988f5471cbf622f7ef2fe9d7bd6fa4fb1a98a67a42R124

fix PR 28224

---

pkg/monitortests/network/disruptionpodnetwork/monitortest.go

This will prevent the early "service is not reachable" problem.

wait for the service to have endpoints before starting pollers

---

pkg/defaultmonitortests/types.go

some monitor tests only function on disruptive tests

---

test/extended/quota/resourcequota.go
test/extended/util/annotate/generated/zz_generated.annotations.go

@soltysh Please review this PR 
Test run - https://privatebin.corp.redhat.com/?5e3a606a01e6ba72#3VwE9iHzqvht8tEagksodSgqBorG6w1LGray2t8tW88u

Automating test "check the quota after import-image with --all option" in upstrem

---

pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go

[TRT-1269](https://issues.redhat.com/browse/TRT-1269)

Fix bug with disable-monitor

---

pkg/monitor/monitor.go

[TRT-1267](https://issues.redhat.com//browse/TRT-1267)
Set final intervals back to bound based on Monitor start/stop time.
This ensures that the serializes run specifically for the intervals for their particular phase where they ran and not run for the entire set of intervals.  The serializers can run twice (once for upgrade phase and once for e2e phase).  Before this change, we would attempt (and fail) to upload intervals to loki from the previous phase.

Limit intervals to the current phase (addresses loki upload problems)

---

test/extended/quota/resourcequota.go
test/extended/util/annotate/generated/zz_generated.annotations.go

@soltysh Backporting https://github.com/openshift/origin/pull/28238 and https://github.com/openshift/origin/pull/28295 to 4.14 release

OCPBUGS-20308: Backport PR 28295 and 28238

---

test/e2e/upgrade/upgrade.go

Reverts openshift/origin#28074

SDN-4062: Revert "SDN-4042: Increase total upgrade time on OVN platforms"

---

test/extended/quota/resourcequota.go
test/extended/util/annotate/generated/zz_generated.annotations.go

@elfosardo @stbenjam Please review this PR. For failure on disconnected env
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-ovn-ipv6/1711658474384920576
Ran 1 of 1 Specs in 30.284 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped

fix for OCP-11594 to skipped on disconnected env

---

pkg/monitortests/network/legacynetworkmonitortests/monitortest.go

[TRT-1298](https://issues.redhat.com/browse/TRT-1298)

Remove some redundant monitor tests

---

pkg/monitor/monitorapi/construction.go
pkg/monitortests/testframework/alertanalyzer/alerts.go

This will now appear in the locator and help with analysis about which
ClusterOperator is down/degraded. It may also prevent overlap problems
we could be experiencing when more than one is down.
[TRT-1235](https://issues.redhat.com//browse/TRT-1235)

Extract the cluster operator name from Down/Degraded Alerts

---

pkg/monitor/monitorapi/construction.go
pkg/monitor/monitorapi/types.go
pkg/monitortests/testframework/watchclusteroperators/operator.go

[TRT-1319](https://issues.redhat.com//browse/TRT-1319)

Port remaining clusteroperator monitor intervals to structured

---

e2echart/e2e-chart-template.html
e2echart/non-spyglass-e2e-chart-template.html
test/extended/testdata/bindata.go

This was broken sometime recently and nobody noticed. This change brings
back yellow intervals for when node's were NotReady. Unfortunately,
there appear to be quite a few, and I have no idea how unusual this is.

Restore Node NotReady intervals

---

pkg/cmd/openshift-tests/monitor/timeline/timeline_command.go

This looks like something that may have been used during development of the new monitortest framework but possibly wasn't meant to be committed.
It does not seem like we would expect the monitortest command to reprocess intervals. If so, it seems broken and is lacking documentation as to what's going on. Using this locally you get a bunch of intervals at the start of the chart with no from, causing it to try to display a year, leaving all your actual intervals in a sliver on the right.

Remove timelines command reprocessing intervals

---

pkg/monitortests/node/nodestateanalyzer/node.go

This was caused by some bag logic here that assumed to closed a node NotReady interval any time we see an interval with a node in the locator, and a reason of Ready, which was picking up container Readys incorrectly. Nodes are not actually flapping as it appeared.
Fix by being more careful with the source of the interval so we know we're interpreting the precise intervals we intend.
[TRT-1327](https://issues.redhat.com//browse/TRT-1327)

Fix intervals mistakenly showing mass node NotReady

---

tls/raw-data/raw-tls-artifacts-ha-amd64-aws-ovn.json
tls/raw-data/raw-tls-artifacts-ha-amd64-aws-sdn.json
tls/raw-data/raw-tls-artifacts-ha-amd64-azure-ovn.json
tls/raw-data/raw-tls-artifacts-ha-amd64-azure-sdn.json
tls/raw-data/raw-tls-artifacts-ha-amd64-gcp-ovn.json
tls/raw-data/raw-tls-artifacts-ha-amd64-gcp-sdn.json
tls/raw-data/raw-tls-artifacts-ha-amd64-metal-ovn.json
tls/raw-data/raw-tls-artifacts-ha-amd64-metal-sdn.json
tls/raw-data/raw-tls-artifacts-ha-amd64-vsphere-ovn.json
tls/raw-data/raw-tls-artifacts-ha-amd64-vsphere-sdn.json
tls/raw-data/raw-tls-artifacts-single-amd64-aws-ovn.json

/hold
just giving us a starting point.

start adding raw tls info

---

.gitignore
Makefile
cmd/update-tls-artifacts/update-tls-artifacts.go
go.mod
hack/update-tls-ownership.sh
hack/verify-tls-ownership.sh
pkg/cmd/update-tls-artifacts/generate-owners/generate_owners_flags.go
pkg/cmd/update-tls-artifacts/generate-owners/generate_owners_options.go
tls/ownership/ownership.md
tls/ownership/tls-ownership.json
tls/violations/OWNERS
tls/violations/README.md
tls/violations/ownership/ownership-violations.json
vendor/modules.txt

and corresponding verify
/assign @vrutkovs

add hack/update-tls-ownership.sh

---

go.mod
go.sum
test/extended/operators/certs.go
vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/collector.go
vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/options.go
vendor/modules.txt

proof of https://github.com/openshift/library-go/pull/1599

skip revisioned certificates in raw info

---

test/extended/prometheus/prometheus.go
test/extended/util/prometheus/helpers.go

Reverts openshift/origin#28320

OCPBUGS-23102: Revert "[sig-instrumentation] tests fail due to JSON parsing error."

---

pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_events.go
pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_events_test.go
pkg/monitortests/testframework/watchevents/event_test.go

Reverts openshift/origin#28381

Revert "TRT-1339: Revert #28233 "ignore repeated TopologyAwareHintsDisabled events""

---

test/extended/images/hardprune.go
test/extended/images/oc_tag.go

To unblock https://github.com/openshift/oc/pull/1596

WRKLDS-908: test: ignore deprecation warnings in command outputs

---

go.mod
go.sum
test/extended/operators/certs.go
vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/collection_options.go
vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/collector.go
vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/filtering_options.go
vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
vendor/modules.txt

builds on https://github.com/openshift/origin/pull/28405

update cert inspect to skip the rest of proxy-CAs

---

examples/image-streams/image-streams-centos7.json
examples/sample-app/application-template-dockerbuild.json
examples/sample-app/application-template-pullspecbuild.json
examples/sample-app/application-template-stibuild.json
test/extended/testdata/bindata.go
test/extended/testdata/cmd/test/cmd/deployments.sh
test/extended/testdata/cmd/test/cmd/testdata/application-template-dockerbuild.json
test/extended/testdata/cmd/test/cmd/testdata/new-app/template-with-app-label.json
test/extended/testdata/cmd/test/cmd/testdata/new-app/template-without-app-label.json

Reverts openshift/origin#28365

Revert "[release-4.14] OCPBUGS-22720: Use Centos 8 Stream mysql image in tests"

---

tls/ownership/ownership.md
tls/ownership/tls-ownership.json
tls/raw-data/raw-tls-artifacts-ha-amd64-aws-ovn.json
tls/raw-data/raw-tls-artifacts-ha-amd64-aws-sdn.json
tls/raw-data/raw-tls-artifacts-ha-amd64-azure-ovn.json
tls/raw-data/raw-tls-artifacts-ha-amd64-azure-sdn.json
tls/raw-data/raw-tls-artifacts-ha-amd64-gcp-ovn.json
tls/raw-data/raw-tls-artifacts-ha-amd64-gcp-sdn.json
tls/raw-data/raw-tls-artifacts-ha-amd64-metal-ovn.json
tls/raw-data/raw-tls-artifacts-ha-amd64-metal-sdn.json
tls/raw-data/raw-tls-artifacts-ha-amd64-vsphere-ovn.json
tls/raw-data/raw-tls-artifacts-ha-amd64-vsphere-sdn.json
tls/raw-data/raw-tls-artifacts-single-amd64-aws-ovn.json
tls/violations/ownership/ownership-violations.json

update the TLS ownership files using https://amd64.ocp.releases.ci.openshift.org/releasestream/4.15.0-0.nightly/release/4.15.0-0.nightly-2023-11-13-174800
/assign @vrutkovs

update the TLS ownership files

---

pkg/cmd/update-tls-artifacts/generate-owners/generate_owners_options.go
pkg/cmd/update-tls-artifacts/generate-owners/markdown.go
tls/ownership/ownership.md

review with whitespace diff off

make it slightly easy to produce markdown with table of contents

---

pkg/monitortestlibrary/disruptionlibrary/disruption_invariant_adapter.go

JobType is checked at startup, prior to any upgrade resulting in upgrade jobs being identified as non upgrade
[periodic-ci-openshift-release-master-ci-4.15-e2e-aws-ovn-upgrade](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.15-e2e-aws-ovn-upgrade/1727794032999927808)
`JobType:platformidentification.JobType{Release:"4.15", FromRelease:"", Platform:"aws", Architecture:"amd64", Network:"ovn", Topology:"ha"}}`
[StartCollection](https://github.com/openshift/origin/blob/b01a3e6c856fe176d3725a2a7728ae2d880fcd84/pkg/monitortestlibrary/disruptionlibrary/disruption_invariant_adapter.go#L41) -> [VersionFromHistory](https://github.com/openshift/origin/blob/b01a3e6c856fe176d3725a2a7728ae2d880fcd84/pkg/monitortestlibrary/platformidentification/types.g …

trt-1367: Get JobType After Collection Ends

---

pkg/monitortestlibrary/podaccess/pod_log_streamer.go

now fits in the margin.
@neisw

eliminate the closed channel race in pod_log_streamer

---

Makefile
test/extended/etcd/etcd_storage_path.go

OCPNODE-1892: Update ETCD storage data for k8s 1.29

---

pkg/test/ginkgo/cmd_runsuite.go

/assign @sairameshv
/hold
for TRT review

OCPNODE-1892: Conditionally skip tests to help with k8s 1.29

---

OWNERS_ALIASES

add pacevedom to the team-leads alias

---

pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadata/autoregenerate_after_expiry/requirement.go
pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadata/ownership/requirement.go
pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/annotation_requirement.go
pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/markdown.go
pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/types.go
test/extended/operators/certs.go
tls/autoregenerate-after-expiry/autoregenerate-after-expiry.md
tls/ownership/ownership.md

cleanup of https://github.com/openshift/origin/pull/28450

update-tls-artifacts: add AnnotationRequirement

---

test/extended/etcd/etcd_storage_path.go

OCPNODE-1892: Update etcd test data for 1.29 release

---

pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadata/descriptions/requirement.go
pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatadefaults/defaults.go
tls/descriptions/descriptions.json
tls/descriptions/descriptions.md
tls/violations/descriptions/descriptions-violations.json

builds on https://github.com/openshift/origin/pull/28460

Show how we can add new annotations using descriptions

---

pkg/disruption/backend/disruption/handler.go
pkg/disruption/backend/shutdown/handler.go
pkg/monitor/backenddisruption/disruption_backend_sampler.go
pkg/monitor/backenddisruption/disruption_locator.go
pkg/monitor/monitorapi/types.go
pkg/monitor/recorder.go
pkg/monitor/recorder_jsonl.go
pkg/monitortests/etcd/etcdloganalyzer/monitortest.go
pkg/monitortests/node/kubeletlogcollector/node.go
pkg/monitortests/node/legacynodemonitortests/kubelet.go
pkg/test/ginkgo/test_runner.go

- Finish porting kubelet log intervals to structured
- Port some more etcd log intervals to structured
- Port disruption intervals to structured
- Fix e2e test intervals without a source
- Port ovs-vswitchd log intervals to structured

TRT-1403: Finish porting ALL intervals to structured

---

test/extended/security/labels.go
test/extended/util/annotate/generated/zz_generated.annotations.go

/hold until https://github.com/openshift/kubernetes/pull/1735 merges.

e2e node label test to verify blocking forbidden labels

---

test/extended/cli/service.go

Port number `30000` may be used in nodes by legitimate services and `oc service`
tests may incorrectly fail due to the already allocated port error. To prevent this and
have a stable test, this PR adds a simple retry with port number `30001`, if it gets
an allocated port error.

OCPBUGS-25142: Retry with different node port to make oc service test stable

---

test/extended/operators/operators.go

Kuryr SDN is removed from 4.15 and 4.14 blocks upgrades if it's configured. This patch makes sure operator tests are ignoring such a condition.

OCPBUGS-25730: Kuryr: Ignore Upgradeable=False on operators tests

---

test/extended/operators/certs.go

TechPreview can add or remove TLS artifacts as its developing.
/assign @vrutkovs

add featureset into the raw-tls artifact names

---

test/extended/storage/csi_snapshot_controller_operator.go
test/extended/storage/helpers.go
test/extended/util/annotate/generated/zz_generated.annotations.go
test/extended/util/deployment.go

https://issues.redhat.com/browse/STOR-1443
To run this test manually against an existing cluster:
make && ./openshift-tests run all --dry-run | grep 'Feature:Cluster-CSI-Snapshot-Controller-Operator' | ./openshift-tests run -f -
/cc @openshift/storage-qe

STOR-1521: Add e2e test cases cover STOR-1443

---

e2echart/e2e-chart-template.html
pkg/monitor/monitorapi/types.go
pkg/monitortests/etcd/etcdloganalyzer/monitortest.go
test/extended/testdata/bindata.go

[TRT-1370](https://issues.redhat.com//browse/TRT-1370)
This adds the `etcd-leaders` section in the spyglass charts to help us track etcd leader changes more clearly.

TRT-1370: Track etcd leadership changes in etcd-leaders section of spyglass chart

---

test/extended/router/http2.go

This PR addresses a specific issue with the HTTP/2 tests in test/extended/router. Due to current limitations in the haproxy.config configuration, two tests - `http2-default-cert-edge` and `http2-default-cert-reencrypt` - cannot accurately assert that the frontend protocol is HTTP/2.0. As a temporary measure, this PR removes these tests. It's important to emphasise that this change is only provisional, and we plan to resurrect these tests once the underlying issue with haproxy.config is resolved.
https://issues.redhat.com/browse/OCPBUGS-27210 is a blocker bug for OCP 4.16. If we haven't fixed these two tests w.r.t HAProxy 2.8 then these changes should be reverted.
Our current haproxy configuration prevents us from asserting the frontend protocol as HTTP/2.0 when testing a route that uses …

NE-1444: test/extended/router/http2: delete skipped tests

---

OWNERS_ALIASES

@omertuc I talked with @romfreiman and he suggested you should be the lead here. 
@bparees @dhellmann fyi

NO-JIRA: Update Omer to be the SNO lead

---

pkg/disruption/ci/factory_test.go
test/extended/util/disruption/controlplane/known_backends.go

Bumping timeout values to better line up with https://github.com/openshift/origin/pull/28037/

trt-1141: bump timeout values

---

pkg/monitortests/testframework/disruptionexternalservicemonitoring/monitortest.go

Found this while looking at problem.

NO-JIRA: remove unnecessary setup code from monitor

---

test/extended/prometheus/prometheus.go
test/extended/util/prometheus/helpers.go

supersedes #28390
cc @raptorsun

OCPBUGS-18776: replace curl calls by net/http

---

test/extended/operators/crd_must_be_stable.go

IOU found based on https://search.ci.openshift.org/?search=has+an+unstable+version&maxAge=168h&context=1&type=bug%2Bissue%2Bjunit&name=4.16&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
oops.  Otherwise this is looking good.  Need to check again next week.
/assign @JoelSpeed

NO-JIRA: techpreview can install unstable CRDs

---

e2echart/e2e-chart-template.html
e2echart/non-spyglass-e2e-chart-template.html
pkg/monitortests/testframework/timelineserializer/rendering.go
test/extended/testdata/bindata.go

Also removed some sections and parts of sections we discussed and deemed not worth including at this top level. Many more details available in the charts generated in artifacts. This dramatically cuts down the size of the spyglass html  and seems to improve load times in prow a fair bit.

TRT-1491: Reorder interval groups to place most important/brief info higher up

---

test/extended/machines/machines.go

We support single node with workers, so when trying to determine if something is a single node deployment or not doing a node count will not be accurate. Updated logic to look for the control plane topology which does take into account single node with workers.

OCPBUGS-29493: fix: updated unit test to look for topology not node count

---

pkg/clioptions/clusterdiscovery/provider.go

In very rare circumstances we see some NetPol tests that should be
skipped on OVN clusters being run. This logging will help us understand
why the next time it happens.

TRT-1501: Add debug logging for decoding cluster provider

---

pkg/monitortestframework/impl.go

This is the corresponding change on 4.15 for https://github.com/openshift/origin/pull/28604

[release-4.15] TRT-1512: Add debug messages to debug openshift-tests hang

---

pkg/defaultmonitortests/types.go
pkg/monitortests/testframework/disruptionexternalgcpcloudservicemonitoring/cloudmonitortest.go

Reverts openshift/origin#28603

TRT-1476: Re-introduce the GCP liveness endpoint test

---

test/extended/prometheus/prometheus.go
test/extended/util/prometheus/helpers.go

Fix for [OCPBUGS-29028](https://issues.redhat.com/browse/OCPBUGS-29028)

OCPBUGS-29028: Add function back to execute commands via pod

---

test/extended/kernel/common.go

OCPBUGS-31513: feat: update regex for rt kernel version match

---

test/extended/image_ecosystem/s2i_images.go
test/extended/image_ecosystem/s2i_php.go
test/extended/image_ecosystem/s2i_ruby.go
test/extended/image_ecosystem/sample_repos.go
test/extended/util/annotate/generated/zz_generated.annotations.go

This required for the release process of samples operator for ocp4.16

SO-121: Samples Release, fix test cases

---

pkg/monitortestframework/impl.go
pkg/monitortests/kubeapiserver/auditloganalyzer/audit_log_summarizer.go
pkg/monitortests/kubeapiserver/auditloganalyzer/audit_log_summary_serialization.go

to ease "what is this operator doing" checks.  Could be uploaded to associate operator and per-resource,per-verb usage.
/assign @neisw 
/cc @yuqi-zhang

NO-JIRA: split the per-user summary to include verbs for resources

---

pkg/testsuites/standard_suites.go

NO-JIRA: Unskip volume populator tests that were disabled in the test suite

---

test/extended/cpu_partitioning/crio.go

Reverting OCPBUGS-31074, the error that caused this was resolved.

OCPBUGS-32320: revert: removing static pod skip for crio check

---

pkg/cmd/openshift-tests/monitor/summarize-audit-logs/cmd.go
pkg/dataloader/types.go
pkg/monitortests/kubeapiserver/auditloganalyzer/audit_log_summarizer.go
pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go
pkg/monitortests/kubeapiserver/auditloganalyzer/node_log.go

Builds on https://github.com/openshift/origin/pull/28705 to create json output for bq loading

NO-JIRA: Create autodl file for per user resource request audit entries

---

test/extended/controller_manager/pull_secret.go

Change GetPrometheusSABearerToken to use TokenRequest API instead of expecting an already existing API token secret.

NO-JIRA: Use bound prometheus-k8s API tokens

---

go.mod
go.sum
pkg/certs/types.go
pkg/certs/utils.go
pkg/cmd/openshift-tests/collect-disk-certificates/collector.go
pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadata/ownership/requirement.go
pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/annotation_requirement.go
pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/helpers.go
pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/simple_requirements_result.go
test/extended/operators/certs.go
vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphapi/type_registry.go
vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphutils/util.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
vendor/github.com/openshift/library-go/test/library/metrics/query.go
vendor/modules.txt

Needed to pickup https://github.com/openshift/library-go/pull/1697.

NO-JIRA: bump library-go

---

test/extended/networking/endpoint_admission.go

use TokenRequest API instead of legacy API token secret

OCPBUGS-33317: use tokenrequest api

---

test/extended/etcd/etcd_storage_path.go

API-1783: Update etcd test data for 1.30 release

---

test/extended/builds/start.go
test/extended/builds/webhook.go

Reverts #28750 ; tracked by [TRT-1656](https://issues.redhat.com//browse/TRT-1656)
TestWebhook test is failing on minor upgrades due to a problem with AUTH-509, until that's resolved we need to kick this out of the payload.  It can be reintroduced when /payload testing verifies minor upgrades succeed
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:
```
/payload 4.16 …
```

TRT-1656: Revert #28750 "OCPBUGS-33041: Add RoleBinding for BuildConfig Webhooks"

---

test/extended/etcd/hardware_speed.go
test/extended/util/annotate/generated/zz_generated.annotations.go
zz_generated.manifests/test-reporting.yaml

I had the wrong feature gate option so this test wasn't getting scraped properly

ETCD-488: Fix feature gate for etcd profiles e2e test

---

pkg/monitortests/clusterversionoperator/terminationmessagepolicy/monitortest.go
pkg/monitortests/monitoring/disruptionmetricsapi/monitortest.go

USHIFT-3143: Skip metrics and adjust termination message policy monitor tests

---

test/extended/cli/template.go

NO-JIRA: oc template - set NS PSP level=privileged (hostPorts)

---

test/extended/dr/OWNERS
test/extended/dr/cert_rotation.go
test/extended/dr/common.go
test/extended/etcd/OWNERS
test/extended/util/annotate/generated/zz_generated.annotations.go

This PR adds a suite of tests related to rotation of etcd certificates.

ETCD-565: add manual etcd signer cert rotation e2e test

---

.golangci.yml
pkg/test/ginkgo/cmd_runsuite.go

API-1783: Conditionally skip tests to help with k8s 1.30

---

pkg/monitortestlibrary/podaccess/pod_logs_stream_all.go

400ish lines of error logging coming out of etcd pods was generating
over 12 million characters logged to the build-log.txt, mostly because
it was including a full massive podspec dump for each line. Settle the
logging down by just displaying the locator. Switches to using logrus
for structured logging.

TRT-1686: Reduce logging of podspec in the PodsStreamer

---

test/extended/util/test.go

[release-4.13] OCPBUGS-33985: Provide SCC access via RBAC

---

test/extended/cpu_partitioning/crio.go

NO-JIRA: test: skip crio test for rt runs

---

test/extended/operators/resources.go

re https://github.com/openshift/cluster-network-operator/pull/2401
/assign @sdodson 
/hold
for testing

OCPBUGS-33497: Add a "limit" exception for iptables-alerter

---

go.mod
images/tests/Dockerfile.rhel

Replaces https://github.com/openshift/origin/pull/28827
Had to layer in go mod tidy.

OCPBUGS-34468: art consistency openshift 4.17 openshift enterprise tests custom

---

pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadata/autoregenerate_after_expiry/requirement.go
pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadata/descriptions/requirement.go
pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadata/ownership/requirement.go
pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/annotation_requirement.go
vendor/github.com/openshift/library-go/pkg/markdown/markdown.go
vendor/modules.txt

Rebase of https://github.com/openshift/origin/pull/28671 on master

NO-JIRA: use lib-go version of the markdown interface

---

test/extended/machines/cluster.go
test/extended/machines/cluster_test.go
test/extended/machines/display_reboots_pod.yaml

/assign @rphillips 
/cc @jupierce

NO-ISSUE: fix the node reboot test to actually run

---

pkg/monitortests/clusterversionoperator/legacycvomonitortests/operators.go

added exceptions for single node operators that go unavailable during serial tests that explicitly cause roll out of those operators, due to the nature of single node, this is acceptable

OCPEDGE-1157: fix: resolve serial operator availability

---

test/extended/etcd/leader_changes.go

cc @sanchezl 
This PR is against 4.15 and has no parent because this is only and issue for 4.15 and earlier.  Will need to be backported to at least 4.14.

OCPBUGS-34949: test/extended: skip etcd leader change check on hypershift

---

test/extended/util/openshift/clusterversionoperator/adminack.go

…
Continuing the work I'd started in d08744620a
(test/extended/util/openshift/clusterversionoperator: Survive API hiccups, 2022-04-21, #27041), because recent runs like [1] sometimes fail like:
```
disruption_tests: [bz-Cluster Version Operator] Verify presence of admin ack gate blocks upgrade until acknowledged expand_less	2h30m29s
{Your Test Panicked
github.com/openshift/origin/test/extended/util/openshift/clusterversionoperator/adminack.go:153
When you, or your assertion library, calls Ginkgo's Fail(),
Ginkgo panics to prevent subsequent assertions from running.
Normally Ginkgo rescues this panic so you shouldn't see it.
However, if you make an assertion in a goroutine, Ginkgo can't capture the
panic.
To circumvent this, you should call
defer GinkgoRecover()
at the top of the goroutine …
```

OCPBUGS-36403: test/extended/util/openshift/clusterversionoperator/adminack: No nested framework.Fail

---

test/extended/cpu_partitioning/crio.go

Logging for this failure state is not descriptive enough to determine what failed where, updating to help log better information.

OCPEDGE-1125: upkeep: add better logging for crio failures

---

test/extended/util/client.go

Needed for https://github.com/openshift/cluster-version-operator/pull/1066

no-jira: e2e: check for deployer SA only when DeploymentConfig is enabled

---

test/extended/networking/network_segmentation.go
test/extended/util/annotate/generated/zz_generated.annotations.go
zz_generated.manifests/test-reporting.yaml

This PR introduces a test framework with the e2e tests for the user defined primary network feature.

SDN-5133: Add udn test framework

---

test/extended/storage/helpers.go
test/extended/storage/s3_configuration.go
test/extended/util/annotate/generated/zz_generated.annotations.go
zz_generated.manifests/test-reporting.yaml

IR-471: Updating the test with skipper function

---

test/extended/router/h2spec.go
test/extended/router/http2.go

manual cherry-pick https://github.com/openshift/origin/pull/28880

[release-4.15] OCPBUGS-36264: add Proxy config

---

test/extended/networking/network_segmentation_endpointslice_mirror.go

Internal IPs are exact addresses so the previous IP family check always returned false.

OCPBUGS-38359: NetworkSegmentation tests: fix the IPv6 node IP detection

---

cmd/openshift-tests/openshift-tests.go
pkg/cmd/openshift-tests/run_resource_watch/resourcewatch.go
pkg/resourcewatch/operator/starter.go

Found these missing while debugging a node lifecycle problem.
/assign @neisw @xueqzhan

NO-JIRA: add important resources to watch

---

test/extended/apiserver/graceful_termination.go

addresses https://github.com/openshift/origin/pull/29015#discussion_r1721639292

NO-JIRA: apiserver/graceful_termination: simplify condition for "kubelet terminates kube-apiserver gracefully extended" test

---

pkg/monitor/monitorapi/types.go
pkg/monitortests/node/watchnodes/monitortest.go
pkg/monitortests/node/watchnodes/node.go

Rename UnexpectedUnreachable to NodeUnexpectedUnreachableReason.
And added a Unreached but expected interval.

NO-JIRA: rename unexpected node unreachable and add unreachable interval

---

test/extended/etcd/etcd_storage_path.go

/assign @bertinatto @atiratree 
/hold 
for testing

WRKLDS-1449: Update etcd test data for 1.31 release

---

OWNERS

NO-JIRA: Expand approvers for origin

---

test/extended/cpu_partitioning/crio.go

in crictl 1.31.1 the data for inspecting multiple container is is now given as a json array, where as before it was given as individual items, grouping is no longer needed going forward.

OCPBUGS-38805: fix: removed grouping flag for jq

---

pkg/monitortests/network/disruptionpodnetwork/utils.go

With
https://github.com/openshift/origin/pull/28764
we are eventually extracting the pull secret from
the cluster under test to be able to inspect the
release image to gather the test one.
This is not always enough on disconnected environments where the internal registry is not only requiring a custom pull-secret but also to trust a custom CA.
Without this we can see errors like:
``` 
{
s: "unable to determine openshift-tests image oc wrapper with cluster ps: Error running /usr/bin/oc adm release info virthost.ostest.test.metalkube.org:5000/localimages/local-release-image@sha256:d368cc92e8d274744aac655e070d3a346f351fc5bd5f18a227b73452fd5c58b7 --image-for=tests --registry-config /tmp/image-pull-secret2435751342:\nStdOut>\nerror: unable to read image …
```

OCPBUGS-38792: Try also user CA for getting openshift-tests image

---

pkg/monitortests/network/disruptionpodnetwork/monitortest.go

added a check to make sure the sa pull secrets are present before applying the deployments

OCPBUGS-38650: fix: add check for sa secrets after ns creation

---

test/extended/ci/job_names.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Guard against job names being incorrect for techpreview and FIPS jobs.

NO-JIRA: Additional job name verification tests

---

test/extended/apiserver/rollout.go

We are sometimes leaving this test with kube-apiserver operator "Progressing" -- this triggers a failure in gather-extra of the "operator conditions kube-apiserver" test, which expects operators to be stable when the job finishes.
Before we return from this test, make sure kube-apiserver is not progressing.

OCPBUGS-39030: kube-apiserver rollout: wait for stability before exiting

---

test/extended/olm/OWNERS

Allow OLM members to get PR merged easier.

NO-JIRA: Update ONWERS list to add current OLM members and remove former ones

---

pkg/clioptions/iooptions/io_options.go
pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
pkg/cmd/openshift-tests/run-disruption/disruption.go
pkg/defaultmonitortests/types.go
pkg/disruption/ci/backend_sampler.go
pkg/disruption/ci/factory.go
pkg/disruption/ci/host_decoder.go
pkg/monitor/monitorapi/disruption.go
pkg/monitortestframework/types.go
pkg/monitortestlibrary/disruptionlibrary/collect.go
pkg/monitortestlibrary/disruptionlibrary/deployment.go
pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/clusterrole-monitor.yaml
pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/crb-monitor.yaml
pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/crb-privileged.yaml
pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-internal-lb.yaml
pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-localhost.yaml
pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-service-network.yaml
pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/namespace.yaml
pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/rb-monitor.yaml
pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/role-monitor.yaml
pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/serviceaccount.yaml
pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/remote.go
pkg/monitortests/kubeapiserver/disruptionlegacyapiservers/monitortest.go
pkg/monitortests/kubeapiserver/disruptionnewapiserver/monitortest.go
pkg/monitortests/network/disruptionpodnetwork/monitortest.go
pkg/monitortests/network/legacynetworkmonitortests/disruption.go
pkg/test/ginkgo/cmd_runsuite.go
test/extended/operators/manifests/pod.yaml
test/extended/util/disruption/controlplane/known_backends.go

This reverts commit 12feee9.
Skip creating disruption junits when loadbalancer is "localhost". Also needs https://github.com/openshift/ci-tools/pull/4251 to make it pass in aggregated jobs

OCPBUGS-18865: Reapply "Merge pull request #28944 from vrutkovs/in-cluster-fixes-v4"

---

pkg/monitortests/clusterversionoperator/legacycvomonitortests/operators.go

Start with failing operators that are degraded during test. We will capture all operators and analyze cases to see if exceptions should be created.

TRT-1578: Enable operator degraded check

---

pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go

**Description:**
A vSphere platform external job is being added [here](https://github.com/openshift/release/pull/54649). There is variability in whether or not an external CCM has support for service load balancers.  The vSphere CCM is one such CCM that does not support service load balancers.
**Change:**
By default, the service load balancer tests will be enabled for platform external. A helper function has been created which allows CCMs which do not support service load balancers to disable the test for platforms which don't support service load balancers.

SPLAT-1624: skip disruptionserviceloadbalancer for platform external with vSphere CCM

---

pkg/monitortests/network/legacynetworkmonitortests/networking.go

https://github.com/openshift/multus-cni/commit/a95c1f46#diff-2a0a19881ba102c36dc17295504ba6fb9f4a0fd42f54410323014e6fdeb7d1b1L535 changed the string we need to search for to differently categorize this problem

OCPBUGS-41270: Update the NotFound case for CNI plugin to reflect changes

---

pkg/cmd/openshift-tests/monitor/summarize-audit-logs/cmd.go
pkg/monitortests/kubeapiserver/auditloganalyzer/handle_excessive_applies.go
pkg/monitortests/kubeapiserver/auditloganalyzer/handle_summarizer.go
pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go
pkg/monitortests/kubeapiserver/auditloganalyzer/node_log.go

prevents an operator from making more than 200 SSA requests in a given job run

API-1835: prevent excessive server-side-applies

---

pkg/cmd/openshift-tests/monitor/summarize-audit-logs/cmd.go
pkg/defaultmonitortests/types.go
pkg/monitortests/kubeapiserver/auditloganalyzer/handle_excessive_applies.go
pkg/monitortests/kubeapiserver/auditloganalyzer/handle_summarizer.go
pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go
pkg/monitortests/kubeapiserver/auditloganalyzer/node_log.go
pkg/monitortests/testframework/watchnamespaces/monitortest.go
pkg/monitortests/testframework/watchnamespaces/namespaces.go

/assign @bertinatto 
@stbenjam which specific payload test would you like?

NO-JIRA: bringing back the server-side apply test

---

pkg/cmd/openshift-tests/monitor/summarize-audit-logs/cmd.go
pkg/defaultmonitortests/types.go
pkg/monitortests/kubeapiserver/auditloganalyzer/handle_excessive_applies.go
pkg/monitortests/kubeapiserver/auditloganalyzer/handle_summarizer.go
pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go
pkg/monitortests/kubeapiserver/auditloganalyzer/node_log.go
pkg/monitortests/testframework/watchnamespaces/monitortest.go
pkg/monitortests/testframework/watchnamespaces/namespaces.go

One commit on top of https://github.com/openshift/origin/pull/29112.  If https://github.com/openshift/origin/pull/29112 tests green, plan to force merge thsi one.
/assign @bertinatto

Add apply exception

---

test/extended/dr/static_pod_rollouts.go

Check for the status of `EtcdMembersDegraded` condition type rather than quorum dependant controllers when quorum is unsafe.

ETCD-612: Changed the static pod rollout E2E test assertion checking for quorum dependant controllers degraded status

---

pkg/monitortests/kubeapiserver/auditloganalyzer/handle_excessive_applies.go
pkg/monitortests/kubeapiserver/auditloganalyzer/handle_invalid_requests.go
pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go

We want to catch users making invalid requests to prevent mistakes.

API-1835: don't allow platform users to make invalid requests

---

test/e2e/upgrade/upgrade.go

Adding an upgrade time override for AWS Metal instances which have a longer reboot cycle due to not being virtualized. This longer reboot cycle is causing upgrade failures on AWS Metal based SNO lanes.

OCPEDGE-1276: fix: adding in a SNO time override for AWS Metal

---

images/tests/Dockerfile.rhel

WRKLDS-1449: Fix kubernetes-tests version annotation

---

pkg/test/ginkgo/external.go

Add retries to handle race conditions in internal registry:
```
Suite run returned error: unable to extract image references from release payload: failed extracting image-references from "registry.build05.ci.openshift.org/ci-op-bqhp939x/release@sha256:343a7c80efb4b63423abdb0b61c5b7971a53a6eb12ef0934060a0996d942d47f": error during image extract: exit status 1 (error: image "registry.build05.ci.openshift.org/ci-op-bqhp939x/release@sha256:343a7c80efb4b63423abdb0b61c5b7971a53a6eb12ef0934060a0996d942d47f" not found: manifest unknown: manifest unknown
```

NO-JIRA: Allow extension binary extraction retries

---

pkg/monitortests/kubeapiserver/auditloganalyzer/handle_requests_during_graceful_shutdown.go
pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go

This may indicate LB issues/misconfiguration.
https://github.com/openshift/origin/pull/29058 is good one to trigger it

OCPBUGS-43483: auditloganalyzer: check audit log for requests arriving after shutdown

---

pkg/test/ginkgo/external.go

NO-JIRA: Additional logging for extract image and binaries

---

test/extended/networking/network_segmentation.go

port of https://github.com/ovn-org/ovn-kubernetes/pull/4809/commits/f02a9d141214e3f64157fbc7b9cca52572fcfa23
cc @trozet

SDN-4930: Don't modify pod routes in tests

---

test/extended/authorization/OWNERS

with a request from David Eads to add Ilias Rinis to the owners.

AUTH-539: Update OWNERS

---

test/extended/olm/olmv1.go
test/extended/testdata/bindata.go
test/extended/testdata/olmv1/install-operator.yaml
test/extended/util/annotate/generated/zz_generated.annotations.go

Install an operator from quay.io

OPRUN-3579: Add happy-path operator-contoller test

---

test/extended/etcd/helpers/helpers.go
test/extended/etcd/vertical_scaling.go

* Previously, the newly created machine was ensured to match the same index as the deleted machine to satisfy the requirement of having at least one Ready replica per index (when CPMS is disabled).
* However, the availability zone of the newly created machine was not aligned with that of the deleted machine. Instead, the new machine was cloned from the running machine with the lowest index, which sometimes led to the new machine being placed in the same availability zone as the other two machines. This uneven distribution caused issues when CPMS was re-enabled, as it would trigger an additional machine deletion to enforce even distribution across availability zones, leading to errors in the scaling jobs.
* Change: Now, a copy of the machine to be deleted is made initially, so it can be …

NO-JIRA: Newly created machine should belong to the same index and should be placed in the same availability zone as the deleted machine.

---

test/extended/prometheus/collection_profiles.go

Address `MetricsCollectionProfiles` failures on `metal` platform due to the absence of a CMO configuration.
***
Branched off of https://github.com/openshift/origin/pull/29265 since we do not want to run these tests on all platforms yet (that'll happen once this makes it into the default set of features).

NO-JIRA: address `MetricsCollectionProfiles` failures on `metal` platform

---

pkg/monitor/monitorapi/types.go
pkg/monitortests/node/watchnodes/monitortest.go
pkg/monitortests/node/watchnodes/node.go

- **Add new intervals when a node starts/stops reporting disk pressure**
- **Flake a test if we see kubelet report DiskPressure**

TRT-1761: kubelet disk pressure

---

test/extended/dr/common.go
test/extended/dr/recovery.go
test/extended/util/annotate/generated/zz_generated.annotations.go

this adds a simple quorum restore test using the newly introduced quorum-restore.sh

ETCD-657: add simple quorum restore test

---

pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/helpers.go
tls/autoregenerate-after-expiry/autoregenerate-after-expiry.json
tls/autoregenerate-after-expiry/autoregenerate-after-expiry.md
tls/descriptions/descriptions.json
tls/descriptions/descriptions.md
tls/ownership/ownership.json
tls/ownership/ownership.md
tls/violations/autoregenerate-after-expiry/autoregenerate-after-expiry-violations.json
tls/violations/descriptions/descriptions-violations.json

Spin-off from https://github.com/openshift/origin/pull/29074

API-1789: tls: add /etc/kubernetes/kubeconfig to known CA bundles

---

test/extended/cpu_partitioning/platform.go
test/extended/cpu_partitioning/pods.go
test/extended/operators/crd_must_be_stable.go
test/extended/operators/qos.go
test/extended/prometheus/prometheus.go

building onto previous excludes, GCP runs two additonal operators that
need to be taken into account

NO-JIRA: test/extended: additional excludes for osd-gcp

---

pkg/resourcewatch/operator/starter.go

This is useful to follow api changes rollouts.

NO-JIRA: watch CRDs

---

pkg/monitortests/node/legacynodemonitortests/exclusions.go
pkg/monitortests/node/legacynodemonitortests/exclusions_test.go

OCPBUGS-39315: remove ingress operator exclusion

---

test/extended/networking/network_segmentation_policy.go

The NetPol test checks assigned pod IP only against IPv4 subnet which would fail on IPv6 only cluster. This PR fixes it by checking on all valid CIDRs.

SDN-5017: Fix subnet check for assigned pod IPs

---

test/extended/networking/network_segmentation.go
test/extended/prometheus/collection_profiles.go
test/extended/storage/driver_configuration.go
test/extended/storage/s3_configuration.go

See https://issues.redhat.com/browse/OCPBUGS-48449 and https://issues.redhat.com/browse/OCPBUGS-48450 for details
More details are present in the individual commits

OCPBUGS-48238,OCPBUGS-48449,OCPBUGS-48450: Set the poll timeout and poll interval in eventually directly for the tests

---

test/extended/networking/network_segmentation.go

Upstream this was fixed in: https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4943
Without this fix, tests are hanging with:
```
[sig-network][OCPFeatureGate:NetworkSegmentation][Feature:UserDefinedPrimaryNetworks] when using openshift ovn-kubernetes when primary network exist, ClusterUserDefinedNetwork status should report not-ready [Suite:openshift/conformance/parallel]
github.com/openshift/origin/test/extended/networking/network_segmentation.go:972
STEP: Creating a kubernetes client @ 01/19/25 15:42:53.369
I0119 15:42:53.371599  105456 discovery.go:214] Invalidating discovery information
I0119 15:42:53.899935 105456 client.go:276] configPath is now "/tmp/configfile725811412"
I0119 15:42:53.899966 105456 client.go:325] The user is now …
```

SDN-4930: Fix CUDN manifest to account for IPV6 singlestack

---

test/extended/networking/livemigration.go
test/extended/networking/network_segmentation.go
test/extended/networking/network_segmentation_endpointslice_mirror.go

Upstream PR: https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4984

SDN-4930: Refactor and fix UDN/CUDN readiness checks

---

test/extended/networking/livemigration.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>
(cherry picked from commit 683bd67c7a837257264ea7bf7f72f6e110f0534f)

[release-4.18] OCPBUGS-48389: virt: add GA placeholder test

---

test/extended/networking/network_segmentation.go

We have seen in OCP CI that it can take two seconds or maybe more
for a single curl to succeed. Example:
```
I0120 00:38:42.320808 70120 builder.go:121] Running '/usr/bin/kubectl
--server=https://api.ci-op-bkg2qwwq-4edbf.XXXXXXXXXXXXXXXXXXXXXX:6443 --kubeconfig=/tmp/kubeconfig-1734723086
--namespace=e2e-test-network-segmentation-e2e-kzdw7 exec udn-pod -- curl --connect-timeout 2 --insecure https://kubernetes.default/healthz'
I0120 00:38:44.108334 70120 builder.go:146] stderr: "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100     2  100     2    0     0      9      0 --:--:-- --:--:-- --:--:-- …
```

OCPBUGS-48320,SDN-4930: Bump KAPI server timeout to be 5seconds

---

test/extended/networking/network_segmentation.go

Some of the network_segmentation tests are missing the Eventually when
checking connectivity between same network, this change address that.
Depends on:
- https://github.com/openshift/origin/pull/29415

SDN-4930: Network segmentation add missing eventually

---

pkg/clioptions/clusterinfo/wait_for_stable_cluster.go
pkg/test/ginkgo/cmd_runsuite.go

Reverts openshift/origin#29399
/hold for testing

Revert "Revert "TRT-1803: Wait for operators to become stable before test""

---

test/extended/operators/crd_must_be_stable.go

NO-JIRA: managed services: add hcp crd to unstable list

---

pkg/monitortests/etcd/etcdloganalyzer/monitortest.go

resolves https://issues.redhat.com/browse/CNTRLPLANE-195
cc @tkashem @vrutkovs @dgrisonnet   @benluddy

CNTRLPLANE-195: add a test that flakes if etcd cluster is leaderless more than 5 seconds

---

test/extended/apiserver/patch.go

Currently, we are in a process of fixing a bug that is caused by that node-controller and installer-controller attempt to update the node statuses of static operators simultaneously. Consequently, that race results in a hot loop that eventually causes the operator fall into a degraded state in a period of time. 
This PR https://github.com/openshift/api/pull/2208 (which is inherited from https://github.com/openshift/api/pull/2203) adds new validations to only allow;
* node status can only be created (or removed) with only node name (no other fields should be set) -- node controller
* node status can be updated with other fields in subsequent update requests -- installer controller
However, `JSONPatch` tests in this repository does indeed allow to create new node statuses with some dummy …

OCPBUGS-50587: Rely on unstructured for update status instead of type conversion

---

test/extended/arbiter_topology/OWNERS
test/extended/arbiter_topology/arbiter_topology.go
test/extended/include.go
test/extended/util/annotate/generated/zz_generated.annotations.go

adding initial happy path tests for the arbiter cluster deployment

OCPEDGE-1568: initial tests for 2Node 1Arbiter cluster

---

pkg/test/extensions/provider.go

Checking for the existence of the binary at the destination path post-extraction seems like the most efficient way to validate this and provide a user-friendly message when it occurs.
The new error message looks like:
```
error running options: encountered errors while extracting binaries: extracted binary at path "/root/.cache/openshift-tests/registry_ci_openshift_org_ocp_release_4_17_0-0_nightly-2025-03-09-083519_98d403caa91e/k8s-tests-ext.gz" does not exist. the src path "/usr/bin/k8s-tests-ext.gz" doesn't exist in image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:c79a94239285fe42301476bc31e4de33b9a12a34b398386ac0c865b335250407". note the version of origin needs to match the version of the cluster under testerror: encountered errors while extracting binaries: extracted …
```

TRT-2026: validate that the binary extraction was successful via existence check

---

test/extended/etcd/etcd_storage_path.go

CBOR serving and storage in apiserver should be TechPreview in 4.19, so we need to adjust our test to accept that type of storage in etcd.

CNTRLPLANE-5: Decode CBOR data in etcd test

---

test/extended/etcd/etcd_storage_path.go

The Unmarshal function uses strict decoding by default. This means that the target object must define all fields present in the CBOR data. Otherwise, it returns an unknown field error. This patch fixes that by using a intermediary map[string]any.
/assign @benluddy

CNTRLPLANE-5: Fix decoding of CBOR data in etcd test

---

pkg/test/ginkgo/cmd_runsuite.go

Temporarily check for the presence of the `[Skipped:xyz]` annotation in the test names, once this synthetic test begins to pass we can remove the annotation logic

TRT-1854: add synthetic test to check for presence of "Skipped" annotations in OTE tests

---

test/extended/router/gatewayapicontroller.go

Increase timeouts to reduce flakiness.  In particular, OLM is known to sometimes take a long time to install a subscription.
---
Based on these flakes, it eappears that the subscription takes on the order of 3 to 5 minutes to install in the flaky runs:
```text
% curl -s 'https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cluster-network-operator/2687/pull-ci-openshift-cluster-network-operator-master-e2e-gcp-ovn-techpreview/1912918779818414080/artifacts/e2e-gcp-ovn-techpreview/gather-extra/artifacts/subscriptions.json' 'https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cluster-network-operator/2678/pull-ci-openshift-cluster-network-operator-master-e2e-gcp-ovn-techpreview/1912568614955782144/ …
```

OCPBUGS-55132: gatewayapicontroller: Increase timeouts

---

test/extended/machine_config/machine_config_node.go

This closes [OCPBUGS-55175](https://issues.redhat.com/browse/OCPBUGS-55175).
- Add cleanup functionality to `ValidateMCNScopeHappyPathTest`.
- General doc comment updates.

OCPBUGS-55175: Add cleanup to MCN test

---

pkg/monitortests/kubeapiserver/auditloganalyzer/handle_operator_watch_count_tracking.go

Adds a check to verify we get *any* watch requests

TRT-2049: check for any watch requests

---

test/extended/router/gatewayapicontroller.go

The OSSM operator is not available as a community operator for OKD.
Since OKD does not include the RedHat catalog, this feature cannot be
used.

OKD-243: Skip GatewayAPIController tests for OKD

---

test/extended/etcd/etcd_storage_path.go

CNTRLPLANE-371: Update etcd test data for k8s 1.33 release

---

pkg/testsuites/standard_suites.go
test/extended/include.go
test/extended/node/nested_container.go
test/extended/testdata/bindata.go
test/extended/testdata/node/nested_container/Dockerfile
test/extended/testdata/node/nested_container/containers.conf
test/extended/testdata/node/nested_container/run_tests.sh
test/extended/testdata/node/nested_container/skip_tests.sh
test/extended/util/annotate/generated/zz_generated.annotations.go
zz_generated.manifests/test-reporting.yaml

https://issues.redhat.com/browse/OCPNODE-2315
This PR runs podman local system tests in a container. This test should help us verify what we can or can't do with a nested container.

OCPNODE-2315: Add nested container test

---

test/extended/machine_config/machine_config_node.go

In the MCN cleanup calls, we take a snapshot of the ready machines, and add 1 to it to get an expected final value.
In practice, there's a race condition where the worker pool is updating, and the actual number of ready nodes is less than we'd expect, since non-updated nodes count towards "not ready".
Thus this check sometimes times out, since by the time the pool is ready, the number of nodes exceed the original count +1, and we loop there until we time out.
Note that this only fixes some of the flakes in [TRT-2106](https://issues.redhat.com//browse/TRT-2106) and likely won't help with the overall timeout all that much.

TRT-2106: Fix race in MCN test cleanup

---

test/extended/networking/OWNERS

@knobunc @trozet PTAL
cc @jcaamano

NO-JIRA: update networking owners

---

test/extended/olm/olmv1.go
test/extended/testdata/bindata.go
test/extended/testdata/olmv1/install-pipeline-operator-base.yaml

These images are in both 4.18 and 4.19 catalogs

OCPBUGS-56047: OLMv1: Update test bundles [main/release-4.20]

---

test/extended/machine_config/helpers.go
test/extended/machine_config/pinnedimages.go

Status:
The PR is passing on manual tests for the Metal Disconnected Case!

OCPBUGS-55394: Handle Metal CI test cases for PIS

---

test/extended/olm/olmv1.go
test/extended/testdata/bindata.go
test/extended/testdata/olmv1/install-pipeline-operator-base.yaml

These images are in both 4.18 and 4.19 catalogs

OCPBUGS-56045: OLMv1: Update test bundles [release-4.19]

---

test/extended/machines/cluster.go
test/extended/machines/machines.go

[SPLAT-2231](https://issues.redhat.com/browse/SPLAT-2231)
- Changed machine api tests to consider nodes that are created without machinesets / machines for case where CI has hybrid environment

SPLAT-2231: Updated tests to work with hybrid environments

---

pkg/test/extensions/binary.go
pkg/testsuites/standard_suites.go

- Copy all the data over including cluster stability and test timeouts
- Add a missing mutex lock for modifying the binaries slice

TRT-2097: Fix a few things in suite selection

---

pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/monitortest.go

Reverts openshift/origin#29959

Revert "Revert "trt-2163: return error""

---

pkg/test/extensions/binary.go

CMO side setup: https://github.com/openshift/cluster-monitoring-operator/pull/2616

MON-4288: register CMO tests extension

---

test/e2e/upgrade/dns/dns.go

The old solution for this was to wait longer for the probe to gather additional DNS data. Neither that solution nor this one addresses the root cause of the issue - that SNO has more recovery disruption than other topologies.
This solution aims to allow us to refine the success threshold for SNO to be something that should always pass, while still detecting statistically significant regressions.

OCPBUGS-59159: Adjust DNS success rate to 98.0% for SNO upgrade test.

---

pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/monitortest.go

Reverts openshift/origin#29964

Revert "Revert "Revert "trt-2163: return error"""

---

pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
test/extended/imagepolicy/imagepolicy.go

update test to v1 version
add event matcher for SetDesiredConfig,AnnotationChange
skip test for metal ipv6 platform

OCPNODE-3454: OCPFeatureGate:SigstoreImageVerification update test on v1 (Cluster)ImagePolicy

---

pkg/test/ginkgo/cmd_runsuite.go

This is a weird one. If a non-retriable and retriable test fail in the same job, and the retry either succeeds or is skipped, the non-retriable failure is lost from the count causing origin to exit 0.  This is because we overwrite the entire list of failing tests instead of selectively removing the retried successes.
There was a hard assumption retries always happened, so this was an existing bug in the logic that never manifested because retries were always on in our suites.
The JUnit was correct; this only affected exit counts causing the job to "pass."

TRT-2224: Fix edge case where failures are not counted

---

test/extended/operators/operators.go

- RHEL8 worker support was removed in 4.19, therefore 4.18 clsuters have machine-config operator Upgradeable=False with reason RHELNodes
- Cgroup v1 support was removed in 4.19, therefore 4.18 clusters have machine-config operator upgradeable=false with reason ClusterOnCgroupV1
Applying these changes directly to release-4.18 branch as future branches do not have jobs that install these configurations and attempt to upgrade.

OCPBUGS-60066, OCPBUGS-60067: Tolerate various expected Upgradeable=False conditions

---

pkg/clioptions/clusterdiscovery/cluster.go

FeatureGates are different for OpenShift and upstream. This PR changes it so we have also FeatureGates from upstream enabled using endpoint /metrics from Prometheus.
This is a continuation of https://github.com/openshift/kubernetes/pull/2317

NO-JIRA: Get enabled featuregates from metrics endpoint

---

test/extended/util/image/README.md

NO-JIRA: Update image mirroring instructions to avoid using external binary

---

test/extended/networking/OWNERS

NO-JIRA: Update extended/networking OWNERS

---

test/extended/images/dryrun.go
test/extended/util/annotate/generated/zz_generated.annotations.go

Backport pr #29834 to release-4.18 manually.

[release-4.18] OCPBUGS-58461:Backport pr 29834 to release-4.18

---

pkg/test/ginkgo/cmd_runsuite.go

We attempted fixing in 4.20 but couldn't quite make it. All are believed
related to the kubelet metrics problem. Restoring retries for 4.20
release but the bugs will remain open.

OCPBUGS-57477: Allow three long term flaky k8s tests to retry

---

test/extended/networking/OWNERS

(cherry picked from commit 96aed9c78fe681029cb637448f085f15987ab6d7)

[release-4.19] NO-JIRA: Update extended/networking OWNERS

---

test/extended/networking/OWNERS

(cherry picked from commit https://github.com/openshift/origin/commit/4952343121fcc8b1e6a9604f4c2bfa0dc2b944cb)

[release-4.18] NO-JIRA: Update extended/networking OWNERS

---

test/extended/cli/mustgather.go
test/extended/util/annotate/generated/zz_generated.annotations.go

needs https://github.com/openshift/must-gather/pull/498

MON-4290: add test for must-gather gather_metrics

---

pkg/test/extensions/binary.go

It enables OTE for olmv0. Thanks

OCPQE-30698:enable OTE for olmv0
