openshift/origin

- pkg/test/ginkgo/cmd_runsuite.go
When we run an update test followed by a conformance test, the previous, static filenames lead to the update-run output being clobbered by the conformance-run output.  For example, [this job][1] has:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.8-e2e-gcp-upgrade/1379237920786878464/artifacts/e2e-gcp-upgrade/openshift-e2e-test/artifacts/e2e.log | grep -A2 'started.*Cluster sh
ould remain functional during upgrade'
started: (0/5/5) "[sig-arch][Feature:ClusterUpgrade] Cluster should remain functional during upgrade [Disruptive] [Serial]"
I0406 01:36:33.559185     246 test_context.go:459] Tolerating taints "node-role.kubernetes.io/master" when considering if nodes are ready
```
But all of the …
> pkg/test/ginkgo/cmd_runsuite: Fix e2e-* clobber for upgrade-conformance

- cmd/openshift-tests/upgrade.go
- test/e2e/upgrade/upgrade.go
For SNO upgrades most disruption tests would fail as there is no HA. This option would allow SNO upgrade test suite to skip those
> Bug 1948629: upgrades: add "none" / "minimal" test suites to skip disruption tests

- test/extended/router/h2spec.go
- test/extended/testdata/bindata.go
- test/extended/testdata/router/router-h2spec-routes.yaml
- test/extended/testdata/router/router-h2spec.yaml
- Requires https://github.com/openshift/cluster-ingress-operator/pull/590
- Builds on https://github.com/openshift/origin/pull/25897 and that should merge first
This PR re-enables the h2spec tests They were previously
disabled as the default ingresscontroller is not configured with http/2
support by default.
There are a number of changes here:
- The text fixture has been split up so that we can first apply the
pod/service, then apply the configured routes, then roll out a
dedicated ingresscontroller.
- There is a new fixture to rollout a new router shard with http/2
enabled.
- There is a new test fixture for the routes which are now parameterised
with an explicit domain and namespace selector to match on the router
shard type.
- The test now spins up a dedicated ingresscontroller.
- …
> Bug 1947806: test/extended/router: Re-enable h2spec tests

- test/extended/router/grpc-interop.go
- test/extended/router/h2spec.go
- test/extended/router/http2.go
Only run http/2, grpc-interop and h2spec tests on platforms where the
default router is exposed by a load balancer service that can also
support http/2.
> Bug 1949042: test/extended/router: skip h2 related tests on OpenStack

- test/e2e/upgrade/upgrade.go
Paused workers test requires watching upgrade to complete on final stage when worker pools is resumed and upgrade proceeds. This commit would record this warning in the log instead of throwing the error
See test results in https://github.com/openshift/release/pull/15939
> Bug 1948634: upgrade: allow upgrades without version change

- test/extended/testdata/bindata.go
- test/extended/testdata/cmd/test/cmd/basicresources.sh
- test/extended/testdata/cmd/test/cmd/testdata/oauthaccesstoken.yaml
Followup to https://github.com/openshift/origin/pull/26009
/assign @sttts
> Bug 1949050: Fix oauthaccesstoken test to use the new required name

- e2echart/e2e-chart-template.html
- pkg/monitor/api.go
- pkg/monitor/e2etest.go
- pkg/monitor/event.go
- pkg/monitor/intervalcreation/e2etest.go
- pkg/monitor/intervalcreation/node.go
- pkg/monitor/intervalcreation/node_test.go
- pkg/monitor/intervalcreation/operator.go
- pkg/monitor/intervalcreation/testdata/node.json
- pkg/monitor/monitor.go
- pkg/monitor/monitor_test.go
- pkg/monitor/monitorapi/identification.go
- pkg/monitor/monitorapi/types.go
- pkg/monitor/node.go
- pkg/monitor/noop.go
- pkg/monitor/sampler_test.go
- pkg/monitor/serialization/serialize.go
- pkg/monitor/types.go
- pkg/synthetictests/apiserver.go
- pkg/synthetictests/kubelet.go
- pkg/synthetictests/networking.go
- pkg/synthetictests/operators.go
- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/synthentic_tests.go
- test/extended/testdata/bindata.go
Expose both existing node not ready intervals as well as add two new sources of intervals:
* The events generated by MCD creating quasi-accurate intervals (events are lossy and MCD logic omits some events some times)
* The transition between two different sets of config at the node level
> test: Expose node changes as intervals

- cmd/openshift-tests/upgrade.go
Previously skip rules for None suite (no additional tests to run during upgrade) were added in https://github.com/openshift/origin/pull/26061. This commits ensures "none" suite is properly declared.
> Bug 1947809: upgrade: register none suite

- test/extended/router/grpc-interop.go
- test/extended/router/h2spec.go
- test/extended/router/http2.go
Primarily to stop lots of CI failures.
> Bug 1949978: test/extended/router: skip h2spec on proxy jobs

- test/extended/operators/resources.go
[1] and [2] have landed.
[1]: https://github.com/openshift/operator-framework-olm/pull/55
[2]: https://github.com/operator-framework/operator-lifecycle-manager/pull/2099
> Bug 1938492: test/extended/operators/resources: Marketplace Job sets requests

- test/extended/builds/proxy.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/test-build-proxy.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
Verify builds can mount the cluster's custom PKI trust bundle if one is
set on the cluster proxy configuration. When `mountProxyTrustedCA` is
set to `true`, builds should add the container's trust bundle as a
read-only mount. The custom PKI should be readable during the build
execution, but should not be present in the resulting image.
> Bug 1895053: Verify builds can mount proxy trustedCA

- cmd/openshift-tests/images.go
- pkg/monitor/cmd.go
- pkg/monitor/e2etest.go
- pkg/monitor/intervalcreation/e2etest.go
- pkg/monitor/intervalcreation/node.go
- pkg/monitor/intervalcreation/node_test.go
- pkg/monitor/intervalcreation/operator.go
- pkg/monitor/intervalcreation/operator_test.go
- pkg/monitor/monitor.go
- pkg/monitor/monitor_test.go
- pkg/monitor/monitorapi/types.go
- pkg/monitor/sampler_test.go
- pkg/monitor/serialization/serialize.go
- pkg/monitor/types.go
- pkg/synthetictests/apiserver.go
- pkg/synthetictests/event_junits.go
- pkg/synthetictests/kubelet.go
- pkg/synthetictests/networking.go
- pkg/synthetictests/operators.go
- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/synthentic_tests.go
- test/e2e/upgrade/service/service.go
- test/extended/util/disruption/controlplane/controlplane.go
- test/extended/util/disruption/disruption.go
- test/extended/util/disruption/frontends/frontends.go
- test/extended/util/disruption/imageregistry/imageregistry.go
Ensure all events going to the output are in fully specified and
clamped intervals.
* Remove the Event object and simply use EventInterval everywhere
* Rename EventInterval to Interval
* Move some helper methods to the monitorapi
> monitor: Clamp intervals to the test duration

- test/extended/operators/resources.go
openshift/cluster-autoscaler-operator#197 and openshift/cluster-autoscaler-operator#201 have landed.
> Bug 1938467: test/extended/operators/resources: Autoscaler sets requests

- test/extended/router/http2.go
AWS/UPI jobs are failing on http2, grpc-interop and h2spec tests
because deleting the ingresscontroller which was explicitly created
for the test takes more than 10 minutes[1] and that (plus the overall
test time) exceeds the amount of time the test is allowed to run for
before being marked as failing.
This commit skips tests on AWS until we fix BZ #1912413.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1912413.
> Bug 1949978: test/extended/router: skip http2, grpc-interop and h2spec on AWS

- test/extended/prometheus/prometheus.go
adding the alert in https://github.com/openshift/cluster-kube-apiserver-operator/pull/1073, high CPU during e2e runs isn't anything to be concerned over.  But in general it is a significant issue and masters should be provisioned larger
> bug 1951705: allow HighOverallControlPlaneCPU during e2e runs

- test/extended/util/image/image.go
- test/extended/util/image/zz_generated.txt
- test/extended/util/nfs.go
The Pr aims to request mirroring for  quay.io/redhat-developer/nfs-server:latest and update jenkins-e2e to use the mirrored image
> Bug 1952045: request mirroring for nfs-server image used in jenkins-e2e tests

- cmd/openshift-tests/e2e.go
- cmd/openshift-tests/openshift-tests.go
- cmd/openshift-tests/provider.go
- cmd/openshift-tests/provider_test.go
- go.mod
- test/extended/util/cloud/cloud.go
- test/extended/util/cluster/cluster.go
- vendor/modules.txt
Currently we are unconditionally skipping all single-stack-IPv6, dual-stack, and SCTP tests, regardless of cluster configuration. This is no good.
This PR extends the existing network-plugin-detection code to also detect network IP configuration and automatically skip IPv4-only, IPv6-only, and dual-stack-only tests as appropriate.
It also kind of adds support for detecting and skipping SCTP tests, except we can't really easily detect whether SCTP is available in the cluster at this point, so in reality it only works if you manually override the SCTP detection via `--provider`/`TEST_PROVIDER`. But we might be able to improve on that in the future. (And being able to unskip the SCTP tests at all is an improvement over the current situation.)
This will require a followup PR to …
> Bug 1945091: Refactor openshift-tests a bit, add more network-test-autodetecting support

- test/extended/prometheus/prometheus.go
our e2e tests run very high parallelism on relatively small masters, so we see high CPU usage.  This is distinct from the customer use-cases around overall size.
> Bug 1949589: allow high CPU alerts to be firing and pending

- test/extended/prometheus/prometheus.go
The bug is open and covers this for normal e2e and upgrades, so make
sure we exclude it until the team can fix the issue (degraded is
not currently causing other failures).
Ties https://bugzilla.redhat.com/show_bug.cgi?id=1939580 to the tests (I thought https://bugzilla.redhat.com/show_bug.cgi?id=1929922 was the issue but the former is more appropriate).
> test: Mark known alert failure for auth operator to bug

- test/e2e/upgrade/alert/alert.go
- test/extended/prometheus/prometheus.go
- test/extended/util/disruption/controlplane/controlplane.go
- test/extended/util/prometheus/helpers.go
The alert seems to fire on GCP in both upgrade and normal cases in 
https://bugzilla.redhat.com/show_bug.cgi?id=1953798, although the symptoms
described there should *also* happen on other clouds, so maybe we have a
general latency issue on GCP.  Disable only on GCP.
Also fix two issues:
test: Alert check should check all conditions
The alert was exiting early after only one matching condition, which means
it was overly aggressively matching the first label. We may have more bugs
after this.
Also add a new custom function to allow conditions to apply only in 
specific cases.
test: Disable upgrade disruption check on GCP
The constant is 'gce', not 'gcp', and the test is failing because of an as
yet undiagnosed issue.
> test: Allow KubeAPIErrorBudgetBurn on GCP platforms only

- test/extended/operators/resources.go
The packageserver deployment already sets resource requests for cpu and memory.
See packageserver manifests: https://github.com/openshift/operator-framework-olm/blob/3440fa2c16fc6a744e2e9bbb1352a0b4731cdd6f/manifests/0000_50_olm_15-packageserver.clusterserviceversion.yaml#L129-L132
Also confirmed on a 4.8 nightly cluster:
```console
$ oc get clusterversion
NAME      VERSION                             AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.8.0-0.nightly-2021-04-22-061234   True        False         21m     Cluster version is 4.8.0-0.nightly-2021-04-22-061234
$ oc -n openshift-operator-lifecycle-manager get pods packageserver-94cbcf856-4xc7j -o yaml
apiVersion: v1
kind: Pod
metadata:
name: packageserver-94cbcf856-4xc7j
namespace: openshift-operator-lifecycle-manager
...
spec: …
```
> Bug 1938466: test/extended/operators/resources: Packageserver already sets requests

- pkg/monitor/pod.go
- pkg/synthetictests/event_junits.go
- pkg/synthetictests/kubelet.go
- test/extended/operators/cluster.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Crashlooping, long pulls, and other container waiting / failing
states should really be in the event log. Update the pod monitor
to catch more transitions and conditions and to be more explicit
about what is happening in containers. Disable the current
crashloop test and replace with a synthetic.
Adds reporting on:
* Duration of all container starts and restarts
* Container exit code 0
* Pods deleted without a grace period
* Pods deleted before they are scheduled to a node
* Reasons containers are waiting and the time at which the event shows up
Still have to test this and add the invariant check
> monitor: Move "crashlooping pods" test to an invariant

- test/extended/router/idle.go
test/extended/router/idle.go:
Wait for the test workload to scale down to
zero replicas once idled before attempting to unidle
the test workload. This is to prevent a race condition
where the test route is GET'd before the test workload
has been idled successfully.
Use a 30 second (instead of 15 minute) HTTP timeout
when trying to unidle the test workload over it's HTTP
route. This way, the HTTP retry logic won't get hung up
on lengthy timeouts. Also, close the HTTP connection if we
receive a valid response.
---
/assign @frobware
> Bug 1953729: test/extended/router: Fix-up Unidling test

- pkg/monitor/pod.go
- pkg/synthetictests/kubelet.go
When terminal pods are evicted they are given a grace period 0
automatically by the apiserver and so it is not a true ForceDelete.
> test: Exclude terminal pods from ForceDeletion

- test/extended/images/oc_tag.go
Wait until the token shows up before attempting to read it:
```
Apr 23 12:26:15.876: INFO: Running 'oc ... serviceaccounts get-token testsa'
Apr 23 12:26:16.071: INFO: Error running /usr/bin/oc ... serviceaccounts get-token testsa:
StdOut>
error: could not find a service account token for service account "testsa"
StdErr>
error: could not find a service account token for se
```
Fixes a flake seen in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/666/pull-ci-openshift-kubernetes-master-e2e-gcp/1385547086795116544
> test: Wait for service account token

- pkg/synthetictests/networking.go
Instead of failing, report the bug that corresponds to temporary
failure to contact the API server (lack of resiliency).
Related to bug https://bugzilla.redhat.com/show_bug.cgi?id=1927264
> test: Report FailedCreatePodSandBox for multus -> API as known issue

- cmd/openshift-tests/e2e.go
Backports https://github.com/openshift/origin/pull/25986 to 4.7 to fix release-openshift-origin-installer-old-rhcos-e2e-aws-4.7
> Bug 1955669: flake testKubeletToAPIServerGracefulTermination

- test/e2e/upgrade/alert/alert.go
We have opened a high severity bug for this issue and the alert
can be tagged to allow merging.
> test: Associate ClusterOperatorDown for machine-config with bug

- test/extended/dns/dns.go
gcr.io/google_containers/dnsutils:e2e isn't a [known image](https://github.com/openshift/origin/blob/839dfa9a49e45ccf103e33cedcfff4834b2b3084/test/extended/util/image/README.md) so dualstack tests are failing the `[sig-arch] Only known images used by tests` test.
> Bug 1948606: test: replace dns test with known image

- e2echart/e2e-chart-template.html
- test/extended/testdata/bindata.go
For example, when [kube-apiserver opens with `Progressing=True`][1]:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.8-e2e-gcp-upgrade/1379189196182261760/artifacts/e2e-gcp-upgrade/openshift-e2e-test/artifacts/e2e-intervals.json | jq '.items[:2]'
[
{
"level": "Warning",
"locator": "clusteroperator/kube-apiserver",
"message": "condition/Progressing status/True reason/Unknown",
"from": null,
"to": "2021-04-05T22:22:24Z"
},
{
"level": "Info",
"locator": "e2e-test/\"[sig-arch][Early] Managed cluster should start all core operators [Suite:openshift/conformance/parallel]\"",
"message": "e2e test finished As \"Passed\"",
"from": "2021-04-05T22:20:18Z",
"to": "2021-04-05T22:20:19Z"
}
]
```
With the older …
> e2echart: Handle intervals that extend past the test range

- cmd/openshift-tests/cni.go
- cmd/openshift-tests/e2e.go
The certification team pointed out that it would make sense to backport this to 4.6, since we will be supporting it as the EUS release for a long time, and it would be simpler to have it use the same process as 4.7+.
/assign @knobunc
> Bug 1948233: Add openshift/network/third-party suite, for CNI plugin conformance

- test/extended/images/oc_tag.go
If the cluster have publicly exposed registry then following happen
when we do a build and tag to `localimage`.
```
$ oc registry info
default-route-openshift-image-registry.apps-crc.testing
$ cat Dockerfile  | oc -n demo new-build -D - --to localimage:latest
--> Found container image 388056c (3 weeks old) from Docker Hub for "busybox:latest"
[...]
--> Success
$ oc get is localimage -oyaml
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
annotations:
openshift.io/generated-by: OpenShiftNewBuild
name: localimage
namespace: demo
spec:
lookupPolicy:
local: false
status:
dockerImageRepository: image-registry.openshift-image-registry.svc:5000/demo/localimage
publicDockerImageRepository: default-route-openshift-image-registry.apps-crc.testing/demo/localimage
tags:
- items:
- …
```
> Bug 1957222: [test/oc_tag] Add internal option for registry info

- e2echart/e2e-chart-template.html
- pkg/monitor/event.go
- pkg/monitor/intervalcreation/node.go
- pkg/monitor/intervalcreation/node_test.go
- pkg/monitor/intervalcreation/testdata/node.json
- pkg/monitor/monitorapi/identification_node.go
- pkg/monitor/monitorapi/identification_node_test.go
- pkg/monitor/node.go
- pkg/monitor/node_test.go
- test/extended/testdata/bindata.go
This PR updates the `node-state` section in the e2echart with node roles, by
embedding the information (in the form of `roles/$roles`) in the `Message` field. 
This change preserves the dependency some tests have on the event
messages, where certain prefix and suffix are expected, as seen in
[pkg/synthetictests/kubelet.go](https://github.com/openshift/origin/blob/36b43d1c8df3a74e1e1fca5e8a9c1c6824d67fe6/pkg/synthetictests/kubelet.go#L132-L134) and [pkg/monitor/intervalcreation/node.go](https://github.com/openshift/origin/blob/36b43d1c8df3a74e1e1fca5e8a9c1c6824d67fe6/pkg/monitor/intervalcreation/node.go#L44-L46)  
This is what the updated section looks like:
Signed-off-by: Ivan Sim <isim@redhat.com>
> Bug 1957041: Update e2echart to include node roles info

- test/extended/router/idle.go
The idle feature is only supported for OVNKubernetes and OpenShiftSDN
so we skip the idle test if the network type is something other than
those two.
> Bug 1957146: test/extended/router/idle: Only run on OVNKubernetes or OpenShiftSDN

- test/extended/cli/observe.go
This PR adds IPv6 validation for `.spec.clusterIP` to be able to run observe tests in IPv6 environments . Because in IPv6 environments, clusterIP returns in format of `fd02::982f` instead of `172.30.0.1` and test `[sig-cli] oc observe works as expected [Suite:openshift/conformance/parallel]` is failing. 
Moreover, this PR adds `Sync ended` control for `oc observe daemonsets --once`.
> Bug 1955089: Add IPv6 check to support observe parallel tests

- cmd/openshift-tests/provider.go
regression from #25818: Trying to override --provider while not actually connected to a cluster (eg, to look at the output of --dry-run) would fail, rather than just falling back to not trying to autodetect anything.
> Bug 1957512: openshift-tests: fix a --provider --dry-run edge case

- test/extended/cli/mustgather.go
Fixes comparison with `.lock` and `lock.log`.
> Bug 1958094: must-gather: check file name instead of whole path

- test/e2e/upgrade/upgrade.go
Sometimes during CI upgrade tests connection errors occur delaying initial CVO pod's shutdown and subsequent CVO pod's startup. This then delays CVO's version sync at times resulting in a failure to ACK the upgrade within the 2 minute constraint of the test.
> Bug 1957927: test/e2e/upgrade/upgrade.go: Bump upgrade ACK timeout to 4 minutes

- test/extended/builds/run_fs_verification.go
Skipping verification tests for the /run directory in builds. A change was
recently made at the node/cri-o layer which added additional content to
the /run directory.
This change should be reverted once the contents added to /run have been
vetted.
> Bug 1959564: builds: skip /run verification tests

- test/extended/cli/admin.go
- test/extended/project/project.go
- test/extended/util/client.go
- test/extended/util/framework.go
Also fix a case where we waited for dockercfg but not the token (which we need).
This fixes the failure to pull openshift/tools in a number of tests (we raced with the secret controller)
> Wait longer in tests where namespace cleanup is slow

- images/tests/Dockerfile.rhel
Multiple tests in the e2e Conformance suite require the Cinder client to be installed when run
against OpenStack.
In the step-registry CI structure, the "test" ref is shared across
platforms; it is therefore not desirable to run the OpenStack tests
using a separate image.
This change adds the Cinder client to the container image used to run
the tests in the CI.
Implements [OSASINFRA-2308](https://issues.redhat.com/browse/OSASINFRA-2308)
cf. "[sig-storage] In-tree Volumes [Driver: cinder] [Testpattern:
Inline-volume (default fs)] volumes should store data
[Suite:openshift/conformance/parallel] [Suite:k8s]"
> Bug 1957131: test: Add the Cinder client to the test image

- test/extended/testdata/bindata.go
- test/extended/testdata/router/ingress.yaml
test/extended/testdata/router/ingress.yaml:
Change `apiVersion` from `networking.k8s.io/v1beta1` to
`networking.k8s.io/v1`.
To ensure compatibility with the new v1 API, use a `pathType`
of `Prefix` for each of the test Ingress resources (which should be
compatible with existing test logic).
Also, use the correct service backend syntax, which requires a trivial
yaml layout change.
test/extended/testdata/bindata.go:
Regenerate.
This commit is in support of Bug 1947800.
---
Edit 5/11/21:
This PR will affect any backports that touch `test/extended/testdata/router/ingress.yaml` going forward.
> Bug 1947800: Router: Switch from networking v1beta1 to v1

- test/extended/builds/run_fs_verification.go
@adambkaplan @nalind FYI
Assuming we can get this to work like we want it I'll associate the bz, fully remove the skip, etc.
> Bug 1959564: move verify run test from tools to cli image to avoid additional /run content

- test/extended/dns/dns.go
test/extended/dns/dns.go:
Use the `discoveryv1` instead of `discoveryv1beta1`
API since `discoveryv1beta1` is officially deprecated in
Kubernetes 1.21.
Note that the test modified in this commit
only runs on dual-stack enabled clusters.
This commit is in support of Bug 1961201.
> Bug 1961201: DNS: Use endpointslice v1 for DNS dual-stack test

- images/tests/Dockerfile.rhel
The openstack repository does not yet exist for s390x, where
python3-cinderclient should be coming from. Safelisting the
existing arches.
> Bug 1961582: Do not install python3-cinderclient on s390x

- test/extended/pods/priorityclasses.go
Instead of just telling folks which pods are broken, tell folks what the current config is and what the expected config is, so they don't have to dig around to figure out how to fix their component.
Following up on d6c4a516ec (#25931), CC @ravisantoshgudimetla.
> Bug 1957295: test/extended/pods/priorityclasses: Improve error actionability

- test/extended/util/disruption/controlplane/controlplane.go
Now that we increased how long we wait for termination and removal
from AWS load balancing (which is a much longer period than their
documentation) we should lock in the fix by failing if we see
control plane disruption.
> test: Tolerate no AWS disruption during control plane upgrade

- pkg/synthetictests/networking.go
https://bugzilla.redhat.com/show_bug.cgi?id=1927264 was previously suppressed from failing in https://github.com/openshift/origin/pull/26115 but looks like this test can fail in multiple modes:
https://bugzilla.redhat.com/show_bug.cgi?id=1927264#c13
> test: Report FailedCreatePodSandBox for multus -> API as known issue (v2)

- test/extended/builds/run_fs_verification.go
manual pick required since bot encountered merge conflict with 4.7 PR
> Bug 1963909: move verify run test from tools to cli image; narrow scope to /run/secrets

- test/extended/operators/operators.go
Because openshift/service-ca-operator#154 has landed.  Also drop the exception for openshift-controller-manager, because openshift/cluster-openshift-controller-manager-operator#210 has landed.
> Bug 1948012: test/extended/operators: Drop service-ca Upgradeable exception

- test/e2e/upgrade/service/service.go
PR #25406 changed ExternalTrafficPolicy from Cluster to Local to try to optimize network performance.  Unfortunately, Local will drop traffic instead of rerouting it.  For this test we need to use Cluster.
> Bug 1929396: Revert part of PR #25406 - use ExternalTrafficPolicyCluster

- test/extended/operators/operators.go
This reverts commit b4a00cbeacf6317ae6dc91fa14a012963667f08e, #26183.
Until the operator fixes make it back to 4.7, dropping the exceptions in 4.8's origin breaks 4.7->4.8 testing.  We'll try dropping the exceptions again after the operator changes make it back to 4.7, or master opens for 4.9.
> Bug 1948012: Revert "test/extended/operators: Drop service-ca Upgradeable exception"

- images/tests/Dockerfile.rhel
Multiple tests require the Cinder client to be installed when run
against OpenStack.
In the step-registry CI structure, the "test" ref is shared across
platforms; it is therefore not desirable to run the OpenStack tests
using a separate image.
This change adds the Cinder client to the container image used to run
the tests in the CI.
Implements [OSASINFRA-2308](https://issues.redhat.com/browse/OSASINFRA-2308)
cf. "[sig-storage] In-tree Volumes [Driver: cinder] [Testpattern:
Inline-volume (default fs)] volumes should store data
[Suite:openshift/conformance/parallel] [Suite:k8s]"
This is a cherry-pick of 559db12abbe938db5d726aa196901e7d5ef47c12
(https://github.com/openshift/origin/pull/26131) modified with the fix
for the architectures where the openstack repository is not available …
> Bug 1961367: Add Cinder client to the test image

- test/extended/builds/s2i_root.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/build-postcommit/sti.yaml
- test/extended/testdata/builds/build-timing/test-s2i-build.json
- test/extended/testdata/builds/statusfail-failedassemble.yaml
- test/extended/testdata/builds/statusfail-postcommithook.yaml
- test/extended/testdata/builds/statusfail-pushtoregistry.yaml
- test/extended/testdata/builds/test-build-cluster-config.yaml
- test/extended/testdata/builds/test-build-proxy.yaml
- test/extended/testdata/builds/test-build-revision.json
- test/extended/testdata/builds/test-nosrc-build.json
- test/extended/testdata/builds/test-s2i-build-quota.json
- test/extended/testdata/builds/test-s2i-build.json
- test/extended/testdata/builds/test-s2i-no-outputname.json
- test/extended/testdata/builds/valuefrom/failed-sti-build-value-from-config.yaml
- test/extended/testdata/builds/valuefrom/successful-sti-build-value-from-config.yaml
- test/extended/testdata/templates/templateinstance_readiness.yaml
- test/extended/util/image/image.go
- test/extended/util/image/zz_generated.txt
Replaced `registry.svc.ci.openshift.org/ocp/4.7:test-build-roots2i` in Origin build tests with `quay.io/multi-arch/test-build-roots2i:ubi8`.
Latest image is multiarch - has multiple references of different architectures in its manifest.
Since `quay.io/multi-arch/test-build-roots2i:ubi8` is a new image, it is not present in the `quay.io/openshift/community-e2e-images` - needs to be mirrored there as described in the `util/image` [README.md](https://github.com/openshift/origin/blob/master/test/extended/util/image/README.md).
> BUILD-250 pull in multi-arch friendly version of roots2i and simples2i, add simples2i to mirroring test infra

- test/extended/quota/clusterquota.go
This skip is intended to allow https://github.com/openshift/kubernetes/pull/714 to merge without breaking CI for everyone. A follow-on PR will re-enable the test once it has been updated to account for the new service ca configmap being created in every namespace.
/cc @sttts @deads2k
> Bug 1946479: Skip cluster quota test while bound token projected volume is being re-enabled

- test/extended/prometheus/prometheus.go
This PR blocks https://github.com/openshift/cluster-monitoring-operator/pull/1183
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>
> Bug 1964334: use bearer token to access prometheus /metrics endpoint

- images/tests/Dockerfile.rhel
A regression was introduced in the Dockerfile, with a typo in
the condition:
https://github.com/openshift/origin/pull/26170
This patch fixes it.
> Bug 1961582: Dockerfile.rhel: fix a bash typo

- cmd/openshift-tests/e2e.go
- test/extended/dr/backup_restore.go
- test/extended/dr/force_redeploy.go
- test/extended/dr/quorum_restore.go
The quorum restore test was previously deleting machines and then attempting to take a backup such that the backup script would race with machine removal. The backup script only supports taking a backup of a cluster that still has quorum. Taking the backup before machine deletion removes the race condition.
This PR also updates the test to follow the documented procedure after executing the restore script. It reuses steps defined for the backup-restore test added in #25723.
/cc @hexfusion @smarterclayton
> Ensure quorum restore test follows the documented procedure

- go.mod
- test/extended/util/disruption/controlplane/controlplane.go
- vendor/modules.txt
If we are upgrading from versions before 4.8, some necessary fixes
are not present and we need to avoid failing the test (because we
deliberately decided not to tighten these restrictions). Only
require 0 disruption going forward. This applies to all platforms.
> test: Tolerate control plane unavailability before 4.8

- test/extended/operators/olm.go
A new catalog-operator alert is being introduced that fires when the
API server produces warnings during operator installation.
The latest amq-streams catalog entry hasn't completed its migration
away from v1beta1 CRDs, which results in deprecation warnings that in
turn cause the catalog-operator alert to fire.
> Bug 1969561: Use cluster-logging for operator installation smoke test.

- test/extended/etcd/leader_changes.go
[Because][1]:
> Observed 1.0106666666666666 leader changes in 25m16s: Leader changes are a result of stopping the etcd leader process or from latency (disk or network), review etcd performance metrics
lead me wondering if maybe 1 was acceptable, and there was some rounding error in the PromQL that lead to the test failing.  With the new string, I would have realized that "are not excessive" currently means "never happen when we don't expect them" ;).
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1970160#c0
> test/extended/etcd/leader_changes: Explicit 'expected 0'

- test/extended/router/metrics.go
- test/extended/testdata/bindata.go
- test/extended/testdata/router/router-metrics.yaml
Tests that hardcode spec.host can fail to be admitted while other instances of the same test are running (in parallel / stress jobs).
We don't need a hardcoded host anyway.
Also, max_sessions tracking is unreliable in the presence of too many restarts, so simply verify after a restart it's zero for our route (as it should be).
> test: Don't reuse route.spec.host in tests run in parallel

- test/e2e/upgrade/alert/alert.go
We're getting:
alert AggregatedAPIDown fired for 210 seconds with labels: {name="v1beta1.metrics.k8s.io", namespace="default", severity="warning"}
and such pretty consistently in those jobs.  Tracked in [rhbz#1970624][1].  Until that gets fixed, ignore the alert, so we are more likely to notice other breakage.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1970624
> test/e2e/upgrade/alert: Allow AggregatedAPIDown to unblock 4.7->4.8 CI

- test/e2e/upgrade/upgrade.go
Due to AWS LB issue apiserver rollout takes twice as much. This bumps upgrade duration on AWS to 90 mins.
Upgrade tests:
* [test upgrade 4.7 https://github.com/openshift/origin/pull/26219 aws](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/1403239794875568128)
```
[sig-cluster-lifecycle] cluster upgrade should complete in 60m (90m on AWS) | 1h7m50s
```
* [test upgrade 4.8.0-fc.8 https://github.com/openshift/origin/pull/26219 aws](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/1403239821593284608)
```
[sig-cluster-lifecycle] cluster upgrade should complete in 60m (90m on AWS)&nbsp;expand_less | 1h32m30s
-- | --
upgrade to …
```
> Bug 1970975: upgrade test: expect upgrades to take longer on AWS

- test/e2e/upgrade/upgrade.go
The failure message for "[sig-cluster-lifecycle] cluster upgrade should be fast" is ambiguous:
upgrade to registry.build01.ci.openshift.org/ci-op-h21l7wld/release@sha256:2148b1c121946ac4f186bb22b166247d3df0ad9cf3966f05dc2a6ea27bc53927 took too long: 86.33481681223333
What does 86.33481681223333 represent? Is it seconds, minutes, hours? What does "too long" mean? Without looking at the test code, one cannot tell. With that info added to the failure string, it's easier to understand:
upgrade to registry.build01.ci.openshift.org/ci-op-h21l7wld/release@sha256:2148b1c121946ac4f186bb22b166247d3df0ad9cf3966f05dc2a6ea27bc53927 took too long: 86.3 minutes, expected 75 minutes or less
I'm happy to change verbiage as needed.
> Bug 1970969: clarify failure message

- test/extended/quota/clusterquota.go
Now that bound token projected volume support has been enabled with openshift/kubernetes#714, the cluster quota test can be re-enabled with awareness of the new service ca configmaps.
> Re-enable cluster quota test

- pkg/synthetictests/networking.go
It's slamming us in 4.8 and later update CI: [rhbz#1972490](https://bugzilla.redhat.com/show_bug.cgi?id=1972490).
> pkg/synthetictests/networking: Grant temporary exception for "error getting pod: Unauthorized"

- test/e2e/upgrade/alert/alert.go
- test/extended/prometheus/prometheus.go
Since `pendingAlertQuery` landed in 59ef04b754 (#25904), it has been measuring pending alerts when the query was run, and the value has always been 1. That would get rendered as:
alert ... pending for 1 seconds with labels...
regardless of how long the alert had been pending before the query was run.  This commit replaces the query with a new one whose value is actually the number of seconds that a currently-pending alert has been pending.  The new query:
* Uses:
ALERTS{...} unless ALERTS offset 1s
to trigger on edges where the alert began pending.
* Uses `last_over_time` to find the most recent edge trigger.
* Uses:
time() + 1 - last_over_time(time() * ...)
to figure out how long ago that most-recent trigger was.  The `+1` sets the floor at 1, for cases where one second ago we were not …
> test: Use last_over_time in pendingAlertQuery

- test/extended/prometheus/OWNERS
This change updates the list of reviewers and approvers to be consistent
with the current team structure.
Signed-off-by: Simon Pasquier <spasquie@redhat.com>
> test/extended/prometheus/OWNERS: refresh members

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
e2e-metal-ipi-ovn-dualstack jobs are permanently failing.
This PR adds 3 tests that are failing in dualstack into the `[Skipped:Network/OVNKubernetes]` list. As stated in https://bugzilla.redhat.com/show_bug.cgi?id=1972684#c5, these tests are not supported by OVN-Kubernetes.
> Bug 1972684: Add failing tests in OVN-K into skipped list

- test/e2e/upgrade/upgrade.go
Some upgrades finish slightly above 90m limit - https://search.ci.openshift.org/?search=sig-cluster-lifecycle.*cluster+upgrade+should+complete+in+&maxAge=96h0m0s&context=3&type=junit&name=aws&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
Longest so far seems to be [aws-ovn-upgrade](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/19195/rehearse-19195-periodic-ci-openshift-release-master-ci-4.9-upgrade-from-stable-4.8-e2e-aws-ovn-upgrade/1403820023339814912) - 104.34.
[test upgrade 4.8.0-rc.0 https://github.com/openshift/origin/pull/26230 aws](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/1405784553200553984)
This would bump AWS timeout to 105m until this is thoroughly investigated
> upgrade: extend upgrade duration to 105mins on AWS

- test/extended/etcd/leader_changes.go
The test would panic if Prometheus returns no result.
Spotted in https://github.com/openshift/cluster-monitoring-operator/pull/1044
Signed-off-by: Simon Pasquier <spasquie@redhat.com>
> test/extended/etcd: fix leader change test

- test/extended/clusterup.sh
Normally 'oc cluster up' looks in $HOME/.docker/config and wires that up
for imagestream imports.  That isn't happening in the clusterup.sh test
since it does clever things with $HOME.
> clusterup.sh lacks creds in CI

- examples/jenkins/pipeline/bluegreen-pipeline.yaml
- examples/jenkins/pipeline/samplepipeline.yaml
- test/extended/testdata/bindata.go
Replacement to https://github.com/openshift/origin/pull/26268
/assign @yselkowitz 
@akram @waveywaves @jkhelil FYI ... the reader's digest of the #26268 and https://github.com/openshift/origin/pull/26072 is that in the attempt to move a bunch of e2e's off of mongodb, as well as onto ubi8, e2e-aws-jenkins slipped through the cracks
I've updated openshift/release to make sure e2e-aws-jenkins runs when the files in question are touched (we'll see if that works here in a sec)
I was able to run the jenkins suite locally with these changes
> move jenkins e2e's that were using mongodb, then mariadb, to postgresql, to get them to pass again

- test/extended/apiserver/api_requests.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Measure the amount of watch requests per operator per bucket and upper bound it in case
an operator introduces an error leading to opening too many watch requests in short time.
https://issues.redhat.com/browse/WRKLDS-291
> [sig-arch][Late] operators should not create watch channels very often [Suite:openshift/conformance/parallel]

- test/extended/builds/pipeline_origin_bld_rhelimagesonly.go
This test relies on pulling yaml from github rather than from bindata,
which makes it difficult to pre-commit testing of changes which affect
it.  @akram and @gabemontero will move this to the jenkins client plugin
E2E, but in the meantime, we comment it out.
https://github.com/openshift/origin/pull/26072#issuecomment-862307401
/cc @gabemontero
> builds: comment out RHEL-only sample-pipeline template test

- test/extended/operators/olm.go
Update the test/extended/operators/olm.go and ensure that all containers
in the OLM deployment resources contain the IfNotPresent image pull
policy.
Previously, this test would make the assumption that all the OLM-related
deployments contain a single container, which won't always be the case
in the future. This updates that test to split the output from the oc
command into array elements, checking each element to ensure it matches
the correct image pull policy.
> test/extended: Ensure all containers in the OLM deployment resources contain the IfNotPresent image pull policy

- test/extended/quota/clusterquota.go
This skip is intended to allow openshift/kubernetes#834 to merge without breaking CI for everyone. A follow-on PR will re-enable the test once it has been updated to account for the new service ca configmap being created in every namespace.
/cc @s-urbaniak @stlaz @sttts @soltysh
> Bug 1977383: [release-4.7] Skip cluster quota test to enable service ca publisher to merge to o/k

- pkg/network/node/networkpolicy.go
- pkg/network/node/networkpolicy_test.go
Backport network policy performance changes from 4.x, adapting the code to 3.11
https://github.com/openshift/origin/pull/26247#discussion_r654645326
> In 4.x we dropped np.pods since the informer already has its own cache (openshift/sdn@4bac7c7 + openshift/sdn@eaf68af) but that also required rewriting the unit tests to use a fake kubeclient (openshift/sdn@2e60296) and I'm not sure how much divergence there's been since 3.11 so that might be too much to backport...
> Bug 1963160: Backport Bug 1896958: NetworkPolicy performance (pod caching) #226

- test/extended/builds/service.go
- test/extended/util/image/image.go
Redis has tighter constraints on client HTTP calls to prevent malicious
attacks. Only official redis clients are guaranteed to receive reliable
HTTP responses. The build test for in-cluster service connections does
not use a redis client, resulting in a test HTTP curl request receiving an
empty repsonse.
This updates the in-cluster service test to use a "hello world" nodejs
application and service. The use of the upstream Redis image is also
removed.
> Bug 1977454: Use nodejs to test service connection

- test/extended/networking/acl_audit_log.go
- test/extended/networking/multicast.go
- test/extended/networking/util.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This works adds a networking extended test for the new [network
policy audit logging feature ](https://issues.redhat.com/browse/SDN-1364)
The name of the new test is:
`"[sig-network] acl-logging should activate acl-logging [Suite:openshift/conformance/parallel]"`
It first activates the audit logging by applying new annotations to the `acl-logging` ns 
```
ns.Annotations["k8s.ovn.org/acl-logging"] = `{ "deny": "alert", "allow": "alert" }`
```
Next it make's three pods, two(pod[0] and pod[1]) in the ns `acl-logging` and one(pod[3]) in the ns `acl-logging-off` 
Then it makes two networkPolicies in the `acl-logging` ns -> 
1. allow-same-namespace
2. default-deny-all 
Finally it sends packets from pods 1 and 2 to pod 0..... The packet from 
pod[1] will be allowed by the allow-same-namespace …
> Add new E2E test for [SDN-1364] ACL audit logging

- test/e2e/upgrade/upgrade.go
- test/extended/prometheus/upgrade.go
- test/extended/util/prometheus/helpers.go
Upgrading from 4.3.18 to 4.4.3 caused Prometheus to claim a new PVC,
thereby losing all the metrics prior to the upgrade.
This change adds an upgrade test verifying that prometheus metrics
from before the upgrade are still available after the upgrade.
> test/extended/prometheus: Add an upgrade test for Prometheus

- test/extended/builds/pipeline_origin_bld.go
a pick of just @yselkowitz 's https://github.com/openshift/origin/pull/26072/commits/7e93e512f3ad715def2424f71a5b486e2c95aa69 to unwedge jenkins e2e's in 4.8
I will be porting this test to the jenkins client plugin e2e's
/assign @yselkowitz 
@akram @waveywaves @jkhelil @adambkaplan FYI
> Bug 1976376: builds: comment out multi-namespace template test

- test/extended/router/metrics.go
- Removed e2e log message since https://github.com/openshift/router/pull/132 merged.
- Updated the expected condition to be != 0.
> Updates router metrics e2e

- pkg/synthetictests/networking.go
"pods should successfully create sandboxes" test should mark pod events as flakes if network is being updated. 
During network update CNI binaries may be in the middle of update. This may cause sandbox errors like:
* `error adding container to network "ovn-kubernetes": failed to send CNI request: Post "http://dummy/": EOF`
* `Multus: [openshift-dns/dns-default-nbkz2]: have you checked that your default network is ready? still waiting for readinessindicatorfile @ /var/run/multus/cni/net.d/10-ovn-kubernetes.conf. pollimmediate error: timed out waiting for the condition`
* `error adding container to network "openshift-sdn": failed to find plugin "openshift-sdn" in path [/opt/multus/bin /var/lib/cni/bin /usr/libexec/cni]`
["never deleted" search in 4.7 -> 4.8 upgrades for last 7 …
> Bug 1970315: testPodSandboxCreation: skip sandbox errors for pods which were not deleted during network update

- test/extended/util/disruption/controlplane/controlplane.go
- test/extended/util/disruption/frontends/frontends.go
- test/extended/util/disruption/imageregistry/imageregistry.go
- test/extended/util/framework.go
Enforce that frontends must remain available now that 4.8 is fixed.
Share code across the three test types and leave a comment about the
known image registry disruption.
> Bug 1972829: Verify upgrades don't disrupt frontends

- test/e2e/upgrade/alert/alert.go
To avoid locking on hard-anti-affinity vs. volume-affinity, Prometheus returned to soft-anti-affinity and dropped its PDBs [rhbz#1967614][1].  [rbhz#1949262][2] has been re-opened to track making Prometheus highly-available again, but until that is addressed, we'll have occasional Prometheus outages [like][3]:
```
disruption_tests: [sig-arch] Check if alerts are firing during or after upgrade success    1h9m50s
Jun  9 11:57:23.048: Unexpected alerts fired or pending during the upgrade:
Watchdog alert had missing intervals during the run, which may be a sign of a Prometheus outage in violation of the prometheus query SLO of 100% uptime during upgrade
```
In that job, Watchdog was down for around 30s, and had two changes (going down and coming back up).  It's possible that both Prometheus …
> test/e2e/upgrade/alert: Allow some Watchdog changes

- vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager.go
- vendor/k8s.io/kubernetes/pkg/kubelet/status/status_manager_test.go
- vendor/k8s.io/kubernetes/pkg/util/pod/pod.go
- vendor/k8s.io/kubernetes/pkg/util/pod/pod_test.go
Backports two upstream fixes into 3.11 for pod statuses: [86320](https://github.com/kubernetes/kubernetes/pull/86320) and [88591](https://github.com/kubernetes/kubernetes/pull/88591).
> [release-3.11] Bug 1930100: Pod status patches

- examples/image-streams/image-streams-centos7.json
- examples/quickstarts/README.md
- examples/quickstarts/dotnet-pgsql-persistent.json
- examples/quickstarts/dotnet.json
- test/extended/testdata/bindata.go
Remove dotnet examples from quickstarts, as they were removed upstream.
In this PR:
- Remove dotnet from quickstarts/examples README.md
- Run ./hack/update-external-examples.sh
- Run make update
Currently, the dotnet files aren't valid JSON and causing tests to fail
in this repo.
> Update quickstart examples and re-run make update

- test/extended/machines/cluster.go
- test/extended/machines/machines.go
- test/extended/machines/scale.go
- test/extended/machines/workers.go
We have a number of tests that use the Machine API, but also topologies of deploying OpenShift that do not install the Machine API (eg IBM). To be able to support this going forward, ensure that all tests check for the presence of Machine API before starting the test. If the Machine API namespace doesn't exist, skip the test.
This should mean that all tests that rely on the Machine API check before starting that the Machine API is installed.
@csrwng I've removed the IBM checks that you added as I was trying to minimize the special cases, do you think the current approach will still work for IBM or do they have the Machine API namespace created even though they have no machines on the cluster?
> Bug 1928856: Skip tests that rely on Machine API when Machine API is not installed

- hack/lib/build/environment.sh
- hack/test-cmd.sh
- test/cmd/newapp.sh
- test/cmd/printer.sh
- test/cmd/set-image.sh
- test/cmd/timeout.sh
- test/cmd/triggers.sh
Fixes several `test/cmd` entries to match the current state of imagestreams.
Includes #26292 to have Dockerhub pullsecret placed, so that import would not hit rate limits
> Bug 1980338: test/cmd/newapp: update app name to match existing tag

- test/extended/etcd/etcd_storage_path.go
a workaround had to be added to merge https://github.com/openshift/cluster-kube-apiserver-operator/pull/1162 - this is removing the workaround so that v1beta1 of apiextensions.k8s.io and admissionregistration.k8s.io are always discarded in etcd_storage_path test
> always discard v1beta1 in etcd test of apiextensions and  admissionregistration

- cmd/openshift-tests/e2e.go
Skip the new network policy tests that were introduced in K8s 1.21 due
to the flakiness they introduced in Openshift's Stress tests.
https://bugzilla.redhat.com/show_bug.cgi?id=1980141
Signed-off-by: astoycos <astoycos@redhat.com>
> Bug 1980141: Skip new `Netpol` tests for Network Stress Suite

- test/e2e/upgrade/alert/alert.go
- test/extended/prometheus/prometheus.go
Allow the HighlyAvailableWorkloadIncorrectlySpread alert to fire until
we can safely enable hard anti-affinity on hostname to workload with
persistent storage, without breaking customers. The timeline for that
should be 4.9. Note that for upgrade tests, we will need to wait one
more release to remove the alert from the allow list since we will
need both the source version and the target to have hard anti-affinity
enabled to prevent the alert from firing.
I linked the alert scoped to prometheus-k8s to [bug 1929262](https://bugzilla.redhat.com/show_bug.cgi?id=1949262) and the 
one scoped to alertmanager-main to [bug 1955489](https://bugzilla.redhat.com/show_bug.cgi?id=1955489). These bugzillas 
track the effort of adding hard anti-affinity constraints to these
components.
> Allow HighlyAvailableWorkloadIncorrectlySpread alert to fire

- test/extended/builds/pipeline_jenkins_e2e.go
See https://github.com/openshift/jenkins/pull/1297 for the tl;dr
But basically, the commented out test alway fails with
```
Cloning the remote Git repository
Cloning repository /tmp/test-build-app-pipeline544874952/test-build-app-pipeline.git
> git init /var/lib/jenkins/jobs/e2e-test-jenkins-pipeline-9bmz9/jobs/e2e-test-jenkins-pipeline-9bmz9-test-build-app-pipeline/workspace@script # timeout=10
Fetching upstream changes from /tmp/test-build-app-pipeline544874952/test-build-app-pipeline.git
> git --version # timeout=10
> git --version # 'git version 2.27.0'
> git fetch --tags --force --progress -- /tmp/test-build-app-pipeline544874952/test-build-app-pipeline.git +refs/heads/*:refs/remotes/origin/* # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: …
```
> comment out broken local git, env var,  jenkins pipeline test (moving to remote repo and openshift/jenkins)

- vendor/k8s.io/kubernetes/pkg/kubelet/metrics/metrics.go
- vendor/k8s.io/kubernetes/pkg/kubelet/pleg/generic.go
- vendor/k8s.io/kubernetes/pkg/kubelet/pleg/generic_test.go
Upsteam ref: https://github.com/kubernetes/kubernetes/pull/72709
> [release-3.11] Bug 1981404: UPSTREAM: 72709: when pleg channel is full, discard events and record how

- test/e2e/upgrade/upgrade.go
The OVN upgrade jobs almost always take longer than 75m
so this fails. There is more context to this here:
https://bugzilla.redhat.com/show_bug.cgi?id=1942164
> Bug 1942164: Increase OVN upgrade timeout to 90m from 75m

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
- test/extended/util/cluster/cluster.go
Skipping disruptive tests on single-node clusters which are not considered as highly available.
This will mark those kind of tests with the ``[Skip:NonHighlyAvailable]`` tag, and make any run with a single-node cluster to skip tests with this tag.
> on SNO, skip disruptive or multinodes tests

- test/e2e/upgrade/upgrade.go
The original PR https://github.com/openshift/origin/pull/26202 use
parens in the wrong place and the actual time calcs were happening
wrong and garbage values were being used, like this job [0] where
the test output looked like:
: [sig-cluster-lifecycle] cluster upgrade should complete in -1386946h6m26.707003392s minutes
This should fix that.
[0] https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.9-upgrade-from-stable-4.8-e2e-gcp-ovn-upgrade/1414923427529101312
> Bug 1942164: Fix time calc ordering for upgrades

- test/e2e/upgrade/upgrade.go
5c5627526a (#26324) adjusted how the failure-mode test-case name was formed, but did not adjust the success-mode test-case name.  This commit restructures to make it impossible to diverge going forward.
> test/e2e/upgrade/upgrade: Unify duration-overshoot test-case name

- test/extended/builds/remove_buildconfig.go
When checking that Build objects are garbage collected after their
parent BuildConfig was deleted, we used a crude means of verifying that
associated ConfigMaps were deleted. This improves the test by checking
that any remaining ConfigMaps in the namespace do not have an owner
reference.
> Bug 1977097: Improve GC Check for Builds

- test/extended/quota/clusterquota.go
Now that the service ca configmap publisher has been added by https://github.com/openshift/kubernetes/pull/834, the cluster quota test can be re-enabled with awareness of the new service ca configmaps.
/cc @stlaz @s-urbaniak @sttts @soltysh
> [release-4.7] Re-enable quota test

- test/extended/prometheus/upgrade.go
- test/extended/util/client.go
- test/extended/util/test.go
Some platforms, like the metal-ipi, have no persistent storage enabled
in the CI. In this case, we should skip the Prometheus upgrade test
since there is no way to preserve metrics across upgrades.
> Bug 1978338: Skip Prometheus upgrade test if persistance storage is not enabled

- test/extended/util/disruption/frontends/frontends.go
GCP has regressed, sometime around 7/12. This temporarily allows gcp
to be disrupted until this is resolved.
BZ for underlying problem: https://bugzilla.redhat.com/show_bug.cgi?id=1981872
> disruption: tolerate on gcp for frontend

- test/extended/builds/pipeline_origin_bld.go
- test/extended/testdata/bindata.go
- test/extended/testdata/imagestreamtag-jenkins-slave-pods.yaml
So the commented out test case is now handled by https://github.com/openshift/jenkins-client-plugin/pull/364
And the add of the label to the imagestream in the imagestreamtag pod template is happening as part of the scalability / existing behavior trade off we will be making once we release whatever version of the sync plugin after v1.0.46 we go with per the saga recorded in https://github.com/openshift/jenkins/pull/1297
I'll then be submitting a PR to sync plugin with my fixes from today that should pass tests once this merges.
/assign @coreydaley 
@openshift/openshift-team-build-api @openshift/team-devtools-jenkins FYI
> Bug 1925524: tweak jenkins imagestreamtag podtemplate test to label imagestream; jenkins multi namespace test has been moved to client plugin

- test/extended/authorization/rbac/groups_default_rules.go
/assign @slaskawi 
/cc @deads2k 
the role is getting added in https://github.com/openshift/cluster-authentication-operator/pull/464
> oauth-server certs e2e: add RBAC rule to be able to read the distributed cert in a CM

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
This PR updates `Skipped:Disconnected` list with the renamed test.
Previously;
`[sig-instrumentation][Late] Alerts shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured`
Currently;
`[sig-instrumentation][Late] Alerts shouldn't report any alerts in firing or pending state apart from Watchdog and AlertmanagerReceiversNotConfigured and have no gaps in Watchdog firing`
> Bug 1983614: Add renamed Prometheus test into skipped disconnected list

- examples/jenkins/pipeline/samplepipeline.yaml
- test/extended/testdata/bindata.go
@gabemontero The auto trigger always make sample-pipeline failed. Please help reivew this
> Remove auto trigger

- test/e2e/upgrade/alert/alert.go
We've allowed these for non-update jobs since 12b022c9b6 (#26102).  But they show up in update jobs too.  [For example][1] included:
alert ExtremelyHighIndividualControlPlaneCPU fired for 60 seconds with labels: {instance="ci-op-vjm670pq-1ff06-pn8bq-master-1", severity="critical"}
alert HighOverallControlPlaneCPU fired for 240 seconds with labels: {severity="warning"}
Searching for recent frequency:
```console
$ w3m -dump -cols 200 'https://search.ci.openshift.org/?maxAge=24h&type=junit&search=alert+.*High.*ControlPlaneCPU+fired+for' | grep 'failures match' | sort
periodic-ci-openshift-release-master-ci-4.9-e2e-gcp-upgrade (all) - 49 runs, 65% failed, 3% of failures match = 2% impact
periodic-ci-openshift-release-master-ci-4.9-upgrade-from-stable-4.8-e2e-gcp-upgrade (all) - 1 runs, 100% …
```
> test/e2e/upgrade/alert: Temporarily allow HighOverallControlPlaneCPU

- test/extended/util/disruption/disruption.go
Fixing a minor annoyance I found when debugging some gcp upgrade failures.
Currently when there's a disruption that's less than a second, we
truncate it to `0s` resulting in odd output like a failure with the
message `Frontends were unreachable during disruption for at least 0s of
1h17m57s`.
This change leaves the duration unchanged if less than a second, so
output will now say `during disruption for at least 382ms of 1h17m57s`.
For values > 1s, the current behavior will stay by rounding down.
> disruptive: output millis when disruption is < 1s

- test/extended/networking/endpoint_admission.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This PR applies only enabling TestEndpointAdmission test for OpenShift SDN
> Bug 1971590: Enable TestEndpointAdmission test only for OpenShift SDN

- cmd/openshift-tests/provider.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Some tests rely on the TestContext IPFamily field, that is being initialized in the upstream ginkgo suites but not in origin's one.
Here we add the initialization in InitTest so the test find the right value.
> Bug 1956989: initialize framework.TestContext.IPFamily correctly

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Necessary to land openshift/kubernetes#862
for etcd tests which is failing due to api changes from k8s 1.22
/assign @jsafrane 
for one more csi test
~~/assign @knobunc 
for UDPConnectivity tests~~
> Bug 1986003: disable etcd tests, one more csi and udpconnectivity

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
This PR adds tests, required internet access and fails in disconnected environment, into the `[Skipped:Disconnected]` list.
> Bug 1957193: Add tests required internet into Skipped:Disconnected list

- test/extended/apiserver/api_requests.go
Increasing the bounds based on
```
aws-ebs-csi-driver-operator, watchrequestcount=284, upperbound=216, ratio=1.3148148148148149
cloud-credential-operator, watchrequestcount=127, upperbound=124, ratio=1.0241935483870968
cluster-monitoring-operator, watchrequestcount=70, upperbound=64, ratio=1.09375
cluster-storage-operator, watchrequestcount=403, upperbound=310, ratio=1.3
csi-snapshot-controller-operator, watchrequestcount=197, upperbound=104, ratio=1.8942307692307692
etcd-operator, watchrequestcount=328, upperbound=250, ratio=1.312
kube-storage-version-migrator-operator, watchrequestcount=136, upperbound=72, ratio=1.8888888888888888
openshift-apiserver-operator, watchrequestcount=514, upperbound=452, ratio=1.1371681415929205
openshift-config-operator, watchrequestcount=99, upperbound=94, …
```
> bug 1987230: Single node apirequestscount upper bounds

- vendor/k8s.io/kubernetes/pkg/credentialprovider/config.go
- vendor/k8s.io/kubernetes/pkg/credentialprovider/config_test.go
> [release-3.11] Bug 1887306: UPSTREAM: 94712: [credentialprovider] avoid potential secret leaking while reading .dockercfg

- pkg/router/controller/hostindex/hostindex.go
Backport https://github.com/openshift/router/pull/126 (modulo potentially incompatible changes related to unit tests).
Before this patch, inactive routes were not being promoted when the conflicting routes were deleted. Fix it so that when deletes happen, all inactive routes are given a chance to be promoted.
> [release-3.11] Bug 1884421: Try to promote inactive routes following route deletion

- test/e2e/upgrade/alert/alert.go
- test/extended/prometheus/prometheus.go
Backport of #26305 to release-4.8.
This is not a blocker so it can wait for 4.8.z before being merged.
Also, the best would be to merge this PR before https://github.com/openshift/cluster-monitoring-operator/pull/1276 since once added to 4.8, the alert will fire from time to time and thus make the e2e tests fail.
> Bug 1981246: [4.8]: test/e2e: allow workload incorrectly spread alert

- test/e2e/upgrade/alert/alert.go
I'd added an exception for the wrong alert in d60209c73f (#26341).  This commit pivots the exception to cover the alert that is actually firing in CI.
> Bug 1985073: test/e2e/upgrade/alert: Temporarily allow ExtremelyHighIndividualControlPlaneCPU

- test/extended/pods/priorityclasses.go
OpenShift marketplace can have workloads pods that are created from Jobs which just have hashes. They can be safely ignored as they're not part of core platform. In future, if this assumption changes, we can revisit it.
cc @soltysh
> Bug 1986003: Ignore openshift-marketplace pods

- test/extended/cli/mustgather.go
The "oc adm must-gather" test in the e2e-aws-single-node suite is failing because
the openshift-apiserver.audit_logs_listing and oauth-apiserver.audit_logs_listing files content is only 38 bytes
while the test is expecting the size to be at least 50 bytes.
Since single node has just one host the file content is shorter.
This commit change the minimum required size to 20 bytes.
https://bugzilla.redhat.com/show_bug.cgi?id=1988828
> Bug 1988828: fix test - reduce minimum size of expected files in must-gather tests

- pkg/synthetictests/operators.go
There's currently a lack of consensus about whether going `Progressing=True` on things like "my DaemonSet is scaling as my cluster node set scales" is [helpful truth][1] (openshift/api#935) or distracting noise.  But we don't have any `Progressing=True` alerts, we do have `ClusterOperatorDown` and `ClusterOperatorDegraded` alerts, and they go off when components go `Available=False` and `Degraded=True` on updates.  Until those get sorted out, we don't have the energy to push for `Progressing` consensus, so this commit drops the:
clusteroperator/... should not change condition/Progressing
noise to make it easier for folks to focus on the more important condition changes.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1940286#c5
[2]: https://github.com/openshift/api/pull/935
> Bug 1941224: pkg/synthetictests/operators: Drop Progressing from "stable" transition checks

- pkg/monitor/monitorapi/types.go
- pkg/monitor/sampler.go
- pkg/synthetictests/apiserver.go
- test/extended/util/disruption/disruption.go
Downtime calculations didn't consider the average downtime *before* detection, so a minimum value is required.  This value is different than cases where the value is actually zero.
The intervals also calculated the startTime of a failure from when the failed request returned as opposed to when the failed request was originally made.  This can result in short downtime calculations, when the actual downtime was significant.
> bug 1989961: refine apiserver downtime sampling and calculations

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
`oc` vendored 1.22 already, and appears to have caused this
test to start [failing about 30-35% of the time](http://sippy-stbenjam-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com/sippy-ng/tests/4.9/details?showFull=1&test=%5Bsig-cli%5D%20Kubectl%20client%20Simple%20pod%20should%20return%20command%20exit%20codes%20%5BSuite%3Aopenshift%2Fconformance%2Fparallel%5D%20%5BSuite%3Ak8s%5D). We can add it
back once we get the fix from uptsream[1].
[1] https://github.com/kubernetes/kubernetes/pull/101295
> Bug 1991507: kubectl: mark exit codes test flaky until 1.22 rebase

- pkg/network/node/ovscontroller.go
EgressIP namespaces should only force the egressIP when the pod is the client. If the pod is the server we want to reply normally.
Backport of openshift/sdn#236
> Bug 1986413: Do not use egressIP on reply packets

- test/extended/operators/operators.go
While trying to set up CI testing for clusters with a `TechPreviewNoUpgrade` feature gate, this test fails as Kube API server blocks upgrades for tech preview clusters.
This PR adds an exception so that if a cluster has a `TechPreviewNoUpgrade` feature set enabled, and the appropriate condition, this will no longer prevent the test from passing.
Specifically it prevents this error:
```
Some cluster operators are not ready: kube-apiserver (Upgradeable=False FeatureGates_RestrictedFeatureGates_TechPreviewNoUpgrade: FeatureGatesUpgradeable: "TechPreviewNoUpgrade" does not allow updates)
```
Ref: https://github.com/openshift/release/pull/19845
> Ignore upgradable false condition on TechPreview clusters

- test/extended/image_ecosystem/s2i_images.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Samples operator library synch failed and we need move the versions forward for PHP. See details in https://bugzilla.redhat.com/show_bug.cgi?id=1990988
> Bug 1990988: Updating s2i images for php

- pkg/router/controller/hostindex/activation.go
- pkg/router/controller/hostindex/hostindex_test.go
Backport https://github.com/openshift/router/pull/57 and https://github.com/openshift/router/pull/59.
Ensure that a passthrough route displaces any path-based TLS routes with the same host, because passthrough is incompatible with path-based routing.
* `pkg/router/controller/hostindex/activation.go` (`hasExistingMatch`): Return true if both routes are TLS and the existing route is a passthrough route.
* `pkg/router/controller/hostindex/hostindex_test.go` (`Test_hostIndex`): Verify that a passthrough route displaces path-based TLS routes with the same host, but does not displace non-TLS routes.
Just as a passthrough route displaces any path-based TLS routes with the same host, a path-based TLS route displaces any passthrough route with the same host.
* …
> [release-3.11] Bug 1884422: Backport router hostindex fixes

- test/extended/prometheus/prometheus.go
As a part of https://github.com/openshift/release/pull/19845, we are trying to add TechPreview periodic jobs as release informing jobs.
To enable this, we need to make sure that the tests pass when the cluster is healthy and only valid failures are reported.
Today, two tests fail because of the presence of a `TechPreviewNoUpgrade` alert created by kube-apiserver when a `TechPreviewNoUpgrade` feature gate is present. Eg https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/19845/rehearse-19845-periodic-ci-openshift-release-master-ci-4.9-e2e-openstack-techpreview-parallel/1425432301084348416
To allow these tests to pass, we must allow the `TechPreviewNoUpgrade` alert when the feature gate is present.
> Allow TechPreviewNoUpgrade alerts when running on a TechPreview cluster

- test/extended/apiserver/kubeconfigs.go
/assign @p0lyn0mial 
since you complained about this particular to me some time ago, maybe not necessarily about this particular problem but it's a good starting point :wink: which I noticed fails pretty frequently
> Bug 1986003: Retry kubeconfig checks, when kube-apiserver is temporarily unavailable

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
We added the test to the "skip on disconnected" only, but it's failing on dual stack lanes.
> Bug 1994613: Re-disable the IPV6 should provide Internet connection test

- test/extended/apiserver/kubeconfigs.go
This is a followup to https://github.com/openshift/origin/pull/26377 but I'm switching this time to use backoff, so it'll retry more but it'll do that after 2, 10 and 50 seconds. 
In https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26401/pull-ci-openshift-origin-master-e2e-metal-ipi-ovn-ipv6/1427903228267204608 I've noticed we did retry, but every 2s which was too fast :disappointed: 
/assign @aojea
> Bug 1986003: Switch kubeconfig retries to use backoff

- test/extended/testdata/bindata.go
- test/extended/testdata/builds/build-quota/.s2i/bin/assemble
For those at RH, see https://coreos.slack.com/archives/C02258G4S79/p1629139934121300 for the tl;dr between @nalind and myself
summary: the cgroup swap files mean different things (memory+swap in v1, just swap in v2) our our build quota tests needs to account for this
or 
/assign @coreydaley 
whoever has the more immediate cycles.  Feel free to unassign as needed.
shellcheck:
```
gmontero ~/go/src/github.com/openshift/origin  (possible-cgroupv2-shell-solution-2)$ shellcheck test/extended/testdata/builds/build-quota/.s2i/bin/assemble 
gmontero ~/go/src/github.com/openshift/origin  (possible-cgroupv2-shell-solution-2)$ 
```
if you are still amenable to adding valid bz label so I can then test against this in …
> BUILD-278: account for cgroup v2 swap file only having swap for its amount, while cgroup v1 has memory+swap for its amount

- pkg/synthetictests/duplicated_events.go
we're hitting this one a lot and i don't think it is indicative of an actual underlying problem (it results from queuing up multiple rollouts and cancelations, which the deploymentconfig tests do)
https://search.ci.openshift.org/?search=DeploymentAwaitingCancellation+Deployment+of+version+2+awaiting+cancellation+of+older+running+deployments&maxAge=12h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
> Add 'DeploymentAwaitingCancellation' as an allowed repeated event

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Previously skipped dualstack tests(https://github.com/openshift/origin/pull/26241) have been renamed after the latest bump.
This PR adds renamed tests into OVN-K skipped list for dualstack.
> Bug 1996097: Skip renamed dualstack tests in OVNKubernetes

- test/extended/oauth/requestheaders.go
OAuthServer tests do not use the proxy settings defined in the environment, if presents.
This is currently required to run remotely the tests through a proxy, for the metal-ipi platform (see https://github.com/openshift/release/pull/19987)
> fix: add proxy support to OAuthServer tests

- test/extended/OWNERS
We seem to need to update networking-test-related annotations a lot, and sometimes it's hard to find Ben to get him to approve them for us, and then tests keep failing for days...
/cc @knobunc
> Add me to test approvers so I can approve annotation changes

- pkg/synthetictests/duplicated_events.go
Fix regex expression for the allowed repeated pattern for `DeploymentAwaitingCancellation` event
> Fix regex pattern for `DeploymentAwaitingCancellation` event

- pkg/synthetictests/duplicated_events.go
Ran into this here:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.9-e2e-aws-canary/1428864201471823872
did not appear to cause any test failures (not sure if that job runs any actual olm tests.  If it doesn't, that could explain it, or the pulls eventually succeeded before the test ran).
> Add imagepull backoff to frequent event allowlist

- test/extended/cli/builds.go
In 4.9 we have put a great deal of effort into making the testsuites 
pass on all architectures, including the newly added ARM, by using ubi8 
images.  https://github.com/openshift/origin/pull/26141 fails on 
non-x86_64 architectures due to use of a centos7 image which is not 
multi-arch enabled.  In addition, ruby-hello-world is currently using 
ruby-27.
/cc @atiratree @adambkaplan @soltysh
> Bug 1992596: cli: use ubi8/ruby-27

- test/extended/apiserver/resiliency.go
- test/extended/single_node/topology.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Adding test that validates cluster is resilient to API restarts.
Ultimately, it will make validations on other cluster components, but for now we'll validate API is getting up fast enough (40 seconds of outage).
This test will only run on single-node clusters, and should be part of suite of disruptive, serial tests.
> Bug 1999561: Add API rollout resiliency test

- test/extended/images/imagechange_buildtrigger.go
After the #26411 regarding this bug, we are already checking that correct value is in `LastTriggeredImageID` field of `BuildConfig`'s status.
Now, since `openshift-apiserver` changes have been merged, we can also check that same spec field is actually empty, and not filled.
> Bug 1986562: check buildConfig spec LastTriggeredImageID is empty

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
The corresponding upstream PR has been merged which should make the test
more robust: https://github.com/kubernetes/kubernetes/pull/101866
This means we can now re-enable the test for the Kubernetes `master`.
> Bug 1952457: Re-enable crictl node test

- test/e2e/upgrade/service/service.go
4.5 -> 4.6 upgrade jobs are perma failing: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.6-upgrade-from-stable-4.5-e2e-metal-ipi-upgrade
Among the failures the test: `: [sig-arch][Feature:ClusterUpgrade] Cluster should remain functional during upgrade [Disruptive] [Serial]` and `[sig-network-edge] Application behind service load balancer with PDB is not disrupted` are perma failing. 
These test are failing because they need to create load balancer type services on bare metal - it should not even try, since that can't work, ex: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.6-upgrade-from-stable-4.5-e2e-metal-ipi-upgrade/1410709653960003584/build-log. …
> Bug 1978717: Add BareMetalPlatformType into e2e upgrade service unsupported list

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
We picked up the kube fix in the rebase, we should be able to
re-enable this.
> Bug 1991507:  kubectl: re-enable exit codes test

- test/extended/idling/idling.go
- test/extended/testdata/bindata.go
- test/extended/testdata/idling-echo-server-rc.yaml
- test/extended/testdata/idling-echo-server.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
- test/extended/util/pods.go
While investigating bz 1953705, I discovered that most of the unidling e2e tests have been disabled for years because they were written under the assumption that the test runner was running inside the cluster. (There is one unidling test in `test/extended/router/` that is not disabled, so we weren't _completely_ without test coverage...)
> Bug 1989158: rewrite idling tests to not be [Local]

- test/extended/operators/operators.go
CustomNoUpgrade should be treated just as TechPreviewNoUpgrade, and
should not be a condition that triggers no-upgrade failures in tests.
This is useful in cases where we want to test a specific set of feature
gates in isolation from other tech preview feature gates.
Specifically we are using CustomNoUpgrade to test
external-cloud-provider CCM promotions in isolation in
https://github.com/openshift/release/blob/992f297ef8a1ba749f3a0b9b40438696f18a1bc4/ci-operator/step-registry/ccm/conf/pre-create-feature-gate/ccm-conf-pre-create-feature-gate-commands.sh#L22
Co-Authored-By: Matthew Booth <mbooth@redhat.com>
> Bug 1998029: CustomNoUpgrade should not fire no-upgrade failures

- test/extended/operators/OWNERS
Remove Evan's handle from test/extended/operators/OWNERS.
> Bug 1999159: Remove Evan's GH handle from OWNERS

- test/extended/router/metrics.go
This PR is a fix for https://bugzilla.redhat.com/show_bug.cgi?id=1969471
Verification steps:
1. Created cluster-bot  4.9.0-0.nightly-2021-08-07-175228 on aws
2. Executed the script [1] - noticed failures after a couple of runs
3. Updated and compiled the openshift-tests with the updated url call for prometheus
4. Executed the script [1] twice and noticed no failures
The proposed solution is really simple, it ensures that only active  targets are looked at restricting the amount of data returning from the prometheus call.
[1] `set -e; for x in {1..100}; do ./openshift-tests run-test '[sig-network][Feature:Router] The HAProxy router should enable openshift-monitoring to pull metrics [Skipped:Disconnected] [Suite:openshift/conformance/parallel]'; if [ "$?" -ne 0 ]; then break; fi; sleep 5; …
> Bug 1969471:  HAProxy tests in sdn-network-stress job are flaky

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Reverts openshift/origin#26320 since the test does not get excluded in the periodics.
> Bug 2000589: Revert "Re-enable crictl node test"

- test/extended/cli/mustgather.go
The test started to fail in the SNO CI after this PR adding this log got merged
https://github.com/openshift/cluster-kube-apiserver-operator/pull/1219
> Bug 2001441: must-gather: Ignore startup logs in kube-apiserver audit logs

- test/extended/networking/multus.go
- test/extended/testdata/bindata.go
- test/extended/testdata/net-attach-defs/bridge-nad.yml
- test/extended/util/annotate/generated/zz_generated.annotations.go
This test performs a similar test to the upstream multus-cni E2E test...
- Creates a net-attach-def
- Creates a pod with an annotation that refers to the net-attach-def
- Checks for newly created net1 interface and passes test if found
Feedback on the test contents/structure is welcome =)
> Added E2E test for multus-cni

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
- test/extended/util/cluster/cluster.go
The vast majority of the tests we run work and run fine through
an HTTP proxy to reach the target cluster under test, however a
handful of tests don't work. This adds a configuration to
openshift-tests to see if given the current proxy environment, we
would use a proxy to reach the API server. If so, then we skip
tests annotated with `[Skip:Proxy]`.
> test: skip tests that won't work behind a proxy automatically

- test/extended/cli/mustgather.go
This is a cherry-pick of #26450
> Bug 2002543: must-gather: Ignore startup logs in kube-apiserver audit logs

- test/extended/builds/start.go
These tests assume that builder's OS_GIT_MAJOR starts with 'v' as it
does in CI.  However, productized builds (nightlies and stable) are
built with OS_GIT_MAJOR=4.  When these tests from the openshift/build
testsuite are run on a nightly, the first fails, and the second could
return a false negative.
/cc @adambkaplan
> Bug 2003252: builds: fix BUILD_LOGLEVEL tests for nightlies

- test/extended/images/signatures.go
- test/extended/testdata/bindata.go
- test/extended/testdata/signer-buildconfig.yaml
This fixes portability issues with this test, given that origin-control-plane:3.11 (besides being obsolete) is only available for x86_64.  Also, copying the oc binary from the machine running the test into a container on the cluster would cause the test to fail when run on a different architecture, or when oc was built for a newer glibc.  There was also no guarantee that the oc found on the test machine matched that of the payload being tested.
Instead, this uses the payload cli container, which inherits UBI 8.  The rest of the changes are a consequence of adapting to the newer versions of gpg2 and skopeo.
> Bug 1960674: images: port image signature workflow test to OCP4/UBI8

- test/extended/builds/multistage.go
Buildah 1.22 modifies how steps are logged for builds.  While older builds would see
```
STEP 1: FROM ... AS test
```
in our multistage build test, 1.22 and later will produce
```
[1/2] STEP 1/2: FROM ... AS test
```
in the first stage of a two-stage build, when the first stage has two instructions in it.  Update our expectations to accept either version.
> tests/extended/builds: handle new step logging

- test/extended/apiserver/kubeconfigs.go
> Bug 2002552: Retry kubeconfig checks, when kube-apiserver is temporarily unavailable

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
This test was only just recently re-enabled after having been disabled for all of 4.x (#26155) but it seems that it's pretty flaky
> disable flaky unidling test

- pkg/monitor/event.go
- pkg/monitor/monitor.go
- pkg/monitor/monitor_test.go
- pkg/monitor/monitorapi/types.go
- pkg/monitor/noop.go
- pkg/monitor/pod.go
- pkg/monitor/serialization/resource.go
- pkg/monitor/types.go
- pkg/test/ginkgo/cmd_runsuite.go
The final states here should be stored and held in artifacts, where we can then argue over size, utility, and display.
> track the final state of pods and events from e2e tests for later debugging

- test/extended/baremetal/hosts.go
Platform is deprecated. Instead it is suggested using `PlatformStatus.Type`. This PR makes this change for baremetalhosts tests.
> Use PlatformStatus Type instead deprecated Platform

- pkg/synthetictests/duplicated_events.go
Since it's blocking merges, adding this event to the known events list while we investigate how to clean them up.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2006975
https://search.ci.openshift.org/?search=EtcdEndpointsDegraded%3A+rpc+error%3A+code+%3D+Canceled+desc+%3D+grpc%3A+the+client+connection+is+closing&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
/cc @hexfusion @bparees
> pkg/synthetictests: add etcd client connection closing to known events

- cmd/openshift-tests/e2e.go
- test/extended/networking/internal_ports.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Failing job - https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.9-e2e-aws-network-stress/1420053950479994880
The most often failing tests are:
```
[sig-network] Internal connectivity for TCP and UDP on ports 9000-9999 is allowed [Suite:openshift/conformance/parallel]
[sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]
```
Add [Serial:Self] label for tests that can't be run in parallel with a copy of itself, exclude these tests from "openshift/network/stress" suite.
"Internal connectivity for TCP and UDP on ports 9000-9999 is allowed" uses exclusive resources …
> Bug 1979962: Fix aws network stress tests

- test/extended/util/test.go
after https://github.com/openshift/origin/pull/26486 and https://github.com/openshift/kubernetes/pull/984, this will eliminate the race during e2e tests to get the "right" SCC permissions.
> stop adding individual serviceaccount namespace groups to SCC for e2e tests

- pkg/synthetictests/duplicated_events.go
The core are more severe.  The e2e namespaces caught an imagestream problem and a single-node upgrade problem this week, so they have value.    This gives us two different names to react to depending on urgency.
> split the event should not repeat pathologically into e2e and core

- cmd/openshift-tests/images.go
lack of passes in addition to failures on this test impacted https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregated-gcp-sdn-upgrade-4.10-micro-release-openshift-release-analysis-aggregator/1443917511878774784
though the run was likely doomed overall.
> record only known images test pass so we can get a percentage of passes

- test/extended/builds/gitauth.go
These tests depend on a secret which is only available on the CI step
registry, and therefore fail when run externally.
/cc @adambkaplan
> Bug 2003239: builds: skip private git repo tests outside of CI

- test/extended/builds/clone_git_protocol.go
Test is no longer valid as github has deprecated unauthenticated git://
access. Will be backported to all releases back to 4.6.
See https://bugzilla.redhat.com/show_bug.cgi?id=2019433 for proper fix.
> Bug 2019516: Skip test 'clone repository using git:// protocol should clone using git:// if no proxy is configured'

- test/extended/router/grpc-interop.go
- test/extended/testdata/bindata.go
- test/extended/testdata/router/router-grpc-interop-routes.yaml
- test/extended/testdata/router/router-grpc-interop.yaml
Enable the grpc-interop with edge-terminated route test, using the service's `spec.ports[*].appProtocol` field to specify that the backend pod expects h2c (cleartext HTTP/2) connections.  Add a test that uses h2c on both the frontend and the backend.
* `test/extended/router/grpc-interop.go`: Add a test that uses h2c on the frontend and backend.  Delete the skip for the edge-terminated route.
* `test/extended/testdata/router/router-grpc-interop-routes.yaml`: Add a non-TLS route.  Use target port 1110 for the edge-terminated route.
* `test/extended/testdata/router/router-grpc-interop.yaml`: Add port 1110 for gRPC over h2c to the grpc-interop service and pod container spec.
* `test/extended/testdata/bindata.go`: Update.
---
Requires https://github.com/openshift/router/pull/328.
> Bug 1826225: test/extended/router: Enable edge-terminated gRPC

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Some tests are known to be unstable since they need Internet access and
therefor cause issue when running behind a secured proxy.
Let's skip them for now.
> Bug 2019375: tests: skip some tests for proxy

- test/extended/baremetal/hosts.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This PR adds test to verify baremetal operator validating
webhook is healthy. It does this by trying to update bootMACAddress
which is not allowed and updating itself which should not get error.
Enabling BMO validating webhook PR https://github.com/openshift/cluster-baremetal-operator/pull/203 is prerequisite of this PR.
> Add baremetal operator validating webhook healthy test

- test/e2e/upgrade/adminack/adminack.go
- test/e2e/upgrade/upgrade.go
- test/extended/adminack/adminack.go
- test/extended/include.go
- test/extended/util/adminack.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Create test to verify Admin Ack functionality and include in both `extended`and `e2e/upgrade` tests.
> Bug 2009879: Add admin ack Upgradeable condition gate test

- pkg/monitor/api.go
- pkg/monitor/monitorapi/disruption.go
- pkg/monitor/write_job_run_data.go
- pkg/synthetictests/apiserver.go
- pkg/test/ginkgo/cmd_runsuite.go
- test/e2e/upgrade/service/service.go
- test/extended/util/disruption/frontends/frontends.go
- test/extended/util/disruption/imageregistry/imageregistry.go
write a data file that can be consumed by aggregation instead of parsing out of junit.
/hold
holding so that we can see the content is correct.  There is a followup needed to fix the four different ways we have to watch for disruption today. I didn't make it worse, but I think it's time to make it better.
> write disruption data

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Newly added `sig-builds][Feature:Builds][pullsearch] docker build where the registry
is not specified Building from a Dockerfile whose FROM image ref does not specify the image
registry should create a docker build that has buildah search from our predefined
list of image registries and succeed` test is failing permanently in disconnected
IPv6 metal jobs and this blocks new releases.
This PR disables this test on disconnected.
> Bug 2021433: Disable new build test on disconnected

- pkg/monitor/monitorapi/identification.go
- pkg/monitor/write_job_run_data.go
builds on https://github.com/openshift/origin/pull/26548
This tracks the duration of alerts firing for later aggregation.  This will allow us to latch progress on reducing the number of firing alerts in our CI clusters.
> add alerts to tracked metadata

- test/extended/prometheus/prometheus.go
This fixes an intermittent test failure that happens when `openshift/tools`
image (provided by the openshift/tools imagestream) used as the shell-image
in CreateExecPodOrFail helper is missing or yet to be populated in the
registry.
Before prometheus tests are run, it ensures that the imagestream is present
before running the actual test.
Signed-off-by: Sunil Thaha <sthaha@redhat.com>
> Bug 2002776: fix intermittent test failure due to missing tools image

- test/extended/oauth/http1.go
Golang 1.17 made it so that a TLS connection is terminated when
a client with supported ALPN protocols attempts to reach a server
that does not support any ALPN protocols or the clients' ALPN
protocols don't match those of the server.
> oauth e2e: fix the expected http2 error to match golang 1.17+

- test/extended/oauth/requestheaders.go
There's an errant semicolon in one of the test cases in
oauth/requestheaders.go. Prior to 1.17, go handled this behavior and
treated it like a &.  However, go's behavior has changed in 1.17[1]:
The net/url and net/http packages used to accept ";" (semicolon) as a
setting separator in URL queries, in addition to "&" (ampersand). Now,
settings with non-percent-encoded semicolons are rejected and net/http
servers will log a warning to Server.ErrorLog when encountering one in
a request URL.
For example, before Go 1.17 the Query method of the URL
example?a=1;b=2&c=3 would have returned map[a:[1] b:[2] c:[3]], while
now it returns map[c:[3]].
In go 1.17, the request is now parsed differently so the server returns
400 (bad request).
[1] https://golang.org/doc/go1.17#semicolons
> oauth/requestheaders: escape semicolon in URI

- test/extended/apiserver/api_requests.go
We have doubled the limit to account for longer tests and to catch pathological changes without blocking slow growth over time.  We will target slow growth via long term data collection.
> account for longer tests runs in the watch pathological watch test case

- test/extended/builds/imagechangetriggers.go
- test/extended/builds/jenkins_autoprovision.go
The current set of tests push the OpenShift cluster past its memory
limits. Removing the auto-provision and imagechange trigger tests from
the core Jenkins suite.
> Bug 2020611: Reduce Test Focus for Jenkins

- pkg/synthetictests/duplicated_events.go
In 4.10 the cluster-etcd operator will begin to version the etcd-endpoints cm resource as part of its static pod resources. During upgrade the installer controller can complain that the resource doesn't exist for the existing version. This can result in a few events as the controller requeues. This issue will resolve with the creation of the next revision which is the result of the upgrade itself.  Thus expected, transient, and benign.
cc @hasbro17  
ref: https://github.com/openshift/cluster-etcd-operator/pull/701#issuecomment-966455818
> pkg/synthetictests: add toleration for missing versioned etcd-endpoints cm during upgrade

- test/extended/networking/whereabouts.go
- test/extended/testdata/bindata.go
- test/extended/testdata/net-attach-defs/whereabouts-nad.yml
- test/extended/testdata/net-attach-defs/whereabouts-race-awake.yml
- test/extended/testdata/net-attach-defs/whereabouts-race-sleepy.yml
- test/extended/util/annotate/generated/zz_generated.annotations.go
Created 2 e2e tests for whereabouts. 
The first makes 4 pods with a whereabouts IPAM that only allows 3 IP addresses. The expected result is that the first 3 come up successfully and the 4th pod doesn't.
The second makes 2 pods, one with a parameter to sleep for ~20 seconds~ 5 seconds (configurable via `whereabouts-race-sleepy.yml`, located in `test/extended/testdata/net-attach-defs`) after getting its IP address, and the second with no such parameter. The expected result is that a race condition should not occur on working code, and both pods should be assigned unique IPs.
> Added 2 Whereabouts e2e tests

- pkg/monitor/alerts.go
found in https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.10-e2e-aws-serial/1459871441305473024
This just does its best to fill in something for missing data.  We don't know the actual end, but we know we don't want to fail and that some alert has started.
> prevent rare alert gathering panic

- test/extended/baremetal/hosts.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Add a test to check that the hostfirmwaresettings and firmwareschema resources are created and populated with BIOS configuration settings.
> Add parallel test for new baremetal resources

- test/extended/apiserver/kubeconfigs.go
Current implementation checks always the same kubeconfig file `localhost-recovery.kubeconfig` for all the cases.
See for example https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.8-e2e-metal-ipi-ovn-ipv6/1453817495201779712, where logs for the `lb-int` case report shows `localhost-recovery.kubeconfig` is used instead:
```
...
oc --kubeconfig /etc/kubernetes/static-pod-resources/kube-apiserver-certs/secrets/node-kubeconfigs/localhost-recovery.kubeconfig get namespace kube-system
...
```
> kubeconfigs: fix capture loop variable in closure

- test/extended/operators/tolerations.go
This pod is used in Hypershift to proxy the connection to the kube
apiserver from nodes. As even the kubelet uses it, it has to be a static
pod and that results in a keyless noExecute toleration being added by
the node.
> Managed cluster should ensure control plane operator: Allow hypershift kapi proxy

- test/extended/olm/olm.go
The default indexes are now available for arm64, and installed by
https://github.com/operator-framework/operator-marketplace/pull/420
/cc @timflannagan 
/assign @kevinrizza
> olm: enable test on arm64

- test/extended/cli/admin.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Switch the cluster-role-reapers test to Serial
This test run the cli command
"oc adm prune auth clusterrole/edit"
which prunes out the rolebindings for the other test that
are running at the same time.
> Bug 2022797: Switch the cluster-role-reapers test to Serial

- test/extended/cli/admin.go
Create new-project without updating kubeconfig
"oc new-project" writes out a new kubconfig file
effecting the outcomes of other tests running in
parallel.
There is at least 2 problems with this
1. kubeconfig is left empty for a short moment which
causes a problem if any other test takes a copy while blank.
e.g. any test that call CLI.UserConfig() or CLI.AdminConfig()
2. the current namespace of kubeconfig if changed by "oc new-project"
which effects any test currently using it to access the cluster.
> Bug 2023631: Create new-project without updating kubeconfig

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
This patch is required by metal-ipi IPv6 serial and compact jobs, since they are disconnected
Required by https://github.com/openshift/release/pull/23044
> Skip imageregistry serial test for disconnected environments

- test/extended/image_ecosystem/s2i_python.go
This is not fixing the bug it self but unblocking the CI pipeline
as a workaround. The fix for this bug will come from the python
image stream team, most likely, will send another PR to enable.
> Bug 2023238: Skipping Django Test until bug is fixed

- test/e2e/upgrade/service/service.go
The replication controller created by this test has 2 replicas with anti-affinity for
running on the same node, so it never becomes ready and times out on single-node clusters
This commit disables this test on single-node clusters
> Disable app behind service lb with pdb disruption test on single-node

- test/extended/util/disruption/controlplane/controlplane.go
On AWS single-node upgrade we observe around 10-14% downtime so the threshold is 15%.
On Azure we need a different threshold because we observe around 19-20% downtime.
> Allow even greater downtime on Azure single-node upgrade

- test/extended/cli/basics.go
In our CI, there are several jobs including baremetal that execute
tests through an HTTP proxy. Whenever our tests use an http client,
the transport should be set to use the ProxyFromEnvironment.
The test `[sig-cli] oc basics can get version information from API` is
now failing and blocking payloads, as when there's a CA present the test
builds it's own transport without proxy settings.
This test was added in https://github.com/openshift/origin/pull/26589.
> cli: use ProxyFromEnvironment for requests

- test/extended/machines/scale.go
- test/extended/machines/workers.go
When a MachineSet is scaled down, it randomly picks a Machine to remove from the group.
When a Machine is removed, it may contain also remove some workload that is long running and part of a failed test. To preserve the logs for later investigation, we should attempt not to disturb any of the running pods.
To minimise disruption, we should scale down the worker node that is added to the MachineSet as part of the scale test. This PR marks the newly created Machines for deletion by the MachineSet controller on scale down. Once marked, these Machines will be removed first, minimising disruption to other workloads.
> Bug 1880738: Minimise test disruption by removing newest workers in scale down

- test/extended/apiserver/kubeconfigs.go
External controlplane topology implies there are no master nodes, so
allow that.
> Local kubeconfig tests: Allow no master nodes when external controlpane topology

- test/extended/testdata/bindata.go
- test/extended/testdata/cmd/test/cmd/testdata/external-service.yaml
- test/extended/testdata/cmd/test/cmd/testdata/multiport-service.yaml
Hypershift uses a different service network, which results in the test
failing as it can not create the services because they have clusterIPs
in the wrong cidr.
From all that I can tell the value of those clusterIPs doesn't need to
be passed and is not asserted anywhere, hence just remove it. I've
tested that the test now passes on both standard self-hosted and
hypershift clusters.
> Fix 'oc expose can ensure the expose command' for custom service cidrs

- pkg/monitor/api.go
This caused the differences found in https://github.com/openshift/ci-tools/pull/2518
> double space preventing proper reporting for disruption

- test/extended/cli/builds.go
Instead of switching the current context to default
just Specify it in the status command preventing the
need to write out to KUBECONFIG, which may effect
other test reading from the file at the same time.
> Specify default namespace when getting API endpoint

- test/e2e/upgrade/upgrade.go
- test/extended/util/adminack.go
Manually picking #26621 back to 4.9.
> Bug 2025722: test/e2e/upgrade: Bump durationToSoftFailure by 15m for minor updates

- test/extended/cli/version.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Adding this test to validate kubernetes version so that we do not ship any GA bits which include invalid version of kubernetes.
> Add test to check kubernetes version

- OWNERS_ALIASES
- test/e2e/upgrade/adminack/OWNERS
- test/e2e/upgrade/adminack/adminack.go
- test/extended/adminack/OWNERS
- test/extended/adminack/adminack.go
- test/extended/util/openshift/clusterversionoperator/OWNERS
- test/extended/util/openshift/clusterversionoperator/adminack.go
So folks don't think Oleg is responsible for these, despite his test/extended/util/OWNERS entry.  Per Ben, he was only added as a starting point to deal w/ the fact that every team gets bottlenecked on approval whenever they touch something that impacts generated code.  This commit restructures so that [existing cluster-version operator approvers][1] (or other folks the origin maintainers want to use instead) can update these test-cases without needing to pull in more generic test-framework review and approval.
[1]: https://github.com/openshift/cluster-version-operator/blob/bc972aafe17f22b0f7f9f6552a327196c77dddf8/OWNERS#L3-L7
> test/extended/util/openshift/clusterversionoperator: Delegate admin-ack ownership

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
`[sig-cli] oc version check kubernetes version matches the io.openshift.build.versions label`
test tries to exec `oc image info` command in master nodes to compare
versions.
However, in disconnected configuration, this command can not access registry by
throwing `network is unreachable`.
This PR skips this test in disconnected.
> Skip oc version test in disconnected

- test/e2e/upgrade/upgrade.go
Picking #26202 , #26324 , and #26327 back to 4.8.
> Bug 1929650: Increase OVN upgrade timeout by 15m

- test/e2e/upgrade/adminack/adminack.go
- test/extended/util/openshift/clusterversionoperator/adminack.go
Poking in [this job][1] for [rhbz#2026806][2]:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade-4.6-to-4.7-to-4.8-to-4.9-ci/1463537431096594432/artifacts/e2e-aws-upgrade/clusterversion.json | jq -r '.items[].status.conditions[] | .lastTransitionTime + " " + .type + "=" + .status + " " + (.reason // "-") + ": " + (.message // "-")'
2021-11-24T16:06:34Z RetrievedUpdates=False NoChannel: The update channel has not been configured.
2021-11-24T16:30:08Z Available=True -: Done applying 4.8.0-0.nightly-2021-11-24-020113
2021-11-24T19:32:46Z Failing=False -: -
2021-11-24T19:03:45Z Progressing=True ClusterOperatorUpdating: Working towards 4.9.0-0.ci-2021-11-24-092816: 205 of 738 done (27% complete), …
```
> Bug 2026806: test/e2e/upgrade/adminack: Poll gates for duration of update

- test/extended/olm/olm.go
- test/extended/util/client.go
- test/extended/util/framework.go
These run in the hypershift management cluster so:
* Add code to get a client for that cluster and find the correct namespace
* Update the tests to check for the controlplanetoplogy and if its external, use the code from the first commit to talk to the correct cluster
> OLM should have imagePullPolicy: Fix when ExternalControlplane

- test/e2e/upgrade/upgrade.go
- test/extended/util/adminack.go
Picking #26634 back to 4.8.  Manually, because 4.8 doesn't have #26162.  Diff vs. 4.9 is trivial context conflict, but still enough to frighten off the cherry-pick bot:
```console
$ cherry-pick-diff origin/release-4.8..bump-update-time-limit-4.8 origin/release-4.9
2b3690ab28 -> 0088c744b5 test/e2e/upgrade: Bump durationToSoftFailure by 15m for minor updates
2b3690ab28 -> 0088c744b5 test/e2e/upgrade: Bump durationToSoftFailure by 15m for minor updates
--- 2b3690ab28
+++ 0088c744b5
@@ -35,9 +35,9 @@
diff --git a/test/e2e/upgrade/upgrade.go b/test/e2e/upgrade/upgrade.go
-index 01e7d952b1..20fcbbd5e7 100644
+index 2a7666962c..dc80d77626 100644
--- a/test/e2e/upgrade/upgrade.go
+++ b/test/e2e/upgrade/upgrade.go
-@@ -35,6 +35,7 @@ import (
- …
```
> Bug 2028021: Bump update time limit 4.8

- cmd/openshift-tests/openshift-tests.go
- cmd/openshift-tests/upgrade.go
- pkg/test/ginkgo/cmd_runsuite.go
It appears that on upgrade jobs where we invoke openshift-tests multiple
times (pre/post upgrade etc), the resulting two junit xml files are
merged by testgrid, and may contain the same test names. Testgrid then
mistakenly marks a test as a flake when in fact, one of them was a fatal
failure. This ultimately led to sippy showing massively successful test
pass rates when in fact we were failing almost all of the time.
This change attempts to address by using different junit test suite
names for different openshift-tests sub-commands.
In the case of the upgrade suite we're chasing problems in, we run:
openshift-tests run-upgrade all
openshift-tests run openshift/conformance/parallel
Hopefully this change will differentiate the tests sufficiently in
testgrid and sippy.
> Alter junit test suite names for jobs with multiple junit xmls.

- test/e2e/upgrade/adminack/adminack.go
- test/extended/util/adminack.go
Picking #26649 back to 4.9, but manually because I don't have #26650 in 4.9.
> Bug 2027929: test/e2e/upgrade/adminack: Poll gates for duration of update

- test/extended/builds/s2i_root.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/build-postcommit/sti.yaml
- test/extended/testdata/builds/build-timing/test-s2i-build.json
- test/extended/testdata/builds/statusfail-failedassemble.yaml
- test/extended/testdata/builds/statusfail-postcommithook.yaml
- test/extended/testdata/builds/statusfail-pushtoregistry.yaml
- test/extended/testdata/builds/test-build-cluster-config.yaml
- test/extended/testdata/builds/test-build-proxy.yaml
- test/extended/testdata/builds/test-build-revision.json
- test/extended/testdata/builds/test-nosrc-build.json
- test/extended/testdata/builds/test-s2i-build-quota.json
- test/extended/testdata/builds/test-s2i-build.json
- test/extended/testdata/builds/test-s2i-no-outputname.json
- test/extended/testdata/builds/valuefrom/failed-sti-build-value-from-config.yaml
- test/extended/testdata/builds/valuefrom/successful-sti-build-value-from-config.yaml
- test/extended/testdata/builds/volumes/docker-buildconfig.yaml
- test/extended/testdata/builds/volumes/s2i-buildconfig.yaml
- test/extended/testdata/templates/templateinstance_readiness.yaml
- test/extended/util/image/image.go
- test/extended/util/image/zz_generated.txt
- test/extended/util/nfs.go
This includes a [test image rebase](https://github.com/openshift/origin/blob/master/test/extended/util/image/README.md).
/cc @sttts 
/cc @dmage
> Adjust build test images for multi-arch support

- test/extended/cli/mustgather.go
Must gather creates a pod with a master role pod selector, but
Hypershift doesn't have master nodes. Additionally, a bunch of
controlplane components that the test expects to find in the must-gather
output run in the management cluster, so wont be there.
/cc @csrwng
> Skip must-gather tests when running on Hypershift

- test/extended/prometheus/prometheus.go
- test/extended/util/framework.go
None of these metrics exist there, as they come out of the apiserver
operator, require someone to manually install the cluster or are based
on etcd metrics.
> Hypershift: Skip Prometheus should have important platform topology metrics

- test/extended/security/fips.go
There are two changes needed:
* Don't test master nodes, as there are none
* Don't execute the command in the machine-config-daemon, but in an oc
debug pod. The only reason the machine-config-daemon was originaly
used is convenience, the test command can be executed in any pod as
long as its on the right node
Ref regarding "can be executed in any pod": https://coreos.slack.com/archives/C999USB0D/p1638981587077200?thread_ts=1638981423.077100&cid=C999USB0D
> Fix TestFIPS on Hypershift

- test/extended/util/disruption/disruption.go
Knowing the toleration when we undershoot is nice, and we've done that for a long time.  This commit also includes the tolerated percentage when we overshoot, so we can distinguish between "slightly overshot a best-guess threshold" from "hugely overshot a best-guess threshold" from "we were not expecting any disruption" without having to have internalized the job/test-case thresholds.  For [example][1]:
```
disruption_tests: [sig-network-edge] OAuth remains available via cluster frontend ingress using new connections | 1h7m18s
-- | --
Nov 29 21:09:48.043: Frontend was unreachable during disruption for at least 31s of 1h7m17s (1%):
```
is fatal, but it's not clear what the expected threshold was, and the logic for calculating toleration is [at least slightly fiddly][2].
[1]: …
> test/extended/util/disruption: Include tolerated percentage when failing

- cmd/openshift-tests/openshift-tests.go
- cmd/openshift-tests/upgrade.go
- pkg/test/ginkgo/cmd_runsuite.go
Reverts openshift/origin#26667
This is blocking payloads because on Azure, we now correctly report the sandbox test as a failure, whereas previously the pass+fail tests were incorrectly put together and considered a flake. Aggregation code and bigquery thinks the historical pass rate is 97%, and that is not the case at all on azure. With deads out and required to push any changes to fix the image manually, I don't think I can code a way to skip the test. 
For now I will revert this fix, until we can figure out how to keep payloads flowing and get the test data updated.
> Revert "Alter junit test suite names for jobs with multiple junit xmls."

- test/extended/prometheus/prometheus.go
The switch from `telemeter-client` to `remote_write` is up at https://github.com/openshift/cluster-monitoring-operator/pull/1416.
One of these two PRs will have to merge with failing tests in order to get past the chicken & egg situation.
> prometheus: adjust telemetry test for remote_write switch

- test/extended/util/oauthserver/oauthserver.go
every user of configObjectsDir already appends a slash after
configObjectsDir.  Avoid generating a path that has a double slash
as `var/oauth/configobjects//htpasswd`.
The reason for such fix is that the crun version currently used in the
CI has a bug when dealing with paths with multiple slashes.  The issue
has already been addressed upstream.
> test: avoid double slash in path

- test/extended/baremetal/hosts.go
When using preprovisioning images, masters fail to be adopted properly due to https://bugzilla.redhat.com/show_bug.cgi?id=2032573. Add a workaround until fix merges.
> Add workaround for baremetal resources test

- test/extended/cli/label.go
This is needed to land updated version of kubectl: https://github.com/openshift/oc/pull/1001
/assign @deejross
> oc label will properly report removed label

- pkg/monitor/backenddisruption/disruption_backend_sampler.go
- pkg/monitor/disruption_known_backends.go
- test/e2e/upgrade/service/service.go
- test/e2e/upgrade/upgrade.go
- test/extended/util/disruption/backend_sampler_tester.go
- test/extended/util/disruption/disruption.go
- test/extended/util/disruption/frontends/frontends.go
- test/extended/util/disruption/imageregistry/imageregistry.go
- test/extended/util/disruption/test_identification.go
replaces https://github.com/openshift/origin/pull/26675, built on https://github.com/openshift/origin/pull/26682
> use standard disruption checker for load balancer

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Some tests are known to be unstable since they need Internet access and
therefor cause issue when running behind a secured proxy.
Let's skip them for now.
(cherry picked from commit b2d569128f2abb5434ea5d36d9bf829efab6562b)
> Bug 2033341: tests: skip some tests for proxy

- test/extended/util/image/OWNERS
This will allow origin PRs which touch test/extended/util/image, which require special handling, to be labelled for better tracking.
This is the follow-up to https://github.com/openshift/release/pull/24398
/cc @smarterclayton @soltysh @sttts
who currently manage such PRs.﻿
> Bug 2033740: Implement e2e-images-update label

- go.mod
- pkg/monitor/backenddisruption/disruption_locator.go
- pkg/monitor/disruption_known_backends.go
- pkg/monitor/monitorapi/disruption.go
- pkg/monitor/monitorapi/identification.go
- pkg/monitor/monitorapi/types.go
- pkg/monitor/write_job_run_data.go
- pkg/synthetictests/apiserver.go
- pkg/synthetictests/event_junits.go
- test/e2e/upgrade/service/service.go
- vendor/modules.txt
builds on https://github.com/openshift/origin/pull/26703 and should give us a complete backend .json
> find disruption backends from the event intervals instead of a hardcoded list

- pkg/monitor/backenddisruption/disruption_backend_sampler.go
- test/extended/util/disruption/controlplane/controlplane.go
- test/extended/util/disruption/frontends/frontends.go
- test/extended/util/disruption/imageregistry/imageregistry.go
tolerate even more disruption with the more precise measurement.
> extend timeouts with 5s for each part

- pkg/monitor/cmd.go
- pkg/test/ginkgo/cmd_runsuite.go
[Avoid][1]:
```
INFO[2021-12-17T19:07:56Z] Tagging openshift/release:rhel-8-release-golang-1.17-openshift-4.10 into pipeline:root.
...
go vet  ./...
pkg/monitor/cmd.go:39:2: misuse of unbuffered os.Signal channel as argument to signal.Notify
pkg/test/ginkgo/cmd_runsuite.go:222:2: misuse of unbuffered os.Signal channel as argument to signal.Notify
```
which is [new for Go 1.17][2].  I'm not all that clear why the handler wants the buffering, because it seems like you could fill the buffer just as easily as you could fill an unbuffered channel.  But whatever, it's easy enough to give each of these channels two slots, so `Notify` can catch and queue enough to get us to quickly exit without needing to block on a channel write.
[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/p …
> Bug 2033810: pkg: Buffer signals for abortCh

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Similar to https://github.com/openshift/origin/pull/26352
Needed for 1.23 bump https://github.com/openshift/origin/pull/26711 and https://github.com/openshift/kubernetes/pull/1087
> Bug 2033751: Disable etcd test for 1.23

- pkg/monitor/backenddisruption/disruption_backend_sampler.go
In CI, metal clusters are accessed using a proxy, so the new sampler doesn't
work on metal.
> Bug 2035128: disruption: use proxy from environment when measuring disruption

- pkg/synthetictests/allowedbackenddisruption/matches.go
- pkg/synthetictests/allowedbackenddisruption/matches_test.go
- pkg/synthetictests/allowedbackenddisruption/query_results.json
- pkg/synthetictests/allowedbackenddisruption/types.go
- test/e2e/upgrade/service/service.go
- test/extended/util/disruption/backend_sampler_tester.go
- test/extended/util/disruption/controlplane/controlplane.go
- test/extended/util/disruption/disruption.go
- test/extended/util/disruption/frontends/frontends.go
- test/extended/util/disruption/imageregistry/imageregistry.go
built on https://github.com/openshift/origin/pull/26707
The last commit adds the historical data and the calculation
> set allowed disruption based on historical p95 data

- test/extended/util/disruption/backend_sampler_tester.go
I think this will solve our immediate problem, but we should add a better skip for the disruption test at some future point.  I don't know that we'll need to mess with it in 4.10, but it would be a good improvement if we end up back in the disruption calculations again for some reason.
/assign @stbenjam 
adding valid BZ to allow merging 
see existing skip logic here: https://github.com/openshift/origin/blob/master/test/e2e/upgrade/service/service.go#L112-L124
> allow skipping a backend test

- cmd/openshift-tests/images.go
- pkg/synthetictests/duplicated_events.go
- pkg/synthetictests/event_junits.go
- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/synthentic_tests.go
The full build suite includes several tests that force rollouts of
openshift-controller-manager. This causes duplicate
"reason/SuccessfulDelete" events to be detected, even though these
events are being triggered by separate rollouts. To fully address this
issue, openshift-controller-manager should be installed as a Deployment
rather than a DameonSet. This has better performance semantics with
respect to rollouts, which may benefit the install and upgrade
experience and reduce these "SuccessfulDelete" events.
This change provides a mechanism for known duplicate events to be
linked to a specific test suite, in addition to a specific platform or
topology. The known problem here is limited to the openshift/build test
suite, which can flake on this check and generally fails when the suite
is …
> Bug 2026488: Skip Duplicate openshift-controller-manager Events

- examples/jenkins/pipeline/bluegreen-pipeline.yaml
- examples/jenkins/pipeline/samplepipeline.yaml
- test/extended/image_ecosystem/s2i_images.go
- test/extended/testdata/bindata.go
- test/extended/testdata/cluster/quickstarts/cakephp-mysql.json
- test/extended/testdata/cluster/quickstarts/nodejs-postgresql.json
- test/extended/testdata/cluster/quickstarts/rails-postgresql.json
- test/extended/util/annotate/generated/zz_generated.annotations.go
The SCL team dropped this from imagestreams earlier than expected.
﻿- cluster: update nodejs-postgresql quickstart to nodejs:14-ubi8
- image_ecosystem: remove nodejs:12-ubi8
- jenkins: update templates for nodejs:14-ubi8
> Bug 2033720: Drop usage of old imagestreams

- test/extended/images/append.go
- test/extended/images/extract.go
- test/extended/images/info.go
- test/extended/images/layers.go
- test/extended/images/oc_tag.go
- test/extended/images/resolve.go
- test/extended/images/trigger/annotation.go
- test/extended/util/image/util.go
- test/extended/util/ldap.go
The intention of this PR is to enable some tests in the `openshift/conformance/parallel` suite which are not subject to the mirror configuration in `/etc/containers/registries.conf` to use a mirror as the source of their required images.  
Note: The pattern in this PR could be applied to other suites as well.
This is needed due to docker.io rate limiting causing CI on some platforms on 4.6 to be in permafail.  To use the feature in this PR:
- Prior to running `openshift-tests`, `export TEST_IMAGE_MIRROR_REGISTRY=<pull-through-cache-host>:<port>`
- Configure a pull-through cache for docker.io with a certificate signed by a well-known CA on a bastion that is only reachable by the nodes executing e2e tests. For example:
~~~
podman run -d -p 5000:5000 -v …
> Bug 1919453: [release-4.6] configure tests to pull images from mirror

- pkg/synthetictests/allowedbackenddisruption/matches.go
- pkg/synthetictests/allowedbackenddisruption/matches_test.go
- pkg/synthetictests/allowedbackenddisruption/query_results.json
- pkg/synthetictests/allowedbackenddisruption/types.go
adds topology to our p95 keys and sets the "missing data" value to `e seconds`, so we have a value to search for that doesn't show up often.
> making missing p95 obvious to see and add topology to our search keys

- pkg/synthetictests/allowedbackenddisruption/matches.go
- pkg/synthetictests/allowedbackenddisruption/matches_test.go
- pkg/synthetictests/allowedbackenddisruption/query_results.json
- pkg/synthetictests/allowedbackenddisruption/types.go
- test/extended/util/disruption/disruption.go
builds on https://github.com/openshift/origin/pull/26730, only the last commit is unique
round before we compare the disruption values.  We aren't really accurate below two seconds (if I remember nyquist correctly), so the rounding is fine and makes the comparison make more sense.  I think the p95 is still accurate enough because it has so many combined results.
This is to avoid messages like 
> Jan  6 14:35:12.184: disruption/service-load-balancer-with-pdb connection/reused was unreachable during disruption for at least 2s of 30m57s (maxAllowed=2s):
which are nonsensical.  That's close enough for this test I think.
> Round before comparing disruption

- OWNERS_ALIASES
- test/extended/util/annotate/generated/OWNERS
Expand on the scaffolding set up with e6f298436d (#26652) to empower all OpenShift team leads to manage skips and such for test-cases covering their own components.
Alias content based on `misc/tools/bin/leads.py` from the internal `li` repo (sorry external folks) as of 4c5bc167f9 (2021-12-17), with subsequent manual pruning for teams that had missing data or didn't seem like they'd care about origin content.
> test/extended/util/annotate/generated: Delegate to team leads

- test/extended/cli/explain.go
> Bug 1981867: add backoff retries for oc explain tests

- test/extended/baremetal/hosts.go
Now that the fix for https://bugzilla.redhat.com/show_bug.cgi?id=2032573 has merged, the workaround in openshift/origin#26693 can be reverted.
> Bug 2039074: Revert "Add workaround for baremetal resources test"

- test/e2e/upgrade/alert/alert.go
- test/extended/machines/cluster.go
- test/extended/prometheus/prometheus.go
- test/extended/prometheus/prometheus_builds.go
- test/extended/prometheus/storage.go
- test/extended/prometheus/upgrade.go
- test/extended/util/client.go
- test/extended/util/prometheus/helpers.go
This reduces the dependency chain and eliminates a source of error.  Just use the route directly.
> use route to access prometheus instead of exec pods.

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
- test/extended/util/cluster/cluster.go
This is manual cherry-pick of https://github.com/openshift/origin/pull/26664
> Bug 2038876: [release-4.8] test: skip tests that won't work behind a proxy automatically

- test/extended/util/disruption/disruption.go
we produce backend-disruption_20220107-223048.json, so no longer need to have the flake noise on every CI run.
> stop flaking on disruption because we always produce data for analysis

- cmd/openshift-tests/images.go
- cmd/openshift-tests/openshift-tests.go
- pkg/monitor/monitorapi/types.go
- pkg/monitor/write_job_run_data.go
- pkg/synthetictests/alerts.go
- pkg/synthetictests/allowedalerts/all.go
- pkg/synthetictests/allowedalerts/basic_alert.go
- pkg/synthetictests/allowedalerts/job_run_data.go
- pkg/synthetictests/apiserver.go
- pkg/synthetictests/duplicated_events.go
- pkg/synthetictests/event_junits.go
- pkg/synthetictests/kubelet.go
- pkg/synthetictests/networking.go
- pkg/synthetictests/operators.go
- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/junit.go
- pkg/test/ginkgo/junitapi/types.go
- pkg/test/ginkgo/synthentic_tests.go
- pkg/test/ginkgo/write_job_run_data.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/disruption/backend_sampler_tester.go
We have a list of known alerts now that is fairly easy to add to.  This is useful to allow us to indicate those runs where this alert did not fire.  This will allow us to find proper percentile values.
> Record zero for known alerts

- pkg/synthetictests/allowedalerts/all.go
/hold
for confirmation of understand from @tkashem and @wallylewis that this 
1. does not mean that https://bugzilla.redhat.com/show_bug.cgi?id=2039539 is not a blocker bug
2. does not mean that an appropriate fix is change the alert.  https://github.com/openshift/cluster-kube-apiserver-operator/pull/1284 fixes a symptom, but does not address a cause
3. The bug does mean that the source of latency needs to be found and either fixed or tightly categorized for impact.  p&f width/seats on lists is something @deads2k suspects.
The purpose of this PR is to unblock our merge queue, while leaving an "easy" signal to find for prospective fixes.  If the issue is fixed, then job runs will stop showing this as a flake.
> allow burn budget to flake until kube-apiserver team finds and fixes it

- pkg/synthetictests/duplicated_events.go
- pkg/synthetictests/duplicated_events_test.go
- test/extended/operators/operators.go
We changed the operator that is responsible for marking cluster as un-upgradeable. so update the e2e workarounds accordingly for UPI installs.
xref https://bugzilla.redhat.com/show_bug.cgi?id=2038389
> Bug 2038389: Fix vsphere testing workarounds

- test/extended/baremetal/hosts.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Metal3 pods can now be deployed on platforms: Baremetal, None,
OpenStack and VSphere.
But, in platforms other than BareMetal, baremetal hosts can be booted only via virtual media.
> Bug 2040741: Allow baremetal tests to run on multiple platforms

- pkg/synthetictests/duplicated_events.go
@vrutkovs says this is normal https://coreos.slack.com/archives/C01CQA76KMX/p1642451829259300?thread_ts=1642451358.258800&cid=C01CQA76KMX
> allow promtail restarts as designed

- pkg/synthetictests/allowedalerts/all.go
- pkg/synthetictests/allowedalerts/basic_alert.go
- pkg/synthetictests/allowedalerts/watchdog.go
- test/e2e/upgrade/alert/alert.go
- test/extended/prometheus/prometheus.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This separates the "no gaps in watchdog" into a separate test so we can track success/failure for it distinct from other alerts failing and avoid noise in the signal without losing the test coverage.
This also adds it as an invariant check at the end of runs to cover all those cases that aren't running [Late] tests.
> split watchdog test into its own test

- pkg/synthetictests/allowedalerts/all.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
https://search.ci.openshift.org/?search=alert+PrometheusOperatorWatchErrors+fired&maxAge=48h&context=1&type=bug%2Bjunit&name=4.10.*upgrade&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job shows that 1% of upgrades are hitting this alert.
The value seems small, but fixing enough 1% problems have real impact.  This doesn't fix it, but it does prevent it from failing the "we don't recognize this alert" test and will give is us a good bit of frequency data for different platforms.
> separate prometheus watch alerts

- pkg/synthetictests/event_junits.go
- pkg/synthetictests/operators.go
Recent test failure investigation led to a possibility of slow disk
speeds doing OS content extraction. Add a test to ensure that we move
from OSUpdateStarted to OSUpdateStaged within 5-10 minutes, which
primarily just encompasses extraction of the content.
If any node is over 10 minutes we will fail the test, if some are over 5
we'll flake instead.
> Add test for OS updates being staged within 5-10m.

- pkg/synthetictests/duplicated_events.go
To address
```
event happened 47 times, something is wrong: ns/openshift-kube-apiserver pod/kube-apiserver-guard-ci-op-h9q0w0xg-14a78-7gf8z-master-0 node/ci-op-h9q0w0xg-14a78-7gf8z-master-0 - reason/ProbeError Readiness probe error: Get "https://10.0.0.8:6443/healthz": dial tcp 10.0.0.8:6443: connect: connection refused
body:
event happened 47 times, something is wrong: ns/openshift-kube-apiserver pod/kube-apiserver-guard-ci-op-h9q0w0xg-14a78-7gf8z-master-0 node/ci-op-h9q0w0xg-14a78-7gf8z-master-0 - reason/Unhealthy Readiness probe failed: Get "https://10.0.0.8:6443/healthz": dial tcp 10.0.0.8:6443: connect: connection refused
```
E.g. https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.10-e2e-azure-ovn-upgrade/1482186672689909760
The KA …
> bug 2005901: Allow KA guard probe to fail as designed

- test/e2e/upgrade/alert/alert.go
- test/extended/prometheus/prometheus.go
prevent failures like https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.10-upgrade-from-stable-4.9-e2e-aws-ovn-upgrade/1484205905842016256
> allow loki target to be down

- test/extended/builds/volumes.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/volumes/csi-docker-buildconfig.yaml
- test/extended/testdata/builds/volumes/csi-s2i-buildconfig.yaml
- test/extended/testdata/builds/volumes/csi-sharedresourcerole.yaml
- test/extended/testdata/builds/volumes/csi-sharedresourcerolebinding.yaml
- test/extended/testdata/builds/volumes/csi-sharedsecret.yaml
- test/extended/testdata/builds/volumes/csi-without-rr-docker-buildconfig.yaml
- test/extended/testdata/builds/volumes/csi-without-rr-s2i-buildconfig.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
https://issues.redhat.com/browse/BUILD-275
> Bug 2037075: Verify Builds with CSI Volume Sources

- test/extended/operators/operators.go
cleans up failures like https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.10-e2e-vsphere-upi-serial/1484206475835346944
/assign @wking @gnufied
> storage operator can go upgradeable=unknown if vsphere is unreachable

- pkg/monitor/pod.go
- pkg/synthetictests/apiserver.go
- pkg/synthetictests/event_junits.go
a simple monitor test for checking immutability of `pod.spec.nodeName` field. 
The field is not allowed to change once set i.e. a pod assigned to a node must stay on it.
It will help gather more data (if any) for https://bugzilla.redhat.com/show_bug.cgi?id=2042657
> adds a synthetic test for checking if the pod.spec.nodeName field is immutable

- pkg/synthetictests/networking.go
more info in https://bugzilla.redhat.com/show_bug.cgi?id=2038481
essentially, two new guard pods are being started in 4.10+ and
are incorrectly being restarted on a cordoned node and when the
node is rebooted those pods fail to set up sandboxes right away
before the underlying network config file is present. This can
be reverted when the PR to fix this is merged:
https://github.com/openshift/library-go/pull/1287
https://github.com/openshift/origin/pull/26763 with gofmt goodness
> Bug 2038481: Flake failed sandboxes from bug in new guard pods

- test/extended/etcd/etcd_storage_path.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Etcd data from upstream has been updated with the rebase and the APIs that the test was previously complaining about have been added: https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/test/integration/etcd/data.go
> Bug 2034285: test/extended: re-enable API data in etcd test

- cmd/openshift-tests/provider.go
- cmd/openshift-tests/provider_test.go
- test/extended/util/alibabacloud/provider.go
Adding AlibabaCloud as a new cloud provider so that I can perform e2e tests.
Calling e2e is failing due to `alibabacloud` missing as a cloud provider.
```
E0124 22:54:06.535535     281 test_context.go:503] Unknown provider "alibabacloud". The following providers are known: aws azure baremetal gce gke ibmcloud kubemark kubevirt local openstack ovirt skeleton vsphere
```
https://github.com/openshift/release/pull/20841
> Bug 2045590: Adding new cloud provider e2e for alibabacloud

- test/extended/oauth/requestheaders.go
https://bugzilla.redhat.com/show_bug.cgi?id=2043042
This Pull Request adds a generation check and a missing `X-CSRF-Token` header to the `[Serial] [sig-auth][Feature:OAuthServer] [RequestHeaders] [IdP]`. This should help stabilizing the test or at least, make failure investigation easier in the future.
It also adds additional check to make explicitly sure the CAO is stable before executing the test.
> Bug 2043042: Additional checks for requestheaders.go

- pkg/synthetictests/event_junits.go
- pkg/synthetictests/operators.go
This new test seems to fail a fair bit on those platforms causing
unecessary failed jobs on platforms that can't yet meet this guideline.
Make sure we only flake on these platforms for now.
> Flake instead of fail the timely OSUpdateStaged test on metal and ovirt.

- pkg/synthetictests/allowedalerts/all.go
Allow the apiserver burn rate to fire since it is a great umbrella alert
to notice anything going wrong in the cluster. With the new thresholds
coming from upstream, it will only fire when a big enough disruption
impacting our SLO is happening.
Holding until https://github.com/openshift/cluster-kube-apiserver-operator/pull/1284 is merged.
/hold
/cc @deads2k @tkashem
> Bug 2039539: Allow apiserver burn rate alert to fire in CI

- test/extended/router/scoped.go
- test/extended/router/unprivileged.go
- test/extended/router/weighted.go
Skip HAProxy tests that use the router image's built-in default certificate, which is incompatible with FIPS.  This is a temporary measure to prevent CI from permafailing on FIPS over the weekend.
* `test/extended/router/scoped.go`:
* `test/extended/router/unprivileged.go`:
* `test/extended/router/weighted.go`: Skip on FIPS.
> Bug 2047790: Skip some HAProxy tests on FIPS

- test/extended/builds/volumes.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/volumes/csi-docker-buildconfig.yaml
- test/extended/testdata/builds/volumes/csi-s2i-buildconfig.yaml
- test/extended/testdata/builds/volumes/csi-sharedresourcerole.yaml
- test/extended/testdata/builds/volumes/csi-sharedresourcerolebinding.yaml
- test/extended/testdata/builds/volumes/csi-sharedsecret.yaml
- test/extended/testdata/builds/volumes/csi-without-rr-docker-buildconfig.yaml
- test/extended/testdata/builds/volumes/csi-without-rr-s2i-buildconfig.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
- Adds e2e tests for builds with csi volume in a techpreview clusters. e2e should be successful
- Adds e2e tests for builds with csi volume in non techpreview clusters. e2e should fail in this case
https://issues.redhat.com/browse/BUILD-275
> Verify Builds with CSI Volume Sources 

- test/extended/baremetal/high_availability.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This PR adds new baremetal test, namely
`[sig-installer][Feature:baremetal][Serial] Baremetal platform should ensure cluster baremetal operator and metal3 deployment return back healthy after they are deleted`.
This test will delete cluster baremetal operator and metal3 deployment
sequentially and ensures that baremetalhosts are in correct and healthy
state.
> Add baremetal high availability tests

- test/extended/util/disruption/frontends/known_backends.go
This test is currently blocking the required e2e-gcp-upgrade job on all
origin PRs. It looks to have broken sometime in the last few days when
the following tests began failing:
disruption_tests: [sig-network-edge] Console remains available via cluster ingress using new connections
disruption_tests: [sig-network-edge] Console remains available via cluster ingress using reused connections
The disruption shown is massive, one hour, the entire duration of the
upgrade.
This is because we are getting a response from the UI that does not
contain the expected text. Previously we expected to see "Red Hat
OpenShift Container Platform" (or OKD).
The actual request body is essentially to inform us that:
<noscript>JavaScript must be enabled.</noscript>
Presumably this is not new.
We no longer see …
> Fix broken console disruption test.

- pkg/synthetictests/allowedalerts/matches.go
- pkg/synthetictests/allowedalerts/matches_test.go
- pkg/synthetictests/allowedalerts/query_results.json
- pkg/synthetictests/allowedbackenddisruption/query_results.json
- test/extended/util/disruption/disruption.go
/cherrypick release-4.10
This picks for feb3 and should clean up our 4.11 signal and our 4.10 signal
> bug 2050345: update p99 values for disruption and alerts

- test/extended/baremetal/helper.go
- test/extended/baremetal/high_availability.go
This PR adds before step to run metal high availability test.
Thanks to that, test will ensure there is no other extra workers which
statuses can be set variably.
> Delete extra workers before running metal high availability test

- pkg/monitor/event.go
- pkg/synthetictests/operators.go
- Improve edge cases error message for OSUpdateStaged test.
- Debugging hack for missing event intervals.
An edge case we didn't really think was possible is occurring in about 0.07% of jobs. 
When this happens it appears we record an OSUpdateStaged event, but are missing an OSUpdateStarted, which logically should be there. Gather-extra sees it after the job when we oc get events, but for some reason the monitor is not recording it. Affects just one host in the job run, the others are fine.
Attempt to debug by ruling out whether or not we're getting the event at all in our watch.
> Debug missing OSUpdateStarted events

- pkg/synthetictests/networking.go
This reverts commit 333d91371a1835f499073208dbb712467921aea5.
https://bugzilla.redhat.com/show_bug.cgi?id=2038481 is resolved now and
this test workaround should no longer be needed.
> Revert "Flake failed sandboxes from bug in new guard pods"

- test/extended/baremetal/common.go
- test/extended/baremetal/hosts.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This patch adds a new simple test to verify that for every worker deployed there is a related preprovisioning image resource
> baremetal: add test for preprovisioning images

- pkg/synthetictests/allowedalerts/basic_alert.go
- pkg/synthetictests/allowedalerts/matches.go
- pkg/synthetictests/allowedalerts/types.go
- pkg/synthetictests/allowedbackenddisruption/matches.go
- pkg/synthetictests/allowedbackenddisruption/matches_test.go
- pkg/synthetictests/allowedbackenddisruption/types.go
- test/extended/util/disruption/backend_sampler_tester.go
This will show us which combination of configuration we're missing for a particular disruption check.
Shows up like `jobType=&platformidentification.JobType{Release:"4.11", FromRelease:"4.11", Platform:"gcp", Network:"sdn", Topology:"ha"}`
> add job type key to the error we track for statistical jobs

- pkg/synthetictests/event_junits.go
- pkg/synthetictests/operators.go
This is confirmed to be happening and we can see that we're missing
events in the disruption monitor watch when apiservers are upgrading.
Move this scenario out to it's own test, which will only ever flake,
while we work on a fix.
Original test will now ignore this scenario.
> Break out test for OSUpdateStaged event with no OSUpdateStarted.

- pkg/synthetictests/event_junits.go
- pkg/synthetictests/operators.go
- Break out test for OSUpdateStaged event with no OSUpdateStarted.
Cherry pick from #26824
> Bug 2052058: Break out test for OSUpdateStaged event with no OSUpdateStarted

- pkg/synthetictests/allowedalerts/matches.go
- pkg/synthetictests/allowedalerts/matches_test.go
- pkg/synthetictests/allowedalerts/types.go
- pkg/synthetictests/allowedbackenddisruption/matches.go
- pkg/synthetictests/allowedbackenddisruption/matches_test.go
- pkg/synthetictests/allowedbackenddisruption/types.go
- pkg/synthetictests/historicaldata/next_best_guess.go
- pkg/synthetictests/historicaldata/types.go
- pkg/synthetictests/platformidentification/types.go
- test/extended/util/disruption/backend_sampler_tester.go
This will help alleviate problems like https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/1302/pull-ci-openshift-cluster-network-operator-master-e2e-agnostic-upgrade/1491351105987153920  where we don't have exact data matches.
> bug 2053143:allow inexact matches for disruption data

- pkg/test/ginkgo/ginkgo.go
- pkg/test/ginkgo/status.go
- pkg/test/ginkgo/test.go
This patch adds the possibility to override the current timeout defined at the suite level for a specif test. This is required since in some specific cases a single test may require some extra time to successfully complete its execution, and it's not desirable to modify the global suite timeout since it will affect also other tests in the same suite.
The timeout is specified as part of the name using the special tag `[Timeout:<duration>]` with the required duration string, for example:
```
...
g.It("skip inspection when disabled by annotation [Timeout:300s]", func() {
...
```
In case of a malformed/incorrect duration string an error will be reported immediatly.
> Allow a single test to override suite timeout

- test/extended/baremetal/helper.go
- test/extended/machines/scale.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
With the fix to remove the extra worker deletion (https://github.com/openshift/origin/pull/26774) there have been occasional test failures when the time to delete the extra worker has exceeded the 15 minute test time. This adds back in the wait after the extra worker is deleted and increases the test time to allow the deletion to complete.
> Bug 2049117: Reenable wait on worker deletion and increase serial test timeout

- test/e2e/upgrade/alert/alert.go
- test/extended/prometheus/prometheus.go
- ignore ip-reconciler failures in CI for now
- Improve ignore for ip-reconciler KubeJobFailed alert.
> ip reconciler ignore

- pkg/synthetictests/allowedalerts/query_results.json
https://github.com/openshift/cluster-etcd-operator/pull/738 extended the time it takes to rollout etcd.  This improved overall install and upgrade success, but it means the time over which we change leaders is extended. this means these alerts are firing for a longer period of time.
/assign @deepsm007
> update alert thresholds after extending static pod install duration

- pkg/test/ginkgo/ginkgo.go
- pkg/test/ginkgo/status.go
- pkg/test/ginkgo/test.go
(cherry picked from commit 01d5fca41604c6e01bdfc440a5d30bab494b0145)
> Bug 2055193: Allow a single test to override suite timeout

- OWNERS
We just grew this component in Bugzilla, so declare it where [doozer][1] (and other consumers) can find it.
[1]: https://github.com/openshift/doozer/blob/231d240702a5c22da488fa241bc76df416acee6a/doozerlib/metadata.py#L288-L343
> OWNERS: Declare Bugzilla component

- pkg/synthetictests/static_pod.go
- pkg/synthetictests/static_pod_test.go
in https://docs.google.com/document/d/1NCqpSzIcUVsIcRnsR0dLcB-ja1L20ePVWKKZM5sKw-U/edit, we found failures where the kubelet was slow in creating the new revision.  This lets it be late.
> allow slow kubelet updates for static pods, but still fail if they never succeed

- test/extended/apiserver/api_requests.go
Observed it reaching 95 watch requests [prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.10-e2e-aws-single-node-serial/1466885201148776448](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.10-e2e-aws-single-node-serial/1466885201148776448)
[bugzilla.redhat.com/show_bug.cgi?id=2056450](https://bugzilla.redhat.com/show_bug.cgi?id=2056450) has been created to
follow up on this issue of increased watches
This PR can be reverted once the issue with increased watch is fixed
> Increase cluster-monitor-operator watch count threshold on single-node clusters

- pkg/synthetictests/networking.go
Test was skipping a junit on success, which appears to break aggregation
because it requires at least 3 results, and we're only getting 1 (a
failure) fairly commonly.
> Fix ovnkube-node readiness test to include successes.

- test/extended/machines/scale.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
For some jobs we noticed that the current 20 minutes timeout doesn't seem to be sufficient (ie `e2e-metal-ipi-serial-ovn-ipv6`), thus increasing it a little bit
> Increase scale test timeout to 30 minutes

- test/extended/util/ibmcloud/provider.go
For IBM Cloud testing, ignore errors when attempting to create
the 'e2e-node-attacher' CRB when it already exists, even after
attempting to configure a mutex to prevent concurrent creations.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2059299
> Bug 2059299: IBMCloud: Ignore CRB already exists

- pkg/synthetictests/duplicated_events.go
- pkg/synthetictests/event_junits.go
- pkg/synthetictests/image_pulls.go
- pkg/synthetictests/image_pulls_test.go
We'd like to track cases like [this](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26854/pull-ci-openshift-origin-master-e2e-gcp-upgrade/1496240296596344832):
```
event happened 45 times, something is wrong: ns/openshift-e2e-loki pod/loki-promtail-r6cbn node/ci-op-ipx1i5kt-db044-hw8hj-worker-b-p276c - reason/BackOff Back-off pulling image "registry.redhat.io/openshift4/ose-oauth-proxy:latest"
event happened 324 times, something is wrong: ns/openshift-e2e-loki pod/loki-promtail-h2zmg node/ci-op-ipx1i5kt-db044-hw8hj-master-2 - reason/BackOff Back-off pulling image "registry.redhat.io/openshift4/ose-oauth-proxy:latest"
```
and
```
ns/openshift-e2e-loki pod/loki-promtail-77rnl node/ip-10-0-182-230.ec2.internal container/oauth-proxy - reason/ContainerWait …
```
> Make a test to specifically look for image pull backoff for registry.redhat.io

- test/extended/networking/acl_audit_log.go
Clean up the namespaces in the network policy extended test.
> cleanup network policy ACL extended test

- pkg/synthetictests/image_pulls.go
followup to https://github.com/openshift/origin/pull/26858 re: "set to duplicateEventThreshold in a followup"
> Use common threshold constant as other event tests

- test/extended/apiserver/api_requests.go
```
Feb 25 11:08:59.756: INFO: operator=cluster-monitoring-operator, watchrequestcount=93, upperbound=82, ratio=1.1341463414634145
Feb 25 11:08:59.756: INFO: Operator "cluster-monitoring-operator" produces more watch requests than expected
```
From https://bugzilla.redhat.com/show_bug.cgi?id=2059845
> bug 2060406: operators should not create watch channels very often: bump OpenStack monitoring operator

- pkg/synthetictests/static_pod.go
- pkg/synthetictests/static_pod_test.go
The static pod synthetic test looks for a message specifying the
explicit revision, but it added a failure for each and every event that
was for another revision. This moves the failure adding to the outer
loop.
> Bug 2060498: only add failure when no event was found for the target revision

- test/extended/apiserver/resiliency.go
It has been witnessed and reported in https://bugzilla.redhat.com/show_bug.cgi?id=2059581 that the KubeApi becomes unexpectedly unreachable for a short time after the completion of the  Serial API resiliance test. While we await the resolution of the BZ, I have introduced a 60 second wait at the end of the test to ensure that the tests after do not break.
It is our intention that this wait will be removed after the resolution of the BZ.
> MGMT-9440: Fix single node serial tests API crash.

- test/extended/images/signatures.go
If the image signature workflow test fails, dump the pod and ConfigMap
states of the namespace under test.
> Bug 2057990: Add debug info for signature test

- test/extended/testdata/bindata.go
- test/extended/testdata/builds/build-quota/.s2i/bin/assemble
In the build-quota test script that we use to confirm that memory limits have been correctly set, do more of the work to find the right cgroup memory limit to read when we're in a cgroupsv2 setting.
The script already used some bash-specific syntax, so make that clear in the shebang line.
> Bug 2026063: build-quota test: fix cgroupv2 parsing holes exposed by buildah upgrade

- test/e2e/upgrade/dns/dns.go
- test/e2e/upgrade/upgrade.go
Add a new test to the upgrade test suite to validate DNS availability during and after an upgrade. The new test implements the simple [UpgradeTest interface](https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/test/e2e/upgrades/upgrade.go#L46). 
- `test/e2e/upgrade/dns/dns.go`: 
(`Name()`) and (`DisplayName()`) provides a name for the test to be used by the framework (e.g. for namespace creation, printing in the logs). 
(`Setup()`) performs the intial setup before the upgrade starts. It retrieves DNS Service Cluster IP and creates a DaemonSet (`createDNSTestDaemonSet()`) which performs a simple dig command (`while true; do dig +short @CLUSTER_IP google.com || echo $(date) fail && sleep 1; done`) to check DNS availability using the obtained Cluster IP.
(`Test()`) is …
> Bug 1961233: Add DNS availability upgrade test

- e2echart/e2e-chart-template.html
- pkg/monitor/intervalcreation/rendering.go
- test/extended/testdata/bindata.go
A recent change in the Spyglass HTML lens means if a `<title>` tag is
present, it shows that instead of the file name.  Currently each
interval chart is showing up as just `e2e-chart`.
> Give each interval chart a title

- test/extended/builds/build_pruning.go
- test/extended/builds/clone_git_protocol.go
- test/extended/builds/new_app.go
- test/extended/builds/service.go
- test/extended/builds/valuefrom.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/build-pruning/default-group-build-config.yaml
- test/extended/testdata/builds/build-pruning/default-legacy-build-config.yaml
- test/extended/testdata/builds/build-pruning/errored-build-config.yaml
- test/extended/testdata/builds/build-pruning/failed-build-config.yaml
- test/extended/testdata/cmd/test/cmd/deployments.sh
- test/extended/testdata/cmd/test/cmd/testdata/application-template-dockerbuild.json
Resolving some of the failures seen in:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.11-e2e-aws-no-capabilities/1503711956505202688
which runs our e2e but with optional capabilities (in this case, samples operator)
disabled.
Note, in a few cases we used "foo:latest" as the imagestream reference which had the nice property that it protected us as the imagestream version (e.g. nodejs:16) moved on to, say, nodejs:17.  None of these tests really care about the underlying image they are using, but it does mean the tests will no longer be automatically picking up newer versions of images as they become available, for better or worse.
> Migrate builds tests away from using sample imagestreams since samples will be optional

- test/extended/prometheus/prometheus.go
- test/extended/util/prometheus/helpers.go
Both tests are querying prometheus/thanos endpoints without any authentication information, the response HTTP status code should be [401 unauthorized](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401) (the user is not yet authenticated) instead of [403 forbidden](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) (an authenticated user has no access to the requested resource.
Do not merge yet. This can block tests of Cluster Monitoring Operator which is returning the code 403 from Oauth-proxy at the moment.
> Bug 2034688: allow Prometheus/Thanos to return 401 or 403 when the request isn't authenticated

- pkg/monitor/event.go
We have confirmed that events are being missed by the test monitor, which then appear in the events.json in must-gather/gather-extra steps. We believe this is due to the handling of resource version in this custom list watch code. Today is does a list of events and uses that resource version to establish the watch. When we encounter an error (which seems to be possible when apiservers are rolling), we repeat the process leaving a gap between the last event observed, and whatever the latest is when we re-establish and list again.
This is fixed by tracking the last resource version observed from incoming events, and using that to re-establish the watch.
> Attempted fix for missing monitor events.

- test/extended/networking/egress_router_cni.go
- test/extended/testdata/bindata.go
- test/extended/testdata/egress-router-cni/egress-router-cni-v4-cr.yaml
- test/extended/testdata/egress-router-cni/egress-router-cni-v6-cr.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
Adding basic egress-router-cni CI e2e test
- build ci test
```
make WHAT=cmd/openshift-tests
```
- manually invoke the test on an existing cluster
```
./openshift-tests run-test "[sig-network][Feature:EgressRouterCNI] should ensure ipv4 egressrouter cni resources are created [Suite:openshift/conformance/parallel]"
```
and for ovnk we can run this additional test
```
./openshift-tests run-test "[sig-network][Feature:EgressRouterCNI] when using openshift ovn-kubernetes should ensure ipv6 egressrouter cni resources are created [Suite:openshift/conformance/parallel]"
```
run this test manually for ovnk and openshift-sdn
```
STEP: Creating an egressroutercni object
STEP: Calling oc create -f /tmp/fixture-testdata-dir3344212678/test/extended/testdata/egress-router-cni/egress-router-cni-cr.yaml …
```
> Implementation for egress-router-cni e2e ci test

- test/extended/networking/egress_firewall.go
- test/extended/networking/util.go
- test/extended/testdata/bindata.go
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
- test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
Adding basic EgressFw CI test
- To manually run this test on ovnk cluster
```
./openshift-tests run-test "[sig-network][Feature:EgressFirewall] when using openshift ovn-kubernetes Should ensure egressfirewall is created [Suite:openshift/conformance/parallel]"
```
- To manually run this test on openshift-sdn cluster
```
./openshift-tests run-test "[sig-network][Feature:EgressFirewall] when using openshift-sdn Should ensure egressnetworkpolicy is created [Suite:openshift/conformance/parallel]"
```
- To run traffic in different name space
```
./openshift-tests run-test "[sig-network][Feature:EgressFirewall] EgressFirewall should have no impact outside its namespace [Suite:openshift/conformance/parallel]"
```
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
> Implementation for basic egressfw e2e CI test

- test/extended/util/image/README.md
This is my understanding after discussion with @derekwaynecarr
> Clarify that the image mirroring requirement applies to conformance tests only

- test/extended/networking/acl_audit_log.go
this was not testing correct operation of network policy. it only worked because of a bug in implementation
original PR: https://github.com/openshift/origin/pull/26876
> Bug 2055381: cleanup network policy ACL extended test

- test/extended/networking/acl_audit_log.go
this was not testing correct operation of network policy. it only worked because of a bug in implementation
original PR: https://github.com/openshift/origin/pull/26876
> Bug 2055380: cleanup network policy ACL extended test

- test/extended/authorization/authorization.go
- test/extended/etcd/etcd_storage_path.go
`ServerResources` function was removed in Kubernetes 1.24(ref: https://github.com/kubernetes/kubernetes/pull/107180). This PR changes places to `ServerGroupResources` to prevent any build errors in bump to 1.24.
> Use ServerGroupResources instead deprecated ServerResources

- test/extended/testdata/bindata.go
- test/extended/testdata/builds/volumes/csi-without-rr-s2i-buildconfig.yaml
Looks like I missed one test in https://github.com/openshift/origin/pull/26941 that runs on techpreview clusters.
> Bug 1996883: increasing build config loglevel

- test/extended/deployments/deployments.go
- test/extended/images/append.go
- test/extended/images/extract.go
- test/extended/templates/templateinstance_readiness.go
- test/extended/testdata/bindata.go
- test/extended/testdata/deployments/deployment-example.yaml
- test/extended/testdata/deployments/multi-ict-deployment.yaml
Resolving some of the failures seen in:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.11-e2e-aws-no-capabilities/1503711956505202688
which runs our e2e but with optional capabilities (in this case, samples operator)
disabled.
> Migrate tests away from using samples-operator provided imagestreams

- pkg/synthetictests/operator_mapping.go
CCM and baremetal are missing.  List updated based on list from a 4.11
cluster:
```
$ oc get clusteroperators -o name | sort
clusteroperator.config.openshift.io/authentication
clusteroperator.config.openshift.io/baremetal
clusteroperator.config.openshift.io/cloud-controller-manager
clusteroperator.config.openshift.io/cloud-credential
clusteroperator.config.openshift.io/cluster-autoscaler
clusteroperator.config.openshift.io/config-operator
clusteroperator.config.openshift.io/console
clusteroperator.config.openshift.io/csi-snapshot-controller
clusteroperator.config.openshift.io/dns
clusteroperator.config.openshift.io/etcd
clusteroperator.config.openshift.io/image-registry
clusteroperator.config.openshift.io/ingress
clusteroperator.config.openshift.io/insights …
```
> Add missing operators from the known operators list

- pkg/synthetictests/networking.go
In https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26908/pull-ci-openshift-origin-master-e2e-gcp/1509938673548791808 , we get:
```
$ cat e2e-events_20220401-174716.json | jq '.items[]|select (.message|test("Error at storage engine: Could not allocate IP in range"))'
{
"level": "Warning",
"locator": "ns/e2e-test-whereabouts-e2e-59pln pod/whereabouts-pod-fgf26 node/ci-op-vqn19vmz-2a78c-tgfb2-worker-c-drphp",
"message": "reason/FailedCreatePodSandBox Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_whereabouts-pod-fgf26_e2e-test-whereabouts-e2e-59pln_3a5636c4-7d4d-4e2c-ad3c-e35ba7bc63df_0(83b31776a78f0592ff291661771cfed6a1af6d718fc348e73b8f73f1fa549c62): error adding pod …
```
> Ignore FailedCreatePodSandBox event that is expected to happen

- pkg/synthetictests/event_junits.go
- pkg/synthetictests/kubelet.go
- pkg/synthetictests/platformidentification/types.go
Due to recent nto update `stalld` will be packaged via rhcos on OCP 4.11. This means that `tuned` profiles that make use of `stalld` in realtime kernel workers may experience an extra restart during upgrade.
Note that this is a one time occurrence, once upgraded and using the OS version of `stalld` going forward this should no longer trigger this test failure.
Signed-off-by: ehila <ehila@redhat.com>
> test: update synthetic test node restart count

- test/extended/networking/external_gateway.go
- test/extended/networking/util.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This validates pod creation fails when supplying an external gateway
address to the namespace that does not match the address family
of the pod.
This PR is continuation of this e2e test (https://github.com/ovn-org/ovn-kubernetes/pull/1881) in ovn-kubernetes.
> Add networking test for invalid external gateway

- test/extended/router/shard/shard.go
When standing up a new router shard omit the DNS managed conditions.
The remainder of the tests that spin up new shards go on to assert
that host names can be resolved so these conditions are not necessary
and will, in general, avoid tests failing on UPI platforms that don't
manage DNS.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2067323
> Bug 2067323: extended/test/router: omit DNS managed conditions for shards

- test/extended/prometheus/prometheus.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Looking at the telemetry data, 4.11 clusters send a bit more metrics on average
to telemetry than the previous versions. The threshold value needs to be
increased accordingly.
To calculate the new value, I've used the following PromQL query which averages
the cluster:telemetry_selected_series:count metric over the last 30 minutes for
all 4.11 installations and then returns the 99th percentile.
```
quantile(0.99,
avg_over_time(
(
cluster:telemetry_selected_series:count
*
on (_id) group_left group by(_id) (cluster_version{version=~"4.11.0-0.ci.+"})
)[30m:1m]
)
)
```
> Bug 2072924: increase the threshold on the number of telemetry series

- test/extended/util/prometheus/helpers.go
The Thanos API may return warnings when it sends back a partial response
(e.g. some of the requests to the Thanos stores have failed). This
happens in particular when the cluster is upgraded and Prometheus pods
are rolled out because the sidecar might be up while Prometheus hasn't
finished loading the WAL.
With this commit, RunQueryAtTime() logs the warnings when they exist
instead of returning an error.
Signed-off-by: Simon Pasquier <spasquie@redhat.com>
> Bug 2066457: don't fail when a query returns warnings

- pkg/synthetictests/duplicated_events.go
prevent the perma failing on 4.9:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.9-e2e-aws-serial/1511875308708433920
it was introduced in https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4.9.0-0.ci/release/4.9.0-0.ci-2022-04-06-133003 but the diff is sadly too large to try to bisect this, thus ignoring along with the existing BZ.
> Bug 2072902: [release-4.9] exclude loki-promtail from duplicated events

- test/extended/prometheus/prometheus.go
Signed-off-by: Martin Kennelly <mkennell@redhat.com>
Depends on https://github.com/openshift/cluster-network-operator/pull/1248 and https://github.com/openshift/cluster-network-operator/pull/1246 merging before this is accepted.
> test/extended/prometheus: Remove SDN/OVN-K alert rules

- test/extended/security/scc.go
as CRI-O will soon drop CapInh, see https://github.com/cri-o/cri-o/security/advisories/GHSA-4hj2-r2pm-3hc6 and CVE-2022-27652
Signed-off-by: Peter Hunt <pehunt@redhat.com>
> test: switch to testing CapBnd over CapInh

- test/extended/router/certs.go
- test/extended/router/config_manager.go
- test/extended/router/headers.go
- test/extended/router/scoped.go
- test/extended/router/unprivileged.go
- test/extended/router/weighted.go
IPv6 IP's need to be bracketed.
> router: fix all uses of Sprintf to build host:port for a URL

- pkg/synthetictests/event_junits.go
- pkg/synthetictests/storage.go
"[sig-arch] cloud API quota should not be exceeded" tells if OCP cluster under test encountered throttling from the underlyig cloud.
cc @openshift/storage @deads2k
> Bug 2011895: Add synthetic test for cloud API throttling

- pkg/synthetictests/duplicated_events.go
- pkg/synthetictests/duplicated_events_eviction.json
- pkg/synthetictests/duplicated_events_test.go
found in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26982/pull-ci-openshift-origin-master-e2e-aws-serial/1511793616459141120 when it did not detect the repeated `Malscheduled` event.
> correct pathological event detection

- go.mod
- test/extended/util/client.go
- vendor/modules.txt
/cc @stlaz @tkashem @soltysh @deads2k
> util/client.go: add method to specify pod security admission level

- pkg/synthetictests/allowedalerts/watchdog.go
SNO are running a single Prometheus replica and require reboots during upgrades. This test is skipped if its running on single node cluster.
cluster-bot's [test upgrade 4.10 4.11,https://github.com/openshift/origin/pull/26976 aws,single-node](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws/1512331511691481088)
> Bug 2072533: synthetictests: skip "alert/Watchdog must have no gaps or changes" on SNO upgrades

- test/extended/apiserver/api_requests.go
Based on percentile measurements the 50-percentile progresses around 112. 112/2 = 56.
> bug 2060406: bump apirequests upper bounds for GCP

- test/extended/util/disruption/disruption.go
Edited to flake recently but the error was still being returned, which caused a secondary test to fail on metal.
> Fix another issue with CVO upgrade ack timeout on metal.

- test/extended/networking/egress_firewall.go
- test/extended/networking/util.go
- test/extended/testdata/bindata.go
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
- test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
re-enabling basic EgressFw CI test
- To manually run this test on ovnk cluster
```
./openshift-tests run-test "[sig-network][Feature:EgressFirewall] when using openshift ovn-kubernetes should ensure egressfirewall is created [Suite:openshift/conformance/parallel]"
```
- To manually run this test on openshift-sdn cluster
```
./openshift-tests run-test "[sig-network][Feature:EgressFirewall] when using openshift-sdn should ensure egressnetworkpolicy is created [Suite:openshift/conformance/parallel]"
```
-To run traffic in different name space
```
./openshift-tests run-test "[sig-network][Feature:EgressFirewall] egressFirewall should have no impact outside its namespace [Suite:openshift/conformance/parallel]"
```
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
(cherry picked from commit …
> Bug 2072171: Reenable the implementation for basic egressfw e2e CI test

- pkg/synthetictests/duplicated_events.go
Needed in order to switch over to using static guard pods for etcd.
https://github.com/openshift/cluster-etcd-operator/pull/789
Associated BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2075204
See also: https://bugzilla.redhat.com/show_bug.cgi?id=2075015
/cc @deads2k
> Add exception for etcd guard pod readiness probe error events

- test/extended/router/scoped.go
I missed one in https://github.com/openshift/origin/pull/26983.
This ensures we construct the host:port correctly in a URL when working
with IPv6 addresses.
> router: construct url with net.JoinHostPort

- test/extended/util/disruption/disruption.go
Currently, all disruption test frameworks, most notable upgrade tests,
are being instanciated here. This sets their pod security level.
/cc @soltysh @stlaz
> test/.../disruption: set pod security level centrally

- pkg/synthetictests/allowedbackenddisruption/matches_test.go
- pkg/synthetictests/historicaldata/next_best_guess.go
SNO disruption tests for OVN will fail due to stricter fuzzy matching on P99 historical duration data, this PR opens the fuzzy matching to allow SDN historical data to be used on OVN cluster tests.
Signed-off-by: ehila <ehila@redhat.com>
> Best matcher single node OVN

- test/extended/builds/imagechangetriggers.go
- test/extended/util/framework.go
Trying to debug failures like the one that happened here:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.11-upgrade-from-stable-4.10-e2e-aws-ovn-upgrade/1514494231735963648
is impossible w/ the current test debug output:
```
:  [sig-builds][Feature:Builds] imagechangetriggers  imagechangetriggers  should trigger builds of all types [Skipped:Disconnected]  [Suite:openshift/conformance/parallel] expand_less | 36s
-- | --
{  fail [github.com/openshift/origin/test/extended/builds/imagechangetriggers.go:55]: Unexpected error:     <*errors.errorString \| 0xc0002fec60>: {         s: "timed out waiting for the condition",     }     timed out waiting for the condition occurred}
```
I suspect that the imagestream never imported successfully and …
> Dump imagestreams and buildconfigs on build imagechange trigger test failure

- test/extended/builds/volumes.go
Relax error string match to check for a substring instead
of an exact match so that we can bubble up better error messages
for these tests.
Supports https://github.com/openshift/openshift-controller-manager/pull/220
> Bug 2075584: Use substring match instead of exact match

- test/extended/apiserver/api_requests.go
```
Feb 25 11:08:59.756: INFO: operator=cluster-monitoring-operator, watchrequestcount=93, upperbound=82, ratio=1.1341463414634145
Feb 25 11:08:59.756: INFO: Operator "cluster-monitoring-operator" produces more watch requests than expected
```
Backporting https://github.com/openshift/origin/pull/26877
> bug 2059845: operators should not create watch channels very often: bump OpenStack monitoring operator

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
[slack conversation](https://coreos.slack.com/archives/CFP6ST0A3/p1650380304125629)
Apparently, this test is failing a lot on the `pull-ci-openshift-cluster-etcd-operator-master-e2e-metal-ipi-ovn-ipv6)` job on https://github.com/openshift/cluster-etcd-operator/pull/781
We will disable it on BM so it can continue to run elsewhere.
Here's a [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2076701) to track the progress on getting that test fixed.
> Disable FIPS disabled serving routes test on BM

- test/extended/dns/dns.go
This is just the boilerplate we need to make complying with the Restricted PodSecurityPolicy happy.
> test/dns: add the bits to make the Restricted PodSecurityPolicy happy

- pkg/synthetictests/storage.go
The latest CI payload was rejected on a test we only had 1 instance of
across the 10 runs [sig-arch] cloud API quota should not be exceeded:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregated-aws-ovn-upgrade-4.11-micro-release-openshift-release-analysis-aggregator/1517414586238636032
Tests should always be present so we can track failure % and aggregate
properly.
> synthetic: cloud api quota synthetic test should always be present

- test/extended/router/config_manager.go
Although HAProxy config manager test was skipped, the BeforeEach part of the test was not, and this was causing failures in the CI. This PR makes the BeforeEach part skipped as well. Also, this task https://issues.redhat.com/browse/NE-906 has been created to de-flake and re-enable the test in the future.
> Bug 2077457: Skip BeforeEach as well for the skipped HAProxy config manager test

- test/e2e/upgrade/adminack/adminack.go
- test/extended/util/openshift/clusterversionoperator/adminack.go
The test case:
[sig-cluster-lifecycle] TestAdminAck should succeed [Suite:openshift/conformance/parallel]
is vulnerable to brief API-server hiccups [like][1]:
Dec  6 00:00:10.440: FAIL: Error accessing configmap openshift-config-managed/admin-gates: Get "https://api.ci-op-g2m38jp7-eafe9.origin-ci-int-aws.dev.rhcloud.com:6443/api/v1/namespaces/openshift-config-managed/configmaps/admin-gates": dial tcp: lookup api.ci-op-g2m38jp7-eafe9.origin-ci-int-aws.dev.rhcloud.com on 172.30.0.10:53: no such host
[and][2]:
Dec  9 19:53:20.747: FAIL: Error accessing configmap openshift-config-managed/admin-gates: Get "https://api.ci-op-w5q90zpi-9278e.origin-ci-int-aws.dev.rhcloud.com:6443/api/v1/namespaces/openshift-config-managed/configmaps/admin-gates": dial tcp 100.21.251.165:6443: i/o timeout
This …
> Bug 2030972: test/extended/util/openshift/clusterversionoperator: Survive API hiccups

- pkg/synthetictests/duplicated_events.go
Known issue below, but no need to special case loki which we tend to
ignore in situations like these.
> Ignore loki NetworkNotReady repeating events.

- pkg/synthetictests/duplicated_events.go
- pkg/synthetictests/event_junits.go
- pkg/synthetictests/image_pulls.go
- pkg/synthetictests/image_pulls_test.go
See [TRT-201](https://issues.redhat.com/browse/TRT-201).
Example of what we want to separate out:
```
: [sig-arch] events should not repeat pathologically
2 events happened too frequently
event happened 56 times, something is wrong: ns/openshift-cluster-csi-drivers pod/gcp-pd-csi-driver-controller-6747df4b84-bc96x node/ci-op-5nx16hrj-d3bee-4jzmr-master-1 - reason/BackOff Back-off restarting failed container
event happened 78 times, something is wrong: ns/openshift-cluster-csi-drivers pod/gcp-pd-csi-driver-controller-6747df4b84-qjf5g node/ci-op-5nx16hrj-d3bee-4jzmr-master-2 - reason/BackOff Back-off restarting failed container
```
> Separate out 'Back-off restarting failed container' from pathological test

- test/extended/builds/pipeline_origin_bld.go
The BlueOcean annotation is no longer applied by the new version of
the plugin which we are upgrading to in 4.9. This test has already
been removed from 4.10 when the plugin was upgraded.
> [release-4.9] Bug 2076256: Remove BlueOcean annotation check

- test/extended/networking/tuning.go
- test/extended/networking/util.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This PR addes basic tuning-cni tests.
It verifies the following:
- all sysctls on the default allow list can be applied
- sysctls not on the whitelist can not be applied
- applying a sysctl via the tuning cni does not affect node sysctls
- applying a sysctl via the tuning cni does not affect previously created pod sysctls
- applying a sysctl via the tuning cni does not affect sysctls of consecutively created sysctls
> tuning-cni: basic tests

- cmd/openshift-tests/e2e.go
- test/extended/networking/services.go
- test/extended/networking/util.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/framework.go
This adds relevant e2e tests covering ExternalIP's `AutoAssignCIDRs` and `Policy`. 
For more details about `ExternalIP` feature, refer [here](https://docs.openshift.com/container-platform/4.9/networking/configuring_ingress_cluster_traffic/configuring-externalip.html).
> Add e2e tests for ExternalIP Policy and AutoAssignCIDRs

- test/extended/apiserver/api_requests.go
When deploying OCP on OpenStack with OVNKubernetes, we got this error
from the tests:
```
"Operator \"cluster-node-tuning-operator\" produces more watch requests than expected: watchrequestcount=143, upperbound=88, ratio=1.625"
```
Bumping the upperbound to 103 should solve this issue.
> Bug 2078528: bump cluster-node-tuning-operator apirequests upper bound for OpenStack

- test/e2e/upgrade/upgrade.go
Adding explicit signal that '[sig-cluster-lifecycle] Cluster completes upgrade' failed when preceding 'Cluster version operator acknowledges upgrade' fails before it.
> force completes upgrade failure if operator failure

- pkg/synthetictests/allowedbackenddisruption/matches_test.go
- pkg/synthetictests/historicaldata/next_best_guess.go
Back porting [PR](https://github.com/openshift/origin/pull/26929), This would allow fuzzy matching for SNO and OVN and should fix the identified tests: [Filtered Tests on 4.10 TestGrid](https://testgrid.k8s.io/redhat-openshift-ocp-release-4.10-informing#periodic-ci-openshift-release-master-ci-4.10-e2e-aws-upgrade-single-node&include-filter-by-regex=remains%3F%20available(.*)(with%7Cusing%7Cfor)%20(reused%7Cnew)%20connections&exclude-non-failed-tests=)
> [release-4.10] Bug 2077995: Best matcher single node OVN

- hack/verify-generated.sh
`--quiet` implied `--exit-code`:
```console
$ git diff --help | grep -A1 -- --quiet
--quiet
Disable all output of the program. Implies --exit-code.
```
So with this change, the exit codes remain unaffected:
```console
$ git diff --help | grep -A1 '^       --exit-code'
--exit-code
Make the program exit with codes similar to diff(1). That is, it exits with 1 if there were differences and 0 means no differences.
```
But [the not-very-actionable output like][1]:
```
Running hack/verify-generated.sh:14: executing 'git diff --quiet /go/src/github.com/openshift/origin/test/extended/util/annotate/generated/' expecting success...
FAILURE after 1.223s: hack/verify-generated.sh:14: executing 'git diff --quiet /go/src/github.com/openshift/origin/test/extended/util/annotate/generated/' expecting …
```
> hack/verify-generated: Replace --quiet with --exit-code

- pkg/monitor/monitorapi/identification_pod.go
- pkg/monitor/pod.go
- pkg/monitor/pod_test.go
- pkg/synthetictests/event_junits.go
- pkg/synthetictests/networking.go
This should let us catch cases where the networking for the cluster assigns the same IP to multiple pods at the same time.
> track pod IP re-use

- pkg/synthetictests/networking.go
Important to see this when we start correlating which pods got which
IPs and when.
> Include timestamp when reporting observed ReusedPodIP events.

- test/extended/util/prometheus/helpers.go
Prior to this chance, we may pick up a service account token that
isn't the one we require. This is causing rare flakes in CI runs.
Signed-off-by: Martin Kennelly <mkennell@redhat.com>
Sample CI run where flake occurred:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.11-e2e-aws-ovn/1514867591028412416
/cc @openshift/openshift-team-monitoring
> Increase determinism when searching for prom service secret token

- cmd/openshift-tests/e2e.go
- test/extended/networking/services.go
- test/extended/networking/util.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/framework.go
Reverts openshift/origin#26894
Apologies but this PR had to be reverted. The test is failing about 30% of the time particularly on serial jobs: https://sippy.dptools.openshift.org/sippy-ng/tests/4.11/analysis?test=[sig-network]%20services%20external%20ip%20ensures%20policy%20is%20configured%20correctly%20on%20the%20cluster%20[Serial]%20[Suite:openshift/conformance/serial]
And subsequently is it killing payload promotion and preventing code from flowing to the greater openshift org: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.11-e2e-aws-serial/1519658962591420416
> Revert "Add e2e tests for ExternalIP Policy and AutoAssignCIDRs"

- test/extended/util/framework.go
kube 1.24 stops autogenerating SA tokens in secrets in behalf
of the projected SA tokens.
/assign @tkashem
> don't wait for SA token secrets

- test/extended/machines/cluster.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
so that it examines the health of nodes collected at the beginning of a test suite
because some tests might add and remove nodes as part of their testing logic
nodes added dynamically naturally initially are not ready causing the test to fail
kudos goes to @dgrisonnet for helping me to understand the prom query!
> updates "managed cluster should report ready nodes the entire duration of the test run"

- test/extended/builds/pipeline_origin_bld.go
- test/extended/builds/pipeline_origin_bld_rhelimagesonly.go
The BlueOcean annotation is no longer applied by the new version of
the plugin which we are upgrading to in 4.10. This test has already
been removed from 4.11 when the plugin was upgraded.
> [release-4.10] Bug 2080759: Remove BlueOcean annotation check

- pkg/monitor/monitorapi/types.go
- pkg/synthetictests/duplicated_events.go
- pkg/synthetictests/event_junits.go
- pkg/synthetictests/image_pulls.go
GCP is only passing 50ish percent of the time.  Let's separate e2e namespaces from core namespaces to start.
> skip 'should not see excessive Back-off restarting failed containers' for e2e tests

- test/e2e/upgrade/upgrade.go
- test/extended/prometheus/image_pulls.go
To help make things [like][1]:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.11-upgrade-from-stable-4.10-e2e-aws-ovn-upgrade/1518821292038426624/artifacts/e2e-aws-ovn-upgrade/gather-extra/artifacts/events.json | jq -r '[.items[] | select(.reason == "Pulled" and (.message | match("[0-9]m[0-9.]+s")))] | sort_by(.metadata.creationTimestamp)[] | .metadata.creationTimestamp + " " + (.involvedObject | (.namespace + " " + .name)) + " " + .reason + ": " + .message'
2022-04-26T06:11:43Z openshift-cluster-version version--xpvbz-zldzn Pulled: Successfully pulled image "registry.build04.ci.openshift.org/ci-op-9k22xqj3/release@sha256:8b4a46a564186bc9738732c573ca317b2b9d897fd8456a7dea0ed4c87f64db83" in …
```
> test/extended/prometheus/image_pulls: New "should be fast" test-case

- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/test.go
This allows the -f option for openshift-tests to work with specific
test suites instead of assuming the "files" test suite.
Examples:
```
$ ./openshift-tests run --dry-run -f offline.txt 
error: suite "files" does not contain any tests
$ ./openshift-tests run all --dry-run | head -2 | ./openshift-tests run --dry-run -f -
"[Conformance][sig-api-machinery][Feature:APIServer] local kubeconfig \"lb-ext.kubeconfig\" should be present on all masters and work [Suite:openshift/conformance/parallel/minimal]"
"[Conformance][sig-api-machinery][Feature:APIServer] local kubeconfig \"lb-int.kubeconfig\" should be present on all masters and work [Suite:openshift/conformance/parallel/minimal]"
$ ./openshift-tests run openshift/csi --dry-run -f offline.txt
May  2 19:57:25.156: INFO: Driver loaded from …
```
> test: allow -f to match tests for any test suite

- test/extended/operators/routable.go
Currently prometheus apis exposed through oauth-proxy returns 403 on
unauthorized access. However the monitoring team is working on to
migrate to kube-rbac-proxy[1] which would 401 for unauthorized access.
This commit adds logic to handle both 401 and 403 status code.
A similar solution[2] has been employed already to fix other part of the relevant test.
[1] https://github.com/openshift/cluster-monitoring-operator/pull/1631
[2] https://github.com/openshift/origin/pull/26695
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>
> MON-2148: Handle 401 code for prometheus api route

- pkg/cmd/server/kubernetes/network/network_config.go
This fix parses the dnsRecursiveResolvConf node-config file
only if it exists on the node, otherwise ignore parsing it.
> Bug 2069201: Check resolv.conf file existence

- test/extended/dns/dns_libraries.go
- test/extended/testdata/bindata.go
- test/extended/testdata/dns/Dockerfile
- test/extended/testdata/dns/dns_libraries_go
- test/extended/testdata/dns/dns_libraries_go.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
This PR is adding an e2e test for go and glibc resolver libraries to reduce the risk that changes to our CoreDNS configuration break DNS resolution for clients. 
- `DNS lookup using Go's DNS resolver` test creates a pod using build and deployment configs where the pod has a simple go application which uses the `net` package to create a resolver targeting CoreDNS service clusterIP. It then calls `LookupHost` function to test DNS resolution for `www.redhat.com`. 
- `DNS lookup using glibc's DNS resolver` test creates a pod using jessie image and executes `getent -s dns ahosts www.redhat.com || echo $(date) fail` ten times to test DNS resolution for `www.redhat.com`. `getent` is a tool that comes with glibc library and can be used to test DNS resolution. It does not have any functionality …
> NE-626: Add DNS CI coverage for golang and glibc resolver libraries

- test/extended/util/openshift/clusterversionoperator/adminack.go
When there's another reason like `TechPreviewNoUpgrade`, the CVO will be complaining about both and set `MultipleReasons`.  We want the test suite to understand that that's still an `AdminAckRequired` complaint, and not fail [like][1]:
```
: [sig-cluster-lifecycle] TestAdminAck should succeed [Suite:openshift/conformance/parallel]
Run #0:  3m3s
{  fail [github.com/openshift/origin/test/extended/util/openshift/clusterversionoperator/adminack.go:117]: May  6 07:24:05.028: Error while waiting for Upgradeable to go AdminAckRequired with message "Kubernetes 1.25 and therefore OpenShift 4.12 remove several APIs which require admin consideration. Please see\nthe knowledge article https://access.redhat.com/articles/6955381 for details and instructions.\n": timed out waiting for the condition …
```
> test/extended/util/openshift/clusterversionoperator/adminack: Accept MultipleReasons

- test/extended/networking/tuning.go
Using sysctl to set values for net.ipv6.neigh.lo.base_reachable_time_ms=30001
is inconsistent between amd64 and aarch64/s390x/ppc64le.
amd64 seems to honor 1ms increments while other architectures round up to 10ms
`[sig-network][Feature:tuning] pod should start with all sysctl on whitelist [Suite:openshift/conformance/parallel] ` is failing for Multiarch 
https://bugzilla.redhat.com/show_bug.cgi?id=2082239
> Bug 2082239: Bump net.ipv6.neigh.IFNAME from 30005 to 30010 for Multiarch

- test/extended/prometheus/client/via_route.go
- test/extended/util/prometheus/helpers.go
Problem: In https://github.com/openshift/origin/pull/27073 the token retrieval
was improved. the via_route client had the same issue and can in some
cases use the wrong token.
Solution: create a helper so token retrieval is handled in a single
location.
Issues: https://github.com/openshift/origin/pull/27073
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>
> prometheus helper: add helper to retrieve prometheus query token

- test/extended/controller_manager/pull_secret.go
Because now there is no need to wait for the tokens to be created.
> Bug 2081012: Don't wait for sa token

- .golangci.yml
This enables a single linter for now, eventually we could turn on more but a quick
check of this code base is that the typical linters need some work to pass. 
Once this merges,  I'll setup the lint job.
---
This enables the [no-sprintf-host-port](https://github.com/stbenjam/no-sprintf-host-port) linter to prevent URL
constructions that are incompatible with IPv6. These breakages
are common in this repo.
The Go linter no-sprintf-host-port checks that sprintf is not used to
construct a host:port combination in a URL. A frequent pattern is for a
developer to construct a URL like this:
```go
fmt.Sprintf("http://%s:%d/foo", host, port)
```
However, if "host" is an IPv6 address like `2001:4860:4860::8888`, the
URL constructed will be invalid. IPv6 addresses must be bracketed, like this:
``` …
```
> Add config for golangci-lint no-sprintf-host-port

- test/extended/router/subdomain.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
* `test/extended/router/subdomain.go`: New file.  Verify that API admission and router admission properly handle routes with `spec.subdomain` set.
* `test/extended/util/annotate/generated/zz_generated.annotations.go`: Regenerate.
---
/hold
until the following PRs are merged:
> NE-883: test/extended/router: Add test for spec.subdomain

- test/extended/networking/tuning.go
Follow up for https://github.com/openshift/origin/pull/27101/files 
/cc @mmirecki
> Bump net.ipv6.neigh.IFNAME.retrans_time_ms for Multiarch

- pkg/synthetictests/apiserver.go
- pkg/synthetictests/event_junits.go
Many single second disruptions usually indicates a pattern where a particular node is not handling traffic properly. this will let us catch this (we think) rare pattern in CI.
> add test to catch single second disruption patterns

- pkg/synthetictests/allowedbackenddisruption/matches_test.go
- pkg/synthetictests/historicaldata/next_best_guess.go
This PR adds a fuzzy match on single node for previous micro upgrades when we lack data for single node minor upgrades
> Bug 2083941: feat: add fuzzy match on micro release

- cmd/openshift-tests/e2e.go
- test/extended/networking/services.go
- test/extended/networking/util.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/framework.go
The external ip configurations tests failing about 35% of the time in CI due to transient errors (service deletion takes a while to    delete it completely in the background, kube api server resets client tcp connection due to an unknown reason). Hence this fix    handles these errors gracefully to make test to succeed.
> Bug 2080007: unrevert external ip configuration e2e networking tests

- pkg/monitor/backenddisruption/disruption_backend_sampler.go
- test/extended/util/disruption/controlplane/known_backends.go
the identity will ill be used to trace audit logs for requests that were sent by the monitor tool
the primary use case will be to find requests that arrived at an API server during its shutdown procedure.
> Bug 2085997: gives the backend monitoring an identity

- test/extended/util/disruption/controlplane/known_backends.go
The new tests get data from the memory cache inside the {Kube,OpenShift, OAuth}API server.
When a request fails we will be able to narrow the scope to only the connection with the server itself.
In addition, we will be able to compare it with the tests that hit the database.
> Bug 2085997: adds new test to the API monitor

- cmd/openshift-tests/openshift-tests.go
Some jobs, like these two [0][1], are showing up as a failure, but there
is no clear reason for the failure other than the test container was
exit(2).
It appears to be happening after the suite run, this adds some
additional debug gathering data to help figure out where this is coming
from.
[0] https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.11-upgrade-from-stable-4.10-e2e-aws-ovn-upgrade/1524255508167397376
[1] https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.11-upgrade-from-stable-4.10-e2e-aws-ovn-upgrade/1524255509832536064
> Bug 2084361: Add some debugging information for mysterious exit 2 errors

- test/extended/etcd/invariants.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
a simple test for ensuring the number of etcd voting members matches the number of master nodes.
the test will be run right after cluster installation and before running any tests.
> Bug 2085997: ensure number of voting members in the cm matches the number of master machines

- test/extended/networking/egressip.go
- test/extended/networking/egressip_helpers.go
- test/extended/networking/util.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
- test/extended/util/framework.go
- test/extended/util/oauthserver/oauthserver.go
- test/extended/util/release.go
Implementation of the EgressIP downstream tests for OVN Kubernetes.
Given that these tests manipulate node and hostSubnet annotations, they must run without competition 
as part of the serial conformance suite.
Test behavior can be changed using several env variables:
EGRESSIP_TARGET_PROTOCOL, EGRESSIP_TARGET_HOST, EGRESSIP_TARGET_PORT
This is a first take on the tests and only tests IPv4 for OVNKubernetes and OpenShiftSDN on Azure, GCP and AWS. 
**Note:** The `vendor-update` label here is a legacy label that the bot added for an earlier version of this PR. The newest version does not modify the vendor folder, yet the bot still reports this.
**Note:** These tests only run on AWS, Azure and GCP and only run in serial. They skip anything baremetal and thus failing baremetal tests would not …
> EgressIP downstream tests for OVN Kubernetes

- pkg/synthetictests/duplicated_events.go
- test/extended/etcd/helpers/helpers.go
on some platforms, machine API can be totally off resulting in a 404 response, and on some, we might get an empty list.
this PR changes the etcd scaling test to take into account both scenarios.
> Bug 2085997: the machine API can be unavailable resulting in a 404 or an empty list

- test/extended/etcd/invariants.go
There are no master nodes when using an external controlplane topology,
so this can't work.
> Bug 2085997: ExternalControlPlaneTopology: Skip etcd master endpoint verification

- test/extended/image_ecosystem/s2i_images.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
RHEL 8 Ruby 2.6 retirement: March 2022
RHEL 7 Ruby 2.6 retirement: May 2022
RHEL 8 .NET 5 retirement: May 2022
RHEL 7 Python 2.7 retirement: July 2022
https://access.redhat.com/support/policy/updates/rhscl-rhel7
https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle
> Bug 2086086: image_ecosystem: remove deprecated imagestreams

- pkg/synthetictests/duplicated_events.go
- test/extended/etcd/helpers/helpers.go
- test/extended/etcd/vertical_scaling.go
for baremetal platforms requires an extra worker to be previously deployed to allow scaling operations. Otherwise creating a new machine has no effect and is stuck on `No available BareMetalHost found`
requires https://github.com/openshift/origin/pull/27127
> Bug 2085997: special configuration on barematal platform for the etcd vertical test is required

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Some but not all unidling tests were disabled when running on ovn-kubernetes.  This one was overlooked.
> Bug 2077167: disable unidling test failing under ovn-k

- test/extended/prometheus/prometheus.go
Reverts openshift/origin#27165
On this [payload run](https://amd64.ocp.releases.ci.openshift.org/releasestream/4.11.0-0.nightly/release/4.11.0-0.nightly-2022-05-24-163302), this [aggregated job](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregated-aws-sdn-upgrade-4.11-micro-release-openshift-release-analysis-aggregator/1529139076328853504) ran.
That job has 10 jobs in it and I see that the `: [sig-instrumentation] Prometheus when installed on the cluster should report telemetry if a cloud.openshift.com token is present [Late] [Skipped:Disconnected] [Suite:openshift/conformance/parallel]` test shows up in the "Tests Passed" list on a handful of those 10 jobs.
We can wait until more jobs pass before merging.
> Revert "Bug 2089831: Temporarily disable telemetry token test."

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
kube v1.24 update https://github.com/openshift/kubernetes/pull/1252 has landed, we need to skip these tests until we have a good clear signal with new kubelet
> Bug 2086092: skip tests to facilitate rebase

- pkg/monitor/alerts.go
- pkg/synthetictests/allowedalerts/basic_alert.go
- pkg/synthetictests/platformidentification/operator_mapping.go
found in https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.11-upgrade-from-stable-4.10-e2e-aws-ovn-upgrade/1530066656057888770 , but that still looks broken.
> restrict the per-namespace invariant alert check

- test/extended/cli/explain.go
When cluster version capabilities is set to None, the baremetal platform
is disabled, and as such, the metal3 CRDs aren't present.  Here, we load
the cluster version CR, and only include the metal3 CRDs when the
capabilities is set to anything other than None.
The error in CI is:
```
: [sig-cli] oc explain should contain proper spec+status for CRDs [Suite:openshift/conformance/parallel]
fail [github.com/openshift/origin/test/extended/cli/explain.go:494]: Unexpected error:
<*errors.errorString | 0xc001f173c0>: {
s: "exit status 1: the server doesn't have a resource type \"baremetalhosts\"",
}
exit status 1: the server doesn't have a resource type "baremetalhosts"
occurred
```
> Bug 2091086: cli: don't insist on metal3 CRDs being present when cluster capabilities are None

- test/extended/util/client.go
/assign @openshift/openshift-team-auth-maintainers 
/cc @deads2k
> Bug 2086519: label project-created namespaces to not sync PodSecurity labels

- test/extended/etcd/helpers/helpers.go
- test/extended/etcd/vertical_scaling.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- vendor/github.com/openshift/library-go/test/library/apiserver/apiserver.go
- vendor/github.com/openshift/library-go/test/library/client.go
- vendor/github.com/openshift/library-go/test/library/library.go
- vendor/github.com/openshift/library-go/test/library/pod_same_revision.go
- vendor/modules.txt
this PR:
- reverts https://github.com/openshift/origin/pull/27174
- skips the test on bare metal for now
- provides a fix for libvirt (https://github.com/openshift/origin/pull/27158)
- hardens `EnsureMemberRemoved` to tolerate some failures (https://github.com/openshift/origin/pull/27163)
- adds cleaning routine so that the test trying to bring the cluster to its initial state in case of an unexpected failures
- improves `EnsureVotingMembersCount` to check the `etcd-endpoints` cm
requires https://github.com/openshift/cluster-etcd-operator/pull/840 and https://github.com/openshift/etcd/pull/131
unfortunately, i cannot test aginst `libvirt`, not even from the `clusterbot`
```
test e2e-serial-remote-libvirt-ppc64le openshift/origin#27176
warning: You are using a custom test name, may not be …
```
> Bug 2085997: brings back the etcd scaling test

- test/extended/networking/egressip.go
- test/extended/networking/egressip_helpers.go
The EgressIP tests use the oc.Run() command a lot. Occasionally, these
commands seem to time out for some of the tests. Add retry logic so that
a single timeout calling the API won't make the entire test fail.
Tested on GCP OVNKubernetes (/):
~~~
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] pods should keep the assigned EgressIPs when being rescheduled to another node [Serial] [Suite:openshift/conformance/serial]"
echo ==========================
./openshift-tests run-test "[sig-network][Feature:EgressIP] [external-targets] only pods matched by the pod selector should have the EgressIPs [Skipped:Network/OpenShiftSDN] [Serial] [Suite:openshift/conformance/serial]"
echo ==========================
./openshift-tests run-test "[sig-network][Feature:EgressIP] …
> Bug 2091067: EgressIP: Make tests retry on API timeout errors 

- pkg/monitor/alerts.go
When fetching alerts from Thanos Query, we should first ensure that the
queriers are connected to both Prometheus sidecars. Otherwise the
returned data could have gaps which would fail the tests verifying that
the Watchdog alert has been always firing.
Signed-off-by: Simon Pasquier <spasquie@redhat.com>
> Bug 2079679: pkg/monitor: wait for Prometheus sidecars to be ready

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Proxy jobs run in an isolated network, the nc command does not correctly
use the proxy configuration defined in the system and the test
constantly fails.
> Bug 2091547: Skip internet connection test if we use a proxy

- pkg/synthetictests/static_pod.go
- pkg/synthetictests/static_pod_test.go
NodeCurrentRevisionChanged message does not contain the namespace for the static pod.
> Bug 2081732: remove incorrect namespace check in static pod test

- test/extended/pods/priorityclasses.go
I stumbled across an infrequent failure case where this test sees an openshift-must-gather -debug pod:
https://search.ci.openshift.org/?search=pods+found+with+invalid+priority+class&maxAge=168h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
These should be ignored.
> Bug 2093046: priority class: add exception for must-gather pending bug fix

- test/extended/networking/tuning.go
This test was listing all interfaces on the host with 'ls /sys/class/net'
which does not return a stable order of interfaces. Thus it was sometimes
reading host-side veths of pods, which would be gone (because we run
tests in parallel and pods are starting/stopping all the time) by the time
the test wanted to read the interface's sysctls.
```
Jun  2 16:13:38.827: INFO: Error running /usr/bin/oc --namespace=e2e-test-tuning-vz9kr --kubeconfig=/tmp/secret/kubeconfig exec nodeaccess-pod-lmbdb -- cat /host/proc/sys/net/ipv4/conf/090399bc34a8bcf/send_redirects:
StdOut>
cat: can't open '/host/proc/sys/net/ipv4/conf/090399bc34a8bcf/send_redirects': No such file or directory
command terminated with exit code 1
StdErr>
cat: can't open '/host/proc/sys/net/ipv4/conf/090399bc34a8bcf/send_redirects': …
```
> Bug 2093049: test/extended/networking: fix [pod sysctls should not affect node] to use host interfaces

- test/e2e/upgrade/cidisruptiontester/cidisruptiontester.go
Recently merged this backend and we're already seeing disruption to the
external service that doesn't even correlate to observed disruption of
the cluster under test.
Allowing 10 minutes of disruption means we'll almost always flake
instead of fail, while we gather more data and try to understand what's
happening.
> Bug 2092961: Flake almost all ci cluster to external svc disruption.

- pkg/synthetictests/kubelet.go
There are certain [documented exceptions](https://github.com/openshift/origin/blob/f88be40a20026986abd239bfb161f21dce283986/test/extended/util/image/README.md#kube-exceptions) where the ErrImagePull event is expected as part of a negative test.  This PR skips those so they are not counted as failures.
See the [Example CI job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/27202/pull-ci-openshift-origin-master-e2e-gcp/1532383286834237440) that ran with these changes.  Look for the `: [sig-node] should not encounter ErrImagePull in non-openshift namespace pods` failure and notice the ErrImagePull failures associated with the 3 regexes in the PR are no longer present.
Look for the same failure in the [another CI job](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs …
> Bug 2091110: Skip ErrImagePull for expected failures

- pkg/monitor/alerts.go
Reverts openshift/origin#27201 because it fails for single node jobs
> Revert "Bug 2079679: pkg/monitor: wait for Prometheus sidecars to be ready"

- test/extended/etcd/vertical_scaling.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
on `libvirt` the `etcd is able to vertically scale up and down with a single node` test seems to be interrupted after 15 minutes even though the global timeout for the suite is set (https://github.com/openshift/origin/blob/master/cmd/openshift-tests/e2e.go#L124). This PR sets the timeout explicitly for the test just in case something gets in the way and overwrites the global timeout for the suite.
for example:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-multiarch-master-nightly-4.11-ocp-e2e-serial-remote-libvirt-ppc64le/1533524212742885376
> Bug 2085997: explicit timeout for the etcd scaling test

- test/extended/networking/tuning.go
- test/extended/security/sysctl.go
This test was listing all interfaces on the host with 'ls /sys/class/net'
which does not return a stable order of interfaces. Thus it was sometimes
reading host-side veths of pods, which would be gone (because we run
tests in parallel and pods are starting/stopping all the time) by the time
the test wanted to read the interface's sysctls.
```
Jun  2 16:13:38.827: INFO: Error running /usr/bin/oc --namespace=e2e-test-tuning-vz9kr --kubeconfig=/tmp/secret/kubeconfig exec nodeaccess-pod-lmbdb -- cat /host/proc/sys/net/ipv4/conf/090399bc34a8bcf/send_redirects:
StdOut>
cat: can't open '/host/proc/sys/net/ipv4/conf/090399bc34a8bcf/send_redirects': No such file or directory
command terminated with exit code 1
StdErr>
cat: can't open '/host/proc/sys/net/ipv4/conf/090399bc34a8bcf/send_redirects': …
```
> Bug 2093049: test/extended/networking: fix [pod sysctls should not affect node] to use known host interfaces

- cmd/openshift-tests/openshift-tests.go
> Bug 2084361: Print error msg before os.Exit()

- test/e2e/upgrade/cidisruptiontester/cidisruptiontester.go
This is tripping about 20% of the time on a tls: internal error.
Trying http to see if that makes it more stable.
> Bug 2092961: Use http for network endpoint test.

- test/extended/etcd/helpers/helpers.go
vpshere serial is permafailing on `[sig-instrumentation][Late] Alerts
shouldn't report any unexpected alerts in firing or pending state`, with
TargetDown alerts for various components.
- This started around 5/11, which is when
https://github.com/openshift/origin/pull/26917 ended up in the first
payload
- TargetDown alerts always happens directly after the etcd vertical
scale test.
Example run:
https://prow.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.11-e2e-vsphere-serial/1532975513713250304
If you look at the intervals chart filtered by "TargetDown|vertical" you
can see the behavior.  This happens on every vsphere serial job.
> Bug 2094919: Skip etcd vertical scaling test on vsphere

- pkg/monitor/monitorapi/identification_pod.go
- pkg/synthetictests/operators.go
While chasing problems with `[bz-Machine Config Operator] Nodes should reach OSUpdateStaged in a timely fashion` like in https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.11-e2e-aws-upgrade/1532346119462326272, I found that we don't have a backstop value for osupdatestaged.  If we complete the upgrade, then at some point we were OSUpdateStaged even if we didn't observe that event.
> bug 2093051: use the node update finished as a backup completion time for OSStaged

- pkg/monitor/backenddisruption/disruption_backend_sampler.go
- pkg/monitor/backenddisruption/disruption_backend_sampler_test.go
- pkg/monitor/backenddisruption/disruption_locator.go
- pkg/monitor/write_job_run_data.go
- pkg/synthetictests/event_junits.go
- pkg/synthetictests/networking.go
From [TRT-277](https://issues.redhat.com//browse/TRT-277) we know that the CI build clusters where openshift-tests runs are encountering DNS lookup problems. These surface as disruption intervals and sometimes test failures where the message looks something like "dial tcp: lookup [hostname]: i/o timeout". We also know at this time that the same error will usually be reported trying to sample a separate external service, with nothing to do with the cluster under test.
We believe this particular error is safe to ignore for the purposes of disruption sampling, it's local to where the tests are running, and not the cluster we're trying to communicate with.
This PR continues to record these intervals, but at warning level instead of error. I have confirmed that warning level intervals still …
> Bug 2097297: Don't consider DNS lookup failure disruption

- test/e2e/upgrade/upgrade.go
In the baremetal environment, especially on ipv6 configuration, it
often happens that the current 4 minutes timeout is not enough to
let the cvo verify the upgrade.
Bumping the timeout value to a ridiculous 10 minutes to try and
improve the situation.
> Bug 2093992: Bump timeout for cvo ugprade check to 10 minutes for Baremetal jobs

- pkg/synthetictests/allowedalerts/allow_on_revision_change.go
This can fire on AWS in rare circumstances where we allow 20 minutes,
but we get 5s - 1min more than allowed, or very rarely up to 5 min more
than allowed.
The problem resolves itself and tests start passing again, indicating
the current limit is valuable, but a little higher will still be
valuable and cause less false positives for problems.
See: https://issues.redhat.com/browse/TRT-305
> Bug 2097713: Extend the allowance for etcdHighNumberOfLeaderChanges.

- test/extended/networking/egressip.go
Remove the print statement on test failure:
a) the print function was trying to print elements "host" instead of
"node" (this was a type)
b) the print statement is of limited value at the end of tests and tends
to pollute the logs (and release's artifacts should contain the same
and more information)
> Bug 2098094: EgressIP test: Remove print statement on test failure

- test/extended/apiserver/api_requests.go
Small increase in the upperbound limit of watch channels for etcd-operator
to avoid frequent failures in ipv6 jobs.
We usually see jobs fail for a small amount of watch channels, for example:
watchrequestcount=431, upperbound=406
> Bug 2099611: Increase etcd-operator watch channels upperbound for BareMetal Platform

- test/extended/authorization/podsecurity_admission.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This is a test to check that our SCC system by default mutates container and pod security context so that they can run with the restricted security profile
> Bug 2086519: authorization: add a test checking that the restricted-v2 SCC mutates securityContext to match restricted PSa

- pkg/synthetictests/duplicated_events.go
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x47791db]
github.com/openshift/origin/pkg/synthetictests.isEventDuringInstallation({{0x1, {0xc0064240e0, 0x62}, {0xc006b74840, 0x34}}, {0x0, 0xeda2b470d, 0xbfae940}, {0x0, 0xeda2b470d, ...}}, ...)
github.com/openshift/origin/pkg/synthetictests/duplicated_events.go:484 +0x2db
github.com/openshift/origin/pkg/synthetictests.testOvnNodeReadinessProbe({0xc00f6dc000, 0x6ee1, 0x745d?}, 0xc01adbe820?)
github.com/openshift/origin/pkg/synthetictests/networking.go:253 +0x408
github.com/openshift/origin/pkg/synthetictests.SystemUpgradeEventInvariants({0xc00f6dc000, 0x6ee1, 0x745d}, 0x0?, 0xc014480000?, {0x7e617a9, 0x3}) …
```
> Bug 2093122: synthetictests: Event struct's Related field is optional

- test/extended/networking/external_gateway.go
- test/extended/networking/util.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Re-revert of [26975](https://github.com/openshift/origin/pull/26975) and fix the test for ipv6 or dual stack clusters.
> Bug 2098053: Re-revert "Add networking test for invalid external gateway"

- test/extended/cli/explain.go
- test/extended/operators/operators.go
[TRT-371](https://issues.redhat.com//browse/TRT-371)
Several tests are failing because the metal images are being rebuilt on RHEL9. As soon as this merges, I'll open a revert so we don't forget to turn these back on.
`Managed cluster should have operators on the cluster version` fails since we have CBO from 4.11.
`oc explain should contain proper spec+status for CRDs` is failing on
4.12 jobs with errors like this:
```
{  fail [github.com/openshift/origin/test/extended/cli/explain.go:518]: Unexpected error:
<*errors.errorString | 0xc00201ef30>: {
s: "exit status 1: the server doesn't have a resource type \"provisionings\"",
}
exit status 1: the server doesn't have a resource type "provisionings"
occurred
Ginkgo exit error 1: exit with code 1}
```
This is because ART is not presently …
> Bypass tests failing due to metal image rebuild on RHEL9

- pkg/synthetictests/networking.go
separates out failures like https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.11-e2e-azure-ovn-upgrade/1535593831418826752 into their own category.  Doesn't fix the problem
> make a new category of pod sandbox failure

- e2echart/e2e-chart-template.html
- test/extended/testdata/bindata.go
In #27238 we began treating DNS lookup errors as disruption warnings not
errors, as they indicate a problem in the CI cluster not the cluster
under test.
I confirmed warnings would show in the graph, but did not realize this
was based on the message. When the message later was changed for these
warnings, they no longer appeared.
Update the message logic to use a slightly safer "reason" my original PR
added, and include the new reason.
> Bug 2097297: Show DNS lookup sampler problems on the disruption intervals chart.

- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/test.go
This allows the -f option for openshift-tests to work with specific
test suites instead of assuming the "files" test suite.
Background:
This change was first merged in this PR: https://github.com/openshift/origin/pull/27091
But that resulted in an issue where providing -f (or --file) without a test suite called `matchTestsFromFile` twice, which means the test file was getting parsed and matched twice. This may have contributed to [OOM errors in e2e-metal-ipi](https://search.ci.openshift.org/?search=Container+test+exited+with+code+1%2C+reason+OOMKilled&maxAge=48h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job).
The change was reverted here: https://github.com/openshift/origin/pull/27095
This PR reintroduces the original fix, with some refactoring …
> test: allow -f to match tests for any test suite (redux)

- test/extended/prometheus/prometheus.go
This changes removes all alert exceptions that have been fixed. It
ensures that no regression will happen for these alerts.
> test/extended/prometheus: clean alert exceptions

- test/extended/networking/egressip.go
- test/extended/networking/egressip_helpers.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
With https://bugzilla.redhat.com/show_bug.cgi?id=2070929 fixed, enable
EgressIP tests for internal targets.
How to test:
~~~
./openshift-tests run-test "[sig-network][Feature:EgressIP] [internal-targets] EgressIP pods should reach hostNetwork pods on other nodes [Skipped:azure] [Serial] [Suite:openshift/conformance/serial]"
~~~
Manually tested and passed on:  AWS/SDN, AWS/OVNKubernetes
Manually tested on Azure ovn/sdn where the test fails intermittently due to a known issue where Azure takes a long time to configure EgressIPs, even though the EgressIP status already shows as assigned to the node. Therefore, the test is disabled on Azure. 
The test is also disabled on GCP due to: https://bugzilla.redhat.com/show_bug.cgi?id=2104637
** NOTE: The vendor-update and e2e-images-update labels are …
> Bug 2098096: Enable EgressIP tests for internal targets

- e2echart/e2e-chart-template.html
- test/extended/testdata/bindata.go
These settings allow you to see more info on the right side of the charts vs. seeing the text squeezed with `...`.
View artifacts in the junit subdir for recent CI runs to see the results.  Note that there is no horizontal scroll bar so you have to widen your browser screen or shrink your font to see all the text in the right margin.
bindata.go is updated via "make update-bindata".
> Make margin wider to see more in spyglass charts

- pkg/monitor/api.go
- pkg/monitor/intervalcreation/types.go
- pkg/monitor/monitor.go
- pkg/monitor/monitor_cmd/command.go
- pkg/monitor/monitor_test.go
- pkg/monitor/types.go
- pkg/test/ginkgo/cmd_runsuite.go
- test/extended/util/disruption/backend_sampler_tester.go
separating the creation of the raw events from the calculated intervals allows us to later add more complicated interval collection without increasing the cost of getting just the raw events.
/assign @DennisPeriquet
> separate interval gathering from interval calculation

- test/extended/cli/explain.go
- test/extended/operators/operators.go
Reverts openshift/origin#27283, to be merged once metal images are being built again for 4.12.
/hold
> Revert "Bypass tests failing due to metal image rebuild on RHEL9"

- test/extended/networking/egressip.go
- test/extended/networking/egressip_helpers.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Reverts openshift/origin#27262
This test is not reliable enough. BZ is logged with details: https://bugzilla.redhat.com/show_bug.cgi?id=2107260. 
Passing rate is less than %60: https://sippy.dptools.openshift.org/sippy-ng/tests/4.12/analysis?test=%5Bsig-network%5D%5BFeature%3AEgressIP%5D%20%5Binternal-targets%5D%20EgressIP%20pods%20should%20reach%20hostNetwork%20pods%20on%20other%20nodes%20%5BSkipped%3Aazure%5D%5BSkipped%3Agce%5D%20%5BSerial%5D%20%5BSuite%3Aopenshift%2Fconformance%2Fserial%5D
We suggest fixing the issue described in the bug and reintroduce the test as flakes to collect some history before make it fail again.
> Revert "Enable EgressIP tests for internal targets"

- test/extended/ci/job_names.go
- test/extended/include.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
[TRT-391](https://issues.redhat.com//browse/TRT-391)
We want to make sure that all jobs indicate both their platform (unless
agnostic) and network type. This adds a flaking test case to help us
identify misconfigured jobs.
> Add test that checks CI job name matches platform and network type

- pkg/monitor/alerts.go
When fetching alerts from Thanos Query, we should first ensure that the
queriers are connected to all Prometheus sidecars. Otherwise the
returned data could have gaps which would fail the tests verifying that
the Watchdog alert has been always firing.
This is a second try after #27201 failed all single node jobs.
>  Bug 2079679: pkg/monitor: wait for Prometheus sidecars to be ready

- test/extended/networking/acl_audit_log.go
In OVN the default deny ACL naming was changed and thus the log line
will be different for the ACL name. This changes allows for both cases.
Signed-off-by: Tim Rozet <trozet@redhat.com>
> Fixes OVN ACL audit log parsing

- pkg/monitor/backenddisruption/disruption_backend_sampler.go
Believe the intention was to set bodyReadErr  in the bodyReadErr switch case
> Bug 2098194: set sampleErr to bodyReadErr

- test/extended/apiserver/apply.go
- test/extended/etcd/etcd_storage_path.go
- test/extended/etcd/etcd_test_runner.go
Etcd tests were using a static namespace name and were creating
a namespace with custom logic different but similar to the namespace
setup logic used everywhere else.
Move etcd storage tests to using the namespace created by the
machinery.
> etcd storage tests: work with dynamic namespace names

- test/extended/scheduling/pods.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
[TRT-395](https://issues.redhat.com//browse/TRT-395)
These two tests are showing as run twice always in testgrid, their name
was duplicated as they have two deployments we wanted to check.
> Fix same test name being used twice for pods on different nodes check.

- test/extended/apiserver/api_requests.go
We are seeing this fail quite a bit in CI at the moment, for example like in [this job](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.12-e2e-openstack-techpreview-serial/1551916732883406848).
This is happening on both [stable](https://search.ci.openshift.org/?search=operators+should+not+create+watch+channels+very+often&maxAge=336h&context=1&type=junit&name=openstack&excludeName=openstack-techpreview&maxMatches=5&maxBytes=20971520&groupBy=job) jobs and [tech preview](https://search.ci.openshift.org/?search=operators+should+not+create+watch+channels+very+often&maxAge=336h&context=1&type=junit&name=openstack-techpreview&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job) jobs.
I've had a look at the Cluster Monitoring …
> Increase API requests limit for monitoring operator on openstack

- go.mod
- test/extended/etcd/helpers/helpers.go
- test/extended/etcd/vertical_scaling.go
This PR increases the timeout for ensuring Machine phase is Running in the etcd vertical scaling test.
The node provisioning times observed on platforms like Azure range from 8-11 mins currently so this should help the test to not prematurely fail on those platforms.
<p><strong>Timeline for failed run:</strong><br /><a class="external-link" href="https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.12-e2e-azure-sdn-serial/1551552247274409984" target="_blank" rel="nofollow noopener">https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.12-e2e-azure-sdn-serial/1551552247274409984</a><br />&gt;&gt;&gt; Machine created</p>
<pre class="code panel" style="border-width: 1px;" …
> etcd vertical scaling test: add verbose timeout error messages and bump machine provisioning timeout for Azure

- test/extended/olm/olm.go
[Avoid][1]:
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.12-e2e-aws-sdn-no-capabilities/1554248054456979456
: [sig-operator] an end user can use OLM can subscribe to the operator [Skipped:Disconnected] [Suite:openshift/conformance/parallel] expand_more
{  fail [github.com/openshift/origin/test/extended/olm/olm.go:270]: Unexpected error:
<*json.SyntaxError | 0xc002396318>: {
msg: "unexpected end of JSON input",
Offset: 0,
}
unexpected end of JSON input
occurred
Ginkgo exit error 1: exit with code 1}
```
because the call returns an empty string, and not valid JSON, when the `enabledCapabilities` property is unset:
```console
$ oc get clusterversion version '-o=jsonpath={.status.capabilities}' …
```
> Bug 2114506: test/extended/olm: Handle unset enabledCapabilities in marketplaceEnabled

- test/extended/authorization/rbac/groups_default_rules.go
Problem: OLM has historically communicated to users which operators
are available in a given namespace by creating a copy of an operator
CSV in each namespace that it is scoped to. This has caused performance
issues on large clusters with many namespaces. OLM provided users with
the means to disable Copied CSVs for operators scoped to all namespaces,
but console was unable to communicate which operators were available
globally. Console will look for csvs in the openshift namespace to
identify which operators are available globally for authenticated users.
The authenticated user group needs read permissions to view the
CSVs in the openshift namespace. The extended e2e origin test suite has
a test that ensures that authenticated users do not have unanticipated
RBAC.
Solution: This commit …
> Update authenticated users RBAC e2e test

- test/extended/ci/job_names.go
The test that looks to see if job names match the network type needs to
exclude the repo name, otherwise we'll consider
pull-ci-openshift-ovn-kubernetes-master-e2e-hypershift to successfully
contain the -ovn- substring because the repo contains -ovn- in the name.
> Ignore repo name when looking for network type in job name

- test/e2e/upgrade/alert/alert.go
This should improve the pass rate on https://github.com/openshift/release/pull/31058 for z-stream upgrades.
> allow techpreviewnoupgrade alert when testing techpreview

- pkg/monitor/alerts.go
re: [TRT-412](https://issues.redhat.com//browse/TRT-412)
When the span exceeds about 3 hours (11,000 seconds), we can't use 1s interval for a range query because it will exceed the Prometheus max.
There's still the problem of a test running for a very long time but this change allows the alert tests to still run (by using an interval of at least 2 seconds).
> Consider Prometheus maximum points in a time series for alert tests

- test/extended/networking/acl_audit_log.go
f.Namespace does not actually represent the current and updated
object and so an UPDATE with such an object will cause removal
of the annotations/labels that, among others, set the PSa level
and auto-PSa label synchronization status.
/assign @openshift/networking
> networking/acl: live-retrieve the NS instead of f.Namespace

- test/extended/util/disruption/backend_sampler_tester.go
The backing logic moved to p99 in 8055267d5f (#26767).  Move to a less-opinionated function name locally, so we don't have to care about these distinctions.
> test/extended/util/disruption: Remove stale p95 references

- test/extended/testdata/bindata.go
- test/extended/testdata/cmd/hack/lib/init.sh
Currently `e2e-agnostic-cmd` jobs are failing due to pod security admission violation
error message. This PR adds required annotations into the namespace that tests run
to fix the error.
> Add required pod security admission annotations into cmd/namespace

- test/extended/ci/job_names.go
[TRT-484](https://issues.redhat.com//browse/TRT-484)
I put the check in the wrong place when I fixed this in
b99b9fc55565ef9e533efd8884b281411b9bcf80.
> job names: exclude text before `e2e` for both platform and network tests

- cmd/openshift-tests/images.go
- pkg/synthetictests/alerts.go
- pkg/synthetictests/allowedalerts/basic_alert.go
- pkg/synthetictests/allowedalerts/watchdog.go
- pkg/synthetictests/event_junits.go
- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/options_monitor_events.go
- pkg/test/ginkgo/synthentic_tests.go
Related to [TRT-238](https://issues.redhat.com//browse/TRT-238)
We look at information from tracked resources (pods and events) that can be used to tell if we should suppress an alert related failure.
The main logic is in `basic_alert.go`.  The rest of the code is about extracting the recorded resources from the `MonitorEventsOptions.recordedResources` field and plumbing that through to the new functions in basic_alert.go.
> Suppress failures if certain firing alerts happened with related event

- test/extended/networking/egressip.go
- test/extended/networking/egressip_helpers.go
Test with:
~~~
./openshift-tests run all --print-commands  | grep EgressIP | grep external | grep -v "Skipped:Network/OVNKubernetes" | while IFS= read -r line; do bash -c "$line" ; echo =========================; done
~~~
Signed-off-by: Andreas Karis <ak.karis@gmail.com>
> EgressIP: Enable EgressIP tests for OpenStack

- pkg/monitor/intervalcreation/rendering_per_namespace.go
Re: [TRT-475](https://issues.redhat.com//browse/TRT-475)
This adds the openshift-ovn-kubernetes namespace which will show the ovnkube-node pods.
> Add ovnkube-node pods in the interval chart for ingress

- cmd/openshift-tests/upgrade.go
- pkg/synthetictests/event_junits.go
- pkg/synthetictests/resource_growth.go
- test/e2e/upgrade/upgrade.go
- test/extended/prometheus/upgrade.go
From a recent regression we looked into whether or not we could catch
what happened in a build cluster, in CI runs. I found that when this bug
was in play, Secret totals would grow by about 60% during upgrade
(roughly 600), and once the change was reverted this was not the case.
As such this test attempts to check for no more than a percentage of
growth for resources that are quite numerous. (i.e. we don't care if a
10 resource count grows to 20), but we do care if a 100 grows to
800.
We are unsure if this will be feasible across all upgrade jobs.
Test uses an early check prior to launching upgrade suite to grab the counts in the cluster and store in a global. We then use an invariant test as this is in the same process and can access the initial counts. The invariant test uses cluster …
> Test we don't see substantial Secret/ConfigMap growth during upgrade.

- test/extended/etcd/helpers/helpers.go
Metal and vsphere platforms have been affected by the etcd scaling test. This will disable the test until it is moved to a separate job.
> Skip etcd scaling test for metal and vsphere platforms

- pkg/synthetictests/duplicated_events.go
- pkg/synthetictests/event_junits.go
- pkg/synthetictests/image_pulls.go
- pkg/synthetictests/image_pulls_test.go
Re: [TRT-488](https://issues.redhat.com//browse/TRT-488)
We want to handle a case like this:
```
: [sig-arch] events should not repeat pathologically
-- | --
{  2 events happened too frequently  event happened 24 times, something is wrong: ns/openshift-ovn-kubernetes service/ovn-kubernetes-master - reason/FailedToUpdateEndpointSlices Error updating Endpoint Slices for Service openshift-ovn-kubernetes/ovn-kubernetes-master: node "ip-10-0-168-211.us-east-2.compute.internal" not found event happened 24 times, something is wrong: ns/openshift-ovn-kubernetes service/ovnkube-db - reason/FailedToUpdateEndpointSlices Error updating Endpoint Slices for Service openshift-ovn-kubernetes/ovnkube-db: node "ip-10-0-168-211.us-east-2.compute.internal" not found}
```
which shows up in an event like this: …
> Separate out pathological event test for error updating endpoint slices

- test/extended/cloud_controller_manager/OWNERS
- test/extended/cloud_controller_manager/ccm.go
- test/extended/include.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
OpenStack platform is moving from in-tree cloud provider
to external one. The switch to external cloud provider has
to be done at the same time for the cluster cloud controller
manager operator and kube controller manager operator to avoid
the two providers being used in the cluster. Besides this the
machine config operator has to configure kubelet with external provider.
This commit includes a new test scenario to check that external provider
is properly configured for the needed operators.
> Ensures operators use external cloud provider

- test/extended/etcd/etcd_storage_path.go
Followup to https://github.com/openshift/origin/pull/27393
The recent failure is here: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1360/pull-ci-openshift-kubernetes-master-e2e-aws-serial/1566341037369069568
> Update etcd tests with k8s 1.25 data

- pkg/synthetictests/networking.go
Garbage collector tests dont care about pod being available/running, they are only testing owner references. If CNI is slow to respond the pod is deleted by the time it needs it, rendering warning events for a failure to create pod sandbox.
This PR removes checks for such events, as they might happen even when the test succeeds.
> Bug 2100091: Ignore FailedCreatePodSandBox events for garbage collector tests

- pkg/synthetictests/resource_growth.go
1100 runs, this hasn't flaked once, test appears reliable enough to hard
fail if it does happen.
[TRT-454](https://issues.redhat.com//browse/TRT-454)
> Remove flake for 40% Secret/ConfigMap growth test.

- pkg/synthetictests/duplicated_events.go
Skips events that are triggered by the build tests: https://search.ci.openshift.org/?search=ns%2Fopenshift-route-controller-manager+deployment%2Froute-controller-manager&maxAge=336h&context=1&type=junit&name=pull-ci-openshift-origin-master-e2e-gcp-builds&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job 
more background in relevant issues: 
- https://issues.redhat.com/browse/BUILD-495
- https://bugzilla.redhat.com/show_bug.cgi?id=2034984
> skip route-controller-manager scaling events in build testsuite

- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/group_filter.go
- pkg/test/ginkgo/status.go
- pkg/test/ginkgo/test.go
Excluding tests with [apigroup:GROUP] labels for apigroups which are not served by a cluster. E.g. MicroShift is not serving most of the openshift.io apigroups. Other installations might be serving only a subset of the api groups.
jira: https://issues.redhat.com/browse/WRKLDS-488
> Automatically skip tests with apigroups which are not served

- pkg/synthetictests/duplicated_events_special.go
- pkg/synthetictests/duplicated_events_special_test.go
Alternative to https://github.com/openshift/origin/pull/27403
This adds logic to the broken out duplicated event slices for a "flake-only" option when failure threshold is set to -1, and does so for this test case while the networking team works on a fix upstream.
This also renames the file away from image_pulls.go as it now has broken out cases for other events.
> OCPBUGS-587: Temporarily flake FailedToUpdateEndpointSlices

- pkg/monitor/alerts.go
Re: [TRT-504](https://issues.redhat.com//browse/TRT-504)
Followup to [PR27319](https://github.com/openshift/origin/pull/27319/files) where we set the resolution down to 2 seconds from 1 for tests that exceed 3 hours.  There were two places to change and I only caught one at the time; this [test failure](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.12-e2e-aws-sdn-serial/1564469492770148352) found the other.
```
Suite run returned error: AlertErr: bad_data: exceeded maximum resolution of 11,000 points per timeseries. Try decreasing the query resolution (?step=XX)
```
> Address exceeded maximum resolution of 11,000 points per timeseries

- test/extended/testdata/bindata.go
- test/extended/testdata/builds/s2i-environment-build-app/Gemfile
This test is failing in CI:
```
[sig-builds][Feature:Builds][Slow] s2i build with environment file in
sources Building from a template should create a image from
"test-env-build.json" template and run it in a pod
[apigroup:build.openshift.io][apigroup:image.openshift.io]
```
The error output from the container is:
```
2022-09-13 09:52:05	       Add rack to your Gemfile in order to start the web server.
2022-09-13 09:52:05	 ERROR: Rubygem Rack is not installed in the present image.
2022-09-13 09:52:05	 You might consider adding 'puma' into your Gemfile.
```
This is coming from https://github.com/sclorg/s2i-ruby-container/blob/master/2.2/s2i/bin/assemble#L52, which is trying to execute `rackup`.
In https://github.com/rack/rack/pull/1937, rackup was moved to a different gem.
This adds …
> OCPBUGS-1237: Fix s2i ruby test that relys on rack

- test/extended/ci/job_names.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
[TRT-541](https://issues.redhat.com//browse/TRT-541)
We have at least one case of a job saying it's 4.11 but actually deploying 4.12. I don't think we can get a perfect test to cover this, but for periodics we can at least check that if a job name mentions a version, that exists in the cluster version history.
There are jobs that mention versions that aren't openshift which will be problematic, but this is just flaking for now until we figure out how to deal with those.
> Add a test case to find job name/cluster version mismatches

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
> OCPBUGS-967: temporarily disable IngressClass test, which is changed in upstream in 1.25

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
We support ITP=local from 4.11 so let's enable the tests
for this feature which were disabled.
Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>
> Enable ServiceInternalTrafficPolicy tests in OVNK

- test/extended/util/ldap.go
In OCPBUGS-1053 we see failures from the runonce-ldapsearch-pod trying to verify the server is active.  
The server pod indicates it is active
`openldap-server-6dbdf9dbbd-wjzfm  ip-10-0-167-146.us-east-2.compute.internal  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2022-09-12 18:11:40 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2022-09-12 18:11:48 +0000 UTC  } {ContainersReady True 0001-01-01 00:00:00 +0000 UTC 2022-09-12 18:11:48 +0000 UTC  }`
So we are adding a retry loop to try again / see if the error is persistent or not
> add retry for checkLADPConn

- test/extended/apiserver/api_requests.go
Found in:
- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-kubernetes-1360-nightly-4.12-e2e-vsphere-ovn-techpreview-serial/1572344489270317056 
- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-kubernetes-1360-nightly-4.12-e2e-vsphere-ovn-serial/1572344487600984064
> Bump api-requests for console-operator on vsphere

- test/extended/util/client.go
- test/extended/util/framework.go
- test/extended/util/oc_copy.go
Swaps project API with k8s namespaces in test/extended/util package. Automatic detection of project API to create a CLI object according to whats available in the cluster.
> USHIFT-285: MicroShift: allow CLI creation without OpenShift APIs

- test/extended/images/imagestream_admission.go
Details in TRT-577. Essentially we bump the limit from 0 to 1,
immediately try to create an ImageStream expecting it to pass, but get
rejected as the old limit of 0 appears to still be in effect.
There is no observed Status on LimitRange to wait for, so I think the
best we can do here is a sleep.
> Fix rare race condition in ImageStream admission tests.

- test/extended/builds/build_pruning.go
- test/extended/builds/new_app.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Builds API is not available in microshift.
Closes [USHIFT-283](https://issues.redhat.com//browse/USHIFT-283)
> USHIFT-283: microshift: skip sig-builds tests

- pkg/test/ginkgo/cmd_runsuite.go
This pull request is intends to address https://github.com/openshift/origin/issues/27350 .  It appears that when https://github.com/openshift/origin/commit/a42d174f9f93110da7b1863d58ab7a21fd056513 was introduced, the storage and must-gather test counts were omitted from the expected test count.
> include storage and must-gather tests in expectedTestCount

- cmd/openshift-tests/provider.go
- test/extended/util/test.go
Every now and then we get catastrophic runs where hundreds of tests fail with this error:
```
error: stat /tmp/kubeconfig-2448219175: no such file or directory
```
Example run at [1].
Typically we use the `KUBECONFIG` from a read-only mounted secret. However there is code in `initializeTestFramework` that causes this temp file to be created in certain cases. The file is written by a vendored kube function, which does this because the context it's given doesn't specify any `KUBECONFIG` so it gets one via a service account.  By setting it in the context, we can avoid writing one to /tmp.
The benefit to this is the secret is mounted read only, so it shouldn't be modifiable or removable.  I dug around and I cannot figure *what* exactly caused the /tmp/kubeconfig- to be deleted, but I am …
> OCPBUGS-1079: Use kubeconfig from secret mount instead of /tmp

- test/extended/networking/egressip_helpers.go
Avoids curl hanging and preventing:
- the test to be tear down up properly, making follow up tests to fail
- the retry mechanism in place from happening
Signed-off-by: Jaime Caamaño Ruiz <jcaamano@redhat.com>
> egressip: avoid curl hanging when sending probes

- test/extended/util/disruption/frontends/frontends.go
Recent 4.8 to 4.9 upgrade tests fail fairly consistently due to cluster frontend ingress being unavailable. Currently the upgrade test tolerates no disruption whatsoever. This PR makes the test more lenient, allowing 2.5% disruption, which is the minimum that would have resulted in passes for the string of recent failures.
Note for reviewer: this is outside my typical domain, so if there's a more targeted fix we could make (e.g. do this only on AWS upgrades), or we think its worth root-causing and/or adding a link in the test output to help our future selves understand this decision, let me know what's appropriate.
Signed-off-by: Joe Lanford <joe.lanford@gmail.com>
> OCPBUGS-1052: allow frontends to tolerate 2.5% disruption during upgrades

- pkg/synthetictests/disruption.go
- pkg/synthetictests/historicaldata/types.go
Our operating assumption was that we were only enforcing disruption
using P99 values, thus would expect to only fail 1% of jobs, and if you
violate that test then you likely have regressed.
We have discovered that the vast majority of job platform combinations
do not have the 100 minimum runs required to get a P99, and thus we're
actually failing jobs on as low as P50's, which causes very erratic
failures and retests.
We are now limiting the data going into the historical
query_results.json in openshift/ci-tools repo. Here we now assume that
if we do not have disruption data for the platform under test, we flake
and report why. Previously this was a failure. The flake will allow us
to find instances where this is occurring if anyone needs to.
OCPBUGS-1459 …
> Drastically reduce the jobs we enforce disruption on.

- pkg/monitor/write_job_run_data.go
- pkg/monitor/write_job_run_data_test.go
[TRT-584](https://issues.redhat.com//browse/TRT-584)
Not including info events caused 0s disruptions to disappear in the
reported data and bigquery since Jun 15. Broken in #27250.
In original PR I needed a way to classify DNS lookup failures as something other than disruption of the ephemeral cluster under test. We still wanted to track these failures, so I used the level of the interval event to do so moving these to a Warning, and leaving what we think is real disruption as Error. I updated the code to filter out the Warnings in appropriate places by just picking up Errors. I was unaware there were actually no disruption intervals at level Info, these then began being omitted in the backend-disruption json files and thus never making it into bigquery.
> Fix missing reporting of 0s disruptions.

- pkg/synthetictests/duplicated_events.go
- pkg/synthetictests/event_junits.go
- pkg/synthetictests/kubelet.go
Related to https://issues.redhat.com/browse/TRT-566
Looking for events like this on openshift-config-operator pods:
```
{
"level": "Info",
"locator": "ns/openshift-config-operator pod/openshift-config-operator-6fb5684645-wx5bt uid/b7869874-df1a-4ecc-bada-59fa9c7d5e64 container/openshift-config-operator",
"message": "constructed/true reason/ReadinessFailed Get \"https://10.130.0.16:8443/healthz\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)",
"from": "2022-08-29T10:41:23Z",
"to": "2022-08-29T10:41:24Z"
}
```
I also augmented the ReadinessFailed and ReadinessErrored messages with the timestamp so I don't have to search an events.json file to get the timestamp when looking at the failure output in the prow job.
If the failure …
> Add Invariant test to look for probe errors for openshift-config-operator

- test/extended/util/cluster/cluster.go
- test/extended/util/disruption/frontends/known_backends.go
Adds new utilities to check for enabled and known capabilities. Check
also assumes that if the cluster doesn't know about the console
capability, it predates 4.12 and thus we should assume to do monitoring
for console as it was default then.
The test should then see no ingress- backends for console, and not fail.
[TRT-573](https://issues.redhat.com//browse/TRT-573)
> Check for console capability before launching it's disruption monitoring.

- cmd/openshift-tests/e2e.go
- test/extended/etcd/helpers/helpers.go
- test/extended/etcd/vertical_scaling.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Reverts #openshift/origin#27444 ; tracked by OCPBUGS-2155
Per TRT policy, we are reverting this breaking change to get ci and/or nightly payloads flowing again. This change made this test run in `[Suite:openshift/conformance/parallel]` instead of the intended new etcd suite. It's causing jobs to fail, so I'm going to have to revert this change.
To unrevert this revert, revert this PR, and layer an additional separate commit on top that addresses the problem, and ensure the test does not run in either serial or parallel conformance runs.
CC: @hasbro17
> OCPBUGS-2155: Revert "Add etcd vertical scaling test suite"

- pkg/synthetictests/allowedbackenddisruption/matches.go
After checking, I think this is the minimal change to disable disruption on prior releases.  We can try to remove all the code, but I think this allows us to retain data collection (such as it is), while disabling test failures.
> disruption checking is disabled for prior releases because we lack a good baseline

- pkg/synthetictests/duplicated_events.go
after a recent change of OCM being managed by a deployment instead of a daemonset: https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/264
similar change was done in RCM as well: https://github.com/openshift/origin/pull/27394
was caught for example here: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_openshift-controller-manager/242/pull-ci-openshift-openshift-controller-manager-master-e2e-gcp-builds/1582378124010590208
> update skip openshift-controller-manager scaling events in build testsuite

- cmd/openshift-tests/e2e.go
- pkg/monitor/intervalcreation/rendering_per_namespace.go
- pkg/monitor/monitor.go
- pkg/synthetictests/allowedalerts/basic_alert.go
- pkg/synthetictests/allowedalerts/types.go
- pkg/synthetictests/duplicated_events_special.go
- test/e2e/upgrade/upgrade.go
- test/extended/authorization/scopes.go
- test/extended/cli/admin.go
- test/extended/cli/project.go
- test/extended/etcd/helpers/helpers.go
- test/extended/images/oc_copy.go
- test/extended/templates/helpers.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/disruption/disruption.go
- test/extended/util/docker.go
- test/extended/util/framework.go
- test/extended/util/image_helpers.go
- test/extended/util/oauthserver/oauthserver.go
- test/extended/util/test.go
- tools/junitreport/pkg/parser/stack/parser.go
This PR adds;
- proper project cleanup in `oc adm storage-admin`, `oc adm new-project` tests.
These tests are precisely failing in second run, because projects which
trying to be created are already existed.
- moving  `oc project can switch between different projects` to serial suite.
Because `oc new-project` without `--skip-config-write` flag can make changes on
global kubeconfig and might cause other tests fail. We can not use `skip-config-write`
flag, since all purpose of this test is testing actual `new-project`. Therefore,
this test can be better run in serial suite(more detail https://github.com/openshift/origin/pull/26610).
> Fix flaky cli tests

- test/extended/networking/egressip.go
- test/extended/util/client.go
- test/extended/util/disruption/frontends/known_backends.go
- test/extended/util/framework.go
When https://github.com/openshift/origin/pull/27460 was introduced the tests in MicroShift stopped working because of checking `clusterversion.config.openshift.io`. Since this API group/resource is not available in MicroShift, we need to skip it.
/cc @dgoodwin
> microshift: avoid oauth and console disruption monitoring

- test/extended/pods/priorityclasses.go
must-gather pod was added exception list because `oc debug node` does not include priorityClassName. After this PR [openshift/oc/pull/1263](https://github.com/openshift/oc/pull/1263) adds priorityClassName statically, we can remove must-gather pod from priorityclass exception list.
> Remove must-gather pod from lack priorityclass exception list

- test/extended/security/scc.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/client.go
Duplicate existing `TestPodUpdateSCCEnforcement` and `TestAllowedSCCViaRBAC` e2e tests with their corresponding service account equivalents to drop api group dependency on `apigroup:user.openshift.io` and `apigroup:authorization.openshift.io`.
> Extend SCC tests with their corresponding service account variants

- cmd/openshift-tests/openshift-tests.go
- pkg/riskanalysis/cmd.go
- pkg/riskanalysis/types.go
- pkg/riskanalysis/write_test_failure_summary.go
- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/cmd_runtest.go
- pkg/test/ginkgo/junit.go
- pkg/test/ginkgo/options_monitor_events.go
- pkg/test/ginkgo/test_failure_summary.go
This change begins writing out a brief test failure summary artifact in a format that is logical and also deserializable by sippy.
It also adds a new sub-command that can be used to merge several of these files, submit them to sippy, and write the resulting risk analysis to the artifacts directory.
Requires https://github.com/openshift/sippy/pull/657
[TRT-602](https://issues.redhat.com//browse/TRT-602)
> Write test failure summary, and add new command to request failure risk analysis from sippy.

- pkg/monitor/resourcewatch/cmd/resourcewatch.go
- pkg/monitor/resourcewatch/controller/clusteroperatormetric/controller.go
- pkg/monitor/resourcewatch/controller/configmonitor/crd_controller.go
- pkg/monitor/resourcewatch/operator/starter.go
- pkg/monitor/resourcewatch/storage/git_store.go
This is mainly port of code from https://github.com/dgoodwin/origin/tree/observer-rw to add more resources to watch. 
[TRT-469](https://issues.redhat.com/browse/TRT-469)
> Add more resource to watch

- cmd/openshift-tests/openshift-tests.go
- pkg/monitor/cmd.go
This is in preparation for using run monitor as CI observer. 
[TRT-469](https://issues.redhat.com/browse/TRT-469)
> Store monitor events in artifact directory at the end of run monitor

- test/extended/scheduling/pods.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This was causing the test to be skipped:
: [sig-scheduling][Early] The openshift-console console pods [apigroup:console.openshift.io should be scheduled on different nodes [Suite:openshift/conformance/parallel]
Reason: skipped because the following required API groups are missing: console.openshift.io should be scheduled on different nodes [Suite:openshift/conformance/parallel
> OCPBUGS-3282: Fix apigroup tag missing closing brace.

- cmd/openshift-tests/e2e.go
- test/extended/etcd/helpers/helpers.go
- test/extended/etcd/vertical_scaling.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
I had to revert https://github.com/openshift/origin/pull/27463 because the etcd tes was mistakenly running in all parallel conformance jobs.  In order to make this test only part of the etcd scaling test, we need to mark it so -- but this requires a change to openshift/kubernetes to allow that behavior.
> Unrevert etcd vertical scaling test

- pkg/monitor/monitorapi/identification.go
- pkg/monitor/monitorapi/types.go
- pkg/synthetictests/allowedalerts/basic_alert.go
I think this does what I mentioned.  It doesn't address the test variant in https://github.com/openshift/origin/blob/master/test/extended/prometheus/alerts.go#L24 .  Do we still need to actually run that test or do we only use it to properly wire ignores?
/assign @dgoodwin @neisw
> ignore kubepodnotready alerts firing when it happens during node upgrade

- pkg/monitor/intervalcreation/node.go
- pkg/monitor/intervalcreation/node_test.go
- pkg/synthetictests/event_junits.go
- pkg/synthetictests/kubelet.go
Adds support for extracting `http2: client connection lost` errors from kubelet logs
> Trt 579 http2 connection lost

- e2echart/test-risk-analysis.html
- pkg/riskanalysis/cmd.go
- test/extended/testdata/bindata.go
[TRT-644](https://issues.redhat.com/browse/TRT-644)
> Add test risk analysis html for spyglass

- test/extended/idling/idling.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
> OCPBUGSM-35025: reenable unidling ci tests

- pkg/synthetictests/apiserver.go
- pkg/synthetictests/duplicated_events.go
- pkg/synthetictests/event_junits.go
- pkg/synthetictests/kubelet.go
- pkg/synthetictests/node.go
Re: [TRT-596](https://issues.redhat.com//browse/TRT-596)
For the `[sig-arch] events should not repeat pathologically` test,
* create 6 new flaking tests to separate out ProbeError tests for openshift-config-operator and openshift-oauth-apiserver
* create 3 new flaking tests to separate out the NodeHasNoDiskPressure, NodeHasSufficientMemory, and NodeHasSufficientPID events
> Separate out more tests from 'events should not repeat pathologically' test

- test/extended/util/client.go
errors like 
```
fail [github.com/openshift/origin/test/extended/deployments/deployments.go:1002]: Unexpected error:
<*exec.ExitError | 0xc00154c560>: {
ProcessState: {
pid: 67978,
status: 256,
rusage: {
Utime: {Sec: 0, Usec: 120054},
Stime: {Sec: 0, Usec: 33352},
Maxrss: 230984,
Ixrss: 0,
Idrss: 0,
Isrss: 0,
Minflt: 3216,
Majflt: 0,
Nswap: 0,
Inblock: 0,
Oublock: 0,
Msgsnd: 0,
Msgrcv: 0,
Nsignals: 0,
Nvcsw: 511,
Nivcsw: 10,
},
},
Stderr: nil,
}
exit status 1
```
are really hard to read,  this should change it to be something more like
```
Error running /usr/bin/oc --namespace=e2e-test-cli-deployment-7kgkc --kubeconfig=/tmp/configfile4230829623 set env dc/history-limit A=9:
StdOut>
Unable to connect to the server: dial tcp 34.170.77.45:6443: i/o timeout
StdErr>
Unable to connect to the …
```
> make command errors easier to read

- test/extended/image_ecosystem/s2i_images.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>
> Nginx 1.18 images will reach EOL in November 2022

- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/junit.go
In PR #27516 we suspect reporting of flakes broke due to a missed
assumption that test.flake accompanied test.success. Our new goal is to
more clearly have just one status set, so we're going to lean into the
new approach and properly break out the flake state into it's own case.
> OCPBUGS-3633: Fix flake reporting for certain tests.

- pkg/alerts/allowed_conformance.go
- pkg/alerts/allowed_upgrade.go
- pkg/alerts/check.go
- test/e2e/upgrade/alert/alert.go
- test/extended/operators/images.go
- test/extended/operators/operators.go
- test/extended/prometheus/prometheus.go
- test/extended/util/conditions.go
TRT has decided with input from @deads2k that we're ok with moving the generic alert backstop tests to always flake, as the signal is not as high value. The post-upgrade alert test fails 30% of the time globally, and the post-conformance variant is also not stellar, and both disproportionately affect certain NURPs.
In sippy as of https://github.com/openshift/sippy/pull/685 we will begin tracking the reasons this test is flaking in the db by storing metadata about what alerts fired, so we'll have good insight into what may be causing issues, provided somebody remembers to look.
PR also re-introduces the refactor to merge the two backstop alert tests into a common code path, which they once were forked from. We thought this caused a regression, turned out it was something else, so this …
> Flake and improve alert tests

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
This test was introduced in k8s v1.24 and disabled here because it was pulling an image from a hardcoded registry.
Since this has been fixed in upstream and landed here through the 1.25 rebase [1], reenable it.
[1] https://github.com/openshift/origin/pull/27526
> Bug 2093339: Reenable data source test

- pkg/synthetictests/networking.go
Kuryr can take long to create Pods as it needs to create ports for these pods in Neutron. If a pod gets deleted while this is being processed, a warning Event will be generated. This causes the `[sig-network] pods should successfully create sandboxes by adding pod to network` to fail.
This commit adds this case as a flake.
> Add Kuryr exception to "pods should successfully create sandboxes" test

- pkg/riskanalysis/cmd.go
- pkg/riskanalysis/types.go
- pkg/riskanalysis/write_test_failure_summary.go
Include the total test count so we can compare against previous runs and detect missing tests in cases like failed installs / upgrades, etc.
On the Sippy side adding:
```
type ProwJob struct {
gorm.Model
Kind        ProwKind
Name        string         `gorm:"unique"`
Release     string         `gorm:"varchar(10)"`
Variants    pq.StringArray `gorm:"index;type:text[]"`
TestGridURL string
Bugs        []Bug        `gorm:"many2many:bug_jobs;"`
JobRuns     []ProwJobRun `gorm:"constraint:OnDelete:CASCADE;"`
TestCount   int			 `gorm:"-"`
}
```
So we can pass the value via struct but not store in db.  Can make that a request parameter if desired.
> TRT-662: include test count totals for analysis

- test/extended/networking/bonds.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
API group k8s.cni.cncf.io is not installed.
Pending JIRA ticket.
> USHIFT-658: ushift: skip networking bond interface tests

- test/extended/cli/explain.go
Fix loop variable capture in closure for `g.It`, as it currently fails randomly because `group`, `bts` and `sts` variables are getting overwritten values for all `g.It` functions in the loop.
As an example, this run mismatches api resources with the api groups they belong to: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-microshift-main-periodic-ocp-4.12-conformance-parallel/1593357119778721792
> USHIFT-647: ushift: fix loop variable capture in sig-cli

- test/extended/util/disruption/disruption.go
> Remove redundant messages that might contain non-xml charactor

- test/extended/baremetal/common.go
- test/extended/baremetal/hosts.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Metal3 pods can now be deployed on AWS platform.
Baremetal hosts can be booted only via virtual media. We only check for the presence of the metal3 pod to verify the baremetal deployment is available in AWS too.
> Allow baremetal tests to run on AWS platform

- test/extended/apiserver/api_requests.go
1.12983275498735 is not particularly relevant, round to two decimal
places instead.
> Round the ratio for excessive watch requests test

- test/extended/util/disruption/backend_sampler_tester.go
Test for allowedDisruption duration early in test and skip
if not present.
-- old
Returning nil (when no historical data is present) causes a nil pointer dereference in "Image registry" disruption tests expecting a value.
> OCPBUGS-4190: 1sec

- pkg/synthetictests/duplicated_events.go
- pkg/synthetictests/duplicated_events_special.go
- pkg/synthetictests/event_junits.go
- pkg/synthetictests/marketplace.go
[TRT-702](https://issues.redhat.com//browse/TRT-702)
OCPBUGS-1152
Separate out "startupProbe failed" messages from pathological events test for community-operators and redhat-operators pods in openshift-marketplace namespace.
> Separate out "startupProbe failed" messages from pathological events test

- test/extended/networking/OWNERS
I don't know if I have the rights to open this PR (I normally don't do these kind of PRs), but currently we don't have very many on the OVNK-origin side who can approve things including our team lead :) So thought of adding Tim to the list so that we can get some test PRs approved within the team.
/cc @dcbw @knobunc  for approval.
> Add trozet to networking approvers

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Unskipping all the session affinity conformance tests for OVNK.
> OCPBUGS-4502: Unskip service session affinity tests

- pkg/alerts/check.go
- test/extended/util/disruption/disruption.go
While investigating why some tests were failing in spyglass, but not present in risk analysis, I discovered this second location where we output junit files (most notably the upgrade junit files) using test suites, which was not updated to also output the test failure summary we use for risk analysis.
Digging further I saw that this path of code was using a totally different representation of testsuite/testcase than everything else in origin (k8s TestSuite vs our ginko JUnitTestSuite). It would have been easier just to write another function to pull the test failures out of this, but I opted to get them both using the same objects as there were other subtle differences in the XML that made me nervous.
To validate I've compared junit_upgrade output from the aws-ovn-upgrade job with an …
> TRT-703: Fix upgrade junit results not present in risk analysis

- test/extended/cli/policy.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This PR adds new tests for `oc policy scc-subject-review` and `oc policy scc-review`
commands. Since these commands are heavily relying on `oc login` command([ref](https://github.com/openshift/origin/blob/c1be83275d48902c0fbec5e1f7a39657b3b35f17/test/extended/testdata/cmd/test/cmd/policy.sh#L196-L240)) and
in test suite, managing `oc login` needs an extra caution, this PR adds some basic tests
at least providing a coverage bigger than zero.
> Add tests for oc scc-subject-review and scc-review commands

- test/extended/cli/status.go
Currently, `oc status` test creates job resource and does not clean it after test is completed.
This PR adds clean up function to prevent any resource leakages.
> OCPBUGS-4731: oc status: clean job resource to prevent leaks

- test/extended/cli/explain.go
- test/extended/networking/egressip.go
- test/extended/util/client.go
- test/extended/util/disruption/frontends/known_backends.go
- test/extended/util/framework.go
When using DoesApiResourceExist function from framework we might get false positives if there are two resources with the same name but difference API group. This change checks the API group (not version) with the resource name too in order to remove ambiguity.
> Remove ambiguity when checking for api resources existence

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
In preparation for kube 1.26 rebase.
> OpenStack: Skip in-tree cinder provisioner tests

- test/extended/dns/dns.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
[NE-1068](https://issues.redhat.com//browse/NE-1068): Add test using chaos plugin to detect local DNS endpoint preference.
New test that uses a chaos query to detect which DNS pod respond will attempt a chaos request multiple times and verify all requests are answered by the local DNS endpoint. Regardless of SDN type, this should always pass.
This is being added due to a regression in which the local DNS endpoint preference broke in 4.11/4.12 https://issues.redhat.com/browse/OCPBUGS-488.
> NE-1068: Add test using chaos plugin to detect local DNS endpoint preference.

- pkg/monitor/intervalcreation/node_test.go
Currently intervalcreation unit tests assures that the dates with static year(2022) however, logs generated are now in 2023.
This PR fixes that.
> Fix intervalcreation incorrect year unit test bug

- test/extended/images/oc_tag.go
This PR uses suggested `create token` command instead of `serviceaccount new-token` command as stated in the TODO.
> Use create token instead serviceaccounts token command

- test/extended/networking/bonds.go
The bond CNI test creates a macvlan interface that inherits its mtu from the hosts default gw nic.
Configure bond NAD config with mtu set to ClusterNetworkMTU which is not going to be higher than the hosts MTU.
Fixes https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/1663/pull-ci-openshift-cluster-network-operator-release-4.12-e2e-network-mtu-migration-sdn-ipv4/1609870734950141952 where the host MTU is set to 1260.
/assign @mmirecki 
Signed-off-by: Patryk Diak <pdiak@redhat.com>
> Use cluster network MTU for bond interfaces

- e2echart/e2e-chart-template.html
- pkg/monitor/intervalcreation/node.go
- pkg/monitor/monitorapi/identification_pod.go
- test/extended/testdata/bindata.go
[TRT-724](https://issues.redhat.com//browse/TRT-724)
The kubelet logs contain the startup probe errors.  We extract them (similar to how the readiness probe events were extracted) so they will be represented in the event Intervals and the Interval charts.
Sample output:
* Startup probes occur just before a container goes to `Ready` state.  You can see them in this [chart](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/27612/pull-ci-openshift-origin-master-e2e-aws-ovn-fips/1603377226177318912/artifacts/e2e-aws-ovn-fips/openshift-e2e-test/artifacts/junit/e2e-timelines_openshift-support-stuff_20221215-140123.html) for pods (e.g., `redhat-operators-5nk4h`) that are in the `openshift-marketplace` namespace.
* For the [node …
> Add Event intervals for Startup Probe failures

- test/extended/cli/template.go
- test/extended/testdata/bindata.go
- test/extended/testdata/cmd/test/cmd/templates.sh
- test/extended/util/annotate/generated/zz_generated.annotations.go
This PR adds new serial suite test in order to verify template processing via `oc process` between different namespaces are working correctly. This test will not work in Disconnected environments because it requires accessing registry images. This test is in serial suite instead of parallel, because it creates temporary user and logins with that by making changes on kubeconfig.
Some steps of test will fail until https://github.com/openshift/oc/pull/1318 is merged.
> Add tests for template cross namespace processing

- test/extended/util/disruption/backend_sampler_tester.go
Discovered that we are getting no data for image registry since Dec 7th
due to PR #27574 which shut off the entire monitor if we have less than
the required 100 runs to appear in the file of allowances to enforce. I
guess at this time, we did not have enough runs with image registry for
4.13. (which is unusual)
Skip the test, but let the monitor run.
[TRT-760](https://issues.redhat.com//browse/TRT-760)
> Fix missing disruption uploads.

- test/extended/util/disruption/backend_sampler_tester.go
- test/extended/util/disruption/disruption.go
Previous attempt did not work, as we were still bypassing
FrameworkEventIntervals() which is needed to add the test summary, which
eventually results in the AdditionalEvents json files in artifacts,
which are then merged into the overall events and disruption data files.
Without calling it, we still get no disruption data uploaded.
Move the nil check into the ExpectNoDisruption function, and allow
FrameworkEventIntervals to run as it should.
[TRT-760](https://issues.redhat.com//browse/TRT-760)
> Fix missing disruption data again.

- test/extended/router/config_manager.go
- test/extended/router/subdomain.go
- test/extended/router/unprivileged.go
- test/extended/router/weighted.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
FindRouterImage was refactored to fall back to checking router-default deployment
> WRKLDS-605: Remove dependency on some router tests on config.openshift.io api group

- test/e2e/upgrade/adminack/adminack.go
- test/extended/util/openshift/clusterversionoperator/adminack.go
While looking into OCPBUGS-5505 I discovered that some 4.10->4.11
upgrade job runs perform an Admin Ack check, while some do not. 4.11 has
a `ack-4.11-kube-1.25-api-removals-in-4.12` gate, so these upgrade jobs
sometimes test that `Upgradeable` goes `false` after the ugprade, and
sometimes they do not. This is only determined by the polling race
condition: the check is executed once per 10 minutes, and we cancel the
polling after upgrade is completed. This means that in some cases we are
lucky and manage to run one check before the cancel, and sometimes we
are not and only check while still on the base version.
Example job that checked admin acks post-upgrade:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-cluster-version-operator-880-ci-4.11-upgrade-from-stable-4.10-e …
> upgrade/adminack: guarantee one admin ack check post-upgrade

- test/extended/dns/dns.go
[sig-network-edge] DNS should answer queries using the local DNS 
endpoint [Suite:openshift/conformance/parallel] tests is perma failing for heteroenegeneous due to missing manifest list support for image registry.
Assigning the dns pod to master to avoid deploying to the incorrect node and fixing issue for  `exec format error`
> OCPBUGS-5506: DNS pod to be created on master node

- pkg/test/ginkgo/cmd_runsuite.go
[TRT-747](https://issues.redhat.com//browse/TRT-747)
If a test fails once and then gets retried, and then the second attempt skips the test, there's a high likelihood the original run was a precondition check failure and we should just omit the original failure.
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-origin-27652-ci-4.13-upgrade-from-stable-4.12-e2e-azure-sdn-upgrade/1613252620154048512 shows a run where I simulated the failure + skip case.
Failure:
```
18182-fail [github.com/openshift/origin/test/extended/networking/util.go:459]: Jan 11 22:30:12.737: Oh no I failed
18183-Ginkgo exit error 1: exit with code 1
18184-
18185:failed: (5.4s) 2023-01-11T22:30:13 "[sig-network] network isolation when using a plugin in a mode that does not isolate namespaces by …
```
> Don't emit failure junit testcase when a retry is skipped

- test/extended/router/config_manager.go
- test/extended/router/subdomain.go
- test/extended/router/unprivileged.go
- test/extended/router/weighted.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This reverts commit 075473cfd82afd92dcc31066f59ec96f2d67b39b.
Per [TRT policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get ci and/or nightly payloads flowing again.
This change broke metal-ipi-ovn-ipv6 and the last 4 4.13 payloads, which is a disconnected job, example: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-ovn-ipv6/1614182397866151936
This test should not actually be running on this job, I believe what happened is that in https://github.com/openshift/origin/blob/master/test/extended/util/annotate/rules.go#L274 we determine whether or not to add the [SKipped:Disconnected] tag based on test name, …
> Revert "Remove dependency on some router tests on config.openshift.io api group"

- test/extended/dns/dns.go
Introduced here https://github.com/openshift/origin/pull/27650
Failure example https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/1474/pull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi-ovn-dualstack/1614322843753910272
Original PR only intended to add new fields to the pod.Spec, and not delete RestartPolicy and SecurityContext
@deepsm007 @trozet @kyrtapz
> Fix nil pointer dereference for createDNSPod.

- pkg/synthetictests/duplicated_events.go
Kube 1.26 introduced the warning level `TopologyAwareHintsDisabled` event. `TopologyAwareHintsDisabled` is fired by the `EndpointSliceController` whenever reconciling a service that has activated topology aware hints via the `service.kubernetes.io/topology-aware-hints` annotation, but there is not enough information cluster resources (typically nodes) to apply the topology aware hints. 
The `service.kubernetes.io/topology-aware-hints=auto` annotation [was added to the `dns-default` service](https://bugzilla.redhat.com/show_bug.cgi?id=2095941) to make it topology aware when using third party CNI plugins that support that feature.
Unfortunately, the OpenShift CNI plugins (sdn & ovn) do not support the topology-aware feature, so we now see these `TopologyAwareHintsDisabled` events during …
> ignore repeated TopologyAwareHintsDisabled events

- pkg/synthetictests/duplicated_events.go
- pkg/synthetictests/duplicated_events_test.go
[TRT-687](https://issues.redhat.com/browse/TRT-687)
Some event messages are multiple line. But all of our analysis focus on only the first line. This PR adds the result tag to the end the first line of the event message.
> Add result tag to the end of first line of an event message

- test/extended/etcd/helpers/helpers.go
- test/extended/etcd/vertical_scaling.go
Resolves: https://issues.redhat.com/browse/ETCD-329
The vertical scaling test workflow needs to account for the presence of the ControlPlaneMachineSet(CPMS) in which case it should not manually add new machines which would get deleted by the CPMSO which reconciles the control plane to the desired number of machines in spec.replicas.
This PR adds a new workflow that utilizes the CPMSO to automatically scale-up and scale-down when the platform supports CPMS (or detects its presence).
> Update etcd scaling test for CPMS supported platforms

- test/extended/security/scc.go
Hypershift does not use `kubernetes.default.svc` as the api audience on the KAS.  It is set to the URL of the OIDC provider.  ROSA also does this so I don't imagine this test passes for it either at the moment.
Explicit setting of the `Audiences` on the `TokenRequest` is not required.  If not set, it will just default to the audiences configured in the KAS.
Causing conformance failure for hypershift
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-aws-ovn/1620240601058381824
> extended: security: do not explicitly set api audience on token request

- test/extended/image_ecosystem/s2i_images.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Update S2i image tests for Dotnet
Remove dotnet3.1 (EOL) as per [#438](https://github.com/redhat-developer/s2i-dotnetcore/pull/438) 
Signed-off-by: Feny Mehta <fbm3307@gmail.com>
> Update S2i image tests for dotnet3.1 EOL

- test/extended/util/openshift/clusterversionoperator/adminack.go
https://github.com/openshift/origin/pull/27645 intended to add a guaranteed post-upgrade check but I have overlooked how exactly the polling is implemented and terminated, leading to the post-upgrade check never actually execute.
Previously the test used `PollImmediateWithContext` for the each-10-minutes check. The `ConditionFunc` never actually returned `true` or non-nil `err`, so the `PollImmediateWithContext` never terminated by the means of `ConditionFunc`: it was always terminated by the `ctx.Done()` that the framework does on finished upgrade (or a test timeout). This means that `PollImmediateWithContext` always terminated with `err=wait.ErrWaitTimeout` and the `Test` method immediately returned, so the "guaranteed" check code is never reached.
Given our `ConditionFunc` never …
> OCPBUGS-6503: upgrade/adminack: simplify polling and unblock "guaranteed" post-upgrade check

- test/extended/etcd/helpers/helpers.go
Due to recent failures in Vertical Scaling, increasing the time out before declaring the test as failed
cc @tjungblu @hasbro17
> bump timeout

- test/extended/security/scc.go
- test/extended/security/supplemental_groups.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- remove user group requirement for the test
Remove [Local] from test as it is not local anymore since https://github.com/openshift/origin/pull/16408 . So this test has not been run in the CI for a long time. And locally as well, since it has been broken because of the removal of `exec -p` feature in https://github.com/kubernetes/kubernetes/pull/76713.
> make supplemental groups test working again

- test/extended/include.go
- test/extended/storage/OWNERS
- test/extended/storage/inline.go
- test/extended/testdata/bindata.go
- test/extended/testdata/storage/inline/csi-sharedresourcerole.yaml
- test/extended/testdata/storage/inline/csi-sharedresourcerolebinding.yaml
- test/extended/testdata/storage/inline/csi-sharedsecret.yaml
- test/extended/testdata/storage/inline/secret.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
https://issues.redhat.com/browse/STOR-1066
This PR adds an e2e test for the admission plugin that was added in https://github.com/openshift/kubernetes/pull/1384
This also has a dependency on https://github.com/openshift/csi-driver-shared-resource-operator/pull/65 so that the operator will not overwrite `security.openshift.io/csi-ephemeral-volume-profile` during the test. That fix is in `registry.ci.openshift.org/ocp/release:4.13.0-0.nightly-2023-01-24-061922` and newer nightly builds.
To run this test manually against an existing cluster:
```
make && ./openshift-tests run all --dry-run | grep CSIInlineVolumeAdmission | ./openshift-tests run -f -
```
> STOR-1066: add e2e tests for CSIInlineVolumeAdmission plugin

- test/e2e/upgrade/adminack/adminack.go
- test/extended/util/openshift/clusterversionoperator/adminack.go
This is a cherry-pick of https://github.com/openshift/origin/pull/27645 and https://github.com/openshift/origin/pull/27678
- upgrade/adminack: guarantee one admin ack check post-upgrade
- upgrade/adminack: optimize the post-upgrade check
- upgrade/adminack: simplify polling and unblock "guaranteed" post-upgrade check
- upgrade/adminack: wait up to 4m until gate propagates to upgradeable
/hold
> OCPBUGS-6851: [release-4.11] upgrade/adminack: guarantee one admin ack check post-upgrade

- test/extended/util/disruption/disruption.go
[TRT-799](https://issues.redhat.com//browse/TRT-799)
There's some examples in CI of chamosmoney-launched tests panicking, and ANSI control sequences ending up in the final JUnit xml (producing entirely invalid XML).
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-e2e-aws-ovn-upgrade/1618360645160275968/artifacts/e2e-aws-ovn-upgrade/openshift-e2e-test/artifacts/junit/junit_upgrade_1674689374.xml
This ensures the chaosmoney uses a ginkgo reporter config with colors off.
> Ensure NoColor for ginkgo in disruption/chamosmoney suite

- test/extended/builds/volumes.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
this will go in once the storage team's in-line driver support moves to GA, and hence we pull the trigger on moving shared resources to GA
When I get that indication, I'll replace the WIP with a [BUILD-407](https://issues.redhat.com//browse/BUILD-407) prefix
this is needed in order for https://github.com/openshift/openshift-controller-manager/pull/250 to pass e2e's
/assign @coreydaley
> BUILD-407: stage one of two of migrating shared resource from tech preview to GA

- test/extended/storage/storageclass.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
https://issues.redhat.com/browse/STOR-950
To run this test manually against an existing cluster:
```
make && ./openshift-tests run all --dry-run | grep DisableStorageClass | ./openshift-tests run -f -
```
> STOR-950: Add CI job for skipping StorageClass creation

- test/extended/baremetal/common.go
- test/extended/baremetal/hosts.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Metal3 pods can now be deployed on GCP platform.
Baremetal hosts can be booted only via virtual media. We only check for the presence of the metal3 pod to verify the baremetal deployment is available in GCP too.
> Allow baremetal tests to run on GCP platform

- OWNERS_ALIASES
- test/extended/kubevirt/OWNERS
- test/extended/kubevirt/services.go
- test/extended/kubevirt/util.go
This PR is a continuation of PR #27308 by @davidvossel 
Introducing 6 test cases to cover pods ability to communicate each other in several scenarios:
* Direct connection between pods on the guest cluster, via Pod Network and Host Network
* Connection between pods in guest cluster to a NodePort service configured on the guest cluster via Pod Network and Host Network.
* Connection between pods in infra cluster to a NodePort service configured on the guest cluster
* ~~Connection between pods in guest cluster to a LoadBalancer service configured on the guest cluster~~
* ~~Connection between pods in infra cluster to a LoadBalancer service configured on the guest cluster~~
> Kubevirt network connectivity tests

- e2echart/e2e-chart-template.html
- pkg/duplicateevents/duplicated_event_patterns.go
- pkg/monitor/event.go
- pkg/monitor/event_test.go
- pkg/monitor/intervalcreation/rendering.go
- pkg/synthetictests/apiserver.go
- pkg/synthetictests/duplicated_events.go
- pkg/synthetictests/duplicated_events_special.go
- pkg/synthetictests/duplicated_events_test.go
- pkg/synthetictests/marketplace.go
- pkg/synthetictests/networking.go
- test/extended/testdata/bindata.go
[TRT-685](https://issues.redhat.com//browse/TRT-685)
The two tests that look for pathological events:
* `[sig-arch] events should not repeat pathologically`
* `[sig-arch] events should not repeat pathologically in e2e namespaces`
will fail for events that repeat more than 20 times (those events are often referred to as  "pathological" or "duplicate" events).  Eventually more tests are created to look for specific regex patterns for those events.
This PR:
* Adds a new section at the bottom of the spyglass charts called "interesting-events".  The pathological/duplicate events are rendered on that section.
* Adds timestamps for events mentioned in the two tests mentioned above
This should aid debugging by making it easier to see when events happen relative to other things going on at the …
> Add pathological events into spyglass charts

- e2echart/e2e-chart-template.html
- test/extended/testdata/bindata.go
[TRT-847](https://issues.redhat.com//browse/TRT-847)
Light blue for CI cluster disruption, continue with red for disruption.
> Chart CI cluster DNS problems in different color from disruption

- test/extended/baremetal/common.go
- test/extended/baremetal/hosts.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Metal3 pods can now be deployed on Azure platform. Baremetal hosts can be booted only via virtual media. We only check for the presence of the metal3 pod to verify the baremetal deployment is available in Azure too.
> Allow baremetal tests to run on Azure platform

- cmd/openshift-tests/openshift-tests.go
- pkg/monitor/intervalcreation/node.go
- pkg/monitor/intervalcreation/types.go
- pkg/monitor/nodedetails/audit_log_loadbalancer_summary.go
- pkg/monitor/nodedetails/audit_log_summarizer.go
- pkg/monitor/nodedetails/audit_log_summary_serialization.go
- pkg/monitor/nodedetails/cmd.go
- pkg/monitor/nodedetails/node_log.go
- pkg/test/ginkgo/options_monitor_events.go
Allow streaming the kube-apiserver audit logs (not the aggregated ones, yet) through openshift-tests and summarizing them in a file we record. This is the basis of being able to call out interesting auditEvents for invariant testing and timeline insertion.
/assign @tkashem
> audit inspection

- pkg/monitor/intervalcreation/node.go
- pkg/test/ginkgo/options_monitor_events.go
Discovered that conformance test artifacts may not appear at all if
nodes are dead, due to recent work to query their logs for interval
creation.
Code modified to proceed even when errors happen here after logging the
problem.
[TRT-855](https://issues.redhat.com//browse/TRT-855)
> Do not bail on producing artifacts when nodes are dead

- test/extended/builds/volumes.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This reverts commit 376971b08a0debc2b32bf9febdacd5826b14ff5c.
see https://redhat-internal.slack.com/archives/C01C8502FMM/p1676472369732279 and https://github.com/openshift/release/pull/36433
after this, I'll update my move to GA PRs in openshift/openshift-controller-manager and openshift/cluster-storage-operator
/assign @coreydaley
@sjenning FYI .... after this merges, I would think the hypershift periodic would no longer cite the test failure that started us down this path, and presumably be green, unless there are tests that check cluster storage operator status perhaps
> Revert "perform build csi volume test on GA clusters"

- test/extended/authorization/rbac/groups_default_rules.go
Clusters that disable the `Console` capability are [currently failing this test-case][1]:
```
: [sig-auth][Feature:OpenShiftAuthorization] The default cluster RBAC policy should have correct RBAC rules [Suite:openshift/conformance/parallel] expand_less
Run #0: Failed expand_less	3s
{  fail [github.com/openshift/origin/test/extended/authorization/rbac/groups_default_rules.go:229]: Jan  3 13:43:14.134: test data for system:authenticated has too many unnecessary permissions:
{APIGroups:["console.openshift.io"], Resources:["consoleclidownloads"], Verbs:["get" "list" "watch"]}
{APIGroups:["console.openshift.io"], Resources:["consoleexternalloglinks"], Verbs:["get" "list" "watch"]}
{APIGroups:["console.openshift.io"], Resources:["consolelinks"], Verbs:["get" "list" "watch"]} …
```
> test/extended/authorization/rbac: Condition console RBAC on 'Console' capability

- images/tests/Dockerfile.rhel
Add `rt-tests` package to `tests` image for running realtime tests on clusters with realtime worker nodes.
> OCPVE-278: feat: add rt tests package to openshift-tests

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
The Centos Stream 9 kernel currently panics on nfs test suite and we'd like to disable that so that we're able to test without crashing nodes. There's a fix pending via https://bugzilla.redhat.com/show_bug.cgi?id=2169017 which we expect to receive within the next few days after which time we'll revert this change.
> OCPBUGS-7519: Skip nfs tests temporarilly

- images/tests/Dockerfile.rhel
This fixes an error encountered in the previous addition of #27740 for multi arch builds.
Currently, rt-tests are needed on only x86, this PR is limiting install only to that `HOSTTYPE`.
> OCPVE-278: fix: multi build error, only add rt-tests for x86

- test/e2e/upgrade/service/service.go
This is related to the Azure load balancer incident that is currently ongoing.
We believe the readyz is failing correctly for 30s during graceful termination before the pods are actually moved, so we should be able to test the Azure load balancer is correctly removing unhealthy instances before the end of the graceful termination.
We don't currently have any concrete evidence that `/healthz` works or not so, this may not change anything, but it would help us to narrow down the search hopefully
> Switch to readyz path for health probes on Azure

- test/extended/networking/vlan.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Tests for the following PRs:
https://github.com/containernetworking/plugins/pull/781
https://github.com/containernetworking/plugins/pull/813
https://github.com/containernetworking/plugins/pull/814
Signed-off-by: mmirecki <mmirecki@redhat.com>
> Add vlan/macvlan/ipvlan incontainer master tests

- test/extended/networking/tap.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/pods.go
Test for the following PR:
https://github.com/containernetworking/plugins/pull/832
Signed-off-by: Marcelo Guerrero Viveros <marguerr@redhat.com>
> Add tap plugin test

- test/extended/util/disruption/backend_sampler_tester.go
- test/extended/util/disruption/disruption.go
These fixes were applied in 4.13 early this year, but the backport was missed, as such we are not gathering SLB or image registry disruption numbers in 4.12. 
No product changes, just CI data gathering.
[TRT-825](https://issues.redhat.com//browse/TRT-825)
> [release-4.12] OCPBUGS-8024: Backport fixes to resume gathering CI disruption data for SLB and image registry

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
The kernel panic has been fixed in most recent RHCOS 9.2 content.
This reverts commit 2e101ceb5d78c5afc0b0526052974f86dea1ea08.
> OCPBUGS-7519: Revert Skip nfs tests temporarilly

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Marking the test as flaky to unblock merges. We'll continue investigating the issue.
/assign @dgoodwin 
> OCPBUGS-8092: mark volume expansion test as Flaky

- cmd/openshift-tests/e2e.go
- pkg/test/ginkgo/options_monitor_events.go
- test/extended/util/client.go
/hold
/assign @xueqzhan 
until after https://github.com/openshift/origin/pull/27694 merges
> Add additional comments with findings from k8s 1.26 bump

- cmd/openshift-tests/e2e.go
- test/extended/include.go
- test/extended/kernel/common.go
- test/extended/kernel/kernel_rt_pi_stress.go
- test/extended/testdata/bindata.go
- test/extended/testdata/kernel/rt-tests-environment.yaml
- test/extended/testdata/kernel/rt-tests-pod.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
This PR adds a few tests in that validate some realtime kernel tests can still be run when the realtime kernel is active. The tests are grouped into a new realtime specific test suite
> Realtime Kernel Tests

- test/extended/cloud_controller_manager/ccm.go
This PR updates the test for checking whether an external cloud provider is deployed or not to run on both the OpenStack (existing) and vSphere (new) platforms.
This will now check that an external cloud provider runs on the vSphere platform.
Will not pass until this [library-go](https://github.com/openshift/library-go/pull/1451) and it's associated PRs merge
> [OCPCLOUD-1818] Enable vSphere platform check in external cloud provider test

- test/extended/include.go
- test/extended/poddisruptionbudget/poddisruptionbudget.go
- test/extended/testdata/bindata.go
- test/extended/testdata/poddisruptionbudgets/always-allow-policy-pdb.yaml
- test/extended/testdata/poddisruptionbudgets/if-healthy-budget-policy-pdb.yaml
- test/extended/testdata/poddisruptionbudgets/nginx-with-delayed-ready-deployment.yaml
- test/extended/testdata/router/reencrypt-serving-cert.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
`PDBUnhealthyPodEvictionPolicy` was enabled as a tech preview in https://github.com/openshift/api/pull/1396. This PR adds E2E tests to test this feature for openshift (upstream is lacking these tests)
> WRKLDS-657: add test for UnhealthyPodEvictionPolicy for PDBs

- test/e2e/upgrade/service/service.go
Reverts openshift/origin#27753
This didn't actually help and I think, could in fact be harmful. Currently we are working on moving the Azure load balancer configuration over to health check kube-proxy, except it doesn't expose a `/readyz` path, only `/healthz`.
I think we should revert this until we find an explicit need for it
> OCPBUGS-8483: Revert "Switch to readyz path for health probes on Azure"

- pkg/monitor/backenddisruption/disruption_backend_sampler.go
- pkg/monitor/backenddisruption/disruption_backend_sampler_test.go
- pkg/monitor/write_job_run_data.go
- test/extended/util/disruption/controlplane/known_backends.go
[TRT-888](https://issues.redhat.com//browse/TRT-888)
> Specify Audit-ID to identify disruption requests in api audit logs

- pkg/monitor/intervalcreation/podlogs.go
- pkg/synthetictests/etcd.go
- pkg/synthetictests/event_junits.go
If found, intervals will be created, charted in spyglass, and a test
will flake giving us insight into how often this is happening across the
fleet.
> Scan etcd logs for dropped internal raft messages

- test/extended/cpu_partitioning/managed.go
- test/extended/cpu_partitioning/platform.go
- test/extended/cpu_partitioning/pods.go
- test/extended/cpu_partitioning/utils.go
- test/extended/include.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Add e2e tests for validating a cluster that is setup for CPU Partitioning is configured correctly. This supports the enhancement workload partitioning enhancement. openshift/enhancements#1213
> CNF-5652: Add cpu partitioning tests

- cmd/openshift-tests/openshift-tests.go
- pkg/monitor/event_test.go
- pkg/test/ginkgo/options_monitor_events.go
- pkg/test/ginkgo/options_monitor_events_test.go
[TRT-841](https://issues.redhat.com//browse/TRT-841)
For pathological events (i.e., they occur more than 20 times), we look back in the events to see the times the events occurred so we can render them on the spyglass chart.
If we have any troubles finding previous events, we skip so we avoid affecting a test's outcome.
> Mark previous pathological events so they get added to spyglass charts

- pkg/synthetictests/disruption.go
TRT-910: Temporarily flake ALL P99 disruption tests in 4.13
We do not have tooling to update the disruption tests in 4.13, on the
assumption we keep the values at fork time. This release we merged a
known regression after forking, and now are mass failing presubmits and
periodics on P99 disruption tests that are using data we knew was going
to go bad until we track down all the problems.
Move to flake all P99 disruption tests for a bit. See Jira links for
details on fixing more properly.
> TRT-910: Temporarily flake ALL P99 disruption tests in 4.13

- pkg/monitor/resourcewatch/storage/git_store.go
Some resource watch repos stop recording history due to
> fatal: Unable to create '/logs/artifacts/resource-watch-store/repo/.git/index.lock': File exists.
Seen from
> bash: line 1: 270427 Bus error               (core dumped) git add "namespaces/openshift-ingress/core/pods/router-default-65c89f6859-94ttq.yaml"
Only our process should be working with git in this area, so adding a delete to the failure path so subsequent files can have intact history.
At some point, a retry for existing files may be useful.
/assign @xueqzhan
> remove runresourcewatch git lock file on failure

- test/extended/idling/idling.go
Trying to reproduce https://bugzilla.redhat.com/show_bug.cgi?id=2091780
Unidled services should be reachable during the first connection attempt, it's important to not retry HTTP requests in tests.
See:
- https://issues.redhat.com/browse/OCPBUGSM-44873
- https://github.com/ovn-org/ovn-kubernetes/pull/3408
> OCPBUGS-9831: Make unidle test more strict

- cmd/openshift-tests/openshift-tests.go
- pkg/monitor/api.go
- pkg/monitor/apiserveravailability/cmd.go
- pkg/monitor/apiserveravailability/pod_log.go
- pkg/monitor/apiserveravailability/summarizer.go
- pkg/monitor/intervalcreation/types.go
- pkg/monitor/monitor.go
- pkg/synthetictests/disruption.go
- pkg/synthetictests/event_junits.go
example PR of how to scan pod logs for particular failures.  apiserver availability probably also wants to scan node logs.
> add apiserver availability timeline events

- test/extended/cli/admin.go
- test/extended/testdata/bindata.go
- test/extended/testdata/cli/test-release-image-references.json
- test/extended/util/annotate/generated/zz_generated.annotations.go
Fixture generated with:
```console
$ oc adm release extract --file image-references quay.io/openshift-release-dev/ocp-release:4.13.0-rc.0-x86_64 >test/extended/testdata/cmd/test/cmd/testdata/test-release-image-references.json
```
Compare [this output][1] from a different release image with the broken `oc`:
```json
{
"kind": "ImageStream",
"apiVersion": "image.openshift.io/v1",
...
"dockerImageRepository": ""
}
}Extracted release payload created at 2022-10-13T12:24:43Z
```
I'd initially suggested we include this test suite in the `oc` repository (openshift/oc#1317), where the fixture could be versioned alongside the code that generates it (making it easy to touch both the code and the fixture in one pull request if there is a need to make adjustments). But Arda and Maciej prefer this …
> OTA-824: test/extended/cli/admin: Test 'oc adm release extract --file image-references ...'

- test/extended/idling/idling.go
Reverts #27673  ; tracked by [TRT-944](https://issues.redhat.com//browse/TRT-944)
After https://github.com/openshift/origin/pull/27673 landed, we started failing payloads on the test: https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.nightly/release/4.14.0-0.nightly-2023-03-30-083327
Example run:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ipi-ovn-ipv6/1641431627710074880
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. …
> Revert "Make unidle test more strict"

- pkg/synthetictests/allowedbackenddisruption/query_results.json
There were (`1223`) added jobs and (`1764`) were removed.
Note: For P99, alerts had `60` jobs increased and `224` jobs decreased.
<details>
<summary>Click To Show Table</summary>
| Name | Release | From | Arch | Network | Platform | Topology | Job Results | P95 | P95 % Increase | P99 | P99 % Increase |
| ---- | ------- | ---- | ---- | ------- | -------- |--------- | ----------- | --- | -------------- | --- | -------------- |
| TargetDown openshift-e2e-loki Warning | 4.13 | 4.13 | amd64 | ovn | aws | ha | 208 | 0s| 0.00% | 1h59m37.76s | 331.46% 
| HighOverallControlPlaneCPU openshift-kube-apiserver Warning | 4.13 | 4.12 | amd64 | ovn | gcp | ha | 109 | 5m16s| 0.00% | 12m34.96s | 33.03% 
| KubePodNotReady openshift-multus Warning | 4.13 | 4.12 | amd64 | sdn | azure | ha | 201 | 0s| 0.00% | …
> upkeep: updated query results

- test/extended/networking/egress_firewall.go
- test/extended/testdata/bindata.go
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
Adds an allow rule for EF with node selector to k8s control plane nodes then tests traffic towards kapi server.
> OCPBUGS-11072: Add test for Egress Firewall node selector

- pkg/monitor/backenddisruption/disruption_backend_sampler.go
- pkg/monitor/backenddisruption/disruption_backend_sampler_test.go
- test/e2e/upgrade/upgrade.go
- test/extended/util/disruption/frontends/frontends.go
- test/extended/util/disruption/frontends/known_backends.go
This adds a wait before installs start to be sure that ingress is available before beginning an upgrade so that upgrades become a cleaner signal.
> add wait for ingress to be responsive before beginning upgrade

- pkg/synthetictests/disruption.go
Reverts openshift/origin#27781
We are past the point of needing to allow azure disruption to pass through unchecked. Reverting.
> Revert "TRT-889: Temp flake all azure disruption"

- test/extended/cli/debug.go
Currently, some `oc debug` tests rely on deterministic pod names. However, with this PR https://github.com/openshift/oc/pull/1393, we start adding a suffix to satisfy the uniqueness 
of pod names. That's why, this PR alleviates rigidity of assertions.
> not rely on deterministic pod names in oc debug tests

- pkg/monitor/intervalcreation/node.go
- pkg/synthetictests/event_junits.go
- pkg/synthetictests/kubelet.go
This will only catch instances *after* the tests have started.  Many instances exist during installation: https://search.ci.openshift.org/?search=static+pod+lifecycle+failure+-+static+pod&maxAge=336h&context=1&type=junit&name=4.13.*gcp&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
This will help identify how many more we've got.  And given it means, "pods don't run right", I wouldn't expect otherwise successful runs to hit this.
@rphillips to be sure this isn't a normal error
@deepsm007 to be sure he thinks it will work
> add specific test for failing cgroups path

- pkg/synthetictests/duplicated_events.go
Brings the same rule that is already in 4.10 to 4.9, now that loki is enabled by default for all clusters in CI.
> Bug OCPBUGS-11467: [release-4.9] Silence loki-promtail readiness probe errors

- test/extended/authorization/rbac/groups_default_rules.go
This PR addresses the following test failure happening in several jobs of openshift/kubernetes/pull/1524
```
{  fail [github.com/openshift/origin/test/extended/authorization/rbac/groups_default_rules.go:274]: Apr 10 17:57:34.909: system:authenticated has extra permissions in namespace "":
{APIGroups:["authentication.k8s.io"], Resources:["selfsubjectreviews"], Verbs:["create"]}
Ginkgo exit error 1: exit with code 1}
```
CC @stlaz @soltysh
> Add selfsubjectreviews RBAC rules

- test/extended/dns/dns.go
- test/extended/util/framework.go
[NE-1067](https://issues.redhat.com//browse/NE-1067): Validate TCP DNS local endpoint preference as well as UDP.
Validating DNS local endpoint preference using TCP is also very important to detect for regressions. Though UDP is typically the default, DNS Clients often retry in TCP if they receive a truncated (too big) DNS reply via UDP.
`test/extended/dns/dns.go`: Refactor DNS local endpoint validation in a common function. Add TCP DNS test case.
`test/extended/util/framework.go`: Make `PodExecutor` public so we can use it as a parameter in new function.
> NE-1243: Validate TCP DNS local endpoint preference as well as UDP.

- test/extended/etcd/etcd_storage_path.go
/assign @bertinatto 
1.27 PR: https://github.com/openshift/kubernetes/pull/1524
Specific failure: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/1524/pull-ci-openshift-kubernetes-master-e2e-aws-ovn-serial/1646116522243919872
> Update ETCD storage data for k8s 1.27

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Flake `Pods Extended Pod Container lifecycle evicted pods should be terminal` test.
I had a conversation with upstream about backporting https://github.com/kubernetes/kubernetes/pull/115331.  115331 depends on other changes for correctness and is also risky to backport. For now, the best we can do is flake this test and work on Clayton's upstream redesign to fix these subsystems.
> OCPBUGS-11560,OCPBUGS-11629: flake Pods Extended Pod Container lifecycle evicted pods

- pkg/monitor/write_job_run_data.go
- pkg/riskanalysis/write_test_failure_summary.go
- pkg/synthetictests/event_junits.go
- pkg/synthetictests/platformidentification/types.go
- pkg/synthetictests/updates.go
- pkg/test/ginkgo/cmd_runsuite.go
- test/extended/util/disruption/disruption.go
Looks for NodeUpdate event intervals with 'master' in the locator to determine if nodes were updated.  Adds a flag to the ClusterData json Y/N (or empty string) to indicate yes, no, unknown.  If considered viable we should be able to extract the flag in ci-tools when uploading disruption to indicate if the upgrade did in fact update the master nodes.
> Trt-945 detect master node updates

- cmd/openshift-tests/cni.go
Some third-party CNI vendors want to be certified as working in OpenShift with dual-stack, so add those tests to the suite.
> Add (optional) dual-stack tests to the CNI certification test suite

- cmd/openshift-tests/e2e.go
- test/extended/pods/graceful-shutdown.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Added the initial tests for verifying that the kubelet is respecting a pods shutdown grace period when configured for graceful shutdown, [see](https://kubernetes.io/docs/concepts/architecture/nodes/#graceful-node-shutdown)
/cc @jerpeter1
> OCPNODE-1257: feat: added unit test for graceful shutdown

- test/extended/cpu_partitioning/platform.go
HostedClusters i.e. Hypershift do not use MachineConfigs and do not have the CRD installed, causing `CPU Partitioning cluster infrastructure should be configured correctly` test to fail on HostedClusters.
We should skip this test for HostedClusters.
> test/extended: cpu-partitioning: skip cluster infrastructure for Hypershift

- test/extended/dr/backup_restore.go
- test/extended/dr/common.go
- test/extended/dr/machine_recover.go
- test/extended/dr/quorum_restore.go
- test/extended/dr/recovery.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
* obsoletes the older non-working tests (due to ssh bastions)
* rebuilds a slightly simpler version that only runs the backup and restore scripts with ssh from within the cluster
> ETCD-417: add a new basic etcd backup/restore test

- test/extended/authorization/podsecurity_admission.go
The restricted-v2 SCC should mutate this instead.
/cc @openshift/openshift-team-auth @deads2k
> PSa podspec exporter e2e: don't specifically add seccompProfile to the podspec

- pkg/monitor/intervalcreation/node.go
- pkg/synthetictests/event_junits.go
- pkg/synthetictests/kubelet.go
Detects a kubelet using only an anonymous user. Kubelet certificates rotate negotiate an OpenShift user instead of using anonymous users.
> add anonymous cert detection test case

- test/extended/operators/operators.go
Testing against an STS cluster without change and with change from this PR
https://gist.githubusercontent.com/abutcher/00e9780d1ce5e4fda2c058f56f0c136b/raw/f39a513b0d28f3eba9b92472135e6dd0d5ad4af9/cco-manual-upgradeable-false-e2e
> CCO-367: Allow CCO to be Upgradeable=False when credentialsMode=Manual

- e2echart/non-spyglass-e2e-chart-template.html
- test/extended/testdata/bindata.go
This PR makes the html on the left image, look like the right image (without going too deep on learning html styling):
<div style="display: flex; flex-direction: row; align-items: center;">
</div>
> Fix up the chart so the "Not" column is lined up

- test/e2e/upgrade/upgrade.go
[TRT-1003](https://issues.redhat.com//browse/TRT-1003)
- The test is renamed to remove the value from the name, meaning we'll be able to do apples-to-apples comparisons in Sippy and Component Readiness.
- Thresholds are adjusted to the 30-day P99 values for 4.14. We've encounted some regressions, a bug was opened for s390x for example.
> Adjust thresholds for reasonable upgrade durations

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Reactivate the newer networkpolicy test suite now
that [e36a14730bdfa8f236626a5e117b0eb51dcb29c7](https://github.com/openshift/kubernetes/commit/e36a14730bdfa8f236626a5e117b0eb51dcb29c7#diff-ed5dc9ca2657cd6bb6ae1cec597b8552bbcb3e6d9bc39c1b6919f2712c6e5e10) and
[145cec925af70fb94a46ec3fefc9411b928377e6](https://github.com/openshift/kubernetes/commit/145cec925af70fb94a46ec3fefc9411b928377e6#diff-ed5dc9ca2657cd6bb6ae1cec597b8552bbcb3e6d9bc39c1b6919f2712c6e5e10) have made
it downstream
fixes #27535
> Reactivate netpol tests

- pkg/duplicateevents/duplicated_event_patterns.go
This reverts #27666.  The purpose of this PR is to determine whether https://issues.redhat.com/browse/OCPBUGS-5943 is still present.
> OCPBUGS-5943: Revert "ignore repeated TopologyAwareHintsDisabled events"

- test/extended/networking/tuning.go
This prevents the test to pass when the pod is not running. A bug was not detected due to this missing check.
> OCPBUGS-13372: Add missing error check in sysctl allowlist test

- pkg/duplicateevents/duplicated_event_patterns.go
This reverts commit 1af057b15c718510b728a645ae5929b79e8a8b83 from https://github.com/openshift/origin/pull/27815 which unfortunately we're still seeing after landing k8s 1.27. 
/assign @Miciah @dgoodwin
> OCPBUGS-13366: ignore repeated TopologyAwareHintsDisabled events

- test/extended/networking/multinetpolicy.go
- test/extended/testdata/bindata.go
- test/extended/testdata/multinetpolicy/deny-ingress-pod-a.yml
- test/extended/testdata/net-attach-defs/macvlan-nad.yml
- test/extended/util/annotate/generated/zz_generated.annotations.go
Adding basic test cases to multinetwork policy feature. 
This PR is mainly to avoid regressions like [OCPBUGS-6917](https://issues.redhat.com/browse/OCPBUGS-6917) from occurring again.
> test/extended: Add MultiNetworkPolicy IPv4/IPv6 test cases

- test/extended/cli/idle.go
For blocking jobs, 30 second timeout value is sufficient. However, these test fails on OpenStack by
getting timeout error. This PR increases oc idle tests timeout to 60 seconds to pass
on OpenStack as mentioned in referenced bug.
> OCPBUGS-6586: oc idle: increase wait timeouts to 60 sec

- test/extended/prometheus/prometheus.go
Telemetry tests were always skipped because nothing checked the first value returned by telemetryIsEnabled().
For example, the openshift/telemeter [e2e-aws-ovn](
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_telemeter/459/pull-ci-openshift-telemeter-master-e2e-aws-ovn/1648956364942217216) job skips the tests while it's [enabled](https://github.com/openshift/release/blob/c423fd934ae060a1e6db5eb7d5ae8b22671c89a4/ci-operator/config/openshift/telemeter/openshift-telemeter-master.yaml#L55-L60) in openshift/release.
ping @wking since you submitted #27422.
> test/extended/prometheus: fix test with enabled telemetry

- test/extended/security/scc.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Reverts openshift/origin#27836
Per OpenShift policy, we are reverting this breaking change to get CI and/or nightly payloads flowing again.
This change is breaking ci 4.14 payloads
* [https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.ci/release/4.14.0-0.{nightly|ci}...](https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.nightly/release/4.14.0-0.nightly-2023-05-25-035545)
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of (job/X or job/X, test/Y tuple) to confirm the fix has corrected the problem:
/payload-job metal-ipi-ovn-ipv6
/payload-job metal-ipi-sdn-bm
This link may be helpful in understanding why the test …
> Revert "Add coverage for GET verb and websocket handshake to SCC exec tests."

- test/extended/include.go
- test/extended/kubevirt/services.go
- test/extended/kubevirt/util.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
The KubeVirt provider for HyperShift now supports connectivity between pods through LoadBalancer, therefore we are adding 2 new test cases to the conformance test suite to validate the following scenarios:
- Connection between pods in infra cluster to a LoadBalancer service configured on the guest cluster
- Connection between pods in guest cluster to a LoadBalancer service configured on the guest cluster
> LoadBalancer network connectivity test cases for HyperShift+KubeVirt

- test/extended/testdata/bindata.go
- test/extended/testdata/cmd/test/cmd/README.md
- test/extended/testdata/cmd/test/cmd/images.sh
- test/extended/testdata/cmd/test/cmd/quota.sh
- test/extended/testdata/cmd/test/cmd/testdata/image-streams/image-streams-centos7.json
It seems that `registry.centos.org` is permanently closed and the tests relying on the images hosted on this registry started failing. This PR changes the images from `registry.centos.org` to `quay.io`.
> OCPBUGS-14125: Move from registry.centos.org to quay.io

- test/extended/networking/multinetpolicy.go
- test/extended/testdata/bindata.go
- test/extended/testdata/multinetpolicy/deny-ingress-pod-a.yml
- test/extended/testdata/net-attach-defs/macvlan-nad.yml
- test/extended/util/annotate/generated/zz_generated.annotations.go
Reverts
- https://github.com/openshift/origin/pull/27926
The original implementation of these tests contains a bug when the `networks.operator.openshift.io.Spec.UseMultiNetworkPolicy` is nil. This PR fix that.
CC: @s1061123 , @bparees, @deepsm007
> OCPBUGS-13788: 2x Revert "test/extended: Add MultiNetworkPolicy IPv4/IPv6 test cases" #27926

- test/extended/prometheus/prometheus.go
Clear missing summary/description annotation test case exception for following alerts
-  CsvAbnormalFailedOver2Min
-  CsvAbnormalOver30Min
-  InstallPlanStepAppliedWithWarnings
-  APIRemovedInNextEUSReleaseInUse
-  APIRemovedInNextReleaseInUse
-  ExtremelyHighIndividualControlPlaneCPU
-  HighOverallControlPlaneCPU
-  TechPreviewNoUpgrade
-  CertifiedOperatorsCatalogError
-  CommunityOperatorsCatalogError
-  RedhatMarketplaceCatalogError
-  RedhatOperatorsCatalogError
Add missing summary/description annotation test case exception for following alerts
-  KubeletHealthState
-  MCCDrainError
-  MCDPivotError
-  MCDRebootError
-  SystemMemoryExceedsReservation
Change test case "[sig-instrumentation][Late] OpenShift alerting rules [apigroup:image.openshift.io]" from flaky to failure
> MON-3219: Clear missing summary/description annotation test case exception

- test/extended/networking/tuning.go
This test sometimes fails because the allowlist controller takes more than 30s to update the sysctl allowlist file. This controller waits up to 60s for the pods of the DS to be in ready state.
> OCPBUGS-14321: Increase timeout in sysctl allowlist test

- test/extended/networking/tuning.go
This test sometimes fails because the allowlist controller takes more than 30s to update the sysctl allowlist file. This controller waits up to 60s for the pods of the DS to be in ready state.
This is a cherry-pick of #27955
> OCPBUGS-14342: Increase timeout in sysctl allowlist test

- test/extended/prometheus/prometheus.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
TechPreview jobs happen to increase significantly the number of series being sent to telemetry (especially because of the additional CRDs being installed which increase the cardinality of the
`cluster:usage:resources:sum` metric).
> OCPBUGS-14338: test/extended/prometheus: increase telemetry series threshold

- cmd/openshift-tests/dev.go
- pkg/cmd/monitor_command/run_monitor_command.go
- pkg/monitor/intervalcreation/e2etest.go
- pkg/monitor/loki_upload.go
- pkg/monitor/monitorapi/identification.go
- pkg/test/ginkgo/options_monitor_events.go
This change is part of a process to get intervals charts, a key debugging tool, more robust and powerful. Once live, sippy will be able to pull intervals from loki instead of gcs buckets, which gives us more powerful searching, but also the ability to intermingle actual logs from the cluster. We will also be able to search intervals across all CI jobs.
Pushing intervals to loki is best effort. If we fail, we log and continue.
- Obtain bearer token for loki upload
- Push intervals to loki in batches
- Detect bad http codes
- Fix an edge case where locators parse badly for loki unpack
- Add retries for batches of intervals going to loki
- Fix discrepancies with interval creation funcs
- Final hookup to run after we write intervals to disk
[TRT-994](https://issues.redhat.com//browse/TRT-994)
> push intervals to loki

- test/extended/prometheus/prometheus.go
This test is permafailing in 4.14
Example logs https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ironic-image/379/pull-ci-openshift-ironic-image-master-prevalidation-e2e-metal-ipi-virtualmedia-prevalidation/1666311316056313856
Reverts openshift/origin#27933
> OCPBUGS-14667:  Revert "MON-3213: Changing the severity of "missing runbook_url annotation for critical alerts" test case from flaky to failure"

- pkg/duplicateevents/duplicated_event_patterns.go
- pkg/synthetictests/duplicated_events_special.go
- pkg/synthetictests/duplicated_events_special_test.go
- pkg/synthetictests/event_junits.go
Updating the test names to reflect pathological event to make it easier to search in sippy.
Adding 3 more events encountered during CI runs in the past month.
https://issues.redhat.com/browse/TRT-689
> Updated pathological events
