- test/extended/networking/acl_audit_log.go
The name in the OVN acl log was updated by
https://github.com/ovn-org/ovn-kubernetes/pull/3521. The matching string needs be updated accordingly.
> Update expected name for OVN acl logging test

- pkg/monitor/loki_upload.go
It seems the locator parts don't always have a "/", skip and log them.
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/40519/rehearse-40519-periodic-ci-openshift-cluster-etcd-operator-release-4.14-periodics-e2e-aws-etcd-recovery/1671511270085365760/artifacts/e2e-aws-etcd-recovery/openshift-e2e-test/build-log.txt
> Fix panic in loki upload

- test/extended/machines/cluster.go
- test/extended/machines/display_reboots_pod.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
Evolution of https://github.com/openshift/origin/pull/27899/ that uses the upstream helpers for waiting, generates a namespace as "normal", marks as allowed for privileged namespace, uses admin creds to pass SCC checks, uses upstream helpers to get logs, avoids recursion for looping, reports all failures for attempts, and reduces length.
/assign @vrutkovs
> OCPBUGS-13379: machines: add a test which verifies number of node reboots

- test/extended/machines/cluster.go
- test/extended/machines/display_reboots_pod.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
enable https://github.com/openshift/origin/pull/27993 everywhere
What if arm64 (or something else) is consistently restarting and on HA we simply recover fast enough to not notice?
/assign @vrutkovs 
This one will require a payload test first to ensure we don't straight out fail.
> verifies number of node reboots even for HA

- pkg/synthetictests/disruption.go
[TRT-1095](https://issues.redhat.com//browse/TRT-1095)
We'll flake these backends to avoid failing payloads.
> Flake ci-cluster-network-liveness and new backend disruption failures to avoid payload rejections

- test/extended/cli/idle.go
- test/extended/testdata/bindata.go
- test/extended/testdata/cmd/test/cmd/testdata/idling-dc.yaml
Avoid parsing output of `oc create` which can return additional lines of text besides the dc name
> OCPBUGS-15291: [sig-cli] oc idle: get a dc name through labels instead of parsing oc create output

- test/extended/machines/cluster.go
/assign @sjenning 
fixes https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn-conformance/1673273617175023616
> skip reboot test when machineconfigs not in target cluster

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Now that all the required PRs for the feature to work has merged, we can enable the test. Please the bug links for the list of PRs.
Manual revert of https://github.com/openshift/origin/pull/27867
> OCPBUGS-11652: Enable oc adm node-logs

- test/extended/prometheus/prometheus.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/prometheus/helpers.go
The following critical alerts do not have have runbook_url annotation added as exceptions:
- OVNKubernetesNorthboundDatabaseClusterIDError
- OVNKubernetesSouthboundDatabaseClusterIDError
- OVNKubernetesNorthboundDatabaseLeaderError
- OVNKubernetesSouthboundDatabaseLeaderError
- OVNKubernetesNorthboundDatabaseMultipleLeadersError
- OVNKubernetesSouthboundDatabaseMultipleLeadersError
- OVNKubernetesNorthdInactive
- KubeSchedulerDown
- MultipleDefaultStorageClasses
- MachineAPIOperatorMetricsCollectionFailing
- MCDRebootError
- ExtremelyHighIndividualControlPlaneMemory
- HAProxyDown
- ClusterOperatorDown
- ClusterVersionOperatorDown
The check for runbook_url validity has been separated out into a new flaky test
> Changing the severity of "missing runbook_url annotation for critical alerts" test case from flaky to failure

- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/external.go
Report external binary usage like other synthetic tests. 
/assign @bparees @ingvagabund
> Report external binary usage

- test/extended/cli/explain.go
- test/extended/util/framework.go
This change will check if a cluster is MicroShift and make changes accordingly for `[sig-cli] oc explain should contain proper spec+status for CRDs` test.
> USHIFT-647: skip sig-cli explain for CRDs in MicroShift

- test/extended/cpu_partitioning/pods.go
- test/extended/cpu_partitioning/utils.go
This skip should be safe now because all identified workloads that were missing the workload annotation have been fixed.
We did run the payload jobs to validate that other platforms were not missing any annotations. Currently these tests are passing on all relevant payload runs, this does not include payloads that did not execute the test suite with these tests, but that.
> OCPVE-378: feat: remove skip, allow check on all platforms regardless

- test/e2e/upgrade/clusteroperator.go
- test/e2e/upgrade/upgrade.go
this will provide a view of exactly which operator is failing when we get errors like: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade/1674247080836599808
> add debugging info for cluster not ready to upgrade

- pkg/synthetictests/allowedalerts/all.go
found in https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade/1674247078311628800
/assign @DennisPeriquet
> add a networking alert for OVNKubernetesResourceRetryFailure

- test/extended/operators/operators.go
To start the process of removing support for Alibaba in IPI installations, we want to set an [upgrade blocker via the CCM](https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/257) to prevent users upgrading into 4.14.
This will then allow us to start moving Alibaba code and its deployment behind a feature gate.
To allow the tests to continue to function right now, need to add an exception to not fail this test when the CCM is blocking the upgrade on Alibaba.
Once we are behind a TechPreview featuregate we can remove this block and the code changes here
> OCPBUGS-14425: Skip CCM upgradable condition on AlibabaCloud

- pkg/monitor/intervalcreation/node.go
- pkg/monitor/intervalcreation/node_test.go
- pkg/synthetictests/event_junits.go
- pkg/synthetictests/kubelet.go
Looks for matches indicating 'Failed to update lease' in journal logs.
Creates a new flake test case.  We see update lease failures early on during the install so a grace period of 30 minutes is added from the first event time.
> trt-1117: Test for update lease errors

- test/extended/cli/explain.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Closes: [USHIFT-647](https://issues.redhat.com/browse/USHIFT-647)
skip non-existing resources from security.openshift.io
> USHIFT-647: skip non-existing resources from security.openshift.io

- test/extended/oauth/redirect_uris.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This PR adds E2E tests that cover the Redirect URI validation in OAuth clients; in particular, they test that when requests include Redirect URIs with/without port on loopback or non-loopback URIs, the URI validation works as expected.
The expectations are the following:
- clients with non-loopback redirect URIs should only accept non-loopback URIs without port in the URI
- clients with loopback redirect URIs should only accept loopback URIs with or without port in the URI
Depends on the following PRs:
- https://github.com/openshift/oauth-server/pull/121
- https://github.com/openshift/oauth-server/pull/128
> AUTH-377: Add oauth-server redirect URI validation e2e tests

- test/extended/quota/clusterquota.go
There is a clear distinction in terms of average duration of test `Cluster resource quota should control resource limits across namespaces` between [4.14](https://sippy.dptools.openshift.org/sippy-ng/tests/4.14/analysis?test=%5Bsig-api-machinery%5D%5BFeature%3AClusterResourceQuota%5D%20Cluster%20resource%20quota%20should%20control%20resource%20limits%20across%20namespaces%20%5Bapigroup%3Aquota.openshift.io%5D%5Bapigroup%3Aimage.openshift.io%5D%5Bapigroup%3Amonitoring.coreos.com%5D%5Bapigroup%3Atemplate.openshift.io%5D%20%5BSuite%3Aopenshift%2Fconformance%2Fparallel%5D&filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22%5Bsig-api-machinery%5D%5BFeature%3AClusterResourceQuota%5D%20Cluster%20resource%20quota%20should%20control …
> OCPBUGS-15568: Increase clusterquota wait timeout from 10 to 30 seconds

- test/extended/cpu_partitioning/pods.go
The reason the flakes have been occurring is due to some tests around the network-operator creating DaemonSets and Deployments that do not contain resources. Adding a skip list for resources that are okay being BestEffort and added comment to code to be explicit on the meaning of best effort in a workload partitioned cluster. This does not effect the CPU affinity for workload partitioning.
Test-Grid Flaks: https://testgrid.k8s.io/redhat-openshift-ocp-release-4.14-informing#periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-ovn-cpu-partitioning&include-filter-by-regex=CPU%20Partitioning
Ref Resources on the network operator:
[DaemonSet](https://github.com/openshift/cluster-network-operator/blob/25b457440a3cf305a75586d879542a98dde4fca2/bindata/allowlist/daemonset/daemonset.yaml) …
> OCPVE-379: fix: avoid checking resources for BestEffort pods

- test/e2e/upgrade/service/service.go
Increases --delay-shutdown to 80 seconds based on analysis in [TRT-1030](https://issues.redhat.com//browse/TRT-1030) that showed disruption at 0 with 80 second and greater delay.
> trt-1030: 80s for service lb under test

- pkg/monitor/intervalcreation/podlogs.go
This avoids a panic in `Scan.scan()` when the `io.ReadCloser()` (`reader`) is invalid (because we were unable to retrieve the logs).
Sample log where this occurred:
```
[2023-06-27 10:12:07] time="2023-06-27T10:12:07Z" level=error msg="error reading pod logs" error="container \"etcd\" in pod \"etcd-test-infra-cluster-a1729bd4-master-2\" is not available" pod=etcd-test-infra-cluster-a1729bd4-master-2
```
From a [pre-submit job](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_assisted-test-infra/2212/pull-ci-openshift-assisted-test-infra-master-e2e-metal-assisted/1673615526967906304/build-log.txt) in a [PR](https://github.com/openshift/assisted-test-infra/pull/2212)
> OCPBUGS-15500: Avoid panic attempting to process interval logs

- test/extended/deployments/deployments.go
AFAICT, the only need for the core apiGroup in this role https://github.com/openshift/cluster-openshift-controller-manager-operator/blob/master/bindata/v3.11.0/openshift-controller-manager/deployer-clusterrole.yaml#L56-L64 is to pass this test because it is using the wrong Group in modern OCP.
cc @deads2k
> test: extended: deployment: use correct apigroup for imagestreamtags

- test/extended/cli/mustgather.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
As `oc adm must-gather` is not supported in MicroShift, these tests can be skipped.
> USHIFT-1379: skip must-gather tests for MicroShift

- test/extended/networking/multinetpolicy.go
The CNO can rewrite networks.operator.openshift.io while the test is trying to update it. Just retry.
```
: [sig-network][Feature:MultiNetworkPolicy][Serial] should enforce a network policies on secondary network IPv6 [Suite:openshift/conformance/serial] expand_less 	52s {  fail [github.com/openshift/origin/test/extended/networking/multinetpolicy.go:165]: Unexpected error:
<*errors.StatusError | 0xc0004f3860>:
Operation cannot be fulfilled on networks.operator.openshift.io "cluster": the object has been modified; please apply your changes to the latest version and try again
{
ErrStatus:
code: 409
details:
group: operator.openshift.io
kind: networks
name: cluster
message: 'Operation cannot be fulfilled on networks.operator.openshift.io "cluster":
the object has been modified; please apply …
```
> multinetpolicy: use RetryOnConflict to reduce flakes

- pkg/synthetictests/duplicated_events.go
To have machine categorization, we need to have the namespace label be pretty unambiguous.  This "namespace foo" has false matches for e2e tests.
To match https://github.com/openshift-eng/ci-test-mapping/pull/50, we need to use "ns/foo", which has less (no?) false matches.
> update pathological event namespace label to be unambiguous

- test/extended/cloud_controller_manager/ccm.go
This PR updates the test for checking whether an external cloud provider is deployed or not to run on both existing platforms and now Azure as well.
This will now check that an external cloud provider runs on the Azure platform.
Will not pass until this [library-go](https://github.com/openshift/library-go/pull/1484) and it's associated PRs merge
> [OCPCLOUD-1987] Enable Azure platform check in external cloud provider test

- test/extended/apiserver/api_requests.go
the CI job I checked showed 30 additional watches which seems plausible given timeouts and interruptions.
> increase cloud-credential-operator watch since we added a self-clusteroperator watch

- test/extended/authorization/rbac/groups_default_rules.go
See also https://github.com/openshift/console-operator/pull/775
Change the permission check for helmchartrepositories from `get, list` to `get, list, watch`.
> OCPBUGS-15893: Update permission to incl. watch for helmchartrepositories for console users

- test/extended/authorization/rbac/groups_default_rules.go
See also https://github.com/openshift/console-operator/pull/776
Add new `consolesamples` resource to the list of resources that every (console) user could read (get, list, watch).
> ODC-7333: Add consolesamples to the list of console resources that all users should have read access

- test/extended/operators/operators.go
required for https://github.com/openshift/cluster-config-operator/pull/329 to allow migration from latency sensitive
> OCPBUGS-16164: allow cluster-config-operator to manage featuregate upgrade block

- test/extended/cli/explain.go
- test/extended/operators/check_crd_status.go
This is a follow-up on #28045:
This PR adds the new `ConsoleSample` CRD to an `exceptionsList` in `check_crd_status.go` because the openshift/api version bump in console-operator PR https://github.com/openshift/console-operator/pull/771 always fails because this new CRD has no `status` field.
**e2e-aws-ovn-single-node** fails with ([example job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console-operator/771/pull-ci-openshift-console-operator-master-e2e-aws-ovn-single-node/1680186512810971136)):
```
[sig-arch][Early] CRDs for openshift.io should have a status in the CRD schema [Suite:openshift/conformance/parallel]
Writing JUnit report to /logs/artifacts/junit/junit_e2e__20230715-124231.xml
Suite run returned error: 1 fail, 1342 pass, 1843 skip (1h2m52s) …
```
> ODC-7333: Add consolesamples to the exception list of CRDs without a status

- cmd/openshift-tests/provider.go
- test/extended/cli/explain.go
- test/extended/util/framework.go
This change will skip 
`"[sig-cli] oc basics can show correct whoami result with console [Skipped:NoOptionalCapabilities] [Suite:openshift/conformance/parallel]"` 
test by adding NoOptionalCapabilities for MicroShift
> USHIFT-704: skip [sig-cli] whoami result with console for MicroShift

- test/extended/image_ecosystem/s2i_images.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This PR is to remove the tests for nodejs 14 ubi8 imagestreams as it is eol and been removed from openshift/library
> Update S2i Image tests for removing nodejs 14 ubi8 eol

- test/extended/cpu_partitioning/pods.go
Originally these namespaces were thought to not be needed for the test, recent flakes show that these pods do get deployed in these namespaces. Updated to include the namespaces.
> fix: add missing namespaces to exclude list

- pkg/monitor/resourcewatch/storage/git_store.go
Min version of [28062](https://github.com/openshift/origin/pull/28062) 
- Just pull in the moved lock for now.  This will slow down commits, we want to evaluate these changes in isolation.
> trt-1150: move lock so prevent multiple file updates in single commit

- test/extended/kubevirt/util.go
Since the console-logger as been introduced, there is one more pod in the HCP namespace that contains the node name.
This is causing the console-logger pod to be fetched instead of the virt-launcher pod, resulting in a test failure while trying to contact the guest node.
We need to fix the filtering to get only the virt-launcher pods and then find the one that contains the node name amongst them, by the `kubevirt.io=virt-launcher` label.
> [sig-kubevirt] Fix retrieval of virt-launcher pod of the guest node

- cmd/openshift-tests/disruption.go
- pkg/monitor/backenddisruption/disruption_backend_sampler.go
- pkg/monitor/event.go
- pkg/monitor/event_test.go
- pkg/monitor/monitor.go
- pkg/monitor/monitor_test.go
- pkg/monitor/recorder.go
- pkg/monitor/types.go
- test/extended/util/disruption/backend_sampler_tester.go
- test/extended/util/disruption/controlplane/known_backends.go
This will let us split controller duties from recording duties.  Only controllers need to have pre- and post-hooks for disruption checking.
This would potentially allow us to establish completely separate "monitors" with pre-post, but I think I'll leave those aspects combined.
> create a recorder interface that separates monitoring from recording

- pkg/defaultinvariants/types.go
- pkg/invariants/impl.go
- pkg/invariants/types.go
Adds an interface to use for tests like kube-apiserver disruption inside the cluster, pod to pod communciation failure inside the cluster, and DNS connectivity inside the cluster.
I'm going to continue wiring in the handling for these changes, but I think this interface will remain. The steps for measuring podnetwork-to-podnetwork, podnetwork-to-service, and podnetwork-to-hostnetwork will probably look something like this.
1. create generated namespace with openshift-ci-network-check-xxx (cleanup will destroy this namespace).  
2. create required permissions
3. create deployment with antiaffinity with an http server (not secured, possibly a simple on in this repo) that honors readyz.  Need a target server for pod network and host network, plus services.  
4. create a binary in this repo …
> add interface for future invariant tests

- test/extended/cpu_partitioning/OWNERS
- test/extended/cpu_partitioning/crio.go
- test/extended/cpu_partitioning/utils.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This PR adds a test for validating CPU shares and CPUSets are being respected in a cluster.
The given test runs a collection script via the machine-config-daemon (this is chosen for ease of querying and it running on every node, adequate permissions and node config responsibilities), The script will generate a json payload that is a trimmed down data set of crio data and CPUSet information per pid from `taskset`. This information is then used to validate that containers in a node are correct configured.
|| Partitioned Cluster |  Regular Cluster  |
|--|-------------------|-----------------|
|CPU Set | Validate CPUSet Are Restricted or Open Depending on PAO | Validates CPUSet are wide open |
|CPU Share| Validate CPUShare match annotation at CRIO Level | Should not be needed, pre-existing …
> OCPVE-318: feat: add node validation for workload partitioning

- pkg/synthetictests/duplicated_events_test.go
[TRT-1161](https://issues.redhat.com//browse/TRT-1161)
CI runs in UTC; so if we set our times in UTC, we can run the tests locally (when in a time zone other than UTC) and they should still pass.
We use asserts where we can.
> Put times in UTC to allow local testing; use asserts where we can

- pkg/disruption/backend/disruption/handler.go
- pkg/disruption/backend/shutdown/handler.go
- pkg/monitor/alerts.go
- pkg/monitor/alerts_test.go
- pkg/monitor/apiserveravailability/summarizer.go
- pkg/monitor/backenddisruption/disruption_locator.go
- pkg/monitor/intervalcreation/node.go
- pkg/monitor/intervalcreation/operator.go
- pkg/monitor/intervalcreation/podlogs.go
- pkg/monitor/intervalcreation/state_tracker.go
- pkg/monitor/monitor_test.go
- pkg/monitor/monitorapi/construction.go
- pkg/monitor/monitorapi/types.go
- pkg/monitor/pod.go
Moved to focus on IntervalBuilding, not ConditionBuilding, we hope to
eliminate Conditions in the future. (move the fields up into Interval)
Add a Display hint, coarse grained, where the generating code can
indicate if something is intended to be displayed in the UI. i.e.
DisruptionBegan DisruptionEnded no, Disruption intervals calculated from
those yes.
Experimenting with a source for each interval so we know where it came
from. This may get removed if we find it too cumbersome. Intent is to
help user see what they're looking at, and help the UI filtering have
something more concrete to filter on beyond message contents.
> Adjust interval builder before we continue porting

- test/extended/images/append.go
This PR will fix the test failure when using a manifest-listed payload for a single-architecture deployment.
> Update image stream test to create a manifest list image by default

- test/e2e/upgrade/upgrade.go
NOTE: The OVNAWSPlatformType and OVNGCPPlatformType upgrade times are originally 85 and 90 minutes each. Due to well-known reasons (https://issues.redhat.com/browse/SDN-4042), these numbers are increased to 100 minutes only for the 4.13->4.14 upgrades - same as OVNAzurePlatformType. These numbers will be brought down to their original values in OCP 4.15 (https://issues.redhat.com/browse/OTA-999)
> SDN-4042: Increase total upgrade time on OVN platforms

- test/extended/networking/multinetpolicy.go
This is now enabled by default in aws serial jobs:
https://github.com/openshift/release/pull/41872
> Remove enabling multinetwork policy

- cmd/openshift-tests/openshift-tests.go
- pkg/clioptions/imagesetup/images.go
- pkg/clioptions/upgradeoptions/upgrade_options.go
- pkg/cmd/openshift-tests/images/images_command.go
- pkg/cmd/openshift-tests/run-test/command.go
- pkg/cmd/openshift-tests/run-upgrade/command.go
- pkg/cmd/openshift-tests/run-upgrade/flags.go
- pkg/cmd/openshift-tests/run-upgrade/options.go
- pkg/cmd/openshift-tests/run/command.go
- pkg/cmd/openshift-tests/run/flags.go
- pkg/cmd/openshift-tests/run/options.go
- pkg/defaultinvariants/types.go
- pkg/invariants/knownimagechecker/invariant.go
- pkg/test/ginkgo/cmd_runsuite.go
- test/extended/util/image/image.go
/hold
opening so I don't lose it, but this won't work until the core of the invariant checking lands.  Darn you images!
> separate the run, run-upgrade, and run-test

- test/extended/prometheus/prometheus.go
https://issues.redhat.com/browse/OCPBUGS-14052 has been fixed.
> Remove exception on KubeSchedulerDown runbook

- pkg/synthetictests/operators.go
- pkg/synthetictests/platformidentification/operator_mapping.go
We have discovered that if there are no clusteroperator intervals in the
e2e/conformance test portion, this test is omitted entirely which breaks
test pass rates in a variety of tooling, as well as the aggregator. In
this case if the operator does trigger an unexpected transition in the
conformance stage, a fail is recorded, and the other jobs in aggregation
report no result, resulting in < 6 results to aggregate on and a
failure.
Switch to always checking for, and including tests for, all operators,
regardless if they have recorded any intervals.
[TRT-1100](https://issues.redhat.com//browse/TRT-1100)
> Fix ClusterOperator tests that can only report failures

- pkg/clioptions/upgradeoptions/upgrade_options.go
- pkg/cmd/openshift-tests/run-upgrade/options.go
Only the actual run test needs to set the global.
> remove unnecessary global modification from upgrade

- test/extended/prometheus/prometheus.go
- test/extended/util/framework.go
This change will first look for `"openshift-monitoring"` namespace before creating prometheus client.
If the namespace doesn't exist, it will skip the following tests
```
"[sig-instrumentation][Late] Alerts shouldn't exceed the series limit of total series sent via telemetry from each cluster": " [Suite:openshift/conformance/parallel]",
"[sig-instrumentation][Late] Alerts shouldn't report any unexpected alerts in firing or pending state": " [Suite:openshift/conformance/parallel]", 
```
[USHIFT-1484](https://issues.redhat.com/browse/USHIFT-1484)
> USHIFT-1484: skip prometheus alerts for MicroShift

- test/extended/csrapprover/csrapprover.go
Test 'Pods cannot access the /config/master API endpoint fails' assumes, that curl output should contain Connection refused, which is not always true, when cluster would be deployed on OpenStack with different CNI (like Kuryr), which is using Security Groups to block the traffic to the internal API. In that case rules created by SG would drop the packet, so there will be no response rather then refuse.
This patch is correcting the test case, where there is added additional response string and added timeout option for curl, just to save the time.
> Bug OCPBUGS-6778: Correct condition for rejecting connection

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
A specific EgressIP test is broken with OVN-K in interconnect mode. Disable temporarily while the bug is fixed.
> Disable EgressIP test termporarily due to OVN-K bug

- test/extended/kubevirt/util.go
When running tests in parallel, it's possible to get a failure when creating our exec pods due to naming collisions between tests. By using the GenerateName for our exec pod, we avoid the collision
below is an example failure
```
fail [k8s.io/kubernetes@v1.27.1/test/e2e/framework/pod/resource.go:367]: failed to create new exec pod in namespace: clusters-vossel2
Unexpected error:
<*errors.StatusError | 0xc0067bf900>: 
pods "execpod-sourceip-ip-10-0-0-126.us-west-1.compute.internal" already exists
{
ErrStatus: 
code: 409
details:
kind: pods
name: execpod-sourceip-ip-10-0-0-126.us-west-1.compute.internal
message: pods "execpod-sourceip-ip-10-0-0-126.us-west-1.compute.internal" already
exists
metadata: {}
reason: AlreadyExists
status: Failure,
}
occurred
```
> Fix kubevirt test flake caused by pod name collision

- pkg/test/ginkgo/test_suite.go
> OCPBUGS-16166: disable 2 tests in preparation to land k8s 1.27.4

- pkg/invariants/network/disruptionserviceloadbalancer/invariant.go
The disruption Service tests that were previously run and skipped for OpenStack on upgrades jobs, are now run on various jobs unrelated to upgrades. This can cause the job run to fail when proxy installations are run with OpenStack given floating ip is not supported in this scenario. This commit fixes the issue by continue to skips those tests for OpenStack.
> Bug OCPBUGS-17483: Skip invariant load balancer test for OpenStack

- test/extended/authentication/front_proxy.go
[USHIFT-1464](https://issues.redhat.com/browse/USHIFT-1464):  Temporarily skip TestFrontProxy for MicroShift.
[OCPBUGS-17431](https://issues.redhat.com/browse/OCPBUGS-17431) will act as a reference to support API Aggregation test for MicroShift
> USHIFT-1464: skip TestFrontProxy for MicroShift

- pkg/invariants/testframework/pathologicaleventanalyzer/invariant.go
- pkg/monitor/event.go
- pkg/monitor/event_test.go
- pkg/monitor/monitorapi/types.go
I've been trying to port these to the new interval builder, and noticed we don't really have enough test coverage to know if I broke something or not. This PR just adds some more tests for the main paths through.
Also fixes a bug I think we recently gained during the invariants refactor, it looks like we did not add the new interval we created back to the list when post-processing intervals that eventually crossed the pathological/true barrier.
> Add some tests for event interval generation

- OWNERS
Both Standa and I have a good track record of contributing to this repository. Standa has managed to contribute 100 PRs, and I've contributed 154.
Additionally, both the Auth team and the API team contribute to this repository. So having an approver from these teams will enable them to work more efficiently.
> Add stlaz and p0lyn0mial to OWNERS

- test/extended/apiserver/openapiv3.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test that merged openapi v3 discovery has partial URLs with a hash/etag
- test groups that are both served by CRDs and external apiservers (eg openshift-apiserver). Like authorization.openshift.io that should be merged from both of these sources
tests should pass after the following merges
TODO:
> OCPBUGS-15726: add tests for openapi v3

- pkg/invariants/node/nodestateanalyzer/node.go
avoids lots of useless intervals.
> only close node ready if the node was not ready before

- pkg/monitor/backenddisruption/disruption_backend_sampler.go
Now that we have a consumption wait, we can stop the consumption immediately and close based on whatever data we already have.
> stop sampling when we stop

- test/extended/prometheus/prometheus.go
Updating the test to run on a subset of jobs as part of serial suite didn't resolve the issue of rate limit. Until monitoring team fixes the issue making the test to flake.
/cc @dgoodwin
> OCPBUGS-16615: Making prometheus telemetry test flake

- pkg/monitortestlibrary/allowedalerts/matches_test.go
- pkg/monitortestlibrary/allowedbackenddisruption/matches_test.go
- pkg/monitortestlibrary/allowedbackenddisruption/query_results.json
- pkg/monitortestlibrary/historicaldata/alert_types.go
- pkg/monitortestlibrary/historicaldata/disruption_types.go
- pkg/monitortestlibrary/historicaldata/next_best_guess.go
- pkg/monitortestlibrary/historicaldata/next_best_guess_test.go
This is the second part to https://github.com/openshift/ci-tools/pull/3562 PR for origin test to support both releases .
Both alerts and disruption tests are updated along with query_results.json.
/cc @dgoodwin @neisw
> TRT-930: Update test to support 2 release query_results.json

- pkg/defaultmonitortests/types.go
- pkg/monitor/api.go
- pkg/monitor/monitor.go
- pkg/monitortests/node/watchnodes/monitortest.go
- pkg/monitortests/node/watchnodes/node.go
- pkg/monitortests/node/watchnodes/node_test.go
- pkg/monitortests/testframework/watchclusteroperators/monitortest.go
- pkg/monitortests/testframework/watchclusteroperators/operator.go
- pkg/monitortests/testframework/watchclusteroperators/operator_test.go
- pkg/monitortests/testframework/watchclusteroperators/watcher.go
- pkg/monitortests/testframework/watchevents/event.go
- pkg/monitortests/testframework/watchevents/event_test.go
- pkg/monitortests/testframework/watchevents/monitortest.go
Just moves.  Be sure that the timeline shows node upgrades, pathological events, and cluster operator progression.
> migrate some watching code to monitortests

- pkg/cmd/openshift-tests/disruption/watch-endpointslice/endpointslice_controller.go
- pkg/cmd/openshift-tests/disruption/watch-endpointslice/watch_endpointslice_flags.go
- pkg/cmd/openshift-tests/disruption/watch-endpointslice/watch_endpointslice_options.go
- pkg/monitor/backenddisruption/disruption_backend_sampler.go
- pkg/monitortests/network/disruptionpodnetwork/host-network-to-host-network-poller-deployment.yaml
- pkg/monitortests/network/disruptionpodnetwork/host-network-to-pod-network-poller-deployment.yaml
- pkg/monitortests/network/disruptionpodnetwork/pod-network-to-host-network-poller-deployment.yaml
This fixes teh current pattern which doesn't cause failure, but does count disruption improperly: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/28191/pull-ci-openshift-origin-master-e2e-gcp-ovn-rt-upgrade/1692509054028484608
> fix *-to-host sampler failure calculation

- test/extended/oauth/requestheaders.go
It seems that some of the old servers might be picking new requests even though they're shutting down. This commit should either prove or disprove that theory.
Another possibility is that the authn operator is not reporting the deployment status properly, or a revision rollout is borked.
> OCPBUGS-17477: requestheader: wait for only 3 oauth-servers to be available

- pkg/monitortests/imageregistry/disruptionimageregistry/monitortest.go
- pkg/monitortests/kubeapiserver/disruptionlegacyapiservers/monitortest.go
- pkg/monitortests/network/disruptioningress/monitortest.go
- pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go
/assign @stbenjam 
this eliminates the secondary errors when setup fails on building samplers and the apiserver is unreliable.
> prevent secondary errors reported in prior steps

- test/extended/apiserver/api_requests.go
- test/extended/etcd/etcd_storage_path.go
- test/extended/etcd/etcd_test_runner.go
This will hard fail until we fix the problems in:
~1. api & auth & etcd https://issues.redhat.com/browse/OCPBUGS-3841~
~2. cvo https://issues.redhat.com/browse/OCPBUGS-3810~
~3. monitoring https://issues.redhat.com/browse/OCPBUGS-3924~
/hold
> Fail on APIs removed in the next release

- test/extended/apiserver/api_requests.go
- test/extended/etcd/etcd_storage_path.go
- test/extended/etcd/etcd_test_runner.go
Reverts #27561 , tracked by [TRT-1209](https://issues.redhat.com//browse/TRT-1209)
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of a minor upgrade.
CC: @soltysh
> Revert "Fail on APIs removed in the next release"

- test/extended/authorization/rbac/groups_default_rules.go
This is a manual backport of #28054
It is required to merge https://github.com/openshift/console-operator/pull/789 to add a missing watch permission to users that have already get and list permission. The missing permission results in unnecessary error logs and network failures because the console UI tries automatically to watch `helmchartrepositories`.
This then results in performance issues customers report with the UI.
The console-operator e2e tests fails with errors like this:
```
[AfterEach] [sig-auth][Feature:OpenShiftAuthorization] The default cluster RBAC policy
github.com/openshift/origin/test/extended/util/client.go:159
STEP: Destroying namespace "e2e-test-default-rbac-policy-zb8gj" for this suite. 08/31/23 06:58:39.292
fail …
```
> [release-4.12] OCPBUGS-18309: Add missing watch permission for console users

- test/extended/util/annotate/rules.go
Feature has been removed in Kubernetes 1.28: https://github.com/kubernetes/kubernetes/pull/115843
/hold
Until master branch opens for OCP 4.15.
> STOR-1425: Disable NetworkPolicyStatus tests

- pkg/cmd/openshift-tests/images/images_command.go
- test/extended/util/image/zz_generated.txt
Some of the metal jobs rely on information which images need to be mirrored, this information is coming in https://github.com/openshift/origin/pull/28097/ but to properly assess correctness we need those information sooner. 
This PR injects that image information directly into `./openshift-tests images` command.
/hold
Until master branch opens for OCP 4.15.
/assign @bertinatto
> STOR-1425: Add images coming in k8s 1.28

- images/tests/Dockerfile.rhel
Adding the `rteval` binary to the test image to be used for realtime kernel testing. The rteval binary is a utility for measuring various aspects of realtime behavior on a system under load.
> OCPVE-295: fix: add rteval to the test image

- pkg/monitortestlibrary/disruptionlibrary/disruption_invariant_adapter.go
[TRT-1219](https://issues.redhat.com/browse/TRT-1219)
[OCPBUGS-18718](https://issues.redhat.com/browse/OCPBUGS-18718)
With the refactor, we are adding connection types twice to the backend name. This PR removes the duplicate.
> Bug OCPBUGS-18718 Remove duplicate connection type from disruption name

- test/extended/include.go
- test/extended/node_tuning/OWNERS
- test/extended/node_tuning/node_tuning.go
- test/extended/testdata/bindata.go
- test/extended/testdata/node_tuning/OWNERS
- test/extended/testdata/node_tuning/nto-stalld.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/nodes.go
Automate PSAP NTO Prevent from stalld continually restarting
**How to execute the test case in local**
1. Clone the origin code
2. make WHAT=cmd/openshift-tests
3. openshift-tests run-test "[sig-node-tuning] NTO should [Conformance][Serial]OCP-66086 NTO Prevent from stalld continually restarting [Slow]"
**The Test Case Logs:**
openshift-tests run-test "[sig-node-tuning] NTO should OCP-66086 NTO Prevent from stalld continually restarting [Slow]"
Aug 17 14:42:51.951: INFO: Enabling in-tree volume drivers
Aug 17 14:42:52.616: INFO: get the first rhcos worker nodes as label node
Aug 17 14:42:52.616: INFO: Running 'oc --kubeconfig=/root/.kube/config get node -l node-role.kubernetes.io/worker -o jsonpath='{.items[*].metadata.name}''
Aug 17 14:42:52.848: INFO: Running 'oc …
> OCP-66086-Automate PSAP NTO Prevent from stalld continually restarting

- pkg/cmd/openshift-tests/run-upgrade/flags.go
- pkg/cmd/openshift-tests/run/flags.go
- pkg/test/ginkgo/cmd_runsuite.go
Alternative to https://github.com/openshift/release/pull/43229
When we're invoking tests with `--from-repository` it means we needed to mirror the images, which is problematic when we're bumping k8s, since the new images are not mirrored, yet. The long term goal would be to read the additional images from the external binary, but we don't have that functionality there, yet. This is a temporary solution to allow landing k8s bump.
/assign @bertinatto
> When --from-repository use built-in tests only

- test/e2e/upgrade/upgrade.go
Data analysis shows that p99 for this variant is just below 125min.
Allow some additional variance but not much.
We have plans to revert values to pre-4.14 values tracked via
https://issues.redhat.com/browse/OTA-999
> TRT-1244: Bump aws-ovn upgradeDurationLimits to 130

- test/extended/prometheus/prometheus.go
Severity has been decreased to warning: https://github.com/openshift/cluster-storage-operator/pull/382
Alert no longer requires a runbook so exception can now be removed.
> OCPBUGS-14053: remove exception for MultipleDefaultStorageClasses

- pkg/monitortestlibrary/allowedalerts/all.go
- test/extended/apiserver/apply.go
- test/extended/kubevirt/services.go
- test/extended/networking/internal_ports.go
- test/extended/networking/isolation.go
- test/extended/networking/services.go
- test/extended/pods/liveness_override.go
- test/extended/testdata/bindata.go
- test/extended/testdata/cmd/hack/lib/init.sh
- test/extended/util/client.go
- test/extended/util/disruption/disruption.go
We don't want this to be firing in vanilla OpenShift clusters.
Supersedes #27634
> AUTH-365: add PodSecurityViolation to watched alerts

- test/extended/kernel/kernel_rt_latency.go
- test/extended/kernel/tools.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This implements rteval as a realtime kernel test and updates the latency thresholds to be a little more forgiving
> OCPVE-295: rteval

- test/extended/kubevirt/migration.go
- test/extended/kubevirt/util.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
The live migration feature is quite destructive and it should be run            
before the rest of kubevirt conformance tests.
> kubevirt: Add live migration tests

- cmd/openshift-tests/openshift-tests.go
- pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
Noticed in https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-kubernetes-1646-nightly-4.15-e2e-metal-ipi-sdn-serial-ipv4/1701752788494585856
> Force using mirrored images in disruption tests

- cmd/openshift-tests/openshift-tests.go
- pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
Reverts openshift/origin#28258
> Revert "Force using mirrored images in disruption tests"

- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Reverts openshift/origin#28146
this is fixed via https://issues.redhat.com/browse/OCPBUGS-17455
we should no longer fail on these tests in serial jobs.
once aws-serial passes we can merge this PR
cc @jcaamano
> Revert "Disable EgressIP test temporarily due to OVN-K bug"

- pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
- pkg/monitortestframework/impl.go
- pkg/monitortestframework/types.go
This is convenient when testing one from the CLI.  It's also pretty easy to accept and run just CollectData and SerializeResults if we want.
> make it possible to select which monitor tests to run

- test/extended/builds/build_timing.go
Builds on bare metal look to be running faster than they used to which is making the PushImage test fail.
> OCPBUGS-19909: Updating parameters for build timing PushImage test

- cmd/openshift-tests/openshift-tests.go
- pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
~Followup to https://github.com/openshift/origin/pull/28258~
Brings back #28258 and adds a fix to the problem found in 
Found in https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.15-upgrade-from-stable-4.14-e2e-aws-ovn-upgrade/1706913500141457408
> Properly default --from-repository in run-monitor

- pkg/synthetictests/duplicated_events.go
- pkg/synthetictests/duplicated_events_test.go
Ignore timeout and connection refused errors during upgrade tests for 4.12
> OCPBUGS-18527: Ignore timeout and connection refused errors during upgrade tests for 4.12

- pkg/synthetictests/duplicated_events.go
- pkg/synthetictests/duplicated_events_test.go
Ignore timeout and connection refused errors during upgrade tests for 4.11
> OCPBUGS-18129: Ignore timeout and connection refused errors during upgrade tests for 4.11

- pkg/clioptions/clusterdiscovery/cluster.go
- pkg/clioptions/clusterdiscovery/provider.go
- pkg/clioptions/clusterdiscovery/provider_test.go
Since [OPNET-198](https://issues.redhat.com//browse/OPNET-198) we support IPv6 Primary cluster
Correctly set IPFamily based on the first family found
> OPNET-330: fix DualStackIPv6Primary

- test/extended/util/annotate/rules.go
Revert d008e1425c0125f9b2cd0121bef4c838e99a7862, since OCPBUGS-13392 is fixed.
no changes in zz_generated, since NetworkPolicyLegacy were completely removed.
> Remove bug-related annotations

- test/extended/cli/basics.go
- test/extended/cli/status.go
- test/extended/deployments/deployments.go
- test/extended/etcd/etcd_storage_path.go
- test/extended/images/trigger/annotation.go
- test/extended/router/idle.go
- test/extended/util/image/image.go
`ImageRegistry` became a new optional component in 4.14 (openshift/api#1572, openshift/openshift-docs#64469). And even before that, it has long been [configurable for `managementState: Removed`][3]. However the no-capabilities test is currently failing [like][4]:
message: Back-off pulling image "image-registry.openshift-image-registry.svc:5000/openshift/tools:latest"
in clusters without a local registry.  This pull request consolidates some `image-registry.openshift-image-registry.svc:5000` consumers around the `ShellImage` and `LimitedShellImage` functions.  Future work can teach those functions to be more flexible about choosing external pullspecs for clusters without a local registry.
[1]: https://github.com/openshift/api/pull/1572
[2]: …
> test/extended: Consolidate hard-coded local image registry dependencies

- pkg/clioptions/clusterinfo/api.go
- pkg/clioptions/clusterinfo/write_job_run_data.go
- pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
- pkg/cmd/openshift-tests/run-disruption/disruption.go
- pkg/monitor/monitor.go
- pkg/monitortests/node/legacynodemonitortests/updates.go
- pkg/monitortests/testframework/clusterinfoserializer/monitortest.go
- pkg/resourcewatch/operator/starter.go
- pkg/riskanalysis/write_test_failure_summary.go
- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/cmd_runtest.go
- test/extended/util/disruption/disruption.go
Add risk analysis test failure summary for monitor junit suites
Moves cluster info apis to clusterinfo package due to comments / circular dependencies
> trt-1271: add risk analysis for monitor junit suites

- test/extended/kubevirt/migration.go
- test/extended/kubevirt/util.go
The test are re-run to check if they are just flaky, in the case of live migration it should wait for the cluster to settle before doing the live migration again. This change wait for cluster to reach readiness.
> hs, kubevirt: Wait node readiness before migration

- pkg/monitortests/clusterversionoperator/legacycvomonitortests/operators.go
For reasons that are not clear to me, e065648534 (#26034) moved `testOperatorState` from using:
```go
condition := monitorapi.GetOperatorConditionStatus(event.Message)
```
to using:
```go
strings.Contains(eventInterval.Message, fmt.Sprintf("%v", interestingCondition))
```
But that can lead to misidentification [like][1]:
```
: [bz-service-ca] clusteroperator/service-ca should not change condition/Available
Run #0: Failed	1h24m4s
{  1 unexpected clusteroperator state transitions during e2e test run
Oct 05 16:28:56.647 - 1s    W clusteroperator/service-ca condition/Progressing reason/_ManagedDeploymentsAvailable status/True Progressing: \nProgressing: service-ca does not have available replicas}
```
That mentions `Available` as part of the `reason`, but the condition `type` itself is …
> pkg/monitortests/clusterversionoperator/legacycvomonitortests: Structured condition types

- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
- pkg/monitortests/testframework/watchevents/event_test.go
Revert the status of TopologyAwareHintsDisabled as a known issue, and fix the
unit test that relied on TopologyAwareHintsDisabled being a known issue.
Revert "OCPBUGS-13366: ignore repeated TopologyAwareHintsDisabled events"
This reverts commit 34fce4f11d0ec8554d9f356c1d72c075ea7ccb5a.
Add a reference to a known bug that can be considered pathological and interesting.
> OCPBUGS-20024: Revert "OCPBUGS-13366: ignore repeated TopologyAwareHintsDisabled events"

- pkg/clioptions/clusterdiscovery/provider.go
- pkg/monitortests/network/disruptionpodnetwork/monitortest.go
- test/extended/cli/debug.go
- test/extended/images/extract.go
- test/extended/images/resolve.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
- test/extended/util/framework.go
- test/extended/util/image/image.go
added skip annotation for situations when the image registry is not enabled via capabilities
added logic to handle imageregistry pullspecs when imageregistry is not enabled
> OCPBUGS-20205: feat: added support for ImageRegistry capability

- pkg/monitor/monitor.go
- pkg/monitortestframework/impl.go
- pkg/monitortests/testframework/uploadtolokiserializer/monitortest.go
Jobs like [this](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.15-upgrade-from-stable-4.14-e2e-azure-sdn-upgrade/1710475847271452672), show intervals in the second spyglass chart that are in the upgrade phase; this is seen in the events.json and html files (what you see for spyglass).  This PR prints the first/last interval times for when those json files are written to disk to try to figure out where these extra intervals are coming from.
Also, we use the To (instead of From) since To is later in hopes of avoiding 'entry too far behind'.
The symptom does not happen consistently in CI since the sno upgrade test is the only one with two spyglass charts.  We can let this run in the wild to see if we can get more data into when and why …
> Add debug info for interval counts and times

- pkg/clioptions/clusterdiscovery/provider.go
wrap InitializeReleasePullSpecString in check for HasNoOptionalCapabilities
> fix: wrap InitializeReleasePullSpecString in check for HasNoOptionalCapabilities

- test/extended/util/url/url.go
ReadResponse from golang's net/http package cannot parse http/2 response text as generated by curl. To work around this, force http/1.1 or earlier to be used.
> OCPBUGS-9037: Require http 1.1 or earlier when using curl

- test/extended/authorization/rbac/groups_default_rules.go
This is a manual backport of #28234
It will be required to backport a similar change as https://github.com/openshift/console-operator/pull/775 to 4.11.
It adds a missing watch permission to users that have already get and list permission. The missing permission results in unnecessary error logs and network failures because the console UI tries automatically to watch `helmchartrepositories`.
This results in performance issues customers report with the UI on OpenShift 4.10. I started this backport before the 4.11 PR was merged so that the tests could get green... :man_shrugging: 
/kind bug
/cc @bparees
> [release-4.11] OCPBUGS-18424: Add missing watch permission for console users

- examples/image-streams/image-streams-centos7.json
- test/extended/testdata/bindata.go
Observed problem is in OKD jobs of which there are none on this repo. So I'm interested in seeing at least that all the OCP jobs continue working without these image streams / tags. Then will follow up in confirming that things are fixed via rehearsals here https://github.com/openshift/release/pull/44127
> OCPBUGS-22276: Remove all docker.io images due to access denied

- pkg/monitor/monitorapi/types.go
[TRT-1267](https://issues.redhat.com//browse/TRT-1267)
The symptom I'm trying to solve is what appears in the [build-log.txt](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.15-e2e-aws-ovn-upgrade/1715259800222175232/artifacts/e2e-aws-ovn-upgrade/openshift-e2e-test/build-log.txt):
```
Writing to storage.
m.startTime = 2023-10-20 09:37:04.165909951 +0000 UTC m=+7.219893181
m.stopTime  = 2023-10-20 10:35:24.147320609 +0000 UTC m=+3507.201303839
Processing monitorTest: etcd-log-analyzer
finalIntervals size = 111920
first interval time: From = 2023-10-20 07:06:45 +0000 UTC; To = 2023-10-20 09:37:04.735409113 +0000 UTC
last interval time: From = 2023-10-20 10:34:07.756247353 +0000 UTC; To = 2023-10-20 10:34:07.756247353 …
```
> put back previous Interval Slice algorithm

- test/extended/apiserver/api_requests.go
Samples Operator added another watching triggerig the upper bound for SNO.
The upper limit was calculated to 52 via curl command below, increasing to 27*2 to buffer the change.
```
curl -L https://search.ci.openshift.org/\?search\=.\*Operator.\*cluster-samples.\*produces+more+watch+requests+than+expected\&maxAge\=168h\&context\=1\&type\=junit\&name\=aws.\*single-node\&excludeName\=\&maxMatches\=5\&maxBytes\=20971520\&groupBy\=job | grep watchrequestcount= | cut -d= -f2 | cut -d, -f1
```
> OCPBUGS-22358: fix: increase upper bounds for samples operator

- e2echart/e2e-chart-template.html
- pkg/monitor/monitorapi/types.go
- pkg/monitortests/kubeapiserver/apiservergracefulrestart/monitortest.go
- pkg/monitortests/kubeapiserver/apiservergracefulrestart/monitortest_test.go
- test/extended/testdata/bindata.go
Discovered these were mistakenly using an incorrect source
classification, so this is changed to be apiserver specific.
Also restore them on the intervals chart and collapse into one group.
> Restore APIServer graceful shutdown windows

- pkg/monitortests/testframework/legacytestframeworkmonitortests/alerts.go
- pkg/monitortests/testframework/legacytestframeworkmonitortests/alerts_test.go
500 runs and no flakes so far. Couple more days we should let this merge and allow the test to fail if it does find something.
[TRT-934](https://issues.redhat.com//browse/TRT-934)
> Allow the unknown alerts test to fail as it looks stable

- examples/image-streams/image-streams-centos7.json
- examples/sample-app/application-template-dockerbuild.json
- examples/sample-app/application-template-pullspecbuild.json
- examples/sample-app/application-template-stibuild.json
- test/extended/testdata/bindata.go
- test/extended/testdata/cmd/test/cmd/deployments.sh
- test/extended/testdata/cmd/test/cmd/testdata/application-template-dockerbuild.json
- test/extended/testdata/cmd/test/cmd/testdata/new-app/template-with-app-label.json
- test/extended/testdata/cmd/test/cmd/testdata/new-app/template-without-app-label.json
This test frequently fails on OKD, as it is importing [mysql samples](https://github.com/openshift/cluster-samples-operator/blob/master/assets/operator/okd-x86_64/mysql/imagestreams/mysql-centos.json) from quay.io. This PR updates used images to explicitly import mysql based on CentOS 8 Stream image instead of relying on imagestreams imported by cluster-samples-operator
> OCPBUGS-22413: Use Centos 8 Stream mysql image in tests

- pkg/cmd/openshift-tests/monitor/timeline/timeline_command.go
- pkg/monitor/monitorapi/identification_pod.go
- pkg/monitor/monitorapi/types.go
- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_events.go
- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_events_test.go
- pkg/monitortestlibrary/statetracker/state_tracker.go
- pkg/monitortests/node/nodestateanalyzer/node.go
- pkg/monitortests/node/nodestateanalyzer/nodeTest/drain-01/expected.json
- pkg/monitortests/node/nodestateanalyzer/nodeTest/drain-02/expected.json
- pkg/monitortests/node/nodestateanalyzer/node_test.go
These events are expected for certain pods during master updates, sometimes if the scheduler retries enough times they can trip our 20x limit and be considered a pathological event, failing tests when in reality this is a fairly normal condition.
I did some more work on the structured intervals so we could detect the NodeUpdate intervals in a structured manner.
[TRT-1335](https://issues.redhat.com//browse/TRT-1335)
> Skip FailedScheduling intervals when masters are in NodeUpdate

- pkg/monitortests/network/disruptionpodnetwork/host-network-target-deployment.yaml
- pkg/monitortests/network/disruptionpodnetwork/host-network-to-host-network-poller-deployment.yaml
- pkg/monitortests/network/disruptionpodnetwork/host-network-to-pod-network-poller-deployment.yaml
- pkg/monitortests/network/disruptionpodnetwork/host-network-to-service-poller-deployment.yaml
- pkg/monitortests/network/disruptionpodnetwork/pod-network-target-deployment.yaml
- pkg/monitortests/network/disruptionpodnetwork/pod-network-to-host-network-poller-deployment.yaml
- pkg/monitortests/network/disruptionpodnetwork/pod-network-to-pod-network-poller-deployment.yaml
- pkg/monitortests/network/disruptionpodnetwork/pod-network-to-service-poller-deployment.yaml
fix/[OCPBUGS-22703](https://issues.redhat.com/browse/OCPBUGS-22703): tolerate AWS 'edge' nodes in monitor tests
Allowing monitor tests to be scheduled in edge nodes.
AWS Local Zones have been supported in OCP since 4.13, those nodes
are classified as 'edge' nodes setting by default NoScheduled taints
in the MachineSet.
Those taints are required to prevent scheduled cluster workloads into
those nodes that run outside of the regular AWS region.
For more information, please check the EP:
https://github.com/openshift/enhancements/blob/master/enhancements/installer/aws-custom-edge-machineset-local-zones.md#user-workload-deployments
This limitation in the monitor tests impacts the delivered feature
in 4.14 (full Local Zones automation), and in the feature planned for
4.15: Wavelength Zones. …
> OCPBUGS-22703: tolerate AWS edge nodes on monitor tests

- pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
- pkg/cmd/openshift-tests/run-test/command.go
- pkg/cmd/openshift-tests/run-upgrade/flags.go
- pkg/cmd/openshift-tests/run-upgrade/options.go
- pkg/cmd/openshift-tests/run/flags.go
- pkg/cmd/openshift-tests/run/options.go
- pkg/defaultmonitortests/types.go
- pkg/monitor/monitorapi/types.go
- pkg/monitor/serialization/serialize.go
- pkg/monitortestframework/types.go
- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/cmd_runtest.go
Moves ExactMonitorTests and DisableMonitorTests filtering to defaultmonitortests
Adds ExactMonitorTests and DisableMonitorTests to openshift-tests run-test and run-upgrade
> TRT-1340: Increase cmd support for ExactMonitorTests and DisableMonitorTests

- e2echart/e2e-chart-template.html
- pkg/monitor/serialization/serialize.go
- pkg/monitortests/network/legacynetworkmonitortests/networking.go
- pkg/monitortests/testframework/watchevents/event.go
- test/extended/testdata/bindata.go
A little hacky until we revisit this for structured intervals, but
should be possible to clean up soon.
OCPBUGS-20479
> OCPBUGS-20479: Add pod sandbox failures to e2e charts

- test/extended/util/client.go
The creation of the Prometheus client does lots of requests to the Kubernetes API behind the scene. This change adds a retry logic to avoid test failures due to transient API errors.
> OCPBUGS-19527: retry Prometheus client creation

- pkg/monitortestlibrary/allowedalerts/matches_test.go
Failure:
```
Error Trace:	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/monitortestlibrary/allowedalerts/matches_test.go:238
Error:      	Not equal: 
expected: ""
actual  : "(no exact match for historicaldata.AlertDataKey{AlertName:\"AlertmanagerReceiversNotConfigured\", AlertNamespace:\"openshift-monitoring\", AlertLevel:\"Warning\", JobType:platformidentification.JobType{Release:\"4.15\", FromRelease:\"4.15\", Platform:\"aws\", Architecture:\"amd64\", Network:\"ovn\", Topology:\"ha\"}}, fell back to historicaldata.AlertDataKey{AlertName:\"AlertmanagerReceiversNotConfigured\", AlertNamespace:\"openshift-monitoring\", AlertLevel:\"Warning\", JobType:platformidentification.JobType{Release:\"4.14\", FromRelease:\"4.14\", Platform:\"aws\", …
```
> trt-1344: remove msg assertion

- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
- pkg/monitortests/testframework/watchevents/event_test.go
Reverts #28233 ; tracked by [TRT-1339](https://issues.redhat.com//browse/TRT-1339)
See JIRA for additional detials.  May jobs are flatlined on this failing, and it's caused many payload rejections. Example job https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.15-e2e-azure-sdn-techpreview-serial/1721106743041200128
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to …
> TRT-1339: Revert #28233 "ignore repeated TopologyAwareHintsDisabled events"

- pkg/cmd/openshift-tests/run-upgrade/options.go
Fix run-upgrade to use GinkgoRunSuiteOption settings
> trt-1340: update run-upgrade to use ginkgorunsuiteoptions

- pkg/monitor/monitorapi/types.go
- pkg/monitortests/testframework/uploadtolokiserializer/monitortest.go
[TRT-1342](https://issues.redhat.com//browse/TRT-1342)
With this PR, ...
* I [revert my earlier PR](https://github.com/openshift/origin/pull/28372/commits/a62bcf00c40db061535eb859ad218756544def2e) so the second spyglass chart (for upgrade jobs) goes back to getting some intervals that started during the upgrade phase (i.e., we go back to the previous `Slice()` algorithm).
* For loki serialization/ingestion, only intervals that happened after the upgrade will be pushed (this will avoid the "entry too far behind" problem that happens when we push intervals that are too old).
> "TRT-1342: Trim the intervals for loki serializer to avoid errors during ingest"

- test/extended/prometheus/prometheus.go
- test/extended/util/prometheus/helpers.go
Replace shell call of curl with net/http implementation in Prometheus helper functions.
So that timeout requests will not get truncated and reassembled responses.
> OCPBUGS-18776: [sig-instrumentation] tests fail due to JSON parsing error.

- e2echart/e2e-chart-template.html
- e2echart/non-spyglass-e2e-chart-template.html
- pkg/monitor/monitorapi/construction.go
- pkg/monitor/monitorapi/types.go
- pkg/monitor/serialization/serialize.go
- pkg/monitortestlibrary/statetracker/state_tracker.go
- pkg/monitortests/node/nodestateanalyzer/node.go
- pkg/monitortests/node/nodestateanalyzer/nodeTest/drain-01/expected.json
- pkg/monitortests/node/nodestateanalyzer/nodeTest/drain-02/expected.json
- pkg/monitortests/node/nodestateanalyzer/node_test.go
- pkg/monitortests/node/watchpods/compute_intervals.go
- test/extended/testdata/bindata.go
With a goal of having intervals be produced by origin and then immediately visible in the charts, which will soon live in sippy, we need a way to inject some kind of differentiator to force rows within one section onto different lines so they do not overlap. The clearest example of this today is the node state category where we would have the same node locator for multiple rows, but we break them out so we can clearly see the phases of update, when the node was not ready, and the overall os update. 
To do this, I've added a row key to the locator, as this feels most closely related. Changes were then required in the state tracker to support this without it getting confused.
> TRT-1354: Add support for intervals to have row differentiators

- test/extended/builds/proxy.go
The "should start a build and wait for the build to fail" test expects to fail some time before openshift-git-clone runs "git clone", but at higher logging levels, this requires that openshift-git-clone not tell us how it was invoked, which is a useful thing to have it be able to do.
Instead of treating the presence of "clone" in the logged output as an error, look for "git clone" (logged along with the rest of the CLI args at level 4 by github.com/openshift/library-go/pkg/git.timedCommand) as the signifier of an error.
> OCPBUGS-23084: expect to not see "git clone" and not just "clone" during a test

- test/extended/apiserver/api_requests.go
After some dep bumps on kube controller operator we have seen an increase in watch count, increasing threshold
> OCPBUGS-23079: fix: increase watch count for KubeControllerManagerOperator

- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
Proposed https://github.com/openshift/cluster-kube-apiserver-operator/pull/1423:
1. Prefixes condition messages with a zero-width non-breaking space (ZWNBSP).
2. Expects operators to quickly (within 1 min) update the condition message, removing the ZWNBSP.
Many operators emit an event when they are updating conditions (thanks to common code in libary-go) , these will trigger the pathological events tests.
This PR configured the pathological events tests to ignore these "challenge response" events.
> ignore stale condition challenge events

- go.mod
- go.sum
- test/extended/operators/certs.go
- vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/collection_options.go
- vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/collector.go
- vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/metadata_options.go
- vendor/github.com/openshift/library-go/pkg/certs/cert-inspection/certgraphanalysis/options.go
- vendor/modules.txt
The logical name removal broke consumers.  We need to restore the proxy-ca eliding because it's so long and not really useful.
proof of https://github.com/openshift/library-go/pull/1617
/hold
hold until we see it work.
> Certs 11 fix certs after break

- pkg/monitortestlibrary/allowedalerts/all.go
- pkg/monitortestlibrary/allowedalerts/basic_alert.go
- pkg/monitortestlibrary/allowedalerts/matches.go
Adds ability to specify alerts that should fail a test if we see ANY
fire, regardless of historical data.
Also allows specifying alert tests for an alert in a specific namespace.
Previously we could just do all interesting namespaces. (hardcoded list)
Adds TargetDown in kube-system (likely a kubelet problem) as  an initial
use of both concepts.
I adjusted how alert tests define their component to stop prepending bz-, move that prefix to all pre-existing alert tests as these are already mapped, and then align this test with sig-node, previously there was no way to map from bz-something to Node / Kubelet without updating the mapping repo. Bugzilla is dead to us anyhow and we shouldn't be making these assumptions in components in this mini-framework.
> TRT-1235: Add ability to specify alerts that should never fire

- test/extended/machines/machines.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
The origin test suite does not test CPMS, so, it should never have a CPMS rollout occur during a run.
We should add a test that checks that, early in the suite, the control plane machines are all named <cluster-name>-master-<index>. If for any reason we see a control plane machine matching <cluster-name>-master-<random>-<index> we know that the CPMS has rolled out and the test should be aborted until we work out why the CPMS rolled out.
> OCPCLOUD-2169: Check that CPMS does not rollout

- pkg/monitortests/network/legacynetworkmonitortests/networking.go
Kuryr is being removed in 4.15, this commit removes a Kuryr-related flake.
> OSASINFRA-3291: Remove Kuryr bits

- pkg/cmd/openshift-tests/run-upgrade/command.go
- test/e2e/upgrade/monitor.go
- test/e2e/upgrade/upgrade.go
There's not much difference between "the machine-config ClusterOperator has finished updating, so 100% of operators have updated" and "ClusterVersion claims the update complete".  The manifests the cluster-version operator reconciles after the machine-config ClusterOperator are mostly related to monitoring and resource-deletion:
```console
$ oc adm release extract --to manifests quay.io/openshift-release-dev/ocp-release:4.15.0-ec.2-x86_64
$ grep -r10 'name: machine-config' manifests | grep 'kind: ClusterOperator'
manifests/0000_80_machine-config-operator_06_clusteroperator.yaml-kind: ClusterOperator
$ ls manifests/0000_8* | sort | tail -n1
manifests/0000_80_machine-config-operator_06_clusteroperator.yaml
$ for X in manifests/0000_9*; do yaml2json < "${X}" | jq -c '.[] | {deletion: …
```
> NO-JIRA: test/e2e/upgrade/monitor: --abort-at=100 requires a complete update

- pkg/monitortests/clusterversionoperator/legacycvomonitortests/operators.go
Filling in known bugs from [here][1] (~WIP: not actually full yet~).  This allows us to fail new regressions, and gradually ratchet tighter as we close out existing issues.
[1]: https://bugzilla.redhat.com/buglist.cgi?bug_status=__open__&f1=longdesc&f2=cf_environment&j_top=OR&known_name=ClusterOperator%20conditions&list_id=12649817&o1=casesubstring&o2=casesubstring&query_based_on=ClusterOperator%20conditions&query_format=advanced&v1=should%20not%20change%20condition%2F&v2=should%20not%20change%20condition%2F
> OTA-362: pkg/monitortests/clusterversionoperator: Fatal unless Available=False in allow-list

- pkg/monitortestframework/errors.go
- pkg/monitortestframework/impl.go
- pkg/monitortests/imageregistry/disruptionimageregistry/monitortest.go
- pkg/monitortests/kubeapiserver/disruptionlegacyapiservers/monitortest.go
- pkg/monitortests/kubeapiserver/disruptionnewapiserver/monitortest.go
- pkg/monitortests/network/disruptionpodnetwork/monitortest.go
- pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go
- pkg/monitortests/testframework/disruptionexternalservicemonitoring/monitortest.go
Currently when the image-registry is unavailable, the monitor tests all just come back successful with no additional data.  This is a bit confusing, since there's no indication that monitor didn't run other than the extremely short duration of the tests.  This introduces a NotSupportedError type that the monitor tests can return which will cause the tests to be skipped instead of faked success.
> TRT-1347: Add ability to indicate a monitor test was skipped

- pkg/monitortests/cloud/azure/metrics/monitortest.go
[TRT-1359](https://issues.redhat.com/browse/TRT-1359)
> TRT-1359: Ignore azure interaction errors since they are not fatal for our usage

- test/extended/operators/certs.go
Skip hashed certs generated by monitoring operator. This has probably been accidentally removed in one of rebases.
> NOJIRA: collect certificate data: use SkipHashed option

- OWNERS_ALIASES
I left the CoreOS team over a year ago, so there are new co-leads for the team.
> OWNER_ALIASES: update CoreOS team leads

- pkg/defaultmonitortests/types.go
picking several from https://sippy.dptools.openshift.org/sippy-ng/component_readiness/capability?baseEndTime=2023-10-31%2023%3A59%3A59&baseRelease=4.14&baseStartTime=2023-10-04%2000%3A00%3A00&capability=Other&component=Unknown&confidence=95&excludeArches=arm64%2Cheterogeneous%2Cppc64le%2Cs390x&excludeClouds=openstack%2Cibmcloud%2Clibvirt%2Covirt%2Cunknown&excludeVariants=hypershift%2Cosd%2Cmicroshift%2Ctechpreview%2Csingle-node%2Cassisted%2Ccompact&groupBy=cloud%2Carch%2Cnetwork&ignoreDisruption=true&ignoreMissing=false&minFail=3&pity=5&sampleEndTime=2023-12-11%2023%3A59%3A59&sampleRelease=4.15&sampleStartTime=2023-12-05%2000%3A00%3A00
/cherry-pick 4.15
> fix jira components to match actual jira components

- pkg/monitortestlibrary/allowedalerts/matches_test.go
- pkg/monitortestlibrary/allowedbackenddisruption/matches_test.go
- pkg/monitortestlibrary/disruptionlibrary/disruption_invariant_adapter.go
- pkg/monitortestlibrary/historicaldata/next_best_guess.go
- pkg/monitortests/imageregistry/disruptionimageregistry/monitortest.go
- pkg/monitortests/kubeapiserver/disruptionlegacyapiservers/monitortest.go
- pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go
Details for the why available in the linked jira.
- Allow 5s or 20% grace on per-job disruption testing
- Drop all disruption/alert matcher fallbacks except previous release
- Stop disruption testing when platform is unknown
- Fix broken new/reused disruption test names causing inaccurate flakes
- Update image registry and PDB disruption test names for consistency
> TRT-786: Relax the per-job disruption tests and fix bugs/improve consistency

- pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadata/autoregenerate_after_expiry/requirement.go
- pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadata/ownership/requirement.go
- pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/annotation_requirement.go
- pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/types.go
This is a wrapper around tlsmetadatainterfaces.Requirement which helps users quickly create new requirements for secret/configmap annotations
> update-tls-artifacts: add AnnotationRequirement

- pkg/test/ginkgo/cmd_runsuite.go
Based on the following conversation[1], this test would be skipped until a fix to the blocker bug[2] is added 
[1] - https://redhat-internal.slack.com/archives/C065R4NCLGM/p1702558716657289?thread_ts=1702481324.774039&cid=C065R4NCLGM 
[2] - https://issues.redhat.com/browse/OCPBUGS-25402
/cc @soltysh
> OCPNODE-1892: Conditionally skip tests to help with k8s 1.29

- pkg/test/ginkgo/cmd_runsuite.go
Fixes #28445
The check of DryRun variable at https://github.com/openshift/origin/blob/master/pkg/test/ginkgo/cmd_runsuite.go#L235 must be done before calling `clusterinfo.GetMonitorRESTConfig` at https://github.com/openshift/origin/blob/master/pkg/test/ginkgo/cmd_runsuite.go#L200
> NO-JIRA: Fix issue 28445

- examples/quickstarts/rails-postgresql.json
- test/extended/builds/dockerfile.go
- test/extended/cli/setimage.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/build-secrets/test-s2i-build.json
- test/extended/testdata/builds/incremental-auth-build.json
- test/extended/testdata/builds/statusfail-badcontextdirs2i.yaml
- test/extended/testdata/builds/statusfail-fetchimagecontentdocker.yaml
- test/extended/testdata/builds/statusfail-fetchsourcedocker.yaml
- test/extended/testdata/builds/statusfail-fetchsources2i.yaml
- test/extended/testdata/builds/statusfail-genericreason.yaml
- test/extended/testdata/builds/statusfail-oomkilled.yaml
- test/extended/testdata/builds/test-build-proxy.yaml
- test/extended/testdata/builds/test-build.yaml
- test/extended/testdata/builds/test-context-build.json
- test/extended/testdata/builds/test-env-build.json
- test/extended/testdata/builds/test-imagesource-buildconfig.yaml
- test/extended/testdata/cluster/quickstarts/rails-postgresql.json
- test/extended/testdata/cmd/test/cmd/testdata/image-streams/image-streams-centos7.json
- test/extended/testdata/cmd/test/cmd/testdata/new-app/imagestream-ref.yaml
- test/extended/testdata/image/test-image.json
- test/extended/testdata/long_names/fixture.json
- test/extended/testdata/run_policy/parallel-bc.yaml
- test/extended/testdata/run_policy/serial-bc.yaml
- test/extended/testdata/run_policy/serial-latest-only-bc.yaml
Recent [changes](https://github.com/openshift/cluster-samples-operator/pull/522) to image streams removed ruby 2.7 in 4.15, updating to use ruby 3.0 in test build assets.
> OCPBUGS-25610: fix: lane e2e-gcp-ovn-builds perma fail

- examples/quickstarts/rails-postgresql-persistent.json
- test/extended/testdata/bindata.go
- test/extended/testdata/cmd/test/cmd/images.sh
updated images.sh and persistent to reference 3.0 image streams
Fixes issue highlighted in agnostic-ovn-cmd, https://github.com/openshift/origin/pull/28471#issuecomment-1864489107
> OCPBUGS-25610: fix: update missing ruby 3.0 ref

- test/extended/images/layers.go
image status contains a lot of messy superflous data, we shouldn't log it. Logging substatus and reason should be enough.
> NO-JIRA: images: don't log entire image status on failure

- test/extended/node_tuning/node_tuning.go
- test/extended/node_tuning/node_tuning_utils.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This test case use for automate for the bug OCPBUGS-18052
https://issues.redhat.com/browse/OCPBUGS-18052
The log of test cases:
make WHAT=cmd/openshift-tests
```openshift-tests run-test "[sig-node-tuning] NTO should SNO installation does not finish due to wait for non-existing machine-config [Early] [Suite:openshift/conformance/parallel]"
Nov 23 12:01:23.354: INFO: Enabling in-tree volume drivers
Running Suite: OpenShift e2e suite - /opt/origin
================================================
Random Seed: 1700740877 - will randomize all specs
Will run 1 of 1 specs
------------------------------
[sig-node-tuning] NTO should SNO installation does not finish due to wait for non-existing machine-config [Early] [Suite:openshift/conformance/parallel] …
```
> PSAP-1210: Update code for automate OCPBUGS-18052

- pkg/monitortests/network/disruptionpodnetwork/monitortest.go
Increase the timeout to give enough time on slower infra.
> OCPBUGS-25687: Increase timeout for pod-network-service

- test/extended/etcd/etcd_storage_path.go
Noticed in nightly failures:
- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.16-e2e-gcp-sdn-techpreview-serial/1737828261645258752
- https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.16-e2e-azure-sdn-techpreview-serial/1737828205005377536
/assign @sairameshv
> OCPNODE-1895: Update etcd test data for 1.29 release

- test/extended/apiserver/api_requests.go
From the new autodl data in bigquery:
```
SELECT
APPROX_QUANTILES(WatchRequestCount, 100)[OFFSET(50)] AS Median,
APPROX_QUANTILES(WatchRequestCount, 100)[OFFSET(95)] AS Percentile_95,
APPROX_QUANTILES(WatchRequestCount, 100)[OFFSET(99)] AS Percentile_99
FROM
openshift-ci-data-analysis.ci_data_autodl_test.operator_watch_requests
WHERE
JobRunName LIKE '%4.15%aws%'
```
Set to 110% of the P99.
> OCPBUGS-26069: Update cluster-monitoring-operator request limits

- pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadata/autoregenerate_after_expiry/requirement.go
- pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadata/descriptions/requirement.go
- pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/annotation_requirement.go
- tls/autoregenerate-after-expiry/autoregenerate-after-expiry.md
- tls/descriptions/descriptions.md
> Refine explanation of meeting regenerate after expiry requirement

- test/extended/security/labels.go
The logic behind the `TestOpenshiftNodeLabeling` test was to pick up a worker node and apply the labels that the worker nodes is not allowed to have. While on a normal cluster the test worked fine, it started failing on the SNO clusters. This is because, on the SNO clusters the only available node is labelled with both `worker` and `master` labels. This would make this test pick up the (only available) node and apply the `master` label. However, since a node in SNO cluster already has `master` label, kubelet will fail that operation [during the validation](https://github.com/kubernetes/kubernetes/blob/6aac45ff1e99068e834ba3b93b673530cf62c007/staging/src/k8s.io/kubectl/pkg/cmd/label/label.go#L391).  
Since the original intention of the test is to just apply labels that aren't allowed for …
> OCPBUGS-26025: Do not apply master label to make sure SNO jobs pass

- pkg/resourcewatch/operator/starter.go
while checking failure on https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-sdn-cgroupsv2/1743684397107777536 I wish I had this.
/assign @xueqzhan
> watch the operator resources during resource watch

- test/extended/networking/egress_firewall.go
Encountered a timeout issue when calling egress_firewall tests. 
This PR updates to 3 seconds for timeouts.
As some background...
When running origin test for egressFirewall in a multiarchitecture compute environment hits network jitter.
```
./openshift-tests run-test "[sig-network][Feature:EgressFirewall] egressFirewall should have no impact outside its namespace [Suite:openshift/conformance/parallel]"
```
Fails without warning...
The reason is the timing takes nearly 1second to execute.
```
time curl -q -I -m1 https://docs.openshift.com -s
real    0m0.920s
user    0m0.058s
sys     0m0.000s
```
This addresses a CI flake.
> OCPBUGS-18577: updated timeout to 3 seconds to account for network timing issues

- test/extended/operators/crd_must_be_stable.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
/hold
make the exclude list prior to merge
> add test to ensure all accessible-by-default apis are stable

- pkg/cmd/openshift-tests/dev/dev.go
- pkg/defaultmonitortests/types.go
- pkg/monitortestlibrary/allowedalerts/all.go
- pkg/monitortestlibrary/allowedalerts/watchdog.go
- pkg/monitortests/testframework/alertanalyzer/job_run_data.go
- pkg/monitortests/testframework/legacytestframeworkmonitortests/alerts.go
- pkg/monitortests/testframework/legacytestframeworkmonitortests/monitortest.go
- test/extended/prometheus/prometheus.go
For Disruptive suites we don't fetch promethues alerts
However we still test for watchdog alert when we shouldn't
> trt-1430: Pass watchdog InvariantCheck when cluster stability is disruptive

- examples/quickstarts/rails-postgresql-persistent.json
- examples/quickstarts/rails-postgresql.json
- test/extended/builds/dockerfile.go
- test/extended/cli/setimage.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/build-secrets/test-s2i-build.json
- test/extended/testdata/builds/incremental-auth-build.json
- test/extended/testdata/builds/statusfail-badcontextdirs2i.yaml
- test/extended/testdata/builds/statusfail-fetchimagecontentdocker.yaml
- test/extended/testdata/builds/statusfail-fetchsourcedocker.yaml
- test/extended/testdata/builds/statusfail-fetchsources2i.yaml
- test/extended/testdata/builds/statusfail-genericreason.yaml
- test/extended/testdata/builds/statusfail-oomkilled.yaml
- test/extended/testdata/builds/test-build-proxy.yaml
- test/extended/testdata/builds/test-build.yaml
- test/extended/testdata/builds/test-context-build.json
- test/extended/testdata/builds/test-env-build.json
- test/extended/testdata/builds/test-imagesource-buildconfig.yaml
- test/extended/testdata/cluster/quickstarts/rails-postgresql.json
- test/extended/testdata/cmd/test/cmd/images.sh
- test/extended/testdata/cmd/test/cmd/testdata/image-streams/image-streams-centos7.json
- test/extended/testdata/cmd/test/cmd/testdata/new-app/imagestream-ref.yaml
- test/extended/testdata/image/test-image.json
- test/extended/testdata/long_names/fixture.json
- test/extended/testdata/run_policy/parallel-bc.yaml
- test/extended/testdata/run_policy/serial-bc.yaml
- test/extended/testdata/run_policy/serial-latest-only-bc.yaml
Ruby 2.7 ImageStreams were removed in 4.15, this PR back ports updates the image references to ruby 3.0
Pulls in fixes from #28471 and #28481
> [release-4.15] OCPBUGS-25724: Cherrypick Ruby 3.0 ImageStream Fix

- hack/verify-kube-version.sh
- images/tests/Dockerfile.rhel
This adds a kubectl version to the Dockerfile so that the release controller can better represent what level of kube is present in our payloads. As our mismatch times extend, this makes certain classes of failures obvious and ensure we don't have an accident shipping.
/assign @soltysh @wking
> NO-JIRA: add kubernetes level to openshift tests image for payload

- pkg/monitortestlibrary/allowedalerts/matches_test.go
- pkg/monitortestlibrary/allowedbackenddisruption/matches_test.go
[TRT-1440](https://issues.redhat.com//browse/TRT-1440)
This unit test failed due to insufficient number of jobs (the number of jobs was 100 and we needed to be >= 101).  This makes it ok as long as we can fallback.
> TRT-1440: Allow BestMatchDuration to pass even on fallback

- test/extended/networking/egress_firewall.go
This PR update the image to use a non-nfs image, since we did not see any reference using nfs image, the test just trys to ping and curl things. And it also fixes the missing ping binary issue on s390x.
> OCPBUGS-20487: update egressFWTestE2E image which contains ping binary

- test/extended/router/http2.go
This PR reintroduces the HTTP/2 tests previously removed by [PR #28522](https://github.com/openshift/origin/pull/28522). The key difference now is the modified client code and the updated test expectations, which enable these tests to pass successfully.
- The `makeHTTPClient` function in `test/extended/router/http2.go` has been refined to better handle HTTP/2 and HTTP/1.1 protocols during TLS handshake.
- We have reintroduced the `http2-default-cert-edge` and `http2-default-cert-reencrypt` tests, which were removed due to previous limitations.
- The test expectations have been adjusted to align with the new client configuration, ensuring that these tests now pass under the updated protocol handling.
The reintroduction of these tests, with the enhanced client setup, significantly improves …
> OCPBUGS-27210: Restore HTTP/2 tests in test/extended/router

- pkg/cmd/openshift-tests/disruption/poll-service/service_controller.go
observed in https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-multiarch-master-nightly-4.16-ocp-e2e-ovn-remote-libvirt-ppc64le/1749182126944686080
/assign @JacobTanenbaum @dgoodwin
> OCPBUGS-27892: fix panic in service-poller

- test/extended/cloud_controller_manager/ccm.go
The cloud provider runs externally to the cluster in HyperShift clusters, therefore it cannot be verified within the cluster.
> NO-JIRA: Skip external cloud provider test for HyperShift clusters

- e2echart/test-risk-analysis.html
- pkg/cmd/openshift-tests/risk-analysis/command.go
- pkg/monitortestlibrary/allowedbackenddisruption/matches.go
- pkg/monitortestlibrary/allowedbackenddisruption/matches_test.go
- pkg/monitortestlibrary/allowedbackenddisruption/types.go
- pkg/monitortestlibrary/historicaldata/alert_types.go
- pkg/monitortestlibrary/historicaldata/disruption_types.go
- pkg/riskanalysis/cmd.go
- test/extended/testdata/bindata.go
Display an additional table in the spyglass risk analysis view which shows the total observed disruption for every backend, as well as it's historical percentiles observed over the past several weeks. Rows which exceed the P95 are highlighted yellow, and P99 red.
Long term we'd like this in sippy in the actual risk analysis report, however this is logistically quite tricky. Sippy does not have disruption data in it's postgres, so we'd need to (a) submit to sippy live after openshift-tests runs now with disruption data observed, (b) update sippy to efficiently compare this to percentiles without blowing bigquery costs, (c) figure out how to fit it into the report and the pr commenter without breaking any assumptions about risk analysis formatting.
For now, origin knows the historical …
> TRT-965: Add disruption to the risk analysis spyglass panel

- e2echart/test-risk-analysis.html
- pkg/riskanalysis/cmd.go
- test/extended/testdata/bindata.go
Risk analysis doesn't work at all on these jobs, and attempting to
reference the OverallRisk field in those cases was causing the
disruption portion of the html (which did work) to not be populated.
Bail out early if it looks like we didn't get a real risk analysis, and
let the disruption table render normally.
Also switch from lightred (Which doesn't actually exist) to pink.
> TRT-1480: Fix disruption analysis on /payload jobs

- test/extended/prometheus/prometheus.go
This PR is needed to migrate crio metrics to HTTPs.
https://github.com/openshift/cluster-monitoring-operator/pull/2229
> OCPNODE-2029: migrate crio metrics to https

- pkg/monitortests/kubeapiserver/legacykubeapiservermonitortests/static_pod.go
- pkg/monitortests/kubeapiserver/legacykubeapiservermonitortests/static_pod_test.go
Found in https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-baremetal-operator/399/pull-ci-openshift-cluster-baremetal-operator-master-e2e-metal-ipi-ovn-ipv6/1750255824447475712
> NO-JIRA: fix the static pod lifecycle failure test for more revisions

- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_events.go
- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_events_special.go
- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_events_special_test.go
- pkg/monitortests/node/legacynodemonitortests/pathological_events.go
- pkg/monitortests/node/legacynodemonitortests/pathological_events_test.go
This introduces `NamespacedTest()` which can be used where the `Test()` method is used if we want to split out more pathological tests by namespace.
To test, we need this test to fail on multiple namespaces:
```
[sig-cluster-lifecycle] pathological event should not see excessive Back-off restarting failed containers
```
> TRT-1452: Separate excessive Back-off restarting tests via namespace

- test/extended/builds/subscription_content.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/subscription-content/build-imagestream.yaml
- test/extended/testdata/builds/subscription-content/buildconfig-subscription-content-rhel7.yaml
- test/extended/testdata/builds/subscription-content/buildconfig-subscription-content-rhel8.yaml
- test/extended/testdata/builds/subscription-content/buildconfig-subscription-content-rhel9.yaml
- test/extended/testdata/builds/subscription-content/secret-template.txt
- test/extended/util/annotate/generated/zz_generated.annotations.go
Add end to end tests to verify we can build images that install
RHEL subscription content via `yum/dnf install`. These tests
need a fully subscribed cluster to function properly - for example,
a ROSA cluster. If the cluster is not subscribed/does not have its
SCA certificates synced via the Insights Operator, the tests are
skipped.
The test verifies the instructions in the official OpenShift
documentation, which includes copying the entitlement keys to
the build's namespace. Docs are currently being drafted in https://github.com/openshift/openshift-docs/pull/70897
> OCPBUGS-23115: Test builds with subscription content

- test/extended/networking/tap.go
Test ` [sig-network][Feature:tap] should create a pod with a tap interface [apigroup:k8s.cni.cncf.io] [Suite:openshift/conformance/parallel] ` is failing when Local Zone node is present and the node is the first in when listing the worker node list.
All edge nodes requires toleration, as this job wants to select random worker node, and not test that feature, this change will make the test to nodes with edge label (`node-role.kubernetes.io/edge`)
Ref: https://github.com/openshift/release/pull/47066
Failed job: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/47066/rehearse-47066-pull-ci-openshift-installer-release-4.14-e2e-aws-ovn-localzones/1738304268001087488
Card: https://issues.redhat.com/browse/SPLAT-1427
> SPLAT-1427: fix/sig-net: ignoring edge when listing worker nodes

- test/extended/operators/crd_must_be_stable.go
/hold
Reminder to merge this next week if https://search.ci.openshift.org/?search=has+an+unstable+version&maxAge=168h&context=1&type=bug%2Bissue%2Bjunit&name=4.16&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job is clean
/assign @JoelSpeed
> NO-JIRA: enforce only stable CRD versions accessible by default

- pkg/monitortestframework/impl.go
This problem is caused by sending to a channel (junitch) that is full. That blocked the code from finishing up.
The junitch was created with a fix limit (2*len(monitortest) in the case of CollectData). It was not expected to create more than 2 junit per monitortest. But flake case is added, one monitortest could potentially add three junit (one created by the monitor test, one for a failure and one for a success) to the channel. The channel is not processed until all monitor tests finished collecting data. Therefore, some monitortest got stuck with a full junitch and blocked.
> TRT-1445: Monitor test hangs during interrupt handling

- test/extended/router/h2spec.go
This PR introduces two updates to the HAProxy configuration and the associated test suite for the h2spec tests in test/extended/router.
1. **Update to HAProxy Configuration:**
The HAProxy configuration in `test/extended/router/h2spec.go` is updated to replace the deprecated directive `tune.ssl.capture-cipherlist-size` with `tune.ssl.capture-buffer-size`. This change is in response to deprecation warnings from HAProxy versions 2.8.5 and 2.6.13, ensuring compatibility with both versions.
2. **Removal of Known h2spec Failures for HAProxy 2.6 and 2.8:**
The h2spec tests "http2/5.4.1.2" and "http2/6.9.1.2", previously known to fail or flake in HAProxy 2.2, have been removed from the list of known failures. The removal is based on successful test runs with HAProxy versions 2.6 and 2.8, …
> NE-1444: test/extended/router: HAProxy 2.8 Compatibility Enhancements for h2spec tests

- pkg/monitortests/testframework/disruptionexternalgcpcloudservicemonitoring/cloudmonitortest.go
Just updating to a new IP given this is a new load balancer and the previous one's IP was reaped.
This LB worked on Feb 11, 2024 8:14pm EST
```
$ url=http://35.212.104.31/health
$ echo $(curl -sk -w "%{http_code}" -o response.txt -H "Audit-ID: 12345" "$url")
200```
> TRT-1477: update IP for new gcp LB

- pkg/defaultmonitortests/types.go
- pkg/monitortests/testframework/disruptionexternalgcpcloudservicemonitoring/cloudmonitortest.go
Revert of this revert: https://github.com/openshift/origin/pull/28586
Plus a commit to add the new GCP LB -- this one should not remain there.
- TODO
- I do NOT see a test in the Passed section on the prow job for `gcp-network-liveness` (but I also didn't see one in the tests for https://github.com/openshift/origin/pull/28571)
> TRT-1493: Re-introduce the GCP liveness endpoint test

- test/extended/cli/admin.go
This PR adds `--tail=100` flag in `adm node-logs --boot=0` test to reduce the generated log size that
may put a pressure on CI pod's memory.
> NO-JIRA: Pass tail flag in adm node-logs to reduce log size

- test/extended/machines/machines.go
This change updates the test to skip when the Cluster object is not found. Usually this object is not found on clusters that have been deployed using the UPI methodology, as such there is no CPMSO in the cluster.
> OCPBUGS-29614: update control plane machine set test

- pkg/monitortests/node/watchnodes/node.go
The convention is a format like `node-role.kubernetes.io/role: ""`, not `node-role.kubernetes.io: role`, however ROSA uses the latter format to indicate the `infra` role. This changes the node watch code to ignore it, as well as other potential variations like `node-role.kubernetes.io/`.
The current code panics when run against a ROSA cluster:
```
E0209 18:10:55.533265      78 runtime.go:79] Observed a panic: runtime.boundsError{x:24, y:23, signed:true, code:0x3} (runtime error: slice bounds out of range [24:23])
goroutine 233 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x7a71840?, 0xc0018e2f48})
k8s.io/apimachinery@v0.27.2/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x1000251f9fe?}) …
```
> OCPBUGS-29858: Only extract node role from properly formatted node-role label

- pkg/cmd/openshift-tests/dev/dev.go
- pkg/monitor/monitorapi/identification.go
- pkg/monitor/monitorapi/types.go
- pkg/monitortests/network/legacynetworkmonitortests/disruption.go
- pkg/monitortests/network/legacynetworkmonitortests/monitortest.go
These were mistakenly broken in the 4.14 release timeframe during the
monitortest refactor. The format of disruption intervals changed and the
way this test was looking for backend names was then broken. I've
modified the code to now better detect all disruption backends, pick the
ones we want to run these tests on (ingress and api backends), and fixed
the ordering of the case logic which was inverted and the > 50 check
could never run, because the > 20 would match first.
Dev command for running invariants against an intervals file is
partially restored, for these tests only.
`./openshift-tests dev  run-disruption-invariants --intervals-file e2e-timelines_spyglass_20240209-082358.json`
Bringing back as they will help us hunt for spatter disruption on gcp jobs.
> TRT-1506: Restore the tests looking for excess single-second disruptions

- test/extended/networking/egressip_helpers.go
Multi-arch compute clusters have an issue where the cluster version's image ref is single arch, so this change resolves the image ref without spinning up a pod.
> MULTIARCH-4160: Stop using the DetermineFromRelease function

- test/extended/operators/images.go
This PR handles release info command's output streams separately instead of merging them. Because
test does not need the data in `errOut`.
> NO-JIRA: Handle release info output streams separately

- pkg/monitortests/clusterversionoperator/legacycvomonitortests/monitortest.go
- pkg/monitortests/clusterversionoperator/legacycvomonitortests/operators.go
Fix for https://issues.redhat.com/browse/OCPBUGS-27323
> OCPBUGS-27323: Skip tests for image-registry operator with single replica

- test/extended/operators/tolerations.go
`kube-rbac-proxy-crio` is a new static pod in the `openshift-machine-config-operator` namespace. Since it is a static pod, the tolerations test needs to ignore this pod due to it tolerating all taints.
```
openshift-machine-config-operator/kube-rbac-proxy-crio-ip-10-0-112-244.us-west-2.compute.internal tolerates all taints
```
* Allow static pod tolerations (this PR): 4.16/master : Backport to EUS 4.14
* MCO Kube-Rbac-Proxy Static pods 4.16/master : https://github.com/openshift/machine-config-operator/pull/4175 : Backport to EUS 4.14
* Create an upgrade edge after all backports merge
***After all the above backports are merged, then***
* Change the Monitoring Operator to use port 9637 (with client certificates) : https://github.com/openshift/cluster-monitoring-operator/pull/2257 : This PR …
> OCPNODE-2099: add kube-rbac-proxy-crio toleration change

- pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
Need additional time to cleanup based on [observed failures](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.16-upgrade-from-stable-4.15-e2e-azure-sdn-upgrade/1765435689505132544/artifacts/e2e-azure-sdn-upgrade/gather-extra/artifacts/pods/openshift-cloud-controller-manager_azure-cloud-controller-manager-54cd8d5744-8f8nb_cloud-controller-manager.log)
`I0306 20:22:36.751700       1 azure_metrics.go:115] "Observed Request Latency" latency_seconds=1057.030765794 request="services_ensure_loadbalancer_deleted" resource_group="ci-op-mjrwbm2m-9d969-9z25b-rg" subscription_id="72e3a972-58b0-4afc-bd4f-da89b39ccebd" source="e2e-service-lb-test-j4ggk/service-test" result_code="succeeded"`
> trt-1538: Bump context timeout to 20 minutes

- test/extended/machines/machines.go
This change updates the check for the machine api operator to inspect the number of machines that might be returned. If zero machines are returned it indicates that the cluster has the CRD but contains no instances, in these cases we want to skip the test.
> OCPBUGS-29614: update skipUnlessMachineAPIOperator function

- pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
- pkg/monitor/monitor.go
- pkg/monitortests/imageregistry/disruptionimageregistry/monitortest.go
- pkg/monitortests/network/disruptionpodnetwork/monitortest.go
- pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go
Additional timeout bumps for
`[Jira:"Networking / router"] monitor test service-type-load-balancer-availability cleanup `
> trt-1538: additional timeout bumps

- test/extended/util/framework.go
Fix for [MULTIARCH-4352](https://issues.redhat.com/browse/MULTIARCH-4352). Private key was exposed in the e2e logs as part of the pod dump. Added code to replace the private key with XXXX
> MULTIARCH-4352: Censor private key from pod dump logs

- pkg/monitortests/testframework/watchevents/event.go
There was a second copy of the nodeRoles function that has the same problem, where non-standard format of the node-role label in ROSA causes a panic.
See 330feda5d5a2aecfec7ec14f42024cd656cf3fd3.
I would refactor this to move the function to util and share it between both, but for backportability I fixed it in-place.
> OCPBUGS-30604: fix panic on non-standard node-role labels

- test/extended/cli/idle.go
- test/extended/idling/idling.go
- test/extended/router/idle.go
We have started fully relying on service's annotation instead of endpoints in oc idle. 
This PR is prerequisite of https://github.com/openshift/oc/pull/1692
> WRKLDS-1076: oc idle: Check idling annotation in services not endpoints

- pkg/defaultmonitortests/types.go
- pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
This PR adds a monitor test that requires the existence of the `openshift.io/required-scc` annotation on all platform workloads (workloads that belong to `openshift*`, `kube-*` and `default` namespaces).
If the annotation is missing, the test suggests an SCC to be pinned using the annotation, based on the following:
- suggested SCC is the one that was used to admit the workload, provided that it is a default SCC and not a custom one
- if it's a custom SCC, the test cannot suggest any; the developer must determine the appropriate SCC
- since SCC admission is disabled for runlevel 0/1 namespaces, the test won't suggest any SCC for their workloads; the developer must determine the appropriate one
At its current state, the test is implemented as a flake, until we've pinned SCCs to all …
> AUTH-483: Add a monitor test to check the existence of required-scc annotation in platform workloads

- test/extended/cpu_partitioning/crio.go
added a check for static containers during the cpu affinity comparison between the host and expected value, this is done to account for the fact that static pods do not get altered by the workload webhook and on realtime deployments we might get CPU affinity changes for static pods that do not go through the workload partitioning feature
> OCPBUGS-31074: fix: add check for static container

- test/extended/operators/server_side_apply_examples.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/framework.go
/assign @stevekuznetsov 
fields clear when not set.
> NO-JIRA: add simple test for server side apply to demonstrate field clearing

- pkg/defaultmonitortests/types.go
- pkg/monitortests/testframework/disruptionexternalawscloudservicemonitoring/cloudmonitortest.go
TODO:
Hit an endpoint (on a VM behind a load-balancer in aws) to test aws connectivity during test runs in a way that (attempts to) mimic pods in an Openshift cluster.  This way we can compare disruption problems noted in TRT-1466.
Here's a test to see if the LB is working on AWS (should return 200):
```bash
url=http://trt-openshift-tests-endpoint-lb-1161093811.us-east-1.elb.amazonaws.com/health
echo $(curl -sk -w "%{http_code}" -o response.txt -H "Audit-ID: 12345" "$url")
```
The VM/LB has been up for days in the TRT aws account:
```
$ date
Sun Feb 18 19:28:25 EST 2024
$ url=http://trt-openshift-tests-endpoint-lb-1161093811.us-east-1.elb.amazonaws.com/health
$ echo $(curl -sk -w "%{http_code}" -o response.txt -H "Audit-ID: 12345" "$url")
200
```
> TRT-1493: Add monitortest for cloud function on aws

- test/extended/storage/csi_snapshot_controller_operator.go
- For HyperShift the CSISnapshot controllers runs on management cluster, so we needs to skip related tests.
**Flake records:** https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn-conformance-serial/1759019959612084224
> NO-JIRA: Add skip condition for Cluster-CSI-Snapshot-Controller-Operator feature

- pkg/monitortests/testframework/watchevents/event.go
I believe that a substantially failing job like https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-ovn-dualstack/1758641985364692992 yields a rather large (38M) `build-log.txt` and browsing to that job takes a long time and consumes an exorbitant amount of RAM (4.6G in my case on chrome) assuming you can successfully load it.  Removing these logs could help shrink that file and speed up the prow job loads in general.
> TRT-1559:Remove two sets of logs to bring build-log.txt size down

- test/extended/prometheus/prometheus.go
Managed services alerts are missing runbooks, or have invalid severity, summary, or descriptions. Adds temporary exceptions while they're being fixed.
> OSD-21709: Add temporary exceptions for managed services alerts

- pkg/defaultmonitortests/types.go
- pkg/monitortests/testframework/disruptionexternalazurecloudservicemonitoring/cloudmonitortest.go
Hit an endpoint (on a VM behind a load-balancer in azure) to test azure connectivity during test runs in a way that (attempts to) mimic pods in an Openshift cluster. This way we can compare disruption problems noted in TRT-1466.
This is just a test using an LB/VM in a personal Azure account.
TODO:
The new resource group is called `do-not-delete-trt-liveness` at portal.azure.com.
> TRT-1494: Add monitortest for cloud function on azure

- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_events.go
- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_events_test.go
We were outputting From: To: timestamps, which was always 1s implying
the event happened 20+ times in a second, which was entirely untrue. We
don't really know the start time for the event, and even the observed
time is a little sketchy. Switch to just showing the time we received
the event with the count being displayed for now.
> OCPBUGS-30267: Clarify a misleading message in patho event failures

- examples/image-streams/image-streams-centos7.json
- test/extended/testdata/bindata.go
- test/extended/testdata/cmd/test/cmd/testdata/image-streams/image-streams-centos7.json
Images' `latest` tag and auto built mechanisms have been permanently disabled in `quay.io/centos7` repository. 
This PR modifies these images to use `centos7` tag instead of latest. So that cmd/images.sh tests will continue passing. 
But there is no indication whether, at some point in the future, these images or this tag will be removed also or not. I try to remove unit tests entirely to overcome this issue https://github.com/openshift/oc/pull/1717 but maybe for e2e tests, we can give one more try to continue with `centos7` tag, until it is removed.
> OCPBUGS-31484: Use centos7 tag instead of latest for cmd images tests

- pkg/monitortests/etcd/legacyetcdmonitortests/etcd.go
- pkg/monitortests/etcd/legacyetcdmonitortests/monitortest.go
We've found a subset of jobs in a specific environment showing extremely
unhealthy etcd pod logs throughout the run, indicating disk IO issues
for etcd.
Add a test to help identify these runs, and clearly communicate with
engineers looking at the failures to help them notice that etcd is
unhealthy and this can cause a multitude of other failures.
> OCPBUGS-31492: Add a test that will fail on over 10k etcd took too long messages

- test/extended/builds/multistage.go
- test/extended/util/image/image.go
During transition period, when we're updating RHEL versions for oc, it's possible that tools and cli images will be on different levels of RHEL. Whereas cli and must-gather will match. To prevent problems in tests use cli & must-gather in multi-stage build tests.
/assign @ardaguclu
> OCPBUGS-20097: Switch to use must-gather image in build multi-stage

- pkg/resourcewatch/operator/starter.go
so we can debug when particular imagepullsecrets were added.
> NO-JIRA: add service accounts to resourcewatcher

- pkg/defaultmonitortests/types.go
- pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
Reverts #28659 in order to reapply #28589
Excludes `openshift-must-gather-*` namespaces from the `required-scc` monitor tests.
> AUTH-483: Reapply #28589

- pkg/monitortestframework/impl.go
- pkg/monitortestframework/panic.go
- pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go
This test is failing periodically in some cases and we can't see when
the problem is occurring to correlate with logs or intervals because the
framework doesn't log much of anything.
> OCPBUGS-31868: Add debug logging for SLB monitortest cleanup

- images/tests/Dockerfile.rhel
Adding this label so that `/manifests` dir is pulled into the ReleaseInfo.  This is necessary to include the number of tests per feature.
/assign @wking 
Trevor: does this have any other side-effects?
> NO-JIRA: add to the operator list

- pkg/clioptions/clusterdiscovery/provider.go
- pkg/monitortests/cloud/azure/metrics/monitortest.go
- pkg/monitortests/monitoring/statefulsetsrecreation/monitortest.go
- test/extended/operators/routable.go
- test/extended/router/metrics.go
According to what was discussed last month, fix:
- openshift-tests crashing when executing over MicroShift.
- Port router tests skip patches from MicroShift.
- Port monitor tests skip patches from MicroShift.
/cc @dgoodwin
/cc @stbenjam
> USHIFT-2985: Fix MicroShift crash and router tests skipping

- pkg/defaultmonitortests/types.go
- pkg/monitortests/clusterversionoperator/terminationmessagepolicy/monitortest.go
Found while trying to debug a pod backoff problem.  We're lacking the logs.
> OCPBUGS-28230: enforce termination message policy on all platform pods

- images/tests/Dockerfile.rhel
This is a preparation to the move to rhel9. For rhel8, there was an openstack-16.1 repo available for ppc64le. For rhel9 openstack 17.1, this seems to be not the case.
> OCPBUGS-31860: ppc64le without python-cinder

- test/extended/builds/multistage.go
/assign @ardaguclu 
Additional followup to #28687
> OCPBUGS-20097: Switch to use cli image, as the scratch image

- test/extended/cpu_partitioning/managed.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
updating the test to reflect change in the webhook allowing pinned workloads in nonpinned namespaces with a warning annotation
See more info https://issues.redhat.com/browse/CNF-10581
> OCPBUGS-32485: upkeep: update test pinned workloads

- test/extended/deployments/util.go
- test/extended/testdata/bindata.go
- test/extended/testdata/deployments/tag-images-deployment.yaml
`tools:latest` image takes 922792256 bytes (i.e. ~1GBi). So that there is no reason to allocate memory size to 3Gi, besides this test fails on the cluster having limited resources. This PR reduces the allocated memory size to 1.4Gi. This value has been chosen to have a safety gap in the cases where tools image's size is increased. 
Moreover, there are numerous deploymentconfig deprecated warnings stemming from deploymentconfig status check function that is executed per 200ms, this PR increases period to 500ms in order to reduce the count of warning messages.
> OCPBUGS-31030, OCPBUGS-31032: Reduce deploymentconfig test 3GBi memory size to reasonable

- e2echart/e2e-chart-template.html
- e2echart/non-spyglass-e2e-chart-template.html
- test/extended/testdata/bindata.go
Two quality-of-life improvements for e2e charts:
* wrap tooltips in e2e chart to make sure that tooltips don't overflow X when a long label is used.
* copy segment label contents to clipboard when its clicked
> OCPBUGS-32484: chart template: limit tooltip width to first word

- .ci-operator.yaml
- images/hello-openshift/Dockerfile.rhel
- images/tests/Dockerfile.rhel
> OCPBUGS-20097: Migrate tools image to RHEL9

- test/extended/builds/failure_status.go
- test/extended/testdata/bindata.go
- test/extended/testdata/cmd/test/cmd/images.sh
This should be a manual cherry-pick of https://github.com/openshift/origin/pull/28725, although the reverse is true (because issues are only happening on 4.15). In any case, these two PRs should be identical.
> [release-4.15]: OCPBUGS-32554: Also rely on oomkilled exit code 137 in build test

- test/extended/etcd/leader_changes.go
- test/extended/prometheus/client/via_route.go
- test/extended/prometheus/prometheus.go
- test/extended/prometheus/storage.go
- test/extended/router/metrics.go
- test/extended/util/conditions.go
- test/extended/util/prometheus/helpers.go
Clean up tests that rely on the existence of a legacy service account API token secret for the `prometheus-k8s` service account.
> OCPBUGS-31589: e2e: use bound API token for prometheus-k8s SA

- test/extended/builds/pipeline_origin_bld.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/jenkins-pipeline/jenkins-ephemeral.json
- test/extended/testdata/builds/jenkins-pipeline/jenkins-rhel.yaml
Update the JenkinsPipeline build strategy test to use an in-tree template to deploy Jenkins during the test setup phase. This decouples the test from the Samples Operator, which is officially deprecated in 4.16 and will be phased out in the future. Previously, this test implicitly relied on the Samples Operator to install the Jenkins ephemeral template.
> OCPBUGS-32293: Use In-Tree Template for Jenkins

- test/extended/builds/failure_status.go
- test/extended/testdata/bindata.go
- test/extended/testdata/cmd/test/cmd/images.sh
In 4.15, when pod is killed due to insufficient memory, it raises an `Error` status rather than expected `OOMKilled`. This seems to be a bug in upstream but in order to unblock the presubmit jobs, we need to have a stop-gap solution. This PR also checks the `Error` status with the 137 exit code which corresponds to the OOMKilled.
Additionally, mariadb:10.3 version seems to be problematic in 4.15, so that this PR drops mariadb:10.3
> OCPBUGS-32477: Also rely on oomkilled exit code 137 in build test

- pkg/alerts/allowed_conformance.go
- pkg/alerts/allowed_upgrade.go
- pkg/alerts/types.go
- pkg/monitortests/testframework/legacytestframeworkmonitortests/alerts.go
- test/extended/util/prometheus/helpers.go
- test/extended/util/prometheus/helpers_test.go
This looks to have been partially implemented some time ago and thus has been broken ever since.
> OCPBUGS-32923: Fix allowed firing alerts not triggering

- pkg/alerts/allowed_conformance.go
- pkg/alerts/allowed_upgrade.go
- pkg/alerts/types.go
- pkg/monitortests/testframework/legacytestframeworkmonitortests/alerts.go
- test/extended/util/prometheus/helpers.go
- test/extended/util/prometheus/helpers_test.go
Reverts openshift/origin#28747
False alarm, this wasn't the source of the problem and the failures were likely real. Thus no fix commit layered on top.
> Revert "TRT-1625: Revert #28741 "OCPBUGS-32923: Fix allowed firing alerts not triggering""

- test/extended/cli/builds.go
For HyperShift, the api-server of the HostedCluster is not x433, so this PR is submitted to adjust the regular expression for obtaining the api-server.
> NO-JIRA: Adjust the method of get the apiServer

- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
during single node deployments knowing the window between graceful shutdown end and readyz start is helpful to determine when connection refused events are expected. This update makes use of a generated buffer interval between the time the graceful shutdown signal is received and some specified buffer of time to account for the API server coming back up.
> OCPBUGS-26440: feat: add buffer interval for SNO pathological events

- test/extended/router/http2.go
Use a unique certificate for each route in the "The HAProxy router should pass the http2 tests" extended test.
To fix OCPBUGS-29373, OpenShift router will be changed to configure HAProxy not to negotiate HTTP/2 with TLS ALPN for routes that share certificates. This change in the router causes the aforesaid extended test to fail because it uses the same certificate for two test routes that are used to verify HTTP/2 compliance.
After this PR, the extended tests should pass with the router change.
> OCPBUGS-29373: test/extended/router/http2: Use unique certs

- test/extended/router/stress.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Add "The HAProxy router converges when multiple routers are writing conflicting upgrade validation status" test which validates router converge when writing conflicting status in a scenario that uses multiple conditions.
Previously, we tested conflicting status fields (hostname), but don't have a test for conflicting status. This test add logic that exercises new logic in the router for the Upgrade Validation plugin.
Also, this updates all of the router stress.go status tests write watch logic to use an informer, which allows for comparison of the old and new route objects along with the ability to start the informer in a separate go routine.
> OCPBUGS-26498: Add test for UpgradeValidation contention

- test/extended/builds/start.go
- test/extended/builds/webhook.go
Starting in OCP 4.16, the `system:webhook` ClusterRole will not be granted to anonymous users by default. This will break most systems that use BuildConfig webhooks to trigger builds, since many can't be add an OpenShift auth token to their HTTP headers (ex: GitHub). Only new installations will be impacted; upgrades to 4.16 will continue to support unauthenticated BuildConfig webhooks.
This test update verifies that BuildConfig webhooks can be triggered using a namespace-scoped RoleBinding for the `system:unauthenticated` group. RoleBindings are preferable to ClusterRoleBindings as they limit unauthenticated API calls to specific namespaces, reducing the potential attack surface.
Use of BuildConfig webhooks should be discouraged in favor of Pipelines as Code, which has more robust …
> OCPBUGS-33041: Add RoleBinding for BuildConfig Webhooks

- pkg/defaultmonitortests/types.go
- pkg/monitortests/monitoring/disruptionmetricsapi/monitortest.go
This should ensure the availability of the Metrics API during e2e tests including upgrades.
Thus it should also help with https://issues.redhat.com/browse/MON-3539.
The correctness of the API: whether the right/expected content is returned, should be tested elsewhere (we already have tests for that in CMO, and the HPA tests already make use of that etc.). This tests only check the availability.
- Got inspired by the existing availability tests.
- Maybe this could be generalized for all the aggregation layer?
> MON-3513: Add availability test for Metrics API

- pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go
- test/extended/util/client.go
[OCPBUGS-18534](https://issues.redhat.com/browse/OCPBUGS-18534)  
Monitor test changes to fix loadbalancer issue in PowerVS platforms.
Test checks if platform is either a PowerVS or IBMCloud cluster and then runs function `checkHostnameReady` where it debugs the master node of the cluster and verifies the hostname is active before hitting through the load balancer
> OCPBUGS-18534: monitor test fix to wait before connecting to a non-existent dns on PowerVS and IBMCloud platforms

- test/extended/cpu_partitioning/crio.go
- test/extended/cpu_partitioning/managed.go
- test/extended/cpu_partitioning/utils.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
workload partitioning now supports cpu limits in resources added a new test and updated existing ones to validate it.
added test to check annotations and resources have been altered updated existing crio check to also validate cpu limits via quota settings
> OCPEDGE-812: feat: add tests for cpu limits on workload partitioning

- pkg/monitortests/clusterversionoperator/terminationmessagepolicy/monitortest.go
We're down to a few violations (first couple hundred fixed).  This updates the test to prevent new ones from being added.
> NO-JIRA: enforce termination policy

- pkg/monitortests/testframework/disruptionexternalawscloudservicemonitoring/cloudmonitortest.go
- pkg/monitortests/testframework/disruptionexternalazurecloudservicemonitoring/cloudmonitortest.go
- pkg/monitortests/testframework/disruptionexternalgcpcloudservicemonitoring/cloudmonitortest.go
These monitors are permafailing in MicroShift as their requirements are not met in MicroShift:
https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/periodic-ci-openshift-microshift-main-e2e-aws-ovn-ocp-conformance
/cc @dgoodwin
> USHIFT-3133: Skip cloud provider disruption monitors for MicroShift

- pkg/clioptions/suiteselection/feature_filter.go
- pkg/clioptions/suiteselection/suite_flags.go
MicroShift does not have support for FeatureGate API. Exclude all tagged tests in case the cluster does not have explicit support for FeatureGate API.
> USHIFT-3142: Automatically exclude FeatureGate tagged tests

- pkg/testsuites/standard_suites.go
- test/extended/networking/ipsec.go
It is found that the IPsec tests need extra time to rollout different IPsec modes and finish executing each test in CI cluster. Hence this PR increases those timeout values accordingly.
Sample runs:
- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/50687/rehearse-50687-pull-ci-openshift-cluster-network-operator-master-e2e-aws-ovn-ipsec-serial/1788123460904423424
- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/50687/rehearse-50687-pull-ci-openshift-cluster-network-operator-release-4.16-e2e-aws-ovn-ipsec-serial/1788123460988309504
- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/50687/rehearse-50687-pull-ci-openshift-origin-master-e2e-aws-ovn-ipsec-serial/178812 …
> SDN-4168: Increase IPsec timeout parameters

- go.mod
- pkg/clusterversion/doc.go
- pkg/clusterversion/upgrade.go
- pkg/clusterversion/upgrade_test.go
- test/extended/builds/start.go
- test/extended/builds/webhook.go
Updating the build suite test to verify the unautenticated build webhook behavior on upgrade. For clusters upgrading from v4.15 or earlier to v4.16, unauthenticated webhooks should continue to be allowed. For clusters that upgrade from v4.16 to a later version, unauthenticated webhooks should be denied by default.
> OCPBUGS-33378: Verify Build Webhooks on Upgrade

- pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go
> OCPBUGS-18534: Pass namespace in function checkHostnameReady for monitortest

- pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go
- test/extended/util/client.go
Added logrus to fix #28776 of cherry pic #28739 for release-4.15 branch
> #28776 FIX [release-4.15] OCPBUGS-33368: monitor test fix to wait before connecting to a non-existent dns on PowerVS and IBMCloud platforms

- test/extended/etcd/hardware_speed.go
the following test is for peer communication for etcd, this is not valid for single node and can cause disruption increases.
/assign @dusk125
> OCPEDGE-1101: skip etcd test for hardware speed on sno

- test/extended/testdata/bindata.go
- test/extended/testdata/cmd/test/cmd/quota.sh
The `quota.sh` testcase is making assumptions on how many secrets are automatically created in namespaces, and this number is lower in OCP 4.16.
Context provided by Luis Sanchez:
> As of OCP 4.11, service account API token secrets (now referred to as “legacy”) were no longer generated automatically for each service account.
> All users were supposed to migrate to using the TokenRequest API.
>  Unfortunately, the integrated image registry was also generating a legacy service account API token for its own use, and some users started to accidentally pick up the token intended for the image registry and missed migrating to the TokenRequest API.
> Starting in v4.15, if the image registry is not enabled, the tokens will not be generated. The image registry is still enabled by default, so again …
> NO-JIRA: quota.sh: 4.16 no longer creates legacy API tokens

- test/extended/networking/egress_firewall.go
- test/extended/testdata/bindata.go
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-wildcard-test.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
e2e test case covering integration of CoreDNS and EgressFirewall as proposed in the [enhancement](https://github.com/openshift/enhancements/pull/1335)
> CFE-853: e2e test case for DNSNameResolver and EgressFirewall integration

- pkg/test/ginkgo/cmd_runsuite.go
This will help with metal failures like https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-kubernetes-1953-nightly-4.17-e2e-metal-ipi-ovn-bm/1791720908369432576 because the healthz handler changed its name.
/assign @dinhxuanvu
> API-1783: Conditionally skip tests to help with k8s 1.30

- pkg/monitortests/clusterversionoperator/terminationmessagepolicy/monitortest.go
I believe these are all fixed now and we should no longer need to be excepted. Down with exceptions!
> NO-JIRA: Drop Cluster Infra related exceptions from termination message policy tests

- test/extended/operators/server_side_apply_examples.go
> NO-JIRA: fix: update test to use IsSingleNode func

- test/extended/util/framework.go
The current regex parser fails to match when there is a new line. Have fixed it to match any whitespace/non whitespace character. Mocked a negative test run locally and verified that it works fine and pasted the results below. The private key is now censored as XXXX as shown below
BEFORE:
```
`Environment:
POD_NAMESPACE:        e2e-test-unprivileged-router-7qzms (v1:metadata.namespace)
DEFAULT_CERTIFICATE:
-----BEGIN CERTIFICATE-----
**<Certificate is displayed here, its not censored in the logs, I have just not copied it here for security reasons>**
-----END CERTIFICATE-----
-----BEGIN PRIVATE KEY-----
**<Private key is displayed here, I have just not copied it here for security reasons>**
-----END PRIVATE KEY-----
Mounts:
/var/run/secrets/kubernetes.io/serviceaccount from …
```
> OCPBUGS-33944: Fix regex parser for censoring private key

- test/extended/etcd/hardware_speed.go
The GA of this feature has merged [1] so this check is no longer needed.
[1] https://github.com/openshift/api/pull/1844
> ETCD-578: remove Tech Preview check from etcd profiles e2e test

- pkg/monitortests/node/kubeletlogcollector/node.go
- pkg/monitortests/node/kubeletlogcollector/node_test.go
This was causing null locators, looks like podUID got quotes somewhere along the way.
> TRT-1653: Fix regexes for now quoted podUID in system journal log parsing

- pkg/monitortests/testframework/alertanalyzer/alerts.go
When observing the number of thanos connections and comparing to the number of platform monitoring stack replicas, the thanos connections to the user-workload-monitoring stack are not accounted for. This will cause metric collection to fail if user-workload-monitoring is enabled.
This fixes the query to only focus on the connections specifically to the platform monitoring stack, as the type of data collection the monitoring tests are doing focuses on platform metrics as opposed to ones from the UWM stack.
> OCPBUGS-34403: Only look for thanos connections to platform monitoring stack

- pkg/monitortests/etcd/etcdloganalyzer/monitortest.go
- pkg/monitortests/node/kubeletlogcollector/node.go
- pkg/monitortests/testframework/e2etestanalyzer/e2etest.go
KubeletLog, EtcdLog, EtcdLeadership, and E2ETest intervals all should
have had this flag true.
This flag will hopefully soon be used to determine what gets shown in a
more dynamic UI.
> TRT-1218: Add the display flag for interval Sources that should have them

- pkg/monitor/monitorapi/types.go
- pkg/monitortestlibrary/platformidentification/upgrade.go
- pkg/monitortests/clusterversionoperator/legacycvomonitortests/monitortest.go
- pkg/monitortests/clusterversionoperator/legacycvomonitortests/operators.go
- pkg/monitortests/clusterversionoperator/legacycvomonitortests/operators_test.go
- pkg/monitortests/node/legacynodemonitortests/kubelet.go
- test/e2e/upgrade/upgrade.go
For this test: `[bz-%v] clusteroperator/%v should not change condition/Available]`:
* For non-upgrade jobs, fail when operator goes to Available=False
* For upgrade-jobs, fail when operator goes to Available=False unless it's during an upgrade window and the condition lasts for less than 10 minutes.
Once the PR where [storage operator stops reporting Available status](https://github.com/openshift/cluster-storage-operator/pull/456) merges, we can remove the exception for it.
> TRT-1576: Fail if operator has Available=False unless in upgrade window

- pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go
fix "--to-namespace" to "--to-namespace="
> OCPBUGS-33368: [release-4.15] monitor test service-type-load-balancer-availability setup fails frequently in 4.14 & 4.15 PowerVS CI jobs

- test/extended/etcd/etcd_storage_path.go
Add these resources to etcd test data:
resource.k8s.io/v1alpha2, Resource=resourceslices
resource.k8s.io/v1alpha2, Resource=resourceclassparameters 
resource.k8s.io/v1alpha2, Resource=resourceclaimparameters
> OCPBUGS-34666: Update etcd test data for 1.30 release

- test/extended/storage/driver_configuration.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
To pass `ci/prow/verify` job in openshift/api tests in origin have to be annotated with `OCPFeatureGate` or `FeatureGate`.
Documented here: https://github.com/openshift/api?tab=readme-ov-file#defining-featuregate-e2e-tests
> STOR-1839: correct feature gate annotation for vsphere snapshot test

- pkg/monitortestframework/impl.go
Logging this as an error can confuse users grepping logs to understand why a job failed, and leading them to investigate something that's not a problem. If a particular monitor isn't supported, then we should just log it as a warning.
```
ERRO[0352]   Finished CollectData for [Jira:"kube-apiserver"] monitor
test apiserver-availability collection with not-supported error
error="not supported: namespace openshift-oauth-apiserver not present"
```
> OCPBUGS-34448: monitortestframework: unsupported monitors should warn, not error

- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
This was limited to secrets, there are others including a new bundle in
https://github.com/openshift/cluster-etcd-operator/pull/1271. Open the
regex up to match more, and this has it's own test which only adds a
flake threshold, but keeps the 20 fail threshold.
> ETCD-606: Open up the RequiredInstallerResourcesMissing test to more resources.

- pkg/monitor/monitorapi/types.go
- pkg/monitortestlibrary/platformidentification/upgrade.go
- pkg/monitortests/clusterversionoperator/legacycvomonitortests/monitortest.go
- pkg/monitortests/clusterversionoperator/legacycvomonitortests/operators.go
- pkg/monitortests/clusterversionoperator/legacycvomonitortests/operators_test.go
- pkg/monitortests/node/legacynodemonitortests/kubelet.go
- test/e2e/upgrade/upgrade.go
Reverts openshift/origin#28847
For this test: [bz-%v] clusteroperator/%v should not change condition/Available]:
* For non-upgrade jobs, fail when operator goes to Available=False
* For upgrade-jobs, fail when operator goes to Available=False unless it's during an upgrade window and the condition lasts for less than 10 minutes.
Exceptions:
* authentication operator is affected by etcd performance issues
* image-registry is affected by other tests that cause all image-registry replicas to go down
For the above exceptions, their tests still run but they will flake as they did before this PR.
Testing tasks:
* see [/payload for azure](https://pr-payload-tests.ci.openshift.org/runs/ci/d8511d30-281a-11ef-9083-d014afac8f40-0)
* see [/payload for techpreview …
> Revert "TRT-1691: Revert #28735 "TRT-1576: Fail if operator has Available=False unless in upgrade window""

- test/extended/router/http2.go
For hypershift agent CI, the cluster is private. We configured the proxy but didn't apply it, so we submitted a PR.
> OCPBUGS-35535: add Proxy config

- test/extended/router/h2spec.go
- test/extended/router/http2.go
It's been a long time since we disabled these tests on AWS. I have been running the http2 tests on AWS all week and I haven't run into the issue once. Let's re-enable the http2 x AWS tests for better coverage.
This PR also addresses an intermittent issue encountered in AWS environments during the router's h2spec conformance tests. The challenge involved slower hostname resolution within the cluster, resulting in frequent timeouts. Notably, AWS exhibited slower resolution times compared to Azure or GCP, hinting at potential differences in DNS handling.
The solution implemented in this PR focuses on resolving the hostname on the test host before initiating the h2spec tests within the cluster. This adjustment has resulted in a remarkable improvement in test execution speed, with the h2spec …
> OCPBUGS-26601: Re-enable test/extended/router/http2 tests on AWS

- test/extended/builds/contextdir.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/test-context-build.json
- test/extended/util/framework.go
OpenShift-Samples operator still points to stale image versions. With the sample operator deprecated with OCP v4.16, these non-existing image references lead to test failures. This commit eliminates the dependency on the samples operator for importing the ruby IS, and instead creates a custom ruby image stream.
> OCPBUGS-33486: Removes dependency on samples operator images

- test/extended/router/h2spec.go
- test/extended/router/http2.go
Reverts #28515 ; tracked by https://issues.redhat.com/browse/OCPBUGS-36187
The HAProxy router should pass the http2 tests failing for aws
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:
```
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn-upgrade 10
```
CC: @frobware
<div align="right">
PR created by <a …
> OCPBUGS-36187: Revert #28515 Re-enable test/extended/router/http2 tests on AWS"

- pkg/monitor/monitorapi/types.go
- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
during single node upgrades we run into errors when the kube-apiserver is progressing that are expected updating the pathological matcher to account for expected errors during kube-apiserver installer progressing
> OCPEDGE-800: feat: add SNO upgrade consideration during pathological errors

- pkg/testsuites/standard_suites.go
- test/extended/dr/cert_rotation.go
- test/extended/dr/common.go
- test/extended/dr/recovery.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This adds the following fixes:
* manual CA rotation does not need openshift-config signers anymore
* fixing the dynamic cert rotation by selecting a node that's actually alive
* recreating the trust bundle
* move to a dedicated test suite to not impact recovery tests
> ETCD-611: update cert rotation tests

- pkg/monitortestlibrary/allowedalerts/watchdog.go
the logic for skipping watch dog check on sno upgrade needs to be inverted since FromRelease will be populated with a string version when the jobtype is a single node upgrade
> NO-JIRA: fix: update skip logic for watchdog

- test/extended/cpu_partitioning/crio.go
Reverts openshift/origin#28854
The issue in `runc` has been resolved and the latest nightly includes the RHCOS version with the updated `runc` package.
> OCPBUGS-34902: Revert "NO-JIRA: test: skip crio test for rt runs"

- test/extended/networking/egress_firewall.go
Updated agnhost image tag to fix #28746 of cherry pic #28408 for release-4.15 branch
> #28746 FIX [release-4.15] OCPBUGS-33023: update egressFWTestE2E image which contains ping binary

- test/extended/networking/egress_firewall.go
Updated agnhost image tag to fix #28745  of cherry pic #28408 for release-4.14 branch
> #28745 FIX [release-4.14] OCPBUGS-33022: update egressFWTestE2E image which contains ping binary

- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
- pkg/monitortests/testframework/watchevents/event.go
library-go emits events when cert rotation happens, these should be displayed as interesting events.
[Example](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/release-openshift-origin-installer-launch-gcp-modern/1780541177255170048/artifacts/launch/openshift-e2e-test/artifacts/junit/e2e-timelines_everything_20240417-115106.html), filter by Interesting Events
> API-1802: watchevents: add cert rotation events

- test/extended/etcd/hardware_speed.go
Shorten stabilization time from 5 minutes to 2 minutes
> OCPBUGS-36672: Shorten stabilization time for etcd profiles test

- test/extended/storage/driver_configuration.go
We no longer store vSphere configuration in a ConfigMap.
> STOR-1961: Fix vSphereDriverConfiguration tests

- test/extended/kubevirt/migration.go
- test/extended/kubevirt/services.go
- test/extended/kubevirt/util.go
- test/extended/networking/egress_firewall.go
In case the cluster under test is an HCP/HyperShift cluster of the kubevirt provider, and the management cluster is running on Azure, ICMP responses from outside of the cluster to the guest cluster are getting blocked. Thus, skipping the ping tests in that case, in addition to the existing exception.
This blocks https://github.com/openshift/release/pull/52508 from passing a full conformance test with Azure infrastructure.
> NO-JIRA: egressfirewall: skip ping tests in case of hypershift kubevirt on Azure infra

- pkg/monitortests/network/disruptionserviceloadbalancer/monitortest.go
- test/extended/util/client.go
Added logrus to fix #28775 of Cherry pick [#28739](https://github.com/openshift/origin/pull/28739) for release 4.14 branch
> #28775 FIX [release-4.14] OCPBUGS-33367: monitor test fix to wait before connecting to a non-existent dns on PowerVS and IBMCloud platforms 

- test/extended/util/client.go
Follow up for https://github.com/openshift/origin/pull/28939.
To resolve failing e2e in https://github.com/openshift/cluster-version-operator/pull/1066.
> no-jira: e2e: check for deployer RB only when DeploymentConfig is enabled

- test/extended/cli/admin.go
- test/extended/cli/builds.go
- test/extended/templates/templateinstance_readiness.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
There are more tests that deploy DeploymentConfig when running. They need to be marked as [apigroup:apps.openshift.io] dependent so they can be skipped when DeploymentConfig api is not installed.
To skip the failing e2e tests in https://github.com/openshift/cluster-version-operator/pull/1066.
> no-jira: e2e: mark tests as [apigroup:apps.openshift.io] dependent

- test/extended/builds/contextdir.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/test-context-build.json
- test/extended/util/framework.go
OpenShift-Samples operator still points to stale image versions. These non-existing image references lead to test-failures. This commit eliminates the dependency on samples operator for importing the ruby IS, and instead creates a custom ruby imageStream.
Manual cherry-pick of #28927
> [release-4.14] OCPBUGS-36800: Removes dependency on samples operator images

- test/extended/machines/display_reboots_pod.yaml
This PR fixes a bug within https://github.com/openshift/origin/pull/28884 `fix the node reboot test to actually run`. 28884 correctly changed the logic of the pod to propagate bash errors, but [missed](https://github.com/openshift/origin/pull/28884/files#diff-874b016393cfee8472299a3f16736fbe9da4973c3a9daed5b1dd00e7f72e1b2fR27) that journalctl with the '-g' option for grep can return an error if no matches are found. In this case, the matches are reboot messages. So if a machine has never rebooted, then the pod would fail incorrectly.
This PR fixes the errors in CI for the test `Managed cluster should verify that nodes have no unexpected reboots`.
> OCPBUGS-35880: fix pod not returning success on 'Managed cluster should verify that nodes have no unexpected reboots'

- pkg/test/ginkgo/test_suite.go
https://github.com/openshift/kubernetes/pull/2020#issuecomment-2228519173
> NO-ISSUE: Use external binary name on retry

- cmd/openshift-tests/openshift-tests.go
- go.mod
- pkg/cmd/openshift-tests/images/images_command.go
- pkg/cmd/openshift-tests/render/test-report/render_test_report.go
- pkg/cmd/openshift-tests/version/version.go
- pkg/cmd/util.go
Currently it's not so easy to figure out what version of openshift-tests is actually being run. Not all commands log it.
Adds a dedicated `version` command and ensures it's always printed out on invocation as well.
> OCPBUGS-37675: Add a version command to openshift-tests

- test/extended/networking/network_segmentation.go
Skip the NetworkSegmentation tests temporarily to allow for breaking ovn-kubernetes changes. 
This will be reverted in https://github.com/openshift/origin/pull/28945. 
/cc @tssurya
> SDN-4919: Skip network segmentation tests

- pkg/riskanalysis/cmd.go
- pkg/riskanalysis/cmd_test.go
I observed that when a RA http request fails for any reason, retries also fail immediately. Stephen speculated that reusing the request object might be a problem. [What I could find](https://github.com/golang/go/issues/19653#issuecomment-308246367) indicated that would only be a problem in specialized circumstances but it seemed worth trying.
> NO-JIRA: riskanalysis: improve request retries

- pkg/clioptions/iooptions/io_options.go
- pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
- pkg/cmd/openshift-tests/run-disruption/disruption.go
- pkg/defaultmonitortests/types.go
- pkg/disruption/ci/backend_sampler.go
- pkg/disruption/ci/factory.go
- pkg/disruption/ci/host_decoder.go
- pkg/monitortestframework/types.go
- pkg/monitortestlibrary/disruptionlibrary/collect.go
- pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/clusterrole-monitor.yaml
- pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/crb-monitor.yaml
- pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/crb-privileged.yaml
- pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-internal-lb.yaml
- pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-localhost.yaml
- pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/dep-service-network.yaml
- pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/namespace.yaml
- pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/rb-monitor.yaml
- pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/role-monitor.yaml
- pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/manifests/serviceaccount.yaml
- pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/remote.go
- pkg/monitortests/kubeapiserver/disruptionnewapiserver/monitortest.go
- pkg/monitortests/network/disruptionpodnetwork/monitortest.go
- pkg/test/ginkgo/cmd_runsuite.go
- test/extended/operators/manifests/pod.yaml
- test/extended/util/disruption/controlplane/known_backends.go
This reverts commit 4d66ac7.
* apiserver disruption tests no longer race with network disruption tests (they used the same label for the namespaces so apiserver disruption tests may have mistakenly assumed it was already running)
* added permissions to watch stop-configmap
* improved logging
> OCPBUGS-18865: Reapply "Merge pull request #28277 from vrutkovs/in-cluster-fixes-v3"

- test/extended/storage/s3_configuration.go
Skipping the chunksizemib as it will fail until both IR and API PR merges.
https://github.com/openshift/api/pull/1948 
https://github.com/openshift/cluster-image-registry-operator/pull/1073 
TODO revert the PR once above 2 merges
> IR-471: Skipping chunksizemib tests

- test/extended/etcd/helpers/helpers.go
- test/extended/etcd/vertical_scaling.go
The vertical scaling test will currently timeout on waiting for the CPMS status.readyReplicas to scale up to 4 where as in practice that may not happen. Ensuring that the cluster membership is 3 and checking that the old member has been removed is enough of a signal that vertical scaling has successfully completed.
> OCPBUGS-37837: vertical scaling test should not rely on CPMS replicas

- pkg/monitortests/etcd/legacyetcdmonitortests/etcd.go
- pkg/monitortests/etcd/legacyetcdmonitortests/monitortest.go
Removing the vsphere exclusion as it may obscure useful signal. The affected vsphere tests have not failed since this change, not even to flake.
> TRT-1688: Revert "allow etcd log test to flake under vsphere"

- test/extended/node_tuning/node_tuning.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This test does not accuratly capture the bug it references, the matcher would match on correct reasons to mark a mc as degraded thus giving false positives. Also the test is not needed because if the condition the test is checking for were ever to arise the install would simply fail before we ever would come to this state. The bug the test references also has tests so we should be fine to remove this check since it's not providing any value.
> OCPEDGE-1182: fix: remove un-needed test

- test/extended/networking/network_segmentation.go
- test/extended/networking/network_segmentation_endpointslice_mirror.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
Based on https://github.com/openshift/origin/pull/28964.
Depends on https://github.com/openshift/ovn-kubernetes/pull/2241
This PR refactors and adds tests for NetworkSegmentation featuregate which is currently in TechPreview.
> SDN-4919: NetworkSegmentation: Add tests for EndpointSlices mirror controller

- pkg/riskanalysis/cmd.go
- pkg/riskanalysis/cmd_test.go
At least with 400 errors, the error message can be useful (e.g. a 400 that tells me sippy couldn't find the job in the DB).
Also bumping up timeouts / retries because I'm seeing some failures that seem avoidable.
> TRT-1723: riskanalysis: pass along errors from API request

- pkg/clioptions/clusterdiscovery/csi.go
- pkg/clioptions/clusterdiscovery/provider.go
- pkg/testsuites/standard_suites.go
- test/extended/storage/csi/README.md
- test/extended/storage/csi/csi.go
- test/extended/storage/csi/scsi_overflow.go
Add a new OpenShift-specific test to `openshift/csi` suite that test a larger number of volumes used in a pod in sequence (or in manageable chunks). There was a 3rd party CSI driver that overflew a kernel counter after 256th attached volume.
This PR introduces OpenShift specific configuration manifest that configures OCP specific tests. There is just one test today, more can come in the future.
Usage:
```
cat <<EOF >ocp-specific-manifest.yaml
Driver: disk.csi.azure.com
LUNStressTest:
Timeout: "40m"
PodsTotal: 260
EOF
export TEST_OCP_CSI_DRIVER_FILES=ocp-specific-manifest.yaml
export TEST_CSI_DRIVER_FILES=upstream-test-manifest.yaml
openshift-tests run openshift/csi 
```
The test itself selects a random schedulable node, and creates configured nr. of Pods in parallel (260 by default). The …
> STOR-1819: Add OpenShift specific CSI certification test

- pkg/monitortests/clusterversionoperator/terminationmessagepolicy/monitortest.go
Follow up to https://github.com/openshift/origin/pull/28777
This drops the exceptions that should be fixed by:
https://github.com/openshift/cluster-storage-operator/pull/470
https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/231
https://github.com/openshift/ibm-vpc-block-csi-driver-operator/pull/114
I'm hoping the presubmit jobs will tell us that they really are fixed.
/cc @deads2k @jsafrane
/test all
> NO-JIRA: drop ocp-storage exceptions for termination policy

- test/extended/storage/driver_configuration.go
VSphereDriverConfiguration is GA in 4.16: https://github.com/openshift/api/pull/1902 + https://github.com/openshift/api/pull/1904
This skip should be removed to enable test on non tech preview clusters.
> STOR-1839: run vsphere driver config test on non techpreview clusters

- test/extended/storage/s3_configuration.go
Reverts openshift/origin#28975
/hold for https://github.com/openshift/cluster-image-registry-operator/pull/1073 to merge
> Revert "IR-471: Skipping chunksizemib tests"

- pkg/monitor/monitorapi/types.go
- pkg/monitortests/node/watchnodes/monitortest.go
- pkg/monitortests/node/watchnodes/node.go
We want to add an error on detection for unexpected ready.
We want to fail a test if node goes not ready without a MCO config change.
1) add a test if node goes not ready for unexpected reasons.
2) add a test if node has unreachable taint for unexpected reasons.
> OCPBUGS-38061: add unexpected ready for monitor tests

- test/extended/cli/debug.go
- test/extended/cli/env.go
- test/extended/cli/idle.go
- test/extended/cli/run.go
- test/extended/cli/setimage.go
- test/extended/cli/timeout.go
- test/extended/idling/idling.go
- test/extended/images/resolve.go
- test/extended/testdata/bindata.go
- test/extended/testdata/cmd/test/cmd/testdata/idling-deployment.yaml
- test/extended/testdata/cmd/test/cmd/testdata/test-deployment.yaml
- test/extended/testdata/idling-echo-server-deployment.yaml
- test/extended/testdata/test-deployment.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Part of simplifying https://github.com/openshift/origin/pull/28957. This PR extends the same e2e testing for Deployments as well. The DCs are already deprecated (yet never planned to be removed from 4.Y) and the DC capability is planned to be disabled by default. This helps to maintain the parity between DCs and Deployments.
> WRKLDS-1431: e2e: extend DC testing to Deployments

- test/extended/apiserver/graceful_termination.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
The new test extends `kubelet terminates kube-apiserver gracefully` test by checking the content of the termination files for kube-apiservers.
It should catch cases where the event is not persisted in the database. 
It should also catch cases where the KAS is immediately restarted or shut down after an ungraceful termination.
> NO-JIRA: new test for detecting ungraceful kube-apiserver termination by kubelet

- test/extended/kubevirt/migration.go
- test/extended/kubevirt/services.go
- test/extended/kubevirt/util.go
- test/extended/networking/egress_firewall.go
In case the cluster under test is an HCP/HyperShift cluster of the kubevirt provider, and the management cluster is running on Azure, ICMP responses from outside of the cluster to the guest cluster are getting blocked.
Thus, skipping the ping tests in that case, in addition to the existing exception.
This is a manual backport of #28916
> OCPBUGS-38788: [4.16] egressfirewall: skip ping tests in case of hypershift kubevirt on Azure infra

- test/extended/router/OWNERS
This PR revises:
Updating the OWNERS file in origin/test/extended/router
> OCPBUGS-36891: Update OWNERS file in origin/test/extended/router

- pkg/monitor/recorder.go
In go, passing slices between functions doesn't copy the internal array. 
Instead, a pointer to the same underlying array is shared among all receivers.
> NO-JIRA: monitor/recorder: snapshot makes copy before returning events

- pkg/monitortests/node/legacynodemonitortests/kubelet.go
We should fail a test run if there are too many restarts on a platform pod.
This test is flaky so we are going to look into how to deflake it.
> OCPBUGS-38435: deflake container restart tests

- test/extended/kubevirt/migration.go
- test/extended/kubevirt/services.go
- test/extended/kubevirt/util.go
- test/extended/networking/egress_firewall.go
In case the cluster under test is an HCP/HyperShift cluster of the kubevirt provider, and the management cluster is running on Azure, ICMP responses from outside of the cluster to the guest cluster are getting blocked. Thus, skipping the ping tests in that case, in addition to the existing exception. This is a manual backport of #28916
> OCPBUGS-38787: [4.15] egressfirewall: skip ping tests in case of hypershift kubevirt on Azure infra

- pkg/defaultmonitortests/types.go
- pkg/monitor/monitor.go
- pkg/monitor/monitorapi/types.go
- pkg/monitortestlibrary/podaccess/one_time_pod_log_streamer.go
- pkg/monitortests/testframework/operatorloganalyzer/operator_lease_check.go
- pkg/monitortests/testframework/operatorloganalyzer/operator_log_scraper.go
It'll be fine....
Adding to identify when leases for operators are non-gracefully released by watching for acquisition time which should be milliseconds long.  When it's longer than 10s, mark failures.  These failures nearly always mean that for some reason the kube-apiserver was inaccessible **for minutes**.
> NO-JIRA: add basic graceful lease checking

- pkg/monitortests/network/disruptionpodnetwork/monitortest.go
In certain environments, it can take 3 minutes to download the agnhost image from quay.io. Bump the timeout to 5 minutes to accommodate such slow environments.
> OCPBUGS-31738: Bump timeout for the pod-network-service endpoints check

- test/extended/apiserver/rollout.go
attempts to turn the test into a flake for a specific kind of error.
> NO-JIRA: allow http2 connection errors until the client tolerates it

- test/extended/olm/olm.go
The cluster-logging operator is (currently) not available in the 4.17 catalog, so we need to use a different candidate for our smoke test in 4.17+ (at least for now).
I'm open to other suggestions for packages to use for this test.
> OCPBUGS-39232: Change Operator Installed for Smoke Test

- test/extended/dr/common.go
- test/extended/dr/static_pod_rollouts.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This E2E tests whether etcd is able to block the rollout of a new revision when the quorum is not safe.
The etcd static pod manifest is removed by debugging into the node to bring down an etcd instance(to simulate insufficient quorum)
> ETCD-639: Add E2E test to check if etcd is able to block the rollout of a revision when the quorum is not safe

- pkg/cmd/openshift-tests/images/images_command.go
- test/extended/util/image/zz_generated.txt
Some of the metal jobs rely on information which images need to be mirrored, this information is coming later when we bump k8s in openshift/origin but to properly assess correctness we need those information sooner.
This PR injects that image information directly into `./openshift-tests` images command.
xref: https://github.com/openshift/origin/pull/28200
/assign @atiratree
> WRKLDS-1449: Add images coming in k8s 1.31

- test/extended/builds/contextdir.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/test-context-build.json
- test/extended/util/framework.go
OpenShift-Samples operator still points to stale image versions. These non-existing image references lead to test-failures. This commit eliminates the dependency on samples operator for importing the ruby IS, and instead creates a custom ruby imageStream.
Manual cherry-pick of #28952 
Tests in #28972 were failing due to inconsistent go version & method. Hence, a manual cherry-pick.
> [release-4.13] OCPBUGS-37921: Removes dependency on samples operator images

- pkg/cmd/openshift-tests/images/images_command.go
- test/extended/util/image/zz_generated.txt
This is a follow-up to https://github.com/openshift/origin/pull/29045.
These images showed up in recent payload jobs.
> WRKLDS-1449: Add other missing images kube 1.31

- pkg/monitortests/node/legacynodemonitortests/exclusions.go
- pkg/monitortests/node/legacynodemonitortests/kubelet.go
- pkg/monitortests/node/legacynodemonitortests/monitortest.go
Exclusions were found by starting https://search.dptools.openshift.org/?search=container%2Fnetworking-console-plugin+restarted+.*+times+at%3A&maxAge=168h&context=1&type=junit&name=4.18&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job for 4.18.
We filed bugs to hopefully catch these exclusions.
The goal of this PR is to start making this test useful again so we catch bad restarts early. This job was flaking for a long time and many people ignored it.
By making the job fail, we hope to catch actual bugs in our product.
> NO-JIRA: add exclusions to restart tests

- test/extended/testdata/bindata.go
- test/extended/testdata/cluster/quickstarts/dancer-mysql.json
- test/extended/testdata/cmd/test/cmd/images.sh
- test/extended/testdata/cmd/test/cmd/testdata/image-streams/image-streams-centos7.json
- test/extended/testdata/image_ecosystem/perl-hotdeploy/perl.json
This should fix the CI tests for the Perl image stream.
> OCPBUGS-39373: Use a supported Perl version in the test template.

- test/extended/olm/olm.go
Modifies the extended e2e test of OLM to use an available operator in the 4.18 `redhat-operators` catalog.
> OCPBUGS-41682: OLM Extended Test 4.18

- test/extended/etcd/etcd_storage_path.go
to fix https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-kubernetes-1647-nightly-4.18-e2e-vsphere-ovn-techpreview-serial/1833870039334260736
> WRKLDS-1449: Update etcd test data for 1.31 release

- pkg/monitortests/testframework/operatorloganalyzer/operator_lease_check.go
- pkg/monitortests/testframework/operatorloganalyzer/operator_log_scraper.go
Found it: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/29094/pull-ci-openshift-origin-master-e2e-aws-ovn-single-node/1833957493491896320
Operators embed logs of operands when the operand fails.  The operand lease is actually failing and the log lines are embedded in the operator log. This skips those entries.
> NO-JIRA: try to track down why the lease acquiring sometimes fails

- pkg/monitortests/network/disruptionpodnetwork/monitortest.go
- test/extended/cpu_partitioning/managed.go
- test/extended/pods/graceful-shutdown.go
- test/extended/util/client.go
- test/extended/util/framework.go
When the image registry capability is disabled, service account pull secret and role bindings are not going to be populated. We need to skip waiting for those events when creating namespaces.
> OCPBUGS-41550: fix: add check for image registry capability

- test/extended/testdata/bindata.go
- test/extended/testdata/cluster/quickstarts/dancer-mysql.json
- test/extended/testdata/cmd/test/cmd/images.sh
- test/extended/testdata/cmd/test/cmd/testdata/image-streams/image-streams-centos7.json
Reverts openshift/origin#29082
see: https://github.com/openshift/origin/pull/29082#issuecomment-2352519270
> Revert "OCPBUGS-39373: Use a supported Perl version in the test template."

- pkg/monitortests/node/legacynodemonitortests/exclusions.go
- pkg/monitortests/node/legacynodemonitortests/kubelet.go
1) Add better exclusions to catch more restarts.
2) add a flake test for 1 or more restarts.
3) add ns/%v to the test output to quickly identity the team responsible.
> NO-JIRA: improve excessive restart tests

- pkg/monitortests/node/legacynodemonitortests/exclusions.go
- pkg/monitortests/node/legacynodemonitortests/kubelet.go
Reverts #29087 ; tracked by [TRT-1823](https://issues.redhat.com//browse/TRT-1823)
These test cases are generating tests with dynamic namespace names in them, this breaks a lot of tooling including aggregation
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:
```
Run /payload blocking jobs to verify aggregation passes
```
CC: @kannon92
<div align="right">
PR created by <a …
> TRT-1823: Revert #29087 "NO-JIRA: improve excessive restart tests"

- pkg/monitortests/node/watchpods/cache_check.go
- pkg/monitortests/node/watchpods/collection.go
- pkg/monitortests/node/watchpods/monitortest.go
- pkg/monitortests/node/watchpods/pod_ip_controller.go
Trying to figure out why pods that were deleted in job runs like https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.18-upgrade-from-stable-4.17-e2e-metal-ipi-ovn-upgrade-cgroupsv1/1832612917804011520 (we very rarely catch the condition because pod IPs have to collide) were still present in our caches.
Reminder to self that some analysis is in https://gist.github.com/deads2k/5f9b725894bdb7ba03011889c06b2127
In this case
1. pods/pod-network-to-service-disruption-poller-565f9f69c4-nqjgl was deleted 05:18:52 (see audit log for delete and a get that 404'd)
2. pod-network-to-host-network-disruption-poller-794dd9846-9sc9m was created at 05:18:52
3. at 2024-09-08T05:18:59, the lister in the pod_ip_controller returned a list that …
> NO-JIRA: add test that ensures our informer cache matches the live results

- pkg/monitortests/kubeapiserver/legacykubeapiservermonitortests/early_e2e_disruption.go
- pkg/monitortests/kubeapiserver/legacykubeapiservermonitortests/monitortest.go
Tighten the conditions for failure a bit.
Skip single-node.
> TRT-1809: refine early E2E disruption test

- pkg/monitortests/network/disruptionpodnetwork/monitortest.go
This is an manual cherry-pick of https://github.com/openshift/origin/pull/28698
In certain environments, it can take 3 minutes to download the agnhost image from quay.io. Bump the timeout to 5 minutes to accommodate such slow environments.
> [release-4.14] OCPBUGS-39137: Bump timeout for the pod-network-service endpoints check

- pkg/monitortestlibrary/platformidentification/types.go
- pkg/monitortests/node/legacynodemonitortests/kubelet.go
- pkg/monitortests/testframework/watchnamespaces/namespaces.go
I am seeing a lot of flakes due to must-gathers.
```
amespace/openshift-must-gather-tqw22 node/control-1 pod/must-gather-v28rc uid/69848c84-2b1a-4b08-9018-deaf9faf6434
namespace/openshift-must-gather-9zxhj node/control-2 pod/must-gather-7tljn uid/c7dd24ab-47f5-48e5-81be-addfe70ceaca
namespace/openshift-must-gather-5ssnz node/control-0 pod/must-gather-gw7q6 uid/0793b22d-63df-41c1-a5b4-411836271ee8
namespace/openshift-must-gather-hxjcm node/compute-0 pod/perf-node-gather-daemonset-vcbmg uid/7fb7f233-6493-41f3-b547-1df416b357d3
namespace/openshift-must-gather-hxjcm node/compute-1 pod/perf-node-gather-daemonset-xm4pd uid/41cecd3b-d0d8-40f7-be44-ad226ce537c0
namespace/openshift-must-gather-hxjcm node/control-1 pod/perf-node-gather-daemonset-2kprz uid/15850d2b-cc8a-40fe-a60a-a1f13dc69d50 …
```
> OCPBUGS-42316: exclude must gather and debug from platform force delete

- test/extended/image_ecosystem/s2i_images.go
- test/extended/image_ecosystem/s2i_perl.go
- test/extended/image_ecosystem/s2i_ruby.go
- test/extended/image_ecosystem/sample_repos.go
- test/extended/testdata/bindata.go
- test/extended/testdata/image_ecosystem/perl-hotdeploy/perl.json
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/deployment.go
- test/extended/util/framework.go
This is a cherry-pick of https://github.com/openshift/origin/pull/29116 and https://github.com/openshift/origin/pull/28965 to the release-4.17 branch.
> OCPBUGS-42336: Fix image ecosystem tests 4.17

- pkg/monitor/monitorapi/types.go
- pkg/monitortests/testframework/operatorloganalyzer/operator_log_scraper.go
To catch things like
> 2024-09-26T09:00:24.282667248Z E0926 09:00:24.282588       1 base_controller.go:271] OAuthAPIServerControllerWorkloadController reconciliation failed: Authentication.operator.openshift.io "cluster" is invalid: [conditions[55].type: Invalid value: "": conditions[55].type in body should match '^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$', conditions[55].status: Unsupported value: "": supported values: "True", "False", "Unknown", <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]
in our operator logs.  It would be better to track client metic invalid request rates, but I don't know how at the moment.
> API-1835: add test to prevent invalid apply statements

- test/extended/include.go
- test/extended/machine_config/OWNERS
- test/extended/machine_config/boot_image_update_agnostic.go
- test/extended/machine_config/boot_image_update_aws.go
- test/extended/machine_config/boot_image_update_gcp.go
- test/extended/machine_config/helpers.go
- test/extended/testdata/bindata.go
- test/extended/testdata/machine_config/machineconfigurations/managedbootimages-all.yaml
- test/extended/testdata/machine_config/machineconfigurations/managedbootimages-none.yaml
- test/extended/testdata/machine_config/machineconfigurations/managedbootimages-partial.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
This PR adds e2e tests for GCP(in GA) and AWS(in tech preview) boot image updates. 
This is also the first set of e2e tests added by the MCO team to origin, so I have added a new OWNERS file for the package.
> MCO-1304: Add boot image update e2e tests

- test/extended/etcd/etcd_backup_noconfig.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
This PR adds an e2e test for the etcd backup noconfig feature. 
resolves https://issues.redhat.com/browse/ETCD-662
cc @openshift/openshift-team-etcd
> ETCD-662: Add etcd-backup-server e2e test

- test/extended/cli/policy.go
By this https://github.com/openshift/api/pull/2017 (and the corresponding changes in upstream), all resources have metadata field. When we bump the dependencies in oc, these changes are also coming in (https://github.com/openshift/oc/pull/1877). On the other hand, openshift-apiserver is not ready yet to understand the metadata field in resources and so it raises a warning about `Warning: unknown field \"metadata\"`. Although this is just a warning, this causes failures in the test `[sig-cli] policy scc-subject-review, scc-review` (e.g. [failed test run](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-oc-1877-nightly-4.18-e2e-metal-ipi-ovn-ipv6/1836336155059032064)).
Ideally we should wait the merge of https://github.com/openshift/openshift-apiserver/pull/444 …
> WRKLDS-1492: Loosen output check in policy scc-subject-review, scc-review test

- test/extended/apiserver/health_endpoints.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
The test could be defined in the operand repo, but since the operand repo doesn't have any CI job defined, I decided to add the test directly to the origin.
This might cause minor issues during rebases when the output changes, but this shouldn't happen frequently.
Also we should add test cases for the remaining aggregated APIs.
Required for https://github.com/openshift/openshift-apiserver/pull/452
> NO-JIRA: test for checking the healthz endpoints for the openshift-apiserver

- examples/quickstarts/rails-postgresql-persistent.json
- examples/quickstarts/rails-postgresql.json
- test/extended/builds/dockerfile.go
- test/extended/cli/setimage.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/build-secrets/test-s2i-build.json
- test/extended/testdata/builds/statusfail-badcontextdirs2i.yaml
- test/extended/testdata/builds/statusfail-fetchimagecontentdocker.yaml
- test/extended/testdata/builds/statusfail-fetchsourcedocker.yaml
- test/extended/testdata/builds/statusfail-fetchsources2i.yaml
- test/extended/testdata/builds/statusfail-genericreason.yaml
- test/extended/testdata/builds/statusfail-oomkilled.yaml
- test/extended/testdata/builds/test-build-proxy.yaml
- test/extended/testdata/builds/test-build.yaml
- test/extended/testdata/builds/test-env-build.json
- test/extended/testdata/builds/test-imagesource-buildconfig.yaml
- test/extended/testdata/cluster/quickstarts/rails-postgresql.json
- test/extended/testdata/cmd/test/cmd/images.sh
- test/extended/testdata/cmd/test/cmd/testdata/image-streams/image-streams-centos7.json
- test/extended/testdata/cmd/test/cmd/testdata/new-app/imagestream-ref.yaml
- test/extended/testdata/image/test-image.json
- test/extended/testdata/long_names/fixture.json
- test/extended/testdata/run_policy/parallel-bc.yaml
- test/extended/testdata/run_policy/serial-bc.yaml
- test/extended/testdata/run_policy/serial-latest-only-bc.yaml
Fix tests that fail due to not finding ruby-3.0-ubi8 images.
> OCPBUGS-42237: bump ruby-3.0-ubi8 image to ruby-3.1-ubi8

- test/extended/networking/network_segmentation.go
- test/extended/networking/network_segmentation_endpointslice_mirror.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
This PR ports using a correct primary network configuration for all user defined networking tests, using both netConfig and UDN crd for all currently ported tests, and overlapping CIDR tests from upstream ovn-kubernetes
> SDN-5202:Porting testing for netConfig and UDN and CIDR overlapping tests from upstream

- test/extended/kernel/kernel_rt_latency.go
- test/extended/kernel/tools.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
We are removing rteval from the realtime test suite. After switching to a metal host it was exposed that this test overruns container limits when creating system load and the only logical fix is to run rteval on the host rather than containerized. That approach is beyond the scope of what this test suite is intended for. In addition, this test is primarily useful when testing hardware being used in production systems to provide platform readiness by putting the CPU under load and then evaluating with cyclictest. We are not validating the hardware with this test suite and as such rteval is a bad fit for this suite.
In our situation we are really trying to just test that there are no obvious underlying issues with the kernel or with Openshift running on top of the real-time kernel which is …
> OCPEDGE-1265: removing rteval from the realtime test suite

- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/external.go
Reverts openshift/origin#29025
Failures beginning in [4.18.0-0.ci-2024-10-08-185524](https://amd64.ocp.releases.ci.openshift.org/releasestream/4.18.0-0.ci/release/4.18.0-0.ci-2024-10-08-185524)
```
Suite run returned error: unable to extract image references from release payload: failed extracting image-references from "registry.ci.openshift.org/ocp/release:4.18.0-0.ci-2024-10-08-185524": error during image extract: exit status 1 (error: unable to read image registry.ci.openshift.org/ocp/release:4.18.0-0.ci-2024-10-08-185524: unauthorized: authentication required
)
error running options: unable to extract image references from release payload: failed extracting image-references from "registry.ci.openshift.org/ocp/release:4.18.0-0.ci-2024-10-08-185524": error during image extract: exit …
```
> TRT-1851: Revert "NO-JIRA: external binary registry"

- test/extended/etcd/helpers/helpers.go
- test/extended/etcd/vertical_scaling.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
The following test covers a basic vertical scaling scenario when CPMS is disabled and validates that the scale-down does not happen before the scale-up event.
1. If the CPMS is active, first disable it by deleting the CPMS custom resource
2. Delete the machine
3. Create a new master machine that belongs to the same index as the deleted machine
4. Scale-up happens first before the scale-down
5. Validate scales-up happens first by verifying 4 voting members in etcd cluster
6. Then scale-down is validated by confirming the member removal and changes in the cluster membership
> ETCD-664: Add e2e test for scaling when CPMS is disabled

- test/extended/networking/network_segmentation.go
Sample test failure signature:
```
STEP: Remaining blue pod cannot communicate with red networks overlapping CIDR @ 10/09/24 01:54:08.744
I1009 01:54:08.744310 63202 builder.go:121] Running '/usr/bin/kubectl --server=https://api.ci-op-5vlfjmrg-64ca1.origin-ci-int-aws.dev.rhcloud.com:6443/ --kubeconfig=/tmp/kubeconfig-3159918400 --namespace=e2e-test-network-segmentation-e2e-jkxkx-blue exec blue-pod-3 -- curl --connect-timeout 2 203.203.0.4:9000'
I1009 01:54:11.246120 63202 builder.go:135] rc: 28
[FAILED] in [It] - github.com/openshift/origin/test/extended/networking/network_segmentation.go:522 @ 10/09/24 01:54:11.29
```
The objective of the test is that the connection does not succeed and I think thats sufficient instead of trying to play whackamole with timeouts and string detection.
> NO-JIRA: Fix Network segmentation test for detecting timeout

- test/extended/kernel/common.go
- test/extended/kernel/tools.go
- test/extended/testdata/bindata.go
- test/extended/testdata/kernel/rt-tests-environment.yaml
- Pins the oslat main thread to the first thread under test to accommodate workload partitioning
- Writes the outputs of oslat, cyclictest and rteval to the artifacts dir
> OCPEDGE-1266: fix: adding oslat updates and outputting test results to the artifacts

- pkg/monitortests/network/disruptionpodnetwork/monitortest.go
- test/extended/cpu_partitioning/managed.go
- test/extended/pods/graceful-shutdown.go
- test/extended/util/client.go
- test/extended/util/framework.go
Backport check for image registry capability to fix for `[sig-network] can collect pod-to-host poller pod logs`
8ab8b41c0adfcf999c6535031348d85a9fc663da
44824bbc69b3f3f56a34344c7cc8d05af02e5f45
https://github.com/openshift/origin/pull/29018
https://github.com/openshift/origin/pull/29077
> [release-4.17] OCPBUGS-39606: Add image registry capability check

- pkg/monitortestlibrary/allowedalerts/basic_alert.go
- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_events_test.go
- pkg/monitortests/node/legacynodemonitortests/exclusions.go
- pkg/monitortests/node/legacynodemonitortests/monitortest.go
- pkg/monitortests/node/legacynodemonitortests/pathological_events.go
- pkg/monitortests/node/legacynodemonitortests/pathological_events_test.go
- test/e2e/upgrade/dns/dns.go
Updating some tests and modifying some checks for SNO upgrade errors, each one of these skips is being tracked and will be removed or modified when the underlying issue is resolved.
* Flake KubeAPIErrorBudgetBurn until resolved
* Skip container restart for snapshot-controller 
* Modify DNS test until regression is resolved 
* Added the pathological errors during kube api progressing, this will be modified or removed upon further investigation on it's usefulness
> OCPBUGS-43059: fix: sno issues with alerts and pathological events

- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/external.go
https://github.com/openshift/origin/pull/29025 introduced an external binary registry. The code assumed that the release payload it analyzed could be accessed without authentication. This is true for every payload except release controller nightly & CI payloads (e.g. registry.ci.openshift.org/ocp/release:<tag>). RELEASE_IMAGE_LATEST, in contexts, like aggregated jobs, directly reference registry.ci instead of payloads in the `ci-op-*` namespace.
https://github.com/openshift/origin/pull/29025 was reverted because it could not access the release controller formulated payloads in these contexts. 
With this PR, the previous method of finding pull-secrets for the installed cluster in order to authorize access to component images is also leveraged to access the release payload image.
It also …
> NO-JIRA: Enable external binary registry

- go.mod
- go.sum
- test/extended/apiserver/patch.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- vendor/github.com/openshift/library-go/pkg/apiserver/jsonpatch/jsonpatch.go
- vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go
- vendor/modules.txt
for https://github.com/openshift/library-go/pull/1835
> NO-JIRA: a new test for the jsonpatch library 

- pkg/defaultmonitortests/types.go
- pkg/monitor/monitorapi/construction.go
- pkg/monitor/monitorapi/types.go
- pkg/monitortests/kubeapiserver/generationanalyzer/generation.go
- pkg/monitortests/kubeapiserver/generationanalyzer/monitortest.go
Example CI run where the max allowed generation is 3 (for testing only) from [this job](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/29168/pull-ci-openshift-origin-master-e2e-aws-csi/1844711431623151616):
```
objects in ns/openshift-apiserver should not have a generation greater than 3 expand_less
Run #0: Failed
{Oct 11 13:13:27.664 I namespace/openshift-apiserver deployment/apiserver reason/HighGeneration Deployment generation too high: 7  objects had a metadata.Generation higher than 3}
Run #1: Passed
objects in ns/openshift-authentication should not have a generation greater than 3 expand_less
Run #0: Failed
{Oct 11 13:13:27.665 I namespace/openshift-authentication deployment/oauth-openshift reason/HighGeneration Deployment generation too high: 4  objects …
```
> API-1835: Add a generation analyzer monitortest

- test/extended/networking/network_segmentation.go
- test/extended/networking/network_segmentation_endpointslice_mirror.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
This PR ports using a correct primary network configuration for all user defined networking tests, using both netConfig and UDN crd for all currently ported tests, and overlapping CIDR tests from upstream ovn-kubernetes
> [release-4.17] OCPBUGS-43576: Porting testing for netConfig and UDN and CIDR overlapping tests from upstream

- pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/annotation_requirement.go
- pkg/cmd/update-tls-artifacts/generate-owners/tlsmetadatainterfaces/helpers.go
- tls/autoregenerate-after-expiry/autoregenerate-after-expiry.md
- tls/descriptions/descriptions.md
Avoid empty string in some markdown reports for TLS registry, instead sets the label as "Unknown"
> NO-JIRA: update-tls-artifacts: set owner to unknown if unset

- test/extended/machine_config/boot_image_update_agnostic.go
This test extends the timeout for the following test to 2 minutes, as 30 seconds seems to be too short.
```
[sig-mco][OCPFeatureGate:ManagedBootImages][Serial] Should degrade on a MachineSet with an OwnerReference [apigroup:machineconfiguration.openshift.io] [Suite:openshift/conformance/serial]
```
> OCPBUGS-43512: New ManagedBootImages test appears to be failing too often

- test/extended/networking/network_segmentation.go
Fix UDN status check to assert required condition is present in the status instead of checking that status has only 1 condition.
required to make https://github.com/openshift/ovn-kubernetes/pull/2314 pass
> SDN-4930: network_segmentation: allow multiple UDN status conditions

- pkg/monitortests/node/watchnodes/monitortest.go
If we have an unexpected node not ready and there are no deletion events this is significant.
> OCPNODE-2668: fix unexpected not ready

- test/extended/apiserver/patch.go
- test/extended/pods/priorityclasses.go
- test/extended/util/framework.go
These tests are prevented from working on managed clusters:
```
admission webhook "regular-user-validation.managed.openshift.io" denied the request: Prevented from accessing Red Hat managed resources. This is in an effort to prevent harmful actions that may cause unintended consequences or affect the stability of the cluster. If you have any questions about this, please reach out to Red Hat support at https://access.redhat.com/support
```
> NO-JIRA: managed services: skip JSON patch tests

- test/extended/machine_config/boot_image_update_agnostic.go
- test/extended/machine_config/boot_image_update_aws.go
- test/extended/machine_config/boot_image_update_gcp.go
- test/extended/machine_config/helpers.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
This adds one more boot image update test to the MCO's test suite. This test ensures that the boot image configmap "stamp" action by the operator is always done, as long as at least one master node is up to date.
> MCO-1370: Add boot image configmap test to openshift/origin

- pkg/monitortests/testframework/knownimagechecker/monitortest.go
"multi-stage:v1" used by ROSA is being flagged, exclude all images pulled from their CI registry
> NO-JIRA: managed services: add exception for known images check

- test/extended/image_ecosystem/sample_repos.go
Trying to reduce the flakiness of the samples smoke tests by increasing the timeout for the build of the app.
Especially the rails example tends to take forever to build.
> OCPBUGS-42536: Trying to reduce the flakiness of the samples smoke tests

- test/extended/olm/olmv1.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This is the initial test. Only works on tech-preview. Checks for presence of OLMv1 CRDs.
> OPRUN-3576: Add OLMv1 origin tests

- test/extended/networking/network_segmentation.go
Instead of relying on routes use a specific interface for accessing KAPI.
cc: @trozet
> NO-JIRA: UserDefinedPrimaryNetworks: curl the KAPI IP through eth0

- test/extended/networking/network_segmentation.go
Hit downstream:
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2314/pull-ci-openshift-ovn-kubernetes-master-e2e-gcp-ovn-techpreview/1849904878739001344
Taken from upstream:
https://github.com/ovn-org/ovn-kubernetes/pull/4811
> SDN-4930: Set startup probe for UDN tests

- test/extended/dns/dns.go
For HyperShift, since master nodes are not visible in the HostedCluster, adjust createDNSPod() to support dual-stack testing in HyperShift.
test job: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/29228/pull-ci-openshift-origin-release-4.16-e2e-agent-connected-ovn-dualstack-metal3/1849379580285030400
```
passed: (20.9s) 2024-10-24T12:00:01 "[sig-network-edge] DNS should answer A and AAAA queries for a dual-stack service [apigroup:config.openshift.io] [Suite:openshift/conformance/parallel]"
```
> OCPBUGS-38713: Adjust createDNSPod() to support hypershift dual-stack test

- test/extended/router/metrics.go
This PR follows up on a Dynamic Configuration Manager (DCM) gap identified during [the smoke test](https://github.com/openshift/cluster-ingress-operator/pull/1113#issuecomment-2315530761).
When DCM is enabled by default, server management behavior changes. Not all servers will be in the UP state, and this must be accounted for in the router metrics tests. This PR updates the tests to handle scenarios where some servers may be DOWN. The scenarios when DCM is not enabled should still be working.
> NE-1815: Adapt router metrics tests for DCM support

- test/extended/machine_config/boot_image_update_aws.go
- test/extended/machine_config/boot_image_update_gcp.go
- test/extended/machine_config/helpers.go
The [last set of timeout failures are isolated to SNO](https://sippy.dptools.openshift.org/sippy-ng/tests/4.18/analysis?test=%5Bsig-mco%5D%5BOCPFeatureGate%3AManagedBootImagesAWS%5D%5BSerial%5D%20Should%20update%20boot%20images%20on%20all%20MachineSets%20when%20configured%20%5Bapigroup%3Amachineconfiguration.openshift.io%5D%20%5BSuite%3Aopenshift%2Fconformance%2Fserial%5D&filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22%5Bsig-mco%5D%5BOCPFeatureGate%3AManagedBootImagesAWS%5D%5BSerial%5D%20Should%20update%20boot%20images%20on%20all%20MachineSets%20when%20configured%20%5Bapigroup%3Amachineconfiguration.openshift.io%5D%20%5BSuite%3Aopenshift%2Fconformance%2Fserial%5D%22%7D%2C%7B%22columnField%22%3A%22variants%22%2C%22not%22 …
> NO-ISSUE: skip boot image tests on single node tests

- test/extended/include.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/windows/OWNERS
- test/extended/windows/nodes.go
This PR proposes a new group of tests targeting Windows nodes in the test cluster and introduces a simple Windows-specific check as the first step in providing test coverage for Windows nodes.
> NO-JIRA: Introduce version annotation test for Windows nodes

- test/extended/operators/daemon_set.go
- test/extended/operators/resources.go
Reverts #29266 ; tracked by https://issues.redhat.com/browse/TRT-1871
While we suspect the test is now finding a legit issue, payloads have blocked. We're going to revert and test a fix with an exception and a jira to address adding the pod requests for the network team.
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:
```
/payload-aggregate …
```
> TRT-1871: Revert #29266 "NO-JIRA: Additional ROSA exceptions"

- test/extended/olm/olmv1.go
We are in a state of API transition, and the meaning of Progressing has changed. We are removing the checks for the Progressing state, and only looking at the final state.
> NO-ISSUE: OLMv1: Remove progressing checks during API transition

- test/extended/apiserver/graceful_termination.go
- test/extended/operators/resources.go
- Additional request/limits exceptions
- Debugging `[sig-api-machinery][Feature:APIServer][Late] API LBs follow /readyz of kube-apiserver and stop sending requests before server shutdowns for external clients [Suite:openshift/conformance/parallel]` by adding more logging
> NO-JIRA: More ROSA work for openshift-tests

- pkg/monitortestlibrary/utility/utility.go
- pkg/monitortests/machines/watchmachines/machines.go
- pkg/monitortests/machines/watchmachines/monitortest.go
- pkg/monitortests/node/kubeletlogcollector/node.go
- pkg/monitortests/node/kubeletlogcollector/node_test.go
- pkg/monitortests/node/watchnodes/monitortest.go
- pkg/monitortests/node/watchnodes/node.go
- pkg/monitortests/node/watchnodes/node_test.go
This PR makes sure to add a node name to the DeletedMachine monitor.
Once that is added, we also added some unit tests to this code to make sure that we are correctly detecting UnexpectedNodeNotReady / UnexpectedUnreachable.
The main edge case we had to work around was when Machines get deleted and that node goes not ready. This is correct behavior but our test was flagging this as this code path does not go through a Machine Config change.
> OCPBUGS-44244: use node node in deleted machine phases

- test/extended/networking/network_segmentation.go
Following the incoming changes of the CUDN controller, the assertion on the UDN status is no longer valid.
Fix the assertion with the expected condition message.
> OCPBUGS-44381: ovn-k, udn crd e2e: Fix status report consumer assertion

- test/extended/networking/network_segmentation.go
Following the incoming changes of the CUDN controller by [origin/ovn-kubernetes#2345](https://github.com/openshift/ovn-kubernetes/pull/2345), the assertion on the UDN status is no longer valid.
This PR fix the assertion with the expected condition message.
Note to reviewer:
Merging this PR means there might be intermediate time where techpreview lane will fail due to missing bits of https://github.com/openshift/ovn-kubernetes/pull/2345
Or if https://github.com/openshift/ovn-kubernetes/pull/2345 merged without this PR changes.
PR converted to draft state to avoid burning CI time
> ovn-k, udn crd e2e: Fix status report consumer assertion

- test/extended/operators/resources.go
- test/extended/pods/priorityclasses.go
- test/extended/util/managed_services.go
Some ephemeral pods in rosa namespaces like openshift-sre-pruning are triggering failures that didn't have per-pod exceptions, just skip examining these namespaces alltogether.
Example:
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.18-e2e-rosa-sts-ovn/1856870032659714048
> NO-JIRA: managed services: centralize definition of namespaces

- test/extended/olm/olmv1.go
Need to disable the OLMv1 install test during the API transition. It will be updated and enabled once the API transition is complete.
> NO-ISSUE: Disable olmv1 install test during API transision

- test/extended/cli/policy.go
Since https://github.com/openshift/openshift-apiserver/pull/458 has merged, we can revert https://github.com/openshift/origin/pull/29141
> OCPBUGS-42532: Revert loosened policy test

- test/extended/olm/olmv1.go
- test/extended/testdata/bindata.go
- test/extended/testdata/olmv1/install-operator.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
Reverts https://github.com/openshift/origin/pull/29290 ; tracked by https://issues.redhat.com/browse/OCPBUGS-44662
This change is breaking 4.18 nightly. First payload failure https://amd64.ocp.releases.ci.openshift.org/releasestream/4.18.0-0.nightly/release/4.18.0-0.nightly-2024-11-16-132904
See thread for more details: https://redhat-internal.slack.com/archives/C01CQA76KMX/p1731937499008099?thread_ts=1731522911.671799&cid=C01CQA76KMX
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, …
> Revert "NO-ISSUE: Add Capability and FeatureGate checks to OLMv1 tests"

- test/extended/olm/olmv1.go
- test/extended/testdata/bindata.go
- test/extended/testdata/olmv1/install-catalog.yaml
- test/extended/testdata/olmv1/install-operator.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
* Cleanup and reorganize some tests.
* Add some negative tests.
> OCPBUGS-44662: Re-enable OLMv1 tests

- test/extended/olm/olmv1.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
as all the skipped tests expect some level of internet access or a specific disconnected environment configuration.
> OPRUN-3605: sig-olmv1: update all but one of the olmv1 tests to be skipped in disconnected testing

- test/extended/olm/olmv1.go
- test/extended/testdata/bindata.go
- test/extended/testdata/olmv1/install-operator.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
* Add diagnostics to figure out what happened when context timeout occurs
* Remove [Serial] requirements, the install tests can now happen in parallel
> OPRUN-3606: Add diagnostics to olmv1 tests

- pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
Enforced required-scc monitor test for fixed namespaces. Extended the required-scc monitor test to validate non-standard SCCs and ensure they are only used in allowed namespaces.
> OCPBUGS-42435: Enforce the required-scc monitor test and validate usage of non-standard OCP SCCs

- pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
Reverts openshift/origin#29135
Observing permafailures in 4.19 Nightly payloads (haven't had a 4.18 recently) for hypershift starting with [4.19.0-0.nightly-2024-11-23-092733](https://amd64.ocp.releases.ci.openshift.org/releasestream/4.19.0-0.nightly/release/4.19.0-0.nightly-2024-11-23-092733)
Due to:
```
: [sig-auth] all workloads in ns/kube-system must set the 'openshift.io/required-scc' annotation expand_less 	0s
{  annotation missing from pod 'konnectivity-agent-6rwjl' (owners: daemonset/konnectivity-agent); cannot suggest required-scc, no validated SCC on pod
annotation missing from pod 'konnectivity-agent-88sdg' (owners: daemonset/konnectivity-agent); cannot suggest required-scc, no validated SCC on pod
annotation missing from pod 'konnectivity-agent-ktcw5' (owners: …
```
> NO-JIRA: Revert "Enforce the required-scc monitor test and validate usage of non-standard OCP SCCs

- pkg/monitortestlibrary/utility/utility.go
- pkg/monitortests/machines/watchmachines/machines.go
- pkg/monitortests/machines/watchmachines/monitortest.go
- pkg/monitortests/node/kubeletlogcollector/node.go
- pkg/monitortests/node/kubeletlogcollector/node_test.go
- pkg/monitortests/node/watchnodes/monitortest.go
- pkg/monitortests/node/watchnodes/node.go
- pkg/monitortests/node/watchnodes/node_test.go
Cherry pick of https://github.com/openshift/origin/pull/29269 into release-4.17.
We want to get reliable data for these tests so we can detect regressions over time.
> [release-4.17] OCPBUGS-44190: Fix UnexpectedNodeNotReady and UnexpectedNodeUnreachable

- pkg/monitortests/node/watchnodes/monitortest.go
Only metal jobs were showing up, rarely at that, and a fix just went in.
https://sippy.dptools.openshift.org/sippy-ng/jobs/4.18/runs?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522flaked_test_names%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522%255BJira%253A%255C%2522Test%2520Framework%255C%2522%255D%2520kubelet%2520should%2520not%2520report%2520DiskPressure%2522%257D%252C%257B%2522columnField%2522%253A%2522variants%2522%252C%2522not%2522%253Atrue%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522never-stable%2522%257D%252C%257B%2522columnField%2522%253A%2522variants%2522%252C%2522not%2522%253Atrue%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522aggregated%2522%25 …
> TRT-1761: Allow the test for kubelet DiskPressure to fail job runs

- test/extended/util/managed_services.go
these are deployed to non-sts and gcp clusters
> NO-JIRA: add additional managed namespaces

- test/extended/prometheus/collection_profiles.go
Reverts openshift/origin#29309; tracked by https://issues.redhat.com/browse/OCPBUGS-45153
This PR has causd the nightly failures for many techpreview jobs. Here is one example: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.19-e2e-aws-ovn-techpreview/1861677512929579008
Test is stuck with this error:
I1127 09:11:20.327512 62130 client.go:421] Project "e2e-test-monitoring-collection-profiles-mqvzf" has been fully provisioned.
STEP: restoring the original configuration for the operator @ 11/27/24 09:11:21.232 …
> TRT-1898: Revert "NO-JIRA: address malformed CMO configmap post-test"

- pkg/monitortests/authentication/requiredsccmonitortests/monitortest.go
Enforced required-scc monitor test for fixed namespaces. Extended the required-scc monitor test to validate non-standard SCCs and ensure they are only used in allowed namespaces.
Fixed the issue from revert #29321 
Added system namespaces such as `default`, `kube-system`, `kube-public`, `openshift-node`, `openshift-infra`, and `openshift` to ensure they are treated as flaking namespaces.
> OCPBUGS-44961: Fix "Enforce the required-scc monitor test and validate usage of non-standard OCP SCCs"

- pkg/monitortests/testframework/knownimagechecker/monitortest.go
this was added for rosa in 12ab194e2ef15737f8cae7793b7eb6294f36ef31
> NO-JIRA: managed services: add known image check for gcp

- pkg/monitortestlibrary/nodeaccess/node_log.go
This PR is complementary of https://github.com/openshift/oc/pull/1934.
> OCPBUGS-45363: Parse node logs also when encountered with standard html header

- pkg/monitortests/node/legacynodemonitortests/exclusions.go
This container is deployed by https://github.com/openshift/release/tree/master/ci-operator/step-registry/ipi/install/hosted-loki and is sensitive to resolving sso.redhat.com. During an SNO upgrade, there is a brief period of time where dns is unavailable because the only instance of the pod has been killed and the new pod is starting up. The goal of this change is to exclude this container from the excessive restart checks since, depending on the exact timing, it can restart enough times to trigger a failed test.
> OCPBUGS-44970: Excluding loki prod-bearer-token container from excessive restarts test in SNO

- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
This is a fixup for previous patch https://github.com/openshift/origin/pull/29151 which does not seem to work well: 
https://sippy.dptools.openshift.org/sippy-ng/component_readiness/test_details?Aggregation=none&Architecture=amd64&FeatureSet=default&Installer=upi&LayeredProduct=none&Network=ovn&NetworkAccess=default&Platform=vsphere&Procedure=none&Scheduler=default&SecurityMode=default&Suite=serial&Topology=ha&Upgrade=none&baseEndTime=2024-10-01%2023%3A59%3A59&baseRelease=4.17&baseStartTime=2024-09-01%2000%3A00%3A00&capability=Other&columnGroupBy=Architecture%2CNetwork%2CPlatform%2CTopology&component=Storage&confidence=95&dbGroupBy=Platform%2CArchitecture%2CNetwork%2CTopology%2CFeatureSet%2CUpgrade%2CSuite%2CInstaller&environment=amd64%20default%20upi%20ovn%20vsphere%20serial%20ha%20none&i …
> OCPBUGS-42610: filter out pod events during vsphere snapshot options

- test/extended/util/managed_services.go
I missed a couple.
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.19-e2e-rosa-sts-ovn/1866441913201070080
> OCPBUGS-45838: managed services: add more missing namespaces

- test/extended/prometheus/prometheus.go
[OSD-26887](https://issues.redhat.com//browse/OSD-26887): managed services taints several nodes as infrastructure. This taint appears to be applied after some of the platform DS are scheduled there, causing this alert to fire.  Managed services rebalances the DS after the taint is added, and the alert clears, but origin fails this test. Allowing this alert to fire while we investigate why the taint is not added at node birth.
> OCPBUGS-45994: managed services: allow KubeDaemonSetMisScheduled alert

- OWNERS_ALIASES
- test/extended/dns/OWNERS
Fix the Network Ingress & DNS OWNERS files and add aliases to OWNERS_ALIASES.
modified:   OWNERS_ALIASES
new file:   test/extended/dns/OWNERS
modified:   test/extended/router/OWNERS
> NE-1870: Fix the Network Ingress & DNS OWNERS files and add aliases to OWNERS_ALIASES

- test/extended/prometheus/prometheus.go
it was 807 in the latest GCP run
> NO-JIRA: managed services: bump series limit

- test/extended/operators/management_plane_operators.go
We don't need these conditions, because we are no longer deploying snapshot webhook stuff in OCP.
See - https://github.com/openshift/cluster-csi-snapshot-controller-operator/pull/219
> STOR-2136: Remove CSI snapshot webhook conditions checks

- test/extended/etcd/etcd_storage_path.go
This is intended to fix:
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-kubernetes-2147-ci-4.19-e2e-aws-ovn-techpreview-serial/1867506662982553600
```
[sig-api-machinery] API data in etcd should be stored at the correct location and version for all resources [Serial] [Suite:openshift/conformance/serial] expand_less 	15s
{  fail [github.com/openshift/origin/test/extended/etcd/etcd_storage_path.go:482]: test failed:
no test data for resource.k8s.io/v1beta1, Kind=DeviceClass.  Please add a test for your new type to etcdStorageData.
no test data for resource.k8s.io/v1beta1, Kind=ResourceClaim.  Please add a test for your new type to etcdStorageData.
no test data for resource.k8s.io/v1beta1, Kind=ResourceClaimTemplate.  Please add a test for your new type to …
```
> CNTRLPLANE-1: Update etcd test data for 1.32 release

- pkg/testsuites/standard_suites.go
- test/extended/networking/ipsec.go
- test/extended/networking/util.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/clusterversion.go
The ipsec test suite takes about 5-6 hours to finish running the tests,  This PR optimizes ipsec tests such that it reboots only worker nodes for cert installation and tests execution time can be greatly reduced to 2-3 hrs.
> SDN-4168: Optimize timing for IPsec tests 

- test/extended/networking/network_segmentation.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
A copy of e2e from https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4696/
```
passed: (1m21s) 2024-12-05T18:24:51 "[sig-network][OCPFeatureGate:NetworkSegmentation][Feature:UserDefinedPrimaryNetworks] when using openshift ovn-kubernetes UDN Pod should react to k8s.ovn.org/open-default-ports annotations changes [Suite:openshift/conformance/parallel]"
```
from https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/29346/pull-ci-openshift-origin-master-e2e-gcp-ovn-techpreview/1864711104433754112
> SDN-5031: e2e,networking: add UDN open-default-ports annotation test.

- test/extended/testdata/bindata.go
- test/extended/testdata/builds/s2i-environment-build-app/Gemfile
**OCPBUGS-44257:fixing build s2i ruby test data inline with latest ruby version(>=3.0)**
The test data for s2i image creation with source type as binary has issues post base image upgrade to ruby 3.0 (test/extended/testdata/builds/test-env-build.json) This is because webrick server is removed from default ruby libraries from 3.0 version,hence a webserver should be installed externally.The test data is missing this causing permanant failure post ruby 3.0 upgrade.
This fix is updating the test data with required dependencies to create a stable app to fulfill the testcase criteria.
signed-off by : moebasim(mbasim@redhat.com)
> OCPBUGS-44257: Fixing build s2i ruby test data inline with latest ruby version(>=3.0)

- test/extended/images/layers.go
Look at the layers in the submanifest rather than the top level manifest if the imagestream is manifestlisted. Refer to the bug for details.
This fixes techpreview jobs for clusters installed with the multi-payload. Example of a failure: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-multiarch-master-nightly-4.19-ocp-e2e-aws-ovn-techpreview-multi-a-a/1873687894279852032
> OCPBUGS-47700: images: Fix layers test to work with manifestlisted imagestreams

- pkg/test/externalbinary/binary.go
- pkg/test/externalbinary/util.go
I had extracted this code, but I broke the case where we're getting the pull secret from the cluster -- because it was immediately getting deleted on return.  In-line the code instead to prevent that, so it gets deleted when we're done using it.
The error you get when this happens looks like:
```
error running options: could not create external binary provider: couldn't extract release payload image stream: failed extracting image-references from "quay.io/openshift-release-dev/ocp-release-nightly@sha256:856d044a4f97813fb31bc4edda39b05b2b7c02de1327b9b297bdf93edc08fa95": error during image extract: exit status 1 (error: unable to load --registry-config: stat /tmp/external-binary2166428580/.dockerconfigjson: no such file or directory
```
> OCPBUGS-48076: external binary: in-line registry auth file fetching

- test/extended/builds/OWNERS
- test/extended/testdata/builds/OWNERS
This PR updates the OWNERS file to include two additional members who can approve pull requests.
> OCPBUGS-47529: Add team members to the OWNERS file for PR approvals

- test/extended/networking/network_segmentation.go
Following the incoming changes of UserDefinedNetwork CRD condition type [1], tests that assert on the NetworkReady condition type should take in account the renamed type NetworkCreated to avoid CI breakage in the following scenarios:
- Production code changes reached D/S before tests code changes: Having the UDN CRD produce the new condition type (NetworkCreated), while e2e tests assert on the old condition type (NetworkReady).
- Tests code changes reached D/S before production code changes: Having the UDN CRD produce the old condition type (NetworkReady), while tests assert on the new condition type (NetworkCreated).
Change assertions on UDN condition type NetworkReady, expect condition type NetworkReady or NetworkCreated.
[1] https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4884
> SDN-4930: networksegmentation, udn: Wait for NetworkCreated or NetworkReady condition

- test/extended/networking/network_segmentation.go
Ported from: https://github.com/ovn-org/ovn-kubernetes/blob/a68ef49d9441ed0f938f99ff2d605506572b7b78/test/e2e/network_segmentation.go#L343-L358
Depends on: 
- https://github.com/ovn-org/ovn-kubernetes/pull/4805 in downstream.
- https://github.com/openshift/cluster-network-operator/pull/2492
> SDN-4930: Verify that a UDN pod can reach the kapi service in the default network

- test/extended/apiserver/access.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Add tests which check that kube-apiserver is reachable via service network, external and internal api endpoints.
In standarf e2e test flow this is being verified by monitor test, but cert rotation tests are disruptive and can't observe the cluster when time is being skewed to emulate age. As a result, these tests need to be oneshot verification tests
> OCPBUGS-43777: apiserver: add tests to verify kube-apiserver is accessible via different endpoints

- test/extended/networking/network_segmentation.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
This PR adds e2e tests for OVN-Kuberentes CluserUserDefinedNetwork CRD, introduced by https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4612.
Note to reviewer:
- Tests has been added as is from U/S repo, no logical changes has been done (1st & 2nd commits)
Any change required on those bits, require introducing the change on U/S and replicating these changes to D/S, after this PR is merged. In order to avoid diverging from U/S code.
- Due to flakes surfaced on OCP CI the some changes has been done on U/S https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4842, this PR changes were replicated to this PR as is (3-5 commits).
Any change required on those bits, require introducing the change on the PR on U/S and replicating these changes to this PR. In order to avoid diverging from U/S …
> SDN-5473: OVN-K: Port e2e tests for CUDN functionality, connectivity and isolation 

- test/extended/networking/network_segmentation.go
The test "Network Segmentation when primary network exist, UserDefinedNetwork status should report not-ready" may flake in case the tested UserDefinedNetwork instance conditions are not populated on the expected time.
This PR stabilize the test by wrapping the failing assertion with Eventually, so that the test wait for conditions to populate.
Note to reviewer:
This PR port the changes introduced on U/S https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4959 
- The test asserts for one of NetworkReady/Created conditions since the relevant bits has not been reached D/S yet.
> OCPBUGS-48569,SDN-4930: e2e,ovn-k,net-seg: Wait for UDN condition populate

- test/extended/networking/network_segmentation.go
`netConfig` pointer was being modified in a loop so pods were removed from only one namespace.
Upstream PR: https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4975.
/cc @ormergi @tssurya
> SDN-4930:  Fix pods cleanup in ClusterUserDefinedNetwork test

- test/extended/networking/network_segmentation.go
This PR should fix flakes related to using work IP family CIDR in IPv6 lanes for the following tests:
```
[sig-network][OCPFeatureGate:NetworkSegmentation][Feature:UserDefinedPrimaryNetworks] when using openshift ovn-kubernetes when primary network exist, ClusterUserDefinedNetwork status should report not-ready [Suite:openshift/conformance/parallel]
[sig-network][OCPFeatureGate:NetworkSegmentation][Feature:UserDefinedPrimaryNetworks] when using openshift ovn-kubernetes when primary network exist, UserDefinedNetwork status should report not-ready [Suite:openshift/conformance/parallel]
```
> OCPBUGS-48569,SDN-4930: ovn-k,net-seg: Use the right IP family according to env

- test/extended/networking/network_segmentation.go
https://github.com/ovn-kubernetes/ovn-kubernetes/commit/97d9b67ab59632e3bcebc66049b400c2a096e370
Modified the network condition. This commit makes it backwards compatible so that downstream merge will not be blocked.
/cc @trozet @ormergi @tssurya
> SDN-4930: Make UserDefinedNetwork status backwards compatible

- test/extended/networking/network_segmentation.go
Reverts openshift/origin#29301
This test change shouldn't have landed till the corresponding code change was brought in
see the 4.17 v/s 4.18 code diff:
https://github.com/openshift/ovn-kubernetes/blob/d60fad7b368831724701ebc90f6581a554eb673f/go-controller/pkg/clustermanager/userdefinednetwork/controller.go#L173
v/s
https://github.com/openshift/ovn-kubernetes/blob/930d8645c00fd2273c4cbb6e1d3c057e0967f0a1/go-controller/pkg/clustermanager/userdefinednetwork/controller.go#L390
> OCPBUGS-48634: Revert "[release-4.17] OCPBUGS-48459, SDN-4930: ovn-k, udn crd e2e: Fix status report consumer assertion"

- test/extended/networking/livemigration.go
- test/extended/networking/network_segmentation.go
- test/extended/networking/network_segmentation_endpointslice_mirror.go
- test/extended/networking/network_segmentation_policy.go
This label will be required for namespaces that wish to use a primary UDN.
Upstream test changes: https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4912
> OCPBUGS-42609: Updates UDN tests with required NS label

- test/extended/networking/network_segmentation.go
We are setting a pods annotations and ovnkube is supposed to react and remove the ACLs opening a specific port however DNC takes a long time to receive the event and perform said activities. Unknown why. Reduce flakes in the meantime until issue is understood.
> SDN-4930: E2Es for net seg: increase server connect timeout to reduce flakes

- test/extended/networking/network_segmentation.go
Originally the network primary UDN test that check isolation between overlapping subnets was creating a pair of namespaces with same subnet and then removing all the pods except one in one of them after that connectivitity was tested between that pod and the other network, problem arise at timing between deleting the pods and doing http request and sometimes traffic was success.
To overcome this this change just introduces different http ports per network so isolation can be tested between the two networks with overlapping ips and without deleting the pods.
> OCPBUGS-45607: network, net-seg use different http port per network

- test/extended/prometheus/collection_profiles.go
I think having the OC command being initialized at the global package level is causing some unwanted behavior since a `NewCLI` will instantiate a `BeforeEach`. We noticed flakes with `"Write to database call failed" len:164,err:users.user.openshift.io "e2e-test-monitoring-collection-profiles-pj9k5-user" already exists ` on TechPreview runs, which is a user created by this function seems to be executed multiple times.
/hold 
Holding for validation on Ginkgo lifecycle
> OCPBUGS-48629: move initialization of OC to test instead of package level

- test/extended/networking/multinetpolicy.go
The curl request is seen as waiting indefinitely though connect time set to 1s, so using max time for connect reestablishment to happen upon a failure.
Flaky job link: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.19-e2e-metal-ipi-ovn-dualstack-techpreview/1879675595101573120
> OCPBUGS-48629: Use max time for netpol pods curl requests

- test/extended/networking/network_segmentation.go
This PR increases the liveness and readiness probe failure threshold to 3 and also increases each probe's timeout to 3seconds instead of the default value 1 for both which is pretty aggressive.
We have seen failures of the following pattern:
```
Pod event: Type=Warning Reason=Unhealthy Message=Liveness probe failed: Get "http://[fd01:0:0:5::2ed]:9000/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers) LastTimestamp=2025-01-21 15:16:43 +0000 UTC Count=1
Pod event: Type=Normal Reason=Killing Message=Container agnhost-container failed liveness probe, will be restarted LastTimestamp=2025-01-21 15:16:43 +0000 UTC Count=1
Pod event: Type=Warning Reason=Unhealthy Message=Readiness probe failed: Get "http://[fd01:0:0:5::2ed]:9000/healthz": context deadline …
```
> OCPBUGS-48320,SDN-4930: Increase probe timeouts on UDN pod

- test/extended/testdata/bindata.go
- test/extended/testdata/signer-buildconfig.yaml
we have the following e2e test failing constantly:
```
Image signature workflow can push a signed image to openshift registry and verify it
```
this e2e is failing when attempting to build an image. the reported build failure is as follow:
```
error: build error: building at STEP "RUN source /etc/os-release && rhel_major=${VERSION_ID%!(BADPREC)%!}(MISSING) && yum config-manager --add-repo "https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi${rhel_major}/${rhel_major}/\$basearch/baseos/os/"     --add-repo "https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi${rhel_major}/${rhel_major}/\$basearch/appstream/os/"":
while running runtime: exit status 6
```
this error seems to be related to the yum wrapper that has been added to the image.
this pr makes the e2e to use the image directly …
> NO-JIRA: use quay.io/openshift/origin-cli:latest directly

- test/extended/prometheus/prometheus.go
When disableAllDefaultSources is true, all default catalogSource are disabled, so there is no metric.
```console
[
{
"metric": {
"__name__": "ALERTS",
"alertname": "OperatorHubSourceError",
"alertstate": "firing",
"container": "catalog-operator",
"endpoint": "https-metrics",
"exported_namespace": "openshift-marketplace",
"instance": "[fd01:0:0:1::1a]:8443",
"job": "catalog-operator-metrics",
"name": "community-operators",
"namespace": "openshift-operator-lifecycle-manager",
"pod": "catalog-operator-6c446dcbbb-sxvjz",
"prometheus": "openshift-monitoring/k8s",
"service": "catalog-operator-metrics",
"severity": "warning"
},
"value": [
1736751753.045,
"1"
]
}
]
```
> OCPBUGS-48340: skip OperatorHubSourceError metric checking when disableAllDefaultSources is true

- pkg/monitortests/kubeapiserver/auditloganalyzer/handle_excessive_applies.go
- pkg/monitortests/kubeapiserver/auditloganalyzer/handle_invalid_requests.go
- pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go
Along with users issuing too many updates its useful to list resources being updated often. Several users may update a single resource, so they may not show up in existing tests.
This PR adds another set of flaking tests `resource <group>.<resource>/<name> [-n <namespace>] has been updated too often` with error message similar to `resource <group>.<resource>/<name> [-n <namespace>] had <n> applies, check the audit log and operator log to figure out why  details in audit log`
> OCPBUGS-48126: kubeapiserver auditloganalyzer: show resources updated too often

- test/extended/networking/util.go
- test/extended/util/managed_services.go
This PR fixes recent test failures around nmstate deployment seen from CI runs.
1. [sig-auth] all workloads in ns/openshift-nmstate must set the 'openshift.io/required-scc' annotation
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/29437/pull-ci-openshift-origin-master-e2e-aws-ovn-ipsec-serial/1879584910717489152
2. Wait enough to get nmstate-handler daemonset running state.
```
[sig-network][Feature:IPsec] when using openshift ovn-kubernetes [BeforeAll] check traffic [apigroup:config.openshift.io] [Suite:openshift/network/ipsec] with IPsec in full mode
[BeforeAll] github.com/openshift/origin/test/extended/networking/ipsec.go:449
[It] github.com/openshift/origin/test/extended/networking/ipsec.go:628
[FAILED] Unexpected error:
<*errors.errorString | 0xc0015847e0>: …
```
> SDN-4168: Fix for nmstate deployment related failures

- pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go
"users in ns/openshift-... must not produce too many applies" test should contain correct error message when it flakes. This fixes it to change from:
```
{  details in audit log}
```
to
```
{user system:serviceaccount:openshift-infra:serviceaccount-pull-secrets-controller had 43897 applies, check the audit log and operator log to figure out why
user system:serviceaccount:openshift-infra:podsecurity-admission-label-syncer-controller had 1034 applies, check the audit log and operator log to figure out why  details in audit log}
```
> OCPBUGS-48053: auditLogAnalyzer: fix flake error message

- test/extended/networking/kubevirt/client.go
- test/extended/networking/livemigration.go
Now that we create the namespace for the tests NewCLIWithoutNamespace, implicitly another function is not called:
SetupProject->setupProject/setupNamespace->ChangeUser
ChangeUser will generate kubeconfig for the namespace user and set CLI.configPath. However we dont setup project, so we dont have a proper user account and the other scaffolding for a project. Therefore calling oc.DynamicClient or other OC commands that would use the user CLI.configPath wont work.
This would result in the "failed to open file" error because there was no user kubeconfig written to disk.
Just use admin for now.
> SDN-4930: Fix live migration tests

- test/extended/router/certs.go
- test/extended/router/config_manager.go
- test/extended/router/headers.go
- test/extended/router/metrics.go
- test/extended/router/reencrypt.go
- test/extended/router/router.go
- test/extended/router/scoped.go
- test/extended/router/unprivileged.go
- test/extended/router/weighted.go
- test/extended/testdata/bindata.go
- test/extended/testdata/router/reencrypt-serving-cert.yaml
- test/extended/util/net.go
curl requires that ipv6 addresses are in brackets. This change adds the IPUrl function to handle adding those brackets when necessary.
Several tests also create router pods directly, and thus require that the environment variable ROUTER_IP_V4_V6_MODE is set. Setting it to "v4v6" should allow the router to work in all environments.
This is part of the fix for OCPBUGS-26603.
> OCPBUGS-26603: e2e: Fix IPv6 handling in router tests.

- e2echart/e2e-chart-template.html
- pkg/defaultmonitortests/types.go
- pkg/monitor/monitorapi/construction.go
- pkg/monitor/monitorapi/types.go
- pkg/monitortests/kubeapiserver/staticpodinstall/analyzer.go
- pkg/monitortests/kubeapiserver/staticpodinstall/analyzer_test.go
- pkg/monitortests/kubeapiserver/staticpodinstall/kubeletlogparser/parser.go
- pkg/monitortests/kubeapiserver/staticpodinstall/kubeletlogparser/pleg_parser.go
- pkg/monitortests/kubeapiserver/staticpodinstall/kubeletlogparser/pleg_parser_test.go
- pkg/monitortests/kubeapiserver/staticpodinstall/kubeletlogparser/probe_parser.go
- pkg/monitortests/kubeapiserver/staticpodinstall/kubeletlogparser/probe_parser_test.go
- pkg/monitortests/kubeapiserver/staticpodinstall/monitortest.go
- pkg/monitortests/node/kubeletlogcollector/node.go
- test/extended/testdata/bindata.go
The monitor test works as follows:
- a) parse the kubelet log for SyncLoop lines (both PLEG and probe lines)
- b) generate events/interval for each of these lines from `a`
- c) add a monitor test that inspects the events from `b` and construct/compute new intervals:
- etcd installer pod duration (derived from PLEG container start, and exit )
- static pod (etcd for now) unready interval (derived from SyncLoop probe events)
This is an example, blue is installer pod duration, the red is etcd static pod unready window:
from: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/29462/pull-ci-openshift-origin-master-e2e-gcp-ovn-upgrade/1882095583997464576 
The monitor test also flakes if:
- it finds two concurrent installer pods running on separate nodes
- it finds two …
> no-jira: add a monitor test to detect concurrent installer pod or static pod

- test/extended/networking/livemigration.go
- test/extended/networking/network_segmentation.go
- test/extended/networking/network_segmentation_endpointslice_mirror.go
- test/extended/networking/network_segmentation_policy.go
Since we create our own namespaces for UDN, we need to wait for the cluster manager to annotate the namespace before we can try to create pods.
> SDN-4930: UDN tests wait for SCC annotation on namespace

- test/extended/apiserver/kubeconfigs.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Add tests to check two more kubeconfigs: check-endpoints and control-plane-node. These kubeconfigs are not present on the node, but available in kube-apiserver container only.
TODO:
> OCPBUGS-43777: tests: extend kubeconfig tests

- test/extended/networking/livemigration.go
- test/extended/networking/network_segmentation.go
Live migration test was launching a pod to determine if cluster is dualstack. This would happen before UDN is created, so it would fail on a namespace that was enabled for UDN (network did not exist yet).
The check is really not needed, since a few lines above we already determine if the cluster is dualstack or not via a service CIDR check. Leverage that.
> SDN-4930: Fix live migration test detecting dualstack

- e2echart/e2e-chart-template.html
- pkg/defaultmonitortests/types.go
- pkg/monitor/monitorapi/construction.go
- pkg/monitor/monitorapi/types.go
- pkg/monitortests/kubeapiserver/staticpodinstall/analyzer.go
- pkg/monitortests/kubeapiserver/staticpodinstall/analyzer_test.go
- pkg/monitortests/kubeapiserver/staticpodinstall/kubeletlogparser/parser.go
- pkg/monitortests/kubeapiserver/staticpodinstall/kubeletlogparser/pleg_parser.go
- pkg/monitortests/kubeapiserver/staticpodinstall/kubeletlogparser/pleg_parser_test.go
- pkg/monitortests/kubeapiserver/staticpodinstall/kubeletlogparser/probe_parser.go
- pkg/monitortests/kubeapiserver/staticpodinstall/kubeletlogparser/probe_parser_test.go
- pkg/monitortests/kubeapiserver/staticpodinstall/monitortest.go
- pkg/monitortests/node/kubeletlogcollector/node.go
- test/extended/testdata/bindata.go
Manually cherry-picked from https://github.com/openshift/origin/pull/29462, the pick is clean - I just had to resolve the conflicts in types.go for the constants and had to manually resolve the conflict in e2e-chart-template.html
We want to see if the test finds any failures in 4.17, so we can determine if it is a regression in 4.18
> OCPBUGS-49411: Add a monitor test to detect concurrent installer pod or static pod

- pkg/monitortests/network/legacynetworkmonitortests/networking.go
There's a statefulset test that does:
- create a pod that binds hostport 21017
- create a StatefulSet that also binds that hostport
- ensure that the StatefulSet can't be deployed to the node with the pod from the first step
- kill the conflicting pod
- ensure that the StatefulSet now gets deployed to that node
The problem is that apparently it's possible for the new StatefulSet pod to get deployed before the conflicting pod is fully cleaned up, in which case the first attempt at CreatePodSandBox will fail because it can't bind the hostport, but then the second attempt a bit later will succeed, and the e2e test doesn't even notice anything unusual happened. But openshift-tests notices the CreatePodSandBox failure and complains (eg, …
> OCPBUGS-48445: Ignore an error intentionally generated by a test case

- test/extended/networking/livemigration.go
- test/extended/networking/network_segmentation.go
- test/extended/networking/network_segmentation_endpointslice_mirror.go
- test/extended/networking/network_segmentation_policy.go
Platforms like SNO can be really slow. Waiting for SCC annotations wasn't enough. We also need to wait for service account as well to prevent flakes.
> SDN-4930: UDN: wait for moar openshift

- test/extended/networking/livemigration.go
- test/extended/networking/network_segmentation.go
- test/extended/networking/network_segmentation_endpointslice_mirror.go
Platforms like SNO can be really slow. Waiting for SCC annotations wasn't enough. We also need to wait for service account as well to prevent flakes.
Signed-off-by: Tim Rozet <trozet@redhat.com>
(cherry picked from commit 20a602244abd5f0a5b6557dd6ea229d3784a267d)
> [release-4.18] OCPBUGS-48460, SDN-4930: UDN: wait for moar openshift

- pkg/test/extensions/binary.go
- pkg/test/extensions/types.go
The enhancement calls for extensions that want to produce artifacts to write them to EXTENSION_ARTIFACT_DIR, this sets the path for each extension. Current design is to provide the dir but it's up to them to `mkdir -p` it -- I could be convinced to do that for them, but figure it's helpful when browsing CI artifacts to only see directories that have contents in them.
> TRT-1958: pass EXTENSION_ARTIFACT_DIR to binaries

- test/extended/router/stress.go
Previously, the router was configured without a readiness probe, resulting in racy startup conditions during router status stress tests. Routers would be marked as ready immediately upon starting, causing the waitForReadyReplicaSet function to proceed prematurely. This allowed the next step of route creation to occur before the routers had fully initialized.
This often led to the first two routers to fight over the route status while the third router was still starting. As a result, the third router missed observing these early status contentions, leading to more writes to the route status than we were expecting.
Adding the readiness probe also revealed that HAProxy was failing to start due to insufficient permissions. The anyuid SCC was added to the router's service account to resolve …
> OCPBUGS-44238: Add Readiness Probe to Router Status Tests

- test/extended/networking/network_segmentation.go
UDN ready timeout was using a constant, that is going to be changed to 60 seconds by:
https://github.com/openshift/origin/pull/29510
The CUDN ready timeout should use the same value.
> SDN-4930: Make CUDN ready timeout use constant

- test/extended/networking/network_segmentation.go
Metal platform is slow, and we can see it take over 4 minutes sometimes for the UDN pod to become ready.
Flake seen taking 4 minutes and 1 second:
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.19-e2e-metal-ipi-ovn-ipv6-techpreview/1884817018687852544
when using openshift ovn-kubernetes created using NetworkAttachmentDefinitions is isolated from the default network with L2 primary UDN
```
STEP: asserting the UDN pod udn-pod reaches the `Ready` state @ 01/30/25 06:35:55.176
I0130 06:39:56.485941    4237 cni.go:332] [e2e-network-segmentation-e2e-7214/udn-pod c2e64986fc2baa86e2fc2aeb3728175dfbe7d5832156f14fab1782e54faedb26 network default NAD default] ADD finished CNI request [e2e-network-segmentation-e2e-7214/udn-pod …
```
> SDN-4930: Bump UDN pod ready timeout

- test/extended/networking/network_segmentation.go
a flake was seen where a test pod was restarted because the startup probe failed 3 times in 3 seconds (connection refused) with the first probe fired 1s after the pod was marked as Started. Digging through the logs, the pod did seem to come up in time and nothing egregious in the node or networking pod logs.
the current theory and hope is that the test pod containers app hadn't fully been ready and listening for the probes and increasing this startup delay will be a little nicer in this case.
> SDN-4930: increase probe initialDelaySeconds from 1 to 5

- test/extended/networking/network_segmentation.go
Kube can take longer than 5 seconds to propagate events.
Seen as flake in CI run:
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.19-e2e-aws-ovn-techpreview/1884817108601147392
"when using openshift ovn-kubernetes UserDefinedNetwork CRD controller should create NetworkAttachmentDefinition according to spec"
I0130 05:39:30.032220       1 controller.go:415] Added Finalizer to UserDefinedNetwork [e2e-network-segmentation-e2e-8121/test-net]
I0130 05:39:30.196059       1 nad_controller.go:245] [clustermanager-nad-controller NAD controller]: finished syncing NAD e2e-network-segmentation-e2e-8121/test-net, took 118.678698ms
I0130 05:39:30.196212       1 secondary_network_cluster_manager.go:62] Creating new network controller for network …
> SDN-4930: Bump wait for UDN CR ready timeout

- test/extended/prometheus/collection_profiles.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
- [[Prow]](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-origin-29307-nightly-4.18-e2e-metal-ipi-ovn-dualstack-techpreview/1858916202634547200) After merging https://github.com/openshift/origin/pull/28889, we found out that the tests were failing on bare-metal, due to the absence of a configmap, and the fact that the tests were "leaving" a new configmap in a malformed state (without a `config.yaml` key).
```
{  fail [github.com/openshift/origin/test/extended/prometheus/prometheus.go:405]: could not determine if Telemetry is enabled: openshift-monitoring/cluster-monitoring-config data lacks a config.yaml key: map[]
Ginkgo exit error 1: exit with code 1}
```
- To address this, https://github.com/openshift/origin/pull/29309 was merged that seemed to …
> OCPBUGS-45153: address malformed configmap post-test

- test/extended/networking/livemigration.go
Checking if the CR was created can take longer than 5 seconds if the cluster is loaded. Bring it inline with other tests to 60 seconds.
Network ready timeout can be much longer than 5 seconds. Create a timeout just for that, and for now make it 5 minutes due to the known bug where network start up takes too long:
https://issues.redhat.com/browse/OCPBUGS-49727
> SDN-4930: Increases timeouts for live migration

- test/extended/networking/network_segmentation.go
With https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4889 the network name is going to change for UDNs. Update tests in advance.
> OCPBUGS-45893: Allows for backwards compatibility with upcoming network name change

- test/extended/networking/egress_firewall.go
- test/extended/testdata/bindata.go
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-wildcard-test.yaml
- test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
This PR adds test case for checking EgressFirewall DNS names in caps.
> NO-JIRA: Add test case for checking EgressFirewall DNS names in caps

- test/extended/networking/egress_firewall.go
- test/extended/testdata/bindata.go
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-wildcard-test.yaml
- test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
Reverts openshift/origin#29414
Just checking if this is causing issues on Azure.
> TRT-2006: Revert "NO-JIRA: Add test case for checking EgressFirewall DNS names in caps"

- go.mod
- go.sum
- vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
- vendor/github.com/onsi/ginkgo/v2/Makefile
- vendor/github.com/onsi/ginkgo/v2/OWNERS
- vendor/github.com/onsi/ginkgo/v2/core_dsl_patch.go
- vendor/github.com/onsi/ginkgo/v2/formatter/formatter.go
- vendor/github.com/onsi/ginkgo/v2/ginkgo/build/build_command.go
- vendor/github.com/onsi/ginkgo/v2/ginkgo/internal/compile.go
- vendor/github.com/onsi/ginkgo/v2/internal/spec_patch.go
- vendor/github.com/onsi/ginkgo/v2/types/config.go
- vendor/github.com/onsi/ginkgo/v2/types/types.go
- vendor/github.com/onsi/ginkgo/v2/types/types_patch.go
- vendor/github.com/onsi/ginkgo/v2/types/version.go
- vendor/modules.txt
We missed this when bumped the o/k dependency to 1.32.
/hold
Until we get a good nightly with the o/k bump.
> CNTRLPLANE-1: Bump to latest downstream version of ginkgo

- test/extended/testdata/bindata.go
- test/extended/testdata/signer-buildconfig.yaml
The DNF wrapper should no longer fail when it is not connected to the VPN after https://github.com/openshift-eng/ocp-build-data/pull/6019
> Revert "NO-JIRA: use quay.io/openshift/origin-cli:latest directly"

- e2echart/e2e-chart-template.html
- pkg/monitor/monitorapi/types.go
- pkg/monitortests/testframework/operatorloganalyzer/operator_log_scraper.go
- test/extended/testdata/bindata.go
Update `operator_log_scraper.go` to record start/finish of etcd bootstrap member removal. This also updates other events tracked there to have a duration of 1 sec otherwise these are not being displayed on spyglass interval chart
> OCPBUGS-49600: Display etcd bootstrap event on timeline

- pkg/clioptions/clusterdiscovery/cluster.go
- pkg/test/extensions/binary.go
- pkg/test/extensions/types.go
- pkg/test/ginkgo/cmd_runsuite.go
The values for these flags are determined by inspecting the cluster.
There will also be an additional PR to translate the current test skips in `openshift/kubernetes` to utilize these flags instead.
For: https://issues.redhat.com/browse/TRT-1853
> TRT-1853: Pass applicable environment flags to the external binary

- test/extended/builds/OWNERS
- test/extended/testdata/builds/OWNERS
new build components owners are added and old ones removed
> OCPBUGS-48749: Add/remove team members to the OWNERS file for Builds

- test/extended/router/h2spec.go
- test/extended/router/http2.go
After local tests on an AWS cluster, I don't see the limitation for the HTTP/2 support on AWS CLB (default LB type) anymore. This PR re-introduces https://github.com/openshift/origin/pull/28515 which was reverted by https://github.com/openshift/origin/pull/28905.
> OCPBUGS-26601: Re-enable AWS for router HTTP/2 test

- pkg/test/extensions/README.md
- pkg/test/extensions/binary.go
- pkg/test/extensions/provider.go
- pkg/test/extensions/provider_test.go
This makes it easier to do local development.
> NO-JIRA: Allow overriding extension binary to local path

- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
caused by the kube bump and needed to fix failing jobs in https://github.com/openshift/openshift-controller-manager/pull/366
> WRKLDS-1653: update pathological ScalingReplicaSet event exception

- pkg/monitortestlibrary/platformidentification/operator_mapping.go
- pkg/monitortests/clusterversionoperator/terminationmessagepolicy/monitortest.go
Aggregation failures for [gcp-ovn-rt-upgrade](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/aggregated-gcp-ovn-rt-upgrade-4.19-minor-release-openshift-release-analysis-aggregator/1888480534607171584) due to the namespace `openshift-infra` showing up in only 1 out of 10 runs.
[Sippy](https://sippy.dptools.openshift.org/sippy-ng/tests/4.19?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522variants%2522%252C%2522not%2522%253Atrue%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522aggregated%2522%257D%252C%257B%2522id%2522%253A99%252C%2522columnField%2522%253A%2522name%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522all%2520containers%2520in%2520ns%252Fopenshift-infra%2520must%2520have% …
> NO-JIRA: Support known namespaces for terminationMessagePolicy tests

- test/extended/machine_config/helpers.go
[These tests ](https://github.com/openshift/origin/blob/1e0a8370f673513a40720f9c597a7028922d17db/test/extended/machine_config/boot_image_update_gcp.go#L44-L46)are failing as they use a fake disk image as part of a patch when checking GCP disk reconciliation.
This is due to recent changes with disk reconciliation on GCP: https://github.com/openshift/machine-api-provider-gcp/pull/108. We now check if the disk is UEFI compatible before trying to create the machine. 
This change updates the fake patch to use a real disk image.
> OCPBUGS-51373: use non-fake boot image for patch

- test/extended/images/info.go
`latest` tag in `quay.io/coreos/etcd` image has been removed. This PR updates the test to use `quay.io/openshift-release-dev/ocp-release:4.18.3-x86_64`.
> OCPBUGS-52578: Use payload pullspec for image info test

- pkg/monitortests/clusterversionoperator/legacycvomonitortests/operators.go
After we collect the known exceptions, we are removing the default flake behavior to catch any new regressions.
> TRT-1575: Fail the test when an expected operator goes to degraded

- test/extended/olm/olmv1.go
Value was previously hardcoded. Can be replaced now since openshift/api has been bumped and has the `configv1.ClusterVersionCapabilityOperatorLifecycleManagerV1` constant.
> NO-ISSUE: replace hardcoded ClusterVersionCapability string in olmv1 tests

- pkg/monitortests/node/legacynodemonitortests/exclusions.go
What type of PR is this?
Test Case Re-Enable
What this PR does / why we need it?
Previously, the managed-upgrade-operator test was excluded due to failures related to a known issue.
Now, after verification, the issue no longer exists. The test should be re-enabled to ensure the managed-upgrade-operator is properly monitored in CI.
By removing this exclusion, we allow failures to be properly detected and addressed in future OpenShift releases.
Key Changes:
- Removed the exclusion entry for `managed-upgrade-operator` in `exclusions.go`.  
Which Jira/GitHub issue(s) this PR fixes?
Part of [https://issues.redhat.com/browse/OSD-26270]
Special notes for your reviewer:
This PR removes the exclusion of `managed-upgrade-operator`, re-enabling the test in CI.  
Issue verification was done on …
> OSD-26270: re-enabled managed-upgrade-operator test by removing exclusion

- test/extended/machine_config/boot_image_update_agnostic.go
- test/extended/machine_config/boot_image_update_aws.go
- test/extended/machine_config/boot_image_update_gcp.go
- test/extended/machine_config/helpers.go
- test/extended/testdata/bindata.go
- test/extended/testdata/machine_config/machineconfigurations/managedbootimages-empty.yaml
This PR modifies boot image update tests:
- Use the explicit opt-out knob when opting out
- Skip the degrade test temporarily
- ensure cleanups are done in success or fail
> MCO-1594: updates for ManagedBootImageStatus

- test/extended/networking/egress_firewall.go
- test/extended/testdata/bindata.go
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-wildcard-test.yaml
- test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
docs.openshift.com got moved to docs.redhat.com and our egress firewall/egressnetworkpolicy tests were using that fqdn to curl and test for egress firewall functionality. With the DNS name no longer resolving, these tests need to be updated to the docs.redhat.com server instead.
> OCPBUGS-52358: Fix egress firewall tests by updating the URL from docs.openshift.com to docs.redhat.com after docs migration

- test/extended/networking/livemigration.go
This - l2bridge - is the binding which we will use on 4.18 and 4.19.
In later releases we expect passt to replace it, but, its shortcomings (unable to preserve TCP connections during live migration) make it a bad candidate for the binding of the primary network attachment.
> SDN-5768: virt, udn: use l2bridge binding

- test/extended/builds/OWNERS
New owners added to build component and old ones removed
> OCPBUGS-53285: Add/remove team members to the OWNERS file for Builds

- test/extended/networking/egress_firewall.go
- test/extended/testdata/bindata.go
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-wildcard-test.yaml
- test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
This PR updates the egressfirewall tests to use redhat.com instead of docs.redhat.com as there are a lot of failure encountered for this URL. The issue with docs.redhat.com is that the TTL is very low (20s) because of which the ovnkube-node and the test pod are resolving to different IP addresses as shown in the following analysis:
- https://github.com/openshift/release/pull/62968#issuecomment-2740905648
- https://github.com/openshift/release/pull/62968#issuecomment-2740933499
The TTL of redhat.com is very large (2695s) which will ensure that the failure of the test is very less.
> OCPBUGS-52358: Fix egress firewall tests by updating the URL from docs.redhat.com to redhat.com

- test/extended/machine_config/boot_image_update_agnostic.go
- test/extended/machine_config/boot_image_update_aws.go
- test/extended/machine_config/boot_image_update_gcp.go
- test/extended/machine_config/helpers.go
Follow-up to https://github.com/openshift/origin/pull/29625 
This encapsulate the apply and wait into a single function, and also added it to a couple of spots that I missed in the original PR.
> NO-ISSUE: Clean up MachineConfiguration fixture apply 

- test/extended/router/gatewayapi.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/client.go
- zz_generated.manifests/test-reporting.yaml
Implements e2e tests for GatewayAPI featuregate. These tests cover the following scenarios:
- Verify Gateway API CRDs and esnure required CRDs should already be installed
- Verfiy Gateway API CRDs and ensure existing CRDs can not be deleted
- Verify Gateway API CRDs and ensure existing CRDs can not be updated
- Verify Gateway API CRDs and ensure CRD of standard group can not be created
- Verify Gateway API CRDs and ensure CRD of experimental group is not installed
- Verify Gateway API CRDs and ensure CRD of experimental group can not be created
requires https://github.com/openshift/cluster-ingress-operator/pull/1192
> NE-1968: add e2e tests for FeatureGate GatewayAPI

- test/extended/operators/check_crd_status.go
- test/extended/operators/check_crd_status_test.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
"[sig-arch][Early] CRDs for openshift.io should have a status in the CRD schema" is no longer relevant.
We only want to be checking for:
If a CRD has a "status" field in the schema but no subresource.status defined. (which causes several problems). Its covered by an existing test "[sig-arch][Early] CRDs for openshift.io should have subresource.status". Hence leaving no need for the prior test to exist.
This work blocks https://github.com/openshift/api/pull/2257, which is necessary to ship PIS as a feature for 4.19
> MCO-1631: Remove "[sig-arch][Early] CRDs for openshift.io should have a status in the CRD schema"

- pkg/clioptions/clusterdiscovery/provider.go
- test/extended/util/external/provider.go
This change register the platform type `external` as a valid `provider` (flag) when running the conformance tests.
This is required if we need more refinement when running conformance tests in that platform type (`External`), which was design inheriting from `None`. EP for more information: https://github.com/openshift/enhancements/blob/master/enhancements/cloud-integration/infrastructure-external-platform-type.md
For more information about the tests executed in this PR, see this comment: https://github.com/openshift/origin/pull/29623#issuecomment-2772616129
[1] OCPBUGS-53249 - The following PR implements granular skips for platform specific on tests coming from kubernetes suites: https://github.com/openshift/kubernetes/pull/2247
> OCPBUGS-53249: feat: support platform type external

- test/extended/router/external_certificate.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
Implements end-to-end tests for routes configured with ExternalCertificate feature. These tests cover the following scenarios:
- Validation and pre-requisite of the feature
- Router serviceaccount should have permission to read the secret.
- The route and the referenced secret must exist in the same namespace.
- The secret should be of type `kubernetes.io/tls`.
- Route with `Passthrough` termination is not supported.
- Both external certificates and inline certificates are not allowed.
- With a valid setup the router should support external certificate.
- Multiple routes can refer a common secret.
- Secret delete, re-create and update scenarios. 
- With RBAC permissions validation.
- Route update scenarios (with validation checks)
- To use a new external certificate.
- To use the same …
> OAPE-91: Add E2E tests for Route ExternalCertificate feature

- test/extended/cli/idle.go
`endpoints` has been deprecated in 1.33 officially and we'll get deprecation warnings that causes failures in our test suite. This PR switches to `endpointslices` to fix the issue permanently in idling tests.
> CNTRLPLANE-371: Use endpointslices in idling tests instead of deprecated endpoints

- pkg/monitortests/network/legacynetworkmonitortests/networking.go
according to the comment in this test case, the Garbage Collector tests which create the "simpletest-rc-to-be-deleted.*" pods is ok to have sandbox creation failures. This specific message below was not being checked and has started to show up recently. skip this case:
"failed to create pod network sandbox"
> OCPBUGS-53279: add failure case to skip in testPodSandboxCreation()

- test/extended/router/external_certificate.go
We are seeing failures in `metal` platforms, so we are temporarily skipping the tests in metal. 
- E2E PR: https://github.com/openshift/origin/pull/29499
> OAPE-91: Route ExternalCertificate: Skip e2e jobs for bare metal platform

- pkg/monitor/monitorapi/construction.go
- pkg/monitor/monitorapi/types.go
- pkg/monitortests/kubeapiserver/apiunreachablefromclientmetrics/monitortest.go
- pkg/monitortests/kubeapiserver/apiunreachablefromclientmetrics/monitortest_test.go
- pkg/monitortests/kubeapiserver/apiunreachablefromclientmetrics/resolver.go
in addition to the `host` view (load balancer type), api-unreachable breaks it down by kubelet, kcm, and scheduler
taken from: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/29070/pull-ci-openshift-origin-main-e2e-vsphere-ovn-etcd-scaling/1909601067327295488
> NO-JIRA: add api error rate observed by kubelet, kcm, and scheduler

- test/extended/networking/egress_firewall.go
- test/extended/testdata/bindata.go
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-wildcard-test.yaml
- test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
Manual backport of #29604 & #29618
> OCPBUGS-54725: Fix egress firewall tests by updating the URL from docs.openshift.com to redhat.com

- pkg/test/extensions/binary.go
[SPLAT-2060](https://issues.redhat.com//browse/SPLAT-2060)
- Registered Machine API tests extension
> SPLAT-2060: Registered Machine API tests extension

- test/extended/router/external_certificate.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
Fix e2e tests related to Route ExternalCertificate for `metal` platform.
There are three variants of `metal` job: `ipv4` , `dualstack`, and `ipv6`.
- For metal `ipv4` and `dualstack` we need to send the traffic from another exec pod instead of test platform.
- For `ipv6`, added `[Skipped:Disconnected]` since it requires internet access. [Slack thread](https://redhat-internal.slack.com/archives/C01CQA76KMX/p1744033603592919?thread_ts=1744026389.400969&cid=C01CQA76KMX).
- Follow up on temporary skip PR : https://github.com/openshift/origin/pull/29651
- Actual e2e PR: https://github.com/openshift/origin/pull/29499
> OCPBUGS-54661: Route ExternalCertificate: Fix e2e tests for metal platform

- test/extended/networking/egress_firewall.go
- test/extended/testdata/bindata.go
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
- test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
> [release-4.16] OCPBUGS-54768: Fix egress firewall tests by updating the URL from docs.openshift.com to redhat.com

- test/extended/machine_config/OWNERS
- test/extended/machine_config/helpers.go
- test/extended/machine_config/machine_config_node.go
- test/extended/testdata/bindata.go
- test/extended/testdata/machine_config/machineconfig/0-infra-mc.yaml
- test/extended/testdata/machine_config/machineconfig/0-master-mc.yaml
- test/extended/testdata/machine_config/machineconfig/1-master-invalid-mc.yaml
- test/extended/testdata/machine_config/machineconfig/1-worker-invalid-mc.yaml
- test/extended/testdata/machine_config/machineconfigpool/infra-mcp.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
Contributors: @isabella-janssen @pablintino @djoshy 
- All current MCO team members added to the /machine_config owners file.
- Adds tests for MCO's MachineConfigNode feature.
- This includes a cherry pick of https://github.com/openshift/origin/pull/29619/commits/8bd781e5f7eb0f817df402e5b446ee1918224d1d.
- All tests should run successfully with a cluster built on `4.19.0-0.nightly-2025-03-21-030708` or later with tech preview enabled.
- The tests for [MCO-1595](https://issues.redhat.com/browse/MCO-1595) & [MCO-1596](https://issues.redhat.com/browse/MCO-1596) will both run in the default serial suite since they can impact other tests through pool creation and updates.
- The tests for [MCO-1597](https://issues.redhat.com//browse/MCO-1597) & …
> MCO-1520: Add MachineConfigNode e2e tests

- test/extended/machine_config/pinnedimages.go
SNO cluster has a single node labelled with master and worker. Attempt to make a MCP from the master node will fail and any applied MC will fail as well
> MCO-1636: skip PIS custom pool checks on SNO cluster

- pkg/monitortests/network/disruptionpodnetwork/host-network-target-deployment.yaml
- pkg/monitortests/network/disruptionpodnetwork/host-network-to-host-network-poller-deployment.yaml
- pkg/monitortests/network/disruptionpodnetwork/host-network-to-pod-network-poller-deployment.yaml
- pkg/monitortests/network/disruptionpodnetwork/host-network-to-service-poller-deployment.yaml
- pkg/monitortests/network/disruptionpodnetwork/pod-network-target-deployment.yaml
- pkg/monitortests/network/disruptionpodnetwork/pod-network-to-host-network-poller-deployment.yaml
- pkg/monitortests/network/disruptionpodnetwork/pod-network-to-pod-network-poller-deployment.yaml
- pkg/monitortests/network/disruptionpodnetwork/pod-network-to-service-poller-deployment.yaml
- test/extended/arbiter_topology/arbiter_topology.go
- test/extended/cpu_partitioning/crio.go
- test/extended/cpu_partitioning/utils.go
Resolves failures in CRI-O workload partitioning tests
Resolves failures in Pod-Poller tests
> OCPEDGE-1675: feat: update some tests to account for the arbiter node

- test/extended/router/external_certificate.go
The e2e tests are failing on AWS ARM64 platform.
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-multiarch-master-nightly-4.19-ocp-e2e-aws-ovn-techpreview-multi-a-a/1909765152207540224
```
Failed to get endpoints for e2e-test-router-external-certificate-z6z2b/hello-openshift 
```
The failure is because `openshift/hello-openshift` is not a multi-arch image.
The [pod log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-multiarch-master-nightly-4.19-ocp-e2e-aws-ovn-techpreview-multi-a-a/1909765152207540224/artifacts/ocp-e2e-aws-ovn-techpreview-multi-a-a/openshift-e2e-test/artifacts/junit/e2e-test-router-external-certificate-5cst4/hello-openshift/hello-openshift/logs.txt) said
```
exec container …
```
> OCPBUGS-54906: Change the test image to registry.k8s.io/e2e-test-images/agnhost

- test/extended/networking/egress_firewall.go
- test/extended/testdata/bindata.go
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
- test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
> [release-4.15] OCPBUGS-54769: Fix egress firewall tests by updating the URL from docs.openshift.com to redhat.com

- test/extended/networking/egress_firewall.go
- test/extended/testdata/bindata.go
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
- test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
> [release-4.14] OCPBUGS-54770: Fix egress firewall tests by updating the URL from docs.openshift.com to redhat.com

- test/extended/networking/egress_firewall.go
- test/extended/testdata/bindata.go
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
- test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
Fix egress firewall tests by updating the URL from docs.redhat.com to redhat.com
> OCPBUGS-54771: Component Readiness: [Networking / ovn-kubernetes] [EgressFirewall] test regressed

- test/extended/prometheus/collection_profiles.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
Backport `MetricsCollectionProfiles` patches to 4.18 to make Sippy happy as it is on 4.19 for the same feature-gate.
> OCPBUGS-55110: Backport `MetricsCollectionProfiles` patches to 4.18

- test/extended/operators/resources.go
Add an exception for Istio pods that specify resource limits.
> OCPBUGS-54651: resources: Add limit exceptions for Istio

- test/extended/router/external_certificate.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
- We switched to `registry.k8s.io/e2e-test-images/agnhost` image in https://github.com/openshift/origin/pull/29672 
- `registry.k8s.io/e2e-test-images/agnhost`  is mirrored in metal ipv6, so there won't be image pull issues in the Disconnected environment. 
- This PR removes  `[Skipped:Disconnected]` annotation to allow metal ipv6 job.
> OCPBUGS-54906: Remove [Skipped:Disconnected] from the test name to allow metal ipv6

- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/sharder.go
- pkg/test/ginkgo/sharder_test.go
Design doc https://docs.google.com/document/d/14uXl_JF-n7WvJj7xQOmn7wRm71LM7Fbuw-2QnP_-bTs/edit?tab=t.0
Parallelizes test execution by distributing tests across multiple CI jobs. 
Results:
- 2h25m https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/29696/pull-ci-openshift-origin-main-e2e-aws-ovn-serial-shard-1/1914824055555362816
- 2h30m https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/29696/pull-ci-openshift-origin-main-e2e-aws-ovn-serial-shard-2/1914852911179894784
> TRT-2086: Support sharding tests across multiple invocations of openshift-tests

- pkg/monitortests/testframework/knownimagechecker/monitortest.go
This issue was peviously reported and even fixed through https://github.com/openshift/origin/pull/28357, but it was reverted by https://github.com/openshift/origin/pull/28367. Instead of changing the images, add this image to the allowed list so the test doesn't flake
> OCPBUGS-22413: Add myql-80 to fix known image check test for OKD

- pkg/monitortests/kubeapiserver/auditloganalyzer/handle_audit_latency.go
- pkg/monitortests/kubeapiserver/auditloganalyzer/handle_audit_latency_test.go
- pkg/monitortests/kubeapiserver/auditloganalyzer/handle_audit_violation.go
- pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go
[TRT-2043](https://issues.redhat.com/browse/TRT-2043) Provides initial implementation tracking etcd and total latency for audit records..  Creating 0,1, 2,5... second buckets to count requests that fall within each individual range (count only applies to one bucket, 5s does not also count as 1 or 2)
> TRT-2043: look for high latency audit requests

- test/extended/machine_config/machine_config_node.go
- test/extended/machine_config/pinnedimages.go
Closes: OCPBUGS-55342
Per [this Slack message](https://redhat-internal.slack.com/archives/CE4L0F143/p1745431032849839?thread_ts=1744910197.447789&cid=CE4L0F143) from @yuqi-zhang, MachineConfigNodes and PinnedImageSets are not supported features on Hypershift. Therefore, the tests for these features should be skipped on the Hypershift platform.
- Skip tests related to the `PinnedImages` and `MachineConfigNodes` feature gates on Hypershift.
> OCPBUGS-55342: Skip Hypershift for MachineConfigNodes and PinnedImages tests

- test/extended/olm/olmv1.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
Introduces tests for the new `api/v1/metas` endpoint when NewOLMCatalogdAPIV1Metas feature gate in enabled.
> OPRUN-3692: Olmv1-catalogd tests for API endpoints

- pkg/monitortests/kubeapiserver/auditloganalyzer/handle_operator_watch_count_tracking.go
Reverts openshift/origin#29674
Failing hypershift
validate fix with `/payload-job periodic-ci-openshift-hypershift-release-4.19-periodics-e2e-aws-ovn-conformance`
> Revert "TRT-2049: check for any watch requests"

- test/extended/machine_config/helpers.go
- test/extended/machine_config/pinnedimages.go
Contributors: @RishabhSaini & @isabella-janssen 
This temporarily skips all PIS tests on metal and the `All Nodes in a standard Pool should have the PinnedImages PIS` on SNO while the team addresses OCPBUGS-55394 & OCPBUGS-55384.
> NO ISSUE: Temporarily skip PinnedImageSet tests on SNO & metal

- test/extended/olm/olmv1-preflight.go
- test/extended/olm/olmv1.go
- test/extended/testdata/bindata.go
- test/extended/testdata/olmv1/install-pipeline-operator-0.yaml
- test/extended/testdata/olmv1/install-pipeline-operator-1.yaml
- test/extended/testdata/olmv1/install-pipeline-operator-2.yaml
- test/extended/testdata/olmv1/install-pipeline-operator-3.yaml
- test/extended/testdata/olmv1/install-pipeline-operator-4.yaml
- test/extended/testdata/olmv1/install-pipeline-operator-5.yaml
- test/extended/testdata/olmv1/install-pipeline-operator-6.yaml
- test/extended/testdata/olmv1/install-pipeline-operator-base.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
Adds several data files, of which -0 is the basic one that allows for installation, and -1 through -6 have minor removals to cause a failure. They are each combined with -base to attempt to install an operator.
> OPRUN-3782: OLMv1: Add support for preflight permissions checks

- test/extended/router/external_certificate.go
This PR will decide the default cert issuer name for Managed Service clusters (ROSA classic). 
If the tests are running on Managed Service cluster, the default cert issuer name would be `R11`
See [Slack Thread](https://redhat-internal.slack.com/archives/C01CQA76KMX/p1745844051668559)
> TRT-2092: Fix default cert issuer name for Managed Service cluster (ROSA classic) in `RouteExternalCertificate` test case

- test/extended/olm/olmv1-preflight.go
- test/extended/olm/olmv1.go
- test/extended/testdata/bindata.go
- test/extended/testdata/olmv1/install-pipeline-operator-0.yaml
- test/extended/testdata/olmv1/install-pipeline-operator-1.yaml
- test/extended/testdata/olmv1/install-pipeline-operator-2.yaml
- test/extended/testdata/olmv1/install-pipeline-operator-3.yaml
- test/extended/testdata/olmv1/install-pipeline-operator-4.yaml
- test/extended/testdata/olmv1/install-pipeline-operator-5.yaml
- test/extended/testdata/olmv1/install-pipeline-operator-6.yaml
- test/extended/testdata/olmv1/install-pipeline-operator-base.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
Adds several data files, of which -0 is the basic one that allows for installation, and -1 through -6 have minor removals to cause a failure. They are each combined with -base to attempt to install an operator.
This reapplies cf207152efc99fb5474650649bddd43cea89c71b with fixes due to upstream-to-downstream merge.
> OPRUN-3783: OLMv1: Add support for preflight permissions checks (fixed)

- test/extended/builds/start.go
The following test case "[sig-builds][Feature:Builds][Slow] starting a build using CLI" and its sub cases are modified to ensure the git-clone container does not run privileged and with minimum capabilities enabled.This is to address "CVE-2024-45496: .gitconfig can be abused to run aritrary commands".
> OCPBUGS-42044: [build] Ensure Git Clone Does Not Run Privileged

- test/extended/router/certgen/certgen.go
- test/extended/router/external_certificate.go
- test/extended/router/grpc-interop.go
- test/extended/router/http2.go
The current logic for verifying the default certificate relies on checking the issuer CommonName against predefined values for different cluster profiles (Self-Managed, HyperShift, Managed Service). However, for managed service clusters (like ROSA), the default certificate issuer CN is dynamic (e.g. R10, R11, etc.), making it difficult to know the exact value beforehand.
This PR modifies the verification logic to handle the dynamic issuer CN. Instead of checking for a specific CN, the updated logic checks if the certificate is not issued by the external certificate issuer. This ensures that the route will not use the external certificate once removed.
Follow up: https://github.com/openshift/origin/pull/29731
> TRT-2092: Fix default cert issuer name in RouteExternalCertificate test case

- test/extended/networking/tap.go
This change prevents the test `"[sig-network][Feature:tap] should create a pod with a tap interface"`  to fail when selecting a worker node that have taints applied to it. This is impacting some variants such as aws/edge (or similar setup) nodes when the first node in the worker list is the edge node, which have `NoSchedule` taints.
This is a permanent failure in CI in edge zones. This is an an example of failed job: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.15-e2e-aws-ovn-shared-vpc-edge-zones/1908671470251282432
~~~
lastTransitionTime: "2025-04-06T02:03:23Z"
message: '0/8 nodes are available: 2 node(s) had untolerated taint {node-role.kubernetes.io/edge:
}, 3 node(s) didn''t match Pod''s node affinity/selector, 3 …
> OCPBUGS-54700: aws/edge: prevent test using unschedulable nodes

- test/extended/networking/egress_firewall.go
- test/extended/testdata/bindata.go
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
- test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
OCPBUGS-54772: Fix egress firewall tests by updating the URL from docs.redhat.com to redhat.com
> OCPBUGS-54772: Component Readiness: [Networking / ovn-kubernetes] [EgressFirewall] test regressed

- test/extended/machine_config/helpers.go
- test/extended/machine_config/machine_config_node.go
This closes OCPBUGS-55441.
- Updates `Should have MCN properties matching associated node properties for nodes in default MCPs` in standard two-node Openshift to test for only master MCP association.
- Updates `Should have MCN properties matching associated node properties for nodes in default MCPs` in two-node arbiter Openshift to test for master & arbiter MCP association.
- Skips `Should have MCN properties matching associated node properties for nodes in custom MCPs` test on two-node openshift.
- Adds more logs to scope impersonation tests to help with future debugging, if necessary.
**To test:**
See payload rehearsals with successful MCN tests:
- https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-origin-29732-nightly-4.19-e2e-metal-ovn-two-nod …
> OCPBUGS-55441: Fix MCN tests for two-node clusters & add more logs to scope tests

- test/extended/machine_config/helpers.go
- test/extended/machine_config/machine_config_node.go
This closes [OCPBUGS-55510](https://issues.redhat.com/browse/OCPBUGS-55510).
- Updates how nodes to test are selected in two-node Openshift environments for `Should properly block MCN updates from a MCD that is not the associated one`.
**How to verify:**
See the following payload rehearsals passing on the `Should properly block MCN updates from a MCD that is not the associated one` test.
> OCPBUGS-55510: Update node selection in MCN scope test for two-node Openshift

- test/extended/olm/olmv1-preflight.go
Don't assume the preflight error message starts with: "pre-authorization failed", but instead contains it.
> NO-ISSUE: OLMv1: Preflight: Relax checking of error message

- pkg/monitortestlibrary/allowedalerts/types.go
It's being worked up in [OCPBUGS-55635][1], and I don't want to fail [runs like this][2] in the meantime, because I expect the failure mode is a longstanding race that has been more frequent recently as a result of increased quay.io 502 rates.
I'm also dropping the `KubeJobFailed` allowance.  It had linked [bugzilla#2054426][3], which was moved to [OCPBUGS-9119][4] when we migrated from Bugzilla to Jira.  And then [OCPBUGS-9119][4] was closed without changes in 2023.  If we see more of this alert, we want to hear about it, so we can re-open.  And checking now, we aren't seeing it in anything more recent than 4.14:
```console
$ w3m -dump -cols 200 'https://search.dptools.openshift.org/?maxAge=48h&type=junit&search=KubeJobFailed+fired+for' | grep 'failures match' …
```
> OCPBUGS-55902: pkg/monitortestlibrary/allowedalerts: Ignore KubeJobFailingSRE for now

- pkg/monitortests/kubeapiserver/faultyloadbalancer/monitortest.go
When aggregation runs several tests it expects either pass or fail. If insufficient number of passes found the aggregation test would fail.
This commit would ensure test either passes or fails without skips, in order not to confuse aggregation
> NO-JIRA: faultyloadbalancer test: pass instead of skip

- test/extended/olm/olmv1.go
Polling with 30 secs timeout is causing thundering herd problem, causing the tests to timeout in resource constrained CI environments. This PR switches to using exponential backoffs with jitter.
> OCPBUGS-55712: (olmv1 tests) Use exponential backoffs for verifyAPIEndpoints

- test/extended/etcd/etcd_storage_path.go
This missing data was caught by techpreview-serial jobs.
> CNTRLPLANE-371: Update etcd test data for k8s 1.33 release (missing data)

- test/extended/olm/olmv1.go
Polling with 30 secs timeout is causing thundering herd problem, causing the tests to timeout in resource constrained CI environments. This PR switches to using exponential backoffs with jitter.
> OCPBUGS-55969: (olmv1 tests) Increase timeout for verifyAPIEndpoints

- test/extended/networking/network_segmentation.go
The static MTU can be incorrect in some clusters, instead rely on the fact that when the MTU is left unset OVN-Kubernetes will use a default equal to the clusterNetworkMTU:
https://github.com/ovn-kubernetes/ovn-kubernetes/blob/1df91ecad2dc2e283dd4106e2e5069aff9eb1eb5/go-controller/pkg/config/cni.go#L103
This approach is aligned with what is already being done for [C]UDNs.
> OCPBUGS-55994: Do not set the MTU when using NetworkAttachementDefinition

- pkg/clioptions/clusterdiscovery/provider.go
- test/extended/util/external/provider.go
Support platform type `External` as a valid provider in the test framework. The external platform initially act as None, and not require additional configuration at this moment. This change will add the minimum support to allow CI readiness for this platform.
The initial support has been added to 4.19, in order to skip permanent failures added in upstream kube on 4.18.
As the --provider flag is added in the CI step level, and that step does not support release check, it will be complex to implement a logic in CI instead of just global support of --provider across all versions the platform type external jobs are tested: 4.15+.
Initial backport PR has been created in https://github.com/openshift/origin/pull/29734 but we found a typo and decided to open here manually. …
> [release-4.17] OCPBUGS-55451: support provider type external

- test/extended/machine_config/helpers.go
- test/extended/machine_config/machine_config_node.go
- test/extended/machine_config/pinnedimages.go
- test/extended/testdata/bindata.go
- test/extended/testdata/machine_config/pinnedimage/masterInvalidPis.yaml
- test/extended/testdata/machine_config/pinnedimage/masterPis.yaml
Closes: OCPBUGS-55384
Closes: OCPBUGS-55968
- Reenable the following tests on SNO
- [MCN] `Should properly block MCN updates by impersonation of the MCD SA`
- [MCN] `Should properly update the MCN from the associated MCD`
- [PIS] `All Nodes in a standard Pool should have the PinnedImages PIS`
- Update the PIS tests running on SNO to use a PIS file targeting the master pool
- General updates to logs & function descriptions
**How to verify:**
SNO tech preview jobs should succeed for all PIS & MCN tests enabled for single-node topologies.
- Parallel suite: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-origin-29785-nightly-4.20-e2e-aws-ovn-single-node-techpreview/1922321162600189952
- Serial suite: …
> OCPBUGS-55384: OCPBUGS-55968: Fix PIS tests on SNO & Enable applicable MCN & PIS tests on SNO

- pkg/clioptions/suiteselection/feature_filter.go
Enable skipping of tests named `OCPFeatureGate` and `FeatureGate`
> NO-JIRA: support skipping [OCP]FeatureGate tests

- pkg/monitortests/kubeapiserver/auditloganalyzer/handle_operator_watch_count_tracking.go
Reverts openshift/origin#29719
Adds a check for ExternalTopology and skips
Makes the new test flake instead of fail
> Revert "Revert "TRT-2049: check for any watch requests""

- test/extended/router/gatewayapicontroller.go
- test/extended/util/client.go
enhancement for httproute test
1. use regular user to create httproute as well as pod/service
2. remove the step of cleaning up httproute
> OCPBUGS-55211: use regular user to create httproute

- test/extended/images/redirect.go
- test/extended/router/external_certificate.go
Some image registry and router e2e test cases failed in [job](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/64371/rehearse-64371-pull-ci-openshift-installer-main-e2e-azure-private/1917463259321995264), which were running in private cluster.
Private cluster needs to be accessed through a proxy, so set proxy for http transport in those cases.
> CORS-3989: set proxy for http transport in router and imageregistry cases

- pkg/clioptions/clusterdiscovery/provider.go
- test/extended/util/external/provider.go
Support platform type `External` as a valid provider in the test framework. The external platform initially act as None, and not require additional configuration at this moment. This change will add the minimum support to allow CI readiness for this platform.
The initial support has been added to 4.19, in order to skip permanent failures added in upstream kube on 4.18.
As the --provider flag is added in the CI step level, and that step does not support release check, it will be complex to implement a logic in CI instead of just global support of --provider across all versions the platform type external jobs are tested: 4.15+.
References:
- 4.19: https://github.com/openshift/origin/pull/29623
- 4.18: https://github.com/openshift/origin/pull/29666
- 4.17: …
> [release-4.16] OCPBUGS-55476: support provider type external

- test/extended/router/gatewayapicontroller.go
- test/extended/util/framework.go
This ensures GatewayAPIController tests are only run on clusters where OLM and related capabilities are enabled.
> OCPBUGS-55317: Skip GatewayAPIController tests on clusters without OLM capabilities

- pkg/test/extensions/binary.go
- pkg/test/extensions/types.go
Include source in the extension test result, so a person debugging can identify where the failed result came from. TRT had issues with a machine-api-operator test that was failed; they couldn't identify where it was coming from.
This also updates the types for ExtensionTestSpec to match the latest OTE version.
> NO-JIRA: Report back source for openshift-tests-extension

- test/extended/machine_config/helpers.go
- test/extended/machine_config/machine_config_node.go
The MCN API has a condition to signal a failure durint the update of a MachineConfigNode. The condition was already in the API but the MCO was not handling it.
With the MCO now handling the condition our testing now needs to check it is properly set/unset when needed.
>  MCO-1615: Mco node degraded mcn condition

- test/extended/networking/route_advertisements.go
Don't turn off EgressIP advertisement for the default network in the default RouteAdvertisements to avoid racing between tests.
> NO-JIRA: Fix egressIP advertisements tests flake

- test/extended/include.go
- test/extended/node/OWNERS
- test/extended/node/cgroups.go
**PR Description:** 
This PR adds a test to verify that modifying the CgroupMode field of the nodes.config object to v1 fails as expected since OpenShift 4.19 does not support cgroupv1.
The test follows the structure of existing  node tests and utilizes a debug pod to verify the failure scenario.
Tested locally , test case has executed successfully. 
PTAL @sairameshv
> OCPNODE-2849: Add testcase to verify removal of cgroupv1 in OCP 4.19

- test/extended/node/zstd_chunked.go
- test/extended/testdata/bindata.go
- test/extended/testdata/node/zstd-chunked/Dockerfile
- test/extended/testdata/node/zstd-chunked/Dockerfile.sample
- test/extended/testdata/node/zstd-chunked/build.sh
- test/extended/testdata/node/zstd-chunked/test-custom-build.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/annotate/rules.go
Fixes https://issues.redhat.com/browse/OCPNODE-3138
> OCPNODE-3138: Add zstd:chunked image test

- pkg/testsuites/standard_suites.go
Add an empty MCO suite, for testing purposes. Future tests will be moved over from serial and added via MCO OTE.
Alternative to https://github.com/openshift/origin/pull/29776
> MCO-1652: Add new MCO disruptive suite

- test/extended/baremetal/hosts.go
- test/extended/util/framework.go
updated baremetal test to account for the difference in two node fencing baremetal deployment
> OCPBUGS-56381: feat: update test to account for two node fencing

- test/extended/router/certgen/certgen.go
- test/extended/router/external_certificate.go
- test/extended/router/grpc-interop.go
- test/extended/router/http2.go
The function `MarshalPrivateKeyToDERFormat` in `test/extended/router/certgen` package was incorrectly named, as it returns a PEM-encoded string, not DER.
This commit renames it to `MarshalPrivateKeyToPEMString` for accuracy and updates variable names accordingly to reflect the correct encoding.
> NO-JIRA: router: Rename MarshalPrivateKeyToDERFormat to MarshalPrivateKeyToPEMString

- pkg/monitortestlibrary/platformidentification/types.go
- test/extended/router/external_certificate.go
- Added `kubevirt` as a recognised platform in `GetJobType()`.
- Replaced `isMetalJob()` with `isOnPremJob()` to include `metal`, `openstack`, and `kubevirt`.
- It ensures tests behave correctly for other on-prem platforms.
- https://issues.redhat.com//browse/OCPBUGS-55721
- https://issues.redhat.com//browse/OCPBUGS-55832
> OCPBUGS-55721, OCPBUGS-55832: Fix `RouteExternalCertificate` tests for few other on-prem jobs

- test/extended/networking/route_advertisements.go
- test/extended/networking/util.go
Due to a bug in the liveness probe of kubernetes-nmstate reported in OCPBUGS-56488, we need, as a workaround, to scale down the operator and disable the probe.
> NO-JIRA: OVNK BGP: workaround OCPBUGS-56488

- test/extended/machine_config/helpers.go
Updates test to account for https://github.com/openshift/machine-config-operator/pull/5084
> OCPBUGS-55830: Only update boot disks during GCP boot image updates tests

- pkg/clioptions/clusterdiscovery/provider.go
- test/extended/util/external/provider.go
Support platform type `External` as a valid provider in the test framework. The external platform initially act as None, and not require additional configuration at this moment. This change will add the minimum support to allow CI readiness for this platform.
The initial support has been added to 4.19, in order to skip permanent failures added in upstream kube on 4.18.
As the --provider flag is added in the CI step level, and that step does not support release check, it will be complex to implement a logic in CI instead of just global support of --provider across all versions the platform type external jobs are tested: 4.15+.
References:
- 4.19: https://github.com/openshift/origin/pull/29623
- 4.18: https://github.com/openshift/origin/pull/29666
- 4.17: …
> [release-4.15] OCPBUGS-55477: support provider type external

- pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/monitortest.go
I suspect this causes this instance of [alerts firing](https://sippy.dptools.openshift.org/sippy-ng/component_readiness/test_details?Architecture=amd64&Architecture=amd64&FeatureSet=default&FeatureSet=default&Installer=ipi&Installer=ipi&Network=ovn&Network=ovn&NetworkAccess=default&Platform=vsphere&Platform=vsphere&Scheduler=default&SecurityMode=default&Suite=unknown&Suite=unknown&Topology=ha&Topology=ha&Upgrade=minor&Upgrade=minor&baseEndTime=2025-02-25%2023%3A59%3A59&baseRelease=4.18&baseStartTime=2025-01-26%2000%3A00%3A00&capability=Other&columnGroupBy=Architecture%2CNetwork%2CPlatform%2CTopology&component=Monitoring&confidence=95&dbGroupBy=Platform%2CArchitecture%2CNetwork%2CTopology%2CFeatureSet%2CUpgrade%2CSuite%2CInstaller&environment=amd64%20default%20ipi%20ovn%20vsphere%20unknown% …
> OCPBUGS-56933: fix deployment rollout wait to wait for desired replicas

- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/test_suite.go
I accidentally broke retries for extension tests, because the pointer to a test binary was omitted.  The retry errors with:
```
error: no test exists with that name: [sig-cli] Kubectl Port forwarding Shutdown client connection while the remote stream is writing data to the port-forward connection port-forward should keep working after detect broken connection [Suite:openshift/conformance/parallel] [Suite:k8s]
```
However, because our end goal is that we don't retry at all, and we've existed in this state for months, I'm leaving retries off for externally sourced tests.
origin-sourced tests will continue to retry with the hope we ratchet up test quality to also stop retrying them.
> OCPBUGS-54412: Do not retry extension-sourced tests

- test/extended/machine_config/helpers.go
- test/extended/machine_config/machine_config_node.go
This reworks and generalizes the custom MCP cleanup used in the MCN tests.
**Payload testing:**
There have been an uptick in the number of failures on custom MCP cleanup in the `e2e-vsphere-ovn-techpreview-serial` test, so that is likely the best payload rehearsal test to use to assess the changes made in this PR.
**Test locally:**
To run the tests being fixed locally, run these against any 4.20 cluster with techpreview enabled.
```
./openshift-tests run-test "[sig-mco][OCPFeatureGate:MachineConfigNodes] [Serial]Should have MCN properties matching associated node properties for nodes in custom MCPs [apigroup:machineconfiguration.openshift.io] [Suite:openshift/conformance/serial]"
```
```
./openshift-tests run-test "[sig-mco][OCPFeatureGate:MachineConfigNodes] …
```
> OCPBUGS-56037: Stabilize custom MCP cleanup on MCN tests

- pkg/clioptions/clusterdiscovery/provider.go
MicroShift has no `--network` flag set when running OTE tests which is causing it to miss a skip that it should have.
There is some [special configuration](https://github.com/openshift/release/blob/master/ci-operator/step-registry/openshift/microshift/e2e/origin-conformance/openshift-microshift-e2e-origin-conformance-commands.sh#L46-L71) that sets it to `OVNKubernetes` for tests. I confirmed that this is a safe assumption to make in [this thread](https://redhat-internal.slack.com/archives/C03DP9PABNC/p1748958779190589). If, in the future, they start testing it with other network plugins we will have to be smarter about differentiating them.
> TRT-1854: set network for MicroShift to OVNKubernetes

- examples/quickstarts/rails-postgresql-persistent.json
- examples/quickstarts/rails-postgresql.json
- test/extended/builds/dockerfile.go
- test/extended/cli/setimage.go
- test/extended/image_ecosystem/s2i_images.go
- test/extended/testdata/bindata.go
- test/extended/testdata/builds/build-secrets/test-s2i-build.json
- test/extended/testdata/builds/statusfail-badcontextdirs2i.yaml
- test/extended/testdata/builds/statusfail-fetchimagecontentdocker.yaml
- test/extended/testdata/builds/statusfail-fetchsourcedocker.yaml
- test/extended/testdata/builds/statusfail-fetchsources2i.yaml
- test/extended/testdata/builds/statusfail-genericreason.yaml
- test/extended/testdata/builds/statusfail-oomkilled.yaml
- test/extended/testdata/builds/test-build-proxy.yaml
- test/extended/testdata/builds/test-build.yaml
- test/extended/testdata/builds/test-env-build.json
- test/extended/testdata/builds/test-imagesource-buildconfig.yaml
- test/extended/testdata/cluster/quickstarts/rails-postgresql.json
- test/extended/testdata/cmd/test/cmd/images.sh
- test/extended/testdata/cmd/test/cmd/testdata/image-streams/image-streams-centos7.json
- test/extended/testdata/cmd/test/cmd/testdata/new-app/imagestream-ref.yaml
- test/extended/testdata/image/test-image.json
- test/extended/testdata/long_names/fixture.json
- test/extended/testdata/run_policy/parallel-bc.yaml
- test/extended/testdata/run_policy/serial-bc.yaml
- test/extended/testdata/run_policy/serial-latest-only-bc.yaml
- test/extended/util/annotate/generated/zz_generated.annotations.go
This PR updates the Ruby version to 3.3:
**Note 1**: If you have committed, for example, test/extended/cli/setimage.go you should do the following:
In a terminal window, run the following in the main origin folder:
**make update-gofmt**
Run git status afterwards. You may see that the file will have been further updated by the make process. If so, git add/commit/push the changes  etc
**Note 2**: As zz_generated.annotations.go has been updated in github, you should test the /verify step locally as follows:
In a terminal window, in the main origin folder, run
**make verify**
If the verification process shows an error, you may find that the corrected file is ready for a further git add/commit/push.
(make verify will modify the file so git add/commit/push the file and then re-run make verify. …
> OCPBUGS-56512: updates ruby to version 3.3

- test/extended/machine_config/boot_image_update_aws.go
- test/extended/machine_config/boot_image_update_gcp.go
- test/extended/machine_config/machine_config_node.go
- test/extended/machine_config/pinnedimages.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
Many MCO tests require node disruption, so it was determined that these would best live as a separate suite.
Create the MCO suite and move existing MCO tests in origin to it. The next goal is to add On Cluster Layering tests to this as well, potentially via OTE.
> MCO-1652: Add MCO disruptive suite

- test/extended/networking/egress_firewall.go
- test/extended/testdata/bindata.go
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-test.yaml
- test/extended/testdata/egress-firewall/ovnk-egressfirewall-wildcard-test.yaml
- test/extended/testdata/egress-firewall/sdn-egressnetworkpolicy-test.yaml
This PR adds test case for checking EgressFirewall DNS names in caps.
This is a follow-up of https://github.com/openshift/origin/pull/29540.
The issue faced here is similar to https://issues.redhat.com/browse/OCPBUGS-52358 which is fixed by https://github.com/openshift/origin/pull/29618.
In this PR `amazon.com` is used which has a large TTL value (~700s).
> OCPBUGS-50701: Add test case for checking EgressFirewall DNS names in caps

- test/extended/clusterversion/OWNERS
- test/extended/clusterversion/clusterversion.go
- test/extended/include.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
A new featuregated field was introduced a while ago under clusterversion status - `desired.Architecture` which denotes the architecture of the release image being reconciled to. As we plan to promote the feature gate to default - this adds a basic test to check if the `desired.Architecture` is set based on the `release.openshift.io/architecture: multi` being present as part of the release metadata.
> MULTIARCH-5391: Add new featuregate test to check if desired.Architecture is set as intended

- test/extended/image_ecosystem/OWNERS
As the sustaining engineering team is owner of the samples operator component, we need to constantly update this group of files to fix the image ecosystem tests.
> OCPBUGS-57421: Add sustaining engineers to owners on image ecosystem

- pkg/monitortests/testframework/timelineserializer/rendering.go
We use a limited file for the most interesting intervals to lower strain
on browsers and memory.
Typically we do not show pending alerts there. However some alerts
related to etcd and CPU are high value to see as soon as they go
pending, because it helps us correlate when tests were failing.
Include a small set of pending alerts in the spyglass files we show by
default.
> TRT-2165: Include select pending alert intervals in spyglass

- test/extended/machine_config/helpers.go
- test/extended/machine_config/machine_config_node.go
This is a manual cherrypick of #29874 since the [automated cherrypick failed](https://github.com/openshift/origin/pull/29874#issuecomment-2956016263).
> [release-4.19] OCPBUGS-57217: Stabilize custom MCP cleanup on MCN tests

- pkg/test/ginkgo/junitapi/types.go
- tools/junitreport/pkg/api/types.go
`openshift-tests` is generating invalid unit xml like 
```
<testsuite name="openshift-tests" tests="14" skipped="0" failures="1" time="240">
<property name="TestVersion" value="4.19.0-202506020913.p0.g33fe530.assembly.stream.el9-33fe530"/>
```
> OCPBUGS-57397: properties should wrap around property

- test/extended/machine_config/helpers.go
This updates the boot image tests to use previously published boot images(instead of a fake value) so the MCO is able to update them when https://github.com/openshift/machine-config-operator/pull/5122 lands.
> OCPBUGS-57426: Boot image controller should correctly handle marketplace boot images

- pkg/clioptions/suiteselection/feature_filter.go
When a test is added, that contains `[OCPFeatureGate:`, we expect that the gate already exists in openshift/api and we therefore have an opinion about the gate as to whether it is enabled or disabled.
In all cases, we render every known gate as either enabled or disabled, so every gate has an opinion.
However, when we remove gates, we no longer have an opinion, and the current code disables the tests.
Generally, removing the gate means the feature was promoted to default in a previous release, and therefore the tests should continue to run.
In some cases, the gate may be removed without ever graduating. This is rare, and in these cases we would start running their tests with the feature removed, which would fail, and we would find out pretty quickly.
This seems like the lesser of two …
> NO-JIRA: We should always run tests where we have no opinion on their gate

- pkg/testsuites/standard_suites.go
- test/extended/networking/egressip_helpers.go
- test/extended/networking/internal_ports.go
- test/extended/networking/ipsec.go
- test/extended/networking/util.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
This PR updates IPsec E2E to test NAT-T implemented with PR: https://github.com/openshift/cluster-network-operator/pull/2573.
Note: This requires a new CI lane to test IPsec NAT-T "Always" encapsulation option.
This PR also adds an e2e tests to ensure ovnk managed pod traffic (EW traffic) is always working across nodes when `ovn-ipsec-host` daemonset goes for multiple reboots.
/assign @martinkennelly
> CORENET-5668: Update IPsec e2e test to validate NAT-T encapsulation option

- test/extended/two_node/arbiter_topology.go
we had too low of a timeout for pod ready wait time, increasing to 5 minutes
> OCPEDGE-1947: fix: resolve timeout problems during some arbiter tests

- go.mod
- pkg/cmd/openshift-tests/run/options.go
- pkg/testsuites/standard_suites.go
- test/extended/two_node/arbiter_topology.go
- test/extended/two_node/common.go
- test/extended/two_node/tnf_recovery.go
- test/extended/two_node/tnf_topology.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
Add initial topology tests
* Ensure correct number of ControlPlanes, and Arbiters
* Ensure correct number of static etcd pod containers
* Ensure correct number of podman etcd containers
Add initial behavior tests
* Ensure the cluster can handle a graceful node shutdown
Closes: [OCPEDGE-1481](https://issues.redhat.com//browse/OCPEDGE-1481), [OCPEDGE-1482](https://issues.redhat.com//browse/OCPEDGE-1482)
---
As a starting point for test integration within this new cluster
environment, this change enables only a minimal set of monitors. These
monitors are known to be reliable in general, but are currently
exhibiting unexpected behavior in this specific cluster.
This approach allows us to establish a foundational test base. Further
investigation into the reasons for their misbehavior in this …
> OCPEDGE-1481: Initial tests for Two Nodes OCP with Fencing (TNF) cluster

- pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/monitortest.go
We should return an error when we fail to determine the openshift-tests image
cc: @vrutkovs
> trt-2163: return error

- test/extended/images/dryrun.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Backport pr [29834](https://github.com/openshift/origin/pull/29834) to release-4.19 manually.
> OCPBUGS-57206: Backport pr 29834 to release-4.19

- test/extended/operators/certs.go
Ingress operator doesn't use ShortCertRotation featuregate, so the test should not fail when wildcard router cert is longer than 8 hours
> NO-JIRA: test/extended/operators: skip wildcard certificate

- pkg/clioptions/clusterdiscovery/csi.go
- pkg/clioptions/clusterdiscovery/provider.go
- pkg/test/extensions/binary.go
External storage tests aren't being found after moving to OTE, this makes InitCSITests a public function and calls it so those ginkgo tests are defined before we initialize OTE.
> OCPBUGS-59157: Ensure CSI tests are defined before OTE initialization

- test/extended/machine_config/pinnedimages.go
pinnedimages: Do not fail prematurely in waitForStatusX
> MCO-1797: Fix transient errors while checking status of PIS

- OWNERS_ALIASES
- @PratikMahajan replaced Lala as a team lead
- Both @DavidHurta and @hongkailiu are more than qualified to review and approve OTA-related tests
> NO-JIRA: OWNERS_ALIASES: Update OTA members / team lead

- go.mod
- test/extended/networking/commatrix.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
Reverts openshift/origin#29782; tracked by [TRT-2202](https://issues.redhat.com/browse/TRT-2202)  
This test has exposed a chance of breaking payload when multiple endpointslice PR are involved. 
In the latest case, this payload failed: https://amd64.ocp.releases.ci.openshift.org/releasestream/4.20.0-0.nightly/release/4.20.0-0.nightly-2025-07-15-214716
Failed job:
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.20-e2e-aws-ovn-serial/1945415340292837376
There is a slack discussion on possible solutions: …
> Revert "CNF-17748: Add a comparing between static entry test"

- pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/monitortest.go
The test should give more time for deployment to roll out. On some openstack tests it takes 7 minutes now
> OCPBUGS-58354: disruptioninclusterapiserver: bump timeout to 10 mins

- test/extended/machine_config/helpers.go
- test/extended/machine_config/machine_config_node.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
_OCPBUGS-59203_
This updates the MCN happy scope path test, `Should properly update the MCN from the associated MCD`, to be a part of the serial test suite instead of the parallel test suite. This update is necessary since the test makes changes to MCN objects that can cause interference with other MCN tests when run in parallel.
_OCPBUGS-57524_
This does two things to improve the stability of the slow, disruptive MCN tests
- Increase the node readiness timeout to reduce failures in the `Should properly create and remove MCN on node creation and deletion` due to the newly provisioned node not becoming ready within two minutes.
- Add debugging logs to help with troubleshooting in the occasionally flaky `Should properly report MCN conditions on node degrade` test.
**Test …
> OCPBUGS-59203: OCPBUGS-57524: Improve MCN test stability

- test/extended/cli/idle.go
It looks like oc idle tests are very flaky ([ref](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.20/runs?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22flaked_test_names%22%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22%5Bsig-cli%5D%20oc%20idle%20%5Bapigroup%3Aapps.openshift.io%5D%5Bapigroup%3Aroute.openshift.io%5D%5Bapigroup%3Aproject.openshift.io%5D%5Bapigroup%3Aimage.openshift.io%5D%20by%20checking%20previous%20scale%20%5BSuite%3Aopenshift%2Fconformance%2Fparallel%5D%22%7D%2C%7B%22columnField%22%3A%22variants%22%2C%22not%22%3Atrue%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22never-stable%22%7D%2C%7B%22columnField%22%3A%22variants%22%2C%22not%22%3Atrue%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22aggregated%22%7D%5D%2C%22linkOperator%22%3 …
> NO-JIRA: oc idle: Increase timeout of endpointslice status check

- test/extended/cli/adm_upgrade/OWNERS
- test/extended/cli/adm_upgrade/status.go
- test/extended/include.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/client.go
- zz_generated.manifests/test-reporting.yaml
- Add a new subdirectory to hold OTA-owned `oc adm upgrade` subcommand tests
- Add a way to pass env vars to `oc` CLI to enable gated subcommand testing
- When not updating, the command emits a simple message stating just that
This has some overlap with https://github.com/openshift/origin/pull/29831 (code placement, ownership, client support for enabling environment variables)
> OTA-1580: Add basic test for `oc adm upgrade status` CLI

- e2echart/non-spyglass-e2e-chart-template.html
- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
- pkg/monitortests/testframework/watchevents/event.go
- test/extended/testdata/bindata.go
Followup for https://github.com/openshift/origin/pull/28639:
* Add "Certificate Rotation" section to e2e-chart-everything.html
* Show cert rotation events from certrotationcontroller, csrapprover and ingress controller
> API-1802: chart template: show cert rotation events

- pkg/defaultmonitortests/types.go
- pkg/monitortests/kubelet/containerfailures/container_failures.go
- pkg/monitortests/kubelet/containerfailures/exclusions.go
- pkg/monitortests/kubelet/containerfailures/exclusions_test.go
- pkg/monitortests/node/legacynodemonitortests/kubelet.go
- pkg/monitortests/node/legacynodemonitortests/monitortest.go
Move the legacy container failures monitor tests to a dedicated MonitorTest implementation and removed the test from the default suites for disruptive test suites.
> OCPBUGS-59750: Move the legacy container failures

- test/extended/node/image_volume.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
Adding an imagevolume e2e test by carrying over https://github.com/openshift/origin/pull/29987
Credits go to @bitoku
> OCPNODE-3004: Add ImageVolume e2e tests

- pkg/testsuites/standard_suites.go
- test/extended/authentication/keycloak_client.go
- test/extended/authentication/keycloak_helpers.go
- test/extended/authentication/oidc.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/client.go
- vendor/github.com/openshift/library-go/pkg/operator/condition/condition.go
- vendor/modules.txt
- zz_generated.manifests/test-reporting.yaml
This PR adds the tests necessary to promote the ExternalOIDC and ExternalOIDCWithUIDAndExtraClaimMappings feature-gates on OpenShift.
It adds a new test suite specific to tests that test the external OIDC provider authentication mode.
Some tests are intentionally marked as skipped as the functionality does not yet exist to test, but I wanted to still provide the skeleton for these tests so that we can easily make some updates when that functionality _is_ implemented.
> CNTRLPLANE-945: Add tests for ExternalOIDC and ExternalOIDCWithUIDAndExtraClaimMappings features

- test/extended/node/image_volume.go
Following up #30015
Fix the flaky `Waiting for pod to be ImagePullBackOff` test.
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/30024/pull-ci-openshift-origin-main-e2e-gcp-ovn-techpreview/1950018871981248512
> OCPNODE-3004: Accept ErrImagePull for non-existent image volume test.

- pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/monitortest.go
- pkg/monitortests/network/disruptionpodnetwork/monitortest.go
- pkg/monitortests/network/disruptionpodnetwork/utils.go
- pkg/test/extensions/binary.go
- pkg/test/extensions/provider.go
- pkg/test/extensions/util.go
- test/extended/util/payload/payload.go
Hitting issues running `oc adm release info` on upi and disconnected clusters.  Looking to reuse OTE based ExtractImageFromReleasePayload
Solution AI assisted by Cursor, Real I by @stbenjam
> TRT-2163: incluster disruption images

- e2echart/non-spyglass-e2e-chart-template.html
- pkg/disruption/backend/disruption/handler.go
- pkg/monitor/monitorapi/types.go
- test/extended/testdata/bindata.go
Reverts openshift/origin#29710
This change is breaking spyglass view for many jobs. We can see this in the presubmit jobs in the original PR. Here is an example:
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/29710/pull-ci-openshift-origin-main-e2e-gcp-ovn-techpreview-serial-2of2/1947614945747144704
Debugging a little further, you can see this error when the generated html is shown:
`TypeError: eventInterval.locator.keys.has is not a function
`
It hits this line: https://github.com/openshift/origin/blob/867bce8197b814cf425fd60e0f6400dd7b743556/e2echart/e2e-chart-template.html#L164
> NO-JIRA: Revert "OCPBUGS-55238: spyglass: hide disruption events for localhost"

- pkg/monitortests/kubeapiserver/disruptioninclusterapiserver/monitortest.go
- test/extended/util/managed_services.go
- test/extended/util/managed_services_test.go
- test/extended/util/pods.go
- test/extended/util/pods_test.go
- Add detection logic for ARO HCP hypershift deployments
- Skip metrics collection when MANAGED_SERVICE=ARO-HCP is detected
- Add helper functions hasEnvVar() and isAROHCP() for environment detection
> OCPBUGS-59218: feat(azure): skip metrics collection for ARO HCP hypershift

- test/extended/networking/route_advertisements.go
In https://github.com/ovn-kubernetes/ovn-kubernetes/pull/5140 we are removing receiving the remote node pod subnet routes for advertised networks.
In the e2e setup, we seem to be checking for these routes which won't be there.
See sample failure:
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2651/pull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi-ovn-dualstack-bgp-local-gw/1950264479669293056 https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_ovn-kubernetes/2693/pull-ci-openshift-ovn-kubernetes-master-e2e-metal-ipi-ovn-dualstack-bgp-local-gw/1948808636629258240
We need this change before we bring in 5140 downstream.
> OCPBUGS-56506: Don't check for remote node subnet BGP routes

- test/extended/olm/olmv1.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
The test was migrated in the PR: https://github.com/openshift/operator-framework-operator-controller/pull/415
> OPRUN-3964: [olmv1] - Remove test [sig-olmv1][OCPFeatureGate:NewOLM] OLMv1 CRDs should be installed migrated to operator-controller repository/OTE

- test/extended/networking/route_advertisements.go
This PR enables the test for LGW L2 which was previously disabled.
> CORENET-6203: Enable test for LGW L2

- test/extended/operators/operators.go
This is only set when featureSets are configured
> OCPBUGS-60067, OCPBUGS-60066: Don't check for isNoUpgrade

- go.mod
- test/extended/cli/adm_upgrade/recommend.go
- test/extended/cli/adm_upgrade/regexp.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
I hear that folks want something similar to [the OpenShift API conditions][1]:
> 1. Tests must contain either `[OCPFeatureGate:<FeatureGateName>]` or the standard upstream `[FeatureGate:<FeatureGateName>]`.
> 2. There must be at least five tests for each FeatureGate.
> 3. Every test must be run on every TechPreview platform we have jobs for.  (Ask for an exception if your feature doesn't support a variant.)
> ...
before promoting command-line features to GA.  Or maybe that is a condition before shifting them from alpha to beta, like [this upstream change][2] moving a commend-line gate from `IsEnabled` to `!IsDisabled`?  Anyhow, I like testing, and while in the origin suite we don't really know what, if anything, we'll find in the ClusterVersion status properties the `recommend` command is …
> OTA-1559: test/extended/cli/admin: Add 'oc adm upgrade recommend' smoke test

- test/extended/node/image_volume.go
Fixing this flakiness.
https://sippy-auth.dptools.openshift.org/sippy-ng/tests/4.20/analysis?test=%5Bsig-node%5D%20%5BFeatureGate%3AImageVolume%5D%20ImageVolume%20when%20subPath%20is%20used%20should%20fail%20to%20mount%20image%20volume%20with%20invalid%20subPath%20%5BSuite%3Aopenshift%2Fconformance%2Fparallel%5D&filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22%5Bsig-node%5D%20%5BFeatureGate%3AImageVolume%5D%20ImageVolume%20when%20subPath%20is%20used%20should%20fail%20to%20mount%20image%20volume%20with%20invalid%20subPath%20%5BSuite%3Aopenshift%2Fconformance%2Fparallel%5D%22%7D%5D%2C%22linkOperator%22%3A%22and%22%7D
> OCPNODE-3004: ImageVolume: Increase timeout duration

- test/e2e/upgrade/upgrade.go
Based on Damien's analysis the test is failing because there wasn't enough time between when the upgrade completed and the DaemonSet pod to become ready. In the cases he reviewed there were single digit seconds between when the test checked and when pods became ready.
In https://github.com/openshift/origin/pull/29960 Damien added 30s sleep but Devan suggested a polling loop instead to limit downtime.
> OCPBUGS-57032: Add wait.Poll retry logic to checkUpgradeability with 30s timeout

- pkg/cmd/openshift-tests/monitor/run/run_monitor_command.go
- pkg/defaultmonitortests/types.go
- pkg/monitortests/cli/adm_upgrade/OWNERS
- pkg/monitortests/cli/adm_upgrade/status/monitortest.go
Pick up the WIP from https://github.com/openshift/origin/pull/29977
> OTA-1580: Monitortest framework test for oc adm upgrade status

- test/extended/two_node/arbiter_topology.go
- test/extended/two_node/common.go
- test/extended/two_node/tna_recovery.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
add recovery tests for TNA
update common.go
arbiter e2e [run](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/30022/pull-ci-openshift-origin-main-e2e-metal-ovn-two-node-arbiter/1950567539113201664)
> OCPEDGE-1969: add recovery tests for TNA

- test/extended/olm/olmv1.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
Blocked by: https://github.com/openshift/operator-framework-operator-controller/pull/418
Closes: https://github.com/openshift/origin/pull/30063
> OPRUN-4055: [OLMv1] Remove olmv1.go tests since those has been executed by OTE

- test/extended/util/framework.go
Fixing this flakiness. https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.20-e2e-gcp-ovn-usernamespace/1952200850893967360 
This is used here.
https://github.com/openshift/origin/blob/4bdcbed43bb02be8939be3a3ad8ca15857368812/test/extended/node/nested_container.go#L30-L37
>  OCPNODE-3520: UserNamespaces: Increase build timeout duration

- test/extended/images/extract.go
3 minutes is not enough when running on compact metal clusters
> OCPBUGS-58037: increase timeout of image extract test

- pkg/monitortestlibrary/pathologicaleventlibrary/duplicated_event_patterns.go
In a Two Node Fencing cluster is it acceptable to have less than two etcd endpoints.
> NO-JIRA: [TNF] add Two Node Fencing exception to accept less than two etcd endpoints

- pkg/monitortests/cli/adm_upgrade/status/controlplane.go
- pkg/monitortests/cli/adm_upgrade/status/controlplane_test.go
- pkg/monitortests/cli/adm_upgrade/status/health.go
- pkg/monitortests/cli/adm_upgrade/status/health_test.go
- pkg/monitortests/cli/adm_upgrade/status/monitortest.go
- pkg/monitortests/cli/adm_upgrade/status/monitortest_test.go
- pkg/monitortests/cli/adm_upgrade/status/outputmodel.go
- pkg/monitortests/cli/adm_upgrade/status/outputmodel_test.go
- pkg/monitortests/cli/adm_upgrade/status/updatelifecycle.go
- pkg/monitortests/cli/adm_upgrade/status/updatelifecycle_test.go
- pkg/monitortests/cli/adm_upgrade/status/workers.go
- pkg/monitortests/cli/adm_upgrade/status/workers_test.go
This is a cleaned up content of https://github.com/openshift/origin/pull/30100 which it supersedes.
The PR adds a programmatic model of `oc adm upgrade status` outputs, based on
something that vaguely resembles a recursive descent parser. The model itself
is somewhat similar to the page object pattern used in web application testing:
instead of tests checking their stuff over the raw output, they interact over
a programmatic model of the output.
Every successfully captured output shapshot is parsed into a programmatic model,
which itself serves as a test (any valid output should be possible to model).
These models are then checked by four new tests:
- Test for control plane section content
- Test for worker section content
- Test for health section content
- Test for consistent update …
> OTA-1580: Further tests for `oc adm upgrade status`

- pkg/monitortests/cli/adm_upgrade/status/monitortest.go
- **Refactor the noFailures case**
- **upgrade status CLI monitortest: use slice instead of map**
- **upgrade status CLI monitortest: snapshot --details=all**
> WIP: OTA-1580: [1/x] Tweaks

- test/e2e/upgrade/monitor.go
- test/extended/two_node/tnf_recovery.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/nodes.go
- zz_generated.manifests/test-reporting.yaml
This change extends the etcd recovery tests in the two_node suite with a new ungraceful shutdown test
Key changes include:
- refactor `test/e2e/upgrade/monitor.go` to allow reusing the utility to trigger graceful/ungraceful node reboots.
- New TNF Ungraceful node shutdown test.
Other minor changes in TNF E2E tests:
- Refactor the Etcd validation logic into a dedicated function, to improve readability and reusability.
- Improve logging and error messages to provide more context during test failures.
> OCPEDGE-1755: Add TNF E2E tests for ungraceful node shutdown 

- pkg/monitortestframework/panic.go
This will not fix the referenced bug, but it will hopefully let us see what needs to be fixed.
> OCPBUGS-60530: Log full stack traces for panics in monitortest cleanup

- pkg/test/extensions/binary.go
- pkg/testsuites/standard_suites.go
This is a manual backport of the content applied by https://github.com/openshift/origin/pull/29922.
This backport needs to be manual mainly because the support for external declared tests-suites was not backported to 4.19.
> OCPBUGS-60429: Load our MCO's OTE binary

- test/extended/two_node/arbiter_topology.go
recent MCO changes removed two pods from the kni-infra namespace on the arbiter node, updating test to reflect change
> NO-JIRA: fix: update arbiter test

- pkg/test/ginkgo/cmd_runsuite.go
Reverts openshift/origin#29997
Investigation into failures for jobs `periodic-ci-openshift-release-master-ci-4.20-upgrade-from-stable-4.19-e2e-aws-ovn-upgrade` and `periodic-ci-openshift-release-master-ci-4.20-e2e-azure-ovn-upgrade` to see if there is an increase in failures like [Metrics should grab all metrics from kubelet](https://sippy.dptools.openshift.org/sippy-ng/component_readiness/test_details?Architecture=amd64&FeatureSet=default&Installer=ipi&Network=ovn&Platform=aws&Suite=unknown&Topology=ha&Upgrade=minor&baseEndTime=2025-06-17%2023%3A59%3A59&baseRelease=4.19&baseStartTime=2025-05-18%2000%3A00%3A00&capability=Other&columnGroupBy=Architecture%2CNetwork%2CPlatform%2CTopology&component=Monitoring&confidence=95&dbGroupBy=Platform%2CArchitecture%2CNetwork%2CTopology%2CFeatureSet%2CU …
> Revert "TRT-2197: use fixed seed for test ordering"

- test/extended/cli/adm_upgrade/status.go
The `oc adm upgrade status` has no support for HyperShift where update procedure is different especially around nodes:
- assumes MCP existence
- no NodePool knowledge
- no knowledge of separate management / hosted cluster
> OTA-1581: Skip `UpgradeStatus` test on HyperShift

- test/extended/networking/egress_firewall.go
This PR updates curl timeout in egress firewall tests from 3 seconds to 5 seconds for improved reliability.
> OCPBUGS-60550: Increase curl timeout from 3s to 5s for egress firewall DNS rule test

- pkg/monitortests/etcd/legacyetcdmonitortests/etcd.go
- pkg/monitortests/etcd/legacyetcdmonitortests/monitortest.go
This has caused nothing but problems as it pretty much logs constantly on some platforms, and has never really caught a bug that we can recall. Trying to tune it is leading to such absurd limits that it's clearly not worth monitoring for failures. Removing with staff eng approval.
> OCPBUGS-52968: Drop the etcd should not log excessive took too long messages test

- test/extended/node/image_volume.go
This must be merged after https://github.com/openshift/api/pull/2453
It won't work in microshift so disabling it.
https://redhat-internal.slack.com/archives/C03DP9PABNC/p1755789772265079?thread_ts=1755768360.420069&cid=C03DP9PABNC
> OCPNODE-3004: Run ImageVolume tests in all clusters.

- test/extended/networking/endpoint_admission.go
Check if namespace exists before creation to prevent unnecessary webhook calls while maintaining same test behavior.
Fixes: [SREP-1622](https://issues.redhat.com//browse/SREP-1622)
> SREP-1622: Fix endpoint admission test namespace creation for ROSA

- test/e2e/upgrade/upgrade.go
This accounts for the fact that it occasionally takes 1-2s for workloads to become ready after the nodes are marked ready at the end of an upgrade.
> OCPBUGS-60244: Wait 30s after the upgrade is complete to validate workloads

- pkg/defaultmonitortests/types.go
- pkg/monitortests/kubeapiserver/auditloganalyzer/monitortest.go
When disruptive tests are run, it is possible that the Kubernetes API server undergoes revision rollouts which may cause an expected increase in watch requests being issued by platform operators.
We encountered this in various jobs for the ExternalOIDC feature we are creating tests for that is known to be a highly disruptive set of tests that triggers many revision rollouts (>20) due to the nature of how the feature is configured and the existing limitations of the `openshift-tests` binary not being able to share setup and teardown logic between individual test cases.
Example jobs:
- https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-cluster-authentication-operator-release-4.20-periodics-e2e-gcp-external-oidc-configure-techpreview/1958846390285111296
- …
> CNTRLPLANE-945: monitor: auditloganalyzer: skip watch channels processing when cluster stability is explicitly marked as `Disruptive`

- pkg/monitortests/cli/adm_upgrade/status/monitortest.go
- test/extended/cli/adm_upgrade/status.go
https://github.com/openshift/oc/pull/2063 promoted `oc adm upgrade status` and removed the conditional check of the `OC_ENABLE_CMD_UPGRADE_STATUS` envvar, so the tests should no longer set it either.
> NO-JIRA: Stop setting feature gate conditional

- test/extended/authentication/keycloak_client.go
We encountered an issue in https://github.com/openshift/release/pull/68209 where requests to configure the Keycloak instance deployed for the OIDC tests failed to resolve the hostname of route for the Keycloak instance.
This appeared to be because all requests to routes on a baremetal cluster must go through a proxy. This PR updates the HTTP client we use for interacting with Keycloak instances to respect any proxies configured from the typical `HTTP_PROXY` `HTTPS_PROXY` and `NO_PROXY` environment variables.
> CNTRLPLANE-945: oidc/keycloak: make keycloak client use environment proxy for HTTP requests

- pkg/test/ginkgo/cmd_runsuite.go
- pkg/testsuites/standard_suites.go
- test/extended/extension/extension.go
- test/extended/include.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
* Adds support for non-terminal test failures (lifecycle = informing is the only currrent one)
* Adds a test suite for OTE (will be used in jobs I'll create later)
```
$ ./openshift-tests run openshift/ote --junit-dir /tmp/junit
[...]
Informing test failures that don't prevent the overall suite from passing:
* [sig-ci] [OTE] OpenShift Tests Extension should support tests with an informing lifecycle
Writing JUnit report to /tmp/junit/junit_e2e__20250827-142903.xml
Writing extension test results JSON to /tmp/junit/extension_test_result_e2e__20250827-142903.json
1 informing failures, 1 pass, 0 skip (11s): suite passes despite failures
```
> TRT-2268: Add support for OTE test lifecycles

- test/extended/authorization/authorization.go
When authorization test runs on HyperShift, there is an additional service account named system:hosted-cluster-config needs to be included.
> OCPBUGS-57496: Account for system:hosted-cluster-config service account in HyperShift

- pkg/test/extensions/binary.go
Cluster-openshift-apiserver-operator side setup: https://github.com/openshift/cluster-openshift-apiserver-operator/pull/623
openshift-apiserver side setup: https://github.com/openshift/openshift-apiserver/pull/536
oauth-apiserver side setup: https://github.com/openshift/oauth-apiserver/pull/138
service-ca-operator side setup: https://github.com/openshift/service-ca-operator/pull/270
cluster-kube-controller-manager-operator side setup: https://github.com/openshift/cluster-kube-controller-manager-operator/pull/859
>  CNTRLPLANE-1257: Enable OTE for apiserver Operators and servers

- test/extended/authentication/keycloak_helpers.go
- test/extended/authentication/oidc.go
We noticed in a few job runs that our tests were failing due to Keycloak Deployment availability checks timing out.
This PR:
- Updates our logging behavior to tie into the Ginkgo `logr.Logger` implementation so we can avoid using standard library print statements for additional debugging logic
- Adds a startup probe for the Keycloak Deployment. It looks like our availability issues stemmed from the liveness/readiness probes hitting connection refused errors because Keycloak hadn't successfully started yet. This lead to Kubelet restarting the Keycloak Pod indefinitely. Chose a ~200 second startup window for Keycloak before it gets restarted and this seems to have resolved our issues.
> CNTRLPLANE-945: improve logging, add startup probe to Keycloak Deployment

- images/tests/Dockerfile.rhel
It was added and to be used by realtime tests however that's never happened and this package pulls in 80+ dependencies and ~350MiB
> OCPBUGS-61229: images/tests: Remove rteval

- test/extended/networking/livemigration.go
/hold until [OCPBUGS-42609](https://issues.redhat.com/browse/OCPBUGS-42609) is available downstream ...
> CORENET-5329: revert primary udn test workaround from virt tests

- test/extended/cli/adm_upgrade/recommend.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
These will probably not pass without more work, but checking to see how far away we are.
> OCPBUGS-61063: test/extended/cli/adm_upgrade/recommend: Enable precheck and accept

- test/extended/cli/adm_upgrade/recommend.go
Avoid failing on rare flakes [like][1]:
: [Serial][sig-cli] oc adm upgrade recommend When the update service has conditional recommendations runs successfully with conditional recommendations to the --version target [Suite:openshift/conformance/serial]	22s
...
Could not evaluate exposure to update risk TestRiskA (invalid PromQL result length must be one, but is 0)
where there was presumably some kind of hiccup in scraping the cluster-version operator.  Instead of expecting to find `cluster_version` at the single point in time "now", accept it if we find that metric anywhere in the past hour.
[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.20-e2e-aws-ovn-techpreview-serial/1959321955551154176
> OTA-1559: test/extended/cli/adm_upgrade/recommend: TestRiskA PromQL use max_over_time

- test/extended/cli/observe.go
`oc observe` test serves an HTTP endpoint with a [static port](https://github.com/openshift/oc/blob/6edd9e45c39d56010dd8983b71782269b39aa217/pkg/cli/observe/observe.go#L200) (i.e. `:11251`). That means, running `oc observe` tests in parallel sometimes cause `listen tcp :11251: bind: address already in use` error. Because one of the test reserves this port number and the other one can not. [1][2]
In order to deflake this test, this PR uses an explicit port number in one of the tests to prevent the race condition. Thanks to that, this test will also exercise the validity of `--listen-addr` flag in observe command.
[1] https://search.dptools.openshift.org/?search=oc+observe+works+as+expected+with+cluster+operators&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&m …
> NO-JIRA: Deflake oc observe test by using explicit port number

- test/extended/cli/timeout.go
oc --request-timeout test expects the success in some execution after passing `--request-timeout` explicitly. After current value is 1 second which is very short for some environments and this causes flakiness. 
This PR increases to 2 seconds to deflake this test.
Example failure: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.20-e2e-vsphere-static-ovn/1966224899647213568
> NO-JIRA: Increase request-timeout to deflake test

- pkg/testsuites/standard_suites.go
- test/extended/two_node/tnf_topology.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- zz_generated.manifests/test-reporting.yaml
updated tests to always target two node topology instead of being a suite tests
small refactor and testing name change
added test to check platform type is set to baremetal or none
added test to check baremetal hosts are set to detached
> OCPEDGE-2090: Add validation tests for tnf topology effects

- pkg/alerts/allowed_conformance.go
Adds an allowed alert for `InstallPlanStepAppliedWithWarnings` to unblock kubernetes 1.34 rebase efforts. The servicemeshoperator VirtualServices CRD is generating warnings from the api server because 1.34 now gives warnings for unknown string formats. Without this exception the rebase efforts may be blocked until the CRD can be fixed. This allowance will be removed once the issue has been resolved.
I don't yet know if the upgrade tests will need this as well, but I'm limiting the scope here for the time being.
> OCPBUGS-61855: CRD Apply Alert Allowance

- test/extended/router/gatewayapicontroller.go
- test/extended/util/framework.go
This is a manual cherry pick of https://github.com/openshift/origin/pull/29784.
> [release-4.19] OCPBUGS-56213: Skip GatewayAPIController tests on clusters without OLM capabilities

- pkg/test/ginkgo/status.go
- pkg/test/ginkgo/test_runner.go
Add nil checks to recordTestResultInMonitor, recordTestResultInLog, and TestEnded functions to prevent segmentation faults when testRunResult is nil during error conditions like network connectivity issues.
This is to prevent test failures like https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-hypershift-release-4.21-periodics-e2e-azure-aks-ovn-conformance/1967830988788600832
> OCPBUGS-61398: fix(test): prevent nil pointer dereference in ginkgo test runner

- test/extended/two_node/tnf_recovery.go
- test/extended/util/annotate/generated/zz_generated.annotations.go
- test/extended/util/nodes.go
- zz_generated.manifests/test-reporting.yaml
This commit introduces a new e2e test for TNF to validate etcd recovery after a network disruption in a two-node cluster.
The test simulates a network partition by using iptables to block traffic between the two nodes for a short, configurable, duration.
It then verifies that the cluster correctly handles the split-brain scenario, with one node becoming the leader and the other rejoining as a learner before being promoted back to a voting member.
Additionally, the node disruption pod creation logic has been refactored from `triggerNodeReboot` to a more generic `createNodeDisruptionPod` to accommodate different types of disruptions, including network partitions and reboots.
> OCPEDGE-1483: Add TNF E2E tests for network failure

- pkg/test/ginkgo/cmd_runsuite.go
- pkg/test/ginkgo/test_suite.go
- pkg/testsuites/standard_suites.go
Jobs like `e2e-agent-ha-dualstack-conformance` only install 2 worker nodes.  Running the default 30 tests in parallel leads to overloaded CPU.  Expectations for the 30 parallel jobs is a standard 6 node cluster with 3 workers.  This will lower the default parallelism when fewer workers are detected.
> trt-2246: lower parallelism based on worker nodes

- pkg/monitortestlibrary/allowedalerts/all.go
The alert ClusterOperatorDegraded is fatal because it indicates
- cluster version operator is working (reporting Avaiable=True) but sad (not reporting Failing=False), or
- some cluster operator is sad (not reporting Degraded=False)
We do not want any of those to happen in the CI upgrade tests.
When a test fails up to the alert, we can check the ClusterVersion manifest usually collected as an artifact of the test to figure out the reason that triggered the alert.
If it was caused by some CO, we should file a bug for the component that CO belongs to.
Otherwise, it is a bug for CVO.
[1]. https://github.com/openshift/cluster-version-operator/blob/d81848ae818b277bdaffa5375ad6366111c4143c/install/0000_90_cluster-version-operator_02_servicemonitor.yaml#L106
> OTA-1626: Fail CI if alert/ClusterOperatorDegraded is fired

- pkg/test/ginkgo/status.go
- pkg/test/ginkgo/test_runner.go
This PR fixes(ginkgo): avoid nil deref and harden env var setup
- Initialize testRunResultHandle with a default inner struct to make defers safe
- Add nil checks for testRunResult and its inner value in status/log/monitor paths
- Make updateEnvVars robust: handle discovery/marshal errors and always set TEST_PROVIDER with a sane default
Prevents panics during early/failed test runs and improves resilience when cluster config is unavailable.
Refs: OCPBUGS-61398
Example test failure - https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-hypershift-release-4.21-periodics-e2e-azure-aks-ovn-conformance/1970035697670688768
> OCPBUGS-61398: fix(ginkgo): avoid nil deref and harden env var setup

- test/extended/prometheus/prometheus.go
see from [OCPBUGS-62227](https://issues.redhat.com/browse/OCPBUGS-62227), case "Alerts shouldn't exceed the series limit of total series sent via telemetry from each cluster" failed on e2e-aws-ovn-techpreview job
this PR bumped the limit to 1000 to tolerate more series added to telemetry in the future
> OCPBUGS-62227: bump telemetry series limit to 1000

- test/extended/machine_config/helpers.go
helpers: vSphere 2x upload is time consuming hence bump timeout
> MCO-1875: Bump timeout for vSphereBootimageUpdate tests

- pkg/monitortestlibrary/platformidentification/operator_mapping.go
Spot the case by https://github.com/openshift/origin/pull/30296#issuecomment-3338621585
```
$ oc --kubeconfig /tmp/ota-stage.c get co kube-apiserver olm
NAME             VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
kube-apiserver   4.18.15   True        False         False      4y13d
olm              4.18.15   True        False         False      121d
```
Looking at the age, `co/olm` might become a cluster operator after the set was last updated.
The name of `bugzillaComponent` is taken from https://github.com/openshift/origin/blob/1c9a26121846f19099909bbdc445442ce65b06cb/pkg/monitortestlibrary/platformidentification/operator_mapping.go#L154
> NO-JIRA: Add olm into the known operator set

- pkg/monitortestlibrary/platformidentification/operator_mapping.go
Reverts openshift/origin#30308
This is causing payload failures in upgrade minor GCP jobs. [Example](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/aggregated-gcp-ovn-upgrade-4.21-micro-release-openshift-release-analysis-aggregator/1972561250676117504)
Verify correct functionality during the un-revert with:
```
/payload-aggregate periodic-ci-openshift-release-master-ci-4.21-e2e-gcp-ovn-upgrade 10
```
> Revert "NO-JIRA: Add olm into the known operator set"

- test/extended/machine_config/boot_image_update_aws.go
- test/extended/machine_config/boot_image_update_gcp.go
- test/extended/machine_config/machine_config_node.go
- test/extended/machine_config/pinnedimages.go
**Work Included:**
- Updates each of team MCO's regression tests so that they only run in one test suite each. The correct suite for each test was determined and documented in MCO-1860.
- Removes the MCN feature gate from the PIS tests since the features are now both GAed and there is no need to ensure the MCN feature is enabled for these tests.
**To Verify:**
The following test suites should include each of the tests listed below it and each test should be present in exactly one test suite.
_`Parallel` [periodic-ci-openshift-release-master-ci-4.21-e2e-gcp-ovn-techpreview](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-origin-30309-ci-4.21-e2e-gcp-ovn-techpreview/1972702743755755520)_
_`Serial` [periodic-ci-openshift-release-master-ci-4.21-e2e-gcp-ovn-techprevie …
> MCO-1865: Update MCO tests to be in only one test suite each

- pkg/monitortests/cli/adm_upgrade/status/monitortest.go
- pkg/monitortests/cli/adm_upgrade/status/updatelifecycle.go
- pkg/monitortests/cli/adm_upgrade/status/updatelifecycle_test.go
Checks in `updateLifecycle` only make sense in jobs that update at most once, so skip the tests when multiple hops were made.
Example failure: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.20-upgrade-from-stable-4.19-from-stable-4.18-e2e-aws-ovn-upgrade/1958216717935054848
> NO-JIRA: `oc adm upgrade status`: Skip test in multihop update jobs

- test/extended/networking/servicecidr.go
- test/extended/testdata/bindata.go
- test/extended/testdata/servicecidr.yaml
(Test should fail until https://github.com/openshift/cluster-network-operator/pull/2605 merges.)
> OCPBUGS-61196: Add test that the ServiceCIDR API is blocked

- pkg/defaultmonitortests/types.go
- pkg/monitortests/testframework/legacytestframeworkmonitortests/alerts_monitortest.go
- pkg/monitortests/testframework/legacytestframeworkmonitortests/pathological_events.go
- pkg/monitortests/testframework/legacytestframeworkmonitortests/pathological_events_monitortest.go
For disruptive test suites like the MCO disruptive these tests doesn't make sense as the nodes reboot, are added and deleted, etc. It's not possible to reliably determine which events are fired because of node status changes and which one can be considered a failure so we just remove the tests for this type of suites.
> MCO-1828: Remove pathological test in disruptive

- test/e2e/upgrade/upgrade.go
- test/extended/machine_config/helpers.go
Adjust the test to not fail upgrade checks if all nodes are ready. This allows for updates that do not require node drain. Shipping a default ClusterImagePolicy during upgrade https://github.com/openshift/cluster-update-keys/pull/85
> OCPNODE-3659: Not fail upgrade checks if all nodes are ready

- test/extended/util/util_otp.go
finalArgs is overwritten in `cli.start()` https://github.com/memodi/origin/blob/main/test/extended/util/client.go#L1016, ultimately templating args set by `Template()` is not being passed.
I verified fix by making a local run for one of the test which uses `Template()`, test passes successfully.
> NO-JIRA: BugFix- don't modify finalArgs in Template func

- pkg/monitortestlibrary/platformidentification/operator_mapping.go
- pkg/monitortests/clusterversionoperator/legacycvomonitortests/operators.go
Revert https://github.com/openshift/origin/pull/30313 with an exception [OCPBUGS-62517](https://issues.redhat.com/browse/OCPBUGS-62517) for co/olm.
/hold
Let us run the aggregated job to avoid breaking payload again.
> Revert "Revert "NO-JIRA: Add olm into the known operator set""

- test/extended/rorfs/readonly_root_filesystem.go
Refactored the single large readOnlyRootFilesystem test case into 18 individual test cases, each focusing on a specific namespace. This change improves test execution time, provides better isolation, and makes debugging easier.
1. Test Structure Refactoring
Before: Single large test case with 50-minute timeout testing all namespaces
After: 18 individual test cases with 10-minute timeout each, using a loop-based approach
> NO-JIRA: Improve case execution time

- test/extended/networking/livemigration.go
Use GetIPAddressFamily and utilnet IP string helpers to filter preconfigured IPs to only include addresses supported by the cluster under test.
> NO-JIRA: Filter preconfiguredIPs based on cluster IP family support
