- pkg/generate/app/imageref.go
Fix for https://github.com/openshift/origin/issues/4186
> Return empty Config field in FromName to avoid nil pointer error 

- README.md
Getting started is better now: https://github.com/openshift/openshift-docs/pull/959
@liggitt @pweil-
> Simplify the readme to point to docs

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/cmd_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/expose.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/expose_test.go
- test/cmd/basicresources.sh
- test/fixtures/external-service.yaml
Fixes #4593 
@smarterclayton 
Upstream PR: https://github.com/kubernetes/kubernetes/pull/13756
> Make external services exposable

- Makefile
- hack/common.sh
- hack/extract-release.sh
Depends on https://github.com/openshift/vagrant-openshift/pull/321
> Make release extraction a separate step for builds

- assets/bower.json
Fixes issue https://github.com/openshift/origin/issues/3180
> Update to version 0.0.9 for kubernetes-label-selector.  

- assets/app/scripts/controllers/builds.js
- assets/app/scripts/controllers/create/createFromImage.js
- assets/app/scripts/controllers/createProject.js
- assets/app/scripts/controllers/util/oauth.js
- assets/app/scripts/directives/oscGitLink.js
- assets/app/scripts/services/applicationGenerator.js
- assets/app/scripts/services/login.js
> Cleaning useless colon

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/ovssubnet/api/types.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/ovssubnet/common.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/ovssubnet/controller/multitenant/bin/openshift-sdn-multitenant-setup.sh
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/ovssubnet/controller/multitenant/multitenant.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/ovssubnet/registry/registry.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/firewalld/firewalld.go
- plugins/osdn/osdn.go
closes: https://github.com/openshift/openshift-sdn/issues/145
Depends on: https://github.com/openshift/openshift-sdn/pull/146
> Fix potential race conditions during SDN setup

- test/util/server.go
In addition to checking for the existence of service accounts, also check for the existing of secrets related to those service accounts.
Fixes #4659
> Add SA secret checking to SA readiness test in integration tests

- examples/image-streams/image-streams-centos7.json
- examples/image-streams/image-streams-rhel7.json
fixes https://github.com/openshift/origin/issues/4699
> switch to https for sample repo url

- hack/build-images.sh
- hack/build-release.sh
- hack/common.sh
- hack/extract-release.sh
Hold to determine whether this works or not.
> Linux 386 cross compile

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/transport.go
Upstream https://github.com/kubernetes/kubernetes/pull/14063
Currently, if I specify a client certificate and do not specify the server's CA, the system trusted CAs are not used.
This change falls back to the system trusted CAs if no certificate authority data is available for the server. I can't create the a pool with the union of the system CAs and specified CA because the system CA cert pool is not exposed.
@liggitt @smarterclayton ptal
@sdodson  fyi
> UPSTREAM: 14063: enable system CAs

- origin.spec
- Create /var/lib/origin symlink for upgrades
- Add obsoletes on openshift < 1.0.6
> [RPMs] Ease the upgrade to v1.0.6

- test/extended/core.sh
- test/extended/util/test.go
> Add TEST_ONLY mode to bypass core execution, exclude k8s

- pkg/cmd/server/origin/ensure.go
The `openshift` and `openshift-infra` namespaces were missing the rolebindings for their default service accounts.  That lack of consistency has led to questions about creating builds in the `openshift` namespaces.
I don't feel strongly about `openshift-infra` since that one is "ours", but I like the consistency of having both.
@liggitt
> add SA role bindings to auto-provisioned namespaces

- pkg/build/builder/common.go
- pkg/build/builder/docker.go
- pkg/build/builder/sti.go
> Refactor setting and resetting HTTP proxies

- assets/app/scripts/services/applicationGenerator.js
- assets/test/spec/services/applicationGeneratorSpec.js
- pkg/cmd/cli/cmd/newapp.go
- pkg/cmd/cli/cmd/newbuild.go
- pkg/generate/app/app.go
- pkg/generate/app/cmd/newapp.go
- pkg/util/labels.go
Fixes: https://github.com/openshift/origin/pull/3987
> Add generated-by annotation to CLI new-app

- test/extended/README.md
> added syntax highlighting to readme

- hack/test-cmd.sh
- pkg/cmd/admin/oadm_bashcomp_func.go
- pkg/cmd/admin/validate/master.go
- pkg/cmd/admin/validate/node.go
- pkg/cmd/admin/validate/validate.go
- pkg/cmd/openshift/openshift.go
- pkg/cmd/server/api/latest/helpers.go
- rel-eng/completions/bash/openshift
@deads2k @liggitt  PTAL
Fixes #3803
> added oadm commands to validate node and master config

- pkg/build/api/types.go
- pkg/build/generator/generator.go
- pkg/build/generator/generator_test.go
- pkg/util/namer/namer.go
fixes https://github.com/openshift/origin/issues/4709
also fixes https://github.com/openshift/origin/issues/3368
> annotate builds on clone

- assets/app/index.html
- assets/app/scripts/app.js
- assets/app/scripts/controllers/create/createFromImage.js
- assets/app/scripts/controllers/create/nextSteps.js
- assets/app/scripts/controllers/newfromtemplate.js
- assets/app/scripts/filters/util.js
- assets/app/scripts/services/data.js
- assets/app/scripts/services/navigate.js
- assets/app/scripts/services/tasks.js
- assets/app/styles/_core.less
- assets/app/views/create/nextSteps.html
Instead of going directly to the overview, this adds an interstitial page (like we did in v2) with possible next steps, like creating webhooks, downloading and installing the CLI, etc.
> Next steps page (after creating stuff in console)

- pkg/project/util/util.go
In case of conflict when doing a finalize operation, we should retry.
> Retry finalizer on conflict error

- hack/install-assets.sh
Notable changes
* JMX plugin won't send X-Authorization header anymore
* Camel plugin improvements
@jwforres FYI
> Update java console

- api/swagger-spec/oapi-v1.json
- pkg/api/deep_copy_generated.go
- pkg/api/serialization_test.go
- pkg/api/v1/conversion_generated.go
- pkg/api/v1/deep_copy_generated.go
- pkg/api/v1beta3/conversion_generated.go
- pkg/api/v1beta3/deep_copy_generated.go
- pkg/build/api/types.go
- pkg/build/api/v1/types.go
- pkg/build/api/v1beta3/types.go
- pkg/build/controller/controller.go
- pkg/build/controller/controller_test.go
> Include pushspec in build status

- test/extended/core.sh
> Disable the pods per node test - it requires the kubelet stats

- Godeps/Godeps.json
Fixes https://github.com/openshift/origin/issues/4675
@liggitt
> bump github.com/vjeantet/ldapserver

- assets/app/scripts/controllers/service.js
- assets/app/views/browse/service.html
> Watch routes on individual service page

- assets/app/scripts/directives/templateopt.js
- assets/app/views/_templateopt.html
> Allow whitespace-only values in UI for required parameters

- test/extended/images/mysql_ephemeral.go
- test/extended/images/mysql_replica.go
- test/extended/util/cli.go
- test/extended/util/db_image_helpers.go
- test/extended/util/framework.go
Adding extended tests for MySQL replication extended tests. Heavy WIP. Will need to move some functionality from the test to a separate helper file. @mfojtik PTAL.
@rhcarvalho happy :christmas_tree:
> Mysql replication extended tests

- assets/app/scripts/controllers/builds.js
- assets/app/views/builds.html
- assets/app/views/deployments.html
Fixes https://github.com/openshift/origin/issues/4855
> Issue 4855 - warning flickers about build config and deployment config not existing

- HACKING.md
@deads2k @liggitt @pweil- @soltysh
> Update docs regarding the rebase

- vagrant/provision-util.sh
(Wasn't correctly updated for the openshift-sdn reorg.)
@pravisankar
> Fix vagrant provisioning

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/handlers_test.go
Upstream flake resolution.  Already merged upstream.  [merge]
> UPSTREAM: 14688: Deflake max in flight

- assets/app/views/deployments.html
Fixes https://github.com/openshift/origin/issues/4860
> Issue 4860 - missing no deployments msg when only have RCs

- assets/app/views/project.html
- assets/test/e2e/test.js
Fixes https://github.com/openshift/origin/issues/4632
> Issue 4632 - remove 'Project' from the project overview header

- pkg/build/controller/controller.go
- pkg/build/controller/factory/factory.go
- pkg/cmd/cli/describe/describer.go
Fixes #4362 and https://bugzilla.redhat.com/show_bug.cgi?id=1262883.
> Set build status message in case of error

- images/base/Dockerfile
- origin.spec
@ncdc @sdodson @smarterclayton 
Closes https://github.com/openshift/origin/issues/4843
> Add ethtool to our deps

- pkg/build/builder/cmd/scmauth/password.go
> Fix output of git basic credentials in builder

- assets/app/views/project.html
- assets/app/views/services.html
Fixes https://github.com/openshift/origin/issues/4867
> Issue 4867 - route links should open in a new window

- assets/app/scripts/controllers/settings.js
- assets/app/styles/_tables.less
- assets/app/views/settings.html
Fixes https://github.com/openshift/origin/issues/4001
> Issue 4001 - add requests and limits to resource limits on settings page

- pkg/project/admission/lifecycle/admission.go
- pkg/project/admission/lifecycle/admission_test.go
- test/integration/bootstrap_policy_test.go
@deads2k @derekwaynecarr - proposal for not leaking the not found error in the lifecycle admission
fixes https://github.com/openshift/origin/issues/4769
> do not leak not found in namespace lifecycle admission

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/patch.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1267428
[merge]d upstream
> UPSTREAM: 14831: allow yaml as argument to patch

- images/base/Dockerfile.rhel7
> Add ethtool to base/Dockerfile.rhel7 too

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/resthandler_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/third_party/forked/json/fields.go
- test/cmd/builds.sh
Blocker bug: https://bugzilla.redhat.com/show_bug.cgi?id=1267474 .
@mfojtik this the upstream version of the kube code.
@liggitt this is worth some thinking on.  Reasoning about safety and intent isn't trivial.
> fix patch of anonymous fields

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/server.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/registry/pod/etcd/etcd.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/conn.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/conn_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/doc.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/stream.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/stream_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/pods.go
- Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/util.go
> UPSTREAM: 13885: Support websockets on exec and pod logs

- HACKING.md
- hack/cherry-pick.sh
- hack/common.sh
Adds support for cherry-picking pulls from upstream.
[merge]
> Cherry-pick helper

- .travis.yml
- hack/common.sh
- pkg/cmd/cli/describe/chaindescriber.go
Extracted from https://github.com/openshift/origin/pull/4324
> Fix compilation on go 1.5

- pkg/project/admission/lifecycle/admission.go
instead of kind per: https://github.com/openshift/origin/commit/9346c85af733d1e5347f92e5fec863e44ed0078e#commitcomment-13575594
@deads2k
> Use resource to check intent

- .travis.yml
- Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go
- Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory_test.go
- hack/cherry-pick.sh
See:
https://github.com/kubernetes/kubernetes/pull/12967#issuecomment-143511934
> Update travis to go 1.5.1

- pkg/build/controller/controller.go
Lowercase resource names in error messages in the build controller to conform to the project guidelines.
> Lowercase resource names

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/stream_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/admission/namespace/lifecycle/admission_test.go
- pkg/build/registry/buildlog/rest_test.go
@bparees PTAL (fixes one of the race conds in go 1.5)
> Fix tests for go 1.5

- test/extended/images/helper.go
- test/extended/images/s2i_perl.go
- test/extended/images/s2i_python.go
- test/extended/util/framework.go
> Add tests for S2I Perl and Python images with Hot Deploy

- pkg/generate/app/cmd/newapp.go
- pkg/generate/app/cmd/newapp_test.go
- pkg/generate/app/componentmatch.go
- pkg/generate/app/dockerimagelookup.go
- pkg/generate/app/imagestreamlookup.go
- test/cmd/newapp.sh
fixes https://github.com/openshift/origin/issues/3637
> create local images as docker refs

- assets/app/index.html
- assets/app/scripts/app.js
- assets/app/scripts/controllers/route.js
- assets/app/scripts/controllers/routes.js
- assets/app/styles/_core.less
- assets/app/views/browse/route.html
- assets/app/views/browse/routes.html
- assets/app/views/browse/service.html
- assets/app/views/services.html
Fixes https://github.com/openshift/origin/issues/2378
> Issue 2378 - Show TLS information for routes, create routes and routes/routename pages

- test/extended/builds/sti_env.go
- test/extended/builds/sti_incremental.go
- test/extended/images/s2i_images.go
- test/extended/images/scl.go
- test/extended/util/framework.go
Obsoletes: https://github.com/openshift/origin/pull/4029
This might serve as an example for adding more 'test groups'. 
NOTE: The first three commits will be removed as long as https://github.com/openshift/origin/pull/4285 gets merged.
> Add SCL usage extended tests for S2I images

- contrib/completions/bash/oadm
- contrib/completions/bash/openshift
- docs/generated/oadm_by_example_content.adoc
- pkg/cmd/admin/policy/policy.go
- pkg/cmd/admin/policy/reconcile_clusterrolebindings.go
- pkg/cmd/admin/policy/reconcile_clusterrolebindings_test.go
- pkg/cmd/admin/policy/reconcile_clusterroles.go
- test/cmd/admin.sh
- test/fixtures/basic-user.json
- test/fixtures/basic-users-binding.json
Needed for the updated role binding needed for the existing kubelet client user the master is using
> reconcile-cluster-role-bindings command

- test/util/server/server.go
@liggitt fixes the ports for the integration all-in-one.
> fix non-default all-in-one ports for testing

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/http.go
- pkg/auth/server/login/helper.go
- pkg/cmd/server/api/conversions.go
- pkg/cmd/server/api/helpers.go
- pkg/cmd/server/api/types.go
- pkg/cmd/server/api/v1/types.go
- pkg/cmd/server/api/v1/types_test.go
- pkg/cmd/server/api/validation/oauth.go
- pkg/cmd/server/origin/auth.go
- pkg/cmd/server/origin/auth_config.go
- pkg/cmd/server/start/master_args.go
- pkg/dockerregistry/client.go
Fixes https://github.com/openshift/origin/issues/4894
> Use correct master url for token requests, set master CA correctly

- CONTRIBUTING.adoc
- examples/sample-app/cleanup.sh
PTAL @rhcarvalho @mfojtik @kargakis
> sample-app/cleanup.sh: fix usage of not-installed killall command

- assets/app/index.html
- assets/app/scripts/directives/nav.js
- assets/app/styles/_components.less
- assets/app/styles/_core.less
- assets/app/styles/_messages.less
- assets/app/styles/_tile.less
- assets/app/styles/_variables.less
- assets/app/styles/main.less
- assets/app/views/_alerts.html
- assets/app/views/_deployment-config-metadata.html
- assets/app/views/_overview-deployment.html
- assets/app/views/_pods.html
- assets/app/views/_project-nav.html
- assets/app/views/browse/image.html
- assets/app/views/builds.html
- assets/app/views/create.html
- assets/app/views/create/fromimage.html
- assets/app/views/create/nextSteps.html
- assets/app/views/deployments.html
- assets/app/views/directives/_pod-warnings.html
- assets/app/views/projects.html
- assets/app/views/settings.html
- assets/bower.json
- Several included plugins were updated
- bootstrap-select
- bootstrap-combobox
- Several areas had positioning/display issues related to the update that were fixed
- messenger messages
- project select
- nav.js updated to remove unneeded li's
- create using your code input field
- Warning and Error icons were updated on several pages
- Move class="checkbox" to parent div so label and checkbox are positioned correctly
- Misc change of header on services page
Fixes https://github.com/openshift/origin/issues/2505
Fixes https://github.com/openshift/origin/issues/4832
> Update to latest version of PatternFly 2.2.0 and Bootstrap  3.3.5

- pkg/cmd/cli/cli.go
Kube made their printers hide terminated pods by default.  Since terminated pods are very interesting (did it fail or exit normally, show me those logs, etc), that really hurts usability.  This pull changes the default.
The implementation is a little weird.  We can't change the default inside the godeps code because that would change the behavior of our `kubectl` symlink.  Instead, after the commands are registered, we walk them looking for the bad flag and change its default value, current value, and description.
@kargakis 
@smarterclayton Want to change it for embedded `kubectl` too?
> change show-all default to true

- test/cmd/newapp.sh
> new-app: fix newapp test flake

- docs/cli.md
Documentation update for https://github.com/openshift/origin/pull/4315
> Delete --all option for oc export in cli doc

- test/extended/images/helper.go
- test/extended/images/s2i_perl.go
- test/extended/images/s2i_php.go
- test/extended/images/s2i_ruby.go
> Adding extended tests for Ruby and PHP hot deploy

- hack/util.sh
- test/extended/builds/gitauth.go
- test/extended/core.sh
- test/extended/fixtures/test-auth-build.yaml
- test/extended/fixtures/test-gitserver.yaml
Uses the internal gitserver to test a build with a custom ca-cert and username/password.
> Add extended test for build from private source repository

- examples/hello-openshift/hello-pod.json
- examples/hello-openshift/hello-project.json
Move hello-openshift example to API v1
> examples: Move hello-openshift example to API v1

- contrib/vagrant/provision-config.sh
- contrib/vagrant/provision-master.sh
- contrib/vagrant/provision-minion.sh
Fix vagrant scripts after they got moved to contrib/.
Make sure that the right network configuration is always started with the default images.
> Vagrant fixes

- hack/test-cmd.sh
- pkg/cmd/openshift/openshift.go
- pkg/cmd/server/api/helpers.go
- pkg/cmd/server/api/types.go
- pkg/cmd/server/api/types_test.go
- pkg/cmd/server/api/validation/validation.go
- pkg/cmd/server/start/start_master.go
- pkg/cmd/util/product.go
- test/cmd/help.sh
Fixes test symlinks setup and ditches speces from API constant values.
Shall be extended for product naming changes once the discussion settles down.
> Atomic feature flags followup

- pkg/generate/app/cmd/newapp_test.go
- pkg/generate/app/pipeline.go
- pkg/util/namer/namer.go
- pkg/util/namer/namer_test.go
> Revert "Unique output image stream names in new-app"

- test/extended/util/cli.go
> Remove forgotten code no longer used

- pkg/build/builder/sti.go
- pkg/build/builder/sti_test.go
These are followup fixes from #4902.
@bparees ptal.
> Post 4902 fixes

- pkg/cmd/admin/policy/reconcile_clusterrolebindings.go
- pkg/cmd/admin/policy/reconcile_clusterrolebindings_test.go
- pkg/cmd/experimental/diagnostics/cluster.go
- pkg/diagnostics/cluster/rolebindings.go
- pkg/diagnostics/cluster/roles.go
- test/old-start-configs/v1.0.0/test-end-to-end.sh
Add diagnostic for role bindings
Updates compatibility test to reconcile rolebindings
> reconcile-cluster-role-bindings followup

- images/openldap/contrib/init.ldif
- test/extended/authentication/sync-schema1-group1.yaml
- test/extended/authentication/sync-schema2-01.yaml
@liggitt Please sanity-check this. I've added the equivalent entries for the Active Directory and enhanced Active Directory schemas.
> added LDAP entries for other schemas

- pkg/cmd/cli/cmd/logs.go
- test/end-to-end/core.sh
> Fix oc logs

- assets/app/views/browse/deployment-config.html
- assets/app/views/builds.html
- assets/app/views/deployments.html
Also:
Fixes https://github.com/openshift/origin/issues/5055
> Remove build history and deployment history from main tables

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/cmd.go
- pkg/cmd/cli/cmd/wrappers.go
- test/cmd/basicresources.sh
Spawned kubernetes/kubernetes#15451 to make this generic
> Display OpenShift resources in `oc get` default info

- assets/app/styles/_components.less
- assets/app/styles/_core.less
- assets/app/styles/_mixins.less
- assets/app/styles/_openshift-icon.less
- assets/app/styles/_variables.less
- assets/app/views/_pod-template.html
- assets/app/views/catalog/_image.html
- assets/app/views/newfromtemplate.html
Fixes https://github.com/openshift/origin/issues/4489
Fixes https://github.com/openshift/origin/issues/3718
icon alignment and font sizing corrections
remove unused styles
> Fix pod template clipped issue

- pkg/api/graph/test/unpushable-build-2.yaml
- pkg/build/graph/analysis/bc.go
- pkg/build/graph/analysis/bc_test.go
Fixes https://github.com/openshift/origin/issues/5007
@deads2k
> status: Fix incorrect missing registry warning

- test/extended/images/mysql_replica.go
This should fix a race condition in the MySQL replication test where we do not wait until the scaled-down slave pod is removed. We scale to 0, then back to 4 and after that, we list the pods and then later use that list for replication testing. However, if the previous slave won't disappear before we get the list of pods, we might end up with the old pod and then fail because it gets deleted. This can be see in this Jenkins job: https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/5541/consoleFull
Relevant logs:
```
STEP: after slave is scaled to 0 and then back to 4 replicas
deploymentconfig "mysql-slave" scaled
deploymentconfig "mysql-slave" scaled
deploymentconfig "mysql-helper" deleted
```
The last line is caused by the cleanup function. Error is here:
```
Expected …
```
> Fix MySQL replication extended test race

- assets/app/scripts/extensions/javaLink.js
Will require this PR -> https://github.com/kubernetes/kubernetes/pull/14876
@liggitt @rhuss FYI...
> Specify scheme in the jolokia URL

- assets/app/index.html
- assets/app/scripts/controllers/image.js
- assets/app/scripts/services/imagestreams.js
- assets/app/views/browse/image.html
Also:
Fixes https://github.com/openshift/origin/issues/2962
> Update image stream page to use a table for the tags

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/cmd/admin/network/isolate_projects.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/cmd/admin/network/join_projects.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/cmd/admin/network/pod_network.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/cmd/admin/network/project_options.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/cmd/admin/network/unisolate_projects.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/ovssubnet/api/types.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/ovssubnet/common.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/ovssubnet/controller/kube/bin/openshift-ovs-subnet
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/ovssubnet/controller/kube/bin/openshift-sdn-kube-subnet-setup.sh
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/ovssubnet/controller/kube/kube.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/ovssubnet/controller/multitenant/bin/openshift-ovs-multitenant
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/ovssubnet/controller/multitenant/multitenant.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/flatsdn/flatsdn.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/multitenant/multitenant.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/multitenant/plugins.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/osdn.go
- contrib/completions/bash/oadm
- contrib/completions/bash/openshift
- docs/generated/oadm_by_example_content.adoc
- pkg/client/netnamespaces.go
- pkg/client/testclient/fake_netnamespaces.go
- pkg/cmd/admin/admin.go
- pkg/sdn/api/validation/validation.go
Remove update netnamespace validation
Depends on PR: https://github.com/openshift/openshift-sdn/pull/176
> Support oadm pod-network cmd

- hack/install-assets.sh
* Adds some enhancements to the hawtio-integration component for Apache Camel
@jwforres FYI, thanks!
> Move to openshift-jvm 1.0.29

- assets/app/index.html
- assets/app/styles/_core.less
- assets/app/styles/_tables.less
- assets/app/views/browse/build-config.html
- assets/app/views/browse/deployment-config.html
- assets/app/views/browse/routes.html
- assets/app/views/builds.html
- assets/app/views/deployments.html
- assets/app/views/events.html
- assets/app/views/images.html
- assets/app/views/pods.html
- assets/app/views/services.html
- assets/bower.json
And update 2 broken paths to their correct locations within patternfly components js
> Convert tables to 2 column layout when less than 769px width

- pkg/diagnostics/cluster/registry.go
In the cluster admin diagnostic which scans the registry pod logs, add an
explicit check for an error which indicates the registry cannot write to disk,
which is a strong indicator for an selinux problem. The fix from the origin
troubleshooting page is then suggested.
We also watch for a successful write log entry, and if found *after* the error,
we know the problem has since been fixed and the diagnostic error can be safely
ignored.
This replaces pr #4926.
> Scan for selinux write error in registry diagnostic.

- hack/test-cmd.sh
- hack/test-go.sh
- hack/update-generated-swagger-spec.sh
- hack/util.sh
These were problems I hit with parallel make.
@jhadvig ptal.
> deconflict swagger ports

- assets/app/scripts/directives/popups.js
- assets/app/scripts/filters/util.js
- assets/app/scripts/services/imageStreamResolver.js
- assets/app/scripts/services/navigate.js
- assets/app/styles/_components.less
- assets/app/views/_overview-deployment.html
- assets/app/views/_pod-template.html
- assets/app/views/_triggers.html
- assets/app/views/browse/routes.html
- assets/app/views/project.html
Also fixes the warning popups on pods.
And the last remaining issue for:
Fixes https://github.com/openshift/origin/issues/3361
Fixes https://github.com/openshift/origin/issues/3364
Fixes https://github.com/openshift/origin/issues/5039
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1270185
> Add links to things from the overview and pod template

- HACKING.md
- hack/cherry-pick.sh
- hack/move-upstream.sh
> Generalize move-upstream.sh

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/cmd/admin/network/isolate_projects.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/cmd/admin/network/join_projects.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/cmd/admin/network/unisolate_projects.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/ovssubnet/api/types.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/ovssubnet/common.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/flatsdn/flatsdn.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/multitenant/multitenant.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/osdn.go
- docs/generated/oadm_by_example_content.adoc
- pkg/cmd/server/kubernetes/node.go
- pkg/cmd/server/origin/run_components.go
- pkg/cmd/server/start/start_node.go
This updates the openshift-sdn Godep to https://github.com/openshift/openshift-sdn/pull/178 and implements the origin side of it.
@pravisankar
> Service endpoint isolation

- pkg/cmd/server/etcd/etcd.go
> Fix etcd transport error with high debug levels

- docs/cli_hacking_guide.adoc
- pkg/cmd/cli/cmd/deploy.go
> Update the hacking guide

- test/extended/builds/sti_env.go
- test/extended/builds/sti_incremental.go
Canary for: https://github.com/openshift/origin/issues/4442
> Rename STI to s2i in extended test

- pkg/cmd/admin/registry/registry.go
- pkg/cmd/admin/router/router.go
- pkg/cmd/cli/cmd/newapp.go
- pkg/cmd/cli/cmd/newbuild.go
- pkg/cmd/experimental/ipfailover/ipfailover.go
- pkg/config/cmd/cmd.go
- pkg/generate/app/cmd/newapp_test.go
- pkg/ipfailover/keepalived/plugin.go
- pkg/ipfailover/types.go
Also remove some extra complexity in new-app output.
@csrwng @bparees
> Use cmdutil.PrintSuccess() to display bulk output

- pkg/generate/app/app.go
- pkg/generate/app/errors.go
- pkg/generate/app/pipeline.go
- pkg/generate/app/pipeline_test.go
Addresses https://github.com/openshift/origin/pull/4994#issuecomment-147004953.
Also replace maxServiceNameLength with constant from kube (as [pointed out](https://github.com/openshift/origin/pull/4994#issuecomment-146716494) by @kargakis).
> Return error instead of generating arbitrary names

- examples/sample-app/README.md
@mfojtik PTAL... just a small update
> Sample app readme update

- pkg/auth/authenticator/password/allowanypassword/anyauthpassword.go
- pkg/auth/authenticator/password/basicauthpassword/basicauthpassword.go
- pkg/auth/authenticator/password/htpasswd/htpasswd.go
- pkg/auth/authenticator/password/keystonepassword/doc.go
- pkg/auth/authenticator/password/keystonepassword/keystonepassword.go
- pkg/auth/authenticator/password/keystonepassword/keystonepassword_test.go
- pkg/auth/authenticator/password/ldappassword/ldap.go
- pkg/auth/authenticator/password/oauthpassword/oauthpassword.go
- pkg/cmd/server/api/helpers.go
- pkg/cmd/server/api/register.go
- pkg/cmd/server/api/types.go
- pkg/cmd/server/api/v1/register.go
- pkg/cmd/server/api/v1/types.go
- pkg/cmd/server/api/v1/types_test.go
- pkg/cmd/server/api/validation/oauth.go
- pkg/cmd/server/origin/auth.go
This now works with Keystone v3 both with and without SSL.
Docs issue: https://github.com/openshift/openshift-docs/issues/1073
> Adding keystone IdP

- pkg/cmd/server/kubernetes/master_config.go
- pkg/cmd/server/kubernetes/node_config.go
Inspired by master_config.go: BuildKubernetesMasterConfig().
Fixes #5156 on OpenStack, but please check carefuly, I have almost no knowledge about OpenShift initialization.
> Provide initialized cloud provider in Kubelet config.

- docs/generated/oc_by_example_content.adoc
- pkg/cmd/cli/cmd/newapp.go
Please refer to https://github.com/openshift/origin/issues/4644
> Add environment values to oc new-app help for mysql

- pkg/api/serialization_test.go
> Fix fuzzing versions in serialization tests

- contrib/systemd/atomic-openshift-master.service
- contrib/systemd/atomic-openshift-node.service
- origin.spec
Also fix an existing build issue.
> [RPMS] Switch atomic-openshift services to /usr/bin/openshift

- pkg/cmd/admin/admin.go
- pkg/cmd/cli/cli.go
- pkg/cmd/infra/builder/builder.go
- pkg/cmd/infra/deployer/deployer.go
- pkg/cmd/infra/router/f5.go
- pkg/cmd/infra/router/template.go
- pkg/cmd/openshift/openshift.go
- pkg/cmd/server/start/kubernetes/kubernetes.go
- pkg/version/version.go
> Print etcd version when calling openshift version

- hack/test-cmd.sh
> Raw sed should not be used in hack/* scripts for Macs

- hack/test-cmd.sh
> Output less info on hack/test-cmd.sh failures

- test/cmd/export.sh
> test/cmd/export.sh shouldn't dump everything to STDOUT

- assets/app/scripts/services/data.js
- assets/test/spec/services/dataServiceSpec.js
> Preserve case of subresources when normalizing URLs

- assets/app/index.html
- assets/app/scripts/app.js
- assets/app/scripts/directives/nav.js
- assets/app/scripts/directives/popups.js
- assets/app/styles/_sidebar.less
- assets/app/styles/_tile.less
- assets/app/styles/_variables.less
- assets/app/views/_sidebar-main-nav-item.html
- assets/app/views/_sidebar.html
- assets/app/views/browse/routes.html
- assets/app/views/directives/osc-secondary-nav.html
- assets/bower.json
Related story
https://trello.com/c/LyjZFY5u/541-5-move-secondary-navigation-into-a-hover-menu
> Convert secondary nav to a hover menu

- assets/app/views/browse/deployment-config.html
> Fix deployment config minor ui changes.

- pkg/cmd/cli/describe/deployments.go
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1268933
> Minor deployment describer formatting fix

- assets/app/index.html
- assets/app/styles/_core.less
https://docs.angularjs.org/api/ng/directive/ngCloak
> Add ng-cloak to navbar to reduce flicker on load

- test/extended/core.sh
> Disable new upstream e2e tests

- assets/app/scripts/controllers/create/createFromImage.js
- assets/app/scripts/controllers/newfromtemplate.js
- assets/app/scripts/services/data.js
- assets/app/scripts/services/project.js
Also fixes an issue with the project dropdown not containing all projects
when on a page that uses the new project service instead of the nested controllers
> Bug 1271989 - error when navigating to resources in diff projects

- pkg/cmd/server/kubernetes/node.go
Fixes bug 1270474
Link is here: https://bugzilla.redhat.com/show_bug.cgi?id=1270474
> This commit implements birthcry event for openshift proxy.

- assets/app/styles/_core.less
- assets/app/views/directives/labels.html
Fixes https://github.com/openshift/origin/issues/5181
uses default .label instead of .badge
uses layout.attrs flex for positioning and wrap/nowrap
> Update label key/value pairs truncate at <769. 

- assets/app/scripts/directives/popups.js
- assets/app/styles/_sidebar.less
- assets/app/views/_sidebar-main-nav-item.html
Makes the hover menu accessible, fixes behavior on ipad.
> Bug 1273350 - make click open the secondary nav instead of navigating

- images/openldap/contrib/init.ldif
- test/extended/authentication.sh
- test/extended/authentication/ldap/ad/valid_all_blacklist_sync.txt
- test/extended/authentication/ldap/ad/valid_all_ldap_sync.txt
- test/extended/authentication/ldap/ad/valid_all_ldap_sync_partially_user_defined.txt
- test/extended/authentication/ldap/ad/valid_all_ldap_sync_user_defined.txt
- test/extended/authentication/ldap/ad/valid_all_openshift_blacklist_sync.txt
- test/extended/authentication/ldap/ad/valid_whitelist_sync.txt
- test/extended/authentication/ldap/ad/valid_whitelist_union_sync.txt
- test/extended/authentication/ldap/augmented-ad/valid_all_blacklist_sync.txt
- test/extended/authentication/ldap/augmented-ad/valid_all_ldap_sync.txt
- test/extended/authentication/ldap/augmented-ad/valid_all_ldap_sync_partially_user_defined.txt
- test/extended/authentication/ldap/augmented-ad/valid_all_ldap_sync_user_defined.txt
- test/extended/authentication/ldap/augmented-ad/valid_all_openshift_blacklist_sync.txt
- test/extended/authentication/ldap/augmented-ad/valid_whitelist_sync.txt
- test/extended/authentication/ldap/augmented-ad/valid_whitelist_union_sync.txt
- test/extended/authentication/ldap/rfc2307/valid_all_blacklist_sync.txt
- test/extended/authentication/ldap/rfc2307/valid_all_ldap_sync.txt
- test/extended/authentication/ldap/rfc2307/valid_all_ldap_sync_dn_everywhere.txt
- test/extended/authentication/ldap/rfc2307/valid_all_ldap_sync_partially_user_defined.txt
- test/extended/authentication/ldap/rfc2307/valid_all_ldap_sync_user_defined.txt
- test/extended/authentication/ldap/rfc2307/valid_all_openshift_blacklist_sync.txt
- test/extended/authentication/ldap/rfc2307/valid_whitelist_sync.txt
- test/extended/authentication/ldap/rfc2307/valid_whitelist_union_sync.txt
Follow-up to #5047 
cc/ @deads2k
> updated artifacts for ldap extended tests

- assets/app/views/browse/_build-details.html
- assets/app/views/browse/deployment-config.html
- assets/app/views/browse/deployment.html
- assets/app/views/browse/route.html
- assets/app/views/browse/service.html
Fixes https://github.com/openshift/origin/issues/5207
> Remove old labels rendering from individual pages since its duplicate info

- assets/app/index.html
- assets/app/scripts/app.js
- assets/app/scripts/controllers/pod.js
- assets/app/scripts/services/ws.js
- assets/app/styles/_components.less
- assets/app/views/browse/pod.html
- assets/bower.json
- assets/test/karma.conf.js
Add a container terminal to the pod details page
This uses the container terminal widget:
https://github.com/kubernetes-ui/container-terminal/
> Add a container terminal to the pod details page

- pkg/client/imagestreammappings.go
- pkg/image/registry/imagestream/etcd/etcd.go
- pkg/image/registry/imagestream/etcd/etcd_test.go
- pkg/image/registry/imagestream/registry.go
- pkg/image/registry/imagestream/strategy.go
- pkg/image/registry/imagestreammapping/registry.go
- pkg/image/registry/imagestreamtag/registry.go
- pkg/image/registry/imagestreamtag/rest.go
- pkg/image/registry/imagestreamtag/rest_test.go
> Support deleting image stream status tags

- contrib/completions/bash/oc
- contrib/completions/bash/openshift
- docs/generated/oc_by_example_content.adoc
- pkg/cmd/cli/cmd/tag.go
- pkg/cmd/cli/cmd/tag_test.go
- test/cmd/images.sh
- test/fixtures/test-stream.yaml
> tag: Support deleting a tag with -d

- pkg/client/imagestreammappings.go
- pkg/image/registry/imagestream/etcd/etcd.go
- pkg/image/registry/imagestream/etcd/etcd_test.go
- pkg/image/registry/imagestream/registry.go
- pkg/image/registry/imagestream/strategy.go
- pkg/image/registry/imagestreammapping/registry.go
- pkg/image/registry/imagestreamtag/registry.go
- pkg/image/registry/imagestreamtag/rest.go
- pkg/image/registry/imagestreamtag/rest_test.go
> Revert "Support deleting image stream status tags"

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/api_installer.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/apiserver_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/errors.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/handlers.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/handlers_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/proxy.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/master/master.go
- pkg/authorization/authorizer/attributes_builder.go
- pkg/cmd/server/bootstrappolicy/policy.go
- pkg/cmd/server/origin/handlers.go
- pkg/cmd/server/origin/master_config.go
Fixes https://github.com/openshift/origin/issues/5234
This adds better non-resource url recognition and enables inspection of the available resources by default.
@liggitt
> Add non resource url parsing

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/proxy/transport.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/proxy/transport_test.go
Upstream PR https://github.com/kubernetes/kubernetes/pull/15784
Fixes BZ 1271955
> UPSTREAM: Proxy: do not send X-Forwarded-Host or X-Forwarded-Proto with an empty value

- assets/app/scripts/controllers/deploymentConfig.js
- assets/app/scripts/directives/popups.js
- assets/app/views/browse/deployment-config.html
- assets/app/views/deployments.html
Fixes https://github.com/openshift/origin/issues/4895
> Show status details for a DC in both the deployments table and DC pages

- pkg/build/controller/factory/factory.go
> Only try to update build if status message changed

- pkg/cmd/cli/cmd/tag.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1274200
> Bug 1274200: Prompt by default when deleting a non-existent tag

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory.go
stop suppressing errors.  [merge]
> UPSTREAM: 16042: fix missing error handling

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/attach.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/attach_test.go
Cherry-picking https://github.com/kubernetes/kubernetes/commit/7f6f85bd7b47db239868bcd868ae3472373a4f05.
PTAL @smarterclayton @liggitt
> Fixes attach broken during the refactor

- pkg/generate/app/cmd/newapp.go
- pkg/generate/app/componentresolvers.go
- pkg/generate/app/componentresolvers_test.go
- pkg/generate/app/dockerimagelookup.go
- test/cmd/newapp.sh
fixes https://github.com/openshift/origin/issues/4991
> rework how allow-missing-images resolves

- pkg/api/latest/latest.go
- pkg/authorization/api/types.go
- pkg/authorization/authorizer/attributes_builder.go
- pkg/cmd/server/api/helpers.go
- pkg/cmd/server/api/types.go
- pkg/cmd/server/api/v1/conversions.go
- pkg/cmd/server/api/v1/types.go
- pkg/cmd/server/api/v1/types_test.go
- pkg/cmd/server/api/validation/master.go
- pkg/cmd/server/bootstrappolicy/policy.go
- pkg/cmd/server/kubernetes/master.go
- pkg/cmd/server/kubernetes/master_config.go
- pkg/cmd/server/origin/handlers.go
- pkg/cmd/server/origin/master_config.go
Fixes https://github.com/openshift/origin/issues/5243
@ironcladlou ptal, the first two commits are from https://github.com/openshift/origin/pull/5257
@ncdc This enables the API for the extensions, but doesn't turn on the controllers yet.  Also, I don't remember Solly's(?) nick.
> Enable extensions

- pkg/cmd/server/bootstrappolicy/policy.go
> Allow patching events

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/client.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/pod_logs.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/pod_logs_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/testclient/fake_pod_logs.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/testclient/testclient.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/cmd_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/log.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/log_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/run.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory.go
- pkg/cmd/cli/cmd/logs.go
- pkg/cmd/cli/cmd/logs_test.go
- pkg/cmd/util/clientcmd/factory.go
@smarterclayton @deads2k @csrwng
> logs: Use resource builder and upstream code

- assets/bower.json
* Keep the vertices in bounds, don't let them stray off screen
Many other fixes
> assets: Update topology-graph widget

- pkg/security/controller/repair.go
- pkg/security/controller/repair_test.go
- pkg/security/uid/uid.go
> UID repair should not fail when out of range allocation

- assets/app/scripts/controllers/deploymentConfig.js
- assets/app/scripts/directives/resources.js
- assets/app/styles/_core.less
- assets/app/views/_pod-template.html
- assets/app/views/browse/_build-details.html
- assets/app/views/browse/_pod-details.html
- assets/app/views/browse/build-config.html
- assets/app/views/browse/build.html
- assets/app/views/browse/deployment-config.html
- assets/app/views/browse/deployment.html
- assets/app/views/browse/image.html
- assets/app/views/browse/pod.html
- assets/app/views/browse/route.html
- assets/app/views/browse/service.html
Consistent placing of created date
Adds mounts to the pod template on pages other than overview
Make volumes use the correct api format to show more info
> More cleanup of the individual pages, use the extra space better

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/conditions.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/conditions_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/service/servicecontroller.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/serviceaccount/tokens_controller.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wait/wait_test.go
- pkg/dockerregistry/server/repositorymiddleware.go
@ncdc this addressed the problem I'm having in #4853 regarding creating IS and immediately posting ISM right after that, which might conflict with import logic. ptal.
> Retry ISM save upon conflicting IS error

- pkg/cmd/server/kubernetes/master_config.go
Storage needs a list of interfaces that matches the API group its going to be referenced for with a version specified that's actually `GroupVersion` string.  Now even though that is fully qualifying and should allow for a shared set, no such set exists.  This builds the thing that's required several layers under.
@soltysh this fixed the create for me.
> enable storage interface functions

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/api/describe/describer.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/api/types.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/api/validation/validation.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/build/interfaces.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/build/strategies/layered/layered.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/build/strategies/onbuild/onbuild.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti_test.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/build/strategies/sti/usage.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/build/strategies/strategies.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/docker/docker.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/tar/tar.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/tar/tar_test.go
- pkg/build/builder/sti.go
- pkg/build/builder/util.go
- pkg/build/builder/util_test.go
Make the builder pod pass the network context to the source-to-image builder pod.
> Pass the network context to the s2i builder

- pkg/build/builder/sti.go
Broken by binary build PR
[test][extended:core]
> Fix context dir for STI

- Vagrantfile
> Vagrantfile should allow multiple sync folders

- examples/wordpress/nfs/README.md
Corrected the command in nfs examples
> Minor fix for nfs readme

- pkg/cmd/server/bootstrappolicy/policy.go
This is a follow-up to #5357 setting up the policies for jobs. Additionally I've removed excessive policies from RC. @deads ptal.
> Job policy

- assets/app/scripts/directives/podStatusChart.js
Don't call c3.generate() until we have data and add a watch expression that compares only pod phases, not the entire pod object.
Fixes #5387
> Only watch pod statuses for overview donut chart

- pkg/build/builder/util.go
Address code review comment: coding convention calls for regex
patterns to be defined as package level vars.
> Move the cgroup regex to package level.

- assets/app/scripts/directives/metrics.js
- assets/app/scripts/services/metrics.js
Don't specify an `end` query parameter on metrics requests so that the server's current time is used as an end time. Show the server error message in the alert details if available.
https://bugzilla.redhat.com/show_bug.cgi?id=1274679
> Bug 1274679 - Use server time for end time in metrics requests

- pkg/client/imagestreammappings.go
- pkg/cmd/server/origin/master.go
- pkg/image/registry/imagestream/etcd/etcd.go
- pkg/image/registry/imagestream/etcd/etcd_test.go
- pkg/image/registry/imagestream/registry.go
- pkg/image/registry/imagestream/strategy.go
- pkg/image/registry/imagestreamimage/rest_test.go
- pkg/image/registry/imagestreammapping/registry.go
- pkg/image/registry/imagestreammapping/rest_test.go
- pkg/image/registry/imagestreamtag/registry.go
- pkg/image/registry/imagestreamtag/rest.go
- pkg/image/registry/imagestreamtag/rest_test.go
- test/cmd/images.sh
- test/integration/buildclient_test.go
- test/integration/deploy_trigger_test.go
@smarterclayton @soltysh reopening this for discussion
> delete: Remove both image stream spec and status tags

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/stream_test.go
> UPSTREAM: 16241: Deflake wsstream stream_test.go

- pkg/generate/app/cmd/newapp.go
- pkg/generate/app/dockerimagelookup.go
- test/extended/cmd.sh
fixes https://github.com/openshift/origin/issues/4944
@csrwng ptal.
> report a warning and do not continue on a partial match

- assets/app/views/browse/build-config.html
- assets/app/views/browse/build.html
Fixes https://github.com/openshift/origin/issues/4886
> Show warning popup when builds have a status message

- assets/app/scripts/directives/resources.js
- assets/app/views/_overview-monopod.html
Show browse pods pod filtered to just that pod.
https://bugzilla.redhat.com/show_bug.cgi?id=1275506
> Bug 1275506 - Allow users to click monopod donut charts on overview

- assets/app/views/browse/routes.html
Fixes https://github.com/openshift/origin/issues/5416
> Show route target port in the routes table if its set

- assets/app/scripts/controllers/create/createFromImage.js
- assets/app/scripts/services/applicationGenerator.js
- assets/app/views/create/fromimage.html
- assets/test/spec/services/applicationGeneratorSpec.js
Fixes #3764
See also #4603 and previous PR #3837
> Expose all container ports creating from source in the UI

- contrib/completions/bash/oc
- contrib/completions/bash/openshift
- pkg/cmd/cli/cmd/newbuild.go
fixes https://github.com/openshift/origin/issues/5433
> add --context-dir flag to new-build

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/rest/create.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/rest/resttest/resttest.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/validation/name.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/validation/name_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/registry/generic/etcd/etcd.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/registry/namespace/etcd/etcd.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/registry/node/etcd/etcd.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/registry/persistentvolume/etcd/etcd.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/storage/util.go
Prevents path traversals in etcd storage
> UPSTREAM: 15975: Validate names in BeforeCreate

- assets/app/scripts/controllers/build.js
- assets/app/scripts/controllers/pod.js
- assets/app/scripts/directives/logViewer.js
- assets/app/scripts/services/data.js
- assets/app/scripts/services/logLinks.js
- assets/app/views/_triggers.html
- assets/app/views/browse/build.html
- assets/app/views/browse/pod.html
- Fix github issue #526 403 forbidden error
- Fix github issue #5262 log links missing href
- Fix github #5269 log links for failed, error builds on overview
- Partial fix github #5266, change "connection closed" to "Log complete"
- Add "Logs for build||pod as first line in log viewer
- Fix download log file link in firefox/other browsers w/arbitrary timeout to destroy link
@spadgett @jwforres
> Various console logs fixes

- assets/app/styles/_components.less
- assets/app/styles/_core.less
fixes https://github.com/openshift/origin/issues/5285
> Fix text-overflow issue on Safari

- CONTRIBUTING.adoc
- Vagrantfile
- contrib/vagrant/provision-dind.sh
- contrib/vagrant/provision-util.sh
- hack/dind-cluster.sh
- hack/dind/init.sh
- hack/util.sh
- images/dind/Dockerfile
- images/dind/supervisord.conf
- images/dind/wrapdind
- test/extended/networking.sh
- test/extended/networking/util.go
The contribution doc may not be the best place for this, so placement suggestions are welcome.
> Improve dind documentation and fix dind testing

- pkg/generate/app/cmd/newapp.go
fixes https://github.com/openshift/origin/issues/5434
> better error message for missing dockerfile

- pkg/build/controller/factory/factory.go
- pkg/build/controller/factory/factory_test.go
- pkg/util/errors/errors.go
fixes https://github.com/openshift/origin/issues/5422
> upper case first letter of status message

- assets/app/scripts/controllers/create/createFromImage.js
- assets/app/scripts/controllers/createProject.js
- assets/app/scripts/controllers/newfromtemplate.js
- assets/app/views/create/fromimage.html
- assets/app/views/createProject.html
- assets/app/views/newfromtemplate.html
Fixes https://github.com/openshift/origin/issues/5374
> Disable create form inputs and submit button while the API request is happening

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/helpers.go
- docs/generated/oc_by_example_content.adoc
- pkg/cmd/cli/cmd/newapp.go
- pkg/cmd/cli/cmd/newbuild.go
- pkg/generate/app/cmd/newapp.go
- pkg/generate/app/cmd/newapp_test.go
- pkg/generate/app/errors.go
- test/cmd/newapp.sh
> Improve error messages in new-app new-build

- hack/common.sh
Don't trust this too much - I may have misplaced an octopus merge somewhere.
@ncdc I know you mentioned you had troubles with cherrypick
@liggitt @deads2k try this
> In hack/cherry-pick find common parent for merged PRs

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/create.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/expose.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/replace.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/run.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/helpers.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/resource/helper.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/resource/helper_test.go
- examples/examples_test.go
- pkg/cmd/cli/cmd/edit.go
- pkg/cmd/cli/cmd/env.go
- pkg/cmd/cli/cmd/volume.go
- pkg/config/cmd/cmd.go
- test/integration/fixtures/project-request-template-with-quota.yaml
- test/integration/unprivileged_newproject_test.go
- test/util/helpers.go
Bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1275001
```
[ResourceQuota in version v1beta3 cannot be handled as a ResourceQuota: The apiVersion in the data (v1beta3) does not match the specified apiVersion(v1), LimitRange in version v1beta3 cannot 
be handled as a LimitRange: The apiVersion in the data (v1beta3) does not match the specified apiVersion(v1)]
```
> Fix project request quota

- assets/app/index.html
- assets/bower.json
https://bugzilla.redhat.com/show_bug.cgi?id=1275918
@jwforres angular-patternfly has the right fix now
> Bug 1275918 - Bump angular-pattern to version 2.3.4

- pkg/cmd/cli/cmd/loginoptions.go
> Slightly better output order in the CLI for login

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/v1/backward_compatibility_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/v1/conversion.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/v1/conversion_generated.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/config/common.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/config/file_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/config/http_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/pod/manager.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/pod/mirror_client.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/types/pod_update.go
> UPSTREAM: 15983,16080: Store mirror pod hash in annotation

- pkg/build/builder/cmd/builder.go
- pkg/build/builder/cmd/scmauth/cacert.go
- pkg/build/builder/cmd/scmauth/gitconfig.go
- pkg/build/builder/cmd/scmauth/password.go
- pkg/build/builder/cmd/scmauth/password_test.go
- pkg/build/builder/cmd/scmauth/scmauth.go
- pkg/build/builder/cmd/scmauth/sshkey.go
Dupe of #5322 so @csrwng can review while @jhadvig is offline
> Bug 1270728 - username in the secret don't override the username in the source URL

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go
Fixes https://github.com/openshift/origin/issues/5417
@deads2k
> UPSTREAM: 15799: Fix PodPhase issue caused by backoff

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/dockertools/manager.go
> UPSTREAM: 16532: Allow log tail and log follow to be specified together

- pkg/build/registry/buildconfiginstantiate/rest.go
The change to validate ObjectMeta *before* the custom strategy
resulted in this failure.
[merge]
> Rest validation of binary builds is more aggressive

- assets/bower.json
- hack/install-assets.sh
Fixes https://github.com/openshift/origin/issues/3992
partially fixes test flake with missing bindata
> Update openshift-object-describer to 1.1.1

- api/swagger-spec/oapi-v1.json
- hack/api-description-whitelist.txt
- pkg/api/deep_copy_generated.go
- pkg/api/v1/conversion_generated.go
- pkg/api/v1/deep_copy_generated.go
- pkg/api/v1beta3/conversion_generated.go
- pkg/api/v1beta3/deep_copy_generated.go
- pkg/api/validation/register.go
- pkg/cmd/cli/describe/printer.go
- pkg/image/api/register.go
- pkg/image/api/types.go
- pkg/image/api/v1/register.go
- pkg/image/api/v1/types.go
- pkg/image/api/v1beta3/register.go
- pkg/image/api/v1beta3/types.go
- pkg/image/api/validation/validation.go
- pkg/image/api/validation/validation_test.go
- pkg/image/registry/imagestreamtag/rest.go
- pkg/image/registry/imagestreamtag/rest_test.go
- pkg/image/registry/imagestreamtag/strategy.go
- test/cmd/images.sh
Fixes https://github.com/openshift/origin/issues/5392
Adds listing and updating for `istags`.  You're only allowed to update the `metadata.annotations`.
@smarterclayton @ncdc
> add istag list, update

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/v1beta3/conversion.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/v1beta3/conversion_generated.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/v1beta3/deep_copy_generated.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/v1beta3/register.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/v1beta3/types.go
- pkg/api/serialization_test.go
Fixes https://github.com/openshift/origin/issues/5483
@deads2k @pmorie @smarterclayton @pweil-
> Run serialization tests against upstream types and update v1beta3

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/node/nodecontroller.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/node/nodecontroller_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/registry/pod/strategy.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/registry/pod/strategy_test.go
15900 and 15930
Referenced by #5107
> Cherry-pick graceful deletion fixes into origin

- pkg/authorization/api/types.go
> Add missing kube resources to bootstrap policy

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/proxy/userspace/proxier.go
> UPSTREAM: 16137: Release node port correctly

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/probe/http/http.go
> UPSTREAM: 15733: Disable keepalive on liveness probes

- Godeps/_workspace/src/github.com/fsouza/go-dockerclient/client.go
Fix stdin-only attach so it doesn't wait for stdout/stderr to complete
before returning. If hijackOptions.stdout and hijackOptions.stderr are
nil, don't try to copy from the container's streams to ioutil.Discard,
as that keeps the attach session open as long as the container is
running. Instead, only copy stdout/stderr if they're non-nil.
Fixes #5507
> UPSTREAM(go-dockerclient): 408: fix stdin-only attach

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/validation/validation.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/validation/validation_test.go
> UPSTREAM: 16068: Increase annotation size significantly

- api/swagger-spec/oapi-v1.json
- contrib/completions/bash/oc
- contrib/completions/bash/openshift
- docs/generated/oc_by_example_content.adoc
- pkg/api/deep_copy_generated.go
- pkg/api/v1/conversion_generated.go
- pkg/api/v1/deep_copy_generated.go
- pkg/api/v1beta3/conversion_generated.go
- pkg/api/v1beta3/deep_copy_generated.go
- pkg/build/api/types.go
- pkg/build/api/v1/types.go
- pkg/build/api/v1beta3/types.go
- pkg/build/api/validation/validation.go
- pkg/build/util/util.go
- pkg/cmd/cli/cmd/logs.go
- pkg/cmd/cli/cmd/newbuild.go
- pkg/cmd/util/clientcmd/factory.go
- pkg/deploy/api/types.go
- pkg/deploy/api/v1/types.go
- pkg/deploy/api/v1beta3/types.go
- pkg/deploy/api/validation/validation.go
- pkg/deploy/registry/deploylog/rest.go
- pkg/deploy/registry/deploylog/rest_test.go
- test/end-to-end/core.sh
- test/fixtures/failing-dc.yaml
Fixes https://github.com/openshift/origin/issues/5163
Fixes https://github.com/openshift/origin/issues/5512
@smarterclayton @ironcladlou @deads2k 
Docs: https://github.com/openshift/openshift-docs/pull/879 + https://github.com/openshift/openshift-docs/pull/1112
> logs: View logs from older deployments/builds with --version

- assets/app/views/browse/pod.html
- assets/app/views/directives/logs/_log-viewer.html
> Use pficon-info on pod terminal tab

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/mount/mount_linux.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/glusterfs/glusterfs_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/iscsi/iscsi.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/nfs/nfs.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/nfs/nfs_test.go
Referenced in #5107
@rootfs please review these are intact
[test]
> UPSTREAM: 15236,15562,15555,16032,16033: Storage fixes

- pkg/cmd/cli/cmd/importimage.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1277017
@miminar ptal
> Bug 1277017 - Added checking if spec.DockerImageRepository and spec.Tags are not empty

- assets/app/scripts/directives/logViewer.js
Some browsers flicker when there are bursts of messages (dozens in a second). This seems worst in Safari. Buffer and throttle updates when auto-scrolling to avoid flicker.
Tested in Chrome, Firefox, IE, and Safari.
> Throttle log updates to avoid UI flicker

- test/end-to-end/core.sh
> Temporarily accept 'Forbidden' and 'forbidden' responses

- test/cmd/admin.sh
> test/cmd/admin.sh isn't reentrant

- assets/app/scripts/filters/resources.js
Fixes https://github.com/openshift/origin/issues/5549
Fixes https://github.com/openshift/origin/issues/2815
> Switch to checking for CrashLoopBackOff to show the container looping message

- assets/app/scripts/services/project.js
Fixes #5031 by directing user to error page.
@spadgett @jwforres for review
> Add error clause to service/project.js

- pkg/cmd/cli/cmd/rsync/copytar.go
- test/extended/cli/rsync.go
Fixes deletion of files when --delete is specified and copying from remote to local filesystem. Also ensures that all files (including .hidden files) are deleted in remote directory when copying from local to remote and --delete is specified.
Adds test to validate that files are deleted when copying from container to local filesystem
> bz 1276319 - Fix oc rsync deletion with tar strategy

- hack/install-assets.sh
Based on https://github.com/openshift/origin/pull/5636 and https://github.com/openshift/origin/pull/5572
> Fix travis assets test

- pkg/cmd/cli/cmd/tag.go
- test/cmd/images.sh
Tagging is an overwrite.  Also update output to be cleaner.
Fixes #5526
> oc tag should retry on conflict errors

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go
> UPSTREAM: 16340: Kubelet pod status update is not correctly occuring

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/resource_printer.go
> UPSTREAM: 15997: Prevent NPE in resource printer on HPA

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/proxy/userspace/proxysocket.go
> UPSTREAM: 15745: Endpoint timeouts in the proxy are bad

- assets/app/scripts/services/logLinks.js
> Calculate correct bottom scroll position

- Godeps/_workspace/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go
- Godeps/_workspace/src/k8s.io/kubernetes/cmd/kube-proxy/app/server_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go
Now support older and newer annotations
Referenced from #5107
[test]
> UPSTREAM: 15414: Annotations for kube-proxy move to beta

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/store.go
> UPSTREAM: 16044: Don't shadow error in cache.Store

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go
> UPSTREAM: 15944: DaemonSet controller modifies the wrong fields

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/describe.go
> UPSTREAM: 16025: Fix NPE in describe of HPA

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/resource_helpers.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/daemon/controller_test.go
> UPSTREAM: 16478: Daemon controller shouldn't place pods on not ready nodes

- assets/app/styles/_core.less
- assets/app/styles/_log.less
- assets/app/views/directives/logs/_log-viewer.html
Fix log status text on IE
https://bugzilla.redhat.com/show_bug.cgi?id=1277039
Wrap non breaking strings correctly in FF
https://github.com/openshift/origin/issues/5542
Give spacing on narrow width tables for status
https://github.com/openshift/origin/issues/5621
> Bug and issue fixes (3)

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/helpers.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/validation/validation.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/validation/validation_test.go
Prevents bad scenarios
Referenced from #5107
> UPSTREAM: 15574: Validation on resource quota

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go
> UPSTREAM: 16191: Mirror pods don't show logs

- pkg/cmd/cli/cmd/importimage.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1277021
> Bug 1277021 - Fixed import-image help information.

- docs/generated/oc_by_example_content.adoc
- pkg/cmd/cli/cmd/logs.go
@openshift/team-project-committers `logs oc` yikes
> oc logs long description is wrong

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/validation/name.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/apis/extensions/validation/validation.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/apis/extensions/validation/validation_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/request.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/request_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/registry/generic/etcd/etcd.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/registry/horizontalpodautoscaler/etcd/etcd_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/storage/util.go
> UPSTREAM: 16717: Ensure HPA has valid resource/name/subresource, validate path segments

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go
Reverts https://github.com/openshift/origin/pull/5647
> Revert UPSTREAM: 15944 <7fc8ab5b>: DaemonSet controller modifies the wrong fields

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/storage/etcd/etcd_helper.go
> UPSTREAM: 16384: Large memory allocation with key prefix generation

- Godeps/_workspace/src/github.com/spf13/cobra/bash_completions.go
- contrib/completions/bash/oadm
- contrib/completions/bash/oc
- contrib/completions/bash/openshift
Not bumping spf13/cobra now since it contains wider changes, but this cherry-picked fix is important. Pretty much filename completions is broken.
@openshift/team-project-committers this should get in.
> Fixes filename completion

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/persistentvolume/persistentvolume_claim_binder_controller.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/persistentvolume/persistentvolume_claim_binder_controller_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/persistentvolume/persistentvolume_index_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/persistentvolume/types.go
Resolves https://github.com/openshift/origin/issues/4829
Upstream PR: https://github.com/kubernetes/kubernetes/pull/16432
@pweil-
> UPSTREAM: 16432: Fixed race condition in pv binder

- pkg/generate/app/cmd/newapp.go
- test/cmd/newapp.sh
> New-app: Set context directory and strategy on source repos specified with tilde(~)

- Godeps/Godeps.json
We are on a derivative of 1.1 that is origin focused
@liggitt review please this is 3.1
> Identify the upstream Kube tag more clearly

- Godeps/_workspace/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/services.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/services_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/testclient/actions.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/testclient/fake_services.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/podautoscaler/horizontal_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/podautoscaler/metrics/metrics_client.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/podautoscaler/metrics/metrics_client_test.go
- pkg/cmd/server/kubernetes/master.go
- pkg/dns/serviceaccessor.go
Required for https://bugzilla.redhat.com/show_bug.cgi?id=1277914
> Allow HPA to work with https heapster

- images/base/Dockerfile
Add device-mapper to yum install in base image
[test]
Possible 1.1 candidate
> cAdvisor needs access to dmsetup for devicemapper info

- Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/admission.go
- Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/admission_test.go
https://github.com/kubernetes/kubernetes/pull/17061
Fixes https://github.com/openshift/origin/issues/5827
cc @liggitt please review based on our discussion.
> UPSTREAM: 17061: Unnecessary updates to ResourceQuota when doing UPDATE

- pkg/build/api/validation/validation.go
- pkg/build/api/validation/validation_test.go
- pkg/build/controller/controller.go
- pkg/build/controller/controller_test.go
fix for bug https://bugzilla.redhat.com/show_bug.cgi?id=1279312
> don't update the build phase once it reaches a terminal state

- hack/common.sh
fixes https://github.com/openshift/origin/issues/5363
> reenable static building of hello pod

- assets/app/scripts/directives/podStatusChart.js
Fixes #5793. Thoughts on the color?
Hovering shows a tooltip like for other phases.
Here is one pod pending (gray) and two not ready.
Patternfly color palette: https://www.patternfly.org/styles/color-palette/
/cc @jwforres @liggitt @smarterclayton
> Use a different donut color for pods not ready

- assets/app/views/_overview-deployment.html
Partially addresses #5487.
@jwforres
> Show deployment status on overview when failed or cancelled

- CONTRIBUTING.adoc
Updated a few small items under the Vagrant setup to ensure instructions can be run to completion. 
@spadgett @gabemontero pinging you guys since I had your assistance.
> Update CONTRIBUTING.adoc 

- pkg/template/generator/expressionvalue.go
- pkg/template/generator/expressionvalue_test.go
This allows to generate stronger passwords
> Allow non-alphabetic characters in expression generator

- pkg/api/graph/test/restarting-pod.yaml
- pkg/api/kubegraph/analysis/pod.go
- pkg/api/kubegraph/analysis/pod_test.go
- pkg/cmd/cli/describe/projectstatus.go
- pkg/cmd/cli/describe/projectstatus_test.go
Fixes https://github.com/openshift/origin/issues/5188
If there are three or more restarts on a single container in a pod, you get a warning in status.
@kargakis ptal
> show warning when pod's containers are restarting

- assets/app/views/_templateopt.html
- assets/app/views/create.html
- assets/app/views/create/fromimage.html
- assets/app/views/createProject.html
- assets/app/views/directives/osc-key-values.html
> Prevent autocorrect and autocapitilization for some inputs

- pkg/build/api/types.go
- pkg/build/controller/controller.go
fixes https://github.com/openshift/origin/issues/5692
> add build pod name annotation to builds

- assets/app/scripts/controllers/buildConfig.js
- assets/app/scripts/controllers/deploymentConfig.js
- assets/app/scripts/services/deployments.js
Fixes https://github.com/openshift/origin/issues/5766
> Dont loop over all the builds / deployments for the config when we get an update for one

- pkg/build/controller/controller.go
- pkg/deploy/controller/deployment/controller.go
Fixes https://github.com/openshift/origin/issues/5677
> fix case for events

- hack/push-release.sh
Include new recycler image in push list.
> Push recycler image

- assets/app/scripts/app.js
- assets/app/scripts/controllers/deployment.js
- assets/app/views/browse/_deployment-details.html
- assets/app/views/browse/deployment.html
- assets/app/views/browse/replication-controller.html
- assets/app/views/directives/_status-icon.html
- assets/app/views/directives/logs/_log-viewer.html
- assets/app/views/logs/chromeless-deployment-log.html
Add a Logs tab to the deployment page.
> Add deployment logs to UI

- pkg/build/api/validation/validation.go
- pkg/build/api/validation/validation_test.go
- pkg/build/generator/generator.go
https://bugzilla.redhat.com/show_bug.cgi?id=1279288
> provide validation for build source type

- pkg/gitserver/gitserver.go
Return an error that the git server code understands
Fixes BZ 1252824
> gitserver: return appropriate error when auth fails

- examples/gitserver/gitserver.yaml
> Fix serviceaccount in gitserver example yaml

- contrib/completions/bash/oc
- contrib/completions/bash/openshift
- pkg/cmd/cli/cli_bashcomp_func.go
- pkg/cmd/cli/cmd/wrappers.go
Fixes https://github.com/openshift/origin/issues/4478 and other places where resource names are not being completed.
> Several auto-completion fixes

- pkg/auth/authenticator/password/basicauthpassword/basicauthpassword.go
- pkg/cmd/util/tokencmd/basicauth.go
- pkg/cmd/util/tokencmd/basicauth_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1268126
> Prevent sending username containing colon via basic auth

- Dockerfile
- hack/test-end-to-end-docker.sh
- images/origin/Dockerfile
> Change the image workdir to be /var/lib/origin

- assets/app/scripts/controllers/create/createFromImage.js
- assets/app/scripts/filters/resources.js
- assets/app/scripts/services/applicationGenerator.js
- assets/app/views/browse/_build-details.html
- assets/app/views/browse/build-config.html
- assets/app/views/create/fromimage.html
- assets/test/spec/services/applicationGeneratorSpec.js
Fixes https://github.com/openshift/origin/issues/5817
> Allow setting build config environment variables, show env vars on build config page

- hack/util.sh
- test/extended/cmd.sh
- test/extended/fixtures/test-env-pod.json
fixes https://github.com/openshift/origin/pull/5903
> add tests for variable expansion

- pkg/build/controller/controller.go
- pkg/build/controller/controller_test.go
> Build controller - set build status only if pod creation succeeds

- assets/app/index.html
- assets/app/scripts/controllers/builds.js
- assets/app/scripts/controllers/deployment.js
- assets/app/scripts/controllers/deployments.js
- assets/app/scripts/controllers/images.js
- assets/app/scripts/controllers/pods.js
- assets/app/scripts/controllers/projects.js
- assets/app/scripts/controllers/services.js
- assets/app/scripts/controllers/settings.js
- assets/app/scripts/directives/deleteButton.js
- assets/app/scripts/filters/resources.js
- assets/app/scripts/services/navigate.js
- assets/app/styles/_core.less
- assets/app/views/browse/build-config.html
- assets/app/views/browse/deployment-config.html
- assets/app/views/browse/image.html
- assets/app/views/browse/pod.html
- assets/app/views/browse/service.html
- assets/app/views/directives/delete-button.html
- assets/app/views/modals/delete-resource.html
- assets/app/views/projects.html
- assets/app/views/settings.html
refactor delete button to work with new design
add bindata
remove openshift.log
add delete button to project settings
update settings list delete button
> delete resources on new design

- test/extended/builds/dockerfile.go
- test/extended/builds/gitauth.go
- test/extended/builds/labels.go
- test/extended/builds/sti_env.go
- test/extended/builds/sti_incremental.go
- test/extended/cli/rsync.go
- test/extended/core.sh
- test/extended/extended_test.go
- test/extended/fixtures/job-controller.yaml
- test/extended/images/helper.go
- test/extended/images/mysql_replica.go
- test/extended/images/s2i_perl.go
- test/extended/images/s2i_php.go
- test/extended/images/s2i_python.go
- test/extended/images/s2i_ruby.go
- test/extended/images/sample_repos.go
- test/extended/job/controller.go
- test/extended/util/framework.go
- test/extended/util/image_helpers.go
@pmorie @smarterclayton built on top of https://github.com/openshift/origin/pull/5632
it sistematically replace `Func` with `Fn`.
Fixes https://github.com/openshift/origin/issues/5538
> To replace Func postfixed identifier with Fn postfixed in e2e extended

- hack/push-release.sh
Pushes gitserver regularly along with other openshift images
> Add openshift/origin-gitserver to push-release.sh

- Godeps/_workspace/src/k8s.io/kubernetes/cmd/kubelet/app/server.go
- pkg/cmd/server/kubernetes/node_config.go
Fixes bug 1275518
https://bugzilla.redhat.com/show_bug.cgi?id=1275518
> Add a config option to set idle time out for streaming connections.

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go
Fixes https://github.com/openshift/origin/issues/5640
> UPSTREAM: 16945: kubelet: Fallback to api server for pod status

- pkg/dockerregistry/client.go
- pkg/image/api/helper.go
- pkg/image/api/helper_test.go
> Use constants for defaults instead of strings

- test/extended/images/mysql_replica.go
- test/extended/util/db_image_helpers.go
Wait until the user has the rights to create templates in the project.
Also make the tests somewhat easier to debug by better errors and not
using random strings to identify tables.
> Unflake MySQL extended test

- pkg/api/graph/test/bc-missing-output.yaml
- pkg/build/graph/analysis/bc_test.go
- pkg/build/graph/edges.go
fixes https://github.com/openshift/origin/issues/5945
@bparees @csrwng PTAL
> prevent go panic when output not specified for build config

- test/extended/builds/start_build.go
Fixes: #5929 
@bparees fixes the issue and add one more test to support #5734
> Fix extended test for start-build

- pkg/cmd/cli/secrets/known_secret_types.go
- test/extended/cmd.sh
- test/extended/fixtures/image-pull-secrets/dc-with-new-pull-secret.yaml
- test/extended/fixtures/image-pull-secrets/dc-with-old-pull-secret.yaml
- test/extended/fixtures/image-pull-secrets/pod-with-new-pull-secret.yaml
- test/extended/fixtures/image-pull-secrets/pod-with-no-pull-secret.yaml
- test/extended/fixtures/image-pull-secrets/pod-with-old-pull-secret.yaml
Fixes https://github.com/openshift/origin/issues/5517
This makes it possible to easily create a docker cfg secret in the new format.
> accept new dockercfg format

- test/integration/buildcontroller_test.go
No longer throws an error if a build update happens and the status is still New.
Fixes Issue #5937
> Fix build controller integration test flake

- pkg/build/api/validation/validation.go
- pkg/build/api/validation/validation_test.go
Fixes: https://github.com/openshift/origin/issues/5944
> The git:// protocol with proxy is not allowed

- test/extended/images/mysql_replica.go
- test/extended/images/postgresql_replica.go
- test/extended/util/db_image_helpers.go
This will fix (partially) #5841
@bparees @rhcarvalho fyi
> Add PostgreSQL replication tests

- hack/util.sh
- test/cmd/builds.sh
fixes https://github.com/openshift/origin/issues/5989
@deads2k fyi, @gabemontero this might be why you were still seeing flakiness also.
> bump the wait for images timeout

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/clientcmd/loader.go
- pkg/cmd/cli/config/loader.go
Fixes https://github.com/openshift/origin/issues/5335
> Use correct home directory on Windows

- pkg/cmd/server/bootstrappolicy/constants.go
- pkg/cmd/server/bootstrappolicy/policy.go
- test/end-to-end/core.sh
Adds a `system:image-pusher` specifically for the purpose.
@liggitt Who would you like to assign?
> add image-pusher role

- pkg/cmd/cli/cli.go
> Exposes the --token flag in login command help

- test/cmd/export.sh
/cc @deads2k 
@derekwaynecarr @smarterclayton   PTAL -- please review and ensure that the expectations (success, failure, with/without text) are correct to what you expected from the tests previously.
> refactored test/cmd/export to use wrapper functions

- test/cmd/secrets.sh
> refactored test/cmd/secrets to use helper methods

- test/cmd/deployments.sh
/cc @deads2k 
@ironcladlou  @pweil-  PTAL -- please review and ensure that the expectations (success, failure, with/without text) are correct to what you expected from the tests previously.
> refactored test/cmd/deployments to use wrapper methods

- test/cmd/help.sh
/cc @deads2k 
@smarterclayton @liggitt PTAL
> refactored test/cmd/help to use wrapper functions

- test/cmd/policy.sh
> refactored test/cmd/policy to use wrapper methods

- test/cmd/templates.sh
> refactored test/cmd/templates to use wrapper methods

- test/integration/dockerregistryclient_test.go
> Skip registry client test if registry is not reachable

- assets/app/scripts/services/builds.js
- assets/app/views/_alerts.html
Based on the https://github.com/openshift/origin/issues/5690 issue.
> Link in the alert for the newly triggered build

- test/cmd/newapp.sh
/cc @deads2k
@bparees @csrwng PTAL -- please review and ensure that the expectations (success, failure, with/without text) are correct to what you expected from the tests previously.
Changes other than simple addition of wrappers are commented below
> refactored test/cmd/newapp to use wrapper functions

- origin.spec
This is in preparation for building this package in Fedora.
> Make building clients for other architectures optional

- test/cmd/basicresources.sh
/cc @liggitt @deads2k @smarterclayton 
My search-fu did not help me figure out who originally wrote these lines.
> refactored test/cmd/basicresources to use wrapper functions

- assets/app/scripts/filters/resources.js
- assets/app/views/_triggers.html
- assets/app/views/browse/_build-details.html
- assets/app/views/browse/_deployment-details.html
- assets/app/views/browse/build-config.html
- assets/app/views/browse/deployment-config.html
- assets/app/views/browse/route.html
- assets/app/views/browse/routes.html
- assets/app/views/builds.html
- assets/app/views/deployments.html
- assets/app/views/images.html
- assets/app/views/pods.html
- assets/app/views/project.html
- assets/app/views/services.html
- also a minor update to projectOverviewURL, allow for string or object
@jwforres @spadgett this is pt1 of breaking down my [project service PR]([breaking down this PR](https://github.com/openshift/origin/pull/5953)).
> Update templates to use navigateResourceURL filter where appropriate

- docs/generated/oc_by_example_content.adoc
- pkg/cmd/cli/secrets/new.go
Adds an example about how to create a `.docker/config.json` secret.
@deads2k ptal
> Adds .docker/config.json secret example

- pkg/generate/app/componentresolvers.go
> Remove type conversion

- pkg/cmd/server/crypto/crypto.go
Fixes #6055
Decimal can always decode as hex, so when we make this switch, we'll just jump several serial numbers forward.
> Output uppercase, hex, 2-character padded serial.txt

- examples/project-quota/README.md
* FRONTEND_RESOURCES_LIMITS_CPU - the amount of cpu for your frontend containers
* FRONTEND_RESOURCES_LIMITS_MEMORY - the amount of memory for your frontend containers
> update the readme 

- examples/db-templates/README.md
> Add README.md to examples/db-templates

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/resource_printer_test.go
Fixes https://github.com/openshift/origin/issues/6137
Upstream PR: https://github.com/kubernetes/kubernetes/pull/18000
> Fix TestTranslateTimestamp flake

- assets/app/views/_templateopt.html
> Add aria-describedby attributes to template parameter inputs

- assets/app/scripts/directives/podStatusChart.js
- assets/app/views/_pod-status-chart.html
> Fix sr-only text for pod status chart

- assets/app/scripts/controllers/overview.js
- assets/app/views/project.html
Fixes #5091
/cc @jwforres @stefwalter
> Hide old deployments in the topology view

- assets/app/scripts/filters/resources.js
- assets/app/scripts/services/navigate.js
- assets/app/views/browse/route.html
https://bugzilla.redhat.com/show_bug.cgi?id=1284366
> Support deleting routes in web console

- pkg/cmd/cli/cmd/rsync/copyrsync.go
- pkg/cmd/cli/cmd/rsync/copyrsync_test.go
- pkg/cmd/cli/cmd/rsync/rsync.go
> oc rsync: pass-thru global command line options

- pkg/cmd/cli/cmd/newapp.go
- test/cmd/builds.sh
- test/cmd/newapp.sh
> Do not print new-build steps for alternative output formats

- assets/app/styles/_components.less
- assets/app/styles/_core.less
- assets/app/views/directives/osc-key-values.html
Border width will be expanded when long value added in Environment Variables for project
> Fix for Bug 1285647

- Godeps/_workspace/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
Lengthens PV sync period to 10m from 10s.  
@liggitt @pweil-
> Upstream: 16728: lengthened pv controller sync period to 10m

- pkg/cmd/admin/router/router.go
@smarterclayton @pweil-  PTAL. Thx
FYI - update probe change related to the healthz port PR (https://github.com/openshift/origin/pull/6030).
> Update probe to use healthz port

- assets/app/views/pods.html
/cc @jwforres @benjaminapetersen
> Fix incorrect status icon on pods page

- test/cmd/admin.sh
/cc @deads2k PTAL, I think this are mostly your tests.
> refactored test/cmd/admin to use wrapper functions

- test/extended/fixtures/test-build-app/Dockerfile
fixes https://github.com/openshift/origin/issues/6216
> fix ruby-22 scl enablement

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/common.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/factory/factory.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/ovs/plugin.go
- Godeps/_workspace/src/k8s.io/kubernetes/cmd/kubelet/app/server.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/config/config.go
- pkg/cmd/server/origin/run_components.go
- pkg/cmd/server/start/start_node.go
Now kubelet will block on network plugin intialization for the node SDN setup to complete.
> Don't use KubeletConfig 'StartUpdates' channel for blocking kubelet

- assets/app/scripts/directives/buildTrendsChart.js
https://bugzilla.redhat.com/show_bug.cgi?id=1289446
> Unload filtered groups from build config chart

- HACKING.md
> HACKING.md: clarify meaning and provide proper usage of OUTPUT_COVERAGE variable

- assets/app/scripts/directives/deleteButton.js
- assets/app/scripts/filters/resources.js
- assets/app/scripts/services/navigate.js
- assets/app/styles/_core.less
- assets/app/views/browse/build.html
- assets/app/views/browse/deployment.html
- assets/app/views/browse/replication-controller.html
- assets/app/views/directives/delete-button.html
- assets/app/views/modals/delete-resource.html
- assets/test/integration/rest_api/project.js
Allow deleting individual builds, deployments, and replication controllers from the UI.
> Web console support for deleting individual builds and deployments

- images/router/haproxy/conf/error-page-503.html
- images/router/haproxy/conf/error-page-503.http
- images/router/haproxy/conf/haproxy-config.template
- test/integration/router_test.go
Bugz: https://bugzilla.redhat.com/show_bug.cgi?id=1283952
@rajatchopra  PTAL   thx
> Fix for bugz 1283952 and add a test.

- assets/test/integration/e2e.js
My attempts to run tests locally have all failed so I haven't been able to ensure this works.
> Fix e2e login tests for OSE variants

- test/end-to-end/core.sh
Fixes https://github.com/openshift/origin/issues/6262
@ironcladlou
> Fix deployment e2e flake

- examples/jenkins/README.md
@bparees - the tweaks to the tutorial to introduce the plugin related changes, point to the plugin, etc.
> update jenkins tutorial for using plugin

- origin.spec
- Remove no longer needed defattr
- Remove negative comments
- Add %license where needed
- Fix dir ownership for sdn
- Add better description
> Packaging specfile clean up

- HACKING.md
- README.md
- hack/build-in-docker.sh
- hack/test-cmd.sh
- hack/test-integration.sh
- test/end-to-end/core.sh
> refactored scripts to use hack/text, refactored test-cmd args, fixed end-to-end/core error output

- pkg/cmd/cli/cli.go
- pkg/cmd/cli/cmd/request_project.go
Don't assume they know about it.
[test]
> Give user suggestion about new-app on new-project

- test/extended/util/db_image_helpers.go
This is just a canary to fix the mysql replication extended tests
> WIP: Fix the mysql replica extended test

- test/extended/fixtures/forcepull-setup.json
Fixes https://github.com/openshift/origin/issues/6299
@bparees PTAL
> fix forcepull setup build config

- pkg/cmd/server/start/start_master.go
Fixes #6272 @sdodson @abutcher
> Controllers should always go async on start

- pkg/dockerregistry/client.go
- pkg/dockerregistry/client_test.go
Trello card:  https://trello.com/c/Obmso4qn/510-allow-image-importing-to-work-with-proxy
Looking for review @soltysh
> Allow image importing to work with proxy

- examples/storage-examples/gluster-examples/nginx_gluster_plugin/README.md
- examples/storage-examples/gluster-examples/nginx_gluster_plugin/gluster-service.json
> doc: create glusterfs service to persist endpoints

- images/router/haproxy/conf/haproxy-config.template
o Make Forwarded header value rfc7239 compliant.
o Set X-Forwarded-Proto for http (if insecure edge terminated routes
are allowed).
@rajatchopra PTAL Thx
> Fix for bugz https://bugzilla.redhat.com/show_bug.cgi?id=1290643

- assets/app/views/browse/route.html
Fixes #6342
https://bugzilla.redhat.com/show_bug.cgi?id=1291559
> Fix service link on route page

- pkg/cmd/cli/cmd/cancelbuild.go
> Output more helpful cancel message

- pkg/oauth/server/osinserver/tokengen.go
> Avoid generating tokens with leading dashes

- pkg/generate/app/cmd/newapp_test.go
- pkg/generate/app/sourcelookup.go
- test/cmd/newapp.sh
Fixes #6345.
Regression introduced in 891fc216e97b9b74cc7f2ba4a568022b1e92a4e4.
> Fix regression: new-app with custom Git ref

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/get.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/get_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/resource/builder.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/resource/builder_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/resource_printer.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1287553
> UPSTREAM: 18165: fixes get --show-all

- assets/app/scripts/filters/util.js
Fixes https://github.com/openshift/origin/issues/6244
> Fix github link when contextDir is set but not git ref

- test/cmd/basicresources.sh
- test/cmd/templates.sh
> Wait for user permissions in test-cmd.sh

- test/integration/dockerregistryclient_test.go
Image may get updated between tag->digest and digest->manifest
resolutions. Retry the operation if such an event occurs.
And skip expired certificate error.
Resolves flake #6232
> Retry get image on not found error

- assets/app/styles/_core.less
> Increase specificity of CSS .yaml-mode .ace-numeric style

- pkg/api/graph/graph.go
@deads2k PTAL
Closes https://github.com/openshift/origin/issues/6394
> graphapi: Remove dead code and add godoc

- examples/project-quota/README.md
@derekwaynecarr @deads2k  PTAL
> examples: Update resource quota README

- docs/generated/oc_by_example_content.adoc
- pkg/cmd/cli/cmd/wrappers.go
Fixes https://github.com/openshift/origin/issues/5325
@deads2k PTAL
> oc: Add more doc and examples in oc get

- assets/app/scripts/directives/buildTrendsChart.js
https://bugzilla.redhat.com/show_bug.cgi?id=1289843
@jwforres We can still open an upstream bug, but this is basically what we were doing before and works around the problem reliably in my testing.
> Wait until animation finishes to call chart.flush()

- pkg/cmd/cli/describe/describer.go
forgotten in https://github.com/openshift/origin/pull/5976
> describe DockerBuildStrategy.DockerfilePath

- assets/app/views/_alerts.html
Adds a close button for each alert.
See also #6187. (I think the changes here will work with that PR.)
> Make web console alerts dismissable

- assets/app/scripts/controllers/modals/confirmScale.js
- assets/app/scripts/controllers/modals/deleteModal.js
- assets/app/scripts/controllers/modals/editModal.js
- assets/app/scripts/controllers/projects.js
- assets/app/scripts/controllers/settings.js
- assets/app/scripts/directives/deleteLink.js
- assets/app/scripts/directives/editLink.js
- assets/app/scripts/directives/overviewDeployment.js
- assets/app/views/create.html
- assets/app/views/project.html
> Use angular-bootstrap uib-prefixed components

- assets/app/scripts/controllers/overview.js
> Show scalable deployments on web console overview even if not latest

- pkg/cmd/experimental/diagnostics/client.go
- pkg/cmd/experimental/diagnostics/cluster.go
Attempting to improve https://github.com/openshift/origin/issues/5753
> diagnostics: improve wording of notes

- assets/app/views/browse/image.html
> Don't allow clock icon to wrap in image tag table

- test/integration/deploy_trigger_test.go
Updates the deploy tests to use an actual master. This one is slightly more involved.
@liggitt @kargakis
> fix deploy test to use actual master

- assets/app/views/_overview-deployment.html
https://bugzilla.redhat.com/show_bug.cgi?id=1293801
@jwforres
> Fix scale up button tooltip

- assets/bower.json
https://bugzilla.redhat.com/show_bug.cgi?id=1293780
Fixes #6491
@jwforres @stefwalter
> Bump kubernetes-topology-graph to 0.0.21

- pkg/cmd/server/origin/handlers.go
- pkg/cmd/server/origin/master.go
- test/integration/api_paths_test.go
> fixed readiness endpoint route listing

- pkg/generate/app/cmd/describe.go
- pkg/generate/app/cmd/newapp.go
- pkg/generate/app/sourcelookup.go
- test/cmd/newapp.sh
https://bugzilla.redhat.com/show_bug.cgi?id=1287999
> handle missing dockerfile with docker strategy

- assets/app/scripts/controllers/create/nextSteps.js
- assets/app/views/create/nextSteps.html
> Fix breadcrumb on next steps page

- contrib/completions/bash/oc
- contrib/completions/bash/openshift
- pkg/cmd/cli/cmd/importimage.go
fix https://github.com/openshift/origin/issues/6227
> add option --insecure for oc import-image

- test/extended/core.sh
fixes https://github.com/openshift/origin/issues/6553
@bparees @gabemontero
> update extended test to point to correct version tool

- pkg/cmd/experimental/diagnostics/diagnostics.go
Fixes https://github.com/openshift/origin/issues/5984
It looks like
```
Diagnostics may be individually run with --diagnostics. The available
diagnostic names are:
AnalyzeLogs,ClusterRegistry,ClusterRoleBindings,ClusterRoles,ClusterRouter,ConfigContexts,MasterConfigCheck,MasterNode,NodeConfigCheck,NodeDefinitions,UnitStatus
```
Would I like the list to be more aesthetically pleasing? Sure. Do I really wanna implement that? No. If there's a nice text-formatting module somewhere, great...
> diagnostics: list diagnostic names in long desc

- pkg/auth/authenticator/request/x509request/x509_test.go
- pkg/build/registry/build/strategy.go
Small clean up of places where we converted time.Duration into time.Duration.
> Remove unnecessary type conversions

- test/extended/util/test.go
Some kube e2e tests (e.g. the one for NodePort services) use replication
controllers to launch containers that require anyuid.  To enable this,
the test project service accounts need to be added to the anyuid scc.
> Fix replication controller usage in kube e2e tests

- pkg/generate/source/detector.go
> Fix detection of Python projects

- pkg/generate/git/git_test.go
fixes https://github.com/openshift/origin/issues/6455
@liggitt @rhcarvalho PTAL
@bparees FYI (and of course TAL if you like :-) )
> deal with RawPath field added to url.URL in go1.5

- assets/app/scripts/filters/util.js
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1285690
> Fix deployment CLI ops link and make all doc links https

- hack/test-end-to-end-docker.sh
- hack/util.sh
@bparees This truncates large logs to 20M.
> made large file behavior smarter

- hack/install-assets.sh
This commit updates the java console and fixes the following reported bugs:
https://bugzilla.redhat.com/show_bug.cgi?id=1287094
https://bugzilla.redhat.com/show_bug.cgi?id=1286949
https://bugzilla.redhat.com/show_bug.cgi?id=1285763
It also contains a few misc tweaks and brings in an updated version of patternfly
@jwforres FYI...
> Update java console to 1.0.38

- assets/app/scripts/filters/util.js
> Fix broken switch in usageWithUnits filter

- pkg/cmd/server/bootstrappolicy/infra_sa_policy.go
- pkg/cmd/server/bootstrappolicy/policy_test.go
- test/fixtures/bootstrappolicy/bootstrap_cluster_role_bindings.yaml
- test/fixtures/bootstrappolicy/bootstrap_cluster_roles.yaml
- test/fixtures/bootstrappolicy/bootstrap_openshift_roles.yaml
- test/fixtures/bootstrappolicy/bootstrap_service_account_project_role_bindings.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1289503
May be related to #6293
> Fix HPA default policy

- images/simple-authenticated-registry/Dockerfile
- images/simple-authenticated-registry/README.md
- images/simple-authenticated-registry/config.yml
- images/simple-authenticated-registry/htpasswd
- pkg/cmd/dockerregistry/dockerregistry.go
Enable htpasswd and token authenticators in our Docker binary.
[merge]
> Add a new image to be used for testing

- pkg/api/latest/latest.go
> The default codec should be v1.Codec, not v1beta3

- test/extended/fixtures/test-build-hello-openshift.yaml
> Fix test fixture fields

- pkg/cmd/server/origin/ensure.go
> Retry adding roles to service accounts in conflict cases

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/netutils/subnet_allocator.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/netutils/subnet_allocator_test.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/ovs/controller.go
Pulls in fixes for:
https://github.com/openshift/openshift-sdn/pull/244
https://github.com/openshift/openshift-sdn/pull/227
> openshift-sdn update

- hack/test-integration.sh
TIMES=100 hack/test-integration.sh TestFooBar
[merge]
> Add TIMES=N to rerun integration tests for flakes

- test/extended/images/postgresql_replica.go
This should get merged after RHEL images are fixed and will be ready for testing.
@bparees fyi
> Enable PostgreSQL replication tests for RHEL images

- pkg/cmd/server/start/start_node.go
Patch from Dan Williams
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1294061
@eparis @smarterclayton
> Fix up net.bridge.bridge-nf-call-iptables after kubernetes breaks it

- assets/bower.json
Fixes #6690
@jwforres @liggitt
> Lock ace-builds version to 1.2.2

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/AdRoll/goamz/aws/aws.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/aws/regions.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/aws/sign.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/multi.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/multi_test.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/responses_test.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/s3.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/s3_test.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/s3i_test.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/s3t_test.go
- Godeps/_workspace/src/github.com/AdRoll/goamz/s3/s3test/server.go
This updates s3 and aws storage drivers.
> Registry rebase follow-up

- pkg/cmd/cli/cmd/newapp.go
fixes https://github.com/openshift/origin/issues/6696
> clarify build-started message based on buildconfig triggers

- hack/lib/log.sh
- hack/test-cmd.sh
- hack/test-end-to-end-docker.sh
- hack/test-end-to-end.sh
- hack/test-integration.sh
- hack/test-tools.sh
- test/extended/cmd.sh
- test/extended/core.sh
- test/extended/ldap_groups.sh
- test/extended/networking.sh
@deads2k @liggitt @smarterclayton FYI
> added system logging utility

- origin.spec
This also sorts the linked files, so we don't miss another one.
> put openshift-f5-router in origin.spec

- docs/generated/oadm_by_example_content.adoc
- pkg/cmd/admin/prune/images.go
> Described oadm prune images command

- docs/debugging-openshift.md
I've stumbled upon this problem earlier today and I see I was not the only one (https://github.com/openshift/origin/issues/5925#issuecomment-158137471), so I'm adding this to the trouble shooting guide.
@miminar ptal
@ncdc fyi
> Updated troubleshooting guide with information about insecure-registry

- pkg/cmd/cli/cmd/newapp.go
- pkg/generate/app/cmd/describe.go
- pkg/generate/app/cmd/newapp.go
- pkg/generate/app/componentmatch.go
- pkg/generate/app/componentresolvers.go
- pkg/generate/app/dockerimagelookup.go
- pkg/generate/app/errors.go
- pkg/generate/app/imagestreamlookup.go
- pkg/generate/app/pipeline.go
fixes https://github.com/openshift/origin/issues/6671
> fail immediately on multimatch error

- contrib/completions/bash/openshift
- hack/test-cmd.sh
- pkg/cmd/experimental/diagnostics/client.go
- pkg/cmd/experimental/diagnostics/cluster.go
- pkg/cmd/experimental/diagnostics/diagnostics.go
- pkg/cmd/experimental/diagnostics/options/diagnostics.go
- pkg/cmd/experimental/diagnostics/options/flaginfo.go
- pkg/cmd/experimental/diagnostics/pod.go
- pkg/cmd/openshift/openshift.go
- pkg/diagnostics/client/config_contexts.go
- pkg/diagnostics/client/config_loading.go
- pkg/diagnostics/client/run_diagnostics_pod.go
- pkg/diagnostics/cluster/registry.go
- pkg/diagnostics/pod/auth.go
- pkg/diagnostics/pod/dns.go
- pkg/diagnostics/pod/util.go
- pkg/diagnostics/systemd/systemd.go
- test/cmd/diagnostics.sh
- test/end-to-end/core.sh
https://trello.com/c/c3Amaijl/88-5-diagnostics-container
checks dns search domains
add service account auth check
introduce registry auth check
introduce image template flags, use "deployer" as diagnostic pod
> diagnostics: add diagnostics from pod perspective

- pkg/generate/app/cmd/describe.go
Also reference that containers can access the service via DNS
> Add annotation information when describing new-app results

- docs/generated/oadm_by_example_content.adoc
- pkg/cmd/admin/prune/deployments.go
> oadm: bump prune deployments description/examples

- contrib/completions/bash/oadm
- contrib/completions/bash/openshift
- docs/generated/oadm_by_example_content.adoc
- pkg/cmd/admin/prune/prune.go
> oadm: should have prune groups cmd

- test/extended/all.sh
- test/extended/cmd.sh
- test/extended/core.sh
- test/extended/ldap_groups.sh
@mfojtik simple, naive, early exit-ing, but helpful.
> add extended all.sh to allow [extended:all] to run all buckets

- docs/generated/oadm_by_example_content.adoc
- pkg/cmd/admin/prune/builds.go
Likewise #6716 and #6729 but for builds.
PTAL @kargakis
> Describe oadm prune builds command

- assets/app/scripts/directives/podStatusChart.js
> Suppress tooltip when hovering over cut-line at top of pod donut

- pkg/cmd/admin/registry/registry.go
This pull request should fix #6482.
@pweil- @kargakis please review.
> Set REGISTRY_HTTP_ADDR to first specified port

- pkg/cmd/admin/registry/registry.go
This pull request should fix #6484. First commit is part of my previous PR #6653.
@miminar, @kargakis please review.
> Issue 6484

- .gitignore
> ignore ctags file

- assets/app/index.html
- assets/app/scripts/controllers/settings.js
- assets/app/scripts/directives/quotaUsageChart.js
- assets/app/scripts/filters/resources.js
- assets/app/scripts/filters/util.js
- assets/app/views/_pod-template.html
- assets/app/views/_quota-usage-chart.html
- assets/app/views/settings.html
https://trello.com/c/bafBgcGY
Project Settings:
Pod Template:
/cc @jwforres @derekwaynecarr @smarterclayton 
Fixes #6649
Fixes #6717
Fixes #6739
Fixes #6740
> Improve display of quota and limits in web console

- pkg/cmd/server/bootstrappolicy/constants.go
- pkg/cmd/server/bootstrappolicy/policy.go
- pkg/cmd/server/origin/master_config.go
- test/cmd/basicresources.sh
- test/fixtures/bootstrappolicy/bootstrap_cluster_role_bindings.yaml
Fixes https://github.com/openshift/origin/issues/6567
Introduces a `system:humans` group.
@csrwng ptal
> restrict project requests to human users: ones with oauth tokens

- hack/test-cmd.sh
> refactored test-cmd core to use os::cmd functions

- hack/util.sh
fixes https://github.com/openshift/origin/issues/6802
> guard openshift resource dump

- pkg/cmd/cli/describe/describer.go
- pkg/cmd/cli/describe/describer_test.go
Fixes #2941 @pweil- @liggitt @kargakis please review.
> Add endpoints to oc describe route

- pkg/api/graph/test/invalid-route.yaml
- pkg/cmd/cli/describe/projectstatus.go
- pkg/route/graph/analysis/analysis.go
- pkg/route/graph/analysis/analysis_test.go
oc status changes for https://github.com/openshift/origin/pull/6037
@ramr @liggitt @deads2k @jwforres @smarterclayton
> status: Report path-based passthrough terminated routes

- test/extended/images/mongodb_ephemeral.go
- test/extended/images/mysql_replica.go
- test/extended/images/postgresql_replica.go
- test/extended/util/db/common.go
- test/extended/util/db/mongodb.go
- test/extended/util/db/mysql.go
- test/extended/util/db/postgresql.go
- test/extended/util/db_image_helpers.go
Also refactored mysql/postgresql a bit by extracting structs and similar pieces of code.
PTAL @rhcarvalho @mnagy @bparees 
Fix #5969
> Add extended test for MongoDB

- test/extended/images/mysql_replica.go
As agreed with @bparees, temporarily disable some features of extended MySQL replication tests so tests pass and @php-coder can get his #6197 merged.
> Temporarily disable replication slave checking

- docs/generated/oc_by_example_content.adoc
- pkg/cmd/cli/cmd/newbuild.go
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1301870
> fix sample usage

- pkg/build/api/types.go
- pkg/build/api/v1/types.go
- pkg/build/api/v1beta3/types.go
- pkg/build/api/validation/validation.go
- pkg/build/registry/buildlog/rest.go
- pkg/build/registry/buildlog/rest_test.go
- pkg/build/registry/test/build.go
- pkg/build/util/util.go
- pkg/client/testclient/fake_buildlogs.go
- pkg/client/testclient/fake_deploymentlogs.go
- pkg/cmd/cli/cmd/logs.go
- pkg/cmd/util/clientcmd/factory.go
- pkg/deploy/api/types.go
- pkg/deploy/api/v1/types.go
- pkg/deploy/api/v1beta3/types.go
- pkg/deploy/api/validation/validation.go
- pkg/deploy/registry/deploylog/rest.go
- pkg/deploy/registry/deploylog/rest_test.go
- test/end-to-end/core.sh
Fixes https://github.com/openshift/origin/issues/5583
@bparees @ironcladlou @deads2k @smarterclayton
> oc: support `logs -p` for builds and deployments

- assets/app/scripts/controllers/deploymentConfig.js
- assets/app/scripts/directives/resources.js
- assets/app/scripts/directives/truncate.js
- assets/app/scripts/filters/util.js
- assets/app/styles/_core.less
- assets/app/views/browse/_build-details.html
- assets/app/views/browse/build-config.html
- assets/app/views/browse/build.html
- assets/app/views/browse/deployment-config.html
- assets/app/views/browse/deployment.html
- assets/app/views/browse/pod.html
- assets/app/views/directives/environment.html
- assets/app/views/directives/truncate-long-text.html
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1278579
> Add environment to the relevant browse pages

- pkg/api/serialization_test.go
Partially addresses https://github.com/openshift/origin/issues/5529
@deads2k @liggitt
> api: enable serialization tests for Pod{Exec,Attach}Options

- assets/Gruntfile.js
- assets/app/scripts/controllers/settings.js
- assets/app/scripts/services/projects.js
- assets/app/views/_settings-general-info.html
- assets/app/views/settings.html
- assets/test/.jshintrc
- assets/test/integration/e2e.js
- assets/test/integration/helpers.js
- assets/test/integration/rest_api/project.js
Adds a drop down menu to top left of settings page (similar to what we have elsewhere) with edit & delete options.  Edit will display an inline form allowing user to update the project's `displayName` and `description`.
@jwforres @spadgett @sg00dwin for review!
> Edit project display name & description via settings page

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/api/scripts.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/docker/docker.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/docker/util.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/scm/file/download.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/scripts/download.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/scripts/install.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/tar/tar.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/util/injection.go
> Update s2i to include fix for #397

- hack/move-upstream.sh
@smarterclayton I needed these tweaks and those steps to be able to build what I needed.
> tweaks and explanation to use move-upstream.sh for rebase

- assets/app/scripts/services/data.js
update kindToResource impl to match upstream
@liggitt - PTAL - figured I'd try my hand at it since I haven't touched any js in a while  
fixes https://github.com/openshift/origin/issues/6851
cc @jwforres
> update kindToResource to match upstream

- hack/install-assets.sh
Should address these bugzilla issues, a couple needed more work:
https://bugzilla.redhat.com/show_bug.cgi?id=1286949
https://bugzilla.redhat.com/show_bug.cgi?id=1285763
https://bugzilla.redhat.com/show_bug.cgi?id=1299751
@jwforress FYI...
> Update java console to 1.0.40

- pkg/build/api/validation/validation.go
- pkg/generate/app/sourcelookup.go
> Bug 1303012 - Validate the build secret name in new-build

- docs/generated/oc_by_example_content.adoc
- pkg/cmd/cli/secrets/dockercfg.go
> Update help for docker/config.json secrets

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/master/master.go
- pkg/cmd/server/bootstrappolicy/infra_sa_policy.go
- pkg/cmd/server/bootstrappolicy/policy.go
- pkg/cmd/server/kubernetes/master.go
- pkg/cmd/server/start/start_master.go
- test/extended/core.sh
- test/fixtures/bootstrappolicy/bootstrap_cluster_roles.yaml
Fixing https://github.com/openshift/origin/pull/6772
For some reason my other PR got screwed up and has 0 commits
TODO: 
1.  ~~rebase~~
1.  ~~pick up var from https://github.com/openshift/origin/pull/6772#discussion_r50994762~~
> enable daemonset

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/docker/util.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/scripts/install.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/tar/tar.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/util/fs.go
@bparees FYI
Fixes: https://github.com/openshift/origin/issues/6910
> bump(github.com/openshift/source-to-image): 91769895109ea8f193f41bc0e2eb6ba83b30a894

- pkg/project/admission/lifecycle/admission.go
Added accidentally during rebase
[merge]
> Remove debug logging from project admission

- assets/app/views/browse/_build-details.html
- assets/app/views/browse/build-config.html
- assets/app/views/builds.html
Fixes https://github.com/openshift/origin/issues/6616
> Fix display when build has not started, no startTimestamp exists

- assets/app/views/create/fromimage.html
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1275902
> Bug 1275902 - fix help text for name field on create from image

- assets/app/views/browse/build-config.html
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1254431
> Bug 1254431 - fix display of ICTs to handle the from subobject

- assets/app/views/directives/header/_navbar-utility.html
Fixes https://github.com/openshift/origin/issues/6964
> Fix both header dropdowns staying open

- HACKING.md
Spreading the knowledge from https://github.com/openshift/origin/pull/6670/files#r51588259
> Document how to run test/cmd tests in development

- assets/app/styles/_core.less
> Update web console tab style

- assets/app/index.html
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1298750
> Bug 1298750 - Force IE document mode to be edge

- pkg/cmd/server/origin/auth.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1302946
Previously, we were updating the secrets for the internal OAuth clients on every launch. This causes problems with HA environments. This PR preserves existing client secrets and just updates the challenge and redirect URI settings on launch.
> Preserve existing oauth client secrets on startup

- Godeps/_workspace/src/github.com/ugorji/go/codec/fast-path.generated.go
- Godeps/_workspace/src/github.com/ugorji/go/codec/fast-path.go.tmpl
- test/cmd/basicresources.sh
fixes #6936
WIll open upstream issue to bump ugorji, but that would make us out of sync with etcd again.
Upstream might not see this if they are using fully generated codecs.
> Fix ugorji empty list decoding

- assets/app/views/create/nextSteps.html
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1291535
> Bug 1291535 - alignment of oc commands in next steps page is wrong

- pkg/cmd/server/origin/master.go
- pkg/dockerregistry/server/repositorymiddleware.go
- pkg/image/importer/credentials.go
- pkg/image/importer/importer.go
- pkg/image/importer/importer_test.go
- pkg/image/registry/imagestreamimport/rest.go
- test/integration/imageimporter_test.go
Avoid loading secrets until a caller requests it.
> Only load secrets during import if needed

- test/extended/core.sh
> Only pass --ginkgo.skip when focus is absent

- pkg/deploy/api/helpers.go
- pkg/deploy/registry/deploylog/rest.go
- pkg/deploy/registry/deploylog/rest_test.go
- test/end-to-end/core.sh
Fixes https://github.com/openshift/origin/issues/4201
cc: @smarterclayton @deads2k @ironcladlou
> logs: return application logs for dcs

- assets/app/index.html
- assets/app/scripts/app.js
- assets/app/scripts/controllers/buildConfig.js
- assets/app/scripts/controllers/create/createFromImage.js
- assets/app/scripts/controllers/edit/buildConfig.js
- assets/app/scripts/directives/oscKeyValues.js
- assets/app/scripts/filters/resources.js
- assets/app/scripts/filters/util.js
- assets/app/scripts/services/navigate.js
- assets/app/styles/_core.less
- assets/app/views/browse/build-config.html
- assets/app/views/directives/edit-link.html
- assets/app/views/directives/osc-key-values.html
- assets/app/views/edit/build-config.html
- assets/bower.json
The access to the edit page is through the kebab dropdown
The edit layout is in similar to the bc show page
After update the page is redirected to the bc show page and alert is printed.
> Modify buildConfig from web console

- assets/app/views/_pod-template.html
Fixes https://github.com/openshift/origin/issues/6972
> Force mount path to word break so it works at mobile

- CONTRIBUTING.adoc
- assets/README.md
@spadgett, review and merge, please?
> Bug fixes:  broken link, formatting fixes, addition of missing step

- pkg/cmd/admin/policy/reconcile_sccs.go
- pkg/cmd/admin/policy/reconcile_sccs_test.go
- test/cmd/admin.sh
This pull request should fix #5717 .
@pweil- @kargakis please review.
> Preserve labels and annotations during reconcile scc

- pkg/route/generator/generate.go
- test/cmd/basicresources.sh
> Bug 1304604: add missing route generator param for path

- hack/cmd_util.sh
fixes https://github.com/openshift/origin/issues/6456
@liggitt PTAL
> declared variables better for RHEL

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/validation/events.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/validation/events_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/registry/event/etcd/etcd_test.go
Fixes https://github.com/openshift/origin/issues/7022.
[test]
> UPSTREAM: 16146: Fix validate event for non-namespaced kinds

- pkg/cmd/cli/cmd/create_route.go
> Bug 1304635: fix termination type for oc create route reencrypt

- test/integration/imageimporter_test.go
> Test insecure TLS without CA for import

- assets/app/styles/_project-menu.less
> Fix of project name alignment in IE, fixes bug 1304228

- assets/app/scripts/controllers/image.js
- assets/app/views/browse/build-config.html
- assets/app/views/browse/build.html
- assets/app/views/browse/deployment-config.html
- assets/app/views/browse/deployment.html
- assets/app/views/browse/image.html
- assets/app/views/browse/persistent-volume-claim.html
- assets/app/views/browse/pod.html
- assets/app/views/browse/replication-controller.html
- assets/app/views/browse/route.html
- assets/app/views/browse/service.html
Fixes https://github.com/openshift/origin/issues/6974
Fixes https://github.com/openshift/origin/issues/6968
Fixes https://github.com/openshift/origin/issues/7030
> Missing loading message on browse pages

- UPGRADE.md
updates to UPGRADE.md
@liggitt @smarterclayton 
fixes https://github.com/openshift/origin/issues/7017
> release notes: incorrect field names will be rejected

- assets/app/scripts/controllers/overview.js
- assets/app/views/project.html
> Prevent header and toolbar flicker for empty project

- assets/app/styles/_substructure.less
- assets/app/styles/_variables.less
@spadgett, review and merge, please?  cc: @sg00dwin
> Removing the transition on .sidebar-left for cleaner rendering on resize

- test/extended/cmd.sh
> reverted typo in extended cmd

- hack/common.sh
- test/extended/core.sh
- test/extended/util/cli.go
- test/extended/util/framework.go
> Fix extended tests and enable them to compile

- pkg/api/validation/register.go
- pkg/api/validation/validation.go
- pkg/cmd/server/origin/reststorage_validation_test.go
Validations were not being registered unless another package had loaded
api/install first. An error on lookup is also not a field.Error.
@deads2k rebase fallout
> example_test can fail due to validations

- pkg/build/admission/defaults/api/install/install.go
- pkg/build/admission/overrides/api/install/install.go
- pkg/project/admission/lifecycle/admission.go
- pkg/project/registry/project/rest_test.go
- pkg/security/admission/scc_exec.go
- pkg/util/labelselector/labelselector.go
- pkg/util/labelselector/labelselector_test.go
- pkg/util/rest/webhook.go
- tools/gendeepcopy/deep_copy.go
@deads2k removed some of those copyright leftovers we've had.
> Removing copyright leftovers

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/apis/extensions/install/install.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/runtime/conversion_generator.go
- pkg/api/v1/conversion_generated.go
The second commit is the easiest short term fix (makes order stable on both go versions) but I'm not sure it's the long term solution.
Fixes #7083
> Fix conversions against travis

- pkg/auth/oauth/external/gitlab/gitlab.go
- pkg/auth/oauth/external/gitlab/gitlab_test.go
Tests url building, makes receiver a pointer, s/Api/API/, s/Url/URL/
> GitLab IDP tweaks

- HACKING.md
> Document requirements on kubernetes clone for cherry-picking.

- pkg/cmd/server/crypto/crypto.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1256692
> Handle cert-writing error

- hack/cherry-pick.sh
> Cherrypick should force delete branch

- tools/junitreport/test/integration.sh
fixes https://github.com/openshift/origin/issues/6862
> remove grep -P usage

- test/cmd/basicresources.sh
> Add tests for explain

- assets/app/scripts/filters/resources.js
> Fix web console type error when image has no env

- pkg/cmd/server/api/types.go
- pkg/cmd/server/api/v1/types.go
- pkg/cmd/server/api/v1/types_test.go
- pkg/cmd/server/origin/run_components.go
Paves the way for making this a cluster config option.
> Allow recursive DNS to be enabled via a config flag

- CONTRIBUTING.adoc
Changed "step 6" to "step 7" so the reference is correct.  
@jwforres or @spadgett, review and merge, please?
> Correcting reference to another step

- images/openldap/contrib/init.ldif
> added LDIF for suppression testing

- assets/app/views/browse/build-config.html
- assets/app/views/browse/deployment-config.html
- assets/app/views/browse/image.html
- assets/app/views/builds.html
- assets/app/views/deployments.html
@spadgett, review and merge, please?
Fixes #7163
> Forging consistency among empty tables at xs screen size

- assets/app/styles/_core.less
- assets/app/views/browse/build-config.html
- assets/app/views/edit/build-config.html
@spadgett, review and merge, please?
Fixes #7201
> Changing .ace_editor to .ace_editor-bordered so the border is optional

- assets/app/views/_pod-template.html
* Link to build config
* Put source on separate line
Fixes #7179 
/cc @sspeiche
> Update build info in web console pod template

- test/extended/core.sh
- test/extended/util/test.go
Create synthetic skip targets to allow --ginkgo.skip='\[Origin\]' to
skip all tests in a particular suite.
[merge]
> Exclude failing tests, add [Kubernetes] and [Origin] skip targets

- pkg/build/builder/cmd/dockercfg/cfg.go
- pkg/build/builder/docker.go
- test/extended/builds/docker_pullsecret.go
- test/extended/builds/docker_quota.go
- test/extended/fixtures/test-docker-build-pullsecret.json
fixes https://github.com/openshift/origin/issues/7228
> read docker pull secret from correct path

- pkg/cmd/server/kubernetes/master.go
> Scheduler has an official default name

- pkg/api/serialization_test.go
Need to ensure all hooks have a ContainerName set due to defaulting
Fixes #7280
[merge]
> DeploymentConfig hooks did not have round trip defaulting

- test/integration/imagechange_buildtrigger_test.go
when testing events for added/modified type,
make sure the event is for the build we care about.
> filter events being tested

- .gitignore
> Add direnv .envrc to gitignore

- assets/app/scripts/controllers/deployment.js
- assets/app/scripts/directives/logViewer.js
- assets/app/views/directives/logs/_log-viewer.html
Got the ok on the fork_ami for this from QE this morning.  
@jwforres @spadgett
> Web console: Fix deployment log var for archive url generation

- UPGRADE.md
- pkg/cmd/server/bootstrappolicy/securitycontextconstraints.go
- pkg/cmd/server/bootstrappolicy/securitycontextconstraints_test.go
- pkg/cmd/server/kubernetes/master.go
- pkg/cmd/server/start/start_master.go
Resolves https://github.com/openshift/origin/issues/6883
Added namespace and SA to recycler to fix permission issues.  Also updated the Upgrade doc.
@pweil- @deads2k
> Added specific namespace and service account to PV recycler

- .travis.yml
Clean travis run in https://travis-ci.org/openshift/origin/builds/109397224
> Bump travis to go1.5.3

- assets/app/scripts/controllers/buildConfig.js
- assets/app/scripts/controllers/deploymentConfig.js
- assets/app/styles/_core.less
- assets/app/views/browse/build-config.html
- assets/app/views/browse/deployment-config.html
- assets/app/views/builds.html
- assets/app/views/deployments.html
Fixes https://github.com/openshift/origin/issues/6485
> Provide a way in console to access orphaned builds / deployments

- pkg/cmd/server/etcd/etcd.go
- pkg/cmd/server/origin/master_config.go
- pkg/cmd/server/origin/run_components.go
- pkg/cmd/server/start/start_master.go
> Remove EtcdClient from MasterConfig

- assets/app/styles/_navbar-alt.less
- assets/app/styles/_project-menu.less
- assets/app/views/directives/header/_navbar-utility.html
- assets/app/views/project.html
- assets/test/integration/e2e.js
@spadgett 
cc @benjaminapetersen
> Changes and additions to enable text truncation of the project menu and username at primary media query breakpoints

- test/integration/imagechange_buildtrigger_test.go
fixes https://github.com/openshift/origin/issues/7239
> ignore events from previous builds

- pkg/authorization/api/types.go
- pkg/authorization/api/v1/types.go
- pkg/build/admission/defaults/api/v1/types.go
- pkg/build/admission/overrides/api/v1/types.go
- pkg/build/api/v1/types.go
- pkg/cmd/server/api/v1/types.go
- pkg/deploy/api/v1/types.go
- pkg/image/api/v1/types.go
- pkg/oauth/api/v1/types.go
- pkg/project/admission/requestlimit/api/v1/types.go
- pkg/project/api/v1/types.go
- pkg/quota/admission/runonceduration/api/v1/types.go
- pkg/route/api/v1/types.go
- pkg/sdn/api/v1/types.go
- pkg/template/api/v1/types.go
- pkg/user/api/v1/types.go
@smarterclayton  PTAL
This pull is straight adds only.
> added Godoc to api types where necessary

- assets/app/scripts/directives/buildTrendsChart.js
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1291615
@jwforres PTAL
> Size build chart correctly in Firefox

- Godeps/Godeps.json
- Godeps/_workspace/src/gopkg.in/ldap.v2/README.md
- Godeps/_workspace/src/gopkg.in/ldap.v2/ldap_test.go
- Godeps/_workspace/src/gopkg.in/ldap.v2/search.go
- pkg/auth/ldaputil/query.go
- pkg/auth/ldaputil/query_test.go
- pkg/auth/ldaputil/testclient/testclient.go
- pkg/cmd/server/api/types.go
- pkg/cmd/server/api/v1/types.go
- test/extended/authentication/ldap/ad/sync-config-paging.yaml
- test/extended/authentication/ldap/augmented-ad/sync-config-paging.yaml
- test/extended/authentication/ldap/rfc2307/sync-config-paging.yaml
- test/extended/ldap_groups.sh
> add support for paged LDAP queries

- assets/app/scripts/controllers/create/createFromImage.js
- assets/app/scripts/controllers/setLimits.js
- assets/app/scripts/directives/editRequestLimit.js
- assets/app/scripts/services/limits.js
- assets/app/views/_edit-request-limit.html
- assets/app/views/create/fromimage.html
- assets/app/views/set-limits.html
Honor project annotation `quota.openshift.io/cluster-resource-override-enabled`.
Fixes #7365
> Web console: honor cluster-resource-override-enabled

- pkg/security/admission/admission.go
> Fix admission attribute comparison

- pkg/router/controller/status.go
- pkg/router/controller/status_test.go
- pkg/router/controller/unique_host.go
Test cases were broken and not catching this error.
Fixes #7350
@jwforres @ramr
> The Host value should be written to all rejected routes

- hack/build-images.sh
> Image building resets the global script time

- examples/hello-openshift/hello_openshift.go
fixes https://github.com/openshift/origin/issues/7314
> make hello-openshift print to stdout when serving a request

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/clientcmd/client_config.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/clientcmd/loader.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/clientcmd/merged_client_builder.go
Fixes https://github.com/openshift/origin/issues/6804
> UPSTREAM: 21266: only load kubeconfig files one time

- pkg/cmd/server/api/validation/validation.go
- pkg/cmd/server/api/validation/validation_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1309435
> Validate wildcard certs against non-wildcard namedCertificate names

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/types.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/v1/types.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/unversioned/clientcmd/client_config.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/serviceaccount/tokens_controller.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/serviceaccount/tokens_controller_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/service_accounts.go
- pkg/cmd/util/clientcmd/factory.go
- test/end-to-end/core.sh
Makes in-cluster-config work without any extra pod modifications
Holding for rebase
> UPSTREAM: 21095: Provide current namespace to InClusterConfig

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory.go
- test/end-to-end/core.sh
Fixes https://github.com/openshift/origin/issues/7329
Adds a test in origin because we've had really bad luck with logs overall.
> Make rc logs work

- Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/admission/limitranger/admission.go
- Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/admission/limitranger/admission_test.go
- pkg/quota/admission/clusterresourceoverride/admission.go
Fixes https://github.com/openshift/origin/issues/7401
@derekwaynecarr downstream pick of https://github.com/kubernetes/kubernetes/pull/21470
@sosiouxme fyi
> Fix limit ranger

- pkg/generate/app/dockerimagelookup.go
https://bugzilla.redhat.com/show_bug.cgi?id=1309805
> properly check for nil docker client value

- assets/app/views/browse/_deployment-details.html
- assets/app/views/browse/_pod-details.html
- assets/app/views/browse/deployment-config.html
- assets/app/views/browse/deployment.html
- assets/app/views/browse/pod.html
- assets/app/views/browse/replication-controller.html
- assets/app/views/browse/service.html
> Add attach storage and create route to the actions dropdown

- assets/app/styles/_sidebar.less
- assets/app/styles/_variables.less
Fixing a couple bugs I noticed in the navbar at mobile resolutions.
After:
@spadgett, review and merge, please?
> Resolving a couple cosmetic issues with navbar at mobile resolutions

- examples/jenkins-master/README.md
- examples/jenkins-master/configuration/jobs/ruby-hello-world-test/config.xml
- examples/jenkins-master/jenkins-master-template.json
- examples/jenkins-master/jenkins-slave-template.json
- examples/jenkins-master/plugins.txt
- examples/jenkins-master/slave/Dockerfile
- examples/jenkins-master/slave/contrib/openshift/passwd.template
- examples/jenkins-master/slave/contrib/openshift/run-jnlp-client
- test/extended/jenkins/kubernetes_plugin.go
Provide easy-to-use example of Jenkins running in OpenShift with kubernetes plugin. Also provide the "s2i-to-slave" template to help with slave image creation.
Trello: https://trello.com/c/DiA0pq8J/751-5-slave-image-support-for-jenkins
**TODO**
> Add Jenkins with kubernetes plugin example

- examples/image-streams/image-streams-centos7.json
- examples/image-streams/image-streams-rhel7.json
- test/cmd/images.sh
- test/cmd/newapp.sh
fixes https://github.com/openshift/origin/issues/5883
@jwforres ptal.
note that all the "latest" ISTs show up now....
> add DB icons and also add annotations to the 'latest' imagestream tags

- assets/app/views/directives/annotations.html
Fixes issue #7005 
The directive does exist on the DeploymentConfig page, so the only item addressed in the top & bottom margin.
@spadgett @jwforres
> Web console: add margin to annotations directive

- docs/proposals/image-promotion.md
@bparees @smarterclayton this is illustrating the example we use in Jenkins to promote between "stage" and "prod". This example requires latest registry. Also there is still this issue about resolving the "prod" IST as "stage/sample-app@...": https://github.com/openshift/origin/issues/6934
> Add cross project promotion example

- test/integration/clusterresourceoverride_admission_test.go
After the race fix from upstream, it is possible to flake like this:
```
--- FAIL: TestClusterResourceOverridePlugin-2 (7.59s)
clusterresourceoverride_admission_test.go:66: limit-with-default: Memory limit did not match default 512Mi: 0
clusterresourceoverride_admission_test.go:69: limit-with-default: Memory req did not match expected 256Mi: 0
clusterresourceoverride_admission_test.go:72: limit-with-default: CPU limit did not match expected 500 mcore: 1
clusterresourceoverride_admission_test.go:75: limit-with-default: CPU req did not match expected 250 mcore: 500m
```
this happens because the cache is empty when the first pod is created (this is because there are no limits at all), the LRU gets primed for a hit with an empty list (also correct).  The limit range is created, but the cache …
> correct cluster resource override tests

- assets/app/views/directives/osc-key-values.html
Fixes https://github.com/openshift/origin/issues/7468
> Env vars with leading slashes cause major js errors in console create from image flow

- pkg/route/api/v1/conversion.go
- pkg/route/api/v1beta3/conversion.go
- pkg/route/api/validation/validation.go
- pkg/route/api/validation/validation_test.go
- pkg/route/registry/route/etcd/etcd_test.go
- pkg/route/registry/route/strategy.go
> Drop route service namespace

- pkg/router/controller/status.go
- pkg/router/controller/status_test.go
Ensures that the router is backwards compatible until roles are updated. Fixes a 1.1.3 regression.
Fixes #7452
> Router should tolerate not having permission to write status

- assets/app/styles/_tables.less
- assets/app/views/browse/build-config.html
- assets/app/views/browse/deployment-config.html
Fixes https://github.com/openshift/origin/issues/7240
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1309557
> Add back the filter bar to the bc and dc pages

- pkg/cmd/server/admin/create_mastercerts.go
- test/cmd/admin.sh
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1305165
> Validate master/publicMaster args to create-master-certs

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/conversion.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/unversioned/time.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/api/v1/conversion_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/conversion/queryparams/convert.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/conversion/queryparams/convert_test.go
- test/end-to-end/core.sh
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1286116
> Fix --since-time log option

- test/extended/util/framework.go
Only a single timeout value is necessary. The fixed 15m limit is left unchanged.
This change avoids trashing a good watcher after 10s, while still respecting the global limit.
----------
I've written just recently a very similar piece of code for a personal project, thus sharing the approach here.
@bparees @gabemontero @php-coder wdyt?
> Refactor WaitForADeployment

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/node/nodecontroller.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/dockertools/manager.go
The node controller makes me want to murder kittens.
[merge]
> UPSTREAM: 21628: Reduce node controller debug logging

- pkg/generate/app/dockerimagelookup.go
@csrwng @bparees can either of you try to add an integration test for when docker client is not installed to verify that we don't regress in the future here?
[merge]
> new-app broken when docker not installed

- assets/app/styles/_core.less
> iOS: prevent select from zooming page

- assets/app/views/browse/replication-controller.html
> Add events tab to plain RCs in web console

- assets/app/styles/_tables.less
- assets/app/views/browse/image.html
Fixes https://github.com/openshift/origin/issues/7476
> Mobile table headers missing on browse image page

- assets/app/views/browse/_deployment-details.html
- assets/app/views/deployments.html
Don't show status "Deployed" for replication controllers that don't have a deployment config.
Fixes #6200
> Don't show "Deployed" for plain RCs in web console

- hack/test-assets.sh
- test/end-to-end/core.sh
> Suppress escape sequences at end of hack/test-assets.sh

- assets/app/views/directives/_status-icon.html
> Add status icon for ContainerCreating reason

- assets/app/scripts/services/routes.js
Fixes https://github.com/openshift/origin/issues/7540
> Js error on overview for route warnings

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/describe.go
Fixes https://github.com/openshift/origin/issues/2949
@smarterclayton @fabianofranz
> UPSTREAM: 21671: kubectl: add container ports in pod description

- pkg/build/registry/buildconfiginstantiate/rest.go
fixes https://github.com/openshift/origin/issues/7489
> increase binary build timeout to 5 minutes

- pkg/cmd/cli/cmd/importimage.go
Needs cleanup in the future for legibility (multi-column printout).
Fixes #7511 [test]
> Display additional tags after import

- examples/examples_test.go
- hack/verify-govet.sh
Got rid of whitelist entries that were not hiding any shadowed variables. 
@deads2k  PTAL
> pruned govet whitelist

- hack/common.sh
hack/build-go.sh attempts to use release archives if they are present,
but untarring on an nfs mount requires that the --no-same-owner flag be
used to prevent tar from trying to change ownership on extracted
files (which can fail even for root on nfs).
> Fix reuse of release build on nfs mount

- assets/Gruntfile.js
- assets/package.json
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1309522
> Fix css compilation issues that affect IE, particularly flexbox

- assets/app/scripts/app.js
- assets/app/scripts/directives/date.js
- assets/app/scripts/filters/date.js
- assets/app/views/directives/events.html
- assets/app/views/events.html
> Web console: improve repeated events message

- assets/app/scripts/directives/metrics.js
- assets/app/scripts/services/metrics.js
- assets/app/views/browse/pod.html
- assets/app/views/directives/_pod-metrics.html
Show a more detailed error including the hawkular-metrics URL. If the problem is with self-signed certs, it gives the user a chance to accept the cert.
@jwforres @smarterclayton
> Improve web console metrics error message

- pkg/build/admission/defaults/admission.go
- pkg/build/admission/overrides/admission.go
> Remove v(4) logging of build admission startup

- examples/quickstarts/cakephp-mysql.json
- examples/quickstarts/dancer-mysql.json
- examples/quickstarts/django-postgresql.json
- examples/quickstarts/nodejs-mongodb.json
- examples/quickstarts/rails-postgresql.json
Update examples including build hooks.
- ~~https://github.com/openshift/cakephp-ex~~ (https://github.com/openshift/cakephp-ex/issues/24)
- ~~https://github.com/openshift/dancer-ex~~ (https://github.com/openshift/dancer-ex/issues/29)
- ~~https://github.com/openshift/nodejs-ex~~ (https://github.com/openshift/nodejs-ex/issues/32)
> Update external examples

- pkg/cmd/cli/describe/describer.go
- pkg/cmd/cli/describe/describer_test.go
All forms of using the hook are transformed into a single equivalent
representation, listing commands/args as a string array, so that
individual arguments can be distiguished unambiguously, as opposed to
representing the hook as a string.
Example output:
```console
$ oc describe build rails-postgresql-example-1
Name:                   rails-postgresql-example-1
Created:                21 hours ago
Labels:                 app=rails-postgresql-example,buildconfig=rails-postgresql-example,openshift.io/build-config.name=rails-postgresql-example,template=rails-postgresql-example
Annotations:            openshift.io/build.number=1
openshift.io/build.pod-name=rails-postgresql-example-1-build
Build Config:           rails-postgresql-example
Started:                2016-02-24 16:31:40 +0000 UTC …
```
> Include build hook in describer

- Makefile
- hack/build-cross.sh
- hack/common.sh
> Add shasums to release build output

- assets/app/styles/_core.less
- assets/app/styles/_substructure.less
- assets/app/styles/_variables.less
- assets/app/views/browse/routes.html
- assets/app/views/builds.html
- assets/app/views/deployments.html
- assets/app/views/images.html
- assets/app/views/pods.html
- assets/app/views/services.html
- assets/app/views/storage.html
Fixes https://github.com/openshift/origin/issues/7402
Additional fixes
Subtle style changes to the project nav menu scrollbar so that it's more noticeable.
fixes https://github.com/openshift/origin/issues/7480
Place margin-bottom on middle-content area
fixes https://github.com/openshift/origin/issues/5742
> Adjustments to the filter widget css so that it addresses some overlapping issues.

- assets/app/views/util/oauth.html
> Add header back to logging in page

- Makefile
> Verify the integration test build early

- pkg/deploy/controller/configchange/controller.go
- pkg/deploy/util/util.go
Fixes https://github.com/openshift/origin/issues/7663
Fixes https://github.com/openshift/origin/issues/7686
@ironcladlou @smarterclayton
> configchange: proceed with deployment with non-automatic ICTs

- assets/app/views/directives/osc-key-values.html
Tested the change and should be fixed
@jwforres PTAL
> BZ_1312819: Can not add Environment Variables on buildconfig edit page

- examples/db-templates/mongodb-ephemeral-template.json
- examples/db-templates/mongodb-persistent-template.json
- examples/db-templates/mysql-ephemeral-template.json
- examples/db-templates/mysql-persistent-template.json
- examples/db-templates/postgresql-ephemeral-template.json
- examples/db-templates/postgresql-persistent-template.json
Update database and application examples to include readiness and liveness probes.
NOTE: Ignore @kargakis commit ;-)
> WIP: Add liveness and readiness probes to examples

- examples/db-templates/mongodb-ephemeral-template.json
- examples/db-templates/mongodb-persistent-template.json
- examples/db-templates/postgresql-ephemeral-template.json
- examples/db-templates/postgresql-persistent-template.json
- examples/jenkins/application-template.json
@bparees @danmcp FYI / PTAL
these changes stem from discussion on aos-scalability and are explicit direction from @danmcp
> bump all template mem limits to 512 Mi

- images/router/haproxy/conf/haproxy-config.template
- pkg/cmd/admin/router/router.go
- pkg/router/template/plugin.go
Allows router ports to be overriden + multiple instances to run with host networking.
Fix for bugz https://bugzilla.redhat.com/show_bug.cgi?id=1268904 
@smarterclayton / @eparis  PTAL  Thx
> Use http[s] ports for environment values. 

- contrib/completions/bash/oc
- pkg/cmd/cli/cli_bashcomp_func.go
Adds completion for oc rsh command
> Adds completion for oc rsh command

- pkg/cmd/server/bootstrappolicy/constants.go
- pkg/cmd/server/bootstrappolicy/policy.go
- test/fixtures/bootstrappolicy/bootstrap_cluster_roles.yaml
I added a roles for image registry users.
@deads2k @pweil- please review.
> Create policy for image registry users

- assets/app/scripts/directives/events.js
https://bugzilla.redhat.com/show_bug.cgi?id=1313161
@jwforres PTAL
> Restrict events filter to certain fields in web console

- pkg/cmd/infra/router/template.go
@eparis / @smarterclayton alternative fix for #7589    PTAL Thx
> Bug fix for negative reload intervals - bugz 1311459.

- assets/app/scripts/controllers/overview.js
- assets/app/scripts/filters/resources.js
- assets/app/scripts/services/routes.js
- assets/test/spec/services/routesSpec.js
> Web console: fix problems with display route and route warnings

- test/integration/imageimporter_test.go
Resolves #7355
This PR is to #7355 as #6335 is to #6232.
> integration: Retry import from external registries when not reachable

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/apply.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/apply_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/test/fixtures/pkg/kubectl/cmd/apply/rc-service.yaml
- Godeps/_workspace/src/k8s.io/kubernetes/test/fixtures/pkg/kubectl/cmd/apply/rc.yaml
- Godeps/_workspace/src/k8s.io/kubernetes/test/fixtures/pkg/kubectl/cmd/apply/service.yaml
- test/cmd/admin.sh
> Fix apply for lists

- hack/lib/log.sh
@danmcp 
no testing necessary I believe
> removed SAR logfile from artifacts

- examples/quickstarts/cakephp-mysql.json
- examples/quickstarts/dancer-mysql.json
- examples/quickstarts/django-postgresql.json
- examples/quickstarts/nodejs-mongodb.json
- examples/quickstarts/rails-postgresql.json
@bparees FYI
(This is just bumping the JSON files from already merged PRs, so merging it now ;-)
> Update external examples to include readiness/liveness probes

- assets/app/views/project.html
> Make overview "other routes" link go to browse routes page

- test/integration/buildcontroller_test.go
fixes https://github.com/openshift/origin/issues/7680
> ignore unrelated build+pod events during tests

- pkg/deploy/api/test/ok.go
- pkg/deploy/controller/configchange/controller.go
- pkg/deploy/controller/configchange/controller_test.go
- pkg/deploy/util/util.go
Fixes https://github.com/openshift/origin/issues/7663
@smarterclayton @ironcladlou PTAL
> configchange: correlate triggers with the generated cause

- test/extended/core.sh
> Dashboard extended test should not be run

- examples/jenkins-master/jenkins-master-template.json
Depends on: https://github.com/openshift/jenkins/pull/86
> Remove downward api call for Jenkins kubernetes example

- pkg/api/graph/graph.go
- pkg/api/graph/interfaces.go
- pkg/api/graph/test/bad_secret_with_just_rc.yaml
- pkg/api/graph/test/circular.yaml
- pkg/api/graph/test/different-project-image-deployment.yaml
- pkg/api/graph/test/unpushable-build.yaml
- pkg/build/graph/analysis/bc_test.go
- pkg/cmd/cli/cmd/status.go
- pkg/cmd/cli/describe/projectstatus.go
- pkg/cmd/cli/describe/projectstatus_test.go
- test/fixtures/app-scenarios/new-project-deployed-app.yaml
Fixes https://github.com/openshift/origin/issues/7192
@deads2k
> oc: hide markers from different projects in oc status

- pkg/cmd/server/bootstrappolicy/securitycontextconstraints.go
Making this WIP PR to do some CI testing while we finish manually testing this.
cc @pweil- @bparees @smarterclayton
> Enable FSGroup in restricted and hostNS SCCs

- tools/genconversion/conversion.go
> Show log output in conversion generation

- test/extended/util/test.go
~~This PR requires the mount propagation support added by docker 1.10.  It should not be merged until #7668 has merged.~~
~~Fixes #6577~~
Update: This PR has been retargeted to fixing the kube e2e test against non-dind clusters.
> Fix kube e2e intra-pod test

- pkg/api/graph/graphview/image_pipeline.go
- pkg/api/graph/test/prereq-image-not-present.yaml
- pkg/api/graph/test/prereq-image-present-notag.yaml
- pkg/api/graph/test/prereq-image-present.yaml
- pkg/build/graph/analysis/bc.go
- pkg/build/graph/analysis/bc_test.go
- pkg/cmd/cli/describe/projectstatus.go
- pkg/deploy/graph/analysis/dc.go
- pkg/deploy/graph/analysis/dc_test.go
- pkg/image/graph/edges.go
- pkg/image/graph/nodes/types.go
fixes #5077 
@bparees @csrwng ptal, with current 3.1 blocking only mode in mind
> add oc status warnings for missing ImageStream/ImageStreamTag for BuildConfig

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/rolling_updater.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/rolling_updater_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1314142
Merged upstream (https://github.com/kubernetes/kubernetes/pull/22526) so merging here as well
[merge]
@smarterclayton @ironcladlou @pweil- fyi
> UPSTREAM: 22526: kubectl: bring the rolling updater on par with the deployments

- pkg/deploy/controller/deployment/controller.go
More helpful since people look for problems into the dc more often than looking at the respective rcs.
Fixes https://github.com/openshift/origin/issues/7295
Fixes https://github.com/openshift/origin/issues/5191
@smarterclayton @ironcladlou PTAL
> deploy: emit events on the dc instead of its rcs

- assets/app/scripts/controllers/modals/editModal.js
- assets/app/scripts/directives/deleteLink.js
- assets/app/scripts/filters/resources.js
- assets/app/scripts/services/navigate.js
- assets/app/views/browse/build-config.html
- assets/app/views/browse/build.html
- assets/app/views/browse/deployment-config.html
- assets/app/views/browse/deployment.html
- assets/app/views/browse/image.html
- assets/app/views/browse/persistent-volume-claim.html
- assets/app/views/browse/pod.html
- assets/app/views/browse/replication-controller.html
- assets/app/views/browse/route.html
- assets/app/views/browse/service.html
- assets/app/views/directives/delete-button.html
- assets/app/views/modals/delete-resource.html
- assets/app/views/projects.html
- assets/app/views/settings.html
Fixes #6990
Fixes #7757
/cc @jwforres @liggitt
> Unconfuse web console about resource and kind

- pkg/router/f5/f5.go
> Fix hardcoded f5 username (admin).

- pkg/deploy/api/types.go
- pkg/deploy/api/v1beta3/types.go
Fixes https://github.com/openshift/origin/issues/7328
> shorten dc caused by annotations

- assets/app/scripts/filters/date.js
- assets/app/views/browse/_pod-details.html
Suggested by @derekwaynecarr 
@jwforres PTAL
> Add active deadline to browse pod page

- hack/verify-jsonformat.sh
- images/builder/docker/custom-docker-builder/build.sh
- test/cmd/admin.sh
- test/cmd/policy.sh
> test-cmd: mktemp --suffix is not supported in Mac

- assets/app/scripts/controllers/create.js
- assets/app/scripts/controllers/create/createFromImage.js
- assets/app/scripts/controllers/create/nextSteps.js
- assets/app/scripts/controllers/createRoute.js
- assets/app/scripts/controllers/newfromtemplate.js
- assets/app/views/create-route.html
- assets/app/views/create.html
- assets/app/views/create/fromimage.html
- assets/app/views/create/next-steps.html
- assets/app/views/newfromtemplate.html
@spadgett @jwforres as we discussed here is the PR unifying the usage of the breadcrumb directive. 
PTAL
> Breadcrumbs unification

- pkg/cmd/cli/cmd/rsync/copyrsync.go
- pkg/cmd/cli/cmd/rsync/rsync.go
- pkg/cmd/cli/cmd/rsync/util.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1314817
@csrwng please review
> rsync must validate if pod exists

- assets/app/scripts/controllers/edit/buildConfig.js
@spadgett wanted to incorporate it into my current work but since that wont be part of the 1.2 I've created a separate commit.
> Fixing typo

- pkg/deploy/controller/deployment/controller.go
> deploy: more informative cancellation event on dc

- pkg/api/graph/test/wrong-named-port.yaml
- pkg/api/graph/test/wrong-numeric-port.yaml
- pkg/cmd/cli/describe/projectstatus.go
- pkg/route/generator/generate.go
- pkg/route/graph/analysis/analysis.go
- pkg/route/graph/analysis/analysis_test.go
@deads2k @ramr @liggitt 
Fixes https://github.com/openshift/origin/issues/6266
> oc: update route warnings for oc status

- test/extended/fixtures/forcepull-setup.json
https://github.com/openshift/origin/issues/7817
> nocache should be noCache

- Godeps/Godeps.json
Corresponds to https://github.com/openshift/kubernetes/tree/stable-20160309
> bump(k8s.io/kubernetes): 91d3e753a4eca4e87462b7c9e5391ec94bb792d9

- pkg/cmd/server/admin/create_signercert.go
- pkg/cmd/server/admin/signer_cert_args.go
- pkg/cmd/server/crypto/crypto.go
- pkg/cmd/server/crypto/crypto_test.go
Introduces a serial based on a hash of the subject and the current time.  I need this (or something like it) for the service serving cert signer.
@liggitt ptal
> allow different cert serial number generators

- assets/Gruntfile.js
@jwforres, I opted for just development on this since that's where the real benefit to the UI team is.  We of course can also add it for production if we deem necessary...
cc:  @spadgett, @benjaminapetersen, @sg00dwin
> Enabling LessCSS source maps for development

- pkg/router/template/plugin.go
fixes #7904 
@smarterclayton  PTAL thx
> Fix default cert for edge route not being used - fixes #7904

- hack/test-go.sh
> add debug statements for test-go

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti.go
> Update incremental build log message to show correct image tag

- examples/sample-app/README.md
@bparees PTAL or assign a reviewer
> sample-app: update docs

- pkg/generate/app/cmd/newapp_test.go
Also:
- Place helpers right under their usage
- Do not export test helper (mockSourceRepositories)
> Remove left over after move to test/integration

- assets/package.json
> Bump grunt-contrib-uglify to 0.6.0

- pkg/build/api/v1/conversion.go
- pkg/build/api/v1beta3/conversion.go
- pkg/build/api/validation/validation.go
- pkg/build/controller/image_change_controller.go
- pkg/build/generator/generator.go
- pkg/build/generator/generator_test.go
- pkg/build/graph/edges.go
- pkg/build/util/util.go
- pkg/cmd/cli/cmd/set/triggers.go
- pkg/generate/app/cmd/newapp.go
- pkg/image/prune/imagepruner.go
- test/extended/builds/dockerfile.go
- test/integration/newapp_test.go
> Fix build output cycle detection

- assets/bower.json
> Bumping openshift-object-describer to v1.1.2

- pkg/build/builder/docker.go
- pkg/build/builder/sti.go
fixes https://github.com/openshift/origin/issues/7939
@smarterclayton ptal
> always flush glog before returning from build logic

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/resource_printer_test.go
Fixes test blocking the merge queue
> UPSTREAM: 22929: Test relative timestamps using UTC

- pkg/api/latest/tags_test.go
- pkg/authorization/api/v1/types.go
- pkg/authorization/api/v1beta3/types.go
- pkg/build/api/v1/types.go
- pkg/build/api/v1beta3/types.go
- pkg/deploy/api/v1/types.go
- pkg/deploy/api/v1beta3/types.go
- pkg/image/api/v1/types.go
- pkg/image/api/v1beta3/types.go
- pkg/oauth/api/v1/types.go
- pkg/project/api/v1/types.go
- pkg/project/api/v1beta3/types.go
- pkg/route/api/v1/types.go
- pkg/sdn/api/v1/types.go
- pkg/sdn/api/v1beta3/types.go
- pkg/template/api/v1/types.go
- pkg/template/api/v1beta3/types.go
- pkg/user/api/v1/types.go
- pkg/user/api/v1beta3/types.go
Fixes: https://github.com/openshift/origin/issues/7786
> Remove description field from types

- pkg/api/graph/graph.go
- pkg/image/prune/imagepruner.go
> made edge language less ambiguous

- pkg/template/template.go
- pkg/template/template_test.go
Fixes https://github.com/openshift/origin/issues/4718
@bparees @liggitt a (hopefully) small one to look at Monday AM
> fine tune which template parameter error types are returned

- pkg/authorization/api/types.go
- pkg/cmd/server/bootstrappolicy/policy.go
- test/fixtures/bootstrappolicy/bootstrap_cluster_roles.yaml
@deads2k partially fixes #7096
> Add ConfigMap permissions

- pkg/deploy/controller/deployment/controller.go
@ironcladlou PTAL
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1317783
@pweil- fyi
> Bug 1317783: avoid shadowing errors in the deployment controller

- hack/cherry-pick.sh
- hack/move-upstream.sh
[merge]
@deads2k unifying these
> move-upstream should use UPSTREAM_REPO_LOCATION like cherry-pick

- examples/db-templates/mongodb-ephemeral-template.json
- examples/db-templates/mongodb-persistent-template.json
- examples/db-templates/mysql-ephemeral-template.json
- examples/db-templates/mysql-persistent-template.json
- examples/db-templates/postgresql-ephemeral-template.json
- examples/db-templates/postgresql-persistent-template.json
- examples/jenkins-master/jenkins-master-template.json
- examples/jenkins-master/jenkins-slave-template.json
- examples/jenkins/application-template.json
- examples/jenkins/jenkins-ephemeral-template.json
- examples/jenkins/jenkins-persistent-template.json
- examples/quickstarts/cakephp-mysql.json
- examples/quickstarts/dancer-mysql.json
- examples/quickstarts/django-postgresql.json
- examples/quickstarts/nodejs-mongodb.json
- examples/quickstarts/rails-postgresql.json
Fixes https://github.com/openshift/origin/issues/3563
@bparees PTAL
> parameterize IS namespace

- test/cmd/admin.sh
> place tmp secret files in tmpdir

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/helpers.go
> UPSTREAM: 22999: Display a better login message

- pkg/cmd/cli/cmd/tag.go
> oc: warn about missing stream when deleting a tag

- assets/app/styles/_core.less
> Stack definition lists only at narrower widths

- hack/test-end-to-end-docker.sh
Fixes https://github.com/openshift/origin/issues/8050
> updated tmpdir for e2e-docker

- pkg/build/graph/analysis/bc.go
- pkg/cmd/cli/describe/projectstatus.go
- pkg/cmd/cli/describe/projectstatus_test.go
- pkg/route/graph/analysis/analysis.go
- pkg/route/graph/analysis/analysis_test.go
@deads2k @stevekuznetsov @ramr PTAL
Fixes https://github.com/openshift/origin/issues/7832
@jwforres @spadgett fyi
> oc: more status fixes

- pkg/build/builder/dockerutil.go
Small nit I noticed when working on porting the ideas from this file to source-to-image.
@bparees PTAL
> Include container ID in glog message

- pkg/cmd/server/origin/ensure.go
If you are running OpenShift on a Kubernetes cluster, we need to ignore security context constraints since they are not actually in upstream Kubernetes...
> Ignore default security context constraints when running on kube

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/api/types.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/common.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/ovs/bin/openshift-sdn-ovs
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/ovs/controller.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/ovs/plugin.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/registry.go
- Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/subnets.go
Includes these openshift-sdn PRs:
https://github.com/openshift/openshift-sdn/pull/268
https://github.com/openshift/openshift-sdn/pull/267
https://github.com/openshift/openshift-sdn/pull/266
https://github.com/openshift/openshift-sdn/pull/245
> bump(github.com/openshift/openshift-sdn): 72d9ab84f4bf650d1922174e6a90bd06018003b4

- assets/app/scripts/extensions/javaLink.js
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1270491
@jwforres FYI, thanks!
> Hide the java link if the container is not ready

- images/router/haproxy/reload-haproxy
- pkg/router/template/router.go
Trim down the output for debugging. Remove -x
@ramr
Fixes #8142
> Log the reload output for admins in the router logs

- test/extended/core.sh
> Disable failing upstream test

- contrib/systemd/containerized/origin-node.service
So that fluentd works properly
> Mount /var/log into node container

- assets/app/views/util/error.html
Fixes https://github.com/openshift/origin/issues/8198
> Add navbar-utility-mobile to error.html

- hack/cmd_util.sh
- pkg/cmd/cli/cmd/debug.go
- test/cmd/debug.sh
Last minute change to Command setup resulted in TTY not being set by
default. Fixed, added test.
[test]
@deads2k review
> oc debug is not defaulting to TTY

- pkg/cmd/cli/cmd/startbuild.go
do not leak response body
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
> pkg: cmd: cli: cmd: startbuild: close response body

- Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/garbage_collector.go
- pkg/cmd/server/bootstrappolicy/infra_sa_policy.go
- pkg/cmd/server/kubernetes/master.go
- pkg/cmd/server/start/start_master.go
- test/extended/core.sh
- test/fixtures/bootstrappolicy/bootstrap_cluster_roles.yaml
> Enable the pod garbage collector

- test/extended/core.sh
Addresses part of #8221
[merge]
> New skips in extended tests

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/restclient/request.go
Got dropped in rebase due to the restclient package refactor
> UPSTREAM: <carry>: Suppress aggressive output of warning

- assets/app/scripts/services/projects.js
Fixes https://github.com/openshift/origin/issues/8137
> Fixes error with quota on project 404

- pkg/image/registry/imagestreamimport/rest.go
- test/extended/cmd.sh
- tools/testdebug/cmd/load_etcd.go
Fixes https://github.com/openshift/origin/issues/8220
Fixes https://github.com/openshift/origin/issues/8092
Image importer got a lot faster, so we were racing with it and losing.  Tidied up some messages, todos, and debt while I was here.
@stevekuznetsov
> fix extended cmd.sh to handle faster importer

- assets/app/index.html
- assets/app/styles/_core.less
This change provides a more descriptive error message when JavaScript
is disabled, including a link to a web site that explains how to enable
JavaScript in various browsers.  It also provides information about
alternatives (i.e. to use the command-line client.)
Closes: #8076
Signed-off-by: Jonathan Yu <jawnsy@redhat.com>
> Better error message when JavaScript is disabled

- examples/sample-app/application-template-custombuild.json
- examples/sample-app/application-template-dockerbuild.json
- examples/sample-app/application-template-pullspecbuild.json
- examples/sample-app/application-template-stibuild.json
fixes https://github.com/openshift/origin/issues/8236
@mfojtik ptal
> use emptydir for sample-app volumes

- pkg/generate/app/componentmatch.go
- pkg/generate/app/dockerimagelookup.go
- pkg/generate/app/pipeline.go
fixes https://github.com/openshift/origin/issues/7389
> introduce virtual image concept to handle scratch images

- pkg/cmd/cli/cmd/debug.go
> Reorder the debug pod name

- test/extended/core.sh
> E2e deployments filter is incorrect

- pkg/serviceaccounts/client.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1306590
SA user agents should include the default string and have their SA details appended.  Thought I commented during review.
@liggitt
> fix useragent for SA

- test/extended/core.sh
> Deployment tests should really be disabled in e2e

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/api/types.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/api/validation/validation.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/api/validation/validation_test.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/build/strategies/layered/layered_test.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/build/strategies/onbuild/onbuild_test.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti_test.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/docker/docker.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/docker/docker_test.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/ignore/ignore_test.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/scm/empty/noop.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/scm/git/clone_test.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/scm/git/git_test.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/scm/scm.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/scm/scm_test.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/scripts/download.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/scripts/install.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/scripts/install_test.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/tar/tar.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/tar/tar_test.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/util/timeout.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/util/timeout_test.go
- pkg/build/builder/sti.go
> builds: use proxy specified in source strategy environment for s2i script download

- assets/app/scripts/services/deployments.js
Fixes #8271
@jwforres PTAL. Let me know how you feel about this for 1.2. In my testing, it works well.
@liggitt CC
> Use scale subresource for DC scaling in web console

- contrib/tuned/origin-node-guest/tuned.conf
- contrib/tuned/origin-node-host/tuned.conf
Addresses https://github.com/openshift/origin/issues/8209
> bump inotify watches

- Godeps/_workspace/src/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/daemon/controller.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/daemon/controller_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/config/config.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/config/config_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/dockertools/docker.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/dockertools/docker_test.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/host_path/host_path.go
- Godeps/_workspace/src/k8s.io/kubernetes/pkg/volume/host_path/host_path_test.go
Picks for https://github.com/openshift/origin/issues/6766
> Upstream cherry picks

- assets/app/styles/_settings.less
- assets/app/styles/main.less
- assets/app/views/_settings-general-info.html
Fixes issue #8162
Primarily addresses stacking the form for mobile. I haven't been able to reproduce the overlapping text via various mobile browsers on browserstack.  Not sure yet what the deal is there.
@spadgett @jwforres @sg00dwin
> Fix 8162: project settings layout issues

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/api/types.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/scm/git/clone.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/scm/git/git.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/scm/scm.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/scm/scm_test.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/scripts/install.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/scripts/install_test.go
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/util/fs.go
> bump(github.com/openshift/source-to-image): 48e62fd57bebba14e1d0f7a40a15b65dafa5458c

- pkg/image/prune/imagepruner.go
> Fixed string formatting for glog.Infof in image prunning

- pkg/deploy/controller/deployerpod/controller.go
- pkg/deploy/controller/deployerpod/factory.go
- pkg/deploy/controller/deployment/controller.go
Ref https://bugzilla.redhat.com/show_bug.cgi?id=1318920
I cannot reproduce the race described in the issue as it is really a corner case but this PR is a good shot at fixing it.
@ironcladlou PTAL
> Bug 1318920: emit events for failed cancellations

- pkg/cmd/admin/policy/reconcile_sccs.go
- pkg/cmd/admin/policy/reconcile_sccs_test.go
Ensure volume slices in differing orders do not produce reconcile diffs.
@deads2k
> sort volumes for reconciliation

- docs/builds.md
Signed-off-by: Wang Qilin <qilin.wang@huawei.com>
> fix a forgotten modification : 'sti->s2i'

- pkg/cmd/cli/cmd/startbuild.go
- pkg/cmd/cli/cmd/startbuild_test.go
Allows reuse of the command from other commands
> Refactor start-build to use options style

- pkg/cmd/admin/groups/sync/cli/sync.go
- pkg/cmd/admin/policy/reconcile_clusterrolebindings.go
- pkg/cmd/admin/policy/reconcile_clusterroles.go
- pkg/cmd/admin/policy/reconcile_sccs.go
- pkg/cmd/admin/registry/registry.go
- pkg/cmd/admin/router/router.go
- pkg/cmd/cli/cmd/newapp.go
- pkg/cmd/cli/cmd/newbuild.go
- pkg/cmd/util/cmd.go
- pkg/generate/app/cmd/newapp.go
- pkg/generate/app/cmd/newapp_test.go
- pkg/generate/app/cmd/resolve.go
- pkg/generate/app/componentref.go
- pkg/generate/app/sourcelookup.go
- test/integration/newapp_test.go
Follows conventions, reduces inconsistencies in the command.
[test] @bparees
> Refactor new app and new build to use options struct

- pkg/image/prune/imagepruner.go
- pkg/image/prune/imagepruner_test.go
This unblocks the problem described in [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1322587). 
@miminar @pweil- ptal
@wshearn fyi
> Bug 1322587 - NotFound error (404) is logged but doesn't terminate pruning

- examples/db-templates/mongodb-persistent-template.json
- examples/db-templates/mysql-persistent-template.json
- examples/db-templates/postgresql-persistent-template.json
- examples/jenkins/jenkins-persistent-template.json
@danmcp per earlier IRC exchange
@bparees FYI
> change default volume size

- assets/app/scripts/directives/podStatusChart.js
- assets/app/scripts/filters/resources.js
- assets/app/scripts/filters/util.js
- assets/app/views/_pod-template.html
* Show donut pulling status for container state reason `ContainerCreating`
* Show donut terminating status when deletionTimestamp is set
* Show image size in pod template
Fixes #8322
@jwforres @smarterclayton
> Show pulling / terminated status in pods donut

- pkg/build/registry/buildconfiginstantiate/rest.go
- pkg/build/registry/rest.go
On BuildConfigInstantiate, makes rapid create -> binary build tolerate
images that haven't been tagged yet.  Also handle when a build is deleted while a user is trying to upload contents, and correct an error message in the wait for binary builds to show the correct output.
@csrwng
> Retry when receiving an imagestreamtag not found error

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/docker/docker.go
Fixing incremental builds deadlock.
> Bump github.com/openshift/source-to-image

- pkg/cmd/cli/cmd/deploy.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1323710
@ironcladlou PTAL
Do you think there is anything else to be done here?
> Bug 1323710: fix deploy --cancel message on subsequent calls

- Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/admission/namespace/lifecycle/admission.go
- Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/admission/namespace/lifecycle/admission_test.go
- pkg/cmd/server/kubernetes/master_config.go
- test/integration/namespace_lifecycle_admission_test.go
> Protect infra/shared resource namespaces

- images/router/egress/Dockerfile
> install iproute since the origin-base image dose not contain ip command

- test/extended/conformance.sh
- test/extended/core.sh
- test/extended/networking.sh
- test/extended/setup.sh
- test/extended/util/test.go
[testonlyextended][extended:conformance]
> Add a conformance test for extended
