openshift/origin

test/extended/cmd.sh
@deads2k @smarterclayton @bparees PTAL
=> refactored test/extended/cmd to use os::cmd

assets/app/views/directives/environment.html
=> Naming inconsistancy fix

pkg/build/builder/source.go
=> Always set the Cmd for source Docker image

test/extended/conformance.sh, test/extended/core.sh, test/extended/setup.sh
=> Support focus arguments on both conformance and core

hack/util.sh
I'm forcing to download docker logs to help debug #8399.
@smarterclayton ptal
=> Getting docker logs always to debug issue 8399

test/extended/fixtures/build-quota/.s2i/bin/assemble
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>
=> Add debugs for CPU Quota flake

pkg/cmd/cli/cmd/deploy.go, pkg/cmd/cli/describe/projectstatus.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1324437
@ironcladlou PTAL
=> Bug 1324437: show cancel as subordinate to non-terminating phases

hack/test-go.sh
This pull adds new behavior to `hack/test-go` when used with `JUNIT_REPORT=true`. Now, `go test` fails but `junitreport` finds no failed *tests*, a nice message is printed to indicate that it's most likely a compilation error. `junitreport` now also exits with an error code of 3 if any failed tests were found. Furthermore, we not longer eat `stderr` from `go test` for `junitreport` and if `go test` printed anything to `stderr` during the run, we print it out afterword.
Sample output:
```
$ JUNIT_REPORT=true hack/test-go.sh tools/junitreport/...
++ Building go targets for linux/amd64: tools/junitreport
++ Placing binaries
hack/build-go.sh took 1 seconds
[INFO] Running `go test`...
ok  	github.com/openshift/origin/tools/junitreport/pkg/builder/flat	1.005s	coverage: 100.0% of statements
ok …
```
=> made hack/test-go handle compilation errors better when generating jUnit reports

Godeps/Godeps.json
godep bump to match https://github.com/openshift/kubernetes/commits/release-1.2-stable-20160316
@liggitt @pweil- I'd like a force-merge to make sure the marker is in the right spot.
=> bump(k8s.io/kubernetes): 114a51dfbc43a8bcf07db1774a20e05d560e34b0

examples/sample-app/README.md
- 'pre-setted' -> 'preset'
@bparees PTAL
=> Improve wording in sample-app README

assets/bower.json
https://github.com/openshift/origin/pull/8412#issuecomment-208534710
@jwforres PTAL
@smarterclayton CC
=> Fix bindata diff for new font-awesome release

origin.spec
Per request of Red Hat docker team.
CC: @lsm5
=> [RPMS] Switch requires from docker-io to docker

test/extended/networking.sh
See the individual commit messages for details.
=> Improve networking extended test reliability

pkg/cmd/cli/cmd/example.go
Makes it easier to spin up new commands
=> Add an example CLI command

docs/generated/oc_by_example_content.adoc, pkg/cmd/cli/cmd/set/triggers.go
fixes https://github.com/openshift/origin/issues/8534#event-631167646
=> remove trailing = from set trigger example

pkg/dockerregistry/client.go
=> Add client debugging for legacy dockerregistry code

contrib/vagrant/provision-config.sh, hack/dind-cluster.sh
As per suggestions from @stevekuznetsov and code from @danwinship.
cc: @openshift/networking
=> dind: Clean up check for ready nodes

test/extended/setup.sh
Extended suite changes
[testonlyextended][extended:core]
=> Exclude deployment tests and set a perf test to serial

hack/test-cmd.sh
=> moved jUnit report for test-cmd to be consistent

test/extended/networking.sh
=> Add summary status message to network test runner

test/extended/builds/s2i_dropcaps.go
@bparees @csrwng more extended test debug
=> debug for failures on jenkins

test/extended/builds/docker_quota.go, test/extended/builds/dockerfile.go, test/extended/builds/forcepull.go, test/extended/builds/gitauth.go, test/extended/builds/image_source.go, test/extended/builds/s2i_dropcaps.go, test/extended/builds/s2i_env.go, test/extended/builds/s2i_incremental.go, test/extended/builds/s2i_quota.go, test/extended/images/s2i_perl.go, test/extended/images/s2i_php.go, test/extended/images/s2i_python.go, test/extended/images/s2i_ruby.go, test/extended/util/framework.go, test/extended/util/image_helpers.go
=> debug for ext test failures on jenkins

origin.spec
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1311220
=> [RPMS] Tighten permissions on config file locations

hack/common.sh, hack/extract-release.sh, test/cmd/basicresources.sh
=> Fix basicresources.sh for bad version check

pkg/image/importer/client.go, pkg/image/importer/client_test.go
Added tests
@liggitt review for merge
=> Open() is called in the pullthrough code path and needs retry

Godeps/Godeps.json, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/common.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/ovs/controller.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/ovs/plugin.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/registry.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/subnets.go
Fix for issue https://github.com/openshift/openshift-sdn/issues/291 (priority/p0) => https://github.com/openshift/openshift-sdn/pull/292
Better/more SDN logging for debugging networking problems => https://github.com/openshift/openshift-sdn/pull/296, https://github.com/openshift/openshift-sdn/pull/295
Remove unnecessary cookies from node ovs rules => https://github.com/openshift/openshift-sdn/pull/274, https://github.com/openshift/openshift-sdn/pull/294
=> bump(github.com/openshift/openshift-sdn) ba3087afd66cce7c7d918af10ad

hack/util.sh, pkg/cmd/cli/cmd/debug.go, pkg/cmd/flagtypes/glog.go
Only changes that already have LGTM and passing as existing pulls.
This will be the first merge to 1.3
=> Post 1.2 server merges

pkg/oauth/server/osinserver/registrystorage/storage.go
=> Improve logging of missing authorization codes

pkg/router/f5/f5.go
The F5 iControl REST API sometimes returns error responses with HTML payloads instead of JSON.  (This has been observed for HTTP 401 and 404 responses.) Gracefully handle such responses by ignoring the error and response payload for HTTP 4xx and 5xx responses if decoding fails.
Before this commit, if the F5 iControl REST API returned an HTML response, the rest_request method would return an error that rendered as follows:
error: Decoder.Decode failed: invalid character '<' looking for beginning of value
After this commit the rest_request method will produce an error that renders similar to the following:
error: HTTP code: 401.
This commit fixes bug 1316463.
https://bugzilla.redhat.com/show_bug.cgi?id=1316463
-
[test]
-
@ramr
=> F5: handle HTML responses gracefully

docs/generated/oc_by_example_content.adoc, pkg/cmd/cli/cli.go, pkg/cmd/cli/cmd/newapp.go, pkg/cmd/cli/cmd/request_project.go
fixes https://github.com/openshift/ruby-hello-world/issues/54
=> switch new project example repo to one that doesn't need a db

test/extended/fixtures/build-quota/.s2i/bin/assemble
@bparees PTAL
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>
=> Add mount debug information for cpu quota test flake

pkg/cmd/admin/diagnostics/cluster.go, pkg/cmd/admin/diagnostics/host.go, pkg/diagnostics/cluster/metrics.go, pkg/diagnostics/cluster/service_externalip.go, pkg/diagnostics/host/check_master_config.go, pkg/diagnostics/host/check_node_config.go, pkg/diagnostics/host/util.go, pkg/service/admission/externalip_admission.go, test/cmd/diagnostics.sh
MetricsApiProxy and ServiceExternalIPs
=> introduce two new diagnostics

pkg/cmd/cli/cmd/deploy.go
Fixes https://github.com/openshift/origin/issues/7045
@smarterclayton @ironcladlou @pweil-
=> oc: fix help message for deploy

README.md
* Adds an IRC badge on top of the README (along with the other badges)
for improved visibility; opens a new browser window/tab with
webchat.freenode.net with pre-selected #openshift-dev.
Signed-off-by: Joao Goncalves <jsvgoncalves@redhat.com>
=> docs: add irc badge

hack/util.sh, pkg/cmd/flagtypes/glog.go
Also enable importer logging for server starts.
@liggitt
=> Support --logspec (glog -vmodule) for finegrained logging

pkg/cmd/cli/cmd/debug.go, test/cmd/debug.sh
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1330050
ptal @smarterclayton
=> Handle client-side errors on debug pod creation

pkg/build/api/v1/conversion.go, pkg/build/api/v1/conversion_test.go, pkg/build/api/v1/types.go, pkg/build/api/validation/validation.go, pkg/build/api/validation/validation_test.go, pkg/build/builder/docker.go, pkg/build/builder/docker_test.go, pkg/build/controller/strategy/custom_test.go, pkg/cmd/cli/describe/describer.go, pkg/cmd/cli/describe/describer_test.go, test/extended/builds/nosrc.go, test/extended/fixtures/test-nosrc-build.json
@bparees PTAL
fyi - I suspect you may want me to reorder the commits and squash the extended test commit with the dev commit, followed by the s2i godeps bump commit ... or maybe put the s2i bump first ? ... just let me know which way you want to go
Also a bit curious on the extended test
=> No input bc

Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/cmd.go
fixes https://github.com/openshift/origin/issues/8640
=> UPSTREAM: <carry>: add templates to valid_resources list

pkg/authorization/api/helpers.go, pkg/generate/app/app.go, pkg/generate/app/cmd/describe.go, pkg/generate/app/cmd/newapp.go, pkg/generate/app/cmd/template.go, pkg/generate/app/env.go, pkg/generate/app/imageref.go, pkg/generate/app/pipeline.go, pkg/generate/app/pipeline_test.go, pkg/generate/app/sourcelookup.go, test/cmd/newapp.sh
Should have 1:1 output, but makes it easier to do deeper generation.
@csrwng @bparees (may still have broken tests)
=> Refactors to generation in preparation for compose

Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/clock.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/clock_test.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/workqueue/default_rate_limiters.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/workqueue/default_rate_limiters_test.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/workqueue/delaying_queue.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/workqueue/delaying_queue_test.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/workqueue/queue.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/workqueue/rate_limitting_queue.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/workqueue/rate_limitting_queue_test.go
Picks the new delaying workqueue and rate limiting workqueue.
I want these for the service serving cert signer and docker pull secret controllers.
@liggitt needs them for SA controller
@stevekuznetsov probably wants them for a "max RCs on a DC" controller.
@liggitt you comfortable taking the upstream review too?
=> work queue pulls

contrib/vagrant/provision-config.sh, contrib/vagrant/provision-dind.sh, contrib/vagrant/provision-master.sh, contrib/vagrant/provision-util.sh, hack/common.sh, hack/dind-cluster.sh
Misc cleanup suggested by @stevekuznetsov in #8506 and #8522.
=> Cleanup dind provision

Godeps/Godeps.json
Fixed to point to https://github.com/openshift/kubernetes/commit/61d1935e4fbaf5b9dd43ebd491dd33fa0aeb48a0 .
It happened picking pulls back, then squashing back in.
=> update godep commit

pkg/generate/app/cmd/template.go, test/cmd/newapp.sh
Fixes #8668, condition was reversed.  Need to add a test
=> Template parameters broken in new-app

test/end-to-end/core.sh
=> Do not stop tests

pkg/generate/app/cmd/newapp.go, pkg/generate/app/cmd/resolve.go, test/cmd/newapp.sh, test/integration/newapp_test.go
fixes https://github.com/openshift/origin/issues/4207
=> warn if image is not a builder, even if it came from source detection

pkg/cmd/dockerregistry/dockerregistry.go
Also enable the proxy code.
@liggitt @pweil- review please
=> Enable the gcs, oss, and inmemory storage drivers in registry

Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/edit.go
ref issue: https://bugzilla.redhat.com/show_bug.cgi?id=1316352
=> Bug 1316352: use platform-agnostic helper in oc edit

assets/app/scripts/services/data.js
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1331324
=> Handle null items array from bad api responses

pkg/api/graph/interfaces.go, pkg/build/graph/analysis/bc.go, pkg/build/graph/helpers.go, pkg/deploy/graph/analysis/dc.go
=> oc: dont warn for missing istag in case of in-flight build

pkg/cmd/cli/cmd/process.go, test/cmd/process.sh, test/fixtures/template_required_params.yaml
Updates failure modes for `oc process` so that the command exits early and yells when something is wrong.
/cc @fabianofranz 
@deads2k PTAL
=> update failure conditions for oc process

assets/.jshintrc, assets/app/index.html, assets/app/scripts/controllers/create.js, assets/app/scripts/controllers/create/createFromImage.js, assets/app/scripts/controllers/modals/confirmReplaceModal.js, assets/app/scripts/controllers/modals/processTemplateModal.js, assets/app/scripts/controllers/newfromtemplate.js, assets/app/scripts/controllers/overview.js, assets/app/scripts/directives/fromFile.js, assets/app/scripts/directives/oscFileInput.js, assets/app/scripts/directives/oscRouting.js, assets/app/scripts/directives/parseError.js, assets/app/scripts/services/cachedTemplate.js, assets/app/scripts/services/data.js, assets/app/scripts/services/navigate.js, assets/app/styles/_core.less, assets/app/views/_parse-error.html, assets/app/views/create.html, assets/app/views/directives/from-file.html, assets/app/views/directives/osc-routing.html, assets/app/views/modals/confirm-replace.html, assets/app/views/modals/confirmScale.html, assets/app/views/modals/delete-resource.html, assets/app/views/modals/edit-resource.html, assets/app/views/modals/process-template.html, assets/app/views/newfromtemplate.html
Adding option to add to project any component that we expose to the users. For this I've created a separate tab in the 'Add to project' page, together with 'From Docker Image'.
Component could be added in a multiple ways:
1. Browse trough the file on users local machine by hitting the "Browse" button right to the input field. 
2. Paste component description into ace editor beneath the input field.
3. Drag and Drop the file from users local machine to the area of the input field or ace editor.
JSON and YAML format are supported.
Also upon componet creation a check is being done to find out whether a component with the same name doesn't exist in current project. If it exists it will be replaced** with the new one. If it doesn't it will be created.
** The way how replacing is working is that …
=> Upload component during the create flow

assets/app/views/modals/delete-resource.html
Use a form and make the button `type="submit"` so that the enter keys works when typing the project name to delete.
@jwforres PTAL
=> Accessibility: make enter key work when confirming project name

Godeps/Godeps.json, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/common.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/factory/factory.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/ovs/controller.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/ovs/plugin.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/registry.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/subnets.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/vnids.go, pkg/cmd/server/kubernetes/node_config.go, pkg/cmd/server/start/node_args.go
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1323279 : https://github.com/openshift/openshift-sdn/pull/293 
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1320959 : https://github.com/openshift/openshift-sdn/pull/302
Make SDN watch resources more resilient: https://github.com/openshift/openshift-sdn/pull/289
Refer SDN plugin names and annotations by constants: https://github.com/openshift/openshift-sdn/pull/301
=> bump(github.com/openshift/openshift-sdn) c709df994a5bbecfa80fae62c201

pkg/cmd/server/bootstrappolicy/policy.go, test/fixtures/bootstrappolicy/bootstrap_cluster_roles.yaml
Fixes https://github.com/openshift/origin/issues/8714
Also cleans up the API groups in the roles I touched.
@legionus ptal
=> let registry-admin delete his project

pkg/cmd/cli/cmd/debug.go
This came up while I was fighting with nginx.  I needed to know the pod IP so that I could curl it.  This isn't very useful for remote debugging sessions, but debugging pods when you're running in the infrastructure or when you can start up a busybox pod in the same namespace, this is useful.
@stevekuznetsov @fabianofranz
=> show pod IP during debug

test/extended/networking.sh
Jenkins relies on the build log to detect failure cause, but the
networking test runner was previously not outputting dind container
logs.  This change ensures that container logs are output to stdout when
deployment failures occur to maximize the chances of jenkins being able
to detect deployment-related flakes.
cc: @openshift/networking
=> Output logs on network e2e deployment failure

examples/jenkins/jenkins-ephemeral-template.json, examples/jenkins/jenkins-persistent-template.json
=> Increase initialDelay for Jenkins livenessprobe

Godeps/Godeps.json, Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/api/describe/describer.go, Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/api/types.go, Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/api/types_test.go, Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti.go, Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/docker/docker.go, Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/errors/errors.go, Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/util/injection.go, Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/util/injection_test.go, pkg/build/builder/sti.go, pkg/generate/app/sourcelookup.go
makes https://github.com/openshift/origin/issues/8737 debuggable.
=> bump(github.com/openshift/source-to-image): c99ef8b29e94bdaf62d5d5aefa74d12af6d37e3c

pkg/util/docker/dockerfile/builder/builder.go, pkg/util/docker/dockerfile/builder/builder_test.go, pkg/util/docker/dockerfile/builder/client.go, pkg/util/docker/dockerfile/builder/conformance_test.go, pkg/util/docker/dockerfile/builder/copyinfo.go
`oc ex dockerbuild` was not recording failures from exec.
@mfojtik
[test]
=> Return error from exec

pkg/cmd/cli/cmd/dockerbuild/dockerbuild.go, pkg/util/docker/dockerfile/builder/client.go
Pulling was broken because the upstream URL was wrong.
@mfojtik review
=> Add output logging to docker build and correctly pull

examples/db-templates/mongodb-ephemeral-template.json, examples/db-templates/mongodb-persistent-template.json, pkg/bootstrap/bindata.go
Fixes: https://github.com/openshift/origin/issues/8740
=> Replace mongostat with mongo in mongodb example template

assets/app/views/browse/_build-details.html, assets/app/views/browse/build-config.html, assets/app/views/builds.html, assets/app/views/create/next-steps.html
=> BZ 1332876 - Break long Git source URL

pkg/util/docker/dockerfile/builder/conformance_test.go
.dockerignore was stripping the dockerbuild sent to the daemon
[test]
=> Fix a problem with ignored Dockerfiles in db conformance

assets/app/views/create/next-steps.html
=> Use copy-to-clipboard for next steps webhook URL

assets/app/scripts/controllers/buildConfig.js, assets/app/scripts/controllers/deploymentConfig.js, assets/app/scripts/filters/resources.js, assets/app/scripts/services/data.js
[Original PR against console_1.3](https://github.com/jwforres/origin/pull/40) w/conversation.
@jwforres @spadgett @liggitt
=> Update data.js to handle fieldSelector/labelSelector

assets/app/scripts/directives/overviewDeployment.js
Fix a problem where the desired replicas are reset when a user scales in the window between when we make the scale request and when we get an updated replica count from the replication controller watch.
Also, increase lodash debounce wait to 1s from 500ms. I found 1s to generate much fewer requests in my testing while still feeling responsive.
https://bugzilla.redhat.com/show_bug.cgi?id=1333158
@jwforres PTAL
=> Fix timing issue scaling deployments

assets/app/views/deployments.html
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1332763
@jwforres or @spadgett, PTAL.
=> Bug fix to remove empty <tbody> that results in Firefox border rendering bug

tools/rebasehelpers/util/git.go
@smarterclayton should help us debug the Travis issue
=> made commitchecker error statements more verbose

pkg/util/leaderlease/leaderlease.go
Prevents spurious panic in error logs. Spotted in #7845.  Not for 1.2
[test]
=> Don't close the "lost" channel more than once

contrib/completions/bash/oc, contrib/completions/bash/openshift, pkg/cmd/cli/cmd/dockerbuild/dockerbuild.go, pkg/util/docker/dockerfile/builder/builder.go, pkg/util/docker/dockerfile/builder/client.go, pkg/util/docker/dockerfile/builder/dispatchers.go
=> Small fixes to dockerbuild

pkg/cmd/server/kubernetes/node_config.go
@ncdc @deads2k @liggitt @smarterclayton 
Still testing though.
=> Disable serial image pulls by default

assets/app/scripts/controllers/setLimits.js, assets/app/scripts/directives/editRequestLimit.js, assets/app/scripts/services/hpa.js, assets/app/scripts/services/limits.js, assets/app/views/create/fromimage.html, assets/app/views/set-limits.html
https://bugzilla.redhat.com/show_bug.cgi?id=1324825
https://bugzilla.redhat.com/show_bug.cgi?id=1331816
/cc @jwforres @derekwaynecarr
=> Calculate effective limit min in UI for request/limit ratio

assets/app/scripts/directives/fromFile.js
Dealing with following bugs:
https://bugzilla.redhat.com/show_bug.cgi?id=1333300
https://bugzilla.redhat.com/show_bug.cgi?id=1333651
https://bugzilla.redhat.com/show_bug.cgi?id=1333669
where each commit deals with an issue.
@spadgett PTAL
=> Add component to project bug fixes

assets/app/index.html, assets/bower.json
https://bugzilla.redhat.com/show_bug.cgi?id=1333163
=> Include ext-searchbox.js for Ace editor search

docs/generated/oc_by_example_content.adoc, pkg/cmd/cli/cmd/rollback.go
=> oc: update rollback example

test/integration/router/router_http_server.go, test/integration/router_test.go
As mentioned [in this comment](https://github.com/openshift/origin/pull/8490#issuecomment-214884895), the router's path-based integration tests only really go in-depth via HTTP. Issues can manifest on HTTP without manifesting on HTTPS and vice versa, as well as on WebSockets (for which there is no path-based route testing). As such, this pull request adds integration testing for all those scenarios.
=> Test path-based routing via HTTPS and WebSockets

assets/app/scripts/directives/buildTrendsChart.js
Treat x-axis values as strings (type: category) rather than numbers to avoid gaps in the chart. This prevents builds from bunching up at one side when many are deleted. See
https://bugzilla.redhat.com/show_bug.cgi?id=1333898
@jwforres PTAL
=> Remove gaps from build chart for deleted builds

Godeps/_workspace/src/k8s.io/kubernetes/pkg/storage/cacher.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/storage/cacher_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1334501
=> Return 'too old' errors from watch cache via watch stream

pkg/cmd/server/admin/create_mastercerts.go, pkg/cmd/server/admin/create_nodeconfig.go, pkg/cmd/server/admin/create_servercert.go, pkg/cmd/server/admin/default_certs.go, pkg/cmd/server/api/helpers.go, pkg/cmd/server/api/types.go, pkg/cmd/server/api/v1/swagger_doc.go, pkg/cmd/server/api/v1/types.go, pkg/cmd/server/api/v1/types_test.go, pkg/cmd/server/api/validation/master.go, pkg/cmd/server/bootstrappolicy/infra_sa_policy.go, pkg/cmd/server/crypto/crypto.go, pkg/cmd/server/origin/run_components.go, pkg/cmd/server/start/master_args.go, pkg/cmd/server/start/start_master.go, pkg/service/controller/servingcert/controller.go, pkg/service/controller/servingcert/controller_test.go, test/extended/cmd.sh, test/extended/fixtures/service-serving-cert/nginx-serving-cert.conf, test/fixtures/bootstrappolicy/bootstrap_cluster_roles.yaml
Adds an automatic serving cert generator for services.
@smarterclayton @liggitt
=> Make service serving certs

examples/jenkins/README.md
=> update jenkins example readme based on OpenShift Online testing

pkg/build/api/v1/conversion.go
@bparees PTAL
per direction from @smarterclayton in https://github.com/openshift/origin/pull/8821
=> migrate use of s.DefaultConvert to autoConvert

examples/db-templates/mysql-ephemeral-template.json, examples/db-templates/postgresql-ephemeral-template.json, examples/jenkins/jenkins-ephemeral-template.json, examples/quickstarts/cakephp-mysql.json, examples/quickstarts/dancer-mysql.json, examples/quickstarts/django-postgresql.json, examples/quickstarts/nodejs-mongodb.json, examples/quickstarts/rails-postgresql.json, pkg/bootstrap/bindata.go
@bparees PTAL
@php-coder @kargakis FYI
=> change BC ICT to automatic=true (more deterministic)

test/extended/builds/gitauth.go
=> disable gitauth tests

test/extended/images/mongodb_ephemeral.go, test/extended/images/mongodb_replica.go, test/extended/images/sample_repos.go, test/extended/jenkins/kubernetes_plugin.go, test/extended/jenkins/plugin.go
=> more spots to dump on error deployment logs in extended tests

Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/kubectl.go, Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/util.go
https://github.com/kubernetes/kubernetes/pull/25537
/cc @smarterclayton @pweil-
=> UPSTREAM: 25537: e2e make ForEach fail if filter is empty, fix no-op tests

pkg/cmd/cli/cmd/importer/dockercompose.go, pkg/generate/app/env.go, pkg/generate/dockercompose/generate.go, test/cmd/newapp.sh, test/fixtures/app-scenarios/docker-compose/wordpress/docker-compose.yml, third_party/github.com/docker/libcompose/project/merge.go
Also give all compose generated objects a label via the template.
@csrwng @bparees
=> Support schema2 of compose, set env vars properly

Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/pleg/generic.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/pleg/generic_test.go
Cherry pick for https://github.com/kubernetes/kubernetes/pull/25077
@ncdc @eparis
=> PLEG: reinspect pods that failed prior inspections

hack/vendor-console.sh
=> Add script for vendoring the console repo into bindata.go files

pkg/build/builder/cmd/builder.go, pkg/build/builder/cmd/scmauth/password.go, pkg/build/builder/cmd/scmauth/scmauths.go, pkg/build/builder/common.go, pkg/build/builder/docker.go, pkg/build/builder/dockerutil.go, pkg/build/builder/source.go, pkg/build/builder/sti.go, pkg/build/builder/util.go, pkg/cmd/infra/builder/builder.go, pkg/util/glog/glog.go, test/extended/builds/no_outputname.go
Also perform some minor cleanups along the way.
@bparees
=> Replace glog output in builders at V(2) and above with straight stderr output.

test/cmd/authentication.sh, test/fixtures/authentication/localsubjectaccessreview.json
Opened during reproduction of https://bugzilla.redhat.com/show_bug.cgi?id=1336312.
I can't reproduce the problem yet.
@kargakis quick look?  Very small.   [test]
=> localsubjectaccessreview test-cmd demonstration with scoped token

docs/proposals/label-associated-quota.md, docs/proposals/shared-quota.md
Writing up my initial thoughts on label based quota allocation.
@pweil- @derekwaynecarr
=> cross project quota options

pkg/authorization/authorizer/scope/authorizer.go, pkg/authorization/authorizer/scope/authorizer_test.go, pkg/cmd/server/origin/master_config.go, test/cmd/authentication.sh
The scopes forbidden message has been hard to read.  Add the human readable version of what you tried to submit.
@kargakis or @soltysh ptal.
=> make scopes forbidden message friendlier to read

Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/describe.go
Fixes #7901 
@kargakis @erinboyd @smarterclayton - please review
=> Fixes #7901 - Add Validated SCC Policy in oc describe

pkg/client/hostsubnets.go, pkg/client/testclient/fake_hostsubnets.go
=> Allow update on hostsubnets

docs/cluster_up_down.md
Help for the 'oc cluster [up|down]' commands
=> README for 'oc cluster up/down'

pkg/router/f5/plugin_test.go
Comment `newTestRouterWithState` and `newTestRouter`.
Delete workaround for slow ECDHE performance now that that issue has been resolved (per https://github.com/openshift/origin/issues/4417).
Close the mock F5 server when `TestInitializeF5Plugin` finishes.
Fix a potential `nil` pointer dereference in `TestF5RouterPartition`.
Fix a potential double-close in `TestF5RouterPartition`.
Related to https://github.com/openshift/origin/issues/8908
--
openshift-bot, please [test]!
@ramr
--
I'm not confident that these changes alone will resolve all the problems reported in the issue, but let's go ahead and see what happens when we fix the obvious problems...
=> F5: Cleanup mockF5.close() calls in tests

pkg/util/docker/dockerfile/builder/client.go
=> Restrict the scratch name to lowercase in the dockerbuilder

pkg/cmd/server/api/serialization_test.go
Fixes https://github.com/openshift/origin/issues/8947
@kargakis ptal
=> fix flaky configapi fuzzing for SA grant method

Godeps/Godeps.json, Godeps/_workspace/src/github.com/AaronO/go-git-http/README.md, Godeps/_workspace/src/github.com/AaronO/go-git-http/git_reader.go, Godeps/_workspace/src/github.com/AaronO/go-git-http/githttp.go, Godeps/_workspace/src/github.com/AaronO/go-git-http/pktparser.go, Godeps/_workspace/src/github.com/AaronO/go-git-http/pktparser_test.go, Godeps/_workspace/src/github.com/AaronO/go-git-http/rpc_reader.go, Godeps/_workspace/src/github.com/AaronO/go-git-http/rpc_reader_test.go
Fixes hang when pushing to gitserver and new-app is invoked
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1334147
=> Fix gitserver hang when cloning with --depth=1

test/fixtures/complete-dc-hooks.yaml
=> Longer timeout on test fixture DC

pkg/util/docker/dockerfile/builder/client.go
=> Docker image cannot have - or _ in succession

pkg/deploy/controller/deployment/controller.go
Fixes regression caused by https://github.com/openshift/origin/pull/8652
Ref https://bugzilla.redhat.com/show_bug.cgi?id=1338679
@smarterclayton @ironcladlou @mfojtik PTAL
=> Bug 1338679: emit events on failure to create a deployer pod

pkg/authorization/api/helpers.go, pkg/authorization/authorizer/remote/authorizer.go, pkg/build/admission/strategyrestrictions/admission.go, pkg/project/registry/projectrequest/delegated/delegated.go
Turns out we don't use it much.  Last commit is unique.
I'll add some tests
=> Respect scopes during SARs

pkg/cmd/server/start/start_allinone.go, test/cmd/admin.sh
=> Display a relevant error message when hostname is missing

Godeps/_workspace/src/k8s.io/kubernetes/pkg/admission/plugins.go, pkg/cmd/server/api/latest/helpers.go, pkg/cmd/server/api/register.go, pkg/cmd/server/api/types.go, pkg/cmd/server/api/v1/register.go, pkg/cmd/server/api/v1/swagger_doc.go, pkg/cmd/server/api/v1/types.go, pkg/cmd/server/kubernetes/master_config.go, pkg/cmd/server/start/admission.go, test/integration/admissionconfig_test.go
@csrwng alternative to https://github.com/openshift/origin/pull/8930
@derekwaynecarr what are my chances of getting that upstream patch merged?
=> Generic admission enablement

pkg/api/restmapper/discovery.go, pkg/cmd/util/clientcmd/factory.go, test/cmd/admin.sh
@mfojtik @soltysh Does this resolve your "hitting the wrong jobs endpoint" problem?
=> add discovery rest mapper

pkg/bootstrap/docker/errors/docker.go
Removes quotes from help message
Fixes #8997
=> cluster up: fix insecure registry argument message

Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/podautoscaler/horizontal_test.go
Fixes flake we hit here: https://github.com/openshift/origin/pull/8945#issuecomment-221265286
=> UPSTREAM: 24537: Add locks in HPA test

.travis.yml, hack/verify-gofmt.sh, hack/verify-golint.sh, hack/verify-govet.sh, origin.spec
=> Drop Go 1.4 conditions, switch to 1.6 by default

Makefile
Based on upstream's scripts. @smarterclayton ptal
=> Added update-all.sh and verify-all.sh to simplify API update process

pkg/build/builder/common.go, pkg/build/builder/source.go, pkg/generate/app/test/fakegit.go, pkg/generate/git/repository.go, pkg/generate/git/repository_test.go
Fixes https://github.com/openshift/origin/issues/8499
@deads2k @csrwng PTAL
=> made call to 'git ls-remote' in new-app time out after 10s

Godeps/Godeps.json, Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/api/types.go, Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti.go, Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti_test.go
Related PR: https://github.com/openshift/source-to-image/pull/509
PTAL @bparees
=> Update s2i to fix setting environment

Godeps/Godeps.json, Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/cmd/admin/network/isolate_projects.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/cmd/admin/network/join_projects.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/pkg/cmd/admin/network/make_projects_global.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/common.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/factory/factory.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/node_iptables.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/ovs/bin/openshift-sdn-ovs, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/ovs/plugin.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/ovs/proxy.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/registry.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/subnets.go, Godeps/_workspace/src/github.com/openshift/openshift-sdn/plugins/osdn/vnids.go, docs/generated/oadm_by_example_content.adoc, docs/generated/oc_by_example_content.adoc, pkg/cmd/server/api/v1/conversions.go, pkg/cmd/server/kubernetes/node_config.go
Depends on https://github.com/openshift/openshift-sdn/pull/313
=> bump(github.com/openshift/openshift-sdn) b74a40614df17a99b8f77ac0dbd9

pkg/cmd/cli/cmd/startbuild.go
=> Printing duplicate messages during startbuild

pkg/cmd/server/origin/audit.go, pkg/cmd/server/origin/audit_test.go, test/integration/audit_test.go
Fixes [bug1340344](https://bugzilla.redhat.com/show_bug.cgi?id=1340344). 
@danmcp @mfojtik ptal
=> Bug 1340344 - Add additional interfaces implementation for handling watches, rsh, etc.

test/util/etcd.go
Fixes https://github.com/openshift/origin/issues/9109.
@stevekuznetsov 
[test]
=> test-integration etcd verbosity controlled by OSTEST_VERBOSE_ETCD

examples/jenkins/master-slave/jenkins-master-template.json
@bparees Please help to merge.
Thanks
=> Update jenkins-master-template.json context

pkg/cmd/cli/cmd/deploy.go, pkg/deploy/api/test/ok.go, pkg/deploy/controller/imagechange/controller.go, pkg/deploy/controller/imagechange/controller_test.go, pkg/deploy/registry/deployconfig/strategy.go, pkg/deploy/util/util.go
Fixes https://github.com/openshift/origin/issues/9120
@ironcladlou @smarterclayton @mfojtik
=> deploy: restore ict behavior for deploymentconfig with no cc triggers

Godeps/Godeps.json, Godeps/_workspace/src/github.com/openshift/source-to-image/pkg/tar/tar.go
Fixes https://github.com/openshift/origin/issues/9072
=> bump(github.com/openshift/source-to-image): 2abf650e2e65008e5837266991ff4f2aed14bf39

hack/test-end-to-end.sh, hack/util.sh
Lets `TEST_END_TO_END=direct hack/test-end-to-end.sh` work again.
@stevekuznetsov
=> unbreak e2e after DNS and oc cluster up

pkg/cmd/cli/cmd/project.go
=> oc: inform about switch to the same project

Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/admission.go, Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/admission_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1333122
=> UPSTREAM: 25161: Sort resources in quota errors to avoid duplicate events

pkg/cmd/flagtypes/glog.go
/cc @jorgemoralespou 
fixes #9052
=> Updated allowed levels of `glog` info levels in CLI doc

Godeps/_workspace/src/k8s.io/kubernetes/pkg/quota/evaluator/core/pods.go, Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/resource_quota.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1332944
=> UPSTREAM: 24514: Quota ignores pod compute resources on updates

Godeps/_workspace/src/k8s.io/kubernetes/pkg/quota/evaluator/core/pods.go, Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/admission_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1318931
=> UPSTREAM: 25487: pod constraints func for quota validates resources

pkg/api/serialization_test.go, pkg/deploy/api/v1/defaults.go
Fixes https://github.com/openshift/origin/issues/9155
@smarterclayton @deads2k
=> api: fix serialization test for deploymentconfigs

Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux.go
@smarterclayton @derekwaynecarr
=> UPSTREAM: 25907: Fix detection of docker cgroup on RHEL

pkg/cmd/cli/describe/describer_test.go
Fixes https://github.com/openshift/origin/issues/9139
@csrwng PTAL
@bparees FYI
=> deflake second level timing issue in TestDescribeBuildDuration

pkg/cmd/cli/cmd/set/probe.go, pkg/cmd/cli/cmd/set/triggers.go
Adds an output version and allows pass-thru of objects that were not modified by the command.
Enables changing a list of objects that are streamed in, like:
```
$ oc new-app https://my.git.repo -o yaml | oc set probe --liveness --open-tcp=8080 -f - -o yaml | oc create -f - 
```
=> oc set probe/triggers: set output version

pkg/oauth/api/validation/validation.go
simplifies rune creation, fixes bug checking `]` endpoint
@deads2k
=> fix scope character validation

pkg/deploy/registry/deployconfig/strategy.go
@smarterclayton @ironcladlou @mfojtik
=> deploy: ignore set lastTriggeredImage on create

examples/db-templates/mysql-persistent-template.json, pkg/bootstrap/bindata.go
- Remove lots of noise from the template
- Mark required field as required
=> Clean MySQL template defaults

images/router/haproxy/conf/haproxy-config.template
We want to use more the one router on the same node => Router sharding.
There is also a bugzilla entry https://bugzilla.redhat.com/show_bug.cgi?id=1343083
=> Add the both ROUTER_SERVICE*SNI_PORT

pkg/client/localsubjectaccessreview.go, pkg/client/subjectaccessreview.go, pkg/generate/app/cmd/template.go
reported by https://goreportcard.com/report/github.com/openshift/origin#ineffassign
mostly shadowing issues
=> fix some ineffassign issues

pkg/scheduler/admission/podnodeconstraints/admission.go, pkg/scheduler/admission/podnodeconstraints/admission_test.go
@deads2k thanks for https://github.com/openshift/origin/pull/8941 this is for the admission in podnodecostraints as discussed. 
Hope I understood what you meant.
=> SCC check API: add admission in podnodeconstraints

images/release/Dockerfile.golang142, images/release/Dockerfile.golang162
=> New release images locked to Go versions

pkg/util/docker/dockerfile/builder/client.go
=> Be more selective about what we generate for build names

examples/jenkins/pipeline/README.md
=> Add instructions for downloading oc and using hosted template

test/integration/service_account_test.go
=> Retry service account update on conflict

api/swagger-spec/oapi-v1.json, pkg/api/v1beta3/deep_copy_generated.go, pkg/authorization/api/casts.go, pkg/authorization/api/deep_copy_generated.go, pkg/authorization/api/types.go, pkg/authorization/api/v1/conversion.go, pkg/authorization/api/v1/deep_copy_generated.go, pkg/authorization/api/v1/swagger_doc.go, pkg/authorization/api/v1/types.go, pkg/authorization/api/v1beta3/conversion.go, pkg/authorization/api/v1beta3/types.go, pkg/authorization/registry/policybinding/strategy.go, pkg/authorization/registry/role/policybased/virtual_storage.go, pkg/authorization/registry/rolebinding/policybased/virtual_storage.go, pkg/cmd/cli/describe/describer.go, pkg/cmd/cli/describe/printer.go
Fixes https://github.com/openshift/origin/issues/9290
[test]
=> remove lastModified from policy and policybinding

CONTRIBUTING.adoc, HACKING.md
=> Update CONTRIBUTING and HACKING docs

api/swagger-spec/oapi-v1.json, pkg/api/v1beta3/deep_copy_generated.go, pkg/authorization/api/casts.go, pkg/authorization/api/deep_copy_generated.go, pkg/authorization/api/types.go, pkg/authorization/api/v1/conversion.go, pkg/authorization/api/v1/deep_copy_generated.go, pkg/authorization/api/v1/swagger_doc.go, pkg/authorization/api/v1/types.go, pkg/authorization/api/v1beta3/conversion.go, pkg/authorization/api/v1beta3/types.go, pkg/authorization/registry/policybinding/strategy.go, pkg/authorization/registry/role/policybased/virtual_storage.go, pkg/authorization/registry/rolebinding/policybased/virtual_storage.go, pkg/cmd/cli/describe/describer.go, pkg/cmd/cli/describe/printer.go
Reverts openshift/origin#9300
[merge]
=> Revert "remove lastModified from policy and policybinding"

hack/test-cmd.sh, pkg/cmd/util/clientcmd/factory.go
=> correct precision in the no config file message

examples/atomic-registry/README.md
from 'origin' to 'projectatomic'
=> change arg for inspect command

pkg/cmd/cli/cmd/debug.go
=> Update the jsonpath template link in oc get -h

pkg/cmd/server/origin/master_config.go, pkg/cmd/server/origin/run_components.go, pkg/cmd/server/start/start_master.go, pkg/deploy/api/test/ok.go, pkg/deploy/controller/generictrigger/controller.go, pkg/deploy/controller/generictrigger/controller_test.go, pkg/deploy/controller/generictrigger/factory.go, pkg/deploy/controller/imagechange/controller.go, pkg/deploy/controller/imagechange/controller_test.go
For more context, see https://github.com/openshift/origin/pull/9132#issuecomment-224017049
@smarterclayton @ironcladlou @mfojtik PTAL
=> Switch config change to a generic trigger controller

pkg/bootstrap/docker/openshift/admin.go
constant was already defined but not being used
@csrwng
=> admin.go use defined constant instead of string

pkg/image/api/helper.go, pkg/image/api/helper_test.go, pkg/image/registry/imagestream/strategy_test.go
@smarterclayton you gonna love this one :stuck_out_tongue_winking_eye:
=> Bug 1343681 - Fix tagsChanged logic

docs/generated/oc_by_example_content.adoc, pkg/cmd/cli/cmd/wrappers.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1316157
=> Fixes examples of port-forward

test/extended/deployments/deployments.go
[testextended][extended:core(should never run a new)]
=> Failure in extended deployment test

Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/cmd_test.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/create.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/create_test.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/replace.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory_test.go, pkg/cmd/util/clientcmd/factory.go
=> Move print method in the factory

api/swagger-spec/oapi-v1.json, pkg/api/validation/register.go, pkg/oauth/api/validation/validation.go, pkg/oauth/api/validation/validation_test.go, pkg/oauth/registry/oauthaccesstoken/etcd/etcd.go, pkg/oauth/registry/oauthaccesstoken/strategy.go, pkg/oauth/registry/oauthauthorizetoken/etcd/etcd.go, pkg/oauth/registry/oauthauthorizetoken/strategy.go
Still need to add tests to verify this is actually not mutating since we have none.
[test]
@liggitt to support migrate
=> Add immutable updates on access and authorize tokens

docs/generated/oc_by_example_content.adoc, pkg/cmd/cli/cmd/wrappers.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1316157
=> Fixes deprecated oc exec examples

Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/dockertools/kube_docker_client.go
Track https://github.com/kubernetes/kubernetes/issues/27588
Fixes #9221 
[test]
=> UPSTREAM: <drop>: Disable timeouts on kubelet pull and logs

pkg/cmd/cli/cmd/rsync/copymulti.go
Added newline print to warning when individual strategies fail, also changed return to report the correct issue.
fixes #8505
=> Fixes issue #8505 (https://github.com/openshift/origin/issues/8505)

pkg/api/install/install.go
=> Add fast path conversions for Origin resources

pkg/cmd/cli/describe/printer.go
Fixes https://github.com/openshift/origin/issues/9357
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1344898
=> Fixes router printer line breaks

Godeps/Godeps.json
@eparis @liggitt 
https://github.com/openshift/origin/commit/e20b7480b71d75bc7d165bef35e0788009cc4e0f did not update Godeps.json
=> fixup coreos dep bump

pkg/template/template.go, pkg/template/template_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1199391
Redo of botched pull request https://github.com/openshift/origin/pull/9237
Nothing has changed from that pull
@bparees
=> Made output of error more specific to bad parameter

Godeps/Godeps.json, hack/install-etcd.sh
Replacement for #9445 
@sjenning @smarterclayton
=> bump(coreos/etcd): fix etcd hash in Godeps.json

pkg/cmd/util/clientcmd/clientcmd.go, pkg/cmd/util/clientcmd/clientcmd_test.go
@deads2k I hope I did this right ;-)
=> Add missing fuzzers for AnonymousConfig test

Godeps/_workspace/src/k8s.io/kubernetes/pkg/controller/controller_utils.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory_test.go, pkg/deploy/registry/deploylog/rest.go, pkg/deploy/registry/deploylog/rest_test.go
@mfojtik @ironcladlou @deads2k
=> Change sorting logic for deployment logs

test/extended/images/mysql_replica.go
MySQL replication template has been updated in https://github.com/sclorg/mysql-container/pull/151 and broke extended tests.
Fixed by adding additional PV for the slave and lifting the capacity.
As an aside, I've enabled replication testing for 5.5 and hopefully It'll work.
@csrwng @bparees @rhcarvalho
=> Update MySQL replication tests to reflect new template

images/ipfailover/keepalived/lib/failover-functions.sh
fixes #9101 
@smarterclayton  PTAL thx
=> Trap sigterm and cleanup - remove any assigned VIPs.

pkg/deploy/strategy/support/lifecycle.go, test/extended/deployments/deployments.go, test/extended/deployments/util.go, test/extended/testdata/failing-pre-hook.yaml
Fixes https://github.com/openshift/origin/issues/9422
@smarterclayton @mfojtik @ironcladlou PTAL
=> deploy: reread hook logs on Retry

Godeps/_workspace/src/k8s.io/kubernetes/pkg/storage/etcd/api_object_versioner.go, Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/admission.go, Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/admission_test.go, Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/controller.go, Godeps/_workspace/src/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/resource_access.go, pkg/quota/admission/resourcequota/admission.go
Prereqs needed for cluster quota.  These are all merged or lgtm'ed upstream.
=>  cluster quota

docs/generated/oc_by_example_content.adoc, pkg/cmd/cli/cmd/wrappers.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1344877
=> Fixes examples of oc proxy

hack/build-images.sh
Fix for https://github.com/openshift/origin/issues/9431
=> Fix docker tag command in hack/build-images.sh

pkg/api/kubegraph/analysis/pod.go, pkg/api/kubegraph/analysis/pod_test.go, pkg/cmd/cli/describe/projectstatus_test.go
fixes #9437 
Tests are a bit ugly...
=> Don't state crashlooping container when pod only has one container

pkg/deploy/controller/deploymentconfig/controller.go
fixes https://github.com/openshift/origin/issues/9505
@kargakis gotcha!
@smarterclayton detection works :)
Also, I'm not really a fan of the way branches affect data for the rest of the branches.  Extra controllers are nearly free, can this be made simpler by breaking it into pieces?
[test]
=> dc controller was mutating cache objects

Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/typed/discovery/discovery_client.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubectl/resource/selector.go, pkg/api/restmapper/discovery.go, pkg/authorization/registry/policybinding/strategy.go, pkg/authorization/registry/role/policybased/virtual_storage.go, pkg/authorization/registry/role/policybased/virtual_storage_test.go, pkg/authorization/registry/rolebinding/policybased/virtual_storage.go, pkg/authorization/registry/rolebinding/policybased/virtual_storage_test.go, pkg/client/client.go, pkg/client/discovery.go, pkg/cmd/util/clientcmd/factory.go
* Don't modify policies when they don't change. Fixes #9290
* Cleanup discovery a bit
* Handle a cache race
* Better message from server
=> Prepare for migration

pkg/cmd/cli/describe/chaindescriber.go, pkg/cmd/cli/describe/chaindescriber_test.go
Fixes https://github.com/openshift/origin/issues/3902
@kargakis @deads2k @bparees PTAL
=> handle cyclic dependencies in build-chain

.gitignore, .travis.yml, contrib/vagrant/provision-util.sh, hack/install-etcd.sh, hack/test-go.sh, hack/util.sh
=> make clean removes _tools

test/integration/buildcontroller_test.go
fixes https://github.com/openshift/origin/issues/9503
=> increase watch timeout for build controller test

hack/test-local-registry.sh
Aids in local development, run a local registry and test push /
interactions.
[merge] @minimar
=> Add a simple script for starting a local docker registry

api/swagger-spec/oapi-v1.json, pkg/client/deploymentconfigs.go, pkg/client/testclient/fake_deploymentconfigs.go, pkg/cmd/cli/cmd/rollback.go, pkg/cmd/server/bootstrappolicy/policy.go, pkg/cmd/server/origin/master.go, pkg/deploy/api/deep_copy_generated.go, pkg/deploy/api/types.go, pkg/deploy/api/v1/conversion_generated.go, pkg/deploy/api/v1/deep_copy_generated.go, pkg/deploy/api/v1/swagger_doc.go, pkg/deploy/api/v1/types.go, pkg/deploy/api/v1beta3/types.go, pkg/deploy/api/validation/validation.go, pkg/deploy/api/validation/validation_test.go, pkg/deploy/registry/rollback/rest.go, pkg/deploy/registry/rollback/rest_deprecated.go, pkg/deploy/registry/rollback/rest_deprecated_test.go, pkg/deploy/registry/rollback/rest_test.go, pkg/deploy/registry/rollback/rollback_generator.go, pkg/deploy/registry/rollback/rollback_generator_test.go, test/cmd/deployments.sh, test/extended/deployments/deployments.go, test/integration/authorization_test.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
@smarterclayton @ironcladlou I want to use the new endpoint in `oc rollout undo`. Thoughts?
=> Rollback rework

test/extended/builds/start.go
fixes https://github.com/openshift/origin/issues/9525
=> use valid commit for binary build test

pkg/cmd/server/kubernetes/master_config.go, pkg/cmd/server/origin/master_config.go, pkg/cmd/server/origin/reststorage_validation_test.go, pkg/controller/shared/authorization_informers.go, pkg/controller/shared/deploy_informers.go, pkg/controller/shared/doc.go, pkg/controller/shared/imagestream_informers.go, pkg/controller/shared/legacy_kube_informers.go, pkg/controller/shared/shared_informer.go, pkg/project/admission/lifecycle/admission_test.go
=> controller: move shared informers in separate package

test/extended/builds/run_policy.go
fixes https://github.com/openshift/origin/issues/9533
=> restructure run policy test and add logging

test/extended/testdata/test-imagesource-build.yaml
fixes https://github.com/openshift/origin/issues/9530
=> add configchange trigger so deploy happens on imagechange

pkg/build/builder/cmd/builder.go, pkg/build/builder/common.go, pkg/build/builder/docker.go, pkg/build/builder/source.go, pkg/build/builder/sti.go, pkg/util/glog/glog.go
Attempting to address concerns on #9247
fixes https://github.com/openshift/origin/issues/9524
=> Changing logging statments to Clayton's spec

pkg/cmd/cli/cmd/set/env.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1304251
=> Fixes oc set env --overwrite=false with multiple resources

test/extended/images/sample_repos.go
fixes https://github.com/openshift/origin/issues/6835
=> force a db deployment in extended template tests

test/integration/deploy_trigger_test.go
Fixes https://github.com/openshift/origin/issues/9560
[test]
=> integration: update test to use only image change trigger

pkg/cmd/cli/cmd/projects.go
fixes https://github.com/openshift/origin/issues/9574
=> fix spacing and project displayname in oc projects output

pkg/cmd/server/origin/master.go, pkg/router/f5/f5.go, pkg/service/controller/servingcert/controller.go, pkg/serviceaccounts/controllers/create_dockercfg_secrets.go
Fixes https://github.com/openshift/origin/issues/9586
[test]
=> remove underscores from function names

pkg/dockerregistry/server/auth.go
follow up from https://github.com/openshift/origin/pull/9593/files/860fa7f54f78603891afc4d5918ca615015c44d9#r68868992
@smarterclayton nits unpicked
=> Registry auth cleanup

hack/test-go.sh, hack/test-integration.sh, test/extended/networking.sh
=> Enable unit test debug with delve

hack/test-end-to-end.sh
Without passing `--images=`, the image will default to
`openshift/origin-${component}:${version}`.
=> e2e: honor $USE_IMAGES during registry's deployment

docs/generated/oadm_by_example_content.adoc, docs/generated/oc_by_example_content.adoc, docs/man/man1/oadm-completion.1, docs/man/man1/oc-adm-completion.1, docs/man/man1/oc-completion.1, docs/man/man1/openshift-admin-completion.1, docs/man/man1/openshift-cli-adm-completion.1, docs/man/man1/openshift-cli-completion.1, docs/man/man1/openshift-completion.1, pkg/cmd/cli/cmd/wrappers.go
Addresses: https://bugzilla.redhat.com/show_bug.cgi?id=1349240
=> Update completion help to use root command in examples

Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/delta_fifo_test.go, Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/fifo.go
Fixes https://github.com/openshift/origin/issues/9638
merged upstream, fixes flake and correctness problem
[merge]
=> UPSTREAM: 27435: Fix bugs in DeltaFIFO

examples/image-streams/image-streams-centos7.json, examples/image-streams/image-streams-rhel7.json, pkg/bootstrap/bindata.go, test/cmd/newapp.sh
nodejs-4-centos is not available yet, will do a followup pull when it is.
=> add new SCL version imagestreams

docs/man/man1/oc-new-app.1, docs/man/man1/openshift-cli-new-app.1, pkg/cmd/cli/cmd/newapp.go
=> Note that new-app --env flag doesn't apply to templates

test/extended/deployments/deployments.go
Closes https://github.com/openshift/origin/issues/9652
=> extended: test for iterative deployments

hack/util.sh, test/end-to-end/core.sh
fixes https://github.com/openshift/origin/issues/9512
=> disable stack tracing for curl operations in e2e

test/integration/deploy_scale_test.go
Fixes https://github.com/openshift/origin/issues/9443
@mfojtik PTAL
=> integration: wait for synced config before testing autoscaling

pkg/cmd/cli/cmd/debug.go, pkg/cmd/cli/cmd/set/probe.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1322665
=> Fixes usage for oc set probe and oc debug

test/end-to-end/core.sh
=> Clean up test/end-to-end/core.sh

docs/generated/oc_by_example_content.adoc, docs/man/man1/oc-convert.1, docs/man/man1/openshift-cli-convert.1, pkg/cmd/cli/cmd/wrappers.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1309217
=> Fixes oc convert examples

pkg/image/prune/prune.go, pkg/image/prune/prune_test.go
Fixes #9702.
@miminar @legionus ptal
=> Issue 9702 - consider schema v2 layers when pruning

pkg/client/cache/deploymentconfig.go, pkg/client/cache/imagestream.go
=> cache: return api errors on not found imagestreams/deploymentconfigs

examples/sample-app/README.md
updated #9150
btw couldn't find a drop-down for repo in UI editor so submitting the regular way
=> we are already production ready

contrib/vagrant/provision-util.sh
in lieu of #8882 
@danwinship @openshift/networking - Minor change
=> allow cni as one of the plugins

test/extended/dns/dns.go
[test]
Fixes the most recent problem in #9192
=> Fix a DNS flake by watching for pod succeeded

test/extended/deployments/deployments.go
=> No info about deployer pods logged

Godeps/Godeps.json, hack/godep-restore.sh
Should be accurate post rebase
@ncdc @liggitt
=> Update godep-restore to latest

images/dind/Dockerfile
=> dind: update to f24 (and go 1.6)

vendor/k8s.io/kubernetes/pkg/client/unversioned/clientcmd/loader.go
Fixes https://github.com/openshift/origin/issues/9581
@fabianofranz hold for rebase.
=> UPSTREAM: 28500: don't migrate files you can't access

pkg/generate/app/cmd/newapp.go
=> Parameter validation for new-app strategy

test/extended/networking/isolation.go, test/extended/networking/pod_network_cli.go, test/extended/networking/services.go, test/extended/networking/util.go
Trello card: https://trello.com/c/r6pvGxVR/179-2-add-tests-for-pod-network-admin-cli-commands-supportability-techdebt
=> Added tests for pod-network CLI command

test/integration/authorization_test.go, test/util/etcd.go
Adds debugging for https://github.com/openshift/origin/issues/9803
@smarterclayton @soltysh review in principle, I'd like to merge this.  I'm willing to add it to add the tests if we want to.
=> add etcd dump for integration test

test/integration/deploy_trigger_test.go
=> integration: add multiple ict deployment test

test/integration/sa_oauthclient_test.go
Change poll to retry on conflict, refetch each time in order to actually retry with new data
fixes https://github.com/openshift/origin/issues/8701#issuecomment-232556736
=> Fix SA OAuth test flake

pkg/generate/app/dockerimagelookup_test.go, pkg/generate/app/test/fakedocker.go, test/integration/newapp_test.go
Fixes https://github.com/openshift/origin/issues/9219
=> Re-enable new-app integration tests

test/extended/jobs/jobs.go
=> Add jobs to conformance run

pkg/build/controller/factory/factory.go, pkg/controller/controller_test.go, pkg/deploy/controller/imagechange/factory.go, pkg/deploy/strategy/support/lifecycle.go, pkg/image/controller/factory.go, pkg/project/controller/factory.go, pkg/security/controller/factory.go, vendor/k8s.io/kubernetes/pkg/client/cache/fifo.go, vendor/k8s.io/kubernetes/pkg/client/cache/fifo_test.go
fixes https://github.com/openshift/origin/issues/9842
Keep all items so that you can resync without doing a relist.
=> Fix resync for fifo controllers

pkg/deploy/api/deep_copy_generated.go, pkg/deploy/api/types.go, pkg/deploy/api/v1/deep_copy_generated.go, pkg/deploy/api/v1/types.go, pkg/deploy/controller/deploymentconfig/controller.go, test/extended/deployments/deployments.go
=> deploy: update revisionHistoryLimit to int32

vendor/k8s.io/kubernetes/pkg/kubectl/cmd/attach.go, vendor/k8s.io/kubernetes/pkg/kubectl/cmd/run.go
Fixes comment 1 of https://bugzilla.redhat.com/show_bug.cgi?id=1341450
=> UPSTREAM: 27263: Cherry-picked "Dynamically derive AttachOptions.CommandName"

pkg/generate/app/cmd/describe.go
=> oc new-app: add missing single quote

hack/env, images/release/golang-1.6/Dockerfile, images/release/golang-1.7/Dockerfile
=> Enable protoc in the release images

pkg/cmd/util/tokencmd/negotiator_gssapi.go
Fixes #9909 
@liggitt I no longer get a `panic` when performing `oc login` on a machine that has Kerberos libraries installed but not configured with an auth proxy server that supports GSSAPI with no BASIC fallback.
=> Copy GSSAPI errors to prevent use-after-free bugs

vendor/k8s.io/kubernetes/pkg/kubectl/describe.go, vendor/k8s.io/kubernetes/pkg/kubectl/sorted_resource_name_list.go
Fixes: https://github.com/openshift/origin/issues/9576
=> UPSTREAM: 28966: Describe container volume mounts

pkg/cmd/cli/cmd/rollback.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1356530
@mfojtik @deads2k
=> Bug 1356530: handle 403 in oc rollback

pkg/deploy/api/v1/defaults.go, pkg/deploy/api/validation/validation.go
Also update the validation message for a missing tag for the istag name.
@openshift/api-review @mfojtik
=> Bug 1357668: update error message on invalid tags in ICTs

pkg/cmd/cli/describe/deployments.go
=> Remove deployment trigger warning

hack/test-cmd.sh
related to https://github.com/openshift/origin/issues/9929
Need to get an etcd dump in order to debug the problem
@stevekuznetsov ptal
=> gather dump before you kill the process

pkg/cmd/admin/registry/registry.go, test/cmd/admin.sh
Fix #8820 
@soltysh @miminar @kargakis
=> add default resource requests to registry creation

pkg/authorization/api/helpers.go, pkg/authorization/interfaces/interfaces.go, pkg/authorization/rulevalidation/find_rules.go
Addresses part of #9368, but still more work needed.
@deads2k [test]
=> Avoid allocations while checking role bindings

pkg/cmd/infra/deployer/deployer.go, pkg/cmd/infra/deployer/deployer_test.go
Fixes: https://github.com/openshift/origin/issues/8972
@kargakis ptal
=> Abort deployment when the from version is higher than to version

README.md
@pweil- this is the more detailed list, still not complete but please PTAL
=> List enabled/disabled features in readme.

pkg/deploy/api/v1/defaults.go, test/cmd/deployments.sh, test/testdata/old-template.json
=> deploy: stop defaulting to ImageStreamTag unconditionally

test/extended/deployments/deployments.go, test/extended/deployments/util.go, test/extended/testdata/generation-test.yaml
@mfojtik ptal
@smarterclayton fyi
=> extended: set failure traps in all deployment tests

pkg/image/prune/prune.go, pkg/image/prune/prune_test.go
Fixes #9846 and [bug 1341527](https://bugzilla.redhat.com/show_bug.cgi?id=1341527)
This patch switches image pruning to use image.DockerImageLayers instead of parsing `image.DockerImageManifest`. Additionally all log levels should be consistent in that all errors finding objects in graph are logged at level 2, the entire debug messages at level 4.
@miminar || @legionus ptal
=> Use image.DockerImageLayers for pruning

pkg/dockerregistry/client.go, test/integration/dockerregistryclient_test.go
=> Fix TestRegistryClientImageV1, TestRegistryClientImageV2

README.md
* Split paragraphs into smaller chunks to improve readability
* Update references to s2i images, which have been moved to sclorg and openshift-s2i
* Correct capitalization of language names (NodeJS -> Node.js, Wildfly -> WildFly)
=> README.md: Updates to "What can I run on Origin?" section

api/swagger-spec/oapi-v1.json, pkg/client/clusteresourcequota.go, pkg/client/testclient/fake_clusterresourcequota.go, pkg/cmd/server/bootstrappolicy/policy.go, pkg/cmd/server/origin/helpers.go, pkg/cmd/server/origin/master.go, pkg/quota/admission/clusterresourcequota/accessor.go, pkg/quota/admission/clusterresourcequota/accessor_test.go, pkg/quota/controller/clusterquotareconciliation/reconcilation_controller.go, pkg/quota/controller/clusterquotareconciliation/reconciliation_controller_test.go, pkg/quota/registry/clusterresourcequota/etcd.go, pkg/quota/registry/clusterresourcequota/strategy.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Adds a `status` subresource for clusterquota.
=> make clusterquota/status endpoint

vendor/k8s.io/kubernetes/pkg/quota/evaluator/core/services.go, vendor/k8s.io/kubernetes/pkg/quota/evaluator/core/services_test.go, vendor/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/admission_test.go
=> UPSTREAM: 29457: Quota was not counting services with multiple nodeports properly

test/end-to-end/core.sh
https://github.com/openshift/origin/issues/9888
Can't see why this is happening so remove it for now.
=> e2e test: remove PodCheckDns flake

docs/man/man1/oc-rsh.1, docs/man/man1/openshift-cli-rsh.1, pkg/cmd/cli/cmd/rsh.go
=> rsh: Insert TERM env variable into the command to be run

test/extended/gssapi.sh
- No longer build `oc` to reduce test time
- Use `os::cmd::expect_success` where possible thanks to PR #10084
- Minor BASH improvements
Fixes #10113
=> Kerberos Extended Test Improvements

pkg/client/cache/securitycontextconstraints.go, pkg/cmd/admin/router/router.go, pkg/cmd/server/origin/run_components.go, pkg/cmd/server/start/start_master.go, pkg/controller/shared/securitycontextconstraints_informers.go, pkg/controller/shared/shared_informer.go, pkg/security/admission/admission.go, pkg/security/admission/admission_test.go, pkg/security/admission/scc_exec.go, pkg/security/admission/scc_exec_test.go, pkg/security/scc/matcher.go, test/integration/buildcontroller_test.go
@deads2k context in email sent you
=> SCC admission with sharedIndexInformer

examples/gitserver/README.md
The URL of git server should be updated, now it looks like this "git-myproject.router.default.svc.cluster.local"
=> update the URL of git server

test/cmd/basicresources.sh, test/cmd/projects.sh
Break `oc projects` tests to separate file
=> mv oc projects tests to separate file

pkg/quota/admission/clusterresourcequota/admission.go, test/integration/clusterquota_test.go, test/integration/endpoint_admission_test.go, test/integration/imagesigning_test.go, test/integration/pod_node_constraints_test.go, test/integration/runonce_duration_test.go
=> prove clusterquota works with image streams

pkg/cmd/openshift/openshift.go
=> use an unused parameter

docs/cluster_up_down.md
1. Modify the repo URL for configuring git to sync the fork with the upstream repository.
2. Fix a link for docker machine which can be used to access accurately the content in the document.
Please check them.
Thanks!
signed-off-by: wang.yuexiao@zte.com.cn
=> Modify the repo URL and the link

contrib/systemd/origin-accounting.conf, origin.spec
Related to https://github.com/kubernetes/kubernetes/pull/17688#issuecomment-220447268
=> [RPMS] Enable CPU and Memory accounting during node installation

images/release/golang-1.4/Dockerfile
No longer possible to Go install Go 1.4
[test]
=> Upstream packages for Go 1.4 have been dropped

vendor/k8s.io/kubernetes/pkg/credentialprovider/gcp/metadata.go, vendor/k8s.io/kubernetes/pkg/credentialprovider/gcp/metadata_test.go, vendor/k8s.io/kubernetes/pkg/credentialprovider/provider.go
/cc @ncdc @pmorie
One of two cherry-picks needed to fix: https://bugzilla.redhat.com/show_bug.cgi?id=1353251
=> UPSTREAM: 28871: Do not use metadata server to know if on GCE

vendor/k8s.io/kubernetes/pkg/credentialprovider/gcp/metadata.go
/cc @ncdc @pmorie 
One of two cherry-picks needed for https://bugzilla.redhat.com/show_bug.cgi?id=1353251
=> UPSTREAM: 28539: Fix httpclient setup for gcp

vendor/k8s.io/kubernetes/test/e2e/framework/util.go, vendor/k8s.io/kubernetes/test/e2e/kubelet.go, vendor/k8s.io/kubernetes/test/e2e/scheduler_predicates.go
Fixes #10182
[test]
@ncdc / @pmorie review please
=> UPSTREAM: 29847: Race condition in scheduler predicates test

pkg/build/builder/sti.go
To address this [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1363944) , @PI-Victor @php-coder 
, could you please help review ?
=> Support image forcePull policy for runtime image when do extended build

api/swagger-spec/api-v1.json, api/swagger-spec/oapi-v1.json, vendor/k8s.io/kubernetes/api/swagger-spec/v1.json, vendor/k8s.io/kubernetes/pkg/api/v1/conversion.go, vendor/k8s.io/kubernetes/pkg/api/v1/conversion_generated.go, vendor/k8s.io/kubernetes/pkg/api/v1/deep_copy_generated.go, vendor/k8s.io/kubernetes/pkg/api/v1/generated.pb.go, vendor/k8s.io/kubernetes/pkg/api/v1/generated.proto, vendor/k8s.io/kubernetes/pkg/api/v1/types.go, vendor/k8s.io/kubernetes/pkg/api/v1/types_swagger_doc_generated.go
https://github.com/kubernetes/kubernetes/pull/28263
@liggitt @ncdc @smarterclayton
=> UPSTREAM: 28263: Allow specifying secret data using strings

examples/project-quota/README.md
when I learn the project-quota example , I found some outputs should be updated.
=> update the output of quota example

pkg/util/netutils/subnet_allocator_test.go
Add more info for test case. Just a nit.
=> Add more info for test case

origin.spec
A few bugs were fixed to allow rpm building in a koji environment.
=> fix rpm spec file to properly build man pages dynamically

examples/db-templates/mongodb-ephemeral-template.json, examples/db-templates/mongodb-persistent-template.json, pkg/bootstrap/bindata.go
=> Add MongoDB connection URL to template message

pkg/deploy/controller/deployment/controller_test.go
Fix some typos in deployment.
Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>
=> Fix some typos in deployment

pkg/image/registry/imagestreamimage/rest_test.go, pkg/image/registry/imagestreamtag/rest_test.go
fixes https://github.com/openshift/origin/issues/10302
view ignoring whitespace for sanity - https://github.com/openshift/origin/pull/10301/files?w=1
=> Clean up test etcd data in test loops

pkg/cmd/cli/describe/projectstatus_test.go
fixes https://github.com/openshift/origin/issues/10319
=> Fix test compile error

examples/db-templates/mariadb-ephemeral-template.json, examples/db-templates/mariadb-persistent-template.json, examples/db-templates/mongodb-ephemeral-template.json, examples/db-templates/mongodb-persistent-template.json, examples/db-templates/mysql-ephemeral-template.json, examples/db-templates/mysql-persistent-template.json, examples/db-templates/postgresql-ephemeral-template.json, examples/db-templates/postgresql-persistent-template.json, pkg/bootstrap/bindata.go
fixes https://github.com/openshift/origin/issues/10295
=> better description for db username/password parameters

images/router/haproxy/conf/haproxy-config.template
validate inputs from ROUTER_SLOWLORIS_TIMEOUT
Take a suggestion from the comments in https://bugzilla.redhat.com/show_bug.cgi?id=1328037 on timeout
http-keep-alive
=> fix some bugs with ROUTER_SLOWLORIS_TIMEOUT

pkg/build/cmd/doc.go, pkg/build/cmd/reaper.go, pkg/build/cmd/reaper_test.go, pkg/build/reaper/doc.go, pkg/cmd/util/clientcmd/factory.go
mirroring https://github.com/openshift/origin/pull/9692
@kargakis ptal
=> move cmd tools to common build cmd package

images/router/haproxy/conf/haproxy-config.template
https://bugzilla.redhat.com/show_bug.cgi?id=1341312
=> Addressing the issues identified in BZ 1341312

pkg/build/builder/docker.go, pkg/build/builder/dockerutil.go
When I read the code of building process, i found that there are 9 parameters in func 'buildImage'.  So many parameters that are inappropriate, I think we can add some parameters refactoring which make the code more easier to read.
=> refactor buildImage function parameters

pkg/quota/controller/clusterquotamapping/clusterquotamapping.go, pkg/quota/controller/clusterquotareconciliation/reconcilation_controller.go, pkg/quota/controller/clusterquotareconciliation/workqueuebucket.go, vendor/k8s.io/kubernetes/pkg/controller/resourcequota/resource_quota_controller.go, vendor/k8s.io/kubernetes/pkg/util/workqueue/delaying_queue.go, vendor/k8s.io/kubernetes/pkg/util/workqueue/delaying_queue_test.go, vendor/k8s.io/kubernetes/pkg/util/workqueue/metrics.go, vendor/k8s.io/kubernetes/pkg/util/workqueue/queue.go, vendor/k8s.io/kubernetes/pkg/util/workqueue/rate_limitting_queue.go, vendor/k8s.io/kubernetes/pkg/util/workqueue/rate_limitting_queue_test.go
Adds metrics to the clusterquota controller so we can see what's running slow in the HA env.
@liggitt can you help me with magic incantation to get a dev ami?
=> Add quota controller metrics

pkg/build/builder/sti_test.go
add missing tests for sti builder in `pkg/build/builder/sti_test.go`
=> complete sti builder tests

pkg/build/generator/generator.go
PTAL @bparees @PI-Victor 
@bparees  If it's not an urgent let me test it a bit more, tomorrow, when I'll continue with extended tests.
Fixes #10214
=> SourceStrategy: assign PullSecret when only RuntimeImage needs it

pkg/cmd/cli/describe/describer.go, pkg/cmd/cli/describe/printer.go
Reverts openshift/origin#10239
=> Revert "Bug 1281735 - remove the internal docker registry information from imagestream"

images/release/golang-1.7/Dockerfile
=> Update to released Go 1.7

pkg/cmd/templates/templater.go, pkg/cmd/templates/templates.go
Reverts openshift/origin#10360
=> Revert "add suggestion to use `describe` to obtain container names"

pkg/client/deploymentconfigs.go, pkg/deploy/cmd/reaper.go, test/extended/deployments/deployments.go
Fixes https://github.com/openshift/origin/issues/9866
@mfojtik ptal
=> extended: retry on update conflicts in deployment tests

pkg/cmd/server/bootstrappolicy/policy.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Fix #8759 
@deads2k please review
=> Allow registry-admin and registry-editor create serviceaccounts

images/dockerregistry/config.yml, pkg/cmd/dockerregistry/dockerregistry.go, pkg/dockerregistry/server/auth.go, pkg/dockerregistry/server/auth_test.go, pkg/util/httprequest/httprequest.go, pkg/util/httprequest/httprequest_test.go
Fixes https://github.com/openshift/origin/issues/10193 and https://bugzilla.redhat.com/show_bug.cgi?id=1367610
=> Use scheme/host from request for token redirect

pkg/sdn/plugin/controller.go, pkg/sdn/plugin/proxy.go
following up from IRC; SDN startup currently bails out if it can't read the list of EgressNetworkPolicy objects, which means if you upgrade and don't reconcile roles, the cluster will break. This patch makes it just print a warning instead.
In terms of security; no one is going to already have EgressNetworkPolicy objects before upgrading, and presumably the first time they tried to add one, they would test to see if it actually worked, so even if they didn't see the warning, they would notice there was a problem before the non-enforcement of EgressNetworkPolicy became a security issue. Although, they have to restart each node after reconciling, so there could be a situation where even after reconciling, some nodes were able to implement EgressNetworkPolicy and others weren't...
@liggitt …
=> Allow startup to continue even if nodes don't have EgressNetworkPolicy list permission

test/integration/imagestream_admission_test.go
Retry on quota exceeded after incrementing limits. The admission plugin
may hit a cache with outdated value.
Closes #9780
=> integration: fix imagestream admission flake

vendor/k8s.io/kubernetes/pkg/apiserver/watch.go, vendor/k8s.io/kubernetes/pkg/apiserver/watch_test.go
=> UPSTREAM: 30736: Close websocket watch when client closes

docs/man/man1/oc-extract.1, docs/man/man1/openshift-cli-extract.1, pkg/cmd/cli/cmd/extract.go, vendor/k8s.io/kubernetes/pkg/kubectl/resource/builder.go, vendor/k8s.io/kubernetes/pkg/kubectl/resource/builder_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1366529
[test]
=> Extract should default to current directory

Godeps/Godeps.json
@smarterclayton let's get this done
=> bump(k8s.io/kubernetes): 447cecf8b808caa00756880f2537b2bafbfcd267

vendor/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/admission_test.go, vendor/k8s.io/kubernetes/plugin/pkg/admission/resourcequota/controller.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1367733
xref https://github.com/kubernetes/kubernetes/pull/30796
/cc @ncdc
=> UPSTREAM: 30796: Quota usage checking ignores unrelated resources

images/router/haproxy/conf/haproxy-config.template
Filled in the rest of the comment about the pass-through case.  Made
the comment cover the additional edge termination case.  Clarified the
wording to make it clear what happens for each termination type.
Fixes bug 1368031
=> Fixed the comment about the different backends we make

vendor/k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache/cache.go, vendor/k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache/cache_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1368155
@ncdc
[test]
=> UPSTREAM: 29093: Fix panic race in scheduler cache from 28886

pkg/cmd/server/api/helpers.go, pkg/cmd/server/api/validation/master.go, pkg/cmd/server/api/validation/master_test.go, pkg/cmd/server/origin/master_config.go, pkg/cmd/server/origin/run_components.go
=> Disable ingress ip when cloud provider enabled

test/integration/deploy_trigger_test.go
Fixes: https://github.com/openshift/origin/issues/10336
=> Retry updating deployment config instead of creating new one in test

images/origin/Dockerfile
=> Remove VOLUME from Origin image

pkg/build/builder/cmd/dockercfg/cfg.go
we should merge the same error handling code.
=> merge duplicate code

test/extended/deployments/util.go
This PR will make debugging the flakes and failures in deployment extended test nicer by showing the YAML version of the resources instead of Go structs.
=> Improve the output of deployment failure trap in extended test

hack/common.sh
Causes files to be created in the root of the project
=> -pkgdir should not be root of project

vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/index.go, vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/index_test.go
=> UPSTREAM: 30690: Don't bind pre-bound pvc & pv if size request not satisfied

pkg/build/builder/source.go
This will solve the intermittent output issue
@bparees ptal?
=> Now check for length on error array

vendor/k8s.io/kubernetes/pkg/kubectl/history.go
xref kubernetes/kubernetes#25308
[test]
=> UPSTREAM: 25308: fix rollout nil panic issue

vendor/k8s.io/kubernetes/pkg/util/wsstream/stream.go, vendor/k8s.io/kubernetes/pkg/util/wsstream/stream_test.go
=> UPSTREAM: 31047: Close websocket stream when client closes

test/end-to-end/core.sh, test/extended/deployments/deployments.go, test/extended/testdata/tag-images-deployment.yaml
Closes https://github.com/openshift/origin/issues/8078
@mfojtik
=> test: move e2e deployment test in extended suite

pkg/build/controller/factory/factory.go
fixes https://github.com/openshift/origin/issues/9830
@smarterclayton ptal
=> retrieve keys from cache.Delta objects properly

api/README.md
updated script name
Clearer instructions
=> update swagger dev README

pkg/cmd/server/origin/master.go, pkg/project/registry/projectrequest/delegated/delegated.go, test/integration/project_request_test.go
Cleans up projects that fail halfway through a project creation, reported in https://bugzilla.redhat.com/show_bug.cgi?id=1367432
=> Clean up requested project if there are errors creating template items

examples/jenkins/master-slave/jenkins-master-template.json
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1368967
=> increase jenkins readiness timeout

pkg/cmd/cli/cmd/debug.go, vendor/k8s.io/kubernetes/pkg/client/unversioned/conditions.go
xref https://bugzilla.redhat.com/show_bug.cgi?id=1364017
xref https://github.com/kubernetes/kubernetes/pull/31150
cc @smarterclayton @fabianofranz
=> Support init containers in 'oc debug'

docs/generated/oc_by_example_content.adoc, docs/man/man1/oc-new-app.1, docs/man/man1/openshift-cli-new-app.1, pkg/cmd/cli/cmd/newapp.go
Improve oc new-app examples:
- remove duplicates
- replace deprecated --image option
- minor improvement
PTAL @bparees
=> New app example improvements

pkg/sdn/plugin/subnets.go
When running with the GCE cloud provider, kubelet code adds an initial
NetworkUnavailable condition to each node which is supposed to be cleared
by the cloud route controller.  Overlay networks (like flannel or
openshift-sdn) don't need the route controller for inter-node
communication, but kubelet code that adds the initial condition
only knows about flannel.
Until we can teach upstream kubelet code that some network plugins
don't need the initial NetworkUnavailable condition set, remove that
condition when openshift-sdn creates the node's HostSubnet.
https://bugzilla.redhat.com/show_bug.cgi?id=1357474
=> sdn: clear kubelet-created initial NetworkUnavailable condition on GCE

hack/update-generated-completions.sh, hack/update-generated-docs.sh
Update the description in script as follows:
update-generated-completions.sh
update-generated-docs.sh
Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>
=> Update the description in script

pkg/deploy/registry/deploylog/rest.go, pkg/deploy/registry/deploylog/rest_test.go, pkg/deploy/registry/rest.go, pkg/deploy/util/util.go
Fixes: https://github.com/openshift/origin/issues/9627
Fixes: https://github.com/openshift/origin/issues/10002 (hopefully)
=> Wait for deployer pod to be running before getting logs

test/integration/imageimporter_test.go
Fixes: https://github.com/openshift/origin/issues/7706
=> Remove NotV2Registry check from redhat registry import test

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go, vendor/k8s.io/kubernetes/pkg/util/limitwriter/limitwriter.go, vendor/k8s.io/kubernetes/pkg/util/limitwriter/limitwriter_test.go, vendor/k8s.io/kubernetes/pkg/util/wsstream/stream.go
fixes https://github.com/openshift/origin/issues/10601
upstream at https://github.com/kubernetes/kubernetes/pull/31446
=> UPSTREAM: 31446: fix delay establishing log streaming connection

pkg/sdn/plugin/proxy.go
When I wrote the code I was thinking there was no way we could update the proxy endpoints when EgressNetworkPolicy changed, because we'd have to get the proxier code to call into our filter again... but it would be OK because the next time the proxier resync'ed everything, we'd update things. Wrong on both counts; we can force an update by just calling the baseEndpointsHandler, and we *have to* do that because the period resync doesn't call our filterer again, it just reuses the most-recently-received list of endpoints.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1369750
Bug 1369750
@openshift/networking PTAL
=> Regenerate proxy iptables rules on EgressNetworkPolicy change

pkg/sdn/api/v1/generated.proto
i think someone forgot to run this whenever they updated the file.
@bparees PTAL. 
p.s: also i don't think we do a good job checking for this as we do for swagger-specs/desc, any ideas for a fix?
=> fix protobuff generation for pkg/sdn/api/v1/generated.proto

hack/common.sh
[test]
Fixes problem identified in #10697
=> Return the exit code of the hack/env container

test/extended/deployments/deployments.go
@mfojtik the test already checks for the amount, I just made it exact
[test]
=> extended: require old deployments to be equal to the expected amount

test/extended/testdata/tag-images-deployment.yaml
@mfojtik for the failure in https://github.com/openshift/origin/pull/10704
=> extended: bump deployment timeout for test about tagging

pkg/authorization/rulevalidation/policy_comparator.go, pkg/authorization/rulevalidation/policy_comparator_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1372579
=> Reconcile non-resource-urls

hack/common.sh, hack/release.sh
Also elide the extra git commit value in a release archive name if it exactly matches.
[test]
=> Release should pass OS_GIT_COMMIT as a commit, not a tag

docs/cli.md
website changed for openshift and can be accessed directly
=> website changed for openshift and can be accessed directly

docs/router_sharding.md
Fix some typos for router_sharding.md
=> Fix some typos for router_sharding.md

test/integration/service_account_test.go
=> Retry service account update correctly

pkg/cmd/server/bootstrappolicy/infra_sa_policy.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
@smarterclayton missing pieces from the rebase to make scheduled jobs work
=> Added necessary policies for running scheduled jobs

HACKING.md
=> Fix invalid hyperlink.

Godeps/Godeps.json, vendor/github.com/coreos/etcd/auth/range_perm_cache.go, vendor/github.com/coreos/etcd/clientv3/balancer.go, vendor/github.com/coreos/etcd/clientv3/watch.go, vendor/github.com/coreos/etcd/discovery/srv.go, vendor/github.com/coreos/etcd/etcdserver/server.go, vendor/github.com/coreos/etcd/pkg/fileutil/dir_unix.go, vendor/github.com/coreos/etcd/pkg/fileutil/dir_windows.go, vendor/github.com/coreos/etcd/pkg/fileutil/fileutil.go, vendor/github.com/coreos/etcd/pkg/ioutil/pagewriter.go, vendor/github.com/coreos/etcd/version/version.go, vendor/github.com/coreos/etcd/wal/encoder.go, vendor/github.com/coreos/etcd/wal/wal.go, vendor/github.com/coreos/etcd/wal/wal_unix.go, vendor/github.com/coreos/etcd/wal/wal_windows.go
=> bump(github.com/coreos/etcd):v3.0.9

CONTRIBUTING.adoc
=> Delete the extra dot

pkg/deploy/util/util.go, test/extended/deployments/deployments.go, test/extended/deployments/util.go, test/integration/deploy_scale_test.go
Also fix HasSynced utility to accept a different generation other the one
in the deployment config.
=> extended: update polling for deployment tests

pkg/cmd/server/bootstrappolicy/policy.go, pkg/cmd/server/bootstrappolicy/policy_test.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
pick of https://github.com/openshift/origin/pull/10851
=> Ensure system:master has full permissions on non-resource-urls

pkg/cmd/server/api/serialization_test.go, pkg/cmd/server/api/v1/conversions.go
pick of https://github.com/openshift/origin/pull/10926
=> Default qps/burst to historical values

test/extended/deployments/deployments.go, test/extended/deployments/util.go, test/extended/testdata/readiness-test.yaml
Closes https://github.com/openshift/origin/issues/9752
@mfojtik
=> extended: add readiness test for initial deployments

pkg/sdn/plugin/controller.go, pkg/sdn/plugin/eventqueue.go, pkg/sdn/plugin/eventqueue_test.go, pkg/sdn/plugin/proxy.go, pkg/sdn/plugin/registry.go, pkg/sdn/plugin/subnets.go, pkg/sdn/plugin/vnids_master.go, pkg/sdn/plugin/vnids_node.go
The OpenShift controller cache should not be used in new code and is eventually going away.
See https://github.com/openshift/origin/pull/9981#discussion_r71818202
@openshift/networking @danwinship @pravisankar @smarterclayton
=> sdn: move from EventQueue to DeltaFIFO

CONTRIBUTING.adoc
=> The promt is missed

examples/zookeeper/Dockerfile, examples/zookeeper/config-and-run.sh
=> Run zookeeper as non-root user. Fix zookeeper conf volumeMount.

CONTRIBUTING.adoc
=> The 'eg' is should be 'e.g.', and 'for example' is better here

images/ipfailover/keepalived/README.md
=> Add bash symbol

test/integration/dns_test.go, test/integration/shortcut_expansion_test.go
Remove all tmp directory and add a break is better.
=> remove all tmp dir after test

pkg/deploy/registry/deployconfig/etcd/etcd.go
Fix a func name from  NewStorage  to NewREST  and modify the description for return value.
Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>
=> Fix a func name and return value in the comment 

pkg/deploy/strategy/support/lifecycle.go, test/extended/deployments/deployments.go, test/extended/testdata/deployment-with-ref-env.yaml
Fixes: https://github.com/openshift/origin/issues/10831
@kargakis @bparees PTAL
=> Preserve valueFrom when merging envs in deployment strategy params

docs/man/man1/oc-create-clusterresourcequota.1, docs/man/man1/openshift-cli-create-clusterresourcequota.1, pkg/cmd/cli/cmd/create/clusterquota.go, pkg/cmd/cli/cmd/create/clusterquota_test.go, pkg/quota/api/validation/validation.go, test/cmd/quota.sh
Fixes https://github.com/openshift/origin/issues/10877 (client-side part)
=> Fix clusterresourcequota annotations validation

pkg/build/controller/strategy/util.go
using just like `dockercfg.PullSourceAuthType`
=> use const string for auth type if exist

pkg/build/controller/strategy/util.go, pkg/build/controller/strategy/util_test.go
fixes https://github.com/openshift/origin/issues/10863
@csrwng ptal
@bdecoste fyi, will get this ported to 3.3.1.
=> use a unique volume name for each input image secret

pkg/generate/app/cmd/newapp.go, pkg/generate/app/cmd/resolve.go, pkg/generate/app/sourcelookup.go, pkg/generate/git/repository.go
=> Use errors.New() instead of fmt.Errorf() where possible.

pkg/image/registry/imagestreamimage/rest.go, test/integration/v2_docker_registry_test.go
Makes the name you requested match the name you get.
@jwforres See how this works out for you.
@smarterclayton you're the one who made them mismatch.  Objections?
[test]
=> return back the name you GETed for ISI

pkg/security/scc/matcher.go
@mfojtik  ref #8199 and #8776
FYI @deads2k
=> SCC check API: refactor

test/extended/deployments/deployments.go, test/extended/deployments/util.go
=> extended: fix latest deployment test flakes 

pkg/generate/app/cmd/describe.go
=> Simplify binary build output in new-build #11000

examples/image-streams/image-streams-centos7.json, pkg/bootstrap/bindata.go, test/cmd/debug.sh, test/cmd/images_tests.sh, test/cmd/newapp.sh
Added wildfly 10.1 spec pointing to wildfly-101-centos7.
Updated wildfly:latest to 10.1 image stream.
=> add wildfly 10.1 spec

docs/router_sharding.md, examples/db-templates/README.md
=> The VS and dot is seprated

vendor/k8s.io/kubernetes/pkg/util/cache/lruexpirecache.go, vendor/k8s.io/kubernetes/plugin/pkg/admission/namespace/lifecycle/admission.go, vendor/k8s.io/kubernetes/plugin/pkg/admission/namespace/lifecycle/admission_test.go
=> UPSTREAM: 33464: Fix cache expiration check

images/release/golang-1.7/Dockerfile
=> Update the release image to released Go 1.7.1

pkg/api/graph/test/dc-with-claim.yaml, pkg/api/graph/test/runtimeobject_nodebuilder.go, pkg/api/kubegraph/nodes/nodes.go, pkg/api/kubegraph/nodes/types.go, pkg/cmd/cli/describe/projectstatus.go, pkg/deploy/graph/analysis/dc.go, pkg/deploy/graph/analysis/dc_test.go, pkg/deploy/graph/edges.go
An oc status warning for rolling deployments with RWO volumes.
@deads2k @smarterclayton @mfojtik 
@thoraxe fyi
=> oc: warn for rolling deployments with RWO volumes

pkg/cmd/cli/cli.go, pkg/cmd/cli/cmd/buildlogs.go, pkg/cmd/cli/cmd/logs.go, pkg/cmd/cli/cmd/logs_test.go, pkg/cmd/cli/cmd/newapp.go, pkg/cmd/cli/cmd/newapp_test.go, pkg/cmd/cli/cmd/newbuild.go, pkg/cmd/cli/cmd/newbuild_test.go, pkg/cmd/cli/cmd/request_project.go, pkg/cmd/cli/cmd/request_project_test.go
Refactor based on openshift cmd guidelines and added unit tests for request_project and newapp cli command.
This is the old #10314 
@fabianofranz PTAL
=> Refactor and add unit tests to cli cmd request_project and newapp

pkg/cmd/cli/cmd/newapp.go, pkg/cmd/cli/cmd/newbuild.go, pkg/util/labels.go, test/cmd/newapp.sh, test/testdata/template-without-app-label.json
fixes the new-app (but not the console) part of https://github.com/openshift/origin/issues/9314
@jwforres fyi.
=> only set app label if it is not present on any object

pkg/cmd/server/bootstrappolicy/infra_sa_policy.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1378796
=> Allow job controller to get jobs

.tito/lib/origin/builder/__init__.py
Fix for https://github.com/openshift/origin/issues/11125
Signed-off-by: Adam Miller <maxamillion@fedoraproject.org>
=> fix tito builder now that provides exceeds argument restriction on subprocess

HACKING.md, cmd/dockerregistry/main.go, pkg/cmd/server/start/kubernetes/kubernetes.go, pkg/cmd/server/start/start_allinone.go
Fixes https://github.com/openshift/origin/issues/7925
=> add option to set ip for profile endpoint

api/swagger-spec/openshift-openapi-spec.json, hack/update-generated-swagger-spec.sh
=> Fix unclosed tag in OpenAPI spec

pkg/generate/app/sourcelookup_test.go
=> line continue should be instead by break

hack/build-cross.sh, hack/common.sh
This PR will make sure that build-cross.sh script works on power64le platform.
=> Add ppc64le platform support for build-cross.sh script

test/extended/deployments/deployments.go
@mfojtik ptal
Fixes https://github.com/openshift/origin/issues/10663
=> extended: bump image tagging timeout

pkg/diagnostics/cluster/aggregated_logging/diagnostic.go, pkg/diagnostics/cluster/aggregated_logging/kibana.go, pkg/diagnostics/cluster/aggregated_logging/routes.go
@sosiouxme   address nits for #10964 that were missed before merge.
=> fix to unaddressed nits in #10964 for AGL diagnostics

pkg/project/registry/projectrequest/delegated/delegated.go
pick of https://github.com/openshift/origin/pull/11226
=> Add logging to project request failures

contrib/completions/bash/oc, contrib/completions/bash/openshift, contrib/completions/zsh/oc, contrib/completions/zsh/openshift, docs/generated/oc_by_example_content.adoc, docs/man/man1/.files_generated_oc, docs/man/man1/.files_generated_openshift, docs/man/man1/oc-rollout-latest.1, docs/man/man1/oc-rollout.1, docs/man/man1/openshift-cli-rollout-latest.1, pkg/cmd/cli/cmd/rollout/latest.go, pkg/cmd/cli/cmd/rollout/rollout.go, test/extended/deployments/deployments.go
Partially addresses https://github.com/openshift/origin/issues/9298
Trello card: https://trello.com/c/uQP2AxXy/508-2-deploy-most-recently-available-image
@fabianofranz @mfojtik @ironcladlou @smarterclayton
=> oc: add rollout latest

test/extended/jenkins/kubernetes_plugin.go, test/extended/jenkins/plugin.go
@bparees ptal
@csrwng @jupierce @oatmealraisin this test has been working fine for the PR tester but this change fixes running this test against the latest jenkins template and officially release plugin
=> get password from dc; add more diag

Godeps/Godeps.json, vendor/github.com/RangelReale/osincli/access.go, vendor/github.com/RangelReale/osincli/authorize.go, vendor/github.com/RangelReale/osincli/client.go, vendor/github.com/RangelReale/osincli/config.go, vendor/github.com/RangelReale/osincli/pkce.go
Adds [PKCE](https://tools.ietf.org/html/rfc7636) support to `osincli`.
xref: #10871
=> bump(github.com/RangelReale/osincli): fababb0555f21315d1a34af6615a16eaab44396b

Makefile
=> Add a `make` target to vendor the web console

pkg/cmd/cli/cmd/deploy.go, pkg/deploy/registry/instantiate/rest.go
=> Bug 1383138: suggest 'rollout latest' if 'deploy --latest' returns a bad request

pkg/deploy/api/validation/validation.go
=> Fixing validation msg

test/integration/deploy_trigger_test.go
Fixes https://github.com/openshift/origin/issues/11318
@mfojtik
=> integration: retry instantiate on conflict

vendor/k8s.io/kubernetes/pkg/securitycontextconstraints/provider.go, vendor/k8s.io/kubernetes/pkg/securitycontextconstraints/provider_test.go
Code courtesy of @sttts. cc @pweil- @smarterclayton
=> UPSTREAM: <carry>: sysctls SCC strategy

vendor/k8s.io/kubernetes/pkg/api/unversioned/group_version.go, vendor/k8s.io/kubernetes/pkg/api/unversioned/group_version_test.go, vendor/k8s.io/kubernetes/pkg/runtime/scheme_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1378368
=> UPSTREAM: 34010: Match GroupVersionKind against specific version

hack/util.sh, pkg/cmd/cli/secrets/basicauth.go, pkg/cmd/cli/secrets/basicauth_test.go, pkg/cmd/cli/secrets/sshauth.go, pkg/cmd/cli/secrets/sshauth_test.go, test/cmd/secrets.sh
=> Correct secret type in oc secrets new-{basic,ssh}auth

test/extended/setup.sh
I tested this locally and it passed for me.
cc @smarterclayton 
Fixes #7097
=> Enable exec/http proxy e2e test

hack/dind-cluster.sh
=> dind: deploy multitenant plugin by default

pkg/security/api/validation/validation.go, pkg/security/api/validation/validation_test.go, pkg/security/registry/podsecuritypolicyreview/rest_test.go, pkg/security/registry/podsecuritypolicysubjectreview/rest_test.go
This was found during testing. 
@sdminonne ptal
@wjiangjay fyi
=> Fix validation messages for PodSecurityPolicy*Review objects

pkg/build/api/validation/validation.go, pkg/build/api/validation/validation_test.go, test/integration/build_admission_test.go
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1384973
GitHub issue: #11324
=> Reject Builds with unresolved image references

pkg/build/api/types.go
Fixes https://github.com/openshift/origin/issues/11422
=> update build status reasons to StatusReason type

pkg/deploy/controller/generictrigger/controller.go, pkg/deploy/controller/generictrigger/factory.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1386054
@mfojtik @smarterclayton @deads2k ptal
=> Bug 1386054: enqueue in the trigger controller only when really needed

pkg/build/admission/jenkinsbootstrapper/admission.go, pkg/build/admission/jenkinsbootstrapper/admission_test.go
=> spell jenkins correctly

examples/gitserver/gitserver-ephemeral.yaml, examples/gitserver/gitserver-persistent.yaml
to address this [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1386482)
=> Change gitserver-persistent template's deploy strategy to Recrate

test/extended/image_ecosystem/mongodb_replica_petset.go
PTAL @bparees
Depends on: https://github.com/sclorg/mongodb-container/pull/206 (ex https://github.com/sclorg/mongodb-container/pull/184)
Trello card: https://trello.com/c/jPGXhxlJ/694-3-mongodb-replica-set-example-with-persistent-storage
=> Extended test for PetSet based MongoDB replica set

images/release/Dockerfile, images/release/golang-1.4/Dockerfile, images/release/golang-1.6/Dockerfile, images/release/golang-1.7/Dockerfile
=> Add `bc` to the release Docker image specs for test-cmd

test/extended/image_ecosystem/mongodb_replica_petset.go, test/extended/util/framework.go
Follow-up to #11266
PTAL @bparees
=> CleanupHostPathVolumes(): remove also directories from the filesystem

vendor/k8s.io/kubernetes/pkg/api/helpers.go, vendor/k8s.io/kubernetes/pkg/api/types.go, vendor/k8s.io/kubernetes/pkg/api/v1/types.go, vendor/k8s.io/kubernetes/pkg/api/validation/validation.go, vendor/k8s.io/kubernetes/pkg/api/validation/validation_test.go, vendor/k8s.io/kubernetes/plugin/pkg/admission/limitranger/admission.go, vendor/k8s.io/kubernetes/plugin/pkg/admission/limitranger/admission_test.go
Cherry-pick of https://github.com/kubernetes/kubernetes/pull/30145
@abhgupta @derekwaynecarr @smarterclayton
=> UPSTREAM: 30145: Add PVC storage to Limit Range

pkg/project/auth/cache.go, pkg/project/auth/cache_test.go, pkg/project/auth/reviewer.go, test/integration/project_test.go
=> Continue project cache evaluation in the presence of evaluation errors

hack/common.sh, hack/env
Makes it possible to set up PR builders with a controlled environment.
=> Support hack/env in 1.2 release

pkg/client/deploymentconfigs.go, pkg/deploy/controller/generictrigger/controller.go
=> client: fix instantiate call to handle 204

origin.spec
Fixes: https://github.com/openshift/origin/pull/11082
@openshift/networking @tdawson @sdodson
=> specfile: fix specfile issues after openshift-sdn CNI plugin merge

docs/man/man1/openshift-kube-set-resources.1, vendor/k8s.io/kubernetes/pkg/kubectl/cmd/set/set_resources.go
Fixes https://github.com/openshift/origin/issues/11513
=> Commands must not use the factory outside of Run

pkg/cmd/cli/cmd/exporter.go, pkg/cmd/cli/cmd/exporter_test.go, pkg/deploy/registry/deployconfig/strategy.go, test/cmd/export.sh
=> oc: fix export for deployment configs

pkg/deploy/strategy/support/lifecycle.go, pkg/deploy/strategy/support/lifecycle_test.go
Fixes: https://github.com/openshift/origin/issues/11352
@kargakis PTAL
=> deployments: lifecycle hooks refactoring

examples/db-templates/mariadb-ephemeral-template.json, examples/db-templates/mariadb-persistent-template.json, examples/db-templates/mongodb-ephemeral-template.json, examples/db-templates/mongodb-persistent-template.json, examples/db-templates/mysql-ephemeral-template.json, examples/db-templates/mysql-persistent-template.json, examples/db-templates/postgresql-ephemeral-template.json, examples/db-templates/postgresql-persistent-template.json, examples/etcd/template.json, examples/image-streams/image-streams-centos7.json, examples/image-streams/image-streams-rhel7.json, examples/jenkins/jenkins-ephemeral-template.json, examples/jenkins/jenkins-persistent-template.json, examples/quickstarts/cakephp-mysql.json, examples/quickstarts/dancer-mysql.json, examples/quickstarts/django-postgresql.json, examples/quickstarts/nodejs-mongodb.json, examples/quickstarts/rails-postgresql.json, examples/wordpress/template/wordpress-mysql.json, examples/zookeeper/template.json, pkg/bootstrap/bindata.go
Adds display name, service grouping, post-deployment message, and
updated descriptions for all templates and image streams
=> Updates template and image stream metadata

hack/util.sh
fixes https://github.com/openshift/origin/issues/11527
=> Correctly report the size of overlarge log files

hack/lib/util/misc.sh, hack/util.sh
@Miciah PTAL the second commit
=> Migrate miscellaneous Bash utilities into the `hack/lib` library

hack/lib/start.sh, hack/test-end-to-end.sh, hack/update-generated-swagger-spec.sh, hack/util.sh, test/extended/README.md, test/extended/alternate_launches.sh, test/extended/cmd.sh, test/extended/gssapi.sh, test/extended/ldap_groups.sh, test/extended/setup.sh
Following up to changes @csrwng made.
@smarterclayton on your sign-off 
[test]
=> Remove usage of deprecated utilities for starting a server

docs/man/man1/oc-cluster-up.1, docs/man/man1/openshift-cli-cluster-up.1, hack/lib/start.sh, pkg/bootstrap/docker/up.go
Signed-off-by: yupeng <yu.peng36@zte.com.cn>
=> "ie." is not the correct abbreviation for "ID EST"

pkg/cmd/server/origin/master.go, pkg/image/importer/client_test.go, pkg/image/importer/importer.go, pkg/image/importer/importer_test.go, pkg/image/importer/layercache.go, test/integration/imageimporter_test.go
Fix #9779
@miminar please review.
=> Use global LRU cache for layer sizes

docs/cluster_up_down.md
Added comment to clarify that oc cluster did not work on versions before that 1.3
=> Added comment to clarify that oc cluster did not work on previous version

examples/db-templates/postgresql-ephemeral-template.json, examples/db-templates/postgresql-persistent-template.json, examples/image-streams/image-streams-centos7.json, examples/image-streams/image-streams-rhel7.json, pkg/bootstrap/bindata.go
=> Adds display name to image streams, updates PostgreSQL link

vendor/k8s.io/kubernetes/pkg/controller/scheduledjob/controller.go, vendor/k8s.io/kubernetes/pkg/controller/scheduledjob/controller_test.go, vendor/k8s.io/kubernetes/pkg/controller/scheduledjob/injection.go
This fixes [bug 1386463](https://bugzilla.redhat.com/show_bug.cgi?id=1386463)
I'm going to merge this once upstream PR gets approved.
=> UPSTREAM: 35420: Remove Job also from .status.active for Replace strategy

vendor/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller_utils.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1379316
=> UPSTREAM: 34298: Fix potential panic in namespace controller

pkg/deploy/controller/deploymentconfig/controller.go
Paused conditions are not so useful with the current state of pausing
in deployment configs. If we ever start pausing the deployer container
then it may make sense to surface a paused condition in the deployment
status. For now since we don't pause rollouts, we can depend on our
cli tooling to let users know that their deployment configs are paused.
Fixes https://github.com/openshift/origin/issues/11656
@mfojtik
=> deploy: drop paused conditions

test/extended/image_ecosystem/plugin.go, test/extended/setup.sh, test/extended/testdata/jenkins-plugin/imagestream-scm-dsl-job.xml, test/extended/testdata/jenkins-plugin/imagestream-scm-job.xml, test/extended/util/framework.go
Adds extended tests to validate the functionality of the Jenkins plugin imagestream SCM and corresponding DSL step.
=> Jenkins plugin ImageStream SCM extended tests

pkg/cmd/server/bootstrappolicy/policy.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
=> Update rules for upstream deployment rollbacks

pkg/cmd/templates/templater.go, test/cmd/help.sh
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1390528
=> Fixes oc help global options hint

pkg/auth/oauth/external/gitlab/gitlab.go
=> Use custom transport for gitlab communication

docs/man/man1/oc-rollout.1, docs/man/man1/openshift-cli-rollout.1, pkg/cmd/cli/cmd/rollout/rollout.go
@openshift/cli-review @mfojtik @smarterclayton
=> oc: update short desc for rollout

test/extended/router/scoped.go, test/extended/router/weighted.go
fixes bug 1380669 [link](https://bugzilla.redhat.com/show_bug.cgi?id=1380669)
and issue https://github.com/openshift/origin/issues/11649
@knobunc this should fix it
=> fix error - cannot list all services in the cluster

test/integration/buildpod_admission_test.go
fixes https://github.com/openshift/origin/issues/11728
=> bump build pod admission test timeout

pkg/router/f5/plugin.go
Poor code before, never accounted that nodes that were already created before F5 is launched will only get a MODIFIED event. This code takes care of that (and ignores the subsequent MODIFY events caused by status updates).
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1389706
@pravisankar Please review. Thanks for the hint.
cc @openshift/networking
=> f5 node watch fix - needs a cache to process 'MODIFY' events

images/router/egress/README.md
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1387645. Just a docs change so there's no reason to not get it in for 3.4. @knobunc PTAL
=> Fix a bug in the egress router README

test/end-to-end/core.sh
Fixes https://github.com/openshift/origin/issues/11682
@mfojtik ptal
=> test: wait for frontend rollout before getting app logs

docs/generated/oc_by_example_content.adoc, docs/man/man1/oc-logs.1, docs/man/man1/openshift-cli-logs.1, pkg/cmd/cli/cmd/logs.go
Signed-off-by: yupeng <yu.peng36@zte.com.cn>
=> Align with other cli descriptions

test/extended/image_ecosystem/mongodb_replica_petset.go
This should fix "Timeout waiting for pods" error that happens sometimes.
PTAL @bparees
=> MongoDB replica petset test: increase time of waiting for pods

pkg/sdn/plugin/pod_test.go
Fixes: https://github.com/openshift/origin/issues/11640
@openshift/networking @soltysh
=> sdn: remove need for locking in pod tests

hack/lib/log/output.sh, hack/util.sh
=> Cleaned up Bash logging

test/cmd/edit.sh, vendor/k8s.io/kubernetes/pkg/kubectl/cmd/edit.go
Help yourselves: https://github.com/openshift/origin/pull/11704/files?w=1
Upstream issue is https://github.com/kubernetes/kubernetes/issues/20519, if it's not fixed until the next rebase, we need to continue carrying the drop commit (will need some changes @soltysh I can help with that). A test is added on our side to prevent future regressions.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1389681
=> Make edit work with lists again

hack/build-rpm-release.sh
When creating a RPM release, it is useful to keep the generated RPM
artifacts separate from the rest of the artifacts in the release out-
put directory. Furthermore, if the user has `createrepo` installed,
we can go ahead anad create a repository and .repo file for them for
the local release so they may install the generated RPMs with `yum`.
=> Placed RPM release in a distinct directory and generated a repository

vendor/k8s.io/kubernetes/pkg/controller/scheduledjob/controller.go
Fixes 2nd part of https://bugzilla.redhat.com/show_bug.cgi?id=1386463. 
Will wait for upstream approval.
@mfojtik @ncdc fyi
=> UPSTREAM: 36161: Fix how we iterate over active jobs when removing them from Replace policy

docs/man/man1/oadm-diagnostics.1, docs/man/man1/oc-adm-diagnostics.1, docs/man/man1/openshift-admin-diagnostics.1, docs/man/man1/openshift-cli-adm-diagnostics.1, docs/man/man1/openshift-ex-diagnostics.1, pkg/cmd/admin/diagnostics/diagnostics.go
Description string fixes.
Fixes Bug 1388025 [link](https://bugzilla.redhat.com/show_bug.cgi?id=1388025)
=> Bug 1388025 - Update NetworkDiagDefaultLogDir description

test/extended/image_ecosystem/plugin.go
This mimics the POST sent by clicking the "Test Connection" button in the Jenkins UI.  It sends a blank apiURL and authToken, which should cause the logic to default to the env var values.
I don't believe this will pass until [#95](https://github.com/openshift/jenkins-plugin/pull/95) is merged, due to an error with checking the environment variables.
@gabemontero ptal?
=> Added a test for doTestConnection functionality

pkg/dockerregistry/server/pullthroughblobstore.go, pkg/dockerregistry/server/pullthroughblobstore_test.go, test/integration/dockerregistry_pullthrough_test.go
Fix https://bugzilla.redhat.com/show_bug.cgi?id=1385855
@miminar please review
=> Allow getting images from registries over untrusted connection

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack.go
https://github.com/kubernetes/kubernetes/pull/36249
@ncdc @derekwaynecarr
=> UPSTREAM: 36249: fix version detection in openstack lbaas

Godeps/Godeps.json, pkg/sdn/plugin/sdn-cni-plugin/openshift-sdn.go, vendor/github.com/containernetworking/cni/libcni/api.go, vendor/github.com/containernetworking/cni/libcni/conf.go, vendor/github.com/containernetworking/cni/pkg/invoke/exec.go, vendor/github.com/containernetworking/cni/pkg/invoke/exec_test.go, vendor/github.com/containernetworking/cni/pkg/invoke/get_version_integration_test.go, vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go, vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec_test.go, vendor/github.com/containernetworking/cni/pkg/ip/link.go, vendor/github.com/containernetworking/cni/pkg/ns/ns.go, vendor/github.com/containernetworking/cni/pkg/skel/skel.go, vendor/github.com/containernetworking/cni/pkg/skel/skel_test.go, vendor/github.com/containernetworking/cni/pkg/types/types.go, vendor/github.com/containernetworking/cni/pkg/utils/hwaddr/hwaddr.go, vendor/github.com/containernetworking/cni/pkg/utils/hwaddr/hwaddr_suite_test.go, vendor/github.com/containernetworking/cni/pkg/utils/hwaddr/hwaddr_test.go, vendor/github.com/containernetworking/cni/pkg/version/plugin.go, vendor/github.com/containernetworking/cni/pkg/version/plugin_test.go, vendor/github.com/containernetworking/cni/pkg/version/version.go, vendor/github.com/containernetworking/cni/pkg/version/version_suite_test.go, vendor/github.com/containernetworking/cni/plugins/ipam/host-local/allocator.go, vendor/github.com/containernetworking/cni/plugins/ipam/host-local/allocator_test.go, vendor/github.com/containernetworking/cni/plugins/ipam/host-local/main.go, vendor/github.com/containernetworking/cni/plugins/main/loopback/loopback.go
CNI updated to get fixes for host-local plugin allocations on IP subnet boundaries.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1392296
@openshift/networking
=> Update CNI for host local fix

docs/man/man1/oc-start-build.1, docs/man/man1/openshift-cli-start-build.1, pkg/cmd/cli/cmd/startbuild.go
=> clarify start-build --from-webhook only meant to work with generic webhook

pkg/route/api/validation/validation.go, pkg/route/api/validation/validation_test.go
@knobunc  @liggitt   PTAL  Thx
addressed the concerns you had in bug 1389165 [link](https://bugzilla.redhat.com/show_bug.cgi?id=1389165) as well - there were already existing tests that covered some of those but added a few more.
Also fixes #11767
=> Fix for bugz #1389165 - extended route validation breaks included templates

pkg/bootstrap/docker/openshift/helper.go
=> fix --host-config-dir, don't download host path from docker container

pkg/generate/app/cmd/resolve.go, test/cmd/newapp.sh
fixes https://github.com/openshift/origin/issues/11744
@csrwng ptal
=> require builder image for source-type binary build creation

hack/lib/util/misc.sh, hack/util.sh
=> Migrated misc method and removed unused method from util.sh

pkg/generate/app/dockerimagelookup.go, pkg/image/api/validation/validation.go, pkg/image/importer/importer.go
Fix https://github.com/openshift/origin/issues/11773
@smarterclayton @liggitt @miminar @mfojtik Please review.
=> Allow to use star as repository name in imagestreamimport

hack/lib/start.sh, hack/test-cmd.sh, hack/util.sh, test/extended/README.md, test/extended/cmd.sh, test/extended/gssapi.sh, test/extended/ldap_groups.sh, test/extended/setup.sh
=> Migrate router and registry startup functions from util.sh

pkg/router/controller/host_admitter.go, pkg/router/controller/host_admitter_test.go
fixes bugz https://bugzilla.redhat.com/show_bug.cgi?id=1391338 and 
bugz https://bugzilla.redhat.com/show_bug.cgi?id=1391878
for multiple wildcard routes requesting the same subdomain for the same subdomain and in the same namespace, reject newer routes with 'HostAlreadyClaimed'.
@knobunc / @liggitt   PTAL  Thx
=> Fix for bugz 1391878 and 1391338 - for multiple wildcard routes requesting the same subdomain

docs/man/man1/openshift-start-kubernetes-kubelet.1, pkg/cmd/server/kubernetes/node_config_test.go, vendor/k8s.io/kubernetes/pkg/apis/componentconfig/v1alpha1/defaults.go
https://github.com/kubernetes/kubernetes/pull/36375
Fixes bug 1392749 https://bugzilla.redhat.com/show_bug.cgi?id=1392749
@ncdc @derekwaynecarr
=> UPSTREAM: 36375: Fix default Seccomp profile directory

images/router/haproxy/conf/haproxy-config.template, pkg/router/template/plugin.go, pkg/router/template/router.go
fix for bugz https://bugzilla.redhat.com/show_bug.cgi?id=1393262  
@knobunc  fyi PTAL Thx
=> Fix for bugz 1393262 - serve certs for wildcard hosts.

pkg/route/api/validation/validation.go, pkg/route/api/validation/validation_test.go
Fixes bugz https://bugzilla.redhat.com/show_bug.cgi?id=1392862
@knobunc  @liggit PTAL thx
=> Fix for bugz 1392862 - don't allow wildcard policy if host is not specified.

pkg/cmd/cli/describe/printer.go, pkg/cmd/cli/describe/printer_test.go
Fixes #11765. 
@bparees @smarterclayton PTAL
=> oc get templates: print only the first line of description

pkg/bootstrap/docker/dockerhelper/filetransfer.go, pkg/bootstrap/docker/openshift/helper.go
fixes #11889
@csrwng @thoraxe 
@bparees if this isn't too late to squeeze this into 1.4, I think it would be a good plan to do so...
=> Wait for remote API response before return in UploadFileToContainer

hack/util.sh
Let's try doubling 50M to 100M to see if that helps.
@stevekuznetsov @danmcp
=> Increase retained CI log size to 100M

pkg/cmd/cli/cmd/login/loginoptions.go
Related Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1262696
This patch replaces the `oc login` suggestion to create a new project
with a forbidden warning if the user does not have rights to create
project requests. This only happens if such user has no projects at
login time.
**Example**
```
$ oc login -u testuser
Logged into "https://10.13.137.149:8443" as "testuser" using existing
credentials.
You do not have access to create new projects, contact your system
administrator to request a project.
```
=> Warn on login when user cannot request projects

pkg/router/f5/plugin.go
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1395153
=> f5 poolname fix

pkg/route/registry/route/strategy.go, pkg/route/registry/route/strategy_test.go
Fixes bug 1392862 https://bugzilla.redhat.com/show_bug.cgi?id=1392862
@liggitt / @knobunc  PTAL Thx
=> We should not be able to create a route when the host is not specified and wildcard policy is enabled

test/cmd/convert.sh, test/testdata/convert/job-v1.yaml, test/testdata/convert/job-v2.json, vendor/k8s.io/kubernetes/pkg/kubectl/cmd/convert.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1393230
=> Fixes handling lists in convert

images/release/golang-1.4/Dockerfile, images/release/golang-1.6/Dockerfile, images/release/golang-1.7/Dockerfile
Blocks containerized testing on openshift [merge]
=> Allow all users to exec protoc in release images

pkg/build/admission/defaults/admission.go, pkg/build/admission/defaults/admission_test.go, pkg/build/admission/defaults/api/types.go, pkg/build/admission/defaults/api/v1/swagger_doc.go, pkg/build/admission/defaults/api/v1/types.go
[Trello Card](https://trello.com/c/fdRnlbqn/1035-default-resource-limits-for-build-pods)
=> default resources for the build

test/extended/image_ecosystem/plugin.go, test/extended/util/framework.go
Example entry:
```
Jenkins memory statistics at 2016-11-04 17:28:23.024556251 -0400 EDT
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1000090+   476  0.0  0.0  47432  3212 ?        Rs   21:28   0:00 ps faux
1000090+     1 30.5  2.7 6063144 438908 ?      Ssl  21:25   0:52 java -Xmx307m -Duser.home=/var/lib/jenkins -Dfile.encoding=UTF8 -jar /usr/lib/jenkins/jenkins.war
cache 90386432
rss 442425344
rss_huge 0
mapped_file 14123008
dirty 20480
writeback 0
swap 180346880
pgpgin 310560
pgpgout 180479
pgfault 194011
pgmajfault 4551
inactive_anon 258682880
active_anon 255033344
inactive_file 4714496
active_file 14323712
unevictable 0
hierarchical_memory_limit 536870912
hierarchical_memsw_limit 9223372036854771712
total_cache 90386432
total_rss 442425344
total_rss_huge 0 …
```
=> Memory monitoring for jenkins during extended tests

pkg/auth/oauth/external/github/github.go, pkg/auth/oauth/external/github/github_test.go, pkg/cmd/server/api/types.go, pkg/cmd/server/api/v1/stringsource_test.go, pkg/cmd/server/api/v1/swagger_doc.go, pkg/cmd/server/api/v1/types.go, pkg/cmd/server/api/v1/types_test.go, pkg/cmd/server/api/validation/oauth.go, pkg/cmd/server/origin/auth.go
Resolves https://github.com/openshift/origin/issues/11882
=> Add support for github teams

Godeps/Godeps.json
- Remove duplicate entries
- Correct "Comment" for github.com/containernetworking/cni/...
- Correct "Comment" and "Rev" for github.com/opencontainers/runc
@soltysh @deads2k @liggitt @smarterclayton
=> Fix issues with Godeps.json

pkg/build/builder/docker.go
Having trouble testing this locally
[testextended][extended:core]
=> Added a check to prevent pulling scratch

README.md
Fix bad markdown format. Just a nit.
=> Fix bad format in README.md

pkg/sdn/plugin/node.go
Cherry-pick of #11938 
@knobunc
=> Fix the command to restart docker on 1.3->1.4 upgrade

HACKING.md
=> Added a mention of TEST_ONLY to extended test doc

test/extended/builds/forcepull.go, test/extended/image_ecosystem/plugin.go, test/extended/testdata/forcepull-test.json, test/extended/testdata/jenkins-plugin/build-job-slave.xml, test/extended/testdata/jenkins-plugin/build-job.xml, test/extended/testdata/jenkins-plugin/build-with-env-job.xml, test/extended/testdata/jenkins-plugin/build-with-exec-steps.xml, test/extended/testdata/jenkins-plugin/imagestream-scm-dsl-job.xml, test/extended/testdata/jenkins-plugin/imagestream-scm-job.xml, test/extended/testdata/jenkins-plugin/multitag-job.xml, test/extended/util/framework.go
Additional tests for Jenkins plugin. Exercises openshift/jenkins-plugin#107 .
ptal @gabemontero @bparees
=> Adding extended tests for Jenkins freestyle exec

pkg/api/kubegraph/nodes/nodes.go, pkg/cmd/cli/describe/projectstatus.go
Fixes https://github.com/openshift/origin/issues/10269
This patch removes adding markers for forbidden resources
cc @openshift/cli-review @stevekuznetsov
=> prevent forbidden resource validation

pkg/generate/app/cmd/resolve.go, pkg/generate/app/cmd/resolve_test.go
https://trello.com/c/H6ZwrpCo/995-5-new-app-new-build-support-for-pipeline-buildconfigs-techdebt
@wanghaoran1988
Resolves the further discussion in #11897.
> I agree it's not clear what's best and no way to maintain true compatibility.
>
> jenkinsfile -> dockerfile -> source seems reasonable to me. As you say, making jenkinsfile king makes sense.
=> new-app: fix priority of Jenkinsfile, Dockerfile, source when strategy unspecified

CONTRIBUTING.adoc
=> dind: Remove mention of br_netfilter from docs

pkg/cmd/openshift/openshift.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1397995
=> Use responsive writer only in help

examples/gitserver/hooks/detect-language
@bparees, I accidentally missed this off #11896.
=> add *.csproj support to examples/gitserver/hooks/detect-language

Godeps/Godeps.json, vendor/github.com/Microsoft/go-winio/README.md, vendor/github.com/Microsoft/go-winio/backup.go, vendor/github.com/Microsoft/go-winio/file.go, vendor/github.com/Microsoft/go-winio/fileinfo.go, vendor/github.com/Microsoft/go-winio/pipe.go, vendor/github.com/Microsoft/go-winio/privilege.go, vendor/github.com/Microsoft/go-winio/sd.go, vendor/github.com/Microsoft/go-winio/syscall.go, vendor/github.com/Microsoft/go-winio/zsyscall_windows.go
Should just be cosmetic - to match https://github.com/openshift/source-to-image/pull/642
=> Bump github.com/Microsoft/go-winio

examples/jenkins/pipeline/samplepipeline.json, pkg/bootstrap/bindata.go
=> added block arguments to remove jenkins deprecation warnings

vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
xref kubernetes/kubernetes#36779
master PR https://github.com/openshift/origin/pull/11939
@derekwaynecarr @ncdc
=> UPSTREAM: 36779: fix leaking memory backed volumes of terminated pods

pkg/sdn/plugin/controller.go, pkg/sdn/plugin/egress_network_policy.go, pkg/sdn/plugin/node.go
cherry-pick of #12045 to 1.4
@knobunc
=> Fix a multiple-pointers-to-single-loop-variable bug in EgressNetworkPolicy

examples/pets/mysql/healthz/README.md
Signed-off-by: yupeng <yu.peng36@zte.com.cn>
=> fix the mistake link type

.travis.yml, Makefile
Discussed with @smarterclayton, this is prereq for #12011.
@stevekuznetsov ptal
=> Move verify-upstream-commits to a separate make target

pkg/image/registry/imagestreamimage/rest.go
Fixes: https://github.com/openshift/origin/issues/12051
=> Copy creationTimestamp from the image

contrib/excluder/excluder-template, origin.spec
Fix excluder usage bug
Exclude the excluders
docker-excluder excludes up to 1.20
=> Fix excluder

docs/generated/oc_by_example_content.adoc, docs/man/man1/oc-create-policybinding.1, docs/man/man1/openshift-cli-create-policybinding.1, pkg/cmd/cli/cmd/create/clusterquota.go, pkg/cmd/cli/cmd/create/deploymentconfig.go, pkg/cmd/cli/cmd/create/policy_binding.go
=> Fix godoc comments and typo in command description

pkg/build/controller/controller.go
=> Fix typo introduced in #10817

examples/gitserver/Dockerfile, examples/gitserver/README.md, hack/build-images.sh
=> build gitserver image FROM origin, not origin-base

pkg/deploy/strategy/support/lifecycle.go, pkg/deploy/strategy/support/lifecycle_test.go
Cherry pick of https://github.com/openshift/origin/pull/12080
@kargakis PTAL
@VanRoy FYI
=> Consideration of imagePullPolicy on lifecycle hook execution

vendor/k8s.io/kubernetes/pkg/api/rest/delete.go, vendor/k8s.io/kubernetes/pkg/registry/generic/registry/store_test.go
xref https://bugzilla.redhat.com/show_bug.cgi?id=1397356
=> UPSTREAM: 37721: Fix logic error in graceful deletion

Godeps/Godeps.json, hack/godep-restore.sh, pkg/cmd/util/tokencmd/request_token.go, test/integration/oauth_request_header_test.go, vendor/github.com/RangelReale/osin/response.go
Fixes incorrectly encoded state param during OAuth flow
=> Fix OAuth state encoding

pkg/client/oauthaccesstoken.go, pkg/client/oauthauthorizetoken.go, pkg/client/oauthclient.go, pkg/client/oauthclientauthorization.go, pkg/client/testclient/fake_oauthclientauthorization.go, pkg/cmd/util/clientcmd/factory.go, pkg/user/reaper/user.go, pkg/user/reaper/user_test.go
=> Reap OAuthClientAuthorizations when deleting a user - 1.4.0

pkg/quota/controller/clusterquotamapping/mapper.go, pkg/quota/controller/clusterquotareconciliation/reconcilation_controller.go, pkg/quota/controller/clusterquotareconciliation/reconciliation_controller_test.go, test/cmd/quota.sh
Cherry-pick of https://github.com/openshift/origin/pull/12123
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1401073
=> Reconcile deleted namespaces out of cluster quota status - 1.4

Godeps/Godeps.json, pkg/cmd/util/tokencmd/request_token.go, test/integration/oauth_request_header_test.go, vendor/github.com/RangelReale/osin/response.go
=> Fix OAuth state encoding - 1.4

pkg/cmd/server/origin/master_config.go, pkg/project/admission/lifecycle/admission.go, pkg/project/admission/lifecycle/admission_test.go
=> Only pay attention to origin types in project lifecycle admission - 1.3.x

pkg/deploy/strategy/recreate/recreate.go, pkg/deploy/strategy/recreate/recreate_test.go, pkg/deploy/strategy/rolling/rolling.go, pkg/deploy/strategy/rolling/rolling_test.go, pkg/deploy/strategy/support/lifecycle.go, pkg/deploy/strategy/support/lifecycle_test.go
@mfojtik cleans up the strategy code a bit and partially addresses https://github.com/openshift/origin/issues/11854
=> deploy: cleanup strategy code

test/extended/idling/util.go
A naive attempt to fix https://github.com/openshift/origin/issues/12112
=> Increase timeouts for idling extended test

images/release/Dockerfile, images/release/golang-1.4/Dockerfile, images/release/golang-1.6/Dockerfile, images/release/golang-1.7/Dockerfile
`openssl` binary required for tests that check certificates, see #11814
PTAL @stevekuznetsov
=> openshift/origin-release:golang-1.x: install openssl

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/mesos/client_test.go, vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/mesos/mesos_test.go
=> [1.3] UPSTREAM: 38196: fix mesos unit tests

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/mesos/client_test.go, vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/mesos/mesos_test.go
=> [1.4] UPSTREAM: 38196: fix mesos unit tests

pkg/bootstrap/docker/openshift/helper.go
=> make /sys/devices/virtual/net r/w for kubelet under oc cluster up

vendor/k8s.io/kubernetes/pkg/volume/volume_linux.go, vendor/k8s.io/kubernetes/test/e2e/common/configmap.go, vendor/k8s.io/kubernetes/test/e2e/common/downwardapi_volume.go, vendor/k8s.io/kubernetes/test/e2e/common/secrets.go
xref https://github.com/kubernetes/kubernetes/pull/37009
@derekwaynecarr @pmorie
=> UPSTREAM: 37009: fix permissions when using fsGroup

vendor/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_executor.go
fix 
https://bugzilla.redhat.com/show_bug.cgi?id=1397693
=> validating pod reference before recording an event

test/extended/setup.sh
=> Provide the directory for Ginkgo jUnit output explicitly

pkg/cmd/admin/node/node.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1403634
=> Suggest oadm drain instead of oadm manage-node drain

docs/debugging-openshift.md
there are some places where "." and ":" missed. Please, add this.
=> missed punctuation

pkg/diagnostics/cluster/aggregated_logging/deploymentconfigs.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1394716
cc @sosiouxme @openshift/cli-review
=> [BZ1394716] Report false diagnostic message for curator-ops DeploymentConfig

pkg/deploy/api/types.go, pkg/deploy/strategy/recreate/recreate.go, pkg/deploy/strategy/recreate/recreate_test.go
Fixes: https://github.com/openshift/origin/issues/12154
=> deploy: make retryTimeout proportional to deployer Pod startTime

test/end-to-end/core.sh
This flag is no longer supported by docker and tests seem to be
passing regardless of that
[test]
=> Remove -f flag from docker tag

hack/update-generated-clientsets.sh, hack/verify-generated-clientsets.sh
Fails to handle failure cases
[test]
=> Verify generated clientset should check errors

hack/test-cmd.sh
Removing because does not work in a container.
[test]
=> Disable test for unwritable config file

test/extended/builds/s2i_extended_build.go, test/extended/testdata/build-extended/bc-scripts-by-url.yaml, test/extended/testdata/build-extended/bc-scripts-in-repo.yaml, test/extended/testdata/build-extended/bc-scripts-in-the-image.yaml, test/extended/testdata/build-extended/jvm-runner-with-scripts.yaml
Update tests to use new URL of the repository (https://github.com/php-coder/java-maven-hello-world => https://github.com/openshift/test-maven-app).
PTAL @bparees
=> s2i_extended_build: update repo url

contrib/excluder/excluder-template, origin.spec
Fix excluder usage bug
Exclude the excluders
docker-excluder excludes up to 1.20
=> (1.4) Fix excluder

hack/lib/util/environment.sh
=> Do not print findmnt on startup

vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go, vendor/github.com/onsi/ginkgo/internal/writer/writer.go, vendor/github.com/onsi/ginkgo/reporters/junit_reporter.go
=> Capture stdout for extended tests

test/extended/conformance.sh, test/extended/setup.sh
=> Disable color on extended test suite

test/extended/util/test.go
e2e parallelism means up to N tests can attempt to mutate the SCC at a
time, which can fail the test if retries is not at least N.
[merge] to allow GCE tester to start passing
=> Allow much higher extended test bursting by increasing retry

test/extended/image_ecosystem/postgresql_replica.go
=> Use [local] consistently

pkg/util/stringreplace/object.go
fixes
https://github.com/openshift/origin/issues/12325
=> clarify unknown type log message

pkg/cmd/admin/policy/who_can.go, pkg/cmd/cli/cmd/dockerbuild/dockerbuild.go, pkg/cmd/cli/cmd/example.go, pkg/cmd/cli/cmd/extract.go, pkg/cmd/cli/cmd/importer/appjson.go, pkg/cmd/cli/cmd/importer/dockercompose.go, pkg/cmd/cli/cmd/set/buildhook.go, pkg/cmd/cli/cmd/set/probe.go, pkg/cmd/cli/cmd/set/routebackends.go, pkg/cmd/cli/cmd/set/triggers.go, pkg/cmd/cli/sa/gettoken.go, pkg/cmd/cli/sa/newtoken.go, pkg/cmd/experimental/buildchain/buildchain.go
@smarterclayton PTAL, and if you don't mind, I would like to take care of those `move me to kcmdutil` code when upstream merged, Is that fine ?  
Thanks
=> Reduce some empty line && code, add some TODO comments, fix typo

test/extended/util/jenkins/ref.go
=> Fix 404 error in Jenkins plugin extended tests

pkg/cmd/server/api/serialization_test.go, pkg/cmd/server/api/types.go, pkg/cmd/server/api/v1/conversions.go, pkg/cmd/server/api/validation/master.go
Addresses #12313
cc: @openshift/networking 
Doc updates: https://github.com/openshift/openshift-docs/issues/3441
=> Ensure default ingress cidr is a private range

examples/jenkins/pipeline/maven-pipeline.yaml, pkg/bootstrap/bindata.go, pkg/cmd/cli/cmd/debug.go, pkg/generate/app/app.go, pkg/generate/app/cmd/newapp.go, pkg/generate/app/imageref.go, pkg/image/api/helper.go, test/extended/builds/new_app.go, test/extended/cli/debug.go, test/extended/testdata/test-cli-debug.yaml
fixes #11906
bug 1392764
#11895
=> remove openshift.io/container.%s.image.entrypoint annotation and clarify new-app maximum name length

pkg/deploy/controller/deployment/controller.go
change "if" to "If" at the beginning of one line.
=> if2If at the begining of one line

vendor/k8s.io/kubernetes/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
Upstream PR https://github.com/kubernetes/kubernetes/pull/39493
Fix on top of https://github.com/openshift/origin/pull/11939
=> UPSTREAM: 39493: kubelet: fix nil deref in volume type check

test/extended/security/supplemental_groups.go
We are well past the supported version now, removing old check that was bad at parsing `-rc` style versions and skipping the test.
=> remove old version check for sup group test

pkg/cmd/server/origin/master.go, test/integration/master_routes_test.go
=> Fix /.well-known/oauth-authorization-server panic and add test

vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go
https://github.com/openshift/origin/issues/12458
[test]
=> UPSTREAM: <drop>: Disable memcfg notifications until softlockup fixed

test/extended/deployments/deployments.go
=> Increase timeout of deployment test

pkg/controller/scheduler.go
Modify comment for pkg/controller/scheduler.go
=> Modify comment for pkg/controller/scheduler.go

pkg/cmd/util/net.go
=> add log arguments

pkg/authorization/api/types.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Add swaggerapi to discovery cluster roles
=> add swaggerapi to discovery rules

test/extended/deployments/deployments.go
Due to #11016, we may wait substantially longer for tests
[merge]
=> Increase deployment test timeout

test/extended/builds/hooks.go
reformatting + a missing 'sh -c' in the last test which meant that it wasn't working
@jupierce as discussed (ages ago)
=> fix broken "failing postCommit default entrypoint" test and reformat for clarity

images/release/golang-1.8/Dockerfile
=> Bump to golang-1.8rc1

Godeps/Godeps.json, hack/godep-restore.sh, pkg/cmd/util/log.go, pkg/util/glog/glog.go, vendor/github.com/golang/glog/glog.go
Currently the sha of our glog godep does not actually seem to exist anywhere in the upstream glog repository.  Bumping to latest.
[test]
=> Update glog godep

pkg/build/builder/dockerutil_test.go
add ut test for the function getContainerNameOrID
=> Add ut test for the function getContainerNameOrID

examples/quickstarts/cakephp-mysql.json, examples/quickstarts/dancer-mysql.json, examples/quickstarts/django-postgresql.json, examples/quickstarts/rails-postgresql.json, pkg/bootstrap/bindata.go
*-ex repository templates have been updated so now we are
updating the ones included with origin
@bparees ptal
=> Updating external examples

pkg/cmd/server/start/master_args.go
=> Re-enable etcd3 mode and proto storage

hack/build-images.sh
@smarterclayton I think you forgot this in https://github.com/openshift/origin/pull/12430
[test]
=> Remove erroneous instance of `${OS_IMAGE_COMPILE_GOFLAGS}`

pkg/build/controller/controller.go, pkg/build/registry/build/etcd/etcd.go, pkg/build/registry/build/strategy.go, pkg/build/registry/build/strategy_test.go, pkg/cmd/cli/describe/describer.go, pkg/cmd/cli/describe/describer_test.go, test/extended/builds/s2i_quota.go
fixes https://github.com/openshift/origin/issues/12549
=> record build durations properly on build completion

pkg/diagnostics/cluster/aggregated_logging/clusterrolebindings_test.go, pkg/diagnostics/cluster/aggregated_logging/deploymentconfigs_test.go, pkg/diagnostics/cluster/aggregated_logging/routes_test.go, pkg/diagnostics/cluster/aggregated_logging/services_test.go
make comments looks more clean in ut file.
=> modify comments  t2T in ut file

test/extended/jobs/jobs.go, test/extended/router/scoped.go, test/extended/router/weighted.go
Increase timeouts due to #11016 causing significant delays in starting
pods.
[merge]
=> Test flakes? Just wait longer in more places

pkg/security/registry/podsecuritypolicyreview/rest.go
@liggitt as you pointed out [here](https://github.com/openshift/origin/pull/12611#pullrequestreview-18092511)
Thanks again
=> avoid to return erroneous sa

hack/update-changelog.sh
hack/update-changelog.sh openshift/origin v1.X.X v1.Y.Y
=> Add a changelog generator for GitHub releases

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go
https://github.com/kubernetes/kubernetes/pull/37846
xref https://bugzilla.redhat.com/show_bug.cgi?id=1400574
@eparis @derekwaynecarr
=> UPSTREAM: 37846: error in setNodeStatus func should not abort node status update

examples/db-templates/postgresql-ephemeral-template.json, examples/db-templates/postgresql-persistent-template.json, pkg/bootstrap/bindata.go
=> Fix connection URL in postgresql examples

hack/lib/build/environment.sh
Calling `hack/env` or `hack/env /bin/sh` will start the container with
stdin/tty (-it).
Also support env variables specified before the command, i.e.:
hack/env A=1 B=2 'C=3 4' make
will pass those variables to make.  Works with shell as well.
Fixes #12614, #12615
=> Upgrade hack/env to support shell, env vars

test/extended/builds/pipeline.go
@bparees PTAL
per scrum discussion this AM following last night's extended test run, followed by reviewing some of the ginkgo godoc and code, minor switch up in how jenkins and background monitoring is launched and terminated.
The use of `g.BeforeEach` and `g.AfterEach` should play more nicely with the use of `g.GinkgoRecover`.
Also, got rid of the `g.JustBeforeEach` ... was a little fuzzy on how it played with `g.BeforeEach`.
=> tweak pipeline build background monitor and ginkgo integration

docs/cluster_up_down.md
Adds information about persistence and proxy settings
Adds step to Unix setup to allow container access through firewall
=> Update cluster up documentation (persistence, proxy)

tools/genman/gen_man.go
=> genman: error message update

hack/common.sh
/cc @liggitt @csrwng @smarterclayton 
[merge]
=> Use a greedy match instead of a lazy one for versions

hack/update-generated-defaulters.sh, hack/update-generated-listers.sh, hack/update-generated-openapi.sh
Fixes #12735 
@stevekuznetsov @smarterclayton
=> Replace find with grep -rl in update scripts

test/extended/testdata/idling-echo-server-rc.yaml, test/extended/testdata/idling-echo-server.yaml, test/testdata/idling-dc.yaml
=> Pick a smaller image for idling unit tests

hack/update-generated-protobuf.sh
Needs to have a chance to handle the error.
=> generated-protobuf is using the wrong method

pkg/cmd/server/kubernetes/master.go
fix https://bugzilla.redhat.com/show_bug.cgi?id=1415466
@childsb @eparis
=> enable Azure disk provisioner

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
Picks https://github.com/kubernetes/kubernetes/pull/40763
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1416051
=> UPSTREAM: 40763: reduce log noise when aws cannot find public-ip4

pkg/cmd/server/api/validation/validation.go
https://bugzilla.redhat.com/show_bug.cgi?id=1415096
=> Preserve file and directory validation errors

images/base/Dockerfile, images/base/Dockerfile.centos7, images/base/Dockerfile.rhel7
Fixes #10940 
@derekwaynecarr @ncdc @smarterclayton @lukegb @marekjelen @PiotrKlimczak
Testing notes:
```
make release
hack/build-base-images.sh
hack/build-images.sh
oc cluster up --version=latest
docker exec -ti <origin-id> /bin/sh
which thin_ls
```
=> images: include package containing  thin_ls in base

hack/common.sh, hack/lib/log/system.sh, hack/test-cmd.sh
If you care, you'll find out.  If you don't care, you don't need to
ignore it while looking at logs anymore
=> No one needs this log output

test/extended/router/scoped.go
All errors should be logged. A future check should verify there are no
temporary failures once the router begins responding, but this fixes the
issue where the router is not yet running and refuses the connection.
Fixes #12784
[merge]
=> Router tests should check for curl errors

vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/binder_test.go, vendor/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1404383
=> UPSTREAM: 40859: PV binding: send an event when there are no PVs to bind

docs/cluster_up_down.md
Changes order of docker network inspect command and grammar fix.
=> Fix cluster up documentation of Linux firewalld instructions

pkg/cmd/cli/cmd/newapp.go, pkg/cmd/cli/cmd/newbuild.go
fixes https://github.com/openshift/origin/issues/6165
@csrwng ptal
=> report a useful error when wide mode is used with new-app/new-build

test/extended/deployments/deployments.go, test/extended/deployments/util.go
Attempt to fix: https://github.com/openshift/origin/issues/11887
Basically use the `oc rollout latest` and have a go-routine to capture the deployer logs (with increased timeout).
=> deploy: rework extended test to use rollout latest and increase timeout for logs

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce.go
=> UPSTREAM 41034: use instance's Name to attach gce disk

hack/common.sh
=> Refactor release packaging to be DRYer

pkg/cmd/cli/cmd/login/loginoptions.go
Output was missing a newline and it annoyed me.
=> add newline to login output

docs/cluster_up_down.md
Adds brew command to install the oc binary for the Mac
Fixes https://github.com/openshift/origin/issues/10946
=> cluster up: add brew install instructions

pkg/diagnostics/cluster/aggregated_logging/daemonsets.go
Fix type %s to %d for int type parameter
=> Fix type %s to %d for int type parameter

pkg/image/api/helper_test.go
=> add test for resolving images with reference policy

examples/wordpress/README.md
Replaces https://github.com/openshift/origin/pull/5958 which has been inactive
=> minor doc correction

images/base/Dockerfile, images/base/Dockerfile.centos7, images/base/Dockerfile.rhel7, images/node/Dockerfile, images/node/Dockerfile.centos7
Reverts openshift/origin#12427
Broke the merge queue because tests never ran.
=> Revert "install ceph-common pkg on origin to support rbd provisioning"

pkg/cmd/server/api/install/install.go
this installs the types for the IngressAdmissionController, I mistakenly
didn't include this on the original PR
=> install the types for the ingress admission controller

pkg/authorization/admission/restrictusers/restrictusers.go
=> Fix wrong type for printf

pkg/generate/app/imagestreamlookup.go, test/cmd/newapp.sh
fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1419849
=> return partial matches when default latest tag is unavailable

test/extended/router/scoped.go, test/extended/router/weighted.go
Will help debug failing tests like #12784
[merge]
=> Dump router pod logs on e2e failures

test/cmd/newapp.sh
fixes https://github.com/openshift/origin/issues/12911
=> don't include the project name in the new-app validation check

images/node/Dockerfile, images/node/Dockerfile.centos7, images/origin/Dockerfile, images/origin/Dockerfile.centos7, images/origin/system-container/config.json.template, images/origin/system-container/manifest.json, images/origin/system-container/system-container-wrapper.sh
=> node: fix typo in the system container image

test/extended/image_ecosystem/mongodb_replica_statefulset.go
The majority of the work was done in https://github.com/sclorg/mongodb-container/pull/227 .  I don't think there's a dependency between the two PRs in terms of which one merges first.
Fixes #12588
=> Take more care in handling statefulset pods in mongodb test

hack/build-rpm-release.sh
=> Perform a mv instead of cp during RPM release

test/extended/router/scoped.go, test/extended/router/weighted.go
=> Change how the router was logging

examples/image-streams/image-streams-rhel7.json, pkg/bootstrap/bindata.go
fixes https://github.com/openshift/origin/issues/12933
=> set php latest to v7

examples/jenkins/pipeline/README.md, examples/jenkins/pipeline/openshift-client-plugin-pipeline.yaml, pkg/bootstrap/bindata.go, test/extended/builds/pipeline.go
@bparees @csrwng @jupierce ptal or fyi
I anticipate the contents of the sample yaml generating some discussion (unless I jinx things by acknowledging that up front :-) )
=> add sample using openshift-client-plugin syntax; add ext test

test/extended/router/scoped.go, test/extended/router/weighted.go
=> Dump router logs for debugging purposes in the scoped and weighted extended tests

images/dind/Dockerfile
fixes https://github.com/openshift/origin/issues/12995
=> do not remove non-existent packages

docs/generated/oc_by_example_content.adoc, docs/man/man1/oc-expose.1, docs/man/man1/openshift-cli-expose.1, pkg/cmd/cli/cmd/expose.go
Related bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1420165
cc @openshift/cli-review @kargakis
=> add oc expose -h explanation on generator

examples/db-templates/mariadb-ephemeral-template.json, examples/db-templates/mariadb-persistent-template.json, examples/db-templates/mongodb-ephemeral-template.json, examples/db-templates/mongodb-persistent-template.json, examples/db-templates/mysql-ephemeral-template.json, examples/db-templates/mysql-persistent-template.json, examples/db-templates/postgresql-ephemeral-template.json, examples/db-templates/postgresql-persistent-template.json, examples/db-templates/redis-ephemeral-template.json, examples/db-templates/redis-persistent-template.json, examples/jenkins/jenkins-ephemeral-template.json, examples/jenkins/jenkins-persistent-template.json, examples/quickstarts/cakephp-mysql-persistent.json, examples/quickstarts/cakephp-mysql.json, examples/quickstarts/dancer-mysql-persistent.json, examples/quickstarts/dancer-mysql.json, examples/quickstarts/django-postgresql-persistent.json, examples/quickstarts/django-postgresql.json, examples/quickstarts/nodejs-mongodb-persistent.json, examples/quickstarts/nodejs-mongodb.json, examples/quickstarts/rails-postgresql-persistent.json, examples/quickstarts/rails-postgresql.json, pkg/bootstrap/bindata.go
fixes https://github.com/openshift/origin/issues/12719
=> add service catalog metadata to templates

vendor/k8s.io/kubernetes/pkg/controller/cronjob/controller.go
@smarterclayton you've asked for it
=> UPSTREAM: 41658: Fix cronjob controller panic on status update failure

vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go, vendor/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util_test.go
=> UPSTREAM: 41196: Fix for Premature iSCSI logout

test/extended/builds/pipeline.go, test/extended/image_ecosystem/jenkins_plugin.go, test/extended/util/jenkins/ref.go
@bparees ptal @openshift/devex @jupierce  fyi
=> jenkins client plugin PR testing

images/base/Dockerfile, images/base/Dockerfile.centos7, images/base/Dockerfile.rhel7, images/node/Dockerfile, images/node/Dockerfile.centos7
=> install ceph-common pkg on origin to support rbd provisioning

images/release/golang-1.8/Dockerfile
=> Update to golang 1.8 ga

test/common/build/controllers.go
fixes https://github.com/openshift/origin/issues/12017
fixes https://github.com/openshift/origin/issues/12899
=> bump watch timeout for tests to allow for reconciliation recovery

pkg/build/registry/build/strategy.go
fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1425320
=> prevent build updates from reverting the build phase

test/extended/security/supplemental_groups.go
- remove outdated comment (follow-up to 4cb9382801c3350dd7f901092e544e29ef51463b commit)
- replace self-written function by gomega matcher
PTAL @pweil-
=> Improve supplemental groups test

pkg/image/api/helper.go, pkg/image/api/helper_test.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1422376
@miminar quick review pls.
=> Bug 1422376: Fix resolving ImageStreamImage latest tag

pkg/util/leaderlease/leaderlease.go
Auto-sync etcd endpoints while trying to acquire the leader lease. If
any of the etcd cluster members is down, the sync operation will update
the client's member list to remove the unavailable members.
Because the lease acquistion key "set" operation is a one-shot attempt,
if the first member the etcd client tries to contact is unavailable, it
will not try any other members and it just fails. With the sync, we
should be able to work around this.
Fixes bug 1426183
https://bugzilla.redhat.com/show_bug.cgi?id=1426183
cc @smarterclayton @deads2k @sttts @liggitt @mfojtik @derekwaynecarr
=> Sync etcd endpoints before lease acquistion

test/testdata/failing-dc-mid.yaml
Fixes: https://github.com/openshift/origin/issues/13098
=> tests: increate timeout for pods to be ready for dc test

contrib/migration/fix-3.4-paths.sh
=> Migration script (release-1.4 cherry-pick)

vendor/k8s.io/kubernetes/pkg/storage/etcd/etcd_helper.go, vendor/k8s.io/kubernetes/pkg/util/trace.go
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1425211
https://github.com/kubernetes/kubernetes/pull/42178
=> UPSTREAM: 42178: stop spamming logs on restart of server

contrib/migration/fix-3.4-paths.sh
=> Migration script (release-1.5 cherry-pick)

vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set.go, vendor/k8s.io/kubernetes/pkg/controller/replicaset/replica_set_utils.go, vendor/k8s.io/kubernetes/pkg/controller/replication/replication_controller.go, vendor/k8s.io/kubernetes/pkg/controller/replication/replication_controller_utils.go
=> UPSTREAM: 42097: Enqueue controllers after minreadyseconds when all pods are ready

vendor/k8s.io/kubernetes/pkg/registry/authorization/subjectaccessreview/rest_test.go, vendor/k8s.io/kubernetes/pkg/registry/authorization/util/helpers.go, vendor/k8s.io/kubernetes/pkg/registry/authorization/util/helpers_test.go
Ref https://github.com/openshift/origin/issues/13025
=> UPSTREAM: 40935: Plumb subresource through subjectaccessreview

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go, vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/device_allocator.go, vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/device_allocator_test.go
=> [1.5] Fix upstream AWS issues

vendor/k8s.io/kubernetes/pkg/controller/disruption/disruption.go, vendor/k8s.io/kubernetes/pkg/controller/disruption/disruption_test.go
Ref: https://github.com/openshift/origin/issues/13025
@kargakis approval pls.
=> UPSTREAM: 39825: Make PDBs represent percentage in StatefulSet

vendor/k8s.io/kubernetes/pkg/credentialprovider/aws/aws_credentials.go
=> UPSTREAM: 38746: recognize eu-west-2 region

vendor/k8s.io/kubernetes/pkg/kubelet/kubelet_getters.go
ref https://github.com/openshift/origin/issues/13025
=> UPSTREAM: 38909: Add path exist check in getPodVolumePathListFromDisk

vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go, vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/device_allocator.go, vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/aws/device_allocator_test.go
Ref: https://github.com/openshift/origin/issues/13025
@jsafrane PTAL
=> Fix upstream AWS issues

pkg/cmd/server/kubernetes/master_config_test.go, vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/options/options.go
Ref: https://github.com/openshift/origin/issues/13025
=> UPSTREAM: 41366: Change default reconciler sync period to 1 minute

pkg/cmd/server/kubernetes/master_config.go, vendor/k8s.io/kubernetes/pkg/genericapiserver/config.go, vendor/k8s.io/kubernetes/pkg/genericapiserver/serve.go, vendor/k8s.io/kubernetes/pkg/genericapiserver/validation/universal_validation.go, vendor/k8s.io/kubernetes/pkg/util/cert/io.go
=> UPSTREAM: 40301: present request header cert CA

pkg/cmd/server/kubernetes/master.go
fix bz https://bugzilla.redhat.com/show_bug.cgi?id=1427227
@gnufied @jsafrane @childsb
=> provider recorder to attach detach controller

vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/security_context.go, vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/security_context_test.go, vendor/k8s.io/kubernetes/pkg/kubelet/dockertools/docker_manager.go, vendor/k8s.io/kubernetes/pkg/kubelet/dockertools/docker_manager_test.go, vendor/k8s.io/kubernetes/pkg/securitycontext/provider.go, vendor/k8s.io/kubernetes/pkg/securitycontext/provider_test.go, vendor/k8s.io/kubernetes/pkg/securitycontext/types.go, vendor/k8s.io/kubernetes/pkg/securitycontext/util.go
=> UPSTREAM: 40903: Set docker opt separator correctly for SELinux options

vendor/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go, vendor/k8s.io/kubernetes/test/e2e/service.go
=> UPSTREAM: 37093: Endpoints with TolerateUnready annotation, should list Pods in state terminating

examples/logging/logging-deployer.yaml, pkg/bootstrap/bindata.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1426534
=> Change logging deployer image name from 'logging-deployment' to 'logging deployer'

pkg/sdn/plugin/subnets.go, test/extended/networking/ovs.go
The OVS tests occasionally flake, which I assume is because there's no synchronization between the changes we make (creating/deleting nodes/pods/services) and our checking the flows, so in some cases we might check the flows before the node has actually changed them. So if we don't get the expected answers the first time, then retry.
Closes #12855 
(Tests are failing for entirely random reasons on my machine right now so this isn't tested yet, and I'm going to run it a few times before requesting review just to give it a chance to flake if it was going to.)
=> Retry OVS flow checks in extended networking a few times if they fail

hack/lib/start.sh
[test]
@csrwng  -- did we just not hit this code path ever?
/cc @sub-mod
=> Use correct function to start the node process

pkg/cmd/server/kubernetes/master_config.go, vendor/k8s.io/kubernetes/pkg/genericapiserver/config.go, vendor/k8s.io/kubernetes/pkg/genericapiserver/serve.go, vendor/k8s.io/kubernetes/pkg/genericapiserver/validation/universal_validation.go, vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/security_context.go, vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/security_context_test.go, vendor/k8s.io/kubernetes/pkg/kubelet/dockertools/docker_manager.go, vendor/k8s.io/kubernetes/pkg/kubelet/dockertools/docker_manager_test.go, vendor/k8s.io/kubernetes/pkg/securitycontext/provider.go, vendor/k8s.io/kubernetes/pkg/securitycontext/provider_test.go, vendor/k8s.io/kubernetes/pkg/securitycontext/types.go, vendor/k8s.io/kubernetes/pkg/securitycontext/util.go, vendor/k8s.io/kubernetes/pkg/util/cert/io.go
This cherry-picks https://github.com/openshift/origin/pull/13141 (@deads2k) and https://github.com/openshift/origin/pull/13145 (@pmorie) into master. 
@ncdc fyi, this will simplify the next rebase, since this reverts two drop/carry commits.
=> Various cherry-picks from 1.5 for master

vendor/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go
@mfojtik one another we need for 1.5
@kargakis ptal
=> UPSTREAM: 42294: fix rsListerSynced and podListerSynced for DeploymentController

pkg/quota/api/validation/validation_test.go
I added these to debug https://bugzilla.redhat.com/show_bug.cgi?id=1427803 .  Seems like a waste to remove them.
@soltysh @mfojtik
=> tests added for quota scopes while debugging

Godeps/Godeps.json, test/extended/setup.sh, vendor/github.com/openshift/source-to-image/pkg/docker/docker.go
fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1427691
=> bump(github.com/openshift/source-to-image): ebe28eafd63b691ccd917dcad1af1c0e5ba15abd

pkg/cmd/server/bootstrappolicy/infra_sa_policy.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1428123
=> Add stateful sets permissions to disruption controller

pkg/cmd/server/bootstrappolicy/infra_sa_policy.go, test/testdata/bootstrappolicy/bootstrap_cluster_roles.yaml
Ref: https://github.com/openshift/origin/pull/13187
=> [1.5] Add stateful sets permissions to disruption controller

Godeps/Godeps.json, vendor/github.com/coreos/etcd/integration/bridge.go, vendor/github.com/coreos/etcd/integration/cluster.go, vendor/github.com/coreos/etcd/integration/cluster_direct.go, vendor/github.com/coreos/etcd/integration/cluster_proxy.go, vendor/github.com/coreos/etcd/proxy/grpcproxy/cache/store.go, vendor/github.com/coreos/etcd/proxy/grpcproxy/kv.go, vendor/github.com/coreos/etcd/proxy/grpcproxy/metrics.go, vendor/github.com/coreos/etcd/proxy/grpcproxy/watch.go, vendor/github.com/coreos/etcd/proxy/grpcproxy/watch_broadcast.go, vendor/github.com/coreos/etcd/proxy/grpcproxy/watch_broadcasts.go, vendor/github.com/coreos/etcd/proxy/grpcproxy/watch_client_adapter.go, vendor/github.com/coreos/etcd/proxy/grpcproxy/watch_ranges.go, vendor/github.com/coreos/etcd/proxy/grpcproxy/watcher.go
Fixes #13215. This is a followup to #12600. 
@smarterclayton mind taking a look, you've bumped etcd but missed these 3 dirs, was that intentionally or this needs to go in?
@legionus @dmage fyi
@ncdc fyi, for the next rebase
=> bump(github.com/coreos/etcd):v3.1.0

Makefile, hack/update-generated-defaulters.sh
This is very convenient for updating api
[merge]
=> Fix defaulter gen on Mac and add make update-api

test/extended/image_ecosystem/s2i_perl.go, test/extended/image_ecosystem/s2i_python.go, test/extended/image_ecosystem/s2i_ruby.go
Updating the image_ecosystem extended tests to not scale using the
replication controllers.
Fixes #13230
=> Updating image_ecosystem extended tests

tools/etcdhelper/etcdhelper.go
@ncdc ptal, we've talked about this some time ago.
=> Helper for accessing etcd

pkg/cmd/server/origin/master_config.go, vendor/k8s.io/kubernetes/pkg/apiserver/authenticator/authn.go, vendor/k8s.io/kubernetes/pkg/auth/group/authenticated_group_adder.go, vendor/k8s.io/kubernetes/pkg/auth/group/group_adder_test.go, vendor/k8s.io/kubernetes/plugin/pkg/auth/authenticator/request/headerrequest/requestheader.go, vendor/k8s.io/kubernetes/plugin/pkg/auth/authenticator/request/x509/x509.go, vendor/k8s.io/kubernetes/plugin/pkg/auth/authenticator/request/x509/x509_test.go
The larger change didn't make 1.6, but the smaller change did.  Revert the big one, use the little one.
@enj ptal
=> UPSTREAM: 42491: make the system:authenticated group adder smarter
